### DISCUSSION TITLE
Clarification on requirements for k8sattributes container.id

### DISCUSSION THREAD

**Discussion by btkostner** [open-telemetry/opentelemetry-collector-contrib#10122] [Q&A]
I'm wondering what is needed to get container metadata from the k8sattributes processor. I currently have configuration set like so:

```yaml
    k8sattributes:
      auth_type: serviceAccount
      extract:
        labels:
          - key: app
        metadata:
          - container.id
          - container.image.name
          - container.image.tag
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.start_time
          - k8s.pod.uid
      passthrough: false
      pod_association:
        - from: resource_attribute
          name: k8s.pod.uid
        - from: resource_attribute
          name: k8s.pod.ip
        - from: resource_attribute
          name: ip
        - from: connection
        - from: resource_attribute
          name: host.name
```

and I am receiving everything in the k8s section in datadog:

```
k8s {  
  cluster {
    name:  <cluster name>
  }
  deployment {
    name: kong
  }
  namespace {
    name: default
  }
  node {
    name: <gke node name>
  }
  pod {
    ip: 192.168.1.1
    name: kong-1234
    start_time: 2022-05-17 18:18:56 +0000 UTC
    uid: 72706e96-a4ab-4b28-b394-d8236ab6e1e4
  }
}
```

however the container section is never filled out. All of the deployments have sidecars, so I'm not sure if that's the reason or if I need to specify additional annotations or labels in deployments to make this work. Any help would be appreciated
