### DISCUSSION TITLE
Is there any grafana dashboards for hostmetrics

### DISCUSSION THREAD

**Discussion by StuCurry** [open-telemetry/opentelemetry-collector-contrib#10191] [General]
We plan to use hotmetrics reciver to collect host monitoring data, is there any corresponding grafana dashboards? I could not find any on grafana.net.

config.yaml:
```
service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: []
      exporters: [prometheus] 
```
