### DISCUSSION TITLE
How can I append (resource) attributes of spans in new attributes?

### DISCUSSION THREAD

**Discussion by heiko-holz** [open-telemetry/opentelemetry-collector-contrib#10468] [Q&A]
I'd like to append (resource) attributes of spans in a new attribute.
E.g., we have the attributes
```
service: service-a
namespace: my-namespace
```

and now I want to append the attributes `service` and `namespace` in a new attribute `instance`, .i.e.,
`instance: service-a.my-namespace`.

Is there a direct way to append attributes?

I am currently using a workaround with the `span` and `transform` processor in the following way:

1. First, I store the span's original name in the attribute `span.name.original` using a `transform` processor (alternatively, I use the `span` processor) :

```yaml
  transform/1:
    traces:
      queries:
        # store the span's original name as an attribute
        - set(attributes["span.name.original"], name)
```

2. I then use the `span` processor to append the attributes in the span's name

````yaml
  span/name-proxy:
    name:
      from_attributes: [service, namespace] 
      separator: '.'
````  

3. and finally I restore the span's original name and set the instance attribute using the `transform` processor:

```yaml
    transform/2:
      traces:
        queries:
          - set(attributes["instance"], name)
          - set(name, attributes["span.name.original"])
```

How can I achieve the desired behavior more easily?

**Comment by t03apt** [comment]
```yaml
  transform/attributes:
    metric_statements:
      - context: datapoint
        statements:
        - set(attributes["k8s_pod_name"], resource.attributes["service.instance.id"])
```
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusexporter/README.md
