### DISCUSSION TITLE
how to filter a message with filter processor based on log body ( not by attributes or resources)

### DISCUSSION THREAD

**Discussion by kumachop2** [open-telemetry/opentelemetry-collector-contrib#12346] [Q&A]
Ex: 172.20.12.7 - - [01/Jul/2022:20:12:54 +0000] "HEAD / HTTP/1.1" 200 0 "-" "**Edge Health Probe**" "-"    - Looking for way to exclude this message

**Comment by jtama** [comment]
Using operator filter ? 

```yaml
- type: filter
  expr: 'body.message not(matches "Edge Health Probe")'
  output: my_output
```
