### DISCUSSION TITLE
Can Multiple Filter Processors Be Used For POD Level Metrics

### DISCUSSION THREAD

**Discussion by mskhan-devops** [open-telemetry/opentelemetry-collector-contrib#12764] [Q&A]
Hi,
Can multiple Filter Processors be used for POD level metrics? What I want to do is to include `metrics pod_network_rx_bytes` for the POD `mysql-db` and `metrics pod_memory_utilization_over_pod_limit` for POD microService.

I am using the following config:

```
processors:
      filter/db-pod-net-metrics:
        # any names NOT matching filters are excluded from remainder of pipeline
        metrics:
          include:
            match_type: regexp
            metric_names:
              # re2 regexp patterns
              - ^pod_network_rx_bytes
            resource_attributes:
              - Key: PodName
                Value: mysql-db

      filter/ms-pod-mem-metrics:
        # any names NOT matching filters are excluded from remainder of pipeline
        metrics:
          include:
            match_type: regexp
            metric_names:
              # re2 regexp patterns
              - ^pod_memory_utilization_over_pod_limit
            resource_attributes:
              - Key: PodName
                Value: microService

```

This configuration does not work. When I remove one of the above filters, it starts scraping metrics nicely.

I am using [AWS Distro for OpenTelemetry](https://aws.amazon.com/blogs/containers/cost-savings-by-customizing-metrics-sent-by-container-insights-in-amazon-eks/) (ADOT) for sending metrics to CloudWatch from my EKS cluster.

If anyone could assist me with this, that would be great. Are there any other workarounds if this is not supported.
