### DISCUSSION TITLE
filter/exclude prometheus metric based on particular label combination in open-telemetry

### DISCUSSION THREAD

**Discussion by ruchir15** [open-telemetry/opentelemetry-collector-contrib#13164] [Q&A]
I have a use case, where I wanted to exclude (filter) metric with particular label combination, I am using otel-collector for collection, processing and exporting metrics

however when I try to write a config, it remove that metric completely with other label combination set as well.

.i.e.

so according to otel Config the receivers is configured as

```
receivers:
   prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 30s
          static_configs:
            - targets: ["localhost:9001"]
```
which gets metric in question as

```
# TYPE node_supervisord_up gauge
node_supervisord_up{group="serviceA",name="serviceA"} 1
node_supervisord_up{group="serviceB",name="serviceB"} 1
node_supervisord_up{group="serviceC",name="serviceC"} 1
node_supervisord_up{group="ServiceD",name="serviceD"} 0
node_supervisord_up{group="ServiceE",name="serviceE"} 1
```

Now my intention is to remove `node_supervisord_up{group="ServiceD",name="serviceD"} 0` 
before sending to central Metric aggregator

so I tried, below config of otel-collector processor 

```
processors:
  exclude:
        match_type: expr
        expressions:
        - MetricName == "node_supervisord_up" && Label("name") == "serviceD"
```
Refered from here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/filterprocessor/README.md

however this results in complete removal of metric name `node_supervisord_up` for other set of services label combination.

what configuration could help here to just exculde node_supervisord_up{group="ServiceD",name="serviceD"} 0 before sending to central aggregator from the client.

**Comment by cyrille-leclerc** [comment]
I face the same problem with the following config, the metrics with `span_kind=="SPAN_KIND_CLIENT"` are not dropped.

```yaml
processors:
  filter:
    error_mode: ignore
    metrics:
      exclude:
        match_type: expr
        expressions:
        - MetricName == "calls"  && Label("span_kind") == "SPAN_KIND_CLIENT"

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      processors: [filter]
      exporters: [prometheus]

```
