### DISCUSSION TITLE
vcenterreceiver : Get the total OS uptime in the 5m interval

### DISCUSSION THREAD

**Discussion by manjunath-batakurki** [open-telemetry/opentelemetry-collector-contrib#13817] [Q&A]
Hi Team,

I'm looking for the ways to get the total OS uptime in the given interval(5 minutes in my case). In my case, the scraping happens every 5 minz and based on the vCenter metric, i'm able to get the OS Uptime that is returned by the vCenter and return to user.

The challenge is that, the VM could be down/up multiple times between the scrapping interval, for example, In a 5min scrapping interval duration, if the VM was down at the second minute, and was again up at the 4th minute, the value returned would be just 60 seconds uptime(actually it was up for 120 seconds), is there a way to get the total uptime ?

below is the metric given by vCenter as part of Performance Counter.
`
metrics:
```
 vcenter.vm.sys.osUptime.latest:
   enabled: true
   description: Total time elapsed, in seconds, since last operating system boot-up
   unit: second
   sum:
     monotonic: false
     value_type: int
     aggregation: cumulative
   attributes: [vm_name]
```

is it possible to get the total uptime in the scrapping interval ?

# cat /etc/otel-collector-config.yaml
```
receivers:
  vcenter:
    endpoint: "https://<ip>/"
    username: '<username>
    password: '<Passwword>'
    collection_interval: 5m
    tls:
      insecure: true
      insecure_skip_verify: true
 
exporters:
  logging:
    loglevel: debug
  prometheusremotewrite:
    endpoint: "https://endpoint"
    headers:
      Authorization: "Bearer <token>"
 
service:
  pipelines:
    metrics:
      receivers: [vcenter]
      exporters: [logging, prometheusremotewrite]
```
