### DISCUSSION TITLE
Jaeger Remote Sampling extension

### DISCUSSION THREAD

**Discussion by hriddhighosh4** [open-telemetry/opentelemetry-collector-contrib#15808] [Q&A] [answered]
Hello everyone,
I am trying to use jaeger remote sampling in my OpenTelemetryCollector CR.
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: oteld
  namespace: opentelemetry-operator-system
spec:
  mode: daemonset
  hostNetwork: true
  config: |
    extensions:
      jaegerremotesampling:
        source:
          remote:
            endpoint: simple-streaming-jaeger-setup-collector.observability.svc.cluster.local:14250
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      logging:
      otlp:
        endpoint: simple-streaming-jaeger-setup-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
      kafka:
        protocol_version: 2.0.0
        topic: jaeger-spans-v4
        brokers: qa-kafka-kong01.mykaarma.com:9092,qa-kafka-kong02.mykaarma.com:9092
    service:
      extensions:
      - jaegerremotesampling
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging,otlp]
```
    But I am getting error `Error: failed to get config: cannot unmarshal the configuration: unknown extensions type "jaegerremotesampling" for "jaegerremotesampling" (valid values: [zpages memory_ballast health_check pprof])
2022/11/01 10:30:25 collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown extensions type "jaegerremotesampling" for "jaegerremotesampling" (valid values: [zpages memory_ballast health_check pprof])`
 
I am using v0.61.0, operator image ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:0.61.0
