### DISCUSSION TITLE
Not able to set datadog exporter for logs in opentelemetry-collector config yaml file

### DISCUSSION THREAD

**Discussion by ff-sdesai** [open-telemetry/opentelemetry-collector-contrib#16579] [Q&A]
Hi,

I have a Spring-boot based micro-service which uses auto-instrumentation provided by spring-cloud-sleuth. I have an open telemetry-collector running in the same docker container and I have configured it to export traces to datadog. I can also see the traces getting exported at app.datadoghq.com.
Now, I am also using open-telemetry-appender for logback and I have managed to log the same trace Id and span Id with the logs (I can see it in the console). However, when I am trying to configure the datadog exporter for logs , I get following error:-

```
spring-cloud-sleuth-otel-slf4j-otel-collector-1                  | 2022-12-02T09:59:00.875Z	info	components/components.go:30	Stability level of component is undefined	{"kind": "exporter", "data_type": "logs", "name": "datadog", "stability": "undefined"}
spring-cloud-sleuth-otel-slf4j-otel-collector-1                  | Error: cannot build pipelines: failed to create "datadog" exporter, in pipeline "logs": telemetry type is not supported
spring-cloud-sleuth-otel-slf4j-otel-collector-1                  | 2022/12/02 09:59:00 collector server run finished with error: cannot build pipelines: failed to create "datadog" exporter, in pipeline "logs": telemetry type is not supported
```
I want to be able to see the logs in datadog associated with same trace Id. Can somebody please suggest what I might be doing wrong? I am using otel/opentelemetry-collector-contrib:0.60.0 docker image. Here's my otel-collector-config.yaml file:- 

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  datadog:
    api:
      site: datadoghq.com
      key: ${DD_API_KEY}
  file:
    path: /tmp/signals.json
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, logging, file]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, logging, file]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog,logging, file]
```
