### DISCUSSION TITLE
Opentelemetry collector gives "partialSuccess": {} response

### DISCUSSION THREAD

**Discussion by BulyKristof** [open-telemetry/opentelemetry-collector-contrib#17833] [Q&A]
I have an opentelemetry collector contrib (0.69.0) installed inside OpenShift container and I want to export my traces to Datadog. I have an http endpoint URL exposed for my Collector service and I can ping it, however when I want to send in some sample trace from Postman to test the connection, I get the following response:

response (200 OK):
```
{
    "partialSuccess": {}
}
```

I read the docs, and partial Success should come with a message to help out the user in troubleshooting, but in my case I have no clue what's wrong :/

collector-config.yml
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: collector-config
  namespace: opentelemetry-collector
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            cors:
              allowed_origins: "*"
          grpc:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          paging:
            metrics:
              system.paging.utilization:
                enabled: true
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
          disk:
          filesystem:
            metrics:
              system.filesystem.utilization:
                enabled: true
          load:
          memory:
          network:
          processes:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otelcol'
            scrape_interval: 10s
            static_configs:
            - targets: ['0.0.0.0:8888']

    processors:
      batch:
        send_batch_max_size: 1000
        send_batch_size: 100
        timeout: 10s

    exporters:
      logging:
        loglevel: debug
      datadog:
        api:
          site: datadoghq.com
          key: ************
          fail_on_invalid_key: true

    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        metrics:
          receivers: [hostmetrics, otlp]
          processors: [batch]
          exporters: [datadog]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [datadog]
```
