### DISCUSSION TITLE
filelog receiver for nomad job

### DISCUSSION THREAD

**Discussion by medival** [open-telemetry/opentelemetry-collector-contrib#17847] [Q&A] [answered]
Hi,
Where I can find a sample filelog receiver to get nomad job logs?

Thanks in advance

**Comment by medival** [comment]
I tried using filelog receiver to get `nomad/alloc/$alloc-id/alloc/logs`
$alloc-id consist several character with - (hypen) separator, example `e1c2036e-76d2-037a-c5dc-accaacdaeae6/`

Configuration
```
receivers:
  filelog:
    include:
      - "/tmp/nomad/data/alloc/*/alloc/logs/*.stderr.0"

processors:
  attributes:
    actions:
    - action: insert
      key: log_file_name
      from_attribute: log.file.name
    - action: insert
      key: loki.attribute.labels
      value: log_file_name

exporters:
  logging:
     logLevel: debug

  loki:
     endpoint: https://loki.url.com/loki/api/v1/push

service:
  pipelines:
    logs:
      receivers: [otlp, filelog]
      processors: [attributes]
      exporters: [logging, loki]
```

unfortunately, the filelog resulted 

`fileconsumer/file.go:62	no files match the configured include patterns	{"kind": "receiver", "name": "filelog", "pipeline": "logs", "component": "fileconsumer", "include": ["/tmp/nomad/data/alloc/*/alloc/logs/*.stderr.0"], "exclude": []}`
