### DISCUSSION TITLE
Attribute Processor Regexp Pattern Errors

### DISCUSSION THREAD

**Discussion by arielvalentin** [open-telemetry/opentelemetry-collector-contrib#18311] [Q&A]
I am experimenting with using an attribute processor to perform in-place replacements of the `http.url` and `http.target` attributes. I started with trying out some of the examples provided in contrib repo, however it seems that the examples have an invalid pattern with an unnamed matcher group:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4061bf6d6d3198c395668a0a08373e9084d0477a/processor/attributesprocessor/testdata/config.yaml#L39

```console
Error: cannot build pipelines: failed to create "attributes" processor, in pipeline "traces": error creating AttrProc. Field "pattern" contains at least one unnamed matcher group at the 0-th actions
2023/02/06 17:40:40 collector server run finished with error: cannot build pipelines: failed to create "attributes" processor, in pipeline "traces": error creating AttrProc. Field "pattern" contains at least one unnamed matcher group at the 0-th actions
````

```yaml
service:
  # For now we only ingest traces. For metrics we use datadog and for logs fluent-bit.
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - attributes
        - batch
      exporters:
        - logging

# The pipeline details
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  attributes:
    actions:
    - key: "http.url"
      pattern: ^(?P<http_protocol>.*):\/\/(?P<http_domain>.*)\/(?P<http_path>.*)(\?|\&)(?P<http_query_params>.*)
      action: extract

  batch: {}

exporters:
  logging:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1
```

Is this an invalid example? Is there a better one I may use instead?
