### DISCUSSION TITLE
Update existing attributes in-place

### DISCUSSION THREAD

**Discussion by arielvalentin** [open-telemetry/opentelemetry-collector-contrib#18383] [Q&A]
I would like to redact the query string `http.target` and `http.url` attributes and the only success I have had so far has been to configure `extract`, `update`, and `delete` actions for each attribute like so:

```yaml
  attributes:
    actions:
      # removes query strings from http.* attributes
    - key: http.url
      pattern: ^(?P<temp_http_url>.*)\?.*$
      action: extract
    - key: http.url
      from_attribute: temp_http_url
      action: update
    - key: temp_http_url
      action: delete
    - key: http.target
      pattern: ^(?P<temp_http_target>.*)\?.*$
      action: extract
    - key: http.target
      from_attribute: temp_http_target
      action: update
    - key: temp_http_target
      action: delete
```

I there a more concise or efficient way to accomplish this?

**Comment by arielvalentin** [comment]
After a few attempts and incantations I found that I am able to use a subset of a regular expression match using `replace_pattern`. 

```yaml

  transform:
    trace_statements:
      - context: span
        statements:
          - replace_pattern(attributes["http.target"], "\\?.*$", "?[REDACTED]")
          - replace_pattern(attributes["http.url"], "\\?.*$", "?[REDACTED]")

```

The part that confuses me here is why I had to add additional escaping to the regular expression match.
