### DISCUSSION TITLE
Rename the value of span service.name from "old_name" to "new_name"

### DISCUSSION THREAD

**Discussion by jvijayan6** [open-telemetry/opentelemetry-collector-contrib#18879] [Q&A] [answered]
Hi Team,

I need some help on renaming the gloo traces coming from zipkin to otel collector. My requirement is to change the value of a span "service.name" from "gateway" to "edge_proxy", The traces are from gloo-edge using zipkin. tried updating with span processor configuration. but its not worked.

need some input on this. Please note that I need to change/rename the value not the key.

**Comment by jvijayan6** [comment]
@dmitryax @jvoravong @emaderer

**Comment by dmitryax** [comment, marked as answer]
@jvijayan6 

Try [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) with the following config:

```
transform:
  error_mode: ignore
  trace_statements:
    - context: resource
      statements:
        - replace_match(attributes["service.name"], "gateway", "edge_proxy")
```

**Reply by jvijayan6** [reply]
@dmitryax updated the configuration as below (from values.yaml).
 ```
# OpenTelemetry Collector configuration for standalone otel-collector deployment can be overriden in this field.
 # Default configuration defined in config/otel-collector-config.yaml
  # Any additional fields will be merged into the defaults,
  # existing fields can be disabled by setting them to `null`.
  config: 
    processors:
      transform:
        # error_mode: ignore
        trace_statements:
          context: resource
          statements:
            - replace_match(attributes["Service"], "gateway", "edge_proxy")
    service:
      pipelines:
        traces:
          processors:
          - memory_limiter
          - batch
          - k8sattributes
          - resource/add_cluster_name
          - resource/add_environment
          - transform
          exporters:
          - sapm
          - signalfx
          receivers:
          - otlp
          - jaeger
          - zipkin
        `
```
