### DISCUSSION TITLE
Datadog processor & exporter export different operation name

### DISCUSSION THREAD

**Discussion by GuillaumeDecMeetsMore** [open-telemetry/opentelemetry-collector-contrib#19745] [Q&A]
Hello,

First, thank you for all the work on Otel and Otel-contrib :)

We are having a small issue when integrating the Otel Collector with Datadog. We are trying to use tail-sampling in order to sample all the errors but still use probabilistic sampling for the rest.

We managed to setup everything but it seems we are having a mistmatch between the (correct) operation name parsed by `datadog processor` and the operation name sent by `datadog exporter` (for traces).

___

We have this service. The metrics shown are coming from Otel Collector with `datadog processor`. Here we have `realtime.server` as the operation name on the top, which I guess is `${appName}.${span.kind}` in the NodeJS lib.

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/113656593/225491518-36710741-791a-466f-86b3-9463d0082695.png">

That's all good, except that if you look at the details of the resources: we have no traces/spans.
And, if we go to "all traces view" of this service, we see nothing.

But, if we then remove the filter on `operationName`, then we can see the traces coming in (all errors and a few successes as expected). Looking at those, they seem to have another operation name `opentelemetry.server` (I suppose this is what is given on the bottom left).

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/113656593/225492122-1823a536-9260-4515-9972-51f8a90db5f1.png">

> Before, we were sending from the otel library to the DD agent via gRPC. This was working fine and both metrics and traces had `realtime.server` as the operation name (but, that doesn't allow to do tail sampling at the collector level).

The configuration of the Otel Collector is the following:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  datadog:
    metrics_exporter: datadog
  batch:
    send_batch_max_size: 100
    send_batch_size: 20
    timeout: 10s
  tail_sampling:
    decision_wait: 15s
    num_traces: 50000
    policies:
      [
        {
          name: randomized-policy,
          type: probabilistic,
          probabilistic: { sampling_percentage: 10 },
        },
        {
          name: latency-policy,
          type: latency,
          latency: { threshold_ms: 5000 },
        },
        {
          name: errors-policy,
          type: status_code,
          status_code: { status_codes: [ERROR] },
        },
      ]

exporters:
  datadog:
    api:
      site: datadoghq.com
      key: ${env:DD_API_KEY}

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [datadog, tail_sampling, batch]
      exporters: [datadog]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
  telemetry:
    logs:
      encoding: "json"
```

Adding this in the exporter **works**:

```yaml
    traces:
      span_name_remappings:
        opentelemetry.server: realtime.server
```

</details>

But I have the feeling it should work without it, so here I am checking if we have missed something 👀 

Thanks!
