### DISCUSSION TITLE
'extensions': unknown type: "docker_observer" for id: "docker_observer"

### DISCUSSION THREAD

**Discussion by eratio08** [open-telemetry/opentelemetry-collector-contrib#20318] [Q&A] [answered]
Hello,

maybe someone with some more xp can spot my mistake.
I'm trying to setup the `docker_observer` in a docker compose setup, but it fails with the following error

```shell
 * error decoding 'extensions': unknown type: "docker_observer" for id: "docker_observer" (valid values: [asapclient bearertokenauth http_forwarder jaegerremotesampling oauth2client k8s_observer awsproxy headers_setter health_check host_observer memory_ballast basicauth oidc pprof sigv4auth zpages file_storage])
 ```

The config of the extension is done with

```yaml
extensions:
  docker_observer:
    api_version: 1.42

receivers:
  receiver_creator:
    ...
service:
  extensions: [ docker_observer ]
  pipelines:
    ...
```

I'm using [otel/opentelemetry-collector-contrib:latest
](https://hub.docker.com/layers/otel/opentelemetry-collector-contrib/latest/images/sha256-12541fc80806999ea3e475c56ef82219ddd964223bcf812aaac2f01c1065b471?context=explore)
According to [the docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/observer/dockerobserver/README.md) it should be done like this.
What am I missing?
