### DISCUSSION TITLE
Authentication for loki exporter

### DISCUSSION THREAD

**Discussion by Chinwendu20** [open-telemetry/opentelemetry-collector-contrib#21165] [Q&A] [answered]
Please how do I add basic authentication details for loki endpoint in the config file.

**Comment by mar4uk** [comment, marked as answer]
you should use [basicauth](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension) extension:

```
extensions:
    basicauth:
      client_auth:
        username: "${LOGS_USER_ID}"
        password: "${API_KEY}" 
exporters:
    loki:
       endpoint: "http://localhost:3100/loki/api/v1/push"
       auth:
          authenticator: basicauth
service:
  extensions: [basicauth]
  pipelines:
     logs: [loki]
```
