### DISCUSSION TITLE
OTLP to Zipkin for Trace exporting

### DISCUSSION THREAD

**Discussion by lxx95** [open-telemetry/opentelemetry-collector-contrib#21492] [Q&A] [answered]
Hi all, 

Trying to export traces from Otel-Demo (with receiver in OTLP format) to Zipkin backend (as suggested [here](https://github.com/apache/skywalking/discussions/10747#discussioncomment-5770493) by @wu-sheng).

Here my otel-collector:
```
receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      zipkin:
        endpoint: "skywalking-oap.skywalking.svc.cluster.local:9411"
        tls:
          insecure: true
      logging:
processors:
      batch:
service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [zipkin, logging]
```
This error message has been shown for exporting phase (from otel-collector):
`2023-05-04T14:56:27.171Z        error   exporterhelper/queued_retry.go:175      Exporting failed. No more retries left. Dropping data.  {"kind": "exporter", "data_type": "traces", "name": "zipkin", "error": "max elapsed time expired failed to push trace data via Zipkin exporter: Post \"skywalking-oap.skywalking.svc.cluster.local:9411\": unsupported protocol scheme \"skywalking-oap.skywalking.svc.cluster.local\"", "dropped_items": 5}`

The zipkin backend (Skywalking OAP) port and endpoint was fine:
`skywalking-oap                             ClusterIP   10.99.240.73     <none>        11800/TCP,12800/TCP,9411/TCP   27m`

Note: I have also tried with "skywalking-oap.skywalking.svc.cluster.local:9411/api/v2/spans", the same message was shown

Thank you,
Luigi
