### DISCUSSION TITLE
Loki exporter: how to remove default labels (job, level, exporter)

### DISCUSSION THREAD

**Discussion by artyom-p** [open-telemetry/opentelemetry-collector-contrib#21508] [Q&A] [answered]
Just upgraded collector to support latest Loki exporter changes, for some reson im getting unwanted labels indexed on my logs. Can i somehow remove those default labels (job, level, exporter) ?

**Comment by mar4uk** [comment]
Hi! No, these labels can't be removed

**Reply by artyom-p** [reply]
Any chance that it will be allowed to remove those in the future?

**Reply by mar4uk** [reply]
we currently don't have plans to do so... But in general, it is possible to implement. Let's say adding a flag to the config like:

```
   loki:
      endpoint: ...
      default_labels:
           job: false
           level: false
           exporter: false
```
Would it help?
Why is it critical to remove those labels?
