### DISCUSSION TITLE
prometheusexporter doesnt export target_info

### DISCUSSION THREAD

**Discussion by IvanZenger** [open-telemetry/opentelemetry-collector-contrib#21666] [Q&A]
With `prometheusexporter` there is no `target_info` exported. 

In the receiving spans (OTLP), export these to the `spanmetrics` Connector and then send them to `prometheusexporter`. 
Note: target_info is exported with `prometheusremotewriteexport`. 

And Second Question: Is there an option to drop label of target_info in prometheusremotewriteexport before they get exported? 

This is my config: 

```yaml
exporters:
  otlp:
    endpoint: localhost:5000
    tls:
      insecure: true
  prometheus:
    endpoint: "localhost:5001"
  logging:
    verbosity: detailed
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5002
      http:
        endpoint: 0.0.0.0:5003
connectors:
  spanmetrics:
service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - spanmetrics
        - otlp
    metrics:
      receivers:
        - spanmetrics
      exporters:
        - prometheus
```

Thanks
