### DISCUSSION TITLE
Having issue using a transform

### DISCUSSION THREAD

**Discussion by rismoney** [open-telemetry/opentelemetry-collector-contrib#22158] [Q&A]
I am trying to modify metrics as follows:
```
receivers:
  windowsperfcounters:
    collection_interval: 5s
    metrics:
      os.processor.information.time:
        description: percentage of the time that the processor takes to execute a non-idle thread during a sample interval. % Processor Time is calculated by subtracting the percentage of time to execute an idle thread from 100%.
        unit: "%"
        gauge:
    perfcounters:
      - object: "Processor Information"
        instances: "*"
        counters:
          - name: "% Processor Time"
            metric: os.processor.information.time
```

This results in output is that it looks like this below [ i snipped to 2 as I have 72 cores].  These are numa groups and cores.  Because the instances are a single field, I am having data splicing problems.  Is it possible to separate this into {numagroup="0", core=1"}
```
os_processor_information_time_percent{instance="0,0"} 11.483630106696385
os_processor_information_time_percent{instance="0,1"} 4.626728213553144
os_processor_information_time_percent{instance="1,0"} 40.157947114386296
os_processor_information_time_percent{instance="1,1"} 48.57323580142572
```
I tried using metrictransform processor and couldn't get it to use new_value.  Not sure if this can be done with ottl and how.

Thank you so much for your help in advance.
