### DISCUSSION TITLE
Sending telemetry to Azure Data Explorer

### DISCUSSION THREAD

**Discussion by tashivani** [open-telemetry/opentelemetry-collector-contrib#23038] [Q&A]
I'm currently facing issues with sending telemetry data from a C++ desktop application to Azure, specifically Azure Data Explorer.

In my project, telemetry is being sent via a gRPC exporter to a collector on the same machine. This collector successfully writes the telemetry data to local files. However, when attempting to send the data to Azure, I find that no data appears in the Azure Data Explorer (ADX) tables that I have set up.

I haven't noticed any error messages from the collector, which makes the issue even harder to troubleshoot. As a reference, I've been following the steps laid out in the Azure documentation for creating an Azure Active Directory application registration in Azure Data Explorer ([link](https://learn.microsoft.com/en-us/azure/data-explorer/provision-azure-ad-app)).

To help identify if there is any configuration issue, I have attached the OpenTelemetry (otel) collector YAML file (otel-collector.yml) here.

I'm at a bit of a loss for how to proceed with debugging this issue. If anyone could provide some guidance, or even better, a working example that I could compare to, it would be greatly appreciated.

Thanks in advance for your help!

otel-collector.yml:
```yml
receivers:
    otlp: # the OTLP receiver the app is sending traces to
      protocols:
        grpc:
  
  exporters:
    azuredataexplorer:
      cluster_uri: "https://<adx-clustor-name>.<region>.kusto.windows.net"
      application_id: "<app_id>"
      application_key: "<app-key>"
      tenant_id: "<tenent-id>"
      db_name: "MyDatabase"
      metrics_table_name: "OTMetrics"
      logs_table_name: "OTLogs"
      traces_table_name: "OTTraces"
      ingestion_type : "managed"
    logging:
      #logLevel: info
    file: # the File Exporter, to ingest logs to local file
      path: "./app_example.json"
      rotation:
  
  processors:
    batch:
  
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [file, azuredataexplorer]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [file, azuredataexplorer]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [file, azuredataexplorer]
```

Screenshot of otelcol-contrib.exe --config=C:\Users\st\otel-collector.yaml
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/10983792/55700eb8-816f-4fcb-87ee-2a76d5a2130c)
