### DISCUSSION TITLE
You can still query metrics data even if the OpenTelemetry client no longer sends that metrics data

### DISCUSSION THREAD

**Discussion by gaochuang** [open-telemetry/opentelemetry-collector-contrib#23261] [Q&A]
Deployment:
opentelemetry client(pod) + opentelmetry collector + prometheus

Function:
Send the CPU usage of multiple processes to the OpenTelemetry Collector through the OpenTelemetry client metrics.

Issue:
When a process stops running, the OpenTelemetry client will not send the CPU usage of that process. However, the OpenTelemetry collector will always query the CPU usage rate of processes, even if they have stopped.

**Comment by gaochuang** [comment]
@atoulme, Hi atoulm  or who can help me about this issue?  Thanks in adcance.

**Reply by atoulme** [reply]
How did you find out the collector is still querying the old processes? Linux or Windows? Got a yaml config file you can share?

**Reply by atoulme** [reply]
Are you exposing metrics data on the prometheus exporter? Are you saying the metrics still show there even after the process has exited?

if so I think that is expected but timestamps should show the metric latest value is old.

**Reply by atoulme** [reply]
Take a look here: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter 
old metrics expire after 5 minutes.

**Reply by gaochuang** [reply]
On the linux env.
This is my OTEL config.

```yaml
 receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
      k8sattributes:
      k8sattributes/2:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
          - sources:
             from: resource_attribute
             name: k8s.pod.uid
          - sources:
            - from: connection
    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 683
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        enable_open_metrics: true
        resource_to_telemetry_conversion:
          enabled: true
      logging:
      jaeger:
        endpoint: jaeger-all-in-one:14250
      otlp:
        endpoint: "http://someotlp.target.com:4317" # Replace with a real endpoint.
    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch, memory_limiter, k8sattributes, k8sattributes/2]
          exporters: [prometheus]
```
