### DISCUSSION TITLE
How to filter events produced by k8sobjects?

### DISCUSSION THREAD

**Discussion by Hronom** [open-telemetry/opentelemetry-collector-contrib#23269] [Q&A]
I wanna filter by `object.type` that I see in logs and leave only warnings.

I tried a lot of things:
```
      filter/events_warning:
        logs:
          include:
            match_type: strict
            resource_attributes:
              - key: object.type
                value: Warning
```
and
```
      filter/events_warning:
        logs:
          include:
            match_type: strict
            record_attributes:
              - key: object.type
                value: Warning
```
and
```
      filter/events_warning:
        logs:
          include:
            severity_number:
              min: "WARN"
              match_undefined: false
```
and
```
      filter/events_warning:
        error_mode: ignore
        logs:
          log_record:
            - 'attributes["object.type"] == "Warning"'
```
and
```
      filter/events_warning:
        error_mode: ignore
        logs:
          include:
            match_type: regexp
            bodies:
              - .*"type":"Warning".*
```
and
```
      filter/events_warning:
        logs:
          include:
            match_type: regexp
            bodies:
              - .*Warning.*
```

Nothing works.

My config is:
```
  config:
    receivers:
      k8sobjects:
        objects:
          - name: events
            mode: "watch"
            group: "events.k8s.io"

    processors:
      batch: {}
      # If set to null, will be overridden with values based on k8s resource limits
      memory_limiter: null
      filter/events_warning:
        logs:
          include:
            match_type: regexp
            bodies:
              - .*Warning.*

    exporters:
      logging:
        verbosity: detailed

    service:
      extensions:
        - health_check
        - memory_ballast
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
        logs:
          level: "warn"
      pipelines:
        metrics: null
        traces: null
        logs: null
        logs/k8sobjects:
          receivers:
            - k8sobjects
          processors:
            - filter/events_warning
            - memory_limiter
            - batch
          exporters:
            - logging
```
