### DISCUSSION TITLE
loadbalancerexporter DNS Verify Cert with provided host?

### DISCUSSION THREAD

**Discussion by Jamian** [open-telemetry/opentelemetry-collector-contrib#23651] [Q&A]
Is it possible to set up `loadbalancerexporter` configured to use `dns` to verify the certificate against the Hostname defined in the config?

Example config:
```
  loadbalancing:
    routing_key: "traceID"
    protocol:
      otlp:
        tls:
          insecure: false
          insecure_skip_verify: true
    resolver:
      dns:
        hostname: amagicalinternalotelcollector.eu-west-1.internal.amazing  # <<-- received cert will match this
        interval: 5s
        timeout: 1s
```

I am using certs signed with a private authority, so I can provide the `ca_file` but am getting the following error due to the IP based requests:
```
failed to verify certificate: x509: cannot validate certificate for <ipaddress> because it doesn't contain any IP SANs
```

Any guidance would be greatly appreciated, thank you!
