### DISCUSSION TITLE
how do specify more than one vCenter in vCenter Reciver config

### DISCUSSION THREAD

**Discussion by manjunath-batakurki** [open-telemetry/opentelemetry-collector-contrib#23974] [Q&A] [answered]
Hi Team,

I'm looking to see if there is an option to specify more than one vCenter details in the config for the vCenter reciver

Currently supported option is as below

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/vcenterreceiver/testdata/config.yaml

Let me know if there is a way currently and whether it is possible to achieve this ?

**Comment by manjunath-batakurki** [comment]
@schmikei Let me know if you have inputs

**Reply by schmikei** [reply, marked as answer]
@manjunath-batakurki 

Would something like this work? All the underlying code could not share a client just due to how govmomi  works so I'm not sure adding multiple endpoints would be worth the overhead. 

```yaml
receivers:
  vcenter/vcenter1:
    endpoint: https://vcsa1.localnet
    username: "otelu"
    password: "otelp"
    tls:
      insecure: false
      insecure_skip_verify: true

  vcenter/vcenter2:
    endpoint: https://vcsa2.localnet
    username: "otelu"
    password: "otelp"
    tls:
      insecure: false
      insecure_skip_verify: true

service:
  pipelines:
    metrics:
      receivers: [vcenter/vcenter1, vcenter/vcenter2]
```
