### DISCUSSION TITLE
Filter attribute otel.library.name

### DISCUSSION THREAD

**Discussion by mauro-velasco-seagull-com** [open-telemetry/opentelemetry-collector-contrib#23988] [Q&A]
Hi,

I'm trying to filter all the traces where the attribute otel.library.name has smallrye inside, but for some reason doesn't work; I wish to know if this is the correct attribute name or if there is another way to get this filtered.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/111927496/a1cbcb87-1f53-4ed7-9b89-e52205a70d3a)

These are some filters I tried without luck:

- 'IsMatch(resource.attributes["otel.library.name"], ".*smallrye.*") == true'
- 'IsMatch(attributes["otel.library.name"], ".*smallrye.*") == true'
- 'resource.attributes["otel.library.name"] == "io.smallrye.reactive.messaging.kafka"'
- 'IsMatch(attributes["otel.scope.name"], ".*smallrye.*") == true'
- 'resource.attributes["otel.scope.name"] == "io.smallrye.reactive.messaging.kafka"

Thank you so much

Kind Regards,
Mauro

**Comment by aquarhead** [comment]
Hey, I was just trying to do the same thing, in the end I think this works for me (different library names):

```
processors:
  filter/opentracing-shim:
    error_mode: ignore
    spans:
      exclude:
        match_type: strict
        libraries:
          - name: opentracing-shim
```

based on the last section in the filterprocessor README.

Another thing is (and I forgot for many hours lol) you'll need to put the processor into the service pipeline! So in my case it's something like this:

```
service:
  pipelines:
    traces:
      processors: [..., filter/opentracing-shim, ...]
```

I had several other iterations of the filter processor config that might have all worked if I actually put it in the list lol.

Hope this helps :)
