### DISCUSSION TITLE
Docker unix socket permissions error

### DISCUSSION THREAD

**Discussion by ClaytonNorthey92** [open-telemetry/opentelemetry-collector-contrib#25892] [Q&A]
Hi all 👋 

I am trying to run the `opentelemetry-collector-contrib` docker image with the docker stats receiver, and I am getting the following error:
```
Error: cannot start pipelines: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.43/containers/json?filters=%7B%22status%22%3A%5B%22running%22%5D%7D": dial unix /var/run/docker.sock: connect: permission denied
2023/08/18 16:03:07 collector server run finished with error: cannot start pipelines: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.43/containers/json?filters=%7B%22status%22%3A%5B%22running%22%5D%7D": dial unix /var/run/docker.sock: connect: permission denied
```

The command I run is:
```
docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /path/to/my/file/my-otel.yaml:/etc/otelcol-contrib/config.yaml -p 5555:5555 otel/opentelemetry-collector-contrib:latest
```

My config file is:
```yaml
receivers:
  docker_stats:
    collection_interval: 1s
    timeout: 20s
    api_version: 1.43

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [docker_stats]
      exporters: [logging]
```

I was wondering if I had something configured incorrectly as far as permissions go, I don't think so though. I can successfully communicate with `/var/run/docker.sock` with the `docker:latest` image:

```
docker run --privileged -v /var/run/docker.sock:/var/run/docker.sock docker:latest docker ps
CONTAINER ID   IMAGE             COMMAND                  CREATED                  STATUS                  PORTS           NAMES
311ea31a2ad0   docker:latest     "dockerd-entrypoint.…"   Less than a second ago   Up Less than a second   2375-2376/tcp   kind_faraday
03e0e34cf490   postgres:latest   "docker-entrypoint.s…"   25 minutes ago           Up 25 minutes           5432/tcp        stoic_lovelace
```

am I configuring something wrong in `opentelemetry-collector-contrib`?   or is this a bug? 🤔 🐛 

thanks!
