### DISCUSSION TITLE
How to modify default port `8888`

### DISCUSSION THREAD

**Discussion by zenvzenv** [open-telemetry/opentelemetry-collector-contrib#27644] [Q&A] [answered]
I known the `8888` port is to send metrics data to prometheus,but I do not known how to modify the default value.I tried to find the answer in [Config](https://opentelemetry.io/docs/collector/configuration/), but couldn't find the relevant information.

Your help is much appreciated. Thank you!

**Comment by zenvzenv** [comment, marked as answer]
```yml
service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
```

Just modify the port of address
