### DISCUSSION TITLE
servicegraph: not generating any metrics and all edges are expiring

### DISCUSSION THREAD

**Discussion by vmihailenco** [open-telemetry/opentelemetry-collector-contrib#27673] [Q&A]
Could anyone share a `servicegraph` connector config that prints some metrics to stdout?

I can't seem to make [servicegraph](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/23a3712cb6e63a8819f384baf69d1c6cf4284bbe/connector/servicegraphconnector) v0.87 to generate any metrics (such as `traces_service_graph_*`) with the following config:

```yaml
connectors:
  servicegraph:
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    store:
      ttl: 5m
      max_items: 1000000

exporters:
  otlp/uptrace:
    endpoint: host.docker.internal:14317
    tls:
      insecure: true
    headers: { 'uptrace-dsn': 'http://project1_secret_token@localhost:14317/1' }
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [otlp/uptrace, servicegraph, debug]
    metrics/servicegraph:
      receivers: [servicegraph]
      processors: []
      exporters: [otlp/uptrace, debug]
```

I see that spans are coming in `traces` pipeline but no logs from `servicegraph`:

```
otelcol_1       | 2023-10-15T07:08:18.956Z	info	servicegraphprocessor@v0.87.0/processor.go:142	Started servicegraphconnector	{"kind": "exporter", "name": "servicegraph", "exporter_in_pipeline": "traces", "receiver_in_pipeline": "metrics"}

....

otelcol_1       | 2023-10-15T06:54:25.702Z	info	TracesExporter	{"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 31}
otelcol_1       | 2023-10-15T06:54:35.703Z	info	TracesExporter	{"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 58}
otelcol_1       | 2023-10-15T06:54:45.703Z	info	TracesExporter	{"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 31}
otelcol_1       | 2023-10-15T06:54:55.704Z	info	TracesExporter	{"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 31}
otelcol_1       | 2023-10-15T06:55:05.704Z	info	TracesExporter	{"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 32}
otelcol_1       | 2023-10-15T06:55:15.705Z	info	TracesExporter	{"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 33}
otelcol_1       | 2023-10-15T06:55:25.705Z	info	TracesExporter	{"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 31}
```

And I have `otelcol_processor_servicegraph_total_edges` and `otelcol_processor_servicegraph_expired_edges` metrics that show me that Collector can't find any matching edges:

![servicegraph](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/290976/0f9f218b-e930-48e3-9e71-3c1008d18e32)
