### DISCUSSION TITLE
[Receiver] [logs] Cloudwatch - New Feature & Future of the receiver

### DISCUSSION THREAD

**Discussion by jorgeancal** [open-telemetry/opentelemetry-collector-contrib#27680] [Ideas]
I see that there is a cloud watch receiver for logs but it's in alpha status. I was wondering if there are any tasks or any plans to be promoted to stable status. 

My current workplace is transitioning from a vendor to an in-house solution.  I would like to add a new feature to this receiver to speed up that transition.  This feature is related to adding the option of including linked accounts while retrieving logs in autodiscovery. We are currently using this receiver with the feature (I have it working in a fork, but it's not really stable I need to add some more testing and a few more things). So this would look as follows:
```
awscloudwatch:
  region: eu-west-1
  logs:
    poll_interval: 30m
    groups:
      autodiscover:
        prefix: aws/eks/
        limit: 100
        includeLinkedAccounts: true
```

thanks
