### DISCUSSION TITLE
need to remove labels from metrics

### DISCUSSION THREAD

**Discussion by kadhamecha-conga** [open-telemetry/opentelemetry-collector-contrib#27794] [Q&A]
hi team,

can someone help me , how can I remove labels from metrics ?
can someone share example to do this ?

i want to remove service_instance_id , instance  and few labels of k8s pods.

thanks.

**Comment by arminru** [comment]
Hi @kadhamecha-conga!

There are two processors that can be used for this purpose:

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor
--> take a look at the `delete_label_value` operation

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor
--> take a look at the language defined in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl and its [`delete` operation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl#remove-a-forbidden-attribute)

Note that the `transformprocessor` is more frequently updated and generally more versatile and powerful and might be the better choice in the long term.

**Comment by kadhamecha-conga** [comment]
hi,

i trying to remove service_version with below spec:

```
metricstransform/service_version:
  transforms:
  - include: ^otelcol_
    match_type: regexp
    action: update
    operations:
    - action: delete_label_value
      label: service_version
      label_value: "1.0.0"
```

but it is not removing it.

how can we disable k8s attributes which are  added by default into trace, logs and metrics ?
I want to remove k8s_pod_ip from all  and that even not part of metadata of k8s processor, but still it is added.
I also want to remove below attributes , how can i remove it ?
```
service_instance_id
instance
service_version
```

thanks.
