### DISCUSSION TITLE
How to filter Traces that match one or multiple conditions

### DISCUSSION THREAD

**Discussion by Rezrazi** [open-telemetry/opentelemetry-collector-contrib#27863] [Q&A]
I'm looking to excludes some traces that match some conditions based on their attributes, but the events are still exported to Tempo.

I'd appreciate if someone can help me with this setup, I did find the documentation a bit unclear.

Thanks 🙏 

Configuration
```yaml
  processors:
    filter/spans:
      spans:
        exclude:
          match_type: regexp
          attributes:
            - key: http.target
              value: "health-check"
            - key: http.target
              value: "horizon.*"
    batch: { }
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter: null
``` 

![CleanShot 2023-10-19 at 19 05 15](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/2086576/e41467cd-42b6-4c0e-ab72-839c97ce69eb)
