### DISCUSSION TITLE
How can i link logs and traces via loki and tempo

### DISCUSSION THREAD

**Discussion by polRk** [open-telemetry/opentelemetry-collector-contrib#28619] [Q&A]
My configuration 

```yaml
receivers:
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      http:
        endpoint: :4318

processors:
  # Data sources: traces, metrics, logs
  batch:

  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: label, duration, http.method, http.url, http.host, http.client_ip, http.user_agent, http.request_id, http.status_code, iam.user_id

  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.namespace, service.name, service.version, deployment.environment

exporters:
  debug:
    verbosity: detailed

  # Data sources: logs
  loki/1:
    endpoint: "http://grafana-loki:3100/loki/api/v1/push"
    default_labels_enabled:
      exporter: false
      job: false

  # Data sources: traces
  otlp/1:
    endpoint: "grafana-tempo:4317"
    tls:
      insecure: true

  # Data sources: metrics
  prometheusremotewrite/1:
    endpoint: "http://grafana-mimir:9009/api/v1/push"
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [attributes, resource]
      exporters: [loki/1]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/1]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite/1]

```
