### DISCUSSION TITLE
Unable to start otel-contrib with OpenSearch exporter basicauth enabled.

### DISCUSSION THREAD

**Discussion by AmythD** [open-telemetry/opentelemetry-collector-contrib#31122] [Q&A] [answered]
Hello,

I am trying to start otel-contrib using below config, but getting errors. Any help is appreciated.

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

extensions:
  basicauth/client:
    client_auth:
      username: user
      password: user

processors:
  batch:

exporters:
  opensearch/trace:
    dataset: otel
    namespace: traces
    http:
      endpoint: http://10.212.174.37:9200
      tls:
        insecure: true
      auth:
        authenticator: basicauth/client
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [opensearch/trace]
      processors: [batch]
```
**ERROR:**

`2024/02/08 05:15:34 collector server run finished with error: cannot start pipelines: failed to resolve authenticator "basicauth/client": authenticator not found`

**otelcol-contrib version 0.93.0**

**Comment by AmythD** [comment, marked as answer]
I realized I needed to specify the extensions again in the service section... Seems to be working now.

```
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [opensearch/trace]
      processors: [batch]

  extensions: [basicauth/client]
```
