### DISCUSSION TITLE
Collecting AWS cloudwatch logs

### DISCUSSION THREAD

**Discussion by jaslkaur29** [open-telemetry/opentelemetry-collector-contrib#31373] [Q&A]
I am trying to use the awscloudwatch receiver and print them to console for now using logging or debug exporter, this is the config that I am using. I have given full Cloudwatch permissions to IAM role. I can see that OTEL is able to connect with log group but unable to print logs from all the streams. How should I proceed further?

```

receivers:
  awscloudwatch:
    logs:
      groups:
        autodiscover:
          limit: 100
          prefix: /aws/events/networkmanagerloggroup
      poll_interval: 10s
    region: us-west-2
exporters:
  logging:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [awscloudwatch]
      exporters: [logging]
  telemetry:
    logs:
      level: "debug"

```

These are the logs that I am receiving from my OTEL pod (It does not print any stream related logging)

2024-02-19T18:57:01.806Z debug awscloudwatchreceiver@v0.93.0/logs.go:323 discovered log group {"kind": "receiver", "name": "awscloudwatch", "data_type": "logs", "log group": "{\n Arn: "arn:aws:logs:us-west-2:494665075828:log-group:/aws/events/networkmanagerloggroup:",\n CreationTime: 1706123061129,\n LogGroupClass: "STANDARD",\n LogGroupName: "/aws/events/networkmanagerloggroup",\n MetricFilterCount: 0,\n StoredBytes: 33447\n}"}
2024-02-19T18:57:11.773Z debug awscloudwatchreceiver@v0.93.0/logs.go:287 attempting to discover log groups. {"kind": "receiver", "name": "awscloudwatch", "data_type": "logs", "limit": 10}
2024-02-19T18:57:11.804Z debug awscloudwatchreceiver@v0.93.0/logs.go:323 discovered log group {"kind": "receiver", "name": "awscloudwatch", "data_type": "logs", "log group": "{\n Arn: "arn:aws:logs:us-west-2:494665075828:log-group:/aws/events/networkmanagerloggroup:",\n CreationTime: 1706123061129,\n LogGroupClass: "STANDARD",\n LogGroupName: "/aws/events/networkmanagerloggroup",\n MetricFilterCount: 0,\n StoredBytes: 33447\n}"}
