### DISCUSSION TITLE
[Q&A - Spanmetrics Connector] Aren't all 5xx errors stored to events{} metrics?

### DISCUSSION THREAD

**Discussion by pingping95** [open-telemetry/opentelemetry-collector-contrib#31437] [Q&A]
Aren't all 5xx errors stored as events metrics?

This is my otel collector config and OTEL Version is '0.92'

```
...
...
  connectors:
    # 1. SERVER Metrics
    spanmetrics:
      histogram:
        explicit:
          buckets: [10ms, 50ms, 100ms, 400ms, 800ms, 1.5s, 3s, 6s, 10s, 15s, 22s, 30s, 60s]
      aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
      metrics_flush_interval: 15s
      dimensions:
        - name: http.method
        - name: http.status_code
        - name: cluster
        - name: messaging.kafka.client_id
        # PRODUCER
        - name: messaging.destination.name
        - name: messaging.kafka.destination.partition
        # CONSUMER
        - name: messaging.kafka.consumer.group
        - name: messaging.kafka.source.partition
        - name: messaging.operation

      events:
        enabled: true
        dimensions:
          - name: exception.type

      resource_metrics_key_attributes:
        - service.name

...
```

I`m wondering what the criteria is for being stored in the events metric.

I am creating a **Request, Error, Duration (RED) dashboard** using the Spanmetrics Connector in the Opentelemetry collector.

Additionally, I want to utilize the **events metric** to see **which exceptions were thrown** in the dashboard at a glance.

<img width="1686" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/67780144/6e4a69ee-f7e8-4166-a188-2b59d75e6e66">

<img width="1227" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/67780144/144f875a-5f19-4429-aca6-e89e97cfd7c9">

I want to know `what criteria` is stored in the events metric.

If I want to store the exeption_type within a span in the events metric, is there a way to do that?

<img width="896" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/67780144/4f068a2f-fd8b-4afe-8f77-3bcfbef1499b">

- Real error counts ~= 60 
- Events{} metric`s count ~= 5 

Thanks
