### DISCUSSION TITLE
File-based bearertokenauth throws an "invalid header field value for Authorization" error.

### DISCUSSION THREAD

**Discussion by VedaprakashSubramanian** [open-telemetry/opentelemetry-collector-contrib#31458] [Q&A]
The following file-based bearertokenauth throws an "invalid header field value for Authorization" error:

````
extensions:
  bearertokenauth:
    scheme: Bearer
    filename: "/etc/otelcol-contrib/jwt.token"

receivers:
  filelog:
    include: [/var/log/*.log]
    operators:
    - type: move
      from: attributes['log.file.name']
      to: resource['filename']

processors:
  batch:

exporters:
  otlphttp:
    endpoint: "https://test-otlp-http.cloud.com"    
    auth:
      authenticator: bearertokenauth

service:
  extensions: [bearertokenauth]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [otlphttp]
````

Error message: 
`"name": "otlphttp", "error": "failed to make an HTTP request: Post \"https://test-otlp-http.cloud.com/v1/logs\":net/http: invalid header field value for \"Authorization\""`

The jwt.token file has a single line and no extra space or new line at the end. Sample jwt.token file:
`eyJ0eXA.....`

If the filename is replaced with "token: eyJ0eXA.....", the collector exports the logs. 

How can I fix it to use file?

I'm using the following release for testing:
https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.94.0/otelcol-contrib_0.94.0_linux_amd64.deb
