### DISCUSSION TITLE
How to start up JMX receiver?

### DISCUSSION THREAD

**Discussion by CzyerChen** [open-telemetry/opentelemetry-collector-contrib#31542] [Q&A]
I'm new here, and I want to start a jmx receiver to otel, but something wrong about starting up by docker.

- opentelemetry-jmx-metrics.jar version:1.33.0 downloaded from github release page
- otel/opentelemetry-collector-contrib version:0.95.0
- docker command:

`docker run -v $(pwd)/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml -v $(pwd)/opentelemetry-jmx-metrics.jar:/usr/local/opentelemetry-jmx-metrics.jar otel/opentelemetry-collector-contrib:latest`

- otel-collector-config.yaml:

```
receivers:
  jmx:
    jar_path: /usr/local/opentelemetry-jmx-metrics.jar
    endpoint: 192.168.x.x:1616
    target_system: jvm
    collection_interval: 10s
    username: admin
    password: xxxxx
    resource_attributes:
      host_name: jmx-activemq

processors:
  batch:
 
exporters:
  otlp:
    endpoint: 192.168.x.x:11800
    tls:
      insecure: true
service:
  pipelines:
    metrics:
      receivers:
      - jmx
      processors:
      - batch
      exporters:
      - otlp
```

- error messge:

```
cs.jar otel/opentelemetry-collector-contrib:latest
Error: invalid configuration: receivers::jmx: invalid `jar_path`: jar hash does not match known versions
2024/03/04 09:01:35 collector server run finished with error: invalid configuration: receivers::jmx: invalid `jar_path`: jar hash does not match known versions
```

I can trigger by executing jar `java -Dotel.jmx.property=value -jar opentelemetry-jmx-metrics.jar -config ./session.properties`

```
otel.jmx.service.url = service:jmx:rmi:///jndi/rmi://192.168.x.x:1616/jmxrmi
otel.jmx.target.system = jvm
otel.jmx.interval.milliseconds = 5000
otel.jmx.username = admin
otel.jmx.password = xxx
otel.jmx.remote.registry.ssl=false
otel.metrics.exporter = otlp
otel.exporter.otlp.endpoint = http://192.168.x.x:11800
```

I don't know what's wrong with me? Any help?
