### DISCUSSION TITLE
can't evaluate field memory_limiter in type string

### DISCUSSION THREAD

**Discussion by ghost** [open-telemetry/opentelemetry-collector-contrib#31935] [General]
When I try to helm install I get an error back:

```
❯ helm install otel open-telemetry/opentelemetry-collector -n otel -f otel-values.yaml
Error: INSTALLATION FAILED: template: opentelemetry-collector/templates/deployment.yaml:35:28: executing "opentelemetry-collector/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: opentelemetry-collector/templates/configmap.yaml:11:8: executing "opentelemetry-collector/templates/configmap.yaml" at <include "opentelemetry-collector.deploymentConfig" .>: error calling include: template: opentelemetry-collector/templates/_config.tpl:70:15: executing "opentelemetry-collector.deploymentConfig" at <include "opentelemetry-collector.baseConfig" $data>: error calling include: template: opentelemetry-collector/templates/_config.tpl:20:28: executing "opentelemetry-collector.baseConfig" at <$processorsConfig.memory_limiter>: can't evaluate field memory_limiter in type string
```

my otel-values.yaml content:

```
ingress:
  enabled: false

config:
  logLevel: info

  # These are for comparison only for the moment
  victoriametrics:
    enabled: false
  amp:
    enabled: false

### Values for the OTEL chart
mode: deployment

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ports:
  otlp:
    enabled: true
  otlp-http:
    enabled: true
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: true
  zpages:
    enabled: true
    containerPort: 55679
    servicePort: 55679
    hostPort: 55679
    protocol: TCP
  health:
    enabled: true
    containerPort: 13133
    servicePort: 13133
    hostPort: 13133
    protocol: TCP
  loki:
    enabled: true
    containerPort: 3500
    servicePort: 3500
    hostPort: 3500
    protocol: TCP

autoscaling:
   enabled: true
   minReplicas: 3
   maxReplicas: 10

# replicaCount: 3

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

serviceMonitor:
  enabled: true

config:
  exporters:
    otlp/tempo:
      endpoint: "http://tempo-app-dmor-distributor.tempo.svc:4317"

    prometheusremotewrite/mimir:
      endpoint: "http://mimir-app-dmor-distributor.mimir.svc:8080/api/v1/push"
      headers:
        X-Scope-OrgID: "anonymous"

    loki:
      endpoint: "http://loki-app-dmor-loki-distributed-distributor.loki.svc:3100/loki/api/v1/push"

  extensions:
    zpages:
      endpoint: ${env:MY_POD_IP}:55679

  processors:
    # Nothing to add here right now

  receivers:
    # Disable already defined receivers that we don't want
    jaeger: null
    prometheus: null
    zipkin: null

    # Enable any additional receivers we want

    loki:
      protocols:
        http:
          endpoint: ${env:MY_POD_IP}:3500
          
        grpc:
          endpoint: ${env:MY_POD_IP}:3600            
      

  service:
    # Add ability to change logging level
#      telemetry:
#        logs:
#          level: {{ tpl .Values.config.logLevel . }}

    pipelines:
      traces:
        receivers: [otlp]
        exporters: [otlp/tempo]
      metrics:
        receivers: [otlp]
        exporters: [prometheusremotewrite/mimir]
      logs:
        receivers: [otlp, loki]
        exporters: [loki]
```

Trying this with helm version:
```
❯ helm version
version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}
```

Any ideas what is going on? I removed the limits block to take the default and still get the same error. Not sure what is going on here
