### DISCUSSION TITLE
Transform events exception.message using replace_pattern

### DISCUSSION THREAD

**Discussion by al-mcintosh** [open-telemetry/opentelemetry-collector-contrib#32129] [Q&A] [answered]
Hi everyone, 
I'm trying to normalize exceptions by replacing UUIDs found in exception.message with the text '{UUID}' using the transform processor replace_pattern  with the following:

```
transform:
        trace_statements:
        - context: span
          statements:
          - replace_pattern(events.attributes["exception.message"], "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", "{UUID}")
```

Example text: `"exception.message": "Error occured: key NotFound for object f777277a-694f-4444-a3f0-5e60386c01c7"`

Thanks.
