### DISCUSSION TITLE
How to use azuremonitor to ship logs with trace_id that is converted to operation_id

### DISCUSSION THREAD

**Discussion by ylbeethoven** [open-telemetry/opentelemetry-collector-contrib#33281] [Q&A] [answered]
Hi,

I have an application that generates logs in JSON format.

I am using fluentbit to scrape and send these logs to opentelementry collector. 

With fluentbit, I have below output.
```
  outputs:
    - name: opentelemetry
      match: kong_http_log
      host: otel-collector
      port: 4318
      logs_uri: /v1/logs
      log_response_payload: true
      tls: off
      logs_body_key: ${message}
      logs_trace_id_message_key: traceid
      logs_span_id_message_key: spanid
```

With `otlphttp` exporter, I can see `trace_id` label for my logs in loki.  However, I do not see `operation_id` being created in Application insights. 

According to [docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter#logs)
> [TraceId](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-traceid) is mapped to operation_id column and [SpanId](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-spanid) is mapped to operation_parentId column.

Does anyone know how to correlate the trace_id from fluentbit to this TraceId?
