### DISCUSSION TITLE
Remove other than attribute or resource attribute keys from log context using the transform processor

### DISCUSSION THREAD

**Discussion by fredsig** [open-telemetry/opentelemetry-collector-contrib#33446] [Q&A]
Following the log context path here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/contexts/ottllog/README.md, I am trying for example to delete the instrumentation_scope.name "Scope.name" key using the transform processor and log context, but this seems not to be working. I want to remove Scope but also some other keys like TraceFlags, SeverityNumber, etc before I write them to an Elasticsearch index. I've tried the following (with no luck):

```
  transform/otlp-remove:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - delete_key(instrumentation_scope, "name")
          - delete_key(attributes, "instrumentation_scope.name")
```

Is this even possible?
