### DISCUSSION TITLE
how to configure snmpreceiver to poll all ifTable Metrics?

### DISCUSSION THREAD

**Discussion by hhgsplk** [open-telemetry/opentelemetry-collector-contrib#33580] [Q&A] [answered]
I want to query the Interface Table Metrics from every snmp target. This is basically a snmpwalk on OID .1.3.6.1.2.1.2.2.
All counters like ifInOctets, ifOutOctets, *Pkts, *Discards, *Errors etc are the metrics that are needed. The ifIndex Number is the key to the table entries and the ifDescr of every line item are needed to identify every interface row in that table (see screenshot). I don't understand the examples of the snmpreceiver: how do I need to set this up?
This is a walk:
![D47728A4-AB6A-435D-8FCE-5304900DB4CA](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/39929657/8c8c5e21-cea3-40c0-9471-efc496d341ea)
The same data as a table (software is ireasoning mib browser (free edition):

![9B5C9403-9E0C-4B25-85E4-26A8DBDACB52](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/39929657/02b123d2-c59d-4cac-9a66-71399899e335)

This is the export of the switch data from the mib browser (can be imported back into the mib browser):
[iftable.xml.gz](https://github.com/user-attachments/files/15843994/iftable.xml.gz)

**Comment by hhgsplk** [comment, marked as answer]
This works.

```
  snmp:
    collection_interval: 10s
    endpoint: udp://192.168.1.221:161
    version: v2c
    community: XXX

    resource_attributes:
      otel-snmp.sysName:
        oid: "1.3.6.1.2.1.1.5"

    attributes:
      otel-snmp.IF-MIB.ifDescr:
        oid: "1.3.6.1.2.1.2.2.1.2"

    metrics:
      otel-snmp.IF-MIB.ifInOctets:
        description: "Interface Incoming Bytes"
        unit: "By"
        sum:
          aggregation: cumulative
          monotonic: true
          value_type: int
        column_oids:
          - oid: "1.3.6.1.2.1.2.2.1.10"
            attributes:
              - name: otel-snmp.IF-MIB.ifDescr
          - oid: "1.3.6.1.2.1.1.5"
            resource_attributes:
              - otel-snmp.sysName

      otel-snmp.IF-MIB.ifOutOctets:
        description: "Interface Outgoing Bytes"
        unit: "By"
        sum:
          aggregation: cumulative
          monotonic: true
          value_type: int
        column_oids:
          - oid: "1.3.6.1.2.1.2.2.1.16"
            attributes:
              - name: otel-snmp.IF-MIB.ifDescr

```
