### DISCUSSION TITLE
Node name resource attribute not found in kubeletstats receiver data for the Pod information

### DISCUSSION THREAD

**Discussion by mukesh1327** [open-telemetry/opentelemetry-collector-contrib#33945] [Q&A]
I'm using kubeletstats receiver to collect the data of pods
Here is my configuration

```
      kubeletstats/pod:
        auth_type: serviceAccount
        collection_interval: 5s
        endpoint: 'https://${env:K8S_NODE_NAME}:10250'
        initial_delay: 1s
        insecure_skip_verify: true
        metric_groups:
          - pod
        metrics:
          k8s.pod.cpu.usage:
            enabled: true
          k8s.pod.cpu.utilization:
            enabled: false
```
In this I can't able to get the resource attribute of name of the node where the corresponding pod is associated.

Is there a way to get node name resource attribute for the above configuration ?
