### DISCUSSION TITLE
How can I use a separate exporter for the gRPC endpoint

### DISCUSSION THREAD

**Discussion by parmeshwar11** [open-telemetry/opentelemetry-collector-contrib#34023] [Q&A]
Below is my openetelemtry-collector-config.yaml (I am using the otel/opentelemetry-collector-contrib:0.91.0 docker image)

```

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:5555
      grpc
         endpoint:0.0.0.0:5556

exporters:
  logging:
    loglevel: warn
  otlphttp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    auth:
      authenticator: basicauth/client
```
