### DISCUSSION TITLE
receiver basic authentication

### DISCUSSION THREAD

**Discussion by krishnaexplore** [open-telemetry/opentelemetry-collector-contrib#34073] [Q&A]
I've following otel collector configuration (version 0.88)

```

extensions:
  basicauth/server:
    htpasswd:
      inline: |
        "myuser:mypassword"
receivers:
  otlp:
    protocols:
      grpc:
      http:
        auth:
          authenticator: basicauth/server
        #endpoint: 0.0.0.0:4318
        #cors:
        #  allowed_origins:
        #    - http://localhost:3000

processors:
  batch:

exporters:
  logging:
    loglevel: debug

  otlp/uptrace:
    endpoint: https://backend:4317
    tls: { insecure: false }
    headers:
      backend-auth: "<>"

service:
  extensions: [basicauth/server]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/uptrace]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]


```

I'm sending request like below still i'm getting 401 error

```
curl --header "Content-Type: application/json" \
     --header "Authorization: Basic myuser:mypassword" \
  --request POST \
  --data '{"username":"xyz","password":"xyz"}' \
  http://localhost:4318/v1/traces
```

where i'm going wrong, please help here
