### DISCUSSION TITLE
jaeger exporter configurations issue with version 0.103.1

### DISCUSSION THREAD

**Discussion by wmashal** [open-telemetry/opentelemetry-collector-contrib#34089] [Q&A] [answered]
Hi

When I am configuring the opentelemetry in my k8s cluster using the **"otel/opentelemetry-collector-contrib:0.103.1"** in deployment mode with the following jaeger exporter configurations but I got errors (see below) when the collector trying to export the traces  so **as a workaround** I am using zipkin to send my traces to Jaeger

**The Original Configurations** 

```
apiVersion: v1
data:
  relay: |
    exporters:
      logging:
        loglevel: debug
      otlp/jaeger:
        endpoint: api-gw-center-jaeger-operator-jaeger-collector.monitoring-prometheus.svc.cluster.local:14250
        retry_on_failure:
          enabled: true
        sending_queue:
          enabled: true
        tls:
          insecure: true
      zipkin:
        endpoint: http://api-gw-center-jaeger-operator-jaeger-collector.monitoring-prometheus.svc.cluster.local:9411/api/v2/spans
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      extensions:
      - health_check
      pipelines:
        logs:
          exporters:
          - logging
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
        traces:
          exporters:
          - logging
          - otlp/jaeger
          receivers:
          - otlp
          - opencensus
kind: ConfigMap
metadata:
  name: api-gw-center-opentelemetry-collector
  namespace: monitoring-prometheus


```

**The workaround in traces exporter I am using zipkin** 

```
apiVersion: v1
data:
  relay: |
    exporters:
      logging:
        loglevel: debug
      otlp/jaeger:
        endpoint: api-gw-center-jaeger-operator-jaeger-collector.monitoring-prometheus.svc.cluster.local:14250
        retry_on_failure:
          enabled: true
        sending_queue:
          enabled: true
        tls:
          insecure: true
      zipkin:
        endpoint: http://api-gw-center-jaeger-operator-jaeger-collector.monitoring-prometheus.svc.cluster.local:9411/api/v2/spans
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      extensions:
      - health_check
      pipelines:
        logs:
          exporters:
          - logging
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
        traces:
          exporters:
          - logging
          - zipkin
          receivers:
          - otlp
          - opencensus
kind: ConfigMap
metadata:
  name: api-gw-center-opentelemetry-collector
  namespace: monitoring-prometheus


```


The Error 

```
│ opentelemetry-collector 2024-07-16T07:45:51.765Z    error    exporterhelper/queue_sender.go:90    Exporting failed. Dropping data.    {"kind": "exporter", "data_type": "traces", "name": "otlp/jaeger", "error": "not retryable error: Permanent error: rpc error: code = Unknown desc = ", "dropped_items": 2}                                                         │
│ opentelemetry-collector go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1                                                                                                                                                                                                                                                                       │
│ opentelemetry-collector     go.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/queue_sender.go:90                                                                                                                                                                                                                                                            │
│ opentelemetry-collector go.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Consume                                                                                                                                                                                                                                                         │
│ opentelemetry-collector     go.opentelemetry.io/collector/exporter@v0.103.0/internal/queue/bounded_memory_queue.go:52                                                                                                                                                                                                                                                    │
│ opentelemetry-collector go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1                                                                                                                                                                                                                                                              │
│ opentelemetry-collector     go.opentelemetry.io/collector/exporter@v0.103.0/internal/queue/consumers.go:43
```
