### DISCUSSION TITLE
Removing resource label from telemetry

### DISCUSSION THREAD

**Discussion by sercanacar** [open-telemetry/opentelemetry-collector-contrib#34308] [General]
Hello,

I've tried various processors to remove the following label from the telemetry data and failed miserably. Any help is appreciated

![Screenshot 2024-07-30 at 10 04 49](https://github.com/user-attachments/assets/f1cd5789-674a-4395-a1a4-6b6439b57d6d)

I've tried

```
    processors:
      attributes:
        actions:
        - action: delete
          key: process_command_line
        - action: delete
          key: process.command.line
        - action: delete
          key: resource.process.command.line
        - action: delete
          key: resource_process.command.line
```
