### DISCUSSION TITLE
Transform k8sobject into expected result (Flatten `status.conditions` into usable key-value pair)

### DISCUSSION THREAD

**Discussion by mikhail5555** [open-telemetry/opentelemetry-collector-contrib#34350] [Q&A]
Hey all, I am trying to transform the following log statement into an usuable format, but am unable to flatten it the way i would like, could someone be able to help out with if this tranformation is possible?

Otel collector config:
```yaml
config:
	exporters:
	  logging/debug:
		verbosity: detailed
	processors:
	  transform:
		error_mode: ignore
		log_statements:
		  - context: log
			statements:
			  - flatten(body["status"])
	receivers:
	  k8sobjects:
		objects:
		  - group: serving.knative.dev
			interval: 15m
			mode: pull
			name: services
	service:
	  pipelines:
		logs:
		  exporters:
			- logging/debug
		  processors:
			- transform
		  receivers:
			- k8sobjects
```

Body:
```json
{
	"apiVersion": "serving.knative.dev/v1",
	"kind": "Service",
	"status": {
		"address": {
			"url": "http://xxx.xxx.svc.cluster.local"
		},
		"conditions": [{
				"lastTransitionTime": "2024-07-31T14:41:04Z",
				"status": "True",
				"type": "ConfigurationsReady"
			}, {
				"lastTransitionTime": "2024-07-31T14:41:04Z",
				"status": "True",
				"type": "Ready"
			}, {
				"lastTransitionTime": "2024-07-31T14:41:04Z",
				"status": "True",
				"type": "RoutesReady"
			}
		],
		"latestCreatedRevisionName": "xxxx",
		"latestReadyRevisionName": "xxxx",
		"observedGeneration": 318,
		"traffic": [{
				"latestRevision": true,
				"percent": 100,
				"revisionName": "xxxx"
			}
		],
		"url": "http://xxx.xxx.svc.cluster.local"
	}
}
```

current result
```json
{
	"apiVersion": "serving.knative.dev/v1",
	"kind": "Service",
	"status": {
		"address.url": "xxxx",
		"conditions.0": {
			"lastTransitionTime": "2024-07-31T14:20:30Z",
			"status": "True",
			"type": "ConfigurationsReady"
		},
		"conditions.1": {
			"lastTransitionTime": "2024-07-31T14:20:34Z",
			"status": "True",
			"type": "Ready"
		},
		"conditions.2": {
			"lastTransitionTime": "2024-07-31T14:20:34Z",
			"status": "True",
			"type": "RoutesReady"
		},
		"latestCreatedRevisionName": "xxxx",
		"latestReadyRevisionName": "xxxx",
		"observedGeneration": 54,
		"traffic.0": {
			"latestRevision": true,
			"percent": 100,
			"revisionName": "xxxx"
		},
		"url": "xxxx"
	}
}
```

Expected/wanted format:
```json
{
	"apiVersion": "serving.knative.dev/v1",
	"kind": "Service",
	"status": {
		"address": {
			"url": "http://xxx.xxx.svc.cluster.local"
		},
		"conditions.ConfigurationsReady": {
				"lastTransitionTime": "2024-07-31T14:41:04Z",
				"status": "True",
				"type": "ConfigurationsReady"
			},
               "conditions.Ready": {
				"lastTransitionTime": "2024-07-31T14:41:04Z",
				"status": "True",
				"type": "Ready"
			}, 
               "conditions.RoutesReady": {
				"lastTransitionTime": "2024-07-31T14:41:04Z",
				"status": "True",
				"type": "RoutesReady"
			},
		"latestCreatedRevisionName": "xxxx",
		"latestReadyRevisionName": "xxxx",
		"observedGeneration": 318,
		"traffic": [{
				"latestRevision": true,
				"percent": 100,
				"revisionName": "xxxx"
			}
		],
		"url": "http://xxx.xxx.svc.cluster.local"
	}
}
```

aka `flatten status.conditions => (value) => status.conditions.[value.type] = value `
