### DISCUSSION TITLE
[helm] Otel Collector Not Extracting Labels From Pod

### DISCUSSION THREAD

**Discussion by natenberenstein** [open-telemetry/opentelemetry-collector-contrib#34625] [Q&A]
## Environment
- K3s cluster (v1.30.2+k3s1)
  - Using Traefik Ingress Controller
- Go (go1.22.4)
- Opentelemetry-collector (v0.106.1)

# Problem
I defined the labels that I want to extract from my pod (e.g. app.kubernetes.io/component) in my values.yaml file, but it doesn't show up in the Tempo traces.  Below is my values.yaml file:

```yaml
mode: deployment

image:
  repository: otel/opentelemetry-collector-k8s

# We only want one of these collectors - any more and we'd produce duplicate data
replicaCount: 1

presets:
  # enables the k8sclusterreceiver and adds it to the metrics pipelines
  clusterMetrics:
    enabled: false
  # enables the k8sobjectsreceiver to collect events only and adds it to the logs pipelines
  kubernetesEvents:
    enabled: false
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
    extractAllPodAnnotations: true
podMonitor:
  enabled: true
serviceMonitor:
  enabled: true
ports:
  metrics:
    enabled: true
config:
  processors:
    k8sattributes:
      extract:
        metadata:
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.start_time
          - container.image.name
          - container.image.tag
        labels:
          - tag_name: app.kubernetes.io/component
            key: app.kubernetes.io/component
            from: pod
          - tag_name:
      pod_association:
        - sources:
            - from: resource_attribute
              name: k8s.pod.ip
        - sources:
            - from: resource_attribute
              name: k8s.pod.uid
        - sources:
            - from: connection
  exporters:
    #otlp:
    #  endpoint: tempo-distributor.tempo.svc.cluster.local:4317
    #  tls:
    #    insecure: true
    otlphttp:
      endpoint: http://tempo-distributor.tempo.svc.cluster.local:4318
      tls:
        insecure: true
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
    #zipkin:
    #  endpoint: 0.0.0.0:9411
  service:
    telemetry:
      logs:
        level: DEBUG
        development: true
        encoding: json
    pipelines:
      metrics: null
      logs: null
      traces:
        processors: [k8sattributes, batch]
        receivers: [otlp]
        exporters: [otlphttp]

ingress:
  enabled: true
  hosts:
    - host: otel-collector.test.com
      paths:
        - path: /
          pathType: Prefix
          port: 4318
```

And here is what I see in Tempo:
![image](https://github.com/user-attachments/assets/b32606a0-b327-429d-9adb-57c853948ea8)

## Discussion
I was expecting the pod labels I defined in my manifest file to be extracted and attached to the spans, but the collector doesn't seem to extract those labels.  I'm wondering if there are additional things I need to configure, or if this is something that the collector isn't handling correctly.

Thanks in advance!

**UPDATE**
I just discovered that the collector is extracting the labels from Traefik instead of the application that's actually sending the traces to the collector.  So my  new question would be: is it possible to fetch the labels from the pod that emitted the traces instead of getting the labels from the Traefik pod?  Or even combine the labels in some way to enrich the metadata?

## Resources I looked into
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md#extracting-attributes-from-pod-labels-and-annotations
