### DISCUSSION TITLE
Using filterprocessor for logs while wildcarding

### DISCUSSION THREAD

**Discussion by sercanacar** [open-telemetry/opentelemetry-collector-contrib#34919] [Q&A] [answered]
Hello,

I'm trying to use filter processor to drop entries which don't match certain string which startswith XYZ

```
      filter/test:
        error_mode: ignore
        logs:
          log_record:
            - 'instrumentation_scope.name != "com.mypackage.*"'
```

I've tried the following also
```
com.mypackage
```

The above doesn't work, all logs are dropped, so clearly i'm misunderstood the docs. How can I wildcard/regex the log_record?

Thanks
