### DISCUSSION TITLE
Clickhouse exporter error "retrieved value (type=string) cannot be used as a Conf" when selecting database

### DISCUSSION THREAD

**Discussion by candlerb** [open-telemetry/opentelemetry-collector-contrib#35157] [General]
(Raising this as a discussion rather than an issue, as I'm not sure if it's me being dense)

Using otelcol-contrib 0.109.0 under Linux, with the following attempt at `config.yaml`:

```
receivers:
  syslog:
    udp:
      listen_address: "[::]:5140"
    protocol: rfc3164
    location: Europe/London

exporters:
  clickhouse:
    endpoint: "tcp://localhost:9000?dial_timeout=10s"
    username: log_ingest
    password: xyzzy
    database: default
    async_insert: true
    ttl: 72h
    compress: lz4
    database: default
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    create_schema: true
    timeout: 5s

service:
  pipelines:
    logs:
      receivers: [syslog]
      exporters: [clickhouse]
```

The collector fails to start, with the following error:

```
otelcol-contrib[7905]: Error: failed to get config: cannot resolve the configuration: retrieved value (type=string) cannot be used as a Conf
```

That's not very helpful in telling me what the error is, or where the error is!

I had to do a binary chop on the config in order to identify the problematic line. It turns out the fault is here:

```
    database: default
```

If I comment out that line, then the collector starts successfully.

Actually, I have three issues now:

1. The error report didn't explain that the problem was with the "database" setting
2. In the [documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/README.md), there are several examples showing that the database setting *is* a string, and indeed the [source code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.109.0/exporter/clickhouseexporter/config.go#L32) confirms this. So I still don't understand what I did wrong.
3. Given the above, how do I point the exporter at a clickhouse database other than "default"? Should I put something in the endpoint or connection_params?

I searched for the string "retrieved value (type=string) cannot be used as a Conf" in both issues and discussions, in both repos "opentelemetry-collector" and "opentelemetry-collector-contrib", and found zero results.
