### DISCUSSION TITLE
Queries on using jaegerremotesampling

### DISCUSSION THREAD

**Discussion by shobanakupuraj** [open-telemetry/opentelemetry-collector-contrib#35386] [Q&A]
Hi @yurishkuro @frzifus,

I'm new to using OpenTelemetry, and I need to configure the OpenTelemetry trace collector to support remote sampling (since my clients are set up for remote sampling).

Here is the relevant portion of my client configuration, where it tries to connect to the Jaeger API:

```
  jaegerRemoteSampler := jaegerremote.New(
    os.Args[1],
    jaegerremote.WithSamplingServerURL("http://localhost:14250"),
    jaegerremote.WithSamplingRefreshInterval(10*time.Second), // Poll frequently for quicker feedback
    jaegerremote.WithInitialSampler(sdktrace.TraceIDRatioBased(1.0)),
)
jaegerRemoteSampler.Close()
jaegerRemoteSampler.UpdateSampler()
```

After reviewing available OpenTelemetry plugins, I found that the jaegerremotesampling extension seems to be what I need: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/jaegerremotesampling.

Below is the configuration I am using:

```yaml
exporters:
  logging:
    verbosity: detailed

extensions:
  jaegerremotesampling:
    source:
      reload_interval: 100s
      file: /jaeger/samplingstrategies.json

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  # Ensure this matches your Go application

service:
  extensions:
    - jaegerremotesampling
  pipelines:
    traces:
      exporters:
        - logging
      receivers:
        - otlp
```

I don't have any other setup apart from this. My expectation is that traces collected through port 4317 will apply the sampling strategy and export to the logging exporter. However, I'm wondering if I need additional configuration. Do I need to collect spans using a Jaeger receiver or have a Jaeger collector running to apply the sampling strategy? I'm unsure about the correct setup required for the **jaegerremotesampling** extension. Any guidance would be greatly appreciated.

**Comment by yurishkuro** [comment]
* Your code example looks odd, why do you close the sampler? You need to pass it to the tracer provider.
* You probably need port 5778, because the other one is gRPC. It's best to look at the SDK extension's example
* Remote sampling has nothing to do with how traces are collected in the backend, sampling happens only in the SDK.

**Comment by shobanakupuraj** [comment]
Thanks for the input @yurishkuro , http://localhost:5778/sampling api is accessible and it was giving the expected results.

We are in the process of migrating from Jaeger to the OpenTelemetry Collector. Some clients are currently using port `14268` for remote sampling, but I noticed that this port is not accessible when running the default OpenTelemetry Collector binary. Since port `5778` is used by the Jaeger Agent and we don't require it, we need to ensure that the OpenTelemetry Collector can support both ports `14268` and `14250` for remote sampling.

For example:

`
curl "http://localhost:5778/sampling?service=foo" | jq
{
  "probabilisticSampling": {
    "samplingRate": 1
  }
}
`

The above command works fine, but when trying to access the sampling endpoint on port `14268`:

`
curl "http://localhost:14268/api/sampling?service=foo"
`

I get the following error:

`
curl: (7) Failed to connect to localhost port 14268: Connection refused
`

How can we configure the OpenTelemetry Collector to support existing clients that use the Collector ports `14250` and `14268`? I have not found any example configuration showing how to modify or enable these ports for the `jaegerremotesampling` extension. Could you provide more information or guidance on how to achieve this?

**Reply by yurishkuro** [reply]
> we need to ensure that the OpenTelemetry Collector can support both ports 14268 and 14250 for remote sampling

this extension does not run on two ports. You may be able to duplicate the extension (with different names).

**Comment by shobanakupuraj** [comment]
@yurishkuro , ok, sure I will give it a try, but in the documentation, I don't find a way to configure the port for jaegerremotesampling, can you please let me know the configuration for it.

**Comment by shobanakupuraj** [comment]
Hi @yurishkuro ,

I understand, the 14268 is available, but not sure on the procedure for configuring it, https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/samplers/jaegerremote/README.md

 To be honest, I don't require 5778 (since it is not deployed as an agent) I only need collector endpoints to be accessible for the clients.
Would be really great if you give the approach to configure it

**Comment by shobanakupuraj** [comment]
Any support here? Please let me know how to configure remote sampling collector ports for telemetry collector, ie. port 14268, 14250

```
extensions:
   jaegerremotesampling:
     source:
       reload_interval: {{ .Values.samplingStrategiesReloadInterval }}
       file: /etc/sampling/samplingstrategies.json
```

**Comment by yurishkuro** [comment]
The extension config has HTTP and gRPC server settings https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3e42ac889bdf82259e2e9015324f610b912a7a48/extension/jaegerremotesampling/config.go#L23

Both support `endpoint` property where you can provide whichever port number you want.

**Comment by shobanakupuraj** [comment]
Thank you @yurishkuro ,

Done the configuration below, it is working fine.

```
extensions:
  jaegerremotesampling:
    http:
      endpoint: "0.0.0.0:14268"
    grpc:
      endpoint: "0.0.0.0:14250"
    source:
      reload_interval: "2m"
      file: /home/ekxxsho/jaeger/samplingstrategies.json
```

But according to the https://www.jaegertracing.io/docs/1.63/apis/#remote-sampling-configuration-stable

I would like to hit `http://localhost:14268/api/sampling` for HTTP and `http://localhost:14250` for Grpc.

But what I get,

```
$ curl "http://localhost:14268/sampling?service=foo" | jq
{
  "probabilisticSampling": {
    "samplingRate": 1
  }
}
```

instead of,

```
curl "http://localhost:14268/api/sampling?service=foo"
404 page not found
```

why this happens, so it is expected to hit `/sampling` always irrespective of receiving input via grpc or http? just we want the client libraries not to make any change in the URL(since we are migrating from jaeger to otel) we need to know this.
