### DISCUSSION TITLE
Not able to get k8s attribues for file logs

### DISCUSSION THREAD

**Discussion by hammadahmed1985** [open-telemetry/opentelemetry-collector-contrib#35530] [Q&A]
Hi all,
I would love to get some help here. I am trying to add k8s attribues to my log events that I am receiving using the filelog receiver. This is on a collector running as a daemonset. Here's my receiver:
```    
      filelog:
        include:
          - /var/lib/kubelet/pods/*/volumes/kubernetes.io~csi/*/mount/*.log
        start_at: beginning
        include_file_path: true
        include_file_name: true
        operators:
          - type: regex_parser
            id: parse-custom-path
            regex: '^/var/lib/kubelet/pods/(?P<uid>[a-f0-9\-]{36})/volumes/kubernetes.io~csi/(?P<pvc_uid>[^/]+)/mount/[^/]+\.log$'
            parse_from: attributes["log.file.path"]
```
Here's my k8s attribute:
```
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          # only retrieve pods running on the same node as the collector
          node_from_env_var: K8S_NODE_NAME
        extract:
          # The attributes provided in 'metadata' will be added to associated resources
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
          - sources:
             - from: resource_attribute
               name: k8s.pod.uid
          - sources:
             - from: resource_attribute
               name: log.file.path
```
Here's what I see in my debug exporter:
```
Trace ID: 
Span ID: 
Flags: 0
LogRecord #96
ObservedTimestamp: 2024-10-01 16:37:38.91378047 +0000 UTC
Timestamp: 1970-01-01 00:00:00 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Str(INFO:MME-SBI-4:)
Attributes:
     -> log.file.name: Str(master.log)
     -> log.file.path: Str(/var/lib/kubelet/pods/8a2db651-69b7-431c-b4d4-0dd668ef6c29/volumes/kubernetes.io~csi/pvc-615259b5-a7b2-4e9a-9ec8-60dfeb10d84d/mount/master.log)
     -> uid: Str(8a2db651-69b7-431c-b4d4-0dd668ef6c29)
     -> pvc_uid: Str(pvc-615259b5-a7b2-4e9a-9ec8-60dfeb10d84d)
```
I have tried various pod associations but no luck.
