### DISCUSSION TITLE
opentelemetry-collector-contrib docker container - permission denied when trying to access docker logs

### DISCUSSION THREAD

**Discussion by GD-Dal** [open-telemetry/opentelemetry-collector-contrib#35774] [Q&A]
Hi.
I'm trying to set up a otel-collector (my first!) to collect all the docker container logs and send them to OpenObserve for better visabiltiy etc.

But I'm getting permission denied when trying to access the docker logs.
Docker and all the containers runs with a user called dockeruser, and it has been added to sudoers along with the docker group

The docker-compose.yml looks like this:

```
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - frontend
      - backend
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
networks:
  frontend:
    external: true
  backend:
    external: true
```

And the config.yaml:

```
receivers:
  filelog:
    include_file_path: true
    include:
      - /var/lib/docker/containers/*/*-json.log
      
    operators:
      - id: container-parser
        type: container

exporters:
  otlphttp/openobserve:
    endpoint: https://oo.domain.tld/api/default
    headers:
      Authorization: Basic YXBwX2Fkllkjlkjlka29tbXVuZS5ubzowUElCT3Q3U0Ywd2tsTm5k
      stream-name: default

service:
  
  pipelines:
   
    logs:
      receivers: [filelog]
      exporters: [otlphttp/openobserve]
```

How can I solve this?
Or is there another way to collect and ship the docker container logs?

Thanks
