### DISCUSSION TITLE
How to dynamically set service_name for Loki

### DISCUSSION THREAD

**Discussion by AlTosterino** [open-telemetry/opentelemetry-collector-contrib#35883] [Q&A]
Hello!

I'm using the below configuration file for OpenTelemetry
```yaml
receivers:
  filelog:
    include:
      - /app/logs/file_*.log
    start_at: end
    operators:
      - type: json_parser

processors:
  resource:
    attributes:
      - action: insert
        key: service.name
        value: log-generator
      - action: insert
        key: loki.format
        value: json

exporters:
  otlphttp:
    endpoint: http://loki:3100/otlp
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [resource]
      exporters: [otlphttp, debug]
```

Everything works fine, service_name is set as `log-generator`, but when I change `value` to `from_attribute: record.extra.service`, then Loki doesn't get expected service name (it becomes unknown_service).

My log statement looks like this:
```
{"text": "Action 'Add to Cart' took unusually long (9s)\n", "record": {"elapsed": {"repr": "0:00:07.483302", "seconds": 7.483302}, "exception": null, "extra": {"service": "log-generator-service", "user_id": "d2f066e5-bf54-4c98-8523-de5c7717f38f", "action": "Add to Cart", "timestamp": "2024-10-19T16:15:13.157894", "session_id": "4498e499-d90c-46ce-9a63-1610f49f128d", "product_id": "d0bb8202-24c9-4b1f-9408-d834cf608a32", "category": "Home & Garden", "duration": 9, "success": true}, "file": {"name": "__init__.py", "path": "/app/src/log_generator/__init__.py"}, "function": "generate_user_journey_logs", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 76, "message": "Action 'Add to Cart' took unusually long (9s)", "module": "__init__", "name": "log_generator", "process": {"id": 16, "name": "MainProcess"}, "thread": {"id": 281473461252480, "name": "Thread-2 (simulate_user_journey)"}, "time": {"repr": "2024-10-19 16:15:13.157957+00:00", "timestamp": 1729354513.157957}}}
```

Everything works fine with the `service.name` set as `log-generator`. However, when I attempt to change the value to `from_attribute: record.extra.service`, Loki no longer receives the expected service name (it gets set to `unknown_service`).

Additionally, this nested `from_attribute` doesn't seem to work for other processors either. For example, if I set `from_attribute: record`, the entire record is sent to Loki, but `from_attribute: record.extra.service` is ignored.

Does the OpenTelemetry Collector support handling nested JSON in the `from_attribute` directive?

Thanks in advance.

**Comment by mar4uk** [comment]
Hey! The `from_attibute: record.extra.service` option tries to find the `record.extra.service` attribute in the OTLP log record. If you add exporter debug into your pipeline with visibility: "detailed", you will see that the record doesn't have such an attribute. That's why the resource attribute is not set and is displayed as undefined_service in Loki. To fix this you need to add attribute first. To do it transform processor could be used: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#parsing-json-logs. 

The config for processors part will look like:
```
processors:
  transform:
     error_mode: ignore
  log_statements:
    - context: log
      statements:
        - merge_maps(cache, ParseJSON(body), "upsert") where IsMatch(body, "^\\{") 
        - set(attributes["record.extra.service"], cache["record.extra.service"])
  resource:
    attributes:
      - action: insert
        key: service.name
        from_attribute: record.extra.service
      - action: insert
        key: loki.format
        value: json
```
Additionally, you use otlphttp exporter to send data to Loki. Loki hints (`loki.format`) don't work for this setup, because logs are exported in OTLP format, not in Loki format
