### DISCUSSION TITLE
How to map ServerityNumber to ServerityText?

### DISCUSSION THREAD

**Discussion by Wudadada** [open-telemetry/opentelemetry-collector-contrib#35890] [Q&A] [answered]
I have tried some configurations but it didn't work

 <img width="1216" alt="image" src="https://github.com/user-attachments/assets/4810419d-fd03-4bb7-93de-3981b0675fbb">

full config
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:19100']

processors:
  batch:
    timeout: 5s
    send_batch_size: 100000
  attributes:
    actions:
      - key: SeverityText
        action: insert
        from_attribute: SeverityNumber
        value: |
          if (SeverityNumber == 1, "TRACE",
              if (SeverityNumber == 5, "DEBUG",
              if (SeverityNumber == 9, "INFO",
              if (SeverityNumber == 13, "WARN",
              if (SeverityNumber == 17, "ERROR",
              if (SeverityNumber == 21, "FATAL", "DEFAULT"))))))

exporters:
  clickhouse:
    endpoint: tcp://10.105.212.248:9000?dial_timeout=10s
    create_schema: true
    database: otel
    async_insert: true
    ttl: 72h
    compress: lz4
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    username: "default"
    password: "123"
    cluster_name: cluster_3S_1R
    table_engine:
      name: "ReplicatedMergeTree"

    logs_table_name: otel_logs

    traces_table_name: otel_traces

    metrics_tables:
      gauge: 
        name: "otel_metrics_gauge"
      sum: 
        name: "otel_metrics_sum"
      summary: 
        name: "otel_metrics_summary"
      histogram: 
        name: "otel_metrics_histogram"
      exponential_histogram: 
        name: "otel_metrics_exp_histogram"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [clickhouse]

  telemetry:
    logs:
      level: "debug"
```
