### DISCUSSION TITLE
InfluxDB Exporter `ExponentialHistogram` Support

### DISCUSSION THREAD

**Discussion by IakMastro** [open-telemetry/opentelemetry-collector-contrib#36253] [General]
Hello,

I am using the InfluxDB OTEL Exporter to export metrics. However, I get this error: 

```
024-11-07T09:47:49.183Z        error   internal/queue_sender.go:92     Exporting failed. Dropping data.        {"kind": "exporter", "data_type": "metrics", "name": "influxdb", "error": "not retryable error: Permanent error: failed to convert OTLP metric to line protocol: unknown metric type \"ExponentialHistogram\"", "dropped_items": 20}
go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1
```

It is missing the `ExponentialHistogram` which I need to export.

This is my configuration:

```yaml
  influxdb:
    endpoint: http://influxdb:8086
    timeout: 500ms
    org: xxxx
    bucket: metrics
    token: xxx
    metrics_schema: telegraf-prometheus-v2
```

I get the same error when the `metrics_schema` is set at `telegraf-prometheus-v1`. I am using this images: `influxdb:2.7.10` and `otel/opentelemetry-collector-contrib:0.112.0`.

I am not sure if I haven't configured something or it's a bug/missing feature.

Cheers!
