### DISCUSSION TITLE
What is the best way to get httpcheck reciever monitoring on many endpoints?

### DISCUSSION THREAD

**Discussion by sRAVanI417** [open-telemetry/opentelemetry-collector-contrib#36290] [Q&A]
To monitor multiple HTTP endpoints using an otel collector, right now I have to list all the endpoints as below in otel-config.yaml

```yml
receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
  httpcheck:
    targets:
      - endpoint: <http://localhost:5000/>
        method: GET
      - endpoint: <http://localhost:5000/one>
        method: GET
      - endpoint: <http://localhost:5000/two>
        method: GET
      - endpoint: <http://localhost:5000/three>
        method: GET
      - endpoint: <http://localhost:5000/four>
        method: GET
      - endpoint: <http://localhost:5000/error>
        method: GET
    collection_interval: 10s
 ```
 
 Is there a better way to do this? Do we have an option to connect openAPI yaml file or is any automation present for a similar requirement?

**Comment by SiwyDym** [comment]
In the current version(0.121.0) it possible to make it a little bit smoother: 
```
receivers:
  httpcheck:
    targets:
      - method: "GET"
        endpoints:      
         - "http://localhost:5000/"
         - "http://localhost:5000/one"
         - "http://localhost:5000/two"
         - "http://localhost:5000/three"
         - "http://localhost:5000/four"
         - "http://localhost:5000/error"
     collection_interval: 10s
```
