### DISCUSSION TITLE
Advice-- Receiver for OSSEC via Syslog

### DISCUSSION THREAD

**Discussion by rphung-cloudwave** [open-telemetry/opentelemetry-collector-contrib#36417] [General]
Greetings--
I've attempted to create a receiver for OSSEC messages from an ossec-control server by enabling a syslog forwarder:
from ossec.conf
```
<syslog_output>
    <server>localhost</server>
    <port>10514</port>
  </syslog_output>
  ```
  
  Then on my agent config.yaml:
  ```
  receivers:     
    syslog:
      udp:
        listen_address: "0.0.0.0:10514"
      protocol: rfc3164
      location: UTC
      attributes:
        chronicle_log_type: OSSEC
 ```
      
  I get something like---
  `Failed to process entry","kind":"receiver","name":"syslog","data_type":"logs","operator_id":"syslog_input_internal_parser","operator_type":"syslog_parser","error":"parsed value was not rfc3164 or rfc5424 compliant"`
  
 Clearly, OSSEC isn't rfc-compliant.
 I've tried something like:
```
udplog:
    listen_address: "localhost:10514"
    attributes:
      chronicle_log_type: OSSEC
```
and although it looks like it's listening, I'm not getting any events.
Any help is appreciated.
