### DISCUSSION TITLE
Issues with running OTEL Contrib Collector on RHEL8

### DISCUSSION THREAD

**Discussion by ETURNA** [open-telemetry/opentelemetry-collector-contrib#36593] [Q&A]
Greetings,

Lately I've been exploring the option of running OTEL Contrib on an AWS EC2 instance for the purpose of supporting CollectD metrics. Right now I have the non-contrib (ADOT) version running fine on ECS. I mostly have my EC2 cluster deployed in a similar fashion as my ECS cluster. Here's my collector configuration:

```
receivers:
    otlp:
        protocols:
            grpc:
                endpoint: "0.0.0.0:4317"
            http:
                endpoint: "0.0.0.0:4318"
        collectd:
            endpoint: "0.0.0.0:8080"
            timeout: "50s"
exporters:
    otlphttp:
        endpoint: "https://myservice.com/api/v2/otlp"
        headers: {"Authorization:": "Api-Token ABCDEFG123456789"}
        sending_queue:
            enabled: true
            num_consumers: 20
            queue_size: 20000
service:
    pipelines:
        metrics:
            receivers: [otlp, collectd]
            exporters: [otlphttp]
    telemetry:
        logs:
            level: "debug"
```

I have the EC2 instance behind an Application Load Balancer and I'm using a self-signed certificate to point any metrics transmission with a TLS listener. For example purposes, the URL will be _otelcontrbonec2.com_ for this discussion. For now I'm using a Python function for metrics transmission.

_http:://otelcontrbonec2.com:4318/v1/metrics_ seems to receive metrics just fine.

However _https:://otelcontrbonec2.com:4318/v1/metrics_ produces the following error:
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1006)
```

_https:://otelcontrbonec2.com/v1/metrics_ produces the following error:
```
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)
```

As I previously mentioned, I have my EC2 + ALB configured similar to my ECS + ALB cluster, with port 4318 setup as an HTTP listener and target group... and 443 as my HTTPS listener with the self-signed certificate assigned.

Curious if I'm doing anything wrong here... or if there's an option I can enable so I can use HTTPS instead of HTTP?

Any insight is greatly appreciated!
