### DISCUSSION TITLE
Oracle sqlqueryreceiver queries from v$ views

### DISCUSSION THREAD

**Discussion by Siampam** [open-telemetry/opentelemetry-collector-contrib#36690] [Q&A]
Hi,

I do have the problem with sqlqueryreceiver and oracle queries. It seems like dollar '$' sign is the problem when there is v$ view in the from clause. I was trying different ways to escape dollar sign, but nothing seems to work. Below you can see the example of the query that I was testing.

Do you know how to deal with dollar sign in such a query to make it work?

**Sample query:**
```
 sqlquery/pdb1:
    datasource: "oracle://host:port/service?WALLET=/opt/oracle/wallet_exporter"
    driver: oracle
    queries:
      - sql: "select instance_number as innum, instance_name as inname from v$instance"
        metrics:
          - metric_name: instance.number.pdb1
            value_column: "INNUM"
            attribute_columns: [ INNAME ]
```

**Error message:**
`{"level":"error","ts":1733390105.0897303,"caller":"scraperhelper/scrapercontroller.go:197","msg":"Error scraping metrics","kind":"receiver","name":"sqlquery/pdb1","data_type":"metrics","error":"Scraper: ORA-00942: table or view does not exist\n","scraper":"sqlqueryreceiver/query-1: select instance_number as innum, instance_name as inname from v","stacktrace":"go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\tgo.opentelemetry.io/collector/receiver@v0.103.0/scraperhelper/scrapercontroller.go:197\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\tgo.opentelemetry.io/collector/receiver@v0.103.0/scraperhelper/scrapercontroller.go:173"}`

**Comment by Siampam** [comment]
Found the solution myself, there should be double dollar used, e.g.:
```
      - sql: "select instance_number as innum, instance_name as inname from v$$instance"
        metrics:
          - metric_name: instance.number.pdb1
            value_column: "INNUM"
            attribute_columns: [ INNAME ]
      - sql: "select bytes from dba_segments where rownum = 1"

```
