### DISCUSSION TITLE
Error with Connector Count: Invalid Temporality and Type Combination for Metric in Prometheus Remote Write

### DISCUSSION THREAD

**Discussion by sswieton** [open-telemetry/opentelemetry-collector-contrib#37143] [Q&A]
Hi,

**Context :** 
open-telemetry/opentelemetry-collector             0.115.1 

**Description**

I'd like to count the number of logs generated by my application and create a new metric in OpenTelemetry Collector that reflects this count
I am using a count connector, and the metric is pushed to a Prometheus instance using the Prometheus Remote Write exporter

An error is generated by the Prometheus Remote Write exporter stating: "invalid temporality and type combination for metric 'my.count'".
The metric generated seems to have **Aggregation Temporality set to Delta**, but I dont' know how to change it to Cumulative in the count connector configuration.

It may not be the reason for the issue. Could you please help?
Thanks  for your support

```
  connectors:
    count:
      logs:
        my.count:
          description: "count logs"
          attributes:
            - key: service.name
              default_value: "otel-test-app"      
```
Pipeline

```
    pipelines:
      ...
      metrics/counts:
        receivers: [count]
        processors: [batch]
        exporters: 
         - prometheusremotewrite
   
      logs:
        receivers:
          - otlp
        processors:
          - attributes/logs
          - k8sattributes/logs
          - batch
        exporters: 
          - otlphttp/loki
          - count
```

**Detailled Logs** 

InstrumentationScope github.com/open-telemetry/opentelemetry-collector-contrib/connector/countconnector
Metric #0
Descriptor:
     -> Name: my.count
     -> Description: count logs
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Delta
NumberDataPoints #0
Data point attributes:
     -> service.name: Str(otel-test-app)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2025-01-10 14:06:07.278717542 +0000 UTC
Value: 1
  
2025-01-10T14:06:08.279Z        debug   prometheusremotewriteexporter@v0.115.0/exporter.go:198  failed to translate metrics, exporting remaining metrics        {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "invalid temporality and type combination for metric \"my.count\"", "translated": 1}
