### DISCUSSION TITLE
Tail sampling - boolean_attribute not work for attributes from OTEL_RESOURCE_ATTRIBUTES

### DISCUSSION THREAD

**Discussion by gamerslouis** [open-telemetry/opentelemetry-collector-contrib#37200] [Q&A]
Hi all,

**Context**

opentelemetry-operator: 0.114.1
opentelemetry-collector: 0.114.1
autoinstrumentation-python: 0.48b0

**Description**
I am integrating OpenTelemetry into our environment and encountered an issue while using the tail sampling processor with a "force accept" policy. Following the example provided in the [tail sampling documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor), I configured the policy as follows:

```yaml
- name: force-sample
  type: boolean_attribute
  boolean_attribute: { key: app.force_sample, value: true }
```
To test this configuration, I deployed a Python FastAPI server in a Kubernetes pod with OpenTelemetry auto-instrumentation enabled via the operator. I also set the OTEL_RESOURCE_ATTRIBUTES environment variable to:
app.force_sample=true

However, this setup did not work as expected. The OpenTelemetry instrumentation treats the value "true" as a string. Referring to the [tail sampling library documentation](https://pkg.go.dev/go.opentelemetry.io/collector/pdata/pcommon#Value.Bool), this results in the boolean value being interpreted as false.

To address this issue and allow the policy to work with both environment variable inputs and SDK settings, I implemented the following workaround by adding two policy rules for different value types:

```yaml
- name: force-sample-str
  type: string_attribute
  string_attribute: { key: app.force_sample, values: ["true"] }
- name: force-sample
  type: boolean_attribute
  boolean_attribute: { key: app.force_sample, value: true }
```

**Questions**
+ Is this the recommended approach to handle such cases, or is there a better configuration available?
+ Would it be possible to improve the way OpenTelemetry instrumentation/collector handles boolean values from environment variables? Should this be considered a bug or a potential enhancement?
