### DISCUSSION TITLE
How to extract env OTEL_RESOURCE_ATTRIBUTS from pod when using redisreceiver

### DISCUSSION THREAD

**Discussion by sswieton** [open-telemetry/opentelemetry-collector-contrib#37433] [Q&A]
Hi,

My environment is deployed on Kubernetes.
Version : Chart Helm opentelemetry-collector-0.111.1    app Version : 0.115.1

I would like to collect metrics from a Redis database and enrich the labels using environment variables defined in the Redis containers. 
In the Redis containers, the env  OTEL_RESOURCE_ATTRIBUTES="myenv=redis" is defined

**My configuration is as follows:** 

I am using the Redis receiver
```
receivers:
    redis:
      endpoint: "redis-otlp-tcp:6379"
      collection_interval: 10s
      password: pwd
      username: user
```

In the processors, I use the environment and system detectors.

```
    resourcedetection:
      detectors: [env,system]
      timeout: 2s
      override: false
```

My pipeline

```
    pipelines:
      metrics:
        receivers:
          - redis
        processors:
          - resourcedetection
          - batch
        exporters: 
          - debug/verbose
```

**Issues** 

In the Resource Attributes, **I can only get information related to the system, not the env**
 Maybe my configuration is incorrect or incomplete

Thanks for your support

```
Resource SchemaURL: https://opentelemetry.io/schemas/1.6.1
Resource attributes:
     -> redis.version: Str(7.2.5)
     -> host.name: Str(otel-collector-sandbox-7bb68868c7-6g884)
     -> os.type: Str(linux)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver 0.115.0
Metric #0
```
