### DISCUSSION TITLE
Explicitly set a log timestamp in transform processor

### DISCUSSION THREAD

**Discussion by ReyJust** [open-telemetry/opentelemetry-collector-contrib#37502] [Q&A]
Hello,
Currently using sqlqueryreceiver with an Oracle DB to get some logs. Trying to explicitly set log timestamps in the transform processors. But without success. I tried:
 ```yaml
   transform:
    log_statements:
      - context: log
        statements:
          - set(time, attributes["MESSAGE_TIMESTAMP"])
          # OR - set(observed_time, attributes["MESSAGE_TIMESTAMP"])
          # OR - set(observed_time_unix_nano, attributes["MESSAGE_TIMESTAMP"])
  ```
  
  Maybe the issue is the format of the data itself? It look like this:
  `2025-01-12T12:20:40.894842Z`
  
  And I also tried as an epoch ts with nano precision.
  My receiver:
  ```yaml
  sqlquery:
  [...]
    queries:
      - sql: |
          SELECT
            ADM.ID,
            LOWER(REPLACE(AA.APPLICATION_NAME, ' ', '_')) AS APPLICATION_NAME,
            COALESCE(ADM.MESSAGE, 'N/A') AS MESSAGE,
            COALESCE(ADM.SESSION_ID, -1) AS SESSION_ID,
            COALESCE(ADM.MESSAGE_LEVEL, 0) AS MESSAGE_LEVEL,
            COALESCE(ADM.APEX_USER, 'N/A') AS APEX_USER,
           COALESCE(ADM.MESSAGE_TIMESTAMP, TO_DATE('1970-01-01', 'YYYY-MM-DD')) AS MESSAGE_TIMESTAMP,
           -- OR  (CAST(ADM.MESSAGE_TIMESTAMP AS DATE) - CAST(to_date('1-1-1970 00:00:00', 'MM-DD-YYYY HH24:MI:SS') AS DATE)) * 
           86400 * 1000000000 AS MESSAGE_TIMESTAMP,
            COALESCE(ADM.APPLICATION_ID, -1) AS APPLICATION_ID,
            COALESCE(ADM.PAGE_VIEW_ID, -1) AS PAGE_VIEW_ID,
            COALESCE(ADM.PAGE_ID, -1) AS PAGE_ID,
            COALESCE(ADM.ELAPSED_TIME, -1) AS ELAPSED_TIME,
            COALESCE(ADM.EXECUTION_TIME, -1) AS EXECUTION_TIME,
            COALESCE(ADM.WORKFLOW_INSTANCE_ID, -1) AS WORKFLOW_INSTANCE_ID
          FROM 
            APEX_DEBUG_MESSAGES ADM
          JOIN 
              APEX_APPLICATIONS AA ON ADM.APPLICATION_ID = AA.APPLICATION_ID
          WHERE 
            ADM.ID > :1
          ORDER BY 
            ADM.ID ASC
          FETCH FIRST 1000 ROWS ONLY
      tracking_start_value: "1"
      tracking_column: ID
      logs:
         - body_column: MESSAGE
            attribute_columns: ["ID", "APPLICATION_NAME", "SESSION_ID", "MESSAGE_LEVEL", "APEX_USER", "MESSAGE_TIMESTAMP", "APPLICATION_ID", "PAGE_VIEW_ID", "PAGE_ID", "ELAPSED_TIME", "EXECUTION_TIME", "WORKFLOW_INSTANCE_ID"]
  ```
Currently verifying if it's work by exploring Logs timestamp in Grafana Loki. Currently, every logs get the current time, the one when the logs get's processed by the collector.

Thanks for any help!
Justin

**Comment by ReyJust** [comment]
Got it! I just needed `Int()`.... 

```yaml
  transform:
   log_statements:
     - context: log
       statements:
         - set(observed_time_unix_nano, Int(attributes["MESSAGE_TIMESTAMP"]))
 ```
 
 Credits to: 
https://stackoverflow.com/a/76908945/18036486
