### DISCUSSION TITLE
Is there any way to copy resource attributes to data point attributes?

### DISCUSSION THREAD

**Discussion by zongsizhang** [open-telemetry/opentelemetry-collector-contrib#37868] [Q&A]
We are sending metrics to the Grafana cloud through OTLP. Prometheus drops our resource attributes.
Is there any way to copy the resource attributes to the data point attributes?

Appreciate!

**Comment by edmocosta** [comment]
I think the [transformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) can help on that:

```yaml
processors:
  transform/copy_resource_attributes:
    metric_statements:
      - context: datapoint
        statements:
          - merge_maps(attributes, resource.attributes, "insert")
```

**Reply by carterd** [reply]
Maybe transform: statements: set will also work if you want to have more control on mappings.
```
processors:
  transform/copy_resource_attributes:
    metric_statements:
      - context: datapoint
        statements:
            - set(attributes["host_name"], resource.attributes["host.name"])
            - set(attributes["label_something"], resource.attributes["something.else"])
```
