### DISCUSSION TITLE
How to create metrics from logs?

### DISCUSSION THREAD

**Discussion by DimiDr0l** [open-telemetry/opentelemetry-collector-contrib#38449] [Q&A]
let's say I have a log like this:
```
2025-03-07T12:21:37.950854+03:00 hostname sshd[3313]: pam_unix(sshd:session): session opened for user username(uid=1000) by username(uid=0)
2025-03-07T12:23:36.365996+03:00 hostname sshd[3313]: pam_unix(sshd:session): session closed for user username
```
I want to get metrics like this
```
user_sessions_opened_total{user="{user}"} 1
user_sessions_closed_total{user="{user}"} 0
```
how can this be done?
receiver:
```yaml
filelog/auth:
  include:
    - /var/log/auth.log
  operators:
    - type: regex_parser
      regex: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}).+\s(?P<hostname>\S+)\s+(?P<appname>[\w-]+)(?:\[\d+\])?:\s(?P<message>.+)$'
      timestamp:
        parse_from: attributes.timestamp
        layout: "%FT%T"
    - type: regex_parser
      parse_from: attributes.message
      regex: '.*session\s(?P<session>\w+)\sfor\suser\s(?P<user>\w+).*'
      if: 'attributes.message matches ".*session (opened|closed).*"'
```
how to do this [vector](https://vector.dev/docs/reference/configuration/transforms/log_to_metric/)
