### DISCUSSION TITLE
How to create label from resource attribute?

### DISCUSSION THREAD

**Discussion by clawoflight** [open-telemetry/opentelemetry-collector-contrib#38531] [Q&A]
I would like to set a label on metrics based on a resource attribute, for easy filtering later.
How can I achieve that? I tried the following, but it sets the literal string as the value:

```yml
  metricstransform/attribute_labels:
    transforms:
      - include: .*
        match_type: regexp
        action: update
        experimental_match_labels: {"resource.my.attribute ".*"}
        operations:
          - action: add_label
            new_label: my.attribute
            new_value: resource.my.attribute
```

Any ideas? I am probably only missing some syntax to dereference the attribute in new_value?
