### DISCUSSION TITLE
debug if not sending logs?

### DISCUSSION THREAD

**Discussion by juju4** [open-telemetry/opentelemetry-collector-contrib#38659] [Q&A] [answered]
How to troubleshoot when a log (file in my case) does not seem to be sent to upstream?
I have "Started watching file" in otel-collector journalctl but nothing on receiving server.

I tried adding to exporter settings following but does not getting much more
```
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

```

only error level message is `error        journald/input.go:107        journalctl command exited        {"kind": "receiver", "name": "journald", "data_type": "logs", "operator_id": "journald_input", "operator_type": "journald_input", "error": "signal: terminated", "output": ""}` which is likely unrelated

otelcol-contrib version is 0.111.0 on linux ubuntu 22.04.
I have logs file and journald that are sending data.

**Comment by juju4** [comment]
tried adding a local file exporter but not getting anything
```
exporters:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/fileexporter/README.md
  file/debug:
    path: /tmp/otel-debug.log
    rotation:
      max_megabytes: 10
      max_days: 3
      max_backups: 3
      localtime: false
    format: json
    # compression: zstd
[...]

service:
[...]
    logs/journald:
      receivers: [journald]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve_journald, file/debug]
[...]
```
