### DISCUSSION TITLE
How to enable the optional metrics of hostmetrics receiver?

### DISCUSSION THREAD

**Discussion by albertoakg** [open-telemetry/opentelemetry-collector-contrib#40077] [Q&A]
Hello,
I activated the hostmetrics receiver, but I cannot enable the optional metrics (like system.cpu.utilization):

```
receivers:
  hostmetrics:
    scrapers:
      cpu:
        metrics:
          system.cpu.time:
            enabled: true
          system.cpu.logical.count:
            enabled: true
          system.cpu.physical.count:
            enabled: true
          system.cpu.utilization:
            enabled: true
      memory:
      paging:
      processes:
      system:
``` 

What's wrong? Is it possible to enable the optional metrics from the config yaml?

Regards

**Comment by albertoakg** [comment]
I think I have found the correct config:

```
receivers:
  hostmetrics:
    scrapers:
      cpu:
        metrics:
          system.cpu.time:
            enabled: true
          system.cpu.logical.count:
            enabled: true
          system.cpu.physical.count:
            enabled: true
          system.cpu.utilization:
            enabled: true
```
