### DISCUSSION TITLE
What is the point of the `output` attribute of a stanza/operator?

### DISCUSSION THREAD

**Discussion by ChristianCiach** [open-telemetry/opentelemetry-collector-contrib#40810] [Q&A] [answered]
The filelog README says:

> Operators will output to the next operator in the pipeline. The last operator in the pipeline will emit from the receiver. Optionally, the `output` parameter can be used to specify the `id` of another operator to which logs will be passed directly.

What's the point? Since the `output` value cannot be an evaluated expression (I think), this `output` attribute can only be used to skip certain operators unconditionally. At this point, I could also just remove/comment the operators I want to skip. Or is there some use-case I am missing?

As far as I know, the only way to *conditionally* skip operators is to use the `router` operator.

**Comment by ChristianCiach** [comment]
I found the documentation that contains the necessary information: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.128.0/pkg/stanza/docs/types/operators.md#non-linear-sequences

So I was half-right: To construct conditional operator-sequences, you *have* to use the `router` operator. But the `output` attribute of an operator is still useful for operators that are themselves only executed conditionally as a router target, in cases where you want to *break out* of a branch, similar to the `break` keyword for switch-cases in most programming languages.

**Reply by ChristianCiach** [reply]
This also means that the `output` attribute is not even strictly necessary. I guess this example from the docs...

```yaml
receivers:
  filelog:
    include: my-log.json
    operators:
      - type: router
        routes:
          - expr: 'body matches "^{.*}$"'
            output: json_parser
          - expr: 'body startsWith "ERROR"'
            output: error_parser
      - type: json_parser
        output: remove # send from here directly to the 'remove' operator
      - type: regex_parser
        id: error_parser
        regex: ... # regex appropriate to parsing error logs
      - type: remove
        field: attributes.foo
      - type: add
        key: attributes.bar
        value: baz
```

could be rewritten like this:

```yaml
receivers:
  filelog:
    include: my-log.json
    operators:
      - type: router
        routes:
          - expr: 'body matches "^{.*}$"'
            output: json_parser
          - expr: 'body startsWith "ERROR"'
            output: error_parser
      - type: json_parser
      - type: router
        id: poor-mans-output-hack
        routes: []
        default: remove
      - type: regex_parser
        id: error_parser
        regex: ... # regex appropriate to parsing error logs
      - type: remove
        field: attributes.foo
      - type: add
        key: attributes.bar
        value: baz
```

Of course, this is ugly and I am glad we don't have to do that. But it still shows that we *could* do without the `output` field in the operator struct.
