### DISCUSSION TITLE
Tail sampling policy min_value and max_value required?

### DISCUSSION THREAD

**Discussion by gpcmol** [open-telemetry/opentelemetry-collector-contrib#40918] [Q&A]
Consider this configuration:

```
      tail_sampling:
        decision_wait: 10s
        num_traces: 100000
        expected_new_traces_per_sec: 10000
        policies:
          - name: trace-status-policy
            type: status_code
            status_code:
              status_codes: ["ERROR"]
          - name: rest_traces
            type: probabilistic
            probabilistic:
              sampling_percentage: 1.0
```

As I expect (using telemetrygen) I get 100 traces in (in this case) Jaeger:
telemetrygen traces --otlp-http --otlp-endpoint "172.18.0.6:4318" --child-spans 5 --otlp-insecure --status-code 1 --traces 100
For the following configuration I also expect 100 traces in Jaeger, but get only 1 (=1%). It seems that it only hits the probabilistic policy
telemetrygen traces --otlp-http --otlp-endpoint "172.18.0.6:4318" --child-spans 5 --otlp-insecure --status-code 0 --telemetry-attributes http.response.status_code=500 --traces 100

```
      tail_sampling:
        decision_wait: 10s
        num_traces: 100000
        expected_new_traces_per_sec: 10000
        policies:
          - name: http_status_400_or_higher
            type: numeric_attribute
            numeric_attribute:
              key: http.response.status_code
              min_value: 400
          - name: rest_traces
            type: probabilistic
            probabilistic:
              sampling_percentage: 1.0
```

When I change the numeric_attribute policy to this, it works as expected:
```
          - name: http_status_400_or_higher
            type: numeric_attribute
            numeric_attribute:
              key: http.response.status_code
              min_value: 400
              max_value: 500
```

I still don't understand why I have to set the max_value, considering how it is implemented in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/internal/sampling/numeric_tag_filter.go (line 26-28 has clear explanation)

Anyone an idea?
