### DISCUSSION TITLE
How to use k8s processor

### DISCUSSION THREAD

**Discussion by sumitm-iiit** [open-telemetry/opentelemetry-collector-contrib#4772] [Q&A]
I am trying to use k8s processor to get the metadata about kubernetes environment as part of span resource attributes.
I have configured agent collector to use k8s processor but I am not seeing any k8s resource attributes as part of span.
I am also attaching the yaml that I am using to deploy collector (agent and gateway).
Any help on this would be great.

Thanks,
Sumit
[otel-config.txt](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/7023381/otel-config.txt)

**Comment by SubhadeepSen** [comment]
Hi @sumitm-iiit 
your otel-agent-config has two k8s taggers, k8s_tagger and k8s_tagger/2. The processors is using k8s_tagger where you have defined k8s tagger configuration in k8s_tagger/2.

 ``` yaml
k8s_tagger:
k8s_tagger/2:
  passthrough: false
  auth_type: "kubeConfig"
```

 ``` yaml
pipelines:
  traces:
    receivers: [otlp]
    processors: [memory_limiter, batch, k8s_tagger]
    exporters: [otlp]
```

would you like to give a try with the attached otel-config.

[otel-config.txt](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/7375657/otel-config.txt)
