### DISCUSSION TITLE
Configuring a InfluxDB Receiver

### DISCUSSION THREAD

**Discussion by perrinj3** [open-telemetry/opentelemetry-collector-contrib#5269] [Q&A] [answered]
I'm trying to configure an influxdb receiver for the Otel Collector but not clear what else I need to specify in the config. Ultimately I want to receive metrics from InfluxDB and export them to Splunk. Initially I am exporting to a file for testing purposes but get no output with the following config. The collector starts without any errors. I've looked at the documentation and examples but it's not clear what the next steps should be.
To be clear my question is around the configuration for the influxdb receiver. I'd expect to have to include more than just the endpoint. eg what bucket to use and what username password to use but the readme only talks about the endpoint. 
Thanks
```
receivers:
  influxdb:
    endpoint: "localhost:8086"
      
exporters:
  splunk_hec:
    # Splunk HTTP Event Collector token.
    token: "remove for security"
    # URL to a Splunk instance to send data to.
    endpoint: "http://hostname:8088/services/collector"
    # Optional Splunk source: https://docs.splunk.com/Splexicon:Source
    source: "otel"
    # Optional Splunk source type: https://docs.splunk.com/Splexicon:Sourcetype
    sourcetype: "otel"
    # Splunk index, optional name of the Splunk index targeted.
    index: "au_cpe_common_app"
    # Maximum HTTP connections to use simultaneously when sending data. Defaults to 100.
    max_connections: 20
    # Whether to disable gzip compression over HTTP. Defaults to false.
    disable_compression: false
    # HTTP timeout when sending data. Defaults to 10s.
    timeout: 10s
    # Whether to skip checking the certificate of the HEC endpoint when sending data over HTTPS. Defaults to false.
    # For this demo, we use a self-signed certificate on the Splunk docker instance, so this flag is set to true.
  file:
    path: ./test2.json 
service:
  pipelines:
   # logs:
   #  receivers: [filelog]
    # exporters: [file]
   metrics:
     receivers: [influxdb]
     exporters: [file]
     #traces:
```

**Comment by tigrannajaryan** [comment]
@jacobmarble is there any way that you can recommend to debug this on the influxdb side? It appears that the receiver does not receive anything (otherwise Collector it would be visible in the output of the `file` exporter).

@perrinj3 Meta: use [code blocks](https://github.github.com/gfm/#fenced-code-blocks) to make the config that you posted readable.

**Reply by jacobmarble** [reply]
Thanks Tigran. @perrinj3 I'll look into this today. Someone else recently asked about a similar problem, and I wonder if my integration tests aren't working properly.

**Comment by jacobmarble** [comment]
@perrinj3 what version of otel-collector-contrib are you using?

I have not considered user/pass/org/bucket configs in this receiver. If that's a requirement for you, then it can probably be added without too much trouble.

Please try this docker compose. It uses otel-collector-contrib version 0.35.0 configured to receive InfluxDB Line Protocol, and exports to STDOUT.

If this works for you, then you should be able to troubleshoot in the Splunk exporter next.

docker-compose.yml:
```yaml
services:

  generate-metrics:
    # https://github.com/open-fresh/avalanche
    # Prometheus metrics at http://localhost:9090/metrics
    image: quay.io/freshtracks.io/avalanche:latest
    command: --port 9090 --value-interval=9 --series-interval=600 --metric-interval=3600
    stop_grace_period: 1s
    links:
    - telegraf

  telegraf:
    # Configuration in telegraf.toml
    image: telegraf:1.20-alpine
    volumes:
    - ./telegraf.toml:/etc/telegraf/telegraf.conf:ro
    links:
    - opentelemetry-collector

  opentelemetry-collector:
    # Configuration in otelcol.yml
    image: otel/opentelemetry-collector-contrib:0.35.0
    command: /otelcolcontrib --config /config.yaml --log-level INFO
    stop_grace_period: 1s
    volumes:
    - ./otelcol.yml:/config.yaml:ro
```

otelcol.yml:
```yaml
receivers:
  influxdb:
    endpoint: 0.0.0.0:8086

processors:

exporters:
  file:
    path: /dev/stdout

extensions:

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [influxdb]
      processors: []
      exporters: [file]
```

telegraf.toml:
```toml
[[inputs.prometheus]]
urls = ["http://generate-metrics:9090/metrics"]
metric_version = 1

[[outputs.influxdb_v2]]
urls = ["http://opentelemetry-collector:8086"]
organization = "my-org"
bucket = "my-bucket"
```

**Comment by perrinj3** [comment]
Hi Jacob
I was running 0.34.0 but upgraded to 0.35.0 after you asked about this.
At this stage we don’t require user/pass/org/bucket configs in this receiver but it may be needed in the future. I believe that Influxdb 2.0 makes authentication mandatory so I think it would be needed then. We are running currently influxdb 1.8 to avoid the authentication issues
It would make sense to be able to filter what data is received from Influxdb but at this stage we are just evaluating OpenTelemetry’s capabilities and I just wanted to know if there were any other config options.
The evaluation setup is running K6, grafana, InfluxDb and the otel-collector-contrib on a single Windows 2012 server. I installed otel using the msi so the collector is running as a Windows Service.
K6 writes to Influxdb and the otel collector is configured to receive from Influxdb and export to Splunk which is running on a separate Windows server.

What I have found is that if the otel collector service is running and connected to InfluxDb then k6 can’t write to InfluxDb.  Grafana can’t connect either.
However I’ve found that if I follow the below sequence data eventually finds its way into Splunk.


1.      Stop the otel collector service

2.      Run k6 test to feed data into Influxdb

3.      Stop k6 test and start the otel collector service
It’s not very consistent though and it can take some time for the data to appear.

Any thoughts on what it might be/

Regards
John

**Reply by jacobmarble** [reply]
I am not familiar with K6, and my only thought on the workaround is that perhaps one of the processes opens a port, and another tries to open the same port? I like to test these things in a Docker Compose because it makes it easier to reproduce the problem, for oneself, and for others.

Regarding InfluxDB 2.0 compatibility, I had not implemented those user/pass/org/bucket details because most people asking about the plugin were planning to write to Telegraf. Clearly, that needs to be rectified.

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5321

**Comment by perrinj3** [comment]
I’ve done some more investigation and found the following.

·         I start Influxdb and it listens on the default port 8086

·         I then try to start an opentelemetry collector with following receiver defined
receivers:
 influxdb:
    endPoint: "0.0.0.0:8086"

The opencollector fails with message

cannot start receivers: failed to bind to address 0.0.0.0:8086: listen tcp 0.0.0.0:8086: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

What is wrong with this please? I’ve looked at the readme and don’t understand why the OpenTel collector is trying to listen to port 8086 which Influxdb is already listening on.
How is Opebtel meant to receive from Influxdb?

Thanks

**Reply by jacobmarble** [reply]
John-

Yes, if you run two processes (OpenTelemetry Collector and InfluxDB) listening on the same port (8086), then only one process can open the port.

In your original post, you said:
> Ultimately I want to receive metrics from InfluxDB and export them to Splunk.

And the config in your original post contains:
```yaml
receivers:
  influxdb:
    endpoint: "localhost:8086"
```

When you say you want to "receive metrics from InfluxDB", what exactly do you mean? InfluxDB emits a few internal metrics via a Prometheus metrics HTTP endpoint, but it is a used as a service which receives and stores metrics.

If you mean "receive metrics via InfluxDB Line Protocol" then don't run InfluxDB. You'll be able to write InfluxDB Line Protocol to port 8086 (OpenTelemetry Collector), and watch the metrics appear in whatever exporter you configure.


Again, simplify your test environment. The docker compose config I posted is intended to do that. If you have some question about my earlier response, then please provide feedback, but it feels like it was ignored.
