### DISCUSSION TITLE
[filter processor] Filter on a resource_attribute or on a datapoint label

### DISCUSSION THREAD

**Discussion by ransoor2** [open-telemetry/opentelemetry-collector-contrib#7244] [Q&A] [answered]
Hello, we have a usecase where we expect all metrics to contain a `service` tag.
In the otel-collector agent we need to support both `statsd` and `OTLP` receivers.
The issue begins that `statsd` does not support resource attributes, therefore all tags will be added as labels to the datapoint. 
What we're trying to achieve in the filter processor is to include all metrics who either contain a resource attribute tag `service`, or a datapoint with label of `service`
Seem's like its possible to filter only on one of the conditions but not both of them.
Separately, the filters look like this

``` yaml
filter/metric_label:
    metrics:
      include:
        match_type: expr
        expressions:
          - HasLabel("service")
        resource_attributes:
filter/metric_resource:
  metrics:
    include:
      match_type: regexp
      resource_attributes:
        - Key: service
          Value: ".*"
```

**Comment by mskhan-devops** [comment]
Hi,
I saw this question which is similar to one of my own questions. I think you are able to use `resource_attributes` to filter out the metrics/logs whereas I am unable to implement Filter Procesor along with `resource_attributes` to further filter out metrics of my EKS Cluster.

Could you please go through my question below and help me out with what I am missing:

[Unable to Filter Metrics Using Resource Attributes - resource_attributes #4887
](https://github.com/open-telemetry/opentelemetry-collector/discussions/4887)

I am sorry I am asking my own question instead of answering your question. I hope you don't mind.

Thanks

**Reply by ransoor2** [reply]
@mskhan-devops Add a logging exporter to your collector and see if the tags you're trying to filter are on the resource level or data points level. When you'll know you will be able to filter with one of the above configurations

**Reply by mskhan-devops** [reply]
Sure, let me add that logging to the exporters to identify the resources or data level points.

Thank you for the response.

**Reply by mskhan-devops** [reply]
@ransoor2 ,

After adding debug level logging to the exporter, I have shared the generated logs. Please look at the following link and let me know what you think:

https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/8106

**Comment by pmm-sumo** [comment, marked as answer]
For `statsd` this can be achieved with [groupbyattrs](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor) processor. It can move record-level attributes to resource, e.g.:

```yaml
processors:
  groupbyattrs:
    keys:
      - service.name
```
