### DISCUSSION TITLE
"TRANSIENT_FAILURE" error for Jaeger exporter

### DISCUSSION THREAD

**Discussion by ardacetinkaya** [open-telemetry/opentelemetry-collector-contrib#9162] [Q&A] [answered]
I am trying to use OpenTelemetry Collector to export my application trace logs to Jaeger, I am trying to use OTLP protocol and my application uses OTLP endpoint.

My otlp configuration is as following;

```yaml
receivers:
  otlp:
    protocols:
      grpc:


exporters:
  jaeger:
    endpoint: localhost:6831
    tls:
      insecure: true

  logging:

  file:
    path: /etc/output/logs.json


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,file,jaeger]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging, file]

```

So when I run my application, trace logs can not be passed into jaeger and when I check the console logs of OpenTelemetry Collector

> [core] grpc: addrConn.createTransport failed to connect to {localhost:6831 localhost:6831 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:6831: connect: connection refused" {"grpc_log": true}
2022-04-11T17:47:41.760Z info jaegerexporter@v0.48.0/exporter.go:186 State of the connection with the Jaeger Collector backend {"kind": "exporter", "name": "jaeger", "state": "TRANSIENT_FAILURE"}

And when I check Jaeger logs there is nothing specific. And also if I don't use OpenTelemetry Collector, my trace logs can easily passed into Jaeger with same endpoint.

I am new to OpenTelemetry Collector topic maybe I am missing something. Any help would be great. 🙏

And by the way, I am able to export trace logs into a file.
