### DISCUSSION TITLE
Is there a way to refresh the Prometheus exporter endpoint more frequently?

### DISCUSSION THREAD

**Discussion by hannahchan** [open-telemetry/opentelemetry-collector-contrib#9788] [Q&A]
Hi,

I'm currently exporting metrics from my application via OTLP to an OpenTelemetry collector. On the OpenTelemetry collector I am using the Prometheus exporter to expose a `/metrics` endpoint on the collector. Is there a way to get this endpoint to update with the latest metrics every time I call it or more frequently like every 10 seconds or less? I am already using the `Simple` OTLP exporter in my app instead of batch. I am also not using the batch processor in my metrics pipeline on the OpenTelemetry collector.

My OpenTelemetry collector's configuration is below.

```yaml
---
extensions: ~
receivers:
  otlp:
    protocols:
      grpc: ~
processors:
  batch: ~
exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8081"
service:
  extensions: []
  pipelines:
    metrics:
      exporters: [prometheus]
      processors: []
      receivers: [otlp]
    traces:
      exporters: [jaeger]
      processors: [batch]
      receivers: [otlp]
```

This is important to me as it slows down my dev loop. If I switch to using the OpenTelemetry exporter in my app, it updates nearly instantaneously. My traces seem to also flow through to my Jaeger backend faster than the metrics can update.
