### DISCUSSION TITLE
OTLP elastic exporter with username and password

### DISCUSSION THREAD

**Discussion by manu-balakrishnan** [open-telemetry/opentelemetry-collector-contrib#9890] [Q&A]
Hi,
    Is there any way to export opentelemetry traces to elasticsearch using otlp exporter by providing username and password of ES along with hostname:port in otel collector config ?

here is the docker compose yaml and otel collector config yaml:

```
version: "2"

    
services:


  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output:/etc/output:rw # Store the logs
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver


    
  jaeger-query:
    image: jaegertracing/jaeger-query
    command: ["--es.server-urls= <ES DNS URL> ", "--es.username=elastic","--es.password=<Password>"]
    ports:
      - "16686:16686"
      - "16687"
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - LOG_LEVEL=debug
    restart: on-failure
```

```
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp/elastic:
    endpoint: "<hostname:port>"


processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/elastic]
      processors: [batch]
```
