### ISSUE TITLE
 unknown processors type "k8s_tagger" for "k8s_tagger" 

### ISSUE THREAD

**Issue by govindarajvenkatesan** [open-telemetry/opentelemetry-collector-contrib#10008]
**Describe the bug**
Seeing error  unknown processors type "k8s_tagger" for "k8s_tagger" while doing apply for opentelemetry-collector-contrib v0.50.0
```
Error: failed to get config: cannot unmarshal the configuration: unknown processors type "k8s_tagger" for "k8s_tagger" (valid values: [memory_limiter deltatorate groupbyattrs resourcedetection resource batch cumulativetodelta experimental_metricsgeneration tail_sampling attributes groupbytrace metricstransform probabilistic_sampler routing filter k8sattributes spanmetrics span])
2022/05/12 14:49:38 collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown processors type "k8s_tagger" for "k8s_tagger" (valid values: [memory_limiter deltatorate groupbyattrs resourcedetection resource batch cumulativetodelta experimental_metricsgeneration tail_sampling attributes groupbytrace metricstransform probabilistic_sampler routing filter k8sattributes spanmetrics span])
```

**Steps to reproduce**
opentelemetry-collector-contrib:0.50.0

```
    processors:
      batch:
        timeout: 10s
      memory_limiter:
        check_interval: 5s
        # 80% of maximum memory up to 2G
        limit_mib: 1336
        # 25% of limit
        spike_limit_mib: 341
      resourcedetection:
        detectors: [env]
        timeout: 5s
        override: false
      k8s_tagger:
        passthrough: true
        
  service:
      extensions:
        - memory_ballast
        - health_check
      pipelines:
        traces/1:
          receivers: [otlp,zipkin]
          processors:
            - memory_limiter
            - resourcedetection
            - k8s_tagger
            - batch
          exporters: [datadog]

```      

**What did you expect to see?**
Expect collector pods to be up and running

**What did you see instead?**
Error as posted above while doing kubectl apply 

**What version did you use?**
opentelemetry-collector-contrib:0.50.0

**What config did you use?**
```
    processors:
      batch:
        timeout: 10s
      memory_limiter:
        check_interval: 5s
        # 80% of maximum memory up to 2G
        limit_mib: 1336
        # 25% of limit
        spike_limit_mib: 341
      resourcedetection:
        detectors: [env]
        timeout: 5s
        override: false
      k8s_tagger:
        passthrough: true
        
  service:
      extensions:
        - memory_ballast
        - health_check
      pipelines:
        traces/1:
          receivers: [otlp,zipkin]
          processors:
            - memory_limiter
            - resourcedetection
            - k8s_tagger
            - batch
          exporters: [datadog]

```
