### ISSUE TITLE
prometheusremotewrite doesn't honor all resource attributes

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#10023]
**Is your feature request related to a problem? Please describe.**
The scenario is scraping cadvisor metrics, enrich them via `k8sattrs` processor based on certain metric labels, so eventually metrics could have additional labels e.g. deployment name, any interested labels and/or annotations.

As currently `k8sattrs` processor only supports pod association from resource attributes, `groupbyattrs` processor was used first in order to move attributes of a metric(e.g. `namespace` and `pod`) to resource attributes, this is working but currently only [a few](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.51.0/pkg/translator/prometheusremotewrite/helper.go#L201-L218) specific resource attributes are used/extracted by `prometheusremotewrite` exporter.

**Describe the solution you'd like**
Support additional resource attributes in `prometheusremotewrite` exporter. As label convention in prometheus is different than open telemetry, resource attribute names may need to be sanitized, or updated by a processor as proposed in #9994. 

**Describe alternatives you've considered**
Support pod association from attribute of a metric, log, span in `k8sattrs` processor.

**Additional context**
Sample config
```yaml
    processors:
      batch:
      groupbyattrs:
        keys:
          - namespace
          - pod
      resource/copy:
        attributes:
          - key: k8s.namespace.name
            from_attribute: namespace
            action: insert
          - key: k8s.pod.name
            from_attribute: pod
            action: insert
      k8sattributes:
        auth_type: kubeConfig
        passthrough: false
        extract:
          metadata:
          labels:
            - key_regex: (.*)
              tag_name: $$0
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.namespace.name
              - from: resource_attribute
                name: k8s.pod.name
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch, groupbyattrs, resource/copy, k8sattributes]
          exporters: [ prometheusremotewrite ]
```
