### ISSUE TITLE
[Prometheus Remote Write Exporter] Forward metrics labels

### ISSUE THREAD

**Issue by clouedoc** [open-telemetry/opentelemetry-collector-contrib#10115]
**Is your feature request related to a problem? Please describe.**
I want to be able to cluster my metrics by host in Prometheus.
On Prometheus' side, I do not get a `host` label to select:

![image](https://user-images.githubusercontent.com/13921610/168844374-eb639319-b7fa-48c5-864c-35efadf69d19.png)

I only get a `job` tag.

Previously, by using Datadog and the `otlp` exporter, I could aggregate metrics by host name, deployment version, etc.
I believe that OTLP tags are not getting forwarded because of the Prometheus Remote Write exporter.

**Describe the solution you'd like**
I want to get the following labels to be forwarded to Prometheus:

- `service.name`
- `deployment.environment`
- `service.version`

These will allow me to see if a specific version of my program is using more memory, and when.

**Describe alternatives you've considered**

- using an official Prometheus Go client

**Additional context**

Here is my configuration:

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:8080
      grpc:
        endpoint: 0.0.0.0:4040

exporters:
  logging:

  # Data sources: traces, metrics
  # On-premise endpoint
  otlphttp:
    endpoint: XXX

  otlp/grafana-cloud-tempo:
    endpoint: tempo-us-central1.grafana.net:443
    headers:
      authorization: XXX
  prometheusremotewrite/grafana-cloud:
    endpoint: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    headers:
      authorization: XXX
processors:
  batch:
    timeout: 10s

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp, otlp/grafana-cloud-tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp, prometheusremotewrite/grafana-cloud]
```
