### ISSUE TITLE
[receiver/filelogreceiver] Filelogreceiver doesn't read from file in case there are two or more empty lines at the beginning

### ISSUE THREAD

**Issue by perk** [open-telemetry/opentelemetry-collector-contrib#10128]
**Describe the bug**
Filelogreceiver doesn't read from file in case there are two or more empty lines at the beginning when the `start_at: beginning` is used.

**Steps to reproduce**
Create the following `logs.txt` file to read the data from:
```


three
four
five
```

Apply the following configuration:
```
receivers:
  filelog:
    include:
    - ./logs.txt
    start_at: beginning

exporters:
  logging:

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

Run the otelcol:
```
./otelcol-contrib --config config.yaml
```

See the following lines:
```
2022-05-18T14:16:59.785+0200	info	service/collector.go:146	Everything is ready. Begin running and processing data.
2022-05-18T14:16:59.988+0200	info	file/file.go:174	Started watching file	{"kind": "receiver", "name": "filelog", "operator_id": "file_input", "operator_type": "file_input", "path": "logs.txt"}
```

Try to add anything into the file:
```
echo six >> logs.txt
echo seven >> logs.txt
```

Nothing happens at this point, file is not being read.

**What did you expect to see?**
I'd expect to see all the logs - old a new ones - collected.

**What did you see instead?**
Collector doesn't receive the data from the file at all.

**What version did you use?**
`0.51.0`

**What config did you use?**
```
receivers:
  filelog:
    include:
    - ./logs.txt
    start_at: beginning

exporters:
  logging:

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

**Environment**
OS: Ubuntu 20.04, MacOS 12.3.1
