### ISSUE TITLE
Filelogreceiver reads the same file in the loop in case there is an empty line between logs

### ISSUE THREAD

**Issue by perk** [open-telemetry/opentelemetry-collector-contrib#10125]
**Describe the bug**
Filelogreceiver reads the same file in the loop in case there is an empty line between logs

**Steps to reproduce**
Create the following `logs.txt` file to read the data from:
```
one

three
```

Apply the following configuration:
```
receivers:
  filelog:
    include:
    - ./logs.txt
    start_at: beginning

exporters:
  logging:

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

Run the otelcol:
```
./otelcol-contrib --config config.yaml
```

**What did you expect to see?**
I'd expect the file to be read only once per otelcol run.

**What did you see instead?**
The file is read constantly from the beginning in a loop.

**What version did you use?**
`0.51.0`

**What config did you use?**
```
receivers:
  filelog:
    include:
    - ./logs.txt
    start_at: beginning

exporters:
  logging:

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

**Environment**
OS: Ubuntu 20.04, MacOS 12.3.1
