### ISSUE TITLE
Filelogreceiver reads the same file twice in case there is an empty line at the beginning

### ISSUE THREAD

**Issue by perk** [open-telemetry/opentelemetry-collector-contrib#10127]
**Describe the bug**
Filelogreceiver reads the same file twice in case there is an empty line at the beginning when the `start_at: beginning` is set.

**Steps to reproduce**
Create the following `logs.txt` file to read the data from:
```

one
two
three
```

Apply the following configuration:
```
receivers:
  filelog:
    include:
    - ./logs.txt
    start_at: beginning

exporters:
  logging:

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

Run the otelcol:
```
./otelcol-contrib --config config.yaml
```

See the following lines:
```
2022-05-18T14:12:35.810+0200	info	file/file.go:174	Started watching file	{"kind": "receiver", "name": "filelog", "operator_id": "file_input", "operator_type": "file_input", "path": "logs.txt"}
2022-05-18T14:12:35.906+0200	INFO	loggingexporter/logging_exporter.go:71	LogsExporter	{"#logs": 3}
2022-05-18T14:12:36.105+0200	INFO	loggingexporter/logging_exporter.go:71	LogsExporter	{"#logs": 3}
```

**What did you expect to see?**
I'd expect the file to be read only once per otelcol run.

**What did you see instead?**
File is read twice.

**What version did you use?**
`0.51.0`

**What config did you use?**
```
receivers:
  filelog:
    include:
    - ./logs.txt
    start_at: beginning

exporters:
  logging:

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

**Environment**
OS: Ubuntu 20.04, MacOS 12.3.1
