### ISSUE TITLE
[processor/transform] Add ability to change metric data type

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#10130]
**Is your feature request related to a problem? Please describe.**
The transform processor is being wired up for metrics.  As a result, it is possible to do a query like 

`set("metric.type", "Gauge") where "metric.type" == "Sum"

But the metrics implementation does not know how to convert from one data type to another.

**Describe the solution you'd like**

The transformprocessor should be updated to be able to convert between all appropriate data types.

**Comment by bogdandrutu** [comment]
This should be only for "scalar/number" metrics.

**Comment by djaglowski** [comment]
When setting the data type to a counter, I think it is also appropriate to specify the monotonicity and aggregation temporality.

**Comment by TylerHelmuth** [comment]
> When setting the data type to a sum, I think it is also appropriate to specify the monotonicity and aggregation temporality.

Agreed

**Comment by BinaryFissionGames** [comment]
I'd be happy to take a stab at this.
Here's what I propose:

Two functions:
- `convert_scalar_metric_to_sum(aggregation_temporality, monotonic)`
  - Where `aggregation_temporality` is one of "delta" or "cumulative", and `monotonic` is true or false
  - If the metric is already a sum, aggregation_temporality and monotonic will be set based on the parameters.
  - If the metric is a gauge, it will be converted to a sum with the given aggregation temporality and monotonicity.
  - This function is a no op on non-scalar metrics
  - This function is only valid for metric pipelines
- `convert_scalar_metric_to_gauge()`
  -  No input parameters
  - If the metric is already a gauge, nothing is done.
  - If the metric is a sum, it is converted to a gauge
  - This function is a no-op for non-scalar metrics
  - This function is only valid for metric pipelines

The functions could be used like this:
```yaml
transform:
   metrics:
      queries:
         # Convert all sum metrics to gauges
         - convert_scalar_metric_to_gauge() where metric.type == "Sum"
         # convert the "my.metric.name.count" metric to a monotonic sum with "cumulative" as its aggregation temporality.
         - convert_scalar_metric_to_sum("cumulative", true) where metric.name == "my.metric.name.count"
```

@TylerHelmuth @bogdandrutu @djaglowski Thoughts on the above design?
