### ISSUE TITLE
Panic and SIGSEGV in awsecscontainermetricsreceiver

### ISSUE THREAD

**Issue by vise890** [open-telemetry/opentelemetry-collector-contrib#10161]
**Describe the bug**
`awsecscontainermetricsreceiver` segfaults at `github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver@v0.45.1/internal/awsecscontainermetrics/metrics_helper.go:27` on a cgroup v2 host.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
This puts the container on a restart loop on ECS.

**Steps to reproduce**
Running sidecar AWS OTEL collector on Flatcar Linux `ami-0c86b15ecbf1ecab6` with the given config reliably reproduces the problem for me.

**What did you expect to see?**
OTEL to start, stay up, and metrics to be collected.

**What did you see instead?**
A segfault.

**What version did you use?**
- aws-observability / [aws-otel-collector](https://github.com/aws-observability/aws-otel-collector) v0.17.0
- Flatcar Linux `ami-0c86b15ecbf1ecab6`

**What config did you use?**
The `awsecscontainermetrics` receiver and `metrics/ecs` pipeline are probably enough to reproduce
```yaml
receivers:
  awsecscontainermetrics:
    collection_interval: 20s

processors:
  resourcedetection:
    detectors:
      - system
      - ecs
      - ec2

  resource:
    attributes:
      - { key: aws.ecs.cluster.arn, action: delete }


exporters:
  awsprometheusremotewrite:
    endpoint: "set on deploy"
    aws_auth:
      region: "eu-west-1"
      service: "aps"
    resource_to_telemetry_conversion:
      enabled: true

  logging:
    loglevel: warn

extensions:
  health_check:
  pprof:
    endpoint: :1888

service:
  extensions: [pprof, health_check]
  pipelines:
    metrics/ecs:
      receivers: [awsecscontainermetrics]
      processors: [resourcedetection, resource]
      exporters: [logging, awsprometheusremotewrite]
```
**Environment**
Flatcar Container Linux `Flatcar-stable-3139.2.1-hvm` `ami-0c86b15ecbf1ecab6`

**Additional context**
- the otel collector makes an HTTP request to the amazon-ecs-agent to obtain task stats. Manually curling `"${ECS_CONTAINER_METADATA_URI_V4/task/stats"` (url found with e.g. `docker inspect`) from a container/node returns shows that the response does not contain some fields such as `MaxUsage`:
![image](https://user-images.githubusercontent.com/1628760/169358007-6351b8c7-8b6e-41b5-8b41-51071fdd8afe.png)
- When [`MaxUsage` gets dereffed](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/awsecscontainermetricsreceiver/internal/awsecscontainermetrics/metrics_helper.go#L27), the segfault happens
- The Docker Engine API (which is what the `amazon-ecs-agent` uses to retrieve those metrics) [doesn't actually export max_usage & others on cgroup v2 hosts](https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerStats):
```jsonc
    // FYI these are the memory stats exposed by the docker engine API
   // $ curl --unix-socket /var/run/docker.sock http://v1.41/containers/$container_id/stats?stream=false | jq '.memory_stats'
{
  "usage": 133541888,
  "stats": {
    "active_anon": 8192,
    "active_file": 20480,
    "anon": 130539520,
    "anon_thp": 98566144,
    "file": 53248,
    "file_dirty": 8192,
    "file_mapped": 32768,
    "file_writeback": 0,
    "inactive_anon": 130531328,
    "inactive_file": 32768,
    "kernel_stack": 425984,
    "pgactivate": 2,
    "pgdeactivate": 0,
    "pgfault": 55242,
    "pglazyfree": 0,
    "pglazyfreed": 0,
    "pgmajfault": 0,
    "pgrefill": 0,
    "pgscan": 0,
    "pgsteal": 0,
    "shmem": 0,
    "slab": 1843112,
    "slab_reclaimable": 1446888,
    "slab_unreclaimable": 396224,
    "sock": 0,
    "thp_collapse_alloc": 32,
    "thp_fault_alloc": 16,
    "unevictable": 0,
    "workingset_activate": 0,
    "workingset_nodereclaim": 0,
    "workingset_refault": 0
  },
  "limit": 2043600896
}
```
