### ISSUE TITLE
[pkg/stanza] Parser "body" block

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#10274]
That is the idea, though there's nothing requiring that `msg` be moved back to body. Some may wish to preserve the original body.

As a possible future feature, we could add a `body` block onto parsers, since this will be such a common workflow.

```yaml
type: json_parser
timestamp:
  layout: ...
  parse_from: time
severity:
  parse_from: sev
body: msg
```

_Originally posted by @djaglowski in https://github.com/open-telemetry/opentelemetry-log-collection/issues/431#issuecomment-1065427281_
