### ISSUE TITLE
[exporter/jaeger] unable to send traces to jaeger collector

### ISSUE THREAD

**Issue by mrjavaguy** [open-telemetry/opentelemetry-collector-contrib#10360]
I am guessing this is some sort of networking issue, but I have exhausted all my ideas on fixing, and I am hoping someone here can help.

I am running the OpenTelemetry collector in an EKS 1.19 cluster with the following config (secrets removed):

``` yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: splunk
spec:
  image: otel/opentelemetry-collector-contrib:0.52.0
  ports: 
    - name: prometheusexport
      port: 8080
    - name: zpages
      port: 55679
  config: |
    receivers:
        otlp:
            protocols:
                grpc:
                http:
    exporters:
        splunk_hec/logs:
            token: ""
            endpoint: ""
            source: "k8s:logs"
            sourcetype: "otlp"
            index: "main"
            max_connections: 20
            disable_compression: false
            timeout: 10s
            tls:
              insecure_skip_verify: true
        splunk_hec/metrics:
            token: ""
            endpoint: ""
            source: "k8s:metrics"
            sourcetype: "prometheus"
            index: "metrics"
            max_connections: 20
            disable_compression: false
            timeout: 10s
            tls:
              insecure_skip_verify: true
        jaeger:
          endpoint: "simplest-collector.observability.svc.cluster.local:14250"
          tls:
            insecure: true
        prometheus:
            endpoint: "0.0.0.0:8080"
            send_timestamps: true
            metric_expiration: 180m
            resource_to_telemetry_conversion:
                enabled: true                           
    processors:
        batch:
        memory_limiter:
          # 80% of maximum memory up to 2G
          limit_mib: 400
          # 25% of limit up to 2G
          spike_limit_mib: 100
          check_interval: 5s        

    extensions:
        health_check:
        pprof:
        zpages:
          endpoint: 0.0.0.0:55679

    service:
        extensions: [pprof, zpages, health_check]
        pipelines:
            logs:
                receivers: [otlp]
                exporters: [splunk_hec/logs]
                processors: [memory_limiter, batch]    
            traces:
                receivers: [otlp]
                exporters: [jaeger]
                processors: [memory_limiter, batch]
            metrics:
                receivers: [otlp]
                exporters: [prometheus]
                processors: [memory_limiter, batch]
```

And the setup I have for Jaeger is

``` yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.34
    options:
      log-level: debug
  ingress:
    enabled: false      
```

The issue is that I not seeing any traces in Jaeger for my services (logs are showing up in Splunk). If I look at the logs for the OpenTelemetry Collector I see multiple lines of `YYYY-MM-DDTHH:MM:SS.mmmZ        warn    zapgrpc/zapgrpc.go:191  [core] [Server #3] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams received bogus greeting from client: \"POST / HTTP/1.1\\r\\nHost: s\"" {"grpc_log": true}`

In searching around I did find an old issues about this but it stated the fix was to use `tls: insecure: true` on the jaeger exporter, which I have.  Any ideas on how to fix?
