### ISSUE TITLE
New component: MongoDB Atlas Alerts Receiver

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#10475]
## The purpose and use-cases of the new component
The MongoDB Atlas Alerts Receiver would be used to receive alerts from MongoDB Atlas through a webhook, and emit them as log signals.
See: https://www.mongodb.com/docs/atlas/tutorial/third-party-service-integrations/ - Webhook Settings

MongoDB Atlas allows sending alerts to select third parties, but this receiver would allow the alerts to be sent to any backend supported by the collector.

## Example configuration for the component

* endpoint (required) - ip:port pair to listen for incoming web requests on.
* secret (required): The webhook secret used to sign the incoming alert payloads.

```yaml
receivers:
  mongodbatlasalerts:
    endpoint: "0.0.0.0:9999"
    secret: "webhook_secret"
```

## Telemetry data types supported
* Logs

## Sponsor (Optional)
Looking for a sponsor
