### ISSUE TITLE
[receiver/filelogreceiver] offset could be taken as additional factor for fingerprinting

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#10481]
**Describe the bug**
We have a situation when rotated file begins the same way like the previous one (so fingerprint is the same), but new file is much behind the offset. So, while we are writing to the new file, nothing happens until we reach the offset. Such cases could be handled by filelog receiver.
There can happen if there are two same fingerprinted files being read in parallel.
My personal thought is to add some kind of hashes to fingerprint 

**Steps to reproduce**
1. `logs/file_1.txt`
   ```
   {"log": "THIS IS MY LOG FROM FILE1....................................................................\n", "stream": "stdout"}
   ```

2. `logs/file_2.txt`
   ```
   {"log": "THIS IS MY LOG FROM FILE2\n", "stream": "stdout"}
   ```

3. `config.yaml`
   ```
   receivers:
     filelog:
       include:
         - logs/file.txt
       fingerprint_size: 16
   exporters:
     logging:
       logLevel: debug
   service:
     pipelines:
       logs:
         receivers:
           - filelog
         exporters:
           - logging
   
   ```

4. run otc
   ```
   ./otelcol-contrib --config config.yaml 2>&1 | tee -a out2.log
   ```

5. steps:
   ```
   cd logs
   ln -s some_file.txt file.txt
   cp file_1.txt some_file.txt
   cp file_2.txt some_file.txt
   echo '{"log": "THIS IS MY LOG FROM FILE2\n", "stream": "stdout"}' >> some_file.txt
   echo '{"log": "THIS IS MY LOG FROM FILE2\n", "stream": "stdout"}' >> some_file.txt
   ```

**What did you expect to see?**
All three logs (or at least an offset error)

**What did you see instead?**
part of the log (starting from offset)
```
Body: HIS IS MY LOG FROM FILE2
```

**What version did you use?**
[v0.52.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.52.0)

**What config did you use?**
`config.yaml`
```
receivers:
  filelog:
    include:
      - logs/file.txt
    fingerprint_size: 16
exporters:
  logging:
    logLevel: debug
service:
  pipelines:
    logs:
      receivers:
        - filelog
      exporters:
        - logging
```

**Environment**
OS: `Ubuntu 22.04 LTS`

**Additional context**
N/A
