### ISSUE TITLE
[receiver/mongodbatlas] Add support for receiving alerts

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#10488]
The mongodbatlas receiver currently scrapes metrics from MongoDB Atlas. This proposal would be to add the ability to receive Alerts through a webhook and emitting them as log signals. Alerts in MongoDB Atlas may be metric based, but there are also many alert types that are not metric based, for instance, backups failing, host failures, user adds, and X509 certificate expiration.

You can see more about configuring the webhook on the MongoDB Atlas end here: https://www.mongodb.com/docs/atlas/tutorial/third-party-service-integrations/

Some ideas for configuration:

## Adding a new config section
```yaml
receivers:
  mongodbatlas:
    # existing metrics settings
    public_key: ${MONGODB_ATLAS_PUBLIC_KEY}
    private_key: ${MONGODB_ATLAS_PRIVATE_KEY}
    granularity: PT1M
    retry_on_failure:
       enabled: false
    # new alerts section
    alerts:
      enabled: true # default true
      endpoint: "0.0.0.0:9999" # webhook endpoint, no default
      secret: "some_secret_string" # webhook secret, no default
```

The big thing about this config is that it's non-breaking. The downside is that it's confusing that some metric-specific fields are top-level, but alerts are not. 

The "enabled" field is left to allow for disabling alerts if log support is added to this receiver.

## Squashing alerts configuration
```yaml
receivers:
  mongodbatlas:
    # existing metrics settings
    public_key: ${MONGODB_ATLAS_PUBLIC_KEY}
    private_key: ${MONGODB_ATLAS_PRIVATE_KEY}
    granularity: PT1M
    retry_on_failure:
       enabled: false
    # new alerts fields
    alerts_enabled: true # default true
    alerts_endpoint: "0.0.0.0:9999" # webhook endpoint, no default
    alerts_secret: "some_secret_string" # webhook secret, no default
```

This keeps the fields at the same level (no weird asymmetry with nesting), but is still strange because "granularity" would be metrics only (other fields, like public/private key may be applicable to application logs). 

This proposal also doesn't introduce any breaking changes to configuration.

## Sectioning the current config
```yaml
receivers:
  mongodbatlas:
    # existing metrics settings
    metrics:
      public_key: ${MONGODB_ATLAS_PUBLIC_KEY}
      private_key: ${MONGODB_ATLAS_PRIVATE_KEY}
      granularity: PT1M
      retry_on_failure:
         enabled: false
    # new alerts section
    alerts:
      enabled: true # default true
      endpoint: "0.0.0.0:9999" # webhook endpoint, no default
      secret: "some_secret_string" # webhook secret, no default
```

This proposal would break current configuration, making it very undesirable. It would create a more "symmetric" configuration. 

It would also be easy to add logs support to this config, however, logs would also likely need public/private key and retry logic, so all fields in the "metrics" section, except for granularity, could be shared.
