### ISSUE TITLE
Give Mysql reciever ability to get metrics based off custom queries

### ISSUE THREAD

**Issue by Konig-Corey** [open-telemetry/opentelemetry-collector-contrib#10544]
**Is your feature request related to a problem? Please describe.**
Datadog's mysql integration is capable of not only pulling in db metrics, but also running custom queries to gather metrics to be submitted. This would be a great addition to the current mysql receiver OR a new receiver

**Describe the solution you'd like**
The ability for Open Telemetry collection agent to gather metrics based on CUSTOM queries on a database. 

Something like 
```
  - server: <my-db>
    user: <my-user>
    pass: <pass>
    tags:
      - foo:bar    #custom tags 
    queries:
      - query: SELECT count(*) FROM users_table where user_name like "%@bar.com%"
        type: gauge
        field: count(*)
```
The above is a rip of a datadog mysql configuration for their integration so not all may apply here but the concept remains the same, wed like to query custom values from the database and have them published as metrics in a receiver. 

**Describe alternatives you've considered**
Some alternative we could have are to write a script in the language of choice that pulls the same queries, and then submits the results to the open telemetry collection agent via otlp (or ingest of choice)
