### ISSUE TITLE
 New component: Solace Receiver

### ISSUE THREAD

**Issue by mcardy** [open-telemetry/opentelemetry-collector-contrib#10572]
## The purpose and use-cases of the new component
The Solace Receiver would collect traces from a [Solace PubSub+ Event Broker](https://solace.com/products/event-broker/) using [Azure AMQP Golang client API](https://github.com/Azure/go-amqp). This component would provide message tracing capabilities for a Solace PubSub+ Event Broker. It will enable full end to end message lifecycle tracing exportable to backends such as Jaeger, Zipkin or Datadog for visualization. 

Solace is currently actively working on a next generation OpenTelemetry tracing integration into the event broker. The release of this component will be coordinated with community to align with a public availability of a Solace event messaging broker with tracing support. 

The Solace Receiver will receive trace messages as Guaranteed Messages from a Solace PubSub+ event broker and produce trace spans for the OpenTelemetry Collector.

## Example configuration for the component
The configuration parameters are:

- broker (Solace broker using amqp over tls; optional; default: localhost:5671; format: ip(host):port)
- queue (The name of the Solace queue to get span trace messages from; non optional; format: `queue://#telemetry-myTelemetryProfile`)
- max_unacknowledged (The maximum number of unacknowledged messages the Solace broker can transmit; optional; default: 10)
- transport (Defines different transport settings)
  - tls (Advanced tls configuration, secure by default)
    - insecure (The switch from ‘amqps’ to 'amqp’ to disable tls; optional; default: false)
    - server_name_override (Server name is the value of the Server Name Indication extension sent by the client; optional; default: empty string)
    - insecure_skip_verify (Disables server certificate validation; optional; default: false)
    - ca_file (Path to the User specified trust-store; used for a client to verify the server certificate; if empty uses system root CA; optional, default: empty string)
    - cert_file (Path to the TLS cert for client cert authentication, it is required when authentication sasl_external is chosen; non optional for sasl_external authentication)
    - key_file (Path to the TLS key for client cert authentication, it is required when authentication sasl_external is chosen; non optional for sasl_external authentication)
  - auth (Authentication settings. Permitted sub sub-configurations: sasl_plain_text, sasl_xauth2, sasl_external)
    - sasl_plain_text (Enables SASL PLAIN authentication)
      - username (The username to use, non optional for sasl_plain_text authentication)
      - password (The password to use; non optional for sasl_plain_text authentication)
    - sasl_xauth2 (SASL XOauth2 authentication)
      - username (The username to use; non optional for sasl_xauth2 authentication)
      - bearer (The bearer token in plain text; non optional for sasl_xauth2 authentication)
    - sasl_external (SASL External required to be used for TLS client cert authentication. When this authentication type is chosen then tls cert_file and key_file are required)

### Examples:
Simple single node configuration with SASL plain text authentication (and tls enabled by default)

```yaml
receivers:
  solace:
    broker: [localhost:5671]
    auth:
      sasl_plain_text:
        username: otel
        password: otel01$
    queue: queue://#telemetry-profile123
 
service:
  pipelines:
    traces:
      receivers: [solace]
```

High availability  setup with SASL plain text authentication (and tls enabled by default)
```yaml
receivers:
  solace/primary:
    broker: [myHost-primary:5671]
    auth:
      sasl_plain_text:
        username: otel
        password: otel01$
    queue: queue://#telemetry-profile123
 
  solace/backup:
    broker: [myHost-backup:5671]
    auth:
      sasl_plain_text:
        username: otel
        password: otel01$
    queue: queue://#telemetry-profile123
 
service:
  pipelines:
    traces/solace:
      receivers: [solace/primary,solace/backup]
```

## Telemetry data types supported
Trace

## Sponsor (Optional)
No sponsor as of now
