### ISSUE TITLE
New component: Icinga Receiver

### ISSUE THREAD

**Issue by sebastianhaeni** [open-telemetry/opentelemetry-collector-contrib#10839]
## The purpose and use-cases of the new component

[Icinga](https://icinga.com/) monitors infrastructure based periodical checks on configured hosts. Each check produces a result, which reflects the state of a service on a host. Using an event stream provided by the Icinga API, this receiver can collect metrics with counters and gauges, as well as mapping performance data (e.g. latency and others) to histograms.

## Example configuration for the component

```yaml
# Receiving check results via event stream from Icinga2
receivers:
  icinga:
    # Connection
    host: localhost:5665
    username: root
    password: test
    disable_ssl_verification: false

    # Filters: https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#icinga2-api-filters
    filter: "event.check_result.state==2"

    # Define histogram values for services, hosts, performance types:
    histograms:
      - service: stp_cpu-usage
        type: cpu_system
        host: .*
        values:
          - .1
          - .5
          - .9
```

## Telemetry data types supported

- metrics

## Sponsor (Optional)

I already have a working receiver and will create a PR for that in the near term future.
