### ISSUE TITLE
[exporters/prometheus] Prometheus exporter mTLS implementation

### ISSUE THREAD

**Issue by gfierka** [open-telemetry/opentelemetry-collector-contrib#10851]
**Is your feature request related to a problem? Please describe.**
Many opentelemetry exporters support TLS, but that's not the case with prometheus exporter. Implementing TLS would boost security. 

**Describe the solution you'd like**
From an end user perspective, implementing a solution similar to existing ones, i.e. Jaeger exporter
```yaml
tls:
  key_file: file.key
  cert_file: file.cert
```
