### ISSUE TITLE
StatsDReceiver appears to be broke

### ISSUE THREAD

**Issue by datsabk** [open-telemetry/opentelemetry-collector-contrib#10876]
**Describe the bug**
I am trying to use StatsD receiver and replace prom/statsd_exporter with it. However, I am noticing that the metrics that show up on StatsD Exporter on same port 8125 - Don't show up when I try the same with StatsDReceiver. 

**Steps to reproduce**
1. 
Configuration: 
```
receivers:
  statsd:
    endpoint: "localhost:8125" # default
    aggregation_interval: 10s  # default
    enable_metric_type: false   # default
    is_monotonic_counter: false # default
    timer_histogram_mapping:
      - statsd_type: "histogram"
        observer_type: "gauge"
      - statsd_type: "timing"
        observer_type: "gauge"
exporters:
  file:
    path: ./test.json
service:
  pipelines:
    metrics:
      receivers: [statsd]
      exporters: [file]
```

2. Start opentelemetry-collector-contrib server - `./otelcol-contrib --config stats_config.yaml`
3. Send some data
`echo "test.metric:43|c|#myKey:myVal" | nc -w 1 -u localhost 8125`
4. The metric won't show up in the file 

**What did you expect to see?**
The metric should get into the file after the aggregation interval is over. 

**What did you see instead?**
No data is going to the file. When I stop the otelcol-contrib and start statsd_exporter as docker on same port, It shows up the metric immediately. 

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
