### ISSUE TITLE
Google Cloud Exporter treats histogram instruments as metrics under "workload.googlapis.com" namespace

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/opentelemetry-collector-contrib#10883]
**Describe the bug**

All custom metrics to Cloud Monitoring via Google Cloud Exporter should go under "custom.googleapis.com" namespace [as documented](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudexporter) unless the developer specify their own prefix. However, when I tried to send Histogram instrument to Cloud Monitoring, it went under "workload.googleapis.com". 

**Steps to reproduce**

1. Create a Histogram instrument in the application
2. Send metrics to Cloud Monitoring via OpenTelemetry Collector with Google Cloud Exporter

**What did you expect to see?**

The custom metrics will be placed under "custom.googleapis.com".

**What did you see instead?**

The custom metrics was placed under "workload.googleapis.com".

**What version did you use?**

OpenTelemetry Collector: v0.52.0

**What config did you use?**

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:24317
exporters:
  googlecloud:
    project: <project-name>
    retry_on_failure:
      enabled: true
    timeout: 15s
  logging:
    loglevel: debug

processors:
  memory_limiter:
      check_interval: 10s
      limit_mib: 4000
      spike_limit_mib: 800
  batch:
    send_batch_max_size: 200
    send_batch_size: 200
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [googlecloud, logging]
```

**Environment**
OS: Debian testing

**Additional context**
