### ISSUE TITLE
StatsD receiver is not handling `count` attribute correctly for Prometheus Remote Write

### ISSUE THREAD

**Issue by datsabk** [open-telemetry/opentelemetry-collector-contrib#10897]
## The purpose and use-cases of the new component
We are trying to utilise Open Telemetry Collector for moving StatsD metrics to Prometheus. We tested and found that all the other metrics type except `count` is not going through well. It ends up with an issue as below: 

```
2022-06-10T21:51:15.055+0530	error	exporterhelper/queued_retry.go:183	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "name": "prometheusremotewrite", "error": "Permanent error: invalid temporality and type combination", "dropped_items": 111}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector@v0.51.0/exporter/exporterhelper/queued_retry.go:183
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
	go.opentelemetry.io/collector@v0.51.0/exporter/exporterhelper/metrics.go:132
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector@v0.51.0/exporter/exporterhelper/queued_retry_inmemory.go:118
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume
	go.opentelemetry.io/collector@v0.51.0/exporter/exporterhelper/internal/bounded_memory_queue.go:82
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2
	go.opentelemetry.io/collector@v0.51.0/exporter/exporterhelper/internal/bounded_memory_queue.go:69
```
## Example configuration for the component
```
receivers:
  statsd:
    endpoint: "0.0.0.0:8125" # default
    aggregation_interval: 10s  # default
    enable_metric_type: false   # default
    is_monotonic_counter: true # default
    timer_histogram_mapping:
      - statsd_type: "histogram"
        observer_type: "gauge"
      - statsd_type: "timing"
        observer_type: "gauge"
exporters:
  # file:
  #   path: ./test.json
  prometheusremotewrite:
    endpoint: <my-aws-amp-url>
    auth:
      authenticator: sigv4auth
    remote_write_queue:
      enabled: true
      queue_size: 5000
      num_consumers: 1
extensions:
  sigv4auth:
    region: "us-west-2"
    assume_role: 
      session_name: "otel_session"
service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [statsd]
      exporters: [prometheusremotewrite]
```

## Telemetry data types supported
Metrics - count datatype not supported
