### ISSUE TITLE
[exporter/datadog] Kubernetes node name resolution via the downward API

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#11033]
**Is your feature request related to a problem? Please describe.**

The Datadog exporter needs to query the Kubernetes node name for resolving the hostname (see #10911). The exporter currently relies on the assumption that the pod name can be retrieved by calling `os.Hostname`, which is not necessarily true if, e.g., the hostname has been modified via fields like [`setHostnameAsFQDN`](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field). In these cases, the Kubernetes source provider will fail.

**Describe the solution you'd like**

The Datadog exporter Kubernetes source provider supports getting the node name via the downward API or directly from the known environment variables documented in open-telemetry/oteps#195.

**Describe alternatives you've considered**

There are no alternatives to support these setups, really.

**Additional context**

Originally mentioned in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/10911#discussion_r895738662

**Comment by ringerc** [comment]
This should use the downward API to inject both the k8s pod name and the node name into the `Pod` at `DaemonSet` level

```
          env:
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_NAMESPACE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
```
