### ISSUE TITLE
googlecloudpubsubreceiver : gRPC unavailable error on response

### ISSUE THREAD

**Issue by hex1848** [open-telemetry/opentelemetry-collector-contrib#11073]
**Describe the bug**

We are running the open-telemetry-collector helm chart in our GKE kubernetes environment.   I added and configured the googlecloudpubsubreceiver component to pull from a gcp pubsub subscription.   It appears that authentication and the request goes through just fine, however the response always comes back with a gRPC status [unavailable](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/660527d6ffe8742a698b41a57d1b384bf769f80f/receiver/googlecloudpubsubreceiver/internal/handler.go#L221).   The GPC metrics explorer shows that events remain in an unack'ed state.

**Steps to reproduce**

- Provision the opentelemetry collector helm chart in GKE and configure the pubsub receiver component to pull from a pub sub subscription
- publish a otlp formatted metric events
- Watch logs for unavailable error
- Watch unacked events grow as new messages are publish

**What did you expect to see?**
 
- pubsub events pulled  ack'ed and processed

**What did you see instead?**

```
2022-06-16T14:33:11.901Z	warn	internal/handler.go:135	End of recovery loop, restarting.	{"kind": "receiver", "name": "googlecloudpubsub"}
2022-06-16T14:33:11.901Z	warn	internal/handler.go:191	Request Stream loop ended.	{"kind": "receiver", "name": "googlecloudpubsub"}
2022-06-16T14:33:11.901Z	warn	internal/handler.go:180	requestStream <-ctx.Done()	{"kind": "receiver", "name": "googlecloudpubsub"}
2022-06-16T14:33:11.901Z	warn	internal/handler.go:241	Response Stream loop ended.	{"kind": "receiver", "name": "googlecloudpubsub"}
2022-06-16T14:33:11.901Z	info	internal/handler.go:221	response stream breaking on gRPC s 'Unavailable'	{"kind": "receiver", "name": "googlecloudpubsub"}
```

**What version did you use?**
0v.53.0

**What config did you use?**
```
config:
  receivers:
    logging:
      loglevel: debug
    googlecloudpubsub:
      subscription: projects/recharge-stage-services-8e59/subscriptions/otlp-metric-events-subscription
  exporters:
    logging:
      loglevel: debug
    signalfx:
      access_token: {{ "ref+vault://... }}
      access_token_passthrough: false
      realm: us1
      log_dimension_updates: true
      timeout: 10s
      max_connections: 100
  processors:
    memory_limiter:
      limit_mib: 3200
      spike_limit_mib: 1024
      check_interval: 5s
    batch/metric:
      send_batch_max_size: 200
      send_batch_size: 200
  extensions:
    memory_ballast:
      size_in_percentage: 40
  service:
    telemetry:
      logs:
        level: debug
    extensions: [health_check, memory_ballast]
    pipelines:
      metrics:
        receivers: [googlecloudpubsub]
        processors: [memory_limiter, batch/metric]
        exporters: [signalfx]
```

**Environment**
OS: GKE
Helm Chart: https://github.com/open-telemetry/opentelemetry-helm-charts

**Additional context**
