### ISSUE TITLE
[receiver/mongodbatlasreceiver] Fix RecordMongodbatlasSystemMemoryUsageAverageDataPoint being called for the wrong metric

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#11126]
**Describe the bug**
There is a typo and RecordMongodbatlasSystemMemoryUsageAverageDataPoint is currently being called for the wrong metric (MAX_SYSTEM_MEMORY_FREE).

**Steps to reproduce**
Run the collection against a good system.

**What did you expect to see?**
A metric for mongodbatlas.system.memory.usage.max

**What did you see instead?**
Duplicate metrics for mongodbatlas.system.memory.usage.average

**What version did you use?**
v0.53.0

**What config did you use?**
```
receivers:
  mongodbatlas:
    public_key: idyesrik
    private_key: ef0dd104-2ece-4f86-9da9-a0c7ce6d1cb7
    collection_interval: 60s
    metrics:
      mongodbatlas.db.counts:
        enabled: false
      mongodbatlas.db.size:
        enabled: false

processors:
  # Copy useful mongodb specific attributes that will otherwise
  # be dropped by the Google exporter.
  # resourceattributetransposer:
  #   operations:
  #     - from: mongodb_atlas.org_name
  #       to: org_name
  #     - from: mongodb_atlas.project.name
  #       to: project
  #     - from: mongodb_atlas.db.name
  #       to: database
  #     - from: mongodb_atlas.process.type_name
  #       to: process_type

  # Used for Google generic_node mapping.
  resource:
    attributes:
    - key: namespace
      value: mongodbatlas
      action: upsert
    - key: location
      value: global
      action: upsert

exporters: 
  googlecloud:
    retry_on_failure:
      enabled: false
    metric:
      prefix: workload.googleapis.com
    resource_mappings:
    - source_type: ""
      target_type: generic_node
      label_mappings:
      - source_key: mongodb_atlas.host.name
        target_key: node_id
      - source_key: location
        target_key: location
      - source_key: namespace
        target_key: namespace

  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers:
      - mongodbatlas
      processors:
      # - resourceattributetransposer
      - resource
      exporters:
      - googlecloud
      - logging
```
