### ISSUE TITLE
[processor/attributes] log_severity_texts does not filter

### ISSUE THREAD

**Issue by amoscatelli** [open-telemetry/opentelemetry-collector-contrib#11439]
**Describe the bug**
log_severity_texts filter simply doesn't work
tried the example here and doesn't work either : 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/testdata/config.yaml

For example :

```
    attributes:
        include:
            match_type: strict
            log_severity_texts: [ "TRACE" ]
        actions:
            -   key: should_exclude
                action: upsert
                value: true
```

should_exclude is added to every log instead of traces only.

**Steps to reproduce**
Use log_severity_texts to filter the attribute processor.

**What did you expect to see?**
Attribute processor to be filtered.

**What did you see instead?**
Attribute processor to be applied always.

**What version did you use?**
otel/opentelemetry-collector-contrib:0.53.0

**What config did you use?**

```
receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins: [
            #OMITTED
          ]

processors:
    memory_limiter:
        check_interval: 5s
        limit_mib: 448
        spike_limit_mib: 64
    batch:
        send_batch_size: 48
        send_batch_max_size: 48
        timeout: 15s
    attributes:
        include:
            match_type: strict
            log_severity_texts: [ "TRACE" ]
        actions:
            -   key: should_exclude
                action: upsert
                value: true
    filter:
        logs:
            exclude:
                match_type: strict
                record_attributes:
                    - key: should_exclude
                      value: true

exporters:
    logging:
        loglevel: debug
        sampling_initial: 2
    otlp:
        endpoint: tempo-eu-west-0.grafana.net:443
        headers:
            authorization: Basic #OMITTED
            
    prometheusremotewrite:
        endpoint: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        headers:
            authorization: Basic #OMITTED
            
    loki:
        endpoint: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
        headers:
            authorization: Basic #OMITTED
        format: json
        labels:
            attributes:
                container_name: ""
                source: ""
            resource:
                host.name: "hostname"

extensions:
    health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [attributes, filter]
      exporters: [logging]
```
