### ISSUE TITLE
[processor/redaction] The Redaction Processor does not honor the `allow_all_keys` configuration

### ISSUE THREAD

**Issue by tcoville-coveo** [open-telemetry/opentelemetry-collector-contrib#11450]
**Describe the bug**
All attributes are dropped even if `allow_all_keys` is set to true

**Steps to reproduce**
start a standalone collector with the processor enabled and send traces to it
observe that the attributes get redacted 

**What did you expect to see?**
with `allow_all_keys` to true I expect all attributes to remain untouched and being sent to the exporter

**What did you see instead?**
All of the attributes were "redacted". 

**What version did you use?**
0.53.0 custom build as the redaction processor is not part of the manifest yet

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680

processors:
  redaction:
    allow_all_keys: true
    summary: debug

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - redaction
      exporters:
        - logging
```
