### ISSUE TITLE
K8s Processor: add ability to associate metadata tags using pod UID rather than just IP

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector-contrib#1146]
**Is your feature request related to a problem? Please describe.**
The logs coming through `fluentforward` receiver can have `pod_uid` associated with them and no information about the IP address of the pod. This could be easily leveraged by adding capability to associate pod with the record using either IP address (as it is now) or Pod UID.

**Describe the solution you'd like**
Let the Kubernetes Processor cache metadata tags using Pod UID as key (similarly as it's [done for IP](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/k8sprocessor/kube/client.go#L48) - two maps could be used)

The name of the tag containing Pod UID can be defaulted to `pod_uid` and optionally made configurable, e.g. a new configuration entry might be added:

`pod_uid_matching_labels` - by default, `[pod_uid]`; if empty - no matching by Pod uid applied

Alternatively, taking into account https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1079 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1078, maybe a more streamlined configuration approach could be applied, e.g.

```
pod_association:
  ip:
    labels: [ip, k8s.pod.ip, host.hostname]
    connection_source_extraction_enabled: true
  uid:
    labels: [pod_uid]
```

**Additional context**

I have prepared a document that describes this in more context: https://docs.google.com/document/d/1QlFbXz0eQUaKXK1WrnEs3VqRkcPD2RAdXJdJMjnOSd8/edit#

**Comment by dashpole** [comment]
Note that the pod name is not unique in a kubernetes cluster, as two pods in different namespaces can have the same name.  I would suggest either:

1. Use pod name + pod namespace
2. Use pod uid (available in the `/var/log/pods/namespace_podname_poduid/containername/restartcount.log` kubernetes log path.

One more thing to note is that (1) does not uniquely identify a pod across time, but (2) does.

**Comment by pmm-sumo** [comment]
> Note that the pod name is not unique in a kubernetes cluster
That's a very fair argument. I think we should be able to extract `pod UID` from the CRI path, gonna check how the config looks like for it

**Comment by tigrannajaryan** [comment]
@owais FYI.

**Comment by owais** [comment]
This sounds good to me. I like the "streamlined" config option more than adding 3 different options that may or may not work together. Can we do something like this:

```yaml
pod_association:
  ip:
    - label_ip
    - label_k8s_pod_ip
    - label_hostname
    - client_ip
  uid:
    - label_pod_uid
```

This will allow users to provide custom lookup order so they can chose to match by source/client IP first and then fallback on the labels if they want but not sure if it's worth the extra complexity such config options might bring. Another option is to keep lists with more detailed items.

```yaml
pod_association:
  - ip:
    - from: labels
      name: ip
    - from: labels
      name: k8s.pod.ip
    - from: labels
      name: host.hostname
    - from: connection
      name: ip
  - uid:
    - from: labels
      name: pod_uid
```

Where `ip` and `uid` map keys are arbitary and don't hold any special meaning. Their presence means that we'll internally hold two maps (or a composite map or a single map with prefixed keys) for lookup.

Or we can always use one map and let the user decide if they want to mix IDs from multiple types of sources (IPs and UIDs) so something like:

```yaml
pod_association:
 - from: labels
   name: ip
 - from: labels
   name: k8s.pod.ip
 - from: labels
   name: host.hostname
 - from: connection
   name: ip
 - from: labels
   name: pod_uid
```

Just thinking out loud here to see if we can have a better approach to config that can allow easier additions down the line. In general I agree we should add this feature but not sure yet exactly what it should look like. WDYT?

**Comment by pmm-sumo** [comment]
This are great ideas @owais. I like the simplicity of those approaches. One another variation might be e.g.:

```yaml
pod_association:
  connection_source: true
  ip:
    - ip
    - k8s.pod.ip
    - host.hostname
  uid:
    - pod_uid
```

Alternatively (and I think this is pretty much what the third example you brought is doing), this could be perhaps even more simplified into a single list and whatever is found in the field being matched as either `uid` or `ip` (since the space for possible values is quite different). So either doing it like int the third example or using e.g.

```yaml
pod_association:
  connection_source: true
  labels:
    - ip
    - k8s.pod.ip
    - host.hostname
    - pod_uid
```
