### ISSUE TITLE
[receiver/mongodbatlas] Adding the receiver to both Logs and Metrics errors

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#11535]
**Describe the bug**
The collector does not properly start if it is added to both the logging and metrics pipeline.

**Steps to reproduce**
Use the following config, and run the collector:
```yaml
receivers:
  mongodbatlas:
    alerts:
      enabled: true
      endpoint: "0.0.0.0:9999"
      secret: "my_secret"

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [mongodbatlas]
      exporters: [logging]
    metrics:
      receivers: [mongodbatlas]
      exporters: [logging]
  telemetry:
    metrics:
      level: none
    logs:
      level: debug
```

**What did you expect to see?**
The collector starts normally (or at least errors on the lack of an API key.)

**What did you see instead?**
2022/06/24 09:44:30 collector server run finished with error: cannot build receivers: factory for "mongodbatlas" is implemented incorrectly: CreateTracesReceiver, CreateMetricsReceiver and CreateLogsReceiver must return the same receiver pointer when creating receivers of different data types

**What version did you use?**
v0.54.0
