### ISSUE TITLE
Failed to receive skywalking trace data from envoy

### ISSUE THREAD

**Issue by suninuni** [open-telemetry/opentelemetry-collector-contrib#11554]
**Describe the bug**

I'm trying to use opentelemetry to process skywalking trace data from envoy in istio, but I got these errors:

```
2022-06-27T10:06:20.937Z	warn	zapgrpc/zapgrpc.go:191	[core] [Server #3] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams received bogus greeting from client: \"POST /skywalking.v3.Trac\""	{"grpc_log": true
```

**Steps to reproduce**

- enable skywalking providers in istio https://github.com/istio/istio/pull/32588#issuecomment-862002263:

    ```yaml
    extensionProviders:
    - name: envoy.tracers.skywalking
      skywalking:
        port: 11800
        service: opentelemetry-collector.sre.svc.cluster.local
    ```

- deploy opentelemetry-collector 0.54.0

    ```yaml
    receivers:
      skywalking:
        protocols:
          grpc:
            endpoint: 0.0.0.0:11800
          http:
            endpoint: 0.0.0.0:12800
    exporters:
      jaeger:
        endpoint: "jaeger:14250"
        tls:
          insecure: true
    processors:
      batch:
    service:
      pipelines:
        traces:
          receivers: [skywalking]
          processors: [batch]
          exporters: [jaeger]
    ```
