### ISSUE TITLE
[exporter/datadog] Services view operation name do not match with Traces view operation names

### ISSUE THREAD

**Issue by Nighttraveler** [open-telemetry/opentelemetry-collector-contrib#11727]
**Describe the bug**
 Services view operation name do not match with Traces view operation names. It looks to be sanitized in one place but not in the other.

**What did you expect to see?**
We expected to see the same operation name in both views, without it the traces list in Service view is useless.
If you click "view in traces" it searches for "operation_name:Web:/foo" and does not show any result, but if you manually  change the `:/` to `_` it does show results.
We relay a lot in operation_name since in our case resource in only GET or POST without much further detail.

[Image example](https://i.imgur.com/ww1I3QF.png)

**What did you see instead?**
An inconsistency in Services tab between `operation` at the top of the page and `operation_name` under Traces tab 
[Image example](https://i.imgur.com/H6Ao5fh.png)

**What version did you use?**
Collector versions:otel/opentelemetry-collector-contrib:0.45.0, otel/opentelemetry-collector-contrib:0.52.0

**What config did you use?**
```
exporters:

  datadog:
    api:
      key: $DD_API_KEY
    traces:
      span_name_as_resource_name: true

  logging:
    logLevel: $LOG_EXPORTER_LOG_LEVEL

```

**Environment**
OS: (e.g., "Ubuntu 20.04")
Collector running in docker
