### ISSUE TITLE
[processor/spanmetrics + exporter/prometheusremotewrite] latency_bucket's are empty

### ISSUE THREAD

**Issue by amoscatelli** [open-telemetry/opentelemetry-collector-contrib#11782]
**Describe the bug**
As long as I understand, by using spanmetrics, a couple of metrics should be exported : 

calls_total
latency_bucket

I am using AGGREGATION_TEMPORALITY_DELTA and exporting to prometheus with an OTEL Collector configuration very similar to this one from testdata : 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/testdata/config-prometheusremotewrite.yaml

I am using Grafana Cloud and I can see calls_total properly filled : 

![image](https://user-images.githubusercontent.com/16684470/176220866-37b34fd7-84ab-464a-bfac-6f8d97659e4b.png)

Yet there is no data for latency_bucket : 

![image](https://user-images.githubusercontent.com/16684470/176221119-1e4e939f-e645-4e31-a0f6-f314d92411d8.png)

I really can't understand the reason.
Please help ?

**Steps to reproduce**
I will provide my open telemetry configuration below

**What did you expect to see?**
I expect to see records/metrics for latency_bucket for different 'le' values.

**What did you see instead?**
No data in latency_bucket

**What version did you use?**
opentelemetry-collector-contrib:0.54

Prometheus and Grafana are SaaS, so I can't be sure about their versions.

**What config did you use?**

```
receivers:
    otlp:
        protocols:
            http:
                cors:
                    allowed_origins: [
                        #################
                    ]
                    
    # Dummy receiver that's never used, because a pipeline is required to have one.
    otlp/spanmetrics:
        protocols:
            grpc:
                endpoint: "localhost:12345"

    prometheus/spanmetrics:
      config:
        scrape_configs:
          - job_name: 'ratelimiter'
            scrape_interval: 6m
            static_configs:
              - targets: ['localhost:8889']

processors:
    memory_limiter:
        check_interval: 5s
        limit_mib: 448
        spike_limit_mib: 64
    batch:
        send_batch_size: 48
        send_batch_max_size: 48
        timeout: 15s
    transform:
        logs:
            queries:
                - set(attributes["severity_text"], severity_text)
    filter:
        logs:
            exclude:
                match_type: regexp
                record_attributes:
                    - key: severity_text
                      value: "(TRACE|DEBUG)"
    spanmetrics:
        metrics_exporter: prometheus/spanmetrics
        dimensions:
            - name: enduser.id
            - name: http.status_code
            - name: http.client_ip
        aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"

exporters:
    logging:
    otlp:
        endpoint: tempo-eu-west-0.grafana.net:443
        headers:
            authorization: Basic #################
            
    prometheusremotewrite:
        endpoint: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        headers:
            authorization: Basic #################
            
    loki:
        endpoint: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
        headers:
            authorization: Basic #################
        format: json
        labels:
            attributes:
                container_name: ""
                source: ""
            resource:
                host.name: "hostname"
                
    prometheus/spanmetrics:
        endpoint: "localhost:8889"

extensions:
    health_check:
service:
    extensions: [health_check]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [spanmetrics, memory_limiter, batch]
            exporters: [otlp]
        metrics/spanmetrics:
            # This receiver is just a dummy and never used.
            # Added to pass validation requiring at least one receiver in a pipeline.
            receivers: [otlp/spanmetrics]
            # The metrics_exporter must be present in this list.
            exporters: [prometheus/spanmetrics]
        metrics:
            receivers: [otlp, prometheus/spanmetrics]
            processors: [memory_limiter, batch]
            exporters: [prometheusremotewrite]
        logs:
            receivers: [otlp]
            processors: [transform, filter, memory_limiter, batch]
            exporters: [loki]

```

**Environment**
OTEL Collector is running on AWS Beanstalk Linux v2, but I don't think this is relevant.

**Additional context**

scrape_interval is set to 6m because I don't want Prometheus to correlate my deltas in its staleness windows.
