### ISSUE TITLE
New component - Azure Data Explorer

### ISSUE THREAD

**Issue by ag-ramachandran** [open-telemetry/opentelemetry-collector-contrib#11830]
### Azure Data Explorer Exporter

This exporter sends metrics, logs and trace data to [Azure Data Explorer](https://azure.microsoft.com/en-us/services/data-explorer/).

## Configuration

The following settings are required:

- `cluster_uri` (no default): The cluster name of the provisioned ADX cluster to ingest the data.
- `application_id` (no default): The client id to connect to the cluster and ingest data.
- `application_key` (no default): The cluster secret corresponding to the client id.
- `tenant_id` (no default): The tenant id where the application_id is referenced from.

The following settings can be optionally configured and have default values:
> Note that the database , tables are expected to be created upfront before the exporter is in operation , the definition of these are in the section [Database and Table definition scripts](#database-and-table-definition-scripts)
- `db_name` (default = "oteldb"): The ADX database where the tables are present to ingest the data.
- `metrics_table_name` (default = OTELMetrics): The target table in the database `db_name` that stores exported metric data.
- `logs_table_name` (default = OTELLogs): The target table in the database `db_name` that stores exported logs data.
- `traces_table_name` (default = OTELLogs): The target table in the database `db_name` that stores exported traces data.

  Optionally the following table mappings can be specified if the data needs to be mapped to a different table on ADX. This uses json [table mapping](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/mappings#json-mapping) that can be used to map [attributes](#attribute-mapping) to target tables
- `metrics_table_name_mapping` (optional, no default): The table mapping name to be used for the table `db_name`.`metrics_table_name` 
- `logs_table_name_mapping` (optional, no default): The table mapping name to be used for the table `db_name`.`logs_table_name`
- `traces_table_name_mapping` (optional, no default): The table mapping name to be used for the table `db_name`.`traces_table_name`
- `ingestion_type` (default = queued): ADX ingest can happen in managed [streaming](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/streamingingestionpolicy) or [queued](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/batchingpolicy) modes.
#### Note: [Streaming ingestion](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-streaming?tabs=azure-portal%2Ccsharp) has to be enabled on ADX [configure the ADX cluster] in case of `streaming` option

An example configuration is provided as follows:

```yaml
exporters:
  azuredataexplorer:
    # Kusto cluster uri
    cluster_uri: "https://CLUSTER.kusto.windows.net"
    # Client Id
    application_id: "f80da32c-108c-415c-a19e-643f461a677a"
    # The client secret for the client
    application_key: "xx-xx-xx-xx"
    # The tenant
    tenant_id: "21ff9e36-fbaa-43c8-98ba-00431ea10bc3"
    # Database for the logs
    db_name: "oteldb"
    # Metric table name
    metrics_table_name: "OTELMetrics"
    # Log table name
    logs_table_name: "OTELLogs"
    # Traces table
    traces_table_name: "OTELTraces"
    # Metric table mapping name
    metrics_table_name_mapping: "otelmetrics_mapping"
    # Log table mapping name
    logs_table_name_mapping: "otellogs_mapping"
    # Traces mapping table
    traces_table_name_mapping: "oteltraces_mapping"
    # Type of ingestion managed or queued
    ingestion_type : "managed"
```

## Telemetry data types supported

Traces , Metrics and Logs are supported

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?

Yes. This interfaces with Azure Data Explorer , a database offering from Microsoft
