### ISSUE TITLE
[processor/transform] Unable to rename operation field

### ISSUE THREAD

**Issue by klubi** [open-telemetry/opentelemetry-collector-contrib#11859]
Hi

I'm having an issue renaming operation field.
My simplified environment setup:

```
API Gateway (getambassador.io) -> otlp collector -> jaeger
```

API Gateway sends data in Zipkin format.
In my setup, there are plenty of subdomains and I'd like operation related field to be more generic, so in jaeger they won't be listed as separate operations, but rather be grouped.

I tried using `transform` processor, but wasn't able to make it work...

```yaml
      transform:
        traces:
          queries:
            - replace_match(attributes["operationName"], "*.domain.com", ".{subdomain}.domain.com")
            - replace_match(attributes["name"], "*.domain.com", ".{subdomain}.domain.com")
            - replace_match(resource.attributes["operationName"], "*.domain.com", ".{subdomain}.domain.com")
            - replace_match(resource.attributes["name"], "*.domain.com", ".{subdomain}.domain.com")
```

**Comment by mx-psi** [comment]
cc @TylerHelmuth maybe you can help?

**Comment by TylerHelmuth** [comment]
@klubi the `replace_match` function will substitute the entire string value with the replacement value if the value matches the glob pattern.  So if your string is `something.domain.com` then the value after your `repalce_match` will be exactly `.{subdomain}.domain.com`.  If you wanted to only replace the part that matches you should use `replace_pattern`.  The results of `replace_pattern` would be `something.{subdomain}.domain.com`.  The `replace_pattern` function will be available in the next release.

All that said, the way you have configured the processor you should at least be getting values modified to `.{subdomain}.domain.com`.  I need more details to determine why that isn't happening. What version of the collector are you running?  Do the logs show any errors? Have you confirmed that data is making it to the collector?

**Comment by klubi** [comment]
I'm on latest versions of collector and jaeger.

I can setup docker-compose example over weekend to demonstrate the issue.

But i guess my question boils down to: "how to reference and alter field used by jaeger to display operation name".
Using "name" and "operationName" was just a guess from my side".

**Comment by TylerHelmuth** [comment]
I'm not familiar with jaeger so I won't be much help with the data once it is there.  

For debugging the collector, though, enabling a logging exporter with logLevel set to Debug is a very useful way to inspect the data that would get exported to a backend.  With the configuration you posted, assuming the transform processor is also added to the traces pipeline, I would expect it to be modifying all those attributes, assuming that all match the pattern.

**Comment by TylerHelmuth** [comment]
Yes, you can do 

```yaml
transform:
  traces:
    queries:
      - replace_match(name, "*.domain.com", "{subdomain}.domain.com")
```
