### ISSUE TITLE
[exporter/loki] Getting error message ->"error": "Permanent error: failed to transform logs into Loki log streams"

### ISSUE THREAD

**Issue by a06953** [open-telemetry/opentelemetry-collector-contrib#11895]
**Describe the bug**
I am trying to use the **Loki exporter** along with the **windowseventlog** receiver to capture the system logs of a windows VM on Grafana. But while running the \cmd\otelcontribcol\main.exe, I am getting the error message {"error": "Permanent error: failed to transform logs into Loki log streams"}. I am also logging it in in a json file and able to view the logs over there

**What config did you use?**
Config: (e.g. the yaml config file)
```
receivers:
  windowseventlog:
    start_at: beginning
    channel: system

processors:

  batch:
    send_batch_size: 50
    timeout: 5s
  memory_limiter:
    check_interval: 2s
    limit_mib: 1800
    spike_limit_mib: 500


exporters:
  file:
    path: C:/Users/..../logfilename.json

  loki:
    endpoint: "https://234372:(****APIKEY****)@logs-prod3.grafana.net/loki/api/v1/push"
    format: "json"
    labels:
     record:
       severity: "SeverityText"

service:
  pipelines:
    logs:
      receivers: [windowseventlog]
      processors: [batch]
      exporters: [file,loki]
```
**Environment**
OS: Windows Server 2022 Datacenter

Error Message:
```
2022-07-04T17:24:54.846Z        error   exporterhelper/queued_retry.go:183      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "logs", "name": "loki", "error": "Permanent error: failed to transform logs into Loki log streams", "dropped_items": 82}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        C:/Users/oatazureuser/go/pkg/mod/go.opentelemetry.io/collector@v0.54.0/exporter/exporterhelper/queued_retry.go:183
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
        C:/Users/oatazureuser/go/pkg/mod/go.opentelemetry.io/collector@v0.54.0/exporter/exporterhelper/logs.go:131
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
        C:/Users/oatazureuser/go/pkg/mod/go.opentelemetry.io/collector@v0.54.0/exporter/exporterhelper/queued_retry_inmemory.go:119
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume
        C:/Users/oatazureuser/go/pkg/mod/go.opentelemetry.io/collector@v0.54.0/exporter/exporterhelper/internal/bounded_memory_queue.go:82
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2
        C:/Users/oatazureuser/go/pkg/mod/go.opentelemetry.io/collector@v0.54.0/exporter/exporterhelper/internal/bounded_memory_queue.go:69
```

**Comment by jpkrohling** [comment]
Would you be able to share the log file that is exported? I don't have a Windows machine available for testing, the output from the file exporter might help me reproduce the issue.

**Comment by lostwong** [comment]
Hi, I think I'm seeing the exact same error while using otelcol-contrib 0.55.0.  I'm using opentelemetry-cpp v1.4.1 to generate logs and traces.  I hope this is just a silly configuration error on my part...

Here's the console output when I used both logger and loki as exporters:
```
2022-07-11T03:00:22.680Z        DEBUG   loggingexporter/logging_exporter.go:82  ResourceLog #0
Resource SchemaURL: 
Resource labels:
     -> service.name: STRING(unknown_service)
     -> telemetry.sdk.version: STRING(1.4.1)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.language: STRING(cpp)
ScopeLogs #0
ScopeLogs SchemaURL: https://opentelemetry.io/schemas/1.11.0
InstrumentationScope default 1.0.0
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-07-11 03:00:22.612549422 +0000 UTC
Severity: DEBUG
Body: body
Trace ID: d5dcd20a3630d9bad59dfa8b78a88ffc
Span ID: 95e57bbac32a2c60
Flags: 1

2022-07-11T03:00:22.680Z        error   exporterhelper/queued_retry.go:183      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "logs", "name": "loki", "error": "Permanent error: failed to transform logs into Loki log streams", "dropped_items": 1}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/queued_retry.go:183
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
        go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/logs.go:131
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
        go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/queued_retry_inmemory.go:119
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume
        go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/internal/bounded_memory_queue.go:82
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2
        go.opentelemetry.io/collector@v0.55.0/exporter/exporterhelper/internal/bounded_memory_queue.go:69
```

And here's my configuration:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"
    # Will encode the whole OTEL message in json
    # This format happen after extracting labels
    format: json
    labels:
      attributes:
        container_name: ""
        source: ""
      resource:
        host.name: "hostname"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, loki]
```

**Comment by jpkrohling** [comment]
Can you set tls.insecure to true within the Loki exporter? The default is false, but given you are using a local Loki under HTTP, you should change it:

```
exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"
    tls:
      insecure: true
```

**Comment by lostwong** [comment]
I just gave it a try and received the same results.  I also verified that my loki installation is currently alright through a separate test application that pushes directly to the http://localhost:3100/loki/api/v1/push endpoint.

Based on the error message, is the problem related to mapping resources / attributes between otelcol and loki?  I have very little experience with Go and I'm still learning about obsevability / opentelemetry in general so digging into this on my own has been a pretty steep climb for me.

**Comment by jpkrohling** [comment]
@lostwong, are you able to come up with a curl call that would trigger this problem? Or provide a client code that I can run to reproduce it.

**Comment by lostwong** [comment]
Sure, I'll see about putting together as small a docker image as possible with the client code / build so that you can give it a whirl.

**Comment by jpkrohling** [comment]
I was able to get the same error on a simple setup with journald receiver:

```yaml
receivers:
  journald:
    directory: /var/log/journal/a04e3a44cdd740f88d6a7ae3bb8c70cf/

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: http://localhost:3100
    tls:
      insecure: true
    labels:
      attributes:
        host: localhost

processors:
extensions:

service:
  extensions:
  pipelines:
    logs:
      receivers: [journald]
      processors: []
      exporters: [logging, loki]
```

My initial investigation shows that the problem is that the incoming data points (ie, log entries) do not have any attributes or resource attributes, causing them to be dropped.

I'll get in touch with the Loki team here at Grafana Labs to see what's the behavior of Promtail, so that we can align them. I'll post updates here as soon as I have them.

**Comment by lostwong** [comment]
Thanks for putting in so much time into this already!  If there's anything I can do to help further, please let me know.

**Comment by lostwong** [comment]
@jpkrohling based on your feedback about the missing resources/attributes, I was able to get my system up and running by adjusting my client code and my otelcol configuration.

After re-reading the [README.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md), I can see where I went wrong and, in my case specifically, this isn't a bug.  It's user error.

In terms of details, I added an attribute to my ::Log() method call (note the addition of the "key": "value" attribute).

```c++
logger->Log(opentelemetry::logs::Severity::kDebug, "body", {{"key", "value"}}, ctx.trace_id(), ctx.span_id(),
              ctx.trace_flags(),
              opentelemetry::common::SystemTimestamp(std::chrono::system_clock::now()));
```

And I needed to adjust my otelcol configuration to map the "key" key from the opentelemetry-cpp client to a field that will be used by loki.

```yaml
exporters:
  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"
    format: json
    labels:
      attributes:
        key: "loki_key"
    tls:
      insecure: true
```

Everything is basically working for me now.  Thanks for all the help @jpkrohling !

**Comment by jpkrohling** [comment]
Glad to hear it's working! I'm still investigating what can be done for sources we don't control, such as journald or logs in files.

**Comment by a06953** [comment]
Thanks, this issue is fixed now. But currently I am not able to view the full logs in Grafana. Can I just see the message  anyhow?

**Exporter:**
exporters:
  loki:
    endpoint: "https://234372:(APIKEY)@logs-prod3.grafana.net/loki/api/v1/push"
    labels:
     attributes:
        log.file.name: "MyLogFile"
        level : "level"
    tls:
      insecure: true
    format: "body"
    

**Grafana expected format.**
   
![Expected Dashboard](https://user-images.githubusercontent.com/108689771/178778292-f56eba19-444d-476d-94f1-49ae540118c8.jpg)

**Grafana current view.**
 
![Grafana Screenshot](https://user-images.githubusercontent.com/108689771/178778294-c8d7a45b-e0c1-45fd-9a71-1fdb304de4c6.jpg)

**Comment by gillg** [comment]
@jpkrohling maybe it's related to this bigger discussion?
https://github.com/open-telemetry/opentelemetry-collector/issues/2588

The receivers for logs are not all consistent

**Comment by Tornhoof** [comment]
I'm getting the same error message, just with logs exported from .NET.
I worked around by adding the following
line to the labels configuration:
```yaml

dotnet.ilogger.category: "category"
```
That attribute is always available, as it is the LoggerName in .NET.

**Comment by jpkrohling** [comment]
@Tornhoof, your problem seems related to the comment I made earlier in this thread:

> My initial investigation shows that the problem is that the incoming data points (ie, log entries) do not have any attributes or resource attributes, causing them to be dropped.

This won't be necessary anymore after the refactoring of the Loki exporter that is underway, see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12873

**Comment by ConnorSMaynes** [comment]
Hi, I am facing the same error. I am using a **filelog** receiver. I am struggling to find some config which will work.

Does anyone have any suggestions?

Config:
```yaml
receivers:
  filelog:
    include_file_name: false
    start_at: beginning
    include: ['\\10.1.1.108\C$\Program Files\Inductive Automation\Ignition\logs\wrapper.log*']   
    attributes:
      key: "value"

processors:
  batch:

exporters:
  logging:
    logLevel: debug

  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"
    tls:
      insecure: true
    tenant_id: "example1"
    labels:
      attributes:
        container_name: ""
        container_id: ""

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [loki]
```

**Comment by jpkrohling** [comment]
Do you have `container_name` and `container_id` as part of your log entry? If you do not have any attributes, you can try to use the resource processor to add a property, and use it in the loki exporter.

**Comment by gillg** [comment]
You create dummy resources attributes but you convert attributes as labels instead of resource attributes.
You must use exporters.loki.labels.resources instead of exporters.loki.labeld.attributes.

That should work.

**Comment by ConnorSMaynes** [comment]
I updated the exporters section, but got the same error.

```
exporters:
  logging:
    logLevel: debug

  loki:
    endpoint: "http://localhost:3100/loki/api/v1/push"
    tls:
      insecure: true
    tenant_id: "example1"
    labels:
      resource:
        host: "hostname"
        version: "v0_0_0_0"
```
