### ISSUE TITLE
[exp/prometheusremotewrite] Exporting "target" instead of "target_info"

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#12079]
**Describe the bug**

When pushing data through Prometheus Remote Write, we should expose the Resource Attributes using the `target_info` metric, but we are currently pushing a `target` metric.

**Steps to reproduce**
Run a simple collector deployment with the following config:
```
exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"

processors:
  batch: {}
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 5s
        external_labels:
          scraped_by: otel-collector 

      scrape_configs:
        - job_name: collector
          static_configs:
            - targets: ['localhost:8888']

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
```

**What did you expect to see?**
`target_info` in Prometheus.

**What did you see instead?**
`target`

**What version did you use?**
Version: `v0.54.0`
