### ISSUE TITLE
[receiver/filelog] Log lines are reordered during file rotation

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-collector-contrib#12084]
**Describe the bug**
When a file is rotated, filelog receiver may read lines from the new file before exhausting the old one, leading to log lines being reordered. This is a problem especially when using recombine to stitch multipart or multiline logs back together.

**Steps to reproduce**
Set a large interval length (5s for example), then rotate a file close to the end of it.

**What did you expect to see?**
Logs in the order they were written (and consistent with their timestamps).

**What did you see instead?**
Newer logs from the new file before older logs from the rotated file.

**What version did you use?**
v0.52.0 - v0.54.0, no change in behaviour between versions.

**What config did you use?**
```
receivers:
  filelog:
    poll_interval: 5s
    include:
    - /var/log/containers/*/*/*.log
  exporters:
    logging:
  service:
    telemetry:
      logs:
        level: debug
    pipelines:
      containers:
        receivers: [filelog]
        processors: []
        exporters: [logging]
```

**Environment**
OS: BottlerocketOS 1.8.0

**Additional context**
This came up in K8s, where container runtimes will split large log lines into parts, and the log collection agent needs to stitch them back together.

A fix is WIP here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11889
