### ISSUE TITLE
[receiver/mongodb] TLS Settings Ignored in certain circumstances

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#12092]
**Describe the bug**
Did some digging and noticed the alpha `receiver/mongodbreceiver` was checking for a non-nil error from `configtls.LoadTLSConfig()` before inputting into the `mongo-go-driver`

**Steps to reproduce**
Set up a mongodb 4.4 instance with these settings:

```yaml
net:
   tls:
      mode: requireTLS
      certificateKeyFile: /opt/mongo/tls/mongo-test.localnet.pem
      allowConnectionsWithoutCertificates: true
```

And the mongod logs indicate a problem from the client:
```
{"t":{"$date":"2022-07-01T22:21:27.345+00:00"},"s":"I",  "c":"NETWORK",  "id":22988,   "ctx":"conn8528","msg":"Error receiving request from client. Ending connection from remote","attr":{"error":{"code":141,"codeName":"SSLHandshakeFailed","errmsg":"The server is configured to only allow SSL connections"},"remote":"127.0.0.1:58444","connectionId":8528}}
```

**What did you expect to see?**
Before: 
```go
        tlsConfig, err := c.LoadTLSConfig()
	if err != nil && tlsConfig != nil {
		clientOptions.SetTLSConfig(tlsConfig)
	}
```

After:
```go
        tlsConfig, err := c.LoadTLSConfig()
	if err == nil && tlsConfig != nil {
		clientOptions.SetTLSConfig(tlsConfig)
	}
```

**What did you see instead?**
Metrics collection did work through TLS

**What version did you use?**
Version 0.54.0 version of the `mongodbreceiver`

**What config did you use?**
```yaml
receivers:
  mongodb:
    hosts:
      - endpoint: keith-mongo-test.bluemedora.localnet:27017
    username: admin
    password: password
    collection_interval: 20s
    tls:
      insecure: false
      cert_file: /opt/mongo/tls/mongo-test.bluemedora.localnet.crt
      key_file: /opt/mongo/tls/mongo-test.bluemedora.localnet.key
      insecure_skip_verify: true
exporters:
  logging:

service:
  pipelines:
    metrics:
      receivers:
      - mongodb
      exporters:
      - logging
[root@keith-mon
```

**Environment**
OS:  "RHEL 7.9"

**Additional context**

Will author a PR shortly to resolve this!
