### ISSUE TITLE
Fail to parse containerd time string

### ISSUE THREAD

**Issue by rlex** [open-telemetry/opentelemetry-collector-contrib#12200]
**Describe the bug**
With logging enabled and loki exporter added otel-collector fails to parse date in containerd log files

**Steps to reproduce**
k3s 1.24.2, otel-collector from helm-chart

**What did you expect to see?**
Logs arriving to loki 

**What did you see instead?**
```
2022-07-08T20:18:51.153Z	error	helper/transformer.go:110	Failed to process entry	{"kind": "receiver", "name": "filelog", "pipeline": "logs", "operator_id": "parser-crio", "operator_type": "regex_parser", "error": {"description": "time parser: parsing time \"2022-07-08T10:17:29.54131618+03:00\" as \"2006-01-02T15:04:05.000000000-07:00\": cannot parse \"03:00\" as \".000000000\""}, "action": "send", "entry": {"observed_timestamp":"2022-07-08T20:18:51.153160911Z","timestamp":"0001-01-01T00:00:00Z","body":"2022-07-08T10:17:29.54131618+03:00 stdout F {\"caller\":\"config_controller.go:136\",\"controller\":\"ConfigReconciler\",\"event\":\"force service reload\",\"level\":\"info\",\"ts\":\"2022-07-08T07:17:29Z\"}","attributes":{"log":"{\"caller\":\"config_controller.go:136\",\"controller\":\"ConfigReconciler\",\"event\":\"force service reload\",\"level\":\"info\",\"ts\":\"2022-07-08T07:17:29Z\"}","log.file.path":"/var/log/pods/metallb-system_metallb-speaker-spsp6_0ecbe3e5-a175-4c1c-a8de-66c2bf3325f3/speaker/17.log","logtag":"F","stream":"stdout","time":"2022-07-08T10:17:29.54131618+03:00"},"severity":0,"scope_name":""}}
```

Looks like date format is a bit different:
```
2006-01-02T15:04:05.000000000-07:00
2022-07-08T10:17:29.54131618+03:00
```

**What version did you use?**
```
otel/opentelemetry-collector-contrib:0.55.0
```

**What config did you use?**
```
      - config:
          receivers:
            filelog:
          exporters:
            loki:
              endpoint: http://loki-distributor.loki.svc.cluster.local:3100/loki/api/v1/push
              tenant_id: kube-lex
              labels:
                resource:
                  container.name: "container_name"
                  {{ .Environment.Values.global_kubecontext }}: kube_cluster
```
**Environment**
Ubuntu 22.04
k3s 1.24.2

**Additional context**
Wonder if default scenario should even catch this or i'm expected to copy operators and adjust them?
