### ISSUE TITLE
[processors/attributes] include match_type: regexp log_bodies not working

### ISSUE THREAD

**Issue by gurpartb** [open-telemetry/opentelemetry-collector-contrib#12207]
**Describe the bug**
Expected `match_type: regexp` to only `include` logs with `log_bodies` that match the pattern `^log 0$` and add `attribute` `body-match: true`, but the processor matches all logs.

**Steps to reproduce**
Add two log entries below to a simple.log file
```
{ "service.name": "test", "message": "log 0" }  
{ "service.name": "test", "message": "log 1" }
```

Use [fluentd](https://www.fluentd.org/download) to send data to Otel Collector  using td-agent.conf below
```
<source>
   @type tail
    tag "simple.log"
    path "C:/path/to/simple.log"
    pos_file "C:/path/to/test.log.pos"
    read_from_head true
    follow_inodes true
    <parse>
      @type "json"
    </parse>
</source>
<match simple.log>
    @type forward
    send_timeout 30s
    recover_wait 5s
    hard_timeout 30s
    <server>
      name "localhost"
      host "127.0.0.1"
      port 8006
      weight 100
    </server>
</match>
```

Use Otel agent-config.yaml below to add `body-match: true` attribute to logs whose bodies match pattern `^log 0$`.
```
receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006

processors:
  attributes/include-regexp-body-insert:
    include:
      match_type: regexp
      log_bodies:
        - '^log 0$'
    actions:
      - key: body-match
        action: insert
        value: true

  groupbyattrs:
    keys:
    - service.name

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers:
      - fluentforward
      processors:
      - groupbyattrs
      - attributes/include-regexp-body-insert
      exporters:
      - logging
```
**What did you expect to see?**
Attribute `body-match: true` should only be added to first log entry...

**What did you see instead?**
...but its added to both. See pic below.
![image](https://user-images.githubusercontent.com/35710086/178114791-4eff44d6-9eda-4077-aeb3-181ff778176d.png)

**What version did you use?**
Version: `v0.55.0`

**What config did you use?**
See `steps to reproduce`

**Environment**
OS: Windows 10

**Additional context**
n/a

**Comment by gurpartb** [comment]
I solved my use case with `processors` `transform`
```
processors:
  transform:
    logs:
      queries:
        - set(attributes["body-match"], true) where body == "log 0"
```
