### ISSUE TITLE
New component - Resource detection processor support for Oracle OCI

### ISSUE THREAD

**Issue by natfly** [open-telemetry/opentelemetry-collector-contrib#12326]
## The purpose and use-cases of the new component
Query the instance metadata service ([IMDS](https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/gettingmetadata.htm)) to provide information about a running instance in OCI

## Example configuration for the component
Configuration showing default available attributes
```
processors:
  resourcedetection/oci:
    detectors: [oci]
    timeout: 2s
    override: false
    attributes: ["cloud.provider", "cloud.platform", "cloud.account.id", "cloud.region", "cloud.availability_zone", "host.id", "host.image.id", "oci.compartment.id"]
```

Configuration showing custom attributes using jpath to reference IMDS document. 
"attributeJPaths" is an array of "name"/"path" values
"name" will be the name of the attribute emitted in logs/traces/metrics
"path" the jpath to the value in the IMDS document
```
processors:
    resourcedetection/oci:
      detectors: [oci]
      timeout: 2s
      override: false
      oci:
        attributeJPaths:
          - name: tags.asdf
            path: freeformTags.asdf
          - name: monitoringDisabled
            path: agentConfig.monitoringDisabled
          - name: agentConfig.pluginNames
            path: agentConfig.pluginsConfig.#.name
          - name: k8s.cluster.name
            path: metadata.oke-cluster-display-name
          - name: k8s.cluster.version
            path: metadata.oke-k8version
```

## Telemetry data types supported
traces, metrics and logs

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?
Yes, and I can if needed.

## Sponsor (Optional)
Looking for a sponsor
