### ISSUE TITLE
k8sattributes: setting tag_name using captured group from key_regex fails for extracting labels

### ISSUE THREAD

**Issue by jparal** [open-telemetry/opentelemetry-collector-contrib#12330]
**Describe the bug**
I am trying to extract k8s labels matching `key_regex` as per documentation and capture the `tag_name` following the steps here:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4cf86dee2359683a4cf0bf71668e00018e76202b/processor/k8sattributesprocessor/config.go#L116

I assume the `name` field is a typo and should be in fact `tag_name`.

**Steps to reproduce**
See the yaml bellow

**What did you expect to see?**
I would expect the metrics exported to Prometheus having labels like: `component: webapp` for a pod label:
`app.kubernetes.io/component: webapp` 

**What did you see instead?**
Instead I see the `tag_name` being empty, eg: `"": webapp`

**What version did you use?**
Version: 0.55.0

**What config did you use?**
Config:
```yaml
    processors:
      k8sattributes:
        # ...
        extract:
          labels:
            - from: pod
              # name: "$1"  # <--- an example in the docs require `name` but   
              tag_name: "$1"
              key_regex: "app.kubernetes.io/(.*)"
```

**Additional context**
* I tried using `name` as per docs but then I get an error the `name` field is not allowed during parsing/validation of config yaml.
