### ISSUE TITLE
[receiver/mongodbatlas] Add support for consuming logs

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector-contrib#12347]
This would be a Logging addition to the current [MongoDB Atlas Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/mongodbatlasreceiver). To monitor logs for MongoDB Atlas you need to pull from the [Logging API](https://www.mongodb.com/docs/atlas/reference/api/logs/) which returns a gzip of a log file. The SDK that is currently used in the receiver provides a [LogsService](https://pkg.go.dev/go.mongodb.org/atlas/mongodbatlas#LogsService) to retrieve logs. 

Following the current configuration split with metrics and alerts:

### Config
---

```yaml
receivers:
  mongodbatlas:
    # existing metrics settings
    public_key: ${MONGODB_ATLAS_PUBLIC_KEY}
    private_key: ${MONGODB_ATLAS_PRIVATE_KEY}
    granularity: PT1M
    retry_on_failure:
       enabled: false
    # existing alerts settings
    alerts:
      enabled: true # default true
      endpoint: "0.0.0.0:9999" # webhook endpoint, no default
      secret: "some_secret_string" # webhook secret, no default
    # new logging settings
    logs:
      enabled: true #default true
      projects: # List of projects to monitor logs from
        - name: project_1 # Human readable name of the project
          exclude_clusters: [] # option blacklist of clusters in a project to exclude from log collection, default empty
          collect_audit_logs: false # The user needs to enable this in Atlas so it needs to be enabled here

```

The current metrics receiver monitors all projects within the organization. Since logs may grow much more than metrics in a system at scale the user must specify projects they wish to collect logs from via the `projects` list. 

By default we will collect logs from all clusters in a project. If a user wishes to remove a cluster from collection they can use the `exclude_clusters` list within a project. The `exclude_clusters` list provides easier first time setup for users to collect their entire system.

### Overloading Logging Receiver
---

Since there is already a logs receiver for collecting alerts we'll have to implement a single logs receiver that will collect both alerts and logs using the same consumer. The logs collected from the logging API will have attributes that are unique from the alert generated logs.

Since we can reuse a lot of the client setup, and configuration values, in the current [receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/mongodbatlasreceiver/receiver.go#L33) this would mean adding a few functions to that receiver code that are geared towards collecting logs.
