### ISSUE TITLE
metricstransformprocess cannot apply to my project

### ISSUE THREAD

**Issue by JonnyDeep** [open-telemetry/opentelemetry-collector-contrib#12349]
i use opentelemetry collector to collect host metrics。 the receiver I choosed was otlp and hostmetrics，the process was batch and metricstransformprocess。but i cannot start the project by docker compose。it has below error
`2022/07/13 03:17:08 collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown processors type "metricstransform" for "metricstransform/1" (valid values: [probabilistic_sampler filter batch memory_limiter attributes resource span])
`  
this was my otel-collector-config.yaml
```yaml
receivers:
  otlp:
    protocols:
      grpc:

  hostmetrics:
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true



exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

  metricstransform/1:
    transform:
      - include: system.cpu.utilization
        action: upadte
        operations:
          - action: aggregate_labels
            label_set: [state]
            aggregation_type: sum




extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [ hostmetrics]
      processors: [batch,metricstransform/1]
      exporters: [logging, prometheus]
```
the opentelemetry image version is v0.55.0。if i want solve the problem，what i should do。

**Comment by JonnyDeep** [comment]
i use opentelemetry collector to collect host metrics。 the receiver I choosed was otlp and hostmetrics，the process was batch and metricstransformprocess。but i cannot start the project by docker compose。it has below error
`2022/07/13 03:17:08 collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown processors type "metricstransform" for "metricstransform/1" (valid values: [probabilistic_sampler filter batch memory_limiter attributes resource span])
`  
this was my otel-collector-config.yaml
```yaml
receivers:
  otlp:
    protocols:
      grpc:

  hostmetrics:
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true



exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

  metricstransform/1:
    transform:
      - include: system.cpu.utilization
        action: upadte
        operations:
          - action: aggregate_labels
            label_set: [state]
            aggregation_type: sum




extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [ hostmetrics]
      processors: [batch,metricstransform/1]
      exporters: [logging, prometheus]
```
the opentelemetry image version is v0.55.0。if i want solve the problem，what i should do。
