### ISSUE TITLE
[processor/resourcedetection] instance hostname missing on GKE with new detector

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#12354]
**Describe the bug**

Before #10347, someone using the `gke` and `gce` detectors would have the instance hostname on GKE. After this change, the new `gcp` detector would not add this attribute. This is a regression on v0.55.0, and also makes it difficult for people to transition to the new detector.

Datadog needs this attribute in order to correctly correlate telemetry reported by the Collector with telemetry reported by the Datadog GCP integration, which uses this as part of the hostname.

**Steps to reproduce**

Add the `gke` and `gce` detectors to your Collector on a GKE cluster.

**What did you expect to see?**

The `host.name` attribute would be present as it happened on v0.54.0 and below

**What did you see instead?**

The `host.name` attribute is missing.

**What version did you use?**

v0.55.0

**What config did you use?**

```
receivers:
  hostmetrics:
    scrapers:
      load:
    collection_interval: 10s

processors:
  resourcedetection:
    detectors: [gke, gce]

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection]
      exporters: [logging]
```

**Environment**

v0.55.0 Docker image
