### ISSUE TITLE
[processor/filter] Refactor the  (expression) expr match_type to support resource attributes 

### ISSUE THREAD

**Issue by jvoravong** [open-telemetry/opentelemetry-collector-contrib#12416]
**Is your feature request related to a problem? Please describe.**
Currently in the filter processor, you can only use expression matching with metric names, label names, and label values. It would be excellent if we also supported attributes names and values when using expression matching in the filter processor.

**Describe the solution you'd like**
I would like to be able to use filter[ expression methods and logic](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#using-an-expr-match_type) with attributes.
Examples: 

- HasAttribute("attribute_x")
- Attribute("attribute_x"),  
- "(HasAttribute("attribute_x") && Attribute("attribute_x") == "valueX") || (HasAttribute("attribute_y") && Attribute("attribute_y") == "valueY")")

Example of use:
```
# Filter in metrics that come from a specific Kubernetes namespace or that don't have the k8s.name.space attribute at all
# Collector Config
processors:
  filter/metrics:
    metrics:
      exclude:
        match_type: expr
        expressions:
          - HasAttribute("k8s.namespace.name") && Attribue("k8s.namespace.name") != "microservices"
```
              
**Describe alternatives you've considered**
I've tried chaining multiple filter processors together and creating extra service pipelines to get the proper sets of telemetry data I desire, it gets tedious to organize.
