### ISSUE TITLE
[logstransformprocessor] Cannot use processor in multiple pipelines with storage extension

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#12424]
**Describe the bug**
Cannot use logstransformprocessor in multiple pipelines as the second instance hangs trying to get access to storage

**Steps to reproduce**

use configuration from configuration section

**What did you expect to see?**
I want to see working collector

**What did you see instead?**
```
otc_1  | 2022-07-14T09:55:27.452Z       info    pipelines/pipelines.go:94       Processor started.      {"kind": "processor", "name": "logstransform", "pipeline": "logs/1"}
otc_1  | 2022-07-14T09:55:27.452Z       info    pipelines/pipelines.go:90       Processor is starting...        {"kind": "processor", "name": "logstransform", "pipeline": "logs/2"}
otc_1  |        {"kind": "processor", "name": "logstransform", "pipeline": "logs/2"}
otc_1  | Error: cannot start pipelines: timeout
otc_1  | 2022/07/14 09:55:32 collector server run finished with error: cannot start pipelines: timeout
2022_06_10_filterprocessor_convert_error_otc_1 exited with code 1
```

**What version did you use?**
`v0.55.0`

**What config did you use?**
```
extensions:
  file_storage:
    directory: /var/lib/storage/otc
    timeout: 5s
exporters:
  logging:
    logLevel: debug
receivers:
  filelog:
    include:
    - nothing
processors:
  logstransform:
    operators:
      - type: filter
        expr: body matches 'log'
service:
  extensions:
    - file_storage
  pipelines:
    logs/1:
      exporters:
      - logging
      processors:
      - logstransform
      receivers:
      - filelog
    logs/2:
      exporters:
      - logging
      processors:
      - logstransform
      receivers:
      - filelog
```

**Environment**
OS: (e.g., "Ubuntu 20.04")
N/A

**Additional context**
N/A
