### ISSUE TITLE
[attributesprocessor]: Field "pattern" contains at least one unnamed matcher group at the 0-th actions

### ISSUE THREAD

**Issue by EddieEldridge** [open-telemetry/opentelemetry-collector-contrib#12477]
**Describe the bug**
I’m trying to use the example outlined here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/testdata/config.yaml#L24

```log
error creating "attributes" processor attributes/extract: error creating AttrProc.s/extract: error creating AttrProc. 
Field "pattern" contains at least one unnamed matcher group at the 0-th actions
```

I'm just copy pasting the whole example as it does exactly what I want but it's throwing this error. 

**Steps to reproduce**
Use the example provided and try to start the Collector

**What did you expect to see?**
I would expect the example to be valid regex.

**What did you see instead?**
The Collector failed to start with the above mentioned error

**What version did you use?**
0.54

**What config did you use?**
```yaml
# Shortened for brevity
processors:
  attributes/extract:
      actions:
        - key: "http.url"
          pattern: ^(?P<http_protocol>.*):\/\/(?P<http_domain>.*)\/(?P<http_path>.*)(\?|\&)(?P<http_query_params>.*)
          action: extract
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - attributes/extract
```

**Environment**
```systemd
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Additional context**
Is the Regex expression provided invalid possibly?

![image](https://user-images.githubusercontent.com/22448079/179028269-5b87f410-29a6-49c1-9e99-72bd61f0ea52.png)
