### ISSUE TITLE
[processor/filter] enable expr evaluation on non-string type metric labels

### ISSUE THREAD

**Issue by samanthawalter** [open-telemetry/opentelemetry-collector-contrib#12479]
**Is your feature request related to a problem? Please describe.**
As of v0.64.0, expr in the filter processor cannot properly evaluate metric labels that are not string type.

**Describe the solution you'd like**
I would like to filter based non-string metric labels. For example:

```yaml
filter:
  metrics:
    exclude:
      match_type: expr
      expressions:
        - Label("my_boolean_attribute") == true
```

Changes would be centered around the [Label method for the env of the expr filter matcher](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.64.0/internal/coreinternal/processor/filterexpr/matcher.go#L42-L45). Specifically, `v.Str()` [returns an empty string if the attribute is not of type string](https://github.com/open-telemetry/opentelemetry-collector/blob/pdata/v0.64.0/pdata/pcommon/common.go#L203).

Ideally, the Label method would return the appropriate value type by using [`AsRaw()`](https://pkg.go.dev/go.opentelemetry.io/collector/pdata@v0.64.0/pcommon#Value.AsRaw).

Alternatively, `v.StringVal()` can be replaced with `v.AsString()`. While AsString would still require evaluating all attributes as strings (e.g. `Label("my_boolean_attribute") == "true"`) this is an improvement over the empty string returned by StringVal.

**Comment by TylerHelmuth** [comment]
Instead of expanding `Expr` configuration options we've chosen to move forward with OTTL.  This is functionality is already achievable with:

```yaml
processors:
  filter/ottl:
    error_mode: ignore
    metrics:
      metric:
        - attributes["my boolean attribute"] == true
```
