### ISSUE TITLE
[receiver/filelog] Field 'body' is not assumed as expected

### ISSUE THREAD

**Issue by EddieEldridge** [open-telemetry/opentelemetry-collector-contrib#12647]
**Describe the bug**
_If a field does not start with resource, attributes, or body, then body is assumed. For example, my_value is equivalent to body.my_value_

**Steps to reproduce**
```yaml
  filelog/service:
    include_file_path_resolved: true
    include_file_path: false
    start_at: beginning
    operators:
      - type: json_parser
      - type: remove
        field: log
```

**What did you expect to see?**
I would expect `body.log` to be removed from my log after the json parsing has occured.

**What did you see instead?**
The Collector failed to start with the following error

`Error: cannot build pipelines: failt to create "filelog" receiver, in pipeline "logs": unmarshal to remove: unrecognized prefix`

**What version did you use?**
0.55 Collector

**What config did you use?**
```yaml
  filelog/service:
    include_file_path_resolved: true
    include_file_path: false
    start_at: beginning
    operators:
      - type: json_parser
      - type: remove
        field: log
```

**Environment**
Amazon Linux 2

**Additional context**
N/A
