### ISSUE TITLE
[receiver/filelog] Unable to remove attribute 'log' 

### ISSUE THREAD

**Issue by EddieEldridge** [open-telemetry/opentelemetry-collector-contrib#12648]
**Describe the bug**
I am able to perform operations on all the other attributes on the same level as the `log` attribute but not the actual `log` attribute itself.

**Steps to reproduce**
```yaml
  filelog/service:
    include_file_path_resolved: true
    include_file_path: false
    start_at: beginning
    operators:
      - type: json_parser
      - type: add
        field: attributes.test_field_1
        value: test_value_1
      - type: add
        field: attributes.test_field_2
        value: test_value_2
      - type: remove
        field: attributes.test_field_1
      - type: remove
        field: attributes.log
```

**What did you expect to see?**
I would expect the `log` attribute to be removed just like `test_field_1` as they are on the same 'level'.

**What did you see instead?**
The `log` attribute was not removed.

**What version did you use?**
0.55

**What config did you use?**
See above.

**Environment**
Amazon Linux 2

**Additional context**
The collector is reading from .log files with the following content
```json
{
    "t": "2022-07-05T14:58:04.985Z",
    "message": "Sent SQS notification to queue",
    "level": "INFO"
}
```
After being ingested through the the `filelog reciever`. 

```json
{
    "t": "2022-07-05T14:58:04.985Z",
    "message": "{\"t\":\"2022-07-05T14:58:04.985Z\",\"message\":\"Sent SQS notification to queue",
    "log.file.name": "ansible-json.log",
    "log.file.path.resolved": "/home/ec2-user/ansible-json.log",
    "log": "{\"t\":\"2022-07-05T14:58:04.985Z\",\"message\":\"Sent SQS notification to queue\", \"level\": \"INFO\"}",
    "level": "INFO"
}
```
I don't actually need the `log` field anymore as it's body  is representing the actual entire 'log' message.

**Comment by djaglowski** [comment]
Will you please share the full receiver configuration and an exact line of text that is being read from the log file?

---

> After being ingested through the the filelog reciever.
>
> {
    "t": "2022-07-05T14:58:04.985Z",
    "message": "{\"t\":\"2022-07-05T14:58:04.985Z\",\"message\":\"Sent SQS notification to queue",
    "log.file.name": "ansible-json.log",
    "log.file.path.resolved": "/home/ec2-user/ansible-json.log",
    "log": "{\"t\":\"2022-07-05T14:58:04.985Z\",\"message\":\"Sent SQS notification to queue\", \"level\": \"INFO\"}",
    "level": "INFO"
}

To my knowledge, the filelog receiver does not add a `"log"` attribute on its own, so I would first determine where this is coming from:
- Is there a `"log"` field in the raw json you are parsing?
- Is the body being copied to `attributes.log`?

---

I am not able to reproduce this issue. 

To test this, I created a log file called `foo.log`:
```
{"t": "2022-07-05T14:58:04.985Z","message": "Sent SQS notification to queue","level": "INFO"}

```

I used the following configuration:
```yaml
receivers:
  filelog:
    include: [ *.log ]
    include_file_path_resolved: true
    include_file_path: false
    start_at: beginning
    operators:
      - type: json_parser
      - type: add
        field: attributes.test_field_1
        value: test_value_1
      - type: add
        field: attributes.test_field_2
        value: test_value_2
      - type: remove
        field: attributes.test_field_1

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

When I run this, I get the following, which (as I would expect) does not contain `attributes.log`.

```
Severity: 
Body: {"t": "2022-07-05T14:58:04.985Z","message": "Sent SQS notification to queue","level": "INFO"}
Attributes:
     -> message: STRING(Sent SQS notification to queue)
     -> level: STRING(INFO)
     -> test_field_2: STRING(test_value_2)
     -> log.file.name: STRING(foo.log)
     -> log.file.path_resolved: STRING(.../foo.log)
     -> t: STRING(2022-07-05T14:58:04.985Z)
```

To setup a removal test, I added a `copy` operator to initialize `attributes.log`:

```yaml
- type: copy
  from: body
  to: attributes.log
```

```
Severity: 
Body: {"t": "2022-07-05T14:58:04.985Z","message": "Sent SQS notification to queue","level": "INFO"}
Attributes:
     -> t: STRING(2022-07-05T14:58:04.985Z)
     -> message: STRING(Sent SQS notification to queue)
     -> level: STRING(INFO)
     -> log: STRING({"t": "2022-07-05T14:58:04.985Z","message": "Sent SQS notification to queue","level": "INFO"})
     -> test_field_2: STRING(test_value_2)
     -> log.file.name: STRING(foo.log)
     -> log.file.path_resolved: STRING(.../foo.log)
```

Then I added the same `remove` operation and observed the field to be removed successfully.

```yaml
- type: remove
  field: attributes.log
```

```
Severity: 
Body: {"t": "2022-07-05T14:58:04.985Z","message": "Sent SQS notification to queue","level": "INFO"}
Attributes:
     -> t: STRING(2022-07-05T14:58:04.985Z)
     -> message: STRING(Sent SQS notification to queue)
     -> test_field_2: STRING(test_value_2)
     -> log.file.name: STRING(foo.log)
     -> log.file.path_resolved: STRING(.../foo.log)
```
