### ISSUE TITLE
[prometheusexporter] error gathering queueSize metrics

### ISSUE THREAD

**Issue by amoscatelli** [open-telemetry/opentelemetry-collector-contrib#12645]
**Describe the bug**
I see a strange error, it seems a sort of collision when collecting queueSize metrics

**Steps to reproduce**
I really don't know, I'll attach my configuration below.
This seems to happen regularly every ten minutes.

**What did you expect to see?**
No error ?

**What did you see instead?**
```
2022-07-22T07:48:58.416Z        error   prometheusexporter@v0.56.0/log.go:34    error gathering metrics: 2 error(s) occurred:
* collected metric queueSize label:<name:"job" value:"iam" > label:<name:"logProcessorType" value:"BatchLogProcessor" > gauge:<value:0 >  has help "The number of logs queued" but should have "The number of spans queued"
* collected metric queueSize label:<name:"job" value:"optoplus-services" > label:<name:"logProcessorType" value:"BatchLogProcessor" > gauge:<value:0 >  has help "The number of logs queued" but should have "The number of spans queued"
        {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.56.0/log.go:34
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1
        github.com/prometheus/client_golang@v1.12.2/prometheus/promhttp/http.go:129
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
        net/http/server.go:2462
net/http.serverHandler.ServeHTTP
        net/http/server.go:2916
net/http.(*conn).serve
        net/http/server.go:1966
```

**What version did you use?**
This happens with both 0.55 or 0.56 otel collector contrib docker image

**What config did you use?**
```
receivers:
    otlp:
        protocols:
            http:
                include_metadata: true
                cors:
                    allowed_origins: [
                        #OMITTED#
                    ]                    
    # Dummy receiver that's never used, because a pipeline is required to have one.
    otlp/spanmetrics:
        protocols:
            grpc:
                endpoint: "localhost:12345"

    prometheus:
      config:
        scrape_configs:
          - job_name: 'ratelimiter'
            scrape_interval: ${RECEIVERS_PROMETHEUS_CONFIG_SCRAPE_INTERVAL}
            static_configs:
              - targets: ['${HOSTNAME}:8889']

processors:
    attributes/traces:
        actions:
          - key: http.client_latitude
            from_context: CloudFront-Viewer-Latitude
            action: upsert
          - key: http.client_longitude
            from_context: CloudFront-Viewer-Longitude
            action: upsert
    memory_limiter:
        check_interval: 5s
        limit_mib: 448
        spike_limit_mib: 64
    batch:
        send_batch_size: 48
        send_batch_max_size: 48
        timeout: 15s
    transform:
        logs:
            queries:
                - set(attributes["severity_text"], severity_text)
    filter:
        logs:
            exclude:
                match_type: regexp
                record_attributes:
                    - key: severity_text
                      value: "(TRACE|DEBUG)"
    spanmetrics:
        metrics_exporter: prometheus
        dimensions:
            - name: enduser.id
            - name: deployment.environment
            - name: http.status_code
            - name: http.client_ip
            - name: http.client_latitude
            - name: http.client_longitude
            - name: http.method

exporters:
    logging:
        loglevel: ${EXPORTERS_LOGGING_LOGLEVEL}
    otlp:
        endpoint: tempo-eu-west-0.grafana.net:443
        headers:
            authorization: ${EXPORTERS_OTLP_HEADERS_AUTHORIZATION}
            
    prometheusremotewrite:
        endpoint: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        headers:
            authorization: ${EXPORTERS_PROMETHEUSREMOTEWRITE_HEADERS_AUTHORIZATION}
            
    loki:
        endpoint: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
        headers:
            authorization: ${EXPORTERS_LOKI_HEADERS_AUTHORIZATION}
        format: json
        labels:
            attributes:
                container_name: ""
                source: ""
            resource:
                host.name: "hostname"
                
    prometheus:
        endpoint: "${HOSTNAME}:8889"
        metric_expiration: ${EXPORTERS_PROMETHEUS_METRIC_EXPIRATION}

extensions:
    health_check:
service:
    telemetry:
        logs:
            level: ${SERVICE_TELEMETRY_LOGS_LEVEL}
    extensions: [health_check]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [attributes/traces, spanmetrics, memory_limiter, batch]
            exporters: [otlp, logging]
        metrics/spanmetrics:
            # This receiver is just a dummy and never used.
            # Added to pass validation requiring at least one receiver in a pipeline.
            receivers: [otlp/spanmetrics]
            # The metrics_exporter must be present in this list.
            exporters: [prometheus, logging]
        metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [prometheus, logging]
        metrics/prometheus:
            receivers: [prometheus]
            processors: [memory_limiter, batch]
            exporters: [prometheusremotewrite, logging]
        logs:
            receivers: [otlp]
            processors: [transform, filter, memory_limiter, batch]
            exporters: [loki, logging]
```

**Environment**
AWS Elastic Beanstalk Linux v2

**Additional context**
I didn't find any real conseguence of this error, so far.
Otel collector stays up and other metrics are normally exported.
