### ISSUE TITLE
Filelog Receiver formatting logs

### ISSUE THREAD

**Issue by thomasbaldwin** [open-telemetry/opentelemetry-collector-contrib#12653]
I'm using the file log receiver, but I'm unsure of how to get the logs to be in the format I'd like. Here is my current config:

```yaml
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          # Exclude logs from all containers named otel-collector
          - /var/log/pods/*/otel-collector/*.log
        start_at: beginning
        include_file_path: true
        include_file_name: true
        operators:
          # Find out which format is used by kubernetes
          - type: router
            id: get-format
            routes:
              - output: parser-docker
                expr: 'body matches "^\\{"'
              - output: parser-crio
                expr: 'body matches "^[^ Z]+ "'
              - output: parser-containerd
                expr: 'body matches "^[^ Z]+Z"'
          # Parse CRI-O format
          - type: regex_parser
            id: parser-crio
            regex: '^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'
            output: extract_metadata_from_filepath
            timestamp:
              parse_from: attributes.time
              layout_type: gotime
              layout: '2006-01-02T15:04:05.000000000-07:00'
          # Parse CRI-Containerd format
          - type: regex_parser
            id: parser-containerd
            regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'
            output: extract_metadata_from_filepath
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          # Parse Docker format
          - type: json_parser
            id: parser-docker
            output: extract_metadata_from_filepath
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          - type: move
            from: attributes.log
            to: body
          # Extract metadata from file path
          - type: regex_parser
            id: extract_metadata_from_filepath
            regex: '^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]{36})\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$'
            parse_from: attributes["log.file.path"]
          # Rename attributes
          - type: move
            from: attributes.stream
            to: attributes["log.iostream"]
          - type: move
            from: attributes.container_name
            to: attributes["k8s.container.name"]
          - type: move
            from: attributes.namespace
            to: attributes["k8s.namespace.name"]
          - type: move
            from: attributes.pod_name
            to: attributes["k8s.pod.name"]
          - type: move
            from: attributes.restart_count
            to: attributes["k8s.container.restart_count"]
          - type: move
            from: attributes.uid
            to: attributes["k8s.pod.uid"]
          - type: add
            field: attributes["k8s.cluster.name"]
            value: '${CLUSTER_NAME}'

    processors:
      batch:
      batch/2:
        send_batch_size: 10
        send_batch_max_size: 10
        timeout: 10s
    exporters:
      awss3:
        s3uploader:
            region: '${S3_PRIMARY_BUCKET_REGION}'
            s3_bucket: '${S3_PRIMARY_BUCKET_NAME}'
            s3_prefix: '${ACCOUNT_ID}'
            s3_partition: 'minute'
      logging:
        loglevel: error
    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch/2]
          exporters: [logging, awss3]
```

and here is what is exported:

```yaml
{
  "resourceLogs": [
    {
      "resource": {},
      "scopeLogs": [
        {
          "scope": {},
          "logRecords": [
            {
              "timeUnixNano": "1658521825188335333",
              "observedTimeUnixNano": "1658522394913204188",
              "body": {
                "stringValue": "{\"log\":\"Hello World\",\"stream\":\"stdout\",\"time\":\"2022-07-22T20:30:25.188335333Z\"}"
              },
              "attributes": [
                {
                  "key": "log.iostream",
                  "value": {
                    "stringValue": "stdout"
                  }
                },
                {
                  "key": "time",
                  "value": {
                    "stringValue": "2022-07-22T20:30:25.188335333Z"
                  }
                },
                {
                  "key": "k8s.cluster.name",
                  "value": {
                    "stringValue": "test-cluster"
                  }
                },
                {
                  "key": "log.file.path",
                  "value": {
                    "stringValue": "/var/log/pods/16e610ca-09fd-11ed-a137-025697522ef6/sample-pod/0.log"
                  }
                },
                {
                  "key": "log.file.name",
                  "value": {
                    "stringValue": "0.log"
                  }
                },
                {
                  "key": "log",
                  "value": {
                    "stringValue": "Hello World"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            },
            {
              "timeUnixNano": "1658521825209382256",
              "observedTimeUnixNano": "1658522394913217073",
              "body": {
                "stringValue": "{\"log\":\"Hello World\",\"stream\":\"stdout\",\"time\":\"2022-07-22T20:30:25.209382256Z\"}"
              },
              "attributes": [
                {
                  "key": "log.iostream",
                  "value": {
                    "stringValue": "stdout"
                  }
                },
                {
                  "key": "time",
                  "value": {
                    "stringValue": "2022-07-22T20:30:25.188335333Z"
                  }
                },
                {
                  "key": "k8s.cluster.name",
                  "value": {
                    "stringValue": "test-cluster"
                  }
                },
                {
                  "key": "log.file.path",
                  "value": {
                    "stringValue": "/var/log/pods/16e610ca-09fd-11ed-a137-025697522ef6/sample-pod/0.log"
                  }
                },
                {
                  "key": "log.file.name",
                  "value": {
                    "stringValue": "0.log"
                  }
                },
                {
                  "key": "log",
                  "value": {
                    "stringValue": "Hello World again"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            }
          ]
        }
      ]
    }
  ]
}
```

This is what I'd ideally like, is my logs to be formatted like:

```
{
  "logs": "...Raw logs here",
  "kubernetes": {
    "filePath": "filePath here",
    "clusterName": "cluster name here"
  }
}
```

is something like this possible?

**Comment by djaglowski** [comment]
> {
  "logs": "...Raw logs here",
  "kubernetes": {
    "filePath": "filePath here",
    "clusterName": "cluster name here"
  }
}

All log receivers emit data as [`plog.Logs`](https://github.com/open-telemetry/opentelemetry-collector/blob/de51f9e800a1d8a562fb792efccd4d301f69f55a/consumer/logs.go#L28), so it is necessary to have more context on where this json struct would be placed.

---

Possibly some partial solutions:

> "kubernetes": {
    "filePath": "filePath here",
    "clusterName": "cluster name here"
  }

You can set up this structure within the log attributes. Something like:

```
operators:
- type: move
  from: attributes['log.file.path']
  to: attributes['kubernetes']['filePath']
- type: move
  from: attributes['k8s.cluster.name']
  to: attributes['kubernetes']['clusterName']
```

>  "logs": "...Raw logs here",

I believe you are referring to the log body, which you could also move or copy to the log attributes:

```
operators:
- type: move # alternately, use 'copy'
  from: body
  to: attributes['logs']
```

These changes would arrange the structure you specified, within the context of the larger log structure.
