### ISSUE TITLE
New component:  Splunk Enterprise Receiver

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#12667]
## The purpose and use-cases of the new component
For those using self host splunk (Splunk Enterprise), there is a few endpoints being exposed by the indexer cluster that can be captured and help monitor the platform.

## Example configuration for the component
```yaml
splunkenterprise:
  hostname: <host url>
  collection_period: <time>
  metrics:
    splunk.enterprise.cluster.peer.status:
       enabled: true
    # ... I am sure there is more but we'll save it for more feedback from the splunk crew
```

## Telemetry data types supported
Metrics

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?

This is a vendor specific component but I am happy for this component to be a community support receiver

## Sponsor (Optional)

It would be nice to have someone from Splunk @dmitryax , @bogdandrutu as a sponsor for this.
