### ISSUE TITLE
[receiver/k8s_cluster] condition_network_unavailable metric negative value

### ISSUE THREAD

**Issue by yusufcemalcelebi** [open-telemetry/opentelemetry-collector-contrib#12727]
**Describe the bug**
I'm using k8s_cluster receiver to receive node conditions on the EKS cluster. But I'm receiving a negative value (-1) for the `k8s.node.condition_network_unavailable` metric on the Datadog. I'm getting correct values for the receiver's other metrics.

**Steps to reproduce**
I'm using following configuration:
```
config:
  receivers:
    k8s_cluster:
      collection_interval: 10s
      node_conditions_to_report: ["Ready", "MemoryPressure", "DiskPressure", "PIDPressure", "NetworkUnavailable"]
      allocatable_types_to_report: ["cpu","memory", "ephemeral-storage", "storage"]
  service:
    extensions:
      - health_check
    pipelines:
      metrics:
        receivers:
          - k8s_cluster
        processors:
          - memory_limiter
          - batch
          - resourcedetection/eks
          - k8sattributes
          - attributes/basics
        exporters:
          - datadog/api
```

**What did you expect to see?**
I expect to see 0 value for that metric because there is no unavailable node on the cluster. 

**What version did you use?**
I'm using `otel/opentelemetry-collector-contrib:0.54.0` image and EKS cluster with 1.22 version

**Comment by dmitryax** [comment]
@yusufcemalcelebi can you please confirm that it's not caused by the datadog exporter? In order to do that you'd need to replace `datadog` exporter with `logging` exporter with the following configuration and look at the value in the collector's logs:

```yaml
exporters:
  logging:
    loglevel: DEBUG
```
