### ISSUE TITLE
[otlp/http/json receiver]: `scopeSpan` no longer recognized as a valid field

### ISSUE THREAD

**Issue by dyladan** [open-telemetry/opentelemetry-collector-contrib#12726]
This is a high priority bug for JS users. On the most recent release of collector-contrib our JSON span exporter stopped working (unknown if metrics still works). Is it possible there was some sort of change in the http receiver which disallowed `camelCase` identifiers?

Sorry I was not sure if I should create this on the contrib or core collector repo. The failing component is in the core repo, but I am using the contrib image.

**Describe the bug**

When exporting spans to the http receiver we are receiving the following error response:

```
{"code":3,"message":"unknown field \\"scopeSpans\\" in v1.ResourceSpans"}
```

**Steps to reproduce**

Steps in https://github.com/open-telemetry/opentelemetry-js/issues/3115

collector config:

```yaml
receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

exporters:
  logging:
  sentry:
    dsn: <my-self-hosted-sentry>

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,sentry]
```

OpenTelemetry JS setup

```typescript
import * as opentelemetry from '@opentelemetry/sdk-node';
import { diag, DiagConsoleLogger, DiagLogLevel } from '@opentelemetry/api';
import { OTLPTraceExporter } from '@opentelemetry/exporter-trace-otlp-http';
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node';
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';
import { Resource } from '@opentelemetry/resources';

diag.setLogger(new DiagConsoleLogger(), DiagLogLevel.DEBUG);

const exporter = new OTLPTraceExporter({
  url: 'http://localhost:4318/v1/trace',
});

const sdk = new opentelemetry.NodeSDK({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: 'local-ex-node',
  }),
  instrumentations: [getNodeAutoInstrumentations()],
  traceExporter: exporter,
});

sdk
  .start()
  .then(() => {
    console.log('Tracing initialized');
  })
  .catch((error) => console.log('Error initializing tracing', error));

process.on('SIGTERM', () => {
  sdk
    .shutdown()
    .then(() => console.log('Tracing terminated'))
    .catch((error) => console.log('Error terminating tracing', error))
    .finally(() => process.exit(0));
});
```

**What did you expect to see?**

Expected to see spans in the collector

**What did you see instead?**

Error response from collector

**What version did you use?**

docker image: otel/opentelemetry-collector-contrib:latest
