### ISSUE TITLE
k8sattributeProcessor Docs

### ISSUE THREAD

**Issue by anarwal** [open-telemetry/opentelemetry-collector-contrib#12725]
**Describe the bug**
I have been trying to setup config for k8sattribute processor and was unable to get it to work as the docs are incomplete

**Steps to reproduce**

I have used the following configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: kube-system
data:
  config.yaml: |-
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          # Exclude logs from all containers named otel-collector
          - /var/log/pods/*/otel-collector/*.log
        start_at: beginning
        include_file_path: true
        include_file_name: true
    processors:
      batch:
        send_batch_size: 1
        send_batch_max_size: 11
        timeout: 10s
      resourcedetection:
        detectors: [env, eks]
        override: true
      k8sattributes:
      k8sattributes/2:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.cluster.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
          - from: resource_attribute
            name: k8s.pod.uid
          - from: resource_attribute
            name: k8s.pod.ip
          - from: connection
    exporters:
      awss3:
        s3uploader:
            region: '${S3_PRIMARY_BUCKET_REGION}'
            s3_bucket: '${S3_PRIMARY_BUCKET_NAME}'
            s3_prefix: '${ACCOUNT_ID}'
            s3_partition: 'minute'
      logging:
        loglevel: error
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch,resourcedetection,k8sattributes]
          exporters: [logging, awss3]
```

However, I couldn't get it to work without adding operator as mentioned here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/kubernetes/otel-collector.yaml#L66. But the docs do not have any word about adding operators, unless I am missing anything.

**What did you expect to see?**
log file with all the attributes provided in `k8sattribute` block. 

**What did you see instead?**
No metadata for k8s

**Comment by fatsheep9146** [comment]
I think maybe your config file is wrong, the processors `k8sattributes` you used have no content, but  processor`k8sattributes/2` does have contents

so change the following part
```
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch,resourcedetection,k8sattributes]
          exporters: [logging, awss3]
```
into following 
```
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch,resourcedetection,k8sattributes/2]
          exporters: [logging, awss3]
``` 

and try it again?
