### ISSUE TITLE
Elastic Exporter: Otel Collector appears as the service "unknown" in Elastic APM (services inventory & service map)

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-collector-contrib#1275]
**Describe the bug**

When reporting metrics from the collector (e.g. `hostmetrics`), the OpenTelemetry Collector appears in Elastic APM as "unknown" with zero transaction reported.

![image](https://user-images.githubusercontent.com/459691/96160035-b4624100-0f15-11eb-9a59-10af56663969.png)

![image](https://user-images.githubusercontent.com/459691/96160149-dcea3b00-0f15-11eb-9469-8be34b0ebef7.png)

**Steps to reproduce**

Monitor an app with the opentelemetry-java-instrumentation and configure OpenTelemetry Collector to collect hostmetrics.

**What did you expect to see?**

I expected the Elastic APM Service inventory to not report the collector, especially if it is named "unknown" and I didn't expect to see the collector on the Elastic APM Service Map.

An alternative behaviour would be to see it with a meaningful name, e.g. "OpenTelemetry Collector"

**What did you see instead?**

A service "unknown" as showed in the screenshots above

**What version did you use?**
OpenTelemetry Collector Contrib Version: 0.12.0
OpenTelemetry Java Instrumentation Version: 0.8.0

**What config did you use?**

```
extensions:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '127.0.0.1:55680'
  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
      load:
      memory:
#      filesystem:
#      network:

processors:
  batch: null
  queued_retry: null

exporters:
  elastic:
    apm_server_url: 'http://localhost:8200'
    secret_token: 'my_secret_token'
  logging:
    loglevel: info
  jaeger:
    endpoint: 'localhost:14250'
    insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - hostmetrics
      exporters:
        - logging
        - prometheus
        - elastic
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - elastic
#        - jaeger
#        - logging
  extensions: [zpages]
```

**Environment**
OS: MAcOS 10.15.7

**Additional context**
