### ISSUE TITLE
[receiver/filelog] "start_at: end" should be disregarded when loading offsets from storage

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#12769]
**Describe the bug**
When using a storage extension, the receiver should be able to seamlessly resume log file consumption after a restart. However, current behavior will skip lines that were added to a file while the collector was not running. In order to correct the behavior, the receiver should use ignore the `start_at` setting for files who's offsets are retrieved from a storage extension.

**Steps to reproduce**
Sample configuration:
```yaml
receivers:
  filelog:
    include: [foo/*.log]

exporters:
  logging:
    loglevel: debug

extensions:
  file_storage:
    directory: foo/storage

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

- Start the collector and add some lines to the log file. They should be consumed immediately. Offsets should be written to the storage extension in nearly real time.
- Stop the collector.
- Add some lines to the log file. These are the lines that are skipped due to this bug.
- Start the collector. The new lines should be consumed immediately, but they are not.
- Add more lines to the log file. These lines are correctly consumed.
