### ISSUE TITLE
[exporter/prometheusremotewrite] Collector crashes while Scraping Histogram Metrics

### ISSUE THREAD

**Issue by ramyasree0299** [open-telemetry/opentelemetry-collector-contrib#12777]
**Describe the bug**
I'm running Opentelemetry collector contrib v0.56.0 Windows Amd64 binary with OTLP Receiver in Windows machine and I have a client application in Spring boot v2.6.9 using Micrometer Registry OTLP v1.9.2 to publish metrics to collector binary in OTLP Format. But as soon as client application starts publishing the metrics, the collector Crashes.
Related to #7149

**Steps to reproduce**
1. Start otel collector binary with provided config below.
2. From https://start.spring.io/ start a new Spring boot project with v2.6.9 and add below micrometer Dependency
```
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-otlp</artifactId>
      <version>1.9.2</version>
    </dependency>
```
3. Create a ```OTLPMeterRegistry``` Bean to start exposing the metrics in OTLP format and start the application.(The collector publish endpoint will be default i.e; http://localhost:4318/v1/metrics)
```
    @Bean
    public OtlpMeterRegistry otlpMeterRegistry(){
        return new OtlpMeterRegistry();
    }
```

**What did you expect to see?**
Metrics to be _remote written_ to the specified remote write endpoint.

**What did you see instead?**
Collector crashes with below exception
```
panic: runtime error: index out of range [-1]

goroutine 138 [running]:
go.opentelemetry.io/collector/pdata/internal.ImmutableUInt64Slice.At(...)
        go.opentelemetry.io/collector/pdata@v0.56.0/internal/generated_immutable_slice.go:125
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite.addSingleHistogramDataPoint({0xc0002df6d8?}, {0x4591ed?}, {0xc000b3acc0?}, {{0x0?, 0x40e2c5?}, 0xc000285aa0?}, 0x50?)
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite@v0.56.0/helper.go:346 +0xf65
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite.FromMetrics({0x9?}, {{0x0?, 0xb3ebe1c?}, 0xc000285aa0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite@v0.56.0/metrics_to_prw.go:88 +0x74a
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter.(*prwExporter).PushMetrics(0xc000147b90, {0x6179b98, 0xc000b41080}, {0x6179bd0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter@v0.56.0/exporter.go:137 +0xd3
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).export(0x6179bd0?, {0x6179b98?, 0xc000b41080?})
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/metrics.go:65 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000462750, {0x618ecf0, 0xc0001624e0})
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/common.go:225 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc000147c20, {0x618ecf0, 0xc0001624e0})
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/queued_retry.go:176 +0x556
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send(0xc001018450, {0x618ecf0, 0xc0001624e0})
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/metrics.go:132 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x51e46e0?, 0xc0001624e0})
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/queued_retry_inmemory.go:119 +0x5c
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume(0xc0003a7200?, {0x51e46e0?, 0xc0001624e0?})
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/internal/bounded_memory_queue.go:82 +0x2c
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2()
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/internal/bounded_memory_queue.go:69 +0xcd
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers
        go.opentelemetry.io/collector@v0.56.0/exporter/exporterhelper/internal/bounded_memory_queue.go:63 +0x98
```

**What version did you use?**
Version: 0.56.0

**What config did you use?**
Config: 
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
  zipkin:

exporters:
  prometheusremotewrite:
    endpoint: "https://remotewriteurl"
  jaeger:
    endpoint: "some.jaeger.endpoint"
  prometheus:
    endpoint: "127.0.0.1:9091"
  file:
    path: otel-logs.txt

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus, file, prometheusremotewrite ]
    traces:
      receivers: [ otlp,zipkin ]
      exporters: [ jaeger, file ]
  telemetry:
    logs:
      level: "debug"
```

**Environment**
OS: Windows
