### ISSUE TITLE
Elastic Exporter: Elastic APM service graph "Time spent by span type" is empty

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-collector-contrib#1277]
**Describe the bug**

Elastic APM service graph "Time spent by span type" is empty with a message "No data within this time range." when using the OpenTelemetry Java instrumentation. On the other side, when using the Elastic APM Java agent with the same application, the graph is properly filled.

![image](https://user-images.githubusercontent.com/459691/96180883-6c521700-0f33-11eb-8b8f-bf4cf6b79703.png)

 
**Steps to reproduce**

Instrument a java application connecting to a database and to a downstream service and look at the  "Time spent by span type" graph.

Here is a sample with Spring Boot and PostgreSQL: https://github.com/cyrille-leclerc/my-shopping-cart/tree/otel-2020-10-15

**What did you expect to see?**

I expected to see the service graph "Time spent by span type" filled.

**What did you see instead?**

The graph "Time spent by span type" is empty with a message "No data within this time range."

**What version did you use?**

OpenTelemetry Collector Contrib Version: v0.12.0
OpenTelemetry Java Instrumentation Version: v0.8.0

**What config did you use?**

```
extensions:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '127.0.0.1:55680'
  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
      load:
      memory:
#      filesystem:
#      network:

processors:
  batch: null
  queued_retry: null

exporters:
  elastic:
    apm_server_url: 'http://localhost:8200'
    secret_token: 'my_secret_token'
  logging:
    loglevel: info
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - hostmetrics
      exporters:
        - logging
        - prometheus
        - elastic
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - elastic
  extensions: [zpages]
```

**Environment**
OS: MAcOS 10.15.7

**Additional context**
