### ISSUE TITLE
New component: Azure Event Hub Receiver

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#12786]
## The purpose and use-cases of the new component
The Azure Event Hub receiver listens to logs emitted by Azure Event hubs.

## Example configuration for the component
```
receivers:
  azureeventhub:
    connection: Endpoint=sb://namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=superSecret1234=;EntityPath=hubName
    partition: foo
    offset: "1234-5566"
```

## Telemetry data types supported
logs

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?
This is an Azure component - I am not a representative of the vendor.

## Sponsor (Optional)
TODO.
