### ISSUE TITLE
prometheus exporter adding new labels on each scrape

### ISSUE THREAD

**Issue by lchopfpt** [open-telemetry/opentelemetry-collector-contrib#12782]
Metrics exported as 'prometheus' exporter saw additional labels added on each scrape, and each label containing an additional prepended 'exported_' string to it. 

Installed 0.56 otelcol (not contrib) with a basic config of scraping a local node_exporter, and exporting as prometheus.

**Expected to see**
Expected a relatively static number of metrics and labels.  

** Saw instead **
Instead there was a new 'metric' after each scrape because there were new labels each time which ended up bloating the amount of metrics.
```
up{instance="localhost:9464",job="otelcol-prom"} 1
up{exported_instance="localhost:9100",exported_job="prometheus",instance="localhost:9464",job="otelcol-prom"} 0
up{exported_instance="localhost:9464",exported_job="otelcol-prom",instance="localhost:9464",job="otelcol-prom"} 1
up{exported_exported_instance="localhost:9464",exported_exported_job="otelcol-prom",exported_instance="localhost:9100",exported_job="prometheus",instance="localhost:9464",job="otelcol-prom"} 0
```

**What version did you use?**
Version: 0.56.0

**What config did you use?**
Config:
```
  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: "prometheus"
          static_configs:
          - targets: ["localhost:9100"]
        - job_name: otelcol-prom
          static_configs:
          - targets: ['localhost:9464']
...

exporters:
  logging:
    logLevel: debug
  prometheus:
    endpoint: "0.0.0.0:9464"
```
(Noting that I changed the target from fqdn to localhost for the sake of sharing here)

**Environment**
OS: CentOS 7.9

**Additional notes:**
When downgrading to 0.44, and using the same config file, the issue stops.  0.44 was a previous known good state, so had that as a reference.

**Comment by gouthamve** [comment]
Hi, this is not a bug. What is happening is this:

```
node_exporter --> otel_collector --> otel_collector --> otel_collector ....
```

i.e, the metrics "exported" by OTel Collector are being scraped by OTel Collector itself. This is like making Prometheus scrape its own federate endpoint which would cause the same behaviour.

Rather you should do the following:

```
  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: "prometheus"
          static_configs:
          - targets: ["localhost:9100"]
        - job_name: otelcol-prom
          static_configs:
          - targets: ['localhost:8888']  # This is where the collector exposes its internal metrics
```

Use `localhost:8888` to scrape metrics about the Collector.
