### ISSUE TITLE
New component: Cilium Hubble 

### ISSUE THREAD

**Issue by philipcwhite** [open-telemetry/opentelemetry-collector-contrib#12781]
## The purpose and use-cases of the new component

Purpose: To collect trace data from Cilium Hubble.   
Use Case: Hubble provides trace data for L3-L7 network flows within Cilium instrumented (Kubernetes) environments.  This data is extremely useful to troubleshoot network data within clusters. Cilium currently has their own one-off build of the Otel collector specifically built for Hubble data extraction.  We are proposing having this module integrated into the collector-contrib package.  By doing this, the hubble-otel adapter will receive more frequent (security) updates and reach a wider audience for consumption.  

## Example configuration for the component
```
receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55690
      hubble:
        endpoint: ${NODE_IP}:4244 # unix:///var/run/cilium/hubble.sock
        buffer_size: 100
        include_flow_types:
          traces: ["l7"]
        tls:
          insecure_skip_verify: true
          ca_file: /var/run/hubble-tls/ca.crt
          cert_file: /var/run/hubble-tls/client.crt
          key_file: /var/run/hubble-tls/client.key
    processors:
      batch:
        #timeout: 30s
        #send_batch_size: 100

    exporters:
      jaeger:
        endpoint: jaeger.cilium-monitoring.svc.cluster.local:14250
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: info
      pipelines:
        traces:
          receivers: [hubble, otlp]
          processors: [batch]
          exporters: [jaeger]
```

## Telemetry data types supported

The hubble-otel adapter provides network and application trace data.  It shows single hop ingress and egress traffic.  This can then be mapped out via Jaeger, or other topology/trace tools.

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?

Cilium and Hubble are CNCF projects developed and supported by Isovalent.  I am submitting this request as an end user who is working with their product.  I have discussed this integration with their team and they asked that I assist in helping this integration move forward.  Isovalent developed the hubble-otel agent and they will be contributing to this component proposal.

Github Project: hubble-otel 
https://github.com/cilium/hubble-otel
