### ISSUE TITLE
New component: Headers Setter extension for exporters 

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/opentelemetry-collector-contrib#12922]
## The purpose and use-cases of the new component

The `headers_setter` extension implements `configauth.GRPCClientAuthenticator`
and is used to set requests headers in `gRPC` / `HTTP` exporters with values
provided via extension configurations or requests metadata (context).

Use cases include but are not limited to enabling multi-tenancy for observability
backends such as [Tempo](https://grafana.com/oss/tempo/), [Mimir]( https://grafana.com/oss/mimir/), [Loki](https://grafana.com/oss/loki/) and others by setting the `X-Scope-OrgID`
header to the value extracted from the context.

Once the extension implementation https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12892 is accepted and merged, this extension can address the following issues:
- https://github.com/open-telemetry/opentelemetry-collector/issues/5733
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7945

- https://github.com/open-telemetry/opentelemetry-collector/issues/4814
- https://github.com/open-telemetry/opentelemetry-collector/issues/4806
- https://github.com/open-telemetry/opentelemetry-collector/issues/5264

-  We can drop specific multi-tenant implementation in `loki/exporter` https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12415

## Example configuration for the component

Example configuration of the component:
```yaml
extensions:
  headers_setter:
    headers:
      - key: X-Scope-OrgID
        from_context: tenant_id
      - key: User-ID
        value: some_user_id
```

Example of the new component usage to address multi-tenancy use case in Grafana Loki:
```yaml
extensions:
  headers_setter:
    headers:
      - key: X-Scope-OrgID
        from_context: tenant_id

receivers:
  otlp:
    protocols:
      http:
        include_metadata: true

processors:
  nop:

exporters:
  loki:
    labels:
      resource:
        container_id: ""
        container_name: ""
    endpoint: https://localhost:<port>/loki/api/v1/push
    auth:
      authenticator: headers_setter

service:
  extensions: [ headers_setter ]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [nop]
      exporters: [loki]
```      

## Telemetry data types supported

Signal agnostic.

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?

It is not a vendor-specific component. 

## Sponsor (Optional)

@jpkrohling https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12892#issuecomment-1203130484
