### ISSUE TITLE
[exporter/datadog] host info is empty for all the hosts

### ISSUE THREAD

**Issue by dineshg13** [open-telemetry/opentelemetry-collector-contrib#12944]
**Is your feature request related to a problem? Please describe.**
When using datadog exporter, we are unable to see host information for any host on the Datadog UI. 

We can easily verify this by using sample config below. 

```
receivers:
  hostmetrics:
    scrapers:
     load:
    collection_interval: 10s

exporters:
  datadog:
    api:
      key: ${DD_API_KEY}

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [datadog]
```

Once we have host in the UI, we can navigate to the `infrastructure List` to see the details of the host. One the details of page, we currently don't see any information for the host. 

UI:  
![image](https://user-images.githubusercontent.com/2471669/182745959-0992ce37-0829-4487-b639-7f064c9e2b5d.png)

**Describe the solution you'd like**
When sending [hostmeta](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ef6e2bb15f78996f4ee70b5a340cec1da7666fc0/exporter/datadogexporter/internal/metadata/metadata.go#L44-L62) from datadog exporter, it should add Host Info. The host information can be derived by using `https://github.com/DataDog/gohai`
