### ISSUE TITLE
 cannot assign requested address

### ISSUE THREAD

**Issue by wajika** [open-telemetry/opentelemetry-collector-contrib#12975]
This error is not a bug.
After I start the otel container there is an error, I don't know if this error is from k8s or bare metal.
can someone give me some advice?

![image](https://user-images.githubusercontent.com/17058349/182992381-16f09123-2a77-4d4b-990a-b9a9e4d51589.png)

otel: 0.56
prometheus: 2.36.1
kubernetes: v1.20.4

```
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        timeout: 10s
    extensions:
      health_check: {}
      zpages: {}
    exporters:
      prometheus:
        endpoint: "prometheus-k8s.monitoring:9090"
        namespace: "default"
        const_labels:
          "env": "dev"
        send_timestamps: true
        metric_expiration: 180m
        resource_to_telemetry_conversion:
          enabled: true
    service:
      telemetry:
        logs:
          level: "DEBUG"
      extensions: [health_check, zpages]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch,]
          exporters: [prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [zikpin]
```
