### ISSUE TITLE
New component: Syslog exporter

### ISSUE THREAD

**Issue by AndriiChuzhynov** [open-telemetry/opentelemetry-collector-contrib#13000]
## The purpose and use-cases of the new component
Syslog is still widely used in the industry to receive logs from remote servers. 
Even the opentelemetry-collector has a Syslog receiver.
This exporter will help connect  observability stack with Syslog receivers 

This exporter will send logs to the Syslog server in [rfc5424](https://datatracker.ietf.org/doc/html/rfc5424) format.
It's will be possible to send logs by TCP and UDP.

### Structured data
Exporter will add resources and log records attributes as [structured data](https://datatracker.ietf.org/doc/html/rfc5424#section-6.3)
Id of the sd-element can be rewritten by configuration options (meta by default)
Attributes from the resource and log records will be merged since each Syslog record is an independent entity.
`service.name` and `host.hostname` attributes will be excluded from structured data and used as HOSTNAME and APPNAME in the message.

### Retries
There will be a limited or custom retry mechanism. 
Since there are no options to send a batch and no "exactly once" support is Syslog.

## Example configuration for the component
```
syslog:
    endpoint: localhost:5552
    net_protocol: tcp
    sd_config:
      common_sdid: user@12345
      trace_sdid: opentelemetry@12345
      mapping_sdid:
        tag: metadata@12345
      static_sd:
        location@12345:
          env: prod
          loc: bcn
        stats@51719:
          proc: "1"
```
- `endpoint` - Endpoint where to send the data. Error if not set. Could be set with `SYSLOG_HOST` env variable
- `net_protocol` - Defines which network protocol to use. (By default TCP)
- `sd_config` - Custom configuration of structured data
- `sd_config.common_sdid` - Defines which SDID should be used for attributes. (`meta` by default)
- `sd_config.trace_sdid` - Defines which SDID should be used for trace_id and span_id attributes. (`meta` by default)
- `sd_config.mapping_sdid` - Key value list. Defines custom SDID for the specific attribute names.
    For example in the config all attributes will have SDID `user@12345` but `tag` attribute will have `metadata@12345` SDID
- `sd_config.static_sd` - Defines structured data that will be added to each log entry. In format: SDID: key:value

## Telemetry data types supported
This exporter will export only logs 

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?
No, it is not a vendor component.
