### ISSUE TITLE
Kafka exporter attempts to connect to localhost despite broker specified in config

### ISSUE THREAD

**Issue by truekonrads** [open-telemetry/opentelemetry-collector-contrib#13114]
**Describe the bug**
Kafka exporter attempts to connect to localhost despite broker specified in config. The brokers setting in the configuration file is specified and the configuration is being read (e.g. if I specify an invalid broker value the collector won't start at all). The error message is:
`
2022-08-09T05:48:32.018Z        info    exporterhelper/queued_retry.go:215      Exporting failed. Will retry the request after interval.     {"kind": "exporter", "data_type": "traces", "name": "kafka", "error": "Failed to deliver 1 messages due to dial tcp 127.0.0.1:9092: connect: connection refused", "interval": "31.504407615s"}
`

**Steps to reproduce**
Sample collector config:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  kafka:
    protocol_version: 2.0.0
    encoding: otlp_json
    brokers:
      - broker:9092  #Broker is hostname of the broker
service:
  pipelines:
    traces:
          receivers: [otlp]
#          processors: [batch]
          exporters: [kafka]
```

**What did you expect to see?**
I expected collector to send to kafka broker

**What did you see instead?**
`
2022-08-09T05:48:32.018Z        info    exporterhelper/queued_retry.go:215      Exporting failed. Will retry the request after interval.     {"kind": "exporter", "data_type": "traces", "name": "kafka", "error": "Failed to deliver 1 messages due to dial tcp 127.0.0.1:9092: connect: connection refused", "interval": "31.504407615s"}
`

**What version did you use?**
Latest docker image: ```otel/opentelemetry-collector```

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
