### ISSUE TITLE
signalfx exporter unknow on aws-otel-collector (using opentelemetry-collector v0.56.0)

### ISSUE THREAD

**Issue by jpOlivo-uala** [open-telemetry/opentelemetry-collector-contrib#13163]
**Describe the bug**
I am using the lambda layer `arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-collector-arm64-ver-0-56-0:1` which contains [ADOT Collector for Lambda v0.20.0](https://github.com/aws-observability/aws-otel-collector/blob/v0.20.0/README.md). This implementation uses opentelemetry-collector v0.56.0

According to documentation on v0.20.0 the signalfx exporter is supported, but when i try use it on my collector.yaml config is not recognized:

> Failed to start the extension: failed to get config: cannot unmarshal the configuration: unknown exporters type "signalfx" for "signalfx" (valid values: [awsemf awsprometheusremotewrite prometheus prometheusremotewrite logging otlp otlphttp awsxray])

**Steps to reproduce**
1. Instrument a Go service on Lambda using layers. See this [guide](https://aws-otel.github.io/docs/getting-started/lambda/lambda-go) 
2. Add the environment variable to lambda config `OPENTELEMETRY_COLLECTOR_CONFIG_FILE = /var/task/collector.yaml`
3. Define the `collector.yaml` as:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  awsxray:
  signalfx:
    access_token: your access token
    realm: your realm
    send_compatible_metrics: true
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, awsxray, signalfx]
```
4. Attach the collector config to with your code
5. Test the lambda function and check the logs

**What did you expect to see?**
I expect that the traces being exported to SignalFx platform due that `aws-otel-collector v0.2.0` uses `opentelemetry-collector v0.56.0` and the `signalfx` exporter is available on this version

**What did you see instead?**
I see that the signalfx exporter is unknow

**What version did you use?**
ver-0-56-0

**What config did you use?**
See config above

**Environment**

**Additional context**
Documentation used by this implementation:
- https://aws-otel.github.io/docs/releases#whats-included-in-the-aws-distro-for-opentelemetry-collector
- https://github.com/aws-observability/aws-otel-collector/blob/v0.20.0/README.md
- https://aws-otel.github.io/docs/getting-started/lambda/lambda-go
- https://github.com/aws-observability/aws-otel-collector/blob/v0.20.0/README.md
