### ISSUE TITLE
[pkg/stanza] SeverityText is not properly preserved

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#13263]
**Describe the bug**
SeverityText is held on the stanza entry, but during conversion, is dropped for a SeverityText derived from the SeverityNumber.

**Steps to reproduce**
Using the following config:
<details>
  <summary>Config</summary>

```yaml
receivers:
  filelog:
    include:
      - local/test.log
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<severity>\w+) .*$'
        severity:
          parse_from: attributes.severity
          mapping:
            info: "INFO_SEVERITY"

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
  telemetry:
    metrics:
      level: none
```
</details>

<details>
  <summary>Sample Log</summary>

```
INFO_SEVERITY this is some info
```
</details>

**What did you expect to see?**
I expect SeverityText on the emitted log record to be "INFO_SEVERITY"

**What did you see instead?**
The SeverityText is "Info"

**What version did you use?**
Version: 73b3ae5be3

**Additional context**
The severity text is preserved on the stanza entry, but is not mapped to the OTel entry:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4ac2eb5aa2673ffa203e8cba71e0369b4f3c4159/pkg/stanza/adapter/converter.go#L341
