### ISSUE TITLE
Improve doc comments on configuration structs and fields

### ISSUE THREAD

**Issue by pmcollins** [open-telemetry/opentelemetry-collector-contrib#13384]
**Describe the bug**
Doc comments on structs (such as [this one](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/config.go)) and their members (as well as on type definitions used by config structs, recursively) get picked up by the [configschema library](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/configschema) and end up in [documentation](https://github.com/pmcollins/opentelemetry-collector/blob/master/receiver/otlpreceiver/config.md) generated by the [docsgen](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/configschema/docsgen) command (among other places to come). These comments are typically helpful and relevant, but since developers are generally not aware that their comments end up getting published to tools and markdown files, they are occasionally missing or could be improved.

**Additional context**
This issue is the result of a suggestion in a PR comment https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12620#discussion_r927384769

**Comment by dmitryax** [comment]
I'm still not sure that the format that we get as [the result](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/redisreceiver/config.md) is what we would like to keep going forward.

I'm curious if regular yaml would be an option to consider instead, e.g.:

```yaml
// Doc string for the `option_1` taken from go doc comments.
option_1: "default_value"

// Doc string for `option_2`.
option_2: 

  // Doc string for `embedded_field_1`.
  embedded_field_1: 0

  // Doc string for `embedded_field_2`.
  embedded_field_2: ""
```

@pmcollins @mx-psi Do you have any other ideas on how to improve readability?

cc @open-telemetry/collector-contrib-approvers

**Comment by neelayu** [comment]
I have created a [PR 5943](https://github.com/open-telemetry/opentelemetry-collector/pull/5943) in the core repo which makes use of this tool.

**Comment by mx-psi** [comment]
> I'm curious if regular yaml would be an option to consider instead, e.g.

How would we add further metadata? For example, how would you indicate that an option is deprecated or if its content is sensitive? These are things that we may add in the future as struct tags/type alias and it's unclear to me how we would write down this information in the YAML format.

Barring that YAML is more intuitive to me for this, but not everyone is familiar with YAML so I don't think my intuition is representative of anything here :)

**Comment by dmitryax** [comment]
> How would we add further metadata? For example, how would you indicate that an option is deprecated or if its content is sensitive? These are things that we may add in the future as struct tags/type alias and it's unclear to me how we would write down this information in the YAML format.

Sorry, I don't understand these concerns. Can you please provide a specific example?

> Barring that YAML is more intuitive to me for this, but not everyone is familiar with YAML so I don't think my intuition is representative of anything here :)

This documentation is intended to be used for preparing a YAML config file. So anyone who is using a collector has to be familiar with YAML anyway. Having documentation in YAML format seems the most intuitive format to me. 

The workflow I would like to have as a user:
1. Copy the generated YAML config with default values
2. Put it in my own config
3. Read comments of the sections I'm interested in
4. Remove sections where default values are suitable for me
5. Update other sections for my preferences.

**Comment by mx-psi** [comment]
Okay, you have convinced me that this makes the most sense :) 
 
For the 'further metadata' question, I guess we can just append the info to a comment. For example, if we have an `awesomevendor` exporter with a deprecated and sensitive `token` field, we could eventually have something like this:

```yaml
awesomevendor:
  # token is the API token for AwesomeVendor.
  #
  # Sensitive:  This is a sensitive field. Read our security recommendations at: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security.md
  # Deprecated: Use `api_token` instead.
  token: ""
```
