### ISSUE TITLE
[receiver/postgresql] Query Metrics

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#13382]
**Is your feature request related to a problem? Please describe.**

Metrics can be sources from [`pg_stat_statements`](https://www.postgresql.org/docs/current/pgstatstatements.html#id-1.11.7.39.6)  however it comes with some design implications.

**Describe the solution you'd like**

First of all is the topology of a given query metric. My initial thoughts were something like this

resource attributes
```
postgresql.query.id
postgresql.query.text
postgresql.query.user.id
postgresql.database.name
```

With metrics I'm proposing to add:

```
postgresql.query.block.count
postgresql.query.count
postgresql.query.duration.average
postgresql.query.duration.total
```

These metrics are valuable to get from a performance analysis perspective, as many application bottlenecks can arise from poor query performance. It would be greatly beneficial to get these in to identify queries that may have longer average execution times or are culprits of high disk usage.

However even in my local test database instance, this quickly racks up the number of resources per collection. It is most likely required that we have a control flow on how we emit the query results.

 My initial thought was just a boolean flag:
 
```yaml
postgresql:
    endpoint: localhost:5432
    transport: tcp
    ...
    collect_queries: true
```

But I could imagine users wanting to monitor a select number of queries and no more. 

I also could imagine a more robust object that perhaps can fine tune a limited number of results, albeit at the cost of complexity.

```yaml
postgresql:
    endpoint: localhost:5432
    transport: tcp
    ...
    query_settings:
      enabled: true
      limit: 10
      order_by: slowest_execution_time | fastest_execution_time
```

I'd love to hear thoughts on this one ^

Other notes:

- This feature also only is applicable for postgres versions > 10.
- Query Text and ID are only available for super users

**Describe alternatives you've considered**

Main concern is how we want to reign in the number of query resources, I've come up with two suggestions, however they both have their pros and cons.

I also considered removing the query text from resource attributes however from a usability standpoint it seems less ideal. 

**Additional context**

- Will have a draft PR going with the boolean flag up soon.
- Initial component enhancement #12338 

Would love some help/guidance to help find a way to best contribute these 😄
