### ISSUE TITLE
New component: Instana Exporter

### ISSUE THREAD

**Issue by hickeyma** [open-telemetry/opentelemetry-collector-contrib#13395]
## The purpose and use-cases of the new component

The Instana exporter converts OpenTelemetry trace data to Instana content and then sends it to the [Instana Backend](https://www.ibm.com/docs/en/instana-observability/current?topic=references-getting-started-instana).

## Example configuration for the component

The configuration parameters are:

- endpoint: The Instana backend endpoint that the Exporter connects to. It depends on your region and it starts with `https://serverless-`. It corresponds to the Instana environment variable `INSTANA_ENDPOINT_URL`.
- agent_key: Your Instana Agent key. The same agent key can be used for host agents and serverless monitoring. It corresponds to the Instana environment variable `INSTANA_AGENT_KEY`.

### Example:

```yaml
[...]

exporters:
  instana:
    endpoint: ${INSTANA_ENDPOINT_URL}
    agent_key: ${INSTANA_AGENT_KEY}

[...]

service:
  pipelines:
    traces:
      exporters: [instana]

[...]
```

## Telemetry data types supported

Trace

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?

Yes

## Sponsor (Optional)

@jpkrohling
