### ISSUE TITLE
[metricstransformprocessor] Enable batch operation (all_metrics) for processor operations

### ISSUE THREAD

**Issue by hossain-rayhan** [open-telemetry/opentelemetry-collector-contrib#1342]
**Is your feature request related to a problem? Please describe.**
`metricstransformprocessor` introduces a new batch operation for `convert_resource_attributes_to_metric_labels` (#1337). When customer put `metric_name=all_metrics`, it converts all the resource attributes to metric labels and it applies to all the metric data points. This batch operation would be helpful for other operations (e.g. `add_label`, `update_label` etc.) as well.

**Describe the solution you'd like**
The following config will update the label for all metric data points.
```
metricstransform:
        transforms:
            - metric_name: all_metrics
              action: update
              operations:
                - action: update_label
                  label: label
                  new_label: new_label
```
