### ISSUE TITLE
k8sattributesprocessor doesn't get pod info for new pods

### ISSUE THREAD

**Issue by willthames** [open-telemetry/opentelemetry-collector-contrib#13619]
**Describe the bug**
While k8sattributesprocessor correctly adds pod attributes to pods that exist when the collector is started, restarting a pod causes the processor to no longer add attributes

**Steps to reproduce**
Add k8sattributesprocessor with a config like that below, check that the pod attributes are coming through ok (the below has traces set to log, and collector log level set to debug), and then restart a pod (I could reproduce using `kubectl rollout restart deploy $deployment`)

**What did you expect to see?**
k8s.pod.name etc added to the spans from the pod

**What did you see instead?**
Span contains k8s.pod.ip but no other attributes

**What version did you use?**
0.58.0

**What config did you use?**
```
exporters:
  logging:
    loglevel: warn
  logging/1:
    loglevel: debug
extensions:
  health_check: {}
  memory_ballast: {}
  zpages:
    endpoint: 0.0.0.0:55679
processors:
  batch:
    timeout: 10s
  filter:
    spans:
      exclude:
        attributes:
        - Key: http.path_group
          Value: (/ping|/actuator/health|/actuator/health/liveness|/actuator/health/readiness|/actuator/prometheus)
        match_type: regexp
  k8sattributes:
    auth_type: serviceAccount
    extract:
      labels:
      - from: pod
        key: env
        tag_name: env
      - from: pod
        key: service
        tag_name: service
      - from: pod
        key: version
        tag_name: version
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: ip
    - sources:
      - from: connection
    - sources:
      - from: resource_attribute
        name: host.name
  memory_limiter:
    check_interval: 5s
    limit_mib: 1638
    spike_limit_mib: 512
  resourcedetection:
    detectors:
    - env
    override: false
    timeout: 10s
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${MY_POD_IP}:8888
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    logs:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - logging
      processors:
      - k8sattributes
      - memory_limiter
      - batch
      receivers:
      - otlp
      - prometheus
    traces:
      exporters:
      - datadog
      - logging/1
      processors:
      - filter
      - memory_limiter
      - resourcedetection
      - k8sattributes
      - batch
      receivers:
      - otlp
      - jaeger
      - zipkin
  telemetry:
    metrics:
      address: 0.0.0.0:8888
    logs:
      level: "debug"
```

**Environment**
Kubernetes on EKS

**Additional context**

Here's the collector debug log entry for a restarted pod that it's refusing to annotate:
```
2022-08-25T08:18:18.075Z	debug	k8sattributesprocessor@v0.58.0/processor.go:111	evaluating pod identifier	{"kind": "processor", "name": "k8sattributes", "pipeline": "traces", "value": [{"Source":{"From":"connection","Name":""},"Value":"100.94.45.162"},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""}]}
```

After that I expect to see

```
2022-08-25T08:28:22.882Z	debug	k8sattributesprocessor@v0.58.0/processor.go:125	getting the pod	{"kind": "processor", "name": "k8sattributes", "pipeline": "traces", "pod": {"Name":"redacted-df69c966-csngn","Address":"100.94.45.162","PodUID":"dca53e26-064f-4dcf-be1f-340b60fc67ea","Attributes":{"env":"test","k8s.deployment.name":"redacted","k8s.namespace.name":"test","k8s.node.name":"ip-172-18-13-74.us-west-2.compute.internal","k8s.pod.name":"redacted-df69c966-csngn","k8s.pod.start_time":"2022-08-25 08:06:55 +0000 UTC","k8s.pod.uid":"dca53e26-064f-4dcf-be1f-340b60fc67ea","service":"redacted","version":"ce402ad"},"StartTime":"2022-08-25T08:06:55Z","Ignore":false,"Namespace":"test","HostNetwork":false,"Containers":null,"DeletedAt":"0001-01-01T00:00:00Z"}}
```

Which is what I see when I restarted the collector
