### ISSUE TITLE
[recievers/filelog] - key_value_parser not registered

### ISSUE THREAD

**Issue by crobertson-conga** [open-telemetry/opentelemetry-collector-contrib#13631]
**Describe the bug**
The key value parser from stanza was merged in response to https://github.com/open-telemetry/opentelemetry-log-collection/issues/455

However, it was never registered, so cannot be used as an operator in the filelog parser receiver. 

**Steps to reproduce**
Have a operator step in a filelog receiver that uses type key_value_parser

in your filelog reciever

**What did you expect to see?**
key=value logs being parsed

**What did you see instead?**
An error upon startup:

Error: cannot build pipelines: failed to create "filelog" receiver, in pipeline "logs": unsupported type 'key_value_parser

**What version did you use?**
Version: 0.58.0

**What config did you use?**
```
config:
  receivers:
    filelog:
      include:
        - /var/log/pods/*/*/*.log
      exclude: []
      operators:
        - type: key_value_parser
          id: general-body-logfmt
          output: severity-parser-0
          parse_from: body
```

**Environment**
Doesn't matter

**Additional context**
Should be a matter of adding a new registration at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/7e14323b53770700e54e1edaa2a0ecb91378bb3e/pkg/stanza/adapter/register.go#L21 and updating the documentation accordingly
