### ISSUE TITLE
prometheus_simple metrics not ending up in prometheus exporter

### ISSUE THREAD

**Issue by ekarlso** [open-telemetry/opentelemetry-collector-contrib#1367]
**Describe the bug**
Metrics that are collected by a prometheus_simple receiver and routed to a prometheus exporter is not showing up in the prometheus' exporters endpoint.

**Steps to reproduce**
Having a application with a /metrics endpoint point this config to it and you will see the metrics coming up in the logs but not in the exported metrics.

**What did you expect to see?**
Metrics should be ending up in <addr>:8889/metrics that has been collected in the downstream service.

**What did you see instead?**
No metrics at all

**What version did you use?**
0.13.0

**What config did you use?**

```
receivers:
  prometheus_simple:
    endpoint: 172.17.0.1:8080
    # path: metrics
    collection_interval: 10s

processors:
  queued_retry:
  batch:

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: "0.0.0.0:55679"

exporters:
  logging:
    loglevel: debug

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1
      "another label": spaced value
    # send_timestamps: true

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers:
        - prometheus_simple
      exporters:
        - logging
        # - prometheusremotewrite
        - prometheus
```

**Environment**
Ubuntu 20.04
Docker collector image 0.13.0

**Additional context**
N/A
