### ISSUE TITLE
New component: Logicmonitor exporter

### ISSUE THREAD

**Issue by khyatigandhi6** [open-telemetry/opentelemetry-collector-contrib#13727]
## The purpose and use-cases of the new component
Logicmonitor exporter will send trace and log data to Logicmonitor platform (https://www.logicmonitor.com/).

### Configuration Options
The following configuration options are supported:

`url (required)`: The address to send logs and traces\
`apitoken` : API Token of Logicmonitor\
`headers`: Headers of POST requests\
`log_batching_enabled`(default = true) : The flag to enable/disable logs batching\
`log_batching_interval`(default = 10s) : The time interval for log batching
### Example Configuration
Ingestion through API Token

```yaml
  exporters:
    logicmonitor:
      url: "https://<company_name>.logicmonitor.com/rest"
      apitoken:
        access_id: "<access_id of logicmonitor>"
        access_key: "<access_key of logicmonitor>"
```
OR 

Ingestion through Bearer token

```yaml
  exporters:
    logicmonitor:
      url: "https://<company_name>.logicmonitor.com/rest"
      headers:
        Authorization: Bearer <bearer token of logicmonitor>
```

## Telemetry data types supported
Traces and logs

## Is this a vendor-specific component? If so, are you proposing to contribute this as a representative of the vendor?
Yes it is a vendor-specific component.

## Sponsor (Optional)
No sponsor as of now. Help me find a sponsor.
