### ISSUE TITLE
[loadbalancingexporter] Not properly batching service traces

### ISSUE THREAD

**Issue by crobertson-conga** [open-telemetry/opentelemetry-collector-contrib#13826]
**Describe the bug**
New loadbalancingexporter option for grouping traces by service name is sending all traces in a block every time instead of splitting up the set of traces to those that only belong to the specific export.

**Steps to reproduce**
Use new `routing_key: service` option to start splitting up the traces by service.  Have at least 2 receiving collectors.  In the receiving collectors, use a resource detection processor to augment the trace payload so you can see which collector is receiving a trace.

**What did you expect to see?**
All traces from a specific service name should have the same receiving processor

**What did you see instead?**
Traces from a specific service name went to both processors.

**What version did you use?**
0.59.0

**What config did you use?**
```
      loadbalancing/spanmetrics:
        routing_key: service
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          dns:
            hostname: <some_k8)sservice_to_target_collectors>
            port: 4317
            interval: 1m
```

**Environment**
Doesn't matter

**Additional context**
