### ISSUE TITLE
[exporter/clickhouseexporter] Clickhouse export fail due to plog.LogRecordFlags unable to convert to UInt32

### ISSUE THREAD

**Issue by gen-xu** [open-telemetry/opentelemetry-collector-contrib#13843]
**Describe the bug**
Clickhouse export fail because clickhouse-go is unable to convert plog.LogRecordFlags into UInt32

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.
Configure clickhouse exporter with default values and send logs then the error should pop out.

**What did you expect to see?**
A clear and concise description of what you expected to see.
OpenTelemetry Collector should export to Clickhouse database.

**What did you see instead?**
A clear and concise description of what you saw instead.
```
 2022-09-02T09:11:06.767Z        info    exporterhelper/queued_retry.go:427      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "data_type": "logs", "name": "clickhouse", "error": "ExecContext:clickhouse [AppendRow]: TraceFlags clickhouse [AppendRow]: converting plog.LogRecordFlags to UInt32 is unsupported", "interval": "21.589639508s"}
```

**What version did you use?**
Version: v0.59.0

**What config did you use?**
Config: 
```yaml
extensions:
  health_check:
  
receivers:
  otlp:
    grpc:
    http:

processors:
  batch:
      timeout: 1s

exporters:
  clickhouse:
    dsn: clickhouse://default:password@localhost:9000/default
    ttl_days: 3
    timeout: 5s
    logs_table_name: otel_logs
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  logging:
    logLevel: info

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - clickhouse
        - logging
  extensions: [health_check]

```

**Environment**
Docker Image: otel/opentelemetry-collector-contrib:0.59.0
Platform: arm64
OS: Ubuntu 22.04
