### ISSUE TITLE
Scraped Prometheus Metric Metadata Missing

### ISSUE THREAD

**Issue by awiddersheim** [open-telemetry/opentelemetry-collector-contrib#13849]
**Describe the bug**
We use the otel-collector to scrape metrics which have metadata about them. The best example of this is metrics that come from HAProxy's Prometheus exporter. When the otel-collector ingests these and then sends them to Prometheus using the `prometheusremotewrite` exporter, the metadata doesn't seem to make it. That said, the metadata does appear when using the logging exporter.

**Steps to reproduce**
Scrape metrics with metadata associated with them and you will not see them. For example, the following is in the logs:

```
Descriptor:
     -> Name: haproxy_frontend_http_requests_total
     -> Description: Total number of HTTP requests processed by this object since the worker process started
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
```

You won't see this in Grafana for example:

![image](https://user-images.githubusercontent.com/3237256/188213063-735765a9-48b6-478d-86e2-c3285f855827.png)

**What did you expect to see?**

I expected to see something similar to what is described [in this Grafana article](https://grafana.com/blog/2020/06/15/how-we-made-working-with-prometheus-easier-with-metric-metadata-in-grafanas-explore-view/):

![image](https://user-images.githubusercontent.com/3237256/188213256-75ec6491-902f-4d14-88e6-004a7ad96abd.png)

**What did you see instead?**

![image](https://user-images.githubusercontent.com/3237256/188213063-735765a9-48b6-478d-86e2-c3285f855827.png)

**What version did you use?**

```
aws-otel-collector:v0.20.0
```

**What config did you use?**

A trimmed down look at the basics of the config we are using:

```
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 15s
          static_configs:
            - targets:
              - sometarget

exporters:
   # log level, defaults to info automatically on all outputs
  logging/metrics:
    loglevel: debug

  prometheusremotewrite:
    endpoint: <some_amazon_managed_prometheus_workspace>/api/v1/remote_write
    auth:
      authenticator: sigv4auth
    resource_to_telemetry_conversion:
      enabled: true

service:
  extensions:
    - sigv4auth
  pipelines:
    metrics:
      receivers:
        - prometheus
      exporters:
        - logging/metrics
        - prometheusremotewrite
```

**Environment**

Amazon Linux

**Additional context**
