### ISSUE TITLE
[chrony receiver] Incorrect socket type

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#13862]
**Describe the bug**
When trying to connect to chronyd via the unix socket, the wrong unix socket type was used meaning that they were unable to communicate.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

1. Having chronyd running on the same domain
2. configure chrony reciever to read from socket
3. run receiver

**What did you expect to see?**
A clear and concise description of what you expected to see.

Data should be captured from the receiver and be visible via a configured exporter.

**What did you see instead?**
A clear and concise description of what you saw instead.

The receiver fails to capture data.

**What version did you use?**
Version: v0.58.0

**What config did you use?**
Config:
```yaml
receivers:
   chrony:
      endpoint: "unix://var/run/chrony/chrony.sock
# The rest is ignored because it should be enough to reproduce.
```

**Environment**
OS: MacOS
Compiler(if manually compiled): go.1.19

**Additional context**
