### ISSUE TITLE
[processor/tailsampling] SpanCount sampler makes incorrect decision on high volume of spans

### ISSUE THREAD

**Issue by Symbianx** [open-telemetry/opentelemetry-collector-contrib#13865]
**Describe the bug**
Sometimes, the SpanCount sampler makes the incorrect decision even though there's many spans coming in for the same trace id. This is more likely to happen when there's a high volume of spans and traces coming in to the processor.

After looking at the code, it seems this might be caused by the internal batching behaviour of the processor.

**What version did you use?**
v0.54.0

**What config did you use?**
``` yaml
processors:
  tail_sampling:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
          {
            name: test-policy-8,
            type: span_count,
            span_count: {min_spans: 2}
          }
      ]
```

**Environment**
Docker image 
  OS: Alpine
Compiler(if manually compiled): go 1.18.3
