### ISSUE TITLE
SAPM exporter: sending_queue is not enabled

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#1389]
The  sending_queue doesn't seem to be enabled for SAPM exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2d1a6e6beffb93ef12b7c8df3fe44e8c8e8752bc/exporter/sapmexporter/exporter.go#L80

Trying to send using this config doesn't enable the queue:
```yaml
sapm:
    access_token: "$ACCESS_TOKEN"
    endpoint: "https://ingest.us1.signalfx.com/v2/trace"
    sending_queue:
      enabled: true
      num_consumers: 16
      queue_size: 100000
    retry_on_failure:
      enabled: true
```
