### ISSUE TITLE
[receiver/elasticsearchreceiver] collect elasticsearch.cluster.state_update.* metrics

### ISSUE THREAD

**Issue by JonathanWamsley** [open-telemetry/opentelemetry-collector-contrib#13930]
**Describe the bug**
The elasticsearch receiver is not collecting the `elasticsearch.cluster.state_update.time` and `elasticsearch.cluster.state_update.time` correctly.

The sample payload for the `elasticsearch.cluster.state_update.*` metrics are: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/84ec43271330c6e1bfaf5c1483042de04798fd10/receiver/elasticsearchreceiver/testdata/sample_payloads/nodes_linux.json#L423-L458

There is a `discovery` field path that was left out in the client request path https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/84ec43271330c6e1bfaf5c1483042de04798fd10/receiver/elasticsearchreceiver/client.go#L85

To validate `elasticsearch.cluster.state_update.*` are collected, an integration test should be updated. However, the `elasticsearch.cluster.state_update.*` metrics were introduced in [7.16](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/release-notes-7.16.0.html). Therefore a new integration test for 7.16 is required for validation. The metric should version requirement should also be noted in the README.

[ ] add discovery in client request path, validate with 7.16 integration test

**Steps to reproduce**
Running the collector with es

**What did you expect to see?**
`elasticsearch.cluster.state_update.*` metrics

**What did you see instead?**
Missing `elasticsearch.cluster.state_update.*` metrics

**What version did you use?**
v0.59.0

**What config did you use?**
```yaml
receivers:
  elasticsearch:
    metrics:
      elasticsearch.node.fs.disk.available:
        enabled: true
    nodes: [ "_local" ]
    skip_cluster_metrics: false
    endpoint: http://localhost:9200
    collection_interval: 10s

exporters:
  logging:
    loglevel: debug
  file:
    path: ./es.json

service:
  pipelines:
    metrics:
      receivers: [elasticsearch]
      exporters: [logging, file]    
```

**Environment**
ES 7.9, 7.17
