### ISSUE TITLE
[Feature Request] [Extension] ECS Service Discovery for Prometheus

### ISSUE THREAD

**Issue by kohrapha** [open-telemetry/opentelemetry-collector-contrib#1395]
**Is your feature request related to a problem? Please describe.**
Customers might want to perform ECS Service Discovery for Prometheus metric scraping in their pipeline. Currently, there is no option to perform this functionality. 

**Describe the solution you'd like**
Our proposal is to create a new extension that performs this ECS Service Discovery logic for the Prometheus receiver. This extension would invoke a separate process that would query ECS API for task metadata and output the discovered list of scrape targets to a defined output file that the Prometheus receiver can scrape from (configured via `file_sd_configs`). This functionality would be similar to the ECS Service Discovery logic in AWS CloudWatch. More info of how this is done in the CloudWatch Agent can be found in [this README](https://github.com/aws/amazon-cloudwatch-agent/blob/master/internal/ecsservicediscovery/README.md) and the [online documentation](https://docs.aws.amazon.com/en_en/AmazonCloudWatch/latest/monitoring/ContainerInsights-Prometheus-Setup-autodiscovery-ecs.html).

**Describe alternatives you've considered**
- Implement as part of Prometheus receiver to support ECS service discovery. There was an earlier proposal for this that was rejected because the ECS API can be throttled and is expensive to call.
- Implement this service discovery in a wrapper around Otel Collector. This would not make the functionality available to all customers using the collector.

**Comment by bogdandrutu** [comment]
@jrcamp can you please comment and propose a solution here?

**Comment by jrcamp** [comment]
Take a look at:

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/extension/observer
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/receiver/receivercreator

I think you should be able to add an ecs observer that works with receiver_creator to dynamically create a prometheus_simple receiver. Would this do what you want?

Also take a look at the proposal here for adding additional resource attributes: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1333. Would there be resource attributes you would want to add by default from the observed ecs endpoint as well?

**Comment by kohrapha** [comment]
Thanks @jrcamp for the suggestion! I looked into this and it looks like it might suit our use case. How expensive would it be to dynamically create new receivers based on each newly discovered scrape target? Our original proposal would only require one Prometheus receiver where we would just update its scrape targets in the config file. Is this overhead significant?

**Comment by jrcamp** [comment]
@kohrapha In general these dynamic receivers should not have much overhead. I can't say for sure about the Prometheus receiver because it's quite complex. In the future we will probably simplify the prometheus_simple receiver to only support the Prometheus protocol instead of wrapping the prometheus receiver which has a lot of functionality and overhead we don't need. (Prometheus is basically an agent into itself, but for our purposes we mainly care about the protocol.)

This is a primary use case of ours so if there are any performance issues we will have a vested interest in making sure they are addressed.

**Comment by kohrapha** [comment]
@jrcamp the number of Prometheus targets is highly dependent on the customer's configuration. We can expect a single agent to retrieve metrics from 2000 targets. Having one receiver per target might be a bit overkill and resource-intensive.

**Comment by kohrapha** [comment]
@jrcamp thinking more about this approach, would it be possible instead to just spawn one Prometheus receiver at init time and then only perform updates to that receiver via the update endpoint API? This method requires that a Prometheus receiver can have multiple targets, but it _seems_ like currently we can only configure one target per endpoint/receiver?

**Comment by jrcamp** [comment]
receiver_creator is built around having a single instance per-target for purposes of starting and stoping scraping as well as for adding additional resource attributes linked above. Changing that assumption will require non-trivial changes.

Before we go down that path we should validate whether 2000 targets are a problem. It's not clear to me that whether you have 2000 receivers scraping 1 host each or 1 receiver scraping 2000 hosts that the later will be way more efficient. I think it needs to be tested to say for sure. If the current prometheus receiver has too much overhead we can add one that only does the prometheus protocol.

Can you gather some hard data to remove some of the unknowns?

**Comment by kohrapha** [comment]
Hi @jrcamp, I spent some time this week to come up with an experiment to test the above hypothesis. In this experiment, I have 2 set ups:
1. Setup 1 has one receiver per endpoint, in which I used the k8sobserver + receivercreator
```yaml
extensions:
  k8s_observer:
    auth_type: serviceAccount

receivers:
  receiver_creator:
    # Name of the extensions to watch for endpoints to start and stop.
    watch_observers: [k8s_observer]
    receivers:
      prometheus_simple:
        rule: type.pod && labels["app"] == "prom-app"
        config:
          metrics_path: /metrics
          endpoint: '`endpoint`:8081'

exporters:
  logging:

service:
  extensions: [k8s_observer]
  pipelines:
    metrics:
      receivers: [receiver_creator]
      exporters: [logging]
```
2. Setup 2 has one receiver for all endpoints, where I used the in-built k8s service discovery in the Prometheus receiver
```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: performance-test
        metrics_path: '/metrics'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - eks-aoc

exporters:
  logging:

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging]
```

I tested this on EKS and ran the set up on 1/10/30/69 pods (69 pods was the max number of allowed pods in my cluster). I also used the CloudWatch Agent to monitor and track CPU/memory usage of the collector. We got the following results:

**CPU Utilization (%)**
|  Num Targets |  Setup 1  | Setup 2  |  Difference  |
|:-------------:|:---------:|:--------:|:------------:|
|  1 | 0.02  | 0.02   | -0  |
| 10  | 0.112  | 0.033 | -0.079  |
| 30  | 0.33  | 0.059  |  -0.271  |
| 69  | 0.705  |  0.105 | -0.6  |

**Memory Utilization (%)**
|  Num Targets |  Setup 1  | Setup 2  |  Difference  |
|:-------------:|:---------:|:--------:|:------------:|
|  1 | 0.196  | 0.182   | -0.014  |
| 10  | 0.311  | 0.23 | -0.081  |
| 30  | 0.468  | 0.332  |  -0.136  |
| 69  | 0.773  |  0.468 | -0.305  |

It looks like the overhead in using multiple receivers scales as the number of scrape targets grows. This might get really hairy with larger numbers of scrape targets.

If we do still want to use the observer API, then maybe an option is to create a new receiver that listens in on the observer and writes the scraped targets to a config file which the Prometheus receiver can pick up on?
