### ISSUE TITLE
[processor/filterprocessor] support filtering by tracestate

### ISSUE THREAD

**Issue by mathnogueira** [open-telemetry/opentelemetry-collector-contrib#13994]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to filter spans based on a value in the `tracestate` field. I tried achieve that with the filter processor, but it doesn't support it, so I had to rely on the `tail sampling` processor instead. It would be nice to be able to use the filter instead due to it being available in the `core` package.

**Describe the solution you'd like**
I'd expect to be able to configure the filter processor to be able to filter spans based on a value in a specific key of the `tracestate`:

```yaml
processors:
  filter:
    spans:
      include:
        match_type: {strict, regexp}
        tracestate:
          key: my-key
          value: my-value
```
**Describe alternatives you've considered**
I managed to make it work using the `tail sampling` processor, but it would be nice to be able to achieve it in the filter processor as well
