### ISSUE TITLE
Prometheus receiver relabel config for controlling scrape targets is not working as documented

### ISSUE THREAD

**Issue by Aanap** [open-telemetry/opentelemetry-collector-contrib#14004]
I have set up prometheus receiver in the OTEL agent yaml where I only want to scrape pods that have pod annotation, prometheus.io/scrape: "true" set. However, if I have a pod with either the annotation set with a different value, eg prometheus.io/scrape: "false" or even where the annotation has not been applied, metrics from those pods are still being scrapped. Therefore, in essence I am unable to specify which k8s resources I want to monitor.
Prometheus receiver configuration in my OTel agent yaml is as below:-
```
 receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'otel-collector-k8s-pods'
            scrape_interval: 30s
            scrape_timeout: 2s
            kubernetes_sd_configs:
            - role: pod
            tls_config:
              insecure_skip_verify: true
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
              action: replace
              target_label: __scheme__
              regex: (https?)
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: (.+)(?::\d+);(\d+)
              replacement: $1:$2
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
            - source_labels: [__meta_kubernetes_host_name]
              action: replace
              target_label: kubernetes_pod_name
```

**Comment by dashpole** [comment]
Make sure you escape $ with $$ in the collector config (i.e. replacement: $$1:$$2

**Comment by Aanap** [comment]
I have tested with $$ and I am still having the same issue. Updated yaml is as below:-
```
receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: "otel-collector-k8s-pods"
            scrape_interval: 30s
            scrape_timeout: 2s
            kubernetes_sd_configs:
              - role: pod
            tls_config:
              insecure_skip_verify: true
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
                action: replace
                target_label: __scheme__
                regex: (https?)
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+)(?::\d+);(\d+)
                replacement: $$1:$$2
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod_name
```
