### ISSUE TITLE
[exporter/loki] Auto replace labels with dot to underscore

### ISSUE THREAD

**Issue by rogeriospinaintelipost** [open-telemetry/opentelemetry-collector-contrib#14113]
### Is your feature request related to a problem? Please describe.

Loki doesn`t accept labels that contains dots, so I have to duplicate my attributes via processors copying the value from attribute with dot to other attribute with underscore.

Ex: ``` host.name ``` copy to -> ```host_name```

```
      resource:
        attributes:     
          - action: insert
            key: host_name
            from_attribute: host.name
    
          - action: insert
            key: namespace
            from_attribute: k8s.namespace.name
   
          - action: insert
            key: container_name
            from_attribute: k8s.container.name
```

### Describe the solution you'd like

Would be nice if the str replace happens automatically by the lokiexporter

### Additional context

@jpkrohling
