### ISSUE TITLE
[receiver/mongodbatlas] Retrieve Alerts Data Through Firewall

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#14121]
### Is your feature request related to a problem? Please describe.

The MongoDB Atlas receiver currently can collect alerts via `webhooks`. This doesn't work for all customers as they may not be able to open a port in the firewall to accept incoming alerts.

We should add an alternative that allows us to scrape the [API for Alerts](https://www.mongodb.com/docs/atlas/reference/api/alerts-get-all-alerts/) so that this user case is accomplished.

### Describe the solution you'd like

I'd like to propose that we introduce a new mode parameter for the alerts config as to dictate whether to listen or retrieve logs from the API. 

```yaml
receivers:
  mongodbatlas:
    alerts:
      enabled: true
      # new parameters
      mode: retrieval # one of retrieval or listen
      projects:
      - name: project-1
      - exclude_clusters: [internal_cluster]
      - include_clusters: []
      - collect_audit_logs: true
```

### Describe alternatives you've considered

Deliberated between adding a new config or mode only parameters and feel like this would be my preference happy to hear other thoughts/concerns though!
