### ISSUE TITLE
Jaeger exporter marking traces with unknown sampling type

### ISSUE THREAD

**Issue by avishefi** [open-telemetry/opentelemetry-collector-contrib#14124]
**Describe the bug**
The OpenTelemetry Collector demo sends OTLP to the collector and from there an exporter is defined to send traces to Jaeger. Spans and traces reach to Jaeger based on debug logs and Jaeger metrics which keep increasing. However, the traces have a sampling type "unknown" in Jaeger which do not appear in the Jaeger query UI.

**What did you expect to see?**
Traces appear in Jaeger UI.

**What did you see instead?**
Traces reach Jaeger collector, but are marked with sampling_type="unknown" in Jaeger Prometheus metrics.

**What version did you use?**
OpenTelemetry collector 0.59.0
Jaeger 1.37

**What config did you use?**
```yaml
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:18889"

  logging:
    loglevel: debug

service:
  extensions: [health_check]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

  telemetry:
    logs:
      level: "debug"
    metrics:
      address: ":6668"
```

**Environment**
OS: CentOS Stream 8
