### ISSUE TITLE
Cannot set span on conditional status

### ISSUE THREAD

**Issue by flenoir** [open-telemetry/opentelemetry-collector-contrib#14136]
### What happened?

```Markdown
## Description

Hi,

I want to edit span staus regarding http.status_code. i found in "opentelemetry-collector-contrib/processor/spanprocessor/testdata/config.yaml" that there's a possibility of doing so 


# However you may want to set status conditionally. Example below sets
# status to success only when attribute http.status_code is equal to 400
span/set_status_ok:
  include:
    attributes:
      - Key: http.status_code
        Value: 400
  status:
    code: "Ok"
```

but i get an error which seem to explain that the syntax should be different.  Should this code be working like so, or do i missed something ? 

## Steps to Reproduce

I think just use the provided default example or use my code below

```
span/statuscode404:
      include:
        attributes: 
          - key: http.status_code
            value: 404
      status:
        code: "Error"

```

## Expected Result

Be able to have status code modified when http.status_code  value is 404

## Actual Result

i get an error message 

```
Error: cannot build pipelines: failed to create "span/statuscode404" processor, in pipeline "traces": error creating attribute filters: unrecognized match_type: '', valid types are: [regexp strict]
```
```


### Collector version

0.59.0

### Environment information

```Markdown
## Environment
Deployed under kubernetes


Deployment is made through Helm, the below configuration is done through values.yaml file

 i obfuscated some informationq regarding customer confidentiality
```

### OpenTelemetry Collector configuration

```yaml
mode: deployment

#presets:
#  logsCollection:
#    enabled: true
#    includeCollectorLogs: true

config:
  receivers:
    kafka:
      protocol_version: 2.0.0
      brokers:
        - xso025-broker0.xxxxxxxxxxxxxxxx:9094
        - xso025-broker1.xxxxxxxxxxxxxxxx:9094
        - xso025-broker2.xxxxxxxxxxxxxxxx:9094
        - xso025-broker3.xxxxxxxxxxxxxxxx:9094
        - xso025-broker4.xxxxxxxxxxxxxxxx:9094
        - xso025-broker5.xxxxxxxxxxxxxxxx:9094
      topic: xso064_collecteurtelemetry-anonyme
    prometheus:
    zipkin:
  exporters:
    otlp/tempo:
      endpoint: tempo:4317
      tls:
        insecure: true
    logging:
      loglevel: debug
    prometheus:
      endpoint: 0.0.0.0:9090
      namespace: otel-quarkus
      enable_open_metrics: false
      send_timestamps: true
      resource_to_telemetry_conversion:
        enabled: true
  processors:
    batch:
      send_batch_size: 100
      timeout: 200ms
    memory_limiter:
      limit_mib: 200
      check_interval: 5s
    span/statuscode404:
      include:
        attributes: 
          - key: http.status_code
            value: 404
      status:
        code: "Error"
  extensions:
    health_check: {}
    memory_ballast:
      size_in_percentage: 20
  service:
    telemetry:
      logs:
        level: "debug"
    extensions: [health_check, memory_ballast]
    pipelines:
      traces:
        receivers: [otlp, jaeger, kafka]
        processors: [memory_limiter, batch, span/statuscode404]
        exporters: [otlp/tempo]
      metrics:
        receivers: [otlp]
        processors: []
        exporters: [prometheus]
      logs:

ports:
  zipkin:
    enabled: false
  metrics:
    enabled: true
    containerPort: 9090
    servicePort: 9090
    protocol: TCP

serviceMonitor:
  enabled: true
  metricsEndpoints:
  - port: metrics
    # interval: 15s

image:
  repository: otel/opentelemetry-collector-contrib
#command:
#  name: otelcol-contrib

resources:
  limits:
    cpu: 300m
    memory: 384Mi
```

### Log output

```shell
Error: cannot build pipelines: failed to create "span/statuscode404" processor, in pipeline "traces": error creating attribute filters: unrecognized match_type: '', valid types are: [regexp strict]
```

### Additional context

```Markdown
As the error, seem to ask for a "math_type", is it mandatory to add a "strict" match_type before attributes ? 

Does the syntax should be different ?
```
