### ISSUE TITLE
prometheus receiver not support openmetrics

### ISSUE THREAD

**Issue by songjiayang** [open-telemetry/opentelemetry-collector-contrib#14160]
### What happened?

```Markdown
## Description

I use prometheus golang SDK to export metrics with exemplars like:


a_bucket{le="0.5"} 10 # {traceID="xxx"}
```

the collector configuration like:

```
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'exemplar-app'
        scrape_interval: 10s
        static_configs:
        - targets: ['app:8080']
        
processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "test"
    enable_open_metrics: true

  logging:
    logLevel: debug
      
extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheus]

```
## Steps to Reproduce

Example curl command:

curl -H 'Accept: application/openmetrics-text; version=0.0.1' http://localhost:8889/metrics

output like:
```
a_bucket{le="0.5"} 10
```
the exemplars missed.
```


### Collector version

v0.60.0
