### ISSUE TITLE
status.message unreachable from attributesprocessor

### ISSUE THREAD

**Issue by alsterg** [open-telemetry/opentelemetry-collector-contrib#14175]
### What happened?

```Markdown
## Description
I'm attempting to use the status.message string with attributeprocessor but it seems that it is not reachable. E.g the following action it not triggered:

      attributes:
        actions:
          - key: "status.message"
            from_attribute: "something"
            action: insert
```
It looks like the common span fields such as status.message are not part of the Attribute list of the span. Is there a way to reach them with a processor?

## Steps to Reproduce
Using the rule above and some input spans that set the message.status.

## Expected Result
Rule is triggered.

## Actual Result
Rule is not triggered.
```


### Collector version

0.54.0

### Environment information

```Markdown
## Environment
OS: (e.g., "RHEL8")
```

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      attributes:
        actions:
          - key: "status.message"
            from_attribute: "XXX"
            action: insert
    exporters:
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [attributes]
          exporters: [logging]
```
