### ISSUE TITLE
New component: k8sobjectsreceiver

### ISSUE THREAD

**Issue by harshit-splunk** [open-telemetry/opentelemetry-collector-contrib#14185]
### The purpose and use-cases of the new component

We need a receiver to collect the Kubernetes objects and send them as log data(similar to [fluent-plugin-kubernetes-objects](https://github.com/splunk/fluent-plugin-kubernetes-objects) fluentd plugin). 
- It should collect objects in 2 ways
  - Pull: Collects all available objects at an interval by calling the list APIs.
  - Watch: Collects only the new objects when they appear by calling the watch APIs. 
    - More about watch API: https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes 
- It should allow filtering objects using namespace, label selector and field selector

### Example configuration for the component

```yaml
receivers:
  k8sobjects: 
    objects:
        - name: <resource-name>
          mode: pull/watch
          interval: <interval> # Required if pull mode
          label_selector: <label selector>
          field_selector: <field selector>
          namespaces: [<namespace>,...] # all namespace if empty
        ...
```

```yaml
receivers:
  k8sobjects:
    objects:
      - name: pods
        mode: pull
        namespace: [default]
        interval: 30s
      - name: event
        mode: watch
      - name: deployments
        mode: pull
        interval: 30s
        label_selector: app=myapp
```

### Telemetry data types supported

logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

@dmitryax 

### Additional context

Design doc: https://docs.google.com/document/d/13ZESiUe0IP73sMNHQT5ZmWo9BPPP_1sy385QVIgNVkw
