### ISSUE TITLE
[exporter/datadog]: Failed to retrieve metadata

### ISSUE THREAD

**Issue by inigohu** [open-telemetry/opentelemetry-collector-contrib#14186]
### What happened?

```Markdown
Some warning messages appear in our logs after upgrading to version v0.60.0.
We don't want to send host metrics to Datadog and it seems to be mandatory with the latest version.
```

### Collector version

v0.60.0

### Environment information

```Markdown
Gateway deployment mode on Google GKE autopilot.
```

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1500
    spike_limit_mib: 500
  resource:
    attributes:
      - key: deployment.environment
        value: test
        action: upsert
      - key: cloud.region
        value: test
        action: upsert
  batch:
    send_batch_size: 256
    send_batch_max_size: 512
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
      site: datadoghq.eu
    metrics:
      sums:
        cumulative_monotonic_mode: to_delta
      histograms:
        mode: distributions
        send_count_sum_metrics: true
      resource_attributes_as_tags: true
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [datadog]
```

### Log output

```shell
[Debug] Error fetching info for pid 1: open /etc/passwd: no such file or directory
warn	gohai/gohai.go:66	Failed to retrieve platform metadata	{"kind": "exporter", "data_type": "metrics", "name": "datadog", "error": "exec: \"uname\": executable file not found in $PATH"}
warn	gohai/gohai.go:47	Failed to retrieve filesystem metadata	{"kind": "exporter", "data_type": "metrics", "name": "datadog", "error": "df failed to collect filesystem data: %!s(<nil>)"}
```

**Comment by Sunilwali679** [comment]
Hi @inigohu  . I am interested to work on this could you please assign this to me ??

**Comment by inigohu** [comment]
>Hi @inigohu . I am interested to work on this could you please assign this to me ??

Hi @Sunilwali679, I have no privileges to assign this issue to you, I am not a CODEOWNER.

**Comment by Sunilwali679** [comment]
@mx-psi  Could you help on this issue assignment ?

**Comment by mx-psi** [comment]
Done! Also cc @dineshg13 to review this work

**Comment by husseinraoouf** [comment]
I think this issue should be with higher priority, the datadog exporter is essentially broken for metrics

at least there should be a workaround until the issue is fixed

**Comment by dineshg13** [comment]
@husseinraoouf sorry for delay in fixing this. I will be taking this on priority and fix same.

**Comment by husseinraoouf** [comment]
Thank you for the quick response

**Comment by dineshg13** [comment]
@husseinraoouf to clarify, this error message shouldn't stop datadog exporter from reporting metrics or have any other issues. This is happening as the docker image doesn't have required dependencies. 

There are few routes we can take. 
1. Classify the warning as info, with additional information that it doesn't impact the exporter.  (preferred ) 
2. Add the dependencies to the official built , might be hard to get approval 
3. Remove these metadata collector (least preferred ) 

@mx-psi let me know your thoughts on same.

**Comment by ronenl3** [comment]
I'm running the Collector with v0.71.0 and see these log messages.
Is the issue going to be solved? I don't see any Infrastructure metrics in my spans since I updated my OTel Collector.

**Comment by mx-psi** [comment]
>  I don't see any Infrastructure metrics in my spans since I updated my OTel Collector.

Could you open a separate issue for this? I don't think your issue is related to the log messages here

**Comment by brunocrt** [comment]
I still see this same error message on version 0.67.0,
```

2023-03-03T22:20:42.839Z        info    gohai/gohai.go:47       Failed to retrieve filesystem metadata  {"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "df failed to collect filesystem data: %!s(<nil>)"}
2023-03-03T22:20:42.840Z        info    gohai/gohai.go:66       Failed to retrieve platform metadata    {"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "exec: \"uname\": executable file not found in $PATH"}
```

**Comment by regisverdin** [comment]
Still seeing this in version 0.72.0

```
gohai/gohai.go:47    Failed to retrieve filesystem metadata  {"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "df failed to collect filesystem data: %!s(<nil>)"}
gohai/gohai.go:66    Failed to retrieve platform metadata    {"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "exec: \"uname\": executable file not found in $PATH"}
```

**Comment by mcatany** [comment]
Getting the same error above agfter upgrading to 0.77.0.
```
2023-05-18T12:47:49.516Z	info	gohai/gohai.go:47	Failed to retrieve filesystem metadata	{"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "df failed to collect filesystem data: %!s(<nil>)"}
2023-05-18T12:47:49.522Z	info	gohai/gohai.go:66	Failed to retrieve platform metadata	{"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "exec: \"uname\": executable file not found in $PATH"}
```

**Comment by VinxItak** [comment]
Hi guys, did you found a solution for this ?

image: otel/opentelemetry-collector-contrib:0.84.0

```
info    gohai/gohai.go:35    Failed to retrieve filesystem metadata    {"kind": "exporter", "data_type": "metrics", "name": "datadog", "error": "df failed to collect filesystem data: %!s(<nil>)"}
info    gohai/gohai.go:54    Failed to retrieve platform metadata    {"kind": "exporter", "data_type": "metrics", "name": "datadog", "error": "exec: \"uname\": executable file not found in $PATH"}

```

**Comment by ringerc** [comment]
To silence this annoying noise, use

```
    exporters: 
      datadog:
        # ...
        host_metadata:
          enabled: false
```
