### ISSUE TITLE
[processor/servicegraphprocessor] Adjust metric names to fit documentation

### ISSUE THREAD

**Issue by sarahsporck** [open-telemetry/opentelemetry-collector-contrib#14187]
### What happened?

```Markdown
## Description

In the documentation the metric names do not align with the actual names of the metrics, e.g. 'traces_service_graph_request_total' and 'request_total'

## Steps to Reproduce

## Expected Result

Metrics are prefixed with traces_service_graph

## Actual Result

Metrics are not prefixed
```

### Collector version

v0.60.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:

  otlp/servicegraph:
    protocols:
      grpc:
        endpoint: "localhost:12345"

processors:    
  servicegraph:
    metrics_exporter: prometheus

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  logging:
    logLevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [servicegraph]
      exporters: [logging]
    metrics:
      receivers: [otlp/servicegraph]
      exporters: [prometheus]
```
