### ISSUE TITLE
stanzareceiver: log is flooded when the input line does not match the expected regexp

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#1419]
I have stanza receiver configured to read a text file. The input lines don't match the config.

Input is like:
```
29/10/2020 INFO Load Generator Counter #0
29/10/2020 INFO Load Generator Counter #1
29/10/2020 INFO Load Generator Counter #2
```

Stanza config is:
```
stanza:
    pipeline:
      - type: file_input
        include: [ %s ]
        start_at: beginning
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
        timestamp:
          parse_from: time
          layout: '%%Y-%%m-%%d'
        severity:
          parse_from: sev
```

**What did you expect to see?**
Collector logs should not be flooded with error messages. Increment an internal metric counter when we have an error in the input data instead. Optionally log the error with very high sampling ratio (e.g. once every 10 seconds, 1/100000th after that). Optionally log the error at debug level.

**What did you see instead?**
Logs are flooded with messages like this, looks like I get one error message per input line:
```
{"level":"error","ts":1604001681.258924,"caller":"helper/transformer.go:74","msg":"Failed to process entry","component_kind":"receiver","component_type":"stanza","component_name":"stanza","operator_id":"$.regex_parser","operator_type":"regex_parser","error":"regex pattern does not match","action":"send","entry":{"timestamp":"2020-10-29T16:01:21.25892-04:00","severity":0,"labels":{"file_name":"perf-logs.log818235745"},"record":"29/10/2020 INFO Load Generator Counter #1"},"stacktrace":"github.com/observiq/stanza/operator/helper.(*TransformerOperator).HandleEntryError\n\t/Users/tnajaryan/.go/pkg/mod/github.com/observiq/stanza@v0.12.0/operator/helper/transformer.go:74\ngithub.com/observiq/stanza/operator/helper.(*ParserOperator).ProcessWith\n\t/Users/tnajaryan/.go/pkg/mod/github.com/observiq/stanza@v0.12.0/operator/helper/parser.go:96\ngithub.com/observiq/stanza/operator/builtin/parser/regex.(*RegexParser).Process\n\t/Users/tnajaryan/.go/pkg/mod/github.com/observiq/stanza@v0.12.0/operator/builtin/parser/regex/regex.go:77\ngithub.com/observiq/stanza/operator/helper.(*WriterOperator).Write\n\t/Users/tnajaryan/.go/pkg/mod/github.com/observiq/stanza@v0.12.0/operator/helper/writer.go:60\ngithub.com/observiq/stanza/operator/builtin/input/file.(*Reader).emit\n\t/Users/tnajaryan/.go/pkg/mod/github.com/observiq/stanza@v0.12.0/operator/builtin/input/file/reader.go:128\ngithub.com/observiq/stanza/operator/builtin/input/file.(*Reader).ReadToEnd\n\t/Users/tnajaryan/.go/pkg/mod/github.com/observiq/stanza@v0.12.0/operator/builtin/input/file/reader.go:97\ngithub.com/observiq/stanza/operator/builtin/input/file.(*InputOperator).poll.func1\n\t/Users/tnajaryan/.go/pkg/mod/github.com/observiq/stanza@v0.12.0/operator/builtin/input/file/file.go:122"}
```

This is not compliant with Collector guidelines: https://github.com/open-telemetry/opentelemetry-collector/blob/master/CONTRIBUTING.md#logging
