### ISSUE TITLE
stanzareceiver: Otel standard severity levels are not recognized

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#1420]
**Steps to reproduce**
Collect a file input with lines like this:
```
2020-10-29 INFO3 Load Generator Counter #0 batch_index=batch_1 item_index=item_1 a=test b=5 c=3 d=true
```

and config file like this:
```
  stanza:
    pipeline:
      - type: file_input
        include: [ %s ]
        start_at: beginning
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2}) (?P<sev>[A-Z0-9]*) (?P<msg>.*)$'
        timestamp:
          parse_from: time
          layout: '%%Y-%%m-%%d'
        severity:
          parse_from: sev
```

**What did you expect to see?**
Log records collected should have SeverityText="INFO3" and SeverityNumber=11

**What did you see instead?**
Log records collected have SeverityText="Undefined" and SeverityNumber=0

We need to correctly recognize standard Otel severity numbers. We also need to keep unrecognized severity text as is, without changing it to "Undefined".
