### ISSUE TITLE
[exporter/loki] Make it easier to map OpenTelemetry Severity to Loki level label

### ISSUE THREAD

**Issue by kago-dk** [open-telemetry/opentelemetry-collector-contrib#14313]
### Is your feature request related to a problem? Please describe.

Currently, the log level is tracked as SeverityText (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md) in v0.60.0, while the same information is tracked in the level label in Loki (https://grafana.com/docs/grafana/latest/explore/logs-integration/). It would be optimal if we could avoid tracking the log level as both "SeverityText" and "level" in the OTEL Collector to make Loki work and support mapping between "SeverityText" and "level" in the Loki Exporter configuration.

*Example*
<img width="1025" alt="NoLevel_Body_Purple" src="https://user-images.githubusercontent.com/49529296/191111206-c1541e86-8502-4648-b15f-11b49e5c7608.png">
If the level is not set, Loki presents the log line as purple because the body text includes the word "Alert"

<img width="1177" alt="AttributeLevel_Body_Purple" src="https://user-images.githubusercontent.com/49529296/191111399-ed3b2265-3c50-4e41-aebb-c3cbdc7fd5b5.png">
If the level is set but not part of loki.attribute.labels, then Loki presents the logline as purple because the body text includes the word "Alert"

```
  attributes/logs:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: net_sock_peer_addr
```
<img width="1071" alt="Level_Green" src="https://user-images.githubusercontent.com/49529296/191111722-d823d974-bb5f-483f-867b-82d5976ba667.png">
If the level is set and part of loki.attribute.labels, then Loki presents the logline as green because Loki uses the log level from the level label.

```
  attributes/logs:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: net_sock_peer_addr,level
```

 

### Describe the solution you'd like

Support mapping between "SeverityText" and "level" in the Loki Exporter configuration in the OTEL Collector, so the user is not forced into Loki-specific transformation in the OTEL Collector. Ideally, it should happen automatically since the purpose of the fields is the same on both sides.
