### ISSUE TITLE
New component: SSH Receiver

### ISSUE THREAD

**Issue by nslaughter** [open-telemetry/opentelemetry-collector-contrib#14312]
### The purpose and use-cases of the new component

Purpose: To monitor the availability and performance of SSH endpoints.
Use case: Methods of monitoring SSH host availability can either use the programs on the host or run as clients. This proposal is for monitoring as a client which can provide less information, but it doesn't require ownership of the host or any additional permissions. It performs simple checks by connecting to the host to validate it's available. Additionally, a common use of SSH is for file transfer over SFTP, which can be checked in the same way.

### Example configuration for the component

```yaml
receivers:
  ssh:
    collection_interval: 60s     # default: 60s
    endpoint: eg.host.str:2222   # required - port defaults to 22 if not included
    user: otelu                  # required
    password: otelp              # required unless key_file is provided
    key_type: ECDSA              # default: RSA (enum: RSA|ECDSA|EDDSA|Ed25519)
    key_file: /path/to/key_id    # required unless password is provided
    sftp: true                   # default: false
```

### Telemetry data types supported

Gauges
ssh_availability: 1/0 (up/down)
ssh_connection_time: (ms)

sftp_availability: 1/0 (up/down)
sftp_connection_time: (ms)

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

@codeboten
