### ISSUE TITLE
[receiver/kubeletstatsreceiver] Use network io as network errors

### ISSUE THREAD

**Issue by tianlin** [open-telemetry/opentelemetry-collector-contrib#14318]
### What happened?

```Markdown
## Description
kubeletstatsreceiver use network io as network errors
## Steps to Reproduce
config kubeletstatsreceiver to scrape node/pod network metric
## Expected Result
use rxErrors/txErrors as network errors
## Actual Resultus
use rxBytes/txBytes as network errors
```

### Collector version

v0.60.0

### Environment information

```Markdown
## Environment
OS: Ubuntu 20.04
Compiler(if manually compiled): go 1.18.5
```

### OpenTelemetry Collector configuration

```yaml
extensions:

receivers:
  kubeletstats:
    auth_type: serviceAccount
    collection_interval: 10s
    endpoint: ${K8S_NODE_IP}:10250
    extra_metadata_labels:
    - container.id
    metric_groups:
    - container
    - pod
    - node

processors:
  batch:
  # Enabling the memory_limiter is strongly recommended for every pipeline.
  # Configuration is based on the amount of memory allocated to the collector.
  # For more information about memory limiter, see
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiter/README.md
  #memory_limiter:
  #  check_interval: 2s
  #  limit_mib: ${BALLAST_SIZE_MIB}
  # detect if the collector is running on a cloud system
  # important for creating unique cloud provider dimensions
  resourcedetection:
    detectors: [ system ]
    override: false

exporters:
  logging:
    loglevel: debug

service:
  telemetry:
    logs:
      level: info
      initial_fields:
        service: yotta-otelcol
    metrics:
      # disable otel-col self metric default
      #level: info
      address: 0.0.0.0:8889
  extensions: [ ]
  pipelines:
    metrics:
      receivers: [ kubeletstats ]
      processors: [ batch, resourcedetection ]
      exporters: [ logging ]
```
