### ISSUE TITLE
Influxdbv2 receiver rejects JMeter output with response code 400

### ISSUE THREAD

**Issue by perrinj3** [open-telemetry/opentelemetry-collector-contrib#14337]
### What happened?

```Markdown
When using a JMeter 5.5 Backend Listener to output test results to Opentelemetry using the InfluxDB receiver the HTTP Post is rejected if the payload contains "count=1". The same payload is accepted by InfluxDB V2 without any errors. 

Sample request body is shown below


requestsRaw,errorMessage=noData,errorResponseBody=<!DOCTYPE\ html><html\ xmlns\="http://www.w3.org/1999/xhtml"><link\ rel\="icon"\ href\="/favicon.ico"><head><title>Test\ Page\ for\ Apache\ Installation</title></head><!--\ Background\ white\,\ links\ blue\ (unvisited)\,\ navy\ (visited)\,\ red(active)\ --><body\ bgcolor\="#FFFFFF"\ text\="#000000"\ link\="#0000FF"vlink\="#000080"\ alink\="#FF0000"\ style\="font-family:Arial;"><div\ align\="center"\ style\="background-color:#284F95;color:#FFF;font-size:30px;font-style:oblique;font-variant:small-caps;height:50px;padding-top:15px;">\ An\ Apache\ Haus\ Distribution</div><center><h3>Test\ Page\ for\ Apache\ Installation</h3><b>Apache/2.4\ OpenSSL</b><br/><table\ width\="80%"><tr>\ \ <td\ colspan\="2"\ align\="center">\ \ <p>This\ page\ is\ used\ to\ test\ the\ proper\ operation\ of\ the\ Apache\ HTTP\ server\ after\ it\ has\ been<br/>\ installed.\ If\ you\ can\ read\ this\ page\,\ it\ means\ that\ the\ web\ server\ installed\ at\ this\ site\ is<br/>\ working\ properly\,\ but\ has\ not\ yet\ been\ configured.</p>\ \ </td></tr><tr\ valign\="top"\ width\="50%"\ style\="padding-left:5px;"><td><h4\ align\="center">If\ you\ are\ a\ member\ of\ the\ general\ public:</h4><p>The\ fact\ that\ you\ are\ seeing\ this\ page\ indicates\ that\ the\ website\ you\ just\ visited\ is\ either\ experiencing\ problems\,\ or\ is\ undergoing\ routine\ maintenance.</p><p>If\ you\ would\ like\ to\ let\ the\ administrators\ of\ this\ website\ know\ that\ you've\ seen\ this\ page\ instead\ of\ the\ page\ you\ expected\,\ you\ should\ send\ them\ e-mail.\ In\ general\,\ mail\ sent\ to\ the\ name\ "webmaster"\ and\ directed\ to\ the\ website's\ domain\ should\ reach\ the\ appropriate\ person.</p><p>For\ example\,\ if\ you\ experienced\ problems\ while\ visiting\ www.example.com\,\ you\ should\ send\ e-mail\ to\ "webmaster@example.com".</p></td><td\ width\="50%"><h4\ align\="center">If\ you\ are\ the\ web\ server\ administrator:</h4><p>You\ may\ now\ add\ content\ to\ the\ directory\ <font\ face\="courier\ new">/htdocs</font>.\ Note\ that\ until\ you\ do\ so\,\ people\ visiting\ your\ website\ will\ see\ this\ page\,\ and\ not\ your\ content.\ To\ prevent\ this\ page\ from\ ever\ being\ used\,\ replace\ the\ existing\ <font\ face\="courier\ new">/htdocs/index.,nodeName=Test-Node,requestName=Transaction1,responseCode=200,result=pass,runId=R002,testName=Test connectTime=43i,count=1i,errorCount=0i,latency=66i,processingTime=23i,receivedBytes=12289i,responseTime=73i,sentBytes=596i 1663736835138802347
```
## Steps to Reproduce
Post this payload with Fiddler to the otelHost/api/v2/write endpoint of a Otel Contrib collector configured to receive InfluxDB

## Expected Result
Response code 204

## Actual Result
Response code 400
```


### Collector version

v0.59.0

### Environment information

```Markdown
## Environment
OS: Windows Server
used binary
```

### OpenTelemetry Collector configuration

```yaml
receivers:
  influxdb:
    endpoint: "0.0.0.0:8087"
exporters:
  influxdb:
    endpoint: http://localhost:8086/
    timeout: 500ms
    org: ANZ
    bucket: OpenTel
    token: ***************
    sending_queue:
      enabled: true
      num_consumers: 3
      queue_size: 20
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 3s
      max_elapsed_time: 10s
  logging:
    loglevel: debug
    sampling_initial: 1
    sampling_thereafter: 1
service:
  pipelines:
    metrics:
     receivers: [influxdb]
     exporters: [influxdb,logging]
```

### Additional context

```Markdown
If the count=1 field is removed from the request body then a response code 204 is received
```
