### ISSUE TITLE
stanzareceiver: original log message is not preserved when regex_parser is used

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#1435]
When using regex_parser there is does not seem to be a way to preserve the original log message.

**Steps to reproduce**
Use config:
```yaml
  stanza:
    pipeline:
      - type: file_input
        include: [ '*.log' ]
        start_at: beginning
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2}) (?P<sev>[A-Z0-9]*)'
        timestamp:
          parse_from: time
          layout: '%Y-%m-%d'
        severity:
          parse_from: sev
        preserve: true
```

Input log record:
```
2010-01-02 INFO hello world, this is a log message
```

Output record:
```json
{
  "resourceLogs": [
    {
      "resource": {},
      "instrumentationLibraryLogs": [
        {
          "instrumentationLibrary": {
            "name": "stanza",
            "version": "0.12.0"
          },
          "logs": [
            {
              "timeUnixNano": "1286856000000000000",
              "severityNumber": "SEVERITY_NUMBER_INFO",
              "severityText": "Info",
              "body": {
                "kvlistValue": {}
              },
              "attributes": [
                {
                  "key": "file_name",
                  "value": {
                    "stringValue": "input.log"
                  }
                }
              ],
              "traceId": "",
              "spanId": ""
            }
          ]
        }
      ]
    }
  ]
}
```

**What did you expect to see?**
I expect to see "2010-01-02 INFO hello world, this is a log message" as the Body of the output record.

**What did you see instead?**
The Body is an empty map.
