### ISSUE TITLE
Lokiexporter document is misleading

### ISSUE THREAD

**Issue by jtama** [open-telemetry/opentelemetry-collector-contrib#14401]
### Describe the issue you're reporting

The documentation shows the following, which is invalid. 

```yaml
processors:
  attributes:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: [http.status_code]

  resource:
    attributes:
    - action: insert
      key: loki.attribute.labels
      value: [http.status]
    - action: insert
      key: loki.resource.labels
      value: [host.name, pod.name]
```
The correct config is 

```yaml
processors:
  attributes:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: http.status_code

  resource:
    attributes:
    - action: insert
      key: loki.attribute.labels
      value: [http.status]
    - action: insert
      key: loki.resource.labels
      value: host.name pod.name
```

I can do a pr if you like.
