### ISSUE TITLE
k8sattributes processor - Allow metadata extractions to be null

### ISSUE THREAD

**Issue by clheikes** [open-telemetry/opentelemetry-collector-contrib#14452]
### Is your feature request related to a problem? Please describe.

I'd like to extract annotations and not be required to extract metadata fields as well.

```
    processors:
      k8sattributes/metrics:
        extract:
          annotations:
          - from: namespace
            key: splunk.com/metrics-index
            tag_name: com.splunk.index
          - from: pod
            key: splunk.com/metrics-index
            tag_name: com.splunk.index
          metadata: [k8s.pod.name] 
```

### Describe the solution you'd like

Allow me to set `metadata: null` or something similar

### Describe alternatives you've considered

As a workaround I'm setting metadata to a field that my pod assocation rule is using

### Additional context

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/bc9e9ba18226059c624aa09ff4ea868c5d90abfe/processor/k8sattributesprocessor/options.go#L73
