### ISSUE TITLE
[prometheusreceiver] timestamp enforcement breaks federation support

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-collector-contrib#14453]
## Description
When scraping a federated endpoint [built-in internal metrics](https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series) appear to conflict with the receiver maintained ones and lead to:

```
2022-09-22T20:11:53.740Z        warn    scrape/scrape.go:1279   Appending scrape report failed  {"kind": "receiver", "name": "prometheus/federation", "pipeline": "metrics", "scrape_pool": "federation", "target": "http://192.168.77.27:9090/federate?match%5B%5D=%7Bjob%3D%22nginx%22%7D", "error": "inconsistent timestamps on metric points for metric up"}
```

## Steps to Reproduce

Try to scrape a `/federate` endpoint of a prometheus server*:

```yaml
scrape_configs:
  - job_name: federation
    honor_labels: true
    metrics_path: /federate
    params:
      'match[]':
         - '{job="nginx"}'
```

## Expected Result

Successful metric scraping and translation

## Actual Result

Above appender error.

I believe this was introduced by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9385 as earlier collector versions work w/ federated scraping.

### Collector version

0.54.0
