### ISSUE TITLE
awsemfexporter is producing dimensions with null value instead of empty dimension

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-collector-contrib#14531]
## Description

It seems that this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/13764 caused a regression in the awsemfexporter.

When the dimension rollup feature is used, it is producing dimensions with a null value instead of empty dimension.

## Steps to Reproduce

Use the collector https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/v0.60.0

Use the following configuration:
```
receivers:
  statsd:
    endpoint: 0.0.0.0:8765
    aggregation_interval: 20s
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  logging:
    loglevel: debug
  awsemf:
    region: 'us-west-2'
    output_destination: stdout

service:
  pipelines:
    metrics:
      receivers: [otlp,statsd]
      exporters: [awsemf]
```

Run:
```
echo "test.metric:42|c|#myKey:myVal,otherkey:val" | nc -w 1 -u localhost 8765
```

## Expected Result

```
{
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "default",
                "Dimensions": [
                    [
                        "myKey",
                        "otherkey"
                    ],
                    [],
                    [
                        "myKey"
                    ],
                    [
                        "otherkey"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "test.metric"
                    }
                ]
            }
        ],
        "Timestamp": 1664239034041
    },
    "myKey": "myVal",
    "otherkey": "val",
    "test.metric": 168
}

```

## Actual Result

```
{
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "default",
                "Dimensions": [
                    [
                        "myKey",
                        "otherkey"
                    ],
                    null,
                    [
                        "myKey"
                    ],
                    [
                        "otherkey"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "test.metric"
                    }
                ]
            }
        ],
        "Timestamp": 1664239034041
    },
    "myKey": "myVal",
    "otherkey": "val",
    "test.metric": 168
}
```
Null dimension is ignored by the awsemf backend and hence the regression.
### Collector version

v0.60.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  statsd:
    endpoint: 0.0.0.0:8765
    aggregation_interval: 20s
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  logging:
    loglevel: debug
  awsemf:
    region: 'us-west-2'
    output_destination: stdout

service:
  pipelines:
    metrics:
      receivers: [otlp,statsd]
      exporters: [awsemf]
```
