### ISSUE TITLE
question/prometheusexporter: error when writing? prometheus metrics

### ISSUE THREAD

**Issue by bbortt** [open-telemetry/opentelemetry-collector-contrib#14541]
### Describe the issue you're reporting

hi there

I've tried exporting collected metrics for collection by Prometheus using the `exporters: prometheus:`. as far as I understand it, this will expose an endpoint which prometheus can scrape later, right?

well, this currently results in the following error:
```shell
2022-09-27T14:02:24.590Z        error   prometheusexporter@v0.59.0/log.go:34    error encoding and sending metric family: write tcp 10.127.110.111:8090->10.127.110.76:48530: write: connection reset by peer
        {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.59.0/log.go:34
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1.2
        github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/http.go:187
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
        github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/http.go:205
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
        net/http/server.go:2462
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
        go.opentelemetry.io/collector@v0.59.0/config/confighttp/compression.go:162
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2084
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.34.0/handler.go:204
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
        go.opentelemetry.io/collector@v0.59.0/config/confighttp/clientinfohandler.go:39
net/http.serverHandler.ServeHTTP
        net/http/server.go:2916
net/http.(*conn).serve
        net/http/server.go:1966
```

I've also seen `error encoding and sending metric family: write tcp 10.127.91.182:8090->10.127.91.232:47078: write: broken pipe`. the configuration for the collector and his endpoint is as following:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 820
    # 25% of limit up to 2G
    spike_limit_mib: 256
    check_interval: 5s
extensions:
  health_check: {}
  memory_ballast:
    # Memory Ballast size should be max 1/3 to 1/2 of memory.
    size_mib: 350
exporters:
  logging:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter
  prometheus:
    endpoint: "0.0.0.0:8090"
#      tls:
#        ca_file: "/path/to/ca.pem"
#        cert_file: "/path/to/cert.pem"
#        key_file: "/path/to/key.pem"
    namespace: appl-sir-e1
    const_labels:
      app: EnTe
      env: tools
      module: otel-collector
    send_timestamps: true
    metric_expiration: 180m
#    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true
service:
  extensions: [health_check, memory_ballast, zpages]
  pipelines:
    metrics/1:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging, prometheus]
```

I don't exactly understand the errors. can somebody point me into a direction, please? the otel-collector container runs on kubernetes, I have almost full control over it. I can provide additional information, if required.

thanks in advance.
