### ISSUE TITLE
Dynamic selection of log_group_name and log_stream_name in aws cloudwatch logs exporter

### ISSUE THREAD

**Issue by mathiaz** [open-telemetry/opentelemetry-collector-contrib#14554]
### Is your feature request related to a problem? Please describe.

We are running the opentelemetry collector to send logs from our edge systems to a central opentelemetry gateway service. From the gateway we'd like to write logs to cloudwatch logs in different log groups and streams based on log resources.

### Describe the solution you'd like

We'd like to be able to set the `log_group_name` and `log_stream_name` dynamically based on fields from the log event:

```yaml
  awscloudwatchlogs:
    log_group_name: "{log_file_name}"
    log_stream_name: "{resource.hostname}"
```
