### ISSUE TITLE
[processor/spanmetrics] Does not recognize some dimensions

### ISSUE THREAD

**Issue by edenkoveshi** [open-telemetry/opentelemetry-collector-contrib#14564]
### Description
I am using the Span Metrics processor to generate R.E.D metrics
I am using the dimensions feature to extract the following tags:
```
- http.method
- http.status_code
- http.target
- http.error_message
- otel.status_code
- otel.status_description
- error
```
All of those attributes exist in the span scope
All the ```http.*``` dimensions are extracted as expected, but the rest aren't
I am using the 2-pipline configuration described [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/testdata/config-2-pipelines.yaml) 

### Collector version

0.60.0

### Environment information

OpenTelemetry Collector Contrib 0.60.0 deployed on Openshift with OpenTelemetry operator 0.60.0

**Comment by evan-bradley** [comment]
Can you post the exact configuration you are using? I don't see any immediately obvious reason why the non-HTTP attributes would be excluded as dimensions.

**Comment by albertteoh** [comment]
Yup, I agree with @evan-bradley (and thanks for responding!). 

As long as the non-HTTP attributes exist at the span or resource attributes at the time the span arrives in the spanmetrics processor, I also can't see why they wouldn't be included in the metrics. Relevant code [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/spanmetricsprocessor/processor.go#L495) in case you were interested @edenkoveshi.

Perhaps they were somehow filtered out/dropped by another upstream processor?

**Comment by edenkoveshi** [comment]
Obviously there shouldn't be any difference between the HTTP and non-HTTP attributes, but it still happens..
This is the exact configuration:
```yaml
receivers:
  jaeger:
  otlp:
    protocols:
      grpc:
      http:
  otlp/dummy:
    protocols:
      grpc:
        endpoint: "localhost:12345"

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
    dimensions:
    - http.method
    - http.status_code
    - http.target
    - http.error_message
    - otel.status_code
    - otel.status_description
    - error

exporters:
  jaeger:
    endpoint: <my-jaeger-endpoint>
 logging:
 prometheus:
   endpoint: "0.0.0.0:8889"

extensions:
  health_check:

service:
  extensions:
   - health_check
  pipelines:
    traces:
      receivers:
        - otlp
        -  jaeger
      processors:
       - spanmetrics
       - batch
      exporters:
       - logging
       - jaeger
    metrics:
       receivers: [otlp/dummy]
       exporters: [prometheus]
  telemetry:
     metrics:
        address: "0.0.0.0:8888"
     logs:
       level: "info"
```


Thank you for your help

**Comment by albertteoh** [comment]
Hi @edenkoveshi, just revisiting some old tickets (sorry for the slow turnaround!) and noticed `dimensions` is misconfigured. It should resemble something like:

```
processors:
  spanmetrics:
    metrics_exporter: prometheus
    dimensions:
      - name: "otel.status_code"
        default: "bad otel status code"
```

I've tested this and confirmed it's working as expected.

<img width="1779" alt="Screenshot 2023-01-29 at 4 38 35 pm" src="https://user-images.githubusercontent.com/26584478/215307295-d5b4e3a4-abc6-434f-b535-1a1cd238962f.png">
