### ISSUE TITLE
[receiver/iis] `iis.request.queue.age.max`consistently fails to scrape

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#14575]
## Description
`iis.request.queue.age.max`consistently fails to scrape. This *MAY* be because the counter that it scrapes, `\HTTP Service Request Queues(*)\MaxQueueItemAge` doesn't seem to be populated consistently (seems to be cleared if nothing is in the queue), and gives this error:

```
2022-09-28T17:47:57.094Z        warn    iisreceiver@v0.60.0/scraper.go:122      some performance counters could not be scraped;         {"kind": "receiver", "name": "iis", "pipeline": "metrics", "error": "A counter with a negative denominator value was detected.\r\n"}
```

This happens on **every** scrape, which ends up filling the logs with the same warning.

Even when generating load, I can't figure out how to get this metric to consistently report.

## Steps to Reproduce
Set up a default site for IIS, with no load.
Attempt to scrape using the iis receiver.
See error message in logs.

## Expected Result
No error message if this is expected behavior; Not sure if omitting the metric in this case is the correct behavior or not.

## Actual Result
Error message is printed on every scrape

### Collector version

v0.60.0

### Environment information

Encountered on Windows server 2019, with the default IIS website.

### OpenTelemetry Collector configuration

```yaml
receivers:
  iis:
    collection_interval: 30s

processors:
  batch:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [iis]
      processors: [batch]
      exporters: [logging]
```

### Log output

```shell
2022-09-28T17:47:57.094Z        warn    iisreceiver@v0.60.0/scraper.go:122      some performance counters could not be scraped;         {"kind": "receiver", "name": "iis", "pipeline": "metrics", "error": "A counter with a negative denominator value was detected.\r\n"}
```
