### ISSUE TITLE
Prometheus receiver does not parse labels correctly

### ISSUE THREAD

**Issue by sfc-gh-aivanou** [open-telemetry/opentelemetry-collector-contrib#14583]
## Description
Prometheus receiver does not parse regex correctly.

## Steps to Reproduce

Run prometheus receiver with the following configuration:

```
      prometheus:
        config:
          scrape_configs:
            - job_name: 'node-exporter'
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
              - source_labels: [__address__]
                regex: ^(.*):\d+$
                target_label: __address__
                replacement: $1:9100

```

## Expected Result
`__address__` should have IP address of the node
## Actual Result
The final url: `http://:9100/metrics` . This means that address is not parsed correctly

### Collector version

0.60.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-read
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: 
    - ""
    - "batch"
    - "apps"
    - "autoscaling"
  resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  - endpoints
  - pods
  - jobs
  - batch
  - resourcequotas
  - deployments
  - statefulsets
  - daemonsets
  - cronjobs
  - replicasets
  - namespaces
  - replicationcontrollers
  - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: monitoring-read
  namespace: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: monitoring
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:      

      prometheus:
        config:
          scrape_configs:
            - job_name: 'node-exporter'
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
              - source_labels: [__address__]
                regex: ^(.*):\d+$
                target_label: __address__
                replacement: $1:9100

    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s

      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false

    extensions:
      k8s_observer:
        observe_nodes: true
        observe_pods: true
      host_observer:
      zpages: {}
      memory_ballast:
        size_mib: 683
    exporters:
      otlp/otlp-metrics:
        endpoint: https://otlp-metrics.reg.snowflakecomputing.com:443
        tls:
          insecure_skip_verify: true
      prometheus:
        endpoint: "0.0.0.0:9001"
        resource_to_telemetry_conversion:
          enabled: true
      logging:
        loglevel: debug
        sampling_initial: 5
        sampling_thereafter: 200
    service:
      telemetry:
        logs:
          level: "debug"
      extensions: [zpages, memory_ballast, k8s_observer]
      pipelines:
        metrics/1:
          receivers: [otlp, prometheus]
          processors: [memory_limiter, batch]
          exporters: [prometheus, logging]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.0.0
spec:
  ports:
  - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
    targetPort: 8888
  - name: metricsprom # Default endpoint for querying metrics.
    port: 9001
    targetPort: 9001
  selector:
    app.kubernetes.io/name: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 1.0.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: otel-collector
      app.kubernetes.io/part-of: kube-prometheus
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: kube-prometheus
        app.kubernetes.io/version: 1.0.0
    spec:
      serviceAccountName: monitoring-read
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - 
        securityContext:
          privileged: true
        image: otel/opentelemetry-collector-contrib:latest
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55679 # Default endpoint for ZPages.
        - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
        - containerPort: 14250 # Default endpoint for Jaeger gRPC receiver.
        - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
        - containerPort: 9411 # Default endpoint for Zipkin receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        - containerPort: 9001
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /etc/otelcol-contrib/config.yaml
          subPath: config.yaml
      volumes:
        - configMap:
            name: otel-collector-conf
          name: otel-collector-config-vol
```

### Log output

```shell
{"kind": "exporter", "data_type": "metrics", "name": "logging"}
2022-09-28T21:38:37.675Z	debug	scrape/scrape.go:1317	Scrape failed	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_pool": "node-exporter", "target": "http://:9100/metrics", "error": "Get \"http://:9100/metrics\": dial tcp :9100: connect: connection refused"}
2022-09-28T21:38:37.676Z	warn	internal/otlp_metricsbuilder.go:164	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_timestamp": 1664401117675, "target_labels": "map[__name__:up aivanou:amd64 aivanouos:linux instance:aivanou-test-m04 job:node-exporter]"}
2022-09-28T21:38:37.789Z	debug	prometheusexporter@v0.56.0/accumulator.go:90	accumulating metric: up	{"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
2022-09-28T21:38:37.789Z	debug	prometheusexporter@v0.56.0/accumulator.go:90	accumulating metric: scrape_duration_seconds	{"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
```

**Comment by bryan-aguilar** [comment]
```
              relabel_configs:
              - source_labels: [__address__]
                regex: ^(.*):\d+$
                target_label: __address__
                replacement: $$1:9100
```
Could this be an issue due to the relabel config requiring double dollar signs? Prom receiver readme has more info [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver#getting-started).
