### ISSUE TITLE
[receiver/hostmetrics] Process scraper fails to read parent-process information for some processes on Windows

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#14679]
## Description
When using the `process` scraper on windows, errors are constantly logged, indicating that some processes do not exist.
This ends up filling the logs with the same error repeatedly, which may bury other logs.

## Steps to Reproduce
Run the collector as administrator with the `process` scraper enabled.

## Expected Result
No errors are logged.

## Actual Result
Error is logged on each scrape.

### Collector version

v0.61.0

## Environment
OS: Windows server 2019

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics/host__source0:
    collection_interval: 60s
    scrapers:
      filesystem:
      load:
      memory:
      network:
      paging:
      process:
        mute_process_name_error: true

exporters:
  logging:

service:
  pipelines:
    metrics:
      receivers:
        - hostmetrics
      exporters:
        - logging
```

### Log output

```shell
{"level":"error","ts":"2022-10-03T18:15:13.347Z","caller":"scraperhelper/scrapercontroller.go:197","msg":"Error scraping metrics","kind":"receiver","name":"hostmetrics/host__source0","pipeline":"metrics","error":"error reading parent pid for process \"csrss.exe\" (pid 388): process does not exist; error reading parent pid for process \"wininit.exe\" (pid 460): process does not exist; error reading parent pid for process \"csrss.exe\" (pid 468): process does not exist; error reading parent pid for process \"winlogon.exe\" (pid 520): process does not exist; error reading parent pid for process \"explorer.exe\" (pid 2516): process does not exist; error reading parent pid for process \"csrss.exe\" (pid 4340): process does not exist; error reading parent pid for process \"winlogon.exe\" (pid 4384): process does not exist","scraper":"process","stacktrace":"go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\tC:/Users/runneradmin/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/receiver/scraperhelper/scrapercontroller.go:197\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\tC:/Users/runneradmin/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/receiver/scraperhelper/scrapercontroller.go:172"}
```
