### ISSUE TITLE
[receiver/hostmetrics] Scraping process metrics gives parent PID read error on Linux

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#14681]
## Description
When scraping process metrics on linux, an error indicating that an invalid PID (0) is being read.
This fills the logs on each scrape with error logs, that may drown out other important logs.

## Steps to Reproduce
Scrape process metrics as root

## Expected Result
No error is logged 

## Actual Result
Error message about error reading parent PID for systemd (PID = 0)

### Collector version

v0.61.0

### Environment information

OS: Debian 11 (bullseye)

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics/host__source0:
    collection_interval: 60s
    scrapers:
      filesystem:
      load:
      memory:
      network:
      paging:
      process:
        mute_process_name_error: true

exporters:
  logging:

service:
  pipelines:
    metrics:
      receivers:
        - hostmetrics
      exporters:
        - logging
```

### Log output

```shell
{"level":"error","ts":"2022-10-03T17:44:51.239Z","caller":"scraperhelper/scrapercontroller.go:197","msg":"Error scraping metrics","kind":"receiver","name":"hostmetrics/host__source0","pipeline":"metrics","error":"error reading parent pid for process \"systemd\" (pid 1): invalid pid 0","scraper":"process","stacktrace":"go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/receiver/scraperhelper/scrapercontroller.go:197\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector@v0.61.0/receiver/scraperhelper/scrapercontroller.go:172"}
```
