### ISSUE TITLE
Compaction on rebound occuring before needed threshold is reached

### ISSUE THREAD

**Issue by jeremyaouad** [open-telemetry/opentelemetry-collector-contrib#14701]
## Description
I have code emitting metrics and logs to a collector. The collector then emits to a visualizer.
I'm doing a test where I `kill -STOP` the visualizer for 10 minutes, and switch it back on, in order to test the compaction on rebound. Only after the visualizer comes back online, I expect to have compaction, and not before.
I configured compaction as follows:
```
extensions:
  file_storage:
    directory: ${WORK_DIR}
    compaction:
      on_start: true
      on_rebound: true
      directory: ${WORK_DIR}
      max_transaction_size: 0
      rebound_needed_threshold_mib: 4000
      rebound_trigger_threshold_mib: 500
      check_interval: 60s
service:
  extensions: [file_storage]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [otlp/mocked_metrics_viz] # kill -STOP for 10 min, then kill -CONT
    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlp/mocked_logs_viz] # kill -STOP for 10 min, then kill -CONT
    metrics/splunk:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [splunk_hec/metrics] # Never stopped, so that we can get the below graphs
```
Since bbolt mmaps disk to memory, I am monitoring the memory of the collector process and cpu.

## Actual Result
Compaction on rebound:
![compaction_on_rebound](https://user-images.githubusercontent.com/4114863/193837573-b18c545f-19aa-4255-9195-ddd0b4cc774d.PNG)

Same scenario without compaction:
We can see that memory goes up above 4 GB after the collector resumes sending to the continued visualizers. This is where I expected to see compaction on rebound happening.
![no_compaction](https://user-images.githubusercontent.com/4114863/193836534-277d6d87-05e1-4876-9306-2414c16333af.png)

### Collector version

0.54.0

## Environment
OS: Red Hat Enterprise Linux release 8.5 (Ootpa)
Compiled on: rhel8 - gcc8 cpp17
