### ISSUE TITLE
[extension/jaegerremotesampling] port collision when converting old receiver settings

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-collector-contrib#14707]
## Description

The jaeger remote sampling extension collides when converting old jaeger receiver settings. The problem can be solved by manually switching to another port, but this leads to potentially invalid configurations for reporters.

Extension readme says:
```
By default, two listeners are made available:

    localhost:5778, following the legacy remote sampling endpoint as defined by Jaeger
    localhost:14250, following the gRPC remote sampling endpoint, also defined by Jaeger

Note that the port 14250 will clash with the Jaeger Receiver. When both are used, it's recommended to change this extension to use another port.
```

## Expected Result

If the extension port matches the receiver port, both endpoints should be registered to the same gRPC server.

## Actual Result

Collector does not launch.

### Collector version

v0.61.0

### OpenTelemetry Collector configuration

```yaml
# v0.60.0 or less
---
extensions:
  jaegerremotesampling:
    source:
      reload_interval: 10s
      file: strategy.json
receivers:
  jaeger:
    protocols:
      grpc:
    remote_sampling:
      strategy_file: "strategy.json"
      strategy_file_reload_interval: 10s

exporters:
  logging:

service:
  pipelines:
    traces:
      exporters:
      - logging
      receivers:
      - jaeger

# v0.61.0 or higher
---
extensions:
  jaegerremotesampling:
    source:
      reload_interval: 10s
      file: strategy.json
receivers:
  jaeger:
    protocols:
      grpc:

exporters:
  logging:

service:
  extensions:
  - jaegerremotesampling
  pipelines:
    traces:
      exporters:
      - logging
      receivers:
      - jaeger
```

### Log output

```shell
Error: cannot start pipelines: failed to bind to gRPC address {"0.0.0.0:14250" "tcp"}: listen tcp 0.0.0.0:14250: bind: address already in use
2022-10-04 17:57:04.066136 I | collector server run finished with error: cannot start pipelines: failed to bind to gRPC address {"0.0.0.0:14250" "tcp"}: listen tcp 0.0.0.0:14250: bind: address already in use
```
