### ISSUE TITLE
[exporter/Loki] Unable to make a connection from Otel to Loki

### ISSUE THREAD

**Issue by Depechie** [open-telemetry/opentelemetry-collector-contrib#14746]
### Describe the issue you're reporting

I'm trying out the Loki exporter.
But I keep getting the following exception in my OTEL container:
`OpenTelemetryCollector config, the OTEL/Loki exporter will give the exception: }. Err: connection error: desc = "transport: Error while dialing dial tcp: address tcp/3100/loki/api/v1/push: unknown port"	{"grpc_log": true}`

I tried several url notations in my otel config yaml, in combination with docker-compose port settings. But somehow I'm not able to get it working.

Are there any sample repo's with a working setup?

**Comment by Depechie** [comment]
Seems I made a type in the exporter tag.
Logs are working fine!

**Comment by nanoandvim** [comment]
What was the typo in your tag? I have the same issue but not seeing what could be causing it?

**Comment by nanoandvim** [comment]
This is what my otel-config looks like

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlp/loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ logging, otlp/tempo ]
    logs:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ logging, otlp/loki ]
```
