### ISSUE TITLE
New component: Flex Metrics Receiver

### ISSUE THREAD

**Issue by cristianciutea** [open-telemetry/opentelemetry-collector-contrib#14753]
### Description:
`Flex Metrics Receiver` will be an application-agnostic cross-platform receiver with which users can instrument any application that exposes metrics over a standard protocol (HTTP, file, shell) in any format (for example, JSON or plain text). The receiver will scrape and parse the data which will be transformed into OTEL metrics format, based on the rules defined in the yaml configuration.

This solution would be best suited for monitoring custom solutions for which a dedicated receiver doesn't exist.

<img width="735" alt="Screenshot 2022-10-06 at 08 41 35" src="https://user-images.githubusercontent.com/15685307/194311244-a73cd588-95ee-48d8-b681-f10ca2210c40.png">

### Context:
This solution is inspired by the [NewRelic flex integration](https://github.com/newrelic/nri-flex/tree/master/examples) which is an application-agnostic, all-in-one tool that allows you to collect metric data from a wide variety of services. It comes bundled with NewRelic infrastructure agent. You can instrument any app that exposes metrics over a standard protocol (HTTP, file, shell) in a standard format (for example, JSON or plain text): you create a YAML config file, start the Infrastructure agent, and your data is reported to New Relic.

NewRelic flex already has dozens (200+) of example yaml config files that can be shared and these contributions would increase the surface area of OTEL instrumentation. Each config yaml file can be viewed as an independent/different Receiver.
Also, after learning the flex syntax, we can create new Receivers easily without development/releasing a new collector version.
Community contributes with new examples without having knowledge of the Collector internals.

### Example configuration for the component

The following examples illustrate the most common use cases: HTTP, db and shell. This configuration structure is inspired by the logs operator pattern.

HTTP Example:
```yaml
---
flexreceiver:
  config:
      name: http_example
      vars:
        client_id: 'XYZ'
      inputs:
        - url:
            run: http://endpoint/{vars.client_id}/token/
            method: POST
            payload: >-
              client_id={vars.client_id}
            # Ignore the output, this call is just for obtaining the token for next calls
            ignore_output: true
            store_var:
              # Assuming that the endpoint will return {“atoken”: “XYZ”}
              token: atoken
        - url:
            run: http://endpoint/{vars.client_id}/data/
            method: GET
            headers:
              Authorization: Bearer {vars:token}

            # Processors should be allowed on both levels: input and collector
      operators:
        - jq: '.[0][0]["server_metrics"]' # output e.g.: {"uptime": 12}
      metrics:
        - name: uptime
           value_from: http_example.uptime 
           unit: s
```

Database query example

```yaml
---
flexreceiver:
  config:
    name: db_example
    inputs:
      - db:
          db_driver: mysql
          db_conn: newrelic:Password@tcp(rds-name.region.rds.amazonaws.com:3306)/sys
          - queries:
              run: SHOW VARIABLES;
  # if metrics operators rules are not specified, default db operator would be used.
```

Shell command example
```yaml
flexreceiver:
  config:
    name: cmd_example
    inputs:
      - command:
        # e.g.
        # 35092301.29 34692781.58
            run: |
              "cat /proc/uptime | awk '{print $0}'"
    operators:
      - regex_parser: "(?P<secondsUptime>.*)\s+(?P<secondsIdleCores>.*)"
      - math:
           metric_name: newMetric
           formula: "cmd_example.secondsUptime / cmd_example.secondsIdleCores"
    metrics:
      - name: secondsUptime
         value_type: double
         value_from: cmd_example.secondsUptime 
         unit: s
         attributes:
           server_name: server_name
     - name: newMetric
        value_from: cmd_example.newMetric
        value_type: double
        unit: s
```

### Telemetry data types supported

Currently flex supports only metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

Flex library will be maintained by New Relic, however this library will be an agnostic data fetcher and parser without any backend specific features.

### Documentation
OTEL flex receiver will contain documentation on how to use the existing configuration examples as well as on how to use each input/processor in order to enable users to build their own integrations
