### ISSUE TITLE
New component: prometheus remotewrite receiver

### ISSUE THREAD

**Issue by adamkubon** [open-telemetry/opentelemetry-collector-contrib#14751]
### The purpose and use-cases of the new component

It consumes data from prometheus remote-write protocol

### Example configuration for the component

```yaml
receivers:
  prometheusremotewrite:
    endpoint: 0.0.0.0:19291
```

### Telemetry data types supported

metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

There are existing prometheus receivers, but no any remote-write interface support
