### ISSUE TITLE
New component: Snowflake Receiver

### ISSUE THREAD

**Issue by shalper2** [open-telemetry/opentelemetry-collector-contrib#14754]
### The purpose and use-cases of the new component

Snowflake is a fast growing data cloud company which allows users to store, manipulate, and analyze data in a SaaS platform.  Its database functionality has found use across multiple industries and the technology is quickly becoming foundational to new and existing platforms. 

The Snowflake receiver would be used to connect to snowflake and then perform queries, converting any results into metrics. Examples could be billing metrics, performance metrics, and security related metrics such as log in attempts. All queries supported by this receiver will be pre defined and included in the receiver module and will target a specific set of metrics to provide parity with existing tools.

While snowflake metrics are accessible through the likes of the [signalfx smart agent](https://github.com/signalfx/signalfx-agent) it makes sense to include a native receiver to improve user experience and reduce the number of tools a customer might need to satisfy their operational requirements.

### Example configuration for the component

```yaml
receivers:
  snowflakedb:
    username: snow
    password: flake
    account: isvery-cool
    warehouse: metricswarehouse
    database: snowflake # defaults to 'snowflake'
    role: accountadmin # defaults to accountadmin (this is inline with default permissions)
    metrics:  # all metrics default to enabled, created using mdatagen
      <metric_name>:
        enabled: <true|false>
```

### Telemetry data types supported

metrics

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.
