### ISSUE TITLE
The transformprocessor drops an error when following the specified format

### ISSUE THREAD

**Issue by Dylan-M** [open-telemetry/opentelemetry-collector-contrib#14885]
## Description
Customer tried to use the logs subsection of the transform processor to set a value on a field, based on one of two specific body messages. This could very well just be an issue with the documentation not being clear enough. It was suggested to me that this might only work if what is being set is a top level field, or perhaps need to address it via dot notation such as `attributes.vAPI_up`

## Steps to Reproduce
Add the following to your pipeline
```
transform:
  logs:
    queries:
      - set(vAPI_up, 1) where body == "Validating vAPI endpoint for vCenter"
      - set(vAPI_up, 0) where body == "vAPI failure occurred to complete the operation"
```

## Expected Result
That `vAPI_up` would be set correctly

## Actual Result
Received this error:
```
invalid configuration: processor "transform/custom__tcp__source0__processor1" has invalid configuration: 1:12: unexpected token "," (expected "(" (Value ("," Value)*)? ")"); 1:12: unexpected token "," (expected "(" (Value ("," Value)*)? ")")
```

I will note that changing `vAPI_up` to `vapi_up` resulted in a different error as well.

### Collector version

Unknown, but recent. Suspect 0.59.0 or 0.60.0

## Environment
Information from the customer was not provided. I reproduced using 
OS: ("CentOS Stream 9")
Compiler(if manually compiled): (N/A)

### OpenTelemetry Collector configuration

```yaml
transform:
  logs:
    queries:
      - set(vAPI_up, 1) where body == "Validating vAPI endpoint for vCenter"
      - set(vAPI_up, 0) where body == "vAPI failure occurred to complete the operation"
```

### Log output

```shell
invalid configuration: processor "transform/custom__tcp__source0__processor1" has invalid configuration: 1:12: unexpected token "," (expected "(" (Value ("," Value)*)? ")"); 1:12: unexpected token "," (expected "(" (Value ("," Value)*)? ")")
```
