### ISSUE TITLE
New component: Pure Storage Receiver for FlashArray

### ISSUE THREAD

**Issue by dgoscn** [open-telemetry/opentelemetry-collector-contrib#14886]
### **Pure Storage Receiver for OpenTelemetry**

PureStorage has a product called FlashArray. Currently, we export the arrays to vendor-specific backends, but we want to provide a receiver that will allow customers to send data to their backends of choice

It is possible to see the current FlashArray OpenMetrics exporters [here](https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter).

### Example configuration for the component

```yaml
receivers:
  purefa:
    confighttp.Client
    arrays:
      address:
      token:
    settings:
      metrics_x_collection_interval:
```

### Telemetry data types supported

Metrics 

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

Juraci Paixão Kröhling @jpkrohling
