### ISSUE TITLE
[resourcetotelemetry] - Using resource_to_telemetry_conversion enabled causes broken internal otelcol_ metrics

### ISSUE THREAD

**Issue by gillg** [open-telemetry/opentelemetry-collector-contrib#14900]
## Description
There is a prometheus exporter **error** `failed to convert metric otelcol_xxxxxxxxxxxxx: duplicate label names` if you enable 
```yaml
resource_to_telemetry_conversion:
      enabled: true
```

## Steps to Reproduce
Add a receiver :
```yaml
prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']
```

and enable resource_to_telemetry_conversion at prometheus exporter level.
(I didn't tested yet with prometheusremotewriteexporter)

### Collector version

0.61.0

## Environment
OS: windows server 2019

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']
        - job_name: windows-exporter
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:9182']

exporters:
  prometheus:
    endpoint: "0.0.0.0:9095"
    send_timestamps: true
    metric_expiration: 30s
    enable_open_metrics: false
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:
    send_batch_size: 50
    timeout: 5s
  resourcedetection:
    detectors: ["gke","aks","eks","ec2","gce","azure","ecs"]
    ec2:
      tags:
        - ^Name$
  resource/metrics:
    attributes:
    - key: job_from
      from_attribute: job
      action: insert
    #- key: job
    #  action: delete
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_percentage: 30

extensions:
  health_check:
  memory_ballast:
    size_mib: 32

service:
  extensions: [memory_ballast,health_check]
  telemetry:
    logs:
      level: info
    metrics:
      level: normal
      address: ":8888"
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, resourcedetection, resource/metrics, batch]
      exporters: [prometheus]
```

### Log output

```shell
2022-10-12T12:11:59.062Z        error   prometheusexporter@v0.61.0/collector.go:367     failed to convert metric otelcol_process_cpu_seconds: duplicate label names     {"kind": "exporter", "data_type": "metrics", "name": "prometheus"
}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).Collect
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.61.0/collector.go:367
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:455
2022-10-12T12:11:59.067Z        error   prometheusexporter@v0.61.0/collector.go:367     failed to convert metric otelcol_processor_batch_batch_send_size: duplicate label names {"kind": "exporter", "data_type": "metrics", "name": "pro
metheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).Collect
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.61.0/collector.go:367
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:455
2022-10-12T12:11:59.067Z        error   prometheusexporter@v0.61.0/collector.go:367     failed to convert metric otelcol_exporter_enqueue_failed_spans: duplicate label names   {"kind": "exporter", "data_type": "metrics", "name": "pro
metheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).Collect
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.61.0/collector.go:367
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:455
```

**Comment by gillg** [comment]
I found the reason, the duplicated label is `service.instance.id`.
Internaly the value is a random uuid, but once scrapped by prometheus receiver, the "instance" become "localhost:8888".
Then if we enable resources as attributes, the instance is converted to service.instance.id and it cause a duplicated label.

**Comment by jojotong** [comment]
Any updates? I met the same problem.

**Comment by jojotong** [comment]
I tested it with `prometheusremotewriteexporter`, it's no problem.
**BUT** how to resolve this with `prometheus exporter`?

**Comment by Aneurysm9** [comment]
This is handled in the PRW exporter by duplicate detection logic added [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/8378).  @dashpole is this logic Prometheus-specific or should it be incorporated in the resource to telemetry helper?  It doesn't seem right for that helper to be creating duplicate attributes.

**Comment by dashpole** [comment]
> is this logic Prometheus-specific or should it be incorporated in the resource to telemetry helper? It doesn't seem right for that helper to be creating duplicate attributes.

I think it should be incorporated into the resource-to-telemetry helper.

**Comment by mx-psi** [comment]
I am not sure what the intended fix for this issue is. Do we want the helper to do nothing when adding the labels would result in duplicates?

> Internaly the value is a random uuid, but once scrapped by prometheus receiver, the "instance" become "localhost:8888".
> Then if we enable resources as attributes, the instance is converted to service.instance.id and it cause a duplicated label.

What does this imply in terms of the generated OTLP payload? I don't quite understand this sentence, I assume this is some Prometheus-specific behavior that I am not aware of

**Comment by mx-psi** [comment]
@Aneurysm9 can you help answering https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14900#issuecomment-1460031172 ? Thanks!

**Comment by dashpole** [comment]
Maybe instead of producing an error, it should prefer one over the other.  It seems like the otel-generated one should take precedence?  I.e. only change instance to service.instance.id if it doesn't already exist?

**Comment by oskoi** [comment]
@Aneurysm9 @dashpole Hi!

I ran into the same issue and it's blocking us.

prometheusexporter already has deduplication logic for labels. Maybe it's worth expanding to this case as it's done in PRW exporter?

**Comment by krsmanovic** [comment]
I have fixed the issue with the metric relabeling configuration:
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector-self'
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:8888']
          metric_relabel_configs:
            - action: labeldrop
              regex: "service_instance_id|service_name"
```

**Explanation**

Prometheus exporter is automatically generating not only `service.instance.id` label (thanks @gillg), but in my case it was also rendering new `service.name` label value. Original `service.name` label value on the receiver was `otelcol-contrib`, however, the exporter is setting that value to match job name, in this case `otel-collector-self`.

Collector version I have tested this on is 0.78.

**Comment by netsandbox** [comment]
> I have fixed the issue using the metric relabeling configuration in the receiver:
> 
> ```
> receivers:
>   prometheus:
>     config:
>       scrape_configs:
>         - job_name: 'otel-collector-self'
>           scrape_interval: 30s
>           static_configs:
>             - targets: ['localhost:8888']
>           metric_relabel_configs:
>             - action: labeldrop
>               regex: "service_instance_id|service_name"
> ```
> 
> **Explanation**
> 
> Prometheus exporter is automatically generating not only `service.instance.id` label (thanks @gillg), but in my case it was also rendering new `service.name` label value. Original `service.name` label value on the receiver was `otelcol-contrib`, however, the exporter is setting that value to match job name, in this case `otel-collector-self`.
> 
> Collector version I have tested this on is 0.78.

Besides `service_instance_id|service_name` I also had to add `http_scheme|net_host_port` to get rid of the error messages:

```
2024-03-11T11:11:21.249Z        error   prometheusexporter@v0.96.0/collector.go:381     failed to convert metric otelcol_http_server_request_size: duplicate label names in constant and variable labels for metric "otelcol_http_server_request_size_total"    {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).Collect
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.96.0/collector.go:381
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        github.com/prometheus/client_golang@v1.19.0/prometheus/registry.go:457
2024-03-11T11:11:21.250Z        error   prometheusexporter@v0.96.0/collector.go:381     failed to convert metric otelcol_http_server_duration: duplicate label names in constant and variable labels for metric "otelcol_http_server_duration"  {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).Collect
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.96.0/collector.go:381
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        github.com/prometheus/client_golang@v1.19.0/prometheus/registry.go:457
2024-03-11T11:11:21.253Z        error   prometheusexporter@v0.96.0/collector.go:381     failed to convert metric otelcol_http_server_response_size: duplicate label names in constant and variable labels for metric "otelcol_http_server_response_size_total"  {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).Collect
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.96.0/collector.go:381
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        github.com/prometheus/client_golang@v1.19.0/prometheus/registry.go:457
```

**Comment by acar-ctpe** [comment]
@netsandbox @krsmanovic how did you find out which labels are conflicting

**Comment by samuelchrist** [comment]
I see the same error

```
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).Collect
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.100.0/collector.go:386
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        github.com/prometheus/client_golang@v1.19.0/prometheus/registry.go:457
2024-07-03T04:21:50.742Z        error   prometheusexporter@v0.100.0/collector.go:386    failed to convert metric otelcol_http_server_response_size: duplicate label names in constant and variable labels for metric "otelcol_http_server_response_size_total"     {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
```
I have added label drop. But still the issue is present

```
      prometheus:
        config:
          scrape_configs:
          - job_name: otel-collector-agent
            scrape_interval: 15s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
            metric_relabel_configs:
            - action: labeldrop
              regex: "service_instance_id|service_name|http_scheme|net_host_port"
```

**Comment by autokilla47** [comment]
any updates?

**Comment by lindsaylandry** [comment]
I have been able to remove this error by setting `honor_labels=true` within `scrape_configs`
```
config:
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'opentelemetry-collector'
            honor_labels: true

```
From prometheus configuration docs:
```
# honor_labels controls how Prometheus handles conflicts between labels that are
# already present in scraped data and labels that Prometheus would attach
# server-side ("job" and "instance" labels, manually configured target
# labels, and labels generated by service discovery implementations).
#
# If honor_labels is set to "true", label conflicts are resolved by keeping label
# values from the scraped data and ignoring the conflicting server-side labels.
```
