### ISSUE TITLE
[prometheusreceiver] Edge case with external labels being duplicated/added to regular labelset

### ISSUE THREAD

**Issue by gracewehner** [open-telemetry/opentelemetry-collector-contrib#14901]
## Description
When external labels are added to the prometheus config in the prometheusreceiver, scrapes for certain targets will start to fail due to duplicate external labels being included. However, this only seems to happen for certain external labels and certain targets. I can repro with external labels where one is a prefix of the other such as `cluster` and `cluster_type` and with `kube-state-metrics` as a target. With other targets like `kube-proxy` or `coredns`, I don't see this issue. With version 0.58.0, this issue doesn't exist, but starting with 0.59.0 it does.

## Steps to Reproduce
Use the prometheusreceiver with a global config with external labels `cluster` and `cluster_type` and scraping kube-state-metrics with a scrape interval of 30s. Wait for a couple minutes.

## Expected Result
There should be no scraping errors and the external labels are added to the metrics correctly.

## Actual Result
The first scrape succeeds. The second and subsequent kube-state-metrics scrapes fail due to `invalid sample: non-unique label names`.

From adding debug logs, the external labels are actually duplicated, but only for 1 or 2 timeseries. In the Append function the external labels are already included in the regular labelset for the metric after the first scrape. They are added again, and then are duplicated in the full labelset. The Log output includes some of this added debug logging.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e68ac79ba95592b83c6e5c9f31feba814804052c/receiver/prometheusreceiver/internal/transaction.go#L75-L85

After some time, the regular labelset includes even more duplicates of the external labels and overwrites the metric's labels.

### Collector version

0.59.0 to latest

## Environment
Ubuntu 20.04
go 1.18.4

### OpenTelemetry Collector configuration

```yaml
exporters:
  otlp:
    endpoint: 127.0.0.1:55680
    tls:
      insecure: true
    compression: "gzip"
    retry_on_failure:
      enabled: false
    timeout: 12s
processors:
  batch:
    send_batch_size: 7000
    timeout: 200ms
    send_batch_max_size: 7000
  resource:
    attributes:
    - key: cluster
      value: "$AZMON_CLUSTER_LABEL"
      action: "upsert"
    - key: job
      from_attribute: service.name
      action: insert
    - key: instance
      from_attribute: service.instance.id
      action: insert
receivers:
    prometheus:
      config:
        global:
          external_labels:
            cluster_type: dev
            cluster: cluster_abc
        scrape_configs:
        - job_name: kube-state-metrics
          scrape_interval: 30s
          static_configs:
          - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlp]
      processors: [batch, resource]
```

### Log output

```shell
labelset before external labels: {__name__="kube_pod_status_ready", abcdefghijk="abc", abcdefghijk_abcd="dev", condition="unknown", instance="prom-kube-state-metrics.monitoring.svc.cluster.local:8080", job="kube-state-metrics", namespace="kube-system"}
external labels: %v {abcdefghijk="master", abcdefghijk_abcd="dev"}
{"level":"debug","ts":1665522995.509266,"caller":"scrape/scrape.go:1335","msg":"Append failed","kind":"receiver","name":"prometheus","pipeline":"metrics","scrape_pool":"kube-state-metrics","target":"http://prom-kube-state-metrics.monitoring.svc.cluster.local:8080/metrics","error":"invalid sample: non-unique label names: [\"abcdefghijk\" \"abcdefghijk_abcd\"]"}
dupLabels detected: [abcdefghijk abcdefghijk_abcd]
metricName: kube_pod_status_ready
labelset: %v {__name__="kube_pod_status_ready", abcdefghijk="abc", abcdefghijk="abc", abcdefghijk_abcd="dev", abcdefghijk_abcd="dev", condition="unknown", instance="prom-kube-state-metrics.monitoring.svc.cluster.local:8080", job="kube-state-metrics", namespace="kube-system"}
external labels: %v {abcdefghijk="master", abcdefghijk_abcd="dev"}
{"level":"debug","ts":1665522995.509266,"caller":"scrape/scrape.go:1335","msg":"Append failed","kind":"receiver","name":"prometheus","pipeline":"metrics","scrape_pool":"kube-state-metrics","target":"http://prom-kube-state-metrics.monitoring.svc.cluster.local:8080/metrics","error":"invalid sample: non-unique label names: [\"abcdefghijk\" \"abcdefghijk_abcd\"]"}
```
