### ISSUE TITLE
Support for extracting attributes/labels from log body

### ISSUE THREAD

**Issue by lsampras** [open-telemetry/opentelemetry-collector-contrib#14938]
### Is your feature request related to a problem? Please describe.

I wanna set loki labels for my logs based on a key-value pair in my JSON formatted logs,
we provide an option to set loki labels from attributes but I'm not able to extract the body value to an attribute...

E.g
assuming the logs to be something like
```
{
    "message":"Adding oranges to basket",
    "service":"my-service-1",
    "log_type":"orange_log"
    ...
},
{
    "message":"Peeling apples for Milkshake",
    "service":"my-service-1",
    "log_type":"apple_log"
    ...
}
```
I wanna extract the the log_type and set it as a loki label...

Promtail supports this behaviour via its [pipeline_stages](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#pipeline_stages) configuration
```
  pipeline_stages:
  - json:
      expressions:
        log_type:
  - labels:
      log_type:
```

### Describe the solution you'd like

I see that we already have the attribute processor which supports setting loki labels and adding context based or static attributes,
we also have the transform processor which can be extended to read/parse from log bodies

I think it would be appropriate to extend the behaviour for one of these processors..

Although not sure if this requirement is loki specific (Since most logging solutions index the body and don't need an explicit label) and needs to be implemented in the loki exporter...

### Describe alternatives you've considered

For now the alternatives seem to be either not adding these labels (which would lead to inefficient queries in loki) or using another tool (maybe kafka) to handle this processing...

**Comment by lsampras** [comment]
I've added a minimal version [here](#15282) which modifies `transformprocessor` for this behaviour (which satisfies my usecase),
This still is far from completion, will need more direction/consideration before we choose a solution and cover all cases from a feature standpoint...

**Comment by jpkrohling** [comment]
cc @mar4uk and @kovrus: I think this belongs to a processor instead of to the Loki exporter, but I wonder what your opinions are.

**Comment by kovrus** [comment]
> cc @mar4uk and @kovrus: I think this belongs to a processor instead of to the Loki exporter, but I wonder what your opinions are.

Agree, it should not be a part of the Loki exporter scope, but the processor components.

**Comment by mar4uk** [comment]
After merging the [promtail receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14632) pipeline_stages will be available the same way they are available in promtail itself.
Just checked it and it works. Here is config:

```
receivers:
  promtail:
    config:
        - job_name: loki_push
          loki_push_api:
            server:
              http_listen_port: 3101
              grpc_listen_port: 3600
            labels:
              pushserver: push1
            use_incoming_timestamp: true
          pipeline_stages:
            - json:
                expressions:
                  http_code: http_code
            - labels:
                http_code:

      target_config:
        sync_period: 10s

processors:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: http_code

exporters:
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push
service:
  pipelines:
    logs:
      receivers: [ promtail ]
      processors: [ attributes ]
      exporters: [ loki ]
```

So when using promtail receiver -> loki exporter labels will work out of the box.
If another receiver is used then I agree that extraction belongs to a processor. But which one? transformprocessor? logstransformprocessor?
