### ISSUE TITLE
azuremonitor exporter is not available

### ISSUE THREAD

**Issue by mathus13** [open-telemetry/opentelemetry-collector-contrib#14936]
## Description
Using the docker image otel/opentelemetryconnector:0.62.0, configuring the azuremonitor exporter generates an error on startup

## Steps to Reproduce
use the following config:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  azuremonitor:
    instrumentation_key: {{key}}

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages,azuremonitor]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
```

## Expected Result
application starts, and exports traces to Azure

## Actual Result

> Error: failed to get config: cannot unmarshal the configuration: unknown exporters type "azuremonitor" for "azuremonitor" (valid values: [file opencensus prometheus otlp otlphttp kafka prometheusremotewrite zipkin logging jaeger])
2022/10/13 17:44:59 collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown exporters type "azuremonitor" for "azuremonitor" (valid values: [file opencensus prometheus otlp otlphttp kafka prometheusremotewrite zipkin logging jaeger])

### Collector version

0.62.0

## Environment
OS: Pop! 22.04 / Docker 
```
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:21 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  azuremonitor:
    instrumentation_key: {{key}}

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages,azuremonitor]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
```

### Log output

```shell
Error: failed to get config: cannot unmarshal the configuration: unknown exporters type "azuremonitor" for "azuremonitor" (valid values: [file opencensus prometheus otlp otlphttp kafka prometheusremotewrite zipkin logging jaeger])
2022/10/13 17:44:59 collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown exporters type "azuremonitor" for "azuremonitor" (valid values: [file opencensus prometheus otlp otlphttp kafka prometheusremotewrite zipkin logging jaeger])
```
