### ISSUE TITLE
[receiver/awscloudwatch] 

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#14952]
## Description
validation for named configs will not work as expected as the `createDefaultConfig` creates a non-nil autodiscover config. 

I think for now we should remove the validation check as it is handled later on. 

### Collector version

v0.62.0

## Environment
OS: Darwin
Compiler(if manually compiled): go 18.5

### OpenTelemetry Collector configuration

```yaml
profile: 'kschmitt'
    region: us-east-2
    logs:
      poll_interval: 10s
      groups:
        autodiscover: null
        named:
          /aws/eks/dev-eks-0/cluster:
            names: [kube-apiserver-audit-ea9c831555adca1815ae04b884b30566]
```

### Log output

```shell
2022-10-14 09:55:17.414048 I | collector server run finished with error: failed to get config: invalid configuration: receiver "awscloudwatch" has invalid configuration: both autodiscover and named configs are configured, Only one or the other is permitted
```

### Additional context

i will submit a PR for this shortly
