### ISSUE TITLE
Postgresql metrics receiver has runtime error on type conversion

### ISSUE THREAD

**Issue by gen-xu** [open-telemetry/opentelemetry-collector-contrib#14972]
## Description

Postgresql metrics receiver has runtime error on converting null to int64 for `write_lag` 
and `checkpoint_duration_write` float64 to int64

### Collector version

v0.62.1

## Environment
OS: "Ubuntu 20.04"
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
extensions:
receivers:
    postgresql:
            endpoint: localhost:5432
            transport: tcp
            username: postgres
            password: password
            databases:
                - test_db
            collection_interval: 10s
            tls:
                insecure: true
exporters:
    kafka:
        brokers: [ localhost:9092 ]
        protocol_version: "3.0.0"
processors:
service:
    pipelines:
        metrics:
            receivers: [ postgresql ]
            processors: []
            exporters: [ kafka ]
```

### Log output

```shell
Oct 17 07:17:31 Test-Host otelcol-contrib[3184939]: 2022-10-17T07:17:31.883Z        error        scraperhelper/scrapercontroller.go:197        Error scraping metrics        {"kind": "receiver", "name": "postgresql", "pipeline": "metrics", "error": "sql: Scan error on column index 2, name \"checkpoint_duration_write\": converting driver.Value type float64 (\"4.0602716e+08\") to a int64: invalid syntax; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported; sql: Scan error on column index 2, name \"write_lag\": converting NULL to int64 is unsupported", "scraper": "postgresql"}
```
