### ISSUE TITLE
Prometheus exporter doesn't expose metrics of type counter

### ISSUE THREAD

**Issue by bigman73** [open-telemetry/opentelemetry-collector-contrib#15353]
## Description
A basic and simple OTEL collector is setup with metrics pipelines that export to logging (console) and Prometheus.
When sending `StatsD` metrics of type `gauge` to OTEL collector the metric is exported/exposed on the OTEL Prometheus `/metrics` page

However, with `counter` type metrics the metric is seen in OTEL collector console but doesn't get exposed on the `/metrics` page and as a result doesn't get scraped by Prometheus job which results in metrics data loss.

## Steps to Reproduce

Sending a `gauge` metric: works
```
echo "test.metric:55|g|#myKey:myVal" | nc -w 1 -u localhost 8125 
```
![image](https://user-images.githubusercontent.com/5384551/197006217-2e9fc88f-1207-49ad-aba9-eabe776351ee.png)

Sending a `counter` metric: does not work
```
 echo "test.metric.total:10|c|#myKey:myVal" | nc -w 1 -u localhost 8125
```
The test.metric.total is visible on the console (see below) but the `/metrics` page doesn't show it

## Expected Result
Metrics of `counter` type should be exposed on the `/metrics` page of the OTEL Prometheus exporter

## Actual Result
Metrics of `counter` type are not exposed on the `/metrics` page of the OTEL Prometheus exporter

### Collector version

OTEL Contrib 0.62.1, for AMD64

## Environment
OS: MacOS Monterey 12.6.1 (Intel Core i7)
Using the packaged/pre-compiled OTEL Collector utility

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
  memory_ballast:
    size_mib: 512

receivers:
  statsd:
    endpoint: "0.0.0.0:8125"
    aggregation_interval: 10s
    enable_metric_type: false
    is_monotonic_counter: false

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  logging:
    loglevel: debug

  prometheus:
    endpoint: "0.0.0.0:9999"
    namespace: testcollector
    const_labels:
      label1: test-counters
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [statsd]
      exporters: [logging, prometheus]


  extensions: [health_check, memory_ballast]
```

### Log output

```shell
2022-10-20T12:28:20.245-0400	info	MetricsExporter	{"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 1}
2022-10-20T12:28:20.245-0400	info	ResourceMetrics #0
Resource SchemaURL: 
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope  
Metric #0
Descriptor:
     -> Name: test.metric.total
     -> Description: 
     -> Unit: 
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: Delta
NumberDataPoints #0
Data point attributes:
     -> myKey: Str(myVal)
StartTimestamp: 2022-10-20 16:28:00.243928 +0000 UTC
Timestamp: 2022-10-20 16:28:15.413864 +0000 UTC
Value: 10
```

### Additional context

During the test Prometheus was intentionally not running in order to disable actual scraping. 

I also tried with a `file` exporter and both metrics were written to the metrics log file, as expected:
```
{"resourceMetrics":[{"resource":{},"scopeMetrics":[{"scope":{},"metrics":[{"name":"test.metric","gauge":{"dataPoints":[{"attributes":[{"key":"myKey","value":{"stringValue":"myVal"}}],"timeUnixNano":"1666358868026223000","asDouble":56}]}}]}]}]}
{"resourceMetrics":[{"resource":{},"scopeMetrics":[{"scope":{},"metrics":[{"name":"test.metric.total","sum":{"dataPoints":[{"attributes":[{"key":"myKey","value":{"stringValue":"myVal"}}],"startTimeUnixNano":"1666358862665573000","timeUnixNano":"1666358887015621000","asInt":"5"}],"aggregationTemporality":"AGGREGATION_TEMPORALITY_DELTA"}}]}]}]}
```

Datadog exporter in the same scenario also works as expected with counter or gauge metrics
