### ISSUE TITLE
Consistent common filtering interface across receivers

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-collector-contrib#15656]
### Is your feature request related to a problem? Please describe.

The initial discussion relating to this issue was originated while defining a configuration option for the Podman receiver to exclude/include the instrumented containers based on their image. That configuration option should be as flexible as possible so we can easily add new filtering parameters in the future. So, the primary goal of this would be to see if there is an agreement/standard way to define and implement filtering configuration options.

Podman's configuration proposal: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9013#issuecomment-1262010828

Currently, the dockerstats receiver uses the `exclude_images` configuration option to achive the same behaviour (exclude containers based on their image name). But how the configuration would be extended if we also want to exclude by label, name or cpu usage (`exclude_labels`, `exclude_name`, etc)? Adding new filters might imply repetition of the `exclude` keyword and vertical growth of the configuration.

The same happens with the `mongodbatlasreceiver` with the `include_clusters` and `exclude_clusters` options.

On the other hand, the `hostmetricsreceiver` uses a map structure to define filtering options, indeed, it benefits of the current internal filterset packages for its implementation:

```yaml
network:
  <include|exclude>:
    interfaces: [ <interface name>, ... ]
    match_type: <strict|regexp>
```

Another reason to unify the filtering interface is because its implementation, all the previous receivers use a different implementation. For maintainability and consistency it would be great to use the same implementation.

### Describe the solution you'd like

- Could all the receivers use the internal filterset package?

The previous mentioned components could use it, except the dockerstats receiver that has a feature not available in the filterset pacakge, negations and globs. The receiver could be adapted to maintain backwards functionality compatibility. (Or add a new `match_type` in the filtering package, e.g `extended_regexp`)

The receiver configuration would look like:

```yaml
receivers:
  dockerstats:
    exclude:
      match_type: extended_regexp
      images:
        - nginx/.*
        - httpd_.*
```

Moving to this solution solves the issue of having a single filtering implementation, but not having a single exclude/include configuration option for all the parameters (images, labels, etc). See for example the filesystem configuration in the hostmetricsreceiver:

```yaml
filesystem:
  <include_devices|exclude_devices>:
    devices: [ <device name>, ... ]
    match_type: <strict|regexp>
  <include_fs_types|exclude_fs_types>:
    fs_types: [ <filesystem type>, ... ]
    match_type: <strict|regexp>
  <include_mount_points|exclude_mount_points>:
    mount_points: [ <mount point>, ... ]
    match_type: <strict|regexp>
```

- Could we have a single entry configuration for exclude and include filtering?

A proposal would be to have a single exclude/include configuration option per receiver in which they will contain a nested map for each element that wants to be excluded/included. For example:

```yaml
filesystem:
  <include|exclude>:
    devices:
       names: [ <device name>, ... ]
       uuids: [ <device uuids>, ... ]
       match_type: <strict|regexp>
    fs:
       types: [ <filesystem type>, ... ]
       match_type: <strict|regexp>
    mount_points:
       match_type: <strict|regexp>
       name: [ <mount point>, ... ]
       options: [ <mount point>, ... ]
```

The previous configuration would ease the process of adding additional filters, for example, adding filtering parameter like the devices UUIDs or mount points options.

A tradeoff of this proposal is that only one `match_type` would be available per element to filter (e.g devices).

### Additional context

Could we consider the internal processor's filterset package as a consistent filtering solution for all the receivers? 

Alternative proposal? Any other package of reference?
