### ISSUE TITLE
New component: AWS CloudWatch metrics receiver 

### ISSUE THREAD

**Issue by lewis262626** [open-telemetry/opentelemetry-collector-contrib#15667]
### The purpose and use-cases of the new component

Collect metrics from AWS Cloudwatch metrics and parse them in to OTel pmetric. Some metrics on AWS, such as Lambda memory usage etc, are  only available from CloudWatch — users may want them to be put in one platform for analysis such as Prometheus with Grafana.

### Example configuration for the component

```
receivers:
    awscloudwatchmetrics:
        region: <aws_region>
        profile: <aws_profile> # optional if omitted will use default for current if the AWS credential environment variables are not set
        polling_interval: 60
        metrics:
          named: 
             - namespace: AWS/ALB
                metric_name: RequestCount
             - namespace: AWS/ALB
                metric_name: 500Count
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

Functionality is similar to AWSContainerMetrics receiver, maybe extend that instead and make it more generic?
