### ISSUE TITLE
[exporter/loki] New Loki Exporter format doesn't work with Grafana derived fields

### ISSUE THREAD

**Issue by disfluxly** [open-telemetry/opentelemetry-collector-contrib#15677]
## Description
With the update to the new version of the Loki exporter, all additional attributes which have not been mapped to a Loki Label via "loki.attributes.labels" are added into the Log as JSON blob under the `attributes` key. Grafana is unable to derive the nested attributes as labels, which reduces usability & visibility. In previous versions of the Loki Exporter, unused attributes (in the sense they were not explicit labels) would very conveniently transform into derived fields within Grafana, assuming because of a difference in how these are input into Loki. In addition, Grafana is unable to derive fields from within the `body` blob, which comes out the same was as attributes.

## Steps to Reproduce
I've created a simple docker-compose setup that illustrates this issue. Here is the file tree layout:
```
.
├── docker-compose.yml
└── files
    ├── grafana
    │   └── provisioning
    │       └── datasources
    │           └── datasources.yaml
    ├── logs
    │   └── logs.json
    └── opentelemetry
        └── otel-collector-config-new-exporter.yml
```

`docker-compose.yml`:
```
---
version: "3"
services:
  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/local-config.yaml" ]

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.62.1
    command: ["--config=/etc/opentelemetry/otel-collector-config-new-exporter.yml"]
    volumes:
      - ./files/opentelemetry/:/etc/opentelemetry/
      - ./files/logs/:/var/log/
    depends_on:
      - loki


  grafana:
    image: grafana/grafana:latest
    user: nobody
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    ports:
      - "3000:3000"
    volumes:
      - ./files/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
```

`files/opentelemetry/otel-collector-config-new-exporter.yml`:
```
receivers:
  filelog:
    include: [ /var/log/*.json ]
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%d %H:%M:%S'

processors:
  attributes:
    actions:
      - key: service_name
        value: file-log-collector
        action: insert
      - key: service_origin
        value: opentelemetry
        action: insert
      - key: otherattribute
        value: othervalue
        action: insert
      - key: loki.attribute.labels
        value: service_origin, service_name
        action: insert

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  loki/legacy:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      attributes:
        service_origin: service_origin
        service_name: service_name
  logging:
    loglevel: debug

service:
  extensions:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [attributes]
      exporters: [loki/legacy, logging]
```

`files/grafana/provisioning/datasources/datasources.yaml`:
```
apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
```

`files/logs/logs.json`:
```
{"timestamp": "2022-10-26 21:01:10", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:01:20", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:01:30", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:01:40", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:01:50", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:02:00", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:02:10", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:02:20", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:02:30", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:02:40", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:02:50", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:04:10", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:04:20", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:04:30", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:04:40", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:04:50", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:05:10", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:05:20", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:05:30", "testkey": "testvalue"}
{"timestamp": "2022-10-26 21:05:40", "testkey": "testvalue"}
```

## Expected Result

Using the setup shown above, update the logs.json entries to be the current date & time (utc). Then execute `docker-compose up`. Once everything is running, navigate to `http://localhost:3000/explore?orgId=1` to go into Grafana. Select the Loki datasource, add in params for `service_name=file-log-collector`, and run a query to view the logs. The logs should look similar to this:

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/31159882/198141904-10d4adf8-4eaf-4950-9cb8-62ab88a21ca1.png">

In our Loki Legacy Exporter config, we have identified both `service_origin` and `service_name` to be label hints. In addition, we have also set the `otherattribute` as an attribute on the log. The legacy exporter properly sets the two labels via hints, but also exports the additional `otherattribute` in such a format that Grafana is able to derive it as a field. Further, the `testkey` field within the log message itself has also been derived as a field.

## Actual Result

Using the setup shown above, update the logs.json entries again with recent timestamps, and change the exporter from `loki/legacy` to `loki`. Then execute `docker-compose up`, and again navigate to `http://localhost:3000/explore?orgId=1`  and perform the same query as before. The log will end up looking like this:

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/31159882/198142280-8137e514-307c-4ac1-b689-6cf46931e589.png">

In the above, we can see that the additional attribute `otherattribute` has been embedded into an `attributes` json blob, and is not a derived field. In addition, the embedded `testkey` within the log message is embedded within the larger `body` construct.

### Collector version

v0.62.1

## Environment
MacOS

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include: [ /var/log/*.json ]
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%d %H:%M:%S'

processors:
  attributes:
    actions:
      - key: service_name
        value: file-log-collector
        action: insert
      - key: service_origin
        value: opentelemetry
        action: insert
      - key: otherattribute
        value: othervalue
        action: insert
      - key: loki.attribute.labels
        value: service_origin, service_name
        action: insert

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  loki/legacy:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      attributes:
        service_origin: service_origin
        service_name: service_name
  logging:
    loglevel: debug

service:
  extensions:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [attributes]
      exporters: [loki/legacy, logging]
```
