### ISSUE TITLE
[[extension/bearertokenauth]] transport: authentication handshake failed: tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by sweetpotato0** [open-telemetry/opentelemetry-collector-contrib#15683]
### Describe the issue you're reporting

Hello:
    When i use bearertokenauth authenticator, an error occur：
```bash
2022-10-27T13:27:47.333+0800    warn    zapgrpc/zapgrpc.go:191  [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
  "Addr": "localhost:55691",
  "ServerName": "localhost:55691",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake"     {"grpc_log": true}
```

My config:
```yaml
receivers:
  hostmetrics:
    collection_interval: 60s
    scrapers:
      processes:
  otlp/metrics:
    protocols:
      grpc:
        endpoint: localhost:55691

processors:

exporters:
  logging:
  otlp/metrics:
    endpoint: https://localhost:55691
    auth:
      authenticator: bearertokenauth

extensions:
  bearertokenauth:
    token: "somerandomtoken"

service:
  extensions: [bearertokenauth]
  pipelines:
    metrics/self:
      receivers: [hostmetrics]
      processors: []
      exporters: [otlp/metrics]
    metrics/otlp:
      receivers: [otlp/metrics]
      processors: []
      exporters: [logging]
```
