### ISSUE TITLE
New component: datadogtracemetrics

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/opentelemetry-collector-contrib#15689]
### The purpose and use-cases of the new component

Collects pre-sampling trace stats. Users who wish to use the [probabilistic sampler](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/probabilisticsamplerprocessor) or the [tailsamplingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor#tail-sampling-processor) can prepend this processor to collect [APM Stats](https://github.com/DataDog/datadog-agent/blob/7.37.0/pkg/trace/pb/stats.proto) for Datadog.

### Example configuration for the component

```yaml
receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
  probabilistic_sampler:
    sampling_percentage: 10
  datadogtracemetrics:

exporters:
  datadog:
    api:
      key: ${DD_API_KEY}

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, k8sattributes]
      exporters: [datadog]
    traces:
      receivers: [otlp]
      processors: [batch, k8sattributes, datadogtracemetrics, probabilistic_sampler]
      exporters: [datadog]
```
An `exporter_name` setting would also be available if one wishes to use a non-Datadog exporter. Otherwise, the `datadogtracemetrics` processor would automatically detect the presence of the Datadog exporter and use that.

### Telemetry data types supported

Traces.

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

@mx-psi

### Why don't you use the spanmetricsprocessor?

While this seems to be the most natural solution, there are some disadvantages and limitations that are blocking it:

* Stats accuracy is too low. It uses Histogram instead of ExponentialHistogram.
* Impossible to obtain the original instrumentation scope which is overridden to "spanmetricsprocessor". This is needed because it is an essential property.
* Can not communicate to a potentially remote Datadog Exporter (in the case of gateway deployments) that stats have already been computed elsewhere and it should skip doing that.
* Is high cardinality because it requires the collection of many dimensions to deduce the Datadog counter-part attributes.
* Is marked as experimental.
* Is meant for generic use cases instead of a specific vendor product.
* Does not obfuscate SQL queries, which is needed for aggregation keys to function correctly at Datadog.
* Hacky setup that needs to specify exporter vs. automatic detection that is being proposed here.

### Why don't you use two separate pipelines?
One could use two separate pipelines with two separate exporters:
* One for traces with sampling
* One for traces without sampling that exports only stats

This change involves adding a second exporter, which is fine (considering it is allowed by the community), but raises several difficulties:

* Traces are duplicated in memory (because the `batch` processor marks itself as mutating).
* Config needs to be duplicated between the two exporters (API keys, etc), which makes it error prone. YAML anchors & aliases can mitigate this.
* Does not work very well with gateway deployments. If a local collector has the Datadog trace metrics exporter, it can not communicate to the existing exporter to skip the stats computation, resulting in duplicate computation.
* Worse user experience in terms of configuration: the user not only has to duplicate the exporter config, but also the pipelines (minus the sampler), which is error prone.
