### ISSUE TITLE
[processor/resourcedetectionprocessor] support openshift as metadata provider

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-collector-contrib#15694]
### Is your feature request related to a problem? Please describe.

I would like to be able to add [openshift infrastructure data](https://docs.openshift.com/container-platform/4.11/rest_api/config_apis/infrastructure-config-openshift-io-v1.html) to transmitted telemetry data. 

### Describe the solution you'd like

Another detector:
```yaml
processors:
  resourcedetection/openshift:
    detectors: ["openshift"]
    timeout: 2s
    override: false
```
