### ISSUE TITLE
`experimental_match_labels` in metricstransformprocessor plugin does not work

### ISSUE THREAD

**Issue by sfc-gh-aivanou** [open-telemetry/opentelemetry-collector-contrib#15699]
## Description
Applying `experimental_match_labels` parameter in metricstransformprocessor does not work
## Steps to Reproduce

Create metrics transform with the following configuration:

```
      metricstransform/prod-pod-status:
        transforms:
            - include: some_metric
              action: insert
              new_name: some_new_metric_name
              experimental_match_labels: {"namespace": "kube-system"}
              match_type: regexp
```

## Expected Result
I will see `some_new_metric_name` 
## Actual Result
The `some_new_metric_name` does not appear, even though there is `namespace` label with value `kube-system`

### Collector version

otel/opentelemetry-collector-contrib:latest

### Environment information

docker image: otel/opentelemetry-collector-contrib:latest

**Comment by sfc-gh-aivanou** [comment]
Found interesting issue:

I have the following pipeline:

```
receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: "kube-state-metrics"
            static_configs:
              - targets: ['kube-state-metrics.system-metrics.svc.cluster.local:8080']
            scrape_interval: 5s
            metrics_path: /metrics

  processors:
    batch:
    metricstransform/prod-pod:
      transforms:
          - include: kube_pod_status_unschedulable
            action: insert
            new_name: kube.pod.status.unschedulable.count
            experimental_match_labels: {"exported_namespace": "kube-system"}
            match_type: strict

  extensions:
    zpages: {}
    memory_ballast:
      size_mib: 2500
  exporters:
    prometheus:
      endpoint: "0.0.0.0:9001"
      resource_to_telemetry_conversion:
        enabled: true

  service:
    telemetry:
      logs:
        level: "info"
    extensions: [zpages, memory_ballast]
    
    pipelines:
      metrics/1:
        receivers: [prometheus]
        processors: [
          attributes, 
          metricstransform/prod-pod,
          batch]
        exporters: [prometheus]

```

I have prometheus set up that I use to develop metrics. Prometheus adds `exported_` prefix to some of the labels at the end, which makes things very confusing. The real label is not `exported_namespace`, but `namespace` ..
