### ISSUE TITLE
[vcenterreceiver]collects metric and still prompts x509 error when TLS.Insecure and TLS.InsecureSkipVerify is set

### ISSUE THREAD

**Issue by wzy531a** [open-telemetry/opentelemetry-collector-contrib#15701]
## Description
In a local area network, a self-signed CA certificate is usually used. At this time, I want to skip the certification. Usually, TLS.Insecure and TLS.InsecureSkipVerify are set, but this seems to have no effect, and an x509-related error is still prompted when connecting to the vcenter.

When I was troubleshooting the problem, I found that in [gommomi.NewClient](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/vcenterreceiver/client.go#L60), when parameter TLS.Insecure is true, a [TLSConfig](https://github.com/vmware/govmomi/blob/master/vim25/soap/client.go#L158) will be automatically generated to vm.client. While in the [LoadTLSConfig method](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/vcenterreceiver/client.go#L64), when the CA certificate path is nil, the mothod return TLSConfig is nil, overrides the default generated TLSConfig in [Line#68](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/vcenterreceiver/client.go#L68), resulting in TLS.InsecureSkipVerify not taking effect.

### Collector version

v0.63.0

## Environment
OS: centos 7

### OpenTelemetry Collector configuration

```yaml
receivers:
  vcenter:
    endpoint: *
    username: *
    password: *
    collection_interval: 10s
    tls:
      insecure: true
      insecure_skip_verify: true
exporters:
  file:
    path: "/opt/otelcol/test.txt"
service:
  pipelines:
    metrics:
      exporters: [ file ]
      receivers: [ vcenter ]
```

### Log output

```shell
2022/10/27 10:01:33	error	scraperhelper/scrapercontroller.go:197	Error scraping metrics	{"error": "Post \"https://*.*.*.*:443/sdk\": x509: cannot validate certificate for *.*.*.* because it doesn't contain any IP SANs ...
```
