### ISSUE TITLE
[prometheusreceiver]'le' label on histogram metric id missing or empty

### ISSUE THREAD

**Issue by Dongqi-Guo** [open-telemetry/opentelemetry-collector-contrib#15700]
## Description
I have a otel collector as agent attached on my spring application which exposes '/actuator/prometheus' path to scrape, I configed prometheus receiver and I got the scrape error when collect metrics

## Expected Result
export to thanos backend
## Actual Result
 "error": "'le' label on histogram metric id missing or empty"

### Collector version

v0.63

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
prometheus:
      config:
        scrape_configs:
          - job_name: 'otel'
            static_configs:
              - targets: ['0.0.0.0:8082']
            metrics_path: 'actuator/prometheus'
```
