### ISSUE TITLE
[exporter/datadogexporter] Potential memory leak in Datadog exporter

### ISSUE THREAD

**Issue by indrekj** [open-telemetry/opentelemetry-collector-contrib#15720]
### What happened?

We have an issue where our OpenTelemetry collector (the agent) memory usage is high.

See memory usage:
![Screenshot from 2022-10-31 18-28-03](https://user-images.githubusercontent.com/3438/199059612-262a4cf7-0261-46aa-92c0-132466ff7955.png)

When the memory usage gets high then the collector starts rejecting spans:
![Screenshot from 2022-10-31 18-29-03](https://user-images.githubusercontent.com/3438/199059717-80f61d73-707f-43b7-97a6-1759b1ee83ef.png)

The traffic is not changing much during the graphs. I've also increased the memory limits ~3x without no success (the pictures use the latest and largest values). When the pod is OOM killed at some point, then it works fine until the memory gets high again.

I also ran pprof heap report:
![heap](https://user-images.githubusercontent.com/3438/199058825-b8dc683f-2af2-4228-ae19-6135b5d3d54a.png)

The pprof report seems to indicate that something is up with datadog-agent Concentrator. It seems to be growing without bounds. I tried looking into the otel contrib and datadog-agent codebase, but I didn't really even figure out who exactly calls it.

### Collector version

v0.63.0

## Environment

Kubernetes, running in a pod (2 replicas atm).

```
  resources:
    requests:
      cpu: 400m
      memory: 2048Mi
    limits:
      cpu: 800m
      memory: 2304Mi
```

### OpenTelemetry Collector configuration

```yaml
config:
    receivers:
      otlp/sidecar:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            tls:
              cert_file: /etc/certs/opentelemetry/tls.crt
              key_file: /etc/certs/opentelemetry/tls.key
              client_ca_file: /etc/certs/opentelemetry/ca.crt
    processors:
      attributes/upsert:
        actions:
          - key: deployment.environment
            value: 'prod-us'
            action: upsert
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
        spike_limit_mib: 400
      resourcedetection:
        detectors:
          - env
        override: false
      k8sattributes: {}
      batch:
        # Datadog APM Intake limit is 3.2MB. Let's make sure the batches do not
        # go over that.
        send_batch_max_size: 1000
        send_batch_size: 100
        # This has to be exactly 10 seconds in case DataDog exporter is used:
        # https://docs.datadoghq.com/tracing/setup_overview/open_standards/#ingesting-opentelemetry-traces-with-the-collector
        timeout: 10s
    exporters:
      datadog:
        api:
          key: "${DATADOG_API_KEY}"
          site: datadoghq.com.
        traces:
          span_name_remappings:
            # From ruby services:
            opentelemetry_instrumentation_faraday.client: faraday.client
            opentelemetry_instrumentation_pg.client: pg.client
            opentelemetry_instrumentation_que.consumer: que.consumer
            opentelemetry_instrumentation_que.producer: que.producer
            opentelemetry_instrumentation_rack.server: rack.server
            opentelemetry_instrumentation_redis.client: redis.client
            opentelemetry_instrumentation_sidekiq.consumer: sidekiq.consumer
            opentelemetry_instrumentation_sidekiq.producer: sidekiq.producer
            opentelemetry_instrumentation_sinatra.server: sinatra.server

            # From elixir services:
            opentelemetry_oban.consumer: oban.consumer
            opentelemetry_oban.internal: oban.internal
            opentelemetry_oban.producer: oban.producer
            opentelemetry_tesla.client: tesla.client
            opentelemetry_phoenix.server: phoenix.server
            opentelemetry_ecto.client: ecto.client
    # Extensions are available primarily for tasks that do not involve processing telemetry data.
    # Examples of extensions include health monitoring, service discovery, and data forwarding.
    extensions:
      pprof:
        endpoint: "0.0.0.0:1777"
        block_profile_fraction: 3
        mutex_profile_fraction: 5
      memory_ballast:
        size_mib: 600
    # The service section is used to configure what components are enabled in the Collector
    # based on the configuration found in the receivers, processors, exporters, and extensions sections.
    service:
      # Extensions consist of a list of all extensions to enable.
      extensions:
        - pprof
        - memory_ballast
      # A pipeline consists of a set of receivers, processors and exporters.
      # Pipelines can be of the following types: traces, metrics and logs
      pipelines:
        traces:
          receivers:
            - otlp/sidecar
          processors:
            # The memory_limiter processor should be the first processor
            # defined in the pipeline (immediately after the receivers). This
            # is to ensure that backpressure can be sent to applicable
            # receivers and minimize the likelihood of dropped data when the
            # memory_limiter gets triggered.
            - memory_limiter
            # resourcedetection must come before k8sattributes
            - resourcedetection
            - k8sattributes
            - attributes/upsert
            - batch
          exporters:
            - datadog
```
