### ISSUE TITLE
[logstransform] logstransform is not in the valid processors

### ISSUE THREAD

**Issue by Dongqi-Guo** [open-telemetry/opentelemetry-collector-contrib#16045]
## Description
I tried to use logstransform processor to handle log body from otel agent and then transfer to loki. I configured and started it. the console log shows it is not a valid processor
### Collector version

v0.63

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
centos

### OpenTelemetry Collector configuration

```yaml
processors:
  logstransform:
    operators:
      - type: regex_parser
        regex: 'INFO  \[(?P<traceId>\w*),(?P<agreementNo>\w*)\] (?P<logger>.*) - (?P<httpMethod>.*),(?P<uri>.*),(?P<uri2>.*),(?P<uriDesc>.*),(?P<state>.*),(?P<stateCode>.*),(?P<stateDesc>.*),(?P<responseTime>.*)'
        traceId:
          parse_from: body.traceId
```

### Log output

```shell
* error decoding 'processors': unknown processors type: "logstransform" for id: "logstransform" (valid values: [redaction spanmetrics memory_limiter groupbyattrs k8sattributes metricstransform resource tail_sampling attributes filter experimental_metricsgeneration probabilistic_sampler span transform cumulativetodelta groupbytrace resourcedetection routing batch deltatorate servicegraph])
```
