### ISSUE TITLE
Crash when using fluentfowarder receiver

### ISSUE THREAD

**Issue by geoffreytran** [open-telemetry/opentelemetry-collector-contrib#16058]
## Description

Collector crashes every few minutes when using the fluent forwarder.

## Steps to Reproduce

Send logs fluentbit to the fluentfowarder receiver.

## Expected Result

Collector runs without crashing.

## Actual Result

Collector crashes every few minutes with the following stacktrace in the logs output.

### Collector version

0.63.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

      # prometheus:
      #   config:
      #     scrape_configs:
      #       - job_name: opentelemetry-collector
      #         scrape_interval: 10s
      #         static_configs:
      #           - targets:
      #               - ${MY_POD_IP}:8888

      fluentforward:
        endpoint: 0.0.0.0:8006

    processors:
      batch:
        timeout: 15s
      # If set to null, will be overridden with values based on k8s resource limits
      memory_limiter: 
        check_interval: 1s
        limit_percentage: 85
        spike_limit_percentage: 30


    exporters:
      logging:
        loglevel: debug
      otlp: 
        endpoint: http://default-collector.opentelemetry.svc:4317
        tls:
          insecure: true

    extensions:
      health_check: {}
      memory_ballast: {}

    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
          
      extensions:
        - health_check
        - memory_ballast

      pipelines:
        logs:
          exporters:
            - otlp
            - logging
          processors:
            - memory_limiter
            - batch
          receivers:
            - fluentforward
```

### Log output

```shell
2022-11-03T16:54:48.745Z	info	LogsExporter	{"kind": "exporter", "data_type": "logs", "name": "logging", "#logs": 58955}
panic: runtime error: slice bounds out of range [-8:]

goroutine 116 [running]:
go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1.(*AnyValue).MarshalToSizedBuffer(0xc00082bf38, {0xc001cee000, 0x87, 0x23842e})
	go.opentelemetry.io/collector/pdata@v0.63.0/internal/data/protogen/common/v1/common.pb.go:483 +0xd0
go.opentelemetry.io/collector/pdata/internal/data/protogen/logs/v1.(*LogRecord).MarshalToSizedBuffer(0xc00082bf10, {0xc001cee000, 0x174, 0x23842e?})
	go.opentelemetry.io/collector/pdata@v0.63.0/internal/data/protogen/logs/v1/logs.pb.go:807 +0x529
go.opentelemetry.io/collector/pdata/internal/data/protogen/logs/v1.(*ScopeLogs).MarshalToSizedBuffer(0xc000afa230, {0xc001cee000, 0x3ca, 0x23842e})
	go.opentelemetry.io/collector/pdata@v0.63.0/internal/data/protogen/logs/v1/logs.pb.go:711 +0x23c
go.opentelemetry.io/collector/pdata/internal/data/protogen/logs/v1.(*ResourceLogs).MarshalToSizedBuffer(0xc0018062a0, {0xc001cee000, 0x3f2, 0x23842e})
	go.opentelemetry.io/collector/pdata@v0.63.0/internal/data/protogen/logs/v1/logs.pb.go:657 +0x25c
go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/logs/v1.(*ExportLogsServiceRequest).MarshalToSizedBuffer(0xc0006682e8, {0xc001cee000, 0x23842e, 0x23842e})
	go.opentelemetry.io/collector/pdata@v0.63.0/internal/data/protogen/collector/logs/v1/logs_service.pb.go:352 +0xac
go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/logs/v1.(*ExportLogsServiceRequest).Marshal(0xc002732700?)
	go.opentelemetry.io/collector/pdata@v0.63.0/internal/data/protogen/collector/logs/v1/logs_service.pb.go:332 +0x56
google.golang.org/protobuf/internal/impl.legacyMarshal({{}, {0x743b938, 0xc002732700}, {0x0, 0x0, 0x0}, 0x0})
	google.golang.org/protobuf@v1.28.1/internal/impl/legacy_message.go:402 +0xa2
google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0x28?, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x743b938, 0xc002732700})
	google.golang.org/protobuf@v1.28.1/proto/encode.go:166 +0x27b
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend({{}, 0x80?, 0xb2?, 0x47?}, {0x0, 0x0, 0x0}, {0x73bbcc0?, 0xc002732700?})
	google.golang.org/protobuf@v1.28.1/proto/encode.go:125 +0x79
github.com/golang/protobuf/proto.marshalAppend({0x0, 0x0, 0x0}, {0x7fc90f3138f0?, 0xc0006682e8?}, 0x0?)
	github.com/golang/protobuf@v1.5.2/proto/wire.go:40 +0xa5
github.com/golang/protobuf/proto.Marshal(...)
	github.com/golang/protobuf@v1.5.2/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0x647b280, 0xc0006682e8})
	google.golang.org/grpc@v1.50.1/encoding/proto/proto.go:45 +0x4e
google.golang.org/grpc.encode({0x7fc90f313880?, 0xb293630?}, {0x647b280?, 0xc0006682e8?})
	google.golang.org/grpc@v1.50.1/rpc_util.go:594 +0x44
google.golang.org/grpc.prepareMsg({0x647b280?, 0xc0006682e8?}, {0x7fc90f313880?, 0xb293630?}, {0x0, 0x0}, {0x73fa520, 0xc000188af0})
	google.golang.org/grpc@v1.50.1/stream.go:1692 +0xd2
google.golang.org/grpc.(*clientStream).SendMsg(0xc0027c10e0, {0x647b280?, 0xc0006682e8})
	google.golang.org/grpc@v1.50.1/stream.go:830 +0xfd
google.golang.org/grpc.invoke({0x7409610?, 0xc0012e0180?}, {0x68db2c6?, 0x4?}, {0x647b280, 0xc0006682e8}, {0x647b3c0, 0xc00276c1f8}, 0x0?, {0xc0006fa400, ...})
	google.golang.org/grpc@v1.50.1/call.go:70 +0xa8
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryClientInterceptor.func1({0x74095d8, 0xc0012e2180}, {0x68db2c6, 0x39}, {0x647b280, 0xc0006682e8}, {0x647b3c0, 0xc00276c1f8}, 0xc000c7d880, 0x6a21840, ...)
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.4/interceptor.go:105 +0x3e4
google.golang.org/grpc.(*ClientConn).Invoke(0xc000c7d880?, {0x74095d8?, 0xc0012e2180?}, {0x68db2c6?, 0x39?}, {0x647b280?, 0xc0006682e8?}, {0x647b3c0?, 0xc00276c1f8?}, {0xc0012ff920, ...})
	google.golang.org/grpc@v1.50.1/call.go:35 +0x223
go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/logs/v1.(*logsServiceClient).Export(0xc0012f4468, {0x74095d8, 0xc0012e2180}, 0xc002732610?, {0xc0012ff920, 0x1, 0x1})
	go.opentelemetry.io/collector/pdata@v0.63.0/internal/data/protogen/collector/logs/v1/logs_service.pb.go:272 +0xc9
go.opentelemetry.io/collector/pdata/plog/plogotlp.(*grpcClient).Export(0x49cd20?, {0x74095d8?, 0xc0012e2180?}, {0xc0012e00c0?}, {0xc0012ff920?, 0x0?, 0x0?})
	go.opentelemetry.io/collector/pdata@v0.63.0/plog/plogotlp/grpc.go:50 +0x30
go.opentelemetry.io/collector/exporter/otlpexporter.(*exporter).pushLogs(0xc000b79f40, {0x74095d8?, 0xc0012e2180?}, {0x7409610?})
	go.opentelemetry.io/collector/exporter/otlpexporter@v0.63.0/otlp.go:117 +0x69
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).Export(0x7409610?, {0x74095d8?, 0xc0012e2180?})
	go.opentelemetry.io/collector@v0.63.0/exporter/exporterhelper/logs.go:65 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000a6ecc8, {0x7428528, 0xc001296180})
	go.opentelemetry.io/collector@v0.63.0/exporter/exporterhelper/common.go:203 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc000d8e750, {0x7428528, 0xc001296180})
	go.opentelemetry.io/collector@v0.63.0/exporter/exporterhelper/queued_retry.go:388 +0x58d
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send(0xc0012e8798, {0x7428528, 0xc001296180})
	go.opentelemetry.io/collector@v0.63.0/exporter/exporterhelper/logs.go:132 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x7428528, 0xc001296180})
	go.opentelemetry.io/collector@v0.63.0/exporter/exporterhelper/queued_retry.go:206 +0x39
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1()
	go.opentelemetry.io/collector@v0.63.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61 +0xb6
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers
	go.opentelemetry.io/collector@v0.63.0/exporter/exporterhelper/internal/bounded_memory_queue.go:56 +0x45
```
