### ISSUE TITLE
'invalid memory address or nil pointer dereference' error in Datadog Logs exporter

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-collector-contrib#16077]
### Component(s)

exporter/datadog

## Description

`invalid memory address or nil pointer dereference` runtime error happened for no apparent reason in the Datadog Logs exporter as per the trace info.

## Steps to Reproduce

Unknown (we have the collector running in the VM and when I logged into the machine today to check something else, it was stopped with this error in the console).

## Expected Result

Collector should run continuously without ever producing errors like this.

## Actual Result

Collector completely halted execution.

### Collector version

0.62.1

## Environment
Azure Windows VM

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:

  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      load:
      memory:
      network:
      processes:

processors:
  batch:
    timeout: 10s

  resource:
    attributes:
    - key: deployment.environment
      value: "beta"
      action: upsert

exporters:
  datadog:
    api:
      key: ${DATADOG_APIKEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [datadog]
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [resource, batch]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [datadog]
```

### Log output

```shell
2022-10-27T07:53:56.703Z        info    metadata/metadata.go:216        Sent host metadata      {"kind": "exporter", "data_type": "metrics", "name": "datadog"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x29487f6]

goroutine 165 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter/internal/logs.(*Sender).SubmitLogs(0xc0008278e0, {0x78ea758, 0xc00115bd00}, {0xc001f93b00, 0x2, 0x2})
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.62.0/internal/logs/sender.go:67 +0x236
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter.(*logsExporter).consumeLogs(0xc000bf1b80, {0x6cbc76e?, 0x10?}, {0xc001f93a80?})
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.62.0/logs_exporter.go:101 +0x16c
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).Export(0x2ed8f1e?, {0x78ea800?, 0xc002023b00?})
        go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/logs.go:65 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000962490, {0x7907d80, 0xc000b90c30})
        go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/common.go:203 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc00069d440, {0x7907d80, 0xc000b90c30})
        go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/queued_retry.go:388 +0x58d
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send(0xc000c62198, {0x7907d80, 0xc000b90c30})
        go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/logs.go:132 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x7907d80, 0xc000b90c30})
        go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/queued_retry.go:206 +0x39
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1()
        go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/internal/bounded_memory_queue.go:61 +0xb6
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers
        go.opentelemetry.io/collector@v0.62.1/exporter/exporterhelper/internal/bounded_memory_queue.go:56 +0x45
```
