### ISSUE TITLE
Cannot unmarshal Kafka record received 

### ISSUE THREAD

**Issue by RobertFloor** [open-telemetry/opentelemetry-collector-contrib#16078]
### Component(s)

receiver/kafka

### What happened?

We are attempting to read a Confluent Kafka Audit topic of our organization in the open telemetery collector. This contains audit events which we would like to ingest into the Open telemetry collector. We would like to read the topic and send it to Splunk. We can connect to confluent cloud , but are getting a format error. I have tried all suggested encoders. Somehow we cannot unmarshal the message correctly. Do you have an idear how to decode the messages from the Audit topic? 

### Collector version

0.63.1

## Environment
Docker container (https://hub.docker.com/layers/otel/opentelemetry-collector/latest/images/sha256-5d5669c53025a0a81d725e36e6c60e8ebf502ddc5259a3036ed8f5f8067f4713?context=explore)

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

  kafka:
    brokers:
    - 'xxxxxxx.aws.confluent.cloud:9092'
    topic: 'confluent-audit-log-events'
    protocol_version: 2.6.0
    encoding: zipkin_raw
    auth: 
      sasl:
        username: "xxxxx"
        password: "xxxxxxxxxx"
        mechanism: PLAIN
      tls:
        insecure: false
        insecure_skip_verify: true

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:

exporters:
  logging:
    logLevel: debug

service:

  pipelines:

    traces:
      receivers: [otlp, opencensus, jaeger, zipkin, kafka]
      processors: [batch]
      exporters: [logging]

    metrics:
      receivers: [otlp, opencensus, prometheus]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check, pprof, zpages]
```

### Log output

```shell
otel-collector_1  | 2022-11-04T11:36:36.150Z    error   kafkareceiver@v0.63.0/kafka_receiver.go:419     failed to unmarshal message     {"kind": "receiver", "name": "kafka", "pipeline": "traces", "error": "proto: illegal wireType 6"}
otel-collector_1  | github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.(*tracesConsumerGroupHandler).ConsumeClaim
otel-collector_1  |     github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.63.0/kafka_receiver.go:419
otel-collector_1  | github.com/Shopify/sarama.(*consumerGroupSession).consume
otel-collector_1  |     github.com/Shopify/sarama@v1.37.2/consumer_group.go:868
otel-collector_1  | github.com/Shopify/sarama.newConsumerGroupSession.func2
otel-collector_1  |     github.com/Shopify/sarama@v1.37.2/consumer_group.go:793
otel-collector_1  | 2022-11-04T11:36:36.161Z    error   kafkareceiver@v0.63.0/kafka_receiver.go:419     failed to unmarshal message     {"kind": "receiver", "name": "kafka", "pipeline": "traces", "error": "proto: illegal wireType 6"}
otel-collector_1  | github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.(*tracesConsumerGroupHandler).ConsumeClaim
otel-collector_1  |     github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.63.0/kafka_receiver.go:419
otel-collector_1  | github.com/Shopify/sarama.(*consumerGroupSession).consume
otel-collector_1  |     github.com/Shopify/sarama@v1.37.2/consumer_group.go:868
otel-collector_1  | github.com/Shopify/sarama.newConsumerGroupSession.func2
otel-collector_1  |     github.com/Shopify/sarama@v1.37.2/consumer_group.go:793
```

### Additional context

This is an example record from Confluent Kafka which we would like to recieve from a Kafka Topic: 

See comment below
