### ISSUE TITLE
How to insert new label from an existing one?

### ISSUE THREAD

**Issue by gabrielgiussi** [open-telemetry/opentelemetry-collector-contrib#16099]
### Component(s)

processor/attributes, processor/metricstransform

### Is your feature request related to a problem? Please describe.

I can't find a way to create a label from an existing one as I need to.
I have the existing label `envoy_response_code`, e.g. `envoy_response_code=200` and I want to extract a label `status_class` from it with only the first digit and the rest being replaced with xx, e.g. `status_class=2xx`.

I could do the mapping with something like this
```yaml
- include: envoy_vhost_vcluster_upstream_rq
        action: update
        operations:
          - action: update_label
            label: envoy_response_code
            value_actions:
              - value: 200
                new_value: 2xx
              - value: 503
                new_value: 5xx
```

But then I will lose the original response code which I want to retain. I was expecting to be able to duplicate the label and then do this transformation, but the following isn't working.

```yaml
      - include: envoy_vhost_vcluster_upstream_rq
        action: update
        operations:
          - action: add_label
            new_label: status_class
            new_value: {{envoy_response_code}} # This doesn't work
          - action: update_label
            label: status_class
            value_actions:
              - value: 200
                new_value: 2xx
              - value: 503
                new_value: 5xx
```

### Describe the solution you'd like

I want to be able to derive new labels from existing ones.

### Describe alternatives you've considered

I didn't find an alternative using the attributes processor

**Comment by gabrielgiussi** [comment]
I found an alternative using `experimental_match_labels` although it requires an entry per status code.
```
      - include: envoy_vhost_vcluster_upstream_rq
        action: insert
        experimental_match_labels: { envoy_response_code: 200 }
        new_name: services_http_errors_total
        operations:
          - action: add_label
            new_label: status_class
            new_value: 2xx
      - include: envoy_vhost_vcluster_upstream_rq
        action: insert
        experimental_match_labels: { envoy_response_code: 503 }
        new_name: services_http_errors_total
        operations:
          - action: add_label
            new_label: status_class
            new_value: 5xx
```

Besides being more verbose I have the feeling that could be less performant than the `value_actions` but of course I couldn't say. Do you think this is a viable option meanwhile?

**Comment by dmitryax** [comment]
@gabrielgiussi I believe this is the correct solution using the metricstransform processor. Keep in mind that this processor going forward will be replaced by the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) which is currently under active development. So I'd encourage you to take a look at that processor, and check if it already supports your use case. If it doesn't, feel free to get involved in introducing that functionality.

cc @TylerHelmuth

**Comment by TylerHelmuth** [comment]
@gabrielgiussi if you choose to use the transform processor believe the statements would look like this

```yaml
transform
  metrics:
    statements:
      - set(attributes["status_class"], "2xx") where attributes["envoy_response_code"] == 200
      - set(attributes["status_class"], "5xx") where attributes["envoy_response_code"] == 503
```

Getting more generic you could do 

```yaml
transform
  metrics:
    statements:
      - set(attributes["status_class"], attributes["envoy_response_code"])
      - replace_match(attributes["status_class"], "2*", "2xx")
      - replace_match(attributes["status_class"], "5*", "5xx")
```

**Comment by gabrielgiussi** [comment]
@TylerHelmuth I'm trying to migrate my current config to use the transform but I'm facing some missing features, should I open tickets for all of them?
- scale value like in metricstransformer (I've already created https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16214)
- create new metrics from existing ones (I can use set(metric.name) to rename but I didn't find a way to keep the existing metric). I'm doing this with `action: insert` in metricstransform.
```yaml
- include: runtime.jvm.gc.time
  action: insert
  new_name: jvm_gc_collection_seconds_sum
```

- aggregate data points grouping by label. I'm doing this with `action: aggregate_labels` in metricstransform. e.g.
```yaml
- include: process.runtime.jvm.memory.usage
        action: insert
        new_name: jvm_memory_bytes_used
        operations:
          - action: aggregate_labels
            label_set: [ type ]
            aggregation_type: sum
          - action: update_label
            label: type
            new_label: area
          - action: update_label
            label: area
            value_actions:
              - value: non_heap
                new_value: nonheap
```
- extract multiple labels from an existing label using regex and capture groups, I'm doing that using the attributes processor 
```yaml
include:
      match_type: strict
      metric_names: [envoy_vhost_vcluster_upstream_rq_time, envoy_vhost_vcluster_upstream_rq]
    actions:
      - key: envoy_virtual_cluster
        pattern: ^(?P<method>.+);(?P<path>.+)
        action: extract
      - key: status
        action: insert
        from_attribute: envoy_response_code
```

I want to avoid opening issues if any oh this features is already in the backlog.
