### ISSUE TITLE
Demo example not working on Mac M1 Pro

### ISSUE THREAD

**Issue by saurabhdes** [open-telemetry/opentelemetry-collector-contrib#16090]
### Component(s)

Examples/demo

## Description
Demo example not working on Mac M1 Pro. Specifically demo-server and demo-client are not starting on Mac M1 Pro.

## Steps to Reproduce

1. Clone the repo and go to examples/demo folder
2. Run `docker compose up -d` to launch the demo app

## Expected Result
demo-server and demo-client docker containers start successfully

## Actual Result
demo-server and demo-client docker containers fail to start

<img width="1395" alt="Screen Shot 2022-11-05 at 3 58 32 PM" src="https://user-images.githubusercontent.com/47896520/200144578-d1e4a997-5980-450b-a6f0-47a065d25ae6.png">

<img width="393" alt="image" src="https://user-images.githubusercontent.com/47896520/200144591-c8349130-3f1e-4093-bc4d-1c8ae2884fd6.png">
<img width="589" alt="image" src="https://user-images.githubusercontent.com/47896520/200144599-021b602f-f595-4fc1-aa66-86f1d5d1058f.png">

Both of them display error message `exec /go/bin/main: no such file or directory` in their respective docker container logs

### Collector version

latest

## Environment
Mac M1 Pro

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
```

### Log output

```shell
exec /go/bin/main: no such file or directory
```

### Additional context

The issue is Mac M1 Pro specific  (arm64) and does not occur on prior Mac (x86_64). Also, i found the issue started occuring after https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/15999 which reduced image sizes was merged. I checked out a commit prior to that and did not encounter the above issue.
