### ISSUE TITLE
Elastic Exporter: Metrics: `DoubleValueRecorder` and `LongValueRecorder` are silently ignored

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-collector-contrib#1610]
**Describe the bug**

`DoubleValueRecorder` and `LongValueRecorder` are silently ignored. We could document it and maybe emit a least one warning message per metric waiting to add support for it.

**Steps to reproduce**

Create a `DoubleValueRecorder`with the OpenTelemetry SDK and export the metrics to Elastic. The metric will not appear

```java
Meter meter = OpenTelemetry.getGlobalMeter("my-application");
DoubleValueRecorder orderValueRecorder = meter.doubleValueRecorderBuilder("order").build();

public void createOrder(){
    double orderPrice = ...
    // business logic

    orderValueRecorder.record(orderPrice);
}
```

**What did you expect to see?**

An histogram metric in Elastic or at least, two counters similarly to what the [Elastic Java Agent does with Micrometer](https://www.elastic.co/guide/en/apm/agent/java/current/metrics.html#metrics-micrometer).

**What did you see instead?**

No metric is created in Elastic for `LongValueRecorder` and `DoubleValueRecorder` without message to help understand the limitation.
The source code of the Elastic Exporter indicates "TODO(axw) requires https://github.com/elastic/apm-server/issues/3195" (see [metrics.go#EncodeMetrics()](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.14.0/exporter/elasticexporter/internal/translator/elastic/metrics.go#L137))
 
**What version did you use?**

* OpenTelemetry Collector 0.14
* OpenTelemetry Java Auto Instrumentation 0.10.1

**What config did you use?**

```
extensions:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '127.0.0.1:55680'
  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
      load:
      memory:

processors:
  batch: null
  queued_retry: null

exporters:
  elastic:
    apm_server_url: 'http://localhost:8200'
    secret_token: 'my_secret_token'
  logging:
    loglevel: info
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - hostmetrics
      exporters:
        - logging
        - prometheus
        - elastic
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - elastic
  extensions: [zpages]
```

**Environment**
OS: MacOS
