### ISSUE TITLE
receivercreator gives created receivers a Nop logger

### ISSUE THREAD

**Issue by kohrapha** [open-telemetry/opentelemetry-collector-contrib#1611]
**Describe the bug**
When creating a new receiver, the `receivercreator` passes in a `zap.NewNop` logger as part of the new receiver's params:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/50593285c23eb7e42fce6f2c3f510f3436901c1d/receiver/receivercreator/runner.go#L109

This caused unnecessary headache in debugging the code to figure out why I wasn't getting any output logs from my exporter.

**Steps to reproduce**
1. Use any of the sample configs for `receivercreator`. In my case, I used the k8sobserver + simpleprometheusreceiver.
2. Use the `logging` exporter.
2. Check the logs of the collector and you'll only see "starting receiver" and no logs for the exporter.

**What did you expect to see?**
I expected to see logs output by the exporter.

**What did you see instead?**
No logs being output.

**What version did you use?**
Version: `v0.14.1-0.20201113155149-095d6cd70b64`

**What config did you use?**
Config: 
```yaml
extensions:
  k8s_observer:
    auth_type: serviceAccount

receivers:
  receiver_creator:
    # Name of the extensions to watch for endpoints to start and stop.
    watch_observers: [k8s_observer]
    receivers:
      prometheus_simple:
        rule: type.pod && labels["app"] == "prom-app"
        config:
          metrics_path: /metrics
          endpoint: '`endpoint`:8081'

exporters:
  logging:

service:
  extensions: [k8s_observer]
  pipelines:
    metrics:
      receivers: [receiver_creator]
      exporters: [logging]
```
