### ISSUE TITLE
Support more tail-sampling scenarios

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-collector-contrib#16161]
**Is your feature request related to a problem? Please describe.**
Current tail-sampling policies can only support simple scenarios, for instance:

```yaml
policies:
  [
    {
      type: numeric_attribute,
      numeric_attribute: { key: key1, min_value: 50, max_value: 100 },
    },
    {
      type: string_attribute,
      string_attribute: { key: key2, values: [value1, value2] },
    },
    {
      type: rate_limiting,
      rate_limiting: { spans_per_second: 35 },
    },
  ]
```

It means if a tracing data matches one of these policies, it will be marked as sampled.

I think it should support complicated policies to obtain more benefits from tail-sampling. Here is the scenario.

I wouldn't say I like to use a global sample rate to make sampling decide since it can miss important traces that we are interested in, and those traces are rare, such as traces with high latencies. Therefore, I need some policies to filter out those traces, other traces which not match those policies will be decided by a global sample rate. 

Example policies:
a trace will be sampled once it matches these policies:
- duration > 10s  **OR**
- (http.latency > 1s **AND** rate_limit = 1000 QPS) **OR**
- (error = true **AND** sample_rate = 1%) **OR**
- sample_rate = 0.01%

In this example, all traces that duration is higher than 10s will be sampled. Traces that HTTP latency is higher than 1s will be sampled with 1000 QPS rate limiter. Error traces have a 1% sample rate. Other traces have a 0.01% sample rate.

**Describe the solution you'd like**
Extend tail-sampling policies. For instance:

```yaml
# type: expression
# operator: OR
policies:
  - type: numeric_attribute
    numeric_attribute: { key: duration, min_value: 10000 }
  - type: expression
    operator: AND
    policies:
      - type: numeric_attribute
        numeric_attribute: { key: http.latency, min_value: 1000 }
      - type: rate_limiting
        rate_limiting: { spans_per_second: 1000 }
  - type: expression
    operator: AND
    policies:
      - type: string_attribute
        string_attribute: { key: error, values: [true] }
      - type: probabilistic_sampler
        sampling_percentage: 1
  - type: probabilistic_sampler
    sampling_percentage: 0.01
```

Also, it will allow complicated attribute matching become reality, like `app=foo && error=true`
