### ISSUE TITLE
awsxray exporter can't handle certain database/sql attributes

### ISSUE THREAD

**Issue by felixscheinost** [open-telemetry/opentelemetry-collector-contrib#16178]
### Component(s)

exporter/awsxray

## Description

Some spans which have certain values for the `db.*` attributes don't get displayed on AWS.

Our setup is: AWS OTel Java agent -> AWS OTel collector -> AWS X-Ray

## Steps to Reproduce

I exported the following attributes from a locally running Jaeger instance. This is a span which doesn't show up in production on AWS.

| attribute | value | note |
| ---------| ----- | ---- |
| otel.library.name | io.opentelemetry.jdbc |
| otel.library.version | 1.18.0-alpha |
| thread.name | http-nio-auto-1-exec-6 |
| db.name | offers?database_to_upper=false | this doesn't look right but should still show up on CloudWatch regardless if possible |
| db.sql.table | OFFER |
| db.operation | SELECT |
| db.statement | <omitted, quite long> | I can provide this if necessary but I don't think it is necessary to reproduce the bug, see my code example below |
| db.system | h2 |
| db.connection_string | h2:mem: |
| thread.id | 149 |

I also tried constructing a minimal span which doesn't show up on AWS as well.

```kotlin
    val tracer: Tracer = GlobalOpenTelemetry.getTracer("instrumentation-library-name", "1.0.0")
    val span = tracer.spanBuilder("SELECT offers?database_to_upper=false.OFFER").startSpan()
    span.setAttribute("db.name", "offers")
    // The following line makes the span completely disappear from AWS CloudWatch
    // span.setAttribute("db.name", "offers?")
    try {
      span.makeCurrent()
    } finally {
      span.end()
    }
```

So it seems that just `db.name` containing a `?` breaks something.

## Expected Result

The span should show up on CloudWatch even if the name, etc aren't ideal.

## Actual Result

The span is nowwhere to be found on CloudWatch not even when viewing the raw JSON of the trace.

### Collector version

0.58.0, v0.21.0 of the AWS repacked docker image

## Environment

Running on Fargate.

Debugged locally on macOS. Could reproduce there (see code example above).

### OpenTelemetry Collector configuration

```yaml
exporters:
  awsxray: {}
extensions:
  awsproxy: {}
  health_check: {}
  memory_ballast:
    size_mib: 64
processors:
  batch/metrics:
    timeout: 60s
  batch/traces:
    send_batch_size: 50
    timeout: 1s
  memory_limiter:
    check_interval: 5s
    limit_mib: 400
    spike_limit_mib: 100
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
service:
  extensions:
  - health_check
  - memory_ballast
  - awsproxy
  pipelines:
    traces:
      exporters:
      - awsxray
      processors:
      - memory_limiter
      - batch/traces
      receivers:
      - otlp
```

### Additional context

I can not certainly say that the problem is with the awsxray exporter. The problem could be on AWS side as well. I don't know how to verify that. Could I increase log verbosity?
