### ISSUE TITLE
loadbalancing: "sending_queue" causes OTLP exporter to not work

### ISSUE THREAD

**Issue by ZhengHe-MD** [open-telemetry/opentelemetry-collector-contrib#1621]
**Describe the bug**
I'm not quite sure if this is a real bug, but I will describe what I've found.

I set up the otel-agent with loadbalancing exporter as the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/exporter/loadbalancingexporter/README.md) suggests. And I trigger a trace report through a simple jaeger-instrumented http app. The otel-collector, which is set up with logging exporter only, and supposed to log spans received to stdout, does not output anything. If I replace the loadbalancing exporter with a plain otlp exporter in otel-agent, everything goes well as expected.

So I guess there is something to do with loadbalancing exporter that make it fail to send the trace data out.

**Steps to reproduce**

1. write a custom distribution with the help of [this tutorial](https://medium.com/opentelemetry/building-your-own-opentelemetry-collector-distribution-42337e994b63).

2. Using the second example in loadbalancing exporter README with a little twist:

```yaml
receivers:
  jaeger/loadbalancer:
    protocols:
      thrift_compact:
        endpoint: localhost:6831
  otlp/loadbalancer:
    protocols:
      grpc:
        endpoint: localhost:55680
  otlp/backend-1:
    protocols:
      grpc:
        endpoint: localhost:55690
  otlp/backend-2:
    protocols:
      grpc:
        endpoint: localhost:55700
  otlp/backend-3:
    protocols:
      grpc:
        endpoint: localhost:55710
  otlp/backend-4:
    protocols:
      grpc:
        endpoint: localhost:55720

processors:

exporters:
  logging:
    loglevel: debug
  otlp:
    insecure: true
    endpoint: localhost:55690
  loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        insecure: true
    resolver:
      static:
        hostnames:
          - localhost:55690
          - localhost:55700
          - localhost:55710
          - localhost:55720

service:
  pipelines:
    traces/loadbalancer:
      receivers:
        - otlp/loadbalancer
        - jaeger/loadbalancer
      processors: []
      exporters:
        - loadbalancing
#        - otlp
        - logging

    traces/backend-1:
      receivers:
        - otlp/backend-1
      processors: []
      exporters:
        - logging

    traces/backend-2:
      receivers:
        - otlp/backend-2
      processors: []
      exporters:
        - logging

    traces/backend-3:
      receivers:
        - otlp/backend-3
      processors: []
      exporters:
        - logging

    traces/backend-4:
      receivers:
        - otlp/backend-4
      processors: []
      exporters:
        - logging
```

3. set up a jaeger-instrumented http app.
4. trigger a http request and check the otel-backend's stdout.

**What did you expect to see?**

Because the same otel-collector acts as both agent and collector, there should be two set of trace data, one is due to the logging exporter in traces/loadbalancer pipeline, and the other is due to the logging exporter in any one of the four traces/backend pipelines.

**What did you see instead?**

Only to find one set of trace data. And If I open otlp exporter and comment out the loadbalancing exporter in the yaml config, I can see two sets of trace data.

**What version did you use?**

I ran the experiment in a go1.14 environment. Here are the package versions:

```
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.14.1-0.20201113203156-50593285c23e
github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.14.1-0.20201113203156-50593285c23e
go.opentelemetry.io/collector v0.14.1-0.20201112191733-c6d9a2be2223
```

**What config did you use?**
Config: in *Steps to reproduce* section I've mentioned that.

**Environment**
OS: MacOS 10.15.6
Compiler(if manually compiled): "go 1.14"

**Additional context**

Here are the metrics:

```
# HELP otelcol_exporter_send_failed_spans Number of spans in failed attempts to send to destination.
# TYPE otelcol_exporter_send_failed_spans counter
otelcol_exporter_send_failed_spans{exporter="logging",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 0
# HELP otelcol_exporter_sent_spans Number of spans successfully sent to destination.
# TYPE otelcol_exporter_sent_spans counter
otelcol_exporter_sent_spans{exporter="logging",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 2
# HELP otelcol_loadbalancer_backend_latency Response latency in ms for the backends
# TYPE otelcol_loadbalancer_backend_latency histogram
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="5"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="10"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="20"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="50"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="100"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="200"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="500"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="1000"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="2000"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="5000"} 2
otelcol_loadbalancer_backend_latency_bucket{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",le="+Inf"} 2
otelcol_loadbalancer_backend_latency_sum{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 0
otelcol_loadbalancer_backend_latency_count{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 2
# HELP otelcol_loadbalancer_backend_outcome Number of success/failures for each endpoint
# TYPE otelcol_loadbalancer_backend_outcome counter
otelcol_loadbalancer_backend_outcome{endpoint="localhost:55720",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",success="true"} 2
# HELP otelcol_loadbalancer_num_backend_updates Number of times the list of backends was updated
# TYPE otelcol_loadbalancer_num_backend_updates counter
otelcol_loadbalancer_num_backend_updates{resolver="static",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 1
# HELP otelcol_loadbalancer_num_backends Current number of backends in use
# TYPE otelcol_loadbalancer_num_backends gauge
otelcol_loadbalancer_num_backends{resolver="static",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 4
# HELP otelcol_loadbalancer_num_resolutions Number of times the resolver triggered a new resolutions
# TYPE otelcol_loadbalancer_num_resolutions counter
otelcol_loadbalancer_num_resolutions{resolver="static",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",success="true"} 1
# HELP otelcol_process_cpu_seconds Total CPU user and system time in seconds
# TYPE otelcol_process_cpu_seconds gauge
otelcol_process_cpu_seconds{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 0.19
# HELP otelcol_process_memory_rss Total physical memory (resident set size)
# TYPE otelcol_process_memory_rss gauge
otelcol_process_memory_rss{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 2.9032448e+07
# HELP otelcol_process_runtime_heap_alloc_bytes Bytes of allocated heap objects (see 'go doc runtime.MemStats.HeapAlloc')
# TYPE otelcol_process_runtime_heap_alloc_bytes gauge
otelcol_process_runtime_heap_alloc_bytes{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 1.3994184e+07
# HELP otelcol_process_runtime_total_alloc_bytes Cumulative bytes allocated for heap objects (see 'go doc runtime.MemStats.TotalAlloc')
# TYPE otelcol_process_runtime_total_alloc_bytes gauge
otelcol_process_runtime_total_alloc_bytes{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 1.913936e+07
# HELP otelcol_process_runtime_total_sys_memory_bytes Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')
# TYPE otelcol_process_runtime_total_sys_memory_bytes gauge
otelcol_process_runtime_total_sys_memory_bytes{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 7.3482496e+07
# HELP otelcol_process_uptime Uptime of the process
# TYPE otelcol_process_uptime counter
otelcol_process_uptime{service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d"} 45.009423999999996
# HELP otelcol_receiver_accepted_spans Number of spans successfully pushed into the pipeline.
# TYPE otelcol_receiver_accepted_spans counter
otelcol_receiver_accepted_spans{receiver="jaeger/loadbalancer",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",transport="udp_thrift_compact"} 2
# HELP otelcol_receiver_refused_spans Number of spans that could not be pushed into the pipeline.
# TYPE otelcol_receiver_refused_spans counter
otelcol_receiver_refused_spans{receiver="jaeger/loadbalancer",service_instance_id="2fc3d209-3a14-4954-b484-dfcd43bb793d",transport="udp_thrift_compact"}
```
I did check the return values from otlp grpc sender when I use breakpoints to debug, everything looks fine, as we can see the counter values are what we expected. But only to find that otel-backend with logging exporter configured receive nothing.

Is there supposed to be a `otelcol_receiver_accepted_spans` with receiver being "otlp/backend-x"? That will make this more clear.

**Comment by ZhengHe-MD** [comment]
@jpkrohling please take a look when you are convenient. thanks

**Comment by jpkrohling** [comment]
@ZhengHe-MD I'll take a closer look at your ticket soon, but here's a quick test I did that worked:

```yaml
receivers:
  otlp/loadbalancer:
    protocols:
      grpc:
        endpoint: localhost:55680
  otlp/backend-1:
    protocols:
      grpc:
        endpoint: localhost:55690
  otlp/backend-2:
    protocols:
      grpc:
        endpoint: localhost:55700
  otlp/backend-3:
    protocols:
      grpc:
        endpoint: localhost:55710
  otlp/backend-4:
    protocols:
      grpc:
        endpoint: localhost:55720

processors:

exporters:
  logging:
  jaeger:
    endpoint: localhost:14250
    insecure: true
    retry_on_failure:
      enabled: false
  loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        insecure: true
        sending_queue:
          enabled: false
        retry_on_failure:
          enabled: false
    resolver:
      static:
        hostnames:
          - localhost:55690
          - localhost:55700
          - localhost:55710
          - localhost:55720

service:
  pipelines:
    traces/loadbalancer:
      receivers:
        - otlp/loadbalancer
      processors: []
      exporters:
        - loadbalancing

    traces/backend-1:
      receivers:
        - otlp/backend-1
      processors: []
      exporters:
        - jaeger

    traces/backend-2:
      receivers:
        - otlp/backend-2
      processors: []
      exporters:
        - jaeger

    traces/backend-3:
      receivers:
        - otlp/backend-3
      processors: []
      exporters:
        - jaeger

    traces/backend-4:
      receivers:
        - otlp/backend-4
      processors: []
      exporters:
        - jaeger
```

Here are the metrics on the load balancer side: https://paste.centos.org/view/79c75544
And on Jaeger's side: https://paste.centos.org/view/d813cc38

I need to check if the numbers match, but looks like the load balancer does send data to the backend.

**Comment by ZhengHe-MD** [comment]
@jpkrohling thanks for your reply first.

and problems seems to narrow down to otlp config. I repeat my experiments with the protocol part of your loadbalancing config, which is the following:

```yaml
# ...
loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        insecure: true
        sending_queue:
          enabled: false
        retry_on_failure:
          enabled: false
    resolver:
# ...
```

It magically worked. And I switch back to the default protocol config:

```yaml
# ...
loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        insecure: true
    resolver:
# ...
```

nothing shows up at the backend side.

**Comment by ZhengHe-MD** [comment]
and problems seems to narrow down to otlp config. I repeat my experiments with the protocol part of your loadbalancing config, which is the following:
```yaml
    # ...
    loadbalancing:
        protocol:
          otlp:
            timeout: 1s
            insecure: true
            sending_queue:
              enabled: false
            retry_on_failure:
              enabled: false
        resolver:
    # ...
```

It magically works. And I switch back to the default protocol config:

```
    # ...
    loadbalancing:
        protocol:
          otlp:
            timeout: 1s
            insecure: true
        resolver:
    # ...
```

nothing shows up at the backend side. 

I do more experiments and find that it should be due to the `sending_queue` config, if it is enabled, then nothing got received by the backends, if it is disabled, then the traces show up immediately. Perhaps it is due to the queueing behavior? It's too late in my place now, I can dig into that tomorrow.

**Comment by Vemmy124** [comment]
@jpkrohling I also experience an issue with `sending_queue` config. Enabled - not traces, disabled - everything is fine. I believe it's a real problem

**Comment by jpkrohling** [comment]
Thanks for the feedback, @Vemmy124. Do you have the same problem with a regular OTLP exporter, with the same `sending_queue` configuration? I'm trying to establish whether the problem is in the load balancing exporter or whether this is in the underlying OTLP exporter.

**Comment by Vemmy124** [comment]
The exact same settings with static resolver. These are good and enabling queue produces the problem.
```  
loadbalancing:
  protocol:
    otlp:
      insecure: true
      retry_on_failure:
        enabled: false
      sending_queue:
        enabled: false
```

Currently I'm using OTLP exporter in a custom loadbalancing exporter and it works fine with and without queue
