### ISSUE TITLE
[pkg/stanza/adapter] Missing storage extension causes panic during shutdown

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#16212]
### Component(s)

pkg/stanza

## Steps to Reproduce
```yaml
receivers:
  filelog:
    storage: foo
    include: foo.log

exporters:
  logging:

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```

## Expected Result
```
2022-11-09T10:23:14.838-0500    info    service/service.go:129  Shutdown complete.
Error: cannot start pipelines: storage client: storage extension 'foo' not found
2022-11-09 10:23:14.838221 I | collector server run finished with error: cannot start pipelines: storage client: storage extension 'foo' not found
```

## Actual Result
```
2022-11-09T10:22:15.859-0500    info    adapter/receiver.go:145 Stopping stanza receiver        {"kind": "receiver", "name": "filelog", "pipeline": "logs"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x105c78b9c]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).Shutdown(0x1400101a6c0, {0x109df1ee0, 0x1400019c000})
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.64.0/adapter/receiver.go:151 +0x9c
go.opentelemetry.io/collector/service/internal/pipelines.(*Pipelines).ShutdownAll(0x140000c9090, {0x109df1ee0, 0x1400019c000})
        go.opentelemetry.io/collector@v0.64.0/service/internal/pipelines/pipelines.go:121 +0x378
go.opentelemetry.io/collector/service.(*service).Shutdown(0x14000acce80, {0x109df1ee0, 0x1400019c000})
```

### Collector version

v0.63.1
