### ISSUE TITLE
[processor/transform] Create new metrics from existing ones

### ISSUE THREAD

**Issue by gabrielgiussi** [open-telemetry/opentelemetry-collector-contrib#16221]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

The metricstransformer allow us to [create new metrics from existing ones](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor#create-a-new-metric-from-an-existing-metric) using the action insert, e.g.
```yaml
- include: runtime.jvm.gc.time
  action: insert
  new_name: jvm_gc_collection_seconds_sum
```

Currently we can change the metric name using `set(metric.name)` but this isn't enough if we want to create a metric from a specific subset of label values while retaining the existing metric, next is an example of how I'm currently doing that in the metricstransformer
```yaml
- include: services_http_requests_total
  action: insert
  experimental_match_labels: { status_class: 4xx }
  new_name: services_http_errors_total
```

### Describe the solution you'd like

A function that allows me to create a new metric from an existing one, e.g.
```yaml
- create(services_http_errors_total) where metric.name == "services_http_requests_total" and attributes['status_class'] == "4xx"
```

**Comment by kebroad** [comment]
I can try taking this one on! Its to replace the same on the [metrictransform procesor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/metricstransformprocessor/operation_scale_value.go), right?

**Comment by kebroad** [comment]
I can try taking this on!

**Comment by kebroad** [comment]
After talking with the maintainer we need a way to reference the metric itself with a getter which is not available currently, blocking progress on this issue

**Comment by TylerHelmuth** [comment]
@kebroad thanks for finding this problem in OTTL!

**Comment by TylerHelmuth** [comment]
For reference later:

The issue here is that we what to work on the entire metric within the metric context. The `CopyMetric` function needs to either:
- Take a path as a parameter that returns the entire metric.  Currently no path exists in ottlmetric.
- OTTL needs to provide a way to access the metric right from the `tCtx` variable.  When `tCtx` is a `ottlmetric.TransformContext` there is a `GetMetric` function we could call, but we can't cast `tCtx` as that type within the funciton.

Currently the first option would be the easiest to implement. We could introduce a path like `this` or `self` for all contexts that return themselves.

**Comment by TylerHelmuth** [comment]
Thinking about this problem for a sec I believe it would be solvable if the `CopyMetric` function was limited to only the `ottlmetric.TransformContext`, similar to the Transform Processor's other custom metric functions.

Maybe it isn't appropriate for the contexts to have a generic accessor path - if you need access to the entire context limiting the function to only that context may be appropriate.

Phrased another way, what is an example of a generic function that would need access to the "root" telemetry object no matter what Context it was used in?  Maybe something like a generic `Copy` function?

**Comment by kebroad** [comment]
That seems to make sense to me, but I'm not super familiar on the matter of making more generic functions vs the custom ones in the processor.

So you're envisioning something like [this](https://github.com/kebroad/opentelemetry-collector-contrib/blob/copy-metric/processor/transformprocessor/internal/metrics/func_copy_metric.go)?

**Comment by TylerHelmuth** [comment]
@kebroad yes thats definitely a valid solution.  The question I'd like an answer to before we go that route is if OTTL should support a solution where a context-agnostic function could access the "whole telemetry object".

**Comment by evan-bradley** [comment]
To make a context-agnostic solution work, I think we would need a some supplementary functions and capabilities that allow OTTL to operate more directly on pdata. The important thing is that if we introduce a new `Copy` function, we need a way to change the data to make it uniquely identifiable.

```
set(cache["new_metric"], Copy(this))
set(cache[new_metric"].name, "new_metric")
append(parent, cache["new_metric"])
```

I see a few advantages to this approach:
1. Much more flexible. We could allow copying in any context using the same functions and capabilities.
2. Allows you to edit the item before you put it back into the parent context. This is would be helpful for things like log records or data points that don't have names or other obvious points to uniquely identify them.

There are a few things would would need to be worked out:
1. We need the ability to store pdata objects inside the cache and address them accordingly. Or another way of accessing the context within itself.
2. This is a bit more complex than doing `CopyMetric("new_metric_name")` and working on it in a later loop iteration. We'd want to be sure that this is better than having copy functions for each context that provide a built-in way to give the new item its own identity.

**Comment by TylerHelmuth** [comment]
> We need the ability to store pdata objects inside the cache and address them accordingly. Or another way of accessing the context within itself.
we have https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26108 at the moment that would help.

The generic approach of using the cache has a placeholder to perform more transformations is definitely flexible.  I don't think it is providing much for the metric situation but I can see how that would be useful for copying datapoints and logs.

I think the identity differences between contexts might be a good reason _not_ to do this in a generic way.  Copying a metric or span is quite simple, but the same procedure for datapoints, logs, and resources would require a different approach. Having a copy function per item would allow the more complex items to define custom copy logic.

One this any copy user needs to be worried about is getting stuck in a loop.  If a copy function isn't able to exclude the new metric then we'll endlessly copy and never make it through the for loop. Both the proposed solutions require a where clause on the copy statement.  It would be nice to enforce that somehow.

**Comment by TylerHelmuth** [comment]
The HTTP semantic convention breaking change is causing me to look at this issue again as I need to be able to duplicate a metric and then mess with it.  

I'm still of the opinion that context-specific copy functions is the way to go for these reasons:
1. It fits nicely into the Converter pattern we've defined
2. We don't need to define any new accessors such as `this` or `parent`. I am definitely wary of `parent` as I think providing a direct accessor to the Slice while operating which the slice is risky - I'd prefer to hid those types of operations with functions like the special metrics functions in the Transform Processor.
3. Context-specific functions allow for optional parameters to set new values for fields during the copy.

The the http semantic conventions it could look something like:

```yaml
transform:
  metric_statements:
    - context: metric
      statements:
        - CopyMetric(name="http.server.request.duration", unit="s") where name == "http.server.duration" and metric.type == METRIC_DATA_TYPE_HISTOGRAM
    - context: datapoint:
      statements:
        # rename http.method -> http.request.method
        - set(attributes["http.request.method"], attributes["http.method"]) where attributes["http.method"] != nil and attributes["http.request.method"] != nil and metric.name == "http.server.request.duration" and metric.type == METRIC_DATA_TYPE_HISTOGRAM
        ...
```
