### ISSUE TITLE
[processor/transform] Allow extracting multiple attributes from an existing one using regex and capture groups

### ISSUE THREAD

**Issue by gabrielgiussi** [open-telemetry/opentelemetry-collector-contrib#16222]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

The attributesprocessor already allows to extract multiple attributes from an existing one using regex and capture groups, e.g.
```yaml
include:
      match_type: strict
      metric_names: [envoy_vhost_vcluster_upstream_rq_time, envoy_vhost_vcluster_upstream_rq]
    actions:
      - key: envoy_virtual_cluster
        pattern: ^(?P<method>.+);(?P<path>.+)
        action: extract
``` 

### Describe the solution you'd like

A function similar to the one provided by attributesprocessor
```
- extract(attributes["envoy_virtual_cluster"],"^(?P<method>.+);(?P<path>.+)") where metric.name == "envoy_vhost_vcluster_upstream_rq_time" or metric.name == "envoy_vhost_vcluster_upstream_rq"
```
