### ISSUE TITLE
[spanmetrics] spanmetrics processor throughput is around 300

### ISSUE THREAD

**Issue by wisre** [open-telemetry/opentelemetry-collector-contrib#16231]
### Component(s)

processor/spanmetrics

### Describe the issue you're reporting

when i use spanmetrics plugin,  i found processor throughput Dropped from 2000 to 800, which lead agent packet dropped.

#### otel-col config
```
extensions:
  health_check:
    endpoint: "0.0.0.0:8777"
  pprof:
    endpoint: "0.0.0.0:8778"
  zpages:
    endpoint: "0.0.0.0:8779"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ":5317"
      http:
        endpoint: ":5318"

  jaeger:
    protocols:
      grpc:
        endpoint: "0.0.0.0:16250"
        read_buffer_size: 524288
        max_concurrent_streams: 20
      thrift_binary:
        endpoint: "0.0.0.0:7832"
      thrift_compact:
        endpoint: "0.0.0.0:7831"
      thrift_http:
        endpoint: "0.0.0.0:16268"
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:12345"


processors:
  batch:
    send_batch_size: 1000
    timeout: 3s
  memory_limiter:
    check_interval: 5s
    limit_mib: 10240
    spike_limit_mib: 2048
  spanmetrics:
    metrics_exporter: prometheus
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    dimensions_cache_size: 200000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"

  tail_sampling:
    decision_wait: 10s
    policies:
      [
        {
           name: test-policy-1,
           type: latency,
           latency: {threshold_ms: 10}
        },
       {
           name: test-policy-2,
           type: probabilistic,
           probabilistic: {sampling_percentage: 100}
        },
      ]


exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  jaeger:
    tls:
      insecure: true
    endpoint: "xxx:14250"
    balancer_name: "round_robin"
    timeout: 3s
    sending_queue:
      enabled: true
      num_consumers: 40
      queue_size: 10000
    retry_on_failure:
      enabled: false
      initial_interval: 10s
      max_interval: 60s
      max_elapsed_time: 10m

service:
  pipelines:
    traces:
      receivers: [otlp,jaeger]
      processors: [ spanmetrics,batch]
      exporters: [jaeger]

    metrics:
      receivers: [otlp/spanmetrics]
      exporters: [prometheus]

  telemetry:
    metrics:
      address: "0.0.0.0:9889"
```
#### throughput trend

<img width="860" alt="image" src="https://user-images.githubusercontent.com/15846757/201025422-6b2df922-2eb9-4827-aaca-1ec07b0a0e19.png">

i read code, found that spanmetrics consumer func may be wait until trace compute over?
<img width="818" alt="image" src="https://user-images.githubusercontent.com/15846757/201025658-e55bed37-3b48-4dc2-96da-9cc66fc211a4.png">
