### ISSUE TITLE
[AWS Kinesis Exporter] Missing setting region on startup

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#16259]
### Component(s)

exporter/awskinesis

## Description

When setting the field 
```yaml
aws:
  region: us-east-1
``` 
this is ignore and the SDK default configuration takes place.

## Steps to Reproduce

Apply above config

## Expected Result

It should be configured to use the expected region

## Actual Result

It will use the default region or region that is found within specified AWS config paths.

### Collector version

latest

## Environment
N/A

### OpenTelemetry Collector configuration

```yaml
exporters:
   awskinesis/cross-region:
     aws:
       region: us-west-1
# etc ...
```
