### ISSUE TITLE
[processor/metricstransform] Include Splitby operation

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#16276]
### Component(s)

processor/metricstransform

### Is your feature request related to a problem? Please describe.

In the components current form, it is not possible without some complicated aggregation logic to convert an attribute to a new metric.

### Describe the solution you'd like

What I'd like to do is the following:

```yaml
processors:
   metricstransform:
      transform:
      - include: system.cpu.utilization
        action: update
        operations:
        - action: split_metric
          new_name: cpu.idle # potential worth reusing `new_value`
          label: state
          label_value: idle
```

### Describe alternatives you've considered

At this point in time, to make `split_metric` logic work, I have either done some combination of label aggregation or using the `signalfx exporter` to perform this operation. 

### Additional context

While A solution exists and works, it is split across two components so keeping metric names consistent across different systems isn't possible.
