### ISSUE TITLE
[receiver/mongodbatlas] Polling alerts sometimes does not have hostname field

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#16284]
### Component(s)

receiver/mongodbatlas

## Description

The receiver in poll mode runs into issues for some alerts.

## Steps to Reproduce

Run polls against active alerts that do not fall into `HOST, HOST_METRIC, and REPLICA_SET` 

## Expected Result

No error

## Actual Result

```json 
{"error":"failed to split host:port : missing port in address"}
```

### Collector version

v0.64.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  mongodbatlas:
    public_key: redacted
    private_key: redacted
    alerts:
      enabled: true
      mode: poll
      projects:
      - name: Project 1
        include_clusters: [Cluster0, Cluster1]
      poll_interval: 1m
```

### Log output

```shell
{"error":"failed to split host:port : missing port in address"}
```

### Additional context

I will be working on creating a PR for this shortly
