### ISSUE TITLE
XRay exporter throwing errors on Name 

### ISSUE THREAD

**Issue by Bigguy34** [open-telemetry/opentelemetry-collector-contrib#16327]
### Component(s)

exporter/awsxray

## Description
The [SqlClientInstrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.SqlClient) will send the [database name with the port](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=dotnet-plat-ext-7.0) as the activity display name. As an example my.database.com,1234. This display name is used as the name in the xray exportor which throws an error, because comma's are not allowed in the name.
## Steps to Reproduce
Include a comma in the display name of any activity.
## Expected Result
comma's would be allowed, or transformed 
## Actual Result
Xray exporter throws an error and traces are never sent to amazon

### Collector version

0-62-1:1 of the aws lambda otel collector layer

## Environment
public.ecr.aws/lambda/dotnet:6.0.301-focal container

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  awsxray:

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
```

### Log output

```shell
{
ErrorCode: "InvalidName"
Message: "Invalid segment. ErrorCode: InvalidName"
}
```
