### ISSUE TITLE
[pkg/stanza] Severity Parser `isRange` decode is expecting wrong type

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#16336]
### Component(s)

pkg/stanza

## Description

I believe this is a regression due to #14553 because now it appears that the keys of a severity mapping is now decoding to `map[string]interface{}` but the code is expecting a decoded `map[interface{}]interface{}` 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/52edaea6d00df10fead2ca2651c51cb3b6af7831/pkg/stanza/operator/helper/severity_builder.go#LL203C22-L203C22

It would be good to load such a config in a test case.

## Steps to Reproduce

Construct a `severity_parser` with `max` and `min` set. Even the one documented here appears to be problematic: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/types/severity.md

```yaml
- id: my_severity_parser
  type: severity_parser
  parse_from: body.severity_field
  mapping:
    warn:
      - min: 500
        max: 599
    error:
      - min: 400
        max: 499
    info:
      - min: 300
        max: 399
    debug:
      - min: 200
        max: 299
```

## Expected Result
Running with config  (templated but principle is the same) should not fail to marshal.

## Actual Result

```
{ error: cannot build pipelines: failed to create \"filelog\" receiver, in pipeline \"logs\": type map[string]interface {} cannot be parsed as a severity }
```

### Collector version

v0.64.0

## Environment
OS: Darwin 
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
    filelog:
      include:
        {{ range $fp := .file_log_path }}
        - '{{ $fp }}'
        {{ end }}
      exclude:
        {{ range $fp := .exclude_file_log_path }}
        - '{{ $fp }}'
        {{end}}
      start_at: {{ .start_at }}
      operators:             
        - type: regex_parser
          regex: '^(?P<timestamp>\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2})\s+((?P<hostname>[^\s]+)\s+)?(?P<cef_headers>[\d\D]+)'
          timestamp:
            parse_from: attributes.timestamp
            layout_type: gotime
            layout: 'Jan 02 15:04:05'
            location: {{ .timezone }}

        - type: csv_parser
          parse_from: attributes.cef_headers
          header: 'version|device_vendor|device_product|device_version|signature_id|name|severity|extensions'
          delimiter: "|"

        - type: regex_parser
          if: 'attributes.version != nil and attributes.version matches "CEF:[^\\|]*"'
          regex: 'CEF:(?P<version>[^\|]*)'
          parse_from: attributes.version

        - type: severity_parser
          if: 'attributes.severity != nil'
          parse_from: attributes.severity
          preset: none
          mapping:
            info:
              - min: 0
                max: 3
            # warn:
            #   - min: 4
            #     max: 6
            # error:
            #   - min: 7
            #     max: 8
            # fatal:
            #   - min: 9
            #     max: 10

        - id: add_log_type
          type: add
          field: attributes.log_type
          value: {{ .log_type }}

  service:
    pipelines:
      logs:
        receivers: [filelog]
```

### Log output

```shell
cannot build pipelines: failed to create \"filelog\" receiver, in pipeline \"logs\": type map[string]interface {} cannot be parsed as a severity"
```
