### ISSUE TITLE
Transform metric_statements fails with "invalid keys"

### ISSUE THREAD

**Issue by rinormaloku** [open-telemetry/opentelemetry-collector-contrib#16366]
## Description

Using the transformation as documented:
```
    transform:
      metric_statements:
      - context: metric
        statements:
          - set(description, "Sum") where app == "frontend"
```

Fails with the following error:

```
* error decoding 'processors': error reading processors configuration for "transform": 1 error(s) decoding:

* '' has invalid keys: metric_statements
```

Using the latest image: `otel/opentelemetry-collector-contrib:0.64.1`

### Collector version

image: otel/opentelemetry-collector-contrib:0.64.1

### OpenTelemetry Collector configuration

```yaml
processors:
  transform:
    metric_statements:
    - context: metric
      statements:
        - set(description, "Sum") where app == "frontend"
```

**Comment by TylerHelmuth** [comment]
@rinormaloku that syntax will be correct starting with 0.65.0 that will be released early next week. 

In the meantime you can use the old syntax:

```yaml

transform:
   <traces|metrics|logs>:
     statements:
       - string
       - string
       - string
```
