### ISSUE TITLE
Combine multiple labels of a metric into a single label

### ISSUE THREAD

**Issue by rinormaloku** [open-telemetry/opentelemetry-collector-contrib#16365]
### Component(s)

 metricstransform

### Is your feature request related to a problem? Please describe.

Frequently, we have a set of labels that we want to combine. For example, pick the `deploy` and `namespace` and combine those into `<deploy>.<namespace>`

So we would go from this metric:
```
"metric": {	
   "__name__": "workload_requests",	
  "deploy": "echo",
  "namespace": "default",
}
```

To:
```
"metric": {	
   "__name__": "workload_requests",	
   "deploy_id": "echo.default"
}
```

### Describe the solution you'd like

I think this would be possible if we could refer to already existing metrics such as:
```
  processors:
    metricstransform:
      transforms:
        - include: workload_requests
          action: update
          operations: 
          - action: add_label
            new_label: workload_id
            new_value: $${deploy}.$${namespace}
```

Or some other variant on how we refer to already existing workloads.
