### ISSUE TITLE
[exporter/loki] Promote nested attribute to label

### ISSUE THREAD

**Issue by nlamirault** [open-telemetry/opentelemetry-collector-contrib#16475]
### Component(s)

exporter/loki, receiver/fluentforward

## Description

I would like to have some labels into Grafana/Loki UI.
But i've got only `exporter` label and `OPTLP` value

### Collector version

v0.64.0

## Environment
OS: (e.g., "Ubuntu 20.04") : K3S
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
      logging:
        verbosity: normal
      loki:
        endpoint: http://loki-gateway.logging.svc.cluster.local:80/loki/api/v1/push
        headers:
          X-Scope-OrgID: homelab
        tls:
          insecure: true
    extensions:
      health_check: null
      memory_ballast:
        size_in_percentage: 20
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
    processors:
      attributes:
        actions:
        - action: insert
          key: loki.attribute.labels
          value: kubernetes.namespace_name
        - action: insert
          key: loki.attribute.labels
          value: kubernetes.pod_name
        - action: insert
          key: loki.attribute.labels
          value: kubernetes.pod_id
        - action: insert
          key: loki.attribute.labels
          value: kubernetes.container_name
        - action: insert
          key: loki.attribute.labels
          value: kubernetes.container_id
        - action: insert
          key: loki.attribute.labels
          value: kubernetes.host
      batch:
        send_batch_max_size: 1000
        send_batch_size: 800
        timeout: 15s
      memory_limiter:
        check_interval: 5s
        limit_percentage: 90
        spike_limit_percentage: 30
      resource:
        attributes:
        - action: insert
          key: collector.name
          value: ${KUBE_POD_NAME}
    receivers:
      fluentforward:
        endpoint: 0.0.0.0:24224
      otlp:
        protocols:
          grpc: null
          http: null
    service:
      extensions:
      - health_check
      - memory_ballast
      - pprof
      - zpages
      pipelines:
        logs:
          exporters:
          - logging
          - loki
          processors:
          - batch
          - memory_limiter
          - resource
          - attributes
          receivers:
          - fluentforward
      telemetry:
        logs:
          encoding: json
          level: info
        metrics:
          address: 0.0.0.0:8888
          level: detailed
```

### Additional context

![2022-11-24_17-06](https://user-images.githubusercontent.com/29233/203845307-82854526-5401-46ed-b616-4e9d9d740de3.png)
![2022-11-24_17-05](https://user-images.githubusercontent.com/29233/203845309-a6800b76-09b0-45ea-8e4c-caf8c3b5e535.png)
