### ISSUE TITLE
contrib image is missing k8sobjects receiver

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#16489]
### Component(s)

receiver/k8sobjects

## Description

When trying to configure k8sobjectsreceiver I get:
```

* error decoding 'receivers': unknown receivers type: "k8sobjects" for id: "k8sobjects" (valid values: [nginx skywalking splunk_hec udplog zipkin aerospike dotnet_diagnostics solace zookeeper influxdb rabbitmq bigip mongodb redis snmp awsfirehose kubeletstats expvar filelog googlecloudpubsub k8s_events signalfx awsxray cloudfoundry elasticsearch googlecloudspanner iis memcached mysql statsd awsecscontainermetrics docker_stats windowsperfcounters riak awscloudwatch awscontainerinsightreceiver fluentforward jmx mongodbatlas apache collectd sqlserver couchdb hostmetrics podman_stats httpcheck journald tcplog wavefront carbon k8s_cluster kafka vcenter flinkmetrics kafkametrics sapm syslog postgresql prometheus receiver_creator jaeger nsxt opencensus prometheus_simple sqlquery otlp active_directory_ds])
``` 

### Collector version

v0.66.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

Kubernetes

### OpenTelemetry Collector configuration

```yaml
exporters:
  logging: {}
extensions:
  health_check: {}
  memory_ballast:
    size_in_percentage: 40
  zpages:
    endpoint: localhost:55679
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  k8s_cluster:
    collection_interval: 10s
  k8sobjects:
    auth_type: serviceAccount
    objects:
    - group: events.k8s.io
      mode: watch
      name: events
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 30s
        static_configs:
        - targets:
          - ${MY_POD_IP}:8888
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
  - zpages
  - health_check
  - memory_ballast
  pipelines:
    logs:
      exporters:
      - coralogix
      processors:
      - memory_limiter
      - batch
      receivers:
      - k8sobjects
    metrics:
      exporters:
      - coralogix
      processors:
      - memory_limiter
      - batch
      receivers:
      - prometheus
      - otlp
      - k8s_cluster
    traces:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
      - jaeger
      - zipkin
  telemetry:
    metrics:
      address: 0.0.0.0:8888
```

### Log output

```shell
* error decoding 'receivers': unknown receivers type: "k8sobjects" for id: "k8sobjects" (valid values: [nginx skywalking splunk_hec udplog zipkin aerospike dotnet_diagnostics solace zookeeper influxdb rabbitmq bigip mongodb redis snmp awsfirehose kubeletstats expvar filelog googlecloudpubsub k8s_events signalfx awsxray cloudfoundry elasticsearch googlecloudspanner iis memcached mysql statsd awsecscontainermetrics docker_stats windowsperfcounters riak awscloudwatch awscontainerinsightreceiver fluentforward jmx mongodbatlas apache collectd sqlserver couchdb hostmetrics podman_stats httpcheck journald tcplog wavefront carbon k8s_cluster kafka vcenter flinkmetrics kafkametrics sapm syslog postgresql prometheus receiver_creator jaeger nsxt opencensus prometheus_simple sqlquery otlp active_directory_ds])

```
```


### Additional context

_No response_
