### ISSUE TITLE
prometheus receiver issue

### ISSUE THREAD

**Issue by praveenchoudhari007** [open-telemetry/opentelemetry-collector-contrib#16484]
**Describe the bug**
I tried to use prometheus receiver and was using kubernetes_sd_config to scrape host metrics. Below is the receiver config on openTelemetry 

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
```

I have created necessary clusterRole and clusterRolebinding on default service account of open telemetry agent. 
I get below error on Open telemetry 

2022-11-25T10:18:36.553Z	debug	scrape/scrape.go:1320	Scrape failed	{"kind": "receiver", "name": "prometheus", "pipeline": "metrics", "scrape_pool": "kubernetes-nodes", "target": "http://host-ip:10250/metrics", "error": "server returned HTTP status 400 Bad Request", "errorVerbose": "server returned HTTP status 400 Bad Request\ngithub.com/prometheus/prometheus/scrape.(*targetScraper).scrape\n\tgithub.com/prometheus/prometheus@v1.8.2-0.20220303173753-edfe657b5405/scrape/scrape.go:790\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport\n\tgithub.com/prometheus/prometheus@v1.8.2-0.20220303173753-edfe657b5405/scrape/scrape.go:1307\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).run\n\tgithub.com/prometheus/prometheus@v1.8.2-0.20220303173753-edfe657b5405/scrape/scrape.go:1231\nruntime.goexit\n\truntime/asm_amd64.s:1594"}

**Steps to reproduce**
Create prometheus receiver with kubernetes_sd_config with host role. Open telemetry is not able to scrape host metrics and throws http 400 error. 

**What did you expect to see?**
kubernetes_sd_config with host role should be able to scrape host metrics on Open telemetry

**What did you see instead?**
Http 400 error 

**What version did you use?**
opentelemetry-collector-contrib:0.64.1

**What config did you use?**
```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
```
