### ISSUE TITLE
loadbalancing exporter: Allow specifying port when using DNS resolver

### ISSUE THREAD

**Issue by vangarp** [open-telemetry/opentelemetry-collector-contrib#1648]
**Problem**
Currently when DNS resolver is used with loadbalancing exporter, there is no option to specify a port and we always assume OTLP receiver port as 55680. On the other hand when using static resolver, we can specify arbitrary ports.

**Proposal**
I propose adding another field to the dns resolver config to allow specifying a port. Something like

```
loadbalancing:
  protocol:
    otlp:
      timeout: 1s
  resolver:
    dns:
      hostname: hostname
      port: 55690
```
