### ISSUE TITLE
Prometheus receiver panics if no configuration is given

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#16538]
### Component(s)

receiver/prometheus

## Description
Run the OpenTelemetry Collector with a prometheus receiver with no configuration settings. The collector panics.

## Expected Result
No panic - an error with a meaningful message and a exit code 1.

## Actual Result
Panics, see output

### Collector version

0.66.0

## Environment
OS: Mac OS X

### OpenTelemetry Collector configuration

```yaml
receivers:
    prometheus:
    otlp:
        protocols:
            grpc:
              endpoint: 0.0.0.0:4317

exporters:
    logging:

processors:
    batch:

extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679

service:
    extensions: [pprof, zpages, health_check]
    pipelines:
      metrics:
        receivers: [prometheus]
        processors: [batch]
        exporters: [logging]
```

### Log output

```shell
2022-11-30T02:35:13.837Z        info    prometheusreceiver@v0.66.0/metrics_receiver.go:254      Starting discovery manager      {"kind": "receiver", "name": "prometheus", "pipeline": "metrics"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2dfe84d]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.gcInterval(...)
        /builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.66.0/metrics_receiver.go:302
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.(*pReceiver).initPrometheusComponents(0xc0010078c0, {0x590d698?, 0xc001372300?}, {0x59111e0?, 0xc000fa26a8}, {0x58cd140, 0xc0007331c0?})
        /builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.66.0/metrics_receiver.go:273 +0x16d
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver.(*pReceiver).Start(0xc0010078c0, {0x4f1c2f0?, 0xc000134000?}, {0x59111e0, 0xc000fa26a8})
        /builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver@v0.66.0/metrics_receiver.go:89 +0xce
go.opentelemetry.io/collector/service/internal/pipelines.(*Pipelines).StartAll(0xc000f55630, {0x590d6d0, 0xc000134000}, {0x59111a8?, 0xc000fdb7a0})
        /builds/o11y-gdi/splunk-otel-collector-releaser/.go/pkg/mod/go.opentelemetry.io/collector@v0.66.0/service/internal/pipelines/pipelines.go:103 +0x452
go.opentelemetry.io/collector/service.(*service).Start(0xc0000d1680, {0x590d6d0, 0xc000134000})
```
