### ISSUE TITLE
`event.name` attribute is empty when using watch mode

### ISSUE THREAD

**Issue by harshit-splunk** [open-telemetry/opentelemetry-collector-contrib#16542]
### Component(s)

receiver/k8sobjects

## Description
`event.name` attribute is empty when collecting any resource using watch mode. 

## Steps to Reproduce

Setup otel agent with following config
```yaml
  k8sobjects:
    auth_type: serviceAccount
    objects:
      - name: pods
        mode: pull
        interval: 15m
      - name: events
        mode: watch
```

## Expected Result

`event.name` attribute should have a non-empty value for all the logs

## Actual Result

`event.name` attribute is empty when using watch mode

### Collector version

0.66.0

## Environment
OS: ("Ubuntu 20.04")
