### ISSUE TITLE
"File Storage" extension online compaction doesn't work with default values

### ISSUE THREAD

**Issue by assafaa** [open-telemetry/opentelemetry-collector-contrib#16541]
### Component(s)

"File Storage" extension

## Description

We have started to use a persistent queue in our OTEL exporter.
The used database 'Bolt' is allocating space and doesn't reclaim it, which is by design.
According to the 'Readme' file, an online (i.e., on_rebound) compaction mechanism for Bolt is supported.
We followed the documentation guidelines and kept the default values to make usability tests.
For some reason, the compaction didn't start, and we had to do some code digging and discovered a few failures.

Firstly, according to the documentation, the following are the defaults:
compaction.rebound_needed_threshold_mib (default: 100)
compaction.rebound_trigger_threshold_mib (default: 10) 

Once attached a debugger, we see the opposite:
compaction.rebound_needed_threshold_mib **(default: 10)**
compaction.rebound_trigger_threshold_mib **(default: 100)** 
 
Once we did a little digging, we found out in the file "factory.go" line 56, function "createDefaultConfig" the following:

	return &Config{
		ExtensionSettings: config.NewExtensionSettings(component.NewID(typeStr)),
		Directory:         getDefaultDirectory(),
		Compaction: &CompactionConfig{
			Directory:                  getDefaultDirectory(),
			OnStart:                    false,
			OnRebound:                  false,
			MaxTransactionSize:         defaultMaxTransactionSize,
			ReboundNeededThresholdMiB:  defaultReboundTriggerThresholdMib,
			ReboundTriggerThresholdMiB: defaultReboundNeededThresholdMib,
			CheckInterval:              defaultCompactionInterval,
		},
		Timeout: time.Second,
	}

I imagine they accidentally assign the wrong values to each.
Fortunately, we could set the values explicitly in OTC config file and pass that.
But, we encountered another issue once we expected to make online compaction.

In file: "client.go" line 297, function "shouldCompact":
There's a super confusing condition, and we're not sure it's even correct.
 
	if dataSizeBytes > c.compactionCfg.ReboundNeededThresholdMiB*oneMiB ||
		totalSizeBytes < c.compactionCfg.ReboundTriggerThresholdMiB*oneMiB {
		return false
	}

The first condition says:
If the "data portion" of the DB is bigger than 100MiB, do not compact.
So basically, once you are over 100MiB (i.e., network failure; retry queue is fully loaded), no compaction will be made.
The documentation says:  "compaction.rebound_needed_threshold_mib (default: 100) - when allocated data exceeds this amount, the "compaction needed" flag will be enabled"

Let's assume for a sec that this is a mistake, and we change the condition to something like:
	if dataSizeBytes < c.compactionCfg.ReboundNeededThresholdMiB*oneMiB ||
		totalSizeBytes < c.compactionCfg.ReboundTriggerThresholdMiB*oneMiB {
		return false
	}

(i.e., smaller than).
The documentation says: "compaction.rebound_trigger_threshold_mib (default: 10) - if the "compaction needed" flag is set, and allocated data drops below this amount, compaction will begin and the "compaction needed" flag will be cleared"

So I imagine we pass the first condition, so the "compaction needed" flag is on.
"The allocated data" is a bit confusing since, in the second condition, we use the total size of the DB (free + allocated).
So the "allocated data" from the documentation is not possible since there will be two "identical" conditions with different values (the second is smaller).

If we ignore the documentation and keep totalSizeBytes (i.e., code), the following happens:
if the data portion of the DB is less than 100MiB OR the total size of the DB is less than 10, don't compact.
But, if the data portion is bigger than 100MiB, the total DB size is bigger than 100MiB.

We can't find any explanation, and if this condition is correct, we would love to get some guidelines.

## Steps to Reproduce

Use the default values of the File Storage extension with online compaction.
We use a persistent queue, which uses this extension to test it.

    extensions:
      file_storage/otc:
        directory: /var/lib/storage/otc
        timeout: 10s
        compaction:
          on_rebound: true

    exporters:
      otlphttp:
        endpoint: https://otel.management.control.euw3.ecp-rnd.cqloud.com:55690
        sending_queue:
          storage: file_storage/otc

## Expected Result

DB compaction is working as expected.

## Actual Result

DB online compaction is not working.

### Collector version

Latest clone

## Environment
OS: Ubuntu 20.04
Compiler(if manually compiled): go1.18

### OpenTelemetry Collector configuration

```yaml
extensions:
      file_storage/otc:
        directory: /var/lib/storage/otc
        timeout: 10s
        compaction:
          on_rebound: true

    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: '****'
            scheme: 'http'
            scrape_interval: 30s
            scrape_timeout: 10s
            metrics_path: '****'
            follow_redirects: true
            static_configs:
            - targets: ['****']

    exporters:
      otlphttp:
        endpoint: https://otel.********
        sending_queue:
          storage: file_storage/otc
        tls:
          insecure: false
          ca_file: ********
          cert_file: ********
          key_file: ********

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [otlphttp]

      extensions: [file_storage/otc]
```
