### ISSUE TITLE
azuremonitorexporter Logs missing CustomDementions

### ISSUE THREAD

**Issue by theEyeD** [open-telemetry/opentelemetry-collector-contrib#16557]
### Component(s)

exporter/azuremonitor

## Description
When mapping Logs to App Insights traces, it is not mapping Attributes to CustomDementions like it does for spans. This loses data when using formatted logging.

## Steps to Reproduce
Log data using formatted logs.
```csharp
logger.LogInformation("Info {data}", 123);
```

## Expected Result
Attributes (log args) display as CustomDimensions.

## Actual Result
CustomDimensions is empty.
![image](https://user-images.githubusercontent.com/4244606/204915167-d05a2217-2b55-4109-a849-a50c61089b98.png)

### Collector version

0.66.0

## Environment
OS: Windows 10

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  # batch:

exporters:
  logging:
    verbosity: detailed
  azuremonitor:
    instrumentation_key: 00000000-0000-0000-0000-000000000000
    spaneventsenabled: true

extensions:
  health_check:
  pprof:
  zpages:


service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, azuremonitor]
    logs:
      receivers: [otlp]
      exporters: [logging, azuremonitor]
```

### Log output

```shell
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-11-30 21:44:38.6123544 +0000 UTC
SeverityText: Information
SeverityNumber: Info(9)
Body: Str(Info {data})
Attributes:
     -> dotnet.ilogger.category: Str(getting_started.Worker)
     -> data: Int(123)
```
