### ISSUE TITLE
[processor/routing]  OTTL statements doesn't work without `from_attribute`

### ISSUE THREAD

**Issue by vchirikov** [open-telemetry/opentelemetry-collector-contrib#16555]
### Component(s)

processor/routing

## Description

According to the docs 
We should be able to use OTTL statements without `from_attribute` and other "conventional routing items"

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fa262b405e5e10ed398379db680e58438e6778f9/processor/routingprocessor/README.md?plain=1#L66-L85

But if I try to use it without `from_attribute` the collector won't start.

p.s. and it will be useful to add an example of filtering k8s logs for example into 2 elasticsearchexporters based on OTTL, because it's unclear how to not route to all exporters in case of similar attributes (for example how to route only one container from the pod into exporter)

### Collector version

0.66.0

## Environment
Docker image otel/opentelemetry-collector-contrib:0.66.0

### OpenTelemetry Collector configuration

```yaml
processors:
  routing:
    default_exporters: [elasticsearch/default]
    table:
      - statement: route() where (resource.attributes["k8s.namespace.name"] == "infra" and resource.attributes["k8s.container.name"] != "access-logs") or resource.attributes["k8s.namespace.name"] == "flux-system"
        exporters: [elasticsearch/infra]
      - statement: route() where resource.attributes["k8s.namespace.name"] == "infra" and resource.attributes["k8s.container.name"] == "access-logs"
        exporters: [elasticsearch/ingress]
      - statement: route() where resource.attributes["k8s.namespace.name"] == "staging" and resource.attributes["k8s.container.name"] == "app"
        exporters: [elasticsearch/apps]
```

### Log output

```shell
Error: invalid configuration: processor "routing" has invalid configuration: invalid attribute to read the route's value from: the FromAttribute property is empty
2022-11-30 13:55:57.699034 I | collector server run finished with error: invalid configuration: processor "routing" has invalid configuration: invalid attribute to read the route's value from: the FromAttribute property is empty
```

### Additional context

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3746 looks like similar
