### ISSUE TITLE
New component: timestamp processor

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#16562]
### The purpose and use-cases of the new component

The purpose of this processor is to change the timestamp of all data that it processes (logs, traces, metrics) by adding or removing a static time duration.

### Example configuration for the component

```
processors:
  timestamp:
    offset: "0h"

  timestamp/add2h:
    offset: "2h"

  timestamp/remove3h:
    offset: "-3h"

receivers:
  nop:

exporters:
  nop:

service:
  pipelines:
    metrics:
      receivers: [nop]
      processors: [timestamp, timestamp/add2h, timestamp/remove3h]
      exporters: [nop]
```

### Telemetry data types supported

all

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

This was needed at one point as a stop gap solution for one of our PoCs and it's possible the transformprocessor and ottl is a better solution long term. See original discussion https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14142

If others find this processor has merit, I can help contribute it to contrib and help maintain it.

The name of the processor might be instead better named "clockskew" - please suggest.
