### ISSUE TITLE
[extension/headerssetter] Extend the headers setter extension with header modification actions.

### ISSUE THREAD

**Issue by kovrus** [open-telemetry/opentelemetry-collector-contrib#16581]
### Component(s)

extension/headerssetter

### Is your feature request related to a problem? Please describe.

There will be cases when users would have to insert, update or drop certain headers, see the scenario
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7596#issuecomment-1326484215 where users have to drop a specific header. The headers setter extension could be a good place where this functionality can be implemented.

### Describe the solution you'd like

Introduce the following header actions in the header setter extension: 
- `insert`: Inserts the new header if it does not exist.
- `update`: Updates the header value if it exists.
- `upsert`: Inserts a header if it does not exist and updates the header if it exists.
- `delete`: Deletes the header.

Configuration example:

```
extensions:
  headers_setter:
    headers:
      - key: <header>
        action: insert
        from_context: <value from context>
      - key: <header>
        action: upsert
        value: <static value>
      - key: <header>
        action: update
        from_context: <value from context>
      - key: <header>
        action: delete    
```

### Additional context

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7596
