### ISSUE TITLE
awsfirehosereceiver fails with  "Invalid Firehose request"

### ISSUE THREAD

**Issue by vasiliy-grinko** [open-telemetry/opentelemetry-collector-contrib#16583]
### Component(s)

receiver/awsfirehose

## Description
I'm sending metrics from CloudWatch metric stream (json format) to Kenesis Firehose delivery stream and in it I specify http endpoint of otel-collector. In logs of otel-collector I see:
```
2022-12-02T15:25:51.453Z    error    awsfirehosereceiver@v0.66.0/receiver.go:164    Invalid Firehose request    {"kind": "receiver", "name": "awsfirehose", "pipeline": "metrics", "error": "missing request id in header"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver.(*firehoseReceiver).ServeHTTP
    github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver@v0.66.0/receiver.go:164
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
    go.opentelemetry.io/collector@v0.66.0/config/confighttp/compression.go:162
net/http.HandlerFunc.ServeHTTP
    net/http/server.go:2109
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
    go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.36.4/handler.go:204
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
    go.opentelemetry.io/collector@v0.66.0/config/confighttp/clientinfohandler.go:39
net/http.serverHandler.ServeHTTP
    net/http/server.go:2947
net/http.(*conn).serve
    net/http/server.go:1991
```
## Steps to Reproduce
otelcol conf:
```
...
awsfirehose:
    endpoint: 0.0.0.0:4433
    record_type: cwmetrics
...
```

Firehose manifest:
```
apiVersion: kinesis.aws.jet.crossplane.io/v1alpha1
kind: FirehoseDeliveryStream
metadata:
  name: shops-cw-metrics-to-amp
spec:
  forProvider:
    name: cw-metrics-to-amp
    destination: http_endpoint
    serverSideEncryption: 
    - enabled: false
    httpEndpointConfiguration:
    - url: "https://otel-collector.***.net"
      name: otel-collector
      roleArn: arn:aws:iam::*:role/otel-collector
      requestConfiguration:
      - contentEncoding: NONE
      s3BackupMode: FailedDataOnly
    s3Configuration:
      - bucketArn: arn:aws:s3:::cw-metrics-backup-for-kenesis
        roleArn: arn:aws:iam::*:role/otel-collector
        compressionFormat: "GZIP"
    region: eu-central-1
  providerConfigRef:
    name: providerconfig-jet-awssc
```

CW stream manifest:
```
apiVersion: cloudwatch.aws.jet.crossplane.io/v1alpha1
kind: MetricStream
metadata:
  name: shops-cw-metrics-to-amp
spec:
  forProvider:
    name: cw-metric-stream-to-amp
    roleArn: arn:aws:iam::*:role/otel-collector
    firehoseArn: arn:aws:firehose:eu-central-1:*:deliverystream/cw-metrics-to-amp
    includeFilter:
    - namespace: "AWS/ApplicationELB"
    - namespace: "AWS/DocDB"
    - namespace: "AWS/EC2"
    - namespace: "AWS/EBS"
    - namespace: "AWS/Lambda"  
    - namespace: "ContainerInsights" 
    outputFormat: json
    region: eu-central-1
  providerConfigRef:
    name: providerconfig-jet-awssc
```
I tried to send json with additional headers manually but it led to: 
```
2022-12-02T15:32:37.107Z    debug    awsfirehosereceiver@v0.66.0/receiver.go:171    Processing Firehose request    {"kind": "receiver", "name": "awsfirehose", "pipeline": "metrics", "RequestID": "1234asdfgasfdasdgf"}
2022-12-02T15:32:37.107Z    error    awsfirehosereceiver@v0.66.0/receiver.go:230    Unable to consume records    {"kind": "receiver", "name": "awsfirehose", "pipeline": "metrics", "error": "record format invalid"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver.(*firehoseReceiver).ServeHTTP
    github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver@v0.66.0/receiver.go:230
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
    go.opentelemetry.io/collector@v0.66.0/config/confighttp/compression.go:162
net/http.HandlerFunc.ServeHTTP
    net/http/server.go:2109
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
    go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.36.4/handler.go:204
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
    go.opentelemetry.io/collector@v0.66.0/config/confighttp/clientinfohandler.go:39
net/http.serverHandler.ServeHTTP
    net/http/server.go:2947
net/http.(*conn).serve
    net/http/server.go:1991
```
## Expected Result
metrics are received and transferred to exporter in otel-collector
## Actual Result
receiving fails with the error above

### Collector version

v0.66.0

## Environment
Kubernetes v1.23.13-eks-fb459a0

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
            grpc:
      awsfirehose:
        endpoint: 0.0.0.0:4433
        record_type: cwmetrics

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      prometheusremotewrite:
        endpoint: "..."
        tls:
          insecure: true
        auth:
          authenticator: sigv4auth
        resource_to_telemetry_conversion:
          enabled: true
      awsemf:
        region: 'eu-central-1'
        resource_to_telemetry_conversion:
          enabled: true
      awsxray:
        region: 'eu-central-1'

    processors:
      filter/metrics:
      batch:
      spanmetrics:
        metrics_exporter: prometheus
        latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
        dimensions:
          - name: http.method
            default: GET
          - name: http.status_code
        dimensions_cache_size: 1000

    extensions:
      health_check:
      pprof:
      zpages:
      sigv4auth:
        service: 'aps'
        region:  'eu-central-1' 
    
    service:
      telemetry:
        logs:
          level: "debug"
      extensions: [sigv4auth]
      pipelines:
        metrics:
          receivers: [otlp,awsfirehose]
          processors: []
          exporters: [prometheusremotewrite]
```

### Log output

```shell
2022-12-02T15:25:51.453Z    error    awsfirehosereceiver@v0.66.0/receiver.go:164    Invalid Firehose request    {"kind": "receiver", "name": "awsfirehose", "pipeline": "metrics", "error": "missing request id in header"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver.(*firehoseReceiver).ServeHTTP
    github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver@v0.66.0/receiver.go:164
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
    go.opentelemetry.io/collector@v0.66.0/config/confighttp/compression.go:162
net/http.HandlerFunc.ServeHTTP
    net/http/server.go:2109
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
    go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.36.4/handler.go:204
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
    go.opentelemetry.io/collector@v0.66.0/config/confighttp/clientinfohandler.go:39
net/http.serverHandler.ServeHTTP
    net/http/server.go:2947
net/http.(*conn).serve
    net/http/server.go:1991
```
