### ISSUE TITLE
winperfcounters receiver reports no metrics if any scraper fails

### ISSUE THREAD

**Issue by chrislbs** [open-telemetry/opentelemetry-collector-contrib#16712]
### Component(s)

receiver/windowsperfcounters

## Description

In the windows perf counter receiver, if any instance or object fails to receive, all metrics are thrown away rather than just the scrapers that failed to successfully read.

## Steps to Reproduce

Create a windowsperfcounter receiver for an instance that exists, and another that doesn't.

## Expected Result

Metrics will be received and exported for the perf counter instance that exists.

## Actual Result

Metrics are not received or exported for the perf counter instance that exists.

### Collector version

v0.66.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  windowsperfcounters:
    metrics:
      dotnet.gen0.heap.size:
        description: dotnet gen 0 heap size
        unit: By
        gauge:
    collection_interval: 30s
    perfcounters:
    - object: .NET CLR Memory
      instance:
      - "notexist.exe"
      - "exists.exe"
      counters:
        - name: "Gen 0 heap size"
          metric: dotnet.gen0.heap.size

service:
  pipelines:
    metrics:
      receivers: [windowsperfcounters]
```
