### ISSUE TITLE
Remove custom standard libraries dependencies from the contrib main build

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector-contrib#16722]
### Component(s)

exporter/loki

### Is your feature request related to a problem? Please describe.

Loki exporter brings custom alternatives of standard libraries like go-kit as requirement in the collector build, see:

```golang
// loki needs grafana fork to be used
replace github.com/hpcloud/tail => github.com/grafana/tail v0.0.0-20220426200921-98e8eb28ea4c

// using fork for support LogpullReceived and LogpullFields for loki - see https://github.com/cloudflare/cloudflare-go/pull/743
replace github.com/cloudflare/cloudflare-go => github.com/cyriltovena/cloudflare-go v0.27.1-0.20211118103540-ff77400bcb93

// using fork for custom dialer support for loki - see https://github.com/bradfitz/gomemcache/pull/86
replace github.com/bradfitz/gomemcache => github.com/grafana/gomemcache v0.0.0-20220812141859-1e3ae89e91a7

// fork containing a line-buffered logger which should improve logging performance for loki
replace github.com/go-kit/log => github.com/dannykopping/go-kit-log v0.2.2-0.20221002180827-5591c1641b6b
```

### Describe the solution you'd like

Remove dependency on non standard libraries (e.g. replacement of go-kit with a custom library).

### Additional context

If nothing happens in the next few weeks we should remove the loki exporter, since using custom builds of libraries is consider a security threat and should be discouraged.

**Comment by jpkrohling** [comment]
Are those dependencies ending up on the binary? I understand we depend only on the proto files, none of those other dependencies are in the binary.

**Comment by bogdandrutu** [comment]
>Are those dependencies ending up on the binary? 

I believe so since I have to add the replace statements on these libraries, I do expect golang compiler/linker to be smart enough to ignore the code that we don't need in the final binary (at least I know that is true in other languages).

**Comment by mar4uk** [comment]
These 4 replace directives were introduced in promtailreceiver (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14632)

We agreed with reviewers that we will get rid of these replaces in the future (as soon as possible) and Juraci created an issue [16453](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16453)

To remove these replaces right now I need to remove promtailreceiver. Can we postpone this issue till the end of January? I will try to get rid of the replaces till then.

**Comment by Aneurysm9** [comment]
I recommend that we remove the promtailreceiver until this issue is resolved.  It will still be tagged and made available for users who want to include it in a custom distribution, but it sounds like we're not yet ready to include it.

**Comment by jpkrohling** [comment]
> I believe so since I have to add the replace statements on these libraries, I do expect golang compiler/linker to be smart enough to ignore the code that we don't need in the final binary (at least I know that is true in other languages).

I just checked the resulting binary for an otelcol-contrib and could find traces only of the last dependency:

```
$ strings otelcol-contrib | grep hpcloud/tail
$ strings otelcol-contrib | grep grafana/tail
$ strings otelcol-contrib | grep cloudflare/cloudflare-go
$ strings otelcol-contrib | grep cyriltovena/cloudflare-go
$ strings otelcol-contrib | grep bradfitz/gomemcache
$ strings otelcol-contrib | grep grafana/gomemcache
$ strings otelcol-contrib | grep go-kit/log
github.com/go-kit/log
github.com/go-kit/log/level
dep     github.com/go-kit/log   v0.2.1
github.com/go-kit/log.(*jsonLogger).Log
github.com/go-kit/log.merge
github.com/go-kit/log.safeString
github.com/go-kit/log.safeString.func1
github.com/go-kit/log.safeError
github.com/go-kit/log.safeError.func1
github.com/go-kit/log.With
github.com/go-kit/log.newContext
github.com/go-kit/log.containsValuer
github.com/go-kit/log.WithPrefix
github.com/go-kit/log.(*context).Log
github.com/go-kit/log.(*logfmtEncoder).Reset
github.com/go-kit/log.glob..func1
github.com/go-kit/log.logfmtLogger.Log
github.com/go-kit/log.logfmtLogger.Log.func1
github.com/go-kit/log.nopLogger.Log
github.com/go-kit/log.(*syncWriter).Write
github.com/go-kit/log.(*syncWriter).Write.func1
github.com/go-kit/log.(*fdSyncWriter).Write
github.com/go-kit/log.(*fdSyncWriter).Write.func1
github.com/go-kit/log.bindValues
github.com/go-kit/log.TimestampFormat
github.com/go-kit/log.TimestampFormat.func1
github.com/go-kit/log.timeFormat.String
github.com/go-kit/log.timeFormat.MarshalText
github.com/go-kit/log.Caller
github.com/go-kit/log.Caller.func1
github.com/go-kit/log.glob..func2
github.com/go-kit/log.init
github.com/go-kit/log.(*jsonLogger).Write
github.com/go-kit/log.jsonLogger.Write
github.com/go-kit/log.(*logfmtLogger).Log
github.com/go-kit/log.(*nopLogger).Log
github.com/go-kit/log.(*fdSyncWriter).Fd
github.com/go-kit/log.(*fdSyncWriter).Lock
github.com/go-kit/log.(*fdSyncWriter).TryLock
github.com/go-kit/log.(*fdSyncWriter).Unlock
type..eq.github.com/go-kit/log.fdSyncWriter
github.com/go-kit/log.fdSyncWriter.Fd
github.com/go-kit/log.(*syncWriter).Lock
github.com/go-kit/log.(*syncWriter).TryLock
github.com/go-kit/log.(*syncWriter).Unlock
type..eq.github.com/go-kit/log.syncWriter
github.com/go-kit/log.(*logfmtEncoder).EncodeKeyval
github.com/go-kit/log.(*logfmtEncoder).EncodeKeyvals
github.com/go-kit/log.(*logfmtEncoder).EndRecord
github.com/go-kit/log.logfmtEncoder.EncodeKeyval
github.com/go-kit/log.logfmtEncoder.EncodeKeyvals
github.com/go-kit/log.logfmtEncoder.EndRecord
type..eq.github.com/go-kit/log.timeFormat
github.com/go-kit/log.(*timeFormat).MarshalText
github.com/go-kit/log.(*timeFormat).String
github.com/go-kit/log/level.(*logger).Log
github.com/go-kit/log/level.(*levelValue).String
github.com/go-kit/log/level.init
type..eq.github.com/go-kit/log/level.levelValue
type..eq.github.com/go-kit/log/level.logger
github.com/go-kit/log/level.NewFilter
github.com/go-kit/log/level.Error
github.com/go-kit/log/level.ErrorValue
github.com/go-kit/log/level.Info
github.com/go-kit/log/level.InfoValue
github.com/go-kit/log.NewLogfmtLogger
github.com/go-kit/log.NewJSONLogger
github.com/go-kit/log.NewSyncWriter
github.com/go-kit/log/level.AllowWarn
github.com/go-kit/log/level.allowed
github.com/go-kit/log/level.AllowInfo
github.com/go-kit/log/level.AllowDebug
github.com/go-kit/log/level.AllowError
github.com/go-kit/log/level.Warn
github.com/go-kit/log/level.WarnValue
github.com/go-kit/log/level.Debug
github.com/go-kit/log/level.DebugValue
github.com/go-kit/log@v0.2.1/json_logger.go
github.com/go-kit/log@v0.2.1/log.go
github.com/go-kit/log@v0.2.1/value.go
github.com/go-kit/log@v0.2.1/logfmt_logger.go
github.com/go-kit/log@v0.2.1/nop_logger.go
github.com/go-kit/log@v0.2.1/sync.go
github.com/go-kit/log@v0.2.1/stdlib.go
github.com/go-kit/log@v0.2.1/level/level.go
dep     github.com/go-kit/log   v0.2.1
$ strings otelcol-contrib | grep dannykopping/go-kit-log
=>      github.com/dannykopping/go-kit-log      v0.2.2-0.20221002180827-5591c1641b6b    h1:G8g9mAKEj9O3RsU6Hd/ow6lIcHarlcUl5omV6sFKEOU=
=>      github.com/dannykopping/go-kit-log      v0.2.2-0.20221002180827-5591c1641b6b    h1:G8g9mAKEj9O3RsU6Hd/ow6lIcHarlcUl5omV6sFKEOU=
```

**Comment by mar4uk** [comment]
There are other dependencies that use Go 1.19. I believe that shouldn't be a reason to remove loki. It is probably better to bump up the collector Go version instead of restricting dependencies using Go 1.19

**Comment by mar4uk** [comment]
@bogdandrutu do you think all these 4 replacements are blockers to include promtail receiver to release? Or the go-kit is the most disturbing one?
Only go-kit is used by the collector components besides promtail receiver.
Other dependencies (github.com/hpcloud/tail, github.com/cloudflare/cloudflare-go, github.com/bradfitz/gomemcache) are used only by promtail receiver

Loki team can remove go-kit replacement by using a fork as the main dependency. That will allow removal replacement from the collector contrib right away

**Comment by mar4uk** [comment]
@disfluxly could you please send the config for the builder you use? 
Currently promtail receiver is not included to the release. Working on fixing it, but probably it will be in the release not sooner than mid/end of January

**Comment by disfluxly** [comment]
@mar4uk:

```
dist:
    module: github.com/open-telemetry/opentelemetry-collector # the module name for the new distribution, following Go mod conventions.
receivers:
  - gomod: "go.opentelemetry.io/collector VERSION"
    import: "go.opentelemetry.io/collector/receiver/otlpreceiver"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/influxdbreceiver"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsecscontainermetricsreceiver"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/promtailreceiver"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheus"
exporters:
  - gomod: "go.opentelemetry.io/collector VERSION"
    import: "go.opentelemetry.io/collector/exporter/loggingexporter"
  - gomod: "go.opentelemetry.io/collector VERSION"
    import: "go.opentelemetry.io/collector/exporter/otlpexporter"
  - gomod: "go.opentelemetry.io/collector VERSION"
    import: "go.opentelemetry.io/collector/exporter/otlphttpexporter"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerthrifthttpexporter"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/lokiexporter"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/zipkinexporter"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter"
processors:
  - gomod: "go.opentelemetry.io/collector VERSION"
    import: "go.opentelemetry.io/collector/processor/batchprocessor"
  - gomod: "go.opentelemetry.io/collector VERSION"
    import: "go.opentelemetry.io/collector/processor/memorylimiterprocessor"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor"
extensions:
  - gomod: "go.opentelemetry.io/collector VERSION"
    import: "go.opentelemetry.io/collector/extension/ballastextension"
  - gomod: "go.opentelemetry.io/collector VERSION"
    import: "go.opentelemetry.io/collector/extension/zpagesextension"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/oauth2clientauthextension"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib VERSION"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/oidcauthextension"
```

We've tried multiple `VERSION`, hence why I left it in there. We `sed` replace it in our build pipeline.

With `v0.68.0`, this ends up throwing the error:

```
Error: failed to compile the OpenTelemetry Collector distribution: exit status 2. Output:
# github.com/grafana/loki/pkg/util/log
/Users/Daniel.Schladweiler/go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221214135803-c71620ae9437/pkg/util/log/log.go:24:22: undefined: log.LineBufferedLogger
/Users/Daniel.Schladweiler/go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221214135803-c71620ae9437/pkg/util/log/log.go:97:24: undefined: log.NewLineBufferedLogger
/Users/Daniel.Schladweiler/go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221214135803-c71620ae9437/pkg/util/log/log.go:98:8: undefined: log.WithFlushPeriod
/Users/Daniel.Schladweiler/go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221214135803-c71620ae9437/pkg/util/log/log.go:99:8: undefined: log.WithPrellocatedBuffer
/Users/Daniel.Schladweiler/go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221214135803-c71620ae9437/pkg/util/log/log.go:100:8: undefined: log.WithFlushCallback
note: module requires Go 1.19
```
