### ISSUE TITLE
[exporter/fileexporter] fileexporter nil pointer due to shared component

### ISSUE THREAD

**Issue by blakeroberts-wk** [open-telemetry/opentelemetry-collector-contrib#16733]
### Component(s)

exporter/file

## Description

nil pointer

## Steps to Reproduce

Start the collector with the following config:

```
receivers:
  otlp:
    protocols:
      http:
exporters:
  file:
    path: /dev/stdout
processors:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [file]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [file]
```

Send metrics and traces to the collector, one of the two will cause a panic.

## Expected Result

No panic

## Actual Result

Panic

### Collector version

v0.66.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
exporters:
  file:
    path: /dev/stdout
processors:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [file]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [file]
```

### Log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x51c20a1]

goroutine 783 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter.(*fileExporter).ConsumeTraces(0xc00015c2d0, {0xc00052ef30?, 0x40b86aa?}, {0x5b5cb78?})
	<REDACTED>/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter@v0.66.0/file_exporter.go:69 +0x21
```
