### ISSUE TITLE
[exporter/datadog] does not send metrics units

### ISSUE THREAD

**Issue by omamoo** [open-telemetry/opentelemetry-collector-contrib#16765]
### Component(s)

exporter/datadog

## Description
While creating histogram metric with the unit "millisecond", the metric at datadog configured without any unit, while 
my expectations was that i'll see time unit metric. 

## Steps to Reproduce
1. Create histogram metric with the unit: `millisecond`.
2. Configure open telemetry collector with datadog exporter.
3. transmit some data on this metric.
4. See metric at configuration at Datadog.

## Expected Result
Histogram metric that configured as time metric.

## Actual Result
Histogram metric that configured without millisecond unit.

![image](https://user-images.githubusercontent.com/91830944/206022314-9626ecc4-26ed-4566-abb6-0c7220f86407.png)

### Collector version

0.63.1

## Environment
OS: Ubuntu 20.04
Compiler(if manually compiled): dotnet6

### OpenTelemetry Collector configuration

```yaml
{
  "exporters": {
        "datadog": {
          "api": {
                "fail_on_invalid_key": true,
                "key": "*********",
                "site": "datadoghq.com"
          },
          "metrics": {
                "resource_attributes_as_tags": true
          }
        }
  },
  "processors": {
        "batch": {
          "send_batch_max_size": 256,
          "send_batch_size": 100,
          "timeout": "10s"
        },
        "memory_limiter": {
          "check_interval": "5s",
          "limit_mib": 4096,
          "spike_limit_mib": 2048
        },
        "resource": {
          "attributes": [
                {
                  "key": "deployment.environment",
                  "value": "Local",
                  "action": "upsert"
                }
          ]
        }
  },
  "receivers": {
        "otlp": {
          "protocols": {
                "grpc": {
                  "max_recv_msg_size_mib": 32
                }
          }
        }
  },
  "service": {
        "pipelines": {
          "metrics": {
                "receivers": [
                  "otlp"
                ],
                "processors": [
                  "memory_limiter",
                  "resource",
                  "batch"
                ],
                "exporters": [
                  "datadog"
                ]
          },
          "traces": {
                "receivers": [
                  "otlp"
                ],
                "processors": [
                  "memory_limiter",
                  "resource",
                  "batch"
                ],
                "exporters": [
                  "datadog"
                ]
          }
        },
        "telemetry": {
          "logs": {
                "encoding": "json"
          }
        }
  }
}
```

### Log output

```shell
Not relevant logs...
```
