### ISSUE TITLE
[receiver / postgres] Postgresql metrics receiver has runtime error 

### ISSUE THREAD

**Issue by Alex-Garg** [open-telemetry/opentelemetry-collector-contrib#16769]
### Component(s)

receiver/postgresql

## Description
Postgres metrics receiver has runtime error when executing the request on pg_stat_replication (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9897fc5080eb2a246fd85debf95ff83ba02f3670/receiver/postgresqlreceiver/client.go#L458)

## Steps to Reproduce
Configure otelcol to receiver metrics from a Postgres 14.6 

## Actual Result
`scraperhelper/scrapercontroller.go:214  Error scraping metrics  {"kind": "receiver", "name": "postgresql", "pipeline": "metrics", "error": "unable to query pg_stat_replication: pq: COALESCE types interval and integer cannot be matched", "scraper": "postgresql"}`

Request executed directly on postgres : 
```
postgres=# SELECT
        client_addr,
        coalesce(pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn), -1) AS replication_bytes_pending,
        coalesce(write_lag, -1),
        coalesce(flush_lag, -1),
        coalesce(replay_lag, -1)
        FROM pg_stat_replication;
ERROR:  COALESCE types interval and integer cannot be matched
LINE 4:  coalesce(write_lag, -1),
                             ^
```

### Collector version

0.66.0

## Environment
OS: CentOS 7 + Docker containers

### OpenTelemetry Collector configuration

```yaml
receivers:
  opencensus:
  otlp:
    protocols:
      grpc:
  postgresql:
    endpoint: postgres:5432
    transport: tcp
    username: postgres
    password: postgres
    databases:
      - db1
      - db2
    collection_interval: 10s
    tls:
      insecure: true
```

### Log output

```shell
scraperhelper/scrapercontroller.go:214  Error scraping metrics  {"kind": "receiver", "name": "postgresql", "pipeline": "metrics", "error": "unable to query pg_stat_replication: pq: COALESCE types interval and integer cannot be matched", "scraper": "postgresql"}
```
