### ISSUE TITLE
[processor/transform] Unable to get item from slice resource attributes value

### ISSUE THREAD

**Issue by ralphgj** [open-telemetry/opentelemetry-collector-contrib#16811]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

Hi, I'm trying to use the generated `slice` result by the `Split` function in transform processor statements. But I didn't find any working solution to access the item in `slice` result.

### Describe the solution you'd like

Expected statements:
```yaml
      - context: resource
        statements:
          - set(attributes["db.instance"], Split(attributes["net.peer.name"], ".")[0]) where attributes["net.peer.name"] != nil
```
or
```yaml
      - context: resource
        statements:
          - set(attributes["db.instance"], Split(attributes["net.peer.name"], ".").Get(0)) where attributes["net.peer.name"] != nil
```
