### ISSUE TITLE
[datadog exporter] Counter metrics are being sent as Gauges

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-collector-contrib#1688]
**Describe the bug**
Counter metrics are incorrectly being reported to Datadog as Gauge metrics

**Steps to reproduce**
Create a `LongCounter` metric.  Send it to datadog using the exporter.

**What did you expect to see?**
I expected to see delta values sent to datadog such that in the Datadog UI each datapoint represents the count within that interval.

**What did you see instead?**
 I see a monotonically increasing chart for the metric.

**What version did you use?**
Version: v0.11.0

**What config did you use?**
Config: 
```yaml
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 10s

exporters:
  logging:
    logLevel: debug
  datadog:
    api:
      key: xxx

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
```

**Environment**
OS: Manjaro Linux

**Additional context**
It seems that this shoudl be mapped as a `monotonic_count` from [these docs](https://docs.datadoghq.com/integrations/guide/prometheus-metrics/).

You can see from the code that `Gauge` and `Counter` metrics are treated identically.  This seems incorrect
```go
				case pdata.MetricDataTypeIntGauge:
					datapoints = mapIntMetrics(md.Name(), md.IntGauge().DataPoints())
				case pdata.MetricDataTypeDoubleGauge:
					datapoints = mapDoubleMetrics(md.Name(), md.DoubleGauge().DataPoints())
				case pdata.MetricDataTypeIntSum:
					// Ignore aggregation temporality; report raw values
					datapoints = mapIntMetrics(md.Name(), md.IntSum().DataPoints())
				case pdata.MetricDataTypeDoubleSum:
					// Ignore aggregation temporality; report raw values
					datapoints = mapDoubleMetrics(md.Name(), md.DoubleSum().DataPoints())
```
