### ISSUE TITLE
Bearer token auth extension does not pick up the updated token from file

### ISSUE THREAD

**Issue by saikrishna397** [open-telemetry/opentelemetry-collector-contrib#17031]
### Component(s)

extension/bearertokenauth

## Description
Bearer token auth extension is not picking up the updated token and instead it fetches the token once and that's re-used forever.

## Steps to Reproduce
1. Use bearer token auth extension that gets the token from a file.
```
config:
  extensions:
    bearertokenauth:
      filename: "/etc/secrets/prometheus/<FILE_NAME>"
  exporters:
    prometheusremotewrite:
      auth: 
        authenticator: bearertokenauth
      endpoint: ""
```
2. Check if the bearer token auth picks up the token and sends it along with the request.
3. Update the contents of the token and verify if the new token is updated in the request.

## Expected Result
Request from the bearer token auth should have the updated bearer token.

## Actual Result
Request from the bearer token auth has the old token. 
When I used a valid token and tried to send data to a prometheus remote write EP, it failed with the following error:
```
Exporting failed. The error is not retryable. Dropping data.  {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error │
│ ": "Permanent error: Permanent error: remote write returned HTTP status 401 Unauthorized; err = %!w(<nil>): {\"Error\":{\"Code\":\"TokenExpired\",\"Message\":\"IDX10223: Lifetime validation failed. The token is expired. Val │
│ idTo: 'System.DateTime', Current time: 'System.DateTime'.\"}}", "dropped_items": 29}
```

### Collector version

0.66.0

## Environment
OS: macOS Monterey

### OpenTelemetry Collector configuration

```yaml
config:
    extensions:
      health_check:
      pprof:
      memory_ballast: {}
      bearertokenauth:
        filename: "/etc/secrets/prometheus/TOKEN"
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      kubeletstats:
        collection_interval: 30s
        auth_type: "serviceAccount"
        endpoint: "https://${NODE_NAME}:10250"
        insecure_skip_verify: true
      prometheus:
        config:
          scrape_configs:
          - job_name: "collector-metrics"
            scrape_interval: 15s
            static_configs:
            - targets: ['localhost:8888']
          - job_name: "otel-collector"
            scrape_interval: 15s
            kubernetes_sd_configs:
            - role: pod
              selectors:
              - role: pod
                field: "spec.nodeName=$NODE_NAME"
            relabel_configs:
            # scrape pods annotated with "prometheus.io/scrape: true"
            - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
              regex: "true"
              action: keep
            # read the port from "prometheus.io/port: <port>" annotation and update scraping address accordingly
            - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
              action: replace
              target_label: __address__
              regex: ([^:]+)(?::\d+)?;(\d+)
              # escaped $1:$2
              replacement: $$1:$$2
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: kubernetes_pod_name
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 30
      resourcedetection:
        detectors:
        - env
        timeout: 2s
        override: false
    exporters:
      prometheusremotewrite:
        auth: 
          authenticator: bearertokenauth
        endpoint: "<AZURE_PROMETHEUS_ENDPOINT>"
        resource_to_telemetry_conversion:
          enabled: true
    service:
      extensions: [health_check, pprof, bearertokenauth]
      pipelines:
        metrics:
          receivers: [prometheus, otlp, kubeletstats]
          processors: [memory_limiter, batch, resourcedetection]
          exporters: [prometheusremotewrite]
```

### Log output

```shell
Exporting failed. The error is not retryable. Dropping data.  {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error │
│ ": "Permanent error: Permanent error: remote write returned HTTP status 401 Unauthorized; err = %!w(<nil>): {\"Error\":{\"Code\":\"TokenExpired\",\"Message\":\"IDX10223: Lifetime validation failed. The token is expired. Val │
│ idTo: 'System.DateTime', Current time: 'System.DateTime'.\"}}", "dropped_items": 29}
```

### Additional context

N/A
