### ISSUE TITLE
splunk_hec exporter always returns `over capacity` error when compression is enabled and MaxContentLength is 0

### ISSUE THREAD

**Issue by harshit-splunk** [open-telemetry/opentelemetry-collector-contrib#17035]
### Component(s)

exporter/splnuk_hec

## Description

splunk_hec exporter always returns `over capacity` error when compression is enabled and MaxContentLength is 0

## Steps to Reproduce

Run the agent with the below configuration

## Expected Result

It should sent the data without any errors

## Actual Result

Throws `over capacity` error. It is also similar for logs and trace pipeline

### Collector version

v0.67.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:

exporters:
  splunk_hec:
    token: "00000000-0000-0000-0000-0000000000000"
    endpoint: "https://splunk:8088/services/collector"
    source: "otel"
    sourcetype: "otel"
    index: "metrics"
    disable_compression: false
    max_content_length_metrics: 0

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [splunk_hec]
```

### Log output

```shell
{"error": "Permanent error: error writing the event: over capacity"}
```

### Additional context

It is assigning maxCapacity by subtracting 8 from max_content_length resulting in -8. 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6f44d8d40372fca13df2358e63bf51faada4cf18/exporter/splunkhecexporter/client.go#L106
