### ISSUE TITLE
Empty X-Ray traces when instrumenting Kafka consumer/producers 

### ISSUE THREAD

**Issue by nachomdo** [open-telemetry/opentelemetry-collector-contrib#1708]
**Describe the bug**

It seems that the current implementation only consider root segments if span kind is SERVER. This makes that other span types (i.e. CONSUMER or PRODUCER) are always considered a subsegment and even though they are exported to X-Ray their information is always empty 

```
{
    "Duration": null,
    "Id": "1-5fc28b8b-d81572f7275da12a1d39eb8b",
    "LimitExceeded": false,
    "Segments": []
}
```

**Steps to reproduce**

Use the opentelemetry java autoinstrumentation agent and Kafka project with some clients/producers 

```
MAVEN_OPTS="-javaagent:/path-to-agent/aws-opentelemetry-agent.jar -Dotel.resource.attributes='service.name=kafka,service.namespace=remote,cloud.infrastructure_service=EC2'" mvn exec:java -Dexec.mainClass=myapps.Pipe
```

**What did you expect to see?**

![image](https://user-images.githubusercontent.com/3109377/100523437-6d1fcf00-31a8-11eb-812b-4e28b91d83f0.png)

**What did you see instead?**

![image](https://user-images.githubusercontent.com/3109377/100523451-7f017200-31a8-11eb-9b11-a2426a8c2e3b.png)

**What version did you use?**
Version: latest stable and dev

**What config did you use?**

```
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  awsxray:
  logging:
    loglevel: debug
processors:
  batch:
    timeout: 1s
    send_batch_size: 50
service:
  pipelines:
    metrics:
      receivers: 
      - otlp
      processors: 
      - batch 
      exporters: 
      - logging
    traces:
      processors:
      - batch
      receivers:
      - otlp
      exporters:
      - logging
      - awsxray
```
