### ISSUE TITLE
OpenTelemetryCollector receivers rabbitmq with azuremonitor

### ISSUE THREAD

**Issue by sb185296** [open-telemetry/opentelemetry-collector-contrib#17080]
### Component(s)

exporter/azuremonitor

## Description
OpenTelemetryCollector receivers rabbitmq with azuremonitor
## Steps to Reproduce

1.install OpenTelemetry opertor
2. use below file to set a rabbit reciver 
3.  get error

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  mode: sidecar
  image: otel/opentelemetry-collector-contrib:latest
  config: |
    receivers:
      rabbitmq:
        endpoint: http://rabbithq:15672
        username: admin
        password: admin
        collection_interval: 10s
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
 
    exporters:
      logging:
 

      otlp:
        endpoint: oteld-collector.default.svc.cluster.local:4317
        tls:
          insecure: true     

      azuremonitor:
        endpoint: "https://dc.services.visualstudio.com/v2/track"
        instrumentation_key: ""
        # maxbatchsize is the maximum number of items that can be
        # queued before calling to the configured endpoint
        maxbatchsize: 100
        # maxbatchinterval is the maximum time to wait before calling
        # the configured endpoint.
        maxbatchinterval: 10s
 
    service:
      pipelines:

        traces:
          receivers: [otlp]
          processors: []
          exporters: [azuremonitor,logging]
        metrics:
          receivers: [rabbitmq]
          exporters: [azuremonitor, logging]
        # logs:
        #   receivers: [otlp]
        #   exporters: [azuremonitor, logging]
```

### Log output

```shell
022-12-17T13:58:11.560Z    info    service/telemetry.go:111    Setting up own telemetry...                                          ││ 2022-12-17T13:58:11.560Z    info    service/telemetry.go:141    Serving Prometheus metrics    {"address": ":8888", "level": "Basic"} ││ 2022-12-17T13:58:11.560Z    info    components/components.go:30    Development component. May change in the future.    {"kind": "exp ││ 2022-12-17T13:58:11.561Z    info    components/components.go:30    Stability level of component is undefined    {"kind": "exporter", ││ Error: cannot build pipelines: failed to create "azuremonitor" exporter, in pipeline "metrics": telemetry type is not supported      ││ 2022/12/17 13:58:11 collector server run finished with error: cannot build pipelines: failed to create "azuremonitor" exporter, in p 
```
```


### Additional context

_No response_
