### ISSUE TITLE
loadbalancerexporter fails if sending_queue is not disabled

### ISSUE THREAD

**Issue by david-perez-martin** [open-telemetry/opentelemetry-collector-contrib#17173]
### Component(s)

exporter/loadbalancing

## Description
When the loadbalancer exporter is enabled, I have all the time the error related to queue_size
## Steps to Reproduce
Deploy otel-collector-contrib with loadbalancer exporter and send data (600 spans or more)
## Expected Result
Work with queues without problems

## Actual Result
Error trace repeated all the time.

...

### Collector version

0.63 & 0.67

## Environment
OS: OEL8
Compiler(if manually compiled): (e.g., "go 14.2") Dowloaded from releases directly

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9901
      http:
        endpoint: 0.0.0.0:9902
processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 20
extensions:
  health_check:
    endpoint: 0.0.0.0:8433
    path: "/health/status"
    check_collector_pipeline:
      enabled: false
      interval: "5m"
      exporter_failure_threshold: 15
  memory_ballast:
    size_in_percentage: 20
exporters:
  loadbalancing:
    protocol: 
      otlp:
        timeout: 5s
        sending_queue:
          enabled: true
        retry_on_failure:
          enabled: true
          max_interval: 60s
          max_elapsed_time: 300s
        tls:
          insecure: true
    resolver:
      dns:
        hostname: otel-collector-backend
        port: 9902
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [loadbalancing]
  extensions: [health_check, memory_ballast]
  telemetry:
    metrics:
      level: normal
      address: 0.0.0.0:8080
```

### Log output

```shell
2022-12-20T09:55:29.849Z        error   exporterhelper/queued_retry.go:310      Dropping data because sending_queue is full. Try increasing queue_size. {"kind": "exporter", "data_type": "traces", "name": "loadbalancing", "dropped_items": 1}
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
```

### Additional context

I tried to increase the queue to 10.000 and 50.000, but the problem persists.
