### ISSUE TITLE
How to use loadbalancingexporter?

### ISSUE THREAD

**Issue by Liubey** [open-telemetry/opentelemetry-collector-contrib#17267]
## Description

Can I recieve Jaeger thrift_compact(port 6381) and load balance them to another collector such as:
Jaeger client(opentracing) --> collector 1 recieve with jaeger+thrift_compact and exporter is  loadbalancing --> collector 2 with receiver is otlp 
Then I got spans in collector1 such as:
```
2022-12-27T13:59:43.238Z	info	TracesExporter	{"kind": "exporter", "data_type": "traces", "name": "logging", "#spans": 10}
```
But I got nothing in collector2.

I have some questions for that(sorry for that):

1. Does I need use docker image of opentelemetry-collector or otel/opentelemetry-collector-contrib?
2. How can use loadbalancingexporter for opentelemetry-collector? I got "* error decoding 'exporters': unknown type: "loadbalancing" for id: "loadbalancing" (valid values: [logging prometheus zipkin jaeger kafka opencensus prometheusremotewrite otlp otlphttp file])"
3. Is the loadbalancingexporter just recieve oltp protocol?What can I do?

Thank you so much.

collector 1 config
```
receivers:
  jaeger/loadbalancer:
    protocols:
      thrift_compact:
        endpoint: localhost:6831

processors:

exporters:
  logging:
    loglevel: debug
  loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        insecure: true
    resolver:
      static:
        hostnames:
          - localhost:4567

service:
  pipelines:
    traces:
      receivers:
        - jaeger/loadbalancer
      processors: []
      exporters:
        - loadbalancing
        - logging

```

collector 2 config:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4567
processors:
 batch:
   timeout: 1s
 resource:
   attributes:
     - key: test.key
       value: "test-value"
       action: insert
exporters:
 logging:
   loglevel: info
 otlp:
   endpoint: localhost:4317
   tls:
    insecure: true
extensions:
 health_check:
 pprof:
   endpoint: :1888
 zpages:
   endpoint: :55679
service:
 extensions: [pprof, zpages, health_check]
 pipelines:
   traces:
     receivers: [otlp]
     processors: [batch, resource]
     exporters: [logging, otlp]
```

### Collector version

0.68.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
