### ISSUE TITLE
New component: exceptionsconnector

### ISSUE THREAD

**Issue by marctc** [open-telemetry/opentelemetry-collector-contrib#17272]
### The purpose and use-cases of the new component

The purpose of this connector component is to extract metrics and logs from [recorded exceptions](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/exceptions/) from spans. It will generate a counter (`exceptions_total`) where exceptions are aggregated by default by exception type and exception message. Aggregation could be configurable by the user.

#### metric output

```
exceptions_total{exception_message="list index out of range", exception_type="IndexError", service_name="test", span_kind="SPAN_KIND_SERVER", status_code="STATUS_CODE_ERROR"}  4

exceptions_total{exception_message="local variable 'a' referenced before assignment", exception_type="UnboundLocalError", service_name="test", span_kind="SPAN_KIND_SERVER", status_code="STATUS_CODE_ERROR"}  6
```

#### log output

```json
{
  "severity": "ERROR",
  "attributes": {
    "exception.message": "division by zero",
    "exception.stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/opentelemetry/trace/__init__.py\", line 541, in use_span\n    yield span\n  File \"/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py\", line 55, in inner\n    response = get_response(request)\n  File \"/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/code/./example/views.py\", line 24, in index\n    random.choice([f0, f1, f2, f3])()\n  File \"/code/./example/views.py\", line 7, in f0\n    a = 1/0\nZeroDivisionError: division by zero\n",
    "exception.type": "ZeroDivisionError",
    "http.flavor": "1.1",
    "http.host": "127.0.0.1:8000",
    "http.method": "GET",
    "http.scheme": "http",
    "http.server_name": "644f31ce42a5",
    "http.status_code": "",
    "http.target": "/",
    "http.user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
    "service.name": "faulty"
  }
}
```

#### Example configuration for the component

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: htp://localhost:4317
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

connectors:
  exceptions: 

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, exceptions]
    metrics:
      receivers: [exceptions]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [exceptions]
      exporters: [loki]
```

### Telemetry data types supported

traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

@jpkrohling
