### ISSUE TITLE
Prometheus histograms are exported as gauge

### ISSUE THREAD

**Issue by klippx** [open-telemetry/opentelemetry-collector-contrib#17284]
### Component(s)

exporter/prometheus, receiver/prometheus

## Description

Prometheus histogram metrics does not work in the `otel/opentelemetry-collector-contrib` docker image.

I have a locally running app and a docker compose cluster running on the side. The app is using open telemetry to push metrics via grpc on port 4317. The app also exposes metrics on localhost:8082/metrics

## Steps to Reproduce

This is my configuration, 

`docker-compose.yaml`:
```
version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.68.0 # More info: https://opentelemetry.io/docs/collector/getting-started/
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "8083:8083" # Prometheus metrics exposed by the collector
      - "4317:4317" # grpc endpoint the app will push toward

  # UI: http://localhost:9090
  prometheus:
    image: prom/prometheus:v2.28.1 # More info: https://prometheus.io/docs/prometheus/latest/installation/#using-docker
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
```

`prometheus.yaml`:
```
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "opentelemetry-collector"
    static_configs:
      - targets: ["otel-collector:8083"]
```

`otel-config.yaml`:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  prometheus:
    endpoint: "0.0.0.0:8083"
    namespace: fed_graph

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
```

You also need an app that can push prometheus metrics, and expose the current state to show how it really looks.

## Expected Result

All metrics are exported from the app to prometheus:

<img width="1197" alt="Screenshot 2022-12-28 at 17 19 19" src="https://user-images.githubusercontent.com/2785359/209841738-9031b900-c60a-4c67-bf0a-12d713735d30.png">

```
# HELP apollo_router_http_request_duration_seconds Total number of HTTP requests made.
# TYPE apollo_router_http_request_duration_seconds histogram
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="0.001"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="0.005"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="0.015"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="0.05"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="0.1"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="0.2"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="0.3"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="0.4"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="0.5"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="1"} 0
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="5"} 1
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="10"} 1
apollo_router_http_request_duration_seconds_bucket{kind="router_response",operation_name="CarByToken",service_name="router",status="200",le="+Inf"} 1
apollo_router_http_request_duration_seconds_sum{kind="router_response",operation_name="CarByToken",service_name="router",status="200"} 2.5408757079999997
apollo_router_http_request_duration_seconds_count{kind="router_response",operation_name="CarByToken",service_name="router",status="200"} 1
```

Note that this is `localhost:8082/metrics`, this is "reality" as far as my app is concerned.

## Actual Result

Al `histogram`s are getting transformed into `gauge`s.

<img width="500" alt="Screenshot 2022-12-28 at 17 20 28" src="https://user-images.githubusercontent.com/2785359/209841970-8fdfe31f-ece2-4af4-80cd-eb3efa85d173.png">

```
# HELP fed_graph_apollo_router_http_request_duration_seconds Total number of HTTP requests made.
# TYPE fed_graph_apollo_router_http_request_duration_seconds gauge
fed_graph_apollo_router_http_request_duration_seconds{job="router",kind="router_response",operation_name="CarByToken",status="200"} 2.5408757079999997
```

Note that this is `localhost:8083/metrics`, this is the metrics from the otel prometheus exporter.

What happened here?

### Collector version

otel/opentelemetry-collector-contrib:0.68.0

## Environment
OS: MacOS Monterey 12.6.1
Docker: Docker Desktop 4.12.0
Compiler(if manually compiled): nope 

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  prometheus:
    endpoint: "0.0.0.0:8083"
    namespace: fed_graph

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
```
