### ISSUE TITLE
How can loadbalancingexporter be combined with otel-agent (daemonset)？

### ISSUE THREAD

**Issue by mizhexiaoxiao** [open-telemetry/opentelemetry-collector-contrib#17297]
### Component(s)

exporter/loadbalancing

### Describe the issue you're reporting

Suppose my otel-agent is deployed as a daemonset, and the exporter uses loadbalancingexporter. Is this the correct way to use it? How do different loadbalancingexporters know which collector the trace data is sent to?

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  namespace: trace
  labels:
    app: opentelemetry
    component: otel-agent-conf
data:
  otel-agent-config: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: localhost:4317
      
      processors:
      
      exporters:
        logging:
        loadbalancing:
          protocol:
            otlp:
              timeout: 1s
          resolver:
            static:
              hostnames:
              - backend-1:4317
              - backend-2:4317
              - backend-3:4317
      
      service:
        pipelines:
          traces:
            receivers:
              - otlp
            processors: []
            exporters:
              - loadbalancing
              - logging

**Comment by Liubey** [comment]
Default It use traceID to route.
And you can config it by 
```
routing_key
```

@mizhexiaoxiao 

you can see detail from https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/README.md

**Comment by Liubey** [comment]
In my config, It looks like:
```
exporters:
  logging:
    loglevel: info
  loadbalancing:
    routing_key: "traceID"
    protocol:
      otlp:
        timeout: 1s
        tls:
          insecure: true
    resolver:
      static:
        hostnames:
          - XXX:4317
          - XXX:4327  
```
