### ISSUE TITLE
OpenTelemetry Collector - error reading server preface: http2: frame too large

### ISSUE THREAD

**Issue by joaorzz** [open-telemetry/opentelemetry-collector-contrib#17311]
### Component(s)

cmd/otelcontribcol

### Describe the issue you're reporting

``Hi, guys!

I've tried to implement open telemetry collector with grafana tempo on my .net 6 application, but now i'm lost.

I'm receiving that error message:

```
[core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {

"Addr": "tempo-us-central1.grafana.net:443",

"ServerName": "tempo-us-central1.grafana.net:443",

"Attributes": null,

"BalancerAttributes": null,

"Type": 0,

"Metadata": null

}. Err: connection error: desc = "error reading server preface: http2: frame too large" {"grpc_log": true}
```

here is my collector.yaml

```
receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317

extensions:
  headers_setter:
    headers:
      - key: Authorization
        value: "Basic MY_TOKEN"

exporters:
  otlp:
    auth:
      authenticator: headers_setter
    endpoint: tempo-us-central1.grafana.net:443
    tls:
      insecure: true
      insecure_skip_verify: true
  logging:
    logLevel: debug

service:
  extensions: [headers_setter]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [logging]
```

here is my docker-compose.yaml
```
version: '3.4'

services:
  api:
    container_name: device-check
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "8080:80"

  collector:
    image: otel/opentelemetry-collector-contrib:0.68.0
    container_name: collector
    command: [ "--config=/etc/collector.yaml" ]
    volumes:
      - ./collector.yaml:/etc/collector.yaml
    ports:
      - "4317"
```

here is my .net configuration
```
services.AddOpenTelemetry().WithTracing(builder =>
  {
      builder.AddConsoleExporter()
      .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("MY_SERVICE"))
      .AddAspNetCoreInstrumentation()
      .AddSource("MY_SERVICE")
      .AddOtlpExporter(options =>
      {
          options.Protocol = OtlpExportProtocol.HttpProtobuf;
  
          options.Endpoint = new Uri("http://collector:4317");
      })
      .AddHttpClientInstrumentation();
}).StartWithHost();
```

can anybody help me? I can't identify what I'm doing wrong.

i've tried to search others .net examples, but it's have been hard.

**Comment by frzifus** [comment]
Seems that with your otel exporter config is wrong. 
My assumption is that `tempo-us-central1.grafana.net:443` expects a TLS-Handshake. But your collector config disables TLS.

cc @jpkrohling

**Comment by joaorzz** [comment]
when I remove the tls config, I got this error:

```warn zapgrpc/zapgrpc.go:195 [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {

"Addr": "tempo-us-central1.grafana.net:443",

"ServerName": "tempo-us-central1.grafana.net:443",

"Attributes": null,

"BalancerAttributes": null,

"Type": 0,

"Metadata": null

}. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority" {"grpc_log": true}```

**Comment by atoulme** [comment]
I wonder if you could try to drop the port `:443` and see if then the certificate check works. I see `"ServerName": "tempo-us-central1.grafana.net:443",` in the response, maybe there's a bug there.

**Comment by frzifus** [comment]
afaik a port number is mandatory. 
May [this](https://github.com/open-telemetry/opentelemetry-collector/blob/f2a0133bf677b9fe2e18b7c02eb1b6bf5e849999/config/configtls/README.md#tls--mtls-configuration) does help?
```
Additionally you can configure TLS to be enabled but skip verifying the server's certificate chain. This cannot be combined with insecure since insecure won't use TLS at all.

    insecure_skip_verify (default = false): whether to skip verifying the certificate or not.
```

**Comment by jpkrohling** [comment]
I'm preparing comprehensive docs on how to connect to Grafana Cloud Traces (https://github.com/grafana/opentelemetry-docs/pull/20), but here's what could work for you:

```yaml
receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317

extensions:
  basicauth:
    client_auth:
      username: "${TRACES_USER_ID}"
      password: "${TOKEN}"

exporters:
  otlp:
    auth:
      authenticator: basicauth
    endpoint: tempo-us-central1.grafana.net:443
  logging:
    logLevel: debug

service:
  extensions: [basicauth]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [logging]
```
