### ISSUE TITLE
Honeycomb exporter sample_rate/sample_rate_attribute config values have undesirable behavior

### ISSUE THREAD

**Issue by cpcloud** [open-telemetry/opentelemetry-collector-contrib#1733]
**Describe the bug**
The Honeycomb exporter sends events using the [`SendPresampled` method](https://github.com/honeycombio/libhoney-go/blob/3bfcd4dd123e0fb94015b8d1baf2fa0bdf81d270/libhoney.go#L759) which assumes that sampling has already taken place.

The `sample_rate`/`sample_rate_attribute` configuration values appear to have almost the opposite effect, which is that since the collector isn't sampling based on these attributes (only setting the attribute globally or per event) Honeycomb upsamples events based on this rate and so each event appears like it occurs `sample_rate`/`sample_rate_attribute` times.

**Steps to reproduce**

Set either attribute to a value > 1 and observe the count of events in the Honeycomb UI.

**What did you expect to see?**

I expect to see the same number of events occurring in the Honeycomb UI, indicating that sampling has occurred on the collector side.

**What did you see instead?**

`sample_rate` number of events

**What version did you use?**
Version: `v0.15.0`

**What config did you use?**
Config: (e.g. the yaml config file)

```
receivers:
  jaeger:
    protocols:
      thrift_compact:

exporters:
  logging:
    loglevel: info
  honeycomb:
    api_key: ${HONEYCOMB_API_KEY}
    dataset: ${HONEYCOMB_DATASET}
    sample_rate: 5

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [honeycomb, logging]
```

**Environment**
OS: NixOS `unstable-small` branch

**Additional context**
I'm running the collector as a container using `docker-compose`.
