### ISSUE TITLE
New component: Cloudflare Logs Receiver

### ISSUE THREAD

**Issue by JonathanWamsley** [open-telemetry/opentelemetry-collector-contrib#17376]
### The purpose and use-cases of the new component

This Cloudflare receiver will use the the [LogPull API](https://developers.cloudflare.com/logs/logpull/) to collect logs from the Cloudflare logs aggregation system. A use case of this receiver is to ingest Cloudflare logs into OTLP format or other desired log platform.

### Example configuration for the component

```yaml
receivers:  
  cloudflare:
    poll_interval: 1m
    storage: <storage id> # not required. ID of the storage extension component
    auth: # Required. Either an email and key or an API token is required in the header authentication
      email: <X-Auth-Email>
      key: <X-Auth-Key>
      token: <API_TOKEN>
    zone: <ZONE_ID> # Required
    logs: # Not required
      count: # not required, return up to that many logs. If no value is given, all logs will be collected
      sample: 1.0 # not required, returns only a sample of logs from 0.001 to 1.0
      fields: [ClientIP, ClientRequestHost, ClientRequestMethod, ClientRequestURI, EdgeEndTimestamp, EdgeResponseBytes, EdgeResponseStatus, EdgeStartTimestamp, RayID] # not required, default, a comma-seperated list of fields to return
```

### Telemetry data types supported

logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

An example request looks like:
```sh
curl -s \
    -H "X-Auth-Email: <EMAIL>" \
    -H "X-Auth-Key: <API_KEY>" \
    "https://api.cloudflare.com/client/v4/zones/<ZONE_ID>/logs/received?start=2017-07-18T22:00:00Z&end=2017-07-18T22:01:00Z&count=1&fields=ClientIP,ClientRequestHost,ClientRequestMethod,ClientRequestURI,EdgeEndTimestamp,EdgeResponseBytes,EdgeResponseStatus,EdgeStartTimestamp,RayID"
```

Since the Cloudflare receiver has a start time, a storage extension adapter like in [mongodbatlasreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a052c88922ae9bba4a1026bdd8c14c36a406da51/receiver/mongodbatlasreceiver/alerts.go#L157-L165) will be used to save the start times in case any interruptions occur.

The `fields` parameter will start out collecting only the default [fields](https://developers.cloudflare.com/logs/logpull/understanding-the-basics/#format-of-the-data-returned), but future enhancements can be made to include more fields values from a list [here](https://developers.cloudflare.com/logs/reference/log-fields/zone/http_requests).
