### ISSUE TITLE
[receiver/kafkareceiver] Consumer Offsets AutoCommit config not working

### ISSUE THREAD

**Issue by avadhut123pisal** [open-telemetry/opentelemetry-collector-contrib#17374]
### Component(s)

receiver/kafka

## Description
`AutoCommit` config for Kafka Receiver is not taking any effect. By default, it is enabled, if we disable it from config, it is not working.

## Steps to Reproduce
Configure the Kafka Receiver to disable the offset Auto Commit.
```
receivers:
  kafka:
    autocommit: 
      enable: false
```

## Expected Result
Above config should disable the offset Auto Commit. 

## Actual Result
Offset Auto Commit is not getting disabled. 

### Collector version

v0.59.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  kafka:
    autocommit: 
      enable: false
```
```


### Log output

_No response_

### Additional context

_No response_
