### ISSUE TITLE
ObservedTimestamp is not populated for logs in Azure Data Explorer

### ISSUE THREAD

**Issue by akakarikos** [open-telemetry/opentelemetry-collector-contrib#17447]
### Component(s)

exporter/azuredataexplorer

## Description
The field `ObservedTimestamp` is not populated when exporting logs to Azure Data Explorer.

## Steps to Reproduce
Setup OTel collector to export logs to the Azure Data Explorer. Check the exported logs to see if the field `ObservedTimestamp` is populated properly.

## Expected Result
The field `ObservedTimestamp` for the logs in Azure Data Explorer should be properly populated.

## Actual Result
The field `ObservedTimestamp` for the logs in Azure Data Explorer is not populated correctly but with the default value `1970-01-01 00:00:00.0000`

![image](https://user-images.githubusercontent.com/10879762/211297783-e525c8c2-c194-4392-9257-df6a0cce88f0.png)

### Collector version

0.68.0

## Environment
OS: AKS 1.23.8 - .NET6

### OpenTelemetry Collector configuration

```yaml
receivers:
      zipkin:
        endpoint: localhost:9411
      otlp:
        protocols:
          grpc:
            endpoint: localhost:4317
          http:
            endpoint: localhost:4318
    processors:
      batch:
        timeout: 10s
        send_batch_size: 10000
        send_batch_max_size: 11000
    
    exporters:
      logging:
        verbosity: detailed

      azuredataexplorer:
        cluster_uri:
        application_id:
        application_key:
        tenant_id:
        db_name:
        metrics_table_name: 'OTELMetrics'
        logs_table_name: 'OTELLogs'
        traces_table_name: 'OTELTraces'
        ingestion_type : 'managed'
    
    service:
      pipelines:
        traces:
          receivers: [zipkin,otlp]
          processors: [batch]
          exporters: [azuredataexplorer,logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [azuredataexplorer,logging]
```
