### ISSUE TITLE
Unable to see exemplar data from span metrics processor when exporter is set to prometheus

### ISSUE THREAD

**Issue by vaish1707** [open-telemetry/opentelemetry-collector-contrib#17496]
### Component(s)

exporter/prometheus, processor/spanmetrics

### What happened?

Hi Team,
I'm trying to generate metrics from span using span metrics processor which I'm able to successfully generate. The exporter is set to prometheus for the metrics generated out of span metrics processor.

I'm using helm charts to deploy opentelemetry collector in kubernetes and following is my configuration

```
mode: "deployment"
replicaCount: 1
nameOverride: otel-collector
fullnameOverride: otel-collector

# Base collector configuration.
config:
  exporters:
    otlp:
      endpoint: otel-collector-grpc:4317
      tls:
        insecure: true
    prometheus:
      endpoint: "0.0.0.0:8889"
      metric_expiration: 1440m
      enable_open_metrics: true
  extensions:
    health_check: {}
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679
  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 4000
      spike_limit_mib: 800
    batch: {}
    tail_sampling:
      policies:
        - name: drop_noisy_traces_url
          type: string_attribute
          string_attribute:
            key: http.target
            values:
              - \/health
              - \/ping
            enabled_regex_matching: true
            invert_match: true
    spanmetrics:
      metrics_exporter: prometheus
      dimensions:
        - name: http.method
        - name: http.status_code
        - name: http.target
      dimensions_cache_size: 1000
      aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
    otlp/spanmetrics:
      protocols:
        grpc:
          endpoint: 0.0.0.0:12346
  service:
    extensions:
      - pprof
      - zpages
      - health_check
    pipelines:
      metrics:
        exporters:
          - prometheus
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp/spanmetrics
      traces:
        exporters:
          - otlp
        processors:
          - memory_limiter
          - batch
          - tail_sampling
          - spanmetrics
        receivers:
          - otlp

# Configuration for ports
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  jaeger-thrift:
    enabled: true
    containerPort: 14268
    servicePort: 14268
    hostPort: 14268
    protocol: TCP
  jaeger-grpc:
    enabled: true
    containerPort: 14250
    servicePort: 14250
    hostPort: 14250
    protocol: TCP
  metrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP
  healthcheck:
    enabled: true
    containerPort: 13133
    servicePort: 13133
    protocol: TCP
  zpages:
    enabled: true
    containerPort: 55679
    servicePort: 55679
    protocol: TCP
  pprof:
    enabled: true
    containerPort: 1888
    servicePort: 1888
    protocol: TCP
# Resource limits & requests. Update according to your own use case as these values might be too low for a typical deployment.
resources:
  limits:
    cpu: 256m
    memory: 512Mi

service:
  type: NodePort
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
```
Following is an example metric which I see in locahost:8889/metrics and it doesn't have any exemplar data. Do I need to change any configuration in prometheus exporter or span metrics processor for me to see the exemplars data in prometheus exporter?

```
    latency_bucket{http_method="GET",http_status_code="200",http_target="<http_target>",operation="<operation name>",service_name="<operation_name>",span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_UNSET",le="15000"} 1

```

Can someone please help me?

### Collector version

0.67.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
mode: "deployment"
replicaCount: 1
nameOverride: otel-collector
fullnameOverride: otel-collector

# Base collector configuration.
config:
  exporters:
    otlp:
      endpoint: otel-collector-grpc:4317
      tls:
        insecure: true
    prometheus:
      endpoint: "0.0.0.0:8889"
      metric_expiration: 1440m
      enable_open_metrics: true
  extensions:
    health_check: {}
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679
  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 4000
      spike_limit_mib: 800
    batch: {}
    tail_sampling:
      policies:
        - name: drop_noisy_traces_url
          type: string_attribute
          string_attribute:
            key: http.target
            values:
              - \/health
              - \/ping
            enabled_regex_matching: true
            invert_match: true
    spanmetrics:
      metrics_exporter: prometheus
      dimensions:
        - name: http.method
        - name: http.status_code
        - name: http.target
      dimensions_cache_size: 1000
      aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
    otlp/spanmetrics:
      protocols:
        grpc:
          endpoint: 0.0.0.0:12346
  service:
    extensions:
      - pprof
      - zpages
      - health_check
    pipelines:
      metrics:
        exporters:
          - prometheus
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp/spanmetrics
      traces:
        exporters:
          - otlp
        processors:
          - memory_limiter
          - batch
          - tail_sampling
          - spanmetrics
        receivers:
          - otlp

# Configuration for ports
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  jaeger-thrift:
    enabled: true
    containerPort: 14268
    servicePort: 14268
    hostPort: 14268
    protocol: TCP
  jaeger-grpc:
    enabled: true
    containerPort: 14250
    servicePort: 14250
    hostPort: 14250
    protocol: TCP
  metrics:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP
  healthcheck:
    enabled: true
    containerPort: 13133
    servicePort: 13133
    protocol: TCP
  zpages:
    enabled: true
    containerPort: 55679
    servicePort: 55679
    protocol: TCP
  pprof:
    enabled: true
    containerPort: 1888
    servicePort: 1888
    protocol: TCP
# Resource limits & requests. Update according to your own use case as these values might be too low for a typical deployment.
resources:
  limits:
    cpu: 256m
    memory: 512Mi

service:
  type: NodePort
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
```
