### ISSUE TITLE
New component: Pure Storage Receiver for FlashBlade

### ISSUE THREAD

**Issue by dgoscn** [open-telemetry/opentelemetry-collector-contrib#17528]
### **Pure Storage Receiver for OpenTelemetry**

PureStorage has a product called **FlashBlade**. Currently, we export the arrays to vendor-specific backends, but we want to provide a receiver that will allow customers to send data to their backends of choice

It is possible to see the current **FlashBlade OpenMetrics exporter** [here](https://github.com/PureStorage-OpenConnect/pure-fb-openmetrics-exporter).

### Example configuration for the component

```yaml
receivers:
  purefb:
    endpoint: http://172.31.60.207:9491/metrics
    arrays:
    - address: gse-fb01
      auth:
        authenticator: bearertokenauth/fb01
    buckets:
    - address: gse-fb01
      auth:
        authenticator: bearertokenauth/fb01
    clients:
    - address: gse-fb01
      auth:
        authenticator: bearertokenauth/fb01
    file:
    - address: gse-fb01
      auth:
        authenticator: bearertokenauth/fb01
    usage:
    - address: gse-fb01
      auth:
        authenticator: bearertokenauth/fb01
    env: dev
    settings:
      reload_intervals:
        array: 
        buckets: 
        clients: 
        file: 
        usage:
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

Juraci Paixão Kröhling @jpkrohling
