### ISSUE TITLE
how to use Opentelemetry collector's health_check as livenessProbe or readinessProbe 

### ISSUE THREAD

**Issue by cdash415** [open-telemetry/opentelemetry-collector-contrib#17526]
### Component(s)

extension/healthcheck

### What happened?

Describe the bug
I'm pretty new to opentelemetry and currently trying to configure livenessProbe for Opentelemetry collector and wanted to verify it in kubernetes cluster.

Issue:

1. How to use livenessProve here (like we use in kubernetes Deployment)?
2. Unable to modify/add initialDelaySeconds, periodSeconds, failureThreshold etc what are the allowed fields here?

Using opentelemetery-collector-contrib:0.60.0

Added below in config.yaml:
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
```
```
config:
      extensions:
        health_check:
          endpoint: 0.0.0.0:8081
          path: healthz
```
```
service:
      extensions:
      - health_check

```

### Collector version

opentelemetery-collector-contrib:0.60.0

### OpenTelemetry Collector configuration

```yaml
replicaCount: 2

OpenTelemetryCollector:
  #Application name for Otel collector instance that collects cluster-level metrics from the Kubernetes API
  name: otelcontribcol
  labels: opentelemetry
  component: otel_collector
  #collector contrib image
  #image: obs-docker-development.pub-repo.prod.us-west-2.aws.fico.com/obs-collector/opentelemetery-collector-contrib:0.60.0
  image: obs-docker-development.pub-repo.prod.us-west-2.aws.fico.com/fico/pb/obs/opentelemetery-collector-contrib:0.60.0
  tag: ""
  mode: deployment
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10001
  #sumoLogic Endpoint for logs ,metrics and traces
  criblEndpoint: https://otel-cribl-trace.services.aws.fico.com:4317
  exporterOtlphttpLoglevel: debug
  pipelinesTelemetryLogsLabel: debug
  pipelinesTelemetryMetricsAddress: 0.0.0.0:8889

secretsData:
  SecretProviderName: obs-otel-secret
  providerName: aws
  arn: "eks.amazonaws.com/role-arn: arn:aws:iam::350063297140:role/platform-cd-jenkins-role-anywhere"
  splunkdirecttokenname: "splunkdirecttoken"
  secretName: obsjfrogregistry


resources:
  limits_cpu: 2000m
  limits_memory: 6Gi
  requests_memory: 1Gi
  requests_cpu: 500m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100

#Metrics receiver,processor,exporter entry
metrics_receivers:
  - k8s_cluster
metrics_processors:
  - memory_limiter
  - filter
  - resource
  - resource/add_collector_k8s
  - resource/add_environment
  - resource/k8s_cluster
  - batch
metrics_exporters:
  - otlp
  - logging

#Logs receiver,processor,exporter entry
logs_receivers:
  - k8s_events
logs_processors:
  - memory_limiter
  - resource
  - attributes/drop_event_attrs
  - resourcedetection
  - resource/add_collector_k8s
  - resource/add_environment
  - resource/k8s_cluster
  - batch

splunk_hec_exporter_direct:
  enabled: true
  endpoint: https://otel-cribl-log.services.aws.fico.com:4319
  log_data_enabled: true
  profiling_data_enabled: false
  token: /etc/ssl/certs/splunktokenreciever  #updating it using set command while deploying via helm in cicd
  tls_insecure: false
  tls_insecure_skip_verify: true
  tls_cert_file: /etc/ssl/certs/criblCert.pem
  tls_key_file: /etc/ssl/certs/criblKey.pem

ClusterRole:
  name: otelcontribcol
  labels: otelcontribcol

ClusterRoleBinding:
  name: otelcontribcol
  labels: otelcontribcol
  roleRefName: otelcontribcol
  serviceAccountName: otelcontribcol-collector

ServiceAccount:
  name: otelcontribcol
  labels: otelcontribcol
  # Specifies whether a service account should be created
  create: true

# receivers: auth types
k8s_cluster:
  auth_type: serviceAccount
k8s_events:
  auth_type: serviceAccount

# processors configuration values

resource:
  cluster_name: k8s.cluster.name
  cluster_value: dms-k8s-dev-EKS-Cluster
  att_key: metric_source
  att_value: kubernetes-cluster-receiver

resource_environment:
  resource_key: deployment.environment
  resource_value: dms-k8s-dev-EKS-Cluster
resource_k8s_cluster:
  resource_key: receiver
  resource_value: k8sclusterreceiver
resourcedetection:
  detectors_env: env
  detectors_eks: eks
  detectors_ec2: ec2
  detectors_system: system
  override: true
  timeout: 10s

memory_limiter:
  limit_percentage: 65
  spike_limit_percentage: 25
  check_interval: 1s
batch:
  send_batch_size: 400
  timeout: 20s

rbac:
  # Specifies whether RBAC resources should be created
  create: true

extensions:
  health_check: null
  memory_ballast:
    size_mib: 500

service:
  extensions:
  pipelines:
    logs:
      exporters:
        - splunk_hec
```
