### ISSUE TITLE
confmap expand feature fails in prometheusremotewrite

### ISSUE THREAD

**Issue by kago-dk** [open-telemetry/opentelemetry-collector-contrib#17529]
### Component(s)

exporter/prometheusremotewrite

### What happened?

**Describe the bug**
When using `endpoint: "http://${env:PROMETHEUS_ENDPOINT}:9090/api/v1/write" `
in otel-config.yaml in the **prometheusremotewrite** exporter, the environment variable is not resolved, while it gets resolved when using: `endpoint: "http://${PROMETHEUS_ENDPOINT}:9090/api/v1/write"`

**Steps to reproduce**
```json

```

**What did you expect to see?**
I expect it gets resolved when using ${env:PROMETHEUS_ENDPOINT} as part of the confmap expand feature.

### Collector version

v0.69.0

### Environment information

**Environment**
Windows 2022 Server

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    collection_interval: 1s  
    scrapers:
      cpu:

exporters:
  prometheusremotewrite:
    # endpoint: "http://${PROMETHEUS_ENDPOINT}:9090/api/v1/write"
    endpoint: "http://${env:PROMETHEUS_ENDPOINT}:9090/api/v1/write"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: []
      exporters: [prometheusremotewrite]
```

### Log output

```shell
**Error**
`2023-01-11T14:27:36.154-0800    error   exporterhelper/queued_retry.go:394      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: Permanent error: Post \"http://:9090/api/v1/write\": dial tcp :9090: connectex: No connection could be made because the target machine actively refused it.", "dropped_items": 96}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector@v0.69.0/exporter/exporterhelper/queued_retry.go:394
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
        go.opentelemetry.io/collector@v0.69.0/exporter/exporterhelper/metrics.go:136
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
        go.opentelemetry.io/collector@v0.69.0/exporter/exporterhelper/queued_retry.go:205
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
        go.opentelemetry.io/collector@v0.69.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61`
```
