### ISSUE TITLE
[exporter/datadog] metrics exporter: 413 - Request Entity Too Large 

### ISSUE THREAD

**Issue by hanikesn** [open-telemetry/opentelemetry-collector-contrib#17566]
### Component(s)

exporter/datadog

### What happened?

After updating to the latest collector, which uses the native [datadog client](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16776) we're seeing a lot of failures to export metrics with: `max elapsed time expired 413 Request Entity Too Large`

### Collector version

0.69.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by songy23** [comment]
Hi @hanikesn are you batching the metrics? If so can you share the config of your batch processor?

**Comment by hanikesn** [comment]
> Hi @hanikesn are you batching the metrics? If so can you share the config of your batch processor?

We have a batch processor with the following configuration:
```
  batch:
    timeout: 1s
```

**Comment by songy23** [comment]
This probably has to do with the V2 metrics data model change, e.g. in V1 host names are plain strings while in V2 they are in a nested proto message.

Two possible mitigations:
1. Set a smaller threshold for `send_batch_size` in [batchprocessor](https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor), this should hopefully reduce the payload size sent to datadogexporter.
2. If the above doesn't work, fall back to using the Zorkian library by adding CLI flag --feature-gates=-exporter.datadogexporter.metricexportnativeclient in your docker file or when starting the collector

**Comment by hanikesn** [comment]
I configured the batch settings like [here](https://docs.datadoghq.com/opentelemetry/otel_collector_datadog_exporter/?tab=onahost#2-configure-the-datadog-exporter):
```
  batch:
    # Datadog APM Intake limit is 3.2MB. Let's make sure the batches do not
    # go over that.
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s
```
And still getting the same error.

**Comment by songy23** [comment]
From https://docs.datadoghq.com/api/latest/metrics/#submit-metrics:

- In V2 metrics export the payload size limit is 500KB uncompressed, or 5MB after decompression
- In V1 the limit is 3.2MB uncompressed, or 62MB after decompression

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16776 switched metric export to call V2 APIs (which is recommended) instead of V1. While the [doc] you mentioned (https://docs.datadoghq.com/opentelemetry/otel_collector_datadog_exporter/?tab=onahost#2-configure-the-datadog-exporter) still refers to the V1 limit. 

Can you try further lowering the `send_batch_size` for datadog exporter?  You might want to have a separate batch processor dedicated for datadog exporter if other exporters expect a larger batch size, e.g.
```
processors:
  batch:
    timeout: 1s
  batch/2:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s
...
service:
  pipelines:
    metrics:
      receivers: ...
      processors: [batch/2]
      exporters: [datadog]
```
