### ISSUE TITLE
Ability to propagate metric data labels to resource attributes

### ISSUE THREAD

**Issue by Sprakhar97** [open-telemetry/opentelemetry-collector-contrib#17560]
### Is your feature request related to a problem? Please describe.

1. I have a use case where I need to do the following:

Prometheus receiver is configured to inject Pod's namespace and name into collected metrics:
```
relabel_configs:
- source_labels: [__meta_kubernetes_pod_uid]
  action: replace
  target_label: kubernetes_pod_uid
- source_labels: [__meta_kubernetes_pod_name]
  action: replace
  target_label: kubernetes_pod_name
```
2. I need to transform these two labels into resource attributes as defined in

 AttributeK8sPodUid          = "k8s.pod.uid" 
 AttributeK8sPod                = "k8s.pod.name"

### Describe the solution you'd like

It may make sense to support this in Resource Processor, Attributes Processor or some other core component, since it seems like a generic functionality.
