### ISSUE TITLE
Example RBAC configuration for k8sprocessor 

### ISSUE THREAD

**Issue by Jammicus** [open-telemetry/opentelemetry-collector-contrib#177]
Hi everyone, 

We're currently trying to implement the K8s processor in our agent pods, but seem to have hit a hurdle.  When checking the logs to the pods we are seeing the following: 

`pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Pod: Get "https://172.20.0.1:443/api/v1/pods?limit=500&resourceVersion=0": Forbidden`

Adding the following Service Account, ClusterRole and Clusterrolebinding to the pod does not seem to have resolved the issue:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentracing-agent

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentracing-agent
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - daemonsets
  - deployments
  - endpoints
  - events
  - namespaces
  - nodes
  - pods
  - replicasets
  - services
  - statefulset
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opentracing-agent
subjects:
- kind: ServiceAccount
  name: opentracing-agent
  namespace: tracing
roleRef:
  kind: ClusterRole
  name: opentracing-agent
  apiGroup: "rbac.authorization.k8s.io"

```

Is there an example of the required RBAC configuration? Below is some additional information if its of use. I've had a look around 

Many thanks

* K8s version (EKS): v1.14.9-eks-502bfb
* Deployed using a Daemonset. 
* Service account seems to have permission to access the API:
```
kubectl auth can-i get pods --as=system:serviceaccount:tracing:opentracing-agent
  yes 
```
* Service accounts token is correctly mounted on the pod and in /var/run/secrets/kubernetes.io/serviceaccount
* K8sprocessor config:
```
processors:
  k8s_tagger:
    filter:
      node_from_env_var: NODE_NAME
    passthrough: false
    extract:
      metadata:
        - podName
```

**Comment by ocervell** [comment]
The following config has worked for me:

```
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
```
