### ISSUE TITLE
[awsxrayexporter] Allow aliases for X-Ray indexed attributes

### ISSUE THREAD

**Issue by adamantike** [open-telemetry/opentelemetry-collector-contrib#1781]
**Is your feature request related to a problem? Please describe.**

Currently, with the implementation of #808, resource and span attributes can be listed to be sent to X-Ray as annotations instead of metadata, which allows filtering by them in X-Ray. An example configuration is:

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50

exporters:
  awsxray:
    indexed_attributes:
      - otel.resource.service.environment

service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      processors: [batch/traces]
      exporters: [awsxray]
```

With this configuration, a filter like `annotation.otel_resource_service_environment = "prod"` works in X-Ray. However, (AFAIK) it's not possible to have a simpler annotation like `annotation.environment`, unless an `environment` attribute is set at the Span level (which is something not done by default in the instrumentations).

**Describe the solution you'd like**

Having a separate config parameter like `indexed_attribute_map`, which is a dictionary where keys are the attribute names, and values are the X-Ray annotation names, will allow users to indicate custom names that simplify filtering in X-Ray.

```
exporters:
  awsxray:
    indexed_attribute_map:
      - otel.resource.service.environment: environment
```

The `indexed_attributes` parameter is still useful for scenarios where a custom name is not needed.

A few design decisions that must be considered:
* Whether the keys in `indexed_attribute_map` include the `otel.resource.` prefix ([which is added by the exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b297bb5db94c17d7c16b379bf998e4e5b1c671ca/exporter/awsxrayexporter/translator/segment.go#L355)) and should indicate the attribute name before/after the execution of `fixAnnotationKey()` (e.g. `otel.resource.service.environment` or `otel_resource_service_environment`)
* Whether possible annotation name collisions will be evaluated on startup, to avoid shadowing other annotations.
