### ISSUE TITLE
[pkg/stanza] time_parser "layout" Format - Missing Documentation Link

### ISSUE THREAD

**Issue by Dylan-M** [open-telemetry/opentelemetry-collector-contrib#17842]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

The Stanza `time_parser` does not include any links out to the formatting of the layout.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.69.0/pkg/stanza/docs/operators/time_parser.md

This is the link that is in other places
https://github.com/observiq/ctimefmt/blob/master/ctimefmt.go#L63

It would be nice to get this added to the document. If I have time, I'll submit a PR upstream, but I wanted to get this in here before I forget again.

**Comment by Dylan-M** [comment]
It might be worth turning that into a proper document as well, rather than linking to source code comments.

**Comment by djaglowski** [comment]
There is a link from [timestamp.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e3d2bd5041ffa8ab7eb1404420d9cdb46f0e051e/pkg/stanza/docs/types/timestamp.md?plain=1#L148). The `time_parser` is the standalone operator version of the same and has a link to `timestamp.md` for full details.

**Comment by djaglowski** [comment]
Closing based on cited link.

**Comment by mvillafuertem** [comment]
why I get errors using time_parser? 

```yaml
- type: json_parser
  id: parser-json-timestamp-gotime
  output: noop
  timestamp:
    parse_from: attributes.timestamp
    layout_type: gotime
    layout: '%Y-%m-%dT%H:%M:%S.%L%z'

- type: json_parser
  id: parser-json-timestamp-strptime
  output: noop
  timestamp:
    parse_from: attributes.timestamp
    layout_type: strptime
    layout: '%Y-%m-%dT%H:%M:%S.%f%z'

```


```

Aug 16 18:03:12 ip-10-0-0-1 otelcol-contrib[10695]: 2024-08-16T18:03:12.887Z        error        reader/reader.go:140        process: %w        {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/var/log/mylog.log", "error": "time parser: parsing time \"2024-08-16T18:03:12.726+00:00\" as \"%Y-%m-%dT%H:%M:%S.%L%z\": cannot parse \"2024-08-16T18:03:12.726+00:00\" as \"%Y-%m-%dT%H:%M:%S.%L%z\""}

```
