### ISSUE TITLE
 Logstransform processor not availabe in latest docker images

### ISSUE THREAD

**Issue by fspiessaignx** [open-telemetry/opentelemetry-collector-contrib#17861]
## Description
According to the Release Changes the [Logstransform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/logstransformprocessor) should be part of the latest distribution of opentelemetry-collector-contrib. Since it is not defined in the [components](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/components/components.go) file, people are not able to use it in the moment.
## Steps to Reproduce
Add logstransform processor to a collector config using the latest docker image.
## Expected Result
A running collector which is able to parse the json body.
## Actual Result
Collector fails during startup because _logstranfom_  is not a valid processor.

### Collector version

v0.69.0 

## Environment
OS: GKE Kubernetes Cluster (v1.22.15-gke.2500) with Linux nodes 
Deployed by the [OpenTelemetry Kubernetes Operator](https://github.com/open-telemetry/opentelemetry-operator)
Collector Image: otel/opentelemetry-collector-contrib:0.69.0

### OpenTelemetry Collector configuration

```yaml
...
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.69.0
  env:
    - name: CLUSTER_NAME
      value: ...
    - name: KUBE_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
  serviceAccount: otel-collector
  config: |
    receivers:
      googlecloudpubsub:
        project: <project>
        subscription: <subscription>
        encoding: raw_text

    processors:
      logstransform:
        operators:
          - type: json_parser
            parse_from: body.message
...
```

### Log output

```shell
2023/01/19 08:45:30 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'processors': unknown type: "logstransform" for id: "logstransform" (valid values: [deltatorate k8sattributes experimental_metricsgeneration probabilistic_sampler redaction routing batch filter groupbytrace resourcedetection span memory_limiter attributes datadog metricstransform resource tail_sampling transform cumulativetodelta groupbyattrs servicegraph spanmetrics])
```

### Additional context

I think we need to add the logstranform processor to [components.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/components/components.go).
