### ISSUE TITLE
googlecloudexporter not compiling above v0.61.0

### ISSUE THREAD

**Issue by ljulliar** [open-telemetry/opentelemetry-collector-contrib#17899]
### Component(s)

exporter/googlecloud

## Description
googlecloudexporter will not compile with revision higher than 0.61.0

## Steps to Reproduce
Use the local build process from https://github.com/GoogleCloudPlatform/opentelemetry-collector-builder-sample/tree/main/build/local
Adjust version in Makefile and in builder-config.yaml. Up to 0.61.0 the compilation will work 

## Expected Result
The custom version of otelcol should compile

## Actual Result
If you use any version higher than 0.61.0 you'll always obtain the same error and the compilation will stop (see below)

### Collector version

0.63.0+

## Environment
OS: Debian 12
Compiler(if manually compiled):  go version go1.19.4 linux/amd64

### OpenTelemetry Collector configuration

```yaml
receivers:
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.63.0

processors:
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.63.0
  - import: go.opentelemetry.io/collector/processor/memorylimiterprocessor
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.63.0

exporters:
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter v0.63.0
```

### Log output

```shell
go: finding module for package go.opentelemetry.io/collector/config
go: finding module for package go.opentelemetry.io/collector/service/servicetest
go.opentelemetry.io/collector/cmd/builder imports
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter imports
	go.opentelemetry.io/collector/config: module go.opentelemetry.io/collector@latest found (v0.69.1), but does not contain package go.opentelemetry.io/collector/config
go.opentelemetry.io/collector/cmd/builder tested by
	go.opentelemetry.io/collector/cmd/builder.test imports
	go.opentelemetry.io/collector/config/configtest: module go.opentelemetry.io/collector@latest found (v0.69.1), but does not contain package go.opentelemetry.io/collector/config/configtest
go.opentelemetry.io/collector/cmd/builder imports
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter tested by
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter.test imports
	go.opentelemetry.io/collector/service/servicetest: module go.opentelemetry.io/collector@latest found (v0.69.1), but does not contain package go.opentelemetry.io/collector/service/servicetest
```
```


### Additional context

_No response_

**Comment by damemi** [comment]
It looks like the configtest package was removed in v0.65.0 from the collector: https://github.com/open-telemetry/opentelemetry-collector/pull/6542

In this case, the collector builder seems to be trying to import from latest (v0.69.1) even though you have v0.63.0 specified, so that's the conflict. I'm not sure why that is, but I'll take a deeper look and try reproducing

**Comment by damemi** [comment]
@ljulliar in your builder config, the loggingexporter import is wrong for v0.63.0. When I update to the following, it works:
```yaml
receivers:
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.63.0

processors:
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.63.0
  - import: go.opentelemetry.io/collector/processor/memorylimiterprocessor
    gomod: go.opentelemetry.io/collector v0.63.0
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.63.0

exporters:
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.63.0
  - import: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter
    gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter v0.63.0
```
