### ISSUE TITLE
New component: syslog exporter

### ISSUE THREAD

**Issue by rnishtala-sumo** [open-telemetry/opentelemetry-collector-contrib#17982]
### The purpose and use-cases of the new component

In order to send events from a device to a remote syslog server, one needs a syslog agent. Most Linux operating systems ship with a syslog agent and if one is not available, one can be easily installed. The two most common syslog agents used on Linux systems today are rsyslog and syslog-ng

The syslog protocol is the standard for remote message logging. Syslog agents are flexible enough to handle more than just logs messages, for example monitoring configuration files, JSON files, and SNMP traps.

OpenTelemetry seems to already have a syslog receiver, a syslog exporter akin to an agent would be useful to send logs/events to a third party syslog server.

### Example configuration for the component

- endpoint (address of the syslog server (default: 127.0.0.1))
- transport (transport to use (tcp|udp) (default: udp))
- port (514/1514)

```yaml
exporters:
  syslog:
    protocols:
      tcp:
        endpoint: 0.0.0.0
        port: 514
```

### Telemetry data types supported

- logs
- events

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

**Comment by rnishtala-sumo** [comment]
Hello there, one of our customers want the syslog exporter/forwarder for otel and contributing this to upstream seemed like the way to go. Please let me know any initial thoughts/suggestions and interest in being a sponsor.

**Comment by atoulme** [comment]
Thank you for your interest. Please bring this to the next SIG meeting for discussion and to find a sponsor. Feel free to engage on the CNCF slack as well. Please see this document to participate in the SIG meeting: https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit

**Comment by djaglowski** [comment]
This is an interesting proposal and would likely be a valuable addition to the collector. However, I have a few questions:
- Will this support the same protocols as the syslog receiver, namely `rfc3164` and `rfc5424`?
- What is the mapping from OTel's log data model to syslog? I expect this would vary by rfc protocol.
- Are you willing to ensure compatibility with the syslog receiver? This may involve making sensible updates to that receiver as necessary to ensure we are able to use the collector as a syslog forwarder. That is, we will need to ensure that the exporter & receiver have equivalent capabilities and can preserve data integrity when used together.

**Comment by astencel-sumo** [comment]
> Will this support the same protocols as the syslog receiver, namely rfc3164 and rfc5424?

Yes, this is the intended outcome.

> What is the mapping from OTel's log data model to syslog? I expect this would vary by rfc protocol.
> Are you willing to ensure compatibility with the syslog receiver?

Yes, we want to ensure compatibility with the Syslog receiver. The assumption is that data ingested with the [Syslog receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.70.0/receiver/syslogreceiver) can be exported by the Syslog exporter and that the exporter's output is equal to the receiver's input (assuming both use the same syslog protocol, for example both use `rfc3164`). I suppose this covers what you describe as "using the collector as syslog forwarder", right? I agree that this requires that both Syslog receiver and exporter evolve in sync.

@rnishtala-sumo please keep me honest here.

**Comment by djaglowski** [comment]
>  I suppose this covers what you describe as "using the collector as syslog forwarder", right?

👍 You said it much better than I did.

**Comment by djaglowski** [comment]
I'm willing to sponsor this based on @astencel-sumo's responses.

**Comment by djaglowski** [comment]
Closed by #19647

**Comment by oppokui** [comment]
How can I forward kubernetes pod logs to syslog exporter? The k8s log is not syslog format. 

I tried the following pipeline, it didn't work. I didn't find any syslog processor or formatter too.

```
    exporters:
      syslog:
        endpoint: 23.21.46.218
        network: udp
        port: 5140
        protocol: rfc5424
        retry_on_failure:
          enabled: true
          initial_interval: 10s
          max_elapsed_time: 150s
          max_interval: 40s
        sending_queue:
          enabled: true
          num_consumers: 20
          queue_size: 10000
        timeout: 1s
    receivers:
      filelog:
        exclude: []
        include:
        - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
    service:
      extensions: {}
      pipelines:
        logs:
          exporters:
          - syslog
          receivers:
          - filelog
```

Any suggestion?
