### ISSUE TITLE
Can't rename `instance` label nor copy it with attributes and metricstransform processors

### ISSUE THREAD

**Issue by fracasula** [open-telemetry/opentelemetry-collector-contrib#18028]
### Component(s)

processor/attributes, processor/metricstransform

## Description

I'm trying to rename (or even a copy would be fine) the `instance` label. I'm using the Go SDK to send a counter to the OpenTelemetry collector and I'm using `semconv.ServiceInstanceIDKey` to set the `instance` label.

The label is set correctly but then I'm unable to access it from the `attributes` and `metricstransform` processors.

## Steps to Reproduce

1. send metric with the Go SDK making sure that the resource used when initializing the meter provider has the `semconv.ServiceInstanceIDKey` set to something
2. verify that the `instance` label is set when hitting the OTel collector exporter endpoint for Prometheus
3. enable either the `metricstransform` processor or the `attributes` processor to try rename or copy the metric

## Expected Result

I'd expect to see a copy of the label as desired or renamed but nothing happens. It works with other labels, not with `instance`.

## Actual Result

The copy or the rename does not happen with the `instance` label specifically.

### Collector version

otel/opentelemetry-collector-contrib:0.68.0

## Environment

Deployed on Kubernetes with the official Helm chart.

### OpenTelemetry Collector configuration

```yaml
nameOverride: ""
fullnameOverride: ""

# Valid values are "daemonset", "deployment", and "statefulset".
mode: "deployment"

# Handles basic configuration of components that
# also require k8s modifications to work correctly.
# .Values.config can be used to modify/add to a preset
# component configuration, but CANNOT be used to remove
# preset configuration. If you require removal of any
# sections of a preset configuration, you cannot use
# the preset. Instead, configure the component manually in
# .Values.config and use the other fields supplied in the
# values.yaml to configure k8s as necessary.
presets:
  # Configures the collector to collect logs.
  # Adds the filelog receiver to the logs pipeline
  # and adds the necessary volumes and volume mounts.
  # Best used with mode = daemonset.
  logsCollection:
    enabled: true
    includeCollectorLogs: true
    # Enabling this writes checkpoints in /var/lib/otelcol/ host directory.
    # Note this changes collector's user to root, so that it can write to host directory.
    storeCheckpoints: false
  # Configures the collector to collect host metrics.
  # Adds the hostmetrics receiver to the metrics pipeline
  # and adds the necessary volumes and volume mounts.
  # Best used with mode = daemonset.
  hostMetrics:
    enabled: false
  # Configures the Kubernetes Processor to add Kubernetes metadata.
  # Adds the k8sattributes processor to all the pipelines
  # and adds the necessary rules to ClusteRole.
  # Best used with mode = daemonset.
  kubernetesAttributes:
    enabled: false
  # Configures the Kubernetes Cluster Receiver to collect cluster-level metrics.
  # Adds the k8s_cluster receiver to the metrics pipeline
  # and adds the necessary rules to ClusteRole.
  # Best used with mode = deployment or statefulset.
  clusterMetrics:
    enabled: false
  # Configures the collector to collect Kubelet metrics.
  # Adds the kubeletstats receiver to the metrics pipeline
  # and adds the necessary rules to ClusteRole.
  # Best used with mode = daemonset.
  kubeletMetrics:
    enabled: false

configMap:
  # Specifies whether a configMap should be created (true by default)
  create: true

# Base collector configuration.
# Supports templating. To escape existing instances of {{ }}, use {{` <original content> `}}.
# For example, {{ REDACTED_EMAIL }} becomes {{` {{ REDACTED_EMAIL }} `}}.
config:
  exporters:
    logging: {}
    prometheus:
      endpoint: 0.0.0.0:9464
      resource_to_telemetry_conversion:
        enabled: true
  extensions:
    # The health_check extension is mandatory for this chart.
    # Without the health_check extension the collector will fail the readiness and liveliness probes.
    # The health_check extension can be modified, but should never be removed.
    health_check: {}
    memory_ballast: {}
  processors:
    batch: {}
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter: null
    attributes/upsert:
      actions:
        - key: instanceName
          action: upsert
          from_attribute: instance
        - key: someOtherTest
          action: upsert
          from_attribute: foo
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
  service:
    telemetry:
      logs:
        level: "info" #debug
      metrics:
        address: 0.0.0.0:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      logs:
        exporters:
          - logging
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - prometheus
          - logging
        processors:
          - memory_limiter
          - attributes/upsert
          - batch
        receivers:
          - otlp
          - prometheus

image:
  # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.68.0"
imagePullSecrets:
  - name: regcred

# OpenTelemetry Collector executable
command:
  name: otelcol-contrib
  extraArgs: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

clusterRole:
  # Specifies whether a clusterRole should be created
  create: false
  # Annotations to add to the clusterRole
  annotations: {}
  # The name of the clusterRole to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # A set of rules as documented here : https://kubernetes.io/docs/reference/access-authn-authz/rbac/
  rules: []
  # - apiGroups:
  #   - ''
  #   resources:
  #   - 'pods'
  #   - 'nodes'
  #   verbs:
  #   - 'get'
  #   - 'list'
  #   - 'watch'

  clusterRoleBinding:
    # Annotations to add to the clusterRoleBinding
    annotations: {}
    # The name of the clusterRoleBinding to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

podSecurityContext: {}
securityContext: {}

nodeSelector: {}
tolerations: []
affinity: {}

# Allows for pod scheduler prioritisation
priorityClassName: ""

extraEnvs: []
extraVolumes: []
extraVolumeMounts: []

# Configuration for ports
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
  prometheus:
    enabled: true
    containerPort: 9464
    servicePort: 9464
    hostPort: 9464
    protocol: TCP
  metrics:
    # The metrics port is disabled by default. However you need to enable the port
    # in order to use the ServiceMonitor (serviceMonitor.enabled) or PodMonitor (podMonitor.enabled).
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

# Resource limits & requests. Update according to your own use case as these values might be too low for a typical deployment.
resources:
  limits:
    cpu: 256m
    memory: 2048Mi

podAnnotations: {}

podLabels: {}

# Host networking requested for this pod. Use the host's network namespace.
hostNetwork: false

# Pod DNS policy ClusterFirst, ClusterFirstWithHostNet, None, Default, None
dnsPolicy: ""

# only used with deployment mode
replicaCount: 1

annotations: {}

# List of extra sidecars to add
extraContainers: []

# List of init container specs, e.g. for copying a binary to be executed as a lifecycle hook.
initContainers: []

# Pod lifecycle policies.
lifecycleHooks: {}

service:
  type: ClusterIP
  # type: LoadBalancer
  # loadBalancerIP: 1.2.3.4
  annotations: {}

ingress:
  enabled: false

  # Additional ingresses - only created if ingress.enabled is true
  # Useful for when differently annotated ingress services are required
  # Each additional ingress needs key "name" set to something unique
  additionalIngresses: []

podMonitor:
  # The pod monitor by default scrapes the metrics port.
  # The metrics port needs to be enabled as well.
  enabled: false
  metricsEndpoints:
    - port: metrics
      # interval: 15s

  # additional labels for the PodMonitor
  extraLabels: {}
  #   release: kube-prometheus-stack

serviceMonitor:
  # The service monitor by default scrapes the metrics port.
  # The metrics port needs to be enabled as well.
  enabled: false
  metricsEndpoints:
    - port: metrics
      # interval: 15s

  # additional labels for the ServiceMonitor
  extraLabels: {}
  #  release: kube-prometheus-stack

# PodDisruptionBudget is used only if deployment enabled
podDisruptionBudget:
  enabled: false
#   minAvailable: 2
#   maxUnavailable: 1

# autoscaling is used only if deployment enabled
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

rollout:
  rollingUpdate: {}
  # When 'mode: daemonset', maxSurge cannot be used when hostPort is set for any of the ports
  # maxSurge: 25%
  # maxUnavailable: 0
  strategy: RollingUpdate

prometheusRule:
  enabled: false
  groups: []
  # Create default rules for monitoring the collector
  defaultRules:
    enabled: false

  # additional labels for the PrometheusRule
  extraLabels: {}

statefulset:
  # volumeClaimTemplates for a statefulset
  volumeClaimTemplates: []
  podManagementPolicy: "Parallel"
```

### Additional context

For example I send a metric like this:

```go
res, err := resource.Merge(
	resource.Default(),
	resource.NewWithAttributes(semconv.SchemaURL, 
		semconv.ServiceNameKey.String("my-fancy-service"),
		semconv.ServiceVersionKey.String("0.0.1"),
		semconv.ServiceInstanceIDKey.String("my-pod-name-0")), // THIS CREATES THE "instance" LABEL!!!
)

// ... some other code in between

test, err := mp.Meter("some-test").SyncInt64().Counter("test")
if err != nil {
	log.Printf("OpenTelemetry counter failed: %v", err)
	return 1
}

ticker := time.NewTicker(1 * time.Second)
for {
	select {
	case <-ctx.Done():
		log.Println("done")
		return 0
	case <-ticker.C:
		log.Println("tick")
		test.Add(ctx, 1, attribute.String("foo", "bar"))
	}
}
```

As you can see I'm setting an attribute `foo=bar`.

Then in the collector configuration I use the `attributes` processor like this:

```yaml
    attributes/upsert:
      actions:
        - key: instanceName
          action: upsert
          from_attribute: instance
        - key: someOtherTest
          action: upsert
          from_attribute: foo
```

The metric as it is visible on the Prometheus exporter looks like this:

```
test{foo="bar",instance="my-pod-name-0",job="my-fancy-service",service_instance_id="my-pod-name-0",service_name="my-fancy-service",service_version="0.0.1",someOtherTest="bar",telemetry_sdk_language="go",telemetry_sdk_name="opentelemetry",telemetry_sdk_version="1.11.2"} 3
```

As you can see the second rule worked because `someOtherTest="bar"` is there. Unfortunately the 1st rule didn't apply given that I cannot see `instanceName="my-pod-name-0"`.

Client code with the Go SDK available [here](https://github.com/rudderlabs/rudder-server/blob/chore.otel-2/cmd/otel/main.go)https://github.com/rudderlabs/rudder-server/blob/chore.otel-2/cmd/otel/main.go.
