### ISSUE TITLE
[tailsampling] Error sending late arrived spans. Failed to find dimensions.

### ISSUE THREAD

**Issue by edenkoveshi** [open-telemetry/opentelemetry-collector-contrib#18025]
### Component(s)

processor/tailsampling

## Description
Hi,
I am using the OpenTelemetry collector with the tail sampling processor (along some other processors), deployed with the OpenTelemetry Kuberentes Operator.
Traces generated mainly using the auto instrumentation feature.
I am receiving the following warnings:
`tailsamplingprocessor@v0.66.0/processor.go:379 Error sending late arrived spans to destination {"kind": "processor", "name": "tail_sampling", "pipeline": "traces", "policy": "error" , "error": "value not found in metricsKeyToDimensions cache by key \"**some-service**\x00some-operation\x00\SPAN_KIND_INTERNAL\x00STATUS_CODE_UNSET\". failed to build metrics: failed to find dimensions for \"**another-service**\u0000**another-service-2**\", "errorCauses": [{"error":"value not found in metricsKeyToDimensions cache by key \"**some-service**\x00some-operation\x00\SPAN_KIND_INTERNAL\x00STATUS_CODE_UNSET\"} ,{"error": "failed to build metrics: failed to find dimensions for \"**another-service**\u0000**another-service-2**\""}] } `

(The ** are for emphasizing, they do not appear in the original log)

To my understanding, the processor fails while generating its` metrics, though I am not sure what dimensions the traces must have so it would work properly.

I have had similar errors with `spanmetrics` and `servicegraph` processor but they were fixed when I have upgraded to 0.66.0

The collector is deployed behind another collector that serves as a load balancer as documeneted [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/88cada9fabf1612bf13c6438631d900daf1a9827/processor/tailsamplingprocessor#scaling-collectors-with-the-tail-sampling-processor). However, the error seems to occur even when removing the load balancer.

Here is the processor configuration:

```yaml
      policies:
      [
          {
            name: error
            type: status_code,
            status_code: {status_codes: [ERROR, UNSET]}
          },
          {
            name: latency
            type: latency,
            latency: {threshold_ms: 200 }
          },
          {
            name: db-connection,
            type: string_attribute,
            string_attribute: {key: db.connection_string , values: [.*], enabled_regex_matching: true}
          },
          {
            name: filter-health-checks,
            type: string_attribute,
            string_attribute: {key: http.url , values: [ \/health ], enabled_regex_matching: true, invert_match: true}
          },
          {
            name: probablistic,
            type: probabilistic,
            probabilistic: {sampling_percentage: 25}
          },
    ]
``` 

### Collector version

contrib 0.66.0

## Environment
Openshift 4.10
Deployed with OpenTelemetry operator 0.66.0
Collector contrib 0.66.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
  otlp/dummy:
processors:
  batch:
  servicegraph:
    metrics_exporter: prometheus
    dimensions: []
  spanmetrics:
    metrics_exporter: prometheus
    dimensions: []
  tailsampling: described above
exporters:
  jaeger:
    endpoint: my-jaeger-collector
  otlp:
    endpoint: some-other-otlp-collector
  logging:
  prometheus:
    endpoint: "0.0.0.0:8889"
extensions:
  health_check:
service:
  extensions:
   - health_check
  pipelines:
   traces:
     receivers:
     - otlp
     processors:
     - tail_sampling
     - spanmetrics
     - servicegraph
     - batch
    exporters:
    - logging
    - jaeger
    - otlp
  metrics:
   receivers: [otlp,otlp/dummy]
   exporters: [prometheus]
 telemetry:
  metrics:
  logs:
```
