### ISSUE TITLE
Elastic exporter discards exception data

### ISSUE THREAD

**Issue by paulgrav** [open-telemetry/opentelemetry-collector-contrib#1803]
**Describe the bug**

I have instrumented a JaxRS Java app with opentelemetry-java-instrumentation. opentelemetry-collector-contrib is configured to receive `otlp` and to export `elastic` + `loggin`. Elastic-APM is configured to output to console and Kibana.

I can see in the logs that the the collector is receiving trace data containing expection data in the span, but the `elastic` exporter drops the exception data. The exception data is not visible in ElasticAPM’s stdout nor is it persisted to Elasticsearch.

**Steps to reproduce**

1. Instrument a Java app with `opentelemetry-java-instrumentation`
2. Configure an opentelemetry-collector to receive `otlp` and export `logging`  and `elastic` trace data.
3. Configure ElasticAPM to output to console
4. Provoke an exception.

**What did you expect to see?**
I expect to see the stacktrace and exception details visible in ElasticAPM’s stdout and persisted to Elasticsearch (if ElasticAPM has been configured to do so).

**What did you see instead?**
JSON objects in ElasticAPM’s console output containing span details but missing the exception details.

**What version did you use?**

`opentelemetry-java-instrumentation:0.12.0`
`elastic-apm:7.10.1`
`opentelemetry-collector-contrib:0.16.0`

**What config did you use?**

otel.yaml
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
exporters:
  elastic:
    apm_server_url: "http://elastic:8200/"
  logging:
    loglevel: debug
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [elastic, logging]
```

apm-server.docker.yml (Elastic APM config)
```
apm-server:
  host: "0.0.0.0:8200"
output.console:
  enabled: true
  codec.json:
    pretty: true
    escape_html: false
```

docker-compose.yaml
```
version: '3'
services:
  otel:
    image: otel/opentelemetry-collector-contrib:0.16.0
    volumes:
      - ./docker/otel.yml:/etc/otel/config.yaml
    ports:
      - "55680:55680"
  elastic:
    image: docker.elastic.co/apm/apm-server:7.10.1
    volumes:
      - "./docker/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro"
  web:
    build: .
```

**Environment**

I’m using macOS 11.0.1 (20B29) 

Below is the output from 

OS: Linux 4.19.121-linuxkit

**Additional context**

Console output showing combined output from otel and elastic:

https://gist.github.com/paulgrav/96f1f1a21e92bf96cfd54db95d7b2559
