### ISSUE TITLE
[receiver/hostmetrics/scrapers/network] system.network.io always send same values

### ISSUE THREAD

**Issue by ljulliar** [open-telemetry/opentelemetry-collector-contrib#18033]
### Component(s)

receiver/hostmetrics

## Description
I'm capturing various metrics on my Linux (Ubuntu 16.04 LTS) distro. All of the metrics are fine except the network metrics and  most specifically the system.network.io. The receive / transmit values I collect are always the same values. They remain constant over time.

Is there any way I could log the actual values that are transferred to the processors and the exporter ?

## Steps to Reproduce
Use the config.ymal file below and run otelcol

## Expected Result
I would expect the TX and RX bytes value to increase over time

## Actual Result
I always get the same values

### Collector version

0.61

## Environment
OS: Ubuntu LTS 16.04
Compiler(if manually compiled): go 1.19

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    collection_interval: 1m
    root_path: /
    scrapers:
      memory:

# Divide load by number of cpus
      load:
        cpu_average: true
        metrics:
          system.cpu.load_average.1m:
            enabled: true
          system.cpu.load_average.5m:
            enabled: false
          system.cpu.load_average.15m:
            enabled: false

    network:
        include:
          interfaces: [enp1s0f0]
          match_type: strict
        metrics:
          system.network.connections:
            enabled: false
          system.network.io:
            enabled: true
          system.network.dropped:
            enabled: false
          system.network.errors:
            enabled: false
          system.network.packets:
            enabled: false

exporters:
  googlecloud:
    project: npt-monitoring
    retry_on_failure:
      enabled: false
    log:
      default_log_name: opentelemetry.io/bigfish-exported-log

processors:
  memory_limiter:
    check_interval: 2s
    limit_mib: 1000
    spike_limit_mib: 200
#    limit_percentage: 65
#    spike_limit_percentage: 20
  batch:
  resourcedetection:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [googlecloud]
```
