### ISSUE TITLE
[receiver/mongodbatlas] default collection interval results some metrics being not populated

### ISSUE THREAD

**Issue by egeturgay** [open-telemetry/opentelemetry-collector-contrib#18032]
### Component(s)

receiver/mongodbatlas

## Description

Currently, this receiver is taking the default receiver collection interval from the scraper library which is set to 1 minute.

Mongo Atlas API seems to provide null values for metrics if the start/end time window is 1 minute for these metrics below.
Increasing the collection interval to 3 minutes seem to allow these values to be populated correctly.

Could you please consider making the default to be set to 3 minutes and document the "collection_interval" setting for the receiver? If increasing the default is not ideal, It might worth adding this as a note in the receiver document as It took us considerable time to troubleshoot this and find how to override the default interval.

Listed metrics not having values if a low interval is set:

mongodbatlas.disk.partition.latency.average
mongodbatlas.process.asserts
mongodbatlas.process.cache.io
mongodbatlas.process.cpu.children.normalized.usage.average
mongodbatlas.process.cpu.children.usage.average
mongodbatlas.process.cpu.normalized.usage.average
mongodbatlas.process.cpu.usage.average
mongodbatlas.process.db.document.rate
mongodbatlas.process.db.operations.rate
mongodbatlas.process.db.operations.time
mongodbatlas.process.db.query_executor.scanned
mongodbatlas.process.db.query_targeting.scanned_per_returned
mongodbatlas.process.network.io
mongodbatlas.process.network.requests
mongodbatlas.process.page_faults
mongodbatlas.system.cpu.normalized.usage.average
mongodbatlas.system.cpu.usage.average
mongodbatlas.system.network.io.average
mongodbatlas.system.paging.io.average
## Steps to Reproduce
Monitoring for metrics via fileexporter should suggest a metric like "mongodbatlas.process.db.document.rate" is not consistently being exported as the other metrics. You should also be able to see this by hitting the mongo API process metrics and having the start/end time set 1 minute apart.

## Expected Result
All metrics to be populated with values

## Actual Result
Only 31 metrics are being populated out of 50 without the interval change

### Collector version

0.70

## Environment
OS: Amazon Linux

### OpenTelemetry Collector configuration

```yaml
exporters:
  file:
    path: /log/exporter.log
receivers:
  mongodbatlas/redacted:
    logs:
      enabled: false
      projects:
      - collect_audit_logs: false
        name: redacted
    granularity: PT1M
    # collection_interval: 3m # this undocumented setting (in the receiver) seems to fix the problem for us
service:
  pipelines:
    metrics/mongodbatlas:
      exporters:
      - file
      receivers:
      - mongodbatlas/redacted
  telemetry:
    metrics:
      address: 0.0.0.0:8889
    logs:
      level: debug
```

### Additional context

Example output from Mongo API when the start/end (interval) is set to 1 minute
```
    "dataPoints" : [ {
      "timestamp" : "2023-01-24T16:37:35Z",
      "value" : null
    } ],
    "name" : "DOCUMENT_METRICS_RETURNED",
    "units" : "SCALAR_PER_SECOND"
  }, {
    "dataPoints" : [ {
      "timestamp" : "2023-01-24T16:37:35Z",
      "value" : null
    } ],
    "name" : "DOCUMENT_METRICS_INSERTED",
    "units" : "SCALAR_PER_SECOND"
  }
```
