### ISSUE TITLE
cumulativetodelta: initial data points are included for monotonic counters

### ISSUE THREAD

**Issue by lincolnmantracer** [open-telemetry/opentelemetry-collector-contrib#18053]
### Component(s)

processor/cumulativetodelta

### What happened?

The cumulative-to-delta processor includes the initial delta from zero to the current value as a data point:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/34b31da629f65c195125e8db07480574b181477f/processor/cumulativetodeltaprocessor/internal/tracking/tracker.go#L92-L104

Even for monotonic counters, this is counterintuitive and noisy. For example, here is what that looks like in real production data when the collector is restarted:

<img width="868" alt="Screen Shot 2023-01-26 at 1 03 13 PM" src="https://user-images.githubusercontent.com/102976597/214830848-8bb75e25-c4e0-454c-9e04-2abe302db114.png">

The processor should drop the first data point regardless of whether the dataset is monotonic or not, because the first data point can not be guaranteed to be a delta.

### Collector version

0.70.0

## Environment
OS: Ubuntu 22.04

### OpenTelemetry Collector configuration

```yaml
<snip>
processors:
  cumulativetodelta:
    include:
      metrics:
        - "bytes_total\\z"
      match_type: regexp
  metricstransform:
    transforms:
      - include: "(.*)_bytes_total\\z"
        action: insert
        new_name: "$${1}_bitrate"
        match_type: regexp
        operations:
          - action: experimental_scale_value
            # The starting unit is bytes per 5s. 0.2 * 8 = 1.6
            experimental_scale: 1.6
```
