### ISSUE TITLE
[receiver/prometheusreceiver] Pipeline names are not propagated in logs

### ISSUE THREAD

**Issue by krisztianfekete** [open-telemetry/opentelemetry-collector-contrib#18052]
### Component(s)

receiver/prometheus

## Description

Currently only the component identifier is logged, so if I have two pipelines, e.g. `metrics/target1` and `metrics/target2`, I won't be able to see which pipeline is misconfigured.

## Steps to Reproduce

Sample pipeline config:
```yaml
      pipelines:
        metrics:
          receivers:
          - otlp
          - prometheus
          processors:
          - memory_limiter
          - batch
          exporters:
          - prometheus
        metrics/target2:
          exporters:
          - prometheus
          processors:
          - memory_limiter
          - batch
          receivers:
          - prometheus/target2
```

Misconfigure the `prometheus/target2` receiver, e.g.

```yaml
    prometheus/gloo-mgmt:
      config:
        scrape_configs:
        - job_name: target2-otel
          honor_labels: true
          kubernetes_sd_configs:
          - namespaces:
              names:
              - default
            role: pod
          relabel_configs:
          - action: keep
            regex: target2|target2-ui
            source_labels:
            - __meta_kubernetes_pod_label_app
          - action: keep
            regex: true
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          - action: drop
            regex: true
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
          - action: replace
            regex: (https?)
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scheme
            target_label: __scheme__
          - action: replace
            regex: (.+)
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_path
            target_label: __metrics_path__
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels:
            - __address__
            - __meta_kubernetes_pod_annotation_prometheus_io_port
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: drop
            regex: Pending|Succeeded|Failed|Completed
            source_labels:
            - __meta_kubernetes_pod_phase
```

Notice that I am using only single `$` chars, instead of `$$`, so this will yield the error seen below.

## Expected Result

In the logs, I should see the actual name of the pipeline that is misconfigured, something like this:

```console
2023-01-17T15:48:56.089Z	warn	internal/transaction.go:121	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus/target2", "pipeline": "metrics/target2", "scrape_timestamp": 1673970536089, "target_labels": "{__name__=\"up\", app=\"target2\", instance=\":\", job=\"target2-otel\", namespace=\"target2\", pod=\"target2-7888ff5588-md59m\", pod_template_hash=\"7888ff5588\"}"}
2023-01-17T15:49:49.049Z	warn	internal/transaction.go:121	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus/target2", "pipeline": "metrics/target2", "scrape_timestamp": 1673970589047, "target_labels": "{__name__=\"up\", app=\"target2-ui\", target2=\"target2-ui\", instance=\":\", job=\"target2-otel\", namespace=\"target2\", pod=\"target2-ui-75c487f979-9nc8z\", pod_template_hash=\"75c487f979\"}"}
```

## Actual Result

I can only see metrics component identifier:

```console
2023-01-17T15:48:56.089Z	warn	internal/transaction.go:121	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus/target2", "pipeline": "metrics", "scrape_timestamp": 1673970536089, "target_labels": "{__name__=\"up\", app=\"target2\", instance=\":\", job=\"target2-otel\", namespace=\"target2\", pod=\"target2-7888ff5588-md59m\", pod_template_hash=\"7888ff5588\"}"}
2023-01-17T15:49:49.049Z	warn	internal/transaction.go:121	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus/target2", "pipeline": "metrics", "scrape_timestamp": 1673970589047, "target_labels": "{__name__=\"up\", app=\"target2-ui\", target2=\"target2-ui\", instance=\":\", job=\"target2-otel\", namespace=\"target2\", pod=\"target2-ui-75c487f979-9nc8z\", pod_template_hash=\"75c487f979\"}"}
```

### Collector version

0.67.0

## Environment
Irrelevant

### OpenTelemetry Collector configuration

```yaml
pipelines:
        metrics:
          receivers:
          - otlp
          - prometheus
          processors:
          - memory_limiter
          - batch
          exporters:
          - prometheus
        metrics/target2:
          exporters:
          - prometheus
          processors:
          - memory_limiter
          - batch
          receivers:
          - prometheus/target2
```

### Log output

```shell
2023-01-17T15:48:56.089Z	warn	internal/transaction.go:121	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus/target2", "pipeline": "metrics", "scrape_timestamp": 1673970536089, "target_labels": "{__name__=\"up\", app=\"target2\", instance=\":\", job=\"target2-otel\", namespace=\"target2\", pod=\"target2-7888ff5588-md59m\", pod_template_hash=\"7888ff5588\"}"}
2023-01-17T15:49:49.049Z	warn	internal/transaction.go:121	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus/target2", "pipeline": "metrics", "scrape_timestamp": 1673970589047, "target_labels": "{__name__=\"up\", app=\"target2-ui\", target2=\"target2-ui\", instance=\":\", job=\"target2-otel\", namespace=\"target2\", pod=\"target2-ui-75c487f979-9nc8z\", pod_template_hash=\"75c487f979\"}"}
```

### Additional context

https://cloud-native.slack.com/archives/C01N6P7KR6W/p1674213181401129
