### ISSUE TITLE
[exporter/loki] retry/queue causes any log to be blocked until queue resolves

### ISSUE THREAD

**Issue by wiardvanrij** [open-telemetry/opentelemetry-collector-contrib#18060]
### Component(s)

exporter/loki

## Description

If the queue starts building up, it blocks all other logs (that would be perfectly fine to ship) to be shipped to Loki. For example, it would be possible to stop shipping logs to Loki entirely on a ~5k logs/s collector by pushing ~100 logs/s that will get rejected by Loki (for ease of testing, using a log that has a very old timestamp and then gets retried due to this bug: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18059).

## Steps to Reproduce

1. Setup a stream of logs that are perfectly fine. Use tenant: foo
2. See that ^ gets into Loki at for example 1k logs/s
3. Setup a new stream of logs that _will_ fail. Use a different tenant: bar
4. See the processor + exporter logs sent per second drop
5. See the queue rise
6. Do not see any improvement until you 'kill' part 3, where you stop ingesting 'bad logs'.

## Expected Result

1. 'bad logs' come in queue en retry (or ideally not for 400 errors but thats a different issue)
2. Since it _should be_ grouped by tenant, this behaviour from tenant `bar`should have zero impact on tenant `foo`

## Actual Result

Completely deadlocked environment 

### Collector version

otel/opentelemetry-collector-contrib:0.66.0

## Environment
K8s

### OpenTelemetry Collector configuration

```yaml
config:
  receivers:
    fluentforward:
      endpoint: 0.0.0.0:8006
  processors:
    memory_limiter: null
    filter/excludeloki:
      logs:
        exclude:
          match_type: strict
          record_attributes:
            - key: namespace_name
              value: "loki"
    attributes/delete:
      actions:
        - key: annotations
          action: delete
        - key: container_hash
          action: delete
        - key: docker_id
          action: delete
        - key: fluent.tag
          action: delete
        - key: labels_pod-template-hash
          action: delete
    filter/excludetenants:
      logs:
        exclude:
          match_type: regexp
          record_attributes:
            - key: tenant
              value: .*.
    filter/includetenants:
      logs:
        include:
          match_type: regexp
          record_attributes:
            - key: tenant
              value: .*.
    attributes/xxxx:
      actions:
      - action: insert
        key: loki.attribute.labels
        value: stream, app, pod_name, account, cluster_name, namespace_name, region, container_name
      - action: insert
        key: loki.tenant
        value: region
    attributes/external:
      actions:
      - action: insert
        key: loki.attribute.labels
        value: account, region, team, environment, service, container_name
      - action: insert
        key: loki.tenant
        value: tenant
  exporters:
    loki:
      endpoint: redacted
  service:
    pipelines:
      logs/xxxx:
        exporters:
          - loki
        processors:
          - memory_limiter
          - filter/excludetenants
          - filter/excludeloki
          - attributes/delete
          - attributes/xxxx
          - batch
        receivers:
          - fluentforward
      logs/external:
        exporters:
          - loki
        processors:
          - memory_limiter
          - filter/includetenants
          - attributes/external
          - batch
        receivers:
          - otlp
          - fluentforward
```

### Additional context

Example visualisation: 
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/5786097/214939135-0761afd5-1632-4c3d-93d5-5737ff50d116.png">
