### ISSUE TITLE
OTTP: Add math expression for logarithm

### ISSUE THREAD

**Issue by mterhar** [open-telemetry/opentelemetry-collector-contrib#18076]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

The transform processor has the ability to do a lot of very cool stuff. One thing it can't do is log(duraion). The example has `sum([1, 2, 3, 4])` but that doesn't seem implemented.

### Describe the solution you'd like

I'd like to see the a `log(x)` function that can be called as a math expression and return the log of the number. This could be combined with rounding down or coercing to integer to make buckets with durations which can then be used for sampling.

### Describe alternatives you've considered

The existing soution is just to have a bunch of `set() where` statements. To get good resolution out of this, there would need to be a ton more and they don't seem to have an "else" option so it always evaluates all of them even if the 1st or 2nd one is the only one that would be true.

```yaml
transform:
  trace_statements:
    - context: span
      statements:
        - set(attributes["tp_duration"], end_time_unix_nano - start_time_unix_nano)
        - set(attributes["duration_bucket"], "quick") where attributes["tp_duration"] < 1000000
        - set(attributes["duration_bucket"], "slow") where attributes["tp_duration"] >= 1000000 and attributes["tp_duration"] < 5000000
        - set(attributes["duration_bucket"], "veryslow") where attributes["tp_duration"] >= 5000000
```
