### ISSUE TITLE
Grab docker label using docker/resourcedetection

### ISSUE THREAD

**Issue by medival** [open-telemetry/opentelemetry-collector-contrib#18093]
### Component(s)

processor/resourcedetection

### Is your feature request related to a problem? Please describe.

I'm using nomad to run otel, I got difficulty when trying to get the nomad label and send it to loki. 
The possible way to grab nomad label is by using docker/resourcedetection. but currently, docker/resourcedetection only supports [host.name and os.type](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/README.md#system-metadata)

Here are some label from containers that might we can use to create our own label
```
            "Labels": {
                "com.hashicorp.nomad.alloc_id": "40c4c3b8-1d1f-8f58-94ca-4efda336d62e",
                "com.hashicorp.nomad.job_id": "fabio",
                "com.hashicorp.nomad.job_name": "fabio",
                "com.hashicorp.nomad.namespace": "default",
                "com.hashicorp.nomad.node_id": "1610be6d-eea9-c4da-8d88-b945fe6e3306",
                "com.hashicorp.nomad.node_name": "t3a-small-ip-10-11-82-122-aws-client",
                "com.hashicorp.nomad.task_group_name": "fabio",
                "com.hashicorp.nomad.task_name": "fabio",
                "org.opencontainers.image.created": "2022-09-10T19:11:50Z",
                "org.opencontainers.image.revision": "ebf15c22df1a4b4b367a9043865d3fe51d5db013",
                "org.opencontainers.image.title": "fabio",
                "org.opencontainers.image.version": "1.6.2"
            }
```

### Describe the solution you'd like

Add support to use docker label in docker/resourcedetection like [vector (see vector configuration file)](https://atodorov.me/2021/07/09/logging-on-nomad-and-log-aggregation-with-loki/)

```
resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false
    attributes:
      - host.name
      - os.type
      - label.com.hashicorp.nomad.job_name
      - label.com.hashicorp.nomad.task_name
```

### Describe alternatives you've considered

-

### Additional context

-
