### ISSUE TITLE
[receiver/filelog] Support detection of headers in header-based log formats (e.g. W3C)

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#18198]
### Component(s)

receiver/filelog

### Is your feature request related to a problem? Please describe.

The [W3C log format](https://www.w3.org/TR/WD-logfile) defines its fields through a list of headers. This allows any agent that is aware of these headers to parse any W3C log, even if the headers change mid-way through the log file (as they could in e.g. Microsoft IIS logs).

The filelog receiver currently does not support parsing these fields and using them to parse CSV lines.

### Describe the solution you'd like

Ideally, there would be some way to configure the filelog receiver to recognize and pass these headers to the CSV parser so that the log lines can be parsed based on the headers.

In Stanza, this functionality was implemented in the following PRs:
* https://github.com/observIQ/stanza/pull/376
* https://github.com/observIQ/stanza/pull/404

Tangentially related:
* https://github.com/observIQ/stanza/pull/370

The way it worked was the the filelog receiver would save the header line, adding it as an attribute to each log record read from the file.

Later in the pipeline, the CSV file would be able to use this attribute as dynamic headers, which allowed the log line to be parsed based on the header attribute that the filelog receiver added.

### Describe alternatives you've considered

I haven't thought of other solutions besides the one implemented in stanza; Would love to hear other ideas!

### Additional context

Sample W3C log line, for context: 

<details>
<summary>W3C log</summary>

```
#Software: Microsoft Internet Information Services 10.0
#Version: 1.0
#Date: 2022-08-09 20:25:26
#Fields: date time s-sitename s-computername s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs-version cs(User-Agent) cs(Cookie) cs(Referer) cs-host sc-status sc-substatus sc-win32-status sc-bytes cs-bytes time-taken
2022-08-09 20:25:26 W3SVC1 <Server> 127.0.0.1 GET /query param1=1&parma2=2 80 - 127.0.0.1 HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:103.0)+Gecko/20100101+Firefox/103.0 - - localhost 404 0 2 5029 464 83
2022-08-09 20:25:29 W3SVC1 <Server> 127.0.0.1 GET /query - 80 - 127.0.0.1 HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:103.0)+Gecko/20100101+Firefox/103.0 - - localhost 404 0 2 5007 446 1
2022-08-09 20:25:32 W3SVC1 <Server> 127.0.0.1 GET / - 80 - 127.0.0.1 HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:103.0)+Gecko/20100101+Firefox/103.0 - - localhost 200 0 0 927 441 1
2022-08-09 20:25:32 W3SVC1 <Server> 127.0.0.1 GET /iisstart.png - 80 - 127.0.0.1 HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:103.0)+Gecko/20100101+Firefox/103.0 - http://localhost/ localhost 200 0 0 99937 374 7
```
</details>

**Comment by BinaryFissionGames** [comment]
> Still, I think it is necessary to assume that we are working with a header. In other words, I do not think we should solve for a case where metadata about the file is discovered and/or updated throughout the reading of the file.

I think it's fair to make the assumption that metadata would be in a header (that is, in a section before any log lines begin).

**Comment by djaglowski** [comment]
Regarding changes to the `file_input` operator - we already manage per-file metadata using a [FileAttributes](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3771eeec8bb87c4235ceddf8186d009e7054f23e/pkg/stanza/fileconsumer/attributes.go#L23) struct, so we should not have trouble managing additional per-file metadata, once isolated.

I spoke with @BinaryFissionGames offline and identified a potential solution for isolating header metadata. I've added some additional context and suggestions:

- Add a new section to the config, tentatively called `header`. This section and its associated behaviors should initially be enabled with a feature gate.
  - The presence of the `header` section in the config indicates that the user intends to parse metadata from a file header.
  - The `header` section takes inspiration from the  [`multiline` configuration](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/file_input.md#multiline-configuration), with the idea being that the user will specify a regex that matches each line in the header and fails once the header has been consumed.
  - When the operator begins reading a new file, it will evaluate the regex against each line until it fails. While the regex matches, these lines are aggregated into a single multiline entry.
    - This "header entry" will then be fed into a dedicated "header pipeline", which will parse metadata from the header entry.
    - At the end of the pipeline, the attributes of this entry are permanently associated with the file such that all records from the file will be emitted with these attributes.

Sample configuration:

```yaml
receivers:
  filelog:
    include: foo*.log
    header: 
      multiline_pattern: '...'
      metadata_operators:
        - type: regex_parser
          regex: '...'
    operators:
      - type: json_parser
      ...
```

**Comment by BinaryFissionGames** [comment]
@djaglowski Could you assign me to this issue?

**Comment by BinaryFissionGames** [comment]
Completed with #18921

**Comment by Krishnadas-KP** [comment]
@BinaryFissionGames How can we enable this feature ? I want to ignore the header lines from IIS logs before exporting

**Comment by djaglowski** [comment]
@xieyuguang, you may be able to do this with the `router` operator. Roughly:
```yaml
filelog:
  ...
  header:
    pattern: '^.+: .+$'
    metadata_operators:
      - type: router
        routes:
          - output: create_at_parser
            expr: 'bodymatches "^Log file created at: .*$"'
          - output: running_on_parser
            expr: 'body matches "^ Running on machine: .*$"'
          ...
      - type: regex_parser
        id: create_at_parser
        regex: '^Log file created at: (?P<log.file.created_time>.+)$'
      - type: regex_parser
        id: running_on_parser
        regex: '^ Running on machine: (?P<machine.name>.+)$'
      ...
```

You can read more about this type of pipeline [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/types/pipeline.md#non-linear-pipelines).
