### ISSUE TITLE
[processor/tailsamplingprocessor] Policy on span_count & min_spans

### ISSUE THREAD

**Issue by yehaotian** [open-telemetry/opentelemetry-collector-contrib#18215]
### Component(s)

processor/tailsamplingprocessor - span_count

### Is your feature request related to a problem? Please describe.

For now tail sampling processor policy on **span_count** only have **min_spans** to sample on traces contains minimal number of spans. 
It is good to have **max_spans** to sample traces contains maximum number of spans, to help filter out giant traces. Usually we find out the giant traces are not helpful and takes a lot of data volume quota.

### Describe the solution you'd like

Something similar
```yaml
policies:
      [
# sample traces with maximum 20 spans.
         {
            name: test-policy-10,
            type: span_count,
            span_count: {max_spans: 20}
         },
# or not sample traces with more than 20 spans
         {
            name: test-policy-11,
            type: span_count,
            span_count: {min_spans: 20, invert_match: true}
         },

...
      ]
```

**Comment by mizhexiaoxiao** [comment]
Seems reasonable to me.
Assign me if possible, i should be able to work on it

**Comment by atoulme** [comment]
@mizhexiaoxiao it's yours!

**Comment by yehaotian** [comment]
Thanks for the help!

**Comment by jpkrohling** [comment]
```yaml
# sample traces with maximum 20 spans.
         {
            name: test-policy-10,
            type: span_count,
            span_count: {max_spans: 20}
         },
# or not sample traces with more than 20 spans
         {
            name: test-policy-11,
            type: span_count,
            span_count: {min_spans: 20, invert_match: true}
         },
```

Aren't those equivalent? Why not just have one of min_spans/max_spans? Or remove the invert match?

**Comment by yehaotian** [comment]
I mentioned **or** in the comment, either way works for me

**Comment by jpkrohling** [comment]
I think just a "num_spans" or just "num" should be fine. I know we use invert_match elsewhere, but perhaps we could use a different name? Like, `operation=min`? Naming...

**Comment by mizhexiaoxiao** [comment]
> I think just a "num_spans" or just "num" should be fine. I know we use invert_match elsewhere, but perhaps we could use a different name? Like, `operation=min`?

I think adding `max_spans` configuration is enough. Users can set the `span_count` number they want to sample in the range of `min_spans` and `max_spans`. Of course, you can also set only one of them. This is similar to the `min_value` and `max_value` of the numeric_attribute policy

Changing the configuration name may not be friendly to users who are using the span_count policy, but adding `max_spans` will not affect it. 

Possible configurations are as follows
```yaml
# sample traces with minimum 5 spans.
{
    name: test-policy-1,
    type: span_count,
    span_count: {min_spans: 5}
}
```
```yaml
# sample traces with maximum 20 spans.
{
    name: test-policy-1,
    type: span_count,
    span_count: {max_spans: 20}
}
```

```yaml
# sample traces range of 5 and 20 spans.
{
    name: test-policy-1,
    type: span_count,
    span_count: {min_spans:5, max_spans: 20}
}
```

@jpkrohling What's your thoughts on this?
