### ISSUE TITLE
ClickHouse - StartTime is not inserted for Gauge and Counter

### ISSUE THREAD

**Issue by StarpTech** [open-telemetry/opentelemetry-collector-contrib#18220]
### Component(s)

exporter/clickhouse

## Description

Hi, I tried metrics with the clickhouse collector. I saw that the column `StartTimeUnix` displayed the UNIX start date `1970`. After digging into the source, I found out that the start time is not inserted.

- (Counter) https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/internal/sum_metrics.go#L129
- (Gauge) https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/clickhouseexporter/internal/gauge_metrics.go#L125

### Collector version

0.70.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
extensions:
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  clickhouse:
    endpoint: "url"
    timeout: 10s
    database: otel
    traces_table_name: otel_traces
    logs_table_name: otel_logs
    metrics_table_name: otel_metrics
    ttl_days: 7
    sending_queue:
      queue_size: 5000
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_interval: 30s
      max_elapsed_time: 300s
#  logging:
#    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
```
