### ISSUE TITLE
Datadog traces end up in a Datadog account that doesn't match the api key used for the traces exporter

### ISSUE THREAD

**Issue by hamidp555** [open-telemetry/opentelemetry-collector-contrib#18233]
### Component(s)

exporter/datadog

## Description
I have a pipeline that consists of three Datadog exporters, logs exporter, metrics exporter and traces exporter. logs and metrics exporters use a different api key than the traces exporter. However, the traces sometimes end up in the Datadog account that is related to the api key used for the logs and metrics exporters.

## Steps to Reproduce
Have a collector with the example configuration provided in this bug report, produce some traces and check where traces end up, restart the collector and check again to see where traces end up. repeat this a few times. sometimes traces will end up in a Datadog account related to the metrics/logs api key

## Expected Result
 My expectation was that traces always end up in a Datadog account that is related to the api key used for traces exporter

### Collector version

0.70.0

## Environment
OS: Ubuntu 20.04.5 LTS

### OpenTelemetry Collector configuration

```yaml
exporters:
  datadog/traces:
    api:
      key:<api_key_1>
      site: datadoghq.com
    sending_queue:
      enabled: false
  datadog/logs:
    api:
      key: <api_key_2>
      site: datadoghq.com
  datadog/metrics:
    api:
      key: <api_key_2>
      site: datadoghq.com

service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    logs:
      exporters:
      - datadog/logs
      processors:
      - memory_limiter
      - batch
      receivers:
      - filelog
    metrics:
      exporters:
      - datadog/metrics
      processors:
      - memory_limiter
      - batch
      receivers:
      - prometheus
    traces:
      exporters:
      - datadog/traces
      processors:
      - memory_limiter
      receivers:
      - solace
```
