### ISSUE TITLE
New component: Log-based metrics processor

### ISSUE THREAD

**Issue by weyert** [open-telemetry/opentelemetry-collector-contrib#18269]
### The purpose and use-cases of the new component

Log-based Metrics (`logmetrics`) analyses the received log records, and generates metrics from them. 

### Example configuration for the component

```yaml
processors:
   logmetrics:
         pg_permissions_errors:
               type: counter
               filter:
                  -   from_attribute: textPayload
                       match: permission denied for table (?P<tableName>.*)
                       action: 
                             - type: add_attribute
                                name: db.table.name
                                value: $tableName
 ```

### Telemetry data types supported

This processor would accept `logs` and create `metrics` 

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

The idea behind this proposed processor is to allow generating metrics from logs that have been sent to the `collector` using the new `logs` functionality. For example, in Google Cloud you have the ability to generate metrics based on the logs. I would love to have a similar solution for the `collector`. 

A potential use case would be the ability to send all the logs to dedicated `logs`-collector which passthrough the logs to the appropriate logs backend  (e.g. Google Cloud Logging) but at the same time generate log-bas metrics which then via the Prometheus Remote Write exporter get send to Prometheus.
