### ISSUE TITLE
Disabling the sending_queue prevents metrics from being scraped

### ISSUE THREAD

**Issue by JustinPaulJohn** [open-telemetry/opentelemetry-collector-contrib#18296]
### Components
otlp reciever and exporter

### Description
Disabling the sending_queue within the otlp-exporter prevents all metric data from being sent. Metrics are still being generated on the localhost:8888/metrics endpoint, however, our Prometheus scrape config (which is setup to scrape that endpoint) is unable to receive any metric data. Re-enabling the sending_queue allows metrics to be sent like normal, however, our current configuration requires the sending_queue to be disabled. Is there any way to keep the sending_queue disabled while allowing metrics to be exported? I may not have the best understanding of the sending_queue, so if anyone is able to point me towards any relevant documentation, that would be helpful too. 

### Collector Version
v.0.17.0

## Current Configuration
```
extensions:
  health_check:

recievers:
  otlp:
    protocols:
      grpc:
        endpoint: ...
      http:
        endpoint: ...

processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200

exporters:
  otlp:
    endpoint: ...
    retry_on_failure:
      enabled: true
      max_elapsed_time: 120s
    sending_queue:
      enabled: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

  extensions: [health_check]
```
