### ISSUE TITLE
OIDC auth extension header handling should be case-insensitive

### ISSUE THREAD

**Issue by alexvanboxel** [open-telemetry/opentelemetry-collector-contrib#18405]
### Component(s)

extension/oidcauth

## Description
The OIDC auth extension header handling should be case-insensitive; also the default header key is declared as `authorization`, while most systems provide the `Authorization` header capitalized. The HTTP spec also specifies that HTTP headers are case-insensitive.

## Steps to Reproduce
Use the OIDC extension, without specifying the attribute key (so default is used), do a call with a JWT bearer token, with as key the capitalized `Authorization`.

## Expected Result
200 OK

## Actual Result
401 Unauthorized

### Collector version

0.77

## Environment
OS: MacOS

### OpenTelemetry Collector configuration

```yaml
receivers:
  googlecloudpubsub:
    mode: "push"
    project: collibra-telemetry
    subscription: projects/acme/subscriptions/test
    push:
      path: "/"
      endpoint: "0.0.0.0:${PORT}"
      auth:
        authenticator: oidc

extensions:
  oidc:
    issuer_url: https://accounts.google.com
    audience: otel
    username_claim: email
    attribute: Authorization

processors:
  batch:

exporters:
  logging:
    logLevel: info

service:
  extensions: [oidc]
  pipelines:
    traces:
      receivers: [googlecloudpubsub]
      exporters: [logging]
    metrics:
      receivers: [googlecloudpubsub]
      exporters: [logging]
    logs:
      receivers: [googlecloudpubsub]
      exporters: [logging]

  telemetry:
    logs:
      level: INFO
```

### Additional context

Workaround for now, declare the `attribute` explicitly:

```extensions:
  oidc:
    # https://accounts.google.com/.well-known/openid-configuration
    issuer_url: https://accounts.google.com
    audience: otel
    username_claim: email
    attribute: Authorization```
