### ISSUE TITLE
Prometheus Receiver Fails to Start when using the ECS Observer Extension

### ISSUE THREAD

**Issue by vijayansarathy** [open-telemetry/opentelemetry-collector-contrib#18490]
### Component(s)

extension/observer

## Description
When using an ECS Observer in the collector configuration to provide scrape targets in a file, the Prometheus Receiver fails to startup because there is not scrape targets file to begin with.

## Steps to Reproduce
When using the following collector configuration, the Prometheus receiver gives this error:
_Error: invalid configuration: receivers::prometheus: file "/etc/ecs_sd_targets.yaml" for file_sd in scrape job "ecs_services" does not exist_

```
extensions:
  health_check:
  sigv4auth:
    region: us-east-1
  ecs_observer:
    refresh_interval: 60s 
    cluster_name: 'ecs-sarathy-cluster'
    cluster_region: us-east-1
    result_file: '/etc/ecs_sd_targets.yaml' 
    services:
      - name_pattern: '^WebAppService$'    
    task_definitions:
        metrics_path: '/metrics'
        metrics_ports:
          - 3000
          - 9779
        arn_pattern: '.*:task-definition/WebAppTask:[0-9]+'

receivers:
  awsxray:
  prometheus:
    config:
      scrape_configs:
        - job_name: ecs_services
          file_sd_configs:
            - files:
                - '/etc/ecs_sd_targets.yaml'
              refresh_interval: 30s
          relabel_configs: 
            - source_labels: [ __meta_ecs_cluster_name ] 
              action: replace
              target_label: cluster
            - source_labels: [ __meta_ecs_service_name ] 
              action: replace
              target_label: service
            - source_labels: [ __meta_ecs_task_definition_family ] 
              action: replace
              target_label: taskdefinition       
            - source_labels: [ __meta_ecs_task_container_name ] 
              action: replace
              target_label: container                        
exporters:
  awsxray:
  prometheusremotewrite:
    endpoint: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/XXX/api/v1/remote_write
    auth:
      authenticator: sigv4auth
    resource_to_telemetry_conversion:
      enabled: true

service:
  extensions:
    - ecs_observer
    - health_check
    - sigv4auth
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]       
    traces:
      receivers: [awsxray]
      exporters: [awsxray]       
```

## Expected Result
The receiver should gracefully startup if the file is missing.

## Actual Result
The receiver gives the following error and the collector process is killed
_Error: invalid configuration: receivers::prometheus: file "/etc/ecs_sd_targets.yaml" for file_sd in scrape job "ecs_services" does not exist_

I worked around this issue by packaging an empty file into the Docker image as follows:

```
FROM amazon/aws-otel-collector:latest
COPY ecs_sd_targets.yaml /etc
```

### Collector version

latest, v0.25.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
This is the relevant message from the logs:

Error: invalid configuration: receivers::prometheus: file "/etc/ecs_sd_targets.yaml" for file_sd in scrape job "ecs_services" does not exis
```
