### ISSUE TITLE
Unable to Use Docker Label Filters for ECS Observer Extension 

### ISSUE THREAD

**Issue by vijayansarathy** [open-telemetry/opentelemetry-collector-contrib#18491]
### Component(s)

extension/observer

## Description
Adding filters to the ECS Observer extension using the _docker_labels_ field results in a configuration error

## Steps to Reproduce

I am using the ECS Observer extension shown below:

```
extensions:
  health_check:
  sigv4auth:
    region: us-east-1
  ecs_observer:
    refresh_interval: 60s 
    cluster_name: 'ecs-sarathy-cluster'
    cluster_region: us-east-1
    result_file: '/etc/ecs_sd_targets.yaml' 
    services:
      - name_pattern: '^WebAppService$'
    docker_labels:
      - port_label: 'ECS_PROMETHEUS_METRICS_PORT'
      - metrics_path_label: 'ECS_PROMETHEUS_METRICS_PATH'      
    task_definitions:
        metrics_path: '/metrics'
        metrics_ports:
          - 3000
          - 9779
        arn_pattern: '.*:task-definition/WebAppTask:[0-9]+'
```

## Expected Result
Expected the collector to start up properly and identity targets.

## Actual Result
Collector fails to start up with the following error:
_Error: invalid configuration: extensions::ecs_observer: port_label is empty_

It works properly if I remove the _docker_labels_ field.

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by Aneurysm9** [comment]
```yaml
    docker_labels:
      - port_label: 'ECS_PROMETHEUS_METRICS_PORT'
      - metrics_path_label: 'ECS_PROMETHEUS_METRICS_PATH' 
```

I think this should be 

```yaml
    docker_labels:
      - port_label: 'ECS_PROMETHEUS_METRICS_PORT'
        metrics_path_label: 'ECS_PROMETHEUS_METRICS_PATH' 
```

The `docker_labels` entry is meant to be a list of maps.  In your original config it is a list of two maps, the second of which does not have a `port_label` entry.
