### ISSUE TITLE
Azure Monitor exporter does not export resource attributes for logs

### ISSUE THREAD

**Issue by bastbu** [open-telemetry/opentelemetry-collector-contrib#18525]
### Component(s)

exporter/azuremonitor

## Description

When exporting logs to an Application Insights instance by using an OTel Collector configured to use the Azure Monitor exporter, any attributes set using `OTEL_RESOURCE_ATTRIBUTES` are not part of the `customDimensions` of the exported log. As the [`Resource` is part of the log data model](https://opentelemetry.io/docs/reference/specification/logs/data-model/#field-resource), I would have expected to see the attribute as a key-value pair in the `customDimensions`.

For both metrics and traces, all `OTEL_RESOURCE_ATTRIBUTES` key-value pairs appear as `customDimensions`.

The console exporter shows that the attributes are exported correctly as part of the resource (note the `key: value` as part of the associated resource), hence the problem does not seem to belong to the .NET SDK:

```
LogRecord.Timestamp:               2023-02-13T11:30:21.0348925Z
LogRecord.CategoryName:            GettingStarted.Program
LogRecord.LogLevel:                Information
LogRecord.StateValues (Key:Value):
    Name: tomato
    Price: 2.99
    OriginalFormat (a.k.a Body): Item {Name} costs {Price}.

Resource associated with LogRecord:
key: value
service.name: unknown_service:oteltest
```

## Steps to Reproduce

Run the following logging sample:

```csharp
public class Program
{
    public static void Main()
    {
        using var loggerFactory = LoggerFactory.Create(builder =>
            builder.AddOpenTelemetry(options => options.AddConsoleExporter().AddOtlpExporter()));

        var logger = loggerFactory.CreateLogger<Program>();

        logger.LogInformation("Item {Name} costs {Price}.", "tomato", 2.99);
    }
}
```

with e.g.

```
OTEL_RESOURCE_ATTRIBUTES="key=value" dotnet run
```

## Expected Result

`customDimensions` for log `"Item {Name} costs {Price}."` contains `key=value`.

## Actual Result

No `customDimensions` appear for `traces` in Application Insights (which are equivalent to logs in OTel-speak).

### Collector version

0.71.0

## Environment
OS: WSL2 on Windows 11
Compiler: Download of binary from OTel Release page

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  azuremonitor:
    instrumentation_key: <redacted>
  logging:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [azuremonitor,logging]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [azuremonitor,logging]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [azuremonitor,logging]
```
