### ISSUE TITLE
proxy settings for Datadog Exporter

### ISSUE THREAD

**Issue by fabiocarvalho-planet** [open-telemetry/opentelemetry-collector-contrib#18527]
### Component(s)

exporter/datadog

### Is your feature request related to a problem? Please describe.

Some servers can reach the internet only by means of a proxy server.
Datadog Exporter should have an additional configuration for specifying a proxy server in order to reach the Datadog API endpoints on internet.

When using containers this is easy as the container can have its own ENV VARS and proxies can be set there. When running OtelCol binaries directly over the OS (Linux or Windows) this is difficult to do or requires additional and not usual configuration.

I think this actually can be done via system-wide proxy settings, but this can pose issues on systems with tight security requirements. I have this situation and couldn't solve it - so no OtelCol on this server.

### Describe the solution you'd like

A simple suggestion, sure that are better attempts on that.
At the Datadog Exporter config section, look at the "http*" starting lines (remaining lines just for context):
```
...
exporters:
  datadog:
    hostname: ${COMPUTERNAME}
    api:
      site: datadoghq.eu
      key: ${DD_API_KEY}
      http_proxy_endpoint: http://a.b.c.d:port (OR http://domain.name:port)
      https_proxy_endpoint: http://a.b.c.d:port (OR http://domain.name:port)
      http_proxy_user: "proxyusername"
      http_proxy_pass: "proxyusernamepassword"
    host_metadata:
      enabled: true
      hostname_source: config_or_system
...
```
Another idea, more concise but harder to read at the beginning:
```
...
exporters:
  datadog:
    hostname: ${COMPUTERNAME}
    api:
      site: datadoghq.eu
      key: ${DD_API_KEY}
      http_proxy_endpoint: http://proxyusername:proxyusernamepassword@a.b.c.d:port (OR http://proxyusername:proxyusernamepassword@domain.name:port)
      https_proxy_endpoint: http://proxyusername:proxyusernamepassword@a.b.c.d:port (OR http://proxyusername:proxyusernamepassword@domain.name:port)
    host_metadata:
      enabled: true
      hostname_source: config_or_system
...
```

### Describe alternatives you've considered

As I mentioned, setting a system-wide proxy configuration or, if the OS allows it, a specific proxy configuration for the process itself.
