### ISSUE TITLE
Elasticsearch exported failing to export traces to elastic

### ISSUE THREAD

**Issue by mpostument** [open-telemetry/opentelemetry-collector-contrib#18523]
### Component(s)

exporter/elasticsearch

## Description

When i am trying to export traces to elasticsearch i am getting an error
## Expected Result
Traces available in elasticsearch

## Actual Result
No traces in elasticsearch

### Collector version

0.71.0

## Environment
EKS 1.22

### OpenTelemetry Collector configuration

```yaml
exporters:
  elasticsearch/log:
    endpoints:
    - https://ES_URL:9200
    logs_index: otel_log_index
    password: $ELASTIC_PASSWORD
    tls:
      insecure_skip_verify: true
    user: USERNAME
  elasticsearch/trace:
    endpoints:
    - https://ES_URL:9200
    password: $ELASTIC_PASSWORD
    tls:
      insecure_skip_verify: true
    traces_index: traces-apm-default
    user: USERNAME
  logging: {}
  prometheusremotewrite:
    endpoint: Prometheus
    resource_to_telemetry_conversion:
      enabled: true
extensions:
  health_check: {}
  memory_ballast:
    size_in_percentage: 40
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: ${MY_POD_IP}:14250
      thrift_compact:
        endpoint: ${MY_POD_IP}:6831
      thrift_http:
        endpoint: ${MY_POD_IP}:14268
  otlp:
    protocols:
      grpc:
        endpoint: ${MY_POD_IP}:4317
        max_recv_msg_size_mib: 100
      http:
        endpoint: ${MY_POD_IP}:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${MY_POD_IP}:8888
  zipkin:
    endpoint: ${MY_POD_IP}:9411
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    logs:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - logging
      - prometheusremotewrite
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
      - prometheus
    traces:
      exporters:
      - logging
      - elasticsearch/trace
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
      - jaeger
      - zipkin
  telemetry:
    metrics:
      address: ${MY_POD_IP}:8888
```

### Log output

```shell
2023-02-13T09:14:12.616Z	error	elasticsearchexporter@v0.71.0/elasticsearch_bulk.go:252	Drop dcos: failed to index: struct { Type string "json:\"type\""; Reason string "json:\"reason\""; Cause struct { Type string "json:\"type\""; Reason string "json:\"reason\"" } "json:\"caused_by\"" }{Type:"illegal_argument_exception", Reason:"field [observer] not present as part of path [observer.version]", Cause:struct { Type string "json:\"type\""; Reason string "json:\"reason\"" }{Type:"", Reason:""}}	{"kind": "exporter", "data_type": "traces", "name": "elasticsearch/trace", "attempt": 1, "status": 400}
observability-v2-otel-deployment-678c69c777-tspfq opentelemetry-collector-deployment github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.pushDocuments.func1
observability-v2-otel-deployment-678c69c777-tspfq opentelemetry-collector-deployment 	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.71.0/elasticsearch_bulk.go:252
observability-v2-otel-deployment-678c69c777-tspfq opentelemetry-collector-deployment github.com/elastic/go-elasticsearch/v8/esutil.(*worker).flush
observability-v2-otel-deployment-678c69c777-tspfq opentelemetry-collector-deployment 	github.com/elastic/go-elasticsearch/v8@v8.5.0/esutil/bulk_indexer.go:581
observability-v2-otel-deployment-678c69c777-tspfq opentelemetry-collector-deployment github.com/elastic/go-elasticsearch/v8/esutil.(*bulkIndexer).init.func1
observability-v2-otel-deployment-678c69c777-tspfq opentelemetry-collector-deployment 	github.com/elastic/go-elasticsearch/v8@v8.5.0/esutil/bulk_indexer.go:319
```
