### ISSUE TITLE
replace_pattern() OTTL function should allow referencing capturing groups

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-collector-contrib#18610]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

I'd like to rename metrics scraped from certain destinations to better align to naming conventions (for example, replacing dashes with dots, etc.)

My attempt was to use the `transform` processor with OTTL for this capability
```yaml
  transform/kube_state_rename:
    metric_statements:
    - context: metric
      statements:
      - replace_pattern(name, "kube_([0-9A-Za-z]+_)", "k8s.$$1")
```

However, the `replace_pattern()` OTTL function does not support expanding references to capturing groups.

### Describe the solution you'd like

I would like `replace_pattern()` OTTL to not support expanding references to capturing groups (using `replace_pattern()` OTTL function does not support expanding references to capturing groups.).

### Additional context

Seems tangentially related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18084
