### ISSUE TITLE
New component: receiver/lokireceiver

### ISSUE THREAD

**Issue by mar4uk** [open-telemetry/opentelemetry-collector-contrib#18635]
### The purpose and use-cases of the new component

The Loki receiver implements the [Loki push api](https://grafana.com/docs/loki/latest/clients/promtail/#loki-push-api) as specified [here](https://grafana.com/docs/loki/latest/api/#get-lokiapiv1tail). It allows Promtail instances to specify the open telemetry collector as their lokiAddress.

This issue is the reincarnation of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9800

### Example configuration for the component

```
receivers:
  loki:
    protocols:
      http:
        endpoint: 0.0.0.0:3500
      grpc:
        endpoint: 0.0.0.0:3600    
   # Label map to add to every log line sent to the push API
    labels:
      [ <labelname>: <labelvalue> ... ]   

```

labels could be converted to Log Record [Attributes](https://opentelemetry.io/docs/reference/specification/logs/data-model/#field-attributes)

### Telemetry data types supported

Logs

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

The previous implementation of promtail receiver failed because it had pull and push implementation. Pull implementation required importing Loki, which led to bringing a lot of dependencies and vulnerabilities to the collector. 
Such amount of dependencies is difficult to maintain. That's why the decision to remove promtail receiver was made (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/18524)

In this proposal, I suggest implementing only the push mechanism.
It will cover community request to send loki logs to the collector
