### ISSUE TITLE
[processor/filter] Standardize configuration on OTTL

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#18642]
### Component(s)

processor/filter

### Is your feature request related to a problem? Please describe.

With https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16369, OTTL was added to the filterprocessor.  This allows us to standardize the way the filterprocessor configures conditions for when data should be dropped.

For spans, the existing non-ottl configuration options are:
- matching by service name, span name, attributes, scopes, resource attributes, and span kind. 
- Both strict and regex is supported. 
- When checking attributes, converting attribute values from bool, double, and int to string is supported

For metric, the existing non-ottl configuration options are:
- matching by metric name, resource attributes 
- Both strict and regex is supported. 
- matching by datapoint attributes via the [expr](https://github.com/antonmedv/expr) expression engine. 
- When checking attributes, converting attribute values from bool, double, and int to string is supported.

For logs, the existing non-ottl configuration options are:
- matching by resource attributes, attributes, severity text, body, and severity number. 
- Both strict and regex is supported.
- When checking attributes, converting attribute values from bool, double, and int to string is supported. 
- When matching severity number, a minimum log severity can be used and any values equal to or greater than the severity match. You can also specify if an undefined severity number can be match.

With the completion of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16413, OTTL can now handle each of these use cases, and more, in a uniform library.

In the past we only had what was in `internal/filter` and as different components needed different condition features those packages grew. As users wanted access to different fields in the telemetry payload the signal-specific filters would change to reflect those needs. The filterprocessor grew with it, providing important value but with increased maintenance burden and configuration complexity. Reading through the filterprocessor's readme highlights the difficulty in maintaining and understanding the different features and fields available.

By unifying on OTTL we'll have a solution that has access to all fields on all signals. Users no longer need to worry about whether or not a field for their signal is available to use and maintainers no longer need to worry about adding more fields to filter on in the future (OTLP changes excluded). Due to OTTL's functions, adding more features to enable complex conditions is simpler as the functions encapsulate the logic and can be added without modifying the underlying libraries or configuration. On top of its field access and functions, OTTL's grammar also provides more robust conditions, allowing users to use inequalities, `nil`, and arithmetic.

Acknowledging that Domain Specific Languages can be scary, there is an [open issue that proposes a declarative syntax solution that works with OTTL](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11852)

### Describe the solution you'd like

temp

**Comment by TylerHelmuth** [comment]
Based on the SIG meeting today, we have decided to take a hands-on approach with deprecating the non-OTTL configuration to help users with the transition.

Since the non-OTTL filter structs/features are translatable to OTTL, we will start out the deprecation process by adding a translator to the `filterprocessor`/`internal/filter` that can convert the non-OTTL structs into the equivalent OTTL statement.  The `filterprocessor` will be updated to use this translator so that it is always using OTTL behind the scenes and users are unaffected.

We can then deprecate the non-OTTL config and start logging warnings and the equivalent OTTL statement so that users know exactly what to change in their config. Eventually we can use a feature gate to fail on startup if using the non-OTTL config, but let users enable the feature gate to keep using them.  Finally, we completely remove the old config and the feature gate.

The timeline from logging deprecation warnings and equivalent OTTL statements -> featuregate and config removal will be large, probably about 3 months.  This timeline will not start until the converter is implemented.

**Comment by TylerHelmuth** [comment]
`internal/filter/filtermetric` allows limited filtering using the [expr](https://github.com/antonmedv/expr) package.  I propose that converting between this language and OTTL should be out-of-scope.  Instead, if the `filter.filtermetric.useOTTLBridge` feature gate is enabled and the configuration contains `expr` matching, the collector will fail to start, including an error about using OTTL instead.

**Comment by Hronom** [comment]
@TylerHelmuth please can you extend set of examples in README.md.

It's also seems like with OTTL not possible to replace this:
```
      filter/allowed_metrics:
        metrics:
          include:
            match_type: expr
            expressions:
              # kube-state-metrics
              - MetricName == "kube_pod_container_resource_requests" && Label("namespace") == "test"
              - MetricName == "kube_pod_container_resource_limits" && Label("namespace") == "test"
              # kubernetes-nodes-cadvisor
              - MetricName == "container_cpu_usage_seconds" && Label("namespace") == "test"
              - MetricName == "container_cpu_cfs_throttled_periods" && Label("namespace") == "test"
              - MetricName == "container_cpu_cfs_periods" && Label("namespace") == "test"
              - MetricName == "container_memory_working_set_bytes" && Label("namespace") == "test"
              # Istio, source https://istio.io/latest/docs/reference/config/metrics/#metrics
              - MetricName == "istio_requests" && Label("namespace") == "test"
              - MetricName == "istio_request_duration_milliseconds" && Label("namespace") == "test"
              - MetricName == "istio_request_bytes" && Label("namespace") == "test"
              - MetricName == "istio_response_bytes" && Label("namespace") == "test"
              # prometheus-node-exporter
              - MetricName == "node_cpu_seconds"
              - MetricName == "node_memory_MemTotal_bytes"
              - MetricName == "node_memory_MemFree_bytes"
              - MetricName == "node_memory_Buffers_bytes"
              - MetricName == "node_memory_Cached_bytes"
```

so basically here I'm allow only specific set of metrics based on conditions. 
It's seems like this case not possible with OTTL as it works like `exclude` filter. 
But what is needed it's an `include` functionality, please can you provide an example how to convert example above to the OTTL?
