### ISSUE TITLE
allow passing environment for sentry exporter

### ISSUE THREAD

**Issue by fadeltd** [open-telemetry/opentelemetry-collector-contrib#18694]
### Component(s)

exporter/sentry

### Is your feature request related to a problem? Please describe.

Hi, I'd like to be able to pass an environment for the sentry exporter as it is currently not supported, for easier sentry filtering

![Sentry Env](https://user-images.githubusercontent.com/4526413/219259329-2b84a04f-07f5-466c-93db-9245125b1737.png)

### Describe the solution you'd like

```
exporters:
  sentry:
    dsn: https://key@host/path/42
    env: prod
    insecure_skip_verify: true
```

### Additional context

I can create a PR for this
