### ISSUE TITLE
New component: Databricks Receiver

### ISSUE THREAD

**Issue by pmcollins** [open-telemetry/opentelemetry-collector-contrib#18724]
### The purpose and use-cases of the new component

The Databricks Receiver uses the Databricks [API](https://docs.databricks.com/dev-tools/api/latest/index.html) to generate metrics about the operation of a Databricks instance.

In addition to generating metrics from the Databricks API, it also generates metrics from the Spark subsystem running in a Databricks instance.

### Example configuration for the component
```
databricks:
  instance_name: my-instance
  endpoint: https://dbr.example.net
  token: abc123
  spark_org_id: 1234567890
  spark_endpoint: https://spark.example.net
  spark_ui_port: 40001
  collection_interval: 10s
```
### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

An early implementation is [here](https://github.com/signalfx/splunk-otel-collector/tree/main/internal/receiver/databricksreceiver). We would like to donate this to the community.
