### ISSUE TITLE
New component: Promql Metrics Processor

### ISSUE THREAD

**Issue by NgZiming** [open-telemetry/opentelemetry-collector-contrib#18771]
### The purpose and use-cases of the new component

Mutating metrics with promql.

Promql is widely used, flexible, meets all kinds of needs, and easily be written and tested in prometheus ui / vm ui or grafana.

### Example configuration for the component

```yaml
tsdb:
  storage_dir: /tmp # randisk or any other fast storage
  max_samples: 1000000
  query_timeout_ms: 1000
  metrics: # metrics that will be store in tsdb for queries 
  - http_requests_total
  - kube_.*
quries:
- query_string: kube_pod_labels{} * on(namespace, pod) group_left(namespace, pod) http_requests_total{}
  output_metric_name: pod_http_requests_total
- query_string: kube_pod_labels{} * on(namespace, pod) group_left(namespace, pod) http_requests_total{}
  output_name: pod_http_requests_total
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

Promql Metrics Processor only processes metrics of current scrape.
Data won't persist across scrapes and timestamps won't be honored.

I'd like to be the contributor of this processor.
