### ISSUE TITLE
can't get k8sattributesprocessor to add k8s metadata

### ISSUE THREAD

**Issue by Driksi** [open-telemetry/opentelemetry-collector-contrib#18772]
### Component(s)

processor/k8sattributes

## Component

processor/k8sattributes

## Description
Apologise in advance if this is not a bug, but some misconfiguration...

I'm trying to configure the otel collector to automatically add k8s metadata (namespace, etc) to exported metrics.
I am currently testing it in a AWS cluster.
The data is currently being recieved by fluent bit, otel reciever and sent with the kafka exporter.

## Steps to Reproduce

I have performed the same steps cited in the  issue #17840

## Expected Result

I would expect more information to be displayed in the resource attributes

## Actual Result

Currently only the service name of the service associated to the pod is displayed in the logs.

### Collector version

v.0.17.0

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols: 
          grpc:
          http:

      fluentforward:
        endpoint: 0.0.0.0:8006

    exporters:

      logging:
        verbosity: detailed

      kafka/traces:
        brokers:
        - broker:9092
        protocol_version: 2.0.0
        topic: otlp_traces_internal

      kafka/logs:
        brokers:
        - broker:9092
        protocol_version: 2.0.0
        topic: otlp_logs_internal
      
    processors:
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time

        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.ip
            - from: resource_attribute
              name: k8s.pod.uid
            - from: connection
      batch:
      
    service:
      pipelines:
        logs:
          receivers: [fluentforward]
          processors: [k8sattributes]
          exporters: [logging, kafka/logs]
        traces:
          receivers: [otlp]
          processors: [k8sattributes]
          exporters: [logging, kafka/traces]
      telemetry:
        logs:
          level: "debug"
```

### Log output

```shell
Trace ID:
Span ID:
Flags: 0
LogRecord #6
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-02-20 12:58:44.274573693 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str(WARN - Request fetchAll returned 0 edges)
Attributes:
     -> time: Str(2023/02/20 12:58:44.274)
     -> severity_text: Str(WARN)
     -> trace_id: Str(8a1c16a2f84fc580148239b5fbf3a9d5)
     -> span_id: Str(11bc2549ff1e1fa8)
     -> function: Str(EdgeServiceAdapter.fetchAll)
     -> execution_timestamp: Str(2023-02-20 12:58:44.273842)
     -> path: Str(microservice)
     -> task: Str(Not Specified)
     -> name: Str(EdgeServiceAdapter)
     -> fluent.tag: Str(log)
Trace ID:
Span ID:
Flags: 0
LogRecord #7
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-02-20 12:58:44.275166631 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str(Successfully retrieved graph)
Attributes:
     -> time: Str(2023/02/20 12:58:44.274)
     -> severity_text: Str(INFO)
     -> trace_id: Str(8a1c16a2f84fc580148239b5fbf3a9d5)
     -> span_id: Str(11bc2549ff1e1fa8)
     -> function: Str(getGraph)
     -> execution_timestamp: Str(2023-02-20 12:58:44.274498)
     -> path: Str(microservice)
     -> task: Str(Not Specified)
     -> name: Str(GraphController)
     -> fluent.tag: Str(log)
Trace ID:
Span ID:
Flags: 0
        {"kind": "exporter", "data_type": "logs", "name": "logging"}
2023-02-20T12:58:47.854Z        debug   k8sattributesprocessor@v0.67.0/processor.go:110 evaluating pod identifier       {"kind": "processor", "name": "k8sattributes", "pipeline": "traces", "value": [{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""}]}
2023-02-20T12:58:47.854Z        info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "logging", "#spans": 15}
2023-02-20T12:58:47.855Z        info    ResourceSpans #0
Resource SchemaURL:
Resource attributes:
     -> service.name: Str(microservice)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope OTel instrumentation
Span #0
    Trace ID       : 48225c24c178eb18a92ec9b6e126b2d9
    Parent ID      : c1f18fa1d90f36d6
    ID             : c1ca2f33608f4c07
    Name           : DB-access-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:43.813575801 +0000 UTC
    End time       : 2023-02-20 12:58:43.819368573 +0000 UTC
    Status code    : Ok
    Status message :
Span #1
    Trace ID       : 48225c24c178eb18a92ec9b6e126b2d9
    Parent ID      : c1ca2f33608f4c07
    ID             : 661bd01139601710
    Name           : DB-access-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:43.820664042 +0000 UTC
    End time       : 2023-02-20 12:58:43.824259562 +0000 UTC
    Status code    : Ok
    Status message :
Span #2
    Trace ID       : 48225c24c178eb18a92ec9b6e126b2d9
    Parent ID      : 661bd01139601710
    ID             : a0af8678fa30bc5d
    Name           : DB-access-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:43.825345338 +0000 UTC
    End time       : 2023-02-20 12:58:43.829356134 +0000 UTC
    Status code    : Ok
    Status message :
Span #3
    Trace ID       : 48225c24c178eb18a92ec9b6e126b2d9
    Parent ID      : 2d42e9802423694b
    ID             : c1f18fa1d90f36d6
    Name           : annotated-method-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:43.810594779 +0000 UTC
    End time       : 2023-02-20 12:58:43.831017328 +0000 UTC
    Status code    : Ok
    Status message :
Span #4
    Trace ID       : 48225c24c178eb18a92ec9b6e126b2d9
    Parent ID      :
    ID             : 2d42e9802423694b
    Name           : http-server-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:43.808580051 +0000 UTC
    End time       : 2023-02-20 12:58:43.83393348 +0000 UTC
    Status code    : Ok
    Status message :
Span #5
    Trace ID       : 659beec08ece64eb67881e06fe3982f2
    Parent ID      : 61a8a23009825008
    ID             : c3fc2afc6c7ab11a
    Name           : DB-access-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:44.056571689 +0000 UTC
    End time       : 2023-02-20 12:58:44.073385227 +0000 UTC
    Status code    : Ok
    Status message :
Span #6
    Trace ID       : 659beec08ece64eb67881e06fe3982f2
    Parent ID      : c3fc2afc6c7ab11a
    ID             : 52d14a7f386126af
    Name           : DB-access-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:44.074460542 +0000 UTC
    End time       : 2023-02-20 12:58:44.077542356 +0000 UTC
    Status code    : Ok
    Status message :
Span #7
    Trace ID       : 659beec08ece64eb67881e06fe3982f2
    Parent ID      : 52d14a7f386126af
    ID             : 32be5fe41bf6b21f
    Name           : DB-access-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:44.078340247 +0000 UTC
    End time       : 2023-02-20 12:58:44.082056209 +0000 UTC
    Status code    : Ok
    Status message :
Span #8
    Trace ID       : 659beec08ece64eb67881e06fe3982f2
    Parent ID      : 679b95e54560b316
    ID             : 61a8a23009825008
    Name           : annotated-method-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:44.0544946 +0000 UTC
    End time       : 2023-02-20 12:58:44.083971726 +0000 UTC
    Status code    : Ok
    Status message :
Span #9
    Trace ID       : 659beec08ece64eb67881e06fe3982f2
    Parent ID      :
    ID             : 679b95e54560b316
    Name           : http-server-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:44.05313191 +0000 UTC
    End time       : 2023-02-20 12:58:44.087804631 +0000 UTC
    Status code    : Ok
    Status message :
Span #10
    Trace ID       : 8a1c16a2f84fc580148239b5fbf3a9d5
    Parent ID      : 11bc2549ff1e1fa8
    ID             : fffab18de09757ce
    Name           : DB-access-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:44.263243542 +0000 UTC
    End time       : 2023-02-20 12:58:44.265767537 +0000 UTC
    Status code    : Ok
    Status message :
Span #11
    Trace ID       : 8a1c16a2f84fc580148239b5fbf3a9d5
    Parent ID      : fffab18de09757ce
    ID             : 313558c8f8ad369f
    Name           : DB-access-span
    Kind           : Internal
    Start time     : 2023-02-20 12:58:44.266977734 +0000 UTC
    End time       : 2023-02-20 12:58:44.269795604 +0000 UTC
    Status code    : Ok
    Status message :
Span #12
```

### Additional context

I have offuscated some private information from the logs.
I wonder if the information simply isn't being displayed to the logs

**Comment by seankhliao** [comment]
I think your pod association is wrong,
first list level is an ordered priority of matches,
second level is an ANDed set of conditions to match
(an i would reverse the order).

```yaml
        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.ip
          - sources:
            - from: resource_attribute
              name: k8s.pod.uid
          - sources:
            - from: connection
```
