### ISSUE TITLE
[exporter/datadog]: Failed to collect data

### ISSUE THREAD

**Issue by ronenl3** [open-telemetry/opentelemetry-collector-contrib#18827]
### Component(s)

exporter/datadog

## Description
After upgrading my OpenTelemetry Collector, it stopped sending Infrastructure metadata.
I'm using the [Helm Chart](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector) to deploy my Collector

## Expected Result
See metadata on Infrastructure in Datadog website

## Actual Result
![image](https://user-images.githubusercontent.com/87305019/220295712-e6c02d29-6f93-409d-a83b-9310e57a643a.png)

### Collector version

v0.71.0

## Environment
Docker image: `otel/opentelemetry-collector-contrib:0.71.0`

### OpenTelemetry Collector configuration

```yaml
exporters:
  datadog:
    api:
      key: ${DATADOG_API_KEY}
    host_metadata:
      tags:
      - env:pre-prod
  logging: {}
extensions:
  health_check: {}
  memory_ballast: {}
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_mib: 3276
    spike_limit_mib: 1024
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    traces:
      exporters:
      - datadog
      processors:
      - batch
      receivers:
      - jaeger
      - otlp
  telemetry:
    metrics:
      address: 0.0.0.0:8888
```

### Log output

```shell
`2023-02-19T12:07:14.613Z	info	gohai/gohai.go:47	Failed to retrieve filesystem metadata	{"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "df failed to collect filesystem data: %!s(<nil>)"}
2023-02-19T12:07:14.614Z	info	gohai/gohai.go:66	Failed to retrieve platform metadata	{"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "exec: \"uname\": executable file not found in $PATH"}`
```
