### ISSUE TITLE
[doc][filter processor]

### ISSUE THREAD

**Issue by edwintye** [open-telemetry/opentelemetry-collector-contrib#18865]
### Component(s)

processor/filter

## Description

We created a config that followed the examples on the [README.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.71.0/processor/filterprocessor/README.md) and it started failing on release `v0.71.0`.  The issue seems to be due to the upstream change https://github.com/open-telemetry/opentelemetry-collector/pull/6876 which means that keys are now case sensitive. The examples on the `README.md` however has (multiple) blocks like 

```yaml
processors:
  filter:
    spans:
      include:
        match_type: strict
        services:
          - app_3
      exclude:
        match_type: regexp
        services:
          - app_1
          - app_2
        span_names:
          - hello_world
          - hello/world
        attributes:
          - Key: container.name
            Value: (app_container_1|app_container_2)
        libraries:
          - Name: opentelemetry
            Version: 0.0-beta
        resources:
          - Key: container.host
            Value: (localhost|127.0.0.1)
```

where `Key` and `Value` should be `key` and `value` instead.  The use of `Key/Value` also differs from the test configs under `/testdata`.

## Steps to Reproduce

We don't need to use a full otel config to test, we can simply adjust the test data to have the incorrect key, i.e. in `processor/filterprocessor/testdata/config_traces.yaml` change `key` and `value` to `Key` and `Value` then run the test

```shel#
[$processor/filterprocessor] go test -v -run TestLoadingSpans
```

which will fail.  Running the same test on tag `v0.70.0` passes.  

## Expected Result

The tests passes - or maybe fail depending on your POV but I feel like this is an unintended breaking change.

## Actual Result

The tests fails with output

```
    config_test.go:610:
        	Error Trace:	/Users/edwintye/github/opentelemetry-collector-contrib/processor/filterprocessor/config_test.go:610
        	Error:      	Received unexpected error:
        	            	1 error(s) decoding:

        	            	* 'spans.include.attributes[0]' has invalid keys: Key, Value
```

### Collector version

v0.71.0

### Environment information

N/A

### Additional context

I don't know how wild spread this issue is and how many people copy the examples from the README.md.  I have discovered in the filter processor because it broke our deployment but this issue may apply everywhere.
