### ISSUE TITLE
New component: Azure Monitor receiver

### ISSUE THREAD

**Issue by altuner** [open-telemetry/opentelemetry-collector-contrib#18899]
### The purpose and use-cases of the new component

The new receiver would allow to collect Azure Monitor metrics per a subscription/resource group(s) by using Azure REST API.

### Example configuration for the component

```yaml
azure_monitor:
  subscription_id: %SUBSCRIPTION_ID%
  tenant_id: %TENANT_ID%
  client_id: %CLIENT_ID%
  client_secret: %CLIENT_SECRET%
  collection_interval: 60s
  resource_groups: %LIST_OF_RESOURCE_GROUPS%
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.
