### ISSUE TITLE
Count connector - Add dimensions based on OTTL

### ISSUE THREAD

**Issue by greatestusername** [open-telemetry/opentelemetry-collector-contrib#18893]
### Component(s)

connector/count

### Is your feature request related to a problem? Please describe.

Currently metrics output using the count connector may lose context that was available in the source trace/metric/log.

Being able to add attributes from the source trace/metric/log using OTTL would help retain that context.

For example logs containing info about batch processes are counted, during the count important context about which batch and which processors ran the batch job is lost. Being able to add that context to the output metric would be ideal.

### Describe the solution you'd like

The ability to add dimensions to the count metric created by the count processor based off of OTTL (similar to the `statements` used in the transform processor).

Example to add an attribute to `batch.count.metric`  called `new.attribute` based on the attribute `source.attribute` from a source log:
```
connectors:
  count:
    logs:
      batch.count.metric:
        conditions: 
          - attributes["batch.name"] == "*payment.batch*"
        statements:
          - set(attributes["new.attribute"], attributes["source.attribute"]) where attributes["source.attribute"] != nil
```

### Describe alternatives you've considered

This seems like the most straightforward solution that matches other patterns and prior art in the collector contrib.
