### ISSUE TITLE
Azure Monitor exporter exports metric values always as `0` for long counter measurements

### ISSUE THREAD

**Issue by bastbu** [open-telemetry/opentelemetry-collector-contrib#18905]
### Component(s)

exporter/azuremonitor

## Description

When using the Azure Monitor exporter to export metrics using the OTLP exporter, the `customMetrics` showing up in application insights always have `value: 0`.

## Steps to Reproduce

Can be reproduced by taking measurements (e.g. from a [counter](https://opentelemetry.io/docs/reference/specification/metrics/api/#counter)) in a .NET application:

```csharp
using OpenTelemetry;
using OpenTelemetry.Metrics;
using System.Diagnostics.Metrics;

namespace Test;

public class Program
{
    private static readonly Meter MyMeter = new("Test", "1.0");
    private static readonly Counter<long> MyFruitCounter = MyMeter.CreateCounter<long>("MyFruitCounter");

    public static void Main()
    {
        using var meterProvider = Sdk.CreateMeterProviderBuilder()
            .AddMeter("Test")
            .AddOtlpExporter()
            .AddConsoleExporter()
            .Build();

        MyFruitCounter.Add(10, new("name", "apple"), new("color", "red"));
    }
}
```

## Expected Result

As per the above example, the `value` field should be `10` (given a `valueCount` of 1).

## Actual Result

The `value`, `valueMin`, `valueMax` and `valueSum` fields are all `0`:

![image](https://user-images.githubusercontent.com/22341213/221149473-205b45aa-bfa0-49d2-b8ce-9aab59988b56.png)

The console exporter on the test application displays the value to be `10`, which is correct:

```
Resource associated with Metric:
    service.name: unknown_service:dotnet

Export MyFruitCounter, Meter: Test/1.0
(2023-02-24T09:54:09.9409890Z, 2023-02-24T09:54:10.1143793Z] color: red name: apple LongSum
Value: 10
```

### Collector version

0.72.0

## Environment
OS: WSL2 on Windows 11

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols: 
      grpc:
processors:
exporters:
  logging:
  azuremonitor:
    instrumentation_key: <redacted>
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging,azuremonitor]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging,azuremonitor]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging,azuremonitor]
```
