### ISSUE TITLE
Prometheus exporter does not support openmetrics-text 1.0.0

### ISSUE THREAD

**Issue by jonatan-ivanov** [open-telemetry/opentelemetry-collector-contrib#18913]
### Component(s)

exporter/prometheus

## Description
It seems the Prometheus exporter does not support `openmetrics-text 1.0.0`, it only supports `openmetrics-text 0.0.1`. 

## Steps to Reproduce
Scrape the `/metrics` endpoint and request `openmetrics-text 1.0.0`:
```
Accept: application/openmetrics-text; version=1.0.0; charset=utf-8
```

## Expected Result
Result in OpenMetrics format, also the content-type should be:
```
Content-Type: application/openmetrics-text; version=1.0.0; charset=utf-8
```
## Actual Result
Result in Prometheus plaintext format, the content-type says the same:
```
Content-Type: text/plain; version=0.0.4; charset=utf-8
```

### Collector version

otel/opentelemetry-collector-contrib:cdf47846a7ff

## Environment
OS: MacOS 13.2.1

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: '0.0.0.0:9090'
    metric_expiration: 1m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
```

### Additional context

If I scrape the `/metrics` endpoint and request `openmetrics-text 0.0.1`, I get the response in the OpenMetrics format:
```
Accept: application/openmetrics-text; version=0.0.1; charset=utf-8
```
will result in
```
Content-Type: application/openmetrics-text; version=0.0.1; charset=utf-8
```

The problem is that `0.0.1` should not be used, only `1.0.0`.
According to the [OpenMetrics specs](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#overall-structure):
>The content type MUST be: application/openmetrics-text; version=1.0.0; charset=utf-8

Also the Prometheus server uses 1.0.0 for scraping: https://github.com/prometheus/prometheus/issues/9430
