### ISSUE TITLE
[pkg/stanza] Delete after read deletes partially read files

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector-contrib#18926]
### Component(s)

pkg/stanza

## Description
When the collector is shutdown while still in progress reading a file it will delete the file even though it's not fully been read.

## Steps to Reproduce
Setup the `filelog` receiver with `delete_after_read` enabled and target a large file. Start the collector then immediately stop it. The file will be deleted even though the collector didn't finish reading it.

## Expected Result
File is left intact until fully read.

## Actual Result
File is deleted on shutdown when only partially read.

### Collector version

v0.71.0

## Environment
OS: macOS 13.2.1
Compiler(if manually compiled): go 1.20.1

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include: ["/tmp/logs/*.log"]
    start_at: beginning
    delete_after_read: true
exporters:
  logging:

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging]
```
