### ISSUE TITLE
[receiver/hostmetrics] Process CPU Utilization values seem wrong

### ISSUE THREAD

**Issue by antonblock** [open-telemetry/opentelemetry-collector-contrib#19119]
### Component(s)

receiver/hostmetrics

## Description

The calculated per-process utilization values seem very different from what's described in documentation. Instead of values between [0.0, 1.0], I'm seeing values between [-1500.0, 2000.0].

## Steps to Reproduce

Enable collection of `process.cpu.utilization` using the `hostmetrics` receiver. After two collections, the value for all processes will be available in whatever exporter's being used.

## Expected Result

From the doc:

> Percentage of total CPU time used by the process since last scrape, expressed as a value between 0 and 1.

## Actual Result

Values way outside that range, including negative numbers. Below is a screenshot of `process.cpu.utilization` exported to Prometheus over several minutes

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/1297166/221680330-5e338095-2cfa-4322-bf29-e5fe75262d84.png">

### Collector version

848486f5324ee16378b23a9ad44a2e5beae2b78d

## Environment
OS: Ubuntu 20.04
Compiler(if manually compiled): go 1.20.1

### OpenTelemetry Collector configuration

```yaml
receivers:
    hostmetrics/source1:
        collection_interval: 10s
        scrapers:
            process:
                metrics:
                    process.cpu.utilization:
                        enabled: true
exporters:
    prometheus/local:
        endpoint: 127.0.0.1:9000
        namespace: null
        resource_to_telemetry_conversion:
            enabled: true
service:
    pipelines:
        metrics/source1__local:
            receivers:
                - hostmetrics/source1
            exporters:
                - prometheus/local
```

### Additional context

Looking at how this value is calculated, I think the issue is that a single `CPUUtilizationCalculator` is being used to calculate utilization for all processes, not a specific process. Because it resets `previousReadTime` each time it records a metric, the `elapsedTime` value is actually the time elapsed since the last call to the calculator, rather than the collection interval. I think this could be addressed by maintaining a map of PIDs to `CPUUtilizationCalculator`s.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/processscraper/ucal/cpu_utilization_calculator.go#L46
