### ISSUE TITLE
Move README status table to separate machine-readable file

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#19175]
### Describe the issue you're reporting

All components must have a status table describing their stability, supported pipeline types, available distributions and warnings (see #19172 for the latter). This is useful for end-users to understand how to use a component. 

Currently, this table is on each component's README file which makes it difficult to ingest this information. I propose moving this table to a separate machine readable file so that
- we can validate its contents (e.g. validate presence of required fields, validate their values, in the future try to match the metadata with the actual code)
- it's easier to build automated tooling around it, for example to
    - include status information on the component registry,
    - help the community understand what components are available on contrib and what their capabilities are
    - automatically validate OCB manifests (e.g. forbid components with a given warning or below a given stability level)

We can still generate the README table from the machine-readable file by placing a comment marking the position of the table.

To kickstart this we would need to:
- [ ] Define a schema for the component's status table
- [ ] Create a tool to generate README table from the machine-readable file.
- [ ] Migrate existing components to use the machine-readable file and enforce in CI this file for new components

**Comment by djaglowski** [comment]
Taking this a step further, wouldn't it make sense to have such a machine readable file for _all_ standardized parts of the readme? 

For example:
```yaml
class: processor
type: transform
description: modifies telemetry based on configuration using the [OpenTelemetry Transformation Language](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl)
support:
  traces: beta
  metrics: alpha
  logs: alpha
distributions: [contrib]
warnings: # See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19172
-  unsound_transformations
-  identity_conflict
-  orphaned_telemetry
```
