### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by arjan-saly-tfs** [open-telemetry/opentelemetry-collector-contrib#19177]
### Component(s)

receiver/sqlquery

## Description
When starting the otelcol-contrib application, it starts, gives the message: `Everything is ready. Begin running and processing data.` , then after a couple of seconds it fails with this message:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x98 pc=0x4d076c9]
```

## Steps to Reproduce
Start with provided configuration

## Expected Result
OTEL starts running and collecting metrics

## Actual Result
OTEL fails with a runtime error

### Collector version

otelcol-contrib Version 0.71.0

## Environment
OS: Windows 10 Enterprise
System Type: 64-bit operating system, x64-based processor

### OpenTelemetry Collector configuration

```yaml
receivers:
  sqlquery:
    driver: postgres
    datasource: "host=localhost port=5432 user=otel password=<removed> dbname=probeer sslmode=disable"
    queries:
      - sql: "SELECT duration_active_nsec, application_name FROM otel.my_stat_activity"
        metrics:
          - metric_name: query_activity.duration
            value_column: "duration_active_nsec"
            data_type: gauge
            attribute_columns: [ "application_name" ]

service:
  pipelines:
    metrics:
      receivers: [sqlquery]
      processors: [batch, resource]
      exporters: [logging]
```

### Log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x98 pc=0x55076c9]

goroutine 112 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver.dbSQLClient.metricRows.func1()
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver@v0.71.0/db_client.go:71 +0x49
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver.reusableRow.toMetricRow(...)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver@v0.71.0/db_client.go:99
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver.dbSQLClient.metricRows({0xc000abb1e0?, 0xc000270150?, {0xc0008be000?, 0x18?}}, {0x7e5aae0?, 0xc0013e41b0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver@v0.71.0/db_client.go:86 +0x47a
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver.scraper.Scrape({{{0x712d4b7, 0x10}, {0xc00076c2a0, 0x51}}, {{0xc0008be000, 0x48}, {0xc000a60500, 0x1, 0x1}}, {0x2540be400}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver@v0.71.0/scraper.go:63 +0x82
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport(0xc000a770e0, {0x7e5aa70, 0xc00006c040})
        go.opentelemetry.io/collector@v0.71.0/receiver/scraperhelper/scrapercontroller.go:209 +0x223
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1()
        go.opentelemetry.io/collector@v0.71.0/receiver/scraperhelper/scrapercontroller.go:191 +0xd4
created by go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping
        go.opentelemetry.io/collector@v0.71.0/receiver/scraperhelper/scrapercontroller.go:180 +0x56
```

### Additional context

Using this view definition to get some usable metrics on a simple laptop-level test database, while keeping the query in the config very simple:

```
create view otel.my_stat_activity
as
select 
      (extract(epoch from (psa.state_change - psa.query_start)) * 100000000)::INTEGER                               as duration_active_nsec
     ,case when coalesce(psa.application_name,'') = ''  THEN 'Backend process'  else psa.application_name   end     as application_name
     ,psa.client_addr
     ,psa.wait_event_type
     ,psa.wait_event
     ,psa.backend_type
     ,psa.usename
from pg_catalog.pg_stat_activity as psa ;

grant usage on schema otel to otel;
grant select on otel.my_stat_activity to otel;
```

Created in the following context:
Databasename: `Probeer`
Schema: `otel`
Used a superuser to create the view
User for query: `otel`, who has `pg_monitor `privileges

When I login on the database using this command in PowerShell, the view can be queried without any issues:
`psql -U otel -d probeer -h localhost -W`

**Comment by pmcollins** [comment]
Thank you for the report. Will investigate.

**Comment by arjan-saly-tfs** [comment]
@pmcollins @dmitryax , found some additional information that might be of help for you.
## Additional information
It occurred to me that this specific metric can be nil in several cases. This is a valid situation for the database and, to my opinion, should be registered as such. 

However, it seems like the receiver can't handle nil as a value for the metric.

## How to reproduce
This is how this can be reproduced:

### New view
I added a new view, which is the same as the one I already reported, but now nil values are replaced by zero:

```
--drop view otel.my_stat_activity_no_nulls;

create view otel.my_stat_activity_no_nulls
as
select 
      COALESCE(extract(epoch from (psa.state_change - psa.query_start)) * 100000000,0)::INTEGER                     as duration_active_nsec
--      (extract(epoch from (psa.state_change - psa.query_start)) * 100000000)::INTEGER                               as duration_active_nsec      
     ,case when coalesce(psa.application_name,'') = ''  THEN 'Backend process'  else psa.application_name   end     as application_name
     ,psa.client_addr
     ,psa.wait_event_type
     ,psa.wait_event
     ,psa.backend_type
     ,psa.usename
from pg_catalog.pg_stat_activity as psa ;

grant select on otel.my_stat_activity_no_nulls to otel;

select * from otel.my_stat_activity_no_nulls;
```

### Changed config.yaml
I change the OTEL config to look in the new view that replaces nil values by zero:
```
  sqlquery:
    driver: postgres
    datasource: "host=localhost port=5432 user=otel password=<removed> dbname=probeer sslmode=disable"
    queries:
      # - sql: "SELECT duration_active_nsec, application_name FROM otel.my_stat_activity"
      - sql: "SELECT duration_active_nsec, application_name FROM otel.my_stat_activity_no_nulls"
        metrics:
          # - metric_name: thermo.msd.d2i.postgresql.oteltest.query_activity.duration
          - metric_name: query_activity.duration
            value_column: "duration_active_nsec"
            data_type: gauge
            value_type: int
            attribute_columns: [ "application_name" ]
```

When I run this configuration, it starts grabbing the metrics as expected.
When I revert the configuration back to use the original view that returns nil values for metrics, it fails again.

Not sure what the general way of working is in Open Telemetry with respect to nil values in metrics. My humble opinion is that metrics should be handled as they come in. This way it's up to the analyst to decide what to do with it. Drop, replace, report on, show as it is, etc. Also, nil and zero have different impact on averages.

Either way, I don't think a receiver should cause a fatal error like this on a nil value in the metric.

Hope this additional information helps solving the issue.

**Comment by arjan-saly-tfs** [comment]
## Additional information: Nil values in attribute values cause this error as well
Took the previous finding one step further: The receiver also fails when attributes columns hold a nil value.

## How to reproduce
The view provides more columns, which are to be added as additional attribute columns. In the views provided in the original description and the previous comment, these attribute columns can hold nil values, which is a valid situation that means "For this process, this information does not exist.".

### Reproduce the error on attribute columns
So, now I add the columns to the query and the "attribute_columns" in the OTEL configuration:
```
  sqlquery:
    driver: postgres
    datasource: "host=localhost port=5432 user=otel password=<replaced> dbname=probeer sslmode=disable"
    queries:
      # - sql: "SELECT duration_active_nsec, application_name FROM otel.my_stat_activity"
      # - sql: "SELECT duration_active_nsec, application_name FROM otel.my_stat_activity_no_nulls_on_metrics"
      - sql: "SELECT duration_active_nsec, application_name, client_addr, wait_event_type, wait_event, backend_type, usename from otel.my_stat_activity_no_nulls_on_metrics;"
      # - sql: "SELECT duration_active_nsec, application_name, client_addr, wait_event_type, wait_event, backend_type, usename from otel.my_stat_activity_no_nulls;"
        metrics:
          - metric_name: query_activity.duration
            value_column: "duration_active_nsec"
            data_type: gauge
            value_type: int
            # attribute_columns: [ "application_name" ]
            attribute_columns: [ "application_name", "client_addr", "wait_event_type", "wait_event", "backend_type", "usename" ]
```

Again, the OTEL fails at first try to gather metrics. Keep in mind that I use the view where the nil values in the metrics are replaced by zero, so they are not causing this:
```
2023-03-03T13:03:26.619+0100    info    service/service.go:157  Everything is ready. Begin running and processing data.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x98 pc=0x56776c9]

goroutine 96 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver.dbSQLClient.metricRows.func1()
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver@v0.71.0/db_client.go:71 +0x49
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver.reusableRow.toMetricRow(...)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver@v0.71.0/db_client.go:99
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver.dbSQLClient.metricRows({0xc00127e750?, 0xc000731260?, {0xc001271040?, 0x18?}}, {0x7fcaae0?, 0xc00127ccc0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver@v0.71.0/db_client.go:86 +0x47a
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver.scraper.Scrape({{{0x729d4b7, 0x10}, {0xc000f700b0, 0xa7}}, {{0xc001271040, 0x9e}, {0xc000f3cd20, 0x1, 0x1}}, {0x2540be400}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlqueryreceiver@v0.71.0/scraper.go:63 +0x82
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport(0xc000a72240, {0x7fcaa70, 0xc000072030})
        go.opentelemetry.io/collector@v0.71.0/receiver/scraperhelper/scrapercontroller.go:209 +0x223
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1()
        go.opentelemetry.io/collector@v0.71.0/receiver/scraperhelper/scrapercontroller.go:191 +0xd4
created by go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping
        go.opentelemetry.io/collector@v0.71.0/receiver/scraperhelper/scrapercontroller.go:180 +0x56
```

### Reproduce no error on attribute columns
For this I create another new view where all nil values in the attributes are replaced by an empty string ('') or in case of the ip address the fictional value '1.1.1.1', as PostgreSQL won't accept an empty string for datatype inet:
```
/*************************************************************************************************************************************************
 * Replace nills on metric and attributes
 *************************************************************************************************************************************************/
drop view otel.my_stat_activity_no_nulls;

create view otel.my_stat_activity_no_nulls
as
select 
      COALESCE(extract(epoch from (psa.state_change - psa.query_start)) * 100000000,0)::INTEGER                         as duration_active_nsec     
     ,case when coalesce(psa.application_name,'') = ''  THEN 'Backend process'      else psa.application_name   end     as application_name
     ,coalesce(psa.client_addr      ,'1.1.1.1')                                                                         as client_addr                                                                                                                
     ,coalesce(psa.wait_event_type  ,'')                                                                                as wait_event_type
     ,coalesce(psa.wait_event       ,'')                                                                                as wait_event     
     ,coalesce(psa.backend_type     ,'')                                                                                as backend_type   
     ,coalesce(psa.usename          ,'')                                                                                as usename        
from pg_catalog.pg_stat_activity as psa ;

grant select on otel.my_stat_activity_no_nulls to otel;

select * from otel.my_stat_activity_no_nulls;
```

And I change the OTEL configuration to start using this view:
```
  sqlquery:
    driver: postgres
    datasource: "host=localhost port=5432 user=otel password=<replaced> dbname=probeer sslmode=disable"
    queries:
      # - sql: "SELECT duration_active_nsec, application_name FROM otel.my_stat_activity"
      # - sql: "SELECT duration_active_nsec, application_name FROM otel.my_stat_activity_no_nulls_on_metrics"
      # - sql: "SELECT duration_active_nsec, application_name, client_addr, wait_event_type, wait_event, backend_type, usename from otel.my_stat_activity_no_nulls_on_metrics;"
      - sql: "SELECT duration_active_nsec, application_name, client_addr, wait_event_type, wait_event, backend_type, usename from otel.my_stat_activity_no_nulls;"
        metrics:
          - metric_name: query_activity.duration
            value_column: "duration_active_nsec"
            data_type: gauge
            value_type: int
            # attribute_columns: [ "application_name" ]
            attribute_columns: [ "application_name", "client_addr", "wait_event_type", "wait_event", "backend_type", "usename" ]
```

Now OTEL starts gathering data nicely as it should.

However, it is not gathering the entire truth as nil is replaced by an empty string, which in the backend can result in different alerts or report-effects and the unknown IP address (valid for internal processes) is replaced by some value, which is never correct.

Again, hope this helps solving the issue better and/or faster.
