### ISSUE TITLE
New component: Faro Receiver

### ISSUE THREAD

**Issue by rlankfo** [open-telemetry/opentelemetry-collector-contrib#19180]
### The purpose and use-cases of the new component

The purpose of this component would be to ingest telemetry data sent from [Grafana Faro](https://github.com/grafana/faro-web-sdk). 

### Example configuration for the component

```yaml
receivers:
  faro:
    http:
  faro/withcors:
    http:
      cors:
        allowed_origins:
          - *
```
      

### Telemetry data types supported

- Logs
- Traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

@dehaansa 

### Additional context

The Grafana Faro Web SDK is a highly configurable open source JavaScript agent that can easily be embedded in web applications to collect real user monitoring (RUM) data: performance metrics, logs, exceptions, events, and traces.
