### ISSUE TITLE
[exporter/prometheusremotewriteexporter]: context deadline exceeded error

### ISSUE THREAD

**Issue by Ishmeet** [open-telemetry/opentelemetry-collector-contrib#19211]
### Component(s)

exporter/prometheusremotewrite

## Description

I am getting context timeout errors from prometheus remote write exporter. 

```
2023-03-06T09:21:19.694Z	error	exporterhelper/queued_retry.go:401	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: Permanent error: Post \"https://k8s-grpc-3589420cb5-576032121.us-west-2.elb.amazonaws.com/cn2-analytics-term/receive\": context deadline exceeded; Permanent error: Permanent error: Post \"https://k8s-grpc-3589420cb5-576032121.us-west-2.elb.amazonaws.com/cn2-analytics-term/receive\": context deadline exceeded", "errorCauses": [{"error": "Permanent error: Permanent error: Post \"https://k8s-grpc-3589420cb5-576032121.us-west-2.elb.amazonaws.com/cn2-analytics-term/receive\": context deadline exceeded"}, {"error": "Permanent error: Permanent error: Post \"https://k8s-grpc-3589420cb5-576032121.us-west-2.elb.amazonaws.com/cn2-analytics-term/receive\": context deadline exceeded"}], "dropped_items": 9191}
```

## Steps to Reproduce

My config
```
      prometheusremotewrite:
        endpoint: "https://k8s-grpc-3589420cb5-576032121.us-west-2.elb.amazonaws.com/cn2-analytics-term/receive"
        tls:
          insecure: false
          insecure_skip_verify: true
        external_labels:
          cluster_name: cluster_test
    service:
      pipelines:
        metrics:
          receivers: [prometheus/3]
          exporters: [prometheusremotewrite]
```

## Expected Result
Metrics received on Thanos.
## Actual Result
Remote write error

### Collector version

0.72.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
2023-03-06T09:25:19.493Z	error	exporterhelper/queued_retry.go:401	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: Permanent error: Post \"https://k8s-grpc-3589420cb5-576032121.us-west-2.elb.amazonaws.com/cn2-analytics-term/receive\": context deadline exceeded; Permanent error: Permanent error: Post \"https://k8s-grpc-3589420cb5-576032121.us-west-2.elb.amazonaws.com/cn2-analytics-term/receive\": context deadline exceeded", "errorCauses": [{"error": "Permanent error: Permanent error: Post \"https://k8s-grpc-3589420cb5-576032121.us-west-2.elb.amazonaws.com/cn2-analytics-term/receive\": context deadline exceeded"}, {"error": "Permanent error: Permanent error: Post \"https://k8s-grpc-3589420cb5-576032121.us-west-2.elb.amazonaws.com/cn2-analytics-term/receive\": context deadline exceeded"}], "dropped_items": 9186}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector@v0.72.0/exporter/exporterhelper/queued_retry.go:401
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
	go.opentelemetry.io/collector@v0.72.0/exporter/exporterhelper/metrics.go:136
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector@v0.72.0/exporter/exporterhelper/queued_retry.go:205
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
	go.opentelemetry.io/collector@v0.72.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61
```
