### ISSUE TITLE
New component: Filebeat Receiver

### ISSUE THREAD

**Issue by shrenikjain38** [open-telemetry/opentelemetry-collector-contrib#19365]
### The purpose and use-cases of the new component

This is a receiver which is able to accept [lumberjack](https://github.com/elastic/logstash-forwarder/blob/master/PROTOCOL.md) protocol events from filebeat agent.

Impact/Why is it needed:

1. Support for ingesting logs from one of the most [widely adopted](https://www.datanyze.com/market-share/logging--322/logstash-market-share) log collection agent i.e., [filebeat](https://www.elastic.co/beats/filebeat).
2. Complimentary addition alongside currently existing fluentforward receiver which is able to receive log data from [fluentbit](https://fluentbit.io/).

Implementation Details:

1. It includes a go-lumber [server](https://github.com/elastic/go-lumber/tree/main/server) which supports both lumberjack v1 and v2.
2. A translation layer which converts lumberjack events to logs in [otlp log format](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto), it adds the filebeat event fields apart from "message" field as resource attributes in otlp log object.

### Example configuration for the component

```yaml
receivers:
  filebeat:
    endpoint: "0.0.0.0:5044"
    tls:
      ca_file: "/abc"
      cert_file: "/abcd"
      key_file: "/abcde"
      min_version: "abcdef"
      max_version: "abcdefg"
      reload_interval: 20
```

### Telemetry data types supported

Logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.
