### ISSUE TITLE
[traces/processor] Processor to take actions on span events

### ISSUE THREAD

**Issue by yehaotian** [open-telemetry/opentelemetry-collector-contrib#19381]
### Is your feature request related to a problem? Please describe.

The open source library will automatically add span events which seems not useful, for example:

```
message
message.type:
"RECEIVED"
message.id:
"..."
message.uncompressed_size:
"..."

message
message.type:
"SENT"
message.id:
"..."
message.uncompressed_size:
"..."
```
It is good to have a processor can do actions like insert/update/delete to the span events.
The current processors seem not able to achieve this, and I do see OTTL may help on filter span events but the documentation is not clear enough.

### Describe the solution you'd like

A processor for spans event could do actions like insert/update/delete, similar as attributes processor.
For deletion part, it may provide condition check, like delete based on events attribute/name, or just delete all events when no condition provided.

**Comment by atoulme** [comment]
The `transformprocessor` should do the job. Please take a look and see if this supports your use case, thanks!

**Comment by yehaotian** [comment]
Not sure if i get the idea:
```
transform:
  error_mode: ignore
  trace_statements:
    - context: spanevent
      statements:
        - truncate_all(attributes, 4096)
```
How can I truncate all events instead of just attributes? There are a lot of path for [span event context](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottlspanevent)

**Comment by atoulme** [comment]
Pinging the transform processor maintainers as they might have a better idea than me about this.

**Comment by evan-bradley** [comment]
The transform processor doesn't support filtering telemetry and the OTTL currently has limited support for modifying slice values. If you're looking to filter span events, I would suggest using [OTTL conditions in the filter processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#ottl). A configuration like this would filter out all span events from a pipeline:

```yaml
processors:
  filter:
    traces:
      spanevent:
        - 'true'
```

If you want to modify span events, you can use the `spanevent` context in the transform processor.

**Comment by TylerHelmuth** [comment]
@evan-bradley is correct: use `filterprocessor` to drop span events, use `transformprocessor` to modify span events.

If there is any updates in filterprocessor, transformprocessor, or OTTL documentation that would have been helpful please let us know.

**Comment by yehaotian** [comment]
Thanks for the help, does that mean to filter span events with name = "message", I need to have:

```
processors:
  filter:
    traces:
      spanevent:
        - 'name == message'
```
which is something added by [otel go contrib instrumentation](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/3311cc2a734d7597598cc67910f8f292d13eeda7/instrumentation/google.golang.org/grpc/otelgrpc/interceptor.go#L44):

**Comment by TylerHelmuth** [comment]
Correct.  That configuration will drop from the collector any span event named `message`.

**Comment by TylerHelmuth** [comment]
Your original config looks correct to me. If you add the loggingexporter to your exporters with loglevel: debug what does your data look like?

**Comment by yehaotian** [comment]
Verified this is working, thanks for the help!
A follow up questions on the filter processor, when use `exclude` for spans, does it mean just skip the rest of pipeline on processors? Because the behavior I observe is that spans will still get exported
```
  filter/spans:
    spans:
      exclude:
        match_type: regexp
        attributes:
          - key: path
            value: .*health.*
        span_names:
          - .*health.*
```

**Comment by TylerHelmuth** [comment]
According to the docs:

```
It takes a pipeline type, of which logs metrics, and traces are supported, followed by an action:
  include: Any names NOT matching filters are excluded from remainder of pipeline
  exclude: Any names matching filters are excluded from remainder of pipeline
```

If something matches in `exclude` it will be dropped from the collector, but all conditions have to be true for the drop to occur. In your case the span name must match `.*health.*` AND the span must have an attribute named `path` that matches `.*health.*`

I find the `include`/`exclude` configuration confusing, so I opt for OTTL.  With OTTL it would look like:

```yaml
processors:
  filter/span:
    error_mode: ignore
    traces:
      span:
        - 'IsMatch(attributes["path"], ".*health.*") == true and IsMatch(name, ".*health.*") == true'
```

If you wanted to drop the span if either of those conditions are true (like an OR) it would be

```yaml
processors:
  filter/span:
    error_mode: ignore
    traces:
      span:
        - 'IsMatch(attributes["path"], ".*health.*") == true'
        - 'IsMatch(name, ".*health.*") == true'
```

Note that in both cases we're operating on spans, not span events.
