### ISSUE TITLE
Azure Monitor exporter does not export metric attributes

### ISSUE THREAD

**Issue by bastbu** [open-telemetry/opentelemetry-collector-contrib#19407]
### Component(s)

exporter/azuremonitor

## Description

The Azure Monitor exporter should export metric attributes as `customDimensions`. Currently it does not export metric attributes (dimensions) to Azure Monitor. 

## Steps to Reproduce

Run the following sample (slight variation of the getting started section [from the OTel .NET docs](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/getting-started)):

```csharp
public class Program
{
    private static readonly Meter MyMeter = new("OtelTest", "1.0");
    private static readonly Counter<long> MyFruitCounter = MyMeter.CreateCounter<long>("MyFruitCounter");

    public static void Main()
    {
        using var meterProvider = Sdk.CreateMeterProviderBuilder()
            .AddMeter("OtelTest")
            .AddOtlpExporter()
            .AddConsoleExporter()
            .Build();

        MyFruitCounter.Add(1, new("name", "apple"), new("color", "red"));
    }
}
```

## Expected Result

The console exporter shows the information an expected result could contain:

```
Resource associated with Metric:
    service.name: unknown_service:oteltest

Export MyFruitCounter, Meter: OtelTest/1.0
(2023-03-08T17:09:25.3912339Z, 2023-03-08T17:09:25.7726745Z] color: red name: apple LongSum
Value: 1
```

Note the `color: red name: apple` snippet. Application Insights should contain the same information.

## Actual Result

The information about the attributes cannot be found in Application Insights.

### Collector version

0.72

## Environment
OS: WSL on Windows 11

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols: 
      grpc:
processors:
exporters:
  logging:
  azuremonitor:
    instrumentation_key: <redacted>
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging,azuremonitor]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging,azuremonitor]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging,azuremonitor]
```
