### ISSUE TITLE
Support Persistent queue for Elasticsearch exporter

### ISSUE THREAD

**Issue by raghu999** [open-telemetry/opentelemetry-collector-contrib#19424]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

   Otel collector fails to start when we configure Elasticsearch exporter to use the [persistent-queue](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper#persistent-queue) with [file storage extension ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage) 

   
   **Error**
```
   kubectl logs -f otel-collector-0
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': error reading configuration for "elasticsearch/log": 1 error(s) decoding:

* '' has invalid keys: retry_on_failure, sending_queue
2023/03/09 15:14:22 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': error reading configuration for "elasticsearch/log": 1 error(s) decoding:

* '' has invalid keys: retry_on_failure, sending_queue
```
   
   **Configuration which fails**:
   
   ```
    extensions:
      file_storage/buffer:
         directory: /buffer
         timeout: 10s # in what time a file lock should be obtained
         compaction:
           directory: /buffer
           on_start: true
           on_rebound: true
           rebound_needed_threshold_mib: 512
           rebound_trigger_threshold_mib: 256

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
      resource:
        attributes:
          - key: test.key
            value: "test-value"
            action: insert

    exporters:
      elasticsearch/log:
        endpoints: ["${ELK_URL}"]
        logs_index: "logs-test"
        user: "${ELK_USERNAME}"
        password: "${ELK_PASSWORD}"
        tls:
          insecure_skip_verify: true
          retry_on_failure:
           enabled: true
           initial_interval: 1s
           max_interval: 300s
           max_elapsed_time: 120s
         sending_queue:
           storage: file_storage/psq
      logging:
        verbosity: detailed

    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
        logs:
          level: "info"
      extensions: [file_storage/buffer]
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [elasticsearch/log, logging]
          ```

### Describe the solution you'd like

Use the existing [file storage extension ](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage)  exporter helper for enabling support for persistent queue.
