### ISSUE TITLE
[cmd/mdatagen] Introduce metric groups 

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#19440]
## Problem

Currently, the hostmetrics receiver has several scrapers, each of them having its metadata.yaml file. There are a couple of problems with this approach:

- It prevents the adoption of other receiver-specific metadata fields that require only one metadata.yaml file per receiver https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19175

- The current hostmetrics receiver `scrapers` configuration interface doesn't allow overriding values, e.g., "disable a scraper that is enabled in a config that I want to override". It's a pretty important feature in the helm chart where the host metrics collection is enabled by one option, but the default set of scrapers cannot be reduced, so users have to disable all metrics in the detectors that they don't need one by one.

## Proposed solution

Because of these issues and to solve other user needs to be described below, I'm suggesting another interface for scraping receivers with metrics that can be split into meaningful groups. Each group can be disabled/enabled like it's currently done for metrics.

### metadata.yaml interface

metadata.yaml interface will get an extra field called `metric_groups` and all the metrics definitions will be moved under particular groups. 

- Each metric group has a set of metrics assigned to the group under `metrics` field. 

- Additional field to be added in the metrics group `enabled`:
  - if `enabled: true`, all the default metrics within the group (defined with `enabled: true`) will be emitted by default.
  - if `enabled: false`, none of the metrics within the group will be emitted by default.

- Additionally, we may have an optional `warnings` field similar to what each metric field currently can use. Using that field, we can proactively warn users about upcoming changes in the group, such as turning the group from optional to default, deprecation, replacement, etc.

The updated metadata.yaml schema will look the following:

```yaml
metric_groups:
  metric_group_1:
    enabled: <true|false>
    metrics:
      metric_1:
        enabled: <true|false>
      metric_2:
        enabled: <true|false>
    warnings:
      if_enabled: "a warning that will be displayed if the metric group is enabled in user config."
      if_enabled_not_set: "a warning that will be displayed if `enabled_metrics` field is not set explicitly in user config."
      if_configured: "a warning that will be displayed if a user configures the metrics group in any way."
```

If a receiver doesn't have logical groups to split the metrics, all the metrics should be defined in a group with `default` name.

### User config interface

Splitting metrics into groups gives users more flexibility in controlling what metrics they want to collect. Using groups, we can allow new patterns of disabling/enabling metrics, such as enabling all metrics from a particular group, enabling default metrics from a particular group, or disabling all group's metrics. For that, we need more than just a boolean `enabled` field in the user config for metrics groups. The following interface can be provided to user:

```yaml
metric_groups:
  metric_group_1:

    # none: none of the group's metrics are emitted
    # default: only the group's default metrics are emitted
    # all: all group's default metrics are emitted
    enabled_metrics: <none|default|all>

    metrics:
      metric_1
        # this field always has the highest precedence to allow use cases like "enable all metrics from group_1 except for metric_1"
        enabled: <true|false>
```
 
### Developer interface

Developer API should not be changed in any way other than introducing additional configuration structures for metric groups. Most existing receivers don't need to change anything because of how the `metadata.MetricsBuilderConfig` struct is added to the receivers config. But, if a receiver author wants to customize the user configuration interface, they can still use the embedded structures directly instead of `metadata.MetricsBuilderConfig`. That customization would be required for hostmetrics receiver to add additional configuration options for the metric groups that are currently defined for each scraper, e.g., `IncludeVirtualFS` in the filesystem scraper.

### Migration

The main problem of the migration is moving all the existing user settings for metrics from the receivers config layer to a metrics group layer, probably `metric_groups.default` for most cases. cmd/mdatagen tool can help with that migration by generating temporary support for the `metrics` field on both layers and generating depreciation messages for users to update their configs.
