### ISSUE TITLE
Processors should remove SchemaURL when transformations violate semantic conventions

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-collector-contrib#19472]
### Component(s)

processor/attributes, processor/cumulativetodelta, processor/deltatorate, processor/groupbyattrs, processor/logstransform, processor/metricstransform, processor/resource, processor/transform

## Description

When using a processor to alter telemetry that has a valid Telemetry Schema URL, it's possible/likely that the processor could cause the telemetry to violate the associated schema.

## Steps to Reproduce

- Create telemetry using https://github.com/open-telemetry/opentelemetry-specification/blob/main/schemas/1.20.0
- Manually rename attribute `net.protocol.name` back to `net.app.protocol.name` via the attributes processor

Telemetry now violates the schema

## Expected Result

The renamed span should be in a new InstrumentationScope that does NOT include a SchemaURL.

## Actual Result

The renamed span remains in an InstrumentationScope that declares compatibility with 1.20.0 of the semantic conventions.

### Collector version

v0.73.0

## Environment
The otel-collector-contrib docker image

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
exporters:
  logging:
processors:
  attributes/bad:
    actions:
      - key: net.app.protocol.name
        action: insert
        from_context: net.protocol.name
      - key: net.protocol.name
        action: delete
pipelines:
  traces:
    receivers: [otlp]
    processors: [attributes/bad]
    exporters: [logging]
```

### Additional context

This is targeted at the viability of SchemaURL itself and its enforceability through the ecosystem.

- Can we simplify processing telemetry so SchemaURL is dropped whenever its guarantees would be violated?
- Do we have the right tools in place to determine, detect and enforce this?
- What does the collector need to make this portion of the specification as easy as possible to deal with?

cc @tigrannajaryan
