### ISSUE TITLE
metric not available for Monitoring 

### ISSUE THREAD

**Issue by sanjaygopinath89** [open-telemetry/opentelemetry-collector-contrib#1958]
**Describe the bug**
As described in https://github.com/open-telemetry/opentelemetry-collector/blob/master/docs/monitoring.md I am trying to setup monitoring for OTEL collector/agent. 

I am staring the controller with metric level as DETAILED(command shown below), but i am not able to find most of the metric given in above doc . I can only find some basic metric like CPU, Memory , Process up time , etc... 

otelcontribcol --config=otel-config.yaml --metrics-level=DETAILED

2021-01-07T04:47:26.367-0800    info    service/telemetry.go:101        Serving Prometheus metrics      {"address": ":8888", "level": 2, "service.instance.id": "39c5d871-f4e9-423f-a733-1cbed7f26807"}

**Metric Exposed** :

```
# HELP otelcol_process_cpu_seconds Total CPU user and system time in seconds
# TYPE otelcol_process_cpu_seconds gauge
otelcol_process_cpu_seconds{service_instance_id="96d1c96e-b0f9-4ebb-9e91-ed69033e35d9"} 0.14
# HELP otelcol_process_memory_rss Total physical memory (resident set size)
# TYPE otelcol_process_memory_rss gauge
otelcol_process_memory_rss{service_instance_id="96d1c96e-b0f9-4ebb-9e91-ed69033e35d9"} 3.1186944e+07
# HELP otelcol_process_runtime_heap_alloc_bytes Bytes of allocated heap objects (see 'go doc runtime.MemStats.HeapAlloc')
# TYPE otelcol_process_runtime_heap_alloc_bytes gauge
otelcol_process_runtime_heap_alloc_bytes{service_instance_id="96d1c96e-b0f9-4ebb-9e91-ed69033e35d9"} 8.717144e+06
# HELP otelcol_process_runtime_total_alloc_bytes Cumulative bytes allocated for heap objects (see 'go doc runtime.MemStats.TotalAlloc')
# TYPE otelcol_process_runtime_total_alloc_bytes gauge
otelcol_process_runtime_total_alloc_bytes{service_instance_id="96d1c96e-b0f9-4ebb-9e91-ed69033e35d9"} 1.4813704e+07
# HELP otelcol_process_runtime_total_sys_memory_bytes Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')
# TYPE otelcol_process_runtime_total_sys_memory_bytes gauge
otelcol_process_runtime_total_sys_memory_bytes{service_instance_id="96d1c96e-b0f9-4ebb-9e91-ed69033e35d9"} 7.4531072e+07
# HELP otelcol_process_uptime Uptime of the process
# TYPE otelcol_process_uptime counter
otelcol_process_uptime{service_instance_id="96d1c96e-b0f9-4ebb-9e91-ed69033e35d9"} 5.006466413
```

Expected metrics : 
otelcol_processor_dropped_spans
otelcol_receiver_accepted_spans 

Version tried : 
 otel-contrib-collector 0.17.0
 otel-contrib-collector 0.13.0

**Steps to reproduce**
1. Install otel-contrib-collector 0.17.0/otel-contrib-collector 0.13.0 in linux server with rpm or use the docker image. 
2. Start the controller 
    otelcontribcol --config=otel-config.yaml --metrics-level=DETAILED
3.. hit the endpoint http://<ip>:8888/metrics to check the metrics . 

**What did you expect to see?**
Expected to see blow metrics , as given in https://github.com/open-telemetry/opentelemetry-collector/blob/master/docs/monitoring.md
otelcol_processor_dropped_spans
otelcol_receiver_accepted_spans 

**What did you see instead?**
Only basic metrics are there , the above listed metric are not available. 

**What version did you use?**
 otel-contrib-collector 0.17.0
 otel-contrib-collector 0.13.0

**What config did you use?**
Config: 

```
receivers:
  otlp/jaeger:
    protocols:
      grpc:
        endpoint: "0.0.0.0:55682"
  otlp/signalfx:
    protocols:
      grpc:
        endpoint: "0.0.0.0:55683"
exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger.collector.endpoint.com:31250
    insecure: true
    retry_on_failure:
      initial_interval: 5s
      max_elapsed_time: 300s
  sapm:
    access_token: "${SIGNALFX_ACCESS_TOKEN}"
    endpoint: "https://signalfx.endpoint/trace"
processors:
  memory_limiter:
    ballast_size_mib: 500
    check_interval: 5s
    limit_percentage: 50
    spike_limit_percentage: 25
  batch:
    send_batch_size: 1000
    timeout: 2s
  resource:
    attributes:
    - key: k8s.cluster.name
      value: "test-cluster"
      action: upsert
service:
  pipelines:
    traces/jaeger:
      receivers: [otlp/jaeger]
      processors: [memory_limiter,batch,resource]
      exporters: [logging,jaeger]
	traces/signalfx:
      receivers: [otlp/signalfx]
      processors: [memory_limiter,batch,resource]
      exporters: [logging,sapm]
```

**Environment**
OS: Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Additional context**
When I use  otel-collector instead of otel-collector-contrib , then I am seeing more metrics, but still some metrics are missing .
