### ISSUE TITLE
Allow to set metrics namespace for service graph processor 

### ISSUE THREAD

**Issue by anneelisabethlelievre** [open-telemetry/opentelemetry-collector-contrib#19628]
### Component(s)

processor/servicegraph

### Is your feature request related to a problem? Please describe.

Feature request to add an prefix to metric names emitted by service graph processor.  I am currently using the span metrics processor with the prometheus remote write exporter and I would like to use the same exporter and add the service graph processor. But with this new processor, I would like to set the namespace in the processor side to be able to send the right metrics according to the [Grafana Service Graph](https://grafana.com/docs/tempo/latest/metrics-generator/service_graphs/#metrics) doc.

Let me know if there something I don't understand correctly.

### Describe the solution you'd like

Add namespace support for service graph processor.

ex:

```
processors:
  servicegraph:
    metrics_exporter: prometheus/servicegraph # Exporter to send metrics to
    namespace: traces_service_graph
```

### Additional context

I can contribute to this new feature.
