### ISSUE TITLE
Missing resource tags in logs-pipeline

### ISSUE THREAD

**Issue by arjan-saly-tfs** [open-telemetry/opentelemetry-collector-contrib#19648]
### Component(s)

exporter/datadog

### Situation description

I'm reading metrics using PostgreSQL & SQL Query receivers as well as application log files using the filelog-receiver.
The results, I write to our Datadog account for further analysis.

To distinct between metrics delivered by Otel and those delivered by the Datadog Agent, I make sure I have the following additional configurations in the otelcol-contrib configuration file:

1. In the datadog exporter settings, I override the hostname by adding an OTEL-test postfix and make sure all attributes are passed through as tags:

```
exporters:
  datadog:
    hostname: ${env:COMPUTERNAME}-OTEL-test
    api:
      key: <undisclosed>
    metrics:
      ## @param resource_attributes_as_tags - string - optional - default: false
      ## Set to true to add all resource attributes of a metric to its metric tags.
      ## When set to false, only a small predefined subset of resource attributes is converted
      ## to metric tags.
      #
      resource_attributes_as_tags: true
```

2. Using the resource processor, I add additional attributes to each record:
```
processors:
  batch:
  resource:
    attributes:
    - key: metric-source
      value: otel
      action: insert
    - key: source
      value: otel
      action: insert
```
I also use the logging exporter on detailed verbosity, so I can get an impression of what happens.

### Issue
When I run otelcol-contrib, I can easily find my metrics based on the distinct hostname as well as by filtering on the metric-source tag. Unfortunately the source tag does not seem to appear in Datadog.

The real issue is that none of these appear for the log-records. The host-tag as well as hostname tag remain empty, the metric-source tag is not found and the source tag is set to "undefined". 

When I add this line to the filelog-receiver config, the value is found in the list for the service facet on the left of the log-screen in datadog, to filter on. But the source is not found in the facet-list for source. I can manually filter of @source though:
`    attributes: { source: otel-postgres-serverlog, service: postgres-a }`
Adding a value for host like this doesn't work either. The value for host remains empty.

Note that the service value should be "postgres" rather than "postgres-a", just added the "-a" for distinction. It should be postgres in this case as I'm reading PostgreSQL logfiles.

Currently the records are very hard to find without proper tagging. Also, we can't distinct between log-records coming from different servers there doesn't seem to be a tag showing which server sent the metrics. By result, the logrecords become useless once we start using this on multiple servers.

### Preferred solution
I would like to have the following options:
1. Have the system's hostname or the override in the datadog-exporter-settings in the host-tag, just like I have for the metrics
2. Have a distinct content for datadog source tag either by OTEL configuration or by fixed value set by the datadog-exporter

Note: Not sure if this is a bug, feature request or quest for help……

Thanks for helping me out…..

**Comment by dineshg13** [comment]
@arjan-saly-tfs This looks like new request. Do you have sample logs that being sent to DD ?

**Comment by arjan-saly-tfs** [comment]
Hi @dineshg13,

### Collector config
Here is the complete configuration (passwords and datadog API key removed). 
```
receivers:
  postgresql:
    endpoint: localhost:5432
    transport: tcp
    username: otel
    password: <NotDisclosed>
    databases: []
    collection_interval: 10s
    tls:
      insecure: true
      insecure_skip_verify: true
  sqlserver:
    collection_interval: 10s
  sqlquery/postgresql:
    driver: postgres
    datasource: "host=localhost port=5432 user=otel password=<NotDisclosed> dbname=probeer sslmode=disable"
    queries:
      - sql: "SELECT duration_active_nsec, application_name, client_addr, wait_event_type, wait_event, backend_type, usename from otel.my_stat_activity_no_nulls;"
        metrics:
          - metric_name: postgresql.oteltest.database_activity.duration
               value_column: "duration_active_nsec"
            description: "Activity Duration of database workers / processes"
            data_type: gauge
            value_type: int
            unit: nanosecond
               attribute_columns: [ "application_name", "client_addr", "wait_event_type", "wait_event", "backend_type", "usename" ]
  sqlquery/sqlserver:
    driver: sqlserver
    # datasource: "sqlserver://user:password@host/instance?param1=value&param2=value"
    datasource: "sqlserver://otel:<NotDisclosed>@localhost"
    queries:
      - sql: "select coalesce(sum(waittime),0) as waittime, coalesce(rtrim(lastwaittype),'') as lastwaittype, coalesce(rtrim(db_name(dbid)),'') as db, coalesce(rtrim(cmd),'') as command_type, coalesce(rtrim(loginame),'') as loginame from sys.sysprocesses group by lastwaittype, db_name(dbid), cmd, loginame"
        metrics:
          - metric_name: thermo.msd.d2i.sqlserver.oteltest.session.wait_time
            value_column: "waittime"
            description: "Session Waittime in milliseconds by database, commandtype, last waittype and user"
            data_type: gauge
            value_type: int
            unit: millisecond
            attribute_columns: [ "lastwaittype", "db", "command_type", "loginame" ]
  filelog/postgres:
    include: [ C:\DS-Test Logfiles\For OTEL read\*.log ]
    attributes: { source: otel-postgres-serverlog, service: postgres-a }
    # resource: { source: otel-postgres-serverlog-r, service: postgres-r }    
    start_at: beginning
    multiline: 
      line_start_pattern: (^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3} [A-Z]+)
    operators:
      - type: regex_parser
        # Regex for timestamp format: yyyy-mm-dd HH24-mi-ss.fff <TimeZoneCode> , for example: 2021-08-20 06:33:42.076 CEST
        #   Bit more details: 
        #       - ?P<timestamp_field> = Python specific definition to wrap the result of the expression into a field, refered to later by" parse_from". Used in other languages as well
        #       - ^                   = Expect the expression to be at the start of the string, or at the beginning of a line if multiline is enabled
        #       - \d                  = Expect any digit character (0-9)
        #       - {x}                 = Expect x of the preceding token (e.g. \d{2} = expect 2 digits)
        #       - - : . <space>       = These are expected as literal characters
        #       - [A-Z]               = Expect an aphabetical character 
        #       - +                   = Expect one or more of the preceding token. Hence the whole TimeZone code is taken here as it's followed by a space, which does not match [A-Z].
        #       - .*?                 = Any character exept new line character (.), any amount of characters (*), but may not be there as well (?)
        #       - ((.|\n)*)            = Any character exept new line character (.) or (|) new line character (\n), both within brackets to apply the any amount of characters (*) and optionally no characters (?) to both . and /n
        #
        # Use this page to test the regex: https://regex101.com/
        # regex: (?P<timestamp_field>^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3} [A-Z]+)
        regex: (?P<timestamp_record>^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3} [A-Z]+) pid=\[(?P<procid>\d+)\] line=\[(?P<linenr>\d+)\] usr=\[(?P<user>(.*?))\] db=\[(?P<dbname>(.*?))\] app=\[(?P<appname>(.*?))\] host=\[(?P<connected_host>(.*?))\] sessid=\[(?P<sessionid>(.*?))\] transid=\[(?P<transactionid>(.*?))\] sqlerr=\[(?P<sqlerror>(.*?))\] (?P<message>((.|\n)*))
        timestamp:
          layout: "%Y-%m-%d %H:%M:%S.%L %Z"
          parse_from: attributes.timestamp_record
      - type: regex_parser
        parse_from: attributes.message
        # Not all records hold duration information in the remainer field. The if makes sure duration is extracted only when it's really there AND that otel doesn't report an error if duration is not there.
        if: attributes.message matches "(LOG:( *)((duration)|(DURATION)):(.*)((.|\n)*))"
        regex: (?P<message_severity>LOG):( *)((duration)|(DURATION)):( *)(?P<query_duration>((\d+(\.\d*)?)|(\.\d+))) (?P<query_duration_unit>\w+)( *)(((statement:)|(STATEMENT:))( *)(?P<query_statement>((.|\n)*))|(?P<message_details>((.|\n)*)))
      - type: regex_parser
        parse_from: attributes.message
        # Not all records hold duration information in the remainer field. Some of the remaining messages hold the exact statement only. This one grabs the statement and puts it in a specific statement attribute
        if: attributes.message not matches "(LOG:( *)((duration)|(DURATION)):(.*)((.|\n)*))" and attributes.message matches "((^CONTEXT:)|(^context)|(^STATEMENT)|(^statement)|(^QUERY)|(^query))"
        regex: (?P<message_severity>((CONTEXT)|(context)|(STATEMENT)|(statement)|(QUERY)|(query))):( *)(SQL statement ")?(?P<query_statement>((.|\n)*))"?
      - type: regex_parser
        parse_from: attributes.message
        # Not all records hold duration information in the remainer field. This one handles the remaining messages
        if: attributes.message not matches "(LOG:( *)((duration)|(DURATION)):(.*)((.|\n)*))" and attributes.message not matches "((^CONTEXT:)|(^context)|(^STATEMENT)|(^statement)|(^QUERY)|(^query))"
        regex: (?P<message_severity>\w+):( *)(?P<message_details>((.|\n)*))

processors:
  batch:
  resource:
    attributes:
    - key: metric-source
      value: otel
      action: insert
    - key: source
      value: otel
      action: insert
    # - key: ddsource
    #   value: otel
    #   action: insert

exporters:
  datadog:
    hostname: ${env:COMPUTERNAME}-OTEL-test
    api:
      key: "<NotDisclosed>"
    metrics:
      ## @param resource_attributes_as_tags - string - optional - default: false
      ## Set to true to add all resource attributes of a metric to its metric tags.
      ## When set to false, only a small predefined subset of resource attributes is converted
      ## to metric tags.
      #
      resource_attributes_as_tags: true
            
  logging:
    # verbosity: detailed|normal|basic
    verbosity: detailed
    # verbosity: normal
  file:
    path: C:\AppData\Open Telemetry\otelcol_data.log

service:
  pipelines:
    # metrics:
      # receivers: [postgresql, sqlserver, sqlquery/postgresql, sqlquery/sqlserver]
      # receivers: [postgresql, sqlquery/postgresql, sqlquery/sqlserver]
      # receivers: [sqlquery/sqlserver]
      # receivers: [sqlquery/postgresql]
      processors: [batch, resource]
      # exporters: [logging, datadog]
      # exporters: [logging]
    logs:
      # receivers: [filelog/postgres]
      # exporters: [logging]
      exporters: [logging, datadog]

```
And as a zipped file (this page doesn't accept yaml files as attachment: 

[config.zip](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/10988989/config.zip)



### Logfiles
And here are two PostgreSQL server logfiles:
[postgresql-2023-03-13_000000.log](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/10988926/postgresql-2023-03-13_000000.log)
[postgresql-2023-03-14_000003.log](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/10988929/postgresql-2023-03-14_000003.log)

### For reply using PostgreSQL
In case you want to replay, note that I changed the PostgreSQL settings to write a different format of logrecords by using this parameter in the postgresql.conf:
`log_line_prefix = '%m pid=[%p] line=[%l] usr=[%u] db=[%d] app=[%a] host=[%h] sessid=[%c] transid=[%x] sqlerr=[%e] '`

**Comment by arjan-saly-tfs** [comment]
Hi @songy23,

Thanks for your reply. In which pipeline should I add those? I tried adding `ddsource` them to `filelog/postgres:` >> `resource:`:
```
  filelog/postgres:
    resource: { ddsource: otel-postgres-serverlog-r } 
```

and `processors:` >> `resources:` (the commented part in the config I gave):
```
processors:
  resource:
    attributes:
    - key: ddsource
      value: otel
      action: upsert
```
Those don't seem to be picked up by Datadog. In Datadog, it ends up as `@source`, but is not found in the `source` facet for quick filtering.

Or do you mean a different way?

Thanks!

**Comment by songy23** [comment]
The format would be `"ddtags":  "key1:val1,key2:val2"` ([example](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/380efc358589cb83bef3c1586799e9110090f023/exporter/datadogexporter/logs_exporter_test.go#L193)). In your case the attribute should be `"ddtags": "ddsource:otel-postgres-serverlog-r"`, so attribute key is `ddtags` while attribute value is the actual resource tag.

**Comment by arjan-saly-tfs** [comment]
Ah ok, but then where is this supposed to be added?
I tried this:
```
processors:
  resource:
    attributes:
    - key: "ddtags"
      value: "ddsource: otel-postgres-p"
      action: upsert
```

And this:
````
receivers:
  filelog/postgres:
    resource: { "ddtags": "ddsource: otel-postgres-serverlog-r, ddservice: postgres-r" }
````

and this:
````
receivers:
  filelog/postgres:
    attributes: { "ddtags": "ddsource: otel-postgres-serverlog-r, ddservice: postgres-r" }
````

But in all these cases, the source facet in datadog gives `undefined`.

What am I doing wrong?
