### ISSUE TITLE
[processor/datadog] Convert into a connector

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#19740]
### Component(s)

processor/datadog

### Describe the issue you're reporting

See https://github.com/open-telemetry/opentelemetry-collector/issues/7370 for additional context.

**Comment by mx-psi** [comment]
@djaglowski How should we name this connector? There is already an exporter and a receiver named `datadog`. With a quick test, I believe a configuration like this works as expected:

```yaml
receivers:
  datadog:

exporters:
  datadog:
    api::key: ${env:DD_API_KEY}

connectors:
  datadog/connector:

service:
  pipelines:
    traces:
      receivers: [datadog]
      exporters: [datadog/connector]
    metrics:
      receivers: [datadog/connector]
      exporters: [datadog]
```

But we are unsure whether this would be too confusing for end users; the error if you drop `/connector` is:

```
Error: invalid configuration: connectors::datadog: there's already an exporter named "datadog"
```

Do we want to have connectors with the same ID as an existing exporter or receiver? Or should we discourage that?
