### ISSUE TITLE
How to support failover in k8sattributes

### ISSUE THREAD

**Issue by alburthoffman** [open-telemetry/opentelemetry-collector-contrib#19742]
### Component(s)

processor/k8sattributes

### Describe the issue you're reporting

Our spans have an attribute called `host`, which might be pod's name or hostname, which is a little different in our system.

In order to enrich spans with k8s metadata, we have to use one k8sattributes processor to enrich based on pod's name first and then another processor to enrich based on hostname. In the end, there are two k8sattributes processors and two copies of data. It's inefficient for memory.

So can we support something like `if no pod found based on pod'name, then query pod based on pod's hostname`

**Comment by dmitryax** [comment]
I don't think you can use `host` attribute as a pod lookup field in the `pod_association` section. AFAIR `pod_association` only accepts attributes available in the `metadata` section.

You can use the transform processor to conditionally (based on regex applied on the value) move/copy `host` attribute to either `k8s.pod.name` or `k8s.pod.hostname`, then use k8sattributes processor with the following config:

```yaml
  pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.name
    - sources:
      - from: resource_attribute
        name: k8s.pod.hostname
```

**Comment by alburthoffman** [comment]
The problem is we dont know if the value is `pod.name` or `pod.hostname`.

The span brings the field value. it might be `pod.name` or `pod.hostname`. the only way to check is querying.

**Comment by dmitryax** [comment]
@alburthoffman not sure I understand, I thought you have only one attribute, `host` which can have values of pod name or hostname. Can you please post attribute examples that you have?

**Comment by alburthoffman** [comment]
ur understanding is correct. something like below

`{"host": "querysrv-cjlfaure"}`

the value could be a pod'name or its hostname.

**Comment by alburthoffman** [comment]
this wont work. I had tried it.
```  
pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.name
    - sources:
      - from: resource_attribute
        name: k8s.pod.hostname
```

as `k8s.pod.name` always has value. the processor will always use it and ignore the second one. refer to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/pod_association.go#L72

**Comment by dmitryax** [comment]
> as k8s.pod.name always has value

Why is this the case for you? 

```
- set(attributes["k8s.pod.name"], attributes["host"]) where IsMatch(attributes["host"], ADD_POD_NAME_REGEXP_HERE)
```

should not set any attribute if the provided regex doesn't match the `host` value.

**Comment by alburthoffman** [comment]
the answer is pretty simply. You have the value, but you dont know if it's pod name or host name. We dont have a matching processor so far to check that

**Comment by alburthoffman** [comment]
@dmitryax could we consider supporting something like below
```
pod_association:
    - sources:
      - from: resource_attribute
         name: k8s.pod.name
         continue_if_no_matched: true
    - sources:
      - from: resource_attribute
        name: k8s.pod.hostname
        continue_if_no_matched: true
```

the option `continue_if_no_matched` means if it could not find a match with the given source, then try matching with next source.
