### ISSUE TITLE
Incorrect Errors for Parent Processes That No Longer Exist

### ISSUE THREAD

**Issue by Dylan-M** [open-telemetry/opentelemetry-collector-contrib#19753]
### Component(s)

receiver/hostmetrics

## Description
When monitoring processes using the hostmetrics receiver, the log gets filled with errors about parent processes that no longer exist.
Examples:
pid 0 on Linux
winlogon.exe on Windows

## Steps to Reproduce
Enable all process/processes monitoring in a host metrics receiver. Check log for these errors.

## Expected Result
Receiver understands that processes can fork and exit, thus no longer existing as a parent to the forked process.

## Actual Result
Errors in the log about these processes that no longer exist.

### Collector version

0.73.0

## Environment
OS: 5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
Compiler(if manually compiled): Not manually compiled

### OpenTelemetry Collector configuration

```yaml
receivers:
    hostmetrics:
        collection_interval: 60s
        scrapers:
            cpu:
                metrics:
                    system.cpu.utilization:
                        enabled: true
            disk:
                metrics: null
            filesystem:
                metrics:
                    system.filesystem.utilization:
                        enabled: true
            load:
                metrics: null
            memory:
                metrics:
                    system.memory.utilization:
                        enabled: true
            network:
                metrics:
                    system.network.conntrack.count:
                        enabled: true
                    system.network.conntrack.max:
                        enabled: true
            paging:
                metrics:
                    system.paging.utilization:
                        enabled: true
            process:
                metrics:
                    process.context_switches:
                        enabled: true
                    process.cpu.utilization:
                        enabled: true
                    process.disk.operations:
                        enabled: true
                    process.memory.utilization:
                        enabled: true
                    process.open_file_descriptors:
                        enabled: true
                    process.paging.faults:
                        enabled: true
                    process.signals_pending:
                        enabled: true
                    process.threads:
                        enabled: true
                mute_process_name_error: true
            processes:
processors:
exporters:
    googlecloud:
service:
    pipelines:
        metrics:
            receivers:
                - hostmetrics
            processors:
            exporters:
                - googlecloud
```

### Log output

```shell
{"level":"error","ts":"2023-03-16T16:03:25.983Z","caller":"scraperhelper/scrapercontroller.go:212","msg":"Error scraping metrics","kind":"receiver","name":"hostmetrics/source1","data_type":"metrics","error":"failed to read conntrack info: open /proc/sys/net/netfilter/nf_conntrack_count: no such file or directory","scraper":"network","stacktrace":"go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.73.0/scraperhelper/scrapercontroller.go:212\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.73.0/scraperhelper/scrapercontroller.go:191"}
{"level":"error","ts":"2023-03-16T16:03:26.011Z","caller":"scraperhelper/scrapercontroller.go:212","msg":"Error scraping metrics","kind":"receiver","name":"hostmetrics/source1","data_type":"metrics","error":"error reading parent pid for process \"systemd\" (pid 1): invalid pid 0","scraper":"process","stacktrace":"go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.73.0/scraperhelper/scrapercontroller.go:212\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/receiver@v0.73.0/scraperhelper/scrapercontroller.go:191"}
```

**Comment by atoulme** [comment]
See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18923 for a possible duplicate.

pid 0 and pid 1 are used in linux and Mac OS. PID 0 refers to the kernel: https://www.baeldung.com/linux/process-pid-0#:~:text=What%20Process%20Has%20PID%200,and%20shutting%20down%20the%20system.

**Comment by atoulme** [comment]
See also https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14311 as a possible duplicate.

**Comment by F21** [comment]
Also seeing this error.

Here's what I have in my logs:
```
Apr 17 05:27:19 system-1 otelcol[2714]: 2023-04-17T05:27:19.621Z        error        scraperhelper/scrapercontroller.go:212        Error scraping metrics        {"kind": "receiver", "name":
 "hostmetrics", "data_type": "metrics", "error": "error reading parent pid for process \"systemd\" (pid 1): invalid pid 0; error reading parent pid for process \"kthreadd\" (pid 2): invali
d pid 0", "scraper": "process"}
Apr 17 05:27:19 system-1 otelcol[2714]: go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
Apr 17 05:27:19 system-1 otelcol[2714]:         go.opentelemetry.io/collector/receiver@v0.75.0/scraperhelper/scrapercontroller.go:212
Apr 17 05:27:19 system-1 otelcol[2714]: go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
Apr 17 05:27:19 system-1 otelcol[2714]:         go.opentelemetry.io/collector/receiver@v0.75.0/scraperhelper/scrapercontroller.go:191
```
In my config, I am muting all errors, but that doesn't seem to silence the `error reading parent pid error`:
```yaml
mute_process_name_error: true
mute_process_exe_error: true
mute_process_io_error: true
```
