### ISSUE TITLE
count connector: Doesn't set StartTime on metrics

### ISSUE THREAD

**Issue by smithclay** [open-telemetry/opentelemetry-collector-contrib#19931]
### Component(s)

connector/count

## Description

When creating metrics using the count connector, `StartTimestamp` is set to a value in the 1970s:

Input log:
```
otel-collector        | LogRecord #98
otel-collector        | ObservedTimestamp: 2023-03-20 19:24:20.200254343 +0000 UTC
otel-collector        | Timestamp: 2023-03-20 18:46:14 +0000 UTC
otel-collector        | SeverityText: 200
otel-collector        | SeverityNumber: Info(9)
otel-collector        | Body: Str(192.168.64.4 - - [20/Mar/2023:18:46:14 +0000] "GET /status HTTP/1.1" 200 98 "-" "Go-http-client/1.1")
otel-collector        | Attributes:
otel-collector        |      -> http_user_agent: Str(Go-http-client/1.1)
otel-collector        |      -> ip: Str(192.168.64.4)
otel-collector        |      -> remote_user: Str(-)
otel-collector        |      -> log.file.name: Str(proxy-access.log)
otel-collector        |      -> time_local: Str(20/Mar/2023:18:46:14 +0000)
otel-collector        |      -> request: Str(GET /status HTTP/1.1)
otel-collector        |      -> http_referer: Str(-)
otel-collector        |      -> status: Str(200)
otel-collector        |      -> body_bytes_sent: Str(98)
otel-collector        | Trace ID:
```

Metric created:
```
2023-03-20T19:06:37.552Z	info	ResourceMetrics #0
otel-collector        | Resource SchemaURL:
otel-collector        | ScopeMetrics #0
otel-collector        | ScopeMetrics SchemaURL:
otel-collector        | InstrumentationScope otelcol/countconnector
otel-collector        | Metric #0
otel-collector        | Descriptor:
otel-collector        |      -> Name: log.record.count
otel-collector        |      -> Description: The number of log records observed.
otel-collector        |      -> Unit:
otel-collector        |      -> DataType: Sum
otel-collector        |      -> IsMonotonic: true
otel-collector        |      -> AggregationTemporality: Delta
otel-collector        | NumberDataPoints #0
otel-collector        | StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
otel-collector        | Timestamp: 2023-03-20 19:06:37.551186461 +0000 UTC
otel-collector        | Value: 39
``` 

## Steps to Reproduce

Collector config, see example here: https://github.com/lightstep/opentelemetry-examples/pull/265

## Expected Result

`StartTimestamp` should be set to `Timestamp` for metrics generated from the log

## Actual Result

`StartTimestamp` is not set

### Collector version

opentelemetry-collector-contrib:0.73.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

Docker image, see attached PR with example config.

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include:
      - /var/log/nginx/proxy-access.log
    start_at: beginning
    operators:
      - type: regex_parser
        on_error: drop
        #127.0.0.1 - - [04/Jul/2021:21:03:19 +0800] "GET /favicon-32x32.png HTTP/1.1" 200 628 "http://api.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
        regex: '^(?P<ip>[^\s]+) - (?P<remote_user>[^\s]+) \[(?P<time_local>[^\]]+)\] \"(?P<request>[^\"]+)\" (?P<status>\d+) (?P<body_bytes_sent>\d+) \"(?P<http_referer>[^\"]+)\" \"(?P<http_user_agent>[^\"]+)\"$'
        timestamp:
          parse_from: attributes.time_local
          layout_type: gotime
          layout: "02/Jan/2006:15:04:05 -0700"
        severity:
          parse_from: "attributes.status"
          mapping:
            info: 2xx
            info2: 3xx
            warn: 4xx
            error: 5xx
  nginx/proxy:
    endpoint: http://nginx_proxy:8080/status
    collection_interval: 10s
  nginx/appsrv:
    endpoint: http://nginx_appsrv:1080/status
    collection_interval: 10s
exporters:
  logging:
    loglevel: debug
  otlp/public:
    endpoint: ingest.lightstep.com:443
    headers:
      lightstep-access-token: ${LS_ACCESS_TOKEN}
processors:
  resource/proxy:
    attributes:
      - key: instance.type
        value: proxy
        action: insert
  resource/appsrv:
    attributes:
      - key: instance.type
        value: appsrv
        action: insert
  batch:
connectors:
  count:
    logs:
      nginx.requests.ok:
        description: Successful requests
        conditions:
          - severity_number == 9

service:
  pipelines:
    # Log to metrics pipeline using connector
    logs/proxy:
      receivers:
        - filelog
      exporters:
        - count
        - logging
    # Count incoming telemetry types, then log and send to public
    metrics/count:
       receivers:
         - count
       exporters:
         - logging
         - otlp/public
    metrics/proxy:
      receivers:
        - nginx/proxy
      processors:
        - resource/proxy
      exporters:
        - logging
        - otlp/public
    metrics/appsrv:
      receivers:
        - nginx/appsrv
      processors:
        - resource/appsrv
      exporters:
        - logging
        - otlp/public
```

### Log output

```shell
2023-03-20T19:06:37.552Z	info	ResourceMetrics #0
otel-collector        | Resource SchemaURL:
otel-collector        | ScopeMetrics #0
otel-collector        | ScopeMetrics SchemaURL:
otel-collector        | InstrumentationScope otelcol/countconnector
otel-collector        | Metric #0
otel-collector        | Descriptor:
otel-collector        |      -> Name: log.record.count
otel-collector        |      -> Description: The number of log records observed.
otel-collector        |      -> Unit:
otel-collector        |      -> DataType: Sum
otel-collector        |      -> IsMonotonic: true
otel-collector        |      -> AggregationTemporality: Delta
otel-collector        | NumberDataPoints #0
otel-collector        | StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
otel-collector        | Timestamp: 2023-03-20 19:06:37.551186461 +0000 UTC
otel-collector        | Value: 39
```
