### ISSUE TITLE
k8sattribute processor does not add metadata for static pods

### ISSUE THREAD

**Issue by dbason** [open-telemetry/opentelemetry-collector-contrib#20231]
### Component(s)

processor/k8sattributes

## Description
Static pods have no metadata added to them by the attributes processor

## Steps to Reproduce
Create a k8s cluster with static pods (for example Rancher RKE2 or kubeadm clusters use static pods for control plane components)

Collect logs from these clusters with k8s attribute processor enabled

## Expected Result
Pod metadata such as labels are added, container image

## Actual Result
No metadata added

### Collector version

v0.71.0

## Environment
k8s v1.23.x

### OpenTelemetry Collector configuration

```yaml
receivers: ${file:/etc/otel/receivers.yaml}
exporters:
  otlp:
    endpoint: "otel-aggregator:4317"
    tls:
      insecure: true
    sending_queue:
      num_consumers: 4
      queue_size: 100
    retry_on_failure:
      enabled: true
processors:
  memory_limiter:
    limit_mib: 250
    spike_limit_mib: 50
    check_interval: 1s
  k8sattributes:
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection
    extract:
      metadata:
      - "k8s.deployment.name"
      - "k8s.statefulset.name"
      - "k8s.daemonset.name"
      - "k8s.cronjob.name"
      - "k8s.job.name"
      - "k8s.node.name"
      - "container.image.name"
      - "container.image.tag"
      labels:
      - key: tier
      - key: component
service:
  pipelines:
    logs:
      receivers:
      - filelog/k8s
      - journald/rke2
      - filelog/rke2
      processors: ["memory_limiter", "k8sattributes"]
      exporters: ["otlp"]
```

### Additional context

I believe this is due to the fact that static pods never hit the shared informer (they are not managed by the api).  One approach may be to get a list of pods that have owner references with Kind of Node as these will be static pods, maybe hidden behind a config flag to enable?

**Comment by dmitryax** [comment]
Hi @dbason,

It looks like you won't be able to set any of these attributes for static pods:
```
      - "k8s.deployment.name"
      - "k8s.statefulset.name"
      - "k8s.daemonset.name"
      - "k8s.cronjob.name"
      - "k8s.job.name"
```

Do you want to fetch only?
```
      - "k8s.node.name"
      - "container.image.name"
      - "container.image.tag"
```

**Comment by dbason** [comment]
That would seem reasonable.  This is a generic config that fetches everything in a cluster, I think that subset would be fine.  For my particular use case getting the labels is the most important

**Comment by dbason** [comment]
I've done some more digging into this and it seems like the issue isn't that the mirror pods aren't exposed by the shared informer, but that the uid section in the filename that we extract the log from is the config hash rather than the pod uid.

E.g. a static pod folder `kube-system_kube-controller-manager-danb-dev-rke2-pool1-479a9f94-mvh72_57585a0305e4e46df816ebab263926f3`

As opposed to a normal pod folder `calico-system_calico-node-5864n_4642c6fa-c1b5-48cb-aabc-0437328d28f9`

The metadata for the static pod is as follows:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 57585a0305e4e46df816ebab263926f3
    kubernetes.io/config.mirror: 57585a0305e4e46df816ebab263926f3
    kubernetes.io/config.seen: "2023-03-21T00:48:48.612274752Z"
    kubernetes.io/config.source: file
    kubernetes.io/psp: global-unrestricted-psp
  creationTimestamp: "2023-03-21T00:49:35Z"
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager-danb-dev-rke2-pool1-479a9f94-mvh72
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: danb-dev-rke2-pool1-479a9f94-mvh72
    uid: 7ac3a80a-fb48-4b6c-87e8-8d1d27aab52b
  resourceVersion: "979"
  uid: d095a6cc-b3d0-431c-98b3-59541a15f56b
```

So it seems like this becomes an issue of resource matching rather than the pods not being available in the list.

**Comment by dmitryax** [comment]
I'm not sure we really need to add the config hash as pod identifier. It seems to serve different purposes. Why can't you use namespace + pod name instead already available in the log file path?

```yaml
    - sources:
      - from: resource_attribute
        name: k8s.namespace.name
      - from: resource_attribute
        name: k8s.pod.name
```
