### ISSUE TITLE
[receivers/prometheusreceiver] Unable to scrape cadvisor metrics due to misconfigured metrics path which is missing the node names

### ISSUE THREAD

**Issue by utr1903** [open-telemetry/opentelemetry-collector-contrib#20271]
### Component(s)

receiver/prometheus

## Description

I am running an AKS (k8s: 1.25.5) and willing to scrape the cadvisor metrics via the prometheus receiver (see config below), yet receive a `400` from the prometheus library within the opentelemetry collector (see logs).

Checking the logs, we can see that the reason for the `BadRequest` comes from missing `node_name` within the target scrape endpoint:
```
"target": "https://kubernetes.default.svc:443/api/v1/nodes//proxy/metrics/cadvisor"
```

As it can be seen in the `__metrics_path__`(`/api/v1/nodes/<NODE_NAME>/proxy/metrics/cadvisor`), the node name is missing. Therefore, I'm assuming that the problem lies somehow on the Kubernetes service discovery since it fails to discover the node names and populate the `__metrics_path__` with the node name:

```
scrape_config:
  relabel_configs:
    - source_labels: [__meta_kubernetes_node_name]
       regex: (.+)
       target_label: __metrics_path__
       replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
```

*Remark1:* When I manually give one of the node names to the `relabel_configs`, the collector can successfully scrape the cadvisor metrics from that node.

*Remark2:* When I tried to scrape the cadvisor in the same cluster with an actual Prometheus server with the same scrape job config and the same service account with the same cluster role binded, it has successfully scraped the cadvisor metrics.

## Steps to Reproduce

- Deploy any K8s cluster
- Create the following `ServiceAccount`, `ClusterRole` &  `ClusterRoleBinding`:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.name }}
rules:
  - apiGroups:
    - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - nodes/stats
      - nodes/proxy
      - nodes/metrics
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
      - endpoints
      - ingresses
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
      - "/metrics/cadvisor"
    verbs:
      - "get"
```
- Deploy an OTel collector with the provided config and assign the `ServiceAccount` to it

## Expected Result

Successfully scraping cadvisor metrics.

## Actual Result

Receiving `400` from the Prometheus SDK within OTel collector.

### Collector version

0.73.0

## Environment

- AKS (k8s version) 1.25.5

### OpenTelemetry Collector configuration

```yaml
receivers:

  prometheus:
    config:
      scrape_configs:

        - job_name: 'kubernetes-nodes-cadvisor'

          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

          kubernetes_sd_configs:
            - role: node

          relabel_configs:
            - target_label: __address__
              replacement: kubernetes.default.svc:443
            - source_labels: [__meta_kubernetes_node_name]
              regex: (.+)
              target_label: __metrics_path__
              replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor

processors:

  batch:
    send_batch_max_size: 1000
    timeout: 30s
    send_batch_size : 800

  memory_limiter:
      check_interval: 1s
      limit_percentage: 70
      spike_limit_percentage: 30

  cumulativetodelta:

  k8sattributes:
    extract:
      metadata:
      - k8s.cluster.name
      - k8s.node.name
      - k8s.namespace.name
      - k8s.pod.name
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection

exporters:

  otlp:
    endpoint: xxx
    tls:
      insecure: false
    headers:
      api-key: xxx

  logging:
    verbosity: detailed

extensions:

  memory_ballast:
    size_in_percentage: 20

  k8s_observer:
    auth_type: serviceAccount
    observe_pods: true
    observe_nodes: true

service:
  extensions:
    - memory_ballast
  pipelines:
    metrics:
      receivers:
        - prometheus
      processors:
        - k8sattributes
        - batch
        - memory_limiter
        - cumulativetodelta
      exporters:
        - otlp
        - logging
  telemetry:
    logs:
      level: DEBUG
    metrics:
      address: 0.0.0.0:9464
```

### Log output

```shell
2023-03-22T19:50:23.175Z	debug	scrape/scrape.go:1351	Scrape failed	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_pool": "kubernetes-nodes-cadvisor", "target": "https://kubernetes.default.svc:443/api/v1/nodes//proxy/metrics/cadvisor", "error": "server returned HTTP status 400 Bad Request", "errorVerbose": "server returned HTTP status 400 Bad Request\ngithub.com/prometheus/prometheus/scrape.(*targetScraper).scrape\n\tgithub.com/prometheus/prometheus@v0.42.1-0.20230210113933-af1d9e01c7e4/scrape/scrape.go:815\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport\n\tgithub.com/prometheus/prometheus@v0.42.1-0.20230210113933-af1d9e01c7e4/scrape/scrape.go:1338\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).run\n\tgithub.com/prometheus/prometheus@v0.42.1-0.20230210113933-af1d9e01c7e4/scrape/scrape.go:1262\nruntime.goexit\n\truntime/asm_amd64.s:1594"}
2023-03-22T19:50:23.175Z	warn	internal/transaction.go:121	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_timestamp": 1679514623171, "target_labels": "{__name__=\"up\", agentpool=\"general\", beta_kubernetes_io_arch=\"amd64\", beta_kubernetes_io_instance_type=\"Standard_D2_v2\", beta_kubernetes_io_os=\"linux\", failure_domain_beta_kubernetes_io_region=\"westeurope\", failure_domain_beta_kubernetes_io_zone=\"0\", instance=\"aks-general-26195720-vmss000001\", job=\"kubernetes-nodes-cadvisor\", kubernetes_azure_com_agentpool=\"general\", kubernetes_azure_com_cluster=\"aksrgnr1euwplatformd001\", kubernetes_azure_com_kubelet_identity_client_id=\"b639b0fc-fc40-4253-b242-2ef5fd272e4d\", kubernetes_azure_com_mode=\"user\", kubernetes_azure_com_node_image_version=\"AKSUbuntu-2204containerd-2023.02.15\", kubernetes_azure_com_os_sku=\"Ubuntu\", kubernetes_azure_com_role=\"agent\", kubernetes_azure_com_storageprofile=\"managed\", kubernetes_azure_com_storagetier=\"Standard_LRS\", kubernetes_io_arch=\"amd64\", kubernetes_io_hostname=\"aks-general-26195720-vmss000001\", kubernetes_io_os=\"linux\", kubernetes_io_role=\"agent\", nodePoolName=\"general\", node_kubernetes_io_instance_type=\"Standard_D2_v2\", storageprofile=\"managed\", storagetier=\"Standard_LRS\", topology_kubernetes_io_region=\"westeurope\", topology_kubernetes_io_zone=\"0\"}"}
```
