### ISSUE TITLE
[exporter/prometheusremotewriteexporter] HTTP status 413 Request Entity Too Large 

### ISSUE THREAD

**Issue by ezequielbarros** [open-telemetry/opentelemetry-collector-contrib#20289]
### Component(s)

exporter/prometheusremotewrite

### What happened?

##Description
I am experiencing errors when sending metrics via PrometheusRemoteWriteExporter to Amazon Managed Prometheus (AMP) service. The error "HTTP status 413 Request Entity Too Large" occurs in the collector log. The service has a payload limit of 1MB that cannot be increased by the cloud provider.

##Steps to Reproduce

- Create an AMP workspace on AWS.
- Provision a collector by configuring PrometheusRemoteWriteExporter to write metrics to the AMP workspace.
- Generate a large volume of metrics and send them to the collector.

##Expected Result
The expected result is that the complete payload of metrics is sent to the Prometheus AMP.

Actual Result
Currently, some requests exceed the maximum 1MB payload of AMP, resulting in loss of these metrics.

### Collector version

v0.72.0

## Environment
OS: alpine (EKS)
Compiler(if manually compiled): go 1.19 - golang:1.19.5-alpine3.17 

### OpenTelemetry Collector configuration

```yaml
receivers:
  jaeger: null
  prometheus:
    config:
      scrape_configs:
        - job_name: otelcol-metrics
          scrape_interval: 60s
          static_configs:
            - targets: [ "${MY_POD_IP}:8888" ]
  zipkin: null
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 8
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 5000
    timeout: 1s
    send_batch_max_size: 5500

  attributes:
    actions:
      - key: cloud.account.id
        value: $CLOUD_ACCOUNT_ID
        action: insert
      - key: cloud.region
        value: $CLOUD_REGION
        action: insert
      - key: k8s.cluster.name
        value: $K8S_CLUSTER_NAME
        action: insert

  k8sattributes:

  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["k8s.pod.name"], resource.attributes["k8s.pod.name"]) where attributes["k8s.pod.name"] == nil

exporters:
  logging: null
  prometheusremotewrite/amp:
    endpoint: $PROMETHEUS_REMOTE_WRITE_ENDPOINT
    max_batch_byte_size: 1048576
    auth:
      authenticator: sigv4auth

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

  sigv4auth:
    region: "us-east-1"
    service: "aps"

service:
  telemetry:
    logs:
      level: "INFO"
      encoding: json
    metrics:
      address: 0.0.0.0:8888
  extensions: [ health_check, sigv4auth ]
  pipelines:
    logs: null
    traces: null
    metrics:
      receivers:
        - otlp
        - prometheus
      processors:
        - k8sattributes
        - batch
        - attributes
        - transform
      exporters:
        - prometheusremotewrite/amp
```

### Log output

```shell
{"level":"error","ts":1678802163.1162071,"caller":"exporterhelper/queued_retry.go:401","msg":"Exporting failed. The error is not retryable. Dropping data.","kind":"exporter","data_type":"metrics","name":"prometheusremotewrite/amp","error":"Permanent error: Permanent error: remote write returned HTTP status 413 Request Entity Too Large; err = %!w(<nil>): <RequestEntityTooLargeException>\n  <Message>HTTP content length exceeded 1048576 bytes.</Message>\n</RequestEntityTooLargeException>\n; Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): user=405825378532_ws-93099f40-6fd1-4516-8895-cf177a28c5e9: err: out of order sample. timestamp=2023-03-14T13:56:02.072Z, series={__name__=\"event_count\", cloud_account_id=\"405825378532\", cloud_region=\"us-east-1\", eventName=\"Pix Screen Viewed\", fromBatch=\"tr","errorCauses":[{"error":"Permanent error: Permanent error: remote write returned HTTP status 413 Request Entity Too Large; err = %!w(<nil>): <RequestEntityTooLargeException>\n  <Message>HTTP content length exceeded 1048576 bytes.</Message>\n</RequestEntityTooLargeException>\n"},{"error":"Permanent error: Permanent error: remote write returned HTTP status 400 Bad Request; err = %!w(<nil>): user=405825378532_ws-93099f40-6fd1-4516-8895-cf177a28c5e9: err: out of order sample. timestamp=2023-03-14T13:56:02.072Z, series={__name__=\"event_count\", cloud_account_id=\"405825378532\", cloud_region=\"us-east-1\", eventName=\"Pix Screen Viewed\", fromBatch=\"tr"}],"dropped_items":5500,"stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send\n\tgo.opentelemetry.io/collector@v0.71.0/exporter/exporterhelper/queued_retry.go:401\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send\n\tgo.opentelemetry.io/collector@v0.71.0/exporter/exporterhelper/metrics.go:136\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1\n\tgo.opentelemetry.io/collector@v0.71.0/exporter/exporterhelper/queued_retry.go:205\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1\n\tgo.opentelemetry.io/collector@v0.71.0/exporter/exporterhelper/internal/bounded_memory_queue.go:61"}
```

### Additional context

I have identified that the sending limit is configured in the code by a constant that is currently not configurable. However, I have already made a correction that allows this limit to be configured and it is currently being tested internally. I plan to submit a pull request (PR) with this correction soon.

This is the code snippet where the constant is currently defined: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/380efc358589cb83bef3c1586799e9110090f023/exporter/prometheusremotewriteexporter/exporter.go#L43
