### ISSUE TITLE
[receiver/sqlquery] Add support for logs

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector-contrib#20284]
### Component(s)

receiver/sqlquery

### Is your feature request related to a problem? Please describe.

At Sumo Logic, we have customers wanting to retrieve logs from SQL databases (MySQL, PostgreSQL, MS SQL Server, possibly others) into OpenTelemetry Collector. The SQL Query receiver can currently create metrics based on SQL queries. It seems natural to extend this feature to logs as well. 

### Describe the solution you'd like

Given the following example that creates metrics, taken from the [SQL Query receiver's README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.74.0/receiver/sqlqueryreceiver):

```yaml
receivers:
  sqlquery:
    driver: postgres
    datasource: "host=localhost port=5432 user=postgres password=s3cr3t sslmode=disable"
    queries:
      - sql: "select count(*) as count, genre from movie group by genre"
        metrics:
          - metric_name: movie.genres
            value_column: "count"
            attribute_columns: [ "genre" ]
            static_attributes:
              dbinstance: mydbinstance
```

the following configuration seems to make sense for logs as a starter:

```yaml
receivers:
  sqlquery:
    driver: postgres
    datasource: "host=localhost port=5432 user=postgres password=s3cr3t sslmode=disable"
    queries:
      - sql: "select * from logs_table"
        logs:
          - # properties to be defined
```

The features that could be considered for logs are:
- defining the columns for body, severity, timestamp etc. (similar to `value_column` for metrics)
- creating structured body from the result set
- keeping track of the rows in the table that were already read/processed, e.g. by storing the highest row ID in persistent storage
- keeping consistency with metrics, e.g. with `attribute_columns` and `static_attributes`
- other? "let me know in the commens" :slightly_smiling_face: 

I'd be happy to work on the implementation if this feature gets accepted.

### Describe alternatives you've considered

I don't see any alternative other than creating a custom binary that does this and sends the data to the collector via OTLP.

### Additional context

Here's a past proposal to achieve similar goal by adding a new component:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12082.

I believe adding the functionality in the SQL Query receiver is the right approach, as it already does the same thing for metrics. Also re-using its configuration and code for connecting to DBs, running queries etc. makes sense.

**Comment by astencel-sumo** [comment]
I borrowed this idea from the previous [mysqlrecordsreceiver proposal](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12082). The idea is to make each row of the result set into a separate log record, where the body of the log would be a map of column_name => row_value. Let me show an example (based on the one in that original issue):

Example SQL query and the result from the database:

```
> select * from Persons;
| PersonID | LastName | FirstName | Address   | City     |
| -------- | -------- | --------- | --------- | -------- |
| 3        | Kalita   | Raktim    | Hatigaon  | Guwahati |
| 4        | Person2  | Someone2  | Somewhere | Else     |
2 row(s) in set (0.01 sec)
```

For a receiver configured like this (subject to change of course):

```yaml
receivers:
  sqlquery:
    driver: postgres
    datasource: "host=localhost port=5432 user=postgres password=s3cr3t sslmode=disable"
    queries:
    - sql: "select * from Persons"
      logs:
      - structured_body: true
```

I would expect the following logs:

```console
Resource SchemaURL:
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 2023-03-23 19:56:22.838756143 +0000 UTC
Timestamp: 2023-03-23 16:53:35.546008 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Map({"Address":"Hatigaon","City":"Guwahati","FirstName":"Raktim","LastName":"Kalita","PersonID":"3"})
Trace ID:
Span ID:
Flags: 0
LogRecord #1
ObservedTimestamp: 2023-03-23 19:56:22.838760884 +0000 UTC
Timestamp: 2023-03-23 16:53:35.546012 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Map({"Address":"Somewhere","City":"Else","FirstName":"Someone2","LastName":"Person2","PersonID":"4"})
Trace ID:
Span ID:
Flags: 0
```

Does it make sense to you @atoulme?

Perhaps @JKashyap96 (as the author of the original proposal) could help with the rationale for this - is this what customers have actually requested?
