### ISSUE TITLE
Routing based on the field value extracted from the logs is not working

### ISSUE THREAD

**Issue by rohits-splunk** [open-telemetry/opentelemetry-collector-contrib#20298]
### Component(s)

processor/routing

### Describe the issue you're reporting

I have a requirement to send logs to different exporters through a collector gateway, for testing purpose i inserted some test messages into the logs which would capture a field value and based on that value, OTEL should send logs to different exporters. This is my processor information which obviously includes attributes processor which will add `environment` field to the logs and `routing` processor will use `environment` field values ( prod or non prod) to send events to different exporters. 

```processors:
  attributes/1:
    actions:
      - action: extract
        key: message
        pattern: \{\"message\"\:\s\"(?P<environment>\w+)
      - key: environment
        action: insert
        from_attribute: message
  routing:
    from_attribute: environment
    default_exporters: [file/no_rotation]
    table:
    - value : 'nonprod'
      exporters: [ file/no_rotation ]
    - value: 'prod'
      exporters: [splunk_hec]
```

Here is the same log : 

`{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "nonprod: some other log data"}
{"message": "prod: some log data"}
{"message": "prod: some log data"}
"hec.log" 169L, 7223B                 
{"message": "prod: some log data"}
{"message": "prod: some log data"} ` 

As it can be seen from the `regex` pattern and sample logs, that only log lines which have `environment=prod` will go to `splunk_hec` and rest will go to `default` exporter. After several rounds of testing, i am still not able to send logs to non default exporters. Is there any guidlines around the type of logs which are suited for conditional routing ?

**Comment by atoulme** [comment]
Here is a working example:

```
receivers:
    filelog:
        include: [ /output/file.log ]

exporters:
    splunk_hec/logs:
        # Splunk HTTP Event Collector token.
        token: "00000000-0000-0000-0000-0000000000000"
        # URL to a Splunk instance to send data to.
        endpoint: "https://splunk:8088/services/collector"
        # Optional Splunk source: https://docs.splunk.com/Splexicon:Source
        source: "output"
        # Splunk index, optional name of the Splunk index targeted.
        index: "logs"
        # Maximum HTTP connections to use simultaneously when sending data. Defaults to 100.
        max_connections: 20
        # Whether to disable gzip compression over HTTP. Defaults to false.
        disable_compression: false
        # HTTP timeout when sending data. Defaults to 10s.
        timeout: 10s
        # Whether to skip checking the certificate of the HEC endpoint when sending data over HTTPS. Defaults to false.
        # For this demo, we use a self-signed certificate on the Splunk docker instance, so this flag is set to true.
        tls:
            insecure_skip_verify: true
    file/done:
        path: /output/done.log
    file/else:
        path: /output/else.log
processors:
    batch:
    logstransform:
        operators:
            - type: regex_parser
              regex: '^.*env:\s(?P<environment>\w+).*$'
    groupbyattrs:
        keys:
            - environment
    logstransform/copy:
        operators:
            - type: copy
              from: attributes.environment
              to: resource.environment
    routing:
        attribute_source: resource
        from_attribute: environment
        default_exporters: [ file/else ]
        table:
            - value: "one"
              exporters: [ file/done ]
            - value: "two"
              exporters: [ splunk_hec/logs ]

extensions:
    health_check:
        endpoint: 0.0.0.0:13133
    pprof:
        endpoint: :1888
    zpages:
        endpoint: :55679

service:
    telemetry:
        logs:
            level: debug
    extensions: [ pprof, zpages, health_check ]
    pipelines:
        logs:
            receivers: [ filelog ]
            processors: [ logstransform, groupbyattrs, logstransform/copy, batch, routing ]
            exporters: [ file/else, file/done, splunk_hec/logs ]

```

I use 2 bash scripts to generate logs:
```
  logging1:
    image: bash:latest
    container_name: logging1
    command: 'bash -c "while(true) do echo \"time: $$(date) env: one body: new message\" >> /output/file.log ; sleep 2; done"'
    volumes:
      - ./output:/output
  # Sample application producing logs.
  logging2:
    image: bash:latest
    container_name: logging2
    command: 'bash -c "while(true) do echo \"time: $$(date) env: two body: new message\" >> /output/file.log ; sleep 2; done"'
    volumes:
      - ./output:/output
```

There are multiple limitations you ran into that created trouble for you:
* The attributes processor cannot act on log bodies, so it's unclear to me if you are able to extract from the message attribute. For myself, I use the logstransform processor to get the attribute extracted.
* You cannot route based on log attributes, you can route based on resources attributes or context. So to get by, we first group our logs by attribute value:
```
    groupbyattrs:
        keys:
            - environment
```

Then we copy the log attribute environment to resource attribute environment:
```
    logstransform/copy:
        operators:
            - type: copy
              from: attributes.environment
              to: resource.environment
```

So now you can route, but final twist of irony, you must route with the resource attribute option. So you need to add `attribute_source: resource` in the configuration.

With those changes, I am able to see both the file and Splunk ingest logs.
