### ISSUE TITLE
[receiver/journald] Add more filtering options

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector-contrib#20295]
### Component(s)

receiver/journald

### Is your feature request related to a problem? Please describe.

The [Journald receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.74.0/receiver/journaldreceiver) currently offers the following options to filter the journald logs: `unit` and `priority`. Sometimes these options are not enough. I have a scenario where a user is running iptables on a host with systemd, and the logs from iptables are written to journald as kernel logs. They do not have any unit assigned, so you cannot filter them by `unit`, and filtering by `priority` doesn't help either. It seems that in this case filtering by kernel messages (`-k`/`--dmesg` as described in the [man page](https://www.man7.org/linux/man-pages/man1/journalctl.1.html)) would help.

### Describe the solution you'd like

The filtering options in the Journald receiver are under the hood translated into the options of the `journalctl` binary. Looking at the command's [man page](https://www.man7.org/linux/man-pages/man1/journalctl.1.html), there are a couple other filtering options that sound like a good candidate to be exposed in the receiver:

- `-k`, `--dmesg` - Show only kernel messages.
- `-g`, `--grep=` - Filter output to entries where the `MESSAGE` field matches the specified regular expression.
- `-t`, `--identifier=` - Show messages for the specified `SYSLOG_IDENTIFIER`

### Describe alternatives you've considered

An alternative is to read all logs without filtering and apply a `filter` operator, for example like this to get only kernel logs:

```yaml
receivers:
  journald:
    operators:
    - type: filter
      expr: body._TRANSPORT != "kernel"
```

It's easy to trip on the `filter` operator as you need to remember to invert the condition :sweat_smile:, also this is probably a lot less performant, especially if you have a lot of logs in systemd.

**Comment by astencel-sumo** [comment]
I missed the "obvious" way to filter journald logs by any property with `journalctl FIELD=value`, as described in the man page's initial [DESCRIPTION](https://www.man7.org/linux/man-pages/man1/journalctl.1.html#DESCRIPTION) section and in the [EXAMPLES](https://www.man7.org/linux/man-pages/man1/journalctl.1.html#EXAMPLES) section. This is apparently what Fluent Bit and Fluentd are exposing, see [Fluent Bit systemd input plugin](https://docs.fluentbit.io/manual/pipeline/inputs/systemd) and [Fluentd systemd input plugin](https://github.com/fluent-plugin-systemd/fluent-plugin-systemd/blob/v1.0.5/README.md#input-plugin-configuration).

**Comment by astencel-sumo** [comment]
Apparently the Journald receiver doesn't have any specific code owners :scream_cat: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ca50a98fdda4c362d8782a29f6fc5cc27977f37b/.github/CODEOWNERS#L189

@djaglowski do you have an opinion or do you know who might? :slightly_smiling_face:

**Comment by astencel-sumo** [comment]
I'd be happy to co-own this component with you @djaglowski, but I'm thinking perhaps @sumo-drosiek would be an even better candidate for this component. What do you think @sumo-drosiek and @djaglowski?

**Comment by sumo-drosiek** [comment]
I would be very honored and happy to co-own the receiver

**Comment by djaglowski** [comment]
Great, thanks @sumo-drosiek and @astencel-sumo!

**Comment by sumo-drosiek** [comment]
> @sumo-drosiek, it appears you are not a member of the OpenTelemetry org. Typically we need code owners to be members so that we can assign issues, etc. If you want to apply I'm happy to be one of your sponsors.

Yes, it seems I need to take care of formal part. I appreciate it and going to start the process

**Comment by atoulme** [comment]
@sumo-drosiek if you are looking for a second sponsor I would be happy to be one of them.

**Comment by sumo-drosiek** [comment]
@djaglowski @atoulme @astencel-sumo here is my application then: https://github.com/open-telemetry/community/issues/1399

**Comment by astencel-sumo** [comment]
OK, back to the topic of this issue then 😅 I think perhaps it's best to start with adding the `matches` property as described in the [man page](https://www.man7.org/linux/man-pages/man1/journalctl.1.html#DESCRIPTION) in a manner like this?

```yaml
receivers:
  journald:
    matches:
    - _SYSTEMD_UNIT: avahi-daemon.service
      _PID: 28097
    - _SYSTEMD_UNIT: dbus.service
```

The `matches` property is a list of maps.. The above example is equivalent to `journalctl _SYSTEMD_UNIT=avahi-daemon.service _PID=28097 + _SYSTEMD_UNIT=dbus.service`, as described in the [EXAMPLES](https://www.man7.org/linux/man-pages/man1/journalctl.1.html#EXAMPLES) section of the man page.

This is similar to [Fluentd's implementation](https://github.com/fluent-plugin-systemd/fluent-plugin-systemd/blob/v1.0.5/docs/matching.md), which I believe to be feature complete. Compared to that, the [Fluent Bit's implementation](https://docs.fluentbit.io/manual/pipeline/inputs/systemd) seems to be not as feature complete, if I'm understanding correctly, as it only allows for a single list of conditions, which are all joined with either an `OR` or an `AND`.

**Comment by sumo-drosiek** [comment]
> OK, back to the topic of this issue then sweat_smile I think perhaps it's best to start with adding the `matches` property as described in the [man page](https://www.man7.org/linux/man-pages/man1/journalctl.1.html#DESCRIPTION) in a manner like this?
> 
> ```yaml
> receivers:
>   journald:
>     matches:
>     - _SYSTEMD_UNIT: avahi-daemon.service
>       _PID: 28097
>     - _SYSTEMD_UNIT: dbus.service
> ```
> 
> The `matches` property is a list of maps.. The above example is equivalent to `journalctl _SYSTEMD_UNIT=avahi-daemon.service _PID=28097 + _SYSTEMD_UNIT=dbus.service`, as described in the [EXAMPLES](https://www.man7.org/linux/man-pages/man1/journalctl.1.html#EXAMPLES) section of the man page.
> 
> This is similar to [Fluentd's implementation](https://github.com/fluent-plugin-systemd/fluent-plugin-systemd/blob/v1.0.5/docs/matching.md), which I believe to be feature complete. Compared to that, the [Fluent Bit's implementation](https://docs.fluentbit.io/manual/pipeline/inputs/systemd) seems to be not as feature complete, if I'm understanding correctly, as it only allows for a single list of conditions, which are all joined with either an `OR` or an `AND`.

It may work, as we are able to cover the following examples:

- `journalctl _SYSTEMD_UNIT=avahi-daemon.service`
  
  <details>
  ```
  receivers:
    journald:
      matches:
      - _SYSTEMD_UNIT: avahi-daemon.service
  ```
  
  or
  
  ```
  receivers:
    journald:
      units:
      - avahi-daemon.service
  ```
  
  </details>
  
- `journalctl _SYSTEMD_UNIT=avahi-daemon.service _PID=28097`
  
  <details>


  ```
  receivers:
    journald:
      matches:
      - _SYSTEMD_UNIT: avahi-daemon.service
        _PID: 28097
  ```
  
  </details>

- `journalctl _SYSTEMD_UNIT=avahi-daemon.service _SYSTEMD_UNIT=dbus.service`
  
  <details>

  ```
    journald:
      matches:
      - _SYSTEMD_UNIT: avahi-daemon.service
      - _SYSTEMD_UNIT: dbus.service
  ```
  
  or
  
  ```
  receivers:
    journald:
      units:
      - avahi-daemon.service
      - dbus.service
  ```
  
  </details>
  
- `journalctl _SYSTEMD_UNIT=avahi-daemon.service _PID=28097 + _SYSTEMD_UNIT=dbus.service`
  
  <details>

  ```yaml
  receivers:
    journald:
      matches:
      - _SYSTEMD_UNIT: avahi-daemon.service
        _PID: 28097
      - _SYSTEMD_UNIT: dbus.service
  ```
  
  </details>

The only thing which I don't really like is duplication of `units` functionality,
but we can treat `matches` are extension of `units` (with OR approach)

For example for the following configuration:

```
receivers:
  journald:
    units:
    - avahi-daemon.service
    - dbus.service
  matches:
    - _PID: 28097
```

The behavior will be:

```journalctl _SYSTEMD_UNIT=avahi-daemon.service + _SYSTEMD_UNIT=dbus.service + _PID=28097```


and another example:

```
receivers:
  journald:
    units:
    - avahi-daemon.service
    - dbus.service
  matches:
    - _SYSTEMD_UNIT: dbus.service
      _PID: 28097
```

converts to

```journalctl _SYSTEMD_UNIT=avahi-daemon.service + _SYSTEMD_UNIT=dbus.service _PID=28097```
