### ISSUE TITLE
[mongodbatlasreceiver] Add support to collect Organization Events

### ISSUE THREAD

**Issue by JonathanWamsley** [open-telemetry/opentelemetry-collector-contrib#20308]
### Component(s)

receiver/mongodbatlas

### Is your feature request related to a problem? Please describe.

The current Mongodb Atlas receiver already supports `Project events`, but it would be a great addition to also support `Organization events` as mentioned [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19449).

Each organization events have occurred within a specific timeframe and contain useful information.  This useful information can be used for monitoring the health and performance of clusters, troubleshooting cluster issues by identifying organization events that may be the source of the problem or auditing all changes and activities in your MongoDB Atlas Organization.

### Describe the solution you'd like

Organization events can be obtained from the [this API](https://www.mongodb.com/docs/atlas/reference/api/events-orgs-get-all/#syntax) endpoint: 
`GET /orgs/{ORG-ID}/events`

This request path requires a parameter `ORG-ID` for the organization similar to how the Project event requires `GROUP-ID`. The request query parameters and response output of the [org events](https://www.mongodb.com/docs/atlas/reference/api/events-orgs-get-all/#request-query-parameters) and the [project events](https://www.mongodb.com/docs/atlas/reference/api/events-projects-get-all/#request-query-parameters) are the same, so a lot of [code from project events](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18061) can be reused.

I suggest following a similar format for the config by including an org event and a name which, is a list of each organization event to be collected.

A sample config to collect both events would look like:
```yaml
mongodbatlas:
  public_key: "my-public-key"
  private_key: "my-private-key"
  events:
    projects:
      - name: Project 0
        include_clusters: [Cluster0]
    orgs:
      - id: Orgid
        include_clusters: [Cluster0]
    poll_interval: 1m
    page_size: 100
    max_pages: 25
```

The PollInterval, types, pageSize and maxpages would be shared across events. Each specified organization or project will have their own org/project config similar to how the current [ProjectConfig](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/mongodbatlasreceiver/config.go#L76-L84) is implmented.

### Describe alternatives you've considered

Not sure if `orgs` in the config is preferred over `organizations`

### Additional context

I'll be happy to implement this feature.
