### ISSUE TITLE
spanmetrics connector generating extreme grpc traffic

### ISSUE THREAD

**Issue by devrimdemiroz** [open-telemetry/opentelemetry-collector-contrib#20306]
### Component(s)

connector/spanmetrics

## Description

I replaced the spanmetrics processor config on opentelemetry demo app with the new spanmetrics connector. The otlp grpc receiver observed traffic increased almost 10,000 times. Accordingly calls (previously calls_total) and related spanmetrics also linearly explode. See the screenshots at the bottom.

## Steps to Reproduce

Following configuration is used in replacement for spanmetrics processor:

```
connectors:
  spanmetrics:
      histogram:
        explicit:
          buckets: [ 100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms ]
      dimensions:
        - name: http.method
          default: GET
        - name: http.status_code
      dimensions_cache_size: 1000
      aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
....

service:
  pipelines:
    traces/spanmetrics:
      receivers: [otlp]
      exporters: [spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
```

## Expected Result

The expected result is to be inline with spanmetrics processor runs.

When processor runs:

![SpanmetricsProcessor](https://user-images.githubusercontent.com/62701796/227580424-29b0bf8e-365b-4e73-a9a7-43bbeef2df62.png)

## Actual Result

When connector runs:

![SpanmetricsConnector](https://user-images.githubusercontent.com/62701796/227580472-35a58e02-e394-40db-9626-2afbe6b705c5.png)

### Collector version

0.74.0

## Environment
# Images
IMAGE_VERSION=1.3.1
IMAGE_NAME=ghcr.io/open-telemetry/demo

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
exporters:
  otlp:
    endpoint: "localhost:4317"
    tls:
      insecure: true
  logging:
  prometheus:
    endpoint: "otelcol:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
connectors:
  spanmetrics:
      histogram:
        explicit:
          buckets: [ 100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms ]
      dimensions:
        - name: http.method
          default: GET
        - name: http.status_code
      dimensions_cache_size: 1000
      aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"

processors:
  batch:
  transform:
    metric_statements:
      - context: metric
        statements:
          - set(description, "Measures the duration of inbound HTTP requests") where name == "http.server.duration"


service:
  pipelines:
    traces/spanmetrics:
      receivers: [otlp]
      exporters: [spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [prometheus]
```

**Comment by kovrus** [comment]
The reason is https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19216, `spanmetrics` generates metrics from spans per resource scope now so the number of generated replicas will grow with the number of resource scopes. I've opened a PR to toggle on/off this functionality or filter resource attributes  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19467 but we decided to close it because this can be achieved with the transform processor's `keep_keys` function.

**Comment by devrimdemiroz** [comment]
@kovrus, I truly appreciate your quick response! If you could provide me with a little bit more on the transform processor configuration I need to add, you'll be an absolute time-saver for me. Thanks in advance!

**Comment by kovrus** [comment]
@devrimdemiroz something like that will reduce the number of resource scopes to the number of the services that produce telemetry. If we want to allow the old behavior, one resource scope for everything, we should wrap https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/19467 up.  

```yaml
...

processors:
  transform:
    trace_statements:
    - context: resource
      statements:
      - keep_keys(attributes, ["service.name"])

...
service:
  pipelines:
    traces/spanmetrics:
      receivers: [otlp]
      processors: [transform]
      exporters: [spanmetrics]
    metrics/spanmetrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
...
```
