### ISSUE TITLE
Renaming metrics does not work on the metrics generated by spanmetrics connector

### ISSUE THREAD

**Issue by xwgao** [open-telemetry/opentelemetry-collector-contrib#20432]
### Component(s)

processor/metricstransform

## Description
I'm using `metricstranform` processor and `spanmetrics` connector in my otel collector as below. There are two transformations contained in the `metricstranform` processor. The first transformation which contains operations to add label `app` and update label (rename the label `http.url`  to `url`) works as expected. But the second transformation which rename the metrics `duration_bucket` (this metrics is generated by the `spanmetrics` connector from received spans) to `duration_seconds` does not work as expected. From the exported metrics, I can only find the original metrics `duration_bucket`  and can not find the `duration_seconds`  metrics.
```
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: 0.0.0.0:12346

    processors:
      batch:
        timeout: 10s
        send_batch_size: 10000
      spanmetrics:
        metrics_exporter: prometheus
        latency_histogram_buckets:
          [10ms, 100ms, 200ms, 400ms, 800ms, 1s, 1200ms, 1400ms, 1600ms, 1800ms, 2s, 5s, 7s]
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: http.target
          - name: http.url
      metricstransform:
        transforms:
          - include: duration_*
            match_type: regexp
            action: update
            operations:
              - action: add_label
                new_label: app
                new_value: assist
              - action: update_label
                label: http.url
                new_label: url
          - include: duration_bucket
            match_type: strict
            action: update
            new_name: duration_seconds

    exporters:
      jaeger:
        endpoint: my-jaeger-collector-headless.jaeger-demo.svc:14250
        tls:
          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
      prometheus:
        endpoint: "0.0.0.0:8889"
        send_timestamps: true
        metric_expiration: 1440m

    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [10ms, 100ms, 200ms, 400ms, 800ms, 1s, 1200ms, 1400ms, 1600ms, 2s, 5s]
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: http.target
          - name: http.url
          - name: http.route

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [spanmetrics, jaeger]
        metrics:
          receivers: [spanmetrics]
          processors: [batch, metricstransform]
          exporters: [prometheus]
  image: >-
    ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.74.0
  mode: statefulset
  volumeMounts:
    - mountPath: /etc/pki/ca-trust/source/service-ca
      name: cabundle-volume
  volumes:
    - configMap:
        name: my-otelcol-cabundle
      name: cabundle-volume
```

## Steps to Reproduce
1. Create an otel collector with `spec` as described above in the description, and create an instrumentation for auto-instrumentation.
2. Check exported metrics data via `localhost:8889/metrics` within otel collector pod.

## Expected Result
I can find the `duration_seconds`  metrics after renaming with the metricstranform processor.

## Actual Result
I still find the original `duration_bucket` metrics before renaming, and can not find the `duration_seconds`  metrics.

### Collector version

v0.74.0

## Environment
OpenShift Cluster: 4.10.50
Kubernetes version: v1.23.12+8a6bfe4

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
          http:
      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: 0.0.0.0:12346

    processors:
      batch:
        timeout: 10s
        send_batch_size: 10000
      spanmetrics:
        metrics_exporter: prometheus
        latency_histogram_buckets:
          [10ms, 100ms, 200ms, 400ms, 800ms, 1s, 1200ms, 1400ms, 1600ms, 1800ms, 2s, 5s, 7s]
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: http.target
          - name: http.url
      metricstransform:
        transforms:
          - include: duration_*
            match_type: regexp
            action: update
            operations:
              - action: add_label
                new_label: app
                new_value: assist
              - action: update_label
                label: http.url
                new_label: url
          - include: duration_bucket
            match_type: strict
            action: update
            new_name: duration_seconds

    exporters:
      jaeger:
        endpoint: my-jaeger-collector-headless.jaeger-demo.svc:14250
        tls:
          ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
      prometheus:
        endpoint: "0.0.0.0:8889"
        send_timestamps: true
        metric_expiration: 1440m

    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [10ms, 100ms, 200ms, 400ms, 800ms, 1s, 1200ms, 1400ms, 1600ms, 2s, 5s]
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: http.target
          - name: http.url
          - name: http.route

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [spanmetrics, jaeger]
        metrics:
          receivers: [spanmetrics]
          processors: [batch, metricstransform]
          exporters: [prometheus]
```

**Comment by kovrus** [comment]
`spanmetrics` produces OTel metrics, so the produced histogram metric name will be `duration`. Then when exporting the OTel metrics generated by `spanmetrics` with `prometheus` they will be converted to Prometheus metrics and the `_bucket` suffix, as well as `_sum` and `_count`, will be added.

**Comment by xwgao** [comment]
@kovrus , thanks a lot for the explanation. If I want to rename `duration_bucket` to `duration_seconds`, how can I specify the transformation for it? May I use as below? Thanks.
```
metricstransform:
        transforms:
          - include: duration._bucket
            match_type: strict
            action: update
            new_name: duration_seconds
```

**Comment by xwgao** [comment]
@kovrus I was able to rename the metrics `duration` to `duration_seconds` using metricstransform as below.
```
      metricstransform:
        transforms:
          - include: duration
            match_type: strict
            action: update
            new_name: duration_seconds
```
But I failed to insert new metric naming `mas_assist_getdocumentusage_duration` using metricstransform as below. Any idea about this? Thanks a lot.
```
      metricstransform:
        transforms:
          - include: duration
            match_type: regexp
            action: insert
            experimental_match_labels: {
              "http.target": "/api/v1/usage/document",
              "http.method": "GET"
            }
            new_name: mas_assist_getdocumentusage_duration
```
