### ISSUE TITLE
Parsing Spanmetrics Connector config failed

### ISSUE THREAD

**Issue by Owenxh** [open-telemetry/opentelemetry-collector-contrib#20450]
### Component(s)

connector/spanmetrics

## Description
An error occurred when starting the OTel collector.
The log of  the OTel collector told me that decode `connectors` failed because of the unknown type: "spanmetrics" for id: "spanmetrics"

### Collector version

v0.74.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
  opencensus:
  zipkin:

processors:
  probabilistic_sampler:
    hash_seed: 22
    sampling_percentage: 15.3
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    timeout: 10s
    send_batch_size: 100

exporters:
  logging:
  otlp:
    endpoint: "0.0.0.0:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    metric_expiration: 1m
    send_timestamps: true
    # resource_to_telemetry_conversion:
  jaeger:
    endpoint: global-jaeger-collector.jaeger:14250
    tls:
      insecure: true
      
connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"

service:
  extensions:
  pipelines:
    traces:
      receivers: [otlp, opencensus, zipkin]
      processors: [memory_limiter, probabilistic_sampler, batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
```

### Log output

```shell
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'connectors': unknown type: "spanmetrics" for id: "spanmetrics" (valid values: [forward])
2023/03/29 09:49:23 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'connectors': unknown type: "spanmetrics" for id: "spanmetrics" (valid values: [forward])
```
