### ISSUE TITLE
influxdbexporter cannot export gauge and histogram metrics

### ISSUE THREAD

**Issue by jenslewie** [open-telemetry/opentelemetry-collector-contrib#20484]
### Component(s)

exporter/influxdb

## Description
I use java autoinstrumentation to collect metrics and send to an opentelemetry collector.
In the pipeline, only receive OTLP metrics, no special processors, and export to logging and influxdb.
But it is unable to export gauge and histogram metrics to influxdb.
Then I add a filter processor in pipeline as below
> 

      filter/exclude:
        metrics:
          exclude:
            match_type: expr
            expressions:
            - MetricType == "Histogram"
            - MetricType == "Gauge"

Now, sum metrics can be exported to influxdb.

## Expected Result
All OTLP metrics can be exported to influxdb via influxdbexporter
## Actual Result
Gauge and histogram metrics cannot be exported to influxdb via influxdbexporter

### Collector version

0.74.0

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
          http:
   
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
   
    exporters:
      influxdb:
        endpoint: http://demo-influxdb2:80
        timeout: 500ms
        org: influxdata
        bucket: demo
        token: changeme
        metrics_schema: telegraf-prometheus-v1
  
        sending_queue:
          enabled: true
          num_consumers: 3
          queue_size: 10
  
        retry_on_failure:
          enabled: true
          initial_interval: 1s
          max_interval: 3s
          max_elapsed_time: 10s
      logging:
        loglevel: debug
   
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, influxdb]
```

### Log output

```shell
2023-03-29T16:26:19.671Z        error   exporterhelper/queued_retry.go:401      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "metrics", "name": "influxdb", "error": "Permanent error: failed to convert OTLP metric to line protocol: failed to write point for histogram: Permanent error: failed to encode point: encoding point 60: invalid tag value exception=\"\"", "dropped_items": 86}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector/exporter@v0.74.0/exporterhelper/queued_retry.go:401
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
        go.opentelemetry.io/collector/exporter@v0.74.0/exporterhelper/metrics.go:136
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
        go.opentelemetry.io/collector/exporter@v0.74.0/exporterhelper/queued_retry.go:205
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
        go.opentelemetry.io/collector/exporter@v0.74.0/exporterhelper/internal/bounded_memory_queue.go:58


2023-03-29T16:41:13.796Z        error   exporterhelper/queued_retry.go:401      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "metrics", "name": "influxdb", "error": "Permanent error: failed to convert OTLP metric to line protocol: failed to write point for gauge: Permanent error: failed to encode point: encoding point 51: invalid tag value exception=\"\"", "dropped_items": 86}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector/exporter@v0.74.0/exporterhelper/queued_retry.go:401
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
        go.opentelemetry.io/collector/exporter@v0.74.0/exporterhelper/metrics.go:136
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
        go.opentelemetry.io/collector/exporter@v0.74.0/exporterhelper/queued_retry.go:205
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
        go.opentelemetry.io/collector/exporter@v0.74.0/exporterhelper/internal/bounded_memory_queue.go:58
```
