### ISSUE TITLE
Azure Monitor Exports All Logs Under stderr LogEntrySource

### ISSUE THREAD

**Issue by thomasbaldwin** [open-telemetry/opentelemetry-collector-contrib#20527]
### Component(s)

exporter/azuremonitor

### Describe the issue you're reporting

I see logs like this:

```
2023-03-29T21:00:28.384Z info fileconsumer/file.go:196 Started watching file {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/var/log/pods/kube-system_ama-logs-rs-6dbf9db495-97rjt_4c211ef6-6d75-4540-a84a-5a63eb611310/ama-logs/0.log"}
```

That are categorized as `stderr` when I view the logs in my log analytics workspace. How is this determined in the code and how can I go about having this properly classified as `info` vs `stderr`?

Here is my configmap:

```
    receivers:
      filelog:
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/*/otel*/*.log
        start_at: beginning
        include_file_path: true
        include_file_name: true

    processors:
  
    exporters:
      azuremonitor:
        instrumentation_key: "...."
      logging:
        loglevel: error
    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: []
          exporters: [azuremonitor]
```
