### ISSUE TITLE
New component: JWT server authenticator

### ISSUE THREAD

**Issue by StarpTech** [open-telemetry/opentelemetry-collector-contrib#20539]
### The purpose and use-cases of the new component

This extension authenticates users who want to send data to your collector with a JWT, enabling multi-tenant use cases easier. Based on the auth claims data, you can use a processor like [`attributesprocessor`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor) to filter or enrich the data. Authenticity is ensured by signing the JWT token with the same secret before.

### Example configuration for the component

```yaml
extensions:
  jwt:
    secret: "secret"

receivers:
  otlp:
    protocols:
      grpc:
        auth:
          authenticator: jwt

processors:
  # Extract the project id from the auth context
  attributes/from_auth_context:
    actions:
      - key: project.id
        from_context: auth.project_id
        action: insert

exporters:
  logging:
    logLevel: debug

service:
  extensions: [jwt]
  pipelines:
    traces:
      receivers: [otlp]
      # Apply the processor
      processors: [attributes/from_auth_context]
      exporters: [logging]
```

### Telemetry data types supported

traces, metrics and logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/20524
