### ISSUE TITLE
New component: DataSet Exporter

### ISSUE THREAD

**Issue by martin-majlis-s1** [open-telemetry/opentelemetry-collector-contrib#20660]
### The purpose and use-cases of the new component

DataSet (https://www.dataset.com) is a log management and observability platform that allows users to collect, search, and analyze log data from their applications and infrastructure.

By exporting log data from OpenTelemetry to DataSet, users can consolidate their logs into a centralized location and take advantage of our real-time search and analysis capabilities to quickly identify and troubleshoot issues. DataSet platform is highly scalable and provides integration with other tools such as alerting and monitoring systems, making it easy for users to build a comprehensive observability solution for their application and infrastructure.

Overall, integrating OpenTelemetry with DataSet can provide users with improved logging and observability capabilities, leading to improved operational efficiency and a better user experience.

### Example configuration for the component

```
exporters:
  dataset:
    # DataSet API URL
    dataset_url: https://app.scalyr.com
    # API Key
    api_key: your_api_key
    # Send batch to the API at least every 15s
    max_delay_ms: 15000
    # Group data based on these attributes
    group_by:
      - attributes.container_id
      - attributes.log.file.path
      - body.map.kubernetes.container_hash
      - body.map.kubernetes.pod_id
      - body.map.kubernetes.docker_id
      - body.map.stream
  ```

Plus all the options from the [exporthelper](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md)

### Telemetry data types supported

logs

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [x] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.
