### ISSUE TITLE
Add operators to cloud watch logs receiver

### ISSUE THREAD

**Issue by AndriySidliarskiy** [open-telemetry/opentelemetry-collector-contrib#20703]
### Is your feature request related to a problem? Please describe.

I have a body message in json format and need to parse it but I cannot do this with transform or filter operators massagemassageJSON

### Describe the solution you'd like

so maybe need to add operators into the cloud watch receiver

**Comment by AndriySidliarskiy** [comment]
@astencel-sumo thanks for the answer. I have a json body message 
` . 
logRecord.body:{"id":"218","type":"TaskStarted","details":{"resource":"call","resourceType":"eks"},"previous_event_id":"217","event_timestamp":"1680697114137","execution_arn":"arn:aws:states:eu-west-1:888888888:execution:PVCStateMachine-fFgbdDPOdoMv:47ec3aca-e90f-4d50-8981-fb60a655cce1"}`
that is going from cloud watch receiver and I need to parse this message if it`s possible. I ty to use filter with this setting ```
 # filter/cw:
    #   error_mode: ignore
    #   logs:
    #     log_record:
    #       - ParseJSON(body) 
```
but I have error `2023/04/06 09:54:04 collector server run finished with error: invalid configuration: processors::filter/cw: unable to parse OTTL statement: 1:29: unexpected token "<EOF>" (expected <opcomparison> Value) 

And In the transform processor not possible to use ParseJSON function or I cannot see an example.

**Comment by AndriySidliarskiy** [comment]
it looks like what i need but it in development https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/logstransformprocessor

**Comment by astencel-sumo** [comment]
Here's the configuration for the [Transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.75.0/processor/transformprocessor) and the ParseJSON function that works for me with the latest version of the collector (v0.75.0):

```yaml
exporters:
  logging:
    verbosity: detailed

processors:
  transform/parse-json:
    log_statements:
    - context: log
      statements:
      - set(body, ParseJSON(body))

receivers:
  filelog:
    include: ./logs-json.log
    start_at: beginning

service:
  pipelines:
    logs:
      exporters:
      - logging
      processors:
      - transform/parse-json
      receivers:
      - filelog
```

You can also use `set(attributes, ParseJSON(body))` to put the parsed data in the record attributes. Please let me know if this points you in the right direction and whether you have any further questions.

I admit that the documentation of the Transform processor could use some improvements. Pull requests are very welcome! 😅 

The Logs Transform processor is intended to be made obsolete by the Transform processor (see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19775), so it will probably never go out of the "development" stage, other than into "deprecated".
