### ISSUE TITLE
Elastic search exporter : request failed, reason: EOF

### ISSUE THREAD

**Issue by shrutichy91** [open-telemetry/opentelemetry-collector-contrib#20715]
### Component(s)

exporter/elasticsearch

## Description
Unable to export logs to elastic search using elastic exporter

## Steps to Reproduce
Collector comes up and shows logs but is not able to export to elastic search

## Expected Result
logs shipped to ELastic

## Actual Result

error   elasticsearchexporter@v0.74.0/elasticsearch_bulk.go:60  Request failed. {"kind": "exporter", "data_type": "logs", "name": "elasticsearch/log", "reason": "EOF"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*clientLogger).LogRoundTrip
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.74.0/elasticsearch_bulk.go:60

### Collector version

v0.74

## Environment
OS: (e.g., "Ubuntu 20.04")
k8s environment

### OpenTelemetry Collector configuration

```yaml
extensions:
      health_check:
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
       endpoint: 0.0.0.0:55679

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            tls:

    processors:
      batch:

    exporters:
      elasticsearch/log:
        tls:
          insecure: true
        endpoints: [http://idc-elasticsearch-es-internal-http:9200]
        logs_index: my_log_index
        timeout: 2m
        headers:
          myheader: test
        pipeline: mypipeline
        user: elastic
        password: 5GPq0Z486mv5mTzSn7Ygq443
        discover:
          on_start: true
        flush:
          bytes: 10485760
        retry:
          max_requests: 5
      logging:
      otlp/elastic:
        endpoint: {{ .Values.apm.url }}:{{ .Values.apm.port }}
        tls:
          insecure: true
    service:

      pipelines:

        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/elastic]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/elastic]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, elasticsearch/log:]
      extensions: [health_check, pprof, zpages]
```

### Log output

```shell
error   elasticsearchexporter@v0.74.0/elasticsearch_bulk.go:60  Request failed. {"kind": "exporter", "data_type": "logs", "name": "elasticsearch/log", "reason": "EOF"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*clientLogger).LogRoundTrip
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.74.0/elasticsearch_bulk.go:60
```
