### ISSUE TITLE
[pkt/ottl] how to partially parse JSON?

### ISSUE THREAD

**Issue by AndriySidliarskiy** [open-telemetry/opentelemetry-collector-contrib#20747]
## Description
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20703

## Steps to Reproduce
ParseJSON cannot parse pcommon.map value
### Collector version

0.75.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
error_mode: ignore
      log_statements:
        - context: log
          statements: 
            - set(body, ParseJSON(body))
            - merge_maps(body.details.input, ParseJSON(body.details.input), "insert")
```

### Log output

```shell
"expected string but got pcommon.Map"
```

**Comment by astencel-sumo** [comment]
I believe this concerns the Transform processor:

```yaml
processors:
  transform:
    error_mode: ignore
    log_statements:
    - context: log
      statements: 
      - set(body, ParseJSON(body))
      - merge_maps(body.details.input, ParseJSON(body.details.input), "insert")
```

I'm not sure if what you're trying to achieve is clear from this example configuration. If my understanding is correct, you have a string in the log's body that is a nested JSON, and you want to parse the string into JSON but leave one of the fields in the JSON unparsed.

For example, taking this string as input:

`{"key1":"value1","details":{"output":{"pvc":{"size":"1200Gi","operation-type":"create"}}}}`

the Transform processor's `ParseJSON` function parses it into this JSON:

```json
{
  "key1": "value1",
  "details": {
    "output": {
      "pvc": {
        "size": "1200Gi",
        "operation-type": "create"
      }
    }
  }
}
```

But you want the contents of the `details.output` field to stay as a string:

```json
{
  "key1": "value1",
  "details": {
    "output": "{\"pvc\":{\"size\":\"1200Gi\",\"operation-type\":\"create\"}}"
  }
}
```
