### ISSUE TITLE
ResourceDetection eks detector causes Panic

### ISSUE THREAD

**Issue by disfluxly** [open-telemetry/opentelemetry-collector-contrib#20750]
### Component(s)

processor/resourcedetection

## Description

Attempting to use the `eks` detector throws a panic

I've tested this using 0.72.0 of the Otel Collector, deployed as a sidecar via the OpenTelemetry Operator. I've tested against both EKS Fargate Pods (running x86_64), and on EKS using EC2 Nodes (running arm64), both yield the same panic. This prevents the collector from starting.

## Steps to Reproduce

Create a pod in EKS, using the OpenTelemetry Operator add a sidecar to the pod OpenTelemetry Collector in EKS, enabling the `resourcedetection` processor with an `eks` detector in the configuration. 

## Expected Result

Processor starts as intended, adding the EKS detected resource properties to signals.

## Actual Result

OpenTelemetry Collector container is unable to start, due to panic.

### Collector version

v0.72.0

## Environment
EKS 1.23
Tested against an arm64 EC2 Worker Node & an x86_64 EKS Fargate Node
OpenTelemetry Operator 0.72.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:

exporters:
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20
  batch:
    send_batch_size: 8192
    timeout: 200ms
    send_batch_max_size: 0
  resourcedetection:
    detectors: [env,eks]
    timeout: 2s
    override: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [logging]
```

### Log output

```
panic: value method github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal/aws/eks.eksDetectorUtils.getConfigMap called using nil *eksDetectorUtils pointer

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal/aws/eks.(*eksDetectorUtils).getConfigMap(0x69fc9d1?, {0x7714678?, 0xc000d34120?}, {0x69aca3b?, 0xc0c622ad20?}, {0x699dfed?, 0x20?})
	<autogenerated>:1 +0x5c
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal/aws/eks.isEKS({0x7714678, 0xc000d34120}, {0x76bc660, 0x0})
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.72.0/internal/aws/eks/detector.go:92 +0x7c
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal/aws/eks.(*detector).Detect(0xc00122b890, {0x7714678, 0xc000d34120})
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.72.0/internal/aws/eks/detector.go:73 +0x7d
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal.(*ResourceProvider).detectResource(0xc0012296d0, {0x7714678, 0xc000d34120})
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.72.0/internal/resourcedetection.go:139 +0x44a
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal.(*ResourceProvider).Get.func1()
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.72.0/internal/resourcedetection.go:124 +0x95
sync.(*Once).doSlow(0x0?, 0x0?)
	sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	sync/once.go:65
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor/internal.(*ResourceProvider).Get(0xc0012296d0?, {0x7714678, 0xc000d34120}, 0x76932f0?)
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.72.0/internal/resourcedetection.go:120 +0x6d
github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor.(*resourceDetectionProcessor).Start(0xc000444640, {0x7714640, 0xc00011c000}, {0x77188f8?, 0xc000a69780?})
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor@v0.72.0/resourcedetection_processor.go:44 +0xfb
go.opentelemetry.io/collector/component.StartFunc.Start(...)
	go.opentelemetry.io/collector/component@v0.72.0/component.go:84
go.opentelemetry.io/collector/service.(*pipelinesGraph).StartAll(0xc000b09180?, {0x7714640, 0xc00011c000}, {0x77188f8, 0xc000a69780})
	go.opentelemetry.io/collector@v0.72.0/service/graph.go:272 +0xb3
go.opentelemetry.io/collector/service.(*Service).Start(0xc000a69700, {0x7714640, 0xc00011c000})
	go.opentelemetry.io/collector@v0.72.0/service/service.go:149 +0x2ac
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc000e71bc0, {0x7714640, 0xc00011c000})
	go.opentelemetry.io/collector@v0.72.0/otelcol/collector.go:182 +0x5eb
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc000e71bc0, {0x7714640, 0xc00011c000})
	go.opentelemetry.io/collector@v0.72.0/otelcol/collector.go:207 +0x65
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc000022f00, {0x699c088?, 0x2?, 0x2?})
	go.opentelemetry.io/collector@v0.72.0/otelcol/command.go:38 +0x96
github.com/spf13/cobra.(*Command).execute(0xc000022f00, {0xc000118160, 0x2, 0x2})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000022f00)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.runInteractive({{0xc0006c6a20, 0xc0006c7c80, 0xc0006c6e40, 0xc0006c6630, 0xc0006c7cb0}, {{0x69c424b, 0xf}, {0x6a4324b, 0x1f}, {0x6995b93, ...}}, ...})
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:31 +0x5d
main.run(...)
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main_others.go:11
main.main()
	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:24 +0x1d9
```
