### ISSUE TITLE
Azure Monitor : Metric Receiver(REST Client)

### ISSUE THREAD

**Issue by rajim17** [open-telemetry/opentelemetry-collector-contrib#20776]
### The purpose and use-cases of the new component

This component is to collect metrics from Azure Monitor platform and parse into OTLP metric format. Azure Monitor provides OS/CPU and major resource level metrics users are interested. List of metrics supported by Azure Monitor can be found [here](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported).

Component also provides a way to configure interested metric namespaces to collect.

### Example configuration for the component

```
receivers:
    azuremetric/5_min:
        subscription_id: <azure_subscription_1> // (mandatory) Azure subscription ID
        collection_interval:300
        timegrain: <1M> //  ( optional: default 1M ) fetch 1 min interval metrics for the past 5 mins
        metric_providers: // metric namespace of the resource providers 
            - microsoft.analysisservices/servers
            - microsoft.apimanagement/service                       
            - microsoft.cdn/profiles                                 
            - microsoft.storage/storageaccounts                     
            - microsoft.network/networksecuritygroups               
            - microsoft.network/privatednszones/virtualnetworklinks 
            - microsoft.network/routetables                         
            - microsoft.dbformysql/servers                          
            - microsoft.cache/redis                                 
            - microsoft.compute/virtualmachines                     
            - microsoft.compute/virtualmachinescalesets             
            - microsoft.streamanalytics/streamingjobs 
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

- Azure MetricReceiver will use http client using [azure-sdk/azquery](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/monitor/azquery#section-readme) module.
- Component can dynamically query all the resources under the subscription and fetch metrics for configured metric namespaces for those resources.
- It also groups multiple metric names and dimensions to reduce number of metric requests to Azure platform.
