### ISSUE TITLE
New component: GRPC processor/connector

### ISSUE THREAD

**Issue by nicolastakashi** [open-telemetry/opentelemetry-collector-contrib#20888]
### The purpose and use-cases of the new component

The OpenTelemetryContrib is providing an amazing job extending the Otel collector capacities and also providing basic functionalities that might be useful for the entire community. 

Although many other engineers would love to extend the OpenTelemetry Collector pipeline without the need to maintain their own OpenTelemetry distribution, which requires some work to keep track of the upstream changes.

With that in mind would be amazing if there's a generic processor to send the telemetry data to a GRPC server, so the engineers can build their own GRPC processors/connectors to manipulate the telemetry data and reply back to the collector, all this integration should be based on the OTEL protocol and a well-defined contract.

This kind of functionality may improve the user experience to extend the OpenTelemetry collector and also provide integrations to the external systems to enrich the telemetry data.

### Example configuration for the component

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  grpc/logs:
    endpoint: grpc-server.com:55690 ## just an example

exporters:
  otlp:
    endpoint: otelcol:4317

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, grpc/logs]
      exporters: [otlp]
```

### Telemetry data types supported

- Logs
- Metrics
- Traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Additional context

We had a short initial conversation on the CNCF Slack channel about this, as you can see [here](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1681332428011919).
