### ISSUE TITLE
prometheusexporter error message in collector logs.

### ISSUE THREAD

**Issue by garg031** [open-telemetry/opentelemetry-collector-contrib#20885]
### Component(s)

exporter/prometheus

## Description
Getting frequent error messages in otel-collector logs from prometheusexporter
## Steps to Reproduce
Configure Collector to send metrics to Prometheus.
## Expected Result
Metrics should be sent without and error.
## Actual Result
Error message was seen in collector logs.

### Collector version

opentelemetry-collector-contrib:0.74.0

### OpenTelemetry Collector configuration

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: random-name
spec:
  resources:
    requests:
      cpu: 50m
    limits:
      memory: 1024Mi
  env:
  {{ if .Values.snc.dcps.lightStep.enabled }}
  - name: LS_TOKEN
    valueFrom:
     secretKeyRef:
       key: lightstep.token
       name: app-secrets
       optional: false
  {{ end }}
  config: |
    exporters:
      logging:
        verbosity: detailed
      otlp:
        endpoint: 'abc-jaeger-collector:4317'
        tls:
          insecure: true
  {{ if .Values.snc.dcps.lightStep.enabled }}
      otlp/ls:
        endpoint: ingest.lightstep.com:443
        headers:
          lightstep-access-token: ${LS_TOKEN}
        timeout: 30s
        tls:
          insecure_skip_verify: true
  {{ end }}
      prometheus:
        endpoint: 0.0.0.0:9464
    extensions:
      health_check: {}
      memory_ballast:
        size_mib: "{{ .Values.memoryBallast.size_mib }}"
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      resource:
        attributes:
          - action: insert
            from_attribute: service.name
            key: service
      resource/add_container:
        attributes:
          - action: insert
            from_attribute: service.name
            key: container
      spanmetrics:
        metrics_exporter: prometheus
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            cors:
              allowed_origins:
                - http://*
                - https://*
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - localhost:8888
    service:
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        logs:
          exporters:
            - logging
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - prometheus
        {{ if .Values.snc.dcps.lightStep.enabled }}
            - otlp/ls
        {{ end }}
          processors:
            - resource
          receivers:
            - otlp
            - prometheus
        traces:
          exporters:
            - otlp
        {{ if .Values.snc.dcps.lightStep.enabled }}
            - otlp/ls
        {{ end }}
          processors:
            - resource/add_container
            - spanmetrics
          receivers:
            - otlp
      telemetry:
        metrics:
          address: 0.0.0.0:8888
```

### Log output

```shell
2023-04-12T16:47:15.805Z    error    prometheusexporter@v0.74.0/log.go:34    error gathering metrics: 5 error(s) occurred:
* collected metric rpc_server_duration label:<name:"job" value:"abdprojectperf-java-cnc" > label:<name:"net_host_name" value:"abdprojectgwperf.xyzcompanylab.com" > label:<name:"net_transport" value:"ip_tcp" > label:<name:"rpc_grpc_status_code" value:"1" > label:<name:"rpc_method" value:"SubscribeAgentToCnC" > label:<name:"rpc_service" value:"xyzcompany.proto.abdproject.discovery.vn.PQRService" > label:<name:"rpc_system" value:"grpc" > histogram:<sample_count:14882 sample_sum:4.335879822856113e+09 bucket:<cumulative_count:0 upper_bound:0 > bucket:<cumulative_count:0 upper_bound:5 > bucket:<cumulative_count:0 upper_bound:10 > bucket:<cumulative_count:0 upper_bound:25 > bucket:<cumulative_count:0 upper_bound:50 > bucket:<cumulative_count:0 upper_bound:75 > bucket:<cumulative_count:0 upper_bound:100 > bucket:<cumulative_count:302 upper_bound:250 > bucket:<cumulative_count:334 upper_bound:500 > bucket:<cumulative_count:344 upper_bound:750 > bucket:<cumulative_count:354 upper_bound:1000 > bucket:<cumulative_count:380 upper_bound:2500 > bucket:<cumulative_count:405 upper_bound:5000 > bucket:<cumulative_count:433 upper_bound:7500 > bucket:<cumulative_count:455 upper_bound:10000 > bucket:<cumulative_count:14882 upper_bound:inf exemplar:<label:<name:"trace_id" value:"89bbc9112468cc74c729b53d91495020" > label:<name:"span_id" value:"11b8fa9301fa9fe1" > value:581896.075213 timestamp:<seconds:1681315680 nanos:124511364 > > > >  has help "The duration of an inbound RPC invocation" but should have ""
* collected metric rpc_server_duration label:<name:"job" value:"abdprojectperf-java-cnc" > label:<name:"net_host_name" value:"abdprojectgwperf.xyzcompanylab.com" > label:<name:"net_transport" value:"ip_tcp" > label:<name:"rpc_grpc_status_code" value:"0" > label:<name:"rpc_method" value:"SendDataFromAgent" > label:<name:"rpc_service" value:"xyzcompany.proto.abdproject.discovery.vn.PQRService" > label:<name:"rpc_system" value:"grpc" > histogram:<sample_count:3327 sample_sum:1939.7749250000008 bucket:<cumulative_count:0 upper_bound:0 > bucket:<cumulative_count:3277 upper_bound:5 exemplar:<label:<name:"trace_id" value:"ac2d05dff8fa9b5a4882b0c0a5ad51d9" > label:<name:"span_id" value:"1b5ae03f56c57501" > value:0.442797 timestamp:<seconds:1681318026 nanos:730518645 > > > bucket:<cumulative_count:3293 upper_bound:10 exemplar:<label:<name:"trace_id" value:"f938f207f2bd4376d78e25757b290fbc" > label:<name:"span_id" value:"929566038e27ea98" > value:5.38782 timestamp:<seconds:1681317997 nanos:648511387 > > > bucket:<cumulative_count:3310 upper_bound:25 > bucket:<cumulative_count:3327 upper_bound:50 > bucket:<cumulative_count:3327 upper_bound:75 > bucket:<cumulative_count:3327 upper_bound:100 > bucket:<cumulative_count:3327 upper_bound:250 > bucket:<cumulative_count:3327 upper_bound:500 > bucket:<cumulative_count:3327 upper_bound:750 > bucket:<cumulative_count:3327 upper_bound:1000 > bucket:<cumulative_count:3327 upper_bound:2500 > bucket:<cumulative_count:3327 upper_bound:5000 > bucket:<cumulative_count:3327 upper_bound:7500 > bucket:<cumulative_count:3327 upper_bound:10000 > >  has help "The duration of an inbound RPC invocation" but should have ""
* collected metric rpc_server_duration label:<name:"job" value:"abdprojectperf-java-cnc" > label:<name:"net_host_name" value:"abdprojectgwperf.xyzcompanylab.com" > label:<name:"net_transport" value:"ip_tcp" > label:<name:"rpc_grpc_status_code" value:"0" > label:<name:"rpc_method" value:"SendKeepAliveFromAgent" > label:<name:"rpc_service" value:"xyzcompany.proto.abdproject.discovery.vn.PQRService" > label:<name:"rpc_system" value:"grpc" > histogram:<sample_count:79985 sample_sum:57551.09316000004 bucket:<cumulative_count:0 upper_bound:0 > bucket:<cumulative_count:78479 upper_bound:5 exemplar:<label:<name:"span_id" value:"890be20f11eb725d" > label:<name:"trace_id" value:"16e2f35872fb56082c1453a9e16a3b47" > value:0.449965 timestamp:<seconds:1681317983 nanos:177930421 > > > bucket:<cumulative_count:78945 upper_bound:10 > bucket:<cumulative_count:79209 upper_bound:25 > bucket:<cumulative_count:79964 upper_bound:50 > bucket:<cumulative_count:79984 upper_bound:75 > bucket:<cumulative_count:79985 upper_bound:100 > bucket:<cumulative_count:79985 upper_bound:250 > bucket:<cumulative_count:79985 upper_bound:500 > bucket:<cumulative_count:79985 upper_bound:750 > bucket:<cumulative_count:79985 upper_bound:1000 > bucket:<cumulative_count:79985 upper_bound:2500 > bucket:<cumulative_count:79985 upper_bound:5000 > bucket:<cumulative_count:79985 upper_bound:7500 > bucket:<cumulative_count:79985 upper_bound:10000 > >  has help "The duration of an inbound RPC invocation" but should have ""
* collected metric rpc_server_duration label:<name:"job" value:"abdprojectperf-java-cnc" > label:<name:"net_host_name" value:"java-cnc" > label:<name:"net_transport" value:"ip_tcp" > label:<name:"rpc_grpc_status_code" value:"0" > label:<name:"rpc_method" value:"Check" > label:<name:"rpc_service" value:"grpc.health.vn.Health" > label:<name:"rpc_system" value:"grpc" > histogram:<sample_count:41 sample_sum:46.407084999999995 bucket:<cumulative_count:0 upper_bound:0 > bucket:<cumulative_count:40 upper_bound:5 > bucket:<cumulative_count:40 upper_bound:10 > bucket:<cumulative_count:40 upper_bound:25 > bucket:<cumulative_count:41 upper_bound:50 > bucket:<cumulative_count:41 upper_bound:75 > bucket:<cumulative_count:41 upper_bound:100 > bucket:<cumulative_count:41 upper_bound:250 > bucket:<cumulative_count:41 upper_bound:500 > bucket:<cumulative_count:41 upper_bound:750 > bucket:<cumulative_count:41 upper_bound:1000 > bucket:<cumulative_count:41 upper_bound:2500 > bucket:<cumulative_count:41 upper_bound:5000 > bucket:<cumulative_count:41 upper_bound:7500 > bucket:<cumulative_count:41 upper_bound:10000 > >  has help "The duration of an inbound RPC invocation" but should have ""
* collected metric rpc_server_duration label:<name:"job" value:"abdprojectperf-java-cnc" > label:<name:"net_host_name" value:"abdprojectgwperf.xyzcompanylab.com" > label:<name:"net_transport" value:"ip_tcp" > label:<name:"rpc_grpc_status_code" value:"0" > label:<name:"rpc_method" value:"SubscribeAgentToCnC" > label:<name:"rpc_service" value:"xyzcompany.proto.abdproject.discovery.vn.PQRService" > label:<name:"rpc_system" value:"grpc" > histogram:<sample_count:14882 sample_sum:4.335849965120674e+09 bucket:<cumulative_count:0 upper_bound:0 > bucket:<cumulative_count:0 upper_bound:5 > bucket:<cumulative_count:0 upper_bound:10 > bucket:<cumulative_count:0 upper_bound:25 > bucket:<cumulative_count:0 upper_bound:50 > bucket:<cumulative_count:0 upper_bound:75 > bucket:<cumulative_count:0 upper_bound:100 > bucket:<cumulative_count:302 upper_bound:250 > bucket:<cumulative_count:334 upper_bound:500 > bucket:<cumulative_count:344 upper_bound:750 > bucket:<cumulative_count:354 upper_bound:1000 > bucket:<cumulative_count:380 upper_bound:2500 > bucket:<cumulative_count:405 upper_bound:5000 > bucket:<cumulative_count:433 upper_bound:7500 > bucket:<cumulative_count:455 upper_bound:10000 > bucket:<cumulative_count:14882 upper_bound:inf exemplar:<label:<name:"trace_id" value:"89bbc9112468cc74c729b53d91495020" > label:<name:"span_id" value:"11b8fa9301fa9fe1" > value:581895.948262 timestamp:<seconds:1681315680 nanos:124407349 > > > >  has help "The duration of an inbound RPC invocation" but should have ""
    {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
    github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.74.0/log.go:34
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
    github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/http.go:139
net/http.HandlerFunc.ServeHTTP
    net/http/server.go:2109
net/http.(*ServeMux).ServeHTTP
    net/http/server.go:2487
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
    go.opentelemetry.io/collector@v0.74.0/config/confighttp/compression.go:162
net/http.HandlerFunc.ServeHTTP
    net/http/server.go:2109
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
    go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.40.0/handler.go:213
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
    go.opentelemetry.io/collector@v0.74.0/config/confighttp/clientinfohandler.go:39
net/http.serverHandler.ServeHTTP
    net/http/server.go:2947
net/http.(*conn).serve
    net/http/server.go:1991
2023-04-12T16:47:16.358Z    error    prometheusexporter@v0.74.0/log.go:34    error gathering metrics: 5 error(s) occurred:
```
