### ISSUE TITLE
[exporter/loki]: Attribute used as hint always added as loki label

### ISSUE THREAD

**Issue by jonaskello** [open-telemetry/opentelemetry-collector-contrib#21045]
### Component(s)

exporter/loki

### Describe the issue you're reporting

It seems like when I add a hint for org-id using `loki.tenant` it also becomes added as a loki label. This seems like an unnecessary overhead since it will always have the same value for the same tenant. 

For example if I use the `k8s.namespace.name` resource attribute for `loki.tenant` it will also add a loki label called `k8s_namespace_name` which will always have the same value within the tenant.

```yaml
processors:
  resource/loki_tenant_from_k8s_namespace:
    attributes:
    - action: insert
      key: loki.tenant
      value: k8s.namespace.name
```

Is automatcially adding a loki label for the `loki.tenant` hint value expected behavior or do I have a misconfiguration?
