### ISSUE TITLE
[receiver/kafkareceiver] add Avro encoding for logs format

### ISSUE THREAD

**Issue by vincentfree** [open-telemetry/opentelemetry-collector-contrib#21067]
### Component(s)

receiver/kafka

### Is your feature request related to a problem? Please describe.

Adding Avro as an event format for logs. Apache Avro like Protobuf is a binary transport format, The added benefit this enhancement is event schemas. 

This supports the ability to add structured logging to the Kafka receiver.

Kafka natively supports the use of schemas using Avro, this enhancement adds the handling and validation of Avro events using schemas.

### Describe the solution you'd like

The kafka receiver should be able to handle the Avro format with schema validation.

The yaml configuration can look like:

```yaml
kafka/avroLogs:
  topic: avroLogs
  encoding: avro
  brokers:
    - "coffee:123"
    - "foobar:456"
  client_id: otel-collector
  group_id: otel-collector
  avro:
    schema_url: "file:testdata/avro/schema.avro"
    mapping:
      timestamp: timestamp
      properties: resource.attributes.properties
      hostname: resource.attributes.hostname
      count: attributes. Count
      message: body
      nestedRecord: attributes.nestedRecord
      levelEnum: severityText
      severity: severityNumber
```

The added Avro struct is needed to support describing the mapping between the structured logging fields to open telemetry attributes & resources.

### Describe alternatives you've considered

The current encoding options can be viewed as alternatives, at the same time they do not support structured logging so it's not like for like.

### Additional context

The current enconding options can
