### ISSUE TITLE
metrics scopeName error

### ISSUE THREAD

**Issue by daoweili** [open-telemetry/opentelemetry-collector-contrib#21082]
### Component(s)

exporter/clickhouse

### What happened?

**Describe the bug**
 When I use a custom meter and set instrumentationScopeName，but the scopeName is not effective in the clickhouse.
i used java agent version is 1.24.0, collector version is v0.75.0

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/3362644/232013730-c9e7af00-0860-4b4e-ab4b-89cb24f9e19c.png)
![image](https://user-images.githubusercontent.com/3362644/232014028-e0b241a9-4f1a-45df-a0db-2490ef7df6c3.png)
![image](https://user-images.githubusercontent.com/3362644/232014363-1967ea99-504a-4839-8bf8-db9c09ec79d4.png)

![image](https://user-images.githubusercontent.com/3362644/231999164-00f44a69-2e56-4cd1-a9f6-82eee85ab39e.png)

### Collector version

v0.75.0

## Environment
OS: (e.g., "Ubuntu 16.04")

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
      endpoint: 0.0.0.0:55679
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14251
      thrift_compact:  
        endpoint: 0.0.0.0:6931
processors:
  batch:
exporters:
  jaeger:
    endpoint: xxx
    tls:
      insecure: true
  kafka/metrics: 
    brokers:
      - xxx
    protocol_version: 2.0.0
    topic: otel_metrics_test
    encoding: otlp_json
    producer: 
      compression: snappy
  kafka/logs: 
    brokers:
      - xxx
    protocol_version: 2.0.0
    topic: otel_logs_test
    encoding: otlp_json
    producer: 
      compression: snappy
  clickhouse: 
    endpoint: xxx
    ttl_days: 30
    timeout: 5s
    database: xxx
    connection_params: {"dial_timeout":"200ms","max_execution_time":60}
    username: xxx
    password: xxxx
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    sending_queue: 
      queue_size: 5000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [resource, batch]
      exporters: [jaeger, clickhouse]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [kafka/metrics, clickhouse]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [kafka/logs, clickhouse]
  extensions: [health_check, pprof, zpages]
```
