### ISSUE TITLE
Spanmetrics Connector  are not giving correct metrics of spans

### ISSUE THREAD

**Issue by harshraigroww** [open-telemetry/opentelemetry-collector-contrib#21101]
### Component(s)

connector/spanmetrics

## Description
I am using spanmetrics connector to generate metrics from span. The **`calls`** metrics is counter metrics so it's value should always increase but i can see graph going up and down of metrics generated  by this connector

## Steps to Reproduce
Using spanmetrics connector config and passing it as exporter in trace pipeline and receiving it in metrics pipeline.
```
connectors:
   count:
    servicegraph:
      latency_histogram_buckets: [5ms, 30ms, 100ms, 500ms, 2s]
      dimensions:
        - span.kind
      #   - dimension-2
      store:
        ttl: 5s
        max_items: 5000
    spanmetrics:
      histogram:
        explicit:
          buckets: [2ms, 6ms, 10ms, 100ms, 250ms, 500ms, 2s]
      dimensions:
        # - name: http.method
        #   default: GET
        - name: http.status_code
      dimensions_cache_size: 100000
      aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
```

## Expected Result
calls and duration_count is counter metrics so there value should always increase

## Actual Result
When graph ploted using these metrics it's going up and down
<img width="1713" alt="Screenshot 2023-04-21 at 7 58 29 PM" src="https://user-images.githubusercontent.com/113598893/233690312-90ec6fae-86f7-4c4f-91a1-fc468635468f.png">

### Collector version

0.75.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
    otlp:
      headers:
        x-scope-orgid: ****
      endpoint: *.*.*.*:4317
      tls:
        insecure: true
    prometheus:
      endpoint: "0.0.0.0:8081"
  extensions:
    health_check: {}
    memory_ballast: {}
  processors:
    batch: {}
    tail_sampling:
      decision_wait: 10s
      num_traces: 100
      expected_new_traces_per_sec: 100
      policies:
        [{ name: latency_policy, type: latency, latency: { threshold_ms: 1 } }]
    memory_limiter: null
  connectors:
    count:
    servicegraph:
      latency_histogram_buckets: [5ms, 30ms, 100ms, 500ms, 2s]
      dimensions:
        - span.kind
      store:
        ttl: 5s
        max_items: 5000
    spanmetrics:
      histogram:
        explicit:
          buckets: [2ms, 6ms, 10ms, 100ms, 250ms, 500ms, 2s]
      dimensions:
        - name: http.status_code
      dimensions_cache_size: 100000
      aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
  receivers:
    otlp:
      protocols:
        grpc:
          include_metadata: true
          endpoint: 0.0.0.0:4317
  service:
    telemetry:
      metrics:
        address: 0.0.0.0:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      traces:
        exporters:
          - otlp
          - count
          - servicegraph
          - spanmetrics
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        receivers:
          - count
          - servicegraph
          - spanmetrics
        exporters:
          - prometheus
```

**Comment by fatsheep9146** [comment]
dos the collector keep restarting?

**Comment by harshraigroww** [comment]
no, collector is not restarting

**Comment by aptomaKetil** [comment]
I'm seeing the same issue when running more than one instance of the collector with the spanmetrics connector enabled. The generated metrics do not have a label unique to that instance of the collector, so any metrics generated for a given span end up in the same timeseries even though they are different counters from different collectors.

**Comment by fatsheep9146** [comment]
> I'm seeing the same issue when running more than one instance of the collector with the spanmetrics connector enabled. The generated metrics do not have a label unique to that instance of the collector, so any metrics generated for a given span end up in the same timeseries even though they are different counters from different collectors.


Could you share your configuration? @aptomaKetil

**Comment by aptomaKetil** [comment]
Sure @fatsheep9146:

```yaml
---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp/tempo:
    endpoint: tempo-distributor:4317
    compression: gzip
    balancer_name: round_robin
    tls:
      insecure: true
  otlphttp/mimir:
    endpoint: http://mimir-distributor:8080/otlp
    tls:
      insecure: true
    compression: gzip

connectors:
  spanmetrics:
    histogram:
      explicit: null
      exponential:
        max_size: 64
    dimensions:
      - name: http.route
      - name: http.method
      - name: db.system
      - name: service.namespace
    namespace: spanmetrics

processors:
  k8sattributes:
    extract:
      metadata:
        - k8s.namespace.name
        - k8s.pod.name
        - k8s.node.name
      labels:
        - tag_name: __app
          key: app.kubernetes.io/name
          from: pod
        - tag_name: __app
          key: app
          from: pod
        - tag_name: __app
          key: k8s-app
          from: pod
        - tag_name: service.version
          key: app.kubernetes.io/version
          from: pod
    pod_association:
      - sources:
          - from: connection
  resource:
    attributes:
      - key: service.name
        from_attribute: __app
        action: upsert
      - key: service.instance.id
        from_attribute: k8s.pod.name
        action: upsert
      - key: service.namespace
        from_attribute: k8s.namespace.name
        action: upsert

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - memory_limiter
        - k8sattributes
        - resource
        - batch
      exporters: [otlp/tempo, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors:
        - memory_limiter
        - k8sattributes
        - resource
        - batch
      exporters: [otlphttp/mimir]
    logs: null
```
