### ISSUE TITLE
[tlscheckreceiver] new receiver

### ISSUE THREAD

**Issue by hecomp** [open-telemetry/opentelemetry-collector-contrib#21107]
### Describe the issue you're reporting

The TLS Check Receiver propose to check protocol versions, certificate expiration, validity, and other statuses.  It is crucial to have visibility into certificate expiration and other TLS-related issues to ensure the security of our systems. We propose the addition of a new TLS Check Receiver that will allow users to monitor and receive alerts on their TLS certificates' status.

Here's an example configuration:

```
receivers:
  tlscheck:
    endpoint: localhost:8443
    tls:
      insecure_skip_verify: true
    collection_interval: 10s

exporters:
  logging:
    loglevel: debug

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [tlscheck]
      processors: [batch]
      exporters: [logging]


metrics:
  tlscheck.days_left:
    enabled: true
    description: Days until X.509 certificate expiration.
    unit: s
    gauge:
      value_type: int
  tlscheck.seconds_left:
    enabled: true
    description: Seconds until X.509 certificate expiration.
    unit: s
    gauge:
      value_type: int
  tlscheck.issued_days:
    enabled: true
    description: Day duration of timespan certificate is issued for.
    unit: s
    gauge:
      value_type: int
  tlscheck.issued_seconds:
    enabled: true
    description: Second duration of timespan certificate is issued for.
    unit: s
    gauge:
      value_type: int
  tlscheck.error:
    description: Records errors occurring during HTTP check.
    enabled: true
    sum:
      value_type: int
      aggregation: cumulative
      monotonic: false
    unit: "{error}"
    attributes: [error.message]

**Comment by atoulme** [comment]
What metrics would you collect? Please follow a metadata.yaml file and post the metrics you have in mind. Initially it’s better to aim for a small subset.

**Comment by hecomp** [comment]
> What metrics would you collect? Please follow a metadata.yaml file and post the metrics you have in mind. Initially it’s better to aim for a small subset.

Addressed question.

**Comment by atoulme** [comment]
I don't think those metrics work quite well.

```
metrics:
```
This is a duplicate of `tlscheck.seconds_left`, the unit is also `s`. I would merge those 2. I would rename it to `tlscheck.time_left`.

```
  tlscheck.days_left:
    enabled: true
    description: Days until X.509 certificate expiration.
    unit: s
    gauge:
      value_type: int
```

```
  tlscheck.seconds_left:
    enabled: true
    description: Seconds until X.509 certificate expiration.
    unit: s
    gauge:
      value_type: int
```
Same for those 2:
```
  tlscheck.issued_days:
    enabled: true
    description: Day duration of timespan certificate is issued for.
    unit: s
    gauge:
      value_type: int
  tlscheck.issued_seconds:
    enabled: true
    description: Second duration of timespan certificate is issued for.
    unit: s
    gauge:
      value_type: int
```
I would use obsreport to report this type of errors. The error message cannot be a dimension of the metric.
```
  tlscheck.error:
    description: Records errors occurring during HTTP check.
    enabled: true
    sum:
      value_type: int
      aggregation: cumulative
      monotonic: false
    unit: "{error}"
    attributes: [error.message]
```
