### ISSUE TITLE
[receiver/mongodbreceiver] Unauthorized to collect index stats on local db with proper role access

### ISSUE THREAD

**Issue by JonathanWamsley** [open-telemetry/opentelemetry-collector-contrib#21114]
### Component(s)

receiver/mongodb

## Description
A scraper error is being emitted while collecting index stats on `local` database, reporting an `Unauthorized` error. Adding in the `clusterMonitor` role and even trying `clusterAdmin` role does not solve this problem. This error has also been reported [here](https://www.mongodb.com/community/forums/t/using-clustermonitor-role-unauthorized-not-authorized-on-local-to-execute-command-aggregate-system-replset-pipeline-indexstats-db-local-readpreference-mode-primary/209566).

## Steps to Reproduce
Run the collector and scrape mongodb metrics with a replica set. Every scrape reports an Unauthorized error.

## Expected Result
To not get any errors.

## Actual Result

```log
Mar 31 16:35:23 custom.env.com otelcol-contrib[1970123]: 2023-03-31T16:35:23.168Z        error        scraperhelper/scrapercontroller.go:212        Error scraping metrics        {"kind": "receiver", "name": "mongodb", "data_type": "metrics", "error": "failed to fetch index stats metrics: (Unauthorized) not authorized on local to execute command { aggregate: \"system.replset\", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID(\"ABC123-4567-891011\") }, $clusterTime: { clusterTime: Timestamp(1680280515, 1), signature: { hash: BinData(0, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA), keyId: 11111111111111111 } }, $db: \"local\", $readPreference: { mode: \"primary\" } }", "scraper": "mongodb"}
```

### Collector version

0.73.0

## Environment
A MongoDB env with a replica set.

### OpenTelemetry Collector configuration

```yaml
receivers:
  mongodb:
    hosts:
      - endpoint: custom.env.com
    username: user
    password: pass
    collection_interval: 60s
    replica_set: rep0
    tls:
      ca_file: /etc/mongo/ssl/mongodb-ca.crt
      cert_file: /etc/mongo/ssl/mongodb.pem
      key_file: /etc/mongo/ssl/mongodb-cert.key
      insecure: false
      insecure_skip_verify: true
​
exporters:
  googlecloud:
      enabled: false
    log:
      default_log_name: opentelemetry.io/collector-exported-log
​
​
processors:
  batch:
​
service:
  pipelines:
    metrics:
      receivers: [mongodb]
      processors: [batch]
      exporters: [googlecloud]
```

### Log output

```shell
Mar 31 16:35:23 custom.env.com otelcol-contrib[1970123]: 2023-03-31T16:35:23.168Z        error        scraperhelper/scrapercontroller.go:212        Error scraping metrics        {"kind": "receiver", "name": "mongodb", "data_type": "metrics", "error": "failed to fetch index stats metrics: (Unauthorized) not authorized on local to execute command { aggregate: \"system.replset\", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID(\"ABC123-4567-891011\") }, $clusterTime: { clusterTime: Timestamp(1680280515, 1), signature: { hash: BinData(0, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA), keyId: 11111111111111111 } }, $db: \"local\", $readPreference: { mode: \"primary\" } }", "scraper": "mongodb"}
```

### Additional context

I can work on this.
