### ISSUE TITLE
[exporter/Loki] multiple attributes for loki not working

### ISSUE THREAD

**Issue by saritatewari4** [open-telemetry/opentelemetry-collector-contrib#21168]
### Component(s)

exporter/loki

### Describe the issue you're reporting

Hello,

I am trying to set multiple labels in loki dashboard, but it's are not working. In the below configuration one label at a time is working but both of them not working together. I can always see app-name in loki dashboard, and if I am adding only traceId id as a label then I can see traceId label  after removing app_name.This app_name and traceId I am setting from flauntD manifest file

```
config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      fluentforward:
        endpoint: 0.0.0.0:8006
    exporters:
      otlp:
        endpoint: http://tempo
        tls:
          insecure: true  
      logging:
        logLevel: "INFO"
        verbosity: detailed
      loki:
        endpoint: http://loki:3100/loki/api/v1/push
        tls:
          insecure: true
    processors:
      batch:
      attributes:
        actions:
          - action: insert
            key: loki.attribute.labels
            value: app_name
          - action: insert
            key: loki.attribute.labels
            value: traceId
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
        logs:
          receivers: [ fluentforward ]
          processors: [ attributes, batch  ]
          exporters: [ logging, loki ]
```

This is my loki dashboard:

<img width="1724" alt="Screenshot 2023-04-25 at 8 36 09 PM" src="https://user-images.githubusercontent.com/72062903/234321126-e96b72a1-acfe-46a2-9ead-d50b621e989d.png">

Please help me where the configuration is wrong.
