### ISSUE TITLE
Datadog exporter - Support for Histogram percentiles

### ISSUE THREAD

**Issue by datsabk** [open-telemetry/opentelemetry-collector-contrib#21170]
### Component(s)

exporter/datadog

### Is your feature request related to a problem? Please describe.

As per [this](https://docs.datadoghq.com/metrics/open_telemetry/otlp_metric_types?tab=histogram) document, Datadog exporter should be generated approximiate percentiles (Quoting the statement below). However, as of today, percentile generation is not supported in Datadog exporter - Count and Sum metrics do land as expected in Datadog. 

```
Note: Histogram metrics in OTLP are mapped to Distribution metrics. Because of how OTLP sends this data, the max, min, and percentile aggregations are approximations, not accurate calculations.
```

Requesting expertise from Datadog team to successfully pipeline percentile metrics (similar to what DogStatsD server does) 

### Describe the solution you'd like

```
metrics:
      resource_attributes_as_tags: true
      histograms:
        send_aggregation_metrics: true
        percentiles: 
          send_percentile_metrics: true
          percentiles:
            - 95
            - 99
            - 75
```
This would allow us to generate percentiles as needed similar to Datadog agent. 

### Describe alternatives you've considered

The only other alternate is to get rid of Open Telemetry collector and start using Datadog agent for this purpose.
