### ISSUE TITLE
Add Include/Exclude Filtering to resourceprocessor 

### ISSUE THREAD

**Issue by mtarcha** [open-telemetry/opentelemetry-collector-contrib#21186]
### Component(s)

processor/resource

### Is your feature request related to a problem? Please describe.

Use case:
I would like to be able to insert resource attributes to a span if that span attributes match some condition (regex in my case) 

### Describe the solution you'd like

Add Include/Exclude Filtering feature to resourceprocessor same as we have for attributesprocessor: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/README.md#includeexclude-filtering

then usage would look for example like this:
 
```
     resource/add_team_name:
        include:
          match_type: regexp
          resources:
            - key: service.name
              value: "^service-name-1$|^my-imaginary-service-2$"
        attributes:
          - key: team.name
            value: "sugar-unicorns"
            action: insert
```

### Additional context

I would like to contribute and implement it if that is ok
