### ISSUE TITLE
[receiver/datadog] `service.name` not set at trace resource resulting in `OTLPResourceNoServiceName`

### ISSUE THREAD

**Issue by mvadu** [open-telemetry/opentelemetry-collector-contrib#21210]
### Component(s)

receiver/datadog

## Description
Currently in [addResourceData](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/84d9f4802bb4d82b4702a4eaefc71f2b95cf0826/receiver/datadogreceiver/translator.go#L33)  `service.name` is not set. Its set in the span attributes. Because of this traces exported to backends like Grafana tempo are appearing as `OTLPResourceNoServiceName`.

## Steps to Reproduce
 - Run an app instrumented with datadog tracer (https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/java/?tab=containers)
 - Forward the traces to Grafana tempo using `otel-collector-contrib` with 
 ``` 
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  datadog:
    endpoint: 0.0.0.0:8126
    read_timeout: 60s

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true 
  logging:
  prometheus:
    endpoint: "otelcol:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [datadog]
      processors: [batch]
      exporters: [otlp]
```

- Validate the traces received in Tempo

## Expected Result
The service Name should be populated in Service Name filter which uses the Resources section
ref: 

## Actual Result
The `Resource` section does not contains a `service.name` tag, thus resulting in `OTLPResourceNoServiceName` 
![image](https://user-images.githubusercontent.com/8618235/234744872-e1547a01-db30-4cdd-98ee-72510ee546ce.png)

### Collector version

v0.75.0

## Environment
OS: Ubuntu 20

### OpenTelemetry Collector configuration

```yaml
receivers:
 otlp:
   protocols:
     grpc:
     http:
       cors:
         allowed_origins:
           - "http://*"
           - "https://*"
 datadog:
   endpoint: 0.0.0.0:8126
   read_timeout: 60s

exporters:
 otlp:
   endpoint: tempo:4317
   tls:
     insecure: true 
 logging:
 prometheus:
   endpoint: "otelcol:9464"
   resource_to_telemetry_conversion:
     enabled: true
   enable_open_metrics: true

processors:
 batch:

service:
 pipelines:
   traces:
     receivers: [datadog]
     processors: [batch]
     exporters: [otlp]
```
