### ISSUE TITLE
k8sattributes processor not allowing metadata

### ISSUE THREAD

**Issue by v1ctorrhs** [open-telemetry/opentelemetry-collector-contrib#21228]
### Component(s)

processor/k8sattributes

## Description

According to k8sattributes processor [README.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md) L64 and [config.goL78 
](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/config.go#L78) point that if container.id is provided k8s.container.name will be available as an attribute.

However, I can't get that to work as expected.
## Steps to Reproduce
k8sattributes config
```
      k8sattributes:
        passthrough: false
        auth_type: "serviceAccount"
        extract:
          metadata:
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.start_time
          - container.id
          labels:
          # extracts value of label from pods with key `app.kubernetes.io/version` and inserts it as a tag with key `service.version`
          - tag_name: service.version
            key: app.kubernetes.io/version
            from: pod
        pod_association:
          - sources:
            - from: connection
          - sources:
            - from: resource_attribute
              name: k8s.pod.ip
          - sources:
            - from: resource_attribute
              name: k8s.pod.uid
          # below association matches for pair `k8s.pod.name` and `k8s.namespace.name`
          - sources:
            - from: resource_attribute
              name: k8s.pod.name
            - from: resource_attribute
              name: k8s.namespace.name
```
This config returns the following attributes
<img width="578" alt="image" src="https://user-images.githubusercontent.com/67688658/234913747-e28cb487-2bdb-4a4f-9933-464da0918632.png">

If i try to add
```
extract:
 metadata:
 ...
 ...
 - k8s.container.name
``` 
I get the following error

>2023-04-27T15:30:47.009Z	debug	processor/processor.go:298	Beta component. May change in the future.	{"kind": "processor", "name": "resource", "pipeline": "traces"}
2023-04-27T15:30:47.009Z	debug	processor/processor.go:298	Beta component. May change in the future.	{"kind": "processor", "name": "k8sattributes", "pipeline": "traces"}
Error: failed to build pipelines: failed to create "k8sattributes" processor, in pipeline "traces": "k8s.container.name" is not a supported metadata field
2023/04/27 15:30:47 collector server run finished with error: failed to build pipelines: failed to create "k8sattributes" processor, in pipeline "traces": "k8s.container.name" is not a supported metadata field

### Collector version

v0.75.0
