### ISSUE TITLE
[SplunkHecReceiver] Add resource configuration for custom metadata

### ISSUE THREAD

**Issue by splunkericl** [open-telemetry/opentelemetry-collector-contrib#21466]
**Is your feature request related to a problem? Please describe.**
As an user of SplunkHecReceiver, I want to add my own custom metadata as part of the resources for the log records and metrics. Our application requires these metadata to identify which receiver is sending data in the processor and observe metrics on our processor.

**Describe the solution you'd like**
A new config option is added:
```
resources map[string]any{}
```
When log records are created, what is specified in the resources are appended as part of the resources.

**Describe alternatives you've considered**
Adding stanza libs similar to filelogreceiver and syslogreceiver. However, these operators can't be added easily on top of the existing http server.

**Comment by dmitryax** [comment]
Most of the receivers set Scope Name field on the generated data like `otelcol/apache` (the format will likely be changed based once https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21382 is resolved). We can make sure the Splunk HEC receiver also sets the Scope Name as well. Then you can use your custom processor to create any resource attributes from that scope name. How does it sound?

**Comment by atoulme** [comment]
> The resource processor extends the attributes processor, so you should be able in any case to express a match on the data flowing through the pipeline to tag selectively based on the data properties: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/README.md

I was wrong, sorry. The resource processor does not allow matching. It's likely the transform processor would be more versatile for your use case.

> We can make sure the Splunk HEC receiver also sets the Scope Name as well.

I checked and we don't currently set the scope name in the HEC receiver, that can certainly be added.

**Comment by dmitryax** [comment]
> This helps to identify which receiver it comes from. But we still need one metadata, datasetName, that is specific to our business logic. We can have multiple pipelines each with a HEC receiver but they would have different datasetName.

So you want to have different instances of HEC receivers in one pipeline?

**Comment by splunkericl** [comment]
>So you want to have different instances of HEC receivers in one pipeline?

That is also a possibility in the future. But for today's use case, our processor is shared among different pipeline so it needs a way to identify which HEC receiver is sending the data. So an example is:
- log/pipeline_1:
  - receivers:  
    - splunkhecreceiver/id1:
        - datasetName: a
  - processors
    - customProcessor
- log/pipeline_2:
  - receivers:
    - splunkhecreceiver/id2:
        - datasetName: b
  - processors
    - customProcessor

If the processor only checks the scope name, it wouldn't know if it is id1 or id2 sending the data, correct? Unless there are other metadata that let us identify them that I am missing?

**Comment by dmitryax** [comment]
If you already have several pipelines, why don't just add the different resource processor in each of them?

```yaml
log/pipeline_1:
  receivers:
    - splunkhecreceiver/id1
  processors:
    - resource/a
    - customProcessor
log/pipeline_2:
  receivers:
  - splunkhecreceiver/id2:
  processors:
    - resource/b
    - customProcessor
```

**Comment by dmitryax** [comment]
Ok, then instead of resource processor you can use transform processor

```yaml
transform/scope:
  metric_statements:
  - context: log
    statements:
      - set(attributes["datasetName"], "a") where instrumentation_scope.name == "otelcol/splunkhec"
      - set(attributes["datasetName"], "b") where instrumentation_scope.name == "otelcol/syslog"
      - set(attributes["datasetName"], "c") where instrumentation_scope.name == "otelcol/s2s"
```
