### ISSUE TITLE
resource_attribute not emerging with metrics

### ISSUE THREAD

**Issue by zchef2k** [open-telemetry/opentelemetry-collector-contrib#21477]
### Component(s)

receiver/sshcheck

### Describe the issue you're reporting

I'm appealing to splunk-otel-collector to include sshcheck in that release. In my testing of the code to include sshcheck, I've noticed that the resouce_attribute ```ssh.endpoint``` does not emerge with the metrics being collected- the net effect being is I have successful collection of metrics but I don't know for what machines/endpoints.

Please let me know if I've misinterpreted the available documentation, if I have a flaw in my testing, or could improve the quality of this issue. Thank you.

https://github.com/signalfx/splunk-otel-collector/issues/3050#issuecomment-1532787623

edit: typos, clarification.

**Comment by atoulme** [comment]
By default, resource attributes are not enabled. You will need to add a configuration entry:
```
receivers:
  sshcheck:
    resource_attributes:
       ssh.endpoint:
         enabled: true
```

Please try it out and let us know if it works.

**Comment by zchef2k** [comment]
This has been my config for testing, the `resource_attributes` bits having been most recently added before I submitted the issue.

```
  sshcheck:
    endpoint: <redacted>:22
    username: zchef2k
    key_file: /etc/otel/collector/id_rsa
    known_hosts: /etc/otel/collector/known_hosts
    ignore_host_key: true
    collection_interval: 30s
    resource_attributes:
      ssh.endpoint:
        enabled: true
```
Again, I do get the metrics, just not the resource_attribute with them.
