### ISSUE TITLE
[exporter/loki]Collector crashing using latest image 'error decoding 'exporters': error reading configuration for "loki"'

### ISSUE THREAD

**Issue by MysterioO** [open-telemetry/opentelemetry-collector-contrib#21473]
### Component(s)

exporter/loki

## Description
Using latest collector version we get our pods in CrashLoopBackOff, with error posted in log output. Once we rollback  to otel/opentelemetry-collector-contrib:0.75.0, collector starts working as before. What changed has been introduced with latest image to be causing this ? 

 

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
processors:
      batch:
        send_batch_size: 2000
        send_batch_max_size: 4000
      
      #Get k8s attributes 
      k8sattributes:
        auth_type: "serviceAccount"
        filter:
          node_from_env_var: KUBE_NODE_NAME
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid

      resource:
        attributes:
        - action: insert
          key: k8s.cluster.name
          value: $CLUSTER_NAME
        - action: insert
          key: cluster
          value: $CLUSTER_NAME
        - action: insert
          key: loki.tenant
          from_attribute: k8s.deployment.name
        - action: insert
          key: service.name
          from_attribute: k8s.deployment.name


    exporters:
      logging:
        verbosity: normal #detailed
        sampling_initial: 5
        sampling_thereafter: 200

      loki:
        endpoint: redacted
        tls:
          insecure_skip_verify: true
        labels:
          resource:
            k8s.container.name: k8s_container_name
            k8s.pod.name: k8s_pod_name
            k8s.node.name: k8s_node_name
            k8s.cluster.name: k8s_cluster_name
            k8s.namespace.name: k8s_namespace_name
            k8s.deployment.name: k8s_deployment_name

    service:
      pipelines:
        logs:
          receivers: 
            - filelog
          processors:  
            - batch
            - k8sattributes
            - resource
          exporters:
            - loki
            - logging
```

### Log output

```shell
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': error reading configuration for "loki": 1 error(s) decoding:

* '' has invalid keys: labels
2023/05/03 07:47:22 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': error reading configuration for "loki": 1 error(s) decoding:

* '' has invalid keys: labels
```
