### ISSUE TITLE
Prometheus Receiver is incompatible with Prometheus behaviour on how checks on file_sd_configs are handled

### ISSUE THREAD

**Issue by PaurushGarg** [open-telemetry/opentelemetry-collector-contrib#21509]
### Component(s)

receiver/prometheus

## Description
Currently, Prometheus Receiver fails with error during [config validation ](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5f47f5b182ce4fdcaf0ce40fd08bf3b64420bbbd/receiver/prometheusreceiver/config.go#L111) when `sd_file` is not found but provided in the `file_sd_config`. However, Prometheus in the absence of `sd_files` or `targetgroups` only [logs the error](https://github.com/prometheus/prometheus/blob/c0c22ed04200a8d24d1d5719f605c85710f0d008/discovery/file/file.go#L337) and continue to watch the sd_file_path. 
This issue was opened on aws-observability/aws-otel-collector repo [here](https://github.com/aws-observability/aws-otel-collector/issues/2039).
This issue also breaks the ECS_Observer as [given](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5373) here.
## Steps to Reproduce
Run the Otel Collector and Prometheus with the `file_sd_config` configuration.

## Expected Result
Expected to see compatibility between Otel Collector (Prometheus Receiver) and Prometheus handling of the `file_sd_config` sd_file validation check, and didn't expect Otel Collector to fail in absence of sd_file.

## Actual Result
In absence of `sd_file`, Otel Collector exits, while Prometheus continues to watch the sd_file_path.

### Collector version

v0.76.3

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "ecssd"
          file_sd_configs:
            - files:
                - 'ecs_sd_targets.yaml'

exporters:
  logging:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: ${log_level}
  pipelines:
    metrics:
      receivers: [ prometheus ]
      exporters: [ logging ]
```
