### ISSUE TITLE
Since v0.75.0, the hostmetricsreceiver emits metrics with empty string attribute values

### ISSUE THREAD

**Issue by jacobmarble** [open-telemetry/opentelemetry-collector-contrib#21527]
Since otelcol-contrib v0.75.0, the hostmetrics receiver is emitting metrics with empty string attribute values, such as `device = string("")`. I've confirmed that this behavior started in v0.75.0.

I'm not certain that empty attribute values are disallowed in the otel spec, but the influxdbexporter has rejected empty attribute values since it has existed.

_Originally posted by @jacobmarble in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21474#issuecomment-1536800106_

## Steps to Reproduce:

otelcontribcol config:
```yaml
receivers:
  hostmetrics:
    collection_interval: 1s
    scrapers:
      cpu:
      memory:
      filesystem:
      paging:
      process:
        metrics:
          process.cpu.time:
            enabled: false
          process.memory.utilization:
            enabled: true

exporters:
  file:
    path: /tmp/metrics.json

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [file]
```

Run for a few seconds, then stop and search the resulting metrics:
```console
$ jq '.. | select(type == "object" and has("key") and has("value") and .value == {"stringValue": ""})' /tmp/metrics.json
{
  "key": "device",
  "value": {
    "stringValue": ""
  }
}
{
  "key": "device",
  "value": {
    "stringValue": ""
...
```

Where `"stringValue": ""`, the influxdbexporeter fails. (After #21526 is merged, the influxdbexporter will drop the offending attribute and emit a Debug log.)
