### ISSUE TITLE
datadog no resource serviceName 

### ISSUE THREAD

**Issue by rxg456** [open-telemetry/opentelemetry-collector-contrib#21525]
### Component(s)

receiver/datadog

## Description
Currently in addResourceData `service.name` is not set. Its set in the span attributes. Because of this traces exported to backends like jaeger are appearing as `empty-service-name`
## Steps to Reproduce
https://github.com/DataDog/dd-trace-php set env[DD_SERVICE] = my-app

```yaml
receivers:
  datadog:
    endpoint: 0.0.0.0:8126
    read_timeout: 60s
processors:
  batch:
exporters:
  jaeger:
    endpoint: jaeger-collector:14250
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [datadog]
      processors: [batch]
      exporters: [jaeger]
```
## Expected Result
jaeger ui service name is my-app
## Actual Result
jaeger ui service name is empty-service-name
![image](https://user-images.githubusercontent.com/57221135/236620193-c6c631e2-b4c5-4a66-ba6b-c8c5a19bcdf9.png)

### Collector version

v0.76.1

## Environment
OS:  Ubuntu 20.04

### OpenTelemetry Collector configuration

```yaml
receivers:
  datadog:
    endpoint: 0.0.0.0:8126
    read_timeout: 60s
processors:
  batch:
exporters:
  jaeger:
    endpoint: jaeger-collector:14250
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [datadog]
      processors: [batch]
      exporters: [jaeger]
```

### Additional context

<img width="984" alt="image" src="https://user-images.githubusercontent.com/57221135/236620287-0d42c526-70e9-494e-a5ec-438874b566f9.png">
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/57221135/236620292-b3c2a42f-d2ca-4c71-8ce7-475596f0fefe.png">

[receiver/datadog] not set at trace resource resulting in OTLPResourceNoServiceName
