### ISSUE TITLE
processes scraper error:  error reading process executable for pid xx: readlink /proc/xx/exe: no such file or directory

### ISSUE THREAD

**Issue by rayrapetyan** [open-telemetry/opentelemetry-collector-contrib#21665]
### Component(s)

receiver/hostmetrics

### What happened?

**IMPORTANT**: this is a regression of `v0.75+` (works as expected in a previous version `v0.74`).
Also reproduces on the latest docker image build (`v0.76.1`).

Happens when running otel-collector-contrib in a docker container:
```
"Labels": {
                "org.opencontainers.image.created": "2023-04-04T08:15:55Z",
                "org.opencontainers.image.name": "opentelemetry-collector-releases",
                "org.opencontainers.image.revision": "06c1c108ae9214c7a5fcb87029085f9a66db7c98",
                "org.opencontainers.image.source": "https://github.com/open-telemetry/opentelemetry-collector-releases",
                "org.opencontainers.image.version": "0.75.0"
            }
```
and mounting `/proc` as `/hostfs/proc`:
```
docker run -v /proc:/hostfs/proc...
```

### Collector version

v0.75.0 and up

## Environment
OS: Debian Bullseye

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics/processes:
    collection_interval: 30s
    root_path: /hostfs
    scrapers:
      processes:
      process:
        include:
          names: foo
          match_type: regexp
        scrape_process_delay: 30s
        mute_process_name_error: true
        metrics:
          process.context_switches:
            enabled: true
          process.memory.usage:
            enabled: true
          process.memory.virtual:
            enabled: true
          process.open_file_descriptors:
            enabled: true
          process.paging.faults:
            enabled: true
          process.threads:
            enabled: true
```

### Log output

```shell
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
	go.opentelemetry.io/collector/receiver@v0.75.0/scraperhelper/scrapercontroller.go:212
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
	go.opentelemetry.io/collector/receiver@v0.75.0/scraperhelper/scrapercontroller.go:191
2023-05-07T21:22:27.126Z	error	scraperhelper/scrapercontroller.go:212	Error scraping metrics	{"kind": "receiver", "name": "hostmetrics/processes", "data_type": "metrics", "error": "error reading process executable for pid 2: readlink /proc/2/exe: no such file or directory; error reading process executable for pid 3: readlink /proc/3/exe: no such file or directory; error reading process executable for pid 4: readlink /proc/4/exe: no such file or directory; error reading process executable for pid 6: readlink /proc/6/exe: no such file or directory; error reading process executable for pid 9: readlink /proc/9/exe: no such file or directory; error reading process executable for pid 10: readlink /proc/10/exe: no such file or directory; error reading process executable for pid 11: readlink /proc/11/exe: no such file or directory; error reading process executable for pid 12: readlink /proc/12/exe: no such file or directory; error reading process executable for pid 13: readlink /proc/13/exe: no such file or directory; error reading process executable for pid 14: readlink /proc/14/exe: no such file or directory; error reading process executable for pid 16: readlink /proc/16/exe: no such file or directory; error reading process executable for pid 17: readlink /proc/17/exe: no such file or directory; error reading process executable for pid 18: readlink /proc/18/exe: no such file or directory; error reading process executable for pid 19: readlink /proc/19/exe: no such file or directory; error reading process executable for pid 21: readlink /proc/21/exe: no such file or directory; error reading process executable for pid 22:...
```
