### ISSUE TITLE
Prometheus Receiver Scraping all pods regardless of Annotation

### ISSUE THREAD

**Issue by 4wdonny** [open-telemetry/opentelemetry-collector-contrib#21739]
### Component(s)

receiver/prometheus

## Description
Prometheus Receiver scrapes every pod in the cluster regardless of the presence of the `prometheus.io/scrape: true` annotation
## Steps to Reproduce
Deploy prometheus receiver with relabel configs to drop all that don't have the prometheus.io/scrape=true annotation

## Expected Result
Only pods with the annotation are scraped
## Actual Result
All pods in the cluster are scraped, leading to log explosion for large clusters with lots of pods. 

### Collector version

0.75.0

## Environment
GKE 1.24

### OpenTelemetry Collector configuration

```yaml
prometheus:
    config:
      scrape_configs:
      - job_name: 'kubernetes-pods'
        scrape_interval: 30s
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: (.+):(?:\d+);(\d+)
          replacement: $${1}:$${2}
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kube_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
```

### Log output

```shell
warn	internal/transaction.go:121	Failed to scrape Prometheus endpoint	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_timestamp": 1683729129956, "target_labels": "{__name__=\"up\", app=\"cert-manager\", app_kubernetes_io_component=\"controller\", app_kubernetes_io_instance=\"cert-manager\", app_kubernetes_io_name=\"cert-manager\", app_kubernetes_io_version=\"v1.10.1\", instance=\"10.3.5.8:9402\", job=\"kubernetes-pods\", kube_namespace=\"cert-manager\", pod=\"cert-manager-7475574-l4c9b\", pod_template_hash=\"7475574\"}"}
```

### Additional context

I realize that the goal of the kubernetes_sd_config Pods job is to discover all pods in the cluster and make them available as scrape targets, but this is polluting not only the Otel agent pods logs, but also the istio side cars of pods that don't export prom metrics with a bunch of failed requests, which seems to be no the intended use of the prom receiver. Please let me know if there's something else I should be doing.
