### ISSUE TITLE
[receiver/filelog] Not respecting order of log messages per file

### ISSUE THREAD

**Issue by SamerJ** [open-telemetry/opentelemetry-collector-contrib#21740]
### Component(s)

receiver/filelog

## Description
We have a log file with 100s of lines. OTEL is configured with a receiver/filelog that will read files from the beginning (start_at: 'beginning'). When OTEL is started, it will read the already existing lines and output the data. The problem we are having is that the order of the log messages isn't preserved **per file**. 
At this point I am not sure what is guaranteed or what configuration can be utilized to preserve the order of logs assuming a sunny scenario.

## Steps to Reproduce
Create a log file with 100s of lines. Run OTEL with the configuration below. Check the exported data. Sometimes the order of the log lines for the file are mixed up. It is flaky, so you might need to run it multiple times.

## Expected Result
Assuming no issues (no failures or retries), the log messages for a given file should be exported in the right order 
i.e line 10 of file A should appear before line 11 of file A.

## Actual Result
For a given file, the order of the log messages isn't guaranteed.

### Collector version

0.75.0

## Environment (Shouldn't matter)
OS: Ubuntu 22.04.2 LTS

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include: [ logs/**/*.* ]
    start_at: 'beginning'
    # max_concurrent_files: 2
    # max_batches: 1
    include_file_name: false
    include_file_path: true
exporters:
  file/logs:
    path: "./out.txt"
service:
  extensions: []
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [file/logs]
```
