### ISSUE TITLE
Filelog Receiver reading incomplete lines

### ISSUE THREAD

**Issue by spruc** [open-telemetry/opentelemetry-collector-contrib#21893]
### Component(s)

receiver/filelog

### Describe the issue you're reporting

The documentation seems to suggest the filelog reader allows reading files that are actively being written to. The receiver however simply reads until the end of the file and then splits log entries by newline character, apparently. This leads to problems when the logging framework at hand hasn't completely flushed the log entries to the log file yet.

Specifically, when reading and writing coincide, an incomplete line might be read. E.g., when logging in JSON format, half a JSON string gets flushed to the log file, is picked up by the filelog receiver before the rest of the string is flushed causing the `json_parser` operator to fail, if you were using that.  This becomes increasingly apparent when using a low `poll_interval`:

```yaml
receivers:
  filelog:
    include: [ /tmp/test.log ]
    poll_interval: 10ms
exporters:
  logging:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [ filelog ]
      processors: [ ]
      exporters: [ logging ]
```

Is the filelog receiver not intended for use with files that are actively being written to?

**Comment by spruc** [comment]
Perhaps I should add that I'm not entirely sure whether this relates to the filelog receiver - it may very well be a flaky file system (for what it's worth, I'm using CephFS on OpenShift). To rule out it's the receiver, I was hoping maybe @djaglowski could tell us whether or not the filelog receiver should be able to correctly handle log files that are actively being written to.

**Comment by djaglowski** [comment]
The receiver should be able to read files that are being actively being written to. However, it should not emit partial lines until some necessary condition is met. With the configuration shown above, it should be looking for newlines only.

> E.g., when logging in JSON format, half a JSON string gets flushed to the log file, is picked up by the filelog receiver before the rest of the string is flushed

Can you confirm whether or not the JSON object is spread across multiple lines? (ie pretty printed)

If it is, each line would be consumed separately, by default. However, you can aggregate these lines by using a `multiline` block:
```yaml
receivers:
  filelog:
    include: [ /tmp/test.log ]
    poll_interval: 10ms
    multiline:
      line_start_pattern: '^\{'
```
