### ISSUE TITLE
Additional attributes not added when parsing failed

### ISSUE THREAD

**Issue by mpostument** [open-telemetry/opentelemetry-collector-contrib#21891]
### Component(s)

receiver/filelog

## Description

When filelog is failing to parse log message no additional attributes added (Assumption)
## Expected Result
All logs entry have additional attributes

## Actual Result
No additional attributes added

### Collector version

0.76.3

## Environment
OS: Amazon linux 2
Kuberentes: EKS

### OpenTelemetry Collector configuration

```yaml
mode: daemonset
config:
  receivers:
    filelog:
      operators:
        - id: get-format
          routes:
            - expr: body matches "^\\\\{"
              output: parser-docker
            - expr: body matches "^[^ Z]+ "
              output: parser-crio
            - expr: body matches "^[^ Z]+Z"
              output: parser-containerd
          type: router
        - id: parser-crio
          output: extract_metadata_from_filepath
          regex: ^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
          timestamp:
            layout: "2006-01-02T15:04:05.000000000-07:00"
            layout_type: gotime
            parse_from: attributes.time
          type: regex_parser
        - id: parser-containerd
          output: extract_metadata_from_filepath
          regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
          timestamp:
            layout: "%Y-%m-%dT%H:%M:%S.%LZ"
            parse_from: attributes.time
          type: regex_parser
        - id: parser-docker
          output: extract_metadata_from_filepath
          timestamp:
            layout: "%Y-%m-%dT%H:%M:%S.%LZ"
            parse_from: attributes.time
          type: json_parser
        - id: extract_metadata_from_filepath
          parse_from: attributes["log.file.path"]
          regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$
          type: regex_parser
        - from: attributes.stream
          to: attributes["log.iostream"]
          type: move
        - from: attributes.container_name
          to: resource["k8s.container.name"]
          type: move
        - from: attributes.namespace
          to: resource["k8s.namespace.name"]
          type: move
        - from: attributes.pod_name
          to: resource["k8s.pod.name"]
          type: move
        - from: attributes.restart_count
          to: resource["k8s.container.restart_count"]
          type: move
        - from: attributes.uid
          to: resource["k8s.pod.uid"]
          type: move
        - from: attributes.log
          to: body
          type: move
        - type: json_parser
          parse_from: body
          parse_to: attributes
      attributes:
        k8s.cluster_name: ${clusterName}
    k8s_events:
      auth_type: serviceAccount
    prometheus:
      config:
        scrape_configs:
          - job_name: kubernetes-pods
            honor_labels: true
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels:
                  [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
                action: replace
                regex: (https?)
                target_label: __scheme__
              - source_labels:
                  [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels:
                  [
                    __meta_kubernetes_pod_annotation_prometheus_io_port,
                    __meta_kubernetes_pod_ip,
                  ]
                action: replace
                regex: (\d+);((([0-9]+?)(\.|$)){4})
                replacement: $$$2:$$$1
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
                replacement: __param_$$$1
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_phase]
                regex: Pending|Succeeded|Failed|Completed
                action: drop
            metric_relabel_configs:
              - target_label: cluster
                replacement: ${clusterName}

          - job_name: "kubernetes-service-endpoints"
            honor_labels: true

            kubernetes_sd_configs:
              - role: endpoints

            relabel_configs:
              - source_labels:
                  [__meta_kubernetes_service_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels:
                  [__meta_kubernetes_service_annotation_prometheus_io_scheme]
                action: replace
                target_label: __scheme__
                regex: (https?)
              - source_labels:
                  [__meta_kubernetes_service_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels:
                  [
                    __address__,
                    __meta_kubernetes_service_annotation_prometheus_io_port,
                  ]
                action: replace
                target_label: __address__
                regex: (.+?)(?::\d+)?;(\d+)
                replacement: $$$1:$$$2
              - action: labelmap
                regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
                replacement: __param_$$$1
              - action: labelmap
                regex: __meta_kubernetes_service_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_service_name]
                action: replace
                target_label: service
              - source_labels: [__meta_kubernetes_pod_node_name]
                action: replace
                target_label: node
            metric_relabel_configs:
              - target_label: cluster
                replacement: ${clusterName}

  exporters:
    otlp:
      endpoint: observability-v2-otel-deployment:4317
      tls:
        insecure: true
  service:
    pipelines:
      logs:
        exporters:
          - logging
          - otlp
        processors:
          - memory_limiter
          - batch
        receivers:
          - k8s_events
          - otlp
      metrics:
        exporters:
          - logging
          - otlp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - prometheus
presets:
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  logsCollection:
    enabled: true
```

### Log output

```shell
otel-daemonset-agent-6rqtw opentelemetry-collector 2023-05-12T06:35:00.734Z	error	helper/transformer.go:110	Failed to process entry	{"kind": "receiver", "name": "filelog", "data_type": "logs", "operator_id": "parser-crio", "operator_type": "regex_parser", "error": "regex pattern does not match", "action": "send", "entry": {"observed_timestamp":"2023-05-12T06:35:00.734340841Z","timestamp":"0001-01-01T00:00:00Z","body":"{\"log\":\"{\\\"service_name\\\": \\\"api\\\", \\\"@message\\\": \\\"0.0.56.213 [12/May/2023:06:35:00 +0000] \\\\\\\"GET /ping HTTP/1.1\\\\\\\" 200 202 \\\\\\\"-\\\\\\\" \\\\\\\"kube-probe/1.23+\\\\\\\"\\\", \\\"@timestamp\\\": \\\"2023-05-12T06:35:00.648165Z\\\", \\\"@source_host\\\": \\\"ds-service-api-759b6b4997-g5fcs\\\", \\\"@fields\\\": {\\\"name\\\": \\\"aiohttp.access\\\", \\\"args\\\": [], \\\"levelname\\\": \\\"INFO\\\", \\\"levelno\\\": 20, \\\"pathname\\\": \\\"/opt/lib-libs/virtualenvs/ds-service/lib/python3.7/site-packages/aiohttp/web_log.py\\\", \\\"filename\\\": \\\"web_log.py\\\", \\\"module\\\": \\\"web_log\\\", \\\"stack_info\\\": null, \\\"lineno\\\": 206, \\\"funcName\\\": \\\"log\\\", \\\"created\\\": 1683873300.648093, \\\"msecs\\\": 648.0929851531982, \\\"relativeCreated\\\": 145656465.8179283, \\\"thread\\\": 139861949314880, \\\"threadName\\\": \\\"MainThread\\\", \\\"processName\\\": \\\"MainProcess\\\", \\\"process\\\": 36, \\\"remote_address\\\": \\\"0.0.56.213\\\", \\\"request_start_time\\\": \\\"[12/May/2023:06:35:00 +0000]\\\", \\\"first_request_line\\\": \\\"GET /ping HTTP/1.1\\\", \\\"response_status\\\": 200, \\\"response_size\\\": 202, \\\"request_header\\\": {\\\"Referer\\\": \\\"-\\\", \\\"User-Agent\\\": \\\"kube-probe/1.23+\\\"}}}\\r\\n\",\"stream\":\"stdout\",\"time\":\"2023-05-12T06:35:00.648385576Z\"}","attributes":{"k8s.cluster_name":"my_cluster","log.file.path":"/var/log/pods/lib_ds-service-api-759b6b4997-g5fcs_bb1403f4-d42c-472f-aea0-7711828662a2/service/0.log"},"severity":0,"scope_name":""}}
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*TransformerOperator).HandleEntryError
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/operator/helper/transformer.go:110
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ParseWith
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/operator/helper/parser.go:151
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWithCallback
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/operator/helper/parser.go:123
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWith
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/operator/helper/parser.go:109
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex.(*Parser).Process
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/operator/parser/regex/regex.go:110
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/transformer/router.(*Transformer).Process
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/operator/transformer/router/router.go:142
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*WriterOperator).Write
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/operator/helper/writer.go:64
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/input/file.(*Input).emit
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/operator/input/file/file.go:65
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Reader).ReadToEnd
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/fileconsumer/reader.go:102
otel-daemonset-agent-6rqtw opentelemetry-collector github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
otel-daemonset-agent-6rqtw opentelemetry-collector 	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.76.3/fileconsumer/file.go:151

otel-daemonset-agent-6rqtw opentelemetry-collector 2023-05-12T06:35:02.734Z	error	helper/transformer.go:110	Failed to process entry	{"kind": "receiver", "name": "filelog", "data_type": "logs", "operator_id": "parser-crio", "operator_type": "regex_parser", "error": "regex pattern does not match", "action": "send", "entry": {"observed_timestamp":"2023-05-12T06:35:02.734816902Z","timestamp":"0001-01-01T00:00:00Z","body":"{\"log\":\"INFO: Bootstrapping with TMPDIR=/dev/shm\\n\",\"stream\":\"stderr\",\"time\":\"2023-05-12T06:35:02.695048291Z\"}","attributes":{"k8s.cluster_name":"my_cluster","log.file.path":"/var/log/pods/lib-645dde1541a84177f930a073-pp4hv_93f2c773-3fdd-4f6d-a624-e991aa528e4b/-645dde1541a84177f930a073/0.log"},"severity":0,"scope_name":""}}
```

### Additional context

I see log messages in elsaticserach, but just few of them has attribute k8s.cluster_name. I would expect this to be present in every log entry. Also not sure why log parsing is failing
