### ISSUE TITLE
[receiver/prometheus] set user-agent header

### ISSUE THREAD

**Issue by seankhliao** [open-telemetry/opentelemetry-collector-contrib#21910]
### Component(s)

receiver/prometheus

## Description

The prometheus receiver only sets a partial user-agent header compared to prometheus

collector receiver:

```
GET /metrics HTTP/1.1
Host: 127.0.0.1:8080
Accept: application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
Accept-Encoding: gzip
User-Agent: Prometheus/
X-Prometheus-Scrape-Timeout-Seconds: 5
```

prometheus:

```
GET /metrics HTTP/1.1
Host: 127.0.0.1:8080
Accept: application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
Accept-Encoding: gzip
User-Agent: Prometheus/2.44.0
X-Prometheus-Scrape-Timeout-Seconds: 5
```

## Steps to Reproduce

run program that logs incoming requests:

```go
package main

import (
	"fmt"
	"net/http"
	"net/http/httputil"

	"github.com/prometheus/client_golang/prometheus/promhttp"
)

func main() {
	prom := promhttp.Handler()

	http.ListenAndServe(":8080", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		b, _ := httputil.DumpRequest(r, false)
		fmt.Println(string(b))
		prom.ServeHTTP(w, r)
	}))
}
```

run collector with prometheus receiver (see below for config).

## Expected Result

something like

```
User-Agent: OpenTelemetry-Collector/0.77.0
```

## Actual Result

```
User-Agent: Prometheus/
```

### Collector version

0.77.0

## Environment
OS: Linux hwaryun 6.3.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000 x86_64 GNU/Linux

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 5s
      scrape_configs:
        - job_name: foo
          static_configs:
            - targets:
              - 127.0.0.1:8080

exporters:
  logging:
  
service:
  pipelines:
    metrics:
      receivers:
        - prometheus
      exporters:
        - logging
```
