### ISSUE TITLE
Cannot extract labels from the pod with k8sattributes

### ISSUE THREAD

**Issue by AndriySidliarskiy** [open-telemetry/opentelemetry-collector-contrib#21918]
### Component(s)

processor/k8sattributes

## Description
I configured k8sattributes to extract labels from pod to log context inside coralogix log but nothing.
## Steps to Reproduce
Configure k8sattributes
## Expected Result
Extract 3 pod labels 
## Actual Result
Nothing

### Collector version

0.77.0

### OpenTelemetry Collector configuration

```yaml
k8sattributes:
      auth_type: "serviceAccount"
      passthrough: false
      filter:
        node_from_env_var: KUBE_NODE_NAME     
      extract:
        metadata:
          - k8s.pod.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.cronjob.name
          - k8s.job.name
        labels:
          - tag_name: job.name
            key: job-name
            from: pod
          - tag_name: controller.uid
            key: controller-uid
            from: pod
          - tag_name: service.instance
            key: app.kubernetes.io/instance
            from: pod
      pod_association:
        - sources:
          - from: connection
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        # below association matches for pair `k8s.pod.name` and `k8s.namespace.name`
        - sources:
          - from: resource_attribute
            name: k8s.pod.name
          - from: resource_attribute
            name: k8s.namespace.name
```

### Log output

```shell
Don`t have error logs about this processor
```
