### ISSUE TITLE
[pkg/ottl] `limit` function can't be used

### ISSUE THREAD

**Issue by swiatekm-sumo** [open-telemetry/opentelemetry-collector-contrib#21920]
### Component(s)

pkg/ottl

## Description
Collector terminated with an error when trying to use the OTTL `limit` function in a transform processor config.

### Collector version

0.77.0

### Environment information
Docker on Linux

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:

processors:
  transform:
    log_statements:
      - context: resource
        statements:
          - limit(attributes, 1, [])

exporters:
  logging:

service:
  pipelines:
    logs:
      exporters: [logging]
      processors: [transform]
      receivers: [otlp]
```

### Log output

```shell
Error: invalid configuration: processors::transform: undefined function limit
2023/05/15 09:50:09 collector server run finished with error: invalid configuration: processors::transform: undefined function limit
```

### Additional context

I think this is because #18822 accidentally set the factory name to uppercase, but functions in OTTL have to be lowercase. See: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d67cbcae5a4cf25e94bef307eab3a6805f561584/pkg/ottl/ottlfuncs/func_limit.go#L33.
