### ISSUE TITLE
How to collect metrics from disks using Hostmetricsreceiver without /proc/stat

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#21984]
### Component(s)

receiver/hostmetrics

## Description
I tried to configure hostmetrics receiver in my config.yaml. This feature is configured in Linux Environment. 
When I run the configuration, it will prompt an error.
Error: cannot start pipelines: open /nfs/proc/stat: no such file or directory
2023/05/15 00:07:16 collector server run finished with error: cannot start pipelines: open <Path>/proc/stat: no such file or directory

## Steps to Reproduce
Configuring the .yaml file with the configuration below. Then run the otelcol-contrib binary.
Configuration:
receivers:
  hostmetrics:
    collection_interval: 15s
    root_path: <Path of my disk>
    scrapers:
      cpu:
      disk:
      filesystem:

## Expected Result
I expected the metrics for the disk in the root_path to be collected and displayed.

## Actual Result
An error is prompted. The error is:
Error: cannot start pipelines: open /nfs/proc/stat: no such file or directory
2023/05/15 00:07:16 collector server run finished with error: cannot start pipelines: open <Path>/proc/stat: no such file or directory

1. May I know how to solve this issue, please? 
2. Is there a way for me to collect the metrics of the specific list of Linux disks without using /proc/stat file?
3. Is there a way for me to collect the metrics when the disks is not specify inside /proc/stat file?

Thank you.

Best Regards,
Erica Ooi

### Collector version

v0.75.0

## Environment
OS: x86-64_linux_4.12_ImageSLES12SP5

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      disk:
      filesystem:

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

  splunk_hec:
    token: "SPLUNK HEC TOKEN"
    endpoint: "SPLUNK COLLECTOR URL"


service:
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8885

  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: []
      exporters: [logging, splunk_hec]
```

### Log output

```shell
Error: cannot start pipelines: open /nfs/proc/stat: no such file or directory
2023/05/15 00:07:16 collector server run finished with error: cannot start pipelines: open <Path>/proc/stat: no such file or directory
```
