### ISSUE TITLE
Unable to filter using resource attributes in Metrics Filter Processor

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#21998]
### Component(s)

processor/filter

## Description
I tried to use the Metrics Filter Processor inside my configuration. I am able to filter according to metrics name.
However, when I tried to filter using metrics name plus resource attributes, it will not have any results.
I have tried for 2 version. One is v0.75.0 while the other is the latest version, v0.77.0. Both are not working too.

## Steps to Reproduce
Configure the .yaml configuration file, then run the .yaml configuration file using the otelcol-contrib binary.
Please refer to the "OpenTelemetry Collector configuration" section for the configurations.

## Expected Result
I expected a set of specific metrics with specific resource attributes according to the filter configurations to be displayed.

## Actual Result
No metrics is displayed in the logging section when the binary is executed after resource attributes is added.

### Collector version

v0.75.0, v0.77.0

## Environment
OS: x86-64_linux_4.12_ImageSLES12SP5

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'node_exporter_filter_7'
        scrape_interval: 10s
        static_configs:
        - targets: ['<NODE EXPORTER ENDPOINT>']

processors:
  batch:

 filter/test:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - node_filesystem_avail_bytes
          - node_filesystem_device_error
        resource_attributes:
          - key: mountpoint
            value: <MOUNTPOINT PATH>

exporters:
  logging:
    verbosity: detailed

  splunk_hec:
    token: "SPLUNK HEC TOKEN"
    endpoint: "SPLUNK COLLECTOR URL"


service:
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8885

  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [filter/test]
      exporters: [logging, splunk_hec]
```

### Additional context

This is one of the node exporter scraped metrics.

# HELP node_filesystem_avail_bytes Filesystem space available to non-root users in bytes.
# TYPE node_filesystem_avail_bytes gauge
node_filesystem_avail_bytes{device="<DEVICE_NAME>",fstype="<FSTYPE>",mountpoint="<MOUNTPOINT_PATH>"} 1.07350556672e+11

Thank you.

Best Regards, 
Erica Ooi

**Comment by TylerHelmuth** [comment]
@ericashi the filterprocessor configuration Include options must all be true in order for the data to pass to the next component in the pipeline.  In your case data will be allowed onward if `(metric name matches node_filesystem_avail_bytes OR metric name matches node_filesystem_device_error) AND there is a resource attribute name mountpoint with a value matching <MOUNTPOINT PATH>`.  Also, you've configured regex matching but it looks like you've provided static values, I recommend switching to `match_type: static`.

Does the data you want to keep always need to be one of those 2 metric name AND contain the specific resource attribute or did you want to keep any data that is either those metric names OR has that specific resource attribute?

**Comment by ericashi** [comment]
Hi @TylerHelmuth ,

Thanks for the reply.
The data I wanted to keep always need to be one of those 2 metric name AND contain the specific resource attribute.
So currently my use case would be to filter to include these two metrics only and will continue to filter the resource attributes which is the mountpoint I configured inside the configuration file.

Based on your recommendation, I changed the match_type: static. However, I got an error.
Error: failed to build pipelines: failed to create "filter/test_2" processor, in pipeline "metrics": unrecognized match_type: 'static', valid types are: [regexp strict]
2023/05/16 17:23:19 collector server run finished with error: failed to build pipelines: failed to create "filter/test_2" processor, in pipeline "metrics": unrecognized match_type: 'static', valid types are: [regexp strict]
Is `match_type: strict` equivalent to `match_type: static`?
I have tried out `match_type: strict` too if it is equivalent to `match_type: static` but it is not working on my side too.

Processor Configuration
  filter/test_2:
    metrics:
      include:
        match_type: strict
        metric_names:
          - node_filesystem_avail_bytes
          - node_filesystem_device_error
        resource_attributes:
          - key: mountpoint
            value: <MOUNTPOINT PATH>

Thank you.

Best Regards,
Erica Ooi

**Comment by TylerHelmuth** [comment]
Ya I meant strict.

You can also try this format:

```yaml
processors:
  filter/ottl:
    error_mode: ignore
    metrics:
      metric:
          - not ((name == "node_filesystem_avail_bytes" or name == "node_filesystem_device_error") and resource.attributes["mountpoint"] == "<MOUNTPOINT PATH>")
```

**Comment by ericashi** [comment]
Hi @TylerHelmuth ,

I have tried out the format you mentioned but it is also not working on my side.

1. Do you know what might be the possible cause for this issue, please?
2. May I know if there is any other workarounds for this feature?

Thank you.

Best Regards,
Erica Ooi

**Comment by ericashi** [comment]
Hi @TylerHelmuth ,

This is some log data I got from the result:

Unix CLI Result:
```
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-05-19 01:40:14.977 +0000 UTC
Value: 819795689472.000000
NumberDataPoints #658
Data point attributes:
     -> device: Str(<DEVICE_NAME>)
     -> fstype: Str(nfs)
     -> mountpoint: Str(<NFS_PATH>)
```

Export result to File
`"timeUnixNano":"1684479461066000000","asDouble":17337679872},{"attributes":[{"key":"device","value":{"stringValue":"<DEVICE_NAME>"}},{"key":"fstype","value":{"stringValue":"nfs"}},{"key":"mountpoint","value":{"stringValue":"<NFS_PATH>"}}]`

We notice that the value is an Object in the File result which the value in the logs have Str() function.
Is this causing us unable to filter according to resource attributes?
If this is the case, how should the resource attributes be written?

Thank you.

Best Regards,
Erica Ooi

**Comment by ericashi** [comment]
Hi @TylerHelmuth ,

Are "Data point attributes:" not considered as "Resource Attributes"?
```
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-05-19 01:40:14.977 +0000 UTC
Value: 819795689472.000000
NumberDataPoints #658
**Data point attributes:
     -> device: Str(<DEVICE_NAME>)
     -> fstype: Str(nfs)
     -> mountpoint: Str(<NFS_PATH>)**
```

Thank you.

Best Regards,
Erica Ooi

**Comment by TylerHelmuth** [comment]
No,datapoints can have attributes, instrumentation scopes can have attributes, and resources can have attributes. 

If the values are actually on the datapoints then you can reference them by removing the "resource_" from the old config or the "resource." from the ottl config.

**Comment by ericashi** [comment]
Hi @TylerHelmuth  ,

I tried out using "attributes" only to filter the mountpoint. However, an error occurs when I ran the configuration.

Configuration:
```
filter/mountstats:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - node_filesystem_avail_bytes
        attributes:
          - key: mountpoint
            value: <MOUNTPOINT_PATH>
```

Error Message:
```
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'processors': error reading configuration for "filter/mountstats": 1 error(s) decoding:
* 'metrics.include' has invalid keys: attributes
2023/05/24 03:15:45 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'processors': error reading configuration for "filter/mountstats": 1 error(s) decoding:
* 'metrics.include' has invalid keys: attributes`
```

Configuration:
```
filter/ottl:
    error_mode: ignore
    metrics:
      metric:
          - not ((name == "node_filesystem_avail_bytes" or name == "node_filesystem_device_error") and attributes["mountpoint"] == "<MOUNTPOINT PATH>")
```

Error Message:
```
Error: invalid configuration: processors::filter/ottl: invalid metric path expression [{attributes [{<nil>}]}]
2023/05/24 17:39:23 collector server run finished with error: invalid configuration: processors::filter/ottl: invalid metric path expression [{attributes [{<nil>}]}]
```

Currently I am using Opentelemetry v0.77.0. Is this due to the current version I am using? 
If yes, may I know what is the right version I should use for this to work and will the feature be added into the latest version?
Or if there is any other workarounds for this issue?

Thank you.

Best Regards,
Erica Ooi

**Comment by TylerHelmuth** [comment]
In my haste I messed up the config:

```yaml
processors:
  filter/ottl:
    error_mode: ignore
    metrics:
      datapoint:
          - not ((name == "node_filesystem_avail_bytes" or name == "node_filesystem_device_error") and attributes["mountpoint"] == "<MOUNTPOINT PATH>")
```
