### ISSUE TITLE
MSSQL Container receiver

### ISSUE THREAD

**Issue by astingengo** [open-telemetry/opentelemetry-collector-contrib#21999]
### Describe the solution you'd like

Can be there created a receiver for sql server not only for Windows [a Linux/Container solution]
Something like
```
      sqlreceiver:
        endpoint: https://sql:1433
        username: sa
        password: passwordhere
```
