### ISSUE TITLE
processor/routing ignores context attributes statements

### ISSUE THREAD

**Issue by FrsRsdXt** [open-telemetry/opentelemetry-collector-contrib#22003]
### Component(s)

processor/routing

## Description
Routing config does not work for context attributes, all traces exported into default exporter instead
Tried several context attributes to test the router such as
1. attributes = http.method value = GET
2. attributes = project_code value = t575-p178 (configuration provided below)

## Steps to Reproduce
Deployed Otel Collector on ECS Fargate using the configuration provided below. 

## Expected Result
Tried several context attributes to test the router such as
1. attributes = http.method value = GET
this configuration should export all traces into xray that matches http.method = GET context attributes. And export non matching traces to logs

2. attributes = project_code value = t575-p178 (configuration provided below)
this configuration should export all traces into xray that matches project_code = t575-p178 context attributes. And export non matching traces to logs

## Actual Result
all configuration using context attributes exports traces into logs 

### Collector version

v0.77.0

## Environment
OS: Amazon Linux 2 on ECS Fargate

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        include_metadata: true
      http:
        endpoint: 0.0.0.0:4318
  awsxray:
    endpoint: 0.0.0.0:2000
    transport: udp

processors:
  routing:
    default_exporters:
    - logging
    from_attribute: project_code
    attribute_source : context
    table:
    - value: t575-p178
      exporters: 
      - awsxray

exporters:
  awsxray:
    endpoint: xray.ap-southeast-1.amazonaws.com
    index_all_attributes: true
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      exporters: [awsxray,logging]
      processors: [routing]

  extensions: [health_check]
```

### Additional context

router works for resource attributes
