### ISSUE TITLE
[pkg/ottl] Update contexts so that all time fields Getters return `time.Time` and Setters take `time.Time`

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#22010]
OTTL contexts are updated so that all time fields Getters return `time.Time` and Setters take `time.Time`.  The accessor names should be updated to drop the time precision (`_nano`).

Context and fields that need updating:
- ottldatapoint
  - start_time_unix_nano
  - time_unix_nano
- ottllog
  - time_unix_nano
  - observed_time_unix_nano
- ottlspan
  - start_time_unix_nano
  - end_time_unix_nano
- ottlspanevent
  - time_unix_nano  

Will also need to update all the `cache` accessors to be able to handle getting and setting `time.Time` and `time.Duration`.  Instead of getting and setting a `pcommon.Map` it should be expressed as a `map[string]string`.

**Comment by ptimofee** [comment]
Just hit this with newly introduced in 0.81.0 Time() converter when wanted to convert some fields from k8s events to Timestamp to send event logs to ElasticSearch
```
      transform:
        error_mode: ignore
        log_statements:
        - context: log
          statements:
          - set(time_unix_nano, Time(body["object"]["eventTime"], "%Y-%m-%dT%H:%M:%SZ")) where body["object"]["eventTime"] != nil
          - set(time_unix_nano, Time(body["object"]["deprecatedLastTimestamp"], "%Y-%m-%dT%H:%M:%SZ")) where body["object"]["deprecatedLastTimestamp"] != nil
```
Looking forward to it!
