### ISSUE TITLE
purefa receiver needs to provide fa_array_name throughout

### ISSUE THREAD

**Issue by james-laing** [open-telemetry/opentelemetry-collector-contrib#22027]
### Component(s)

receiver/purefa

## Description
The receiver has no way of correlating metrics to the device endpoint (the FlashArray).
In config.yaml `endpoint` is defined as the OpenMetrics exporter host and mapped to `host`. `address` is mapped to `purefa_info{fa_array_name}` across each of the target /metric/endpoints but no across all metrics.
This means that when multiple Pure Storage FlashArray's are being scraped by the OpenMetrics exporter, all metrics are tagged with the host name of the OpenMetrics exporter address and not the device endpoint.

## Suggestion
1. tag `endpoint` (not host) to every single metric. This would ensure consistency between config.yaml and scraped metrics.
2. scrape the label from 'purefa_info:{array_name}' from each `/metric/endpoint` and tag every single metric as 'fa_array_name' that way we capture the array name directly from the array.
## Steps to Reproduce
Just scrape any data from FlashArray
## Expected Result
```receivers:
  purefa/array01:
    endpoint: http://pure-ome:9490/metrics # tag endpoint (not host) to every single metric 
    array:
      - address: array01 # scrape the label from 'purefa_info:{array_name}' and apply to every single metric as 'fa_array_name'
        auth:
          authenticator: bearertokenauth/array01
    env: prod
    settings:
      reload_intervals:
        array: 2m
```
## Actual Result
```receivers:
  purefa/array01:
    endpoint: http://pure-ome:9490/metrics
    array:
      - address: array01
        auth:
          authenticator: bearertokenauth/array01
    env: array01
    settings:
      reload_intervals:
        array: 2m
```

### Collector version

otelcontribcol_v0.76.3-PR21100

## Environment
OS: Ubuntu 20.04.4 LTS
Build: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21100

### OpenTelemetry Collector configuration

```yaml
receivers:
  purefa/array01:
    endpoint: http://pure-ome:9490/metrics
    array:
      - address: gse-array01
        auth:
          authenticator: bearertokenauth/array01
    volumes:
      - address: gse-array01
        auth:
          authenticator: bearertokenauth/array01
    hosts:
      - address: gse-array01
        auth:
          authenticator: bearertokenauth/array01
    pods:
      - address: gse-array01
        auth:
          authenticator: bearertokenauth/array01
    directories:
      - address: gse-array01
        auth:
          authenticator: bearertokenauth/array01
    env: array01
    settings:
      reload_intervals:
        array: 2m
        volumes: 2m
        hosts: 2m
        pods: 2m
        directories: 2m
```
