### ISSUE TITLE
Panic using two filtered spanmetrics connectors for metrics pipeline

### ISSUE THREAD

**Issue by taisph** [open-telemetry/opentelemetry-collector-contrib#22034]
### Component(s)

connector/spanmetrics

## Description

I am trying to use a differently partitioned bucket for a certain type of trace spans. If I only send spanmetrics to logging, everything seems to be stable. As soon as I connect both to the metrics pipeline, it panics after running for a few minutes.

## Actual Result

```
panic: runtime error: index out of range [28] with length 0
```

### Collector version

v0.77.0

## Environment
OS: Docker: otel/opentelemetry-collector:0.77.0
Compiler(if manually compiled): go 1.20.4

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  opencensus:
    endpoint: 0.0.0.0:55678

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1800
  batch:
    timeout: 5s
  batch/metrics:
    timeout: 30s
    send_batch_size: 2000
  filter/jobtraces:
    traces:
      span:
      - 'not IsMatch(name, "job\\..+")'
  filter/othertraces:
    traces:
      span:
      - 'IsMatch(name, "job\\..+")'

exporters:
  otlp:
    endpoint: jaeger-collector:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
    send_timestamps: true
    metric_expiration: 5m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: false
  logging:
    verbosity: normal

connectors:
  forward:
  spanmetrics/default:
  spanmetrics/jobs:
    histogram:
      unit: "s"
      explicit:
        buckets: [1ms, 10ms, 50ms, 100ms, 250ms, 500ms, 1s, 5s, 10s, 60s, 300s, 900s]

extensions:
  health_check:
  memory_ballast:
    # Memory Ballast size should be max 1/3 to 1/2 of memory.
    size_mib: 682

service:
  extensions: [health_check, memory_ballast]
  pipelines:
    traces:
      receivers: [otlp, opencensus]
      processors: [memory_limiter, batch]
      exporters: [otlp, logging, forward]
    traces/jobs:
      receivers: [forward]
      processors: [filter/jobtraces]
      exporters: [spanmetrics/jobs]
    traces/other:
      receivers: [forward]
      processors: [filter/othertraces]
      exporters: [spanmetrics/default]
    metrics:
      receivers: [otlp, opencensus, spanmetrics/default, spanmetrics/jobs]
      processors: [memory_limiter, batch/metrics]
      exporters: [prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
  telemetry:
    logs:
      level: info
      encoding: json
      output_paths: stdout
```

### Log output

```shell
{"level":"info","ts":1684312086.8010168,"msg":"TracesExporter","kind":"exporter","data_type":"traces","name":"logging","resource spans":2,"spans":5}
{"level":"info","ts":1684312091.754628,"msg":"MetricsExporter","kind":"exporter","data_type":"metrics","name":"logging","resource metrics":116,"metrics":251,"data points":524}
{"level":"info","ts":1684312091.802254,"msg":"TracesExporter","kind":"exporter","data_type":"traces","name":"logging","resource spans":1,"spans":23}
{"level":"info","ts":1684312106.8045988,"msg":"TracesExporter","kind":"exporter","data_type":"traces","name":"logging","resource spans":1,"spans":2}
{"level":"info","ts":1684312121.759074,"msg":"MetricsExporter","kind":"exporter","data_type":"metrics","name":"logging","resource metrics":127,"metrics":300,"data points":633}
{"level":"info","ts":1684312121.8058608,"msg":"TracesExporter","kind":"exporter","data_type":"traces","name":"logging","resource spans":1,"spans":37}
panic: runtime error: index out of range [28] with length 0

goroutine 130 [running]:
go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1.(*ScopeSpans).MarshalToSizedBuffer(0xc00091c0e0, {0xc02be68a80, 0x6197, 0x61c0})
    go.opentelemetry.io/collector/pdata@v1.0.0-rcv0011/internal/data/protogen/trace/v1/trace.pb.go:956 +0x2f8
go.opentelemetry.io/collector/pdata/internal/data/protogen/trace/v1.(*ResourceSpans).MarshalToSizedBuffer(0xc02c3900c0, {0xc02be68a80, 0x61c0, 0x61c0})
    go.opentelemetry.io/collector/pdata@v1.0.0-rcv0011/internal/data/protogen/trace/v1/trace.pb.go:902 +0x25c
go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1.(*ExportTraceServiceRequest).MarshalToSizedBuffer(0xc02bdcc180, {0xc02be68a80, 0x61c0, 0x61c0})
    go.opentelemetry.io/collector/pdata@v1.0.0-rcv0011/internal/data/protogen/collector/trace/v1/trace_service.pb.go:351 +0xac
go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1.(*ExportTraceServiceRequest).Marshal(0xc000088800?)
    go.opentelemetry.io/collector/pdata@v1.0.0-rcv0011/internal/data/protogen/collector/trace/v1/trace_service.pb.go:331 +0x56
google.golang.org/protobuf/internal/impl.legacyMarshal({{}, {0x3d49d00, 0xc02c0020a0}, {0x0, 0x0, 0x0}, 0x0})
    google.golang.org/protobuf@v1.30.0/internal/impl/legacy_message.go:402 +0xa2
google.golang.org/protobuf/proto.MarshalOptions.marshal({{}, 0x28?, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x3d49d00, 0xc02c0020a0})
    google.golang.org/protobuf@v1.30.0/proto/encode.go:166 +0x27b
google.golang.org/protobuf/proto.MarshalOptions.MarshalAppend({{}, 0x0?, 0x2?, 0x51?}, {0x0, 0x0, 0x0}, {0x3d09060?, 0xc02c0020a0?})
    google.golang.org/protobuf@v1.30.0/proto/encode.go:125 +0x79
github.com/golang/protobuf/proto.marshalAppend({0x0, 0x0, 0x0}, {0x7f7f36822468?, 0xc02bdcc180?}, 0x90?)
    github.com/golang/protobuf@v1.5.3/proto/wire.go:40 +0xa5
github.com/golang/protobuf/proto.Marshal(...)
    github.com/golang/protobuf@v1.5.3/proto/wire.go:23
google.golang.org/grpc/encoding/proto.codec.Marshal({}, {0x3510200, 0xc02bdcc180})
    google.golang.org/grpc@v1.54.0/encoding/proto/proto.go:45 +0x4e
google.golang.org/grpc.encode({0x7f7f36822440?, 0x587c2d0?}, {0x3510200?, 0xc02bdcc180?})
    google.golang.org/grpc@v1.54.0/rpc_util.go:632 +0x44
google.golang.org/grpc.prepareMsg({0x3510200?, 0xc02bdcc180?}, {0x7f7f36822440?, 0x587c2d0?}, {0x0, 0x0}, {0x3d24bb0, 0xc0004a85a0})
    google.golang.org/grpc@v1.54.0/stream.go:1753 +0xd2
google.golang.org/grpc.(*clientStream).SendMsg(0xc000552000, {0x3510200?, 0xc02bdcc180})
    google.golang.org/grpc@v1.54.0/stream.go:874 +0xfd
google.golang.org/grpc.invoke({0x3d32778?, 0xc02bdb6240?}, {0x37a5d48?, 0x4?}, {0x3510200, 0xc02bdcc180}, {0x3510340, 0xc02c644018}, 0x0?, {0xc000050080, ...})
    google.golang.org/grpc@v1.54.0/call.go:70 +0xa8
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryClientInterceptor.func1({0x3d32740, 0xc02bdb6030}, {0x37a5d48, 0x3b}, {0x3510200, 0xc02bdcc180}, {0x3510340, 0xc02c644018}, 0xc000757c00, 0x386e9a8, ...)
    go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.41.1/interceptor.go:100 +0x3e4
google.golang.org/grpc.(*ClientConn).Invoke(0xc000757c00?, {0x3d32740?, 0xc02bdb6030?}, {0x37a5d48?, 0x3b?}, {0x3510200?, 0xc02bdcc180?}, {0x3510340?, 0xc02c644018?}, {0xc0006fedd0, ...})
    google.golang.org/grpc@v1.54.0/call.go:35 +0x223
go.opentelemetry.io/collector/pdata/internal/data/protogen/collector/trace/v1.(*traceServiceClient).Export(0xc00088e170, {0x3d32740, 0xc02bdb6030}, 0x583c000?, {0xc0006fedd0, 0x1, 0x1})
    go.opentelemetry.io/collector/pdata@v1.0.0-rcv0011/internal/data/protogen/collector/trace/v1/trace_service.pb.go:271 +0xc9
go.opentelemetry.io/collector/pdata/ptrace/ptraceotlp.(*grpcClient).Export(0xcbcd15c992?, {0x3d32740?, 0xc02bdb6030?}, {0xc0004a94f0?}, {0xc0006fedd0?, 0x583c000?, 0x3d32740?})
    go.opentelemetry.io/collector/pdata@v1.0.0-rcv0011/ptrace/ptraceotlp/grpc.go:53 +0x30
go.opentelemetry.io/collector/exporter/otlpexporter.(*baseExporter).pushTraces(0xc0005ad970, {0x3d32740?, 0xc02bdb6030?}, {0x3d32778?})
    go.opentelemetry.io/collector/exporter/otlpexporter@v0.77.0/otlp.go:105 +0x69
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesRequest).Export(0x3d32778?, {0x3d32740?, 0xc02bdb6030?})
    go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/traces.go:70 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000429de8, {0x3d3ff48, 0xc02c2a2000})
    go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/common.go:208 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc00086af00, {0x3d3ff48, 0xc02c2a2000})
    go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/queued_retry.go:395 +0x596
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send(0xc000862ab0, {0x3d3ff48, 0xc02c2a2000})
    go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/traces.go:137 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x3d3ff48, 0xc02c2a2000})
    go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/queued_retry.go:206 +0x39
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1()
    go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/internal/bounded_memory_queue.go:58 +0xb6
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers
    go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/internal/bounded_memory_queue.go:53 +0x45
```
