### ISSUE TITLE
replace_all_patterns function for attribute keys doesn not expand regex

### ISSUE THREAD

**Issue by vainiusd** [open-telemetry/opentelemetry-collector-contrib#22094]
### Component(s)

processor/transform

## Description
replace_all_patterns function does not support regex expand replacement for attribute keys
## Steps to Reproduce
```
processors:
  transform:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - replace_all_patterns(attributes, "key", "^dimension_(.+)", "$$1")
```

## Expected Result
```
Attributes:
     -> dimension_A: Str() ==> This should change attr key to A from dimension_A 
     -> dimension_B: Str() ==> This should change attr key to B from dimension_B
```
## Actual Result
```
Attributes:
     -> key_1: Str()
```

### Collector version

v0.77.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
processors:
  transform:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - replace_all_patterns(attributes, "key", "^dimension_(.+)", "$$1")
```

### Log output

```shell
no response
```

### Additional context

Function implementation differs for attribute keys and values. Is there a specific reason for that?

Values: [ReplaceAllString](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a619329714c5ca24b0e9ba2a83025c441cbf35a8/pkg/ottl/ottlfuncs/func_replace_all_patterns.go#LL62C39-L62C55)
Keys: [ReplaceAllLiteralString](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a619329714c5ca24b0e9ba2a83025c441cbf35a8/pkg/ottl/ottlfuncs/func_replace_all_patterns.go#L69)

Use case: bulk rename of attributes.
