### ISSUE TITLE
inconsistent timestamps on metric points for metric up

### ISSUE THREAD

**Issue by shenlvcheng** [open-telemetry/opentelemetry-collector-contrib#22096]
### Component(s)

cmd/otelcontribcol

### Describe the issue you're reporting

**otel collecotr config：**
```
prometheus:
    config:
      scrape_configs:
        - job_name: 'federate'
          scrape_interval: 15s
          honor_labels: true
          metrics_path: '/federate'
          params:
            'match[]':
              - '{job="prometheus"}'
              - '{job="mysql"}'
          static_configs:
            - targets:
              - '192.168.2.245:9090'
```

**prometheus   metrics：**
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="+Inf"} 6.3285439e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="13568.999999999998"} 6.3056218e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="144.99999999999997"} 5.9483332e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="1536.9999999999998"} 6.2455961e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="24.999999999999996"} 3.3698032e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="27264.999999999996"} 6.3218909e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="320.99999999999994"} 6.1425144e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="3200.9999999999995"} 6.2638457e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="64.99999999999999"} 4.6509709e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="6528.999999999999"} 6.29979e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="704.9999999999999"} 6.1907236e+07 1684481521360
go_gc_heap_allocs_by_size_bytes_total_bucket{instance="192.168.2.245:9104",job="mysql",le="8.999999999999998"} 6.137389e+06 1684481521360

**prometheus url：**http://192.168.2.245:9090/federate?match%5B%5D=%7Bjob%3D%22mysql%22%7D

**otel collecotr error：**Appending scrape report failed	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_pool": "federate", "target": "http://192.168.2.245:9090/federate?match%5B%5D=%7Bjob%3D%22mysql%22%7D", "error": "inconsistent timestamps on metric points for metric up"}

I would like to ask how to solve this problem. Is this a bug?
