### ISSUE TITLE
The awscloudwatch receiver isn't able to filter cloudwatch log streams reliably using a stream prefix

### ISSUE THREAD

**Issue by rnishtala-sumo** [open-telemetry/opentelemetry-collector-contrib#22123]
### Component(s)

receiver/awscloudwatch

## Description
The awscloudwatch receiver isn't able to filter logs from cloudwatch log streams reliably using a stream prefix. There are additional logs collected from  log streams that don't share the same prefix.

## Steps to Reproduce
Please use the configuration provided below to reproduce the issue. It uses the following components
- receiver/awscloudwatch
- exporter/logging

## Expected Result
Cloudwatch log streams are filtered reliably using a stream prefix

## Actual Result
Logs are being collected from log streams that do not match the stream prefix in the configuration.

### Collector version

v0.77.0

## Environment
OS: macos (Darwin Kernel Version 22.3.0)

### OpenTelemetry Collector configuration

```yaml
receivers:
  awscloudwatch:
    region: us-east-1
    logs:
      poll_interval: 10s
      groups:
        named:
          fluent-bit-cloudwatch:
            prefixes:
            - from-fluent-bit-kube.var.log.containers.example-pod-multiline-logs-long-lines1

exporters:
  logging:
    verbosity: detailed

service:
  telemetry:
      logs:
        level: "debug"
  pipelines:
    logs:
      receivers: [awscloudwatch]
      exporters: [logging]
```

### Log output

```shell
2023-05-19T19:03:02.817-0400	debug	awscloudwatchreceiver@v0.0.0-00010101000000-000000000000/logs.go:210	===========Group Request===========	{"kind": "receiver", "name": "awscloudwatch", "data_type": "logs", "prefix": "from-fluent-bit-kube.var.log.containers.example-pod-multiline-logs-long-lines1"}

2023-05-19T19:03:03.319-0400	debug	awscloudwatchreceiver@v0.0.0-00010101000000-000000000000/logs.go:210	===========Group Request===========	{"kind": "receiver", "name": "awscloudwatch", "data_type": "logs", "prefix": ""}
```

### Additional context

The logs above show us that an additional request is being made to cloudwatch with the prefix set to "", with the above collector configuration.
