### ISSUE TITLE
The AWS cloudwatch receiver treats every cloudwatch log as a new resource log

### ISSUE THREAD

**Issue by rnishtala-sumo** [open-telemetry/opentelemetry-collector-contrib#22145]
## Description
The AWS cloudwatch receiver treats every cloudwatch log, that belong to the same log stream as a new resource log

## Steps to Reproduce
Please use the configuration below to reproduce the issue. It uses the following components
- receiver/awscloudwatch
- exporter/logging

## Expected Result
Cloudwatch logs that are part of a log stream should ideally be part of the same resource log in the receiver.

## Actual Result
Cloudwatch logs that are part of a log stream are treated as individual resource logs.

### Collector version

v0.77.0

## Environment
OS: macos (Darwin Kernel Version 22.3.0)

### OpenTelemetry Collector configuration

```yaml
receivers:
  awscloudwatch:
    region: us-east-1
    logs:
      poll_interval: 10s
      groups:
        named:
          fluent-bit-cloudwatch:
            prefixes:
            - from-fluent-bit-kube.var.log.containers.example-pod-multiline-logs-long-lines1

exporters:
  logging:
    verbosity: detailed

service:
  telemetry:
      logs:
        level: "debug"
  pipelines:
    logs:
      receivers: [awscloudwatch]
      exporters: [logging]
```

### Log output

```shell
ResourceLog #27
Resource SchemaURL: 
Resource attributes:
     -> aws.region: Str(eu-west-1)
     -> cloudwatch.log.group.name: Str(fluent-bit-cloudwatch)
     -> cloudwatch.log.stream: Str(from-fluent-bit-kube.var.log.containers.example-pod-multiline-logs-long-lines1_demo_example-container-multiline-logs-long-lines-4926d427fb0095dbfa6a0d8dc9bfed3b0099a5ae3f812664b51ff8c2456b4136.log)
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope  
LogRecord #0
ObservedTimestamp: 2023-05-12 13:18:46.622187 +0000 UTC
Timestamp: 2023-05-12 13:18:37.327 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Str({"log":"2023-05-12T13:18:37.327698615Z stdout F 2022-02-08T20:53:28.621+0000 1st single line..."})
Attributes:
     -> id: Str(37552169474347732038449956520910431877939058318515830784)
Trace ID: 
Span ID: 
Flags: 0
-------------------------------------------------------------------------------------------------
ResourceLog #28
Resource SchemaURL: 
Resource attributes:
     -> aws.region: Str(eu-west-1)
     -> cloudwatch.log.group.name: Str(fluent-bit-cloudwatch)
     -> cloudwatch.log.stream: Str(from-fluent-bit-kube.var.log.containers.example-pod-multiline-logs-long-lines1_demo_example-container-multiline-logs-long-lines-4926d427fb0095dbfa6a0d8dc9bfed3b0099a5ae3f812664b51ff8c2456b4136.log)
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope  
LogRecord #0
ObservedTimestamp: 2023-05-12 13:18:46.622187 +0000 UTC
Timestamp: 2023-05-12 13:18:37.327 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Str({"log":"2023-05-12T13:18:37.327749297Z stdout F 2022-02-08T20:53:29.622+0000 2nd single line..."})
Attributes:
     -> id: Str(37552169474347732038449956520910431877939058318515830785)
Trace ID: 
Span ID: 
Flags: 0
```

### Additional context

As seen above, the two logs that belong to the cloudwatch log stream below

```
cloudwatch.log.stream: Str(from-fluent-bit-kube.var.log.containers.example-pod-multiline-logs-long-lines1_demo_example-container-multiline-logs-long-lines-
```

are treated as individual resource logs, instead of being two log records that belong to the same resource.
