### ISSUE TITLE
filter processor based on other processor generated attributes seems not working

### ISSUE THREAD

**Issue by blackluck** [open-telemetry/opentelemetry-collector-contrib#22152]
### Component(s)

processor/filter

### Is your feature request related to a problem? Please describe.

I would like to remove unneeded traces, logs etc. based on k8sresourceattributes generated attributes like namespace name or pods having a label etc. including multiple choices like ns name is test1 or test2. But however I tried to configure it didn't worked, not sure if it's really not working or just I don't know how to. In that case some working examples would be much appreciated.

generating extra attributes
````
  processors:
    batch: {}
    memory_limiter: null
    k8sattributes:
      auth_type: "serviceAccount"
      passthrough: false
      filter:
      extract:
        metadata:
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.start_time
        labels:
          - tag_name: k8s.ns.otel_disabled
            key: otel_disabled
            from: namespace
          - tag_name: k8s.pod.otel_disabled
            key: otel_disabled
            from: pod
      pod_association:
      - sources:
        - from: resource_attribute
          name: k8s.pod.ip
      - sources:
        - from: resource_attribute
          name: k8s.pod.uid
      - sources:
        - from: connection

````
and create filters to remove datas like:

````
    filter/span:
      error_mode: ignore
      spans:
        include:
          match_type: strict
          attributes:
            - key: "k8s.namespace.name"
              value: "test1"
````
````
    filter/span2:
      error_mode: ignore
      spans:
        include:
          match_type: strict
          attributes:
            - key: "k8s.pod.otel_disabled"
              value: "true"
````

and in service 

````
  service:
    telemetry:
      metrics:
        address: ${env:MY_POD_IP}:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      traces:
        exporters:
          - kafka
        processors:
          - k8sattributes
          - memory_limiter
          - filter/span
          - batch
        receivers:
          - otlp

### Describe the solution you'd like

More detailed examples could be very useful.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

**Comment by TylerHelmuth** [comment]
@blackluck if you want to drop data that matches then you should use `exclude` instead of `include` and also `resource_attributes` instead of `attributes`.

Your config
```yaml
filter/span:
      error_mode: ignore
      spans:
        include:
          match_type: strict
          attributes:
            - key: "k8s.namespace.name"
              value: "test1"
```
Will drop any data that DOES NOT contain an attribute named `k8s.namespace.name` with a value of `test1`.  But the k8sattributesprocessor adds the attributes as resource attributes, so your data does not contain an attribute named `k8s.namespace.name` so all your data is dropped.

Instead, you can try 

```yaml
filter/span:
      spans:
        exclude:
          match_type: strict
          resource_attributes:
            - key: "k8s.namespace.name"
              value: "test1"
```

This configuration will drop any data that DOES contain a resource attribute named `k8s.namespace.name` with a value of `test1`.


Even better would be to use the OTTL configuration, which is the future of the processor:
```yaml
filter/span:
  error_mode: ignore
  traces:
    span:
      - 'resource.attributes["k8s.namespace.name"] == "test1"'
```
This configuration drops any data that DOES contain a resource attribute named `k8s.namespace.name` with a value of `test1`.  You can supply multiple statements, and the data will be dropped if any is true 
```yaml
filter/span:
  error_mode: ignore
  traces:
    span:
      - 'resource.attributes["k8s.namespace.name"] == "test1"'
      - 'attributes["k8s.pod.otel_disabled"] == true'
```

**Comment by blackluck** [comment]
@TylerHelmuth , thanks for examples, that works.

If somebody else need I did namespace filtering by ns labels. Like forwarding traffic only from namespace having label: `otel-enabled: true` (we use this label also in otel operator webhook namespace selector) and also if we want quickly blacklist a namespace (if it generates too much/unwanted traffic and needs to block it) just label ns with `otel-blacklisted: true`
Similiar could work with pods also.
(not sure about metrics, logs part or even spanevents if needed, we starting to use traces only, just for future put there those too)

```
    processors:
      batch: {}
      filter/ottl:
        error_mode: ignore
        logs:
          log_record:
          - resource.attributes["k8s.ns.labels.otel_blacklisted"] == "true
          - resource.attributes["k8s.ns.labels.otel_enabled"] != "true
        metrics:
          datapoint:
          - resource.attributes["k8s.ns.labels.otel_blacklisted"] == "true
          - resource.attributes["k8s.ns.labels.otel_enabled"] != "true
          metric:
          - resource.attributes["k8s.ns.labels.otel_blacklisted"] == "true
          - resource.attributes["k8s.ns.labels.otel_enabled"] != "true
        traces:
          span:
          - resource.attributes["k8s.ns.labels.otel_blacklisted"] == "true
          - resource.attributes["k8s.ns.labels.otel_enabled"] != "true
          spanevent:
          - resource.attributes["k8s.ns.labels.otel_blacklisted"] == "true
          - resource.attributes["k8s.ns.labels.otel_enabled"] != "true

      k8sattributes:
        auth_type: serviceAccount
        extract:
          labels:
          - from: namespace
            key: otel-enabled
            tag_name: k8s.ns.labels.otel_enabled
          - from: namespace
            key: otel-blacklisted
            tag_name: k8s.ns.labels.otel_blacklisted
          metadata:
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.start_time
        filter: null
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection

      transform:
        trace_statements:
        - context: resource
          statements:
          - delete_key(attributes, "paas.k8s.ns.otel_enabled") where attributes["paas.k8s.ns.otel_enabled"] != nil

    service:
      extensions:
      - health_check
      - memory_ballast
      pipelines:
        logs:
          exporters:
          - kafka
          processors:
          - k8sattributes
          - memory_limiter
          - resource
          - filter/ottl
          - transform
          - batch
          receivers:
          - otlp
        metrics:
          exporters:
          - kafka
          processors:
          - k8sattributes
          - memory_limiter
          - resource
          - filter/ottl
          - transform
          - batch
          receivers:
          - otlp
        traces:
          exporters:
          - kafka
          processors:
          - k8sattributes
          - memory_limiter
          - resource
          - filter/ottl
          - transform
          - batch
          receivers:
          - otlp

```

Thank you!
