### ISSUE TITLE
[exporter/loki] Make optional default labels exporter, job, instance, level

### ISSUE THREAD

**Issue by mar4uk** [open-telemetry/opentelemetry-collector-contrib#22156]
### Component(s)

exporter/loki

### Is your feature request related to a problem? Please describe.

Currently, loki exporter sets default labels:
- exporter=OTLP
- job=service.namespace/service.name
- instance=service.instance.id
- level=severity

For the user's convenience, it would be nice to make these labels optional 

Related issues/discussions:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22155
- https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/21508

### Describe the solution you'd like

1) I would reconsider setting `level` label by default (it is actually [not a good practice to promote log level to the label in Loki](https://grafana.com/blog/2020/08/27/the-concise-guide-to-labels-in-loki/))
2) I would add `default_labels` section to the loki exporter config:
```
loki:
      endpoint: ...
      default_labels:
           job: false
           instance: false
           exporter: false
```
