### ISSUE TITLE
Prometheus receiver does not pick up the updated bearer token from file 

### ISSUE THREAD

**Issue by aniket02k** [open-telemetry/opentelemetry-collector-contrib#22153]
### Component(s)

receiver/prometheus

## Description
I am trying to add authorization header  to the every scrape request but when  bearer token is updated, prometheus receiver is not picking up the updated bearer token and scraping of the metrics is failing due to invalid bearer token 
## Steps to Reproduce
I am using below scrape configurations:
```
      config:
        scrape_configs:
        - job_name: k8s
          scrape_interval: 5s
          metrics_path: /metrics
          scheme: https
          kubernetes_sd_configs:
          - role: service
            namespaces:
              names: ["test"]
          relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            regex: "test"
            action: keep
          tls_config:
            insecure_skip_verify: true
          authorization:
            credentials_file: /tmp/secrets/bearer_token

```

## Expected Result

Whenever bearer token is updated in the bearer token file, prometheus receiver should fetch the updated bearer token and scraping of metrics should happen using latest bearer token

## Actual Result
when  bearer token is updated, prometheus receiver is not picking up the updated bearer token and scraping of the metrics is failing due to invalid bearer token

### Collector version

0.75.0

### OpenTelemetry Collector configuration

```yaml
receivers:
    prometheus:   
      config:
        scrape_configs:
        - job_name: k8s
          scrape_interval: 5s
          metrics_path: /metrics
          scheme: https
          kubernetes_sd_configs:
          - role: service
            namespaces:
              names: ["test"]
          relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            regex: "test"
            action: keep
          tls_config:
            insecure_skip_verify: true
          authorization:
            credentials_file: /tmp/secrets/bearer_token
```

### Log output

```shell
2023-05-22T09:49:04.742Z        warn    internal/transaction.go:121     Failed to scrape Prometheus endpoint    {"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_timestamp": 1684748944739, "target_labels": "{__name__=\"up\", instance=\"test.aniket.svc:8443\", job=\"k8s\"}"}
```
