### ISSUE TITLE
[pkg/ottl] Allow checking path type

### ISSUE THREAD

**Issue by danelson** [open-telemetry/opentelemetry-collector-contrib#22161]
### Component(s)

internal/filter, processor/transform

### Is your feature request related to a problem? Please describe.

I have a log pipeline where I consume logs of different formats. The log body may be of few forms:

- kvlistValue
  ```json
  "body":
  {
    "kvlistValue":
    {
      "values":
      [
        {
          "key": "message",
          "value":
          {
            "stringValue": "kvlistValue message"
          }
        }
      ]
    }
  }
  ```
- stringValue
  - pure string
    ```json
    "body":
    {
      "stringValue": "this is a message"
    }
    ```
  - json string
    ```json
    "body":
    {
      "stringValue": "{\"message\":\"stringValue message\"}"
    }
    ```
- other? (not sure if this is possible)

When the log is not a pure string I would like to move data to attributes. Currently I do this with the `transformprocessor` as follows:

```yaml
transform/move_body_to_attributes:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - merge_maps(attributes, body, "insert") where IsMatch(body, "^\\{")
          - merge_maps(attributes, ParseJSON(body), "insert") where IsMatch(body, "^\\{")
          - set(body, "") where IsMatch(body, "^\\{")
```

This seems to work ok but I get one of the following warnings depending on whether body is a `kvlistValue` or a `stringValue`

> expected string but got pcommon.Map

or
> expected pcommon.Map but got string

### Describe the solution you'd like

I would like a way to determine the type of an object in the transform processor. Something like the following

```yaml
- merge_maps(attributes, body, "insert") where IsMatch(body, "^\\{") and body is kvlistValue
- merge_maps(attributes, ParseJSON(body), "insert") where IsMatch(body, "^\\{") and body is stringValue
```

### Additional context

The problem is written specific to my use case but it might apply more generally.
