### ISSUE TITLE
[processor/k8sattribute] Optionally add labels and annotations from node as resource attributes in the k8sattributes processor

### ISSUE THREAD

**Issue by jinja2** [open-telemetry/opentelemetry-collector-contrib#22620]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

Some node labels like the topology or arch type of node, might provide useful insight into telemetry from applications. Being able to filter application performance metrics by the zone the pods are running in, can be useful for application developers to identify degradation in an availability zone due to cloud provider outage for e.g.

### Describe the solution you'd like

I'd like to be able to add labels and annotations from the node as additional resource attributes on telemetry processed through the k8s attributes processor.

```
k8sattributes:
  labels:
    - tag_name: availability_zone
      key: topology.kubernetes.io/zone
      from: node
```
