### ISSUE TITLE
Refactor stanzareceiver to allow splitting into separate receivers

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#2265]
We would like to separate the "source" of the log from the "operators" (it is currently one list in stanzareceiver). The goal is to be able to do this in the config:

```yaml
filelog:
 include: [ receiver/stanzareceiver/testdata/simple.log ]
 start_at: beginning
 operators:
   - type: regex_parser
       regex: '^(?P<time>\d{4}-\d{2}-\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
       timestamp:
         parse_from: time
         layout: '%Y-%m-%d'
       severity:
         parse_from: sev
```
 
```yaml
winlog:
 channels: [Application, System]
 # other winlog options.
 operators:
   # similar to filelog.
```
 
```yaml
journald:
 # optional settings.
 directory:
 files:
 operators:
   # similar to filelog.
```
