### ISSUE TITLE
logs_dynamic_index not working for elasticsearch exporter

### ISSUE THREAD

**Issue by shrutichy91** [open-telemetry/opentelemetry-collector-contrib#22705]
### Component(s)

exporter/elasticsearch

## Description
I am using elasticsearch exporter, the dynamic index doesnt work

## Steps to Reproduce

elasticsearch/log:
        endpoints:
        - https://xyz:9200
        logs_dynamic_index:
          enabled: true
        logs_index: index-name
        password: ${ELASTICSEARCH_PASSWORD}
        tls:
          ca_file: tls.crt
        user: elastic

## Expected Result
to send logs to a dynamic index

## Actual Result
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': error reading configuration for "elasticsearch/log": 1 error(s) decoding:

* '' has invalid keys: logs_dynamic_index

### Collector version

v0.77.0

## Environment

Kubernetes

### OpenTelemetry Collector configuration

```yaml
exporters:
      elasticsearch/log:
        endpoints:
        - https://xyz:9200
        logs_dynamic_index:
          enabled: true
        logs_index: sample-index-name
        password: ${ELASTICSEARCH_PASSWORD}
        tls:
          ca_file: tls.crt
        user: elastic
      logging: {}
```
