### ISSUE TITLE
windows perfcounter in e-notation yielding incorrect value in prometheus

### ISSUE THREAD

**Issue by rismoney** [open-telemetry/opentelemetry-collector-contrib#22724]
### Component(s)

receiver/windowsperfcounters

### What happened?

use perf counter and metric outputs to a enotation: ie 9.155035136e+09

I am not sure how to handle this.  I believe this is why I am getting false readings in grafana.

### Collector version

0.76.3

## Environment
Windows 2019 core

### OpenTelemetry Collector configuration

```yaml
receivers:
  windowsperfcounters:
    collection_interval: 5s
    metrics:
      os.process.workingset:
        description: "amount of mem a Process is taking individually."
        unit: By
        gauge:
    perfcounters:
      - object: "Process"
        instances: "*"
        counters:
          - name: "% Processor Time"
            metric: os.process.time
          - name: "Working Set"
            metric: os.process.workingset

exporters:
  logging:
  prometheus:
    endpoint:  1.2.3.4:1234

service:
  pipelines:
    metrics:
      receivers: [windowsperfcounters]
      exporters: [prometheus]
```

### Log output

```shell
os_process_workingset_bytes{instance="svc1"} 9.155035136e+09
os_process_workingset_bytes{instance="svc2"} 7.935459328e+09
os_process_workingset_bytes{instance="svc3"} 8.038641664e+09
os_process_workingset_bytes{instance="svc4"} 8.713064448e+09
os_process_workingset_bytes{instance="svc5"} 9.08232704e+09
os_process_workingset_bytes{instance="svc6"} 9.1252736e+09
```
