### ISSUE TITLE
bearertokenauth extensions does not support configauth.ServerAuthenticator

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-collector-contrib#22737]
### Component(s)

extension/bearertokenauth

### Is your feature request related to a problem? Please describe.

currently it is not possible to use the bearertokenauth extension as server authenticator.

```yaml
---
extensions:
  bearertokenauth/withscheme:
    scheme: "Bearer"
    token: "randomtoken"

receivers:
  otlp:
    protocols:
      grpc:
        auth:
          authenticator: bearertokenauth/withscheme
      http:

exporters:
  logging:
    verbosity: detailed

service:
  extensions: [bearertokenauth/withscheme]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
```

This configuration leads to: 
```bash
2023/05/23 16:00:15 collector server run finished with error: cannot start pipelines: requested authenticator is not a server authenticator
```

### Describe the solution you'd like

bearertokenauth should implement [configauth.ServerAuthenticator](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.78.2/config/configauth#creating-an-authenticator) like e.g. [basicauth](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.78.0/extension/basicauthextension#basic-authenticator) does.

### Additional context

Testing:
```bash
telemetrygen metrics --otlp-insecure --duration 15s --rate 4 --otlp-http=false --otlp-header authorization=\"Bearer\ randomtoken\"
```

---

cc @sallyom
