### ISSUE TITLE
[processor/filter] Filters out all logs if logBodies used and logs aren't strings

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector-contrib#22736]
### Component(s)

processor/filter

## Description

All logs are filtered out by filter processor if LogBodies is being used and logs are not a string

## Steps to Reproduce

Run configuration with example log

## Expected Result

Logs are not filtered out

## Actual Result

Logs are filtered out

### Collector version

latest

## Environment
N/A

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include:
      - ./tmp/2.log
    start_at: beginning
processors:
  filter/exclude-phi:
    logs:
      exclude:
        bodies:
        - not matches anything
  transform/containers_parse_json:
    error_mode: ignore
    log_statements:
    - context: log
      statements:
      - set(body, ParseJSON(body)) where IsMatch(body, "^{") == true
exporters:
  logging:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers:
        - filelog
      processors:
        - transform/containers_parse_json
        - filter/exclude-phi
      exporters:
        - logging
```

### Additional context

`./tmp/2.log`:
```
{"level":"info"}
```

**Comment by sumo-drosiek** [comment]
I'm going to issue a PR for it

**Comment by sumo-drosiek** [comment]
The following configuration may be use as alternative:

```
  filter:
    logs:
      log_record:
      - 'IsMatch(body, "not matches anything")'
```
