### ISSUE TITLE
Fileexporter rotation breaks up log lines

### ISSUE THREAD

**Issue by peterzandbergen** [open-telemetry/opentelemetry-collector-contrib#22747]
### Component(s)

exporter/file

## Description
When rotation is configured the rotation does not occur on line ends.

## Steps to Reproduce
- Configure the file exporter with rotation and set max_megabytes: 1
- produce enough signals, e.g. using the filelog receiver to trigger a rotation
- tail the rotated file. This shows that the end of the file breaks up the json

## Expected Result
The logfiles produced by the file exporter should contain valid json structs

## Actual Result
The last line ends in the middle of the last json struct

### Collector version

85a618f8bb7204b63d3d7bf0f679cc61c0f42ea0

## Environment
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

Compiler(if manually compiled): (e.g., "go 14.2")
go version go1.20.4 linux/amd64

### OpenTelemetry Collector configuration

```yaml
# File log receiver
extensions:
  file_storage/filelog_status:
    directory: ./filelog_status

receivers:
  otlp:
    protocols:
      grpc:
      http:
  filelog/test.log:
    include:
      - ./app_logs/*.log
    operators:
      - type: json_parser
        # parse_from: key
    storage: file_storage/filelog_status

exporters:
  file/stdout:
    path: /dev/stdout
  file/test-out:
    rotation:
      max_megabytes: 1
    path: ./logs/test.out
    flush_interval: 1s

service:
  # telemetry:
  #   logs:
  #     encoding: json
  #   metrics:
  #     address: 0.0.0.0:18888

  extensions:
    - file_storage/filelog_status
    
  pipelines:
    traces:
      receivers:
        - otlp
      processors: []
      exporters:
        - file/stdout
        - file/test-out
    logs:
      receivers:
        - filelog/test.log
        - otlp
      processors: []
      exporters:
        - file/stdout
        - file/test-out
```

### Additional context

I have analyzed the error and it was introduced by my contribution for flushing the file exporter. 
I have also managed to fix it by not wrapping the buffered writer around the lumberjack logger.

```
diff --git a/exporter/fileexporter/factory.go b/exporter/fileexporter/factory.go
index baecdc4701..246a61f5f0 100644
--- a/exporter/fileexporter/factory.go
+++ b/exporter/fileexporter/factory.go
@@ -142,13 +142,13 @@ func buildFileWriter(cfg *Config) (io.WriteCloser, error) {
                }
                return newBufferedWriteCloser(f), nil
        }
-       return newBufferedWriteCloser(&lumberjack.Logger{
+       return &lumberjack.Logger{
                Filename:   cfg.Path,
                MaxSize:    cfg.Rotation.MaxMegabytes,
                MaxAge:     cfg.Rotation.MaxDays,
                MaxBackups: cfg.Rotation.MaxBackups,
                LocalTime:  cfg.Rotation.LocalTime,
-       }), nil
+       }, nil
 }
 
```
