### ISSUE TITLE
How to optimize Kafka receiver for slow consumption of messages?

### ISSUE THREAD

**Issue by addname** [open-telemetry/opentelemetry-collector-contrib#22741]
### Component(s)

receiver/kafka

### Describe the issue you're reporting

Kafka receiver is only consuming a few dozen messages per second, how can I optimize it?

```
receivers:
  kafka/1:
    brokers:
    - 10.xx.xx.x1:9092
    - 10.xx.xx.x2:9092
    - 10.xx.xx.x3:9092
    protocol_version: 2.0.0
    topic: otlp-spans-topic-01
    group_id: otel-collector-01
    encoding: jaeger_json      
  kafka/2:
    brokers:
     - 10.xx.xx.x1:9092
     - 10.xx.xx.x2:9092
     - 10.xx.xx.x3:9092
    protocol_version: 2.0.0
    topic: otlp-spans-topic-02
    group_id: otel-collector-02
    encoding: jaeger_json  

service:
    traces:
      exporters:
      - clickhousetraces
      processors:
      - signozspanmetrics/prometheus
      - batch
      receivers:
      - otlp
      - kafka/1
      - kafka/2
      - jaeger 
 
 ```
