### ISSUE TITLE
kubeletstats receiver: "Get \"https://NODE_NAME:10250/stats/summary\": dial tcp: lookup NODE_NAME on 10.245.0.10:53: no such host"

### ISSUE THREAD

**Issue by devurandom** [open-telemetry/opentelemetry-collector-contrib#22843]
### Component(s)

receiver/kubeletstats

## Description

I set up OpenTelemetry Collector as a agent on each node using the Helm Chart and the `values.yaml` template below. The `kubeletstatsreceiver` tries to resolve the Kubernetes node name that the Helm Chart injects as its endpoint via the cluster's DNS, but fails (see logs below).

This seems similar to how the Kubernetes metrics-server tried to do the same and then was changed to resolve the node via the Kubernetes API and the `InternalIP` field of the node status.

## Steps to Reproduce

See `values.yaml` file below. I deployed it to a DigitalOcean Kubernetes cluster.

## Expected Result

`kubeletstatsreceiver` should "just work".

## Actual Result

See the error message and stack trace below.

### Collector version

0.77.0

## Environment
OS: DigitalOcean Kubernetes

### OpenTelemetry Collector configuration

```yaml
# Helm values.yaml template
# ${redeploy_trigger}
fullnameOverride: "collector"
mode: "daemonset"
image:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22815
  tag: "0.77.0"
service:
  enabled: true
presets:
  logsCollection:
    enabled: true
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
config:
  extensions:
    basicauth/otlp:
      client_auth:
        username: "$${env:INSTANCE_ID}"
        password: "$${env:PUBLISHER_TOKEN}"
  processors:
    # https://community.grafana.com/t/error-sending-logs-with-loki-resource-labels/87561
    resource:
      attributes:
        - action: insert
          key: service_name
          from_attribute: service.name
        - action: insert
          key: service_namespace
          from_attribute: service.namespace
        - action: insert
          key: service_version
          from_attribute: service.version
        - action: insert
          key: deployment_environment
          from_attribute: deployment.environment
        - action: insert
          key: loki.resource.labels
          value: service_name,service_namespace,service_version,deployment_environment
  receivers:
    jaeger: null
    zipkin: null
  exporters:
    otlphttp:
      auth:
        authenticator: basicauth/otlp
      endpoint: "$${env:EXPORT_URL}"
  service:
    extensions:
      - health_check
      - memory_ballast
      - basicauth/otlp
    pipelines:
      metrics:
        receivers:
          - otlp
          - prometheus
        exporters:
          - otlphttp
      traces:
        receivers:
          - otlp
        exporters:
          - otlphttp
      logs:
        receivers:
          - otlp
        processors:
          - resource
          - memory_limiter
          - batch
        exporters:
          - otlphttp
extraEnvs:
  - name: INSTANCE_ID
    valueFrom:
      secretKeyRef:
        name: "${grafana_secret}"
        key: instance_id
  - name: PUBLISHER_TOKEN
    valueFrom:
      secretKeyRef:
        name: "${grafana_secret}"
        key: publisher_token
  - name: EXPORT_URL
    valueFrom:
      secretKeyRef:
        name: "${grafana_secret}"
        key: export_url
```

### Log output

```shell
2023-05-27T19:12:22.078Z	error	kubeletstatsreceiver@v0.77.0/scraper.go:79	call to /stats/summary endpoint failed	{"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "Get \"https://NODE_NAME:10250/stats/summary\": dial tcp: lookup NODE_NAME on 10.245.0.10:53: no such host"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver.(*kubletScraper).scrape
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver@v0.77.0/scraper.go:79
go.opentelemetry.io/collector/receiver/scraperhelper.ScrapeFunc.Scrape
	go.opentelemetry.io/collector/receiver@v0.77.0/scraperhelper/scraper.go:31
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
	go.opentelemetry.io/collector/receiver@v0.77.0/scraperhelper/scrapercontroller.go:209
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
	go.opentelemetry.io/collector/receiver@v0.77.0/scraperhelper/scrapercontroller.go:191
2023-05-27T19:12:22.078Z	error	scraperhelper/scrapercontroller.go:212	Error scraping metrics	{"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "Get \"https://NODE_NAME:10250/stats/summary\": dial tcp: lookup NODE_NAME on 10.245.0.10:53: no such host", "scraper": "kubeletstats"}
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
	go.opentelemetry.io/collector/receiver@v0.77.0/scraperhelper/scrapercontroller.go:212
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
	go.opentelemetry.io/collector/receiver@v0.77.0/scraperhelper/scrapercontroller.go:191
```

### Additional context

Is there a workaround, e.g. relying on `metrics-server` or `kube-state-metrics`? How would I configure that?

**Comment by crobert-1** [comment]
Apologies for the delay here. Is this the full and correct config file? I'm confused as to why you're getting `kubeletstats` receiver errors when there's no `kubeletstats` receiver defined, or in your pipeline shown.

**Comment by devurandom** [comment]
> Apologies for the delay here. Is this the full and correct config file? I'm confused as to why you're getting `kubeletstats` receiver errors when there's no `kubeletstats` receiver defined, or in your pipeline shown.

Thank you for your response!

The Helm Chart enables the `kubeletstats` receiver under the `kubeletMetrics` flag:
```tmpl
{{- if .Values.presets.kubeletMetrics.enabled }}
{{- $config = (include "opentelemetry-collector.applyKubeletMetricsConfig" (dict "Values" $data "config" $config) | fromYaml) }}
{{- end }}
[...]
{{- tpl (toYaml $config) . }}
```
(from https://github.com/open-telemetry/opentelemetry-helm-charts/blob/3471a2afe2d5e01d23b4bc02f62ef70077c7dcc7/charts/opentelemetry-collector/templates/_config.tpl#L43-L45 and https://github.com/open-telemetry/opentelemetry-helm-charts/blob/3471a2afe2d5e01d23b4bc02f62ef70077c7dcc7/charts/opentelemetry-collector/templates/_config.tpl#L52, the version of the Helm Chart I tried might have been different)

`applyKubeletMetricsConfig` is:
```tmpl
{{- define "opentelemetry-collector.applyKubeletMetricsConfig" -}}
{{- $config := mustMergeOverwrite (include "opentelemetry-collector.kubeletMetricsConfig" .Values | fromYaml) .config }}
{{- $_ := set $config.service.pipelines.metrics "receivers" (append $config.service.pipelines.metrics.receivers "kubeletstats" | uniq)  }}
{{- $config | toYaml }}
{{- end }}

{{- define "opentelemetry-collector.kubeletMetricsConfig" -}}
receivers:
  kubeletstats:
    collection_interval: 20s
    auth_type: "serviceAccount"
    endpoint: "${env:K8S_NODE_NAME}:10250"
{{- end }}
```
(from https://github.com/open-telemetry/opentelemetry-helm-charts/blob/3471a2afe2d5e01d23b4bc02f62ef70077c7dcc7/charts/opentelemetry-collector/templates/_config.tpl#L151-L163, the version of the Helm Chart I tried might have been different)

**Comment by paulohmorais** [comment]
Same problem here

Digital Oean K8s

The IP from the error is kube-dns svc:

`kube-system                kube-dns                                                          ClusterIP                10.245.0.10                                           dns:53►0╱UDP dns-tcp:53►0 metrics:9153►0 `

Errors logs:

```
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x 2023-09-06T22:25:02.668Z    error    scraperhelper/scrapercontroller.go:213    Error scraping metrics    {"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "Get \"https://w-pool-uy4qaitgx-y74ag:10250/stats/summary\": dial tcp: lookup w-pool-uy4qaitgx-y74ag on 10.245.0.10:53: no such host", "scraper": "kubeletstats"}                                                      │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport                                                                                                                                                                                                                                                                                                                                         │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x     go.opentelemetry.io/collector/receiver@v0.79.0/scraperhelper/scrapercontroller.go:213                                                                                                                                                                                                                                                                                                                                         │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1                                                                                                                                                                                                                                                                                                                                            │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x     go.opentelemetry.io/collector/receiver@v0.79.0/scraperhelper/scrapercontroller.go:192                                                                                                                                                                                                                                                                                                                                         │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x 2023-09-06T22:25:32.665Z    error    kubeletstatsreceiver@v0.79.0/scraper.go:68    call to /stats/summary endpoint failed    {"kind": "receiver", "name": "kubeletstats", "data_type": "metrics", "error": "Get \"https://w-pool-uy4qaitgx-y74ag:10250/stats/summary\": dial tcp: lookup w-pool-uy4qaitgx-y74ag on 10.245.0.10:53: no such host"}                                                             │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver.(*kubletScraper).scrape                                                                                                                                                                                                                                                                                                                   │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x     github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver@v0.79.0/scraper.go:68                                                                                                                                                                                                                                                                                                                 │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x go.opentelemetry.io/collector/receiver/scraperhelper.ScrapeFunc.Scrape                                                                                                                                                                                                                                                                                                                                                            │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x     go.opentelemetry.io/collector/receiver@v0.79.0/scraperhelper/scraper.go:20                                                                                                                                                                                                                                                                                                                                                    │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport                                                                                                                                                                                                                                                                                                                                         │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x     go.opentelemetry.io/collector/receiver@v0.79.0/scraperhelper/scrapercontroller.go:210                                                                                                                                                                                                                                                                                                                                         │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1                                                                                                                                                                                                                                                                                                                                            │
│ signoz-k8s-metrics-exporter-k8s-infra-otel-agent-dnl9x     go.opentelemetry.io/collector/receiver@v0.79.0/scraperhelper/scrapercontroller.go:192     
```

**Comment by jinja2** [comment]
Usually, cloud provider managed compute services have a private DNS setup for vms, and then the node's local domain is appended to the `/etc/resolv.conf` passed to k8s pods by the kubelet which makes the k8s node name (when same as the vm's hostname) resolvable. I am not familiar with Digital Ocean, but maybe they don't have a similar setup or the instances are not assigned private dnses. Either ways, you can use the node IP instead which can be passed as env var with a snippet like below
```
env:
- name: K8S_NODE_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```
and then in the kubeletstats receiver
```
receivers:
  kubeletstats:
    endpoint: "${env:K8S_NODE_IP}:10250"
 ```
 
 I would suggest opening up an issue in the chart repo to add using the node ip as an option and closing this one. This isn't something to fix in the receiver, instead it can be resolved with changes to the config passed to it.

**Comment by crobert-1** [comment]
@devurandom Let us know if any other information would be helpful! Otherwise, feel free to close the issue and open another one in the [chart repo](https://github.com/open-telemetry/opentelemetry-helm-charts) as @jinja2 suggested.

**Comment by crobert-1** [comment]
I'm going to close this issue for now, but please feel free to let us know if you have any other questions.

**Comment by alextricity25** [comment]
> Usually, cloud provider managed compute services have a private DNS setup for vms, and then the node's local domain is appended to the `/etc/resolv.conf` passed to k8s pods by the kubelet which makes the k8s node name (when same as the vm's hostname) resolvable. I am not familiar with Digital Ocean, but maybe they don't have a similar setup or the instances are not assigned private dnses. Either ways, you can use the node IP instead which can be passed as env var with a snippet like below
> 
> ```
> env:
> - name: K8S_NODE_IP
>   valueFrom:
>     fieldRef:
>       fieldPath: status.hostIP
> ```
> 
> and then in the kubeletstats receiver
> 
> ```
> receivers:
>   kubeletstats:
>     endpoint: "${env:K8S_NODE_IP}:10250"
> ```
> 
> I would suggest opening up an issue in the chart repo to add using the node ip as an option and closing this one. This isn't something to fix in the receiver, instead it can be resolved with changes to the config passed to it.

For those interested, I opened up a PR in the charts repo here:
https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1206

**Comment by momenthana** [comment]
The above configuration was effective for me in addressing issues I was experiencing on DigitalOcean.

Since I was too busy to wait for a new chart version to be deployed, I added the following environment variable configuration to the opentelemetry-collector-daemonset Helm chart and used it with the existing chart version:

```yaml
extraEnvs:
  - name: K8S_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
```

and then in the kubeletstats receiver

```yaml
receivers:
  kubeletstats:
    endpoint: "${env:K8S_NODE_IP}:10250"
```
