### ISSUE TITLE
replace_all_patterns regex not working

### ISSUE THREAD

**Issue by kostyaLem** [open-telemetry/opentelemetry-collector-contrib#22852]
### Component(s)

processor/transform

## Description
replace_all_patterns doesn't substitute value from regular expression.
I'm trying to replace the key **"kube_myHold_test"** with a value from a regular expression, but it is not substituted.

## Steps to Reproduce
[Example in documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#replace_all_patterns)
Send a log with attributes to the collector. Among the attributes should be a key named kube_myHold_test.

## Expected Result
```
"attributes": [
  {
      "key": "k8s.myHold.test",
      "value": {
      "stringValue": "fbfe469f77ef052b7dbf0d6694a2ada8a8e32e48"
     }
 }
]
```

## Actual Result
```
"attributes": [
  {
      "key": "k8s.$1.test",
      "value": {
      "stringValue": "fbfe469f77ef052b7dbf0d6694a2ada8a8e32e48"
     }
 }
]
```

### Collector version

v0.71.0

## Environment
OS: alpine 3.18

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4319

processors:
  transform:
    log_statements:
      - context: log
        statements:
          - replace_all_patterns(attributes, "key", "^kube_([0-9A-Za-z]+_)", "k8s.$$1.")

exporters:
  file:
    path: /var/lib/data/collected_data.json

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [transform]
      exporters: [file]
```

### Log output

```shell
{
    "resourceLogs": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "service.version",
                        "value": {
                            "stringValue": "1.0.0"
                        }
                    }
                ]
            },
            "schemaUrl": "https://opentelemetry.io/schemas/v1.13.0",
            "scopeLogs": [
                {
                    "logRecords": [
                        {
                            "attributes": [
                                {
                                    "key": "k8s.$1.test",
                                    "value": {
                                        "stringValue": "fbfe469f77ef052b7dbf0d6694a2ada8a8e32e48"
                                    }
                                },
                                {
                                    "key": "Guid",
                                    "value": {
                                        "stringValue": "3132a8ca-6c6e-412e-aae6-72c82cbedaf5"
                                    }
                                },
                            ],
                            "body": {
                                "stringValue": "Test"
                            },
                            "severityNumber": 9,
                            "severityText": "Information",
                            "spanId": "",
                            "timeUnixNano": "1685362208807000000",
                            "traceId": ""
                        }
                    ],
                    "schemaUrl": "https://opentelemetry.io/schemas/v1.13.0",
                    "scope": {
                        "name": "Serilog.Sinks.OpenTelemetry",
                        "version": "1.0.0.0"
                    }
                }
            ]
        }
    ]
}
```
