### ISSUE TITLE
Allow configuring which resource attributes should be kept at the metric

### ISSUE THREAD

**Issue by jmichalek132** [open-telemetry/opentelemetry-collector-contrib#22914]
### Component(s)

pkg/translator/prometheusremotewrite

### Is your feature request related to a problem? Please describe.

Right now prometheus remote write exporter allows you to either use `target_info` metric to store resource attributes or you can configure it to attach all the resource attribute on the existing metric. 

In our case we are currently using the `target_info` metric approach. However the current translation expects to have `service.instance.id` present on all metrics (it's used to uniquely identify the target), this is however not always the case. 

In our company we unfortunately didn't  set it before hand so it's missing on most metrics, but also at least some of the receivers present in otel contrib are not setting it either (i.e. [postgresqlreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/postgresqlreceiver/metadata.yaml)).

This leads to metrics being rejected by prometheus compatible backends, due to not having unique metrics, because the rest of the unique identifiers are moved to the `target_info` metric. 

### Describe the solution you'd like

We would like to solve this by updating the `pkg/translator/prometheusremotewrite` to allow providing a list resource attributes that would be moved to the original metrics even when the `target_info` metric is enabled.

Configuration could look something like this:

```yaml
exporters:
  prometheusremotewrite:
    endpoint: "https://my-cortex:7900/api/v1/push"
    resource_to_telemetry_conversion_allowed_list:
      - k8s_pod_name
      - k8s_node_name
      - k8s_namespace_name
      - hostname
      - ip
      - etc ....
```

Making this even more flexible, possibly as a second iteration we could expect regex inside the list, so in case we have a common prefix among resource attribute keys we want to move we could write a single regex to match all of them instead of having to list them one by one, and therefore updating otel collector configuration each time such resource attribute is added. 

None of the processors currently supports an operation where you can iterate on keys of resource attributes like this to support this feature.

Example of config like that:

```yaml
exporters:
  prometheusremotewrite:
    endpoint: "https://my-cortex:7900/api/v1/push"
    resource_to_telemetry_conversion_allowed_list:
      - k8s.*
      - hostname
      - ip
      - etc ....
```

### Describe alternatives you've considered

As of now we use `transform` processor as a workaround to copy specific resource attributes into attributes and therefore having them on metrics, and having the metrics uniquely identified. 

Example configuration:

```yaml
transform:
  metric_statements:
    - context: datapoint
      statements:
        - set(attributes["k8s_replicaset_name"], resource.attributes["k8s.replicaset.name"])
        - set(attributes["k8s_deployment_name"], resource.attributes["k8s.deployment.name"])
        - set(attributes["k8s_statefulset_name"], resource.attributes["k8s.statefulset.name"])
        - set(attributes["k8s_hpa_name"], resource.attributes["k8s.hpa.name"])
        - set(attributes["k8s_volume_name"], resource.attributes["k8s.volume.name"])
        - set(attributes["k8s_job_name"], resource.attributes["k8s.job.name"])
```

### Additional context

This was discussed during OpenTelemetry SIG: Agent/Collector on [May 24th, 2023](https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit#heading=h.72toyygajlkn) outcome being open this issue, and starting a discussion about implementation / how would this be configurable.

I would be willing to working on contributing this feature.
