### ISSUE TITLE
Expected metrics from Kafka is not Shown

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#22935]
### Component(s)

receiver/kafkametrics

## Description
I am trying to get metrics from a Kafka Instance. When I looked at the metrics collected, it only shows the properties of the Topics and not the metrics of the Topics.

## Steps to Reproduce
Configure the .yaml configuration file, then run the .yaml configuration file using the otelcol-contrib binary.
Please refer to the "OpenTelemetry Collector configuration" section for the configurations.

## Expected Result
A set of metrics from a specific topics.
Sample metrics expected:
```
nfs_read_data
nfs_read_latency
nfs_write_data
nfs_write_latency
```

## Actual Result
I got a set of metrics which is considered as the properties of the topics.
Sample metrics gotten:
```
kafka.consumer_group.lag
kafka.consumer_group.offset
kafka.partition.current_offset
```

### Collector version

v0.77.0

## Environment
OS: x86-64_linux_4.12_ImageSLES12SP5

### OpenTelemetry Collector configuration

```yaml
receivers:
  kafkametrics:
    brokers: <BROKER_TARGET>
    protocol_version: 2.0.0
    scrapers:
      - brokers
      - topics
      - consumers

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

service:
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8886

  pipelines:
    metrics:
      receivers: [kafkametrics]
      processors: []
      exporters: [logging]
```

### Additional context

May I know if I have configured correctly, please?
How can I configure to get the metrics that I am expecting, please?

Thank you.
