### ISSUE TITLE
"proto: illegal wireType 7" error when using Kafka Receiver

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#22934]
### Component(s)

receiver/kafka

## Description
I am trying to collect Kafka data from a Kafka instance by using Kafka receiver. When I configured the configurations, it displays "Starting consumer group ....." then error is prompted.

## Steps to Reproduce
Configure the .yaml configuration file, then run the .yaml configuration file using the otelcol-contrib binary.
Please refer to the "OpenTelemetry Collector configuration" section for the configurations.

## Expected Result
I expected to see that the data is being collected without any error prompted.

## Actual Result
No data is collected and errors are prompted.
Please refer to "Log Output" section for the logs displayed

### Collector version

v0.77.0

## Environment
OS: x86-64_linux_4.12_ImageSLES12SP5

### OpenTelemetry Collector configuration

```yaml
receivers:
  kafka:
    protocol_version: 2.0.0
    topic: <TOPIC_NAME>
    brokers:
      - "<BROKER_TARGET>"

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

service:
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8886

  pipelines:
    metrics:
      receivers: [kafka]
      processors: []
      exporters: [logging]
```

### Log output

```shell
2023-05-29T21:01:51.641-0700    error   kafkareceiver@v0.77.0/kafka_receiver.go:519     failed to unmarshal message     {"kind": "receiver", "name": "kafka", "data_type": "metrics", "error": "proto: illegal wireType 7"}
```
```
2023-05-29T23:49:19.185-0700    error   kafkareceiver@v0.77.0/kafka_receiver.go:519     failed to unmarshal message     {"kind": "receiver", "name": "kafka", "data_type": "metrics", "error": "proto: MetricsData: wiretype end group for non-group"}
```
```


### Additional context

May I know what is the issue and how to solve this issue, please?
