### ISSUE TITLE
Duplicated logs when fingerprint_size is set to larger value

### ISSUE THREAD

**Issue by kkujawa-sumo** [open-telemetry/opentelemetry-collector-contrib#22936]
### Component(s)

receiver/filelog

## Description

Filelog receiver constantly reads the same log file when `fingerprint_size` is set to value larger than  [size of  scanner default buffer](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/62c39d6ba132ed5377620a53eebe6a265b5f5f3d/pkg/stanza/fileconsumer/scanner.go#LL14C7-L14C21) and size of the log file is lower than `fingerprint_size` but larger than scanner buffer.

## Steps to Reproduce

- Run otelcontribcol with attached configuration and read [example log file](https://gist.github.com/kkujawa-sumo/60babc6790bf229c6380a6c645a936c8)

## Expected Result
Logs are not duplicated

## Actual Result
Logs are duplicated, the same logs are constantly read

### Collector version

commit: `ca50a98fdda4c362d8782a29f6fc5cc27977f37b`

## Environment
Darwin Kernel Version 22.3.0
go version go1.19.6 darwin/amd64

### OpenTelemetry Collector configuration

```yaml
exporters:
  file:
    path: out.log
receivers:
  filelog:
    fingerprint_size: 17408
    start_at: beginning
    include:
    - generated_log.txt
service:
  pipelines:
    logs:
      exporters:
      - file
      receivers:
      - filelog
```
