### ISSUE TITLE
Datadog mishandling Gauge metrics

### ISSUE THREAD

**Issue by datsabk** [open-telemetry/opentelemetry-collector-contrib#22975]
## Description
Datadog exporter sends trailing "zero" valued datapoints for Gauge even after target is down  
<img width="1169" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/16060349/ba325358-ec38-47eb-85c5-19e0ef79f77c">

## Steps to Reproduce
Run two pods in Kubernetes that emits Gauge metrics - Run for a few minutes and then terminate one of the pods. The metric from that terminated pod would still show up for another 5 mins as 0 value 

## Expected Result
The metric should not have any datapoints for that target once it is terminated 

## Actual Result
There are datapoints for upto 5 mins even after target is terminated 

### Collector version

0.75.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
      datadog:
        api:
          key: xx
          site: datadoghq.com
        host_metadata:
          enabled: true
        metrics:
          histograms:
            send_aggregation_metrics: true
          resource_attributes_as_tags: true
      prometheusremotewrite:
        auth:
          authenticator: sigv4auth
        endpoint: xx
        external_labels:
          cluster_name: xx
    extensions:
      health_check: {}
      memory_ballast:
        size_in_percentage: 40
      pprof:
        endpoint: 0.0.0.0:1777
      sigv4auth:
        assume_role:
          sts_region: us-west-2
    processors:
      attributes:
        actions:
        - action: insert
          key: cluster
          value: backstage
        - action: insert
          key: env
          value: backstage-stage
        - action: insert
          key: environment
          value: backstage-stage
      batch: {}
      batch/datadog:
        send_batch_max_size: 100
        send_batch_size: 10
        timeout: 10s
      cumulativetodelta: null
      memory_limiter:
        check_interval: 1s
        limit_mib: 1024
        spike_limit_mib: 256
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4327
          http:
            endpoint: 0.0.0.0:4328
      prometheus:
        config:
          scrape_configs:
          - job_name: pods-scraper
            kubernetes_sd_configs:
            - role: pod
            metric_relabel_configs:
            - action: labeldrop
              regex: prometheus_(.*)
            - action: labeldrop
              regex: beta_(.*)
            - action: labeldrop
              regex: (app_kubernetes_io_instance|url|pod_template_hash|prometheus|container_id)
            - action: drop
              regex: (centrifuge_functions_.*|functions_.*|feature_.*|span_.*)
              source_labels:
              - __name__
            relabel_configs:
            - action: drop
              regex: (kube-prometheus-stack|prometheus|yace|kube-dns-cache)-.*
              source_labels:
              - __meta_kubernetes_pod_name
            - action: keep
              regex: (Running|running)
              source_labels:
              - __meta_kubernetes_pod_phase
            - action: keep
              regex: $NODE_NAME
              source_labels:
              - __meta_kubernetes_pod_node_name
            - action: keep
              regex: "true"
              separator: ;
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            - action: replace
              regex: (.+)
              replacement: $$1
              separator: ;
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $$1:$$2
              source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - action: labeldrop
              regex: __meta_kubernetes_pod_label_k2_(.+)
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: drop
              regex: .*_kubernetes_io_.*
            - action: replace
              regex: (.*)
              replacement: $$1
              separator: ;
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: node
            - source_labels:
              - __meta_kubernetes_pod_label_cluster
              target_label: cluster
            - source_labels:
              - quantile
              target_label: le
            scrape_interval: 15s
    service:
      extensions:
      - sigv4auth
      - health_check
      - pprof
      pipelines:
        metrics:
          exporters:
          - prometheusremotewrite
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
          - prometheus
        metrics/2:
          exporters:
          - datadog
          processors:
          - memory_limiter
          - attributes
          - batch/datadog
          receivers:
          - prometheus
      telemetry:
        metrics:
          address: 0.0.0.0:8888
```
