### ISSUE TITLE
otel.metrics.exporter= none still reporting error (otel/opentelemetry-collector-contrib:0.77.0)

### ISSUE THREAD

**Issue by aayushave** [open-telemetry/opentelemetry-collector-contrib#22987]
### Component(s)

cmd/otelcontribcol

### What happened?

In spring application 3.0.5
using dependency
```
<dependency>
	<groupId>io.opentelemetry.contrib</groupId>
	<artifactId>opentelemetry-runtime-attach</artifactId>
	<version>${opentelemetry.runtime.attach.version}</version>
</dependency>
```
And 
`otel.metrics.exporter = none
`
still spring reporting issue 
[otel.javaagent 2023-06-01 04:25:25:656 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317 

## Steps to Reproduce
Added in application properties

spring.application.name=test
otel.exporter.otlp.traces.endpoint=http://localhost:4317
otel.traces.exporter=otlp
otel.metrics.exporter = none

## Expected Result
No Error should be reported

## Actual Result
[otel.javaagent 2023-06-01 04:25:25:656 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317 

### Collector version

otel/opentelemetry-collector-contrib:0.77.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
K8s Centos Setup
K8s Windows Setup
Local Windows Setup

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
            endpoint: :4317
          http: 
            endpoint: :4318
      
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      

    exporters:
      jaeger:
        endpoint: jaeger-svc:14250
        tls:
          insecure: true
      
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger]
```

### Log output

```shell
[otel.javaagent 2023-06-01 04:25:25:656 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317
```

### Additional context

No
