### ISSUE TITLE
processor: add resource_attributes group in metadata.yaml files

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-collector-contrib#22997]
### Component(s)

k8sattributesprocessor, resourcedetectionprocessor

### Describe the issue you're reporting

The group `resource_attributes` was introduced in the following [PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21664).

As of today, no processors use the `resource_attributes` group and its generated config structs. What I'm proposing is adding the `resource_attributes` to processors where this is relevant:

- [x] [k8sattributesprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23152)
- [x] [resourcedetectionprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21482)

**Comment by mackjmr** [comment]
cc @dmitryax and @atoulme as you worked on the PR which added the ability to generate configs for resource attributes.

**Comment by dmitryax** [comment]
@mackjmr we already have an issue for resource detection processor https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21482 which is in progress. 

K8s attribute processor supports enabling/disabling the resource via a different configuration interface:

```
    extract:
      metadata:
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.name
        - k8s.pod.uid
        - container.id
        - container.image.name
        - container.image.tag
      annotations:
        ...
      labels:
        ...
```

Not sure we should change it, it'll like be less intuitive, but we definitely can leverage the metadata.yaml with a comment that it's exposed through a different configuration interface. Feel free to submit an issue and work on it
