### ISSUE TITLE
[datadogreceiver] missing client (pod) ip 

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#22991]
### Component(s)

receiver/datadog

## Description

When sending traces using datadog receiver we are missing the k8sattributes, because the ddreceiver doesn't add client ip to the context.

## Steps to Reproduce

1. Set up datadogreceiver and k8sattributes receiver
2. Send some datadog traces

## Expected Result

K8s attributes are there 
## Actual Result
No k8s attributes are added

### Collector version

v0.78

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
      datadog:
        endpoint: 0.0.0.0:8127 # Custom Port to avoid conflict with DD Agent
        read_timeout: 60s
    exporters:
      logging:
        verbosity: detailed
    service:
      pipelines:
        traces:
          receivers:
            - datadog
            - otlp
            - jaeger
            - zipkin
          processors:
            - batch
            - memory_limiter
            - k8sattributes
            - transform
          exporters:
            - logging
```
