### ISSUE TITLE
trace data will be partially lost

### ISSUE THREAD

**Issue by tuhao1020** [open-telemetry/opentelemetry-collector-contrib#23028]
### Component(s)

processor/servicegraph

## Description
trace data will be partially lost

## Steps to Reproduce
1.deploy two services to generate topology data using otel agent and collector
2.restart collector
3.request service

## Expected Result
get 6 spans (complete) of both services
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/26807520/9ac27d07-3e23-4fad-b1a3-e3a18babad57)

## Actual Result
get 4 spans (incomplete) of one service
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/26807520/f0a997f7-71a6-4fe2-a65b-1953c75daf6c)

### Collector version

0.71.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp/traces:
    protocols:
      grpc:
        endpoint: :14317
  otlp/servicegraph: # Dummy receiver for the metrics pipeline
    protocols:
      grpc:
        endpoint: localhost:12345      

processors:
  servicegraph:
    metrics_exporter: prometheus/servicegraph # Exporter to send metrics to
    #latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms] # Buckets for latency histogram
    dimensions: [cluster, namespace] # Additional dimensions (labels) to be added to the metrics extracted from the resource and span attributes
    store: # Configuration for the in-memory store
      ttl: 5s # Value to wait for an edge to be completed
      max_items: 500 # Amount of edges that will be stored in the storeMap

exporters:
  otlp:
    endpoint: http://jaeger-prod-collector.istio-system:4317  # to jaeger
    tls:
      insecure: true
  prometheus/servicegraph:
    endpoint: localhost:9090    
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp/traces]
      processors: [asmservicegraph]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp/servicegraph]
      processors: []
      exporters: [prometheus/servicegraph]
```
