### ISSUE TITLE
DataDog exporter is not forwarding the logs

### ISSUE THREAD

**Issue by larryc-cdw** [open-telemetry/opentelemetry-collector-contrib#23043]
### Component(s)

exporter/datadog

## Description
I am getting an error saying:
Failed to retrieve platform metadata	{"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "exec: \"uname\": executable file not found in $PATH"}
1684255603916189599 [Debug] Error fetching info for pid 1: open /etc/passwd: no such file or directory

I downloaded an executable of the collector and ran it on my machine outside of rancher and it works fine.  The same worked on another developer's machine locally.  It does not work in rancher or in AKS running as a container.

## Expected Result
Expected to see the logs when running as a container.

## Actual Result
Saw the logs only when running as an executable.

### Collector version

Tried multiple versions from 0.70.0 to 0.78.0

## Environment

Azure Kubernetes and rancher

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:

  logging:


  datadog:
    api:
      site: us3.datadoghq.com
      key: <DD API KEY here>

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
```

### Log output

```shell
Failed to retrieve platform metadata	{"kind": "exporter", "data_type": "traces", "name": "datadog", "error": "exec: \"uname\": executable file not found in $PATH"}
1684255603916189599 [Debug] Error fetching info for pid 1: open /etc/passwd: no such file or directory
```
