### ISSUE TITLE
How to aggregate gauge data points to single value in processor ?

### ISSUE THREAD

**Issue by kostyaLem** [open-telemetry/opentelemetry-collector-contrib#23052]
### Component(s)

processor/metricstransform, processor/transform

### Description:
I have a set of data points for each metric. I looked at all the processors and did not find the right one that would help to aggregate each metric.
**How to collapse each metric in _scopeMetrics.metrics_ to single values ?** 
Thanks for reading (I don't have Slack so I'm posting here) :D

### Config.yaml:
```
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4319

processors:
  batch:
    timeout: 25s
  groupbyattrs:
    keys:
      - service.name
      - service.version
      - service.instance.id
  metricstransform:
    transforms:
      - include: process.runtime.dotnet.gc.heap
        action: update
        operations:
          - action: toggle_scalar_data_type

exporters:
  file:
    path: /var/lib/data/collected.json

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch, groupbyattrs, metricstransform ]
      exporters: [ file ]
```

### ActualResult:
```
{
    "resourceMetrics": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "service.name",
                        "value": {
                            "stringValue": "DummyMicroservice"
                        }
                    },
                    {
                        "key": "service.version",
                        "value": {
                            "stringValue": "1.0.0"
                        }
                    },
                    {
                        "key": "service.instance.id",
                        "value": {
                            "stringValue": "b5e7e9b1-e297-45fd-a101-1becc1118ba6"
                        }
                    }
                ]
            },
            "scopeMetrics": [
                {
                    "metrics": [
                        {
                            "description": "GC Heap Size",
                            "gauge": {
                                "dataPoints": [
                                    {
                                        "asDouble": 5569712,
                                        "startTimeUnixNano": "1685741600647452000",
                                        "timeUnixNano": "1685741605618902700"
                                    },
                                    {
                                        "asDouble": 5610672,
                                        "startTimeUnixNano": "1685741600647452000",
                                        "timeUnixNano": "1685741606620596400"
                                    },
                                    {
                                        "asDouble": 5651632,
                                        "startTimeUnixNano": "1685741600647452000",
                                        "timeUnixNano": "1685741607627150400"
                                    },
                                    {
                                        "asDouble": 5774328,
                                        "startTimeUnixNano": "1685741600647452000",
                                        "timeUnixNano": "1685741610623289700"
                                    },
                                    {
                                        "asDouble": 5897208,
                                        "startTimeUnixNano": "1685741600647452000",
                                        "timeUnixNano": "1685741613618195300"
                                    },
                                    {
                                        "asDouble": 5165872,
                                        "startTimeUnixNano": "1685741600647452000",
                                        "timeUnixNano": "1685741601645867100"
                                    },
                                    {
                                        "asDouble": 5536944,
                                        "startTimeUnixNano": "1685741600647452000",
                                        "timeUnixNano": "1685741604627212100"
                                    }
                                ]
                            },
                            "name": "process.runtime.dotnet.gc.heap",
                            "unit": "By"
                        }
                    ],
                    "scope": {
                        "name": "OpenTelemetry.Instrumentation.Runtime",
                        "version": "0.1.0.1"
                    }
                }
            ]
        }
    ]
}
```

### Want to get:
Singe value using avregare, sum, min or max functions for each metrics in scopeMetrics.
