### ISSUE TITLE
span metrics connector messing up the metrics when the traces exporter queue is full

### ISSUE THREAD

**Issue by ramanjaneyagupta** [open-telemetry/opentelemetry-collector-contrib#23233]
## Description 
spanmetrics connector is giving wrong metrics when the exporter queue is full.

## Steps to Reproduce
i have a setup like below : 
collector agent -> collector gateway(traces) -> storage(traces).
on gateway collector(there are 3 nodes behind the load balancer) i added span metrics connector and it will write the metrics to prometheus. And from gateway collector, it will send the traces to trace backend.
So somehow my trace backend was down, so exporter queue got filed up. and from there span metrics are giving wrong numbers in grafana.

After some time,  though i started my trace backend it is showing wrong metrics. 

And on otel collector logs i am seeing the below error : " Permanent error remote write returned status code of 400 bad request" "err"=nil error out of order sample and duplicate timestamp".

## Expected Result
Span-metrics should calculate correctly
## Actual Result
span-metrics calculating wrongly, and all count and histogram metrics are gradually increasing (with high numbers).

### Collector version

v0.77.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  prometheusremotewrite:
    endpoint: http://<endpoint>
     target_info:
       enabled: true

connectors:
  spanmetrics:
   dimensions:
      - name: http.method
      - name: http.status_code
      - name: k8s.namespace.name
    namespace: span.metrics
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection/system, batch]
      exporters: [spanmetrics,tracebackend]
    metrics:
      receivers: [spanmetrics]
      processors: [resourcedetection/system, batch]
      exporters: [prometheusremotewrite]
```

### Log output

```shell
And on otel collector logs i am seeing the below error : " Permanent error remote write returned status code of 400 bad request" "err"=nil error out of order sample and duplicate timestamp".
```

### Additional context

NA
