### ISSUE TITLE
[NewRelic Exporter] Errors are not decorated

### ISSUE THREAD

**Issue by georlav** [open-telemetry/opentelemetry-collector-contrib#2327]
**Describe the bug**
Errors are not decorated and its hard to identify them at newrelic UI
Docs: https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/trace-api/trace-api-decorate-spans-attributes

Newrelic exporter does this by appending extra error attributes to the span
https://github.com/newrelic/opentelemetry-exporter-go/blob/7c24e335d64821f6aaec96e1c48d478bcb290d70/newrelic/internal/transform/span.go#L66,L69
```
errorCodeAttrKey    = "error.code"
errorMessageAttrKey = "error.message"
```

In your newrelic exporter those keys are named
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ffce8840ae193079da5ef813a4e807a17ca2fabc/exporter/newrelicexporter/transformer.go#L40,L41
```
otel.status_code
otel.status_description
```

**Steps to reproduce**
After sending an error go to Monitor -> Distributed tracing errors counter is 0

**What did you expect to see?**
I would expect to see the number of errors occurred in all spans

**What did you see instead?**
0 Errors

**What version did you use?**
Using the latest docker container otel/opentelemetry-collector-contrib

**What config did you use?**
```yml
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  newrelic:
    apikey: xxx
    timeout: 30s
    spans_url_override: https://trace-api.eu.newrelic.com/trace/v1
    metrics_url_override: https://metric-api.eu.newrelic.com/metric/v1
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [newrelic]
    metrics:
      receivers: [otlp]
      exporters: [newrelic]
```
