### ISSUE TITLE
`header_setter` does not work for Kafka Exporter

### ISSUE THREAD

**Issue by mdrakiburrahman** [open-telemetry/opentelemetry-collector-contrib#23273]
### Component(s)

extension/headerssetter

## Description
Our use case is straightforward:
1. A few dotnet services write logs to an OTEL Collector endpoint using SDK - [sample code](https://github.com/mdrakiburrahman/authenticated-otel-logger/blob/000edafcb05249b44a99946b8e2c689960e0ae72/src/Program.cs#LL36C19-L36C19)
 a. For multi-tenancy use case, various `Headers` are added to the HTTP request - that we need in Kafka.
3. A few OTEL Collectors are behind a load balancer, and need to persist the Data to Kafka. 

Basically, those `Headers` are what enable us to enable multi-tenancy. We need the headers in Kafka.

## Steps to Reproduce

When we try following the steps in the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/752330ec48dcc3f91791615f486a8253f83c6bd0/extension/headerssetterextension) for `header_setter` (which seem heavily skewed to support Grafana/Loki etc only), Kafka Exporter throws.

## Expected Result
Kafka Exporter doesn't throw, and I somehow see the headers attached to my `oltp_proto` or `oltp_json` payload in Kafka topic.

## Actual Result
When collector boots up:
```bash
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
* error decoding 'exporters': error reading configuration for "kafka": 1 error(s) decoding:
* 'auth' has invalid keys: authenticator
```

### Collector version

0.69.0

## Environment
OS: (e.g., "Ubuntu 20.04"): Docker container, running in any Kubernetes distro

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        include_metadata: true
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true

exporters:
  kafka:
    brokers:
      - ${env:EH_FQDN}
    topic: ${env:EH_NAME}
    protocol_version: 2.0.0
    encoding: ${env:EH_ENCODING}
    auth:
      # === Doing this per documentation breaks Kafka... ===
      authenticator: headers_setter
      # ===================================================
      tls:
        insecure: true
      sasl:
        username: "$$ConnectionString"
        password: ${env:EH_SAS_KEY}
        mechanism: PLAIN

extensions:
  headers_setter:
    headers:
      - key: Authorization
        value: random

service:
  extensions: [headers_setter]
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [kafka]
```

### Additional context

There's a high likelihood that `header_setter` is only meant for Grafana/Loki, and isn't supported for all Exporters - such as Kafka. It would be good if this was called out in the docs, for someone who's trying to use OpenTelemetry for Multi-tenancy without years of experience with OpenTelemetry, this isn't obvious.

If Kafka _is_ supported, I'd highly appreciate if someone could share a minimium reproducible config file that works.

**Comment by mdrakiburrahman** [comment]
Never mind, I realize what I really needed was an Attribute Processor for my use case.

E.g. the following config gets me exactly what I needed in the payload:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        include_metadata: true
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true

exporters:
  kafka:
    brokers:
      - ${env:EH_FQDN}
    topic: ${env:EH_NAME}
    protocol_version: 2.0.0
    encoding: ${env:EH_ENCODING}
    auth:
      tls:
        insecure: true
      sasl:
        username: "$$ConnectionString"
        password: ${env:EH_SAS_KEY}
        mechanism: PLAIN

processors:
  attributes:
    actions:
      - key: http.authorization
        from_context: metadata.Authorization <----------------------------
        action: upsert
extensions:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [attributes]
      exporters: [kafka]
```

Sample payload:
```json
{
   "resourceLogs": [
      {
         "resource": {
            "attributes": [
               {
                  "key": "telemetry.sdk.name",
                  "value": {
                     "stringValue": "opentelemetry"
                  }
               },
               {
                  "key": "telemetry.sdk.language",
                  "value": {
                     "stringValue": "dotnet"
                  }
               },
               {
                  "key": "telemetry.sdk.version",
                  "value": {
                     "stringValue": "1.5.0"
                  }
               },
               {
                  "key": "service.name",
                  "value": {
                     "stringValue": "unknown_service:AuthenticatedOtelLogger"
                  }
               }
            ]
         },
         "scopeLogs": [
            {
               "scope": {},
               "logRecords": [
                  {
                     "timeUnixNano": "1686528621913653800",
                     "observedTimeUnixNano": "1686528621913653800",
                     "severityNumber": 9,
                     "severityText": "Information",
                     "body": {
                        "stringValue": "[Flavor: Local OTEL AuthN: NO, Logger AuthN: MSFT SPN | Tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47 | Authorization: ServicePrincipal] [Hostname: 2-sample-logger-local-spnyesmsftauth-84987677c6-zlnkp | Logging endpoint: http://otel-collector:4318/v1/logs] Counter: 5689"
                     },
                     "attributes": [
                        {
                           "key": "dotnet.ilogger.category",
                           "value": {
                              "stringValue": "AuthenticatedOtelLogger.Program"
                           }
                        },
                        {
                           "key": "scope_name",
                           "value": {
                              "stringValue": "parent"
                           }
                        },
                        {
                           "key": "http.authorization",
                           "value": {
                              "stringValue": "Bearer eyJ..." <----------------------------
                           }
                        }
                     ],
                     "traceId": "",
                     "spanId": ""
                  }
               ]
            }
         ]
      }
   ]
}
```
