### ISSUE TITLE
Can't create `prometheus` receiver in `receiver_creator`: invalid keys: scrape_configs

### ISSUE THREAD

**Issue by marcogiorgio** [open-telemetry/opentelemetry-collector-contrib#23341]
### Component(s)

receiver/prometheus, receiver/receivercreator

## Description
I am trying to gather `cadvisor` metrics in an AWS EKS/Fargate environment. The idea is having `prometheus` receivers dynamically created using a `receiver_creator` block able to gather metrics from `/api/v1/nodes/'name'/proxy/metrics/cadvisor`. However, this fails.

## Steps to Reproduce
Try to start a prometheusreceiver

## Expected Result
Prometheus receiver collecting `cadvisor` metrics

## Actual Result
`failed to start receiver	{"kind": "receiver", "name": "receiver_creator", "data_type": "metrics", "receiver": "prometheus", "error": "failed to load \"prometheus\" template config: prometheus receiver failed to parse config: 1 error(s) decoding:\n\n* '' has invalid keys: scrape_configs"}`

### Collector version

v0.78.0

## Environment

AWS EKS/Fargate

### OpenTelemetry Collector configuration

```yaml
This is the configmap currently in use:

Name:         splunk-otel-collector-otel-k8s-cluster-receiver
Namespace:    observability
Labels:       app=splunk-otel-collector
              app.kubernetes.io/instance=splunk-otel-collector
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=splunk-otel-collector
              app.kubernetes.io/version=0.78.1
              chart=splunk-otel-collector-0.78.0
              helm.sh/chart=splunk-otel-collector-0.78.0
              heritage=Helm
              release=splunk-otel-collector
Annotations:  meta.helm.sh/release-name: splunk-otel-collector
              meta.helm.sh/release-namespace: observability

Data
====
relay:
----
exporters:
  signalfx:
    access_token: ${SPLUNK_OBSERVABILITY_ACCESS_TOKEN}
    api_url: https://api.us1.signalfx.com
    ingest_url: https://ingest.us1.signalfx.com
    timeout: 10s
extensions:
  health_check: null
  k8s_observer:
    auth_type: serviceAccount
    observe_nodes: true
    observe_pods: true
  memory_ballast:
    size_mib: ${SPLUNK_BALLAST_SIZE_MIB}
processors:
  batch:
    send_batch_max_size: 32768
  memory_limiter:
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
  resource:
    attributes:
    - action: insert
      key: metric_source
      value: kubernetes
    - action: upsert
      key: k8s.cluster.name
      value: ws-in-sme-poc
  resource/add_collector_k8s:
    attributes:
    - action: insert
      key: k8s.node.name
      value: ${K8S_NODE_NAME}
    - action: insert
      key: k8s.pod.name
      value: ${K8S_POD_NAME}
    - action: insert
      key: k8s.pod.uid
      value: ${K8S_POD_UID}
    - action: insert
      key: k8s.namespace.name
      value: ${K8S_NAMESPACE}
  resource/k8s_cluster:
    attributes:
    - action: insert
      key: receiver
      value: k8scluster
  resourcedetection:
    detectors:
    - env
    - eks
    - ec2
    - system
    override: true
    timeout: 10s
receivers:
  k8s_cluster:
    auth_type: serviceAccount
    metadata_exporters:
    - signalfx
  prometheus/k8s_cluster_receiver:
    config:
      scrape_configs:
      - job_name: otel-k8s-cluster-receiver
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${K8S_POD_IP}:8889
  receiver_creator:
    receivers:
      kubeletstats:
        config:
          auth_type: serviceAccount
          collection_interval: 10s
          endpoint: '`endpoint`:`kubelet_endpoint_port`'
          extra_metadata_labels:
          - container.id
          metric_groups:
          - container
          - pod
          - node
        rule: type == "k8s.node" && name contains "fargate"
      prometheus:
        config:
          scrape_configs:
          - authorization:
              credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            job_name: cadvisor
            metric_relabel_configs:
            - action: keep
              regex: container_cpu_cfs_.*
              source_labels:
              - __name__
            scheme: https
            scrape_interval: 10s
            static_configs:
            - metrics_path: /api/v1/nodes/`name`/proxy/metrics/cadvisor
              targets:
              - ${KUBERNETES_SERVICE_HOST}:443
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        rule: type == "k8s.node" && ("${K8S_POD_NAME}" endsWith "0") && name contains
          "fargate"
    watch_observers:
    - k8s_observer
service:
  extensions:
  - health_check
  - memory_ballast
  - k8s_observer
  pipelines:
    metrics:
      exporters:
      - signalfx
      processors:
      - memory_limiter
      - batch
      - resource
      - resource/k8s_cluster
      receivers:
      - k8s_cluster
    metrics/collector:
      exporters:
      - signalfx
      processors:
      - memory_limiter
      - batch
      - resource/add_collector_k8s
      - resourcedetection
      - resource
      receivers:
      - prometheus/k8s_cluster_receiver
    metrics/eks:
      exporters:
      - signalfx
      processors:
      - memory_limiter
      - batch
      - resource
      receivers:
      - receiver_creator
  telemetry:
    metrics:
      address: 0.0.0.0:8889
```

### Log output

```shell
failed to start receiver	{"kind": "receiver", "name": "receiver_creator", "data_type": "metrics", "receiver": "prometheus", "error": "failed to load \"prometheus\" template config: prometheus receiver failed to parse config: 1 error(s) decoding:\n\n* '' has invalid keys: scrape_configs"}
```
