### ISSUE TITLE
Change operation by using transform

### ISSUE THREAD

**Issue by ekfo33** [open-telemetry/opentelemetry-collector-contrib#23371]
### Is your feature request related to a problem? Please describe.

I'm using otel collector for collecting trace(using jaeger)
Some request has id (example, GET /hello?id=???)
in those case, spanmetrics has high cardinality.

### Describe the solution you'd like

So, I want change operation (GET /hello?id=??? --> GET /hello?). 
I referred (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md) but, I do not know how to change operation.

**Comment by evan-bradley** [comment]
It sounds like the [replace_match](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#replace_match) function would fit your use case, do you think that would work for your use case? I could see the config looking like this:

```yaml
transform:
  trace_statements:
    - context: span
      statements:
        - replace_match(name, "/hello?id=*", "/hello?id={id}")
```
