### ISSUE TITLE
[awscontainerinsightsreceiver]- Full Pod Name is not being set when configured.

### ISSUE THREAD

**Issue by vasireddy99** [open-telemetry/opentelemetry-collector-contrib#23370]
### Component(s)

receiver/awscontainerinsight

## Description
The "PodName" attribute is not set to the full pod's name, when `prefer_full_pod_name` is set to true. 
K8 Controller-Daemonset

## Steps to Reproduce
Example Deployment template used.
```
# create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: aws-otel-eks
  labels:
    name: aws-otel-eks

---
# create cwagent service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-otel-sa
  namespace: aws-otel-eks

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aoc-agent-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "endpoints"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes/stats", "configmaps", "events"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    resourceNames: ["otel-container-insight-clusterleader"]
    verbs: ["get","update", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["otel-container-insight-clusterleader"]
    verbs: ["get","update", "create"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create","get", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aoc-agent-role-binding
subjects:
  - kind: ServiceAccount
    name: aws-otel-sa
    namespace: aws-otel-eks
roleRef:
  kind: ClusterRole
  name: aoc-agent-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  namespace: aws-otel-eks
  labels:
    app: opentelemetry
    component: otel-agent-conf
data:
  otel-agent-config: |
    extensions:
      health_check:
      sigv4auth:
        region: "us-west-2"

    receivers:
      awscontainerinsightreceiver:
        prefer_full_pod_name: true

    processors:
      batch/metrics:
        timeout: 10s

    exporters:
      prometheusremotewrite:
        #remote write url
        endpoint: "https://aps-workspaces.us-west-2.amazonaws.com/workspaces/*****/api/v1/remote_write"
        resource_to_telemetry_conversion:
          enabled: true
        auth:
          authenticator: sigv4auth
      awsemf:
        namespace: ContainerInsights
        log_group_name: '/aws/containerinsights/{ClusterName}/performance'
        log_stream_name: '{NodeName}'
        resource_to_telemetry_conversion:
          enabled: true
        dimension_rollup_option: NoDimensionRollup
        parse_json_encoded_attr_values: [Sources, kubernetes]
        metric_declarations:
          # node metrics
          - dimensions: [[NodeName, InstanceId, ClusterName]]
            metric_name_selectors:
              - node_cpu_utilization
              - node_memory_utilization
              - node_network_total_bytes
              - node_cpu_reserved_capacity
              - node_memory_reserved_capacity
              - node_number_of_running_pods
              - node_number_of_running_containers
          - dimensions: [[ClusterName]]
            metric_name_selectors:
              - node_cpu_utilization
              - node_memory_utilization
              - node_network_total_bytes
              - node_cpu_reserved_capacity
              - node_memory_reserved_capacity
              - node_number_of_running_pods
              - node_number_of_running_containers
              - node_cpu_usage_total
              - node_cpu_limit
              - node_memory_working_set
              - node_memory_limit

          # pod metrics
          - dimensions: [[PodName, Namespace, ClusterName], [Service, Namespace, ClusterName], [Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - pod_cpu_utilization
              - pod_memory_utilization
              - pod_network_rx_bytes
              - pod_network_tx_bytes
              - pod_cpu_utilization_over_pod_limit
              - pod_memory_utilization_over_pod_limit
          - dimensions: [[PodName, Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - pod_cpu_reserved_capacity
              - pod_memory_reserved_capacity
          - dimensions: [[PodName, Namespace, ClusterName]]
            metric_name_selectors:
              - pod_number_of_container_restarts

          # cluster metrics
          - dimensions: [[ClusterName]]
            metric_name_selectors:
              - cluster_node_count
              - cluster_failed_node_count

          # service metrics
          - dimensions: [[Service, Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - service_number_of_running_pods

          # node fs metrics
          - dimensions: [[NodeName, InstanceId, ClusterName], [ClusterName]]
            metric_name_selectors:
              - node_filesystem_utilization

          # namespace metrics
          - dimensions: [[Namespace, ClusterName], [ClusterName]]
            metric_name_selectors:
              - namespace_number_of_running_pods

    service:
      pipelines:
        metrics:
          receivers: [awscontainerinsightreceiver]
          processors: [batch/metrics]
          exporters: [awsemf, prometheusremotewrite]

      extensions: [health_check, sigv4auth]


---
# create Daemonset
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-otel-eks-ci
  namespace: aws-otel-eks
spec:
  selector:
    matchLabels:
      name: aws-otel-eks-ci
  template:
    metadata:
      labels:
        name: aws-otel-eks-ci
    spec:
      containers:
        - name: aws-otel-collector
          image: public.ecr.aws/aws-observability/aws-otel-collector:v0.30.0
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: Always
          command:
            - "/awscollector"
            - "--config=/conf/otel-agent-config.yaml"
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: varlibdocker
              mountPath: /var/lib/docker
              readOnly: true
            - name: containerdsock
              mountPath: /run/containerd/containerd.sock
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: devdisk
              mountPath: /dev/disk
              readOnly: true
            - name: otel-agent-config-vol
              mountPath: /conf
          resources:
            limits:
              cpu:  200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
        - configMap:
            name: otel-agent-conf
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml
          name: otel-agent-config-vol
        - name: rootfs
          hostPath:
            path: /
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker
        - name: containerdsock
          hostPath:
            path: /run/containerd/containerd.sock
        - name: sys
          hostPath:
            path: /sys
        - name: devdisk
          hostPath:
            path: /dev/disk/
      serviceAccountName: aws-otel-sa

```

## Expected Result

Prefer Full pod Name when `prefer_full_pod_name: true`

## Actual Result
Full Pod Name is not reflected.

### Collector version

v0.78.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Log output

```shell
{
    "AutoScalingGroupName": "eks-ng-15d5ba68-52c44b3a-4150-86e3-6e8d-e176c601b6c1",
    "ClusterName": "my-cluster",
    "InstanceId": "i-021eb5739e33e7b5a",
    "InstanceType": "m5.large",
    "Namespace": "aws-otel-eks",
    "NodeName": "ip-192-168-68-251.us-west-2.compute.internal",
    "PodName": "aws-otel-eks-ci", // POD Name
    "Sources": [
        "cadvisor",
        "pod",
        "calculated"
    ],
    "Timestamp": "1686720884057",
    "Type": "Container",
    "Version": "0",
    "container_cpu_limit": 200,
    "container_cpu_request": 200,
    "container_cpu_usage_system": 0.30053388832913264,
    "container_cpu_usage_total": 2.3600048691532867,
    "container_cpu_usage_user": 1.2021355533165305,
    "container_cpu_utilization": 0.11800024345766434,
    "container_memory_cache": 0,
    "container_memory_failcnt": 0,
    "container_memory_hierarchical_pgfault": 12.892903809319792,
    "container_memory_hierarchical_pgmajfault": 0,
    "container_memory_limit": 209715200,
    "container_memory_mapped_file": 0,
    "container_memory_max_usage": 31723520,
    "container_memory_pgfault": 12.892903809319792,
    "container_memory_pgmajfault": 0,
    "container_memory_request": 209715200,
    "container_memory_rss": 30412800,
    "container_memory_swap": 0,
    "container_memory_usage": 31592448,
    "container_memory_utilization": 0.3943082198923972,
    "container_memory_working_set": 31592448,
    "container_status": "Running",
    "kubernetes": {
        "container_name": "aws-otel-collector",
        "containerd": {
            "container_id": "cee20356e2e6c7fc795ee47b1a84714a9bf1cb3897d97361519c884fc7ff280b"
        },
        "host": "ip-192-168-68-251.us-west-2.compute.internal",
        "labels": {
            "controller-revision-hash": "6697b947c5",
            "name": "aws-otel-eks-ci",
            "pod-template-generation": "1"
        },
        "namespace_name": "aws-otel-eks",
        "pod_id": "4000d5f6-******a07112d64d41",
        "pod_name": "aws-otel-eks-ci-cxlbq",
        "pod_owners": [
            {
                "owner_kind": "DaemonSet",
                "owner_name": "aws-otel-eks-ci"
            }
        ]
    },
    "number_of_container_restarts": 0
}
```
