### ISSUE TITLE
receiver_creator doesn't appear to create prometheus receivers even though there were no error logs

### ISSUE THREAD

**Issue by hardproblems** [open-telemetry/opentelemetry-collector-contrib#23388]
### Component(s)

receiver/prometheus, receiver/receivercreator

## Description

I am trying to use an otel-collector daemonset pod to scrape istio-proxy containers from all pods on the same host as the otel-collector daemonset pod. Since pods can come and go, I'm using `receiver_creator` to dynamically create prometheus receivers when it sees new pods that match the rule block.

## Steps to Reproduce

I turned on debug logging and can see observer_handler logging newly added endpoints and confirm that they match my rule. 
![Screenshot 2023-06-14 at 5 40 14 PM](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/142453/c4b2a32c-a335-4af7-b4cd-25db38f44894)

and can can curl the endpoints from the daemonset otel-collector pod (http//$endpoint:15020/stats/prometheus and get metrics

However, there're no logs past [this line in observerhandler.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/receivercreator/observerhandler.go#L86). I also didn't see any errors at startup time complaining about the config being invalid. Would be great to have more metrics/logs observability in the receivercreator to make debugging easier.

## Expected Result
Prometheus receiver should be created and collects istio-proxy container metrics from pods on the same host

## Actual Result
Nothing is being enqueued or sent through the prometheusremotewrite/airmesh-dataplane exporter

### Collector version

v0.78.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

self-hosted k8s clusters running in AWS
go 1.19.5
Ubuntu 22.04 (last updated 2023-05-15)

### OpenTelemetry Collector configuration

```yaml
exporters:
  prometheusremotewrite/airmesh-dataplane:
    endpoint: $some-internal-endpoint
    external_labels:
      agent: otelcol-sidecar
      k8s_role: node
      kube_cluster: m-bigq-test-a-ea1-us
      kube_cluster_type: m-bigq-test-ea1-us
    headers:
    - X-Scope-OrgID: airmesh
    remote_write_queue:
      queue_size: 50
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 35s
      max_interval: 20s
    target_info:
      enabled: false
    timeout: 14s
extensions:
  health_check:
  k8s_observer:
    auth_type: serviceAccount
    observe_nodes: true
    observe_pods: true
  memory_ballast:
    size_mib: 128
processors:
  batch/telescope:
    send_batch_max_size: 2000
    send_batch_size: 2000
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_mib: 577
receivers:
  receiver_creator:
    prometheus:
      config:
        config:
          scrape_configs:
          - job_name: istio-proxy
            metrics_path: /stats/prometheus
            scrape_interval: 15s
            scrape_timeout: 5s
            static_configs:
            - labels:
                __metrics_path__: /stats/prometheus
                image_tag: '`labels["istio.io/rev"]`'
              targets:
              - '`endpoint`:15020'
      rule: type == "pod" && "istio.io/rev" in labels
    watch_observers:
    - k8s_observer
service:
  extensions:
  - memory_ballast
  - k8s_observer
  pipelines:
    metrics/airmesh-dataplane:
      exporters:
      - prometheusremotewrite/airmesh-dataplane
      processors:
      - memory_limiter
      - batch/telescope
      receivers:
      - receiver_creator
  telemetry:
    logging:
      level: debug
```

### Log output

```shell
see screenshot above
```

### Additional context

After seeing https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23341 i checked to make sure there are two levels of `config` key under the prometheus receiver. However it didn't seem to make a difference.
