### ISSUE TITLE
AzureMonitor exporter does not correctly handle non-string Body types

### ISSUE THREAD

**Issue by drewby** [open-telemetry/opentelemetry-collector-contrib#23422]
### Component(s)

exporter/azuremonitor

## Description
AzureMonitor correctly exports log messages that have a logRecord.Body().Type of ValueTypeStr. However, other types are possible (for example, Map). These are correctly handled by other exporters, but the AzureMonitor exporter uses sets the envelope message to an empty string when the logRecord.Body().Type is not ValueTypeStr. This is because the extension uses the ".Str()" function to convert to string which only recognizes ValueTypeStr.

## Steps to Reproduce

1. Run an OpenTelemetry Collector with the following config:

```
receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:14317

processors:

exporters:
  logging:
    verbosity: detailed
  azuremonitor:
    instrumentation_key: 4e6564eb-ad8f-49cc-8b0e-5464ddea7690

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [azuremonitor, logging]
```

3. Configure fluent-bit to forward logs to the above OLTP endpoint

## Expected Result

Both AzureMonitor and Logging should emit logs including the Body.

## Actual Result

Logging correctly emits a log to the console with the Body correctly displayed.

AzureMonitor emits an envelope with message set to empty string, causing an error when forwarding to the Azure Monitor service.

### Collector version

Custom build 0.77.0 with azuremonitorexporter, loggingexporters, otlpreceiver

### Environment information

Fluent Bit v2.1.4 via docker image fluent/fluent-bit:latest

### OpenTelemetry Collector configuration

```yaml
extensions:

receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:14317

processors:
  batch:

exporters:
  logging:
    verbosity: detailed
  azuremonitor:
    instrumentation_key: 4e6564eb-ad8f-49cc-8b0e-5464ddea7690

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [azuremonitor]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [azuremonitor]

  telemetry:
    logs:
      level: "debug"
```

### Additional context

The following line in LogRecordToEnvelope requires a ValueTypeStr for Body: 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/559f19c11d343b7b7833e0038c2b38d7d9a6c0d4/exporter/azuremonitorexporter/log_to_envelope.go#L33

Logging correctly accepts other value types for Body by using .AsString():

https://github.com/open-telemetry/opentelemetry-collector/blob/e1d1297d0bee677d07cd60e837080d32ba453f91/exporter/loggingexporter/internal/otlptext/databuffer.go#LL261C1-L263C2
