### ISSUE TITLE
Prometheus Remote Write mkdir permission denied wal error

### ISSUE THREAD

**Issue by zakariais** [open-telemetry/opentelemetry-collector-contrib#23442]
### Component(s)

exporter/prometheusremotewrite

### What happened?

Hi,
I am getting below error when enabling wal in prometheus remote write exporter
Error: cannot start pipelines: prometheusremotewriteexporter: failed to open WAL: mkdir /tmp: permission denied; failed to shutdown pipelines: no existing monitoring routine is running; no existing monitoring routine is running.
I am using 0.75.0 otel version
kubernetes 1.23

### Collector version

0.75.0

### Environment information

EKS kubernetes 1.23

### OpenTelemetry Collector configuration

```yaml
relay: |
    exporters:
      logging:
        verbosity: basic
      otlp:
        endpoint: jaeger-operator-jaeger-collector:4317
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local/api/v1/write
        remote_write_queue:
          enabled: true
        resource_to_telemetry_conversion:
          enabled: true
        target_info:
          enabled: false
        tls:
          insecure: true
        wal:
          buffer_size: 100
          directory: /tmp/prom
          truncate_frequency: 45s
    extensions:
      health_check: {}
      memory_ballast:
        size_in_percentage: 40
      zpages: {}
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${MY_POD_IP}:6831
          thrift_http:
            endpoint: ${MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${MY_POD_IP}:8888
      zipkin:
        endpoint: ${MY_POD_IP}:9411
    service:
      extensions:
      - health_check
      - memory_ballast
      - zpages
      pipelines:
        logs:
          exporters:
          - logging
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
        metrics:
          exporters:
          - prometheusremotewrite
          - logging
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
        traces:
          exporters:
          - otlp
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: 0.0.0.0:8888
```

### Log output

```shell
Error: cannot start pipelines: prometheusremotewriteexporter: failed to open WAL: mkdir /tmp: permission denied; failed to shutdown pipelines: no existing monitoring routine is running; no existing monitoring routine is running.
```

**Comment by mwear** [comment]
@zakariais Taking a quick look at your config I see:

```
wal:
          buffer_size: 100
          directory: /tmp/prom
          truncate_frequency: 45s
```

And your log message says: `failed to open WAL: mkdir /tmp: permission denied;`

Can you ensure that `tmp` is writable for your user, or try changing the wal directory to something that you know is writable?
