### ISSUE TITLE
OTTL: Allow copying attributes with a regex

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#23444]
### Component(s)

pkg/ottl, processor/transform

### Is your feature request related to a problem? Please describe.

A common usecase in Prometheus is to copy all resource attributes matching a prefix / regex into metric attributes.

Right now its not possible and users are asking for workaround features in the exporter itself: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/22914

The usecase in the above issue is that they'd like to copy all the resource attributes with`k8s.*` regex into metric attributes. And right now they're doing the following:

```
transform:
  metric_statements:
    - context: datapoint
      statements:
        - set(attributes["k8s_replicaset_name"], resource.attributes["k8s.replicaset.name"])
        - set(attributes["k8s_deployment_name"], resource.attributes["k8s.deployment.name"])
        - set(attributes["k8s_statefulset_name"], resource.attributes["k8s.statefulset.name"])
        - set(attributes["k8s_hpa_name"], resource.attributes["k8s.hpa.name"])
        - set(attributes["k8s_volume_name"], resource.attributes["k8s.volume.name"])
        - set(attributes["k8s_job_name"], resource.attributes["k8s.job.name"])
        ....
```

This is not scalable as new attributes that are added will be missed.

### Describe the solution you'd like

Something like: `copy_keys(target, source, regex)`

```
transform:
  metric_statements:
    - context: datapoint
      statements:
        - copy_keys(attributes, resource.attributes, "k8s.*")
```
