### ISSUE TITLE
[receiver/k8scluster] Attribute k8s.namespace.name in k8s.namespace.phase is always empty

### ISSUE THREAD

**Issue by eplightning** [open-telemetry/opentelemetry-collector-contrib#23452]
### Component(s)

receiver/k8scluster

## Description

Namespace name resource attribute for namespace phase metrics in k8scluster receiver seems to be incorrectly populated.

## Steps to Reproduce

Configure k8scluster receiver and configure pipeline to export metrics from it (for example via Prometheus exporter)

## Expected Result

```
# HELP k8s_namespace_phase The current phase of namespaces (1 for active and 0 for terminating)
# TYPE k8s_namespace_phase gauge
k8s_namespace_phase{k8s_namespace_name="some-namespace-name",k8s_namespace_uid="17484d33-f8e6-4512-bebf-394de39a6278",opencensus_resourcetype="k8s"} 1
k8s_namespace_phase{k8s_namespace_name="other-namespace",k8s_namespace_uid="2a0d3510-f895-4cd9-84ff-cd8078cf7097",opencensus_resourcetype="k8s"} 1
k8s_namespace_phase{k8s_namespace_name="kube-system",k8s_namespace_uid="2ba798ae-2e10-45a1-bd73-60d892349123",opencensus_resourcetype="k8s"} 1
```

## Actual Result

```
# HELP k8s_namespace_phase The current phase of namespaces (1 for active and 0 for terminating)
# TYPE k8s_namespace_phase gauge
k8s_namespace_phase{k8s_namespace_name="",k8s_namespace_uid="17484d33-f8e6-4512-bebf-394de39a6278",opencensus_resourcetype="k8s"} 1
k8s_namespace_phase{k8s_namespace_name="",k8s_namespace_uid="2a0d3510-f895-4cd9-84ff-cd8078cf7097",opencensus_resourcetype="k8s"} 1
k8s_namespace_phase{k8s_namespace_name="",k8s_namespace_uid="2ba798ae-2e10-45a1-bd73-60d892349123",opencensus_resourcetype="k8s"} 1
```

### Collector version

v0.79.0

## Environment
OS: Ubuntu 22.04.2 LTS
Compiler(if manually compiled): go 1.20

### OpenTelemetry Collector configuration

```yaml
receivers:
      k8s_cluster:
        collection_interval: 1m
        auth_type: serviceAccount
        allocatable_types_to_report: [cpu, memory]
    exporters:
      prometheus:
        endpoint: 0.0.0.0:9402
        resource_to_telemetry_conversion:
          enabled: true
    processors:
      batch:
    extensions:
      health_check:
    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [k8s_cluster]
          processors: [batch]
          exporters: [prometheus]
```
