### ISSUE TITLE
[receiver/hostmetrics]process.cpu.utilization not scraped when process.cpu.time is disabled

### ISSUE THREAD

**Issue by rubenruizdegauna** [open-telemetry/opentelemetry-collector-contrib#23450]
### Component(s)

receiver/hostmetrics

## Description
`process.cpu.utilization` optional metric is not scraped if `process.cpu.time` is disabled.

## Steps to Reproduce
Enable `hostmetricsreceiver` with `process.cpu.time` disabled and `process.cpu.utilization` enabled:
```yaml
receivers:
  hostmetrics:
    collection_interval: 20s
    scrapers:
      process:
        metrics:
          process.cpu.utilization:
            enabled: true
          process.cpu.time:
            enabled: false

```

## Expected Result
`process.cpu.utilization` metric should be sent.

## Actual Result
`process.cpu.utilization` metric is not sent.

### Collector version

5fff1040a2

## Environment
OS: Ubuntu 20.04, Macos 13.4
Compiler: go 19.1

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    collection_interval: 20s
    scrapers:
      process:
        metrics:
          process.cpu.utilization:
            enabled: true
          process.cpu.time:
            enabled: false
```

### Additional context

While debugging this I created a PR that fixes the bug. Feel free to review and merge it :) 

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/23451
