### ISSUE TITLE
New component: Alert Manager Exporter

### ISSUE THREAD

**Issue by sokoide** [open-telemetry/opentelemetry-collector-contrib#23569]
### The purpose and use-cases of the new component

OTEL event is a span event in Tracing added by [AddEvent ](https://opentelemetry.io/docs/specs/otel/trace/api/#add-events) API or a logging event added by [Log Event API](https://opentelemetry.io/docs/specs/otel/logs/event-api/).
Before the OTEL logging is finalized, we are using the former (trace event) for events.

We'd like to filter and forward specific OTEL events to an [Alert Manager](https://prometheus.io/docs/alerting/latest/alertmanager/) instances to notify a critical error which need attention.

The filter part can be done by the existing `transform` processor. This component will focus on the exporter part to Alert Manager.

### Example configuration for the component

```yaml
exporters:
  logging:
    loglevel: debug
  alertmanager:
    generator_url: "otelcol.example.com:4317"
    endpoint: "http://alertmanager.example.com:12345"
    severity: "info"
    severity_attribute: "severity"
    tls:
      insecure: true
    timeout: 1s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 10
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_interval: 10s
      max_elapsed_time: 10s
```

### Telemetry data types supported

- traces (initial focus)
- logs (later)

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.
