### ISSUE TITLE
[exporter/awsemf] upDownCounter is not properly handled by the awsemf exporter

### ISSUE THREAD

**Issue by rapphil** [open-telemetry/opentelemetry-collector-contrib#23579]
### Component(s)

exporter/awsemf

## Description

It seems that the [upDownCounter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#updowncounter) in OpenTelemetry doesn’t work well with the awsemfexporter.

Take JVM memory metrics as an example, the java agent registers memory metrics with [upDownCounterBuilder](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/ca24c388463cb36baa4b3926b26d7fc4b348b237/instrumentation/runtime-telemetry/runtime-telemetry-java8/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/java8/MemoryPools.java#L89).

Then I use the emf exporter to publish the metrics to CloudWatch.
In the CloudWatch (see the attached image), it shows the the “increments/decrements” instead of the “current value”.
(In this particular case, I want to know the current memory limit instead of the increments)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/5030304/52147f1d-2771-49bd-ac36-1f9f89174612)

## Steps to Reproduce

Use the OpenTelemetry Java agent to get runtime process metrics about the heap and try to send those metrics to CloudWatch using emf.

## Expected Result

We expect to see the actual value for the heap size instead of the delta.

## Actual Result

We can only see the values in the form of increments.

### Collector version

0.78.0

## Environment
NA

### OpenTelemetry Collector configuration

```yaml
NA
```

### Log output

```shell
NA
```

### Additional context

NA

**Comment by karoldrazek** [comment]
This core issue is probably the same as in: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18408

**Comment by karoldrazek** [comment]
@rapphil Not sure if you managed to work this around, but until fix is implemented you can utilize jmx-metrics plugin that is included in otel java agent (also in aws distro). Define each JMX item as separate gauge metric and it will be exported just fine by awsemf. 
`java -javaagent:/path/otel-agent.jar -Dotel.jmx.config=/path/jmx.yaml`

Example jmx.yaml
```
---
rules:
  - bean: java.lang:type=Memory
    mapping:
      HeapMemoryUsage.used:
        metric: java.jmx.memory.heapmemoryusage.used
        type: gauge
        desc: The current heap size
        unit: By
      HeapMemoryUsage.max:
        metric: java.jmx.memory.heapmemoryusage.max
        type: gauge
        desc: The maximum allowed heap size
        unit: By
  - bean: java.lang:name=G1 Old Gen,type=MemoryPool
    mapping:
      Usage.max:
        metric: java.jmx.memorypool.g1oldgen.max
        type: gauge
        desc: G1 Old Gen pool memory currently max
        unit: By
      Usage.used:
        metric: java.jmx.memorypool.g1oldgen.used
        type: gauge
        desc: G1 Old Gen pool memory currently used
        unit: By        
```
