### ISSUE TITLE
HPA autoscaling/v2beta2 Deprecated Warning

### ISSUE THREAD

**Issue by gurpartb** [open-telemetry/opentelemetry-collector-contrib#23612]
### Component(s)

receiver/k8scluster

## Description
Repeatedly getting HPA autoscaling/v2beta2 Deprecated Warning in AKS

## Steps to Reproduce
Deploy Otel Collector version 0.76.0 in AKS

## Expected Result
Ignore autoscaling/v2beta2 warning

## Actual Result
Deprecated Warning

### Collector version

v0.76.0

## Environment
Node Info:
architecture            : amd64
bootID                  : xxx
containerRuntimeVersion : containerd://1.7.1+azure-1
kernelVersion           : 5.15.0-1038-azure
kubeProxyVersion        : v1.25.6
kubeletVersion          : v1.25.6
machineID               : xxx
operatingSystem         : linux
osImage                 : Ubuntu 22.04.2 LTS
systemUUID              : xxx

### OpenTelemetry Collector configuration

```yaml
data:
  relay: |
    exporters:
      splunk_hec/platform_metrics:
        endpoint: xxx
        index: xxx
        splunk_app_version: 0.76.0
        token: ${SPLUNK_PLATFORM_HEC_TOKEN}
    extensions:
      health_check: null
      memory_ballast:
        size_mib: ${SPLUNK_BALLAST_SIZE_MIB}
    processors:
      batch:
        send_batch_max_size: 32768
      memory_limiter:
        check_interval: 2s
        limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
      resource:
        attributes:
        - action: insert
          key: metric_source
          value: kubernetes
      resource/add_collector_k8s:
        attributes:
        - action: insert
          key: k8s.node.name
          value: ${K8S_NODE_NAME}
        - action: insert
          key: k8s.pod.name
          value: ${K8S_POD_NAME}
        - action: insert
          key: k8s.pod.uid
          value: ${K8S_POD_UID}
        - action: insert
          key: k8s.namespace.name
          value: ${K8S_NAMESPACE}
      resource/k8s_cluster:
        attributes:
        - action: insert
          key: receiver
          value: k8scluster
    receivers:
      k8s_cluster:
        auth_type: serviceAccount
    service:
      extensions:
      - health_check
      - memory_ballast
      pipelines:
        metrics:
          exporters:
          - splunk_hec/platform_metrics
          processors:
          - memory_limiter
          - batch
          - resource
          - resource/k8s_cluster
          receivers:
          - k8s_cluster
```

### Log output

```shell
W0621 17:17:58.295255       1 warnings.go:70] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
W0621 17:17:58.299935       1 warnings.go:70] autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
```
