### ISSUE TITLE
Headersetter extension not supporting action: insert

### ISSUE THREAD

**Issue by akalita-conga** [open-telemetry/opentelemetry-collector-contrib#23634]
### What happened?

I am trying to pass dynamic header using https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/headerssetterextension/README.md extension for Loki exporter

Exporter Config
       lok:
        endpoint: http://loki--gateway:80/loki/api/v1/push
        auth:
          authenticator: headers_setter

## Steps to Reproduce
Using the config from the https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/headerssetterextension/README.md
extensions:
  headers_setter:
    headers:
      - action: insert
        key: X-Scope-OrgID
        from_context:  Orgid(Should be dynamically passed /value should come from the log attribute)
 

## Expected Result
I was expecting logs segregated according to the Orgid that is passed in logs dynamically. S3 bucket should have different directory for each orgid(orgid1,orgid2)
TenantId1=orgid1
Tenantid2=orgid2
But it is not working. 
It would be great if someone can help me setting up this multitenant environment.

### Collector version

opentelemetry-collector-contrib:0.69.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
apiVersion: v1
data:
    exporters:
      loki/multitenant:
        endpoint: http://loki--gateway:80/loki/api/v1/push
        auth:
          authenticator: headers_setter
        labels:
          attributes:
            OrgId: OrgId
          resource:
            k8s.namespace.name: k8s_namespace_name
            service.name: service_name
        tls:
          insecure: true
          insecure_skip_verify: true
    extensions:
      headers_setter:
        headers:
         - action: insert
           key: X-Scope-OrgID
           from_context: OrgId

    processors:
      resource:
        extract:
          labels:
          - key: deployment.environment
            tag_name: deployment.environment
    receivers:
      filelog:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            include_metadata: true

    service:
      extensions:
      - headers_setter
      pipelines:
        logs:
          exporters:
          - loki
          processors:
          - resource
          receivers:
          - otlp
          - filelog
```

### Log output

```shell
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'extensions': error reading configuration for "headers_setter": 1 error(s) decoding:

* 'headers[0]' has invalid keys: action
2023/06/21 18:05:22 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'extensions': error reading configuration for "headers_setter": 1 error(s) decoding:

* 'headers[0]' has invalid keys: action
```

### Additional context

Expectation : Need to pass OrgId dynamically which will create separate directory in the S3 for Loki backend
