### ISSUE TITLE
Otel upload metrics to prometheus every 15 sec, despite scraping interval on scrape jobs

### ISSUE THREAD

**Issue by mpostument** [open-telemetry/opentelemetry-collector-contrib#23635]
### Component(s)

exporter/prometheus, exporter/prometheusremotewrite

### Describe the issue you're reporting

Hello, i am running otel as daemon set in kubernetes, otel gateway. On otel daemon set i have job which scrape node exporter endpoint and send data to otel gateway. Daemonset config

```yaml
exporters:
  logging: {}
  otlp:
    endpoint: observability-v2-otel-deployment:4317
    tls:
      insecure: true
extensions:
  health_check: {}
  memory_ballast:
    size_in_percentage: 40
processors:
  batch: {}
  k8sattributes:
    extract:
      metadata:
      - k8s.namespace.name
      - k8s.statefulset.name
      - k8s.daemonset.name
      - k8s.cronjob.name
      - k8s.job.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.deployment.name
    filter:
      node_from_env_var: K8S_NODE_NAME
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
receivers:
  filelog:
    exclude:
    - /var/log/pods/observability_observability-v2-otel-daemonset*_*/opentelemetry-collector-daemonset/*.log
    include:
    - /var/log/pods/*/*/*.log
    include_file_name: false
    include_file_path: true
    operators:
    - id: get-format
      routes:
      - expr: body matches "^\\{"
        output: parser-docker
      - expr: body matches "^[^ Z]+ "
        output: parser-crio
      - expr: body matches "^[^ Z]+Z"
        output: parser-containerd
      type: router
    - id: parser-crio
      output: extract_metadata_from_filepath
      regex: ^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
      timestamp:
        layout: "2006-01-02T15:04:05.000000000-07:00"
        layout_type: gotime
        parse_from: attributes.time
      type: regex_parser
    - id: parser-containerd
      output: extract_metadata_from_filepath
      regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: attributes.time
      type: regex_parser
    - id: parser-docker
      output: extract_metadata_from_filepath
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: attributes.time
      type: json_parser
    - id: extract_metadata_from_filepath
      parse_from: attributes["log.file.path"]
      regex: ^.*/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)/(?P<container_name>[^\._]+)/(?P<restart_count>\d+)\.log$
      type: regex_parser
    - from: attributes.stream
      to: attributes["log.iostream"]
      type: move
    - from: attributes.container_name
      to: resource["k8s.container.name"]
      type: move
    - from: attributes.namespace
      to: resource["k8s.namespace.name"]
      type: move
    - from: attributes.pod_name
      to: resource["k8s.pod.name"]
      type: move
    - from: attributes.restart_count
      to: resource["k8s.container.restart_count"]
      type: move
    - from: attributes.uid
      to: resource["k8s.pod.uid"]
      type: move
    - from: attributes.log
      to: body
      type: move
    - parse_from: body
      parse_to: attributes
      type: json_parser
    start_at: beginning
  jaeger:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:14250
      thrift_compact:
        endpoint: ${env:MY_POD_IP}:6831
      thrift_http:
        endpoint: ${env:MY_POD_IP}:14268
  k8s_events:
    auth_type: serviceAccount
  kubeletstats:
    auth_type: serviceAccount
    collection_interval: 20s
    endpoint: ${K8S_NODE_NAME}:10250
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
      http:
        endpoint: ${env:MY_POD_IP}:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: node
        metric_relabel_configs:
        - replacement: dev
          target_label: cluster
        - replacement: scraper
          target_label: type
        scrape_interval: 25s
        static_configs:
        - targets:
          - ${K8S_NODE_NAME}:9101
  zipkin:
    endpoint: ${env:MY_POD_IP}:9411
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    logs:
      exporters:
      - logging
      - otlp
      processors:
      - k8sattributes
      - memory_limiter
      - batch
      receivers:
      - k8s_events
      - otlp
      - filelog
    metrics:
      exporters:
      - logging
      - otlp
      processors:
      - k8sattributes
      - memory_limiter
      - batch
      receivers:
      - otlp
      - prometheus
      - kubeletstats
    traces:
      exporters:
      - logging
      processors:
      - k8sattributes
      - memory_limiter
      - batch
      receivers:
      - otlp
      - jaeger
      - zipkin
  telemetry:
    logs:
      level: debug
    metrics:
      address: ${env:MY_POD_IP}:8888
```

Here is my otel gateway config

```yaml
exporters:
  elasticsearch/logv2:
    endpoints:
    - ES_ENDPOINT
    logs_dynamic_index:
      enabled: true
    logs_index: otel-logs-dev-
    password: $ELASTIC_PASSWORD_V2
    user: $ELASTIC_USER_V2
  logging: {}
  otlp/o11yv2:
    endpoint: APM_ENDPOINT
    tls:
      insecure_skip_verify: true
  prometheusremotewrite:
    auth:
      authenticator: sigv4auth
    endpoint: PROMETHEU_ENDPOINT
    resource_to_telemetry_conversion:
      enabled: true
    timeout: 30s
extensions:
  health_check: {}
  memory_ballast:
    size_in_percentage: 40
  sigv4auth:
    region: us-east-1
    service: aps
processors:
  attributes:
    actions:
    - action: insert
      key: cluster
      value: dev
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:14250
      thrift_compact:
        endpoint: ${env:MY_POD_IP}:6831
      thrift_http:
        endpoint: ${env:MY_POD_IP}:14268
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
        max_recv_msg_size_mib: 100
      http:
        endpoint: ${env:MY_POD_IP}:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        metric_relabel_configs:
        - replacement: dev
          target_label: cluster
        - replacement: gateway
          target_label: type
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${MY_POD_IP}:8888
  zipkin:
    endpoint: ${env:MY_POD_IP}:9411
service:
  extensions:
  - sigv4auth
  - health_check
  pipelines:
    logs:
      exporters:
      - logging
      - elasticsearch/logv2
      processors:
      - memory_limiter
      - batch
      - attributes
      receivers:
      - otlp
    metrics:
      exporters:
      - logging
      - prometheusremotewrite
      processors:
      - memory_limiter
      - batch
      - attributes
      receivers:
      - otlp
      - prometheus
    traces:
      exporters:
      - logging
      - otlp/o11yv2
      processors:
      - memory_limiter
      - batch
      - attributes
      receivers:
      - otlp
      - jaeger
      - zipkin
  telemetry:
    metrics:
      address: ${env:MY_POD_IP}:8888
```

Right now i have set scrape interval to 25 seconds, but in grafana i see metrics uploaded every 15 seconds, with duplicates
![Screenshot 2023-06-22 at 14 41 33](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/9252594/6b408ea3-f7f1-4085-97ce-71b020aa2543)

I would expect metrics interval to be equal 25 seconds and not 15. Besides that i have separate otel which doing just scraping and sending data to otel gateway, but again all metrics are written with 15 sec interval

**Comment by ilia-medvedev-codefresh** [comment]
I'm using target allocator with Prometheus CRD's and noticed that when the the scrape interval is set on the ServiceMonitors the scrape interval works - but when setting it under global config it doesn't work
```
receivers:
    prometheus:
      config:
        global:
          evaluation_interval: 60s
          scrape_interval: 60s
          scrape_timeout: 60s
```
