### ISSUE TITLE
otelcol_processor_tail_sampling_sampling_traces_on_memory is only incrementing, it is not a gauge

### ISSUE THREAD

**Issue by utezduyar** [open-telemetry/opentelemetry-collector-contrib#23648]
### Component(s)

processor/tailsampling

## Description
The help text of the metric indicates that it is a gauge. This metric is only increasing, as if it is just the count of spans processed. 

## Steps to Reproduce
Run this collector and send 300 spans. Wait 2 minutes. See the metric is not going down. 
```
# HELP otelcol_processor_tail_sampling_sampling_traces_on_memory Tracks the number of traces current on memory
# TYPE otelcol_processor_tail_sampling_sampling_traces_on_memory gauge
otelcol_processor_tail_sampling_sampling_traces_on_memory{service_instance_id="490bb5de-9af9-4d47-8b16-afb69583fbc7",service_name="otelcol-contrib",service_version="0.79.0"} 300
```

### Collector version

0.79.0

### Environment information

otelcol-contrib_0.79.0_darwin_arm64

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    verbosity: detailed
    sampling_initial: 1000
    sampling_thereafter: 1000

processors:
  batch:
  tail_sampling:
    decision_wait: 60s
    policies:
      [
        {
          name: composite-policy,
          type: composite,
          composite:
            {
              max_total_spans_per_second: 10,
              policy_order: [composite-policy-errors, test-composite-always],
              composite_sub_policy:
                [
                  {
                    name: composite-policy-errors,
                    type: status_code,
                    status_code: {status_codes: [ERROR]}
                  },
                ],
              rate_allocation:
                [
                  {
                    policy: composite-policy-errors,
                    percent: 100
                  },
                ]
            }
        },
        {
          name: test-policy-8,
          type: rate_limiting,
          rate_limiting: {spans_per_second: 2}
        },
#        {
#          name: test-policy-1,
#          type: always_sample
#        },
#        {
#          name: test-policy-5,
#          type: status_code,
#          status_code: {status_codes: [ERROR]}
#        },
#        {
#          name: test-policy-4,
#          type: probabilistic,
#          probabilistic: {sampling_percentage: 50}
#        },
      ]

service:
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      address: ":8888"
  pipelines:
    traces:
      receivers: [otlp]
      #processors: [batch, tail_sampling]
      processors: [tail_sampling]
      exporters: [logging]
```
