### ISSUE TITLE
Support random sampling logs without hashing based on any attribute

### ISSUE THREAD

**Issue by chenlujjj** [open-telemetry/opentelemetry-collector-contrib#23652]
### Component(s)

processor/probabilisticsampler

### Is your feature request related to a problem? Please describe.

We are using otel collector and want to sample logs, but some of the logs have no trace id and it's hard to choose a specific log record attribute for hashing and sampling.

It would be great if the `Probabilistic Sampling Processor` can support random sampling logs without hashing based on any attribute.

### Describe the solution you'd like

Sample logs without hashing of traceId or any log record attributes.

For example, if we want to sample 15% of the logs and set `sampling_percentage ` as 15, we can generate a random number in the range of [0, 100] for each log to process. If the number < 15, then the log is sampled, otherwise dropped.

**Comment by daianmartinho** [comment]
We are looking for something similar.
Use case:
- Logs with severity >=  WARN: 100% sampled
- Logs with severity < WARN: X% sampled


>I started working on a uuid() function in ottl for this

That would be great..  but we may have to handle #18222 for this use case

Example:
```
processors:
  filter/max-info-severity:
    logs:
      log_record:
        - 'severity_number >= SEVERITY_NUMBER_WARN'
  filter/min-warn-severity:
    logs:
      log_record:
        - 'severity_number < SEVERITY_NUMBER_WARN'
  transform/set-log-uuid:
    log_statements:
    - context: log
      statements:
        - set(attributes["uuid"], UUID())
```
```
pipelines:
  logs/max-info-severity:
    receivers:
      - otlp
    processors:
      - filter/max-info-severity
      - transform/set-log-uuid
      - probabilistic_sampler/logs
    exporters:
      - logging
  
  logs/min-warn-severity:
    ...
```
