### ISSUE TITLE
[exporter/clickhouse] create database fail

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#23664]
### Component(s)

exporter/clickhouse

## Description
OTel collector can't start with clickhouse exporter when the database doesn't exist.  error log:
```
Error: cannot start pipelines: create database:code: 81, message: Database otel doesn't exist; failed to shutdown pipelines: no existing monitoring routine is running; no existing monitoring routine is running
2023/06/25 17:25:35 collector server run finished with error: cannot start pipelines: create database:code: 81, message: Database otel doesn't exist; failed to shutdown pipelines: no existing monitoring routine is running; no existing monitoring routine is running
```

I found that 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/da5df85e77bb717e87096c20663ddc8bbb5ebf8a/exporter/clickhouseexporter/exporter_logs.go#L181-L200
The `createDatabase()` needs `buildDB()` to replace the origin database to `defaultDatabase`(e.g. `tcp://127.0.0.1:9000/otel` to `tcp://127.0.0.1:9000/default`) however `cfg.buildDB` doesn't cover that.

### Collector version

latest

### OpenTelemetry Collector configuration

```yaml
receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  batch:
    send_batch_size: 100000
    timeout: 5s
  memory_limiter:
    check_interval: 2s
    limit_mib: 1800
    spike_limit_mib: 500
  resourcedetection/system:
    detectors: [ "system" ]
    system:
      hostname_sources: [ "os" ]
  resource:
    attributes:
      - key: service.name
        value: "serviceName"
        action: upsert
exporters:
  clickhouse:
    endpoint: tcp://172.0.0.1:9000
    database: otel
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    ttl_days: 3
    timeout: 10s
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
extensions:
  health_check:
  pprof:
  zpages:
  memory_ballast:
    size_mib: 1000

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    logs:
      receivers: [ fluentforward, otlp ]
      processors: [ memory_limiter, resourcedetection/system, resource, batch ]
      exporters: [ clickhouse ]
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, resourcedetection/system, resource, batch ]
      exporters: [ clickhouse ]
```

### Log output

```shell
Error: cannot start pipelines: create database:code: 81, message: Database otel doesn't exist; failed to shutdown pipelines: no existing monitoring routine is running; no existing monitoring routine is running
2023/06/25 17:25:35 collector server run finished with error: cannot start pipelines: create database:code: 81, message: Database otel doesn't exist; failed to shutdown pipelines: no existing monitoring routine is running; no existing monitoring routine is running
```
