### ISSUE TITLE
[processor/transform] not enough preconditions to guard against warnings

### ISSUE THREAD

**Issue by ajsaclayan** [open-telemetry/opentelemetry-collector-contrib#23847]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

I have a transform processor configured to truncate log attributes and the body field:

```yaml
  transform/newrelic:
    log_statements:
      - context: resource
        statements:
          - truncate_all(attributes, 4090)
      - context: log
        statements:
          - truncate_all(attributes, 4090)
          - set(body, Substring(body.string, 0, 4090))
```
This works, but the problem is when we send a `body` whose length is less than 4090 this warning message occurs:
`invalid range for substring function, 4090 cannot be greater than the length of target string`

### Describe the solution you'd like

It would be nice to be able to have a precondition like `WHERE body.Length() > 4090` to be able to guard against this warning.

**Comment by jack-berg** [comment]
Another alternative would be to adjust allow `truncate` to be called on on `body` when its an AnyValue string. Right now, calling `truncate_all(body, 4090)` errors with:
```
failed to execute statement: truncate_all(body, 4095), expected pcommon.Map but got string"}
```
Definitely useful to have some way to truncate string log bodies in the transform processor.

**Comment by TylerHelmuth** [comment]
Both suggestions sound valuable.

It would be good to have a way to check the lengths of things (string, maps, slices, etc).  It would also be good to have a function that can truncate strings.

In the meantime, this will work and will not cause a warning when `len(body)` is less than 4090:

```yaml
transform/newrelic:
    log_statements:
      - context: resource
        statements:
          - truncate_all(attributes, 4090)
      - context: log
        statements:
          - truncate_all(attributes, 4090)
          - set(cache["body"], body)
          - truncate_all(cache, 4090)
          - set(body, cache["body"])
```

**Comment by TylerHelmuth** [comment]
@ajsaclayan @jack-berg @danelson is this something you'd like to work on?

**Comment by TylerHelmuth** [comment]
Technically more efficient solution:

```yaml
transform/newrelic:
    log_statements:
      - context: resource
        statements:
          - truncate_all(attributes, 4090)
      - context: log
        statements:
          - set(attributes["truncate-body"], body)
          - truncate_all(attributes, 4090)
          - set(body, attributes["truncate-body"])
          - delete_key(attributes, "truncate-body")
```

But won't be viable if `truncate-body` already exists in `attributes` as you'd be overwriting the value.
