### ISSUE TITLE
Clarify ordering of k8sattributes processor in the presence of tail_sampling

### ISSUE THREAD

**Issue by gebn** [open-telemetry/opentelemetry-collector-contrib#23870]
### Component(s)

processor/k8sattributes, processor/tailsampling

## Description

The [recommended][] order of collectors is:

> 1. [memory_limiter](https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md)
> 2. _any sampling processors_
> 3. Any processor relying on sending source from Context (e.g. k8sattributes)
> 4. [batch](https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/README.md)
> 5. _any other processors_

[recommended]: https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/README.md#recommended-processors

When using both `k8sattributes` and `tail_sampling` processors, if `k8sattributes` appears _after_ `tail_sampling`, it will not be able to determine the source IP of spans ([`connectionIP(ctx)`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.80.0/processor/k8sattributesprocessor/pod_association.go#L101) returns `""`), and enrichment will fail.

## Steps to Reproduce

Create a traces pipeline containing `tail_sampling` followed by `k8sattributes`.

## Expected Result

Traces are enriched with pod metadata.

## Actual Result

No enrichment happens due to the pod identifier incorrectly coming back as blank:

```
2023-06-29T15:20:32.747Z        debug   k8sattributesprocessor@v0.80.0/processor.go:102 evaluating pod identifier       {"kind": "processor", "name": "k8sattributes/<name>", "pipeline": "traces/internal", "value": [{"Source":{"From":"", "Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""}]}
```

### Collector version

v0.80.0

### Environment information

The official 0.80.0 Docker image.

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:

processors:
  tail_sampling:
    policies:
    - type: rate_limiting
      rate_limiting:
        spans_per_second: 100

  k8sattributes:
    filter:
      namespace: <snipped>

exporters:
  logging:

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - tail_sampling
      - k8sattributes
      exporters:
      - logging
```
