### ISSUE TITLE
Counter64 not a supported type

### ISSUE THREAD

**Issue by bobbled** [open-telemetry/opentelemetry-collector-contrib#23897]
### Component(s)

receiver/snmp

## Description
snmpreceiver does not support collecting counter64 values.
## Steps to Reproduce
Attempt to collect counter64 values with snmpreceiver.
## Expected Result
counter64 objects are handled as int's and passed through the pipeline.
## Actual Result
counter64 objects are treated as unsupported types.

### Collector version

0.80.0

## Environment
OS: Ubuntu 20.04 (kubernetes)

### OpenTelemetry Collector configuration

```yaml
receivers:
  snmp/test:
    endpoint: udp://10.1.1.1:161
    version: v2c
    community: public
    metrics:
      ipSystemStatsHCInReceives:
        unit: "By"
        sum:
          aggregation: cumulative
          monotonic: false
          value_type: int
        scalar_oids:
          - oid: "1.3.6.1.2.1.4.31.1.1.4.1"
exporters:
  logging:
    loglevel: debug
service:
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [snmp/test]
      processors: []
      exporters: [logging]
```

### Log output

```shell
2023-07-03T16:04:48.309Z    error    scraperhelper/scrapercontroller.go:213    Error scraping metrics    {"kind": "receiver", "name": "snmp/test", "data_type": "metrics", "error": "problem with getting scalar data: data for OID '.1.3.6.1.2.1.4.31.1.1.4.1' not a supported type", "scraper": "snmp"}
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
    go.opentelemetry.io/collector/receiver@v0.80.0/scraperhelper/scrapercontroller.go:213
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
go.opentelemetry.io/collector/receiver@v0.80.0/scraperhelper/scrapercontroller.go:192
```

### Additional context

This may have been left out deliberately for some reason I can't see.  It looks like it may have been an oversight, however.

The [relevant line](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4c817c69a2fe9cab7f1a9c357a84eff7a40b7fe7/receiver/snmpreceiver/client.go#L330) in the snmp receiver that lacks counter64 support.

The [gosnmp const](https://github.com/gosnmp/gosnmp/blob/f30602b8dad6f413fc2ca4bf680f6952594ad1e1/gosnmp.go#L225).
