### ISSUE TITLE
cannot use routingprocessor.NewFactory() as exporter.Factory, does not implement exporter.Factory.CreateLogsExporter

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#23983]
### Component(s)

exporter/azuredataexplorer, processor/routing

### What happened?

Using ocb builder which uses a router processor to push logs towards either or azure adx  cluster dependent on service attribute.
ocb build fails.

------

```
dist:
  name: otelcollector
  version: "0.2.0"
  otelcol_version: "0.80.0"
  include_core: true
  output_path: bin
  debug_compilation: false
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.80.0
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver  v0.80.0 # beta
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.80.0 # alpha  
processors:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.80.0 # beta  
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.80.0 # beta  
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.80.0 # alpha
contrib/tree/main/processor/resourcedetectionprocessor#resource-detection-processor
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.80.0 # beta
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.80.0 # beta  
otelcol/tree/ab7ac790b11e0e21bd36f6afd69ac781366a794c/processors/authenticationprocessor
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.80.0 # stable
exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.80.0 # stable
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/azuredataexplorerexporter v0.80.0 # beta
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor  v0.80.0 # beta
connectors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.80.0 # alpha
extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.80.0 # beta 
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.80.0 # beta  
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.80.0 # beta
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.80.0 # beta   
replaces:
  # Datadog Exporter causing the dependency issue - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23425#issuecomment-1595557595
  - google.golang.org/genproto => google.golang.org/genproto v0.0.0-20230530153820-e85fd2cbaebc
```

### Collector version

0.80.0

## Environment
Ubuntu 22.04
go 1.20.5 

### OpenTelemetry Collector configuration

```yaml
# container ports exposed:
#ports:
#  - "1888:1888"   # pprof extension
#  - "13133:13133" # health_check extension
#  - "4317:4317"   # OTLP gRPC receiver
#  - "4318:4318"   # OTLP HTTP receiver
#  - "55670:55679" # zpages extension
extensions:
  # zPages extension enables in-process diagnostics
  zpages:
    endpoint: "localhost:55679"
  # Health Check extension responds to health check requests
  health_check:
    endpoint: localhost:8081 # health check result is pushed to 8081 port and this is referred in livenessProbe of the collector app
  memory_ballast:
    size_mib: 512    
  # PProf extension allows fetching Collector's performance profile
  #https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/pprofextension
  pprof:
    endpoint: "localhost:1777"
  #  block_profile_fraction: 3
  #  mutex_profile_fraction: 5
receivers:
  hostmetrics:
    collection_interval: 10s # The hostmetrics receiver is required to get correct infrastructure metrics in Datadog.
    scrapers:
      paging: 
        metrics:
          system.paging.utilization:
            enabled: true # This metric is required to get correct infrastructure metrics in Datadog.
      cpu:
        metrics:
          system.cpu.utilization:
             enabled: true # This metric is required to get correct infrastructure metrics in Datadog.
      memory:
      load:
        cpu_average: true
      network:
        #<include|exclude>:
        #  interfaces: [ <interface name>, ... ]
        #  match_type: <strict|regexp>
      process:
        #<include|exclude>:
        #  names: [ <process name>, ... ]
        #  match_type: <strict|regexp>
        # https://github.com/open-telemetry/opentelemetry-collector/issues/3004
        mute_process_name_error: false
        mute_process_exe_error: false
        mute_process_io_error: false
        #scrape_process_delay: <time>      
  hostmetrics/disk:
    collection_interval: 3m
    scrapers:
      disk: # This metric is required to get correct infrastructure metrics in Datadog.
        #<include|exclude>:
        #  devices: [ <device name>, ... ]
        #  match_type: <strict|regexp>
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true # This metric is required to get correct infrastructure metrics in Datadog.
        #<include_devices|exclude_devices>:
        #  devices: [ <device name>, ... ]
        #  match_type: <strict|regexp>
        #<include_fs_types|exclude_fs_types>:
        #  fs_types: [ <filesystem type>, ... ]
        #  match_type: <strict|regexp>
        #<include_mount_points|exclude_mount_points>:
        #  mount_points: [ <mount point>, ... ]
        #  match_type: <strict|regexp>      
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

  # scrape collector's own metrics and push
  prometheus/otelcol:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']
processors:
  # https://github.com/observatorium/observatorium-otelcol/tree/ab7ac790b11e0e21bd36f6afd69ac781366a794c/processors/authenticationprocessor
  #plugin processor for token oauth ?


  # detect docker env 
  # To detect resource information from the host, Otel Collector comes with resourcedetection processor.
  # Resource Detection Processor automatically detects and labels metadata about the environment in which the data was generated.
  # Such metadata, known as "resources", provides context to the telemetry data and can include information such as the host, service,
  # container, and cloud provider.
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor
  resourcedetection: # Queries the host machine to retrieve the following resource attributes: host.name, host.id, os.type,
    detectors: [env, system, docker, azure]
    timeout: 10s
    override: false
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.80.0/processor/cumulativetodeltaprocessor  
  cumulativetodelta:
  batch/metrics:
    # Datadog APM Intake limit is 3.2MB. Let's make sure the batches do not go over that.
    send_batch_max_size: 1000 # (default = 8192): Maximum batch size of spans to be sent to the backend. The default value is 8192 spans.
    send_batch_size: 100 # (default = 512): Maximum number of spans to process in a batch. The default value is 512 spans.
    timeout: 10s # (default = 5s): Maximum time to wait until the batch is sent. The default value is 5s.
  batch/traces:
    send_batch_max_size: 1000 # (default = 8192): Maximum batch size of spans to be sent to the backend. The default value is 8192 spans.
    send_batch_size: 100 # (default = 512): Maximum number of spans to process in a batch. The default value is 512 spans.
    timeout: 5s # (default = 5s): Maximum time to wait until the batched traces are sent. The default value is 5s.
  batch/logs:
    send_batch_max_size: 1000 # (default = 8192): Maximum batch size of spans to be sent to the backend. The default value is 8192 spans.
    send_batch_size: 100 # (default = 512): Maximum number of spans to process in a batch. The default value is 512 spans.
    timeout: 30s # (default = 5s): Maximum time to wait until the batched logs are sent. The default value is 5s.
  attributes:
    actions:
      - key: tags
        value: ["DD_ENV:${env:ENVIRONMENT}", "geo:${env:GEO}"]
        action: upsert
  resource:
    attributes:
      - key: DD_ENV
        value: ${env:ENVIRONMENT}
        action: upsert
      - key: env
        value: ${env:ENVIRONMENT}
        action: upsert
      - key: geo
        value: ${env:GEO} # china, emea, amap
        action: upsert
  routing:
    from_attribute: service
    attribute_source: context
    default_exporters:
    - azuredataexplorer/unrouted
    table:
    - value: micotelcollector
      exporters: [azuredataexplorer/emeadev]
    - value: micotelgateway
      exporters: [azuredataexplorer/emeadev]
connectors:
  # get metrics about the  collector traces by connecting trace exporter to metric receiver producing trace collector metrics
  spanmetrics:
  #  histogram:
  #    explicit:
  #      buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
  #  dimensions:
  #    - name: http.method
  #      default: GET
  #    - name: http.status_code
  #  dimensions_cache_size: 1000
  #  aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"

exporters:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter
  datadog:
    api:
      site: datadoghq.com
      key: ${env:DATADOG_API_KEY}
    #tls:
    #  insecure_skip_verify: true
    metrics:
      resource_attributes_as_tags: true
    host_metadata:
      enabled: true
      tags: ["DD_ENV:${env:ENVIRONMENT}", "geo:${env:GEO}", "region:${env:REGION}"]
      #tags: ["DD_SERVICE:${env:APP_NAME}", "DD_VERSION:${env:APP_VERSION}", "fqin:${env:APP_NAME}", "geo:${env:GEO}", "region:${env:REGION}", "release_name:${env:APP_NAME}", "service:${env:APP_NAME}", "key:${env:APP_ID}", "hostname:"]
  # this exporter is used for logs in ownership of en2ned monitoring, like logs from collector and or gateway    
  azuredataexplorer/emeadev:
      cluster_uri: "https://XXXXXXXXXXX.westeurope.kusto.windows.net"
      application_id: "XXXXXXXXXXXXXXXXXXXXXXXX"
      application_key: "${ADX_APPREG_SECRET}"
      tenant_id: "${AZURE_TENANT_ID}"
      db_name: "emeadev"
      metrics_table_name: "metrics"
      logs_table_name: "logs"
      traces_table_name: "traces"
      ingestion_type : "managed" # https://learn.microsoft.com/en-us/azure/data-explorer/open-telemetry-connector?tabs=command-line#set-up-streaming-ingestion 
      #otelmetrics_mapping : "<json metrics_table_name mapping>"
      #otellogs_mapping  : "<json logs_table_name mapping>"
      #oteltraces_mapping  : "<json traces_table_name mapping>"
  azuredataexplorer/unrouted:
      cluster_uri: "https://XXXXXXXX.westeurope.kusto.windows.net"
      application_id: "XXXXXXXXXXXXXXXXXXXX"
      application_key: "${ADX_APPREG_SECRET}"
      tenant_id: "${AZURE_TENANT_ID}"
      db_name: "unrouted"
      metrics_table_name: "metrics"
      logs_table_name: "logs"
      traces_table_name: "traces"
      ingestion_type : "managed" # https://learn.microsoft.com/en-us/azure/data-explorer/open-telemetry-connector?tabs=command-line#set-up-streaming-ingestion 
      #otelmetrics_mapping : "<json metrics_table_name mapping>"
      #otellogs_mapping  : "<json logs_table_name mapping>"
      #oteltraces_mapping  : "<json traces_table_name mapping>"
    logging:
      logLevel: info

service:
  extensions: [pprof, zpages, health_check,memory_ballast]
  telemetry:
    # collect metrics about collector itself
    metrics:
      address: 'localhost:8888'
    # debug if collector is not working
    logs:
      level: 'info'
  pipelines:
    #The ballast should be configured to be 1/3 to 1/2 of the memory allocated to the collector.
    traces:
      receivers: [otlp]
      processors: [batch/traces,attributes, resource]
      exporters: [datadog, spanmetrics]
    metrics/hostmetrics:
      receivers: [spanmetrics,otlp]
      processors: [batch/metrics, attributes, resource]
      exporters: [datadog]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch/metrics,attributes, resource]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [routing,batch/logs,attributes]
      exporters: [azuredataexplorer/emeadev,azuredataexplorer/unrouted]
```

### Log output

```shell
> [build 11/11] RUN ocb --config /workspace/builder.yaml:
#18 0.405 2023-07-05T09:01:57.895Z	INFO	internal/command.go:115	OpenTelemetry Collector Builder	{"version": "0.80.0", "date": "2023-06-20T19:29:20Z"}
#18 0.417 2023-07-05T09:01:57.904Z	INFO	internal/command.go:148	Using config file	{"path": "/workspace/builder.yaml"}
#18 0.417 2023-07-05T09:01:57.904Z	INFO	builder/config.go:105	Using go	{"go-executable": "/usr/local/go/bin/go"}
#18 0.417 2023-07-05T09:01:57.907Z	INFO	builder/main.go:65	Sources created	{"path": "bin"}
#18 132.9 2023-07-05T09:04:10.[425](https://gitlab.com/Mercedes-Intelligent-Cloud/mic-monlog/mic-otel-gateway/-/jobs/4595588176#L425)Z	INFO	builder/main.go:117	Getting go modules
#18 135.6 2023-07-05T09:04:13.116Z	INFO	builder/main.go:76	Compiling
#18 1406.1 Error: failed to compile the OpenTelemetry Collector distribution: exit status 1. Output:
#18 1406.1 # gitlab.com/otelcollector
#18 1406.1 ./components.go:57:3: cannot use routingprocessor.NewFactory() (value of type processor.Factory) as exporter.Factory value in argument to exporter.MakeFactoryMap: processor.Factory does not implement exporter.Factory (missing method CreateLogsExporter)
#18 1406.1 
```
```


### Additional context

_No response_
