### ISSUE TITLE
filelog receiver sets nil log body after removing body field

### ISSUE THREAD

**Issue by rupeshnemade** [open-telemetry/opentelemetry-collector-contrib#24017]
### Component(s)

receiver/filelog

## Description
When we removes body from the log field with filelog receiver and renames it then the converter renders the key value as Nil.
It's expected that if the value is Nil then key should not appear at all.

## Steps to Reproduce
Use filelog receiver to read logs from a file with regex parser and rules as below-
`          filelog/auditlog:
            include:
            - /var/log/audit/audit.log
            operators:
            - type: regex_parser
              regex: '^(?P<message>.*)$'
            - from: attributes.message
              to: attributes["message"]
              type: move
            - field: body
              type: remove`

## Expected Result
`log` field should not appear in output.

## Actual Result
Getting Nil log field.
<img width="866" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/31383439/b9b171ed-1e3d-4544-a90f-510e1b1dd775">

### Collector version

v0.80.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  logging:
    verbosity: detailed
receivers:
  filelog/auditlog:
    include:
      - /var/log/audit/audit.log
    operators:
      - type: regex_parser
        regex: '^(?P<message>.*)$'
      - from: attributes.message
        to: attributes["message"]
        type: move
      - field: body
        type: remove
service:
  pipelines:
    logs/kernel:
      exporters:
        - logging
      processors:
        - batch
      receivers:
        - filelog/authlog
```

### Log output

```shell
Body: Str(<nil>)
Attributes:
     -> message: Str(kubelet: E0706 11:32:21.943440    4715 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"0d4cf341-424f-462c-a50a-406ac8f66331\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=5)
```
