### ISSUE TITLE
Docker API version float64

### ISSUE THREAD

**Issue by b0kky** [open-telemetry/opentelemetry-collector-contrib#24025]
### Component(s)

receiver/dockerstats

## Description
Docker API  with round versions (1.20, 1.30, 1.40, etc)   converted to 1.2, 1.3, 1.4 etc
## Steps to Reproduce
Enable dockerstatreceiver and set round  api_version , for example 1.40:
```receivers:
    docker_stats:
        api_version: 1.40
```
## Expected Result
This config will set api_version as expected: 1.40

## Actual Result
opentelemetry restarting with error:
>Error: cannot start pipelines: Error response from daemon: client version 1.4 is too old. Minimum supported API version is >1.12, please upgrade your client to a newer version

At docker documentation described version, and you can see "round" version : 1.20, 1.30 etc.
https://docs.docker.com/engine/api/#api-version-matrix

### Collector version

0.80.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
data:
      receivers:
        docker_stats:
          endpoint: unix:///var/run/docker.sock
          collection_interval: 10s
          timeout: 20s
          api_version: 1.40
-----------
          metrics:
            receivers:
              - docker_stats
            processors:
              - batch
              - metricstransform
            exporters:
              - prometheus
```

### Log output

```shell
Error: cannot start pipelines: Error response from daemon: client version 1.4 is too old. Minimum supported API version is 1.12, please upgrade your client to a newer version
```

### Additional context

In a source receiver/dockerstatsreceiver/config.go ,  set 
```go
`DockerAPIVersion float64 `mapstructure:"api_version"
``` 
While uses float64, 1.40 will convert to 1.4
```bash
$ python -c 'print(float(1.40))'
1.4
```
