### ISSUE TITLE
[resourceprocessor] share atrribute data between resource attribte and span/log/metrics attributes

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#24022]
### Component(s)

processor/attributes, processor/resource

### Is your feature request related to a problem? Please describe.

The two processors have the power ability to modify their attributes of themselves but, can't apply the ability between them, 
e.g. I want to move a key value from the span attribute to its resource attribute, 

### Describe the solution you'd like

giving an option to tell resourceprocessor it will fetch data from span/log/metrics attribute instead of itself attribute when using `from_attribute` for the actions `insert`, `update`, and `upsert`

resourceprocessor config:
```
processors:
  resource:
    attributes:
    - key: k8s.cluster.name
      from_attribute: k8s-cluster
      use_attribute: true
      action: insert
```

The same as attributeprocessor, the config will look like:
```
processors:
  attributes/example:
    actions:
    - key: k8s.cluster.name
      from_attribute: k8s-cluster
      use_resource_attribute: true
      action: insert
```

### Additional context

In our scenes, we want to standardize the resource attributes map like: `k8s.namespace.name`, `k8s.pod.name`, `service.name` however istio trace only supports generating those in span attribute, we need to move them to resource attribute.

**Comment by mar4uk** [comment]
Hey! To move the attribute to the resource attribute you can use [groupbyattrsprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor)
```
processors:
  groupbyattrs:
    keys:
      - k8s.namespace.name
      - k8s.pod.name
      - service.name
```
