### ISSUE TITLE
Incorrect system.memory.usage:free values

### ISSUE THREAD

**Issue by ItsLastDay** [open-telemetry/opentelemetry-collector-contrib#24031]
### Component(s)

receiver/hostmetrics

## Description

We're using OpenTelemetry Collector, some of the metrics that we export are "VM memory usage, free and total". Our customer noticed that the metric value for "free memory" is inconsistent with the other two: https://pasteboard.co/vop8kWDatOPY.png.

## Steps to Reproduce

I haven't came up with a reliable test yet. 

## Expected Result

I would expect that if the graph for "free" memory goes down, then the graph for "used" memory goes up. 

## Actual Result

The "free" memory goes down, but "used" memory stays the same: https://pasteboard.co/vop8kWDatOPY.png. As if something was consuming "free" memory without being reflected in "used".

### Collector version

0.80.0

## Environment
OS: cos_105_17412.101.37 (https://cloud.google.com/container-optimized-os/docs)
Compiler: go 1.20.3

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics/memory:
    collection_interval: 5s
    scrapers:
      memory:

exporters:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

processors:
  filter/hostmetrics_after_transform:
    metrics:
      include:
        match_type: strict
        metric_names:
        - "instance/vm/memory/usage"
        - "instance/vm/memory/free"

  metricstransform/hostmetrics_memory:
    transforms:
    - include: system.memory.usage
      action: insert
      new_name: "instance/vm/memory/usage"
      operations:
      - action: delete_label_value
        label: state
        label_value: cached
      - action: delete_label_value
        label: state
        label_value: buffered
      - action: delete_label_value
        label: state
        label_value: inactive
      - action: delete_label_value
        label: state
        label_value: free
      - action: delete_label_value
        label: state
        label_value: slab_reclaimable
      - action: delete_label_value
        label: state
        label_value: slab_unreclaimable
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum

    - include: system.memory.usage
      action: insert
      new_name: "instance/vm/memory/free"
      operations:
      - action: delete_label_value
        label: state
        label_value: cached
      - action: delete_label_value
        label: state
        label_value: buffered
      - action: delete_label_value
        label: state
        label_value: inactive
      - action: delete_label_value
        label: state
        label_value: used
      - action: delete_label_value
        label: state
        label_value: slab_reclaimable
      - action: delete_label_value
        label: state
        label_value: slab_unreclaimable
      - action: aggregate_labels
        label_set: []
        aggregation_type: sum

service:
  pipelines:
    metrics/hostmetrics_memory:
      receivers: [hostmetrics/memory]
      processors: [metricstransform/hostmetrics_memory,
              filter/hostmetrics_after_transform]
      exporters: [logging]
```

### Log output

```shell
https://pastebin.com/4A538YvN
```

### Additional context

I looked at the code, and IMO here's what's happening:
1. On a high level, memory scraper defines `system.memory.usage` metric with different labels: ``buffered``, ``cached``, ``inactive``, ``free``, ``slab_reclaimable``, ``slab_unreclaimable``, ``used``. [code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.81.0/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/documentation.md?plain=1#L29C53-L29C157).
2. In memory scraper implementation, we use "github.com/shirou/gopsutil/v3/mem": [code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.81.0/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper.go#L55). This happens regardless of the system: Linux, Windows, others
3. Then we pass `mem.VirtualMemoryStat` to handlers of specific systems: Linux, Windows, others. E.g. [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.81.0/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_linux.go#L17) is code for Linux. It reads certain fields of `VirtualMemoryStat`
4. To produce `system.memory.usage` value for label `free`, we use `memInfo.Free`: [Linux](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.81.0/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_linux.go#L18), [Windows](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.81.0/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_windows.go#L18C44-L18C44), [others](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.81.0/receiver/hostmetricsreceiver/internal/scraper/memoryscraper/memory_scraper_others.go#L18C44-L18C44)
5. `gopsutil/v3/mem`'s documentation for `VirtualMemoryStat` says that `Free` is kernel's notion of free memory, and human-readable value is in `Available`: [code](https://github.com/shirou/gopsutil/blob/v3.23.6/mem/mem.go#L34-L37)
6. I looked at the Linux-specific code of `gopsutil`: [code](https://github.com/shirou/gopsutil/blob/042e63609b4e22a95b6201d48c874b62a976d133/mem/mem_linux.go#L88-L100). It fetches `MemAvailable` and `MemFree`, which are documented in https://www.kernel.org/doc/Documentation/filesystems/proc.txt. The documentation is very different for those two values.

So, in total, I believe that I'm seeing a glitch in `free` memory graph, because it is not meant to be human-readable :) I believe that we should use `Available` instead of `Free` throughout memory scraper code. I'll prepare a pull request, though I don't yet know how to test it.
