### ISSUE TITLE
[exporter/prometheusexporter] There are errors with prometheusexporter in otel collector log messages

### ISSUE THREAD

**Issue by xwgao** [open-telemetry/opentelemetry-collector-contrib#24054]
### Component(s)

exporter/prometheus

## Description
I'm using prometheusexporter in my otel collector. I found the below errors with prometheusexporter in otel collector log messages.
```
2023-07-07T07:05:56.702Z	error	prometheusexporter@v0.80.0/log.go:23	error gathering metrics: collected metric "http_server_active_requests" { label:{name:"http_method" value:"GET"} label:{name:"http_scheme" value:"https"} label:{name:"job" value:"mas811-api"} label:{name:"net_host_name" value:"10.254.24.116"} label:{name:"net_host_port" value:"9443"} gauge:{value:0} timestamp_ms:1688713513547} was collected before with the same name and label values
	{"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.80.0/log.go:23
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
	github.com/prometheus/client_golang@v1.16.0/prometheus/promhttp/http.go:144
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2122
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2500
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
	go.opentelemetry.io/collector/config/confighttp@v0.80.0/compression.go:111
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2122
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
	go.opentelemetry.io/collector/config/confighttp@v0.80.0/clientinfohandler.go:28
net/http.serverHandler.ServeHTTP
	net/http/server.go:2936
net/http.(*conn).serve
	net/http/server.go:1995
```
I'm using auto-instrumentation for Java for my service, the instrumentation image is ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.26.0.

## Steps to Reproduce
Use prometheusexporter in otel collector config. After otel collector pod is running, can find the error messages from the otel collector pod log.

## Expected Result
There is no error with prometheusexporter found in otel collector log messages.

## Actual Result
Found errors with prometheusexporter in otel collector log messages.

### Collector version

0.80.0

## Environment
OpenShift 4.12.16

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
          http:
      otlp/spanmetrics:
        protocols:
          grpc:
            endpoint: 0.0.0.0:12346

    processors:
      attributes/delete:
        actions:
          - key: "http.target"
            action: delete
      batch:
        timeout: 10s
        send_batch_size: 10000
      metricstransform:
        transforms:
          - include: mas-optimizer.duration
            match_type: strict
            action: insert
            experimental_match_labels: {
              "service.name": "mas811-api",
              "span.name": "POST /jobs"
            }
            new_name: mas-optimizer.api_create_job_duration_seconds

    exporters:
      logging:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:8889"
        send_timestamps: true
        metric_expiration: 1440m

    connectors:
      spanmetrics:
        namespace: mas-optimizer
        histogram:
          unit: s
          explicit:
            buckets: [10ms, 100ms, 200ms, 400ms, 800ms, 1s, 1200ms, 1400ms, 1600ms, 1800ms, 2s, 4s, 6s, 8s, 10s, 20s, 30s]
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: http.url
          - name: http.route
          - name: http.host

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, attributes/delete]
          exporters: [spanmetrics, logging]
        metrics:
          receivers: [otlp, otlp/spanmetrics, spanmetrics]
          processors: [batch, metricstransform]
          exporters: [prometheus, logging]
```

### Log output

```shell
2023-07-07T07:05:56.702Z	error	prometheusexporter@v0.80.0/log.go:23	error gathering metrics: collected metric "http_server_active_requests" { label:{name:"http_method" value:"GET"} label:{name:"http_scheme" value:"https"} label:{name:"job" value:"mas811-api"} label:{name:"net_host_name" value:"10.254.24.116"} label:{name:"net_host_port" value:"9443"} gauge:{value:0} timestamp_ms:1688713513547} was collected before with the same name and label values
	{"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.80.0/log.go:23
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
	github.com/prometheus/client_golang@v1.16.0/prometheus/promhttp/http.go:144
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2122
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2500
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
	go.opentelemetry.io/collector/config/confighttp@v0.80.0/compression.go:111
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2122
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
	go.opentelemetry.io/collector/config/confighttp@v0.80.0/clientinfohandler.go:28
net/http.serverHandler.ServeHTTP
	net/http/server.go:2936
net/http.(*conn).serve
	net/http/server.go:1995
```
