### ISSUE TITLE
HostMetrics Logging exporter does not respect the LogLevel / Verbosity for console and Windows Event Viewer

### ISSUE THREAD

**Issue by deadlydog** [open-telemetry/opentelemetry-collector-contrib#24263]
### Component(s)

receiver/hostmetrics

## Description

When using the OTEL Collector's `logging` exporter to report hostmetrics, `info` messages are always written to the console and Windows Event Viewer, even if the `loglevel` is set to `warn` or `error`.

## Steps to Reproduce

1. Download [otelcol-contrib_0.81.0_windows_amd64.tar.gz](https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.81.0/otelcol-contrib_0.81.0_windows_amd64.tar.gz) and extract it on a Windows machine (I used Windows Server 2016).
1. Download the default host-metrics config file [honeycomb-metrics-config.yaml](https://github.com/honeycombio/opentelemetry-collector-configs/releases/download/v1.7.0/honeycomb-metrics-config.yaml).
1. On line 8 of the config file, change the `loglevel` from `info` to `error`:
   ```
   exporters:
     otlp:
       endpoint: api.honeycomb.io:443
       headers:
         x-honeycomb-team: $HNY_API_KEY
         x-honeycomb-dataset: $HNY_DATASET
     logging:
       loglevel: error # Change this from info to error.
   ```
1. In the Processors, comment out the timestamp lines 26 and 27 (as they seem to be invalid config and cause an error):
   ```
   processors:
     resourcedetection:
       detectors:
         - env
         - system
     # timestamp: # Comment this line out.
       # round_to_nearest: 1s # Comment this line out.
   ```
1. In the Services, comment out the timestamp on line 701 and the otlp exporter on line 706, since we don't actually want to send metrics to Honeycomb for this test:
   ```
   service:
     pipelines:
       metrics:
         receivers:
           - hostmetrics
         processors:
           - metricstransform
           - filter
           # - timestamp # Comment this line out.
           - resourcedetection
           - batch
         exporters:
           - logging
           # - otlp # Comment this line out.
   ```
1. Run the service using `otelcol-contrib.exe --config honeycomb-metrics-config.yaml`

You will notice that it continually logs `info` messages with how many logging metrics are being exported, like this:

> 2023-07-13T11:43:15.796-0600    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging",
"resource metrics": 7, "metrics": 43, "data points": 43}

If you install the application as a Windows Service, you will also notice that the `info` messages are also logged to the Windows Event Viewer in the `Application` logs.

You can install the exe as a Windows Service using the following command, adjusting the file paths as needed:

```
sc.exe create OpenTelemetryAgentCollector binPath= "C:\OtelTests\otelcol-contrib_0.81.0_windows_amd64.exe --config C:\OtelTests\honeycomb-metrics-config.yaml" start= auto
```

You will need to manually start the service once it is installed.

## Expected Result

Only errors should be written to the console when running interactively, and to the Event Viewer when running as a Windows Service.

## Actual Result

`info` messages are still written to the console when running interactively, and to the Event Viewer when running as a Windows Service.

## Why this is a problem

This is a problem for us because we don't want the Windows Event Viewer to be constantly spammed with `info` messages, but would still like it to report warnings or errors in there. Currently, our only option is to disable logging completely by commenting out the logging exporter service (line 705 in the config file) so that no events are reported to the console/Event Viewer, which is not ideal.

### Collector version

v0.81.0

## Environment
OS: Windows Server 2016

### OpenTelemetry Collector configuration

```yaml
exporters:
  otlp:
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: $HNY_API_KEY
      x-honeycomb-dataset: $HNY_DATASET
  logging:
    loglevel: error
receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      memory: {}
      cpu: {}
      load: {}
      disk: {}
      filesystem: {}
      network: {}
      paging: {}
      processes: {}
processors:
  resourcedetection:
    detectors:
      - env
      - system
  # timestamp:
    # round_to_nearest: 1s
  batch:
    send_batch_size: 8192
    timeout: 200ms
  metricstransform:
    transforms:
      - include: system.disk.io_time
        action: update
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.weighted_io_time
        action: update
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.pending_operations
        action: update
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: process.cpu.time
        experimental_match_labels:
          state: system
        action: insert
        new_name: process.cpu.time.system
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: process.cpu.time
        experimental_match_labels:
          state: user
        action: insert
        new_name: process.cpu.time.user
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: process.cpu.time
        experimental_match_labels:
          state: wait
        action: insert
        new_name: process.cpu.time.wait
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: process.disk.io
        experimental_match_labels:
          direction: read
        action: insert
        new_name: process.disk.io.read
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: process.disk.io
        experimental_match_labels:
          direction: write
        action: insert
        new_name: process.disk.io.write
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.cpu.time
        experimental_match_labels:
          state: idle
        action: insert
        new_name: system.cpu.time.idle
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.cpu.time
        experimental_match_labels:
          state: interrupt
        action: insert
        new_name: system.cpu.time.interrupt
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.cpu.time
        experimental_match_labels:
          state: nice
        action: insert
        new_name: system.cpu.time.nice
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.cpu.time
        experimental_match_labels:
          state: softirq
        action: insert
        new_name: system.cpu.time.softirq
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.cpu.time
        experimental_match_labels:
          state: steal
        action: insert
        new_name: system.cpu.time.steal
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.cpu.time
        experimental_match_labels:
          state: system
        action: insert
        new_name: system.cpu.time.system
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.cpu.time
        experimental_match_labels:
          state: user
        action: insert
        new_name: system.cpu.time.user
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.cpu.time
        experimental_match_labels:
          state: wait
        action: insert
        new_name: system.cpu.time.wait
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.memory.usage
        experimental_match_labels:
          state: buffered
        action: insert
        new_name: system.memory.usage.buffered
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.memory.usage
        experimental_match_labels:
          state: cached
        action: insert
        new_name: system.memory.usage.cached
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.memory.usage
        experimental_match_labels:
          state: inactive
        action: insert
        new_name: system.memory.usage.inactive
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.memory.usage
        experimental_match_labels:
          state: free
        action: insert
        new_name: system.memory.usage.free
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.memory.usage
        experimental_match_labels:
          state: slab_reclaimable
        action: insert
        new_name: system.memory.usage.slab_reclaimable
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.memory.usage
        experimental_match_labels:
          state: slab_unreclaimable
        action: insert
        new_name: system.memory.usage.slab_unreclaimable
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.memory.usage
        experimental_match_labels:
          state: used
        action: insert
        new_name: system.memory.usage.used
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.io
        experimental_match_labels:
          direction: read
        action: insert
        new_name: system.disk.io.read
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.io
        experimental_match_labels:
          direction: write
        action: insert
        new_name: system.disk.io.write
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.operations
        experimental_match_labels:
          direction: read
        action: insert
        new_name: system.disk.operations.read
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.operations
        experimental_match_labels:
          direction: write
        action: insert
        new_name: system.disk.operations.write
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.operation_time
        experimental_match_labels:
          direction: read
        action: insert
        new_name: system.disk.operation_time.read
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.operation_time
        experimental_match_labels:
          direction: write
        action: insert
        new_name: system.disk.operation_time.write
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.merged
        experimental_match_labels:
          direction: read
        action: insert
        new_name: system.disk.merged.read
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.disk.merged
        experimental_match_labels:
          direction: write
        action: insert
        new_name: system.disk.merged.write
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.filesystem.usage
        experimental_match_labels:
          state: free
        action: insert
        new_name: system.filesystem.usage.free
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.filesystem.usage
        experimental_match_labels:
          state: reserved
        action: insert
        new_name: system.filesystem.usage.reserved
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.filesystem.usage
        experimental_match_labels:
          state: used
        action: insert
        new_name: system.filesystem.usage.used
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.filesystem.inodes.usage
        experimental_match_labels:
          state: free
        action: insert
        new_name: system.filesystem.inodes.usage.free
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.filesystem.inodes.usage
        experimental_match_labels:
          state: reserved
        action: insert
        new_name: system.filesystem.inodes.usage.reserved
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.filesystem.inodes.usage
        experimental_match_labels:
          state: used
        action: insert
        new_name: system.filesystem.inodes.usage.used
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.packets
        experimental_match_labels:
          direction: receive
        action: insert
        new_name: system.network.packets.receive
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.packets
        experimental_match_labels:
          direction: transmit
        action: insert
        new_name: system.network.packets.transmit
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.dropped
        experimental_match_labels:
          direction: receive
        action: insert
        new_name: system.network.dropped.receive
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.dropped
        experimental_match_labels:
          direction: transmit
        action: insert
        new_name: system.network.dropped.transmit
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.errors
        experimental_match_labels:
          direction: receive
        action: insert
        new_name: system.network.errors.receive
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.errors
        experimental_match_labels:
          direction: transmit
        action: insert
        new_name: system.network.errors.transmit
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.io
        experimental_match_labels:
          direction: receive
        action: insert
        new_name: system.network.io.receive
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.io
        experimental_match_labels:
          direction: transmit
        action: insert
        new_name: system.network.io.transmit
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections
        experimental_match_labels:
          protocol: tcp
        action: insert
        new_name: system.network.connections.tcp
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set:
              - state
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: CLOSE_WAIT
        action: insert
        new_name: system.network.connections.tcp.CLOSE_WAIT
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: CLOSED
        action: insert
        new_name: system.network.connections.tcp.CLOSED
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: CLOSING
        action: insert
        new_name: system.network.connections.tcp.CLOSING
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: DELETE
        action: insert
        new_name: system.network.connections.tcp.DELETE
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: ESTABLISHED
        action: insert
        new_name: system.network.connections.tcp.ESTABLISHED
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: FIN_WAIT_1
        action: insert
        new_name: system.network.connections.tcp.FIN_WAIT_1
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: FIN_WAIT_2
        action: insert
        new_name: system.network.connections.tcp.FIN_WAIT_2
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: LAST_ACK
        action: insert
        new_name: system.network.connections.tcp.LAST_ACK
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: LISTEN
        action: insert
        new_name: system.network.connections.tcp.LISTEN
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: SYN_RECEIVED
        action: insert
        new_name: system.network.connections.tcp.SYN_RECEIVED
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: SYN_SENT
        action: insert
        new_name: system.network.connections.tcp.SYN_SENT
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.network.connections.tcp
        experimental_match_labels:
          state: TIME_WAIT
        action: insert
        new_name: system.network.connections.tcp.TIME_WAIT
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.paging.usage
        experimental_match_labels:
          state: cached
        action: insert
        new_name: system.paging.usage.cached
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.paging.usage
        experimental_match_labels:
          state: free
        action: insert
        new_name: system.paging.usage.free
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.paging.usage
        experimental_match_labels:
          state: used
        action: insert
        new_name: system.paging.usage.used
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.paging.operations
        experimental_match_labels:
          direction: page_in
        action: insert
        new_name: system.paging.operations.page_in
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set:
              - type
      - include: system.paging.operations.page_in
        experimental_match_labels:
          type: major
        action: insert
        new_name: system.paging.operations.page_in.major
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.paging.operations.page_in
        experimental_match_labels:
          type: minor
        action: insert
        new_name: system.paging.operations.page_in.minor
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.paging.operations
        experimental_match_labels:
          direction: page_out
        action: insert
        new_name: system.paging.operations.page_out
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set:
              - type
      - include: system.paging.operations.page_out
        experimental_match_labels:
          type: major
        action: insert
        new_name: system.paging.operations.page_out.major
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.paging.operations.page_out
        experimental_match_labels:
          type: minor
        action: insert
        new_name: system.paging.operations.page_out.minor
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.paging.faults
        experimental_match_labels:
          type: major
        action: insert
        new_name: system.paging.faults.major
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.paging.faults
        experimental_match_labels:
          type: minor
        action: insert
        new_name: system.paging.faults.minor
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.processes.count
        experimental_match_labels:
          status: blocked
        action: insert
        new_name: system.processes.count.blocked
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
      - include: system.processes.count
        experimental_match_labels:
          status: running
        action: insert
        new_name: system.processes.count.running
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - process.cpu.time
          - process.disk.io
          - system.cpu.time
          - system.disk.io
          - system.disk.merged
          - system.disk.operation_time
          - system.disk.operations
          - system.filesystem.inodes.usage
          - system.filesystem.usage
          - system.memory.usage
          - system.network.connections
          - system.network.connections.tcp
          - system.network.dropped
          - system.network.errors
          - system.network.io
          - system.network.packets
          - system.paging.faults
          - system.paging.operations
          - system.paging.operations.page_in
          - system.paging.operations.page_out
          - system.paging.usage
          - system.processes.count
service:
  pipelines:
    metrics:
      receivers:
        - hostmetrics
      processors:
        - metricstransform
        - filter
        # - timestamp
        - resourcedetection
        - batch
      exporters:
        - logging
        # - otlp
```

### Log output

```shell
2023-07-13T11:43:15.796-0600    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging",
"resource metrics": 7, "metrics": 43, "data points": 43}
```

### Additional context

I received the warning message:

> 2023-07-13T11:49:03.005-0600    warn    loggingexporter@v0.81.0/factory.go:98   'loglevel' option is deprecated in favor
 of 'verbosity'. Set 'verbosity' to equivalent value to preserve behavior.      {"kind": "exporter", "data_type": "metri
cs", "name": "logging", "loglevel": "error", "equivalent verbosity level": "Basic"}

So I tried replacing:

```
  logging:
    loglevel: error
```

with:

```
  logging:
    verbosity: Basic
```

But the behaviour is the same.

**Comment by mx-psi** [comment]
The logging exporter always logs at info level. The `logging::loglevel` setting was changed to `logging::verbosity` to reflect that the log level of messages outputted by it do not have its log level changed ever. The logging exporter also does not affect the log level of other OpenTelemetry Collector components. To change that, you need to set `service::telemetry::logs::level`. For example, to only get warnings, you can do:

```yaml
service:
  telemetry:
     logs:
       level: warn
```
