### ISSUE TITLE
Metric Datapoint attribute isn't getting filtered out via otelcollector

### ISSUE THREAD

**Issue by Ryang20718** [open-telemetry/opentelemetry-collector-contrib#24277]
### What happened?

Metric data attributes aren't getting filtered out from otel metrics 

### Collector version

0.79.0

## Environment

- OS: Ubuntu
- Architecture: x86
- Go Version: 1.20
- `otelgrpc` version: v0.42.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
        endpoint: 0.0.0.0:4317

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
        - net.sock.peer.addr


exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [filter]
      exporters: [logging]
```

### Log output

```shell
Data point attributes:
     -> net.sock.peer.addr: Str(172.19.0.5)
     -> net.sock.peer.port: Int(51452)
     -> rpc.grpc.status_code: Int(0)
     ....
```

### Expected behavior 

We expected that the data point attribute will be filtered out. However, we see that the metric attribute is still within the payload

```
Data point attributes:
     -> net.sock.peer.port: Int(51452)
     -> rpc.grpc.status_code: Int(0)
     ....
```
```


### Additional context

1. Using the default tracing/metrics for otel,
```
	grpcServer := grpc.NewServer(
		grpc.UnaryInterceptor(otelgrpc.UnaryServerInterceptor()),
		grpc.StreamInterceptor(otelgrpc.StreamServerInterceptor()),
		grpc.MaxRecvMsgSize(100*1024*1024), 
	)
```

2. Run the otel collector
3. We still see attributes not getting filtered out
