### ISSUE TITLE
[extension/file_storage] - The config field "directory" seems never used

### ISSUE THREAD

**Issue by gillg** [open-telemetry/opentelemetry-collector-contrib#24297]
### Component(s)

`extension/file_storage`

## Description
When we configure the extention with something like:
```
file_storage:
  directory: /var/custom/path
```
It seems never used. I get an error on te otel collector becasue the default hardcoded folder doesn't exists.
The code seems confirm it here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1fb3ef29b52a1a0215283f70b413ac2ffe1dbf6d/extension/storage/filestorage/factory.go#L41C11-L41C11
The directory is never read from the config but always rom the default folder (depending on the OS).

## Steps to Reproduce
Try to use a different directory than the default

## Expected Result
No fatal errors if we configured a custom folder and the default folder doesn't exists on the filesystem.

## Actual Result
Otel collector stops because the default path doesn't exists

### Collector version

0.80.0

## Environment
OS: windows

**Comment by crobert-1** [comment]
Hello @gillg, could you please share your whole config file? I modified [the basic config](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/1fb3ef29b52a1a0215283f70b413ac2ffe1dbf6d/extension/storage/filestorage#example) from the filestorage extension's README, and once I set `directory` to a different directory and created it manually, it worked as expected.

My working config:
```
extensions:
  file_storage/all_settings:
    directory: /var/lib/other_dir
    timeout: 1s
    compaction:
      on_start: true
      directory: /tmp/
      max_transaction_size: 65_536


service:
  extensions: [file_storage/all_settings]
```
I did define a basic receiver and exporter as well. I'm running also running on MacOS.

**Comment by djaglowski** [comment]
The code referenced [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1fb3ef29b52a1a0215283f70b413ac2ffe1dbf6d/extension/storage/filestorage/factory.go#L41C11-L41C11) is setting up a default configuration for the component. Later, the user's config is unmarshaled into the same struct, overriding default settings which the user has configured.

[Here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/247e2bb66ec3dc908ad018c2d4e7830d0199fe73/extension/storage/filestorage/extension.go#L53:L54) is where we use the resulting directory name to determine the path for the storage file.

**Comment by gillg** [comment]
Hello, I finaly bring more details, but I still confirm my issue.

```
extensions:
    file_storage:
      directory: "C:/var/lib/otelcol/buffer" # The directory MUST exists in advance ! The collector will not try to create it.
      compaction:
        on_start: true

service:
  extensions: [memory_ballast,health_check,file_storage]
```

So with this config I expect the otel collector able to use the custom folder if it exists. But when I launch otel collector the full console output is:
```
otelcol_windows_amd64.exe' --config 'otel-collector-config.yaml'

Error: invalid configuration: extensions::file_storage: directory must exist: CreateFile C:\ProgramData\Otelcol\FileStorage: The system cannot find the path specified.
2023/07/30 21:51:45 collector server run finished with error: invalid configuration: extensions::file_storage: directory must exist: CreateFile C:\ProgramData\Otelcol\FileStorage: The system cannot find the path specified.
```

**Comment by djaglowski** [comment]
I've not had any luck replicating this. I suspect it must be a peculiarity of windows paths which I am failing to recognize.

**Comment by gillg** [comment]
Ok, I understand what happen !

Problematic config:
```
extensions:
    file_storage:
      directory: "C:/var/lib/otelcol/buffer" # The directory MUST exists in advance ! The collector will not try to create it.
      compaction:
        on_start: true

service:
  extensions: [memory_ballast,health_check,file_storage]
```

Working config:
```
extensions:
    file_storage:
      directory: "C:/var/lib/otelcol/buffer" # The directory MUST exists in advance ! The collector will not try to create it.
      compaction:
        directory: "C:/var/lib/otelcol/buffer"
        on_start: true

service:
  extensions: [memory_ballast,health_check,file_storage]
```

Obviously... if we don't define the specific compaction.directory the default is used and must exists. So if we want to override the folders we must think about defining both.

By the way, there is no problem about using the same folder for the temp compaction and the final storage ?
