### ISSUE TITLE
[cmd/opampsupervisor] Specify requirements for privilege dropping

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#24299]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

Update the Supervisor design document to describe how to run the Collector as another user, which will generally be a user with lesser permissions.

### Describe the solution you'd like

The current draft for the Supervisor's config file specifies the following config to run the Collector as different user:

```yaml
collector:
  # Optional user name to drop the privileges to when running the
  # Collector process.
  run_as: myuser
```

Open questions:
1. Should this key be optional or required?
2. What mechanism should be used to accomplish this?
One idea is to use a default tool (`su`, `sudo`, etc.) and provide an option for users to specify their own tool/script to run the Collector. 

### Additional context

See [this comment chain](https://docs.google.com/document/d/1KtH5atZQUs9Achbce6LiOaJxLbksNJenvgvyKLsJrkc/edit?pli=1&disco=AAAAkWOtq2Y) on the Google Doc for more context on the discussion so far.
