### ISSUE TITLE
New component: Kinetica Exporter

### ISSUE THREAD

**Issue by kyle-sutton** [open-telemetry/opentelemetry-collector-contrib#24294]
### The purpose and use-cases of the new component

Kinetica is a real-time database, combining time-series, spatial, and graph capabilities into a unified platform accessible through a SQL based interface.

The Kinetica Exporter would allow telemetry data to be rapidly ingested into a fixed set of tables within Kinetica and support distributed searching, filtering, and aggregating of the telemetry data, once loaded

### Example configuration for the component

```
exporters:
  kinetica:
    host: http://localhost:9191/
    schema: otel
    username: admin
    password: password
    bypasssslcertcheck: true
    logconfigfile: log_config.yaml


service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - kinetica
    metrics:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - kinetica
    logs:
      receivers:
      - otlp
      processors:
      - batch
      exporters:
      - kinetica

```

### Telemetry data types supported

Traces, logs, & metrics are supported.

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute this as a representative of the vendor.

### Sponsor (optional)

@TylerHelmuth
