### ISSUE TITLE
[cmd/opampsupervisor] Allow configuring Collector process execution

### ISSUE THREAD

**Issue by evan-bradley** [open-telemetry/opentelemetry-collector-contrib#24324]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

When a user normally runs a Collector process, they can pass arguments, environment variables, and multiple configuration files. The Supervisor needs to support passing these.

### Describe the solution you'd like

Implement the following config, as defined in the Supervisor design document.

```yaml
collector:
  # Extra command line flags to pass to the Collector executable.
  args:

  # Extra environment variables to set when executing the Collector.
  env:
  
  # Path to optional local Collector config files to be merged with the
  # config provided by the OpAMP server.
  config_file: /etc/otelcol/config.yaml
```

For the `config_file` key, determine if multiple config files should be passed and update the design document if they should.

**Comment by srikanthccv** [comment]
I started working on this.

**Comment by srikanthccv** [comment]
Can we get rid of the `config_file` field? It's an optional field and its contents alone may not provide the effective config (we should use the opamp extension for this which is being tracked here) so why not just let it be part of the `args` because ultimately we provide it as args to the command. One can also use multiple config sources using the `args`.

**Comment by evan-bradley** [comment]
I see your argument there, but a Collector built with only upstream components actually only supports a few different flags, so it would be nice to allow configuring it entirely through YAML if at all possible. What if we made the option `config_sources` (we should allow providers other than files, e.g. HTTP) and provided a `feature_gates` key as well to configure feature gates? I think those are the two most common arguments passed to a Collector.

**Comment by srikanthccv** [comment]
There is one other flag I haven't personally seen many use `--set`. I guess we can start with `config_sources` and `feature_gates`. Does this look good?
```
collector:
  # Extra command line flags to pass to the Collector executable.
  args:

  # Extra environment variables to set when executing the Collector.
  env:
  
  config_sources:
    file:
      - /etc/collector/otlp.yaml
      - /etc/collector/internal-metrics.yaml
      - ...
    http:
      - 
      - 
    https:
      -
    env:
    yaml:
    s3:
  
  feature_gates:
    - +a
    - -b

```

Should we limit the config sources to the supported sources in core distribution?
