### ISSUE TITLE
Metrics: Support for updating/adding the metrics label names/values from metric name regex groups

### ISSUE THREAD

**Issue by dirrao** [open-telemetry/opentelemetry-collector-contrib#24366]
### Is your feature request related to a problem? Please describe.

Unable to use metrics regex groups in label names or values in metrics transform processor. It will be great to add this to avoid blowing the metrics namespace. We are looking something similar to statsd telegraf templates. 
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/README.md

**Comment by crobert-1** [comment]
Hello @dirrao, sorry for the delay in response! Can you provide some more information for your goal here? A specific example of what you're trying to match and do with the processor would be a lot of help in directing your concern here.

**Comment by charz** [comment]
@dirrao Thanks for raising this request. I have a similar reqeust, but I'm not sure if this is your case. 

@crobert-1 This is my case. 

I tried to use statsdreciever + metricstransform to cover some statad metrics that don't have label and value.

stats metrics
```
http.GET.404.timing
http.GET.200.timing
```

The configuration that I have for metricstransform. I can add regex group to metric name, but I'm not able to make it work in new label. 

### This works in metric name
```
processors:
  metricstransform:
    transforms:
      - include: ^http.([A-Z_]*).([0-9]{3}).timing
        match_type: regexp
        action: update
        new_name: http_timing_$${1}_$${2}
```

### This doesn't work. The regex group won't able to add in label value.
```
processors:
  metricstransform:
    transforms:
      - include: ^http.([A-Z_]*).([0-9]{3}).timing
        match_type: regexp
        action: update
        new_name: http_timing
        operations:
          - action: add_label
            new_label: method
            new_value: $${1}
          - action: add_label
            new_label: status_code
            new_value: $${2}    
```
