### ISSUE TITLE
[exporter/datadog] Missing histogram metrics in datadog payload 

### ISSUE THREAD

**Issue by karmingc** [open-telemetry/opentelemetry-collector-contrib#24377]
### Component(s)

exporter/datadog

## Description

Hi, I am currently using Sprint Boot v3.1.1 and it is using Micrometer to send metrics to OpenTelemetry Collector. However, I am having issue debugging missing metrics of type `histogram` as they seem to be missing from the datadog payload step. 

I'd like to get some pointers what's the best way to debug this.

spring boot config:
```yaml
# spring boot application.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
  server:
    port: 8081
  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
        aggregationTemporality: "delta"
```

## Steps to Reproduce

1. Create a Spring Boot application, that uses otlp registry https://micrometer.io/docs/registry/otlp
2. Run OpenTelemetry collector locally with Datadog as exporter

## Expected Result

all `histogram` metrics should be part of the datadog payload step

## Actual Result

all `histogram` metrics are excluded from the datadog payload step

### Collector version

v0.81

## Environment
using the Docker image `otel/opentelemetry-collector-contrib`

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  datadog:
    api:
      site: datadoghq.com
      key: ${env:DD_API_KEY}
    metrics:
      histograms:
        mode: distributions
  logging:
    verbosity: detailed

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
  telemetry:
    logs:
      level: "debug"
```

### Log output

```shell
otel-otel-collector-1  | Metric #91
otel-otel-collector-1  | Descriptor:
otel-otel-collector-1  |      -> Name: jvm.gc.pause
otel-otel-collector-1  |      -> Description: Time spent in GC pause
otel-otel-collector-1  |      -> Unit: milliseconds
otel-otel-collector-1  |      -> DataType: Histogram
otel-otel-collector-1  |      -> AggregationTemporality: Delta
otel-otel-collector-1  | HistogramDataPoints #0
otel-otel-collector-1  | Data point attributes:
otel-otel-collector-1  |      -> action: Str(end of minor GC)
otel-otel-collector-1  |      -> cause: Str(G1 Evacuation Pause)
otel-otel-collector-1  |      -> env: Str(local-kc-test)
otel-otel-collector-1  |      -> gc: Str(G1 Young Generation)
otel-otel-collector-1  | StartTimestamp: 2023-07-18 21:33:00 +0000 UTC
otel-otel-collector-1  | Timestamp: 2023-07-18 21:34:00 +0000 UTC
otel-otel-collector-1  | Count: 1
otel-otel-collector-1  | Sum: 2.000000
otel-otel-collector-1  | Max: 2.000000
```

**Comment by songy23** [comment]
Hi @karmingc it looks like there's no bucket in your histogram metric?  If that's the case you might want to enable config [send_aggregation_metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/examples/collector.yaml#L262) so that the sum, count, min and max metrics are exported. E.g.
```yaml
exporters:
  datadog:
    api:
      site: datadoghq.com
      key: ${env:DD_API_KEY}
    metrics:
      histograms:
        mode: distributions
        send_aggregation_metrics: true
```
