### ISSUE TITLE
Context based routing not working for grpc protocol

### ISSUE THREAD

**Issue by mukeshhv** [open-telemetry/opentelemetry-collector-contrib#24395]
### Component(s)

processor/routing

## Description
I have a basic routing processor configuration that I am testing. I am not sure where I am going wrong. It always goes to my default exporter when enabled but not the table. 
## Steps to Reproduce
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        include_metadata: true
processors:
  routing:
    from_attribute: flag
    attribute_source : context
    # default_exporters:
    #   - logging
    table:
    - value: 1
      exporters: logging
exporters:
    logging:
      loglevel: debug
service:
    extensions: [ pprof, zpages, health_check, memory_ballast ]
    telemetry:
      metrics:
        address: "0.0.0.0:8888"
        level: "detailed"
    pipelines:
      traces:
        receivers: [ otlp ]
        processors: [ routing]
        exporters: [ logging ]
```
## Expected Result
Spans from my application. I pass a certain flag as a baggage header to my application. 
## Actual Result
No logs

### Collector version

v.0.64.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
