### ISSUE TITLE
[k8sclusterreceiver] refactoring pod status phase

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#24425]
### Component(s)

receiver/k8scluster

### Describe the issue you're reporting

We currently encode pod status phase to number:

```
  k8s.pod.phase:
    enabled: true
    description: Current phase of the pod (1 - Pending, 2 - Running, 3 - Succeeded, 4 - Failed, 5 - Unknown)
    unit: 1
    gauge:
      value_type: int
```

I think it's preferable to split into many metrics:
```
  k8s.pod.phase_pending:
    enabled: true
    description: Whether this pod phase is Pending (1), or not (0).
    unit: 1
    gauge:
      value_type: int
  k8s.pod.phase_running:
    enabled: true
    description: Whether this pod phase is Running (1), or not (0).
    unit: 1
    gauge:
      value_type: int
```

IMO it's easier to parse from the name what is happening and we already have this pattern for Nodes conditions.

Thoughts?
