### ISSUE TITLE
[filterprocessor] Does not filter metrics correctly

### ISSUE THREAD

**Issue by sfc-gh-aivanou** [open-telemetry/opentelemetry-collector-contrib#24435]
### Component(s)

processor/filter

## Description

Filterprocessor does not filter metrics correctly.
I am trying to configure this filter to allow only metrics with specific label and name, but filter removes all metrics.

## Steps to Reproduce

Run configuration.

## Expected Result

`kube_pod_status_phase` for only `namespace = my_namespace`

## Actual Result

The actual result does not contain any metrics

### Collector version

0.81

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "kube-state-metrics"
              static_configs:
                - targets: ['kube-state-hostname:8080']
              scrape_interval: 5s
              metrics_path: /metrics

              metric_relabel_configs:
                - source_labels: [ __name__ ]
                  regex: '(kube_pod_status_phase)'
                  action: keep

    processors:
      filter/1:
        metrics:
          include:
            match_type: expr
            expressions:
            - MetricName == "kube_pod_status_phase" && Label("namespace") == "my_namespace"

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9001"
        resource_to_telemetry_conversion:
          enabled: true
    service:
      telemetry:
        logs:
          level: "info"
      
      pipelines:
        metrics/1:
          receivers: [prometheus]
          processors: [filter/1]
          exporters: [prometheus]
```

**Comment by sfc-gh-aivanou** [comment]
also this does not work:
```
    processors:
      filter/1:
        metrics:
          exclude:
            match_type: expr
            expressions:
            - MetricName == "kube_pod_status_phase" && Label("namespace") != "my_namespace"
            - MetricType == "Gauge"
```


Also, Is it possible to provide more insights into why one or another filter does not work. It is very hard to configure filter since there is no feedback why metric streams are getting dropped

**Comment by TylerHelmuth** [comment]
@sfc-gh-aivanou the best thing to do when debugging the filterprocessor is to add the loggingexporter with verbosity=detailed and make sure the data looks like you expect it to. In this case you want to ensure that the metric name and attribute you're expecting really are on the data.

**Comment by WheeskyJack** [comment]
following works for me  in `0.80.0` version: 

```
  filter/1:
    error_mode: ignore
    metrics:
      metric:
        - 'name != "kube_pod_status_phase"'
      datapoint:
        - 'attributes["namespace"] != "my_namespace"'
```

if you don't want to filter by metric name(i.e. allow all metrics but with specific label name and value) then you can simply remove `metric:` section from above and keep only datapoint.

**Comment by atoulme** [comment]
Closing as not planned, please reopen if you still have difficulties.

**Comment by maximillianus** [comment]
Hi, can we reopen? I encountered this issue too. I am hoping to scrape hostmetrics for `cpu0` only using this:
```
 filter/metric_attr:
    metrics:
      include:
        match_type: expr
        expressions:
        - MetricName == "system.cpu.time" && Label("cpu") == "cpu0"
```

Expected results:
```
# HELP otel_host_metrics_system_cpu_time_seconds_total Total seconds each logical CPU spent on each mode.
# TYPE otel_host_metrics_system_cpu_time_seconds_total counter
otel_host_metrics_system_cpu_time_seconds_total{cpu="cpu0",state="idle"} 135036.14
otel_host_metrics_system_cpu_time_seconds_total{cpu="cpu0",state="interrupt"} 0
.
.
.
```

Actual results:
```
# HELP otel_host_metrics_system_cpu_time_seconds_total Total seconds each logical CPU spent on each mode.
# TYPE otel_host_metrics_system_cpu_time_seconds_total counter
otel_host_metrics_system_cpu_time_seconds_total{cpu="cpu0",state="idle"} 135036.14
otel_host_metrics_system_cpu_time_seconds_total{cpu="cpu0",state="interrupt"} 0
.
.
.
otel_host_metrics_system_cpu_time_seconds_total{cpu="cpu1",state="idle"} 135040.18
otel_host_metrics_system_cpu_time_seconds_total{cpu="cpu1",state="interrupt"} 0
.
.
.
```

@WheeskyJack 's answer works but I wonder why the above does not work?
