### ISSUE TITLE
resourcetotelemetry wrapper makes an unnecessary copy of metrics

### ISSUE THREAD

**Issue by sfc-gh-mcreech** [open-telemetry/opentelemetry-collector-contrib#24432]
### Component(s)

pkg/resourcetotelemetry

## Description

We use `prometheusremotewriteexporter` with `resource_to_telemetry_conversion` enabled. While analyzing a profile due to high heap usage, I noticed that the copy operation [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c7bd50ce773e66be327ef7618775a884a774e5d1/pkg/resourcetotelemetry/resource_to_telemetry.go#L51) was responsible for a very large %age of the heap consumption.

This copy operation has to happen unconditionally because the `resourcetotelemetry` wrapper [says](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c7bd50ce773e66be327ef7618775a884a774e5d1/pkg/resourcetotelemetry/resource_to_telemetry.go#L37) it doesn't mutate data. But (IIUC) simply setting `MutatesData: true` and avoiding the internal/explicit copy would have a similar effect, and in non-fanout cases would avoid the copy altogether.

### Collector version

v0.81.0

## Environment
OS: linux_amd64
Compiler(if manually compiled): go 1.19

### OpenTelemetry Collector configuration

```yaml
exporters:
      prometheusremotewrite/local:
        endpoint: http://prom-gateway.ns.svc.cluster.local:80/api/v1/push
        resource_to_telemetry_conversion:
          enabled: true
        remote_write_queue:
          enabled: true
          queue_size: 250
          num_consumers: 5
    service:
      extensions:
        - memory_ballast
        - health_check
        - pprof
      pipelines:
        metrics/prom:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheusremotewrite/local]
```
