### ISSUE TITLE
[exporter/datadog] Log events are lost in case of network issues without retry

### ISSUE THREAD

**Issue by anmalysh-yb** [open-telemetry/opentelemetry-collector-contrib#24550]
### Component(s)

exporter/datadog

### What happened?

Currently datadog exporter treats network error as permanent error and does not queue log event for retry, because of that.

Probably introduced with this diff: https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/a21144b395101eac46c61fc422f338289a5cd955

## Steps to Reproduce
Configure collector as shown in the ticket.
Start writing log.
Turn off network connection.
Turn network connection back on after some time.

## Expected Result
All the logs are exported to datadog.

## Actual Result
Logs written during network outage are lost.

### Collector version

0.81.0

## Environment
OS: MacOS
Compiler(if manually compiled): N/A

### OpenTelemetry Collector configuration

```yaml
receivers:
   filelog:
    include: [ /Users/amalysh86/otelcol/simple.log*]
    start_at: beginning
    storage: file_storage/pts
    operators:
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%d %H:%M:%S'
        severity:
          parse_from: attributes.sev

exporters:
  file:
    path: /Users/amalysh86/otelcol/out.json
  datadog:
    api:
      site: us3.datadoghq.com
      key: <API KEY HERE>
    retry_on_failure:
      enabled: true
      initial_interval: 1m
      max_interval: 1800m
    sending_queue:
      storage: file_storage/psq

extensions:
  file_storage/pts:
     directory: /Users/amalysh86/otelcol/pts
     timeout: 10s # in what time a file lock should be obtained

  file_storage/psq:
     directory: /Users/amalysh86/otelcol/psq
     timeout: 10s # in what time a file lock should be obtained
     compaction:
       directory: /Users/amalysh86/otelcol/psq
       on_start: true
       on_rebound: true
       rebound_needed_threshold_mib: 5
       rebound_trigger_threshold_mib: 3

service:
  extensions:
  - file_storage/pts
  - file_storage/psq
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [datadog]
```

### Log output

```shell
2023-06-30T19:05:28.650+0300	error	exporterhelper/queued_retry.go:391	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "logs", "name": "datadog", "error": "Permanent error: Post \"https://http-intake.logs.us3.datadoghq.com/api/v2/logs?ddtags=otel_source%3Adatadog_exporter\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)", "dropped_items": 1}
```
