### ISSUE TITLE
[exporter/elasticsearchexporter] the client noticed that the server is not Elasticsearch and we do not support this unknown product

### ISSUE THREAD

**Issue by pjachowi** [open-telemetry/opentelemetry-collector-contrib#24561]
### Component(s)

exporter/elasticsearch

## Description
Logs export fail with error `the client noticed that the server is not Elasticsearch and we do not support this unknown product`

## Expected Result

Logs exported to Elastic

## Actual Result

Error
```
2023-07-25T10:49:25.173Z	error	elasticsearchexporter@v0.81.0/elasticsearch_bulk.go:150	Bulk indexer error: flush: the client noticed that the server is not Elasticsearch and we do not support this unknown product	{"kind": "exporter", "data_type": "logs", "name": "elasticsearch/log"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newBulkIndexer.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.81.0/elasticsearch_bulk.go:150
github.com/elastic/go-elasticsearch/v7/esutil.(*worker).flush
	github.com/elastic/go-elasticsearch/v7@v7.17.10/esutil/bulk_indexer.go:557
github.com/elastic/go-elasticsearch/v7/esutil.(*bulkIndexer).init.func1
	github.com/elastic/go-elasticsearch/v7@v7.17.10/esutil/bulk_indexer.go:321
2023-07-25T10:49:25.174Z	error	elasticsearchexporter@v0.81.0/elasticsearch_bulk.go:150	Bulk indexer error: flush: the client noticed that the server is not Elasticsearch and we do not support this unknown product	{"kind": "exporter", "data_type": "logs", "name": "elasticsearch/log"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newBulkIndexer.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.81.0/elasticsearch_bulk.go:150
github.com/elastic/go-elasticsearch/v7/esutil.(*bulkIndexer).init.func1
	github.com/elastic/go-elasticsearch/v7@v7.17.10/esutil/bulk_indexer.go:324
```

### Collector version

v0.81.0

## Environment
Elastic server version is v8:
```
{
  "build_date": "2023-02-13T13:01:54Z",
  "build_sha": "8638b035d700e5e85e376252402b5375e4d4190b",
  "publish_ready": true,
  "version": "8.6.2"
}
```

### OpenTelemetry Collector configuration

```yaml
extensions:
  jwtauthextension:
    issuer_url: https://someservice.motorolasolutions.com:443
    jwks_path: ext/oauth/jwks

  health_check:


receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          cert_file: /etc/otel/cert.pem
          key_file:  /etc/otel/cert-key.pem
        auth:
          authenticator: jwtauthextension

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

exporters:
  otlp/elastic:
    endpoint: apm.elastic.svc.cluster.local:8200
    tls:
      insecure: true
      insecure_skip_verify: false
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: ccdrive-dev
    const_labels:
      project: ccdrive
    send_timestamps: true
    metric_expiration: 180m
  logging:
  elasticsearch/log:
    endpoints: [http://apm.elastic.svc.cluster.local:8200]
    logs_index: Default
    sending_queue:
      enabled: true
      num_consumers: 20
      queue_size: 1000

service:
  extensions: [jwtauthextension, health_check]
  telemetry:
    logs:
      level: "debug"
    metrics:
      address: ":8888"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic, logging]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlp/elastic, prometheus, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, elasticsearch/log, otlp/elastic]
```

### Log output

```shell
2023-07-25T10:49:25.173Z	error	elasticsearchexporter@v0.81.0/elasticsearch_bulk.go:150	Bulk indexer error: flush: the client noticed that the server is not Elasticsearch and we do not support this unknown product	{"kind": "exporter", "data_type": "logs", "name": "elasticsearch/log"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newBulkIndexer.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.81.0/elasticsearch_bulk.go:150
github.com/elastic/go-elasticsearch/v7/esutil.(*worker).flush
	github.com/elastic/go-elasticsearch/v7@v7.17.10/esutil/bulk_indexer.go:557
github.com/elastic/go-elasticsearch/v7/esutil.(*bulkIndexer).init.func1
	github.com/elastic/go-elasticsearch/v7@v7.17.10/esutil/bulk_indexer.go:321
2023-07-25T10:49:25.174Z	error	elasticsearchexporter@v0.81.0/elasticsearch_bulk.go:150	Bulk indexer error: flush: the client noticed that the server is not Elasticsearch and we do not support this unknown product	{"kind": "exporter", "data_type": "logs", "name": "elasticsearch/log"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newBulkIndexer.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.81.0/elasticsearch_bulk.go:150
github.com/elastic/go-elasticsearch/v7/esutil.(*bulkIndexer).init.func1
	github.com/elastic/go-elasticsearch/v7@v7.17.10/esutil/bulk_indexer.go:324
```

### Additional context

The elastic version is
```
{
  "build_date": "2023-02-13T13:01:54Z",
  "build_sha": "8638b035d700e5e85e376252402b5375e4d4190b",
  "publish_ready": true,
  "version": "8.6.2"
}
```
In the collector source code I found that there is v7 used. According to https://stackoverflow.com/questions/68802324/elasticsearch-in-go-err-the-client-noticed-that-the-server-is-not-elasticsear the error is caused by client v7 connecting to server v8.
