### ISSUE TITLE
[processor/k8sattributes] Allow specifying that all labels/annotations should be copied

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#24599]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

Today the processor allows configuring which specific labels and annotations should be added as resource attributes. For users who want all the labels and/or annotations, this requires them to:
1. Know all the possible keys
2. List all the possible keys in the configuration

In my opinion this is a poor user experience. 

### Describe the solution you'd like

As a quality of life improvement I'd like to be able to specify the "Add all the labels from the pod" or "Add all the annotations from the namespace" and so on.  I think the configuration API would look something like:

```yaml
k8sattributes/:
 extract:
   allAnnotationsFrom:
     - pod
     - namespace
   allLabelsFrom:
     - pod 
```

I also don't believe this needs to be mutually exclusive from `annotations` and `labels` configuration option.  Users should be allowed to use `allAnnotationsFrom` and `annotations` so that they can specify regexp extractions to get even more attributes.  I does sound like a good idea to validate that if both options are used (`allAnnotationsFrom` and `annotations` or `allLabelsFrom` and `labels`) that each extraction in `annotations`/`labels` uses regexp.

**Comment by TylerHelmuth** [comment]
I started work on this an then realized the current extraction logic already allows grabbing all the labels and annotations:

```yaml
extract:
  labels:
    - tag_name: $$1
      key_regex: (.*)
      from: pod
    - tag_name: $$1
      key_regex: (.*)
      from: namespace
  annotations:
    - tag_name: $$1
      key_regex: (.*)
      from: pod
    - tag_name: $$1
      key_regex: (.*)
      from: namespace
```

It is a little more difficult than the config I proposed, but is a useable solution. Based on the ongoing filtering config work (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25128, https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25135) I think we hold on this proposal for now.
