### ISSUE TITLE
Problem running lokiexporter example with flog

### ISSUE THREAD

**Issue by joshuali925** [open-telemetry/opentelemetry-collector-contrib#2463]
**Describe the bug**
Tried to run the docker compose example for [lokiexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/example/docker-compose.yml). After `docker-compose up`, I'm seeing this warning message from docker, and seems no logs are being generated.
```
flog_1            | WARNING: no logs are available with the 'fluentd' log driver
```
There are suggestions of setting `fluentd-async-connect` to true to fix the issue, but didn't work in this case.
I've also tried this example with elasticsearchexporter and got the same behavior.

**Steps to reproduce**
- clone repo
- `cd exporter/lokiexporter/example`
- in docker-compose.yml change `otel-collector` to build instead of using image `otelcontribcol:latest`
- run `docker-compose up`

**What did you expect to see?**
logs generated and exported to loki

**What did you see instead?**
no logs generated

**What version did you use?**
latest main branch

**What config did you use?**
config in the example folder

**Environment**
Docker env running on MacOS 10.15.7

**Additional context**
NA

Thanks

**Comment by gramidt** [comment]
Thank you for reporting this, @joshuali925! I'm sorry to hear that you're experiencing issues with the example.

Could you provide the version of Docker that you're using?

**Comment by gramidt** [comment]
@bogdandrutu @tigrannajaryan - Could either of you assign this issue to me?

**Comment by joshuali925** [comment]
Hi @gramidt , I'm using `Docker version 20.10.2, build 2291f61`, thanks

**Comment by gramidt** [comment]
Thank you, @joshuali925!

Upon recreating the example a fresh environment, I ran into an issue with the collector memory limiter configuration that prevented the collector from starting up. This could cause the issue that you are seeing. Could you try pulling the changes from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2547/files  and re-testing the example?

**Comment by joshuali925** [comment]
Just tried it, I'm able to see logs in grafana now. Thanks a lot!

One more question on elasticsearchexporter. I tried to use the same setup for Loki logs, and here is what I got
```
otel              | panic: TODO
otel              |
otel              | goroutine 48 [running]:
otel              | github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*elasticsearchExporter).pushLogsData(...)
otel              | 	/src/exporter/elasticsearchexporter/exporter.go:72
otel              | go.opentelemetry.io/collector/exporter/exporterhelper.(*logsRequest).export(0xc0003dbd00, 0x4383e60, 0xc00051bda0, 0x4383e60, 0xc00051bda0, 0xc0008b8a10)
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/exporter/exporterhelper/logshelper.go:53 +0x47
otel              | go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc0000b66b8, 0x439b4a0, 0xc0003dbd00, 0x0, 0x0, 0x0)
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/exporter/exporterhelper/common.go:222 +0x92
otel              | go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc00051b4a0, 0x439b4a0, 0xc0003dbd00, 0x3ba69f0, 0x5, 0x4383ea0)
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/exporter/exporterhelper/queued_retry.go:202 +0x14a0
otel              | go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send(0xc00041b8c0, 0x439b4a0, 0xc0003dbd00, 0xc0004582a0, 0xc000384cc8, 0x40)
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/exporter/exporterhelper/logshelper.go:111 +0xcd
otel              | go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send(0xc00051b500, 0x439b4a0, 0xc0003dbd00, 0xd, 0x4383ea0, 0xc0008fed20)
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/exporter/exporterhelper/queued_retry.go:140 +0x444
otel              | go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporter).ConsumeLogs(0xc0008b8290, 0x4383e20, 0xc0000b6000, 0xc00041b940, 0xc0003dbc80, 0xc0003dbca0)
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/exporter/exporterhelper/logshelper.go:67 +0xf7
otel              | go.opentelemetry.io/collector/processor/batchprocessor.(*batchLogs).export(0xc00041b920, 0x4383e20, 0xc0000b6000, 0x1, 0x1)
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/processor/batchprocessor/batch_processor.go:332 +0x50
otel              | go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems(0xc000868070, 0xc0004120a0)
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/processor/batchprocessor/batch_processor.go:196 +0x246
otel              | go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle(0xc000868070)
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/processor/batchprocessor/batch_processor.go:144 +0x1e6
otel              | created by go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).Start
otel              | 	/go/pkg/mod/go.opentelemetry.io/collector@v0.20.1-0.20210222231653-a04feee5a0cb/processor/batchprocessor/batch_processor.go:104 +0x3f
otel exited with code 2
```

Seems to be an issue with elasticsearchexporter itself, but I'm not very familiar with docker so I might have messed up the config somewhere. I already added the exporter to otel binary, and here is what I changed for docker config:

```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
```
```
...
exporters:
  elasticsearch:
    endpoints:
    - "https://localhost:9200"
...
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [ fluentforward ]
      processors: [ memory_limiter, batch ]
      exporters: [ elasticsearch ]
```

Do you know what's causing the error? Or do you have a working example with elasticsearchexporter?

This could be a separate issue, let me know if you want me to open a new one. Thanks.
