### ISSUE TITLE
Support dynamic paths based on attributes of logs

### ISSUE THREAD

**Issue by captainfalcon23** [open-telemetry/opentelemetry-collector-contrib#24654]
### Component(s)

exporter/file

### Is your feature request related to a problem? Please describe.

I want to send our kubernetes pod logs to an opentelementry server and then write them to disk to log files based on attributes within the logs. For example: /data/logs/NAMESPACE_NAME/POD_NAME/CONTAINER_NAME/out.log

### Describe the solution you'd like

As above, allow the file exporter to be able to read attributes of the logs and dynamically generate the log location.

**Comment by captainfalcon23** [comment]
So I am starting to look at this, but still don't think it will meet the requirement. 
Let's say I get logs from a container with the following details:
Container Name: zabbix-agent-1234567
Pod Name: zabbix-agent
Namespace: foo
Cluster (static value): ABC

In this case, I want to save logs to a location like: /mnt/data/logs/$Cluster/$Namespace/$PodName/$ContainerName.log

If I use routing processor, I think I still need to hard code values, and I have to know exactly where my pods are running and if there's some change, I need to manually update this configuration.

Another example is the host logs (e.g. /var/log/messages. I want these to go to a file which is dynamically named "$hostname.log". But again, it seems impossible?

What's your thoughts @atingchen ?

**Comment by atingchen** [comment]
If we need to implement dynamic file export paths, I think we need to follow these three steps:

1. We need to add a `subdirectory_attribute`  in the configuration. It will be used to generate the export path.
```yaml
path: /data
subdirectory_attribute:
  - cluster
  - namespace
```

2. We need to maintain a mapping between the file export path and the `io.writer`.
   + If the export path is not in our mapping, we need to create a new `io.writer`.
   + We also need to consider the eviction mechanism of this map, otherwise, there may be a risk of memory leakage.

3. Before exporting telemetry data each time, obtaining `io.writer` based on the file export path and exporting it.

If we implement it this way, the existing code needs to be significantly modified. I'd like to hear your thoughts on this. @atoulme @djaglowski Thank you.

**Comment by djaglowski** [comment]
There does seem to be some valuable utility here but it would certainly add a lot of complexity and responsibility to the component. I'm not opposed to it in theory but don't think I can make it a priority to help with it.

**Comment by captainfalcon23** [comment]
No worries... I am actually about to start looking at some other solution as I can't get my use-case to work as it stands.

**Comment by atoulme** [comment]
Same way, I would use the routingprocessor and limit this to a set of known paths.

**Comment by captainfalcon23** [comment]
Happy for these to be closed if you guys like. I moved to another, more flexible solution (vector.dev)

**Comment by adam-kiss-sg** [comment]
Hi!

I also need this, and I would like to implement this.

I'm thinking of only supporting a single resource level attribute for the subdirectory_attribute. Multiple attributes can be combined with the transform processor, attributes can be moved to the Resource level using the groupbyattrs processor.

My plan for the implementation (described for logs, but same goes for traces and metrics):
- split fileExporter struct
  - create a new struct fileWriter, move "file", "mutex" fields and part of flush and shutdown functions to it
  - modify exportMessageAsLine and exportMessageAsBuffer to get fileWriter as first parameter
- add an LRU cache for the fileWriters 
  - eg: https://github.com/hashicorp/golang-lru
    - this is already used in the repository in a couple components, eg: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6f3ff4a37efe4591f728250d4ea9e4ad6672fb2b/processor/spanmetricsprocessor/internal/cache/cache.go#L18
- in consumeLogs
  - split plog.Logs by resource attribute
    - there is an example for this in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/routingconnector/logs.go
  - iterate over the groups, for each group:
    - call marshaller
    - call compressor
    - get (or create) the correct fileWriter from the LRU cache, and call export with it

For the configuration, I would add:
```yaml
group_by_attribute:
  subdirectory_attribute: "my_attribute" # (or maybe subpath_attribute instead, and allow '/' in it)
  max_open_files: 1000 # (this would set the size of the LRU cache)
```

What do you think? @atingchen @atoulme @djaglowski

**Comment by filipeferreira89** [comment]
This feature would be interesting, we have a use-case where we save the application data in file to then send to coldstorage, in case, we need the raw logs in the future. We save the files per application name which it's a field in the log, we are achieving that at the moment with logstash, but we are making the effort to move the logging stack to otel.

**Comment by djaglowski** [comment]
It seems there is ongoing interest in this feature and someone willing to implement it with a detailed proposal. (Thanks for stepping forward @adam-kiss-sg.) I'm in favor of this and will be happy to review PRs.

The most immediate question in my mind is the config. Looking at the proposal, a few quick thoughts and a longer discussion:

```yaml
group_by_attribute:
  subdirectory_attribute: "my_attribute" # (or maybe subpath_attribute instead, and allow '/' in it)
  max_open_files: 1000 # (this would set the size of the LRU cache)
```

1. I agree this should be a dedicated section. The name seems reasonable but I think `group_by` is sufficient.
2. For better or worse, we often use a pattern where we enable or disable subsections using an explicit `enabled` flag. I can't seem to find the previous discussion on this but if I recall correctly it is beneficial to helm charts and other tools which may have trouble distinguishing between nil and empty structs when rendering config.
3. We certainly need some sort of capacity setting. I think the proposed name is great as it is simple and user facing.

--- 

Defining the dynamic element of the path is the trickiest part of this proposal. One challenge I have not seen addressed is that our current `path` setting is used to specify not only the directory but the actual file name. e.g. `path: my_dir/my_file.json` 

However, if we introduce a `subdirectory_attribute`, the user should still be able to specify a file name as well. e.g. The following doesn't quite get us there:

```yaml
# my_dir/${my.attr}/????
path: my_dir # but no file name
group_by:
  subdirectory_attribute: my.attr
```

One way to address this is to add another setting within `group_by` to define the file name.

```yaml
# my_dir/${my.attr}/my_file.json
path: my_dir # but no file name
group_by:
  subdirectory_attribute: my.attr
  filename: my_file.json
```

However, this seems awkward because it differs so much from the way `path` currently works. It's also not very flexible. Why not allow the file name to be the dynamic part?

To that end, when `group_by` is enabled, the path could be required to contain exactly one `*` (or equivalent indicator), which will be replaced by the attribute value. This keeps the file _name_ responsibility in the `path` setting and allows more flexibility to the user. `subdirectory_attribute` would not be the right term in this case, so perhaps just `attribute` or `replace_attribute`.

```yaml
# always my_dir/my_file.json
file/static:
  path: my_dir/my_file.json

# my_dir/foo/my_file.json
# my_dir/bar/my_file.json
file/dynamic_subdir:
  path: my_dir/*/my_file.json
  group_by:
    enabled: true
    replace_attribute: my.attr

# my_dir/foo/my_nested_dir/my_file.json
# my_dir/bar/my_nested_dir/my_file.json
file/dynamic_subdir_with_nested_subdirs:
  path: my_dir/*/my_nested_dir/my_file.json
  group_by:
    enabled: true
    replace_attribute: my.attr

# my_dir/foo.json
# my_dir/bar.json
file/dynamic_filename:
  path: my_dir/*.json
  group_by:
    enabled: true
    replace_attribute: my.attr
```

WDYT?
