### ISSUE TITLE
health_check extension: liveliness is failing, not sure.

### ISSUE THREAD

**Issue by Ishmeet** [open-telemetry/opentelemetry-collector-contrib#24655]
### Component(s)

extension/healthcheck

## Description
Getting this error
```
Liveness probe failed: Get "http://10.85.3.47:13133/": dial tcp 10.85.3.47:13133: connect: connection refused 
```
But when I exec into the pod and do `curl localhost:13133` it gives 200 ok. I am not sure, If I am missing something.

Otel config:
```
    extensions:
      health_check:
        check_collector_pipeline:
          enabled: true
          exporter_failure_threshold: 5
          interval: 5m
        endpoint: localhost:13133 // tried with 0.0.0.0:13133 -> same error   
```

I am using open telemetry-operator to create a statefulset pod of collector config.

## Steps to Reproduce
Use health check extension

## Expected Result
Healthcheck should have worked.
## Actual Result
```
Liveness probe failed: Get "http://10.85.3.47:13133/": dial tcp 10.85.3.47:13133: connect: connection refused 
```

### Collector version

v0.79.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
extensions:
      health_check:
        check_collector_pipeline:
          enabled: true
          exporter_failure_threshold: 5
          interval: 5m
        endpoint: localhost:13133 // tried with 0.0.0.0:13133 -> same error
```
