### ISSUE TITLE
value and from_context not working for header_setter otel extension.

### ISSUE THREAD

**Issue by kadhamecha-conga** [open-telemetry/opentelemetry-collector-contrib#24682]
### Component(s)

exporter/loki, extension/headerssetter

### What happened?

hi team,

i'm not able to set value of resource attributes which are passes in header from agent.
we have agents and collector architecture, where agent is configured to set header level values as  X-Scope-OrgID as env name and those are used at collector level to looked up from the value property of the extension configuration.

I tried with value and  from_context in collector level , but folder  are not creating in s3 as per values set in tenant_id , i'm trying to achieve multi tenant for whole (LGTM) as per dynamic header value? 

how to can we check if header values are set? ( i'm using  logging exporter with  verbosity: detailed ) but it is not showing any header level values.

let me know, if you need more info.

thanks.

### Collector version

0.75.0

## Environment
kubernetes 1.24
otel agent and collector version: 0.75.0

### OpenTelemetry Collector configuration

```yaml
agent config: 

  extensions:
    headers_setter:
      headers:
        - action: upsert
          key: X-Scope-OrgID
          value: tenant_id

  processors:
    batch:
      timeout: 10s  
    resource/loki:
      attributes:
        - action: insert
          key: tenant_id
          value: test-env

  service:
    telemetry:
      metrics:
        address: 0.0.0.0:8888
    extensions:  
      - headers_setter
    pipelines:
      logs:
        exporters:
        - otlphttp
        - logging
        processors:
        - memory_limiter
        - resource/loki
        receivers:
        - otlp
        - filelog
```

collector config :

```
  exporters:
    otlphttp:
      endpoint: http://loki-loki-distributed-gateway/loki/api/v1/push
      auth:
        authenticator: headers_setter
      tls:
        insecure: false
        insecure_skip_verify: true

  extensions:
    headers_setter:
      headers:
        - action: upsert
          key: X-Scope-OrgID
          value: tenant_id ( from_context: X-Scope-OrgID ) << tried with both things.....
          
  receivers:
      otlp:
        protocols:
          grpc:
            include_metadata: true
          http:
            include_metadata: true
    extensions:
      - headers_setter
      - memory_ballast
    pipelines:
      logs:
        exporters:
        - otlphttp
        - logging
        processors:
        - memory_limiter
        receivers:
        - otlp
```

**Comment by mar4uk** [comment]
Did I understand it correctly: you have two collectors running. The first collector sends data to the second collector. Is it correct?

If so, the configuration of the first collector could look like this:
```
receivers:
  otlp:
    protocols:
      http:
extensions:
  headers_setter:
    headers:
      - action: insert
        key: X-Scope-OrgID
        value: test-env
exporters:
  otlphttp:
    endpoint: "http://otelcol:4318"
    auth:
      authenticator: headers_setter
service:
  extensions: [headers_setter]
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp]
```
The configuration of the second collector:
```
receivers:
  otlp:
    protocols:
      http:
        include_metadata: true
extensions:
  headers_setter:
    headers:
      - action: insert
        key: X-Scope-OrgID
        from_context: X-Scope-OrgID
exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    auth:
      authenticator: headers_setter
service:
  extensions: [headers_setter]
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [loki]
```

The first collector receives data in otlp format, sets header "X-Scope-OrgID: test-env" and exports data to the second collector. The second collector receives "X-Scope-OrgID: test-env" and propagates this header to Loki. Is it what you want to achieve? Let me know if it helps
