### ISSUE TITLE
[exporter/kafkaexporter] panic runtime error when not using SASL config

### ISSUE THREAD

**Issue by rcrowe** [open-telemetry/opentelemetry-collector-contrib#24797]
### Component(s)

exporter/kafka

## Description

Kafka exporter will attempt to validate SASL config even when it's not present; likely introduced as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21075

`validateSASLConfig` is being called with nil generating a runtime panic.

## Steps to Reproduce

Configure Kafka exporter with TLS auth & start the collector...

```yaml
exporters:
  kafka:
    protocol_version: 2.6.0
    brokers:
      - <snip>
    auth:
      tls:
        ca_file: /kafka-client-certificate/ca.crt
        cert_file: /kafka-client-certificate/tls.crt
        key_file: /kafka-client-certificate/tls.key
        reload_interval: 1h
```

## Expected Result

When SASL auth configuration is not defined, validation is skipped & no error is generated.

## Actual Result

Starting the collector will raise...

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x327b638]

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter.validateSASLConfig(0xc000e840c8?)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter@v0.82.0/config.go:107 +0x18
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter.(*Config).Validate(0xc0003dd400)
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter@v0.82.0/config.go:103 +0x6b
```

### Collector version

v0.82.0

### Environment information

k8s v1.27.2

### Additional context

PR addressing the issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24798
