### ISSUE TITLE
[receiver/kubeletstatsreceiver] Some metrics are not being fetched

### ISSUE THREAD

**Issue by SamerJ** [open-telemetry/opentelemetry-collector-contrib#24833]
### Component(s)

receiver/kubeletstats

## Description

Hello,

When trying to use the receiver, I've noticed I get all the metrics except for "k8s.node.network.io" & "k8s.node.network.errors".
Although these metrics are documented to be available (by default).
I tried to explicitly enable it to see if that will make a difference, but to no avail.

Any help is appreciated.

## Steps to Reproduce
Launch the receiver and check if you can find any of the 2 metrics "k8s.node.network.io" & "k8s.node.network.errors"

## Expected Result
All metrics in the documentation to be present.

### Collector version

0.75.0

### Environment information

Ubuntu 22.04.2 LTS

### OpenTelemetry Collector configuration

```yaml
receivers:
  kubeletstats:
    auth_type: "kubeConfig"
    collection_interval: 10s
    endpoint: "NODE_NAME"
    metric_groups:
      - container
      - pod
      - node
      - volume
    # Tried with and without the below
    metrics:
      k8s.node.network.errors:
        enabled: true
      k8s.node.network.io:
        enabled: true

....
```
