### ISSUE TITLE
[pkg/stanza] New operator for removing multiple fields.

### ISSUE THREAD

**Issue by nityanandagohain** [open-telemetry/opentelemetry-collector-contrib#24893]
### Is your feature request related to a problem? Please describe.

As of now to remove multiple fields we have to use the `remove` operator multiple times for each field.

### Describe the solution you'd like

We should have an operator which can remove multiple fields and takes any array of field as an input.

**Comment by djaglowski** [comment]
We used to have an operator which could perform multiple actions like this. It was a bit more generalized and encompassed `add`, `copy`, `move`, `remove`, `retain`, and `flatten`. The problem ended up being that it was difficult to define the scope of its intended use. We decided that it was clearer to make these simple manipulations as atomic as possible, since they can always be sequenced as necessary.

I can appreciate that `remove` is the simplest of all of these and that it _could_ easily be extended to support multiple fields, but I don't see a clear reason why we wouldn't then expect to do the same for the others as well. Personally, I don't think this ambiguity is worth the slightly more concise configuration:

```yaml
operators:
  - type: remove
    field: foo
  - type: remove
    field: bar
  - type: remove
    field: hello
  - type: remove
    field: world

operators:
  - type: remove
    fields: 
      - foo
      - bar
      - hello
      - world
```

Is there some criteria which would also apply to the other operations, that would clearly define which of these actions should be able repeatable within a single operator?
