### ISSUE TITLE
Tail Sampling Processor is using async spans to count the latency duration

### ISSUE THREAD

**Issue by tonidas** [open-telemetry/opentelemetry-collector-contrib#24912]
### Component(s)

processor/tailsampling

## Description
Tail Sampling Processor can sample more traces than it should, if there are async activity on the end of the request trace

## Steps to Reproduce
Send a request trace that has Kafka async producing at the end of the request (that will finish after the response was already sent). Lets assume that the request had 5ms of execution time, and that the kafka production had 500ms of execution time.

## Expected Result
If the Tail Sampling Processor is configured with a latency threshold of 10ms, I expect that this trace doesn't get sampled

## Actual Result
If the Tail Sampling Processor is configured with a latency threshold of 10ms, this trace will get sampled

### Collector version

v0.8.x

## Environment
OS: Amazon Linux 2
Compiler(if manually compiled): N/A

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 7000
    spike_limit_mib: 1400
  batch:
    send_batch_size: 2000
    timeout: 1s
  tail_sampling:
    decision_wait: 30s
    num_traces: 2000000
    policies:
      [
        {
          name: main-policy,
          type: latency,
          latency: { threshold_ms: 80 }
        }
      ]

exporters:
  otlp/elastic:
    endpoint: "${ELASTICSEARCH_APM_HOST}"
    headers:
      Authorization: "Bearer ${ELASTICSEARCH_APM_TOKEN}"
    sending_queue:
      enabled: true
      queue_size: 1000000
      num_consumers: 20
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_elapsed_time: 10m

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, tail_sampling, batch ]
      exporters: [ otlp/elastic ]
```

### Additional context

Right now I'm running a dirty otel-collector-contrib using a patch to ignore kafka producing spans on Tail Sampling Processor latency duration calculation, but it's not generic enough to be pull-requested. Is there a broad way of detecting async spans?

I think that the best approach it's to provide a configuration for the user to choose between those two approaches and the default one should be to ignore the async spans. The mindset here is that it's much more straightforward to think about the latency as the duration of the request lifetime.
