### ISSUE TITLE
Error parsing ISO 8601 timestamp format

### ISSUE THREAD

**Issue by arpitjindal97** [open-telemetry/opentelemetry-collector-contrib#24922]
### Component(s)

pkg/stanza

## Description
I have a json log file. Each log has a timestamp of ISO 8601 format.

ex: `{"type": "server", "timestamp": "2023-04-07T20:43:56,833+02:00"}`

I'm unable to parse it. So far, the closest I have got it:

```
    operators:
      - type: json_parser
        parse_to: body
        timestamp:
          parse_from: body.timestamp
          layout: '%Y-%m-%dT%H:%M:%S,%f%z'
```

Ideally `%z` should be capable to parse `±HHMM` or `±HH:MM` but it is not accepting the colon.

## Steps to Reproduce

Create a log file with above timestamp field value and try to parse it like I mentioned in the config.

## Expected Result

Timestamp should be parsable

## Actual Result

Runtime exception

```
2023-08-05T20:39:53.901Z        error   helper/transformer.go:99        Failed to process entry {"kind": "receiver", "name": "filelog/elasticsearch", "data_type": "logs", "operator_id": "json_parser", "operator_type": "json_parser", "error": {"description": "time parser: parsing time \"2023-08-05T22:18:53,248+02:00\" as \"2006-01-02T15:04:05,999999-0700\": cannot parse \"+02:00\" as \"-0700\""}
```

### Collector version

v0.82.0

## Environment
OS: Centos 7
Arch: amd64
Docker Image: otel/opentelemetry-collector-contrib:0.82.0
