### ISSUE TITLE
[receiver/postgresqlreceiver] password with `$` doesn't work when passed via `${env:DB_PASSWORD}`

### ISSUE THREAD

**Issue by wand2016** [open-telemetry/opentelemetry-collector-contrib#25107]
### Component(s)

receiver/postgresql

## Steps to Reproduce

1. Prepare PostgreSQL DB:
   - username: `user`
   - password: `p@s$w0rd`
2. Configure postgresql receiver:

```yaml
  postgresql:
    ...
    username: "${env:DB_USERNAME}"
    password: "${env:DB_PASSWORD}"
```

3. Pass environment variables to OpenTelemetry CR:

```yaml
spec:
  ...
  env:
    - name: DB_USERNAME
      value: user
    - name: DB_PASSWORD
      value: p@s$w0rd
```

## Expected Result

Authentication passes.

## Actual Result

Authentication fails.

Given password directly, authentication passes.

```yaml
  postgresql:
    ...
    username: "${env:DB_USERNAME}"
    password: "p@s$$w0rd"
```

### Collector version

otel/opentelemetry-collector-contrib:0.81.0

## Environment

contrib Docker Image

**Comment by mx-psi** [comment]
The Collector supports recursively expanding `${env:...}` and the legacy `$ENV` syntax in the contents of an environment variable, so you need to escape the `$` as documented on [the official docs][1]:

> Use $$ to indicate a literal $.

In your case this would be `p@s$$w0rd`

[1]: https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables

**Comment by wand2016** [comment]
Thanks for replying!

Actually, the password is stored in a Secret resource:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
...
spec:
  config: <configuration mentioned above>
  env:
    - name: DB_PASSWORD   
      valueFrom:
        secretKeyRef:
          name: db-secrets
          key: password
```

(By the way, the Secret resource is synchronized by ExternalSecret Operator in my project.)

Must it be stored in the Secret resource (or secret backend) as escaped `p@s$$w0rd`?  
This couples the secrets and opentelemetry collector, which makes reuse hard.  
Is there any way to disable recursive expanding?
