### ISSUE TITLE
[cmd/mdatagen] Ability to filter by resource attribute values

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#25134]
There are some scenarios when scrapers emit metrics for too many different resource attributes. We need to introduce a configuration interface generated and applied to every item in `resource_attributes` section that users can use to reduce the set of emitted resource attribute metrics.

We already have an option to disable resource attributes like this:

```
resource_attributes:
  process.command_line:
    enabled: false
```

We can add an option to filter resource metrics in the same configuration section.

So user can do the following:

```
resource_attributes:
  process.command_line:
    include:
      - "/home/dir/*"
  process.owned:
    exclude:
      - "root"
```

The exact filtering interface is still to be defined. 

Originally suggested in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8188#issuecomment-1480424446

**Comment by dmitryax** [comment]
For the include/exclude config interface, we need to stick to the new standardized approach proposed in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25161. People are more in favor of option B, but we still have time to reconsider it.

**Comment by dmitryax** [comment]
> We still have the open question around what do we do with types such as int, double, bool, bytes, slice and map?

I think those should only accept `strict` filtering

**Comment by dmitryax** [comment]
@andrzej-stencel I understand that some complicated use cases might not be covered by this interface. And I don't think we need to aim for that. Any complicated use case can be solved by adding the filter processor. 

The intent behind this issue is to provide a simple interface to control what resources are "allowed" to emit metrics. It'll be a pretty important feature for scraping receivers collecting data with many resources. 

For example, in the k8scluster receiver, if I want to simply exclude all metrics from the `kube-*` namespaces I can easily do 
```
receivers:
  k8scluster:
    resource_attributes:
      k8s.cluster.name:
        metrics_exclude:
          - regex: kube-.*
```

which seems pretty straight-forward to use compared to

```
receivers:
  k8scluster:
    metrics:
      include:
        resource:
          - '!IsMatch(attributes["k8s.cluster.name"], "kube-.*")'
```

I see two problems with the approach you suggest:
1. Users have to type attributes as strings which is error-prone, if an attribute is renamed it's easy to miss updating the string.
2. The `metrics` config section has metric names as keys. Adding `include` or `include_filter` creates confusion and restricts metrics with the same name, even if it's unlikely a component will have an `include` metric.
