### ISSUE TITLE
[pkg/stanza] render embedded expression: reflect: call of reflect.Value.Call on map Value (1:1)

### ISSUE THREAD

**Issue by omrozowicz-splunk** [open-telemetry/opentelemetry-collector-contrib#25163]
### Component(s)

pkg/stanza

## Description

We're using filelog receiver to gather logs from Kubernetes, after migrating to `0.82.0` some customers filed a question/issue like this: https://github.com/signalfx/splunk-otel-collector-chart/issues/881, `EXPR(env["K8S_NODE_NAME"])` started to return an error.

## Steps to Reproduce

Create filelog receiver with `resource` to be `EXPR(env["K8S_NODE_NAME"])`:

```
  filelog/test:
    include:
    - /log.txt
    include_file_name: false
    include_file_path: true
    resource:
      com.splunk.sourcetype: kube:test
      host.name: EXPR(env["K8S_NODE_NAME"])
    start_at: beginning
    storage: file_storage
```
And write something in `/log.txt` file

## Expected Result

Data being received and processed by otel.

## Actual Result

```
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Reader).ReadToEnd
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.82.0/fileconsumer/reader.go:111
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.82.0/fileconsumer/file.go:163
2023-08-09T09:35:39.898Z        error   fileconsumer/reader.go:111      process: %w     {"kind": "receiver", "name": "filelog/audit-log-openshift-apiserver", "data_type": "logs", "component": "fileconsumer", "path": "/var/log/openshift-apiserver/audit.log", "error": "create entry: add resource keys to entry: render embedded expression: reflect: call of reflect.Value.Call on map Value (1:1)\n | env(\"K8S_NODE_NAME\")\n | ^"}
```

### Collector version

0.82.0

## Environment
OS: Ubuntu 20.04

### Additional context

I've seen this issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24575, it is for sure connected. I thought after this fix https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24648 there's no breaking change on the configuration side.
