### ISSUE TITLE
[receiver/httpcheck] no timestamp bug

### ISSUE THREAD

**Issue by BominRahmani** [open-telemetry/opentelemetry-collector-contrib#25167]
## Description
There seems to be a bug in HTTPCheckReceiver where one of the metrics "httpcheck.duration" doesn't report a timestamp when testing against multiple targets. This can be seen here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/b7b4c81722b76698ab2fe2f736e58fa641b78629/receiver/httpcheckreceiver/testdata/expected_metrics/multiple_targets.yaml#L18C14-L18C14
<img width="1147" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/38274348/cdec9b01-fd73-4b5c-b093-368dd3415640">

## Expected Result
There should be a timeUnixNano fields for this metric.
### Collector version

0.82.0

## Environment
OS: Darwin

**Comment by codeboten** [comment]
Thanks for opening the issue, @srikanthccv would you have time to look at this issue?

**Comment by srikanthccv** [comment]
Sure, please assign this to me

**Comment by codeboten** [comment]
Thanks @srikanthccv! Assigned

**Comment by srikanthccv** [comment]
I looked into it. I don't think there is any bug. The tests don't have timestamps as they keep changing. You can see use of `pmetrictest.IgnoreTimestamp` and `pmetrictest.IgnoreStartTimestamp()` in several places. The tests would still pass if you removed all instance of `timeUnixNano` and `startTimeUnixNano` in the file. 

@BominRahmani do you not see the data when running the collector, or did you assume it was a bug because the testdata file didn't have them?


```
receivers:
  httpcheck:
    targets:
      - endpoint: http://example.com
        method: GET
      - endpoint: http://google.com
        method: GET
    collection_interval: 5s

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics/otlp:
      receivers: [httpcheck]
      processors: []
      exporters: [logging]
```
