### ISSUE TITLE
New component: YDB Exporter

### ISSUE THREAD

**Issue by gingersamurai** [open-telemetry/opentelemetry-collector-contrib#25186]
### The purpose and use-cases of the new component

>[YDB](https://ydb.tech/) is an open-source Distributed SQL Database that combines high availability and scalability with strong consistency and ACID transactions.

### Purpose
The purpose of this exporter is to extract telemetry to YDB.
- YDB is a distributed fault-tolerant database with support for vertical scaling out of the box, which is useful if a service has uneven load.
- YDB is already used as a [jaeger storage plugin](https://github.com/ydb-platform/jaeger-ydb-store).

### Use cases

- Analyse telemetry via YQL.
- Use [Grafana YDB datasource](https://github.com/ydb-platform/ydb-grafana-datasource-plugin) to make dashboards.

### Example configuration for the component

```yaml
exporters:  
  ydb:
    connection:
      dsn: "grpc://localhost:2136/local"
      credentials: 
        anonymous: true
  
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [ydb]
    metrics:
      receivers: [otlp]
      exporters: [ydb]
    logs:
      receivers: [otlp]
      exporters: [ydb]
```

### Telemetry data types supported

- traces
- metrics
- logs

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.
