### ISSUE TITLE
Improve Kubernetes Logs Collection Experience

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#25251]
### Component(s)

receiver/filelog

## Problem Statement

The Collector's solution for collecting logs from Kubernetes is the [Filelog Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver) and it can handle collection of Kubernetes Logs for most scenarios. But Filelog Receiver was created to be a generic solution and therefore does not take advantage of useful Kubernetes assumptions out-of-the-box.

At the moment to collector logs with the Filelog receiver the recommended configuration is:

```yaml
receivers:
filelog:
exclude: []
include:
- /var/log/pods/*/*/*.log
include_file_name: false
include_file_path: true
operators:
- id: get-format
  routes:
  - expr: body matches "^\\{"
    output: parser-docker
  - expr: body matches "^[^ Z]+ "
    output: parser-crio
  - expr: body matches "^[^ Z]+Z"
    output: parser-containerd
  type: router
- id: parser-crio
  regex: ^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
  timestamp:
    layout: 2006-01-02T15:04:05.999999999Z07:00
    layout_type: gotime
    parse_from: attributes.time
  type: regex_parser
- combine_field: attributes.log
  combine_with: ""
  id: crio-recombine
  is_last_entry: attributes.logtag == 'F'
  max_log_size: 102400
  output: extract_metadata_from_filepath
  source_identifier: attributes["log.file.path"]
  type: recombine
- id: parser-containerd
  regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
  timestamp:
    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
    parse_from: attributes.time
  type: regex_parser
- combine_field: attributes.log
  combine_with: ""
  id: containerd-recombine
  is_last_entry: attributes.logtag == 'F'
  max_log_size: 102400
  output: extract_metadata_from_filepath
  source_identifier: attributes["log.file.path"]
  type: recombine
- id: parser-docker
  output: extract_metadata_from_filepath
  timestamp:
    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
    parse_from: attributes.time
  type: json_parser
- id: extract_metadata_from_filepath
  parse_from: attributes["log.file.path"]
  regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$
  type: regex_parser
- from: attributes.stream
  to: attributes["log.iostream"]
  type: move
- from: attributes.container_name
  to: resource["k8s.container.name"]
  type: move
- from: attributes.namespace
  to: resource["k8s.namespace.name"]
  type: move
- from: attributes.pod_name
  to: resource["k8s.pod.name"]
  type: move
- from: attributes.restart_count
  to: resource["k8s.container.restart_count"]
  type: move
- from: attributes.uid
  to: resource["k8s.pod.uid"]
  type: move
- from: attributes.log
  to: body
  type: move
start_at: beginning
```

To a new user that is a lot of scary configuration that will take time to comprehend, and they also probably don't want to comprehend it, yet it has to live in their configuration. In the Collector Helm chart we hide this complexity behind a preset, but it can't handle all situations.

Here are a couple experiences I'd like to improve:
-  "Multi-tenancy" support.  The Filelog receiver is good at gathering all the logs at once and sending them down a pipeline, but it is not setup to collect logs for a specific namespace or pod and send that down a specific pipeline. To meet this requirement you must configure multiple instances of the filelogreceiver and duplicate all of the configuration, only changing the `include` section as needed.
    - I believe multiple instances of the receiver are needed, but it would be nice to reduce the amount of duplicate configuration. It would be nice to be able to quickly configure a k8s-specific filelogreceiver and add it to the appropriate pipeline
- No support for label selectors.  Although you can specify specific namespaces/pods/containers to collect by taking advantage of the log path, using label selectors to identify an object is a common practice in k8s.

Some of the solution might be in the helm chart and some might be in the file log receiver itself.  It is also possible this spawns a new k8s-specific receiver that is using stanza behind the scenes.

Ultimately, I am looking to improve the "easy path" solution for most users in Kubernetes.  I want to make it easier for user to collect logs for a specific subset of all the logs in the cluster and for it to be easier to configure multiple instances of the receiver to support different destinations. Packaging up all the Kubernetes assumptions into something like:

```yaml
receivers:
  filelog:
    forKubernetes: true
    include: 
      - /var/log/pods/my-namespace/*/*.log
```

or

```yaml
receivers:
  filelog/api-server:
    forKubernetes: true
    labelSelectors:
      - component=kube-apiserver,tier=control-plane
```

would be great.

**Comment by dmitryax** [comment]
There is no way to apply label selectors with filelog receiver because that information is not exposed on the file paths. The only way to do that is by fetching logs from k8s API, which adds significant load on the API and likely will significantly degrade the performance. This should not be part of filelog receiver. We have a proposal with another component for this purpose:  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24439. Feel free to take a look

**Comment by TylerHelmuth** [comment]
@dmitryax I agree, which is why I believe a possible outcome of this issue is a k8s-specific logs collection receiver.  It looks like the component you linked (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23339) is exactly that and would help the 2 experiences I want to solve.

**Comment by makas45** [comment]
We have also ended the same situation and would like to export the logs based on the namespace level.

**Comment by ChrsMark** [comment]
@dmitryax @TylerHelmuth +1 for this!

It would be nice if we can skip/exclude Pods' logfiles based on Pod's labels/annotations.

This is super useful when a user would like to use https://opentelemetry.io/docs/concepts/sdk-configuration/general-sdk-configuration/#otel_logs_exporter to collect the logs for specific instrumented apps while for the rest of the apps/Pods filelog receiver should handle the collection.

Without the option to skip/exclude specific Pod's logfiles based on metadata we end up having duplicate records.

**Comment by ChrsMark** [comment]
@TylerHelmuth I wonder if for this we could instead use the `receiver_creator` in order to populate `filelog` receiver configs dynamically.

Sth like that:

```
receivers:
  receiver_creator:
    watch_observers: [ k8s_observer ]
    receivers:
      filelog:
        rule: type == "pod" && labels["otel.logs.exporter"] == "otlp"
        config:
          ...
```

Note: I'm trying to make it work but without success yet but I'm posting the question already just to verify if that approach would be a no-go for any reasons.

**Comment by TylerHelmuth** [comment]
@ChrsMark I think that is an option for handling the multi-tenency solution, but I don't think it address these issues:
1. Still needing to configure the filelogreceiver multiple times 
2. The ability to select what pod logs to scrape based on selectors

**Comment by ChrsMark** [comment]
> @ChrsMark I think that is an option for handling the multi-tenency solution, but I don't think it address these issues:
> 
> 1. Still needing to configure the filelogreceiver multiple times

Maybe I miss sth here but `k8slog` receiver proposed at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/23339 would need to be configured multiple times as well so as to cover all the different filter combinations, right? Or it will have more explicit support for routing to specific pipelines somehow?


> 2. The ability to select what pod logs to scrape based on selectors

Won't a `rule` in the `receiver_creator` like `rule: type == "pod" && labels["componeney"] == "kube-apiserver"` be equivalent to

 ```yaml
labelSelectors:
      - component=kube-apiserver`
```
?


I'm just trying to understand what extra value the `k8slog` receiver will bring. However it's true that defining `filelog` receivers as part of the `receiver_creator` makes the configuration more complex and maybe hard to troubleshoot so maybe a more native approach would be preferable here.

Let me know what you think @TylerHelmuth. I'm also cc-ing @h0cheung who works on the `k8slog` proposal.

I'm also sharing my working example for reference:

<details>
<summary>daemonset.yaml</summary>

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: daemonset
spec:
  mode: daemonset
  serviceAccount:
  hostNetwork: true
  volumeMounts:
    - name: varlogpods
      mountPath: /var/log/pods
      readOnly: true
  volumes:
    - name: varlogpods
      hostPath:
        path: /var/log/pods
  config: |
    exporters:
      debug: {}
      logging: {}
      otlp/elastic:
        compression: none
        endpoint: http://fleet-server:8200
        tls:
          insecure: true
          insecure_skip_verify: true
    extensions:
      k8s_observer:
        auth_type: serviceAccount
        node: ${env:K8S_NODE_NAME}
        observe_pods: true
      health_check: {}
      memory_ballast:
        size_in_percentage: 40
    processors:
      batch: {}
      resource/k8s:
        attributes:
          - key: service.name
            from_attribute: app.label.component
            action: insert
      k8sattributes:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
          - container.id
          labels:
          - tag_name: app.label.component
            key: app.kubernetes.io/component
            from: pod
          - tag_name: logs.exporter
            key: otel.logs.exporter
            from: pod
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      receiver_creator:
        watch_observers: [ k8s_observer ]
        receivers:
          filelog:
            rule: type == "pod" && labels["otel.logs.exporter"] = "otlp"
            config: 
              exclude:
              - /var/log/pods/default_daemonset-opentelemetry-collector*_*/opentelemetry-collector/*.log
              include:
              - /var/log/pods/`namespace`_`name`*/*/*.log
              include_file_name: false
              include_file_path: true
              operators:
              - id: get-format
                routes:
                - expr: body matches "^{"
                  output: parser-docker
                - expr: body matches '^[^ Z]+ '
                  output: parser-crio
                - expr: body matches '^[^ Z]+Z'
                  output: parser-containerd
                type: router
              - id: parser-crio
                regex: ^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
                timestamp:
                  layout: 2006-01-02T15:04:05.999999999Z07:00
                  layout_type: gotime
                  parse_from: attributes.time
                type: regex_parser
              - combine_field: attributes.log
                combine_with: ""
                id: crio-recombine
                is_last_entry: attributes.logtag == 'F'
                max_log_size: 102400
                output: json_parser
                source_identifier: attributes['log.file.path']
                type: recombine
              - id: parser-containerd
                regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
                timestamp:
                  layout: '%Y-%m-%dT%H:%M:%S.%LZ'
                  parse_from: attributes.time
                type: regex_parser
              - combine_field: attributes.log
                combine_with: ""
                id: containerd-recombine
                is_last_entry: attributes.logtag == 'F'
                max_log_size: 102400
                output: json_parser
                source_identifier: attributes["log.file.path"]
                type: recombine
              - id: parser-docker
                output: json_parser
                timestamp:
                  layout: '%Y-%m-%dT%H:%M:%S.%LZ'
                  parse_from: attributes.time
                type: json_parser
              - type: json_parser
                if: 'body matches "^{.*}$"'
                severity:
                  parse_from: attributes.level
              start_at: end
    service:
      extensions:
      - health_check
      - k8s_observer
      pipelines:
        logs:
          exporters:
          - otlp/elastic
          processors:
          - k8sattributes
          - batch
          - resource/k8s
          receivers:
          - receiver_creator
``` 
</details>
