### ISSUE TITLE
Datadog processor/connector Should Support span_name_as_resource_name

### ISSUE THREAD

**Issue by gord02** [open-telemetry/opentelemetry-collector-contrib#25829]
### Component(s)

datadogprocessor & datadogconnector

## Description
When span_name_as_resource_name is enabled on DD exporter, we would get traces and trace metrics with different operation. It creates inconsistent view of the data. 

## Steps to Reproduce
1. instrument an application
2. Use the provided OTel Collector Configurations
3. View the sent over data in the backend

## Expected Result
The expected operation label is the operation type sent to the backend which is based on the application emitting data. 
## Actual Result
The result shown in the backend for operations label is: operation:io.opentelemtery.tomcat_10.0.server

### Collector version

v0.82.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  logging:
    verbosity: detailed
  datadog:
    traces:
      span_name_as_resource_name: true
    hostname: "otelcol-docker"
    api:
      site: us5.datadoghq.com
      key: ${DD_API_KEY}


processors:
  batch:
  datadog/processor:


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, datadog/processor]
      exporters: [datadog]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
```
