### ISSUE TITLE
Syslog Exporter Unavailable In Container Builds

### ISSUE THREAD

**Issue by TaylorWork** [open-telemetry/opentelemetry-collector-contrib#25833]
### Component(s)

exporter/syslog

### Describe the issue you're reporting

I've been trying to make use of the syslog exporter that was added in 0.78.0, however when deploying the docker image for [opentelemetry-collector-contrib](https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags), the syslog exporter doesn't seem to be available.

I've tried both the 0.78.0 container build and the 0.83.0 build, and both of them produce the below error.

```
* error decoding 'exporters': unknown type: "syslog" for id: "syslog" (valid values: [f5cloud opencensus logzio zipkin logging awscloudwatchlogs awsemf elasticsearch jaeger_thrift kafka logicmonitor prometheus awskinesis awsxray azuredataexplorer datadog dynatrace googlemanagedprometheus tanzuobservability otlp carbon clickhouse sentry alibabacloud_logservice jaeger prometheusremotewrite sapm otlphttp coralogix dataset googlecloud loki mezmo pulsar sumologic awss3 azuremonitor file googlecloudpubsub influxdb instana tencentcloud_logservice loadbalancing signalfx skywalking splunk_hec])
```

For the configuration I am following the guidance from the below:
* https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.83.0/exporter/syslogexporter
* https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.83.0/exporter/syslogexporter/examples/config_with_filelog_receiver.yaml

My config:

```
    extensions:
      file_storage/syslog:
        directory: /tmp/otc
        timeout: 10s
    exporters:
      syslog:
        network: tcp
        port: 514
        endpoint: syslog-endpoint.local
        format: rfc5424
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
        sending_queue:
          enabled: true
          storage: file_storage/syslog
    receivers:
      otlp/container-logs:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
        operators:
          - type: syslog_parser
            protocol: rfc5424
      otlp/other-logs:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4318"
        operators:
          - type: syslog_parser
            protocol: rfc5424
    service:
      extensions:
        - file_storage/syslog
      pipelines:
        logs:
          exporters:
            - syslog
          receivers:
            - otlp/container-logs
            - otlp/other-logs
```
