### ISSUE TITLE
Add support for Metrics Slices to ottl len converter

### ISSUE THREAD

**Issue by markdingram** [open-telemetry/opentelemetry-collector-contrib#25868]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

An enhancement to the recent Len converter added in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24420 to handle the slice types in pmetric.

Use case is along the lines of:

```
transform:
  metric_statements:
    - context: metric
      statements:
        - set(description, "too many buckets") where Len(data_points) > 10
```

### Describe the solution you'd like

Extend the switch in [computeLen](https://github.com/jack-berg/opentelemetry-collector-contrib/blob/7a541c2fdb89729d073850110222bf1f475f5e3b/pkg/ottl/ottlfuncs/func_len.go) to handle the pmetric Slice cases:

```
case pmetric.NumberDataPointSlice:
	return int64(valType.Len()), nil
case pmetric.HistogramDataPointSlice:
	return int64(valType.Len()), nil
etc..
```

### Additional context

Happy to contribute the PR if this request is reasonable.
