### ISSUE TITLE
[processor/metricstransform] support value regex matching pattern when renaming label values

### ISSUE THREAD

**Issue by karmingc** [open-telemetry/opentelemetry-collector-contrib#25913]
### Component(s)

processor/metricstransform

### Is your feature request related to a problem? Please describe.

Currently, the metricstranform processor support renaming label values such as the following:
```yaml
# from https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor#rename-label-values
# rename the label value slab_reclaimable to sreclaimable, slab_unreclaimable to sunreclaimable
include: system.memory.usage
action: update
operations:
  - action: update_label
    label: state
    value_actions:
      - value: slab_reclaimable
        new_value: sreclaimable
      - value: slab_unreclaimable
        new_value: sunreclaimable
```

However, there might be situations where we want to use a regex matching pattern instead of a strict one. For example, when dealing with http.status_code, the range goes from 1xx to 5xx so adding these values 1 by 1 is long and can be error-prone. 

The goal is to reduce cardinality such as 200, 201, 202... to 2xx to reduce cardinality.

### Describe the solution you'd like

Potentially add a `value_match_type` field under the `operations` field. But open to suggestion.

### Describe alternatives you've considered

We can leverage the transform processor such as:
```yaml
  transform/metric:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - replace_pattern(attributes["http.status_code"], "\\b1\\d{2}\\b", "1xx")
          - replace_pattern(attributes["http.status_code"], "\\b2\\d{2}\\b", "2xx")
          - replace_pattern(attributes["http.status_code"], "\\b3\\d{2}\\b", "3xx")
          - replace_pattern(attributes["http.status_code"], "\\b4\\d{2}\\b", "4xx")
          - replace_pattern(attributes["http.status_code"], "\\b5\\d{2}\\b", "5xx")
```
