### ISSUE TITLE
[exporter/awsemf] batch requests to fit AWS EMF guidelines in CloudWatch

### ISSUE THREAD

**Issue by abarganier** [open-telemetry/opentelemetry-collector-contrib#26073]
### Component(s)

exporter/awsemf

## Description

This is a recreation of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16186, which for some reason lost momentum and eventually went unanswered.

Has something already been implemented to fix this? If so please note here and we can close. Otherwise, this is a frustrating experience to those using the exporter in real world use cases (> 100 metrics).

---

When attempting to use the awsemfexporter to send metrics data to Amazon CloudWatch, we encountered cryptic issues on the AWS CloudWatch side once the data was ingested. We could see the log payloads in CloudWatch containing the EMF logs containing the metric payloads, but we were unable to successfully plot the data on any timeseries chart.

Nothing in Amazon CloudWatch gave us any clue as to what the cause of the issue was.

It wasn't until we got in touch with AWS support (thankfully, we have a support contract that made this process quick & easy!) that we learned of a crucial requirement for *how* metrics are sent using the EMF format:

> when you declare metrics on the log event within "Metrics" section - this section can have up to 100 metric definition objects which means that you can have up to 100 metrics defined in that section. This array MUST NOT contain more than 100 MetricDefinition objects. For the majority of the log events that you have provided I can see either 105 or 132 metrics defined so these are invalid by the "Metrics" section having more than 100 objects.

This max size requirement is not documented in the awsemfexporter, nor anywhere else that we could find on the internet. What this means is that if you have more than 100 metrics you wish to export using the awsemfexporter, it seems like the batchprocessor is a *requirement* if you wish to do anything with your data in CloudWatch.

## Expected Result

The awsemfexporter should implement batching by default to impose its own size limits on the number of metric definitions sent in a single payload. 

We've managed to get things working in CloudWatch using the batchprocessor in the meantime, but from what we can tell, our batch sizes are not optimal.

For example, we configured batchprocessor with a `send_batch_max_size` and `send_batch_size` of `100` to match the max # of metrics per payload, and a large timeout (e.g. `120s`). We then sent metric payloads of 250+ metrics through the pipeline every ~30s, and noticed that the resulting log events received in Amazon CloudWatch contained a number of metrics much less than 100 for each payload (for example, batches of 20-50 metrics per log event).

Considering that the PutLogEvents API used by the awsemfexporter costs money *per-API call*, this means we're wasting money with these sub-optimal batch sizes. What's the recommended configuration to optimize batch sizes to reach the 100 metrics per-request limit?

### Collector version

v0.5.0

## Environment
Linux/.Ubuntu

### OpenTelemetry Collector configuration

```yaml
## Example
receivers:
  otlp:
    protocols:
      grpc: {}
processors:
  batch/cloudwatch:
    timeout: 60s
    send_batch_size: 90
    send_batch_max_size: 100
exporters:
  awsemf:
    log_group_name: my-log-group
    log_stream_name: my-metrics-stream
    namespace: my-metrics
    dimension_rollup_option: NoDimensionRollup
    role_arn: ${CLOUDWATCH_ROLE_ARN}
    region: us-east-1
service:
  pipelines:
    metrics/cloudwatch:
      receivers:
      - otlp
      processors:
      - batch/cloudwatch
      exporters:
      - awsemf
```
