### ISSUE TITLE
Opentelemetry collector memory leak/non-optimized GC

### ISSUE THREAD

**Issue by yehaotian** [open-telemetry/opentelemetry-collector-contrib#26087]
### Component(s)

exporter/loadbalancing

## Description
We observe opentelemetry collector load balancing layer memory leak which will trigger OOM killed for nomad jobs restart.
The Mem metrics for high load region:

![Screenshot 2023-08-23 at 4 32 26 PM](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17459153/97a1e834-5ed4-4d07-b0c2-e112e0f78349)

pprof top 10 resutls:
--inuse_space:
```
      flat  flat%   sum%        cum   cum%
 2198.65MB 60.34% 60.34%  2198.65MB 60.34%  google.golang.org/grpc/internal/transport.newBufWriter (inline)
  972.33MB 26.68% 87.02%   972.33MB 26.68%  go.uber.org/zap/zapcore.newCounters
  142.02MB  3.90% 90.92%   142.02MB  3.90%  bufio.NewReaderSize (inline)
   75.63MB  2.08% 92.99%    75.63MB  2.08%  bytes.growSlice
   41.43MB  1.14% 94.13%    51.56MB  1.41%  compress/flate.NewWriter
   38.90MB  1.07% 95.20%    38.90MB  1.07%  go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewBoundedMemoryQueue
   22.09MB  0.61% 95.80%    22.09MB  0.61%  golang.org/x/net/http2/hpack.(*headerFieldTable).addEntry
   20.76MB  0.57% 96.37%    20.76MB  0.57%  golang.org/x/net/http2.(*Framer).startWriteDataPadded
       2MB 0.055% 96.43%  2258.75MB 61.98%  google.golang.org/grpc/internal/transport.newHTTP2Client
    1.50MB 0.041% 96.47%    77.13MB  2.12%  bytes.(*Buffer).grow
```
--inuse_objects:
```
      flat  flat%   sum%        cum   cum%
    131074 15.39% 15.39%     163842 19.24%  google.golang.org/grpc/internal/grpcutil.EncodeDuration
     40345  4.74% 20.13%      40345  4.74%  runtime.malg
     38232  4.49% 24.61%      38232  4.49%  google.golang.org/grpc/internal/transport.(*controlBuffer).get
     32774  3.85% 28.46%      32774  3.85%  strconv.formatBits
     32769  3.85% 32.31%      32769  3.85%  fmt.Sprintf
     32769  3.85% 36.16%      32769  3.85%  google.golang.org/grpc/internal/channelz.newIdentifer
     32768  3.85% 40.00%      32768  3.85%  go.opentelemetry.io/otel/metric/noop.MeterProvider.Meter
     26216  3.08% 43.08%      26216  3.08%  context.newCancelCtx
     21846  2.56% 45.65%      21846  2.56%  google.golang.org/grpc/internal/buffer.NewUnbounded
     21846  2.56% 48.21%      21846  2.56%  google.golang.org/grpc/internal/transport.NewServerTransport.func3
```

The Mem metrics for low load region:
![Screenshot 2023-08-23 at 4 33 05 PM](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17459153/c91fa15e-648b-4fa4-9d5e-46927868f8e0)

So we are not sure if GC for go is not functioning well or there is an actual mem leak.

### Collector version

0.83.0

## Environment
nomad + docker

### OpenTelemetry Collector configuration

```yaml
receivers:
  jaeger/withendpoint:
    protocols:
      grpc:
        endpoint: {{env "NOMAD_HOST_ADDR_jaeger_grpc_receiver_port"}}

  otlp/httpendpoint:
    protocols:
      http:
        endpoint: {{env "NOMAD_HOST_ADDR_oltp_http_receiver_port"}}

  otlp/grpcendpoint:
    protocols:
      grpc:
        endpoint: {{env "NOMAD_HOST_ADDR_oltp_grpc_receiver_port"}}

exporters:
  logging:
  
  loadbalancing:
    protocol:
      otlp:
        keepalive:
          time: 30s
          timeout: 20s
        timeout: 30s
        tls:
          insecure: true
        sending_queue:
          queue_size: 1500
    resolver:
      static:
        hostnames:
{{ range service "${otel_collector_backend_service_name}" }}
        - {{.Address}}:{{.Port}}
{{ end }}

processors:
  batch:
    send_batch_size: 5000
    send_batch_max_size: 7000

  filter/span:
    error_mode: ignore
    traces:
      span:
        - 'IsMatch(attributes["path"], ".*[h|H]ealth.*") == true'
        - 'IsMatch(name, ".*\\.[h|H]ealth.*") == true'
        - 'IsMatch(attributes["action"], ".*[h|H]ealth.*") == true'
      spanevent:
        - 'name == "message"'

extensions:
  health_check/withendpoint:
    endpoint: :{{env "NOMAD_HOST_PORT_health_check_extension_port"}}
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5
  pprof/withendpoint:
    endpoint: :{{env "NOMAD_HOST_PORT_pprof_port"}}

service:
  extensions: [ health_check/withendpoint, pprof/withendpoint ]

  telemetry:
    logs:
      level: ${telemetry_log_level}
      encoding: json
    metrics:
      level: detailed
      address: :{{env "NOMAD_HOST_PORT_metrics_port"}}

  pipelines:
    traces:
      receivers: [ jaeger/withendpoint, otlp/httpendpoint, otlp/grpcendpoint ]
      processors: [ filter/span, batch ]
      exporters: [ loadbalancing ]
```

### Additional context

We are using Nomad signal change_mode to re-render template when backend otel collector list get updated. And everytime there is a signaling re-render, there will be a mem jump.

![Screenshot 2023-08-23 at 5 00 52 PM](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17459153/c5f2f77e-c45e-4d66-8618-6b97f30e64e8)

![Screenshot 2023-08-23 at 4 47 28 PM](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17459153/1a3e3f1a-1bcc-45f7-9df5-56c15dfa002d)
