### ISSUE TITLE
Datadog panic's and OTEL collector crashes for empty ExponentialHistogram

### ISSUE THREAD

**Issue by lenin-jaganathan** [open-telemetry/opentelemetry-collector-contrib#26103]
### Component(s)

exporter/datadog

## Description
When an empty exponential Histogram is sent with empty buckets, the datadog exporter panic's and crashes the OTEL Collector (using the latest collector-contirb v0.83.0).

## Steps to Reproduce
Export a metric datapoint with the below information,
```
Metric #0
Descriptor:
     -> Name: test_exponential_histogram
     -> Description: Test histogram with empty values
     -> Unit: byte
     -> DataType: ExponentialHistogram
     -> AggregationTemporality: Delta
ExponentialHistogramDataPoints #0
StartTimestamp: 2023-08-25 10:41:00 +0000 UTC
Timestamp: 2023-08-25 10:41:10 +0000 UTC
Count: 0
Sum: 0.000000
Max: 0.000000
Min: 0.000000
```
## Expected Result
Datapoint with value 0 to be sent to the back-end or Datapoint to be dropped gracefully

## Actual Result
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x3746eac]

goroutine 110 [running]:
github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics.(*Translator).mapExponentialHistogramMetrics(0xc0004cbe30, {0x922d858, 0xc000d4b5c0}, {0x9215dc0, 0xc000d74ea0}, 0xc0011f30c8, {0x0?}, 0x1)
        github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics@v0.7.0/exponential_histograms_translator.go:158 +0xe2c
github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics.(*Translator).mapToDDFormat(0xc0004cbe30, {0x922d858, 0xc000d4b5c0}, {0x1016350?}, {0x9215dc0?, 0xc000d74ea0?}, {0xc000d9e440, 0x1, 0x4}, {0xc00069d1a0, ...}, ...)
        github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics@v0.7.0/metrics_translator.go:774 +0xc68
github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics.(*Translator).MapMetrics(0xc0004cbe30, {0x922d858, 0xc000d4b5c0}, {0x0?}, {0x9215dc0, 0xc000d74ea0?})
        github.com/DataDog/opentelemetry-mapping-go/pkg/otlp/metrics@v0.7.0/metrics_translator.go:716 +0x97c
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter.(*metricsExporter).PushMetricsData(0xc000c85d40, {0x922d858, 0xc000d4b5c0}, {0xc000de4e10?})
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.83.0/metrics_exporter.go:208 +0x20d
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter.(*metricsExporter).PushMetricsDataScrubbed(0xc000c85d40, {0x922d858?, 0xc000d4b5c0?}, {0x0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter@v0.83.0/metrics_exporter.go:181 +0x28
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).Export(0x0?, {0x922d858?, 0xc000d4b5c0?})
        go.opentelemetry.io/collector/exporter@v0.83.0/exporterhelper/metrics.go:54 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000ee2018, {0x9256d30, 0xc000e03560})
        go.opentelemetry.io/collector/exporter@v0.83.0/exporterhelper/common.go:197 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc000ede460, {0x9256d30?, 0xc000e03560?})
        go.opentelemetry.io/collector/exporter@v0.83.0/exporterhelper/queued_retry.go:355 +0x190
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send(0xc000c8ade0, {0x9256d30, 0xc000e03560})
        go.opentelemetry.io/collector/exporter@v0.83.0/exporterhelper/metrics.go:125 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1({0x9256d30, 0xc000e03560})
        go.opentelemetry.io/collector/exporter@v0.83.0/exporterhelper/queued_retry.go:195 +0x39
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1()
        go.opentelemetry.io/collector/exporter@v0.83.0/exporterhelper/internal/bounded_memory_queue.go:47 +0xb6
created by go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers
        go.opentelemetry.io/collector/exporter@v0.83.0/exporterhelper/internal/bounded_memory_queue.go:42 +0x45
```

### Collector version

0.83.0

## Environment
OS: MacOs/Ubuntu

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
  zpages:
    endpoint: 0.0.0.0:55679
receivers:
  otlp:
    protocols:
      grpc:
      http:
  zipkin:
processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_mib: 8000
    spike_limit_mib: 2000
exporters:
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 10
  datadog:
    hostname: somehost
    metrics:
      endpoint: https://somehost
    api:
      key: <key>
    tls:
      insecure_skip_verify: true
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
  extensions: [health_check, zpages]
```
