### ISSUE TITLE
failed to build pipelines: failed to create "kafka" receiver for data type "traces": unrecognized encoding

### ISSUE THREAD

**Issue by withlin** [open-telemetry/opentelemetry-collector-contrib#26116]
### Component(s)

exporter/elasticsearch, receiver/kafka

## Description
```
collector server run finished with error: failed to build pipelines: failed to create "kafka" receiver for data type "traces": unrecognized encoding
```
## Steps to Reproduce
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otlp-collector
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-contrib:0.83.0
  config: |
    receivers:
      kafka:
        brokers:
          - kafka-0.kafka-headless.kafka.svc.cluster.local:29092
          - kafka-1.kafka-headless.kafka.svc.cluster.local:29092
          - kafka-2.kafka-headless.kafka.svc.cluster.local:29092
        topic: otel
        encoding: otlp_json
        protocol_version: 2.0.0
    processors:
    exporters:
      elasticsearch/1:
        endpoints: [http://es-es-internal-http.otel.svc:9200]
        traces_index: test
        user: "elastic"
        password: "xxxx"
        tls:
          insecure: false
          insecure_skip_verify: false
    service:
      pipelines:
        traces/2:
          receivers: [kafka]
          exporters: [elasticsearch/1]
```

## Expected Result
can support  encoding ` otlp_json`
## Actual Result
```
Error: failed to build pipelines: failed to create "kafka" receiver for data type "traces": unrecognized encoding
2023/08/28 13:23:23 collector server run finished with error: failed to build pipelines: failed to create "kafka" receiver for data type "traces": unrecognized encoding
```

### Collector version

opentelemetry-collector-contrib:0.83.0

## Environment
OS: (e.g., "Redhat 8.0")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otlp-collector
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-contrib:0.83.0
  config: |
    receivers:
      kafka:
        brokers:
          - kafka-0.kafka-headless.kafka.svc.cluster.local:29092
          - kafka-1.kafka-headless.kafka.svc.cluster.local:29092
          - kafka-2.kafka-headless.kafka.svc.cluster.local:29092
        topic: otel
        encoding: otlp_json
        protocol_version: 2.0.0
    processors:
    exporters:
      elasticsearch/1:
        endpoints: [http://es-es-internal-http.otel.svc:9200]
        traces_index: test
        user: "elastic"
        password: "xxxx"
        tls:
          insecure: false
          insecure_skip_verify: false
    service:
      pipelines:
        traces/2:
          receivers: [kafka]
          exporters: [elasticsearch/1]
```

### Log output

```shell
2023/08/28 13:23:23 collector server run finished with error: failed to build pipelines: failed to create "kafka" receiver for data type "traces": unrecognized encoding
```
