### ISSUE TITLE
[exporter/newrelic] instrumentation.provider attribute is missing

### ISSUE THREAD

**Issue by F21** [open-telemetry/opentelemetry-collector-contrib#2621]
**Describe the bug**
According to the opentelemetry spec for new relic, there should be an `instrumentation.provider` attribute:https://github.com/newrelic/newrelic-exporter-specs/blob/master/opentelemetry/OpenTelemetry-Spans.md

This appears to be missing in the exporter and spans sent to new relic are missing this attribute.

**Steps to reproduce**
1. Instrument an app (I used the Go SDK)
2. Point the app to use an opentelemetry collector with the new relic exporter.
3. Filter entities in the explorer with `instrumentation.provider = opentelemetry` and see that the entities do not show up.

**What did you expect to see?**
Spans sent to new relic should have the `instrumentation.provider` attribute set.

**What did you see instead?**
The `instrumentation.provider` attribute was not set.

**What version did you use?**
v0.21.0

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:
processors:
  batch:
exporters:
  newrelic:
    apikey: NEW_RELIC_KEY_GOES_HERE
    timeout: 30s
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [newrelic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [newrelic]
```

**Environment**
OS: Minikube in docker mode
