### ISSUE TITLE
New component: AWS Lambda Telemetry API Receiver

### ISSUE THREAD

**Issue by driverpt** [open-telemetry/opentelemetry-collector-contrib#26254]
### The purpose and use-cases of the new component

To be able to Stream Logs and Telemetry directly from AWS Lambda API

https://docs.aws.amazon.com/lambda/latest/dg/telemetry-api.html

### Example configuration for the component

```
receivers:
  awslambdatelemetry:
    subscription: # Optional (true | false) Default (true), this invokes the Subscribe to the Service
    port: # Optional (Integer)
    protocols:
      tcp:
      http:
```
### Telemetry data types supported

Traces, Metrics and Logs

### Is this a vendor-specific component?

- [x] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.
