### ISSUE TITLE
Some metrics are missing from the kubeletstats receiver

### ISSUE THREAD

**Issue by chenlujjj** [open-telemetry/opentelemetry-collector-contrib#26300]
### Component(s)

receiver/kubeletstats

### Describe the issue you're reporting

Hi Team,

We are using the kubeletstats receiver to collect metrics of pods and containers. But we found that some metrics are missing.  For example, `container.memory.usage` is collected but `container.memory.page_faults` is missing. 

The collector version is 0.79.0 and we didn't exclude any metrics in filter processor.

The config for kubeletstats receiver is:
```
kubeletstats:
        auth_type: serviceAccount
        collection_interval: 10s
        endpoint: ${K8S_NODE_IP}:10250
        extra_metadata_labels:
        - container.id
        metric_groups:
        - container
        - pod
        - node
        - volume
```

We have also confirmed that the response of `/stats/summary` endpoint from kubelet do include container memory page faults infos using following command:
```
kubectl get --raw /api/v1/nodes/<node_name>:10250/proxy/stats/summary
```

Any suggestions would be much appreciated.
