### ISSUE TITLE
Azure Data Explorer Exporter - TraceId and SpanId property names have wrong mappings

### ISSUE THREAD

**Issue by akakarikos** [open-telemetry/opentelemetry-collector-contrib#26303]
### Component(s)

exporter/azuredataexplorer

## Description

The properties TraceId, SpanId, and ParentId for the ADX Logs and Traces tables, do not map to the properties emitted by the OTel collector for this exporter.

## Steps to Reproduce

Configure the OTel collector to export to ADX using the table schemas provided by the documentation.

## Expected Result

The TraceId, SpanId, and ParentId column names in the ADX Logs and Traces tables are populated with the correct values.

## Actual Result

The TraceId, SpanId, and ParentId column names in the ADX Logs and Traces tables are empty.

### Collector version

0.83.0

## Environment
Docker image deployed in AKS.
OS: linux amd64

### OpenTelemetry Collector configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |-
    receivers:
      zipkin:
        endpoint: localhost:9411
      otlp:
        protocols:
          grpc:
            endpoint: localhost:4317
          http:
            endpoint: localhost:4318
            
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 30

      batch:
        send_batch_size: 50
    
    exporters:
      logging:
        verbosity: detailed
    
      azuremonitor:
        instrumentation_key: 
        spaneventsenabled: true

      azuredataexplorer:
        cluster_uri: 
        application_id: 
        application_key: 
        tenant_id:
        db_name: 
        metrics_table_name: 
        logs_table_name: 
        traces_table_name: 
        ingestion_type : 'managed'
    
    service:
      pipelines:
        traces:
          receivers: [zipkin,otlp]
          processors: [memory_limiter,batch]
          exporters: [azuredataexplorer,azuremonitor,logging]
        logs:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [azuredataexplorer,azuremonitor,logging]
```

### Additional context

The workaround in order to fix this, is to use custom ingestion mappings that will map the TraceID to TraceId, SpanID to SpanId, and ParentID to ParentId.
