### ISSUE TITLE
Weird opentelemetry-collector errors

### ISSUE THREAD

**Issue by ghevge** [open-telemetry/opentelemetry-collector-contrib#26343]
### Component(s)

exporter/prometheus

### What happened?

I'm trying to set up opentelemetry-collector with prometheus, tempo and loki on a dockerize jave springboot 3 application.

I've managed to start all the containers, but once I generet some activity on my app, otel collector start to generate errors like bellow:

Any idea what could be causing this?

### Collector version

0.82.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  # batch metrics before sending to reduce API usage
  batch:

exporters:
  logging:
    loglevel: debug

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

# https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/README.md
extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
  # fetches the collector’s performance data
  pprof:
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [loki]
```

### Log output

```shell
otel-collector_1  | 2023-08-30T15:24:45.452Z    error   prometheusexporter@v0.82.0/log.go:23    error gathering metrics: 5 error(s) occurred:
otel-collector_1  | * collected metric log4j2_events label:{name:"application" value:"testapp"} label:{name:"job" value:"unknown_service"} label:{name:"label1" value:"value1"} label:{name:"level" value:"debug"} counter:{value:599} has help "Number of debug level log events" but should have "Number of trace level log events"
otel-collector_1  | * collected metric log4j2_events label:{name:"application" value:"testapp"} label:{name:"job" value:"unknown_service"} label:{name:"label1" value:"value1"} label:{name:"level" value:"warn"} counter:{value:2} has help "Number of warn level log events" but should have "Number of trace level log events"
otel-collector_1  | * collected metric log4j2_events label:{name:"application" value:"testapp"} label:{name:"job" value:"unknown_service"} label:{name:"label1" value:"value1"} label:{name:"level" value:"fatal"} counter:{value:0} has help "Number of fatal level log events" but should have "Number of trace level log events"
otel-collector_1  | * collected metric log4j2_events label:{name:"application" value:"testapp"} label:{name:"job" value:"unknown_service"} label:{name:"label1" value:"value1"} label:{name:"level" value:"error"} counter:{value:0} has help "Number of error level log events" but should have "Number of trace level log events"
otel-collector_1  | * collected metric log4j2_events label:{name:"application" value:"testapp"} label:{name:"job" value:"unknown_service"} label:{name:"label1" value:"value1"} label:{name:"level" value:"info"} counter:{value:12} has help "Number of info level log events" but should have "Number of trace level log events"
otel-collector_1  |     {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
otel-collector_1  | github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
otel-collector_1  |     github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.82.0/log.go:23
otel-collector_1  | github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
otel-collector_1  |     github.com/prometheus/client_golang@v1.16.0/prometheus/promhttp/http.go:144
otel-collector_1  | net/http.HandlerFunc.ServeHTTP
otel-collector_1  |     net/http/server.go:2122
otel-collector_1  | net/http.(*ServeMux).ServeHTTP
otel-collector_1  |     net/http/server.go:2500
otel-collector_1  | go.opentelemetry.io/collector/config/confighttp.(*decompressor).ServeHTTP
otel-collector_1  |     go.opentelemetry.io/collector/config/confighttp@v0.82.0/compression.go:147
otel-collector_1  | go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
otel-collector_1  |     go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212
otel-collector_1  | go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
otel-collector_1  |     go.opentelemetry.io/collector/config/confighttp@v0.82.0/clientinfohandler.go:28
otel-collector_1  | net/http.serverHandler.ServeHTTP
otel-collector_1  |     net/http/server.go:2936
otel-collector_1  | net/http.(*conn).serve
otel-collector_1  |     net/http/server.go:1995
```

### Additional context

My docker-compose looks something like this:

```
........
version: '3.8'

services:
 otel-collector:
    image: otel/opentelemetry-collector-contrib:0.82.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - /data/configs/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    networks:
      mw-network:
        aliases:
          - otel-collector

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - /data/configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      mw-network:
        aliases:
          - prometheus

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      mw-network:
        aliases:
          - loki

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - /data/configs/tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"   # tempo
      - "4317"  # otlp grpc
    networks:
      mw-network:
        aliases:
          - tempo

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /data/grafana:/var/lib/grafana 
..........
```

Java config class:

```
@Configuration
public class OpenTelemetryConfig {
    @Bean
    OpenTelemetry openTelemetry(SdkLoggerProvider sdkLoggerProvider, SdkTracerProvider sdkTracerProvider, ContextPropagators contextPropagators) {
        OpenTelemetrySdk openTelemetrySdk = OpenTelemetrySdk.builder()
                .setLoggerProvider(sdkLoggerProvider)
                .setTracerProvider(sdkTracerProvider)
                .setPropagators(contextPropagators)
                .build();
        OpenTelemetryAppender.install(openTelemetrySdk);
        return openTelemetrySdk;
    }

    @Bean
    SdkLoggerProvider otelSdkLoggerProvider(Environment environment, ObjectProvider<LogRecordProcessor> logRecordProcessors) {
        String applicationName = environment.getProperty("spring.application.name", "application");
        Resource springResource = Resource.create(Attributes.of(ResourceAttributes.SERVICE_NAME, applicationName));
        SdkLoggerProviderBuilder builder = SdkLoggerProvider.builder()
                .setResource(Resource.getDefault().merge(springResource));
        logRecordProcessors.orderedStream().forEach(builder::addLogRecordProcessor);
        return builder.build();
    }

    @Bean
    LogRecordProcessor otelLogRecordProcessor() {
        return BatchLogRecordProcessor
                .builder(OtlpGrpcLogRecordExporter.builder()
                                                  .setEndpoint("http://otel-collector:4317")
                                                  .build())
                .build();
    }
}
```

application.yaml:

```
logging:
  config: classpath:/log4j2-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: metrics
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: kelteu
...............
```

**Comment by crobert-1** [comment]
Also filed here: [#opentelemetry-collector/issues/8340](https://github.com/open-telemetry/opentelemetry-collector/issues/8340)

**Comment by frzifus** [comment]
hm... I am sure I have seen this in the past. But looking at the stacktrace and impl. I can only guess what might have caused it.
Since `promLogger` is just a wrapper around `zap.Logger` which is thread-safe, I assume the error is somehow related to the object(s) passed to the logger. 

A closer look with a real debugger might help. Could you provide some details about the passed objects?

**Comment by andrm** [comment]
Same problem here with wildfly 30.

**Comment by fede843** [comment]
getting the same error too

**Comment by crobert-1** [comment]
@andrm, @fede843, or @ghevge: Would you be able to provide the detailed information about the passed objects that the logger is hitting the errors on? This would be very helpful in debugging, otherwise it will be hard to make progress.

**Comment by ghevge** [comment]
@crobert-1 it will probably be faster to change otel-collector and throw those packages in the logs, in debug mode.

**Comment by crobert-1** [comment]
> @crobert-1 it will probably be faster to change otel-collector and throw those packages in the logs, in debug mode.

Pardon my ignorance, but I don't understand what you mean here. Since this isn't failing every time the goal is to find what data is causing this exception to be hit, helping us understand the root cause and fix it.

Are you suggesting adding more logging to the collector to understand which packages are causing the failure? Either way, any more information that can be provided here would be helpful.

**Comment by ghevge** [comment]
#Are you suggesting adding more logging to the collector to understand which packages are causing the failure?  
Yes

**Comment by andrm** [comment]
I'm getting this from wildfly 30:
```
Dec 01 07:56:42  t-02 otelcol[41089]: 2023-12-01T07:56:42.739Z        error        prometheusexporter@v0.89.0/log.go:23        error gathering metrics: 2 error(s) occurred:
Dec 01 07:55:42 t-02 otelcol[41089]: * collected metric undertow_request_count_total label:{name:"app"  value:"wildfly"}  label:{name:"deployment"  value:""}  label:{name:"job"  value:"wildfly"}  label:{name:"name"  value:"default"}  label:{name:"subdeployment"  value:""}  label:{name:"type"  value:"http-listener"}  counter:{value:0} has help "The number of requests this listener has served" but should have "Number of all requests"
Dec 01 07:55:42 t-02 otelcol[41089]: * collected metric undertow_request_count_total label:{name:"app"  value:"wildfly"}  label:{name:"deployment"  value:""}  label:{name:"job"  value:"wildfly"}  label:{name:"name"  value:"https"}  label:{name:"subdeployment"  value:""}  label:{name:"type"  value:"https-listener"}  counter:{value:0} has help "The number of requests this listener has served" but should have "Number of all requests"
Dec 01 07:55:42 t-02 otelcol[41089]:         {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
Dec 01 07:55:42 t-02 otelcol[41089]: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
Dec 01 07:55:42 t-02 otelcol[41089]:         github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.89.0/log.go:23
Dec 01 07:55:42 t-02 otelcol[41089]: github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
Dec 01 07:55:42 t-02 otelcol[41089]:         github.com/prometheus/client_golang@v1.17.0/prometheus/promhttp/http.go:144
Dec 01 07:55:42 t-02 otelcol[41089]: net/http.HandlerFunc.ServeHTTP
Dec 01 07:55:42 t-02 otelcol[41089]:         net/http/server.go:2136
Dec 01 07:55:42 t-02 otelcol[41089]: net/http.(*ServeMux).ServeHTTP
Dec 01 07:55:42 t-02 otelcol[41089]:         net/http/server.go:2514
Dec 01 07:55:42 t-02 otelcol[41089]: go.opentelemetry.io/collector/config/confighttp.(*decompressor).ServeHTTP
Dec 01 07:55:42 t-02 otelcol[41089]:         go.opentelemetry.io/collector/config/confighttp@v0.89.0/compression.go:147
Dec 01 07:55:42 t-02 otelcol[41089]: go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
Dec 01 07:55:42 t-02 otelcol[41089]:         go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0/handler.go:229
Dec 01 07:55:42 t-02 otelcol[41089]: go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
Dec 01 07:55:42 t-02 otelcol[41089]:         go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.0/handler.go:81
Dec 01 07:55:42 t-02 otelcol[41089]: net/http.HandlerFunc.ServeHTTP
Dec 01 07:55:42 t-02 otelcol[41089]:         net/http/server.go:2136
Dec 01 07:55:42 t-02 otelcol[41089]: go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
Dec 01 07:55:42 t-02 otelcol[41089]:         go.opentelemetry.io/collector/config/confighttp@v0.89.0/clientinfohandler.go:28
Dec 01 07:55:42 t-02 otelcol[41089]: net/http.serverHandler.ServeHTTP
Dec 01 07:55:42 t-02 otelcol[41089]:         net/http/server.go:2938
Dec 01 07:55:42 t-02 otelcol[41089]: net/http.(*conn).serve
Dec 01 07:55:42 t-02 otelcol[41089]:         net/http/server.go:2009
```
It's very confusing, how does the collector know the comment? From prometheus?

**Comment by andrm** [comment]
It looks like a concurrency issue. I issue the same curl command twice and I different entries for the same counter:
```
:~$ date && curl http://t-02:9989/metrics | grep undertow_request_count_total              
Fr 1. Dez 09:13:18 CET 2023
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 52413    0 52413    0     0  10.0M      0 --:--:-- --:--:-- --:--:-- 12.4M
# HELP undertow_request_count_total The number of requests this listener has served
# TYPE undertow_request_count_total counter
undertow_request_count_total{app="wildfly",deployment="",job="wildfly",name="default",subdeployment="",type="http-listener"} 0
undertow_request_count_total{app="wildfly",deployment="",job="wildfly",name="https",subdeployment="",type="https-listener"} 0
:~$ date && curl http://t-02:9989/metrics | grep undertow_request_count_total              
Fr 1. Dez 09:13:21 CET 2023
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 52320    0 52320    0     0  8948k      0 --:--:-- --:--:-- --:--:--  9.9M
# HELP undertow_request_count_total Number of all requests
# TYPE undertow_request_count_total counter
undertow_request_count_total{app="tb.war",deployment="tb.war",job="wildfly",name="com.XXXX.rest.RestApplication",subdeployment="tb.war",type="servlet"} 0
:~$  
```

Is this a wildfly problem?

**Comment by andrm** [comment]
Is there a way to debug what wildfly is sending?

**Comment by eaisling** [comment]
I'm having the same issue with Wildfly 30 publishing to the collector 
```
2024-01-31T12:51:54.544Z	error	prometheusexporter@v0.93.0/log.go:23	error gathering metrics: 3 error(s) occurred:
* collected metric undertow_request_count_total label:{name:"app"  value:"uvw.ear"}  label:{name:"deployment"  value:"uvw.ear"}  label:{name:"host"  value:"foooo"}  label:{name:"instance"  value:"bob"}  label:{name:"job"  value:"wildfly"}  label:{name:"maininstance"  value:"false"}  label:{name:"name"  value:"de.bob.JaxRsCoreApplication"}  label:{name:"subdeployment"  value:"rest-api.war"}  label:{name:"type"  value:"servlet"}  counter:{value:0} has help "Number of all requests" but should have "The number of requests this listener has served"
* collected metric undertow_request_count_total label:{name:"app"  value:"uvw.ear"}  label:{name:"deployment"  value:"uvw.ear"}  label:{name:"host"  value:"foooo"}  label:{name:"instance"  value:"bob"}  label:{name:"job"  value:"wildfly"}  label:{name:"maininstance"  value:"false"}  label:{name:"name"  value:"de.bob.JaxRsCoreApplication"}  label:{name:"subdeployment"  value:"webs.war"}  label:{name:"type"  value:"servlet"}  counter:{value:0} has help "Number of all requests" but should have "The number of requests this listener has served"
* collected metric undertow_request_count_total label:{name:"app"  value:"uvw.ear"}  label:{name:"deployment"  value:"uvw.ear"}  label:{name:"host"  value:"foooo"}  label:{name:"instance"  value:"bob"}  label:{name:"job"  value:"wildfly"}  label:{name:"maininstance"  value:"false"}  label:{name:"name"  value:"de.bob.MyRestApplication"}  label:{name:"subdeployment"  value:"rest-api.war"}  label:{name:"type"  value:"servlet"}  counter:{value:0} has help "Number of all requests" but should have "The number of requests this listener has served"
	{"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.93.0/log.go:23
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
	github.com/prometheus/client_golang@v1.18.0/prometheus/promhttp/http.go:144
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2136
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2514
go.opentelemetry.io/collector/config/confighttp.(*decompressor).ServeHTTP
	go.opentelemetry.io/collector/config/confighttp@v0.93.0/compression.go:147
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.47.0/handler.go:225
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.47.0/handler.go:83
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2136
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
	go.opentelemetry.io/collector/config/confighttp@v0.93.0/clientinfohandler.go:28
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.(*conn).serve
	net/http/server.go:2009
```
otel-collector-config
```
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
    
receivers:
  otlp:
    protocols:
      grpc:
      http:
      
processors:
  batch:
  
exporters:
  prometheus:
    endpoint: "0.0.0.0:1234"
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
  extensions: [health_check, pprof, zpages]
```
