### ISSUE TITLE
loki receiver - basic authentication

### ISSUE THREAD

**Issue by sairamsadanala** [open-telemetry/opentelemetry-collector-contrib#26352]
### Component(s)

receiver/loki

### Describe the issue you're reporting

Context: I am trying to setup otelcol-contrib abstraction layer with loki receiver implementing basic authentication and with transform processor to set dynamic tenant(X-scope-OrgID) in the request header while exporting to Grafana Loki endpoint.

Issue: It does not sound like loki receiver support basic authentication.

**Comment by jpkrohling** [comment]
It does support, as it uses the common HTTP and gRPC server settings. Something like this should work:

```
extensions:
  basicauth:
    htpasswd: 
      inline: "admin: $apr1$so2zr16x$jWvnqhK3fg24qjBB4iN6x/"

receivers:
  loki:
    protocols:
      http:
        auth:
          authenticator: basicauth
      grpc:
        auth:
          authenticator: basicauth

exporters:
  logging:

service:
  extensions: [basicauth]
  pipelines:
    logs:
      receivers: [loki]
      processors:
      exporters: [logging]
```

I'll work on documenting this.
