### ISSUE TITLE
processor/routing supports matching the statement only once.

### ISSUE THREAD

**Issue by huange7** [open-telemetry/opentelemetry-collector-contrib#26353]
### Component(s)

processor/routing

### Is your feature request related to a problem? Please describe.

If multiple statements are configured in the configuration file, the routing processor will judge each statement. Whenever a match is made, data will be sent to the exporters defined in the configuration. Can we support interrupting the match after matching only once?

### Describe the solution you'd like

Use a switch to allow the routing processor to match only once.

### Additional context

``` 
 routing:
    default_exporters:
      - jaeger
    error_mode: ignore
    table:
      - statement: route() where resource.attributes["service.name"] == "demo"
        exporters: [ logging ]
      - statement: route() where resource.attributes["service.name"] == "demo" and resource.attributes["token"] == "xxx"
        exporters: [ logging/2 ]
```
As shown in the configuration file above, I hope that some traces/metrics/logs will be sent to `logging exporter` if they only match the `service.name` attribute, and if they match both the `service.name` and the `token`, they will be sent to `logging/2 exporter`. This is possible in practice.

If this seems reasonable, I sincerely hope that I can make some contributions.

**Comment by huange7** [comment]
> would it be possible to simply make your routing statements more specific to accomplish this functionality?

@crobert-1 Thanks for your reply. This sounds feasible. 

However, let's consider a scenario where there is a `processor` that adds `data.index` attribute as the first layer of routing, and a second processor that adds `exporter.index` attribute as the second layer of routing. In this case, we want to configure a default route for the first layer of routing (`data.index`), and then configure individual routes for each value of `exporter.index`.

In that case, the configuration file would look like this:
```
routing:
    default_exporters:
      - jaeger
    error_mode: ignore
    table:
      - statement: route() where resource.attributes["data.index"] == "1" and resource.attributes["exporter.index"] != "1" and resource.attributes["exporter.index"] != "2"
         exporters: [ logging ]
      - statement: route() where resource.attributes["data.index"] == "1" and resource.attributes["exporter.index"] == "1"
        exporters: [ logging/1 ]
      - statement: route() where resource.attributes["data.index"] == "1" and resource.attributes["exporter.index"] == "2"
        exporters: [ logging/2 ]
```

As the number of different `exporter.index` values increases, the configuration for the default route could become more complex and lengthy. It's important to consider how to maintain the readability and manageability of the configuration file in such cases.
