### ISSUE TITLE
[connector/spanmetrics] How to use spanmetrics together with grafana's service graph

### ISSUE THREAD

**Issue by cmergenthaler** [open-telemetry/opentelemetry-collector-contrib#26370]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

From what I see, the changes introduced in #18760 made the spanmetrics connector incompatible with grafana's service graph. 
As stated in [grafana tempo docs](https://grafana.com/docs/grafana/latest/datasources/tempo/#open-the-service-graph-view): 
> Grafana uses the `traces_spanmetrics_calls_total` metric to display the name, rate, and error rate columns, and `traces_spanmetrics_latency_bucket` to display the duration column. These metrics must exist in your Prometheus data source.

### Describe the solution you'd like

Allow customizing the name of the `duration` metric so that it can be used by grafana.

### Describe alternatives you've considered

Would be happy to know about other solutions

**Comment by crobert-1** [comment]
Hello @cmergenthaler, can you share the config you're using for this functionality? There are a couple of options, but it depends on how the collector is configured.

**Comment by cmergenthaler** [comment]
Hey @crobert-1, appreciate your help!
My config looks the following:

``` yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

connectors:
  servicegraph:
    latency_histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
  spanmetrics:
    namespace: traces.spanmetrics
    histogram:
      explicit:
        buckets: [2ms, 4ms, 8ms, 16ms, 32ms, 64ms, 128ms, 256ms, 512ms, 1.02s, 2.05s, 4.10s]

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: my-prom
    target_info:
      enabled: false

service:
  pipelines:
    metrics:
      receivers: [otlp, servicegraph, spanmetrics]
      processors: [batch]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [servicegraph, spanmetrics]
```

In prometheus I have the following spanmetrics available:
- traces_spanmetrics_calls
- traces_spanmetrics_duration_bucket
- traces_spanmetrics_duration_count
- traces_spanmetrics_duration_sum

As described, Grafana expects slightly different metrics to be present in prometheus. It also seems that the prometheusremotewrite does not add `_total` suffix to the `calls` metric - even though `add_metric_suffixes` is set to true. 
I am running otel-collector-contrib 0.84.0
