### ISSUE TITLE
[exporter/prometheusremotewrite] - add_metric_suffixes not respected for counters / gauge

### ISSUE THREAD

**Issue by StarpTech** [open-telemetry/opentelemetry-collector-contrib#26380]
### Component(s)

exporter/prometheusremotewrite

## Description

The property `add_metric_suffixes` is not respected for counters and gauge metrics.

## Steps to Reproduce

1. Create a counter and call it `my_counter`
2. Export it to the collector endpoint.
3. Navigate to your local Prometheus instance and check the metrics. The name is `my_counter`

`add_metric_suffixes` should be enabled by default so no configuration is necessary.

## Expected Result

The name of the metric should `my_counter_total` in prometheus

## Actual Result

The name is `my_counter`

### Collector version

0.84.0

## Environment
OS: (e.g., "Ubuntu 20.04") Pop!_OS 22.04 LTS
Compiler(if manually compiled): (e.g., "go 14.2") go1.20.4 linux/amd64

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: '0.0.0.0:4318'

exporters:
  prometheusremotewrite:
    endpoint: "${PROMETHEUS_REMOTE_ENDPOINT}"
    namespace: "test"
    add_metric_suffixes: true
    auth:
      authenticator: basicauth/prw
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_interval: 30s
      max_elapsed_time: 300s
    remote_write_queue:
      # Maximum number of batches kept in memory before dropping;
      queue_size: 2000
      # Number of consumers that dequeue batches
      num_consumers: 10
    timeout: 5s
    target_info:
      enabled: true

extensions:
  basicauth/prw:
    client_auth:
      username: ${PROMETHEUS_USERNAME}
      password: ${PROMETHEUS_PASSWORD}

service:
  extensions: [basicauth/prw]
  pipelines:
    metrics:
      receivers: [otlp]
      # Order is important here. Otherwise, the attributes processor will not be able to read the attributes from the auth context.
      exporters: [prometheusremotewrite]
```
