### ISSUE TITLE
[connector/routing] Not included in contrib distribution

### ISSUE THREAD

**Issue by yanamg7** [open-telemetry/opentelemetry-collector-contrib#26495]
### Component(s)

connector/routing

### What happened?

Using artifactory.f5net.com/dockerhub-remote/otel/opentelemetry-collector-contrib:0.84.0 I trying to add connector routing 

## Steps to Reproduce
I added to config.yaml this part:
connector:
  routing:
      default_pipelines: [logs/all]
      error_mode: ignore
      table:
        - statement: route() where resource.attributes["Severity"] == "err"
          pipelines: [logs/err]
        - statement: route() where resource.attributes["Severity"] == "info"
          pipelines: [logs/info]

Trying to run 
## Expected Result

Run successfully, no errors, correct output

## Actual Result

 error decoding 'connectors': unknown type: "routing" for id: "routing" (valid values: [count datadog servicegraph spanmetrics forward])

### Collector version

0.84.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include: [ /opt/parser/*.log ]
    start_at: beginning
    operators:
      - type: add
        field: attributes.sev
        value: unspecified
      - type: json_parser
      - type: severity_parser
        parse_from: attributes.sev
        mapping:
          fatal: emergency
          info4: notice
      - type: move
        id: move5
        from: attributes.sev
        to: resource["Severity"]
      

exporters:
  file/file1:
    path: /var/log/collector/logging1/otlp.json
  file/file2:
    path: /var/log/collector/logging2/otlp.json
  file/file3:
    path: /var/log/collector/logging3/otlp.json
  logging:
    loglevel: debug


connector:
  routing:
      default_pipelines: [logs/all]
      error_mode: ignore
      table:
        - statement: route() where resource.attributes["Severity"] == "err"
          pipelines: [logs/err]
        - statement: route() where resource.attributes["Severity"] == "info"
          pipelines: [logs/info]

service:
  pipelines:
    logs/in:
      receivers: [filelog]
      exporters: [routing, logging]
    logs/all:
      receivers: [routing]
      exporters: [file/file3, logging]
    logs/info:
      receivers: [routing]
      processors: []
      exporters: [file/file1, logging]
    logs/err:
      receivers: [routing]
      processors: []
      exporters: [file/file2, logging]
```

### Log output

```shell
otel-contrib  | Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
otel-contrib  | 
otel-contrib  | * error decoding 'connectors': unknown type: "routing" for id: "routing" (valid values: [count datadog servicegraph spanmetrics forward])
otel-contrib  | 2023/09/07 07:53:12 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
otel-contrib  | 
otel-contrib  | * error decoding 'connectors': unknown type: "routing" for id: "routing" (valid values: [count datadog servicegraph spanmetrics forward])
otel-contrib exited with code 1
```

**Comment by mwear** [comment]
@yanamg7 can you make sure that connectors ends in an "s" (rename connector -> connectors) in your yaml?

```
connectors:
  routing:
      default_pipelines: [logs/all]
      error_mode: ignore
      table:
        - statement: route() where resource.attributes["Severity"] == "err"
          pipelines: [logs/err]
        - statement: route() where resource.attributes["Severity"] == "info"
          pipelines: [logs/info]
```
