### ISSUE TITLE
Otelcol-contrib attributes extract action issue

### ISSUE THREAD

**Issue by sairamsadanala** [open-telemetry/opentelemetry-collector-contrib#26515]
### Component(s)

processor/attributes

## Description
I am setting up otelcol-contrib hub to receive telemetry(logs) from different sources and exporting them to loki adding tenant(X-Scope-OrgID) dynamically. Otelcol-contrib hub receives log.file.path: Str(/var/log/pods/<kubernetes namespace>_XXXX-sample-XX-default-1_d30d866a-b217-4d9a-a4c3-6dd8efb4a79a/XXX-XXX-XX-XXX/0.log) attribute and need to extract <kubernetes namespace> value from log.file.path attribute and set loki.tenant attribute while exporting logs to loki endpoint.
## Steps to Reproduce
```
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133

  processors:
    memory_limiter: null
    attributes:
      actions:
        - key: "loki.tenant"
          action: extract
          pattern: \/var\/log\/pods\/([^_]+)_.*\/\d+\.log           
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
          include_metadata: true
  exporters:
    logging:
      verbosity: detailed
    loki:
      endpoint: "http://aaaa-bbb.ccc.xx/loki/api/v1/push"
      tls:
          insecure: false
          insecure_skip_verify: true
  service:
    extensions:
      - health_check
    pipelines:
      logs:
        exporters:
          - logging
          - loki
        receivers:
          - otlp
        processors:
          - memory_limiter
          - attributes
```

## Expected Result
we should see the loki.tenant
## Actual Result

```
error: failed to build pipelines: failed to create "attributes" processor, in pipeline "logs": error creating AttrProc. Field "pattern" contains at least one unnamed matcher group at the 0-th actions
```

### Collector version

0.82.0

## Environment
OS: AWS Kubernetes 

### OpenTelemetry Collector configuration

```yaml
extensions:
    health_check:
      endpoint: 0.0.0.0:13133

  processors:
    memory_limiter: null
    attributes:
      actions:
        - key: loki.tenant
          action: extract
          pattern: \/var\/log\/pods\/([^_]+)_.*\/\d+\.log           
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
          include_metadata: true
  exporters:
    logging:
      verbosity: detailed
    loki:
      endpoint: "http://aaaa-bbb.ccc.xx/loki/api/v1/push"
      tls:
          insecure: false
          insecure_skip_verify: true
  service:
    extensions:
      - health_check
    pipelines:
      logs:
        exporters:
          - logging
          - loki
        receivers:
          - otlp
        processors:
          - memory_limiter
          - attributes
```

### Log output

```shell
Error: failed to build pipelines: failed to create "attributes" processor, in pipeline "logs": error creating AttrProc. Field "pattern" contains at least one unnamed matcher group at the 0-th actions
2023/09/X XX:XX:XXcollector server run finished with error: failed to build pipelines: failed to create "attributes" processor, in pipeline "logs": error creating AttrProc. Field "pattern" contains at least one unnamed matcher group at the 0-th actions
```

**Comment by crobert-1** [comment]
Hello @sairamsadanala, to confirm my understanding, you're receiving the `log.file.path` attribute, and want to extract information from the value of this attribute to set the value of a new attribute named `loki.tenant`, is that correct?

I think the config is essentially backwards, where your `key` should be the existing key. It should look like this:
```
attributes:
      actions:
        - key: log.file.path
           action: extract
```
The logic here is that we want to extract a new attribute **from** the value of the specified key `log.file.path`. The regex is then used to match a part of the value of the `log.file.path`, and name whatever part is matched `loki.tenant`.

The error message you're getting is saying that you have a matcher group in your regex, but there isn't a name specified to set what's matched. Refer to [this example](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/3c1eec6b9b955ec9c0a515d14f2dc903f575e725/processor/attributesprocessor/testdata/config.yaml#L38) to see how to name the matched group.

Happy to help if I missed something here or if there's any confusion.
