### ISSUE TITLE
Azure Data Explorer - Ingestion Failures - BadRequest_NoRecordsOrWrongFormat

### ISSUE THREAD

**Issue by akakarikos** [open-telemetry/opentelemetry-collector-contrib#26651]
### Component(s)

exporter/azuredataexplorer

## Description

When exporting to Azure Data Explorer exporter, there are several ingestion failures when ingesting for the OMNITELLogs and OMNITELTraces tables. One example of the error is the below:

```
"OperationId": 3bbeb9f5-41bd-4611-b2e2-43f650e4166b,
"Database": adx-prod-omni-telemetry,
"Table": OMNITELTraces,
"FailedOn": 2023-09-12T09:57:07.3958316Z,
"IngestionSourcePath": https://282strldadxadpprdwe00101.blob.core.windows.net/20230912-ingestdata-e5c334ee145d4b4-0/adx-prod-omni-telemetry_OMNITELTraces_2023-09-12%2009:56:45.25714285%20+0000%20UTC%20m=+2228478.125662742_25eb7f10-60c3-436c-bc55-ff498b909fa3.json,
"Details": BadRequest_NoRecordsOrWrongFormat: The input stream produced 0 bytes. This usually means that the input JSON stream was ill formed.,
"FailureKind": Permanent,
"RootActivityId": a747c063-18d3-4ed6-aba4-0a3272bb14c6,
"OperationKind": DataIngestPull,
"OriginatesFromUpdatePolicy": false,
"ErrorCode": BadRequest_NoRecordsOrWrongFormat,
"Principal": dstsapp=KustoIngestionProd,
"ShouldRetry": false,
"User": ,
"IngestionProperties": [Format=Json/mandatory, IngestionMapping=[{"ColumnName":"TraceID","ColumnType":"string","Properties":{"Field":"TraceID"}},{"ColumnName":"SpanID","ColumnType":"string","Properties":{"Field":"SpanID"}},{"ColumnName":"ParentID","ColumnType":"string","Properties":{"Field":"ParentID"}},{"ColumnName":"SpanName","ColumnType":"string","Properties":{"Field":"SpanName"}},{"ColumnName":"SpanStatus","ColumnType":"string","Properties":{"Field":"SpanStatus"}},{"ColumnName":"SpanKind","ColumnType":"string","Properties":{"Field":"SpanKind"}},{"ColumnName":"StartTime","ColumnType":"datetime","Properties":{"Field":"StartTime"}},{"ColumnName":"EndTime","ColumnType":"datetime","Properties":{"Field":"EndTime"}},{"ColumnName":"ResourceAttributes","ColumnType":"dynamic","Properties":{"Field":"ResourceAttributes"}},{"ColumnName":"TraceAttributes","ColumnType":"dynamic","Properties":{"Field":"TraceAttributes"}},{"ColumnName":"Events","ColumnType":"dynamic","Properties":{"Field":"Events"}},{"ColumnName":"Links","ColumnType":"dynamic","Properties":{"Field":"Links"}}], ValidationPolicy=[Options=ValidateCsvInputConstantColumns, Implications=BestEffort, IsDetailedErrorReportingEnabled=False], Tags=[ToStringEmpty], IngestIfNotExists=[ToStringEmpty], ZipPattern=[null]],
"NumberOfSources": 1
```

## Steps to Reproduce

Not specific steps. Just set up an application with the OTel collector that exports to ADX exporter.

## Expected Result

The logs and traces are successfully exported and ingested by the Azure Data Explorer.

## Actual Result

There are multiple ingestion failures emitted by the Azure Data Explorer.

### Collector version

0.80.0

## Environment
Docker image deployed in AKS.
OS: linux amd64

### OpenTelemetry Collector configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |-
    receivers:
      zipkin:
        endpoint: localhost:9411
      otlp:
        protocols:
          grpc:
            endpoint: localhost:4317
          http:
            endpoint: localhost:4318
            
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 30

      batch:
        send_batch_size: 50
    
    exporters:
      logging:
        verbosity: detailed
    
      azuremonitor:
        instrumentation_key: 
        spaneventsenabled: true

      azuredataexplorer:
        cluster_uri: 
        application_id: 
        application_key: 
        tenant_id:
        db_name: 
        metrics_table_name: 
        logs_table_name: 
        traces_table_name:
    
    service:
      pipelines:
        traces:
          receivers: [zipkin,otlp]
          processors: [memory_limiter,batch]
          exporters: [azuredataexplorer,azuremonitor,logging]
        logs:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [azuredataexplorer,azuremonitor,logging]
```

### Additional context

Is there a way to select the format of the ingestion between JSON and MultiJSON?
