### ISSUE TITLE
resource labels missing in logs,  post migrate to otel collector 0.73

### ISSUE THREAD

**Issue by kadhamecha-conga** [open-telemetry/opentelemetry-collector-contrib#26650]
### Component(s)

exporter/loki

### What happened?

hi team,

we facing issue when we upgrade from otel 0.47 to 0.73.  all config we make compatible with 0.73.
service.name and service.namespace , we fetch from  pod labels.
metrics and traces are having these labels . but same labels are missing for logs.

can you please help here ?

thanks.

### Collector version

0.73

## Environment
kubernetes 

### OpenTelemetry Collector configuration

```yaml
resource:
        attributes:
        - action: insert
          key: k8s.cluster.name
          value: test-cluster
        - action: insert
          key: deployment.environment
          value: env1
        - action: insert
          from_attribute: k8s.pod.labels.service.namespace
          key: service.namespace
        - action: insert
          from_attribute: k8s.pod.name
          key: service.instance.id
        - action: upsert
          from_attribute: k8s.deployment.name
          key: service.name
        - action: upsert
          from_attribute: k8s.pod.labels.app
          key: service.name

    service:
      pipelines:
        logs:
          exporters:
          - otlphttp
          processors:
          - memory_limiter
          - batch
          - resource
          receivers:
          - filelog
        metrics:
          exporters:
          - otlphttp/metrics
          processors:
          - memory_limiter
          - batch
          - resource
          receivers:
          - prometheus
          - otlp
        traces:
          exporters:
          - otlphttp
          processors:
          - memory_limiter
          - batch
          - resource
          receivers:
          - otlp
```
