### ISSUE TITLE
[connector/spanmetrics] support custom metric name

### ISSUE THREAD

**Issue by karmingc** [open-telemetry/opentelemetry-collector-contrib#26673]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

Currently, the spanmetrics connector generate `calls` and `duration` and supports adding `dimensions` from span attributes. However, there are situation where we want to give more flexibility to the producers and support custom metric name.

For example, given an HTTP client call vs a gRPC client call, I would prefer having `http.client.request` and `grpc.client.request` as two separate metrics rather than having `calls` with all of their attributes combined.

### Describe the solution you'd like

Support custom metric name through span attribute. Provide a field to pull the custom metric name from, if none is provided, default to `calls` and `duration` as usual.

```yaml
receivers:
  nop:

exporters:
  nop:

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code
    metric_name:
      - metric: {calls or duration}
         name: metric.name
         default: calls
    exemplars:
      enabled: true
    exclude_dimensions: ['status.code']
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"    
    metrics_flush_interval: 15s 

service:
  pipelines:
    traces:
      receivers: [nop]
      exporters: [spanmetrics]
    metrics:
      receivers: [spanmetrics]
      exporters: [nop]
```

**Comment by karmingc** [comment]
@albertteoh tried adding a label but no luck. It seems like you're the only maintainer, any thoughts or existing approaches to resolve this?

**Comment by albertteoh** [comment]
I'm curious what is the benefit of having separate metrics, for example, in the use case above where there's an HTTP and gRPC client? Could they not be separate dimensions under a single metric name (e.g. calls)?

**Comment by karmingc** [comment]
I tend to think it provides more granularity, in terms of naming and isolating metrics by their purpose.

I think the semantic-conventions provides a [good explanation](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/metrics.md#general-guidelines) as well that I follow 

> [“As a rule of thumb, aggregations over all the attributes of a given metric SHOULD be meaningful,”](https://prometheus.io/docs/practices/naming/#metric-names) as Prometheus recommends.


For example, assume we expand this to more span kinds, such as server, client, producers, consumers. For example, let's say that each of these different kinds having 10 tags, this would end up with a metric with 40 tags. This in turns create a too "general" (or not "meaningful" per Prometheus definition) metric.

**Comment by karmingc** [comment]
@albertteoh any updates?

**Comment by albertteoh** [comment]
Could we use the [metricstransformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor) to achieve what you need?

**Comment by karmingc** [comment]
The spans are ingested as datapoints with different dimensions under the same metric name, such as `calls`. Using the metricstransformprofessor, I don’t think that we would be able to achieve the wanted behaviour. 

I tried using the transform processor, but using the datapoint context to modify the metric name would not work as well as the last datapoint would be overwrite everything previously. We’d probably would want to create a metric over a set of datapoints with a specific set of labels, but that would not ideal.

I’m in favour of seeing this implemented at the spanmetrics connector level because it’s where the metrics are being created. It should would be beneficial to have the flexibility to create custom metric names, possibly via a specific span attribute.

What are some of the concerns you have on this enhancement?

**Comment by albertteoh** [comment]
It seems @xwgao was able get metricstransform processor to successfully rename metrics generated by the spanmetrics connector, based on a match on labels/dimensions. Please refer to [this comment](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20432#issuecomment-1489637421).

> What are some of the concerns you have on this enhancement?

I would like the spanmetrics processor to do one thing well and not duplicate functionality implemented in an existing processor (that would do the same job a lot better).

**Comment by karmingc** [comment]
Thanks for the clarification and suggestion! Maybe I lack context on the implementation but is it really a duplicate functionality? I see it as a functionality similar to the `namespace` configuration, which is similar to renaming a metric as well.

if we were to implement this enhancement, we would avoid having another processor and avoid making changes to the configuration each time we want to generate a new metric from a span.

**Comment by albertteoh** [comment]
> I see it as a functionality similar to the namespace configuration, which is similar to setting a metric name as well.

Adding a `namespace` is fairly trivial functionality, and if the requirement for this issue is to simply rename `calls` and `duration` with a single, statically configured name as per the example config in the description above, I'm okay with adding this functionality:

```yaml
    metric_name:
      - metric: {calls or duration}
         name: metric.name
         default: calls
```

However, from what I understand of the description:

> For example, given an HTTP client call vs a gRPC client call, I would prefer having http.client.request and grpc.client.request as two separate metrics rather than having calls with all of their attributes combined.
...
Support custom metric name through span attribute. Provide a field to pull the custom metric name from,...

If I understand this correctly, the requested functionality is a somewhat more dynamic metric name that's based on the span attribute, and seems to me that we'd be essentially duplicating a subset of the metricstransform processor's functionality if we want this within the spanmetrics connector. Please correct me if I'm wrong though! 😄
