### ISSUE TITLE
Region information is AKS and EKS

### ISSUE THREAD

**Issue by prudhvi-hasura** [open-telemetry/opentelemetry-collector-contrib#26688]
### Component(s)

processor/resourcedetection

### Describe the issue you're reporting

Hi, I went through the documentation and observed that cloud.region is not exposed for AKS and EKS. 

- Is there any particular reason for not exposing this information ?
- Is there any possible way to get region information with current resource detection
- If its not possible to get region, are there any other alternatives to achieve this funcationality ?

**Comment by jinja2** [comment]
@prudhvi-hasura `cloud.region` is added by the respective provider's instance metadata detector. So for your use case, take a look at the `ec2` and `azure` detectors. An e.g. config will look like

```
resourcedetection:
  detectors:
  - eks
  - ec2
  ec2:
    resource_attributes:
      cloud.region:
        enabled: true
      cloud.account.id:
        enabled: false
      cloud.availability_zone:
        enabled: false
      host.type:
        enabled: false
      host.name:
        enabled: false
 ```
