### ISSUE TITLE
Tranform processor- expected string but got pcommon.Map

### ISSUE THREAD

**Issue by sairamsadanala** [open-telemetry/opentelemetry-collector-contrib#26689]
### Component(s)

processor/transform

## Description
Fluent Bit is sending logs to otelcol-contrib otlphttp receiver and otelcol-contrib extract kubernetes.namespace_name value using Transform processor and set loki.tenant hint so that loki exporter sends logs to loki endpoint.
## Expected Result
it should set loki.tenant =mytenant
## Actual Result
        warn    ottl@v0.82.0/parser.go:211      failed to execute statement     {"kind": "processor", "name": "transform", "pipeline": "logs", "error": "expected string but got pcommon.Map",

### Collector version

0.82

## Environment
OS: AWS EKS

### OpenTelemetry Collector configuration

```yaml
Name:         otel-hub-statefulset
Namespace:    otel-hub
Labels:       app.kubernetes.io/instance=otel-hub
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=otel-hub
              app.kubernetes.io/version=0.82.0
              helm.sh/chart=otel-hub-0.82.0_da6ca26aca3a.3
              helm.toolkit.fluxcd.io/name=otel-hub
              helm.toolkit.fluxcd.io/namespace=otel-hub
Annotations:  meta.helm.sh/release-name: otel-hub
              meta.helm.sh/release-namespace: otel-hub

Data
====
relay:
----
exporters:
  logging:
    verbosity: detailed
  loki:
    endpoint: http://XXXX/loki/api/v1/push
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_elapsed_time: 120s
      max_interval: 300s
    sending_queue:
      storage: file_storage/psq
    tls:
      insecure: false
      insecure_skip_verify: true
  splunk_hec/logs:
    endpoint: https://splunksandbox.bpweb.bp.com:8088/services/collector
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_elapsed_time: 60s
      max_interval: 60s
    sending_queue:
      storage: file_storage/psq
    timeout: 30s
    tls:
      insecure: false
      insecure_skip_verify: true
    token: 95c4beb5-c1b0-4735-bcd3-310cea0c9fa8
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
 
  transform:
    error_mode: ignore
    log_statements:
    - context: log
      statements:
      - set(attributes["cache"], ParseJSON(body)) where IsMatch(body[""], "^\\{")
      - set(attributes["tenant"], attributes["cache"]["kubernetes"]["namespace_name"])
      - set(attributes["loki.tenant"], "tenant")
      - delete_key(attributes, "cache")
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - logging
      - loki
      processors:
      - transform
      receivers:
      - otlp
```

### Log output

```shell
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-09-14 15:54:35.813509554 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Map({"@timestamp":"2023-09-14T15:54:35.813509554+00:00","cluster":"XXX","kubernetes":{"annotations":{"XXX-linux"},"container_hash":"XX","container_image":"XX","container_name":"XX","docker_id":"XXX","host":"XX","labels":{"app":"XX","controller-revision-hash":"XX","pod-template-generation":"XX"},"namespace_name":"mynamespace","pod_id":"XX","pod_name":"XX"},"logtag":"X","message":"time=\"2XX\" level=debug msg=\"XX\" Duration=\"XX\" Method=GET RequestURL=/readiness Route=ReadinessProbe StatusCode=200 logLayer=rest_frontend requestID=XX requestSource=REST workflow=\"trident_rest=logger\"","stream":"stderr"})
Attributes:
     -> loki.tenant: Str(loki_tenant)
Trace ID:
Span ID:
Flags: 0
        {"kind": "exporter", "data_type": "logs", "name": "logging"}
2023-09-14T15:54:37.887Z        error   exporterhelper/queued_retry.go:391      Exporting failed. The error is not retryable. Dropping data.       {"kind": "exporter", "data_type": "logs", "name": "loki", "error": 
"Permanent error: HTTP 401 \"Unauthorized\": no org id", "dropped_items": 4}
```

### Additional context

Below telemetry is being exported from Fluent Bit to Otelcol-contrib and then sending to loki endpoint.

ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-09-14 15:54:35.813509554 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Map({"@timestamp":"2023-09-14T15:54:35.813509554+00:00","cluster":"XXX","kubernetes":{"annotations":{"XXX-linux"},"container_hash":"XX","container_image":"XX","container_name":"XX","docker_id":"XXX","host":"XX","labels":{"app":"XX","controller-revision-hash":"XX","pod-template-generation":"XX"},"namespace_name":"mynamespace","pod_id":"XX","pod_name":"XX"},"logtag":"X","message":"time=\"2XX\" level=debug msg=\"XX\" Duration=\"XX\" Method=GET RequestURL=/readiness Route=ReadinessProbe StatusCode=200 logLayer=rest_frontend requestID=XX requestSource=REST workflow=\"trident_rest=logger\"","stream":"stderr"})
Attributes:
     -> loki.tenant: Str(loki_tenant)
Trace ID:
Span ID:
Flags: 0
        {"kind": "exporter", "data_type": "logs", "name": "logging"}
2023-09-14T15:54:37.887Z        error   exporterhelper/queued_retry.go:391      Exporting failed. The error is not retryable. Dropping data.       {"kind": "exporter", "data_type": "logs", "name": "loki", "error": 
"Permanent error: HTTP 401 \"Unauthorized\": no org id", "dropped_items": 4}

1) It is working if the log body is a string. Transform processor able to extract namespace_name and set orgid.
2) It is failing the with below error if the log body is a map.
        warn    ottl@v0.82.0/parser.go:211      failed to execute statement     {"kind": "processor", "name": "transform", "pipeline": "logs", "error": "expected string but got pcommon.Map",
