### ISSUE TITLE
Regression: filelog receiver no longer reads the last line of a file it it doesn't end with a newline character

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#26691]
### Component(s)

receiver/filelog

## Description
When upgrading from 0.84.0 to 0.85.0, our integration test started to fail because the last log record was not consumed in the file.

## Steps to Reproduce
See https://github.com/signalfx/splunk-otel-collector/actions/runs/6182103965/job/16794484352?pr=3631 and 
the fix: https://github.com/signalfx/splunk-otel-collector/pull/3631/commits/5e3502ba0e71d7ce076df024ae2a25648658da56

## Expected Result
The filelog receiver should continue to ingest files, including the last line if not terminated by an EOL character.
If this change is voluntary, we need to document this change in the filelog receiver documentation and register this as a breaking change.

## Actual Result
The filelog receiver ignores the last line of the file if not ending with an EOL.

### Collector version

0.85.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by djaglowski** [comment]
What configuration is being used?

The receiver does not emit a log just because it reaches the end of a file. A log is emitted if either 1) a complete log is read, as defined by the `multiline` configuration or lack thereor, or 2) the `force_flush_period` expires.

**Comment by crobert-1** [comment]
Configuration is [here](https://github.com/signalfx/splunk-otel-collector/blob/main/tests/receivers/filelog/testdata/syslog_config.yaml):

```
receivers:
  filelog:
    include: ["${env:LOGFILE_PATH}"]
    start_at: beginning
    operators:
      type: syslog_parser
      protocol: rfc3164

exporters:
  otlp:
    endpoint: "${OTLP_ENDPOINT}"
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [otlp]
```
