### ISSUE TITLE
Loadbalance export action in several services

### ISSUE THREAD

**Issue by Liubey** [open-telemetry/opentelemetry-collector-contrib#26703]
### Component(s)

exporter/loadbalancing

### Describe the issue you're reporting

I have there services named S1,S2,S3. They run in different Pods.
And they have some config of loadbalancing:
```
    exporters:
      logging:
        loglevel: info
      loadbalancing:
        routing_key: "traceID"
        protocol:
          otlp:
            timeout: 10s
            compression: gzip
            tls:
              insecure: true
        resolver:
          dns:
            hostname: {{ .Values.common.otelHostName }}     
```

My question is: **some TraceId in different service, will routing to the same collector**?
for example:
Service1 call Service2, they have same traceId
Service1 report to Collector1 by routing.
**Service2 will report to the same collector of Service1?** ( Service2 in other Pods)

Thanks for your time~
