### ISSUE TITLE
Jaeger UI SPM spanmetrics not working in 0.85.0

### ISSUE THREAD

**Issue by bangbaew** [open-telemetry/opentelemetry-collector-contrib#26712]
## Description

I updated to v0.85.0 and Jaeger UI spanmetrics stopped working in SPM page,
It worked fine in v0.84.0 with the same settings.
I think it has something to do with #26546 

## Steps to Reproduce
Update to v0.85.0

## Expected Result
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/29559559/b4d5384f-4fa8-473f-b6de-0810f3228341)

## Actual Result
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/29559559/664abf26-9408-4256-9231-5573866cfca5)

### Collector version

v0.85.0

## Environment
Docker Image `otel/opentelemetry-collector-contrib:0.85.0` on Ubuntu AKS

### OpenTelemetry Collector configuration

```yaml
receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"

  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    target_info:
       enabled: true

  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

connectors:
  spanmetrics:
    exemplars:
      enabled: true

processors:
  batch:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: container
      - action: insert
        key: loki.format
        value: raw

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [attributes]
      exporters: [loki]
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [spanmetrics, otlp, zipkin]
    metrics:
      receivers: [spanmetrics]
      exporters: [prometheusremotewrite]
```
