### ISSUE TITLE
[processor/tailsamplingprocessor] config allows duplicate policy names resulting in metrics collision

### ISSUE THREAD

**Issue by jmsnll** [open-telemetry/opentelemetry-collector-contrib#26726]
### Component(s)

processor/tailsampling

## Description

As noted in: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25882#issuecomment-1719811798

The name of each sampling policy is attached to the `count_traces_sampled` metric as an attribute which records how many traces each policy is responsible for sampling. 

If a user provides two policies with identical names then a collision occurs and the counts for the two policies are combined and reported under one metric.

## Steps to Reproduce

Given any two or more policies with identical names:

```
    policies:
      - name: policy-a
        type: status_code
        status_code:
          status_codes:
            - ERROR
      - name: policy-a
        type: probabilistic
        probabilistic:
          sampling_percentage: 25
```

The `count_traces_sampled` metric will report a combined count of both policies:

```
otelcol_processor_tail_sampling_count_traces_sampled{policy="policy-a",sampled="false"} 249
otelcol_processor_tail_sampling_count_traces_sampled{policy="policy-a",sampled="true"} 151
```

## Suggested fix

```
func (c *Config) Validate() error {
	policyNames := make(map[string]bool)

	// checks each policy is uniquely named to ensure accuracy of `count_traces_sampled` metric
	// sub policies contained within `and` or `composite` policies do not need to be checked
	for _, p := range c.PolicyCfgs {
		if _, exists := policyNames[p.Name]; exists {
			return fmt.Errorf("sampling policies must have unique names")
		}
		policyNames[p.Name] = true
	}

	return nil
}
```

## Expected Result

Config validation checks each sampling policy's name is unique and returns an error, preventing the collector from starting.

## Actual Result

Collector starts.

### Collector version

v0.85.0

## Environment
OS: Mac OS Ventura 13.5.2 (22G91)
Compiler(if manually compiled): go version go1.21.1 darwin/arm64

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  tail_sampling:
    decision_wait: 5s
    policies:
      - name: policy-a
        type: status_code
        status_code:
          status_codes:
            - ERROR
      - name: policy-a
        type: probabilistic
        probabilistic:
          sampling_percentage: 25
exporters:
  logging:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [logging]
```
