### ISSUE TITLE
Route the logs to loki exporter or Splunk exporter based on log attributes.

### ISSUE THREAD

**Issue by sairamsadanala** [open-telemetry/opentelemetry-collector-contrib#26720]
### Component(s)

processor/routing

## Description
Fluent Bit is sending logs to otelcol-contrib otlphttp receiver and otelcol-contrib extracts kubernetes.namespace_name value using Transform processor and set loki.tenant hint so that loki exporter sends logs to loki endpoint.I also need logs to send to Splunk. I have the requirement to route the logs based on kubernetes namespace and send logs to loki exporter if the namespace matches a condition and send logs to Splunk exporters if the namespace meet the condition. 

### Collector version

0.82

## Environment
OS: AWS EKS

### OpenTelemetry Collector configuration

```yaml
exporters:
  logging:
    verbosity: detailed
  loki:
    endpoint: http://XXXX/loki/api/v1/push
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_elapsed_time: 120s
      max_interval: 300s
    sending_queue:
      storage: file_storage/psq
    tls:
      insecure: false
      insecure_skip_verify: true
  splunk_hec/logs:
    endpoint: https://XXXXXXXXXX/services/collector
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_elapsed_time: 60s
      max_interval: 60s
    sending_queue:
      storage: file_storage/psq
    timeout: 30s
    tls:
      insecure: false
      insecure_skip_verify: true
    token: 95c4beb5-c1b0-4735-bcd3-310cea0c9fa8
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
 
  transform:
    error_mode: ignore
    log_statements:
    - context: log
      statements:
      - set(attributes["cache"], ParseJSON(body)) where IsMatch(body[""], "^\\{")
      - set(attributes["tenant"], attributes["cache"]["kubernetes"]["namespace_name"])
      - set(attributes["loki.tenant"], "tenant")
      - delete_key(attributes, "cache")
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - logging
      - loki
      processors:
      - transform
      receivers:
      - otlp
```

### Additional context

I have gone through Routing processor and understood that we can configure conditions/setting on [context] includes HTTP headers and Resource attributes. I would like to know whether I can configure log attributes in the statement to route the logs to respective exporter. 

 - statement: route() where log.attributes["tenant"] == "XXX"
   exporters: [loki]
