### ISSUE TITLE
New Component: pytransform processor

### ISSUE THREAD

**Issue by daidokoro** [open-telemetry/opentelemetry-collector-contrib#26731]
### The purpose and use-cases of the new component

# pytransform

The pytransform processor modifies telemetry based on configuration using Python code.

The processor leverages an embedded python version that has access to core python functionality and __does not__ require python be installed on the host. By leveraging Python code to modify telemetry, you have access to the full power of the Python language to modify data.

## Why?

While there are a number of transform processors in Open Telemetry Contrib, there is some overhead in understanding and leveraging the Open Telemetry Transform Language especially when dealing with complex telemetry data transformations. 

Python is a popular, well known language, even among non-developers. By allowing Python to be used as an option to transform telemetry data, it allows users to achieve more complex transformations, much faster and with a greater degree of control and precision. 

## How it works

The python language is embedded to the Open Telemetry binary, this allows you to run this processor without having python installed on the host itself. 

This design is based on Embedded Python for Go Project found [here](https://github.com/kluctl/go-embed-python).

When a python transform is executed, a controlled subprocess is called using the embedded python implementation that calls the user code. 

### Python Runtime and Helper Fucntions

The pytransform processor sends the metric, trace or log events to the python runtime by setting the env variable `INPUT`. You do not need to read this environment variable, pytransform adds helper functions to handle this automatically.

When a telemetry event is initialised in python, the event data will be accessible under the variable `event`. For example, the code below would print the event received from open telemetry.

```yaml
processors:
  pytransform:
    code: |
      print(event)
```

#### send()

You are able to modify this event using python code, however you choose. This can be in the form of functions, classes, regex using the python [re](https://docs.python.org/3/library/re.html) library, etc. It is import however, to maintain the structure of the event as the modified event needs to be returned to the pytransform processor. Events can be returned using another helper function, `send`.

For example, the config below adds a resource attribute to the telemetry event and returns it to the pytransform processor. 

```yaml
processors:
  pytransform/logs:
    code: |
      # edit resource attributes
      for data in event['resourceLogs']:
        for attr in data['resource']['attributes']:
          attr['value']['stringValue'] = 'source.log'

      send(event)
```

Note the use of the `send` function at the end of the code. If the event is not passed back to the processor using send, this will result in an error and the input event will be passed as unchanged.

```log
pytransform/logprocessor.go:54	python script returned empty output, returning record unchanged	{"kind": "processor", "name": "pytransform/test", "pipeline": "logs"}
```

#### print()

The `print` function in the pytransform Python runtime is overwritten with a special function that sends strings to the pytransform processor. These strings are then printed using the internal Open Telemetry logger. 

For example, take the following config:

```yaml
processors:
  pytransform:
    code: |
      print('hello world')
      send(event)
```

This results in a log line appearing in the Open Telemetry process:

```log
2023-09-16T18:00:21.551+0200	info	pytransform/pytransform.go:45	hello world	{"kind": "processor", "name": "pytransform/test", "pipeline": "logs", "src": "python.print()"}
```

The is useful for debugging python code.

### Timeout

There are a number of things that are possible running python within the Open Telemetry workflow, as such, to protect the runtime and host from long running zombie processes in python, each python invokation has a **maximum timeout of 1500ms**

The goal is to encourage using this processor solely for complex telemetry transformations rather than long running tasks.

## Config

To configure pytransform, you add your code using the `code` option in the config. Each instance of pytransform can only have a single code section. 

```yaml
processors:
  pytransform:
    code: |
      {your python code}
```

## Full Configuration Example:

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

  filelog:
    start_at: beginning
    include_file_name: true
    include: 
      - $LOGFILE

    operators:
      - type: move
        from: attributes["log.file.name"]
        to: resource["log.file.name"]

      - type: add
        field: attributes.app
        value: dev

processors:

  # - change resource attribute log.file.name to source.log
  # - add resource attribute cluster: dev
  # - filter out any logs that contain the word password
  # - add an attribute to each log: language: golang
  pytransform/logs:
    code: |
      # edit resource attributes
      for data in event['resourceLogs']:
        for attr in [
            attr for attr in data['resource']['attributes']
            if attr['key'] == 'log.file.name'
        ]:
          attr['value']['stringValue'] = 'source.log'

        # add resource attribute
        data['resource']['attributes'].append({
          'key': 'cluser',
          'value': {
            'stringValue': 'dev'
          }
        })


      # filter/delete logs
      for data in event['resourceLogs']:
        for slog in  data['scopeLogs']:
          slog['logRecords'] = [ lr for lr in slog['logRecords'] if 'password' not in lr['body']['stringValue']]
          
          # add an attribute to each log
          for lr in slog['logRecords']:
            lr['attributes'].append({
              'key': 'language',
              'value': {
                'stringValue': 'golang'
              }})
              
      send(event)

  # - print event received to otel runtime log
  # - if there are no resources, add a resource attribute source pytransform
  # - prefix each metric name with pytransform
  pytransform/metrics:
    code: |
      print("received event")
      for md in event['resourceMetrics']:
        # if resources are empty
        if not md['resource']:
          md['resource'] = {
            'attributes': [
              {
                "key": "source",
                "value": {
                  "stringValue": "pytransform"
                }
              }
            ]
          }

        # prefix each metric name with pytransform
        for sm in md['scopeMetrics']:
          for m in sm['metrics']:
            m['name'] = 'pytransform.' + m['name']

      send(event)

  # - add resource attribute source pytransform
  # - filter out any spans with http.target /roll attribute
  pytransform/traces:
    code: |
      for td in event['resourceSpans']:
        # add resource attribute
        td['resource']['attributes'].append({
          'key': 'source',
          'value': {
            'stringValue': 'pytransform'
          }
        })

        # filter spans with http.target /roll attribute
        has_roll_attr = lambda attrs: [a for a in attrs if a['key'] == 'http.target' and a['value']['stringValue'] == '/roll']
        for sd in td['scopeSpans']:
          sd['spans'] = [
            s for s in sd['spans']
            if not has_roll_attr(s['attributes'])
          ]

      send(event)
exporters:
  logging:
    verbosity: detailed


service:
  pipelines:
    logs:
      receivers:
      - filelog
      processors:
      - pytransform/logs
      exporters:
      - logging

    metrics:
      receivers:
      - otlp
      processors:
      - pytransform/metrics
      exporters:
      - logging

    traces:
      receivers:
      - otlp
      processors:
      - pytransform/traces
      exporters:
      - logging
```

### Telemetry data types supported

Supports all telemetry data types:
- metrics
- logs
- traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@daidokoro

### Additional context

The code implementation for this processor has been written and tested, you can find it [here](https://github.com/daidokoro/opentelemetry-collector-contrib/tree/main/processor/pytransform) and via the PR [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/26721).
