### ISSUE TITLE
Adding log attributes to resource attributes

### ISSUE THREAD

**Issue by sairamsadanala** [open-telemetry/opentelemetry-collector-contrib#26989]
### Component(s)

processor/resource

## Description
Setting up otelcol-contrib abstraction layer to receive telemetry having multiple exporter (loki and Splunk). Otel-hub extracts Kubernetes namespace from log body using Transform processor and set loki.tenant hint so that loki exporter can send to Loki endpoint. Logs need to be routed b/w loki and Splunk based on namespace attributes. Currently i have the namespace in log attributes but Routing processor only support context(header) or resource attributes and hence trying to set resource attribute from log attribute.
## Steps to Reproduce

  transform:
    error_mode: ignore
    log_statements:
    - context: log
      statements:
      - set(attributes["cache"], ParseJSON(body)) where IsMatch(body[""], "^\\{")
      - set(attributes["tenant"], attributes["cache"]["kubernetes"]["namespace_name"])
      - set(attributes["loki.tenant"], "tenant")
      - delete_key(attributes, "cache")
    resource:
      attributes:
      - key: tenantname
        value: tenant 
        action: insert 
## Expected Result
tenantname resource attribute should be available.
## Actual Result
No resource attributes are available..

### Collector version

0.82

## Environment
OS: AWS EKS

### OpenTelemetry Collector configuration

```yaml
exporters:
  logging:
    verbosity: detailed
  loki:
    endpoint: http://XXXX/loki/api/v1/push
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_elapsed_time: 120s
      max_interval: 300s
    sending_queue:
      storage: file_storage/psq
    tls:
      insecure: false
      insecure_skip_verify: true
  splunk_hec/logs:
    endpoint: https://XXXXXXXXXX/services/collector
    retry_on_failure:
      enabled: true
      initial_interval: 10s
      max_elapsed_time: 60s
      max_interval: 60s
    sending_queue:
      storage: file_storage/psq
    timeout: 30s
    tls:
      insecure: false
      insecure_skip_verify: true
    token: 95c4beb5-c1b0-4735-bcd3-310cea0c9fa8
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
processors:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
 
  transform:
    error_mode: ignore
    log_statements:
    - context: log
      statements:
      - set(attributes["cache"], ParseJSON(body)) where IsMatch(body[""], "^\\{")
      - set(attributes["tenant"], attributes["cache"]["kubernetes"]["namespace_name"])
      - set(attributes["loki.tenant"], "tenant")
      - delete_key(attributes, "cache")
    resource:
      attributes:
      - key: tenantname
        value: tenant 
        action: insert 
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - logging
      - loki
      processors:
      - transform
      - resource
      receivers:
      - otlp
```

### Log output

```shell
Not seeing resource attribute(tenantname) which was being set in resource processor.
```
