### ISSUE TITLE
Duplicate policy names should yield an error

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector-contrib#27016]
The tail-sampling processor should refuse policies with duplicate names. Otherwise, the telemetry it generates becomes ambiguous, or incorrect.

              While we (me and @jmsnll) were trying to work out a solution internally (to see the various output of the metric), we realized a potential bug in that the tail sampler does not check for uniqueness in the policy name.  More concretely, if we use a config as below, where someone accidentally use identical name for two different policies

```yaml
receivers:
  otlp:
    protocols:
      grpc:
processors:
  tail_sampling:
    decision_wait: 5s
    policies:
      - name: status-code-policy
        type: status_code
        status_code:
          status_codes: [ERROR]
      - name: status-code-policy
        type: probabilistic
        probabilistic:
          sampling_percentage: 50
exporters:
  logging:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [logging]

```

then firing off 100 traces with `STATUS_CODE_UNSET` result in 

```shell
otelcol_processor_tail_sampling_count_traces_sampled{policy="status-code-policy",sampled="true",service_name="otelcontribcol",service_version="0.84.0-dev"} 49
```

which is true as per the config but deceiving to anyone without looking at the config.  As the label is taken from the policy context in `stats.RecordWithTags` and there is no check during the initial unmarshal, we can in theory give every single policy the same name which result in the metric being incorrect.  This issue with non-unique policy name remains regardless of whether this issue is fixed (and may have wider impact).

One would argue that no engineer should make the mistake of having non-unique policy name.  However, if a new (silence) tag say `final-decision` is introduced, it may clash with a config that is using that exact policy name `final-decision`. I am not sure how likely this scenario is but I thought it is worth flagging as we have already made that mistake ourselves.

_Originally posted by @edwintye in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25882#issuecomment-1719811798_
