### ISSUE TITLE
[processor/transform] unable to parse OTTL statement

### ISSUE THREAD

**Issue by nickv2002** [open-telemetry/opentelemetry-collector-contrib#27012]
### Component(s)

processor/transform

### Description
I'm trying to follow the [example from here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter#setting-resource-attributes-as-metric-labels) to add metric labels for Prometheus. It suggests using the transform processor like so in order to copy the most common resource attributes into metric labels:

```yaml
processor:
  transform:
    metric_statements:
      - context: metric
        statements:
        - set(attributes["namespace"], resource.attributes["k8s_namespace_name"])
        - set(attributes["container"], resource.attributes["k8s.container.name"])
        - set(attributes["pod"], resource.attributes["k8s.pod.name"])
        - set(attributes["cluster"], resource.attributes["k8s.cluster.name"])
```

Given that example I've simplified my collector config down to this simplified version:.

```yaml
processors:
  transform:
    metric_statements:
      - context: metric
        statements:
          - set(attributes["k8s_namespace_name"], resource.attributes["k8s_namespace_name"])
  resource:
    attributes:
      - key: environment_name
        value: dev
        action: insert
exporters:
  otlphttp:
    endpoint: <Omitted>
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resource, transform, batch]
      exporters: [otlphttp]
```

Unfortunately, with this configuration, the collector fails to start and complains with the following message:

> Error: invalid configuration: processors::transform: unable to parse OTTL statement "set(attributes[\"k8s_namespace_name\"], resource.attributes[\"k8s_namespace_name\"])": error while parsing arguments for call to "set": invalid argument at position 0: invalid metric path expression [{attributes [{0xc002ad2250 <nil>}]}]2023/09/20 00:43:53 collector server run finished with error: invalid configuration: processors::transform: unable to parse OTTL statement "set(attributes[\"k8s_namespace_name\"], resource.attributes[\"k8s_namespace_name\"])": error while parsing arguments for call to "set": invalid argument at position 0: invalid metric path expression [{attributes [{0xc002ad2250 <nil>}]}]

### Collector version

0.85.0

## Environment
docker image: otel/opentelemetry-collector-contrib:0.85.0

**Comment by TylerHelmuth** [comment]
The metric context does have have attributes because metrics don't have attributes. Try the datapoint context.

**Comment by nickv2002** [comment]
> The metric context does not have attributes because metrics don't have attributes. Try the datapoint context.

@TylerHelmuth thanks for that tip. I've got it working for several attributes that are now showing up with proper labels in Prometheus/Grafana. Here's an excerpt of my working config (for other's potential ref):

```yaml
processors:
  transform:
    trace_statements:
      - context: span
        statements:
        - set(resource.attributes["cluster"], "dev")
    metric_statements:
      - context: datapoint
        statements:
        - set(attributes["k8s_namespace"], resource.attributes["k8s.namespace.name"])
        - set(attributes["k8s_container"], resource.attributes["k8s.container.name"])
        - set(attributes["k8s_deployment"], resource.attributes["k8s.deployment.name"])
        - set(attributes["k8s_pod"], resource.attributes["k8s.pod.name"])
        - set(attributes["telemetry_sdk_language"], resource.attributes["telemetry.sdk.language"])
        - set(attributes["cluster"], "dev")
```

Seems like the documentation should be updated [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/cf286cf28e47f7d2a5b0343c32b88f658e56d8e4/exporter/prometheusexporter/README.md?plain=1#L88) and [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/cf286cf28e47f7d2a5b0343c32b88f658e56d8e4/exporter/prometheusremotewriteexporter/README.md?plain=1#L125)

I will see if I can make a quick PR for that.
