### ISSUE TITLE
Accept data from datadog agent

### ISSUE THREAD

**Issue by miki-sunlight** [open-telemetry/opentelemetry-collector-contrib#27045]
### Component(s)

receiver/datadog

### Describe the issue you're reporting

Hey, trying to collect traces from `DataDog agent` using the `OTEL collector` with the `DataDog Receiver`.
On `DataDog` side I set up another end point by adding this code to the `values.yaml` file:
```
agents:
  useConfigMap: true
  customAgentConfig:
    apm_config:
      additional_endpoints:
        "http://otel-collector-cli-service:8126":
          - "1234" 
```
On the `OTEL collector side` I added the `DataDog receiver`:
```
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      datadog:
        endpoint: 0.0.0.0:8126
        read_timeout: 60s
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        traces:
          receivers: [otlp, datadog]
```
When a trace is created I get the following `warn` on the `DataDog trace agent`:
```
trace-agent 2023-09-19 06:53:35 UTC | TRACE | WARN | (run.go:276 in Warnf) | Stats writer payload rejected by edge: 404 Not Found
```
The `OTEL collector` log show nothing.

If the `OTEL collector` is **unreachable**, The `DataDog agent` log this message:
```
trace-agent 2023-09-21 06:55:20 UTC | TRACE | WARN | (run.go:276 in Warnf) | Retried payload 4 times: Post "http://otel-collector-cli-service:8126/api/v0.2/traces": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Any idea what can be the problem? or if there is another way to collect `traces` from the `DataDog agent`?
