### ISSUE TITLE
[exporter/influxdb] influxdb exporter does not accept v1_compatibility config

### ISSUE THREAD

**Issue by otbe** [open-telemetry/opentelemetry-collector-contrib#27084]
### Component(s)

exporter/influxdb

## Description

I would like to use the influxdb exporter to send metrics to influx that the opentelemetry collector receives via OTLP.
Sadly I have to use the influx v1 compat mode and it seems like Im not able to configure it. Looks like theres a runtime error during constructing the basic auth header.

## Steps to Reproduce
You can simple take the config from below and put it into a docker container.
Something like this works in my machine: `docker run -v $(PWD)/otel.yml:/etc/otelcol-contrib/config.yaml otel/opentelemetry-collector-contrib:0.85.0`

## Expected Result
Should work :)

## Actual Result
panic, runtime error. Collector stops working at all.

### Collector version

0.85.0

## Environment
Docker image: otel/opentelemetry-collector-contrib:0.85.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 100
    spike_limit_mib: 20

exporters:
  influxdb:
    endpoint: https://foo.bar
    log_record_dimensions:
    span_dimensions:
    v1_compatibility:
      enabled: true
      db: foo
      username: bar
      password: baz

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter ]
      exporters: [ influxdb ]

  extensions: [ health_check ]
```

### Log output

```shell
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
encoding/base64.(*Encoding).Encode(0x68471e0?, {0x0?, 0x6fe1906?, 0x7da5688?}, {0x4001dfa478?, 0x40027b0a20?, 0x4001dfa448?})
        encoding/base64/base64.go:158 +0x284
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/influxdbexporter.composeWriteURL(0x4002822900)
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/influxdbexporter@v0.85.0/writer.go:92 +0x25c
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/influxdbexporter.newInfluxHTTPWriter({0x7dc84e0?, 0x4002841aa0}, 0x4002822900, {0x40023a4620, {0x7dcb000, 0x400282ec00}, {0x7dfd2a0, 0x40028411e0}, 0x0, {0x4002846740}})
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/influxdbexporter@v0.85.0/writer.go:43 +0x4c
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/influxdbexporter.createMetricsExporter({0x7e45808, 0xc9f4dc0}, {{{0x40027b1288, 0x8}, {0x0, 0x0}}, {0x40023a4620, {0x7dcb000, 0x400282ec00}, {0x7dfd2a0, ...}, ...}, ...}, ...)
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/influxdbexporter@v0.85.0/factory.go:94 +0x194
go.opentelemetry.io/collector/exporter.CreateMetricsFunc.CreateMetricsExporter(...)


```
```


### Additional context

_No response_
