### ISSUE TITLE
Parsing json logs with transform/logstransform processors

### ISSUE THREAD

**Issue by AsoTora** [open-telemetry/opentelemetry-collector-contrib#27095]
### Component(s)

processor/transform

### Describe the issue you're reporting

According to the previous issues (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16045, https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9410, etc) i have an option to parse my logs that are json via the [json_parser operator](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/json_parser.md). However, that is available only at logstransform, that is not included in the main build.

Question is, how to i parse my application logs recieved via the otlp? In my specific case i need to parse the unstructured json from python, but the concept seems a bit unclear in general. What is the status/workaround at the moment for that?

**for reference, here is the basic OtelCollector config i'm using:**
```yaml
receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      otlp/signoz:
        endpoint: "***:4317"
        tls:
          insecure: true
      logging:
        loglevel: debug
    processors:
      batch:
      transform:  #???
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging,otlp/signoz]
          processors: [batch]
        metrics:
          receivers: [otlp]
          exporters: [logging,otlp/signoz]
          processors: [batch]
        logs:
          receivers: [otlp]
          exporters: [logging,otlp/signoz]
          processors: [batch]
```
**log example:**
```json
{
  "attributes_float64": {},
  "attributes_int64": {
    "code_lineno": 169,
    "http_request_body_size": 0,
    "http_response_body_size": 61,
    "http_response_status_code": 200,
    "thread_id": 140711454365504
  },
  "attributes_string": {
    "api_gateway_name": "api",
    "code_filepath": "/opt/app/****.py",
    "code_function": "log_request",
    "code_namespace": "client",
    "http_request_body_content": "",
    "http_request_headers": "",
    "http_request_method": "GET",
    "http_response_body_content": "{\n  \"upcoming_date\": \"2023-10-02\",\n  \"hint\": null,\n  \"retry_days_num\": 1\n}",
    "http_response_headers": "",
    "log_kind": "api_gateway_request",
    "otelServiceName": "nat-public-api",
    "otelSpanID": "5f2de6422f144e4e",
    "otelTraceID": "bd220139d6b0ef00e03a79ba92999496",
    "thread_name": "MainThread",
    "url_fragment": "",
    "url_full": "http://autoinvest-api/v1/plans/upcoming-date/GOOG?day_of_month=1",
    "url_host": "autoinvest-api",
    "url_path": "/v1/plans/upcoming-date/GOOG",
    "url_scheme": "http"
  },
  "body": "GET http://api/v1/plans/upcoming-date/GOOG?day_of_month=1 [200]",
  "id": "2Vt0Q2NkuuyWF7hVtfTeewNZtHG",
  "resources_string": {
    "service_name": "api",
    "telemetry_sdk_language": "python",
    "telemetry_sdk_name": "opentelemetry",
    "telemetry_sdk_version": "1.19.0"
  },
  "severity_number": 9,
  "severity_text": "INFO",
  "span_id": "5f2de6422f144e4e",
  "trace_flags": 1,
  "trace_id": "bd220139d6b0ef00e03a79ba92999496",
  "timestamp": "2023-09-25T11:23:52.012100864Z"
}
```

How would one add json_parser operator to that?

Sorry if the question is stupid, i really don't get the concept. Thank you.
