### ISSUE TITLE
Not able to receive logs with multiple wildcards

### ISSUE THREAD

**Issue by kago-dk** [open-telemetry/opentelemetry-collector-contrib#27231]
### Component(s)

receiver/filelog

## Description
In OpenTelemetry Collector V0.86.0 (Windows 2022 Server), does a filelog receiver with the following configuration produce an error. 

The same configuration worked fine in OpenTelemetry Collector V0.85.0.

**Configuration**
`    - "C://Users//*//AppData//Local//Application//Logs//App*.log" `

**Error**
`2023-09-26T15:46:26.015-0700	warn	fileconsumer/file.go:61	finding files: find files with 'C://Users//*//AppData//Local//Application//Logs//App*.log' pattern: open Default User: Access is denied.`

## Steps to Reproduce
Use the "OpenTelemetry Collector configuration" included and check the OtelCol log file.

## Expected Result
The configuration that worked in V0.85.0 would still work in V0.86.0

### Collector version

v0.86.0

## Environment
Windows 2022 Server

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    - "C://Users//user1//AppData//Local//Application//Logs//App*.log"
    - "C://Users//*//AppData//Local//Application//Logs//App*.log"  
```
The first line works, while the second line does not work anymore.

### Log output
`2023-09-26T15:46:26.015-0700	warn	fileconsumer/file.go:61	finding files: find files with 'C://Users//*//AppData//Local//Application//Logs//App*.log' pattern: open Default User: Access is denied.`
