### ISSUE TITLE
Mezmo OTEL exporter does not accept Kubernetes Enrichment

### ISSUE THREAD

**Issue by 88nafees77** [open-telemetry/opentelemetry-collector-contrib#27238]
### Component(s)

exporter/mezmo

### Is your feature request related to a problem? Please describe.

I would like to request the addition of support for Mezmo Kubernetes enrichment in OpenTelemetry (OTel). 
I can see the all the kubernetes related logs in the otel agents and otel collector, but those data are not showing in mezmo UI.

As you can see in the below image, we are able to get all the logs in Mezmo but the Kubernetes info are not showing.

<img width="760" alt="Screenshot 2023-09-06 at 11 08 21 AM" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/36165540/ecaad3e5-8c0c-4ee2-9f44-87e9ad0b2a57">

### Describe the solution you'd like

I just want the support of Kubernetes enrichment with otel.

below is the configuration file of otel collector.

```
otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc: 
          http:
    processors:
      batch:
      k8sattributes:
    exporters:
      mezmo:
        ingest_url: "https://logs.mezmo.com/otel/ingest/rest"
        ingest_key: "<ingest_key>"
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [k8sattributes, batch]
          exporters: [mezmo]
      telemetry:
        logs:
          level: "debug"`
```
