### ISSUE TITLE
New component: Named Pipe Receiver

### ISSUE THREAD

**Issue by sinkingpoint** [open-telemetry/opentelemetry-collector-contrib#27234]
### The purpose and use-cases of the new component

It's sometimes useful to be able to sends telemetry to a collector running on a node over a named pipe, rather than having to deal with the overhead of network protocols, or the inherent disk buffering of writing to a file. I'd like to propose a receiver that has the ability to create a named pipe, and then read logs off of it, similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/tcplogreceiver or https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filereceiver

### Example configuration for the component

```
receivers:
  pipes:
    - path: /pipes/logs1
    - path: /pipes/logs2
      mode: 0600
  encoding: utf-8
  multiline: # A split.Config
    line_end_pattern: "\n"
  preserve_trailing_whitespaces: false # A trim.Config
```

I suspect the complete config would end up looking something like the filereceiver one, with multiline config etc.

### Telemetry data types supported

Logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@sinkingpoint 

### Sponsor (optional)

@djaglowski
