### ISSUE TITLE
azuremonitorexporter assign wrong parentId to span events

### ISSUE THREAD

**Issue by Obi-Dann** [open-telemetry/opentelemetry-collector-contrib#27233]
### Component(s)

exporter/azuremonitor

## Description
`azuremonitorexporter` seems to assign wrong parentId to span events. As the results, span events have the same parentId as the span, but should have spanId as the parentId IIUC.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/12251341/43be8622-d128-4a52-8a49-7d8d0681a49a)
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/12251341/b2317089-6588-45cf-bc81-5b19bbbd5d0b)

It looks like the issue is [here](https://github.com/pcwiese/opentelemetry-collector-contrib/blob/3a6f54773c1c494bb95e31307c2faefa6bd38403/exporter/azuremonitorexporter/trace_to_envelope.go#L134)
`newEnvelope` implementation should be different for span events, setting parentId to the spanId instead of [always setting](https://github.com/pcwiese/opentelemetry-collector-contrib/blob/3a6f54773c1c494bb95e31307c2faefa6bd38403/exporter/azuremonitorexporter/trace_to_envelope.go#L179C2-L179C2) parentId to the span's parent id

## Steps to Reproduce
Configure a collector with azuremonitor as an exported, set `spaneventsenabled: true` and ensure to send spans with events to the collector.

## Expected Result
Span events should have the spanId set as their parentId

## Actual Result
Span events have the span's parentId set as their parentId

### Collector version

0.85.0

## Environment
OS: macOS 13.6

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
  azuremonitor:
    instrumentation_key: ""
    spaneventsenabled: true

processors:
  batch:
    timeout: 10s
    send_batch_size: 1000

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, azuremonitor]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging, azuremonitor]
```
