### ISSUE TITLE
filelog: Allow placing attributes into Resource instead of LogRecord

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#2725]
All attributes extracted/parsed by filelog receiver currently go into LogRecord. It would be nice to be able to specify that some attributes should be populated into Resource. 

This can be useful for example for k8s log collection where we want to put k8s attributes such as k8s.pod.name into the Resource. See e.g. https://github.com/open-telemetry/opentelemetry-helm-charts/pull/38#discussion_r595989316

**Comment by tigrannajaryan** [comment]
@djaglowski FYI, this would be a useful addition to filelog.

**Comment by djaglowski** [comment]
This should be possible today, if my understanding is correct.

The [Entry](https://github.com/open-telemetry/opentelemetry-log-collection/blob/eb3a760bcf631b101c266fa0505c47a4d24d156b/entry/entry.go#L44) struct in `log-collection` has both a `Resource` and an `Attributes` map. The intention, as I understand it, is to translate [Resource into Resource](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f8c550fe19262199463401ac5c3fdce44130a31b/internal/stanza/converter.go#L31) and [Attributes into Attributes](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f8c550fe19262199463401ac5c3fdce44130a31b/internal/stanza/converter.go#L49). 

So I think this may just come down to a matter of placing the value into the appropriate map at the `log-collection` level.

**Comment by rockb1017** [comment]
@djaglowski Do you mean something like this in the operators?
```
      - type: metadata
        attributes:
          stream: 'EXPR($.stream)'
          k8s.container.name: 'EXPR($.container_name)'
          k8s.namespace.name: 'EXPR($.namespace)'
          k8s.pod.name: 'EXPR($.pod_name)'
          run_id: 'EXPR($.run_id)'
          k8s.pod.uid: 'EXPR($.uid)'
        resource:
          k8s.pod.uid: 'EXPR($.uid)'
```
