### ISSUE TITLE
Add opt-in option for k8sattributes to enrich well-known Kubernetes labels

### ISSUE THREAD

**Issue by smithclay** [open-telemetry/opentelemetry-collector-contrib#27261]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

Per the proposed recommendation in https://github.com/open-telemetry/semantic-conventions/pull/349, the kubernetes attribute processor should, in an opt-in basis, automatically enrich telemetry using Kubernetes well-known labels by mapping them to OpenTelemety resource attributes like `service.name` and `service.version`.

This helps end users uniformly adopt OpenTelemetry semantic conventions in Kubernetes environments and map pod metrics, traces, and logs to Kubernetes workloads identified by well-known labels like `app.kubernetes.io/name`.

### Describe the solution you'd like

An opt-in configuration option, something like:

```yaml
  k8sattributes:
    extract:
      wellKnownLabels: true
```

Which would functionally be equivalent to:

```yaml
  k8sattributes:
    extract:
      labels:
          - tag_name: service.name
            key: app.kubernetes.io/name
            from: pod
          - tag_name: service.version
            key: app.kubernetes.io/version
            from: pod
```

### Describe alternatives you've considered

This can be achieved right now through more verbose configuration, but it presumes the end-user is familiar with k8s conventions and otel conventions.

### Additional context

see also https://github.com/open-telemetry/semantic-conventions/issues/236
