### ISSUE TITLE
Flaky test: TestTracingGoldenData/otlp-opencensus port already in use

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector-contrib#27295]
### Component(s)

testbed

### What happened?

See https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6381486879/job/17318149920?pr=27291:

```
panic: cannot start pipelines: listen tcp 127.0.0.1:44455: bind: address already in use

goroutine 229 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*inProcessCollector).Start.func1()
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/testbed/testbed/in_process_collector.go:89 +0x[99](https://github.com/open-telemetry/opentelemetry-collector-contrib/actions/runs/6381486879/job/17318149920?pr=27291#step:7:100)
created by github.com/open-telemetry/opentelemetry-collector-contrib/testbed/testbed.(*inProcessCollector).Start
	/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/testbed/testbed/in_process_collector.go:85 +0x59e
exit status 2
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/testbed/correctnesstests/traces	3.165s
cat: results/TESTRESULTS.md: No such file or directory
make: Leaving directory '/home/runner/work/opentelemetry-collector-contrib/opentelemetry-collector-contrib/testbed'
make: *** [Makefile:37: run-correctness-traces-tests] Error 1
Error: Process completed with exit code 2.
```

### Collector version

mainline

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "127.0.0.1:44455"
exporters:
  opencensus:
    endpoint: "127.0.0.1:44455"
    tls:
      insecure: true
processors:
  
  batch:
    send_batch_size: 1024



extensions:

service:
  extensions:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [opencensus]
```
