### ISSUE TITLE
[googlecloud] Unable to map host.name resource labels to google resource labels

### ISSUE THREAD

**Issue by seanhoughton** [open-telemetry/opentelemetry-collector-contrib#2730]
**Describe the bug**

The `host.name` resource attribute is automatically removed from the set of resource labels and is therefore not available for mapping. Multiple Google resource types require a `node_id` label to be populated and the `host.name` attribute is a prime candidate for mapping here.

**Steps to reproduce**

Create a `googlecloud` exporter with the following configuration and send metrics with `host.name` set. Use the `generic_node` resource type which requires that `node_id` be provided. (see config below)

**What did you expect to see?**

I expect to see the value of `host.name` sent to Google as a `node_id` resource label.

**What did you see instead?**

The value is missing

**What version did you use?**

The `main` branch at `9fd7b9179ca872e8cf92b0e38bab37eaaa816150` 

**What config did you use?**

```yaml
exporters:
  googlecloud:
    project: myproject
    trace:
    metric:
    resource_mappings:
      - source_type: ""
        target_type: generic_node
        label_mappings:
          - source_key: host.name
            target_key: node_id
```

**Environment**

**Additional context**

The problem stems from the conversion of opentelemetry resource types to opencensus resource types. The label is converted into a first-class property here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/translator/internaldata/resource_to_oc.go#L106

It looks like the google cloud exporter deals with the opencensus type which means a few special labels are not available as sources for mapping. The workaround is to use an alternative label name in your instrumentation or add a new one with the `OTEL_RESOURCE_ATTRIBUTE` var if your app supports environment variable attribute discovery.
