### ISSUE TITLE
[processor/transform] Allow configuring "common" statements that apply to all signals

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#27407]
### Component(s)

transformprocessor

### Is your feature request related to a problem? Please describe.

At the moment the resourceprocessor lets you apply resource attribute transformations with minimal config:

```yaml
resource:
  attributes:
    - key: service.instance.id
       from_attribute: k8s.pod.uid
       action: insert
```

That configuration lets you add a new attribute named `service.instance.id` from the existing `k8s.pod.uid` attribute for traces, metrics, and logs.

The equivalent config in the transformprocessor would be

```yaml
transform:
  error_mode: ignore
  trace_statements:
    - context: resource
      statements:
        - set(attributes["service.instance.id"], attributes["k8s.pod.uid"]) where attributes["service.instance.id"] == nil

  metric_statements:
    - context: resource
      statements:
        - set(attributes["service.instance.id"], attributes["k8s.pod.uid"]) where attributes["service.instance.id"] == nil
        
  log_statements:
    - context: resource
      statements:
        - set(attributes["service.instance.id"], attributes["k8s.pod.uid"]) where attributes["service.instance.id"] == nil
```

Although the transformprocessor can achieve the same functionality, it isn't very ergonomic.

### Describe the solution you'd like

It would be nice to be able to configure some "common" statements that would be run in the resource or instrumentation scope context for each signal.  Something like

```yaml
transform:
  error_mode: ignore
  common_statements:
    - context: resource
      statements:
        - set(attributes["service.instance.id"], attributes["k8s.pod.uid"]) where attributes["service.instance.id"] == nil
```

These statements would then be added to the signal-specific statement lists.  We could allow the user to specify if they should be added to the front or end of the list.

I think to start we could restrict it to resource and scope contexts, but I think there is potential here to reproduce some attributesprocessor functionality as well.  A statement like `set(attributes["my-attribute"], attributes["my-other-attribute"])` could be run for `span`, `datapoint` or `log`.

### Additional context

Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18643
