### ISSUE TITLE
in k8s prometheus receiver does not have the ability to only scrape the metrics of pods on its own node

### ISSUE THREAD

**Issue by yutingcaicyt** [open-telemetry/opentelemetry-collector-contrib#27642]
### Component(s)

receiver/prometheus

### Is your feature request related to a problem? Please describe.

The collector is deployed by deamonset in my project. I want to collect metrics of apps in each pod with the Prometheus receiver, but I found the receiver can't only scrape the metrics of pods on its own node. Is there any method to solve this problem?

### Describe the solution you'd like

Prometheus receiver can scrape the metrics of pods on its own node.

**Comment by jinja2** [comment]
You can use the [receivercreator](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/receivercreator) with the `k8s_observer` for this. Refer to the prometheus receiver example [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/receivercreator#examples).

**Comment by dashpole** [comment]
You can also use the field selector in the prometheus scrape config:

```yaml
  scrape_configs:
    - job_name: kubernetes_pods
      kubernetes_sd_configs:
        - role: pod
          selectors:
            - role: pod
              field: spec.nodeName=$NODE_NAME
```

Then on your pod spec:

```yaml
  env:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
```
