### ISSUE TITLE
Custom Ingestion into multiple tables

### ISSUE THREAD

**Issue by cherish-inampudi** [open-telemetry/opentelemetry-collector-contrib#27643]
### Component(s)

exporter/clickhouse

### Describe the issue you're reporting

Can we have a provision to customize insert query or insert into multiple tables while exporting to clickhouse.

**Comment by Frapschen** [comment]
Hi @cherish-inampudi, have you tried using multiple clickhouse exporter? like:
```yaml
receivers:
  examplereceiver:
processors:
  batch:
    timeout: 5s
    send_batch_size: 100000
exporters:
  clickhouse/one:
    endpoint: tcp://127.0.0.1:9000?dial_timeout=10s&compress=lz4
    database: otel
    ttl_days: 3
    logs_table_name: otel_logs_one
    timeout: 5s
  clickhouse/two:
    endpoint: tcp://127.0.0.1:9000?dial_timeout=10s&compress=lz4
    database: otel
    ttl_days: 3
    logs_table_name: otel_logs_two
    timeout: 5s
service:
  pipelines:
    logs:
      receivers: [ examplereceiver ]
      processors: [ batch ]
      exporters: [ clickhouse/one,clickhouse/two ]
```

you can also combine a [routingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor).
