### ISSUE TITLE
failed to convert cpuinfo model to integer: strconv.ParseInt: parsing \"\": invalid syntax"

### ISSUE THREAD

**Issue by kago-dk** [open-telemetry/opentelemetry-collector-contrib#27675]
### Component(s)

processor/resourcedetection

## Description
After the implementation of "[processor/resourcedetection] Add support for host cpuinfo attributes #26533", I am getting this warning on my Windows Servers (2022). I have tried to disable most of the CPU attributes without any success.

**Warning log line**
2023-10-15T06:20:10.734-0700	warn	system/system.go:102	failed to get host cpuinfo	{"kind": "processor", "name": "resourcedetection/system", "pipeline": "metrics", "error": "failed to convert cpuinfo model to integer: strconv.ParseInt: parsing \"\": invalid syntax"}

## Steps to Reproduce
Use configuration

## Expected Result
No warnings should be shown on the Windows Servers.

### Collector version

v0.87.0

## Environment
Windows 2022 Server

### OpenTelemetry Collector configuration

```yaml
resourcedetection/system:
    detectors: ["system"]
    timeout: 2s
    override: false
    system:
      resource_attributes:
        host.arch:
          enabled: false
        host.cpu.cache.l2.size:
          enabled: false
        host.cpu.family:
          enabled: false
        host.cpu.model.id:
          enabled: false
        host.cpu.model.name:
          enabled: false
        host.cpu.stepping:
          enabled: false
        host.cpu.vendor.id:
          enabled: false
        host.id:
          enabled: true
        host.name:
          enabled: true
        os.description:
          enabled: true
        os.type:
          enabled: true         
      hostname_sources: ["os"]
```
