### ISSUE TITLE
Error: "http.method" is not a valid label name for metric

### ISSUE THREAD

**Issue by albertteoh** [open-telemetry/opentelemetry-collector-contrib#2772]
**Describe the bug**

Running Otel-collector from v0.22.0 with `spanmetrics` processor enabled in a trace pipeline results in errors and no metrics exported.

**Steps to reproduce**
Run Otel-collector with `spanmetrics` processor in a trace pipeline, then send traces containing span tags with periods `.` in them like `span.kind` or `http.method`.

**What did you expect to see?**
No error.

**What did you see instead?**
```
2021-03-19T21:37:24.397+1100	error	prometheusexporter/collector.go:259	failed to convert metric calls: "http.method" is not a valid label name for metric "calls"	{"component_kind": "exporter", "component_type": "prometheus", "component_name": "prometheus"}
go.opentelemetry.io/collector/exporter/prometheusexporter.(*collector).Collect
	/Users/albertteoh/go/pkg/mod/go.opentelemetry.io/collector@v0.22.1-0.20210313012550-03904de3dd61/exporter/prometheusexporter/collector.go:259
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
	/Users/albertteoh/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:448
```

**What version did you use?**
Version: v0.22.0

**What config did you use?**
Config:
```
 processors:
   batch:
   spanmetrics:
     metrics_exporter: prometheus
     dimensions:
     - name: http.method
       default: GET
     - name: http.status_code

 service:
   pipelines:
     traces:
       receivers: [jaeger]
       processors: [spanmetrics, batch]
       exporters: [jaeger]
     metrics/spanmetrics:
       receivers: [otlp/spanmetrics]
       exporters: [prometheus]
     metrics:
       receivers: [prometheus]
       exporters: [prometheusremotewrite]
```

**Environment**
OS: macOS
Compiler(if manually compiled): go 1.16

**Additional context**

I believe the root cause is from [this line](https://github.com/prometheus/common/blame/6e540be855969b2431824fe4efbd7a3ecee69318/model/labels.go#L100) that checks label names only contain alphanumeric chars or `_`, triggering errors for labels containing `.` like `span.kind` and `http.method`. 

That line of code is 5 years old, but there was a [recent rewrite of prometheus exporter](https://github.com/open-telemetry/opentelemetry-collector/pull/2393/files#diff-59096f8af265799d33e8452f5323b2928279fb46ae2765c62261deb7fcd12182R105) which calls [prometheus' client_golang](https://github.com/prometheus/client_golang/blame/4fbf74e2ce3c0983ead84b83e442b878471c492a/prometheus/desc.go#L98) lib, and I think this is why we're seeing this error from v0.22.0.

Given `.` char is invalid in prometheus labels, I propose to fix this in spanmetrics processor by replacing all non-alphanumeric chars with `_`.
