### ISSUE TITLE
Func Concat doesn't accept output of Split

### ISSUE THREAD

**Issue by Pwalne** [open-telemetry/opentelemetry-collector-contrib#27821]
### Component(s)

processor/transform

## Description
The OTL func `Concat` complains that the output from a func `Split` is not `StringLIkeGetter`

## Steps to Reproduce
Use `transformprocessor` to adjust attribute values (or a UUID)

## Expected Result
Setting the value of attribute["a"] to the split and then rejoined string.

## Actual Result
doesnt work; throws error if you try to pass a value from an attribute.

### Collector version

0.87.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
processors:
  transform:
    trace_statements:
      -context: span
        statements:
          - set(attributes["a"], Concat(Split(attributes["a"],"-"),""))
```

### Log output

```shell
error while parsing arguments for call to "set": invalid argument at position 1: error while parsing arguments for call to "Concat": invalid argument at position 0: must be a list of type StringLIkeGetter
```

**Comment by TylerHelmuth** [comment]
Oh thats interesting.  Since OTTL Converters don't have an associated Return Type yet, the grammar doesn't recognize that a Converter could be a valid input for the list it is expecting. In fact, the `Concat` currently needs a literal list, so you must supply `[]` in the statement, which means it wouldn't accept a list value from an attribute either.

I think we need to adjust the input type to be something like a `ListGetter[T]`, where T is the type of the thing in the list.  Probably needs touched up to handle the list type being a `StringLikeGetter`.

**Comment by TylerHelmuth** [comment]
For your needs though, you probably want to do 

```yaml
processors:
  transform:
    trace_statements:
      -context: span
        statements:
          - replace_pattern(attributes["a"], "-", "")
```

**Comment by Pwalne** [comment]
> For your needs though, you probably want to do
> 
> ```yaml
> processors:
>   transform:
>     trace_statements:
>       -context: span
>         statements:
>           - replace_pattern(attributes["a"], "-", "")
> ```

Yes, I ended up doing something like that. Although in our scenerio we have todo something such as:
```yaml
processors:
  transform:
    trace_statements:
      -context: span
        statements:
          -set(attributes["a"], attributes["b"])
          - replace_pattern(attributes["a"], "-", "")
          - set(trace_id.string, attributes["a"])
          - delete(atributes, "a")
```
