### ISSUE TITLE
[connectors/spanmetrics] Not included in contrib distribution, error decoding 'connectors': unknown type: "spanmetrics" 

### ISSUE THREAD

**Issue by nomadesoft** [open-telemetry/opentelemetry-collector-contrib#27851]
### Component(s)

connector/spanmetrics

## Description

I was trying to configure the connectors.spanmetrics following the official [documentation](https://opentelemetry.io/docs/collector/configuration/#connectors) of connectors, however the otel collector is finishing with error.

`local-otel-collector-1  | * error decoding 'connectors': unknown type: "spanmetrics" for id: "spanmetrics" (valid values: [forward])
local-otel-collector-1  | 2023/10/19 00:28:09 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
`

## Steps to Reproduce

1.- Add the connector.spanmetrics config in otel-collector.yaml

2. Try to run the otel collector

## Expected Result

Run successfully with no errors.

## Actual Result

error decoding 'connectors': unknown type: "spanmetrics" for id: "spanmetrics" (valid values: [forward])

### Collector version

0.87.0

## Environment
OS: Ubuntu 22.04.1
Docker image: otel/opentelemetry-collector   0.87.0 

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

extensions:
  health_check: {}

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    target_info:
      enabled: true
  logging:
    loglevel: debug
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code
    dimensions_cache_size: 1000
    aggregation_temporality: 'AGGREGATION_TEMPORALITY_CUMULATIVE'

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, logging, spanmetrics]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging, prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging]
```

### Log output

```shell
local-otel-collector-1  | Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
local-otel-collector-1  | 
local-otel-collector-1  | 
local-otel-collector-1  | * error decoding 'connectors': unknown type: "spanmetrics" for id: "spanmetrics" (valid values: [forward])
local-otel-collector-1  | 2023/10/19 00:28:09 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
local-otel-collector-1  | 
local-otel-collector-1  | 
local-otel-collector-1  | * error decoding 'connectors': unknown type: "spanmetrics" for id: "spanmetrics" (valid values: [forward])
```
