### ISSUE TITLE
[spanmetricsprocessor] Counter metrics missing _total suffix

### ISSUE THREAD

**Issue by albertteoh** [open-telemetry/opentelemetry-collector-contrib#2829]
**Describe the bug**
Previously, `spanmetrics` processor would output the "calls" metrics with the name: `calls_total` to follow the [metrics naming convention used by Prometheus](https://prometheus.io/docs/practices/naming/#metric-names).

However, we have recently discovered this is no longer the case and the metric name is now `calls` instead.

**Steps to reproduce**
Run otel-collector-contrib with `spanmetrics` processor, submitting spans. Attempting to query this data with the `calls_total` metric returns no data, but querying the `calls` metric returns data.

**What did you expect to see?**
Metrics data for queries on the `calls_total` metric.

**What did you see instead?**
No metrics data.

**What version did you use?**
Version: `v0.22.0`

**What config did you use?**
Config:
```
 processors:
   batch:
   spanmetrics:
     metrics_exporter: prometheus
     dimensions:
     - name: http.method
       default: GET
     - name: http.status_code

 service:
   pipelines:
     traces:
       receivers: [jaeger]
       processors: [spanmetrics, batch]
       exporters: [jaeger]
     metrics/spanmetrics:
       receivers: [otlp/spanmetrics]
       exporters: [prometheus]
     metrics:
       receivers: [prometheus]
       exporters: [prometheusremotewrite]
```

**Environment**
OS: macOS
Compiler(if manually compiled): go 1.16

**Additional context**
This bug was introduced with the recent [prometheus exporter rewrite](https://github.com/open-telemetry/opentelemetry-collector/pull/2393/files#diff-59096f8af265799d33e8452f5323b2928279fb46ae2765c62261deb7fcd12182R105); specifically, [this line of code](https://github.com/open-telemetry/opentelemetry-collector/blob/c5c673d351e463a0da0acf19b3292b7ad8898692/exporter/prometheusexporter/collector.go#L136) that checks the `IsMonotonic` property of a `Sum` metric, which was not set before.

Is there any way we can write integration tests to prevent such breaking behaviour?

**Proposed Fix**
Set `IsMonotic=true` property of the `IntSum` metric in `spanmetrics` processor.
