### ISSUE TITLE
[spanmetricsprocessor] lacenty_bucket histogram +Inf label inconsistency

### ISSUE THREAD

**Issue by yeya24** [open-telemetry/opentelemetry-collector-contrib#2838]
**Describe the bug**

When using `spanmetricsprocessor`, if the output exporter is `prometheus`, then the `lantency_bucket` metrics have a bucket for +Inf and Math.MaxFloat64.

![Screenshot from 2021-03-23 23-16-14](https://user-images.githubusercontent.com/25150124/112249263-d0d57880-8c2d-11eb-8257-e799178de249.png)

If the output exporter is `prometheusremotewrite`, then the `latency_bucket` metric doesn't contain the `+Inf` bucket

![Screenshot from 2021-03-23 23-14-33](https://user-images.githubusercontent.com/25150124/112249141-a2f03400-8c2d-11eb-8336-8c9e9aab7fd8.png)

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

Use the config below

``` yaml
receivers:
  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:12345"

  otlp:
    protocols:
      grpc:
      http:

processors:
  spanmetrics:
    metrics_exporter: prometheusremotewrite
    latency_histogram_buckets: [2ms, 6ms, 10ms, 100ms, 250ms]
    dimensions:
      - name: namespace
      - name: reason
#      - name: http.method
#        default: GET

exporters:
  otlp/spanmetrics:
    endpoint: "localhost:55680"
    insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample

  prometheusremotewrite:
    endpoint: "http://localhost:9090/api/v1/write"

  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics]
      exporters: [logging]

  # The exporter name must match the metrics_exporter name.
  # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics:
      # This receiver is just a dummy and never used.
      # Added to pass validation requiring at least one receiver in a pipeline.
      receivers: [otlp/spanmetrics]
      # The metrics_exporter must be present in this list.
      exporters: [prometheusremotewrite, logging]

```

**What did you expect to see?**
A clear and concise description of what you expected to see.

Ideally, the bucket for `Math.MaxFloat64` shouldn't exist. I just want to see the upper bound of `+Inf`.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: 0.23.0

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
