### ISSUE TITLE
Missing Metrics (cpu.utilization_per_core) after upgrade from 0.10.0 to 0.19.0

### ISSUE THREAD

**Issue by AchimGrolimund** [open-telemetry/opentelemetry-collector-contrib#2846]
**Describe the bug**
We do not receive data (cpu.utilization_per_core) on SignalFX anymore since version 0.19.0

**Steps to reproduce**
SignalFX-Agent Monitor:
```
  signalFxAccessToken: xxxx
  ingestUrl: xxxx
  apiUrl: xxxx
  eventEndpointUrl: xxxx
  intervalSeconds: 10
  logging:
    level: info
  
  observers:
    - type: host
  procPath: /proc
  
  monitors:
    - '"#from"': "/etc/signalfx/monitors/*.yaml"
      flatten: true
      optional: true
    - type: host-metadata
    - type: processlist
    - type: cpu
      reportPerCPU: true
      extraMetrics:      
       - cpu.utilization_per_core
    - type: filesystems
    - type: disk-io
    - type: net-io
    - type: load
    - type: memory
    - type: vmem
```

With the Version 0.10.0 we recive the Metrics `cpu.utilization_per_core`.
after update to version 0.19.0 we lost some metrics on SignalFX as example this `cpu.utilization_per_core`

**What did you expect to see?**

Metric about `cpu.utilization_per_core`

**What did you see instead?**

Nothing

**What version did you use?**
Version: 0.10.0 --> It works
Version 0.19.0 --> Dosnt work

**What config did you use?**

```yaml
extensions:
  health_check:
  zpages:
receivers:
  sapm:
  signalfx:
  # This section is used to collect the OpenTelemetry Collector metrics
  # Even if just a SignalFx µAPM customer, these metrics are included
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']
              # If you want to use the environment filter
              # In the SignalFx dashboard
              labels:
                environment: {{ otel_label_environment }} # set with Ansible
          metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: '.*grpc_io.*'
              action: drop
  # Enable Zipkin to support Istio Mixer Adapter
  # https://github.com/signalfx/signalfx-istio-adapter
  zipkin:
processors:
  batch:
  # Optional: If you have a different environment tag name
  # If this option is enabled it must be added to the pipeline section below
  attributes/copyfromexistingkey:
    actions:
      - key: environment
        from_attribute: env
        action: upsert
  # Optional: If you want to add an environment tag
  # If this option is enabled it must be added to the pipeline section below
  attributes/newenvironment:
    actions:
      - key: environment
        value: "{{ otel_label_environment }}" # set with Ansible
        action: insert

  # for demo environment
  attributes/addenvdemo:
    include:
      match_type: regexp
      services: [^test-.*]
    actions:
      - key: environment
        action: upsert
        value: demo

  # for devl environment
  attributes/addenvdevl:
    include:
      match_type: regexp
      services: [.*-devl-.*]
    actions:
      - key: environment
        action: upsert
        value: devl

  # for intg environment
  attributes/addenvintg:
    include:
      match_type: regexp
      services: [.*-intg-.*]
    actions:
      - key: environment
        action: upsert
        value: intg

  # for prod environment
  attributes/addenvprod:
    include:
      match_type: regexp
      services: [.*-prod-.*]
    actions:
      - key: environment
        action: upsert
        value: prod

  # for cicd environment
  attributes/addenvcicd:
    include:
      match_type: regexp
      services: [.*-cicd-.*]
    actions:
      - key: environment
        action: upsert
        value: cicd

  # Add Label to all Ressources
  resource:
    attributes:
    - key: zone
      value: "Xxxxx"
      action: upsert
    - key: serviceTime
      value: 1
      action: insert

exporters:
  # Traces
  sapm:
    access_token: "{{exporters_sapm_access_token}}" # set with Ansible
    endpoint: "https://ingest.eu0.signalfx.com/v2/trace"
  # Metrics
  signalfx:
    access_token: "{{exporters_signalfx_access_token}}" # set with Ansible
    realm: "eu0"
service:
  pipelines:
    traces:
      receivers: [sapm, zipkin]
      processors: [batch, attributes/copyfromexistingkey,attributes/newenvironment,attributes/addenvdemo, attributes/addenvdevl, attributes/addenvintg, attributes/addenvprod, attributes/addenvcicd]
      exporters: [sapm]
    metrics:
      receivers: [signalfx, prometheus]
      processors: [resource, batch]
      exporters: [signalfx]
  extensions: [health_check, zpages]
```

**Environment**
RHEL 8 Linux on AWS EC2 C5.Large

**Additional context**
