### ISSUE TITLE
K8s filelog collection: put the log record in the Body as a string

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-collector-contrib#2851]
**Describe the bug**
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2266#issuecomment-789986345
log record is wrapped in a json with key `log`. it should be just plain string.

**Steps to reproduce**
Read files using filelog

**What did you expect to see?**
"EPS: 98"
**What did you see instead?**
{"log":"EPS: 98\n"}
![image](https://user-images.githubusercontent.com/12387289/112512390-8f89b980-8d50-11eb-99f1-2a15d7b02391.png)

**What version did you use?**
0.22.0

**Comment by tigrannajaryan** [comment]
@pmm-sumo @djaglowski this is the bug that I mentioned about when were looking at k8s collection. Can one you take this?

**Comment by djaglowski** [comment]
@sumo-drosiek would you be able to validate #2873?

**Comment by pmm-sumo** [comment]
@djaglowski what do you think, should we be good with just using #2873 or perhaps it would be better to make a deeper change in the source code?

**Comment by djaglowski** [comment]
@pmm-sumo There are probably some things we can do to improve the usability of the parsing operations, but I think you are maybe referring to whether or not we should need the `"log"` field in the first place? There is a specific reason it exists in this case - it's because there are other values that need to be parsed, and those values temporarily exist alongside `"log"` until they are parsed.

#### Detailed Version
Note that this regex operation is capturing multiple values, `"time"`, `"stream"`, and `"log"` (and also `"logtag"`, but this doesn't appear to be used, so I am omitting from this example):
```yaml
- type: regex_parser
    id: parser-containerd
    regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$'
    ...
```
At this point, the entry looks something like this (showing only the parts relevant to this example):
```json
{
  "record": {  
    "time": "...",
    "stream": "...",
    "log": "The rest of the log line",
  },
  "attributes": { },
  "timestamp": "default,
  ...
}
```

Then some additional processing is done based on the other values:
```yaml
...
  timestamp:
    parse_from: time # parses "time" to timestamp
    ...
- type: metadata
    attributes:
      stream: 'EXPR($.stream)' # moves "stream" to attributes
```

Now we have:
```json
{
  "record": {  
    "stream": "...",
    "log": "The rest of the log line",
  },
  "attributes": { 
    "stream": "stderr",
  },
  "timestamp": "2021-03-25T...",
  ...
}
```

Now we can clean up the record:
```
ops:
  - move:
       from: log
       to: $
```

This leaves us with:
```json
{
  "record": "The rest of the log line",
  "attributes": { 
    "stream": "stderr",
  },
  "timestamp": "2021-03-25T...",
  ...
}
```

There are a few minor things that I would like to improve here though, such as [flattening the restructure operator](https://github.com/open-telemetry/opentelemetry-log-collection/issues/68), but I'm not sure what specifically we should do to improve this parsing pipeline.

**Comment by tigrannajaryan** [comment]
@djaglowski a slightly different approach that possibly could work is for regex operator to extract value directly into "attributes" and also have an option to specify which extracted value becomes the new value of the "record" (or "Body" in otel terminology). For example:

```yaml
type: regex_parser
    id: parser-containerd
    regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$'
    set_body_from: log # this refers to an extracted field name in the line above
```
Now once this is applied the data will look like this:
```json
{
  "record": "The rest of the log line",
  "attributes": {
    "time": "...",
    "stream": "...",
  },
  "timestamp": "default,
  ...
}
```

I don't know how feasible this, just an idea.

**Comment by djaglowski** [comment]
I think when you consider a wider set of log parsing cases, you end up needing the ability to parse into an arbitrary object that you can then manipulate as needed. You might need to parse further. You might keep or discard any field at all.

This isn't really a regex specific problem either - it's a general question of how parsing operations should behave. To me, the primary action you are taking with any parsing operation is to structure to the log entry. Once the values are individually accessible, you can parse them further or move them into the appropriate special fields (resource, attributes, timestamp, severity).

All that said, there are many scenarios such as this that are much more constrained. Taking inspiration from @tigrannajaryan's suggestion, I think there is potentially a way in which we can support cases such as this one, while still allowing arbitrary field manipulations if needed. 

We already support a concept of "nested parsers" for `timestamp` and `severity`. These are just subsequent operations that can be specified in a more concise because they are embedded within all parsers:
```yaml
- type: regex_parser
  id: my_regex
  regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<sev>[^ ]*) (?P<uuid>[^ ]*) (?P<log>.*)$'
  timestamp: # this is a timestamp_parser embedded within the regex_parser
    parse_from: time
    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
  severity: # this is a severity_parser embedded within the regex_parser
    parse_from: sev
```
What is really happening here is essentially the same thing as if you specified:
```yaml
- type: regex_parser
  id: my_regex
  regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<sev>[^ ]*) (?P<uuid>[^ ]*) (?P<log>.*)$'
- type: timestamp # separate operator
  parse_from: time
  layout: '%Y-%m-%dT%H:%M:%S.%LZ'
- type: severity # separate operator
  parse_from: sev
```

So working with the same idea in mind, would it be helpful to embed additional operators into all parsers?

The `metadata` operator (possibly with some modifications) could also be embedded in the same way. This would allow roughly:
```yaml
- type: regex_parser
  id: my_regex
  regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<sev>[^ ]*) (?P<uuid>[^ ]*) (?P<log>.*)$'
  timestamp:
    parse_from: time
    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
  severity:
    parse_from: sev
  attributes:
    - stream
  resource:
    - uuid
```

Tigran's suggested `set_body_from: log` would fit the pattern just as well. Maybe this is a special field on parsers, or maybe it's just a simplified version of `restructure.move`, but this would allow roughly:

```yaml
- type: regex_parser
  id: my_regex
  regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<sev>[^ ]*) (?P<uuid>[^ ]*) (?P<log>.*)$'
  timestamp:
    parse_from: time
    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
  severity:
    parse_from: sev
  attributes:
    - stream
  resource:
    - uuid
  record: log
```

If instead, `log` needed to be parsed further, a user could do:
```yaml
- type: regex_parser
  id: my_regex
  regex: '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<sev>[^ ]*) (?P<uuid>[^ ]*) (?P<log>.*)$'
  timestamp:
    parse_from: time
    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
  severity:
    parse_from: sev
  attributes:
    - stream
  resource:
    - uuid
- type: regex_parser
  id: more_parsing
  parse_from: log
  regex: '^(?P<some_id>[^ ^Z]+Z) (?P<the_rest>.*)$'
  resource:
    - some_id
  record: the_rest
```

There are some nuances here as well, such as how ordering is applied, but these seem manageable. 

Thoughts on this?
