### ISSUE TITLE
[connector/spanmetrics] Add option exclude_dimensions_values

### ISSUE THREAD

**Issue by mar4uk** [open-telemetry/opentelemetry-collector-contrib#28568]
### Component(s)

connector/spanmetrics

### Is your feature request related to a problem? Please describe.

Some data in metrics spanmetrics connector generates is not needed in specific cases. To reduce cardinality (and the price for storing those metrics) would be good to have an opportunity to exclude some dimension values

### Describe the solution you'd like

Add new options to the `spanmetrics` config: `exclude_dimensions_values`

For example, the user is not interested in metrics that have `span.kind != SPAN_KIND_SERVER`. So the user can exclude those metrics by adding the option:
```
exclude_dimensions_values:
  - name: span.kind
     values: ['SPAN_KIND_INTERNAL','SPAN_KIND_CLIENT','SPAN_KIND_PRODUCER']
```

### Describe alternatives you've considered

The workaround to exclude metrics with specific dimension values is to use [filterprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor):
```
  filter/drop_unneeded_span_metrics:
    error_mode: ignore
    metrics:
      datapoint:
          - 'IsMatch(metric.name, "traces.spanmetrics.calls") and IsMatch(attributes["span.kind"], "SPAN_KIND_INTERNAL|SPAN_KIND_CLIENT|SPAN_KIND_PRODUCER")'
```
