### ISSUE TITLE
Otel Processor metric filter is not working as expected

### ISSUE THREAD

**Issue by prateekpatel** [open-telemetry/opentelemetry-collector-contrib#28585]
### Component(s)

processor/filter

### What happened?

I have the following configuration for my OpenTelemetry (otel) filter processor. Within the receiver configuration, kubelet is scraping node metrics, and the filter is intended to selectively include or exclude metrics based on the filter configuration.

Here's the scrape configuration job in the receiver:

job_name: kubelet
scrape_interval: 1m
scheme: https
tls_config:
  ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  insecure_skip_verify: true
bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
kubernetes_sd_configs:
  - role: node
    api_server: null
relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
    action: replace
    target_label: __metrics_path__
    regex: (ip-.*)
    replacement: /api/v1/nodes/$${1}/proxy/metrics

In the filter configuration:

filter/metrics:
  error_mode: ignore
  metrics:
    include:
      match_type: regexp
      metric_names:
        - otelcol_receiver_accepted_metric_points_total$
        - jvm_memory_used_bytes$
        - jvm_threads_states_threads$
        - container_cpu_usage_seconds_total$
        - kubelet_runtime_operations_duration_seconds_bucket$

However, I'm encountering an issue. While I expect to see the metric name kubelet_runtime_operations_duration_seconds_bucket,' I also observe metrics like 'kubelet_runtime_operations_duration_seconds_sum' and 'kubelet_runtime_operations_duration_seconds_total' in Grafana. Any guidance or insights on resolving this would be greatly appreciated."
<img width="1402" alt="Screenshot 2023-10-24 at 16 34 24" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17063624/0f916674-c822-455e-a529-c1247a4dbfa3">

I tried below with no success

filter/metrics:
        error_mode: ignore
        metrics:
          include:
            match_type: strict
            metric_names:
              - otelcol_receiver_accepted_metric_points_total
              - jvm_memory_used_bytes
              - jvm_threads_states_threads
              - container_cpu_usage_seconds_total
              - kubelet_runtime_operations_duration_seconds 

 filter/metrics:
        error_mode: ignore
        metrics:
          include:
            match_type: regexp
            metric_names:
              - otelcol.*
              - jvm_memory_used_bytes
              - jvm_threads_states_threads
              - container_cpu_usage_seconds_total
              - kubelet_runtime_operations_duration_seconds_buck.*
              - volume_operation_total_seconds_bucket.* 

### Collector version

refinery version v0.17.0

### OpenTelemetry Collector configuration

```yaml
receivers:

  # This section below is used to collect the metric
  prometheus/internal:
    config:
      scrape_configs:
        - job_name: cadvisor
          scrape_interval: 1m
          scheme: https
          metrics_path: /metrics/cadvisor
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: __metrics_path__
            regex: (ip-.*)
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor


        - job_name: kubelet
          scrape_interval: 1m
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
              api_server: null
          relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            action: replace
            target_label: __metrics_path__
            regex: (ip-.*)
            replacement: /api/v1/nodes/$1/proxy/metrics
processors:
  memory_limiter/with-settings:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 20

 
  batch:
    timeout: 5s
    send_batch_size: 8192
    send_batch_max_size: 0

  # Detect if the collector is running on a cloud system. Overrides resource attributes set by receivers.
  # Detector order is important: the `system` detector goes last, so it can't preclude cloud detectors from setting host/os info.
  resourcedetection/internal:
    detectors: [ gcp, ecs, ec2, azure, system ]
    override: true            
  filter/metrics:
    error_mode: propagate
    metrics:
      include:
        match_type: regexp
        metric_names:
          - otel.*
          - container_cpu_.*
          - jvm_gc.*
          - container_mem.*
          - container_tasks_state.*
          - container_blkio_device_usage_total.*
          - jvm.Memory.pools.Eden-Space.*
          - kubelet_runtime_operations_duration_seconds_*
          - kubelet_volume_stat*
exporters:
 

  logging:
    verbosity: normal
    sampling_initial: 2
    sampling_thereafter: 500
    
  prometheusremotewrite:
    endpoint: {remote_write}     
    auth:
      authenticator: sigv4auth
pipelines:
    metrics/general:
      receivers: 
        - prometheus/internal
      processors:
        - memory_limiter/with-settings 
        
        - filter/metrics
        
        - batch
      exporters:
        - logging
        - prometheusremotewrite
```

**Comment by crobert-1** [comment]
Hello @prateekpatel, just want to make sure I understand: From your configuration it looks like you're explicitly including metrics that match the filter `kubelet_runtime_operations_duration_seconds_*`. Then from your description you say that you expect `kubelet_runtime_operations_duration_seconds_bucket`, but don't expect `kubelet_runtime_operations_duration_seconds_sum` and `kubelet_runtime_operations_duration_seconds_total`.

Can you share exactly which metric names you want, and which ones you don't want? Then for the configurations that aren't working, can you share what their output is, and how it's not matching what you'd expect?

**Comment by kizitonzeka** [comment]
Hi @crobert-1 , I am working together with @prateekpatel on this. 
When `kubelet_runtime_operations_duration_seconds_*` is used we are able to see all `kubelet_runtime_operations_duration_seconds_`(bucket|count|sum) but when we try to get `kubelet_runtime_operations_duration_seconds_bucket` just by itself, we dont see the metric. In the case above we are using regexp match type.
I also tried to use strict match type to include kubelet_runtime_operations_duration_seconds_bucket I dont see the metric.

I made a slack post on this.
https://cloud-native.slack.com/archives/C01N6P7KR6W/p1698844433792289

**Comment by crobert-1** [comment]
_Copying current status and question from the Slack thread_

The goal is to keep **only** the `kubelet_runtime_operations_duration_seconds_bucket` metric. Here's the config being used:
```
filter/metrics:
        error_mode: propagate
        metrics:
          include:
            match_type: strict
            metric_names:
              - kubelet_runtime_operations_duration_seconds_bucket
```
With this filter in place all metrics end up being filtered, including the `kubelet_runtime_operations_duration_seconds_bucket` metric that is supposed to be included.

**Comment by kizitonzeka** [comment]
@crobert-1 could this behaviour be because this is a histogram metric type and _bucket, _sum and _count are considered datapoints where as filtering is done based on [metric name](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ad6fa27ad929aa2884e1c2d28bf3cc4ed2627310/internal/filter/filtermetric/name_matcher.go#L36) which in this case is `kubelet_runtime_operations_duration_seconds`?
I have also observed the same behaviour in other histogram metrics such as `otelcol_processor_batch_batch_send_size` and `storage_operation_duration_seconds`.

**Comment by kizitonzeka** [comment]
@TylerHelmuth Yes, the metric name is `kubelet_runtime_operations_duration_seconds` as on the screenshot. Just to confirm as on my previous comment, should I not expect to filter based on `bucket`, `sum` or `count` for this type of metric?

<img width="926" alt="Screenshot 2023-11-06 at 16 02 23" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/50271698/af56d625-5151-428d-a4fe-aa0bcd2b70ac">

**Comment by TylerHelmuth** [comment]
Correct, if you filter by metric name it would drop (or keep) the entire metric and all of its datapoints.

**Comment by crobert-1** [comment]
Is there anything else that we can do to help here, or are you able to get filtering working the way you need now? We can close this issue if there's nothing left to do here.

**Comment by kizitonzeka** [comment]
Thank you so much @crobert-1 @TylerHelmuth, we have more understanding now on how filtering is working and we have made it to suit our need. This issue can be closed.

**Comment by karvounis-form3** [comment]
@kizitonzeka I am interested to hear how you made it work. I am also facing issues with it. We transform Prometheus metrics from Delta to Cumulative temporality and we have metrics like:
- `metricA_bucket`
- `metricA_sum`
- `metricA_count`

However, when I am trying to use:

```yaml
processors:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - metricA_bucket
```

`metricA_bucket` still appears in Grafana
