### ISSUE TITLE
Can using access and secret key to login in aws account

### ISSUE THREAD

**Issue by matheusrosmaninho** [open-telemetry/opentelemetry-collector-contrib#28667]
### Component(s)

exporter/awss3

### Is your feature request related to a problem? Please describe.

I would like enter the credentials of AWS for login in account

### Describe the solution you'd like

The credential are optional, if don't use  don't need pass nothing

**Comment by crobert-1** [comment]
From the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awss3exporter#aws-credential-configuration) there's a link that explains how to [specify credentials to AWS](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials). This looks like the best practice for accomplishing what you want.

Can you share why it would be better to specify credentials in the config file instead of how it's currently done?

**Comment by matheusrosmaninho** [comment]
> From the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awss3exporter#aws-credential-configuration) there's a link that explains how to [specify credentials to AWS](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials). This looks like the best practice for accomplishing what you want.
> 
> Can you share why it would be better to specify credentials in the config file instead of how it's currently done?

Hi,
I'm using the container otel/opentelemetry-collector-contrib and need describe the credentials in the config.yaml

I tried copy ~/.aws folder inside the container, but doesn't work
I tried create the environment AWS_PROFILE, doesn't work too

If you could have the option of putting the credentials in the file, it would be a solution. Equals the other parameters

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/93738948/876899dd-ad9e-4400-97d5-cf8c0e846758)

**Comment by crobert-1** [comment]
I believe you can accomplish this by [passing environment variables into your docker container](https://phoenixnap.com/kb/docker-environment-variables). 

Are you passing the environment variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN`) into the container?

**Comment by matheusrosmaninho** [comment]
In the aws sdk for go the default login use the environment `AWS_PROFILE` and read `~/.aws/credentials`  file

> I tried copy ~/.aws folder inside the container, but doesn't work
> I tried create the environment AWS_PROFILE, doesn't work too

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/93738948/ff352c6f-5029-4cc8-8df3-2a21fc7cc904)

**Comment by crobert-1** [comment]
It looks like there are some ways to mount the credentials file if required, or specify the environment variables. Here's a [stack overflow](https://stackoverflow.com/questions/57297867/how-to-get-aws-credentials-and-access-to-s3-on-docker) thread on this.

**Comment by matheusrosmaninho** [comment]
In the code I can't pass the access key and secret key. The code get this credentials in default profile

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/511b04b63fffb9060c88b8dc9089db00a9a09ce9/exporter/awss3exporter/s3_writer.go#L49

**Comment by crobert-1** [comment]
Can you share your configuration? I might be missing something so it would help to know exactly how you're trying to run the collector in a container. The collector's config file, any kind of dockerfile/CLI command being used would be helpful.

**Comment by matheusrosmaninho** [comment]
Sure :)

`docker-compose.yml`

```
version: "3.8"
services:
  collector:
    container_name: collector
    build:
      context: .
      args:
        COLLECTOR_VERSION: 0.88.0
    ports:
      - 4318:4318 # OTLP http receiver
      - 4317:4317 # OTLP http receiver
    volumes:
      - ./aws:/.aws
    environment:
      AWS_PROFILE: "default"
```

`Dockerfile`

```
ARG COLLECTOR_VERSION

FROM otel/opentelemetry-collector-contrib:${COLLECTOR_VERSION}

COPY ./otel-collector-config.yaml /etc/otel-collector-config

COPY ./aws ~/.aws

CMD [ "--config=/etc/otel-collector-config" ]

EXPOSE 4317
EXPOSE 4318
```

`Config.yaml`

```
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317


processors:
  batch:
    timeout: 5s

extensions:
  health_check:
  basicauth:
    client_auth:
      username: <grafana_cloud_username>
      password: <grafana_cloud_password>


exporters:
  logging:
    verbosity: detailed

  otlphttp:
    auth:
      authenticator: basicauth
    endpoint: <grafana_endpoint>

  awss3:
    s3uploader:
      region: 'us-east-1'
      s3_bucket: 'bucket-teste-otel'
      s3_prefix: 'metric'
      s3_partition: 'minute'

service:
  extensions: [basicauth, health_check]
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: batch
    #   exporters: [otlphttp]

    # metrics:
    #   receivers: [otlp]
    #   processors: batch
    #   exporters: [logging, otlphttp]

    logs:
      receivers: [otlp]
      processors: batch
      exporters: [logging, otlphttp, awss3]
```

The error message:

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/93738948/4d7a742e-bd1b-4c46-9630-43e17df78a88)

**Comment by crobert-1** [comment]
I'll defer to the code owners at this point since they're the best suited to help. I believe the authentication can be done with the correct mounting path for the `aws/credentials` file, or adding the right environment variables, but I'll let others add more information here.

**Comment by tkanhe-karini** [comment]
According to https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/#specifying-credentials
We can also give environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION) in docker environment like this:

docker-compose.yaml
```
version: '3'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    environment:
      AWS_ACCESS_KEY_ID: "AK*************"
      AWS_SECRET_ACCESS_KEY: "MA**************"
      AWS_REGION: "us-east-1"
``````

otel-collector-config.yaml
```
receivers:
  otlp: # the OTLP receiver the app is sending logs to
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s

exporters:
  awss3:
    s3uploader:
      region: "us-east-1"
      s3_bucket: "otel-traces-test"
      s3_prefix: "traces"
      s3_partition: "minute"
      disable_ssl: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awss3]
```
