### ISSUE TITLE
[exporter/pulsar] Make pulsarexporter configuration more configurable

### ISSUE THREAD

**Issue by dao-jun** [open-telemetry/opentelemetry-collector-contrib#28684]
### Component(s)

exporter/pulsar

### Is your feature request related to a problem? Please describe.

Currently, in pulsar_exporter, configuration items only supports specify a single topic name for traces/metrics/logs.

And traces/metrics/logs exporter has default topic name(otlp_spans for traces, otlp_logs for logs and otlp_metrics for metrics),  say, if users specify a topic for traces, but couldn't specify topic for logs and metrics. If users want to start a metrics exporter pipeline, it will be failed, because `otlp_spans` `otlp_logs` and `otlp_metrics` is not pulsar topic name pattern.

A topic name pattern must comply with a certain patter(pulsar://tenant/namespace/topic_name, example: pulsar://public/default/otlp_spans).

Also, pulsar_exporter only provide a single `encoding` configuration for logs,traces and metrics. Say, users want to use `jaeger_proto` for traces, but it couldn't apply to metrics and logs.

In this conditions, users have to config as below:
```yml
exporters:
  pulsar/trace:
    encoding: jaeger_json
    topic: pulsar://public/default/otlp_spans
    #ignore other items...

  pulsar/log:
    encoding: otlp_proto
    topic: pulsar://public/default/otlp_logs
    #ignore other items...

  pulsar/metric:
    encoding: otlp_proto
    topic: pulsar://public/default/otlp_metrics
    #ignore other items...

service:
  pipeline:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [pulsar/trace]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [pulsar/log]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [pulsar/metric]

```

This is relatively complex, so I hope to make pulsar_exporter more configurable.

### Describe the solution you'd like

Provide extra configuration items:
```yaml
trace:
  topic:
  encoding:
log:
  topic:
  encoding:
metric:
  topic:
  encoding:
```
