### ISSUE TITLE
[receiver/pulsar] Make pulsar_receiver more configurable

### ISSUE THREAD

**Issue by dao-jun** [open-telemetry/opentelemetry-collector-contrib#28685]
### Component(s)

receiver/pulsar

### Is your feature request related to a problem? Please describe.

Currently, in pulsar_receiver, configuration items only supports specify a single topic name for traces/metrics/logs.

And traces/metrics/logs receiver has default topic name(otlp_spans for traces, otlp_logs for logs and otlp_metrics for metrics), say, if users specify a topic for traces, but couldn't specify topic for logs and metrics. If users want to start a metrics receiver pipeline, it will be failed, because otlp_spans otlp_logs and otlp_metrics is not pulsar topic name pattern.

A topic name pattern must comply with a certain patter(pulsar://tenant/namespace/topic_name, example: pulsar://public/default/otlp_spans).

Also, pulsar_receiver only provide a single encoding configuration for logs,traces and metrics. Say, users want to use jaeger_proto for traces, but it couldn't apply to metrics and logs.

In this conditions, users have to config as below:

```yaml
receivers:
  pulsar/trace:
    encoding: jaeger_json
    topic: pulsar://public/default/otlp_spans
    #ignore other items...

  pulsar/log:
    encoding: otlp_proto
    topic: pulsar://public/default/otlp_logs
    #ignore other items...

  pulsar/metric:
    encoding: otlp_proto
    topic: pulsar://public/default/otlp_metrics
    #ignore other items...

service:
  pipeline:
    traces:
      receivers: [pulsar/trace]
      processors: [batch]
      exporters: [zipkin]

    logs:
      receivers: [pulsar/log]
      processors: [batch]
      exporters: [file]

    metrics:
      receivers: [pulsar/metric]
      processors: [batch]
      exporters: [prometheus]
```
This is relatively complex, so I hope to make pulsar_receiver more configurable.

### Describe the solution you'd like

Provide extra configuration items:
```yaml
trace:
  topic:
  encoding:
  subscription:
  consumer_name:
log:
  topic:
  encoding:
  subscription:
  consumer_name:
metric:
  topic:
  encoding:
  subscription:
  consumer_name:
```
