### ISSUE TITLE
New component: IPFIX Lookup

### ISSUE THREAD

**Issue by fizzers123** [open-telemetry/opentelemetry-collector-contrib#28692]
### The purpose and use-cases of the new component

Allow traces to be enhanced by [IPFIX ](https://en.wikipedia.org/wiki/IP_Flow_Information_Export) information stored in an [ElasticSearch ](https://www.elastic.co/elasticsearch/) cluster. 

A very similar functionality was already suggested once in February 2023 https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18270. We would be interested in contributing our code here. 

### Example configuration for the component
![CorrelationUnitv3 drawio](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/15678530/5bb8e7de-c254-4991-871d-05c9c6d6f3f6)

```YAML
processors:
  groupbytrace:
    wait_duration: 100s
    num_traces: 1000
    num_workers: 2
  ipfix_lookup:
    elastic_search:
      connection: 
        addresses:
          - https://<elastic_ip>:30200/
        username: elastic
        password: <password_here>
        certificate_fingerprint: <cert_fingerprint_here>
    timing:
      lookup_window: 120
    # # OPTIONAL settings:
    # query_parameters:
    #   base_query:
    #     field_name: input.type
    #     field_value: netflow
    #   device_identifier: "fields.observer\\.ip.0"
    #   lookup_fields:
    #     source_ip: source.ip
    #     source_port: source.port
    #     destination_ip: destination.ip
    #     destination_port: destination.port
    # span_attribute_fields:
    #   - "@this"
    #   - "fields.event\\.duration.0"
    #   - "fields.observer\\.ip.0"
    #   - "fields.source\\.ip.0"
    #   - "fields.source\\.port.0"
    #   - "fields.destination\\.ip.0"
    #   - "fields.destination\\.port.0"
    #   - "fields.netflow\\.ip_next_hop_ipv4_address"
    # spans:
    #   span_fields:
    #     source_ips:
    #       - net.peer.ip
    #       - net.peer.name
    #       - src.ip
    #     source_ports:
    #       - net.peer.port
    #       - src.port
    #     destination_ip_and_port:
    #       - http.host
    #     destination_ips:
    #       - dst.ip
    #     destination_ports:
    #       - dst.port  
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [groupbytrace, ipfix_lookup]
      exporters: [otlp/jaeger, debug]
  telemetry:
    logs:
      level: debug
```

### Telemetry data types supported

traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Additional context

As part of our Bachelor thesis at the [Eastern Switzerland University of Applied Sciences](https://www.ost.ch/de/) we have created a basic implementation of this functionality.

![finnal-implementation](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/15678530/37036d33-07f1-4c9e-bdea-7834a5e01015)

(The network was intentionally slowed down for this screenshot)

#### ipfix_lookup processor
Inside the OptenTelemetry pipeline, a new processor called `ipfix_lookup` can be configured. Before the IPFIX lookup is performed, all the traces are grouped together, and a delay is added by the `groupbytrace` processor. The `groupbytrace` will group all the incoming spans by trace and wait for the `wait_duration` until forwarding it to the `ipfix_lookup` processor.

Inside the `ipfix_lookup` processor each trace span is then checked to see if the IP and port quartet can be extracted. When the four values (`source.ip, source.port, destination.ip, destination.port, observer.ip`) are found, the corresponding flow is searched in ElasticSearch. For the time frame of the search, two considerations must be made.

Firstly, there is an ingest delay in any large distributed search engine. Because of this, the spans need to be pre-processed by the `groupbytrace` processor. The delay can be defined in the `processors.groupbytrace.wait_duration` value. Afterwards, the search can be started. The time window that will be searched can be configured in the `processors.ipfixLookup.timing.lookupWindow`. To keep the processor simple, the `lookupWindow` is added before the start timestamp and after the end timestamp. This way, the chance that the Netflow/IPFIX records leading or being caused by this span is found is maximized. 

#### summary span
A summary span was added to simplify the display of the spans in Jaeger, under which all Netflow/IPFIX spans are placed. As depicted in the screenshot the summary span is highlighted yellow and contains the TCP IP quartet in the name. Both request and response are grouped under the same summary span. 

The summary span improves the  `ipfix_lookup` processor as it can be split into two separate actions. First, the trace will be checked for the IP/Port quartet, and summary spans will be created. In the second step, the processor iterates through.
