### ISSUE TITLE
Count Connecter should be able to count by Resource Attributes

### ISSUE THREAD

**Issue by 0x006EA1E5** [open-telemetry/opentelemetry-collector-contrib#28825]
### Component(s)

connector/count

### Is your feature request related to a problem? Please describe.

Currently, the Count Connector can specify attributes for metrics: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/countconnector#attributes

I want to be able to count spans by `service.name`. `service.name` is a natural dimension for counting  spans, and will help us attribute "cost" per service, and identify "problematic" services.

However, `service.name` is not an attribute of the span or span event, but of the parent resource, so it is not currently possible.

### Describe the solution you'd like

Be able to specify "resource attributes", as we currently can for "attributes"

### Describe alternatives you've considered

We could transform each span to add the containing Resource's `service.name` to each span.  This would inflate the data passing through the pipeline, and would need to be removed before sending to any trace backend

### Additional context

I have a POC working.  Seems like a minor change to add this to https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/countconnector/counter.go#L38

**Comment by 0x006EA1E5** [comment]
FYI, I created a PR with a POC

**Comment by djaglowski** [comment]
Thanks for opening the issue and PR @0x006EA1E5.

While I agree with the use case, I'm not convinced this is doing what you suggest.

We already count on a per-resource basis, so I don't think this changes anything specific to counting. It looks like the only change is that we're copying resource attributes to data point attributes. 

To use a specific example, say we have the following input:
```yaml
resources:
  - attributes:
      service.name: foo
    spans: [...] # assume there are 4 spans
  - attributes:
      service.name: bar
    spans: [...] # assume there are 3 spans
```

Currently, will will emit the following:
```yaml
resources:
  - attributes:
      service.name: foo
    metrics:
      span.count:
        datapoints:
          - value: 4
  - attributes:
      service.name: bar
    metrics:
      span.count:
        datapoints:
          - value: 3
```

If I understand correctly, what you're proposing would result in:
```yaml
resources:
  - attributes:
      service.name: foo
    metrics:
      span.count:
        datapoints:
          - value: 4
            attributes:
              service.name: foo # copied from resource, but the count is the same and the attribute is still available on the resource
  - attributes:
      service.name: bar
    metrics:
      span.count:
        datapoints:
          - value: 3
            attributes:
              service.name: bar # copied from resource, but the count is the same and the attribute is still available on the resource
```

Am I understanding this correctly? If so, I think the need to copy the resource attribute to each data point could be handled with existing functionality in other components.
