### ISSUE TITLE
How to solve "error": "Throttle (0s), error: HTTP 503 \"Service Unavailable\" when using SplunkHECExporter to send data into Splunk?

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector-contrib#28895]
### Component(s)

exporter/splunkhec

## Description
Currently, I am consuming data from Kafka Stream using kafkareceiver then send the data consumed into Splunk using splunkhec exporter. I am able to get the data into Splunk but there are times where error message is flagged. Please refer to the Log Output for the error log message.

May I get your assistance on the following questions, please?
1. Why does this error message flagged sometimes?
2. How can I solve this error message flagged?
3. Will this error message cause data loss?

## Steps to Reproduce
Setup a config.yaml file with needed configurations and run the otelcol-contrib-collector image in Kubernetes environment.
Please refer to the "OpenTelemetry Collector configuration" section for the configurations.

## Expected Result
I expected the data to always be pushed and will not display any error.

## Actual Result
The data is pushed but will flagged the error message as shown in the Log Output section.

### Collector version

v0.88.0

## Environment
Kubernetes container

### OpenTelemetry Collector configuration

```yaml
receivers:
  kafka:
    protocol_version: 2.0.0
    topic: <topic_name>
    brokers:
      - "<broker_link>"
    group_id: <group_id_name>
    encoding: json

processors:
  batch:
    send_batch_size: 10000
    timeout: 10s

exporters:
  splunk_hec:
    token: <HEC_Token>
    endpoint: <SPLUNK_Endpoint>
    sourcetype: <sourcetype_name>

  logging:
    verbosity: detailed

service:
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8885

  pipelines:
    logs:
      receivers: [kafka]
      processors: [batch]
      exporters: [logging, splunk_hec]
```

### Log output

```shell
2023-11-05T16:24:47.334Z	info	exporterhelper/retry_sender.go:177	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "logs", "name": "splunk_hec", "error": "Throttle (0s), error: HTTP 503 \"Service Unavailable\"", "interval": "3.965794253s"}
```

### Additional context

May I get your assistance on the following questions, please?
1. Why does this error message flagged sometimes?
2. How can I solve this error message flagged?
3. Will this error message cause data loss?
