### ISSUE TITLE
Provide the capability of orphan detection

### ISSUE THREAD

**Issue by trajano** [open-telemetry/opentelemetry-collector-contrib#28890]
### Component(s)

processor/filter

### Is your feature request related to a problem? Please describe.

I know it's already written as a warning in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#warnings but is there anyway to delete the orphans?

Or is it in the road map of this component?

### Describe the solution you'd like

```
  filter/drop_actuator:
    traces:
      span:
        - (attributes["http.route"] == "/actuator/prometheus") and (attributes["http.method"] == "GET")
        - (attributes["http.route"] == "/actuator/health") and (attributes["http.method"] == "GET")
       orphans: "drop"
```

### Describe alternatives you've considered

Dropping some of the internal traces
