### ISSUE TITLE
Performance and dropped resouces

### ISSUE THREAD

**Issue by yanamg7** [open-telemetry/opentelemetry-collector-contrib#28900]
## Description
We conducted POC for the routing methods. When we used routing connectors we saw the resources drop and increase the memory usage.
We tried sending 15K resources per second: logs and metrics, otlp, and filereceiver. We tried to run the same traffic using multiple receivers (otlp receiver using several ports, filereceiver using different file names matching) and traffic was processed without errors. I tried it without profiling but after seeing errors, I added profiling

## Steps to Reproduce
Run traffic 15K resources per sec 

## Expected Result
No dropped resources

## Actual Result
Dropped resources and error, increased memory and CPU

### Collector version

otelcol-contrib version 0.88.0

## Environment
Ubuntu 22.04.2 LTS
pod resources:
      limits:
        memory: 3Gi
      requests:
        memory: 500Mi

### OpenTelemetry Collector configuration

```yaml
---
extensions:
  zpages: null
  pprof/1:
        endpoint: ":1777"
        block_profile_fraction: 3
        mutex_profile_fraction: 5
        save_to_file: "/prof_file.ppf"
receivers:
  filelog:
    exclude: []
    include:
      - /TODA/bench_log/*.log
    include_file_name: true
    include_file_path: true
    operators:
      - field: attributes.log
        type: add
        value: unspecified
      - field: attributes.ct
        type: add
        value: unspecified
      - field: attributes.scid
        type: add
        value: unspecified
      - field: attributes.sysid
        type: add
        value: unspecified
      - field: attributes.sev
        type: add
        value: unspecified
      - field: attributes.ts
        type: add
        value: 1970-01-01 00:00:00.000000 UTC
      - field: attributes.mid
        type: add
        value: unspecified
      - type: json_parser
      - mapping:
          fatal: emergency
          info4: notice
        parse_from: attributes.sev
        type: severity_parser
      - from: attributes.log
        id: move1
        to: resource["Log Message"]
        type: move
      - from: attributes.ct
        id: move2
        to: resource["Container Name"]
        type: move
      - from: attributes.scid
        id: move3
        to: resource["Unique Container ID"]
        type: move
      - from: attributes.sysid
        id: move4
        to: resource["System ID"]
        type: move
      - from: attributes.sev
        id: move5
        to: resource["Severity"]
        type: move
      - from: attributes.ts
        id: move6
        to: resource["Timestamp"]
        type: move
      - from: attributes.mid
        id: move7
        to: resource["Message ID"]
        type: move  

    resource:
      - dataType: bigipn-pods-log
    start_at: beginning
    
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4617
        tls:
          cert_file: ${OTEL_TLS_CERT_FILE}
          client_ca_file: ${OTEL_TLS_CA_FILE}
          key_file: ${OTEL_TLS_KEY_FILE}
          min_version: "1.2"
          reload_interval: 100000
  
processors:
  batch: null

exporters:
    file:
      path: /var/log/otlp.json
    logging:
      sampling_initial: 0
      sampling_thereafter: 0
      verbosity: basic
    otlp/2c27f38b-3399-4531-b66c-f557f646ebb0:
        endpoint: 10.144.74.39:4417
        sending_queue:
            enabled: true
            queue_size: 5
        retry_on_failure:
            enabled: true
            initial_interval: 2s
            max_elapsed_time: 6s
        tls:
            insecure: true
    otlp/ccb8b939-5dab-465f-bcf4-921385d8001d:
        endpoint: 10.144.74.39:4517
        sending_queue:
            enabled: true
            queue_size: 5
        retry_on_failure:
            enabled: true
            initial_interval: 2s
            max_elapsed_time: 6s
        tls:
            insecure: true
    otlp/fd71bd0c-de38-4512-8a78-f07918f9a0ea:
        endpoint: 10.144.74.39:4317
        sending_queue:
            enabled: true
            queue_size: 5
        retry_on_failure:
            enabled: true
            initial_interval: 2s
            max_elapsed_time: 6s
        tls:
            insecure: true
connectors:
  routing/logs:
      default_pipelines: [logs/otlp-all]
      error_mode: propagate
      table:
        - statement: route() where IsMatch(attributes["FileName"], ".*access.*log")
          pipelines: [logs/access]
        - statement: route() where IsMatch(attributes["FileName"], ".*sec.*log")
          pipelines: [logs/sec]
        - statement: route() where not IsMatch(attributes["FileName"], ".*sec.*log") and not IsMatch(attributes["FileName"], ".*access.*log") 
          pipelines: [logs/container]
  routing/metrics:
      default_pipelines: [metrics/1]
      error_mode: propagate
      table:
        - statement: route() where attributes["dataType"] == "type1"
          pipelines: [metrics/1]
        - statement: route() where attributes["dataType"] == "type2"
          pipelines: [metrics/2]
        - statement: route() where attributes["dataType"] == "type3"
          pipelines: [metrics/3]
service:
  pipelines:
    logs/in:
      receivers: [filelog]
      exporters: [routing/logs]
    metrics/in:
      receivers: [otlp]
      exporters: [routing/metrics] 
    logs/otlp-all:
      exporters:
        - logging
        - otlp/fd71bd0c-de38-4512-8a78-f07918f9a0ea
      receivers:
        - routing/logs
    logs/access:
      exporters:
        - logging
        - otlp/ccb8b939-5dab-465f-bcf4-921385d8001d
      receivers:
        - routing/logs
    logs/container:
      exporters:
        - logging
        - otlp/2c27f38b-3399-4531-b66c-f557f646ebb0
      receivers:
        - routing/logs
    logs/sec:
      exporters:
        - logging
        - otlp/fd71bd0c-de38-4512-8a78-f07918f9a0ea
      receivers:
        - routing/logs
    metrics/1:
      exporters:
        - logging
        - otlp/2c27f38b-3399-4531-b66c-f557f646ebb0
      receivers:
        - routing/metrics
    metrics/2:
      exporters:
        - logging
        - otlp/ccb8b939-5dab-465f-bcf4-921385d8001d
      receivers:
        - routing/metrics
    metrics/3:
      exporters:
        - logging
        - otlp/fd71bd0c-de38-4512-8a78-f07918f9a0ea
      receivers:
        - routing/metrics 
  extensions:
    - zpages
    - pprof/1
```

### Log output

```shell
2023-11-06T11:09:53.092Z	error	exporterhelper/queue_sender.go:184	Dropping data because sending_queue is full. Try increasing queue_size.	{"kind": "exporter", "data_type": "logs", "name": "otlp/2c27f38b-3399-4531-b66c-f557f646ebb0", "dropped_items": 100}
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).send
	go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/queue_sender.go:184
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseExporter).send
	go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/common.go:196
go.opentelemetry.io/collector/exporter/exporterhelper.NewLogsExporter.func1
	go.opentelemetry.io/collector/exporter@v0.88.0/exporterhelper/logs.go:100
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs
	go.opentelemetry.io/collector/consumer@v0.88.0/logs.go:25
go.opentelemetry.io/collector/internal/fanoutconsumer.(*logsConsumer).ConsumeLogs
	go.opentelemetry.io/collector@v0.88.0/internal/fanoutconsumer/logs.go:75
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs
	go.opentelemetry.io/collector/consumer@v0.88.0/logs.go:25
github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector.(*logsConnector).ConsumeLogs
	github.com/open-telemetry/opentelemetry-collector-contrib/connector/routingconnector@v0.88.0/logs.go:97
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs
	go.opentelemetry.io/collector/consumer@v0.88.0/logs.go:25
github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/consumerretry.(*logsConsumer).ConsumeLogs
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal@v0.88.0/consumerretry/logs.go:37
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).consumerLoop
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/adapter/receiver.go:124
2023-11-06T11:09:53.719Z	error	consumerretry/logs.go:39	ConsumeLogs() failed. Enable retry_on_failure to slow down reading logs and avoid dropping.	{"kind": "receiver", "name": "filelog", "data_type": "logs", "error": "sending_queue is full"}
github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/consumerretry.(*logsConsumer).ConsumeLogs
	github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal@v0.88.0/consumerretry/logs.go:39
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).consumerLoop
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/adapter/receiver.go:124
2023-11-06T11:09:53.720Z	error	adapter/receiver.go:126	ConsumeLogs() failed	{"kind": "receiver", "name": "filelog", "data_type": "logs", "error": "sending_queue is full"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).consumerLoop
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/adapter/receiver.go:126
```
