### ISSUE TITLE
[question] how to control the "maximum number of batches stored to disk" independently of in-memory queue size while using persistent queue in "exporterhelper" (ClickHouseExporter)

### ISSUE THREAD

**Issue by ceevaaa** [open-telemetry/opentelemetry-collector-contrib#29006]
### Component(s)

exporter/clickhouse, extension/storage, extension/storage/filestorage

## Design
At a macro level I am sending the telemetry data like this.
local Otel collector (otlp exporter) -> central Otel collector (clickhouse exporter) -> ClickHouse DB

## Description
AIM - To control the number of batches of telemetry data that can be stored in 
1. in-memory
2. persistent storage

"independently" as and when there is an error in exportation due to various reasons.

Eg- I would want to have very less amount of data in-memory (say 1_000 batches) but I am okay with having 100_000 batches written to my persistent storage.

I am confused which exact parameter does that, as in the [docs](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/exporterhelper/README.md#persistent-queue) it says,
`The maximum number of batches stored to disk can be controlled using sending_queue.queue_size parameter (which, similarly as for in-memory buffering, defaults to 1000 batches).`
But I can only see one param in exporter helper that can change this (which I think will only change the in-memory queue size)

So my two questions are -
1. Can I control these two parameters independently ? Say, increase storage and decrease in-memory ?
2. How can I use the same in the ClickHouse exporter ?

Regards,
Shiva Pundir

### Collector version

v0.88.0

### OpenTelemetry Collector configuration

```yaml
# Local Otel Collector

extensions:
  file_storage/otlp:
    directory: /var/lib/otelcol/file_storage
    timeout: 1s

exporters:
  otlp:
    endpoint: ${env:CENTRAL_OTEL_COLLECTOR_ENDPOINT}
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 3600s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 10000
      storage: file_storage/otlp
    timeout: 5s


# Central Otel Collector

exporters:
  clickhouse/realtime:
    endpoint: ${env:CLICKHOUSE_REALTIME_ENDPOINT}
    username: ${env:CLICKHOUSE_REALTIME_USERNAME}
    database: otel
    ttl_days: 90
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    sending_queue: 
      queue_size: 10000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
```
