### ISSUE TITLE
noisy debug logs with compare string to non-string

### ISSUE THREAD

**Issue by trajano** [open-telemetry/opentelemetry-collector-contrib#29015]
### Component(s)

processor/filter

## Description

Seeing a lot of debug noise, but does not show any reason how to fix it (note this may be due to `compare.go` not providing a facility to mute invalid comparisons.

## Steps to Reproduce

Define the filter

## Expected Result

Quiet

## Actual Result

Lots of debug statements 

### Collector version

0.88.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
processors:
  filter/drop_actuator:
    traces:
      span:
        - (attributes["http.method"] != nil) and (attributes["http.method"] == "GET") and (attributes["http.route"] == "/actuator/prometheus")
service:
  telemetry:
    logs:
      level: debug
      encoding: json
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/drop_actuator,batch]
```

### Log output

```shell
{"level":"debug","ts":1699397830.919674,"caller":"ottl@v0.88.0/compare.go:22","msg":"string to non-string","kind":"processor","name":"filter/drop_actuator","pipeline":"traces","op":0}
{"level":"debug","ts":1699397832.4553528,"caller":"ottl@v0.88.0/compare.go:22","msg":"string to non-string","kind":"processor","name":"filter/drop_actuator","pipeline":"traces","op":1}
{"level":"debug","ts":1699397832.4554641,"caller":"ottl@v0.88.0/compare.go:22","msg":"string to non-string","kind":"processor","name":"filter/drop_actuator","pipeline":"traces","op":0}
{"level":"debug","ts":1699397832.4554925,"caller":"ottl@v0.88.0/compare.go:22","msg":"string to non-string","kind":"processor","name":"filter/drop_actuator","pipeline":"traces","op":1}
```

### Additional context

I also tried
```
    error_mode: ignore
```
still noisy.

**Comment by crobert-1** [comment]
Hello @trajano, just to clarify, did you file this issue because you don't want so many logs in your collector's output, or because you want the specific message you're seeing to provide some kind of guidance to resolve the issue?

**Comment by trajano** [comment]
> Too many logs in the collectors output

There's also two problems with the messaging
1. it does not provide a way of fixing the problem if there is one.
2. it does not tell me what specific data and ideally what line as well caused the problem (that could likely be done on `compare.go` 

But I think the fix would be `filter` should do a cursory check or maybe compare can provide a validator before sending it to compare for processing.

**Comment by crobert-1** [comment]
I think the best option is probably to add more information to the log output, specifically which string and non-string values are being compared.

I don't think anything should be done with the filter processor here, or other logic changes. The check will fail either way and this log message is really showing that we're properly validating data in our checks, and that everything is working as intended. The logic that's being used to compare values is in the `ottl` package which is widely used across different collector components. Because of this, I don't think it's a good idea to start adding logic around it in different components.

The log message is also showing where the check is coming from (`filter/drop_actuator`). From this, we know the comparisons defined here in your processor are what's logging errors:
```
        - (attributes["http.method"] != nil) and (attributes["http.method"] == "GET") and (attributes["http.route"] == "/actuator/prometheus")
```
So we know it's one of those conditions that's comparing a string to a non-string. Also, we know from the `op` value in the log that both equalities (`0`) and inequalities (`1`) are failing with this error.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/22d86de838858c25d1d644b84221eb37198d2c86/pkg/ottl/grammar.go#L121-L132

**Comment by crobert-1** [comment]
(This is also relevant for all of the other comparisons as well, not just strings.)

**Comment by trajano** [comment]
I am thinking maybe it's the `nil` perhaps we it should log differently or ignore if `nil == "string"`

**Comment by TylerHelmuth** [comment]
This is happening because you've enabled

```yaml
service:
  telemetry:
    logs:
      level: debug
```

At the moment it is working as intended. The log could be improved.  If you want to stop the influx of logs in the meantime you should switch to 

```yaml
service:
  telemetry:
    logs:
      level: info
```
