### ISSUE TITLE
Loki to Loki exporter not working

### ISSUE THREAD

**Issue by trajano** [open-telemetry/opentelemetry-collector-contrib#29013]
### Component(s)

exporter/loki

## Description

I am trying to send data from promtail to loki via the OTEL collector.  It's does not appear to be sending to LOKI

## Steps to Reproduce

Configure a loki receiver and loki exporter
Send a message based on the example

```
curl -v -H "Content-Type: application/json" -XPOST -s "http://otelcol:3500/loki/api/v1/push" --data-raw   '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "'$(date +'%s')'000000000", "fizzbuzz3" ] ] }]}'
```

## Expected Result

Debug message appears AND data appears in loki

## Actual Result

Debug message appears but no data appears in loki.

Sending via 
```
curl -v -H "Content-Type: application/json" -XPOST -s "http://loki:3100/loki/api/v1/push" --data-raw   '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "'$(date +'%s')'000000000", "fizzbuzz2" ] ] }]}'
```

Works and I receive the entry.
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/110627/d192c3c7-ad2b-4ae2-ae17-c4e4b8cbcba0)

### Collector version

v0.88.0

## Environment
OS: DietPi
Docker Swarm

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug:
    verbosity: detailed
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: true
      job: true
receivers:
  loki:
    protocols:
      http:
    use_incoming_timestamp: true
processors:
  batch:
  attributes/loki:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: container
      - action: insert
        key: loki.format
        value: raw
service:
  pipelines:
    logs:
      receivers: [loki]
       # I tried without batch even attributes
      processors: [attributes/loki,batch]
      # I also tried without debug
      exporters: [debug,loki]
```

### Log output

```shell
{"level":"info","ts":1699392758.861195,"msg":"LogsExporter","kind":"exporter","data_type":"logs","name":"debug","resource logs":1,"log records":1}
{"level":"info","ts":1699392758.8614204,"msg":"ResourceLog #0\nResource SchemaURL: \nScopeLogs #0\nScopeLogs SchemaURL: \nInstrumentationScope  \nLogRecord #0\nObservedTimestamp: 2023-11-07 21:32:38.731536162 +0000 UTC\nTimestamp: 2023-11-07 21:32:38 +0000 UTC\nSeverityText: \nSeverityNumber: Unspecified(0)\nBody: Str(fizzbuzz3)\nAttributes:\n     -> foo: Str(bar2)\n     -> loki.attribute.labels: Str(container)\nTrace ID: \nSpan ID: \nFlags: 0\n","kind":"exporter","data_type":"logs","name":"debug"}
```

**Comment by crobert-1** [comment]
Hello @trajano, are you seeing any errors in your loki backend that could explain the failure here?

Also, I noticed this in your config:
```
processors:
  batch:
  attributes/loki:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: container
      - action: insert
        key: loki.format
        value: raw
```
From the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter#format), the `loki.format` variable is actually supposed to be a resource attribute, so it would be defined in a resource processor instead, and added to the pipeline there.

**Comment by trajano** [comment]
Checking, but I did copy that block from 
https://grafana.com/docs/opentelemetry/collector/send-logs-to-loki/loki-receiver/#use-opentelemetry-collector-to-send-logs-to-loki

**Comment by crobert-1** [comment]
> Checking, but I did copy that block from https://grafana.com/docs/opentelemetry/collector/send-logs-to-loki/loki-receiver/#use-opentelemetry-collector-to-send-logs-to-loki

Oh, thanks for linking, you're right. We'll have to check with the loki code owners to see if one wrong (maybe they both work?), and update documentation if necessary 👍

**Comment by crobert-1** [comment]
I'll have to defer to the Loki exporter code owners for now, I'm not very experienced here.

**Comment by trajano** [comment]
NP I did try 
```
  resource/loki:
    attributes:
      - action: insert
        key: loki.format
        value: raw
```

And 

```
    logs:
      receivers: [loki]
      processors: [resource/loki]
      exporters: [loki]
```

No luck.  I wonder if there's a way to debug the exporter itself so I can tell whether it is trying to send something

**Comment by crobert-1** [comment]
One more thing: Could you try to run with [the log level to debug](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#logs)? Maybe there are some logs that will show.

**Comment by trajano** [comment]
Nope all it showed was this which was part of the tracing
```
{
  "level": "debug",
  "ts": 1699396862.3295133,
  "caller": "ottl@v0.88.0/compare.go:22",
  "msg": "string to non-string",
  "kind": "processor",
  "name": "filter/drop_actuator",
  "pipeline": "traces",
  "op": 0
}
```
I turned off the trace processors to silence that log but all I see is the `info` log for the message I send

**Comment by jangaraj** [comment]
IMHO it's config issue. Log MUST have some label(s) otherwise Loki can't index it.
Log example has only foo: bar attribute, but config is saying that container will be label used by Loki. But that attribute is missing, so there is no label which can be used by Loki.

**Comment by trajano** [comment]
I had this originally

```
  attributes/loki:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: container
```
Shouldn't that add a label?

**Comment by jangaraj** [comment]
Use foo attribute attribute as label because you don't have container attribute, pls
 attributes/loki:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: container

**Comment by trajano** [comment]
```
  attributes/loki:
    actions:
    - action: insert
      key: loki.attribute.labels
      value: foo
...
  pipelines:
    logs:
      receivers: [loki]
      processors: [attributes/loki]
      exporters: [debug,loki]
```

Still not showing anything on Grafana loki when I send 
```
> curl -v -H "Content-Type: application/json" -XPOST -s "http://otelcol:3500/loki/api/v1/push" --data-raw   '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "'$(date +'%s')'000000000", "fizzbuzz3" ] ] }]}'

*   Trying 10.0.14.51:3500...
* Connected to otelcol (10.0.14.51) port 3500
> POST /loki/api/v1/push HTTP/1.1
> Host: otelcol:3500
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 100
>
} [100 bytes data]
< HTTP/1.1 204 No Content
< Date: Tue, 07 Nov 2023 23:26:07 GMT
<
* Connection #0 to host otelcol left intact
```

**Comment by jangaraj** [comment]
Debug output always, pls. And format them for humans, pls e.g.:
```
ResourceLog #0
Resource SchemaURL: 
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope  
LogRecord #0
ObservedTimestamp: 2023-11-07 21:32:38.731536162 +0000 UTC
Timestamp: 2023-11-07 21:32:38 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Str(fizzbuzz3)
Attributes:
     -> foo: Str(bar2)
     -> loki.attribute.labels: Str(container)
Trace ID: 
Span ID: 
Flags: 0
```
This doesn't make sense:
```
Attributes:
     -> foo: Str(bar2)
     -> loki.attribute.labels: Str(container)
```
It should be:
```
Attributes:
     -> foo: Str(bar2)
     -> loki.attribute.labels: Str(foo)
 ```

**Comment by trajano** [comment]
I sent the message based on the example

https://grafana.com/docs/loki/latest/reference/api/#examples-4

I just swapped a couple of values

**Comment by jangaraj** [comment]
Pls provide debug output. And format them for humans.

**Comment by trajano** [comment]
I got it working with the following:
```
  attributes/loki:
    actions:
    - action: insert
      key: loki.format
      value: raw
    - action: insert
      key: loki.attribute.labels
      value: exporter
```
Seems `exporter` is sent implicitly so I don't have to list it.  However, all the mappings I did on promtail are lost.  I am going to see if that loki.format would resolve it.
