### ISSUE TITLE
[metricstransformprocessor] Configuration driven simple arithmetic to manipulate values of metric data points

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector-contrib#2901]
**Is your feature request related to a problem? Please describe.**
Data point values in metrics from collector sometimes require a bit of (basic) simple arithmetic manipulation to produce a new series.  

**Describe the solution you'd like**
A feature in metricstransform processor that can provide configuration driven basic arithmetic operation on data point values. 

```yaml
  metricstransform:
    transforms:
      - include: node_cpu_seconds_idle
        action: insert
        new_name: node_cpu_seconds_used
        operations:
          - action: eval
            eval_expression: 100-value
```

**Additional context**
[GoEval](https://github.com/PaesslerAG/gval) library  can do such evaluations. It can do a lot more than simple arithmetic but feature is to limit to simple arithmetic 

Sample code 

```Go
	eval, err := gval.Arithmetic().NewEvaluable(mtpOp.configOperation.EvalExpression)
	if err != nil {
		mtp.logger.Debug(err.Error())
		return
	}

....

        value, err := eval.EvalFloat64(context.Background(), map[string]interface{}{"value": dp.GetDoubleValue()})
        if err != nil {
	        mtp.logger.Debug(err.Error())
	        continue
        }
        dp.Value = &metricspb.Point_DoubleValue{DoubleValue: value}

```
