### ISSUE TITLE
[receiver/receivercreator]  Support for probing K8s services

### ISSUE THREAD

**Issue by a-thaler** [open-telemetry/opentelemetry-collector-contrib#29021]
### Component(s)

receiver/receivercreator
extension/observer

### Is your feature request related to a problem? Please describe.

I used the typical setup of blackbox-exporter and prometheus to probe the availability of k8s services and make the results available as metrics. Hereby, the discovery of services by [prometheus annotations](https://github.com/prometheus-community/helm-charts/blob/d3b3006ada0e00ba8b57f8010717c6207f2d35a7/charts/prometheus/values.yaml#L989) is an elegant approach.

With the availability of the [httpcheck receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/httpcheckreceiver) the setup can be turned into an otel-collector based setup. However, the configuration is static and does not support any discovery capabilities.

The [receivercreator reciever](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/receivercreator/README.md) seems the perfect match for that scenario by configuring the httpcheck dynamically dependent on the discovered service endpoints.

### Describe the solution you'd like

Add support to the [k8s_observer](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/observer/k8sobserver) to watch k8s services, so that a new rule type `k8s.service` is available in the [receivercreator reciever](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/receivercreator/README.md) which allows the dynamic configuration of the [httpcheck receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/httpcheckreceiver).

An example configuration might look like this:
```yaml
  extensions:
    k8s_observer:
      observe_nodes: false
      observe_pods: false
      observe_services: true

  receivers:
    receiver_creator:
      watch_observers: [k8s_observer]
      receivers:
        httpcheck:
          rule: type == "k8s.service" && annotations["prometheus.io/probe"] == "true"
          config:
            targets:
              - endpoint: 'http://`endpoint`:9090/health'
                method: 'GET'
            collection_interval: 10s

  exporters:
    debug:
      verbosity: detailed

  service:
    extensions:
      - k8s_observer
    pipelines:
      metrics:
        receivers:
        - receiver_creator
        exporters:
        - debug
```

A more advanced config could look like this:
```yaml
  receivers:
    receiver_creator:
      watch_observers: [k8s_observer]
      receivers:
        httpcheck:
          rule: type == "k8s.service" && annotations["prometheus.io/probe"] == "true"
          config:
            targets:
              - endpoint: '`"prometheus.io/scheme" in annotations ? annotations["prometheus.io/scheme"] : http`://`endpoint`:`"prometheus.io/port" in annotations ? annotations["prometheus.io/port"] : 9090``"prometheus.io/path" in annotations ? annotations["prometheus.io/path"] : "/health"`'
                method: '`"prometheus.io/method" in annotations ? annotations["prometheus.io/method"] : GET`'
            collection_interval: '`pod.annotations["collection_interval"]`'
```

### Describe alternatives you've considered

As the httpcheck receiver does not support any discovery, the only alternative is to stick to the blackbox-exporter and use the prometheusreceiver with a target_allocator instead which is way more complex and requires the blackbox-exporter.
