### ISSUE TITLE
[receiver/windowsperfcounters] Instance wildcard doesn't capture _Total instance

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector-contrib#29054]
### Component(s)

receiver/windowsperfcounters

## Description

When the instance is set to "*" the user wants to capture all instances of a counter like `\Processor(*)\%Process Time`. However, the wildcard doesn't capture the `_Total` instance.

## Steps to Reproduce

Run the collector using a config like this one:
```yaml
receivers:
  windowsperfcounters:
    metrics:
      processor.time:
        description: CPU active and idle time
        unit: "%"
        gauge:
    collection_interval: 30s
    perfcounters:
      - object: "Processor"
        instances:
           - "*"
        counters:
          - name: "% Processor Time"
            metric: processor.time
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    metrics:
      receivers: [windowsperfcounters]
      exporters: [debug]
```

## Expected Result

That the `_Total` instance is also captured when the wildcard is used.

## Actual Result

The `_Total` instance is not captured.

If the user tries to workaround by forcing the capture by explicitly adding `_Total` to the instances, i.e.:
```yaml
    perfcounters:
      - object: "Processor"
        instances: ["_Total", "*"]
        counters:
          - name: "% Processor Time"
            metric: processor.time
```
It still doesn't work because internally if the instances contain "*" they are treated as if only "*" was specified.

The way to workaround the issue is to create two receivers: one to capture `_Total` and one to capture the other instances, the later one using the wildcard.

### Collector version

22d86de838

## Environment
OS: Windows 10, Windows Server 2022
Compiler(if manually compiled): go1.21.1 windows/amd64

### OpenTelemetry Collector configuration

```yaml
receivers:
  windowsperfcounters:
    metrics:
      processor.time:
        description: CPU active and idle time
        unit: "%"
        gauge:
    collection_interval: 30s
    perfcounters:
      - object: "Processor"
        instances:
           - "*"
        counters:
          - name: "% Processor Time"
            metric: processor.time
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    metrics:
      receivers: [windowsperfcounters]
      exporters: [debug]
```
