### ISSUE TITLE
[pkg/ottl] Add OTTL String Conversion Function

### ISSUE THREAD

**Issue by Mrod1598** [open-telemetry/opentelemetry-collector-contrib#29087]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

Currently, when trying to convert a value from a `float` to `string` the only way I've seen to convert a number value to a string is to use the `Concat` function. 

example parser using OTTL to convert a float into epoch time:
```
    transform/logging-0__processor1__logs:
        error_mode: ignore
        log_statements:
            - context: log
              statements:
                - set(cache["split"], Split(Concat([attributes["test"]],""), "."))
                - set(cache["seconds"], Concat([cache["split"][0], "s"], ""))
                - set(cache["fractional"], Concat([cache["split"][1], "ms"], ""))
                - set(time, Time("1970-01-01T00:00:00.000000+0000", "%Y-%m-%dT%H:%M:%S.%f%z") + Duration(Concat([cache["seconds"], cache["fractional"]], ""))) 
```
In the first set function, To ensure we can split on `attributes["test"]`, with the value of `1234456.1234546`, representing `s.ms`, we have to Call `Concat` to change it from a `float` to a `string`.

### Describe the solution you'd like

A new function called `String` takes in a value and converts it into a string if possible.
