### ISSUE TITLE
Any end-to-end tutorial for OpAMP in OTel Collector?

### ISSUE THREAD

**Issue by brightzheng100** [open-telemetry/opentelemetry-collector-contrib#29098]
### Component(s)

extension/opamp

### Is your feature request related to a problem? Please describe.

Even OpAMP in Otel is still in early days but it is really cool so I wanted to have a try by picking up some pieces of the info scattered into the Otel projects.

What I've tried is something like this:

1. Spin up the OpAMP server:

```sh
git clone https://github.com/open-telemetry/opamp-go.git
make build-example-server
cd internal/examples/server
./bin/server
```

Then I can access the UI at: http://127.0.0.1:4321/

2. Customize the Otel Collector:

Open another console.

```sh
cat <<EOF > builder-config.yaml
dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.88.0

exporters:
  - gomod:
      # debug
      go.opentelemetry.io/collector/exporter/debugexporter v0.88.0
  - gomod:
      # otlp
      go.opentelemetry.io/collector/exporter/otlpexporter v0.88.0

receivers:
  - gomod:
      # otlp
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.88.0

processors:
  - gomod:
      # batch
      go.opentelemetry.io/collector/processor/batchprocessor v0.88.0

extensions:
  - gomod:
      # opamp
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/opampextension 22d86de838858c25d1d644b84221eb37198d2c86
EOF

./ocb --config builder-config.yaml
```

3. Configure the Collector and start it up:

```sh
cat <<EOF > config.yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed

extensions:
  opamp:
    server:
      ws:
        endpoint: wss://127.0.0.1:4320/v1/opamp

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
EOF

./otelcol-dev/otelcol-dev --config config.yaml
```

But there sounds no effect: everything looks okay but nothing happens, in both UI and Collector.

So, is there an end-to-end tutorial that I can read and follow through?

### Describe the solution you'd like

An end-to-end tutorial about how OpAMP in Otel.

**Comment by brightzheng100** [comment]
The `opamp-supervisor` is slightly more interesting at this moment.

1. Build `opamp-supervisor`

```sh
git clone https://github.com/open-telemetry/opentelemetry-collector-contrib.git
cd opentelemetry-collector-contrib/cmd/opampsupervisor
go build -o ~/workspaces/OSS/OpenTelemetry/playground/opamp-supervisor
```

2. Configure `supervisor-config.yaml`

```sh
cd ~/workspaces/OSS/OpenTelemetry/playground

cat <<EOF > supervisor-config.yaml
server:
  endpoint: wss://127.0.0.1:4320/v1/opamp
  tls:
    insecure_skip_verify: true 

capabilities:
  reports_effective_config: true
  reports_own_metrics: true
  reports_health: true
  accepts_remote_config: true
  reports_remote_config: true

agent:
  executable: ./otelcol-contrib
  config_file: ./config.yaml
EOF
```

3. Start up `opamp-supervisor`

```sh
./opamp-supervisor --config supervisor-config.yaml
```

4. Check out the UI

<img width="1320" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/1422425/a54f62ad-9c47-40d0-978d-f93940096a2a">

I found that the effective configuration is not what I injected so I roughly checked out the code and found that the feature of accepting OTel Collector config file might not be ready yet.

**Comment by tigrannajaryan** [comment]
There is no tutorial that I am aware of. You are doing the right things, the Collector is just not yet ready :-)
Both opampextension and Supervisor are work-in-progress. 

>But there sounds no effect: everything looks okay but nothing happens, in both UI and Collector. 

You should also see the connected Agent in the Server's UI when using just the opamp extension without the Supervisor. If you don't then this is a bug, please file it as a separate issue. Note that you should expect anything to happen in the Collector. The opamp extension is purely readonly at the moment.

>I found that the effective configuration is not what I injected so I roughly checked out the code and found that the feature of accepting OTel Collector config file might not be ready yet.

This should work as far as I know. You may want to open a separate issue and describe what exactly is wrong.

**Comment by crobert-1** [comment]
_It looks like there are a few different things going on here, but we'll keep this issue open as a request for an end-to-end example of how to use the opamp extension._

**Comment by brightzheng100** [comment]
> You should also see the connected Agent in the Server's UI when using just the opamp extension without the Supervisor.

You're right. I should activate such an extension by adding it as part of the `service` section, like this:

```yaml
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
  extensions: [opamp]   # <-- I missed this part
```

But the effective configuration isn't what I configured in the Collector, so I will raise it in another issue as a bug.

What I configured now is:

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed

extensions:
  opamp:
    server:
      ws:
        endpoint: wss://127.0.0.1:4320/v1/opamp
        tls:
          insecure_skip_verify: true
    instance_uid: 01ARZ3NDEKTSV4RRFFQ69G5FAV

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
  extensions: [opamp]
```

And what I saw in the Effective Configuration in <http://127.0.0.1:4321/agent?instanceid=01ARZ3NDEKTSV4RRFFQ69G5FAV> is:

```yaml
exporters:
  otlp:
    endpoint: localhost:1111
receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
```
<img width="1040" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/1422425/409eec81-87a0-413a-a09a-aa6acaf45e7c">
