### ISSUE TITLE
[extension/opamp] The effective configuration is not what is expected

### ISSUE THREAD

**Issue by brightzheng100** [open-telemetry/opentelemetry-collector-contrib#29117]
### Component(s)

extension/opamp

## Description

When `extension/opamp` is enabled, the effective configuration viewed in the UI, should be exactly the actual configuration plus merged extra configuration by the extension itself.

But as of now, it's not the case.

## Steps to Reproduce

1. Spin up the OpAMP server:

```sh
git clone https://github.com/open-telemetry/opamp-go.git
make build-example-server
cd internal/examples/server
./bin/server
```

Then I can access the UI at: http://127.0.0.1:4321/

2. Customize the Otel Collector:

Open another console.

```sh
cat <<EOF > builder-config.yaml
dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.88.0

exporters:
  - gomod:
      # debug
      go.opentelemetry.io/collector/exporter/debugexporter v0.88.0
  - gomod:
      # otlp
      go.opentelemetry.io/collector/exporter/otlpexporter v0.88.0

receivers:
  - gomod:
      # otlp
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.88.0

processors:
  - gomod:
      # batch
      go.opentelemetry.io/collector/processor/batchprocessor v0.88.0

extensions:
  - gomod:
      # opamp
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/opampextension 22d86de838858c25d1d644b84221eb37198d2c86
EOF

./ocb --config builder-config.yaml
```

3. Configure the Collector and start it up:

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed

extensions:
  opamp:
    server:
      ws:
        endpoint: wss://127.0.0.1:4320/v1/opamp
        tls:
          insecure_skip_verify: true
    #instance_uid: 01ARZ3NDEKTSV4RRFFQ69G5FAV

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
  extensions: [opamp]
```

4. Check out the UI:

What I saw in the Effective Configuration is as below, which is NOT the right effective configuration:

```yaml
exporters:
  otlp:
    endpoint: localhost:1111
receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
```

<img width="1043" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/1422425/32ad1895-4769-4a52-b3c0-c7a3fc5c1237">

## Expected Result

The effective configuration should be the actual configuration plus potentially merged extra configuration by the extension itself.

## Actual Result

Some components, say `debug` exporters, `telemetry` service are missing.

### Collector version

22d86de838858c25d1d644b84221eb37198d2c86

## Environment
OS:  MBP with M1 chip
Compiler(if manually compiled): go version go1.21.3 darwin/arm64
