### ISSUE TITLE
[cmd/opampsuervisor] Some suggestions about the cmd/opampsuervisor in configuration experience

### ISSUE THREAD

**Issue by brightzheng100** [open-telemetry/opentelemetry-collector-contrib#29119]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

The OpAMP spec is interesting and very compelling in terms of massive agent management in OTel, and maybe other domans.

After a quick try of both OpAMP extension and OpAMP Supervisor in OTel Collector, I'd like to suggest some small changes.

**1. The alignment of config experience.**

In Collector extension, the config is like this:

```yaml
extensions:
  opamp:
    server:
      ws:
        endpoint: wss://127.0.0.1:4320/v1/opamp
        tls:
          insecure_skip_verify: true
```

While in OpAMP Supervisor, it's like this:

```yaml
server:
  endpoint: wss://127.0.0.1:4320/v1/opamp
  tls:
    insecure_skip_verify: true 
```

So it's not fully aligned, and I'd suggest to use the same pattern in OpAMP Supervisor:

```yaml
server:
  ws:
    endpoint: wss://127.0.0.1:4320/v1/opamp
    tls:
      insecure_skip_verify: true 
```

Note: using the `ws` is a good idea as there might be other transport implementations in the future. Who knows.

**2. The OTel Collector is just a "normal agent".**

The current spec has a dedicated `collector` top element to configure the collector itself:

```yaml
collector:
  # Path to Collector executable. Required.
  executable: /opt/otelcol/bin/otelcol

  # Extra command line flags to pass to the Collector executable.
  args:
  ...
```

However, the Collector is just a "normal agent" from the Supervisor perspective and this Supervisor might become a reference implementation for future reference.

So I'd suggest replacing `collector` with a generic `agent`, thus:

```yaml
agent:
  # Path to Collector executable. Required.
  executable: /opt/otelcol/bin/otelcol

  # Extra command line flags to pass to the Collector executable.
  args:
  ...
```

For your consideration only.

### Describe the solution you'd like

As described in the above section to improve the configuration experience.

**Comment by brightzheng100** [comment]
Meanwhile, we may be able to further tune the agent's config with generic items.
For example, the `config_file` can be removed as it can be injected by `args`, especially when we have only one optional `--config` arg as of now for the Collector.

So this:

```yaml
collector:
  executable: /opt/otelcol/bin/otelcol
  args:
  env:
  run_as: myuser
  config_file: /etc/otelcol/config.yaml
```

may become:

```yaml
collector:
  executable: /opt/otelcol/bin/otelcol
  args:
    - --config
    - config.yaml
  env:
  run_as: myuser
```

**Comment by brightzheng100** [comment]
Another point is that, we now have `server`, `capabilities`, `storage`, and `agent` (to replace `collector`), but actually we don't have Supervisor's self-configuration.

For example, in the near future, we may extend the Supervisor:Agent from 1:1 to 1:N relationship, which means that we may consider to have 1 Supervisor manage multiple agents, we need at least `supervisor.instance_uid` to identify itself among other Supervisor instances from the OpAMP Server perspective.

So how to handle that?

**Comment by tigrannajaryan** [comment]
>we need at least supervisor.instance_uid to identify itself among other Supervisor instances from the OpAMP Server perspective.

This contradicts [opamp spec's](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md) concept of Supervisor. The Supervisor has no separate identity itself.

**Comment by brightzheng100** [comment]
Thanks for the detailed explanation. Appreciate that!

I personally think that the relationship between Supervisor and supervised Agent being 1:N may makes more sense as 1:1 is just one of the 1:N options. Even the Supervisor might not be a huge overhead but once OpAMP becomes popular, there might be more and more agents to be supervised. I like your proposed design:
```
agents:
  collector/1: ...
  collector/2: ...
  otheragent: ...
```

> Regarding the config_file option

After digging into the Collector I found that Collector itself supports multiple `--config` files with its built-in merge logic, so having a `config_file` configuration option might not be a good idea.
I feel that even having a generic config format for Collector still makes sense, without sacrificing the UX at all.
For example:
```yaml
agent:
  executable: ./otelcol-contrib
  args:
    - --config=./config1.yaml
    - --config=./config2.yaml
    - --config=./config3.yaml
 ```

Meanwhile, I'd suggest to change the `env` to be `envs` to align with the `args`, so the section looks like:
```yaml
agent:
  executable: ./otelcol-contrib
  args:
    - --config=./config1.yaml
    - --config=./config2.yaml
    - --config=./config3.yaml
  envs:
    - OTEL_SERVICE_NAME=my_collector
  ...
 ```

**Comment by cforce** [comment]
> Meanwhile, we may be able to further tune the agent's config with generic items. For example, the `config_file` can be removed as it can be injected by `args`, especially when we have only one optional `--config` arg as of now for the Collector.
> 
> So this:
> 
> ```yaml
> collector:
>   executable: /opt/otelcol/bin/otelcol
>   args:
>   env:
>   run_as: myuser
>   config_file: /etc/otelcol/config.yaml
> ```
> 
> may become:
> 
> ```yaml
> collector:
>   executable: /opt/otelcol/bin/otelcol
>   args:
>     - --config
>     - config.yaml
>   env:
>   run_as: myuser
> ```

None of this are currently supported un supervisor, are they? Other features with work on collector don't on supervisor as well.
I' am mostly missing auth (config) features which already are supported in opamp extension, like
* instance_uid:XXXx   (not sure why this is needed in collector standalone and if this might be passed through supervsior from collector using opamp extension cfg in collector. Generating a UUID on the fly and persisting would be also more convenient)
* headers like "header.authorization" to auth http based 
* advanced auth being used to from extension 
```
oauth2client:
    client_id: ${env:CLIENT}
    client_secret: ${env:SECRET}
    token_url: https://tokenidp.net/v1/token
    scopes: ["openid", "audience:server:client_id:${env:AUDIENCE}"]
    timeout: 2s
```
* supporting ${env:XXX} un supervisor.yaml
* allowing to start supervisor without -- config xxx .yaml by defining an looking for a default  filename.yaml in same folder, eg. supervisor.yaml
