### ISSUE TITLE
Allow jaeger supported connections to service graph

### ISSUE THREAD

**Issue by trajano** [open-telemetry/opentelemetry-collector-contrib#29148]
### Component(s)

connector/servicegraph

### Is your feature request related to a problem? Please describe.

I used to use [Jaeger to generate a service graph](https://github.com/jaegertracing/jaeger/issues/4931#issuecomment-1804077892) for the most part I didn't have to do anything special, but when I am using the servicegraph component it appears to be restricted as denoted here

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/1d4cf910e1a87f19b1ae6cbf614e0f52b67b58fb/connector/servicegraphconnector/README.md?plain=1#L47-L51

### Describe the solution you'd like

Just make it generate similar graphs to Jaeger.

I think a good one would be to simply check whether a trace contains a span that goes from one service.name to another.  This is one that Jaeger would support
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/110627/3c3fc5f6-9894-4421-8c8a-069cb81c8157)

Here's another one with Spring Boot connecting to Redis where `net.sock.peer.name` can be used as a fallback to `db.name` to specify a remote non-tracked service (note Jaeger doesn't support this one either)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/110627/8194f025-797f-4681-80b6-2aa6761cc874)

### Describe alternatives you've considered

Go back to Jaeger

Using something like this (but that didn't work)
```
  transform/set_span_kind_client:
    trace_statements:
      - context: span
        statements:
          - set(attributes["kind"], "client") where attributes["kind"] == nil
```

### Additional context

I do get data specifically from Grafana services

```
# HELP traces_service_graph_request_total 
# TYPE traces_service_graph_request_total counter
traces_service_graph_request_total{client="grafana",connection_type="",failed="false",server="prometheus"} 540
```

So I know it's working.

**Comment by trajano** [comment]
I think an easy way is to remove the requirement that the source is a `client` so you'd allow a connection when it is `server` to `server`

**Comment by trajano** [comment]
For the connection using `net.sock.peer.name` it can be done using
```
  transform/set_db_name
    trace_statements:
      - context: span
        statements:
          - set(attributes["db.name"], attributes["net.sock.peer.name"]) where attributes["db.name"] == nil and attributes["db.system"] != nil
```
