### ISSUE TITLE
Logs Transform Processor - unknown type: "logstransform"

### ISSUE THREAD

**Issue by Jessimon** [open-telemetry/opentelemetry-collector-contrib#29150]
### Component(s)

processor/logstransform

### What happened?

Hello Everyone,

I receive logs where the body of the logs are in json format.
I would like to see them as json.

I added the following in my config.
`processors:
  logstransform:
    operators:
      - type: json_parser
        parse_from: body
`

But when starting i get the following error:
otel-collector_1  | * error decoding 'processors': unknown type: "logstransform" for id: "logstransform" (valid values: [servicegraph span tail_sampling k8sattributes experimental_metricsgeneration metricstransform probabilistic_sampler transform cumulativetodelta filter remoteobserver resourcedetection resource batch memory_limiter attributes datadog routing spanmetrics deltatorate groupbyattrs groupbytrace redaction])

I used the following documentation:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/logstransformprocessor/README.md
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/README.md
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/json_parser.md

Is the config wrong?

Thanks for the help.

### Collector version

0.88

## Environment
OTLP is running in a docker on a Debian 11 server.

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4319

  awscloudwatch:
    region: *************
    logs:
      poll_interval: 1m

exporters:
  loki:
    endpoint: http://loki-test:3100/loki/api/v1/push
    tls:
      insecure: true

processors:
  logstransform:
    operators:
      - type: json_parser
        parse_from: body

service:
  pipelines:
    logs:
      receivers: [awscloudwatch]
      processors: [logstransform]
      exporters: [loki]
```

### Log output

```shell
otel-collector_1  | 2023/11/13 11:18:27 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
otel-collector_1  |
otel-collector_1  | * error decoding 'processors': unknown type: "logstransform" for id: "logstransform" (valid values: [servicegraph span tail_sampling k8sattributes experimental_metricsgeneration metricstransform probabilistic_sampler transform cumulativetodelta filter remoteobserver resourcedetection resource batch memory_limiter attributes datadog routing spanmetrics deltatorate groupbyattrs groupbytrace redaction])
```
