### ISSUE TITLE
connection_string not supported in azuremonitor exporter

### ISSUE THREAD

**Issue by Toudahl** [open-telemetry/opentelemetry-collector-contrib#29151]
### Component(s)

exporter/azuremonitor

## Description
The connection_string setting does not work for azuremonitor

## Steps to Reproduce
Create docker-compose from https://opentelemetry.io/docs/collector/installation/#docker-compose

```yaml
version: "3.9"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.88.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
```

Combine information found in the readme for the azuremonitor exporter, found [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/azuremonitorexporter) with the example configuration found [here](https://opentelemetry.io/docs/collector/configuration/) to create a config file like the one see in the config section

In your terminal, write: `docker compose up`

## Expected Result
The collector starts correctly.

## Actual Result
The collector prints an error message and shuts down

### Collector version

0.88.0

## Environment
OS: Windows 11
Docker: 24.0.6, build ed223bc

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        
exporters:
  azuremonitor:
    connection_string: "InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://ingestion.azuremonitor.com/"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [azuremonitor]
    metrics:
      receivers: [otlp]
      exporters: [azuremonitor]
    logs:
      receivers: [otlp]
      exporters: [azuremonitor]
```

### Log output

```shell
infrastructure-otel-collector-1  | Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
infrastructure-otel-collector-1  |
infrastructure-otel-collector-1  | * error decoding 'exporters': error reading configuration for "azuremonitor": 1 error(s) decoding:
infrastructure-otel-collector-1  |
infrastructure-otel-collector-1  | * '' has invalid keys: connection_string
infrastructure-otel-collector-1  | 2023/11/13 12:35:54 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
infrastructure-otel-collector-1  |
infrastructure-otel-collector-1  | * error decoding 'exporters': error reading configuration for "azuremonitor": 1 error(s) decoding:
infrastructure-otel-collector-1  |
infrastructure-otel-collector-1  | * '' has invalid keys: connection_string
infrastructure-otel-collector-1 exited with code 1
```
