### ISSUE TITLE
Do I need to install prometheus in my cluster in order to scrape metrics into Otel?

### ISSUE THREAD

**Issue by mmoya91** [open-telemetry/opentelemetry-collector-contrib#29301]
Hello, I have a python service that includes a prometheus client and `/metrics` endpoint for those metrics. That said, do I need to install prometheus in my cluster in order to scrape those metrics into the otel collector? I noticed documentation around setting up a prometheus receiver but not sure if that would involve standing up prometheus

**Comment by mmoya91** [comment]
@dashpole thank you for your reply. We're ultimately looking to store metrics in datadog but some of our applications use prometheus metrics instead of fastapi metrics. For applications that use fastapi metrics, we're deploying Otel Collector as a sidecar. However, for services that use prometheus metrics, we would need to consider a `StatefulSet`?

**Comment by dashpole** [comment]
You can use the prometheus receiver in the collector as a sidecar without issues.  You will want to use `static_configs` within the prometheus receiver configuration, e.g.

```yaml
receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 5s
            static_configs:
              - targets: ['0.0.0.0:8888']
```
