### ISSUE TITLE
[exporter/honeycombmarker] Use the `service.name` resource attribute to set `dataset_slug`

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#29407]
### Is your feature request related to a problem? Please describe.

Currently the honeycombmarker exporter allows you to specify exactly 1 dataset per marker.  If you want to create a marker in different datasets based on similar conditions you have to keep recreating the marker.

### Describe the solution you'd like

Allow the exporter to use `service.name` resource attribute to determine the dataset.  With that feature in place a user could create a rule like to following:

```yaml
exporters:
  honeycombmarker:
    api_key: {{env:HONEYCOMB_API_KEY}}
    markers:
      - type: k8s-backoff-events
        useServiceName: true 
        rules:
          - log_conditions:
              - IsMap(body) and IsMap(body["object"]) and body["object"]["reason"] == "Backoff"
```

That rule could then create markers in specific datasets based on the service that produced the log. Without this feature, you'd have to do

```yaml
exporters:
  honeycombmarker:
    api_key: {{env:HONEYCOMB_API_KEY}}
    markers:
      - type: k8s-backoff-events
        dataset_slug: "foo" 
        rules:
          - log_conditions:
              - IsMap(body) and IsMap(body["object"]) and body["object"]["reason"] == "Backoff" and resource.attributes["service.name"] == "foo"
      - type: k8s-backoff-events
        dataset_slug: "bar" 
        rules:
          - log_conditions:
              - IsMap(body) and IsMap(body["object"]) and body["object"]["reason"] == "Backoff" and resource.attributes["service.name"] == "bar"
```

### Additional context

We need to think about how this config option interacts with `dataset_slug`? If both are set, which takes precedence? Should only 1 be settable at a time?
