### ISSUE TITLE
New component: Fluent Forward Exporter

### ISSUE THREAD

**Issue by r0mdau** [open-telemetry/opentelemetry-collector-contrib#29413]
### The purpose and use-cases of the new component

Forward is the protocol used by Fluentd to route message between peers.

The goal is to export logs to [Fluentd](https://docs.fluentd.org/input/forward) or [Fluentbit](https://docs.fluentbit.io/manual/pipeline/inputs/forward) process that runs with the `in_forward` input.

This protocol act on TCP (optional with TLS) using [MessagePack](https://github.com/msgpack/msgpack/blob/master/spec.md) object serialization.

- Protocol specification: [Forward protocol specification v1](https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1)
- Library used [IBM/fluent-forward-go](https://github.com/IBM/fluent-forward-go) (MIT License)

### Example configuration for the component

```yaml
fluentforward/allsettings:
  endpoint: "localhost:24224"
  connection_timeout: 30s
  tls:
    insecure: false
    insecure_skip_verify: true
    ca_file: ca.crt
    cert_file: client.crt
    key_file: client.key
  shared_key: "otelcol-dev"
  require_ack: true
  tag: nginx
  compress_gzip: true
  default_labels_enabled:
    time: true
    exporter: false
    job: false
    instance: false
  sending_queue:
    enabled: true
    num_consumers: 2
    queue_size: 10
  retry_on_failure:
    enabled: true
    initial_interval: 10s
    max_interval: 60s
    max_elapsed_time: 10m
```

Configuration example source: https://github.com/r0mdau/fluentforwardexporter/blob/main/testdata/config.yaml

### Telemetry data types supported

Logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

r0mdau

### Additional context

- The exporter code is currently available here: https://github.com/r0mdau/fluentforwardexporter
- My testing environment to build the exporter available here: https://github.com/r0mdau/otelcol-dev
