### ISSUE TITLE
signalfxexporter: Prometheus Summary Type Not Implemented

### ISSUE THREAD

**Issue by alanbrent** [open-telemetry/opentelemetry-collector-contrib#2944]
**Describe the bug**

The Prometheus Metric [Summary](https://prometheus.io/docs/concepts/metric_types/#summary) type is not implemented in the `signalfxexporter`.

See [`converter.go`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/signalfxexporter/translation/converter.go#L100-L114) for proof of the missing type.

**Steps to reproduce**

1. Setup `otelcol-contrib` to receive Prometheus metrics that you know contain summary metrics and export them to the `signalfxexporter`
2. Notice that all summary metric types are missing.

**What did you expect to see?**

I expected to see the summary metrics appear in SignalFx along with the other metrics.

**What did you see instead?**

The summary metrics did not appear. Non-summary metrics _did_ appear.

**What version did you use?**

v0.23.0

**What config did you use?**

Standard YAML config file, similar to the below (our airflow reports statsd metrics to a Prometheus `statsd-exporter` container)

```yaml
receivers:
  prometheus/airflow:
    config:
      scrape_configs:
        - job_name: "prom-airflow"
          scrape_interval: 10s
          kubernetes_sd_configs:
            - role: service
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_port_name]
              regex: prometheus-scrape-endpoint
              action: keep
            - source_labels: [__address__]
              action: replace
              target_label: instance
              regex: (.+)
              replacement: $1:9102
exporters:
  signalfx/airflow:
    access_token: ${SFX_ACCESS_TOKEN_AIRFLOW}
    realm: us0
processors:
  batch:
  memory_limiter:
    ballast_size_mib: ${OTELCOL_MEMORY_LIMITER_BALLAST_SIZE_MIB}
    limit_mib: ${OTELCOL_MEMORY_LIMITER_LIMIT_MIB}
    spike_limit_mib: ${OTELCOL_MEMORY_LIMITER_SPIKE_LIMIT_MIB}
    check_interval: ${OTELCOL_MEMORY_LIMITER_CHECK_INTERVAL_SECONDS}s
  k8s_tagger:
pipelines:
    metrics/airflow:
      receivers: [prometheus/airflow]
      processors: [memory_limiter, batch, k8s_tagger]
      exporters: [signalfx/airflow]
```

**Environment**

We use the official `otelcolcontrib` container image with some lightweight tooling added in.

**Additional context**

1. Thanks to @jrcamp for the Slack discussion [here](https://app.slack.com/client/T08PSQ7BQ/C01N6P7KR6W/thread/C01N6P7KR6W-1614118942.012500)
1. Originally I thought the issue was with the `prometheusreceiver`, but I narrowed it down to the `signalfxexporter` by using the `file` exporter and confirming that the metrics are actually picked up by the receiver.
