### ISSUE TITLE
Error while validating API key: https://api.datadoghq.eu/api/v1/validate: Not Found

### ISSUE THREAD

**Issue by AxelJoly** [open-telemetry/opentelemetry-collector-contrib#29445]
### Component(s)

exporter/datadog

## Description
I'm running the opentelemetry-collector-contrib:0.82.0 on my EKS cluster. I tried as well on previous version (0.75) and got the same result.
With the config below, I get the following log:

`2023-11-22T08:25:43.051Z    warn    clientutil/api.go:48    Error while validating API key    {"kind": "exporter", "data_type": "metrics", "name": "datadog", "error": "Get \"https://api.datadoghq.eu/api/v1/validate\": Not Found"}`

When I run the following command on my terminal, I have no issues:

`curl -X GET "https://api.datadoghq.eu/api/v1/validate" -H "Accept: application/json" -H "DD-API-KEY: myapikey"
{"valid":true}`
I tried it in a sidecar container and it's working fine as well with the curl command.

## Steps to Reproduce
Run opentelemetry-collector-contrib:0.82.0 image
add the following config with a valid key

## Expected Result
The /api/v1/validate should be validating my key
## Actual Result
The /api/v1/validate doesn't validate my key

### Collector version

0.82

## Environment
EKS 1.25, running on Amazon Linux 2 AMIs

### OpenTelemetry Collector configuration

```yaml
exporters:
  datadog:
    api:
      key: myapikey
      site: datadoghq.eu
    tls:
      insecure_skip_verify: true
```

### Log output

```shell
`2023-11-22T08:25:43.051Z    warn    clientutil/api.go:48    Error while validating API key    {"kind": "exporter", "data_type": "metrics", "name": "datadog", "error": "Get \"https://api.datadoghq.eu/api/v1/validate\": Not Found"}`
```

**Comment by mx-psi** [comment]
@AxelJoly Is it possible you are using some kind of proxy? To validate this, you can try running the Collector locally with a minimal configuration and see if the API key is correctly validated.

**Comment by AxelJoly** [comment]
Hi @mx-psi , yes we are behind a proxy, we added a bunch of proxy settings.
```
      - env:
        - name: HTTP_PROXY
          value: http://myproxy:80
        - name: HTTPS_PROXY
          value:  http://myproxy:80
        - name: NO_PROXY
          value: 127.0.0.1,localhost,datadog-agent.datadog.svc.cluster.local:8126,172.25.0.0/16,169.254.0.0/16,10.147.0.0/16

```
For the sidecar test, I added the proxy option to my curl command and it works. Could it be the datadog ignoring the proxy context?
Thank you for your fast answer.
