### ISSUE TITLE
[exporter/clickhouse] Injection of projection into table schema via config

### ISSUE THREAD

**Issue by fredthomsen** [open-telemetry/opentelemetry-collector-contrib#29443]
### Component(s)

exporter/clickhouse

### Is your feature request related to a problem? Please describe.

I am using the `clickhouseexporter` to get data into clickhouse and multiple different services/applications read that data, but the current table schema may allow a query to be done in a way that is scalable or performs well.

### Describe the solution you'd like

Injection of projection in the schema DDL via configuration as follows:
```
clickhouse:
  endpoint: tcp://clickhouse:9000
  projections:
    gauge:
      app1_query_projection: |
        SELECT * 
        ORDER BY toUnixTimestamp64Nano(TimeUnix), Attributes['context.id'], ResourceAttributes['resource.name']
```                                        

### Describe alternatives you've considered

More customizable DDL statements for table schema creation in general.
