### ISSUE TITLE
[FileReader] Collector doesn't use more than 700m CPU 

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-collector-contrib#2945]
**Describe the bug**
I generated ~9710 EPS of load total from 2 log generator containers. 
the collector's CPU and memory usage was around 650. 
The calculated EPS on Splunk was ~9750. 
it ingested 99% of data (some data loss).

Then I doubled the load. total 18112 EPS from 4 log generator containers. 
the collector's CPU and memory utilization was at 700m.
The calculated EPS on Splunk was ~9900. 
It lost half of data.

So even though number of files to tail has increased, multiple CPUs are not being used. 

**What did you expect to see?**
Increase utilization on collector side and increased EPS

**What version did you use?**
Version: 0.22.0

**What config did you use?**
Config: 
```
exporters:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 2000
  splunk_hec:
    disable_compression: true
    endpoint: https://0.0.0.0:8088/services/collector
    index: k8s_log
    insecure_skip_verify: true
    max_connections: 2000
    source: otel
    sourcetype: otel
    timeout: 10s
    token: XXXXX
extensions:
  health_check: {}
processors:
  batch: {}
  k8s_tagger:
    auth_type: kubeConfig
    extract:
      annotations:
      - key: splunk.com/index
      - key: splunk.com/sourcetype
      labels:
      - key: hello
      - key: app
      - key: nonExisitngLabel
      metadata:
      - deployment
      - cluster
      - namespace
      - node
      - startTime
    filter:
      node_from_env_var: KUBE_NODE_NAME
    passthrough: false
    pod_association:
    - from: resource_attribute
      name: k8s.pod.uid
  memory_limiter:
    ballast_size_mib: 6553
    check_interval: 5s
    limit_mib: 13107
    spike_limit_mib: 4096
  resource/splunk:
    attributes:
    - action: upsert
      from_attribute: k8s.node.name
      key: host.name
    - action: upsert
      from_attribute: k8s.container.name
      key: com.splunk.sourcetype
    - action: upsert
      from_attribute: k8s.pod.annotations.splunk.com/index
      key: com.splunk.index
receivers:
  filelog:
    exclude:
    - /var/log/pods/default_rock-opentelemetry-collector-agent-*_*/opentelemetry-collector/*.log
    include:
    - /var/log/pods/*/*/*.log
    include_file_name: false
    include_file_path: true
    operators:
    - id: parser-docker
      output: extract_metadata_from_filepath
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: time
      type: json_parser
    - id: extract_metadata_from_filepath
      parse_from: $$attributes.file_path
      regex: ^\/var\/log\/pods\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[^\/]+)\/(?P<container_name>[^\._]+)\/(?P<run_id>\d+)\.log$
      type: regex_parser
    - attributes:
        k8s.container.name: EXPR($.container_name)
        k8s.namespace.name: EXPR($.namespace)
        k8s.pod.name: EXPR($.pod_name)
        run_id: EXPR($.run_id)
      resource:
        k8s.container.name: EXPR($.container_name)
        k8s.pod.uid: EXPR($.uid)
      type: metadata
    - id: clean-up-log-record
      ops:
      - remove: logtag
      - remove: stream
      - remove: container_name
      - remove: namespace
      - remove: pod_name
      - remove: run_id
      - remove: uid
      type: restructure
    start_at: beginning
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - logging
      - splunk_hec
      processors:
      - batch
      - k8s_tagger
      - resource/splunk
      receivers:
      - filelog
```

Container Spec
```
Containers:
  opentelemetry-collector:
    Container ID:  docker://b07312cea63c1a3f42e9b8b150d93b26db55b76acbdeb2dc23ed335b68936658
    Image:         rock1017/otelcontribcol:test5
    Image ID:      docker-pullable://rock1017/otelcontribcol@sha256:6300748fa3fbfeb6ddc1de2f6fc33aac329260062f8411fb210bb274e15b9dc7
    Port:          <none>
    Host Port:     <none>
    Command:
      /otelcontribcol
      --config=/conf/relay.yaml
      --metrics-addr=0.0.0.0:8888
      --mem-ballast-size-mib=6553
    State:          Running
      Started:      Mon, 29 Mar 2021 14:55:38 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     4
      memory:  16Gi
    Requests:
      cpu:     4
      memory:  16Gi
```
**Environment**
OS: Docker image
