### ISSUE TITLE
postgresql receiver inconsistently does not include schemaname in tablename for some metrics

### ISSUE THREAD

**Issue by cultpony** [open-telemetry/opentelemetry-collector-contrib#29559]
### Component(s)

receiver/postgresql

## Description

When retreiving the metrics for index and sequential scans (postgresql.sequential_scan and postgresql.index.scan), the tablename in the metricset is inconsistently constructed;

Sequential Scan Metrics will concat the schema to the tablename (`schema.relation`), while Index.Scan will only use the Table Name, omitting the schema (`relation`)

You can see the issue here in these two codeblocks:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.88.0/receiver/postgresqlreceiver/client.go#L270

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.88.0/receiver/postgresqlreceiver/client.go#L376

The same occurs with locks, which also do not include a schema.

The issue is that as a result, it becomes harder to actually correlate between the datasets, especially if tables exists with the same name in two schemas.

## Steps to Reproduce

1. Enable postgresql Metrics with optional metrics such as postgresql.sequential_scans

## Expected Result

Metrics have consistent names for the resources they track.

## Actual Result

Metrics have inconsistent names and cannot be reliably correlated.

### Collector version

v0.88.0, v0.90.0, 3b84eae0fd6718642294d0ab9b7e00cfc8bc208a

### Environment information

not relevant

### OpenTelemetry Collector configuration

```yaml
receivers:
  postgresql:
    endpoint: "localhost:5432"
    username: postgres
    password: postgres
    metrics:
      postgresql.sequential_scans:
        enabled: true
```

### Log output

```shell
not relevant
```

### Additional context

I'm happy to write a patch to change the index.* metrics to use a "schema.relation" name mapping in the same way all the other metrics for postgres work. It would be nice if all metrics had consistent tagging.

**Comment by djaglowski** [comment]
Thanks for pointing this out @cultpony. I agree we should be consistent across the receiver.

We seem to have two options here. Either have `postgresql.database.name: "schema.relation"`, or add a new attribute `postgresql.schema.name` and store the fields separately.

Generally I lean towards using separate attributes when we have two pieces of information. WDYT?

**Comment by crobert-1** [comment]
_Removing `needs triage` as the next steps and solution has been agreed upon._

**Comment by cultpony** [comment]
I mentioned it in the PR (and to bring this on the issue so that discussion isn't fragmented too much) but the best option would be to recommend users to migrate their system to rely on the newer attributes, since they are simply more reliable.

To restore old behaviour a transform step in the pipeline would be sufficient:

```yaml
transform:
  error_mode: ignore
  metric_statements:
  - context: resource
    statements:
    - set(attributes["postgresql.table.name"], Concat(attributes["postgresql.table.schema"],attributes["postgresql.table.name"],"."))
```
