### ISSUE TITLE
Splunk exporter causing CPU regression with version update

### ISSUE THREAD

**Issue by sarkisjad** [open-telemetry/opentelemetry-collector-contrib#29560]
**Describe the bug**
When comparing versions v0.54.0 and v0.87.0, there was a major issue with the CPU regression. This regression is happening because we are adding a Splunk exporter in our yaml file. 

**Steps to reproduce**
In order to reproduce the error, I did a performance profiler `pprof` for the two versions on the same application that is using the otel collector. 
We add `pprof` in the extension of the config yaml file: 
```
extensions:
  pprof:
    save_to_file: ${file_name}
```
The file saved is a binary file that can produce the results in the form of a FlamGraph through a software called `graphviz`.
We can visualize the results by writing on the command line `go tool pprog -http : ${file_name}`

Here are the results: 

![v0.54.0](https://github.com/open-telemetry/opentelemetry-collector/assets/77465705/88d30a3c-e110-477d-93fd-3b67a74ecbaa)
![v0.87.0](https://github.com/open-telemetry/opentelemetry-collector/assets/77465705/1c832baa-989a-43e1-97b5-79da3c5aeee0)

**What did you expect to see?**
I expected to not see a big difference in the CPU regression.

**What did you see instead?**
here is a table outline what is causing the main issue.
![image](https://github.com/open-telemetry/opentelemetry-collector/assets/77465705/0f34848e-78f2-44d1-af9d-a6ed66e71aa5)
Indeed, there is a 656% increase in CPU regression

**What version did you use?**
Version: `v0.54.0`, `v0.87.0`

**What config did you use?**
```
receivers:
  otlp: # pushed by agents
    protocols:
      grpc:
        endpoint: :${AGENT_RECEIVER_PORT}
  otlp/groupby: # pushed by env probes
    protocols:
      grpc:
        endpoint: :${OTLP_RECEIVER_PORT}

exporters:
  extensions: [pprof]
  splunk_hec/splunk_metrics: # push to Splunk.
    token: ${SPLUNK_TOKEN}
    endpoint: ${SPLUNK_ENDPOINT}
    source: "mx"
    sourcetype: "otel"
    index: "metrics_test"
    tls:
      insecure_skip_verify: true
    retry_on_failure:
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 3600s
    sending_queue:
      queue_size: 100000
      storage: file_storage

extensions:
  pprof:
    save_to_file: profiling_results

service:
  pipelines:
    metrics/splunk/env_probes:
      receivers: [otlp/groupby]
      exporters: [splunk_hec/splunk_metrics]
    metrics/splunk/agents:
      receivers: [otlp]
      exporters: [splunk_hec/splunk_metrics]
```
