### ISSUE TITLE
open telemetry agent problems with  Hostname, Timestamp add on attributes list

### ISSUE THREAD

**Issue by plrrag** [open-telemetry/opentelemetry-collector-contrib#29583]
Hi All,

I'm trying to extract and past "hostname" and "timestamp" into attributeslist, but both settings don't work, they return empty 
This is the complete config.yaml.
The agent version is Otelcontrib 0.72 and it is running on windows system

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.time:
            enabled: false
      disk:
      #load:
      filesystem:
      memory:
      network:
      #paging:
      #process:




processors:
  batch:
    timeout: 1s

    
  resource:
    attributes:
      - key: hostname
        value: "LAB-DB"
        action: insert
      - key: ipaddress
        value: "127.0.0.0"
        #from_context: host.name  it doesn't work
        action: insert
      - key: servertype
        value: "Database Lab"
        action: insert
      - key: isactive
        value: "1"
        action: insert
      #- key: timeStamp
        #value: ${event.time} it doesn't work
        #action: upsert
      - key: timestamp
        value: "${timestamp}" it doesn't work
        action: upsert
        

exporters:
  otlp:
    endpoint: 0.0.0.0:4320
    tls:
      insecure: true
  
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 5




service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,resource]
      exporters: [logging,otlp]
      
    metrics:
      receivers: [otlp,hostmetrics]
      processors: [batch,resource]
      exporters: [logging,otlp]
```

Does anyone know how to fix the problem?

Many thanks
