### ISSUE TITLE
Generic resource detector 

### ISSUE THREAD

**Issue by Doron-Bargo** [open-telemetry/opentelemetry-collector-contrib#29627]
### Component(s)

processor/resourcedetection

### Is your feature request related to a problem? Please describe.

A customer would like to dynamicly enrich his telemetries from his asset management platform 

### Describe the solution you'd like

A generic resource detector processor that get a url and list of parameters. For example:
```
processors:
  resourcedetection/http:
    detectors: [http]
    url: http://www.my-asset-management.com
    timeout: 2s
    metadata:
        key1:
            values:
                  value1,
                  value2
         key2:
              values:
                   value3
                   value4
```
            
Since each resource detector has metadata.yaml and here it is http based we don't know in advance the metadata so we would like to put it inside the configuration.

Explanation for this example

Key1,key2 are the keys that we are going to query the asset management platform against and values are the results fields we are expect to get from the asset management platform 

### Describe alternatives you've considered

We can tag as environment variable on each component that is being monitored by otel but this tag is static and we would like a dynamic solution where we can update it in one place and enrich the data based on it
