### ISSUE TITLE
[lokiexporter] Support structured metadata

### ISSUE THREAD

**Issue by verejoel** [open-telemetry/opentelemetry-collector-contrib#29634]
### Is your feature request related to a problem? Please describe.

It is not currently possible to make use of [structured metadata](https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/) when exporting logs using the Loki exporter.

### Describe the solution you'd like

Proposal is to add two new hints that would be used to tell the exporter which log/resource attributes should be attached as metadata:
- `loki.attribute.metadata`
- `loki.resource.metadata`

The translation library needs to be updated, to combine these maps and unmarshal them into a JSON suffix to the log line (as described in the Loki HTTP API [docs](https://grafana.com/docs/loki/latest/reference/api/#push-log-entries-to-loki)).

**Example:**

Given the following processors:

```yaml
processors:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: level
      - action: insert
        key: loki.attribute.metadata
        value: user_id

  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name
      - action: insert
        key: loki.resource.metadata
        value: trace_id
```

the HTTP post output would be constructed as:
```json
{
  "streams": [
    {
      "stream": {
        "level": "value",
        "service_name": "value",
      },
      "values": [
          [ "<unix epoch in nanoseconds>", "<log line>", {"trace_id": "0242ac120002", "user_id": "superUser123"} ]
      ]
    }
  ]
}
```

### Describe alternatives you've considered

Use an intermediary promtail component that has the `structured_metadata` stage configured.

### Additional context

`lokireceiver` probably also needs an update to correctly handle incoming structured metadata. I leave this as out of scope for this issue, but it could potentially be tackled at the same time (as the translator module probably needs both marshalling and unmarshalling of structured metadata).
