### ISSUE TITLE
Using AGGREGATION_ TEMPORARITY_ DELTA does not support histogram metrics

### ISSUE THREAD

**Issue by shicli** [open-telemetry/opentelemetry-collector-contrib#29659]
### Component(s)

connector/spanmetrics

## Description
I am using AGGREGATION_ TEMPORARITY_ DELTA, but I found that only the calls indicator was generated and there was no histogram indicator. I am confused about this. The reason why I chose DELTA is because CUMULATIV generates too many metrics, so I hope to use DELTA to clean up old data, but in reality, there is no duration data generation. I don't know if I misunderstood it, and I hope you can help me
## Steps to Reproduce
```
connectors:
   count:
    servicegraph:
      latency_histogram_buckets: [5ms, 30ms, 100ms, 500ms, 2s]
      dimensions:
        - span.kind
      #   - dimension-2
      store:
        ttl: 5s
        max_items: 5000
    spanmetrics:
      histogram:
        explicit:
          buckets: [2ms, 6ms, 10ms, 100ms, 250ms, 500ms, 2s]
      dimensions:
        # - name: http.method
        #   default: GET
        - name: http.status_code
      dimensions_cache_size: 100000
      aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"
```
## Expected Result
calls and duration
## Actual Result
only calls

### Collector version

0.88

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
