### ISSUE TITLE
metricsgenerationprocessor skips a rule if the second operand is 0

### ISSUE THREAD

**Issue by flyfire2002** [open-telemetry/opentelemetry-collector-contrib#29667]
### Component(s)

processor/metricsgeneration

## Description

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/05929995236e49ccdedc9a1ae0569bf3efd95cc5/processor/metricsgenerationprocessor/processor.go#L64 the check here means that if the second operand is 0 (even for actons like `add` or `subtract`), the affected rule is skipped (and the metric not generated)

## Steps to Reproduce

1. Have a rule
```
  experimental_metricsgeneration/subset:
    rules:
    - name: part_b
      type: calculate
      metric1: total
      metric2: part_a
      operation: subtract
```
2. make sure `part_a` has a value of 0
3. query `part_b`

## Expected Result

`part_b` has the same value as total.

## Actual Result

`part_b` is not generated at all.

### Collector version

main, 0.90.1
