### ISSUE TITLE
headers_setter not setting  header value from_context

### ISSUE THREAD

**Issue by gunjan-chauhan-dev** [open-telemetry/opentelemetry-collector-contrib#29676]
### Component(s)

extension/headerssetter

## Description
I am looking to setup open telemetry collector in gateway mode, where in each tenant is responsible for sending the tenant in for in "X-Scope-Orgid" header. The setup uses headers_setter extension to populate the header value in the otlp exporter. 

## Steps to Reproduce
save zipkin format trace sample in traces.json
```
[
  {
    "traceId": "5982fe77008310cc80f1da5e10147519",
    "parentId": "90394f6bcffb5d13",
    "id": "67fae42571535f60",
    "kind": "SERVER",
    "name": "/m/n/2.6.1",
    "timestamp": 1516781775726000,
    "duration": 26000,
    "localEndpoint": {
      "serviceName": "api"
    },
    "remoteEndpoint": {
      "serviceName": "apip"
    },
    "tags": {
      "data.http_response_code": "201"
    }
  }
]
```
 
Via curl send above trace to local otel collector:
`curl -X POST localhost:9411/api/v2/spans -H'Content-Type: application/json' -H 'X-Scope-Orgid: <my-tenant-id>' -d @trace.json`

## Expected Result
Authentication with the traces backend succeeds and traces are propagated.
## Actual Result
```
2023-12-06T19:04:25.134Z error exporterhelper/retry_sender.go:145 Exporting failed. The error is not retryable. Dropping data. {"kind": "exporter", "data_type": "traces", "name": "otlp/cloudoi", "error": "Permanent error: rpc error: code = Unknown desc = authentication token missing", "dropped_items": 1}

go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send

go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/retry_sender.go:145

go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send

go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/traces.go:177

go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).start.func1

go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/queue_sender.go:124

go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start.func1

go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/internal/bounded_memory_queue.go:52
```

### Collector version

v0.86.0

## Environment
OS: macos 13.6.1
running docker image locally otel/opentelemetry-collector-contrib:0.86.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  zipkin:
    include_metadata: true
exporters:
  otlp/cloud:
    endpoint: <cloud-otel-col-endpoint>:443
    auth: 
      authenticator: headers_setter/cloud
processors:
  attributes:
    actions:
     - key: "traces_orgid"
       action: insert
       from_context: "X-Scope-Orgid"
  filter/ctd:
    traces:
      span:
        - 'resource.attributes["service.name"] == "frontend-proxy"'
  batch:

extensions:
  headers_setter/cloud:
    headers:
      - action: insert
        key: "X-Scope-Orgid"
        from_context: "X-Scope-Orgid"

service:
  extensions: [ headers_setter/cloud ]
  pipelines:
    traces/ctd:
      receivers: [zipkin ]
      processors: [ attributes, filter/ctd, batch ]
      exporters: [ otlp/cloud  ]
```

### Log output

```shell
2023-12-06T19:04:25.134Z error exporterhelper/retry_sender.go:145 Exporting failed. The error is not retryable. Dropping data. {"kind": "exporter", "data_type": "traces", "name": "otlp/cloudoi", "error": "Permanent error: rpc error: code = Unknown desc = authentication token missing", "dropped_items": 1}

go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send

go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/retry_sender.go:145

go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send

go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/traces.go:177

go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).start.func1

go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/queue_sender.go:124

go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start.func1

go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/internal/bounded_memory_queue.go:52
```

**Comment by gunjan-chauhan-dev** [comment]
Thanks, this works as expected after removing batch processor.. Is there any plans that this also starts to work with batch processor as well in future?
Closing this issue.

**Comment by crobert-1** [comment]
Hello @gunjan-chauhan-dev, there are some configuration options available in the batch processor to batch by metadata, which will allow metadata to be kept with the data. [Here's the section in the README](https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor#batching-and-client-metadata). The keys specified in `metadata_keys` will be included in the metadata of telemetry created by the batch processor.

**Comment by gunjan-chauhan-dev** [comment]
Thanks @crobert-1, this is helpful.

**Comment by wondertalik** [comment]
Hello, i tried all: remove batch, use metadata_keys, but still can't read from context value. Any guess?

 image: otel/opentelemetry-collector-contrib:0.119.0

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          cert_file: /var/otel/certs/dev2.crt
          key_file: /var/otel/certs/dev2.key
        include_metadata: true
      http:
        endpoint: 0.0.0.0:4318
        tls:
          cert_file: /var/otel/certs/dev2.crt
          key_file: /var/otel/certs/dev2.key
        include_metadata: true

processors:
  attributes:
    actions:
      - key: http.client_ip
        from_context: metadata.x-forwarded-for
        action: upsert
  
  batch:
    metadata_keys:
      - x-otlp-api-key
      - metadata.x-otlp-api-key
    # limit to 10 batcher processes before raising errors
    metadata_cardinality_limit: 10

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  otlp/aspire-dashboard:
    endpoint: http://aspire-dashboard:18889
    tls:
      insecure: true
      insecure_skip_verify: true
    auth:
      authenticator: headers_setter


extensions:
  headers_setter:
    headers:
      - action: insert
        key: x-otlp-api-key
#        value: ${env:ASPIRE_DASHBOARD_OTLP_PRIMARYAPIKEY}
        from_context:  x-otlp-api-key
  health_check:
  pprof:
  zpages:

service:
  extensions: [ headers_setter ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [  ]
      exporters: [ otlp/aspire-dashboard, debug ]
    metrics:
      receivers: [ otlp ]
      processors: [  ]
      exporters: [ otlp/aspire-dashboard, debug ]
    logs:
      receivers: [ otlp ]
      processors: [  ]
      exporters: [ otlp/aspire-dashboard, debug ]
```
