### ISSUE TITLE
New component: Apache Druid Receiver

### ISSUE THREAD

**Issue by yuanlihan** [open-telemetry/opentelemetry-collector-contrib#29685]
### The purpose and use-cases of the new component

To be able to stream [metrics](https://druid.apache.org/docs/latest/operations/metrics), [logs](https://druid.apache.org/docs/latest/operations/request-logging) and [alerts](https://druid.apache.org/docs/latest/operations/alerts) directly from the [HTTP Emitter](https://druid.apache.org/docs/latest/configuration/#http-emitter-module) of Apache Druid.

### Example configuration for the component

```yaml
receivers:
  apachedruid:
    endpoint: 0.0.0.0:9000
    metrics_path: '/services/collector/metrics'
    logs_path: '/services/collector/logs'
```

### Telemetry data types supported

Metrics and Logs.

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@yuanlihan 

### Sponsor (optional)

@atoulme

### Additional context

> [Apache Druid](https://druid.apache.org) is a high performance, real-time analytics database that delivers sub-second queries on streaming and batch data at scale and under load.

It'll be great to integrate Apache Druid with OpenTelemetry ecosystem. I'm ready to submit the first PR of the new component if the proposal looks good to the team!
