### ISSUE TITLE
Splunk HEC Exporter Transmission to HEC Endpoint Fails With Missing Body

### ISSUE THREAD

**Issue by bdschaap** [open-telemetry/opentelemetry-collector-contrib#29693]
### Component(s)

exporter/splunkhec

## Description
Splunk HEC Exporter transmission to HEC endpoint fails when there is a missing `body` field.  The otel logs data model lists body as an optional field.  I'm using Faro Web SDK which has a log type (measurement) that does not contain a `body` field.

## Steps to Reproduce
Transmit a log without a `body` field.

## Expected Result
OTLP logs received and exported with a missing body field should not fail transmission to a HEC endpoint.  Perhaps a default value should be set.  Alternative is that the HEC endpoint (ie Splunk Forwarder, Splunk Enterprise, Splunk Cloud, etc) should accept a missing body field.  I have encountered this behavior with a Splunk Forwarder.

## Actual Result
400 response code is returned stating bad data format.

### Collector version

opentelemetry-collector-contrib:0.88.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  splunk_hec/dev:
	token: "<guid>"
	endpoint: "https://splunkforwarder.mydomain.local:8088/services/collector/event"
	source: "otel"
	hec_metadata_to_otel_attrs:
	  source: "service.name"        
	sourcetype: "faro"
	index: "dev"
```
