### ISSUE TITLE
New component: Kentik Network Telemetry Receiver

### ISSUE THREAD

**Issue by i3149** [open-telemetry/opentelemetry-collector-contrib#29759]
### The purpose and use-cases of the new component

Kentik is a company which collects both passive and active network data. Passive examples are [netflow](https://www.kentik.com/kentipedia/netflow-tool/) and [npm](https://www.kentik.com/kentipedia/network-performance-monitoring/) both of which are best seen as metrics, while active is the [network synthetic](https://www.kentik.com/blog/website-performance-and-transaction-monitoring-with-kentik/) product which performs web transactions and produces a har file result for each test run which should map to a trace. 

These signals can be exported from Kentik via a http stream of Cap'n Proto buffers. We would like to create an otel receiver for this feed and allow any otel collector to work with Kentik data. [New Relic](https://newrelic.com/instant-observability/kentik-firehose-pack) provides an example of how this data can be integrated. 

### Example configuration for the component

```
receivers:
  kentik:
    endpoint: 0.0.0.0:9000 # Where to listen for the HTTP push from Kentik.
    auth: # Required. An email and an API token is required in the header authentication
      email: <X-Auth-Email>
      token: <API_TOKEN>
    region: US # defaults to US, can override for other Kentik regions. 
```

### Telemetry data types supported

Metrics, Traces

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@i3149 

### Sponsor (optional)

@astencel-sumo

### Additional context

There is an existing OSS tool to translate the binary feed from kentik at https://github.com/kentik/ktranslate. We'd like to get away from having users run 2 binaries (ktranslate + otel collector) but there's an argument to be made that ktranslate should just be updated to emit otel. In practice, we find getting 1 binary running correctly is hard enough.
