### ISSUE TITLE
New component: FIFO diskbuffer processor

### ISSUE THREAD

**Issue by CatherineF-dev** [open-telemetry/opentelemetry-collector-contrib#29779]
### The purpose and use-cases of the new component

Purpose: buffer metrics data in disk when network disconnected. 

The buffer is 1. FIFO  2. support retention size 3. support retention time

Why FIFO: some metrics database don't support writing old data points.

### Example configuration for the component

```
processors:
  disk_buffer:
    buffer_dir: "testNsq"
    retention_size_mib: 5000
    retention_time: 6h
    probe_interval: 2s
    backend_endpoint: "http://monitoring.backend.com"
```

### Telemetry data types supported

metrics, logs, traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@CatherineF-dev, @leonzz
