### ISSUE TITLE
Extract value set from attributes processor

### ISSUE THREAD

**Issue by JRosa316** [open-telemetry/opentelemetry-collector-contrib#29845]
### Component(s)

processor/routing

## Description
As part of our implementation we would like to rip out values from labels in our namespace via the k8sattributes processor and then be able to direct them to the correct exporters via the routing processor, with our current implementation it doesn't seem to work 

### Collector version

0.69.1

## Environment
OS: Kubernetes v1.24.15

### OpenTelemetry Collector configuration

```yaml
---
opentelemetry-collector:
  mode: daemonset
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi

  presets:
    logsCollection:
      enabled: true
      includeCollectorLogs: false
    kubernetesAttributes:
      enabled: true
    kubeletMetrics:
      enabled: false
    hostMetrics:
      enabled: false

  image:
    repository: <private repo>
  config:
    processors:
      # Resource Processors
      resource:
        attributes:
        - key: k8s.cluster.name
          value: cluster1
          action: upsert
      # K8's Processor
      k8sattributes/2:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          labels:
            - tag_name: namespace.label # Setting value for log sgnal
              key_regex: (\b[Ll][Oo][Bb]\b)
              from: namespace
      # Routing Processor
      routing/value:
        from_attribute: namespace.label
        attribute_source: resource
        default_exporters: 
          - otlphttp/default
        table:
          - statement: route () where resource.attributes["namespace.label"] == "value1" # trying to extract and route value 
            exporters:
              - otlphttp/value1
    extensions:
      health_check: {}
      memory_ballast: {}
    exporters:
      debug:
        verbosity: normal
      otlphttp/default:
        endpoint: http://otel-standalone.aws.k8s
        tls:
          insecure: true
        sending_queue:
          num_consumers: 100
          queue_size: 100000
      otlphttp/value1:
        endpoint: http://otel-standalone1.aws.k8s
        tls:
          insecure: true
        sending_queue:
          num_consumers: 100
          queue_size: 100000
    service:
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        logs:  
          exporters:
          - debug
          - otlphttp/default
          - otlphttp/value1
          processors:
            - resource
            - k8sattributes/2
            - routing/value
```

**Comment by crobert-1** [comment]
> with our current implementation it doesn't seem to work

Hello @JRosa316, can you add some more information here about what isn't working as expected? Do you have any logs you're seeing in the collector that are relevant?

A couple things I'm seeing:
```
        extract:
          labels:
            - tag_name: namespace.label # Setting value for log sgnal
              key_regex: (\b[Ll][Oo][Bb]\b)
              from: namespace
```
From your config, do you know if this `key_regex` is matching what you expect it to?

```
      routing/value:
        from_attribute: namespace.label
        attribute_source: resource
        default_exporters: 
          - otlphttp/default
        table:
          - statement: route () where resource.attributes["namespace.label"] == "value1" # trying to extract and route value 
            exporters:
              - otlphttp/value1
```
You can remove `from_attribute` and `attribute_source`, since you're OTTL in your table statement.
