### ISSUE TITLE
Open Telemetry headers setter extension not working when any processor is added to the trace pipeline

### ISSUE THREAD

**Issue by SimranCode** [open-telemetry/opentelemetry-collector-contrib#29852]
### What happened?

When I use Headers Setter extension to set the Tenant ID and Sampling Processor or any processor for that matter for Traces
 in Otel Collector Config, the data doesnt get exported to the endpoint. 

Both of these features works fine when added individually.

Could you provide any workaround for this if there is no fix available for now?

### Collector version

0.91

### OpenTelemetry Collector configuration

```yaml
extensions:
  headers_setter:
    headers:
      - action: upsert
        key: X-Scope-OrgID
        from_context: tenantid
receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
        endpoint: 0.0.0.0:5555
      http:
        include_metadata: true
      

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      tenant: tenant1
    
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true
    auth:
      authenticator: headers_setter

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    auth:
      authenticator: headers_setter 


processors:
  tail_sampling:
    decision_wait: 1s
    num_traces: 1000
    expected_new_traces_per_sec: 100
    policies:
      [
          {
            name: latency-policy,
            type: latency,
            latency: {threshold_ms: 1000}
          }        
                  
      ]
               
  transform:
    metric_statements:
      - context: datapoint
        statements:
        - set(attributes["tenantname"], resource.attributes["tenantid"])
  batch:
    timeout: 1s
    send_batch_size: 1024
    
service:
  extensions: [headers_setter]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [transform]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]
```
