### ISSUE TITLE
metricstransformprocessor just not working

### ISSUE THREAD

**Issue by tcaty** [open-telemetry/opentelemetry-collector-contrib#29853]
### Component(s)

processor/metricstransform

## Description

Hi! Today I faced this issue: I tried to use `metricstransform` processor in metrics pipeline but it just not working.

## Steps to Reproduce

1. Try to use `metricstransform` in pipelines

## Expected Result
Target metric should contains new label like that

```
duration_milliseconds_count{custom_label="custom_value", exported_job="client", instance="otel-collector-aggregated:8889", job="otel-collector-aggregated", service_name="client", span_kind="SPAN_KIND_CLIENT", span_name="HTTP GET", status_code="STATUS_CODE_ERROR"}
```

## Actual Result

As you can see on screenshot below prometheus pull metrics which has no custom label from metricstransform

```
duration_milliseconds_count{exported_job="client", instance="otel-collector-aggregated:8889", job="otel-collector-aggregated", service_name="client", span_kind="SPAN_KIND_CLIENT", span_name="HTTP GET", status_code="STATUS_CODE_ERROR"}
```

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/79706809/c579d73f-b78c-4aba-bf4c-da85ffef0cdd)

### Collector version

v0.90.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
  metricstransform:
    transforms:
      - include: duration_milliseconds_count
        action: update
        operations:
          - action: add_label
            new_label: custom_label
            new_value: custom_value

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
      
connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/tempo
        - otlp/jaeger
        - spanmetrics
    metrics:
      receivers:
        - otlp
        - spanmetrics
      processors:
        - batch
        - metricstransform
      exporters:
        - prometheus
```
