### ISSUE TITLE
[receiver/azuremonitor] Error with microsoft.insights/components

### ISSUE THREAD

**Issue by danelson** [open-telemetry/opentelemetry-collector-contrib#29861]
### Component(s)

receiver/azuremonitor

## Description

When using azuremonitor I encounter the following error when including the [microsoft.insights/components](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-insights-components-metrics) service (either directly or indirectly)

```json
{
    "cost": 0,
    "timespan": "2023-12-13T17:56:50Z/2023-12-13T17:57:50Z",
    "interval": "PT1M",
    "value":
    [
        {
            "id": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Insights/components/<redacted>/providers/Microsoft.Insights/metrics/availabilityResults/availabilityPercentage",
            "type": "Microsoft.Insights/metrics",
            "name":
            {
                "value": "availabilityResults/availabilityPercentage",
                "localizedValue": "Availability"
            },
            "displayDescription": "Percentage of successfully completed availability tests",
            "unit": "Percent",
            "timeseries":
            [],
            "errorMessage": "Sampling type is not found. Metric:ApplicationInsights_PROD_centralus,ApplicationInsights,availabilityResults/availabilityPercentage, SamplingType:Max.",
            "errorCode": "InvalidSamplingType"
        }
    ],
    "namespace": "Microsoft.Insights/components",
    "resourceregion": "centralus"
}
```

## Steps to Reproduce

Direct reference
```yaml
azuremonitor:
  subscription_id: <redacted>
  tenant_id: <redacted>
  client_id: <redacted>
  client_secret: <redacted>
  resource_groups:
    - <redacted>
  services:
    - microsoft.insights/components
  collection_interval: 60s
  initial_delay: 10s
```

Indirect reference. This results in no data for any services
```yaml
azuremonitor:
  subscription_id: <redacted>
  tenant_id: <redacted>
  client_id: <redacted>
  client_secret: <redacted>
  collection_interval: 60s
  initial_delay: 10s
```

## Expected Result

- I would expect to not get an error.
- If there is an error for a single service I would expect to get data for the the other services

## Actual Result

- Errors and no data

### Collector version

v0.90.1

## Environment

- Running a custom collector distribution on alpine
