### ISSUE TITLE
[connector/routing] When matching multiple conditions, build a new consumer each time.

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#29882]
Related question which can be a separate issue. Is the _other_ (match multiple routes) approach implemented correctly? I am wondering if we are not properly fanning out the data.

For example, if we match routes 1 and 2, we cannot send the same copy of the data to both consumers. We need to use a fanout. In other words, we should build a consumer which contains all the pipelines in both 1 and 2, and send to that.

_Originally posted by @djaglowski in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/28888#issuecomment-1832340932_

**Comment by jpkrohling** [comment]
@mwear, are you interested in taking a look at this one?

**Comment by sirianni** [comment]
> Does anyone actually rely on match_once: false?

My team relies on `match_once: false`.  We have many use cases for telemetry in our platform and different "sinks" supporting those use cases.  We use the `routingconnector` to selectively send telemetry to those sinks.  A single resource may provide telemetry that's useful in multiple sinks.

**Comment by djaglowski** [comment]
Thanks @sirianni. What do you think about the alternatives that I proposed above? If you want to share an example configuration, I would be interested in trying to convert it to produce the same result as `match_once: true`.

**Comment by sirianni** [comment]
> What do you think about the alternatives that I proposed above?

It's doable, but as you said forces the user to enumerate all of the possible combinations explicitly which increases configuration complexity.

As you pointed out, the alternative would be to have the code itself build a `consumer` for each unique set of matched routes which is quite complex on the implementation side.

**Comment by jpkrohling** [comment]
For reference, this was added as part of this PR and does NOT exist as part of the processor:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/28888

**Comment by djaglowski** [comment]
As much as I don't want to break anyone and would like to support the `match_once: false` use case, I think we have a serious problem with that implementation and no capacity to solve it. 

At a minimum, I think we should proceed with deprecation and changing the default to `match_once: true` before we are able to declare the component beta. However, we can keep the setting in place for quite a while and make a final decision later.

Thoughts?

**Comment by jpkrohling** [comment]
I agree that the best course of action is to deprecate/remove that feature, at least for the moment.

**Comment by sirianni** [comment]
@djaglowski thanks for your work on this component.

I'm thinking through this and going around in circles a bit 🙂 .  Is there a practical difference between 
(A) using the `routing` connector 
-- vs --
(B) using the `forward` connector combined with a `filtering` processor as the first step in the destination pipeline that filters out telemetry not for itself?

```yaml
routing/region:
  match_once: true
  table:
    - condition: attributes["region"] == "east"
       pipelines: [ logs/east ]
    - condition: attributes["region"] == "west"
       pipelines: [ logs/west ]
```

vs. 
```yaml
...
exporters: [ forward/logs ]

logs_east:
  receivers: [ foward/logs ]
  processors: [ filter/logs_east ]
  exporters: [ ... ]
logs_west:
  receivers: [ foward/logs ]
  processors: [ filter/logs_west ]
  exporters: [ ... ]
```
