### ISSUE TITLE
mdatagen: attribute with type `bytes` generates erroneous unit tests

### ISSUE THREAD

**Issue by mmynk** [open-telemetry/opentelemetry-collector-contrib#29923]
### Component(s)

cmd/mdatagen

## Description
Defining an attribute in `metadata.yaml` with `bytes` type generates unit tests which do not compile. The [schema](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9378ab5a15e4fe481fdc03627138e5def9638eb5/cmd/mdatagen/metadata-schema.yaml#L68) defines `bytes` as a valid type for an attribute.

However, the unit tests tries to create byte arrays like:
```go
mb.RecordMetric1(ts, bytes("attr1-val")
```

However, I believe it should be:
```go
mb.RecordMetric1(ts, []byte("attr1-val")
```

## Steps to Reproduce
Define an attribute in `metadata.yaml` as:
```yaml
attributes:
  attr1:
    description: An attribute with type bytes
    type: bytes

metrics:
  metric1:
  desciption: A metric
  enabled: true
  sum:
    value_type: int
    monotonic: true
  unit: kg
  attributes:
    - attr1
```

## Expected Result
A compiling unit test

## Actual Result
A not compiling unit test

### Collector version

v0.90.0

## Environment
OS: Ubuntu v22.04
Compiler(if manually compiled): go 1.21.3 linux/amd64
