### ISSUE TITLE
[DataDog Collector] Not able to send traces to DataDog using an HTTPS proxy 

### ISSUE THREAD

**Issue by anuprout** [open-telemetry/opentelemetry-collector-contrib#3004]
**Describe the bug**
Hi, I have set up a DataDog collector with an HTTPS proxy and  I am sending the Otel traces from my application to this collector on port 55680 over gRPC.  I get the below certificate error in the collector log.

`failed to send trace stats        {"component_kind": "exporter", "component_type": "datadog", "component_name": "datadog/api", "error": "failed to send stats payload to trace edge: Post \"https://my_proxy.com:8444/api/v0.2/stats\": x509: certificate is valid for *.agent.datadoghq.com, agent.datadoghq.com, not my_proxy.com"}`

However, this is the same proxy we use for [a regular DataDog agent](https://docs.datadoghq.com/getting_started/agent/) running on the same host and it works. 

Is there any proxy setting I am missing here?

**Steps to reproduce**

- Set up the DD collector with the below config.
- Start sending the OTel traces on the port 55680

**What version did you use?**
Version: 0.23.0

**What config did you use?**
Config: 
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  datadog/api:
    hostname: test_host
    env: dev
    service: otel-demo-java
    version: 1.0

    tags:
      - datacenter:iad1
      - env:dev

    api:
      key: <api_key>
      site: datadoghq.com
    traces:
      endpoint: https://my_proxy.com:8444
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/api]
```

**Environment**
OS: Centos
