### ISSUE TITLE
Instana exporter

### ISSUE THREAD

**Issue by rupinder10** [open-telemetry/opentelemetry-collector-contrib#30048]
### Component(s)

exporter/instana

### What happened?

I am using the OpenTelemetry collector contrib (version 0.91.0) with the instana exporter.

I got the endpoint and agent keys from my instana console and plugged them into the otelcollector config. 

```  instana:
      endpoint: https://ingress-coral-saas.instana.io
      agent_key: my-actual-key here
```
But when the collector starts I get this error message

"error": "Permanent error: error when sending payload to https://ingress-coral-saas.instana.io/bundle: 404 Not Found"

I checked and the /bundle endpoint is invalid. 

What is the correct configuration for this ?

### Collector version

0.91.0

## Environment
OS: Windows 11

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:  
  instana:
    endpoint: https://ingress-coral-saas.instana.io
    agent_key: my-actual-key
    
processors:
  batch:
    timeout: 30s
    send_batch_size: 90


extensions:
  health_check:
  pprof:
  zpages:

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [instana]
      processors: [batch]
```

### Log output

```shell
2023-12-18T20:46:14.785Z	error	exporterhelper/common.go:49	Exporting failed. Try enabling retry_on_failure config option to retry on retryable errors	{"kind": "exporter", "data_type": "traces", "name": "instana", "dropped_items": 512, "error": "Permanent error: error when sending payload to https://ingress-coral-saas.instana.io/bundle: 404 Not Found"}
```
