### ISSUE TITLE
"SERVICE" column in DataDog Logs not showing "service.name" attribute: shows entire Json section in string form

### ISSUE THREAD

**Issue by julealgon** [open-telemetry/opentelemetry-collector-contrib#30049]
### Component(s)

exporter/datadog

## Description
"Service" log column in DataDog showing entire "service" json section from log instead of just "service.name" as before.

Instead of just showing "SequenceNumberTracker API", the UI just shows the entire "service" section in serialized Json form.

(third column is the "SERVICE" column):
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/461579/e8f39bb5-860e-4559-900e-899776801efd)

Information inside the log event:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/461579/d94f6228-4359-4030-8ec9-1f024806d63b)

This started happening after I upgraded the collector to the latest version (v0.91.0) from a fairly old version, v0.62.0

## Steps to Reproduce
Upgrade to v0.91.0? It's hard to tell precisely which version actually introduced this issue, since we migrated from a fairly old release and did a big version jump.

## Expected Result
I expect the "SERVICE" column to still contain just the `service.name` value, and not the entire Json section in string form.

## Actual Result
The "SERVICE" column now contains the entire "service" section of the log event in Json string form.

### Collector version

0.91.0

## Environment
OS: Windows Server 2019 Datacenter 10.0.17763 (Azure VM)
Compiler(if manually compiled): N/A (downloaded Windows amd64 binary)

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:

  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      load:
      memory:
      network:
      processes:

processors:
  batch:
    timeout: 10s

  resource:
    attributes:
    - key: deployment.environment
      value: "prod"
      action: upsert

  transform:
    trace_statements:
      - context: scope
        statements:
          - set(name, "aspnet.request") where name == "Microsoft.AspNetCore" or name == "OpenTelemetry.Instrumentation.AspNetCore" or name == "OpenTelemetry.Instrumentation.AspNet.Telemetry"
          - set(name, "sql_server.query") where name == "OpenTelemetry.Instrumentation.SqlClient"
          - set(name, "http.request") where name == "OpenTelemetry.Instrumentation.Http.HttpWebRequest" or name == "OpenTelemetry.Instrumentation.Http.HttpClient"

exporters:
  datadog:
    api:
      key: ${DATADOG_APIKEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, transform, batch]
      exporters: [datadog]
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [resource, batch]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [datadog]
```

### Log output

```shell
N/A
```
