### ISSUE TITLE
support http (security) headers in opamp supervisor

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#30137]
### Is your feature request related to a problem? Please describe.

Please add support for standard and custom security headers in opamp supervisor configuration. 

### Describe the solution you'd like

```
server:
  endpoint: wss://localhost:4320/v1/opamp
  headers:
    Authorization: key value
    x: 123445
    y:  hello
         
```

Especially it would be beneficial if authorization based on opneid connect is supported like its done fpr exporters by otel collector via extension https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/8f6fc8f16a628e0c4d6bdfd4f516ddb46b899e0c/extension/oidcauthextension

```
extensions:
  oidc:
    issuer_url: http://localhost:8080/auth/realms/opentelemetry
    issuer_ca_path: /etc/pki/tls/cert.pem
    audience: account
    username_claim: email

server:
  endpoint: wss://localhost:4320/v1/opamp
  auth:
    authenticator: oidc
```

**Comment by srikanthccv** [comment]
Headers support will be added as a part of this PR https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30237

**Comment by cforce** [comment]
@srikanthccv  Can we close this?

**Comment by evan-bradley** [comment]
Closing as resolved via https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30237

**Comment by cforce** [comment]
@srikanthccv  @evan-bradley 
This issue was rquesting as well support for openid


As far as i understood only below is now supported

```
server:
  endpoint: wss://localhost:4320/v1/opamp
  headers:
    Authorization: key value
    x: 123445
    y:  hello
```

but still below openid is not, is it?

```
extensions:
  oidc:
    issuer_url: http://localhost:8080/auth/realms/opentelemetry
    issuer_ca_path: /etc/pki/tls/cert.pem
    audience: account
    username_claim: email

server:
  endpoint: wss://localhost:4320/v1/opamp
  auth:
    authenticator: oidc
```

Can we reopen or do you want me to create  an additional request?
