### ISSUE TITLE
Implement Connectors into the Testbed

### ISSUE THREAD

**Issue by humivo** [open-telemetry/opentelemetry-collector-contrib#30165]
### Component(s)

testbed

### Is your feature request related to a problem? Please describe.

The current Testbed configuration does not support [Connectors](https://opentelemetry.io/docs/collector/building/connector/).

### Describe the solution you'd like

I would like the Testbed configuration/data flow to be restructured to accept connectors.  For example, in this [configuration for correctness tests](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4acf9f80ae63bbde07bf064e49bccd24b5d373b2/testbed/correctnesstests/utils.go#L22),  allow a connector to be added for multiple pipelines in the Collector.

**Comment by humivo** [comment]
I am currently looking into the changes that would need to be made to introduce connectors into the Testbed but would appreciate any input on the approach for this!

**Comment by humivo** [comment]
Hello, I'm looking for any input on this approach to add connectors to testbed.  I initially thought that we could just add in a connector parameter into the [CreateConfigYaml()](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/00263adfcea901c7c3394b62065fe860b82256fc/testbed/correctnesstests/utils.go#L22) method in correctnesstests and if defined, create a config with 2 pipelines that looks like this:
```
receivers: sender
exporters: receiver
processors: processors
connectors: connector

extensions:

service:
  extensions:
  pipelines:
    traces:
      receivers: [sender]
      processors: [processors]
      exporters: [connector]
    metrics:
      receivers: [connector]
      exporters: [receiver]
```
However, I noticed that `pipelineType` is a required parameter and correctnesstests are split up between traces and metrics so I am not sure how it would handle a traces DataSender but a metrics DataReceiver.  Is the answer here to create a new type of tests so that we can create another `TestCaseValidator` for this use case?
