### ISSUE TITLE
filter processor for metrics sending non matching values to exporter

### ISSUE THREAD

**Issue by meSATYA** [open-telemetry/opentelemetry-collector-contrib#30176]
### Component(s)

processor/filter

## Description
I am trying to filter metrics where a metric having a specific label and non-empty values should be filtered and send to the exporters. But, unfortunately it also sends label values having null as well. It detects right metric names having those labels, but can't ignore null values. 
## Steps to Reproduce
Filter configurations I have tried is mentioned in the OpenTelemetry Collector configuration section.

## Expected Result
 Filter processor should only filter metrics having label "my.last.name" and value should be not null.

## Actual Result
Filter processor sending metrics with null values as well. 

### Collector version

v0.87.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
Filter configurations I have tried:

1. filter/egress-otel:
      metrics:
        include:
          match_type: expr
          expressions:
          - Label("my.last.name") == "rout" # didn't work, sending null values as well
 2. filter/egress-otel:
      metrics:
        include:
          match_type: expr
          expressions:
          - Label("my.last.name") != nil # didn't work, sending null values as well
 3. filter/egress-otel:
      metrics:
        include:
          metric_names:
              - .*
          match_type: expr
          expressions:
          - Label("service.name") == "passport" && Label("my.last.name") != nil # didn't work, sending null values as well
  4. filter/egress-otel:
        metrics:
          include:
            match_type: regexp
            metric_names:
            - .*
            resource_attributes:
            - key: service.name
              value: passport
            - key: my.last.name
               value: rout
```

**Comment by meSATYA** [comment]
Has anyone else faced this issue?

**Comment by meSATYA** [comment]
@MacroPower @TylerHelmuth Could you please check if you can reproduce this issue at your end?

**Comment by vaibhhavv** [comment]
Hi @jpkrohling, @austinlparker, can you guide here or may be someone you know who can guide better here? 
Actually we are stuck in middle of a use case and need to filter down the data over OpenTelemetry and forward it, but seems like filter process is not working as per the requirements.

**Comment by TylerHelmuth** [comment]
I am still on holiday break but will try to get to this issue next week.

**Comment by meSATYA** [comment]
Thanks @TylerHelmuth for your response. As further tested, it is observed that though filterprocessor matches correct label, it not only sends the timeseries having that label, but also sends other timeseries where that label is not present. It seems the filterprocessor works on metric names, but not on the timeseries. Is it possible to export only those timeseries having matching labels?

For example:
    `filter/egress-metrics:
        metrics:
          include:
            expressions:
            - Label("vwg.checkpoint.log") != ""
            match_type: expr`
          
The output is exported to Mimir and as you can see the result in the screenshot, there are 3 timeseries are exported, where as the expectation from the filterprocessor is that it should only export the 3rd timeseries where the Label("vwg.checkpoint.log") is "register". It's great to have your opinion on this.

**Comment by TylerHelmuth** [comment]
I want to clarify first that metrics do not have attributes (what prometheus calls labels).  Metrics have datapoints and datapoints have attributes. 

Based on your description I'm going to assume you want to KEEP data based on a datapoint attribute and DROP (filter) all other data.

I highly encourage you to try using the filterprocessor's preferred configuration option that uses OTTL. You can see some examples [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#dropping-non-http-spans) of how OTTL allows checking for the presence or absence of an attribute.

I'm not totally understanding your exact use case, but if you want to KEEP a metric where ANY datapoint in that metric contains a specific attribute and DROP all other metrics you can do:

```yaml
processors:
  filter/ottl:
    error_mode: ignore
    metrics:
      metric:
          - HasAttrKeyOnDatapoint("my.last.name")
```

This configuration uses the [HasAttrKeyOnDatapoint function](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#hasattrkeyondatapoint) to check if any datapoint in the metric has an attribute named `"my.last.name"`
