### ISSUE TITLE
[exporter/clickhouse] exporter fails with IO timeout error under load

### ISSUE THREAD

**Issue by MacNale** [open-telemetry/opentelemetry-collector-contrib#30175]
### Component(s)

exporter/clickhouse

## Description
Using prometeus-receiver to stress test the clickhouse exporter.  Clickhouse exporter fails with IO timeout error.

## Steps to Reproduce
1) Use Prometheus receiver or any other receiver (100K metric samples/minute)
2) Configure clickhouse exporter using the config below

Single node clickhouse running on linux with 16 core and 64 GB memory

## Expected Result
- Load testing result needs to be published.
- Exporter is able to ingest 100K metric samples per minute

## Actual Result
Timeout error

### Collector version

0.81.0

## Environment
OS: (e.g., "Ubuntu 20.04")
CentOS 8

### OpenTelemetry Collector configuration

```yaml
prometheus:
      config:
        scrape_configs:
          - job_name: 'otel-collector-prom-load'
            scrape_interval: 30s
            static_configs:
              - targets: xxxx
processors:
  batch:
    send_batch_size: 20000
    timeout: 30s
    
 exporters:
  clickhouse:
    endpoint: xxxx
    ...
    timeout: 100s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
      
 pipelines:
    metrics:
      receivers: [prometheus, otlp]
      processors: [resource, batch]
      exporters: [clickhouse]
```

### Log output

```shell
2023-12-22T03:25:33.335Z        debug   internal/gauge_metrics.go:145   insert gauge metrics fail       
{"kind": "exporter", "data_type": "metrics", "name": "clickhouse", "cost": 99.529687419}
2023-12-22T03:25:33.335Z        error   exporterhelper/queued_retry.go:165      Exporting failed. 
No more retries left. Dropping data.  {"kind": "exporter", "data_type": "metrics", "name": "clickhouse", "error": "max elapsed time expired insert gauge metrics fail:read: read tcp xxxxxxx:9000 i/o timeout", "dropped_items": 200005}
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).onTemporaryFailure
        go.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/queued_retry.go:165
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/queued_retry.go:407
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
        go.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/metrics.go:125
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
        go.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/queued_retry.go:195
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func1
        go.opentelemetry.io/collector/exporter@v0.81.0/exporterhelper/internal/bounded_memory_queue.go:47
```
