### ISSUE TITLE
k8s.pod.network.io gives data only from eth0

### ISSUE THREAD

**Issue by prabhatsharma** [open-telemetry/opentelemetry-collector-contrib#30196]
### Component(s)

receiver/kubeletstats

## Description

I have been trying to get network io details per namespace. Comparing the metrics of `k8s.pod.network.io` with cadvisor - `container_network_receive_bytes_total` I found that kubeletstatsreceiver does not return data for interfaces other than `eth0` . This provides incomplete picture around networking bandwidth utilized.

## Steps to Reproduce

sum(rate(k8s_pod_network_io{k8s_namespace_name="$k8s_namespace_name", direction="receive"}[5m])) by (interface)

vs

sum(rate(container_network_receive_bytes_total{namespace="$k8s_namespace_name"}[5m])) by (interface)

## Expected Result

I should see data from all interfaces from `k8s_pod_network_io` stream.

## Actual Result

got results only for `eth0`

<img width="1516" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/4242188/d58a27b1-14dc-4f18-9f0e-71d69023bb88">

### Collector version

v0.90.1

## Environment
Amazon EKS

### OpenTelemetry Collector configuration

```yaml
receivers:
  kubeletstats:
      collection_interval: 15s
      auth_type: "serviceAccount"
      endpoint: "https://${env:K8S_NODE_NAME}:10250"
      insecure_skip_verify: true
      extra_metadata_labels:
        - container.id
        - k8s.volume.type
      metric_groups:
        - node
        - pod
        - container
        - volume
      metrics:
        k8s.pod.cpu_limit_utilization:
          enabled: true
        k8s.pod.cpu_request_utilization:
          enabled: true
        k8s.pod.memory_limit_utilization:
          enabled: true
        k8s.pod.memory_request_utilization:
          enabled: true
```
