### ISSUE TITLE
allow to use hash and convert on attribute values (also if retrieved from env var)

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#30192]
### Component(s)

processor/attributes

### Is your feature request related to a problem? Please describe.

1.) I read and env var as attribute value and want to apply the attribute processor hash or convert method on it.
2.) I want to apply hash/convert on value(env var ) and use this new value inside a array element value of an attribute value
 

### Describe the solution you'd like

1.)
```
  attributes:
    actions:
      - key: "env"
        value: "${env:DEVICEID}" 
        action: hash,upsert
```

2.) ${attribute:deviceid} allows to read data from attribute's namespace (even if converted or hased before) and reuse it in any substring of another value
```
  attributes:
    actions:
      - key: "deviceid"
        value: "${env:DEVICEID}" 
        action: hash
      - key: tags
         value: ["deviceid:${attribute:deviceid}", xxx:YYYY]
         action: upsert
```

### Describe alternatives you've considered

None. Open for alternatives ideas

**Comment by crobert-1** [comment]
Hello @cforce, apologies for the delayed response. I'm a bit unsure what your specific request is. I believe step 1 is already possible, so is your request simply to be able to add a `key:value` pair to an attribute whose type is a list? Am I missing something?

**Comment by cforce** [comment]
I want to hash the attribute deviceid and then use the hashed attribute value of deviceid  inline in another attribute tags as array element

```
 attributes:
    actions:
      - key: "deviceid"
        value: "${env:DEVICEID}" 
        action: hash
      - key: tags
         value: ["deviceid:${attribute:deviceid}", xxx:YYYY]
         action: upsert
```
