### ISSUE TITLE
metrics name changes

### ISSUE THREAD

**Issue by rootofevils** [open-telemetry/opentelemetry-collector-contrib#30223]
### Describe the issue you're reporting

I'm using promtheus jmx_exporter to monitor jmx
my otelcol config 
```yaml
extensions:
  health_check:

receivers:
  prometheus/jmx:
    config:
      scrape_configs:
        - job_name: 'jmx_exporter'
          scrape_interval: 15s
          static_configs:
            - targets: ["127.0.0.1:12345"]
              labels:
                metric_type: "jmx"

exporters:
  prometheus/01:
    endpoint: "0.0.0.0:8091"
    const_labels:
      host_name: "r02"

service:
  pipelines:
    metrics/01:
      receivers: [prometheus/jmx]
      exporters: [prometheus/01]

```

When I visit http://127.0.0.1:12345/metrics (jvm_exporter), I can find the metrics named jvm_info
<img width="918" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/32833619/d6de085d-4d7c-4f54-b368-34069a5136f9">

But when I visit http://127.0.0.1:8091/metrics, what I find is the metrics named jvm.
<img width="1126" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/32833619/dd50ec44-0359-42a0-aa5e-f3e8de522f42">

I suspect otelcol processed the data, although I did not configure processors

By the way, the version of my otelcol is
otelcol-contrib version 0.91.0
