### ISSUE TITLE
[receiver/splunkenterprise] Configuration options for querying different enterprise instance types (SH, Indexer, Manager, etc)

### ISSUE THREAD

**Issue by greatestusername** [open-telemetry/opentelemetry-collector-contrib#30254]
### Component(s)

receiver/splunkenterprise

### Is your feature request related to a problem? Please describe.

Some metrics require querying specifically a Search Head or specifically an Indexer (or a cluster manager, etc). Config currently only allows one endpoint that is expected to point at an Indexer and currently produces primarily Indexer metrics.

While possible to setup multiple receiver instances pointing at various instance types that would also require manually enabling/disabling the correct metrics for that instance type.

### Describe the solution you'd like

Have optional configuration fields for different types of splunk enterprise instances that would then enable the metrics for that type of instance when applied. Essentially have optional fields for something like `indexer_endpoint`, `search_head_endpoint`, `cluster_manager_endpoint` and have metrics related to these specific instance types only be enabled when their instance type endpoint is defined.

```
receivers:
    splunkenterprise:
        auth: basicauth/client
        indexer_endpoint: "https://21.1.1.1:8089"
        sh_endpoint: "https://31.1.1.1:8089"
        cluster_manager_endpoint: "https://11.1.1.1:8089"
        timeout: 45s
```

### Describe alternatives you've considered

Possible to have multiple instances of the receiver, one for each type, but this is fiddly with enabling/disabling metrics.

Could allow a list of instances but would still require enabling/disabling metrics based on what instance types would be in the list

### Additional context

Search head and cluster manager specific metrics will be added soon and this work would be a pre-requisite to adding those metrics.
