### ISSUE TITLE
Miss error logs after changes in retry

### ISSUE THREAD

**Issue by monoxono** [open-telemetry/opentelemetry-collector-contrib#30271]
### Component(s)

exporter/prometheusremotewrite

## Description

Before the commit 8715a5ccc3e97214fbb834fdaa164f48d022f4f2(#23842), when prometheusremotewrite failed to send metrics, we can see error logs like this:

```
2024-01-03T09:49:45.963+0100	error	exporterhelper/retry_sender.go:145	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite", "error": "Permanent error: Permanent error: Post \"https://xxxx.com/prom/push\": Service Unavailable", "dropped_items": 16}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/retry_sender.go:145
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
	go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/metrics.go:176
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).start.func1
	go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/queue_sender.go:124
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).Start.func1
	go.opentelemetry.io/collector/exporter@v0.86.0/exporterhelper/internal/bounded_memory_queue.go:52
```

That commit uses "cenkalti/backoff" to retry instead of retry function provided by `exporterhelper` and now when  prometheusremotewrite failed to send metrics, there's no any error log and it's very hard to do troubleshooting.

## Steps to Reproduce
Run the example configuration to reproduce

## Expected Result
We can see errors in logs to understand why metrics sending fails.

## Actual Result
No error log.

### Collector version

8715a5ccc3e97214fbb834fdaa164f48d022f4f2

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus/self:
    config:
      global:
        scrape_interval: 10s
        scrape_timeout: 1s
      scrape_configs:
      - job_name: opentelemetry
        static_configs:
        - targets: [localhost:8888]

exporters:
  prometheusremotewrite:
    endpoint: https://xxx.com/prom/push # some fake url

service:
  pipelines:
    metrics:
      receivers:
      - prometheus/self
      exporters:
      - prometheusremotewrite
```
