### ISSUE TITLE
`receiver/kubeletstats` cannot read /pods with `nodes/proxy` permissions

### ISSUE THREAD

**Issue by Joibel** [open-telemetry/opentelemetry-collector-contrib#30272]
### Component(s)

receiver/kubeletstats

### What happened?

## Description

If I use kubeletstats with a clusterrole with
```
- apiGroups:
    - ""
  resources:
    - nodes/stats
    - nodes/proxy
  verbs:
    - get
```
and with a receiver config of
```
              extra_metadata_labels:                                                                                                                                                                                                           
                - container.id   
```
I get 
```
2024-01-03T11:09:05.622Z    error    scraperhelper/scrapercontroller.go:200    Error scraping metrics    {"kind": "receiver", "name": "receiver_creator/kubeletstats", "data_type": "metrics", "name": "kubeletstats//receiver_creator/kubeletstats{endpoint=\"172.20.24.255:10250\"}/k8s_observer/ip-10-106-248-44.us-east-2.compute.internal-1c3ebbc5-a1b7-494f-b2a0-70a938e1f782", "error": "kubelet request GET https://172.20.24.255:10250/pods failed - \"403 Forbidden\", response: \"{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"forbidden: User \\\\\\\"system:serviceaccount:sample:sample-collector\\\\\\\" cannot get path \\\\\\\"/pods\\\\\\\"\\\",\\\"reason\\\":\\\"Forbidden\\\",\\\"details\\\":{},\\\"code\\\":403}\\n\"", "scraper": "kubeletstats"}    
```

If I add 
```
- nonResourceURLs:
    - /pods
  verbs:
    - get
```
then the logged error goes away (and removing `nodes/proxy` has no effect)

## Expected Result

Successful scraping of `/pods` according to the [readme](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kubeletstatsreceiver#role-based-access-control)

## Actual Result

Failure to read `/pods`

### Collector version

0.91.0

### Environment information

## Environment

Kubernetes 1.28.4 on Arm.


### OpenTelemetry Collector configuration

```yaml
receivers:
      kubeletstats:                                                                                                                                                                                                                                                                                                                                                                      
        auth_type: serviceAccount                                                                                                                                                                                                        
        collection_interval: 10s                                                                                                                                                                                                         
        endpoint: "${env:K8S_NODE_NAME}:10250"                                                                                                                                                                                   
          extra_metadata_labels:                                                                                                                                                                                                           
            - container.id                                                                                                                                                                                                                 
          metric_groups:                                                                                                                                                                                                                   
            - container                                                                                                                                                                                                                    
            - pod                                                                                                                                                                                                                          
            - node                                                                                                                                                                                                                         
                                                                                                                                                                                                                                               
    exporters:                                                                                                                                                                                                                                 
      otlp:                                                                                                                                                                                                                                    
        endpoint: collector:4317                                                                                                                                                                                               
                                                                                                                                                                                                                                               
    service:                                                                                                                                                                                                                                   
      pipelines:                                                                                                                                                                                                                               
        metrics:                                                                                                                                                                                                                               
          receivers: [kubeletstats]                                                                                                                                                            
          exporters: [otlp]                                                                                                                                                                                                   
      telemetry:                                                                                                                                                                                                                               
        logs:                                                                                                                                                                                                                                  
          level: debug                                                                                                                                                                                                                         
        metrics:                                                                                                                                                                                                                               
          address: ":8888"
```


### Log output

```shell
2024-01-03T11:09:05.622Z    error    scraperhelper/scrapercontroller.go:200    Error scraping metrics    {"kind": "receiver", "name": "receiver_creator/kubeletstats", "data_type": "metrics", "name": "kubeletstats//receiver_creator/kubeletstats{endpoint=\"172.20.24.255:10250\"}/k8s_observer/ip-10-106-248-44.us-east-2.compute.internal-1c3ebbc5-a1b7-494f-b2a0-70a938e1f782", "error": "kubelet request GET https://172.20.24.255:10250/pods failed - \"403 Forbidden\", response: \"{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"forbidden: User \\\\\\\"system:serviceaccount:sample:sample-collector\\\\\\\" cannot get path \\\\\\\"/pods\\\\\\\"\\\",\\\"reason\\\":\\\"Forbidden\\\",\\\"details\\\":{},\\\"code\\\":403}\\n\"", "scraper": "kubeletstats"}
```


### Additional context

Removing `nodes/stats` from the cluster role gives a similar error from the path `/stats/summary` so that part of the cluster role is working as expected.
