### ISSUE TITLE
[vcenterreceiver] Add support for additional VM CPU stats

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30285]
### Component(s)

receiver/vcenter

### Is your feature request related to a problem? Please describe.

The vcenter receiver doesn't provide CPU metrics for VMs.

### Describe the solution you'd like

I would like to add additional CPU metrics.

**Comment by crobert-1** [comment]
Do you have a specific list of metrics you're looking for here?

Here's the list of CPU metrics I found in `metadata.yaml` that are already provided, so I'm wondering what's missing:
```
  vcenter.cluster.cpu.limit:
  vcenter.cluster.cpu.effective:

  vcenter.host.cpu.utilization:
  vcenter.host.cpu.usage:

  vcenter.resource_pool.cpu.usage:
  vcenter.resource_pool.cpu.shares:

  vcenter.vm.cpu.utilization:
  vcenter.vm.cpu.usage:
```
