### ISSUE TITLE
Feature to split tailsampling into two phases pre and post sample

### ISSUE THREAD

**Issue by tiithansen** [open-telemetry/opentelemetry-collector-contrib#30319]
### Component(s)

connector/spanmetrics, processor/tailsampling

### Is your feature request related to a problem? Please describe.

When generating spanmetrics with exemplars its not possible to specify which traces are going to be stored by tailsampling processor and which not. Currently all traces passing through spanmetrics connector will have exemplars added to them even if traces are not actually stored. This causes frustration for developers trying to debug spikes on graphs.

### Describe the solution you'd like

Split tailsampling into two phases:
* Presample phase runs policies to detect which traces should be stored. If trace should be stored new attribute will be attached `tail_sampling.sample: true`. Presample phase will pass all traces to next stages
* Postsample phase drops all traces which do not have `tail_sampling.sample: true` set.

Between these two stages it is possible to run spanmetrics connector which would check `tail_sampling.sample` attribute to determine if it should export exemplars or not.

Sample pipeline:

```yaml
processors:
  tail_sampling/presample:
    processor_mode: presample
  tail_sampling/postsample:
    processor_mode: postsample

service:
      telemetry:
        logs:
          encoding: json
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - ...
          exporters:
            - loadbalancing
        traces/after_lb:
          receivers:
            - otlp/lb
          processors:
            - tail_sampling/presample
          exporters:
            - forward
            - spanmetrics
        traces/sample:
          receivers:
            - forward
          processors:
            - tail_sampling/postsample
            - batch
          exporters:
            - otlphttp
        metrics:
          receivers:
            - spanmetrics
          processors:
            - attributes/metrics
            - batch/metrics
          exporters:
            - otlphttp/metrics
        logs: null
```
