### ISSUE TITLE
Count connector improperly handles non-string attributes

### ISSUE THREAD

**Issue by j-kap-t** [open-telemetry/opentelemetry-collector-contrib#30314]
### Component(s)

connector/count

## Description
When specifying attributes the connector will lose the client provided value if it is not a string, such as for `http.status_code`. [The connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/countconnector/counter.go#L44) calls [`.Str()`](https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/pcommon/value.go#L203) without checking the type, which results in setting the value to an empty string if the original value is not a string.

## Steps to Reproduce
Count an attribute sent by clients as a non-string value:
```yaml
connectors:
  count:
    spans:
      http.status.codes:
        attributes:
          - key: http.status_code
```

## Expected Result
The connector emits metrics with the counts split by `http.status_code`

## Actual Result
The connector emits metrics with `http.status_code` set to an empty string.

### Collector version

v0.91.0
