### ISSUE TITLE
[receiver/k8scluster] adding more Node resource attributes

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#30342]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

I would like to use k8s cluster receiver to get more information about Node, such as Container Runtime Version, OS version and OS description.

### Describe the solution you'd like

I propose to add these resource attributes added to Node metrics, which should be disabled by default:

```
  k8s.container_runtime.version:
    description: The version of container runtime used by Kubernetes Node.
    type: string
    enabled: false

  os.version:
    description: The version of operating system used by Kubernetes Node.
    type: string
    enabled: false

  os.description:
    description: The os description used by Kubernetes Node.
    type: string
    enabled: false
```

### Additional context

I did a POC and this is how it looks rendered, when using kind cluster:
```
k8s_node_allocatable_cpu{k8s_container_runtime_version="containerd://1.6.9", k8s_kubelet_version="v1.25.3", k8s_node_name="kind-control-plane", os_description="Ubuntu 22.04.1 LTS", os_version="6.6.8-arch1-1"}
```

Which seems to fit the Otel Semantic conventions in https://opentelemetry.io/docs/specs/semconv/resource/os/
