### ISSUE TITLE
Error reading Windows processes when filtering is applied

### ISSUE THREAD

**Issue by carlosli888** [open-telemetry/opentelemetry-collector-contrib#30359]
**Describe the bug**
Errors are encountered when collector tries to scrape metrics if a filter is configured for processes in Windows.

**Steps to reproduce**
1.  Use the following configuration for the `hostmetrics` receiver:
```yaml
  hostmetrics:
    scrapers:
      process:
        include:
          names: "Notepad.exe"
          match_type: strict
```
2. Start the open telemetry collector using admin account.

**What did you expect to see?**
No errors or warning.

**What did you see instead?**
2024-01-08T16:07:23.951-0800    error   scraperhelper/scrapercontroller.go:200  Error scraping metrics  {"kind": "receiver", "name": "hostmetrics", "data_type": "metrics", "error": "error reading process executable for pid 0: The parameter is incorrect.; error reading process name for pid 0: executable path is empty; error reading process executable for pid 4: A device attached to the system is not functioning.; error reading process name for pid 4: executable path is empty; error reading process executable for pid 72: A device attached to the system is not functioning.; error reading process name for pid 72: executable path is empty; error reading process executable for pid 132: A device attached to the system is not functioning.; error reading process name for pid 132: executable path is empty; error reading process executable for pid 4400: A device attached to the system is not functioning.; error reading process name for pid 4400: executable path is empty; error reading process executable for pid 13488: A device attached to the system is not functioning.; error reading process name for pid 13488: executable path is empty", "scraper": "process"}
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scrapercontroller.go:200
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scrapercontroller.go:172

**What version did you use?**
otelcol-contrib version 0.91.0

**What config did you use?**
```yaml
receivers:
  hostmetrics:
    scrapers:
      process:
        include:
          names: "Notepad.exe"
          match_type: strict
...
```

**Environment**
OS: Windows 10 Pro

**Additional context**
Error does not exist if I remove the `include` section (i.e., do not filter for any process) of the `process` scraper.
