### ISSUE TITLE
Refactor unit test execution so it does not check for a Go version

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#30358]
### Describe the issue you're reporting

We had an issue with the last Go upgrade where we ended up not running unit tests for Go 1.21 because a condition in the github action checked for:

```yaml
 - name: Run Unit Tests
   if: startsWith( matrix.go-version, '1.19' )
   run: make gotest GROUP=${{ matrix.group }}
```

and the condition was not updated.  Since github counts skipped steps as successful, the CI showed Go 1.21 tests as passing when in reality they weren't running.

To avoid this issue in the future, it would be nice if the unit test job did not need to differentiate between regular test execution and text-with-coverage execution using the Go version and instead differentiated on something else - something that wouldn't be affected by a Go version upgrade.

Related to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30324
