### ISSUE TITLE
New component: osquery

### ISSUE THREAD

**Issue by smithclay** [open-telemetry/opentelemetry-collector-contrib#30375]
### The purpose and use-cases of the new component

[osquery](https://osquery.io/) is a popular [open-source Linux Foundation project](https://github.com/osquery/osquery) that allows system administrators to query information about their systems using a SQL-like language.

As a collector receiver for logs, it allows users to extract detailed information about their Linux, macOS, or Windows systems like running processes, certificates, or disks on a predefined schedule. This receiver is particularly helpful for using the collector for security and compliance use-cases. 

### Example configuration for the component

```
osquery:
  collection_internal: 10s
  extensions_socket: /var/osquery/osquery.em
  queries:
    - "select * from certificates"
    - "select * from block_devices"
 ```

### Telemetry data types supported

logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@smithclay

### Sponsor (optional)

@codeboten
