### ISSUE TITLE
opentelemetry-collector processors/routing use custom http header can not route to right exporters

### ISSUE THREAD

**Issue by burning954320420** [open-telemetry/opentelemetry-collector-contrib#30393]
### Component(s)

processor/routing

### Describe the issue you're reporting

I want fluent-bit collect logs and push to opentelemetry-collector, then the opentelemetry-collector can get fluent-bit output custom http header, finally the opentelemetry-conllector based on fluent-bit output http header to different exporter. So I try to use processors/routing.

But the logs always output to default exporter, never output to desired exporter.

My fluentbit config is

```
[INPUT]
    Name        tail
    Path        /tmp/test.log

[OUTPUT]
    Name                 opentelemetry
    Match                *
    Host                 localhost
    Port                 4318
    Logs_uri             /v1/logs
    Header               X-Custom-Logs-Header custom
```

My opentelemetry-collector config is
```
receivers:
  otlp:
    protocols:
      http:

exporters:
  file/default:
    path: /data/default.log
  file/custom:
    path: /data/custom.log

processors:
  routing:
    attribute_source: context
    from_attribute: X-Custom-Logs-Header
    default_exporters: [file/default]
    table:
    - value: custom
      exporters:
      - file/custom

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [routing]
      exporters: [file/default, file/custom]
```

I expect fluentbit input the /tmp/test.log and opentelemetry-conllector written to /data/custom.log, but it written to /data/default.log.
I used tcpdump command to get opentelemetry-conllector packet, and X-Custom-Logs-Header header really in the opentelemetry-conllector http port when fluentbit post to opentelemetry-conllector.

**Comment by crobert-1** [comment]
Hello @burning954320420, thanks for filing this issue! Usually when all of your data is going to the default exporter it means that your incoming data is formatted differently than expected when being compared to the `table.value` configuration option.

Can you share a few example log messages? Preferably using the [`debug` exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter).

Here's a sample config that would display what I'm requesting:
```
receivers:
  otlp:
    protocols:
      http:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug]
```

**Comment by burning954320420** [comment]
@crobert-1 Thank you for your help. I config exporters.debug, and the opentelemetry-collector log like:
```
2024-01-11T01:59:54.106Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "debug", "resource logs": 1, "log records": 1}
2024-01-11T01:59:54.107Z        info    ResourceLog #0
Resource SchemaURL: 
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope  
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2024-01-11 01:59:53.989822498 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Map({"log":"a"})
Trace ID: 
Span ID: 
Flags: 0
        {"kind": "exporter", "data_type": "logs", "name": "debug"}
```
But I feel that it may not be possible to see HTTP header information in the exporters.

And I capture the packet in opentelemetry-collector http 4318 port, the packet like that:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/11408203/46207663-49d6-4b28-9f46-1584e7e16e89)
So I think opentelemetry-collector get the custom header, but for some reason processor/routing not get the header or routing processing failed.

**Comment by crobert-1** [comment]
It looks like you need to add `include_metadata: true` as an option to your receiver, this way the [context will be preserved](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor#limitations) in your logs. More information on this configuration option can be found [here.](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/README.md#server-configuration)

Here's what your receiver configuration should look like:
```
receivers:
  otlp:
    protocols:
      http:
        include_metadata: true
```
