### ISSUE TITLE
`k8sattributes` Extract labels to a Map

### ISSUE THREAD

**Issue by omegion** [open-telemetry/opentelemetry-collector-contrib#30474]
### Component(s)

processor/k8sattributes

### Describe the issue you're reporting

Hi,

I am trying to extract Kubernetes labels to a map so that I can display them as nested JSON in the log body. However, they are all extracted as flat parameters. Any way to convert them to a Map?

My config:
```
      k8sattributes:
        extract:
          labels:
            - tag_name: k8s.labels.$$1
              key_regex: (.*)
              from: pod
 ```
 
 This will extract Kubernetes pod labels to:
 ```
      -> k8s.labels.app: Str(kindnet)
     -> k8s.labels.controller-revision-hash: Str(68bf578d5f)
     -> k8s.labels.k8s-app: Str(kindnet)
     -> k8s.labels.pod-template-generation: Str(1)
     -> k8s.labels.tier: Str(node)
```

However, I would like to put each label in into `Map({"labels":{}})` with their keys, is this possible?

**Comment by omegion** [comment]
help-wanted

**Comment by TylerHelmuth** [comment]
This isn't possible with the k8sattributesprocessor (and I don't think we'd add it), but you can use the transformprocessor to achieve this.  After the k8sattributes processor has extracted the labels:

```yaml
transform:
  error_mode: ignore
  log_statements:
    - context: resource
      statements:
        - set(attributes["labels"], attributes)
        # you made need to remove unwanted keys
        - delete_key(attributes["labels"], "service.name")
        - ...
    - context: log
      statements:
        - set(body, attributes["labels") 
```

I've not tests that but its the general idea.
