### ISSUE TITLE
500 error when scraping metrics from otel-collector pod when loadbalancing exporter is used

### ISSUE THREAD

**Issue by juissi-t** [open-telemetry/opentelemetry-collector-contrib#30477]
### Component(s)

exporter/loadbalancing

## Description

I enabled loadbalancing exporter on our collector pods. After a while (~1 hour), Prometheus fails to scrape metrics from the pods which have the exporter configured. Below is an error message from one pod.

```
* Connected to localhost (::1) port 8888
> GET /metrics HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/8.2.1
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 12 Jan 2024 13:41:47 GMT
< Content-Length: 401
< 
An error has occurred while serving metrics:

collected metric "otelcol_exporter_queue_size" { label:{name:"exporter"  value:"loadbalancing"}  label:{name:"service_instance_id"  value:"f3215806-0275-446f-acdc-32c306d25337"}  label:{name:"service_name"  value:"otelcol-contrib"}  label:{name:"service_version"  value:"0.92.0"}  gauge:{value:0}} was collected before with the same name and label values
```

## Steps to Reproduce

- Enable loadbalancing exporter.

## Expected Result

- Prometheus metrics work correctly

## Actual Result

- Prometheus metrics fail after a while

### Collector version

0.92.0

## Environment
OS: EKS 1.26 Bottlerocket

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug: {}
  loadbalancing:
    protocol:
      otlp:
        sending_queue:
          queue_size: 10000
        tls:
          insecure: true
    resolver:
      k8s:
        service: opentelemetry-collector-sts.monitoring
  logging: {}
extensions:
  health_check: {}
processors:
  batch: {}
  k8sattributes:
    extract:
      labels:
      - from: pod
        key_regex: (.*)
        tag_name: $$1
      metadata:
      - k8s.namespace.name
      - k8s.deployment.name
      - k8s.statefulset.name
      - k8s.daemonset.name
      - k8s.cronjob.name
      - k8s.job.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.pod.start_time
    filter:
      node_from_env_var: K8S_NODE_NAME
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
    - action: upsert
      key: cluster
      value: dev
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - ${env:MY_POD_IP}:8888
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
  - health_check
  pipelines:
    metrics:
      exporters:
      - loadbalancing
      processors:
      - k8sattributes
      - memory_limiter
      - resource
      - batch
      receivers:
      - otlp
    traces:
      exporters:
      - loadbalancing
      processors:
      - k8sattributes
      - memory_limiter
      - resource
      - batch
      receivers:
      - otlp
      - jaeger
  telemetry:
    metrics:
      address: 0.0.0.0:8888
```

**Comment by jpkrohling** [comment]
I think this is more likely to be something with the Prometheus receiver/exporter than with the load balancing, given that this seems to be about the component's own metrics, rather than the load balanced telemetry.

**Comment by swar8080** [comment]
Getting the same error with this loadbalancer configuration

```
    exporters:
      loadbalancing:
        protocol:
          otlp:
            sending_queue:
              queue_size: 10000
            tls:
              insecure: true
        resolver:
          k8s:
            service: abc-collector-headless.observability

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [otlp/forwarder, debug]
        traces:
          receivers: [otlp]
          exporters: [loadbalancing, debug]
```
