### ISSUE TITLE
Exporter Feature: OpenSearch Metrics

### ISSUE THREAD

**Issue by edmondsiu0** [open-telemetry/opentelemetry-collector-contrib#30556]
### Component(s)

exporter/opensearch

### Is your feature request related to a problem? Please describe.

Similar to issue #23611, this Issue is to suggest OpenSearch exporter to convert Otel metric data directly into OpenSearch. 

This will remove the need of using dataprepper `otel_metrics` processor to reprocess the information before being sent into OpenSearch. 

### Describe the solution you'd like

Similar to the linked issue, but specific to metrics, such as:

```
exporters:
  opensearch/metrics:
    http:
      endpoint: https://opensearch.example.com:9200
    index: my-metrics-index

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch/metrics]
```

### Describe alternatives you've considered

Dataprepper `otel_metrics` processor is able to perform this task but it is an external component. It would be good if this can be transformed directly within Otel.
