### ISSUE TITLE
[attributesprocessor] The `resource` part of metrics include filtering config doesn't work

### ISSUE THREAD

**Issue by chenlujjj** [open-telemetry/opentelemetry-collector-contrib#30642]
### Component(s)

processor/attributes

## Description

As you can see in the attached collector config file, I tried to use the attributes processor to add labels for the metric `node_disk_write_time_seconds_total` only when `device=disk0`

NOTE: this is just a minimum example to reproduce the issue.

## Actual Result

All the metrics `node_disk_write_time_seconds_total` even with `device!=disk0` were updated as well.

### Collector version

0.79.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: "node_exporter"
            scrape_interval: 10s
            static_configs:
              - targets: ['0.0.0.0:9100']

exporters:
    file/metrics:
      path: /tmp/metrics

processors:
    batch:
    attributes/1:
      include:
        resources:
          - key: device
            value: disk0
        metric_names: [node_disk_write_time_seconds_total]
        match_type: strict
      actions:
        - key: name
          action: upsert
          value: zhangsan

extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679

service:
    extensions: [pprof, zpages, health_check]
    telemetry:
      metrics:
        address: ":8888"
    pipelines:
      metrics:
        receivers: [prometheus]
        processors: [batch, attributes/1]
        exporters: [logging, file/metrics]
```

### Additional context

In the source code:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.79.0/internal/filter/filtermetric/filtermetric.go#L49
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.79.0/internal/filter/filtermetric/name_matcher.go#L18

The `ResourceAttributes` of `MatchProperties` doesn't take effect at all. Only the metric names are used to filter.

**Comment by chenlujjj** [comment]
The readme doc says: "For metrics, one of metric_names or resources must be specified with a valid non-empty value for a valid configuration." So I think the `resources` can be used to filter as well.

**Comment by chenlujjj** [comment]
And when I just specified the `resources` like:
```
attributes/1:
      include:
        resources:
          - key: device
            value: disk0
     actions:
        - key: name
          action: upsert
          value: zhangsan
```
It will update labels for all metrics ... 
The cause is at this line: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.79.0/internal/filter/filtermetric/filtermetric.go#L47

**Comment by crobert-1** [comment]
To clarify your minimum reproducible config file, you're saying that with this config all metrics named `node_disk_write_time_seconds_total` are coming through, even if their `device` resource isn't `disk0`, is that correct?

If that's the case, could you post some example metrics from your logging output?

**Comment by chenlujjj** [comment]
hi, @crobert-1, please see the attached file for the full list of node exporter metrics.
[node_metrics.json](https://github.com/open-telemetry/opentelemetry-collector-contrib/files/13971366/node_metrics.json)

<img width="747" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17081528/a4ff2e3d-7c31-4e2e-9bc2-25690a082c55">

**Comment by crobert-1** [comment]
Okay, I'm seeing two main issues here.

1. The filter expression [only accounts for the metric name](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/03f9c3a7a8fef749e8a3916b99c20b95b24962eb/internal/filter/filtermetric/name_matcher.go#L19) from what I'm seeing, it drops the resource attribute filter from the check. This is what is causing part of your issue. Adding a reference to `NewResourceSkipExprBridge` to properly account for resource attribute filters would resolve this.
2. The attributes you're looking at are datapoint attributes, not resource attributes. However, this would still fail due to the bug referenced in my first point, attributes aren't properly accounted for either from what I can tell.

There is another more supported way to do this though, using the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor). If you use the [datapoint context](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottldatapoint) you can use the `set` function to add a key to your attributes map [when specific conditions are met](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/LANGUAGE.md#boolean-expressions), as you're attempting to do here.

**Comment by chenlujjj** [comment]
Hi @crobert-1 , thanks for your reply. 
If I understand correctly, the `device` filter specified in the config above will not work even if the resource attribute filter is added to the attributes processor properly, because the `device` is a datapoint attribute, not resource attribute, is that right?

**Comment by chenlujjj** [comment]
And from the [code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/attributes_metric.go#L73)  here, the attributesprocessor processes the datapoint attribute, not resource attribute, too.

I'll give a try to transform processor, thanks.

**Comment by crobert-1** [comment]
> If I understand correctly, the device filter specified in the config above will not work even if the resource attribute filter is added to the attributes processor properly, because the device is a datapoint attribute, not resource attribute, is that right?

That's correct, even if this bug is fixed the filter you've shared won't work with your data.

> And from the [code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/attributes_metric.go#L73) here, the attributesprocessor processes the datapoint attribute, not resource attribute, too.

Yes, the attributes processor only supports operations on datapoint attributes for metrics, it does not support operations on resource attributes.

**Comment by chenlujjj** [comment]
Thanks for your confirmation :)

**Comment by TylerHelmuth** [comment]
In the transformprocessor it would look like

```yaml
transform:
  error_mode: ignore
  metric_statements:
    - context: datapoint
      statements:
        - set(name, "zhangsan") where metric.name == "node_disk_write_time_seconds_total" and resource.attributes["device"] == "disk0"
```

**Comment by TylerHelmuth** [comment]
@chenlujjj I am going to close this issue for now since that transformprocessor config solves the use case you wanted.  Please ping me if it doesnt work and I'll reopen.

**Comment by chenlujjj** [comment]
Thank you @TylerHelmuth 
After trial, I found the right config of transform processor for this case is:
```
transform:
      error_mode: ignore
      metric_statements:
        - context: datapoint
          statements:
            - set(attributes["name"], "zhangsan") where metric.name == "node_disk_write_time_seconds_total" and attributes["device"] == "disk0"
```

**Comment by TylerHelmuth** [comment]
You're right, good correction!

**Comment by tjuchniewicz** [comment]
@TylerHelmuth we are interested to fix this issue. Our requirement is to conditionally add attribute (for all signals) for some services only:
```yaml
 attributes/oidc:
    actions:
     - key: oidc.subject
       from_context: auth.subject
       action: upsert
      default_value: "oidc.subject obfuscated according to the configuration"
    exclude:
      match_type: strict
      resources:
        - key: service.name
          value: excluded-service
```
