### ISSUE TITLE
Routing statements are not parsed properly if statement strings match

### ISSUE THREAD

**Issue by kristofgyuracz** [open-telemetry/opentelemetry-collector-contrib#30663]
### Component(s)

connector/routing

## Description
If two routing table entries have the exact same routing strings(, but different target pipelines), messages will be only forwarded to one of the target pipelines.
The reason is that it the route map's key is the routing statement string, and during parsing it is overwritten by the second entry.
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.92.0/connector/routingconnector/router.go#L133

## Steps to Reproduce
```
    connectors:
        routing/subscriptions:
            default_pipelines: []
            table:
                - statement: route()
                  pipelines: [logs/another-subscription-sample]
                - statement: route()
                  pipelines: [logs/subscription-sample]
```
## Expected Result
Messages are sent to both pipelines.
## Actual Result
Messages are sent to only one of the pipelines.

### Collector version

0.92.0

## Environment
Kubernetes distro: KinD v1.27.3
Opentelemetry-operator

### OpenTelemetry Collector configuration

```yaml
receivers:
        filelog/kubernetes:
            exclude:
                - /var/log/pods/*/otc-container/*.log
            include:
                - /var/log/pods/*/*/*.log
            include_file_name: false
            include_file_path: true
            operators:
                - id: get-format
                  routes:
                    - expr: body matches "^\\{"
                      output: parser-docker
                    - expr: body matches "^[^ Z]+ "
                      output: parser-crio
                    - expr: body matches "^[^ Z]+Z"
                      output: parser-containerd
                  type: router
                - id: parser-crio
                  output: extract_metadata_from_filepath
                  regex: '''^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'''
                  timestamp:
                    layout: 2006-01-02T15:04:05.999999999Z07:00
                    layout_type: gotime
                    parse_from: attributes.time
                  type: regex_parser
                - id: parser-containerd
                  output: extract_metadata_from_filepath
                  regex: '''^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$'''
                  timestamp:
                    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
                    parse_from: attributes.time
                  type: regex_parser
                - id: parser-docker
                  output: extract_metadata_from_filepath
                  timestamp:
                    layout: '%Y-%m-%dT%H:%M:%S.%LZ'
                    parse_from: attributes.time
                  type: json_parser
                - cache:
                    size: 128
                  id: extract_metadata_from_filepath
                  parse_from: attributes["log.file.path"]
                  regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9-]+)\/(?P<container_name>[^\/]+)\/(?P<restart_count>\d+)\.log$
                  type: regex_parser
                - from: attributes.log
                  to: body
                  type: move
                - from: attributes.stream
                  to: attributes["log.iostream"]
                  type: move
                - from: attributes.container_name
                  to: resource["k8s.container.name"]
                  type: move
                - from: attributes.namespace
                  to: resource["k8s.namespace.name"]
                  type: move
                - from: attributes.pod_name
                  to: resource["k8s.pod.name"]
                  type: move
                - from: attributes.restart_count
                  to: resource["k8s.container.restart_count"]
                  type: move
                - from: attributes.uid
                  to: resource["k8s.pod.uid"]
                  type: move
            start_at: end
    exporters:
        otlp/collector_otlp-test-output:
            endpoint: receiver-collector.example-tenant-ns.svc.cluster.local:4317
            tls:
                insecure: true
        otlp/collector_otlp-test-output-2:
            endpoint: receiver-collector.example-tenant-ns.svc.cluster.local:4317
            tls:
                insecure: true
    processors:
        attributes/subscription_another-subscription-sample:
            actions:
                - action: insert
                  key: subscription_name
                  value: another-subscription-sample
        attributes/subscription_subscription-sample:
            actions:
                - action: insert
                  key: subscription_name
                  value: subscription-sample
        attributes/tenant_example-tenant:
            actions:
                - action: insert
                  key: tenant_name
                  value: example-tenant
        k8sattributes:
            auth_type: serviceAccount
            extract:
                metadata:
                    - k8s.pod.name
                    - k8s.pod.uid
                    - k8s.deployment.name
                    - k8s.namespace.name
                    - k8s.node.name
                    - k8s.pod.start_time
            passthrough: false
            pod_association:
                - sources:
                    - name: k8s.namespace.name
                      from: resource_attribute
                    - name: k8s.pod.name
                      from: resource_attribute
    connectors:
        routing/tenant_example-tenant_subscriptions:
            default_pipelines: []
            table:
                - statement: route()
                  pipelines: [logs/tenant_example-tenant_subscription_another-subscription-sample]
                - statement: route()
                  pipelines: [logs/tenant_example-tenant_subscription_subscription-sample]
        routing/tenants:
            default_pipelines: []
            table:
                - statement: route() where IsMatch(attributes["k8s.namespace.name"], "example-tenant-ns")
                  pipelines: [logs/tenant_example-tenant]
    service:
        pipelines:
            logs/all:
                receivers: [filelog/kubernetes]
                processors: [k8sattributes]
                exporters: [routing/tenants]
            logs/tenant_example-tenant:
                receivers: [routing/tenants]
                processors: [attributes/tenant_example-tenant]
                exporters: [routing/tenant_example-tenant_subscriptions]
            logs/tenant_example-tenant_subscription_another-subscription-sample:
                receivers: [routing/tenant_example-tenant_subscriptions]
                processors: [attributes/subscription_another-subscription-sample]
                exporters: [otlp/collector_otlp-test-output-2]
            logs/tenant_example-tenant_subscription_subscription-sample:
                receivers: [routing/tenant_example-tenant_subscriptions]
                processors: [attributes/subscription_subscription-sample]
                exporters: [otlp/collector_otlp-test-output]
```

**Comment by kristofgyuracz** [comment]
Added a draft pull requests that would fix this issue (according to unit tests). In the meantime I'll build a collector image from this state and test it manually.

**Comment by crobert-1** [comment]
Is there any reason the configuration you're sharing wouldn't be the following?

```
    connectors:
        routing/subscriptions:
            default_pipelines: []
            table:
                - statement: route()
                  pipelines: [logs/subscription-sample, logs/another-subscription-sample]
```

The connector very clearly supports routing the same statement to multiple pipelines. In the case of the config you've shared I'd actually prefer failing the collector on startup with a descriptive message telling the user that multiple identical routing statements should be consolidated into one. This may break existing configurations that currently run, but the existing configurations are not doing what users want, so I don't believe this is **actually** a negative impact.

The alternative would be internally resolving the mismatched logic in the collector as you've shared, but I worry about long term complexity of this going forward. In general, having users supply bad configs and then the collector fixing it without letting the user know can lead to ambiguous behavior and complex code. I'd rather just keep it simple and clearly communicate to users when something like this is happening.

I'll defer to code owners though, I might be missing something here.
