### ISSUE TITLE
Zipkin Exporter does not include the headers from client settings in request

### ISSUE THREAD

**Issue by EOjeah** [open-telemetry/opentelemetry-collector-contrib#30679]
### Component(s)

exporter/zipkin

## Description

According to [HTTP Configuration Settings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/README.md#client-configuration) Exporters can leverage client configuration. 

Zipkin Exporter specifies you can leverage these advanced settings from [README.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/zipkinexporter#advanced-configuration), however it does not properly update the `headers` when you put that in the configuration. 

## Steps to Reproduce
- Set headers in the zipkin exporter configuration
```yaml
exporters:
  zipkin:
    endpoint: "https://<zipkin-url>/api/v2/spans"
    format: proto
    headers:
      "any-key": "value"
```

## Actual Result
Print your `req` struct from [zipkin.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.92.0/exporter/zipkinexporter/zipkin.go#L81) with fmt.Println(req)
- Result will print a Go struct and i have included the mapping from [struct](https://pkg.go.dev/net/http#Request) so result looks like:
```
&{
  Method      POST
  URL         https://<zipkin-url>/api/v2/spans
  Proto       HTTP/1.1
  ProtoMajor  1 
  ProtoMinor  1 
  Header      map[Content-Type:[application/x-protobuf]]
...
}
```
## Expected Result
```diff
&{
  Method      POST
  URL         https://<zipkin-url>/api/v2/spans
  Proto       HTTP/1.1
  ProtoMajor  1 
  ProtoMinor  1 
- Header      map[Content-Type:[application/x-protobuf]]
+ Header      map[Content-Type:[application/x-protobuf] Test:[value]]
...
}
```

### Collector version

v0.92.0

## Environment
OS: Ubuntu 22.04.3 LTS 
Compiler: go1.21.5 linux/amd64

### OpenTelemetry Collector configuration

```yaml
receivers:
  zipkin:

exporters:
  zipkin:
    endpoint: "https://<zipkin>/api/v2/spans"
    format: proto
    headers:
      Test: "value"

service:
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [zipkin]
```
