### ISSUE TITLE
prometheusexporter's "metric_expiration" parameter is ignored when used with spanmetrics connector

### ISSUE THREAD

**Issue by tqi-raurora** [open-telemetry/opentelemetry-collector-contrib#30688]
### Component(s)

exporter/prometheus

## Description

metric_expiration setting for prometheus exporter seems to be ignored

Using otelcol-contrib version 0.92.0 with spanmetrics connector, and the prometheus exporter with setting metric_expiration: 10m

After 10 minutes have passed metrics that where not updated should disappear from the prometheus metric scrapping endpoint.
However, metrics are not disappearing. To test this I instrumented a test application, sent some telemetry, then killed the application. The metrics are never erased

![Screenshot from 2024-01-19 19-35-56](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/78105687/d1714c46-983a-451e-9962-93628f70ab46)

after 20 minutes:

![Screenshot from 2024-01-19 19-55-17](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/78105687/3082bf80-57f1-430a-808c-1eb94b86f64c)

## Steps to Reproduce

- Start the collector with following configuration:

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9130"
    metric_expiration: 10m
    add_metric_suffixes: false

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [125ms, 500ms, 2000ms, 8000ms]
    dimensions:
      - name: http.method
        default: GET
      - name: http.route
      - name: http.scheme
      - name: http.status_code
      - name: net.host.name
      - name: net.host.port
      - name: net.protocol.name
      - name: net.protocol.version
      - name: net.sock.host.addr
      - name: net.sock.peer.addr

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [spanmetrics]
    metrics:
      receivers: [spanmetrics]
      processors: [batch]
      exporters: [prometheus]
```

- Send some traces
- Stop sending any telemetry data
- Check the prometheus exporter endpoint: `curl -s localhost:9130/metrics | grep duration_count | grep SPAN_KIND_SERVER`

## Expected Result

After 10 minutes of metrics not being updated, metric_expiration should kick in, and metrics should be removed from prometheus endpoint

## Actual Result

Metrics are never removed from prometheus endpoint

### Collector version

0.92.0

## Environment
Ubuntu 22.04.2 LTS

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9130"
    metric_expiration: 10m
    add_metric_suffixes: false

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [125ms, 500ms, 2000ms, 8000ms]
    dimensions:
      - name: http.method
        default: GET
      - name: http.route
      - name: http.scheme
      - name: http.status_code
      - name: net.host.name
      - name: net.host.port
      - name: net.protocol.name
      - name: net.protocol.version
      - name: net.sock.host.addr
      - name: net.sock.peer.addr

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [spanmetrics]
    metrics:
      receivers: [spanmetrics]
      processors: [batch]
      exporters: [prometheus]
```
