### ISSUE TITLE
Issue with Datadog Exporter Configuration in OpenTelemetry

### ISSUE THREAD

**Issue by ezopstheta** [open-telemetry/opentelemetry-collector-contrib#30686]
### Component(s)

exporter/datadog

### Describe the issue you're reporting

After carefully reviewing and understanding the documentation, I proceeded to download and configure OpenTelemetry on the host machine running the Datadog agent. Following the download, I configured the .yaml file and executed the command 'otelcol --config=my_configuration_file.yaml.' Unfortunately, I encountered the following error after multiple attempts:

`error decoding 'exporters': unknown type: "datadog" for id: "datadog" (valid values: [prometheus debug otlp file kafka opencensus prometheusremotewrite zipkin logging otlphttp])`

I am currently debugging this issue to resolve it promptly.

YAML Configuration:

```
receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"
      grpc:
        endpoint: "localhost:4317"

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s

exporters:
  datadogexporter:
    api:
      site: datadoghq.com
      key: my_key

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
```
Note: The objective is to configure OpenTelemetry with Datadog to act as an intermediary for sending logs from Hasura Cloud for visualization in Datadog. The priority is to address the configuration issue with the Datadog exporter.
