### ISSUE TITLE
Timestamp defaults to 1/1 when date is not included

### ISSUE THREAD

**Issue by matt14483** [open-telemetry/opentelemetry-collector-contrib#30683]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

When parsing a timestamp that does not include the month or date, the default value becomes Jan 1, rather than the current date.  For example, a timestamp with this header
`[14:37:21] Info: `...
Gets parsed like this:
```
     - type: regex_parser
        regex: ^\[(?P<timestamp_field>\d{1,2}\:\d{2}\:\d{2})\]
        timestamp:
          layout: "%H:%M:%S"
          parse_from: attributes.timestamp_field
```
It parsed the timestamp as 1/1/24 at 14:37:21.
