### ISSUE TITLE
[loadbalancingexporter] using the loadbalancingexporter k8s resolved breaks the internal metrics

### ISSUE THREAD

**Issue by grzn** [open-telemetry/opentelemetry-collector-contrib#30697]
### Component(s)

exporter/loadbalancing

## Description
metrics endpoint fails 

## Steps to Reproduce
Enable the load balacing exporter
```  exporters:
    loadbalancing/traces:
      resolver:
        k8s:
          service: opentelemetry-collector.default

## Expected Result

`curl http://<podip>:9090/metrics` to succeed

## Actual Result
```
curl http;curl http;wiz@utils-ops-5db4f67695-mtupg:/$ curl http://10.0.46.15:9090/metrics
An error has occurred while serving metrics:

collected metric "otelcol_exporter_queue_size" { label:{name:"exporter"  value:"loadbalancing/traces"}  label:{name:"service_instance_id"  value:"16abe78b-1a05-4f33-909c-cc9e9cb4b73e
```

### Collector version

0.92.0

### Environment information

## Environment
Docker image `otel/opentelemetry-collector-contrib:0.92.0`

### OpenTelemetry Collector configuration

```yaml
exporters:
    loadbalancing/traces:
      resolver:
        k8s:
          service: opentelemetry-collector.default
      protocol:
        otlp:
          tls:
            insecure: true
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
    prometheus:
      config:
        scrape_configs:
        - job_name: opentelemetry-agent
          scrape_interval: 10s
          static_configs:
          - targets:
            - ${K8S_POD_IP}:9090
  service:
    telemetry:
      logs:
        level: info
      metrics:
        address: 0.0.0.0:9090
    extensions:
    - health_check
    - memory_ballast
    pipelines:
      traces:
        exporters:
        - loadbalancing/traces
        processors:
        - memory_limiter
        - k8sattributes
        - resource
        - resource/add_cluster_name
        - resource/add_environment
        - resourcedetection
        receivers:
        - otlp
```

### Log output

```shell
the logs are clean
```

**Comment by grzn** [comment]
Looks like this is happening after the k8s service restarts and the pods change

**Comment by grzn** [comment]
In our setup, we have an agent daemonset and a collector deployment; the agent sends metrics to the k8s service for that deployment, using the config mentioned in the description.

To reproduce:
1. start the collector/deployment
2. start the agent/daemonset
3. curl to one of the agent pods at http://<ip>:8080/metrics, all works
4. rollout restart the collector/deployment
5. run the curl again, them metrics endpoint will return an error as mentioned in the issue description

eveyrthing works when doing the same but with the sending queue disabled, e.g. 

```
      loadbalancing/traces:
        protocol:
          otlp:
            retry_on_failure:
              enabled: false
            sending_queue:
              enabled: false
            timeout: 3s
            tls:
              insecure: true
        resolver:
          k8s:
            service: opentelemetry-collector.default
```
