### ISSUE TITLE
Span processor cannot match a span when status code is set to 500, but works for "500"

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#30771]
### What happened?

Pre-conditions (If any):
Use a sample like this (https://github.com/billg-splunk/observability-content-contrib/tree/main/integration-examples/otel-processor-supress-errors) to recreate the situation.

Steps to reproduce:
1. Setup a demo app to call a phony service (generate 500 errors)
2. Create a processor and add it to the tracing pipeline

```
span/suppress:
    include:
      attributes:
      - key: error
        value: true
    status:
      code: "Ok"
```
Also tried with a more specific example:
```
span/suppress:
    include:
      attributes:
      - key: http.status_code
        value: 500
    status:
      code: "Ok"
```

Expected:
The error spans would be changed to being OK
Actual:
Observe that spans do not appear to change and continue to show errors.

--

NOTE: This may be user error, but we need clear documentation on how to accomplish this very common scenario.

### Collector version

v0.91.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
