### ISSUE TITLE
[exporter/datadog] Memory leak in trace stats module

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-collector-contrib#30828]
### Component(s)

exporter/datadog

## Description
We are observing a memory leak in the Datadog Exporter which appears to be in the trace/apm stats component.

The pattern we see is that when the collector restarts, memory grows steadily until `GOMEMLIMIT` is reached 
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/381302/249f82e4-91e1-4788-9b00-91534da5130f)

We consider this a "leak" vs. a large working set because of the slow growth in heap usage.

Looking at a `pprof` of the collector process we see the majority of heap is used by the `datadog-agent/trace/stats` module.

```
$ go tool pprof -top -cum ~/tmp/mothership-pprof-heap.out
File: collector
Build ID: 38f9c6cdffde4b9f1487841c8b484fa5cf2787fb
Type: inuse_space
Time: Jan 29, 2024 at 9:59am (EST)
Showing nodes accounting for 376.01MB, 93.97% of 400.12MB total
Dropped 263 nodes (cum <= 2MB)
      flat  flat%   sum%        cum   cum%
         0     0%     0%   294.57MB 73.62%  github.com/DataDog/datadog-agent/pkg/trace/stats.(*Concentrator).Add
         0     0%     0%   294.57MB 73.62%  github.com/DataDog/datadog-agent/pkg/trace/stats.(*Concentrator).Run.func1
    0.67MB  0.17%  0.17%   294.57MB 73.62%  github.com/DataDog/datadog-agent/pkg/trace/stats.(*Concentrator).addNow
         0     0%  0.17%   293.90MB 73.45%  github.com/DataDog/datadog-agent/pkg/trace/stats.(*RawBucket).HandleSpan
   23.51MB  5.87%  6.04%   293.90MB 73.45%  github.com/DataDog/datadog-agent/pkg/trace/stats.(*RawBucket).add
         0     0%  6.04%   195.39MB 48.83%  github.com/DataDog/sketches-go/ddsketch.(*DDSketch).Add (inline)
         0     0%  6.04%   195.39MB 48.83%  github.com/DataDog/sketches-go/ddsketch.(*DDSketch).AddWithCount
         0     0%  6.04%   195.39MB 48.83%  github.com/DataDog/sketches-go/ddsketch/store.(*CollapsingLowestDenseStore).AddWithCount
  195.39MB 48.83% 54.88%   195.39MB 48.83%  github.com/DataDog/sketches-go/ddsketch/store.(*CollapsingLowestDenseStore).extendRange
         0     0% 54.88%   195.39MB 48.83%  github.com/DataDog/sketches-go/ddsketch/store.(*CollapsingLowestDenseStore).normalize
   10.50MB  2.62% 57.50%    75.01MB 18.75%  github.com/DataDog/datadog-agent/pkg/trace/stats.newGroupedStats
         0     0% 57.50%    64.50MB 16.12%  github.com/DataDog/sketches-go/ddsketch.LogCollapsingLowestDenseDDSketch
      37MB  9.25% 66.75%       37MB  9.25%  github.com/DataDog/sketches-go/ddsketch/store.NewCollapsingLowestDenseStore (inline)
```

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/381302/04d9b08b-685c-4d0b-962f-9683d392f07e)

We have already disabled these flags in the Datadog Exporter.
```yaml
    traces:
      compute_stats_by_span_kind: false
      peer_tags_aggregation: false
```

### Collector version

v0.90.1

### Additional context

Seems similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15720

When we send the same workload of traces via the Datadog Agent, we do not see a similar memory leak.  I thought this was worth noting since my understanding is that the two use the same library to calculate the trace stats.

**Comment by dineshg13** [comment]
Thanks for reporting. Can you please test this with collector after setting [trace buffer] (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/4918e96af2447d4b5110d71143eb1a8e1071cb78/exporter/datadogexporter/config.go#L297) in datadog exporter to 1000.

**Comment by sirianni** [comment]
Our full collector config is massive.  Here is the config for the Datadog exporter
```yaml
  datadog:
    metrics:
      resource_attributes_as_tags: true
      instrumentation_scope_metadata_as_tags: true
      summaries:
        mode: noquantiles
    traces:
      compute_stats_by_span_kind: false
      peer_tags_aggregation: false
      # Buffer traces to avoid "Payload in channel full" errors
      trace_buffer: 10
    host_metadata:
      enabled: false
    sending_queue:
      queue_size: 200
```

**Comment by songy23** [comment]
@sirianni 👋 QQ
> When we send the same workload of traces via the Datadog Agent, we do not see a similar memory leak. I thought this was worth noting since my understanding is that the two use the same library to calculate the trace stats.

What's the version of Datadog Agent that you use? 
You're right Datadog Agent and Datadog exporter use the same library to calculate the trace stats. We want to double check the versions

**Comment by sirianni** [comment]
We are currently running Datadog Agent `6.45.1`.

**Comment by sirianni** [comment]
Thanks @dineshg13 - I will experiment with the change.  Can you help me understand how increasing `trace_buffer` would affect memory usage of the DD APM stats?

**Comment by sirianni** [comment]
@dineshg13 setting `trace_buffer: 1000` did not fix the leak or show any meaningful improvement in memory usage.

**Comment by dineshg13** [comment]
@sirianni Are you using Datadog connector ? It would be helpful to have share the full  collector config.

**Comment by sirianni** [comment]
> @sirianni Are you using Datadog connector ? It would be helpful to have share the full collector config.

Yes we are.  The full config is quite complicated because we have applications that dual write traces to both our OTel Collector and the DD Agent.  We are doing this to allow for a graceful transition from DD Agent to OTel Collector.  

What we are trying to accomplish for OpenCensus is:
* Convert OpenCensus traces to OTel in the collector
* Generate DD APM stats from these converted traces
* Send only the APM stats for these traces to DD
* We don't send the raw traces to DD because these would cause duplicate SpanIDs (since the applications themselves are dual-exporting to both DD Agent and our collector)

Effectively we're doing something like this.
```yaml
piplelines:
  traces/opencensus:
    receivers: 
    - opencensus
    exporters:
    - datadog/trace_stats_connector
  traces/otel:
    receivers:
    - otlp
    exporters:
    - datadog
  metrics:
    receivers:
    - datadog/trace_stats_connector
    exporters:
    - datadog
```

I noticed that the `datadogconnector` does not support any configuration options `compute_stats_by_span_kind` or `peer_tags_aggregation`
