### ISSUE TITLE
The trace_id/span_id of exemplar would not change when using promethuesremotewrite exporter

### ISSUE THREAD

**Issue by toughnoah** [open-telemetry/opentelemetry-collector-contrib#30830]
### Component(s)

exporter/prometheusremotewrite

## Description
when I use the spanmetrics connector, the trace_id/span_id of exemplar  **would not** change if I use the promethuesremotewrite exporter directly write into backend prometheus/mimir
## Steps to Reproduce
Simply start a demo to produce traces to otel collector

## Expected Result
trace_id and span_id of the exemplar should change if I start a new trace

## Actual Result

trace_id/span_id would always be the same, and the only way to is to restart otel collector
![1706547360287](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/75348324/fa8a537f-b5af-4e0e-b79c-abc5c42431f5)
![WX20240130-005511@2x](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/75348324/7f0a1f2f-03e2-4a0b-944d-536e984b412a)
![WX20240130-005539@2x](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/75348324/363ad7bc-b0f8-4d2d-8eb4-8ecf04cdfdfe)

### Collector version

v0.91.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

kubernetes 1.25

### OpenTelemetry Collector configuration

```yaml
connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
        exemplars:
          enabled: true
          max_per_data_point: 1000
        metrics_flush_interval: 30s
    receivers:
      otlp:
        protocols:
          http:
            endpoint: :4317
          grpc:
            endpoint: :4318
    service:
      telemetry:
        logs:
          level: "debug"
      extensions: []
      pipelines:
        metrics:
          receivers: [otlp, spanmetrics]
          exporters: [prometheusremotewrite]
        traces:
          receivers: [otlp]
          exporters: [spanmetrics]
    exporters:
      prometheusremotewrite: # the PRW exporter, to ingest metrics to backend
        endpoint: http://mimir-distributed-nginx.grafana/api/v1/push
        remote_write_queue:
          enabled: false
        resource_to_telemetry_conversion:
          enabled: true
```
