### ISSUE TITLE
[receiver/hostmetricsreceiver] Deprecate the `processesscraper`

### ISSUE THREAD

**Issue by braydonk** [open-telemetry/opentelemetry-collector-contrib#30895]
### Is your feature request related to a problem? Please describe.

In the orbit of the coming semantic conventions changes, it was decided that the `processesscraper` should be deprecated in favour of adding the `system.processes.*` metrics to the `processscraper` directly. 

### Describe the solution you'd like

Instead of:
```yaml
hostmetrics:
  scrapers:
    process:
    processes:
```

I would like the following config to give the same results:
```yaml
hostmetrics:
  scrapers:
    process:
      metrics:
        system.processes.created:
          enabled: true
        system.processes.count:
          enabled: true
```

### Describe alternatives you've considered

It might be useful to have particular flags on the `processscraper` to enable/disable per process metrics and enable/disable aggregate process metrics. This is because if you only want the `system.processes.*` metrics, it is quite tedious to manually disable all the other metrics through the configuration.

### Additional context

This has two benefits:
1. While the change hasn't formulated yet, there is a plan for the `system.processes` namespace to be renamed to conform with the semantic conventions rules around pluralized namespaces
2. Collecting all the processes on the system only one time should be a performance/memory improvement.
