### ISSUE TITLE
Loki exporter : Lot of out of order errors

### ISSUE THREAD

**Issue by gillg** [open-telemetry/opentelemetry-collector-contrib#3090]
**Describe the bug**
When a use Loki exporter with a unique set of labels I get a lot of out of order dropped messages (resulting in a full OTEL collector queue).
My labels are correct accross logs to be uniques by main producers processes (but I can't seriously introduce thread ID as label).

Is there a workarond for now ?

**Steps to reproduce**
Create an app which sends logs through OTLP to a collector.
Different threads of the app emits logs, so timestamps can be a little shuffled when OTEL Collector receive them.

**What did you expect to see?**
Especialy for Loki exporter (or as a new processor), we should be able to buffer logs for a short time and order them before send them to Loki.

**What did you see instead?**
OTEL Collector queue is filling a lot with retries for loki 400 bad resquests responses (out of order).

**What version did you use?**
otel-collector-contrib:523e417c06215ffdd5ce1d36ad4fa657f4dd525c

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push
    labels:
      attributes:
        [... mappings for otel attributes...]

processors:
  batch:

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, loki]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
```

**Additional context**
Could be fixed by https://github.com/grafana/loki/issues/1544
