### ISSUE TITLE
connectors/datadogconnector: Increasing Memory That Eventually Kills Collector Pods

### ISSUE THREAD

**Issue by NickAnge** [open-telemetry/opentelemetry-collector-contrib#30908]
### Component(s)

connector/datadog

## Description
In our setup, we've activated both the Datadog connector and exporter to avoid APM stats sampling. We've been experiencing a continuous increase in memory, eventually leading to the pod reaching an Out-of-Memory (OOM) state after a few hours. We followed the suggested configuration from the README.md and have datadog/connector as the receiver for traces.

## Steps to Reproduce

1. Setup a OpenTelemetry Collector with the above configuration
2. Publish trace telemetry data through the telemetry collector
3. Evaluate memory through pprof

## Expected Result

Not Memory increase that kills the pod

## Actual Result

Memory increase that kills the pod eventually.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/53213326/816bad22-7505-4f9c-9f7e-6f1664710ef0)

### Collector version

opentelemetry-collector-contrib:0.88.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

 probabilistic_sampler:
    sampling_percentage: 20

connectors:
    datadog/connector:

service:
  extensions: [ health_check, pprof ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ datadog/connector ]
 
    traces/sampled:
      receivers: [ datadog/connector ]
      processors:[ probabilistic_sampler, batch ]
      exporters: [ datadog ]
```
