### ISSUE TITLE
Unable to start otelcol-contrib with opensearch exporter enabled 

### ISSUE THREAD

**Issue by AmythD** [open-telemetry/opentelemetry-collector-contrib#30907]
### Component(s)

exporter/opensearch on otelcol-contrib version 0.93.0

### Describe the issue you're reporting

I'm getting an error when trying to start otelcol-contrib using below config, any ideas on what could be wrong? 

```
 receivers:
   otlp:
     protocols:
       grpc:
         endpoint: 0.0.0.0:4317
       http:
         endpoint: 0.0.0.0:4318
 extensions:
   basicauth/client:
   client_auth:
     username: user
     password: user
 exporters:
   opensearch/trace:
     http:
       endpoint: https://opensearch:9200
       auth:
         authenticator: basicauth/client
 service:
   pipelines:
     traces:
       receivers: [otlp]
       exporters: [opensearch/trace]
       processors: [batch]

```
**Error message that I'm seeing :** 

> * error decoding 'extensions': unknown type: "client_auth" for id: "client_auth" (valid values: [k8s_observer memory_ballast bearertokenauth ecs_task_observer ecs_observer host_observer headers_setter jaegerremotesampling docker_observer oidc pprof file_storage db_storage zpages http_forwarder oauth2client health_check sigv4auth asapclient awsproxy basicauth])
>

**Comment by crobert-1** [comment]
Helly @AmythD, the error message is saying that there's no extension named `client_auth`. It looks like the problem is indentation in your config file.

Original config:
```
extensions:
   basicauth/client:
   client_auth:
     username: user
     password: user
```
Should instead be:
```
extensions:
  basicauth/client:
    client_auth:
      username: user
      password: user
```
`client_auth` is a configuration option within the `basic_auth` extension, not its own extension.
