### ISSUE TITLE
kubernetes client logging not wrapped in otel collector logging

### ISSUE THREAD

**Issue by ringerc** [open-telemetry/opentelemetry-collector-contrib#30928]
### Component(s)

processor/k8sattributes, processor/resourcedetection, receiver/k8scluster, receiver/kubeletstats, receiver/prometheus

## Description

Error logs from [`kubernetes/client-go`](https://github.com/kubernetes/client-go) library not wrapped and captured in otel collector logger, so they are logged as plaintext when when json logging is on.

## Steps to Reproduce

Deploy an OpenTelemetry collector in Kubernetes with

* `receivers..prometheus` configured with k8s pod discovery
* `receivers.kubletstats` configured
* `receivers.k8s_cluster` configured
* `processors.k8sattributes` configured

... but omit the `ClusterRole` and `ClusterRoleBinding` required for kube RBAC, so as to deliberately induce error logging on k8s apiserver accesses.

## Expected Result

Errors from k8s apiserver access are logged through the OpenTelemetry Collector's logging stream, respecting the `service.telemetry.logs.encoding` setting (json logging) and `service.telemetry.logs.level` setting (log level).

## Actual Result

Errors from k8s apiserver are logged in plaintext even when `service.telemetry.logs.encoding` is set to `json`, ignoring log formatting configuration.

E.g.

```
W1220 20:43:06.585812       1 reflector.go:535] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:serviceaccount:p-6sbq4blfkb:otel-collector" cannot list resource "replicasets" in API group "apps" at the cluster scope
```

I suspect this issue involves multiple components that interact with the `client-go` library, but have not yet isolated exactly which ones.

**Edit:** Per ticket comments below

* `k8s_cluster` - does not wrap `client-go` logs
* `k8sattributes` - does not wrap `client-go` logs
* `prometheus` - k8s discover does not wrap `client-go` logs
* `kubeletstats` - doesn't seem to use k8sclient calls that emit logs directly, all its logs are properly json 

### Collector version

0.92.0

## Environment

Kubernetes 1.29 (Ubuntu nodes)

### OpenTelemetry Collector configuration

```yaml
# requires K8S_NODE_NAME injected via kube downward API from DaemonSet
#
receivers:
  prometheus/discovery:
    config:
      scrape_configs:
      - job_name: 'postgres-pod'
        scrape_interval: 1m
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: keep
          regex: ${env:K8S_NODE_NAME}

  kubeletstats:
    collection_interval: 1m
    auth_type: 'serviceAccount'
    endpoint: '${env:K8S_NODE_NAME}:10250'
    insecure_skip_verify: true
    metric_groups:
      - node
      - pod
      - container
      - volume
    extra_metadata_labels:
      - container.id
      - k8s.volume.type
    k8s_api_config:
      auth_type: serviceAccount

  k8s_cluster:
    collection_interval: 1m
    auth_type: serviceAccount
    node_conditions_to_report:
      # https://kubernetes.io/docs/reference/node/node-status/#condition
      - Ready
      - MemoryPressure
    allocatable_types_to_report:
      - cpu
      - memory
    metrics:
      k8s.node.condition:
         enabled: true
      k8s.pod.status_reason:
         enabled: true

exporters:
  debug/basic:
    verbosity: basic

processors:
  resourcedetection/k8snode:
    detectors: ["k8snode"]
    k8snode:
      node_from_env_var: K8S_NODE_NAME
    system:
      hostname_sources: ["os"]

  k8sattributes:
    passthrough: false
    auth_type: "serviceAccount"
    filter:
      node_from_env_var: K8S_NODE_NAME
    pod_association:
      - sources:
        - from: resource_attribute
          name: k8s.pod.uid
      - sources:
        - from: resource_attribute
          name: k8s.pod.ip
      - sources:
        - from: connection
    extract:
      metadata:
        - container.id
        - container.image.name
        - container.image.tag
        - k8s.container.name
        - k8s.cronjob.name
        - k8s.daemonset.name
        - k8s.daemonset.uid
        - k8s.deployment.name
        - k8s.job.name
        - k8s.job.uid
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.name
        - k8s.pod.start_time
        - k8s.pod.uid
        - k8s.replicaset.name
        - k8s.replicaset.uid
        - k8s.statefulset.name
        - k8s.statefulset.uid
      labels:
      - tag_name: "app.kubernetes.io/name"
        key: app.kubernetes.io/name
        from: pod
      - tag_name: "app.kubernetes.io/instance"
        key: app.kubernetes.io/instance
        from: pod
      - tag_name: "app.kubernetes.io/version"
        key: app.kubernetes.io/version
        from: pod
      - tag_name: "app.kubernetes.io/component"
        key: app.kubernetes.io/component
        from: pod
      - tag_name: "app.kubernetes.io/part-of"
        key: app.kubernetes.io/part-of
        from: pod
      - tag_name: "app.kubernetes.io/managed-by"
        key: app.kubernetes.io/managed-by
        from: pod

  batch:

service:
  telemetry:
    logs:
      encoding: "json"
      level: "info"
  pipelines:
    metrics:
      receivers:
        - prometheus/discovery
        - k8s_cluster
        - kubeletstats
      processors:
        - k8sattributes
        - batch
      exporters:
        - debug/basic
```

### Log output

```
E0201 23:39:52.564923       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:otel-collector" cannot list resource "pods" in API group "" at the cluster scope
W0201 23:39:52.697503       1 reflector.go:535] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:otel-collector" cannot list resource "pods" in API group "" at the cluster scope
E0201 23:39:52.697525       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:otel-collector" cannot list resource "pods" in API group "" at the cluster scope
W0201 23:39:52.711159       1 reflector.go:535] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.DaemonSet: daemonsets.apps is forbidden: User "system:serviceaccount:default:otel-collector" cannot list resource "daemonsets" in API group "apps" at the cluster scope
E0201 23:39:52.711172       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.DaemonSet: failed to list *v1.DaemonSet: daemonsets.apps is forbidden: User "system:serviceaccount:default:otel-collector" cannot list resource "daemonsets" in API group "apps" at the cluster scope
W0201 23:39:52.750020       1 reflector.go:535] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:otel-collector" cannot list resource "pods" in API group "" at the cluster scope
E0201 23:39:52.750045       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:default:otel-collector" cannot list resource "pods" in API group "" at the cluster scope
W0201 23:39:52.763790       1 reflector.go:535] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:default:otel-collector" cannot list resource "nodes" in API group "" at the cluster scope
E0201
...
```

(more complete log will be attached)

### Additional context

(Extracted from my real config, which is much larger, and as yet untested because it omits various specifics that mean it can no longer be deployed in my real running environment)

Use a `kustomization.yaml` like:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: otel-collector-config
    files:
      - otel-collector-config.yaml
    options:
      disableNameSuffixHash: true
resources:
  - daemonset.yaml
  - serviceaccount.yaml
```

with `otel-collector-config.yaml` containing the config listed above.

with `serviceaccount.yaml`:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
```

with `daemonset.yaml`:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector-node-agent
  annotations:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-node-agent
      app.kubernetes.io/component: otel-collector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector-node-agent
        app.kubernetes.io/component: otel-collector
      annotations:
        kubectl.kubernetes.io/default-container: opentelemetry-collector
    spec:
      containers:
        - name: opentelemetry-collector
          command:
            - "/otelcol-contrib"
            - "--config=/etc/otel-collector-config/otel-collector-config.yaml"
            - "--feature-gates=+k8sattr.rfc3339"
          image: "otel/opentelemetry-collector-contrib:0.93.0"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector-config
      serviceAccountName: otel-collector
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
            items:
              - key: otel-collector-config.yaml
                path: otel-collector-config.yaml
```
