### ISSUE TITLE
OTTL 'log' function needed for debugging complex transform pipelines

### ISSUE THREAD

**Issue by ringerc** [open-telemetry/opentelemetry-collector-contrib#30932]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

It's difficult to inspect and diagnose the behaviour of complex transform processor pipelines because of the lack of a means of inspecting the state and execution partway through the pipeline.

Answering questions like "why does this 'where' clause not match" is considerably more difficult than might be expected.

### Describe the solution you'd like

An OTTL `debug_log` function that writes its argument(s) out in json form to the otel collector log stream would be very helpful. If passed multiple arguments it would log each in turn. If passed a path, it would serialize and log all children of the path, following the usual access rules.

It would take a key/value pairing of log field label to log field value, and emit them through the otel collector's logger, so if json logging is turned on the results would be distinct json logging keys.

E.g.

```yaml
  transform/afterdiscovery-vendor:
    metric_statements:
      - context: resource
        statements:
          - |
            set(attributes["foo"], true)
            where attributes["bar"] == "baz"
          - debug_log("attribute foo", attributes["foo"], "attribute bar", attributes["bar"])
```

For use in the filter processor, logging converter variants may make sense. These would take their first argument and return it unchanged, then take all additional parameters as data to emit as logs.

### Describe alternatives you've considered

Presently debugging complex pipelines often involves commenting out various parts, or splitting them up into two separate processors linked by a connector with a debug exporter in the middle. It's wholly impractical.

Ideally some form of attachable debugger could be added, where it could establish a socket to the running collector and place probes dynamically. This is far beyond what's practical to add to the OTTL stack at present however.

Sometimes it's possible to get the info needed by using `set` to apply various attributes to carry the info required, then inspect with a debug exporter. But this quickly fall down for more complex transforms.
