### ISSUE TITLE
Error while sending traces using OpenSearch exporter

### ISSUE THREAD

**Issue by AmythD** [open-telemetry/opentelemetry-collector-contrib#31039]
### Component(s)

exporter/opensearch

### Describe the issue you're reporting

Hello,

I am trying to send otel format application traces through an opentelemetry collector to an OpenSearch backend. I observed below errors on the otel collector logs and don't seem to be getting any traces on the opensearch side yet. I did not see any errors on the OpenSearch logs itself. Could anyone please help me with this?

`2024-02-05T16:35:41.140Z        warn        batchprocessor@v0.93.0/batch_processor.go:258        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "traces", "error": "not retryable error: Permanent error: {\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\",\"caused_by\":{\"type\":\"class_cast_exception\",\"reason\":\"class org.opensearch.index.mapper.KeywordFieldMapper cannot be cast to class org.opensearch.index.mapper.ObjectMapper (org.opensearch.index.mapper.KeywordFieldMapper and org.opensearch.index.mapper.ObjectMapper are in unnamed module of loader 'app')\",\"caused_by\":null}}"}
`

```
receivers:
   otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  opensearch/trace:
    http:
      endpoint: http://X.X.X.X:9200
      tls:
        insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [opensearch/trace]
      processors: [batch]

```
Kindly excuse any incorrect indendation during copy paste of the config.

I'm on otel-contrib version 0.93.0 OpenSearch version 2.11.1
