### ISSUE TITLE
File Log receiver loses logs even if persistence is set up

### ISSUE THREAD

**Issue by OverOrion** [open-telemetry/opentelemetry-collector-contrib#31074]
### Component(s)

extension/storage/filestorage, receiver/filelog

## Description
UPDATE: filelog receiver might be the culprit: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31074#issuecomment-1932137539
I tried the [fault tolerant log collection example](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/fault-tolerant-logs-collection), but it seemingly loses logs (does not matter if the exporter is `file` or `OTLP(GRPC)`).
`file_storage` is enabled for receiver (and for the `OTLP` exporter as well), so the state should not be lost.
I tried the `fileexporter` and the logs are lost here as well, below are the results.
## Steps to Reproduce
See gist for files: https://gist.github.com/OverOrion/2086516236e343ae2c362557302c70ce

```bash
$ cat input_gen.sh
#!/usr/bin/env bash

for i in $(seq 1 600000); do
  echo line$i
done
```

### Steps:
1. Generate a big enough input file for the collector to read:
```bash
./input_gen.sh > input.log
```
2. Start the collector with the given configuration file (make sure the file receiver path points to `input.log`)
```
./otelcontribcol_linux_amd64 --config ./sender.yaml
```
3. Watch the received logs (written by the `exporter/file`) with:
```
 watch -n 1 -d "cat sender_output.log | grep -E 'line[0-9]+' -o -w | wc -l"
```
4. After some time stop the controller by pressing CTRL+C (sending a SIGINT)
5. Restart the controller using the same configuration file
6. Wait for it to finalize sending the logs and check the `sender_output.log` file:
```
cat sender_output.log | grep -E 'line[0-9]+' -o -w | wc -l
598887
```

## Expected Result
All logs should be written, no logs should be lost.

## Actual Result
In my case I consistently lose 1k+ logs out of 600k.

### Collector version

8ae1539c84a55140075063d27e62eb561f9b5dab

## Environment
OS: Ubuntu 23.10
Compiler(if manually compiled): go1.21.6 linux/amd64

### OpenTelemetry Collector configuration

```yaml
extensions:
  file_storage/default:
    directory: /home/orion/work/others/open-telemetry/opentelemetry-collector-contrib/persist_dir/receivers
    fsync: true

receivers:
  filelog:
    include: ["/home/orion/work/others/open-telemetry/opentelemetry-collector-contrib/bin/input.log"]
    storage: file_storage/default
    start_at: beginning
    retry_on_failure:
      enabled: true

exporters:
  # Optional debug output
  debug:
    verbosity: detailed
  otlp/debug:
    endpoint: localhost:4317
    retry_on_failure:
      enabled: true
    sending_queue:
      queue_size: 10000
    tls:
      insecure: true

service:
  extensions: [file_storage/default]
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [otlp/debug]
```

### Additional context

~~Can you please confirm that the given configuration should not lose any logs?~~ EDIT: confirmed
I think this issue is related: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20552 
I think it would be great to have an example config snippet that showcases
- fault tolerance
- and is E2E tested by the CI

**Comment by mx-psi** [comment]
cc @swiatekm-sumo in case you can help here

**Comment by astencel-sumo** [comment]
I'm not able to reproduce this with either `v0.92.0` or https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/8ae1539c84a55140075063d27e62eb561f9b5dab. For me, the output file always contains 600k items:

```console
$ cat sender_output.log| grep -E 'line[0-9]+' -o -w | wc -l
600000
```

I'm on Ubuntu 23.10 as well.

Also looking at the collector's metrics, I can see 600k logs recieved by the Filelog receiver and 600k logs exported by both exporters:

```console

# HELP otelcol_exporter_sent_log_records Number of log record successfully sent to destination.
# TYPE otelcol_exporter_sent_log_records counter
otelcol_exporter_sent_log_records{exporter="file",service_instance_id="75a83cc2-c414-45fe-bcb1-3f1cdb8eaa6f",service_name="otelcontribcol",service_version="0.93.0-dev"} 600000
otelcol_exporter_sent_log_records{exporter="otlp/debug",service_instance_id="75a83cc2-c414-45fe-bcb1-3f1cdb8eaa6f",service_name="otelcontribcol",service_version="0.93.0-dev"} 600000

# HELP otelcol_receiver_accepted_log_records Number of log records successfully pushed into the pipeline.
# TYPE otelcol_receiver_accepted_log_records counter
otelcol_receiver_accepted_log_records{receiver="filelog",service_instance_id="75a83cc2-c414-45fe-bcb1-3f1cdb8eaa6f",service_name="otelcontribcol",service_version="0.93.0-dev",transport=""} 600000
```

Same with the other collector that is receiving the OTLP logs:

```console
# HELP otelcol_exporter_sent_log_records Number of log record successfully sent to destination.
# TYPE otelcol_exporter_sent_log_records counter
otelcol_exporter_sent_log_records{exporter="debug",service_instance_id="9ff1b1b4-525a-42d3-b0b2-56e97080db2d",service_name="otelcol-contrib",service_version="0.92.0"} 600000

# HELP otelcol_receiver_accepted_log_records Number of log records successfully pushed into the pipeline.
# TYPE otelcol_receiver_accepted_log_records counter
otelcol_receiver_accepted_log_records{receiver="otlp",service_instance_id="9ff1b1b4-525a-42d3-b0b2-56e97080db2d",service_name="otelcol-contrib",service_version="0.92.0",transport="grpc"} 600000
```

Here's the configuration of the OTLP receiving collector for reference:

```yaml
exporters:
  debug:
receivers:
  otlp:
    protocols:
      grpc:
service:
  pipelines:
    logs:
      exporters:
      - debug
      receivers:
      - otlp
  telemetry:
    metrics:
      address: localhost:8889
```

@OverOrion let me know if you can still reproduce this. If you can, please attach the following:

- The metrics output from http://localhost:8888/metrics from the collector (and possibly from the other, OTLP receiving collector)
- The logs from the collector with debug logs enabled: `service.telemetry.logs.level: debug`
