### ISSUE TITLE
[receiver/filelog]High memory consumption of collector and dropped logs

### ISSUE THREAD

**Issue by marcinsiennicki95** [open-telemetry/opentelemetry-collector-contrib#31129]
### Component(s)

receiver/filelog

## Description
I am currently configuring the OpenTelemetry Collector to gather logs through the FileLog Receiver, which are then transmitted to Fluent Bit via the OpenTelemetry exporter. Fluent Bit ingests these logs through the OpenTelemetry Input and forwards them using OpenTelemetry Output. In this configuration, OpenTelemetry acts as a proxy for Fluent Bit, allowing it to collect and process data from other various telemetry sources

## Steps to Reproduce

1. Set up the environment with installed FluentBit and OpenTelemetry Collector
2. Configure and start the OpenTelemetry Collector to gather logs from the Test file using the Filelog receiver, and sent the logs using the otlphttp exporter and not consume more memory than limit
3. Configure and run FluentBit to receive logs using the OpenTelemetry Input and sent logs using the OpenTelemetry Output to destination
4. Upload the prepared Test file which has size ~500mb/1mln logs to the configured folder simulating high load
5. Monitor the environment and validate the results in CloudPlatform

## Expected Result
Each of the logs should be processed. No error logs should visible on console  

## Actual Result

Without memory-limiting processor, the number of logs displayed in the user interface does not correspond exactly to 1 million and service consume a lot of memory
```
2024-02-08T11:58:49.791Z        error   exporterhelper/common.go:174    Exporting failed. Rejecting data.       {"kind": "exporter", "data_type": "logs", "name": "otlphttp", "error": "sending queue is full", "rejected_items": 100}
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseExporter).send
        go.opentelemetry.io/collector/exporter@v0.93.0/exporterhelper/common.go:174
go.opentelemetry.io/collector/exporter/exporterhelper.NewLogsExporter.func1
        go.opentelemetry.io/collector/exporter@v0.93.0/exporterhelper/logs.go:98
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs
        go.opentelemetry.io/collector/consumer@v0.93.0/logs.go:25
go.opentelemetry.io/collector/internal/fanoutconsumer.(*logsConsumer).ConsumeLogs
        go.opentelemetry.io/collector@v0.93.0/internal/fanoutconsumer/logs.go:73
go.opentelemetry.io/collector/consumer.ConsumeLogsFunc.ConsumeLogs
        go.opentelemetry.io/collector/consumer@v0.93.0/logs.go:25
github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal/consumerretry.(*logsConsumer).ConsumeLogs
        github.com/open-telemetry/opentelemetry-collector-contrib/internal/coreinternal@v0.93.0/consumerretry/logs.go:66
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).consumerLoop
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.93.0/adapter/receiver.go:125
```

With memory limiter processor. 

### Collector version

v.0.93

### Environment information

WindowsServer:2019-Datacenter:latest

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include: [ C:/test ]
    encoding: utf-16le
    include_file_path: true
    max_log_size: 1MiB
    storage: file_storage
    poll_interval: 10s
    retry_on_failure:
        enabled: true

exporters:
  logging:

  otlphttp:
    endpoint: http://127.0.0.1:4318
    tls:
      insecure: true

extensions:
  file_storage:
    directory: C:/collector
    fsync: true

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [logging, otlphttp]

or added 

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 120
    spike_limit_mib: 80
```

### Additional context

Log output with memory limiter.
![2024-02-08 11_34_32-default-windows-chef-17 - 10 6 106 10_3389 - Remote Desktop Connection](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/108410394/32183d3a-6c13-4a25-8180-7c375dcb1f62)

Actual 
OpenTelemetry Collector sends only a limited number of logs before reaching a memory limit, which starts the garbage collection (GC) process and stops further log processing. As a result, about 950,000 logs are not send. Only new generated logs are sent . Ie, Fluent Bit, when the memory limit is reached, pauses log entry and after a short pause resumes processing without losing logs 

FluentBit Configuration. 

```
[INPUT]
    name opentelemetry
    tag_from_uri false
    tag test
    listen 127.0.0.1
    port 4318

    Mem_Buf_Limit 50MB
```

Does the OpenTelemetry Collector offer a parameter analogous to fleuntbit `mem_buf_limit` for managing memory buffer constraints?

**Comment by djaglowski** [comment]
At a glance this appears to be a back pressure problem but it's unclear where. Have you tried using the exporter's retry & queueing functionality to manage this? [Example](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/testdata/config.yaml#L10-L20)

**Comment by djaglowski** [comment]
cc: @dmitryax

**Comment by marcinsiennicki95** [comment]
@djaglowski  Thanks for your reply. I tested your suggestion and it didn't help

I do not think I have described the test scenario in detail

**OpenTelemetry Collector configuration**

`receivers:
  filelog:
    include: [ C:/test]
    encoding: utf-16le
    include_file_path: true
    max_log_size: 1MiB
    storage: file_storage
    poll_interval: 10s
    retry_on_failure:
        enabled: true

exporters:
  logging:

  otlphttp:
    endpoint: http://127.0.0.1:4318
    tls:
      insecure: true

extensions:
  file_storage:
    directory: C:/collector
    fsync: true

processors:
  batch:
    send_batch_size: 1000
  memory_limiter:
    check_interval: 1s
    limit_mib: 250
    spike_limit_mib: 100

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [memory_limiter,batch]
      exporters: [logging, otlphttp]`
     

**Log output**

`PS C:\Users\kCuraCloudAdmin> C:\\collector\\otelcol-contrib_0.93.0_windows_amd64\\otelcol-contrib.exe --config C:\\collector\\otelcol-contrib_0.93.0_windows_amd64\\config.yaml
2024-02-09T13:04:50.083Z        info    service@v0.93.0/telemetry.go:76 Setting up own telemetry...
2024-02-09T13:04:50.083Z        info    service@v0.93.0/telemetry.go:146        Serving metrics {"address": ":8888", "level": "Basic"}
2024-02-09T13:04:50.084Z        info    exporter@v0.93.0/exporter.go:275        Deprecated component. Will be removed in future releases.       {"kind": "exporter", "data_type": "logs", "name": "logging"}
2024-02-09T13:04:50.085Z        info    memorylimiter/memorylimiter.go:77       Memory limiter configured       {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "limit_mib": 250, "spike_limit_mib": 150, "check_interval": 1}
2024-02-09T13:04:50.086Z        info    service@v0.93.0/service.go:139  Starting otelcol-contrib...     {"Version": "0.93.0", "NumCPU": 2}
2024-02-09T13:04:50.086Z        info    extensions/extensions.go:34     Starting extensions...
2024-02-09T13:04:50.086Z        info    extensions/extensions.go:37     Extension is starting...        {"kind": "extension", "name": "file_storage"}
2024-02-09T13:04:50.086Z        info    extensions/extensions.go:52     Extension started.      {"kind": "extension", "name": "file_storage"}
2024-02-09T13:04:50.086Z        info    adapter/receiver.go:45  Starting stanza receiver        {"kind": "receiver", "name": "filelog", "data_type": "logs"}
2024-02-09T13:04:50.118Z        warn    fileconsumer/file.go:51 finding files: no files match the configured criteria   {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
2024-02-09T13:04:50.129Z        info    service@v0.93.0/service.go:165  Everything is ready. Begin running and processing data.
2024-02-09T13:05:10.298Z        info    fileconsumer/file.go:268        Started watching file   {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "C:\\test"}
2024-02-09T13:05:10.303Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:05:10.304Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:05:11.227Z        info    memorylimiter/memorylimiter.go:222      Memory usage is above soft limit. Forcing a GC. {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 112}
2024-02-09T13:05:11.310Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:05:11.361Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:05:12.093Z        info    memorylimiter/memorylimiter.go:192      Memory usage after GC.  {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 194}
2024-02-09T13:05:12.107Z        warn    memorylimiter/memorylimiter.go:229      Memory usage is above soft limit. Refusing data.        {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 194}
2024-02-09T13:05:12.456Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 9, "log records": 819}
2024-02-09T13:07:13.100Z        info    memorylimiter/memorylimiter.go:215      Memory usage back within limits. Resuming normal operation.     {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 36}
2024-02-09T13:07:34.312Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:07:34.312Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:07:35.222Z        info    memorylimiter/memorylimiter.go:222      Memory usage is above soft limit. Forcing a GC. {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 166}
2024-02-09T13:07:35.328Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:07:35.353Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:07:35.430Z        info    memorylimiter/memorylimiter.go:192      Memory usage after GC.  {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 99}
2024-02-09T13:07:36.168Z        warn    memorylimiter/memorylimiter.go:229      Memory usage is above soft limit. Refusing data.        {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 211}
2024-02-09T13:07:36.466Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 4, "log records": 400}
2024-02-09T13:09:37.102Z        info    memorylimiter/memorylimiter.go:215      Memory usage back within limits. Resuming normal operation.     {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 36}
2024-02-09T13:10:14.145Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:10:14.155Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:10:15.150Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:10:15.158Z        info    memorylimiter/memorylimiter.go:222      Memory usage is above soft limit. Forcing a GC. {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 152}
2024-02-09T13:10:15.177Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:10:15.433Z        info    memorylimiter/memorylimiter.go:192      Memory usage after GC.  {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 110}
2024-02-09T13:10:15.624Z        warn    memorylimiter/memorylimiter.go:229      Memory usage is above soft limit. Refusing data.        {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 110}
2024-02-09T13:12:16.100Z        info    memorylimiter/memorylimiter.go:215      Memory usage back within limits. Resuming normal operation.     {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 35}
2024-02-09T13:12:27.063Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:12:27.073Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:12:28.072Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:12:28.077Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 10, "log records": 1000}
2024-02-09T13:12:28.087Z        info    memorylimiter/memorylimiter.go:222      Memory usage is above soft limit. Forcing a GC. {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 152}
2024-02-09T13:12:28.929Z        info    memorylimiter/memorylimiter.go:192      Memory usage after GC.  {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 188}
2024-02-09T13:12:28.949Z        warn    memorylimiter/memorylimiter.go:229      Memory usage is above soft limit. Refusing data.        {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 188}
2024-02-09T13:12:29.144Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 6, "log records": 600}
2024-02-09T13:14:29.099Z        info    memorylimiter/memorylimiter.go:215      Memory usage back within limits. Resuming normal operation.     {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 35}
2024-02-09T13:14:35.501Z        info    LogsExporter    {"kind": "exporter", "data_type": "logs", "name": "logging", "resource logs": 2, "log records": 37}`

**Result** 
Processed only 889k logs. Upon reaching the soft limit, the receiver pauses for approximately 120 seconds before resuming to process the remainder of the file. It appears that some logs are not being returned to the receiver but are instead being dropped. According to the documentation, the logs should be returned to the receiver for reprocessing

**Comment by marcinsiennicki95** [comment]
Here is second scenario where the collector is now working as expected

 **OpenTelemetry Collector configuration**
```receivers:
  filelog:
    include: [ C:/test ]
    encoding: utf-16le
    include_file_path: true
    max_log_size: 1MiB
    storage: file_storage
    poll_interval: 10s
    retry_on_failure:
        enabled: true
  filelog/continues:
    include: [ C:/test1.txt]
    include_file_path: true
    max_log_size: 1MiB
    storage: file_storage
    poll_interval: 10s
    retry_on_failure:
        enabled: true

exporters:
  logging:

  otlphttp:
    endpoint: http://127.0.0.1:4318
    tls:
      insecure: true

extensions:
  file_storage:
    directory: C:/collector
    fsync: true

processors:
  batch:
    send_batch_size: 1000
  memory_limiter:
    check_interval: 1s
    limit_mib: 250
    spike_limit_mib: 100

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers: [filelog, filelog/continues]
      processors: [memory_limiter,batch]
      exporters: [logging, otlphttp]
```

**Comment by marcinsiennicki95** [comment]
To me, it is not clear why the pipeline is paused at about 120, even if this message is displayed
```2024-02-09T13:12:16.100Z        info    memorylimiter/memorylimiter.go:215      Memory usage back within limits. Resuming normal operation.     {"kind": "processor", "name": "memory_limiter", "pipeline": "logs", "cur_mem_mib": 35}
```
I assumed that it should resume immediately after recover to normal memory

**Comment by marcinsiennicki95** [comment]
Another test, Handling High Volumes of Logs and Metrics with the Memory Limiter Processor in pipelines

 **OpenTelemetry Collector configuration**
 ```
 receivers:
  filelog:
    include: [ C:/test ]
    encoding: utf-16le
    include_file_path: true
    max_log_size: 1MiB
    storage: file_storage
    poll_interval: 10s
    retry_on_failure:
        enabled: true
  
  hostmetrics:
    collection_interval: 2s
    scrapers:
      cpu:
      memory:

exporters:
  logging:

  otlphttp:
    endpoint: http://127.0.0.1:4318
    tls:
      insecure: true

extensions:
  file_storage:
    directory: C:/collector
    fsync: true

processors:
  batch:
    send_batch_size: 1000
  memory_limiter:
    check_interval: 1s
    limit_mib: 250
    spike_limit_mib: 100

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [memory_limiter,batch]
      exporters: [logging, otlphttp]
    metrics:
      receivers: [hostmetrics]
      processors: [memory_limiter,batch]
      exporters: [logging, otlphttp]
  ```

**Comment by marcinsiennicki95** [comment]
Initially, OpenTelemetry Collector successfully collected the metrics. However, after processing a file containing a large number of logs (200,000), the collector encountered a soft limit on the pipeline metrics, resulting in the collection of only 120,000 logs. The situation resembled a "hard limit" scenario for logs, as the log flow was stopped and even after a 120-second pause, the logs were not retried

**Comment by marcinsiennicki95** [comment]
Another test

Communication between 2 Instances of OpenTelemetry Collector with memory_limiter processors 

**First OpenTelemetry Collector configuration**
```
receivers:
  filelog:
    include: [ C:/ERRORLOG ]
    encoding: utf-16le
    include_file_path: true
    max_log_size: 1MiB
    storage: file_storage
    poll_interval: 10s
    retry_on_failure:
        enabled: true
  
  hostmetrics:
    collection_interval: 2s
    scrapers:
      cpu:
      memory:

exporters:
  logging:

  otlphttp:
    endpoint: http://127.0.0.1:4320
    tls:
      insecure: true

extensions:
  file_storage:
    directory: C:/collector
    fsync: true

processors:
  batch:
    send_batch_size: 1000
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 250

service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [logging, otlphttp]
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [logging, otlphttp]
```
