### ISSUE TITLE
[exporter/opensearch-exporter] Unable to send traces to OpenSearch with TLS disabled

### ISSUE THREAD

**Issue by AmythD** [open-telemetry/opentelemetry-collector-contrib#31126]
### Describe the issue you're reporting

Hello,

My OpenSearch endpoint has TLS enabled using a self signed certificate, but while trying to connect from OTEL Collector, I am seeing errors when disabling TLS (insecure=true, and removed references to certificates)

Ideally I would like to have TLS disabled. Any suggestions on what could be wrong here?

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

extensions:
  basicauth/client:
    client_auth:
      username: admin
      password: admin

processors:
  batch:

exporters:
  opensearch/trace:
    dataset: otel
    namespace: traces
    http:
      endpoint: https://dev-opensearch.com:9200
      tls:
        insecure: true
        ca_file: /apps/PDC****-CA.crt
        cert_file: /apps/10.xx.xx.xx.crt         
        key_file: /apps/10.xx.xx.xx.key
       #insecure_skip_verify : true
      auth:
        authenticator: basicauth/client
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [opensearch/trace]
      processors: [batch]

  extensions: [basicauth/client]      

```

> 2024-02-08T10:41:30.168Z        warn        batchprocessor@v0.93.0/batch_processor.go:258        Sender failed        {"kind": "processor", "name": "batch", "pipeline": "traces", "error": "not retryable error: Permanent error: Permanent error: flush: tls: failed to verify certificate: x509: certificate signed by unknown authority\nPermanent error: Permanent error: flush: tls: failed to verify certificate: x509: certificate signed by unknown authority"}
