### ISSUE TITLE
You want to dynamically determine the topic when exporting with Kafka Exporter.

### ISSUE THREAD

**Issue by pyama86** [open-telemetry/opentelemetry-collector-contrib#31178]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

When adding log information to Kafka, you separate the topics by log file or type. However, currently, to do this, you need to write many exporter definitions.

### Describe the solution you'd like

You want to dynamically determine the topic from metadata, such as the file name obtained from the Filelog Receiver.

**Comment by shivanshu1333** [comment]
This looks like a reasonable request to me, if this gets triaged, would love to work on it.

**Comment by crobert-1** [comment]
Hello @pyama86, can you share a proposal for what the configuration of this option would look like?

**Comment by pyama86** [comment]
@crobert-1 
Thank you for your reply. I'm hoping to be able to make definitions like the ones below.
```yaml
receivers:
  filelog:
    include: [ /var/log/containers/*.log]
    operators:
      - type: json_parser

processors:
  # This processor is expected to extract k8s-related metadata from the logs,
  # and add it as attributes to the logs.
  k8sattributes:

exporters:
  kafka/custom:
    default_topic: default-topic
    brokers:
      - localhost:9092
    topic_from_attribute: k8s.app

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [k8sattributes]
      exporters: [kafka/custom]
```
It seems there's currently no way to access the attributes created by the processor, which would be very useful for various purposes.
