### ISSUE TITLE
Need an indication on how the LoadBalancingExporter works with a static list of hosts when a host is down

### ISSUE THREAD

**Issue by alexchowle** [open-telemetry/opentelemetry-collector-contrib#31209]
### Component(s)

exporter/loadbalancing

### Describe the issue you're reporting

With a static configuration of hosts in the LoadBalancingExporter configuration:

```
exporters:
  loadbalancing:
    routing_key: traceID
    protocol:
      otlp:
        tls:
          insecure: true
    resolver:
      static:
        hostnames:
          - host1:4317
          - host2:4317
```

If `host2` has its Collector stopped, it seems like all Spans that would normally be load-balanced to it would just be dropped instead of re-routing to `host1`. If that is the case then the README.md should make it clear.
