### ISSUE TITLE
Timestamp parse failure drops log record

### ISSUE THREAD

**Issue by nslaughter** [open-telemetry/opentelemetry-collector-contrib#31244]
### Component(s)

receiver/azureeventhub

## Description

The ResourceLogsUnmarshaler for the Azure records drops them when timestamp parsing fails. This is due to [this block](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a8b3a1b596dc46bc376db5cf46c475684edbfa76/pkg/translator/azure/resourcelogs_to_logs.go#L110-L114) in `pkg/translator/azure` which continues to the next record on timestamp parse failures without appending to log records.

## Steps to Reproduce

Run the `azureeventhubreceiver` and watch warnings in logs while no records are exported.

## Expected Result

Log records without timestamps.

## Actual Result

No log records.

### Collector version

0.94.0

## Environment
OS: Docker on OSX/AMD
Compiler(if manually compiled): go v1.21.6 (via `make docker-otelcontribcol`)

### OpenTelemetry Collector configuration

```yaml
receivers:
  azureeventhub:
    connection: ${AZURE_EVENTHUB_CONNECTION} 

exporters:
  otlp:
    endpoint: "${INGEST_ENDPOINT}"
    headers:
        "lightstep-access-token": "${LS_ACCESS_TOKEN}"

processors:
  batch:

service:
  telemetry:
    logs:
  pipelines:
    logs:
      receivers: [azureeventhub]
      processors: [batch]
      exporters: [otlp]
```

### Log output

```shell
2024-02-13T18:39:26.651Z	warn	azure@v0.94.0/resourcelogs_to_logs.go:112	Unable to convert timestamp from log	{"kind": "receiver", "name": "azureeventhub", "data_type": "logs", "timestamp": ""}
```

### Additional context

#27589 is related. 
We're likely going to do better by parsing to an RFC3339 timestamp instead of ISO8601, but I still believe that the current behavior in the case of parse failures is unexpected and we should change.
