### ISSUE TITLE
[extensions/headerssetter] fatal error: concurrent map writes - collector crashes when multiple exporters uses headers_setter

### ISSUE THREAD

**Issue by tdarwin** [open-telemetry/opentelemetry-collector-contrib#31289]
## Description
Daemonset collector instances have been crashing and restarting when having multiple exporters using the same instance of the `headers_setter` extension.  Collectors  eventually crash with the following error:
`fatal error: concurrent map writes`

## Steps to Reproduce
1. Setup a collector to receive OTLP metrics
2. Use the headers_setter extension to transmit a header via exporter [Honeycomb blog for example](https://www.honeycomb.io/blog/simplify-opentelemetry-pipelines-headers-setter)
3. Apply a header via the HS extension to multiple exporters (the more exporters, the faster you get crashes)
4. Send OTLP metrics through the collector for several minutes
5. Watch for the collector to crash

## Expected Result
Collector does not crash

## Actual Result
Collector crashes

### Collector version

0.94.0

## Environment
Kubernetes deployment via helm chart version 0.81.1.
Running in AWS/EKS, on Graviton3 processors

### OpenTelemetry Collector configuration

```yaml
mode: daemonset
service:
  enabled: true

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

presets:
  kubernetesAttributes:
    enabled: true
  logsCollection:
    enabled: false
  kubeletMetrics:
    enabled: true

# Adding a comment here to trigger the helm deployment
config:
  extensions:
    headers_setter:
      headers:
        - action: upsert
          key: x-honeycomb-dataset
          from_context: x-honeycomb-dataset
  receivers:
    jaeger: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
          include_metadata: true
        http:
          endpoint: ${env:MY_POD_IP}:4318
          include_metadata: true
    kubeletstats:
      collection_interval: 30s
      metrics:
        k8s.node.uptime:
          enabled: true
        k8s.pod.uptime:
          enabled: true
        container.uptime:
          enabled: true
        k8s.container.cpu_limit_utilization:
          enabled: true
        k8s.container.cpu_request_utilization:
          enabled: true
        k8s.container.memory_limit_utilization:
          enabled: true
        k8s.container.memory_request_utilization:
          enabled: true
        k8s.pod.cpu_limit_utilization:
          enabled: true
        k8s.pod.cpu_request_utilization:
          enabled: true
        k8s.pod.memory_limit_utilization:
          enabled: true
        k8s.pod.memory_request_utilization:
          enabled: true
    prometheus:
      config:
        scrape_configs:
        - job_name: opentelemetry-collector
          scrape_interval: 30s
          static_configs:
          - targets:
            - ${env:MY_POD_IP}:8888
  processors:
    batch:
      metadata_keys: 
        - x-honeycomb-dataset
      metadata_cardinality_limit: 30
    k8sattributes:
      extract:
        annotations:
        - from: pod
          key_regex: (.*)
          tag_name: $$1
        - from: node
          key_regex: (.*)
          tag_name: $$1
        labels:
        - from: pod
          key_regex: (.*)
          tag_name: $$1
        - from: node
          key_regex: (.*)
          tag_name: $$1
      passthrough: false
      pod_association:
      - sources:
        - from: resource_attribute
          name: k8s.pod.ip
      - sources:
        - from: resource_attribute
          name: k8s.pod.uid
      - sources:
        - from: connection
    attributes:
      include:
        match_type: strict
        services:
          - frontend-proxy
      actions:
        - key: net.component
          value: proxy
          action: insert
    transform:
      error_mode: ignore
      trace_statements:
        - context: span
          statements:
            - set(attributes["k8s.cluster.name"], "cs-k8s-sandbox")
            - set(attributes["http.response.status_code"], attributes["http.status_code"]) where attributes["http.status_code"] != nil and attributes["http.response.status_code"] == nil
        - context: spanevent
          statements:
            - set(attributes["k8s.cluster.name"], "cs-k8s-sandbox")
  exporters:
    otlp/unrefined:
      endpoint: "api.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
    otlp/refined:
      # sends to prrrod sampled environment on the ca team slack
      endpoint: "refinery.carefinery:4317"
      tls:
        insecure: true
      headers:
        "x-honeycomb-team": "REDACTED"
    otlp/dogfood-unrefined:
      endpoint: "api-dogfood.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
    otlp/eu-unrefined:
      endpoint: "api.eu1.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
    otlp/eu-refined:
      # sends to eu-prrrod sampled environment on the EU1 ca team slack
      endpoint: "hnytest.refinery.eu1.honeydemo.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
    otlp/dataset_hs_traffic:
      endpoint: "api.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
      auth:
        authenticator: headers_setter
    otlp/dataset_hs_traffic2:
      endpoint: "api.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
      auth:
        authenticator: headers_setter
    otlp/dataset_hs_traffic-dogfood:
      endpoint: "api-dogfood.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
      auth:
        authenticator: headers_setter
    otlp/eu-dataset_hs_traffic:
      endpoint: "api.eu1.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
      auth:
        authenticator: headers_setter
    otlp/eu-dataset_hs_traffic2:
      endpoint: "api.eu1.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
      auth:
        authenticator: headers_setter
    otlp/k8sMetrics:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-kubeletstats"
    otlp/dogfood-k8sMetrics:
      endpoint: "api-dogfood.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-kubeletstats"
    otlp/k8sMetrics2:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-kubeletstats"
    otlp/eu-k8sMetrics:
      endpoint: "api.eu1.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-kubeletstats"
    otlp/eu-k8sMetrics2:
      endpoint: "api.eu1.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-kubeletstats"
    otlp/otelColMetrics:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-collector-metrics"
    otlp/dogfood-otelColMetrics:
      endpoint: "api-dogfood.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-collector-metrics"
    otlp/otelColMetrics2:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-collector-metrics"
    otlp/eu-otelColMetrics:
      endpoint: "api.eu1.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-collector-metrics"
    otlp/eu-otelColMetrics2:
      endpoint: "api.eu1.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-collector-metrics"
    otlp/k8slogs:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-filelog"
    otlp/dogfood-k8slogs:
      endpoint: "api-dogfood.honeycomb.io:443"
      headers:
        "x-honeycomb-team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-filelog"
    otlp/k8slogs2:
      endpoint: "api.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-filelog"
    otlp/eu-k8slogs:
      endpoint: "api.eu1.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-filelog"
    otlp/eu-k8slogs2:
      endpoint: "api.eu1.honeycomb.io:443"
      headers:
        "X-Honeycomb-Team": "REDACTED"
        "X-Honeycomb-Dataset": "otel-filelog"
  service:
    telemetry:
      logs:
        level: DEBUG
        initial_fields:
          service: otel-daemonset
    extensions:
      - headers_setter
      - health_check
      - memory_ballast
    pipelines:
      traces:
        receivers: [ otlp ]
        processors: [ k8sattributes, transform, attributes, batch]
        exporters: [ otlp/unrefined, otlp/eu-unrefined, otlp/refined, otlp/eu-refined, otlp/dogfood-unrefined ]
      metrics:
        receivers: [ otlp ]
        processors: [ k8sattributes, batch ]
        exporters: [ otlp/dataset_hs_traffic, otlp/dataset_hs_traffic2, otlp/eu-dataset_hs_traffic, otlp/eu-dataset_hs_traffic2, otlp/dataset_hs_traffic-dogfood ]
      logs:
        receivers: [ otlp ]
        processors: [ k8sattributes, batch ]
        exporters: [ otlp/dataset_hs_traffic, otlp/dataset_hs_traffic2, otlp/eu-dataset_hs_traffic, otlp/eu-dataset_hs_traffic2, otlp/dataset_hs_traffic-dogfood ]
      metrics/k8s:
        receivers: [ kubeletstats ]
        processors: [ k8sattributes, transform, batch ]
        exporters: [ otlp/k8sMetrics, otlp/k8sMetrics2, otlp/eu-k8sMetrics, otlp/eu-k8sMetrics2, otlp/dogfood-k8sMetrics ]
      metrics/otelcol:
        receivers: [ prometheus ]
        processors: [ k8sattributes, transform, batch ]
        exporters: [ otlp/otelColMetrics, otlp/otelColMetrics2, otlp/eu-otelColMetrics, otlp/eu-otelColMetrics2, otlp/dogfood-otelColMetrics ]
      # logs/k8s:
      #   receivers: [ filelog ]
      #   processors: [ k8sattributes, batch ]
      #   exporters: [ otlp/k8slogs, otlp/k8slogs2, otlp/eu-k8slogs, otlp/eu-k8slogs2, otlp/dogfood-k8slogs ]

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    # The metrics port is disabled by default. However you need to enable the port
    # in order to use the ServiceMonitor (serviceMonitor.enabled) or PodMonitor (podMonitor.enabled).
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

clusterRole:
  create: true
  rules:
    - apiGroups: 
        - ""
      resources:
        - nodes/proxy
      verbs:
        - get
    - apiGroups:
        - ""
      resources:
        - nodes
      verbs:
        - get
        - watch
        - list
```

### Log output

```shell
Will add stack trace as comments, as it's 7200 lines long and causes this submission to fail.
```

### Additional context

Have tried duplicating the extension and using the second extension for a second exporter, but still got a crash/restart of the pod.
