### ISSUE TITLE
[clickhouseexporter]incorrect values of exemplar span id and trace id

### ISSUE THREAD

**Issue by cezhang** [open-telemetry/opentelemetry-collector-contrib#31332]
### Component(s)

exporter/clickhouse

## Description
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/5362164/ea535cd2-d202-4610-b8e1-c7b505696014)

spanId and traceId are put in wrong column between each other
## Steps to Reproduce

On my case, just use java agent to do auto instrumentation.

I check the source code of this exporter. It seems fine, probably somewhere go wrong with exemplar data.

## Expected Result
The value of spanid and trace id should be swapped.

### Collector version

0.9.2

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        timeout: 15s
        send_batch_size: 100000
    exporters:
      debug:
        verbosity: detailed
      clickhouse:
        endpoint: tcp://proxy.o11y.svc.cluster.local:9000?dial_timeout=10s&compress=lz4
        database: otel
        ttl: 72h
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        metrics_table_name: otel_metrics
        timeout: 5s
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
      prometheus:
        endpoint: ':8889'
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse, prometheus]
```
