### ISSUE TITLE
OTTL Filter Processor doesn't seem to work for traces

### ISSUE THREAD

**Issue by akshat-io** [open-telemetry/opentelemetry-collector-contrib#31355]
### Component(s)

processor/filter

## Description
As per the [docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#dropping-http-spans), the filter processor with the config to drop all HTTP spans, should have dropped all spans having 'GET' HTTP method. But they are still showing in Jaeger UI.

## Steps to Reproduce
1. Clone the repo: https://github.com/akshat-io/spring-cloud-open-telemetry-filter-processor-issue
2. Use JDK 17 on your system.
3. Change directory into project: `cd spring-cloud-open-telemetry-filter-processor-issue`
4. Run command: `./mvnw clean install`
5. After running 4th step successfully, run command: `docker compose up`
6. It should spin up both Java Applications, OpenTelemetry Collector and Jaeger.
7. Go to Jaeger UI: http://localhost:16686/search
8. Call Product API by opening below links in the browser: 
    http://localhost:8080/product/100002
    http://localhost:8080/product/100003
    http://localhost:8080/product/100004
9. Jaeger UI at http://localhost:16686/search should be showing some traces.

## Expected Result
No traces should be showing in Jaeger UI. As all spans with HTTP request method should have filtered out by the otel-config filter defined [here](https://github.com/akshat-io/spring-cloud-open-telemetry-filter-processor-issue/blob/81659444cdc114aaea787c5a41ff6a4492139c35/otel-config.yml#L8).

## Actual Result
The traces are still coming for HTTP spans.

Multiple conditions have been checked, including custom attributes, but the same issue is happening with all.

### Collector version

0.81.0

## Environment
OS: Ubuntu 20.04
Compiler(if manually compiled): Did not compile collector manually, instead used docker image for collector version "0.81.0"
Container: Docker & Docker Compose 
(Used docker to start the applications, collector and jaeger).

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  filter/drophttp:
    error_mode: ignore
    traces:
      span:
        - attributes["http.method"] != nil
  batch:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-service:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, jaeger ]
```

**Comment by TylerHelmuth** [comment]
You configured `filter/drophttp` but did not add it to the traces pipeline:

```yaml
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ filter/drophttp, batch ]
      exporters: [ logging, jaeger ]
```

**Comment by krishnaexplore** [comment]
i've used in reverse for some other requirement (my_attribute), it only captures that span not entire trace.. what should i configure capture entire trace

```yml filter/drophttp:
        error_mode: ignore
        traces:
          span:
            - attributes["my_attribute"] == nil
```

**Comment by akshat-io** [comment]
@krishnaexplore I was going to ask the same thing as well. My use-case is also similar to you.

I want to get the complete trace, but only when a custom attribute `productId` is added to the parent (root) span of that trace.

My filter processor is as follows:

```
processors:
  filter/productidonly:
    error_mode: ignore
    traces:
      span:
        - attributes["productId"] == nil
```

 I have modified the same repo to reproduce this:
 The repo: https://github.com/akshat-io/spring-cloud-open-telemetry-filter-processor-issue
 
 I have added a custom attribute `productId` to the span but only when the productId queried is `100004`.

The filter is working and only when we hit below URL.
http://localhost:8080/product/100004

The trace comes for `Product Service` with this `productId` only, but not the other products like `100001`, `100002` etc.

But now it doesn't contain lower level spans, which I need.

@TylerHelmuth What can be the approach to get the whole trace on the basis of some custom attribute, which is only added on the root / parent span and not to the child spans.
