### ISSUE TITLE
otlp endpoint required on loadbalancingexporter config

### ISSUE THREAD

**Issue by kurayama** [open-telemetry/opentelemetry-collector-contrib#31371]
### Component(s)

exporter/loadbalancing

## Description
Since https://github.com/open-telemetry/opentelemetry-collector/pull/9523, the endpoint inside `otlp` became mandatory and for it to work we needed to add a bogus endpoint that is replaced by the resolver later on.
The documentation states:

> The otlp property configures the template used for building the OTLP exporter. Refer to the OTLP Exporter documentation for information on which options are available. Note that the endpoint property should not be set and will be overridden by this exporter with the backend endpoint.

Which is not true anymore.

### Collector version

v0.95.0

## Environment
0.95 tag for the dockerhub image

### OpenTelemetry Collector configuration

```yaml
exporters:
  loadbalancing:
    protocol:
      otlp:
        timeout: 1s
        tls:
          insecure: true
    resolver:
      k8s:
        service: <our-internal-endpoint>
```

### Log output

```shell
Error: invalid configuration: exporters::loadbalancing: requires a non-empty "endpoint"
2024/02/21 18:08:46 collector server run finished with error: invalid configuration: exporters::loadbalancing: requires a non-empty "endpoint"
```
