### ISSUE TITLE
Add service name as attribute

### ISSUE THREAD

**Issue by dhilgarth** [open-telemetry/opentelemetry-collector-contrib#31409]
### Component(s)

receiver/dockerstats

### Is your feature request related to a problem? Please describe.

In Docker Swarm, the unit of aggregation I often care about is the total usage of a service per host.
This is currently not possible.

### Describe the solution you'd like

Add a new attribute for the service name

### Describe alternatives you've considered

- grouping by container_image_name, host_name (from OTEL_RESOURCE_ATTRIBUTES): Close, but I could have different services using the same image and also, I am looking for the service name, so I would need to deduct the service name from the image name
- Derive from `container_name`, e.g. via `label_replace` in PromQL: Works, but is quite a handful which I would need to use in each query instead of simply selecting the label. For reference: `label_replace(container_memory_usage_total, "container_service_name", "$1", "container_name", "^([^.]+)\\..*")`

**Comment by jamesmoessis** [comment]
@dhilgarth have you considered using the `resourceprocessor` to add the service name attribute?

**Comment by dhilgarth** [comment]
@jamesmoessis Thanks, this works beautifully

```
receivers:
  ...
  docker_stats:
    ...
processors:
  ...
  resource:
    attributes:
      - key: container.name
        pattern: ^(?P<container_service_name>[^.]+)\..*
        action: extract

exporters:
...

service:
  pipelines:
    ...
    metrics/generic:
      receivers: [ docker_stats, ... ]
      processors: [ resource, ...]
      exporters: [ ...]

```
