### ISSUE TITLE
New component: Google Client Auth Extension

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-collector-contrib#31412]
### The purpose and use-cases of the new component

Google Client Auth Extension provides Google OAuth2 Client Credentials and Metadata for gRPC and http based exporters. It allows exporters to authenticate with GCP and send telemetry to endpoints in Google Cloud.

### Example configuration for the component

```
extensions:
  googleclientauth:
    project: my-project
    quota_project: billing-project
    scopes:
    - "https://www.googleapis.com/auth/cloud-platform"

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp/withauth:
    endpoint: 0.0.0.0:5000
    ca_file: /tmp/certs/ca.pem
    auth:
      authenticator: googleclientauth

service:
  extensions: [googleclientauth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [otlp/withauth]
```

### Telemetry data types supported

traces, metrics, logs

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [x] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

dashpole, damemi

### Sponsor (optional)

dashpole

### Additional context

Component is currently available downstream at https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/87124ac8635698cc7cdc9f8f2dfca94a8aa13606/extension/googleclientauthextension
