### ISSUE TITLE
OTTL Converter Slice Index

### ISSUE THREAD

**Issue by fredyfredburger** [open-telemetry/opentelemetry-collector-contrib#31482]
### Component(s)

pkg/ottl

## Description
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/LANGUAGE.md
Per this documentation it should be possible to do int referencing from the result of Slice(), but it is not because type []String does not support int indexing.
## Steps to Reproduce
Below I am attempting to set application name by taking the body of a /var/log/messages log and indexing into the 5th value (assuming 0-base indexes)
set(resource.attributes["application_name"], Slice(body, " ")[4])
## Expected Result
Since slice returns an array, I should be able to use an int to grab the nth value.
## Actual Result
"type, []string, does not support int indexing"

### Collector version

7ac560f

## Environment
OS: (Amazon Linux 2)
Compiler(if manually compiled): go 1.21.5

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include:
      - /var/log/messages
    include_file_name: true
    include_file_path: true
    operators:
      - type: syslog_parser
        protocol: rfc3164
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
  batch:
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources:
      resource_attributes:
        host.ip:
          enabled: true
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["application_name"], Split(body, " ")[4])
exporters:
  otlphttp:
    endpoint: https://localhost:8201
    headers:
      Authorization: "Bearer notsosecrettoken"
    tls:
      insecure_skip_verify: true
service:
  telemetry:
    metrics:
      level: none
  pipelines:
    logs:
      receivers: [filelog]
      processors: [transform, memory_limiter, resourcedetection, batch]
      exporters: [otlphttp]
```

### Log output

```shell
2024-02-28T13:18:57.248Z        warn        ottl@v0.94.0/parser.go:273        failed to execute statement        {"kind": "processor", "name": "transform", "pipeline": "logs", "error": "type, []string, does not support int indexing", "statement": "set(resource.attributes[\"application_name\"], Split(body, \" \")[4])"}
```
