### ISSUE TITLE
[exporter/datadog] Update span_name_remappings examples

### ISSUE THREAD

**Issue by hanikesn** [open-telemetry/opentelemetry-collector-contrib#31483]
### Component(s)

exporter/datadog

## Description
The examples use outdated behavior and do not give expected results. The expected format is `# "otel.library.name/ScopeName"."span.kind"` See:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a257d0f86bced167cd57bd44ae1e4137b86c2664/exporter/datadogexporter/examples/collector.yaml#L318-L321

### Collector version

0.95

### OpenTelemetry Collector configuration

```yaml
exporters:
  datadog:
    traces:
      span_name_remappings:
        # "otel.library.name"."span.kind"
        "go.opentelemetry.io/contrib/instrumentation/github.com/labstack/echo/otelecho/echo.server": echo.server
        "go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.client": http.client
        "go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.client": grpc.client
        "go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.server": grpc.server
```
