### ISSUE TITLE
[simple prometheus receiver]Support customized job name in configuration

### ISSUE THREAD

**Issue by chenlujjj** [open-telemetry/opentelemetry-collector-contrib#31502]
### Component(s)

receiver/simpleprometheus

### Is your feature request related to a problem? Please describe.

Hi team, we use the simple prometheus receiver within the receiver creator to scrape metrics from k8s pods with specific annotations, the config is like:
```
receiver_creator/application:
      receivers:
        prometheus_simple/app_pods:
          rule: type == "port" && pod.annotations["prometheus.io/scrape"] == "true" && ( string(port) == pod.annotations["prometheus.io/port"] || name == pod.annotations["prometheus.io/port"] )
          config:
            endpoint: '`endpoint`'
            metrics_path: '`"prometheus.io/path" in pod.annotations ? pod.annotations["prometheus.io/path"] : "/metrics"`'
            collection_interval: '`"prometheus.io/collection_interval" in pod.annotations ? pod.annotations["prometheus.io/collection_interval"] : "30s"`'
```
it works good, but a small problem is that the simple prometheus receiver uses the `prometheus_simple/$endpoint` as the `job name` which would be transformed to `service.name` label in the metric.

It will be great if we can customize the job name here.

### Describe the solution you'd like

Add a job name setting in the configuration. The setting is optional.
