### ISSUE TITLE
newrelicexporter - A value is required for "name"

### ISSUE THREAD

**Issue by strangeminds** [open-telemetry/opentelemetry-collector-contrib#3151]
In New Relic `NrIntegrationError` events we're seeing an error when pushing traces to New Relic using the exporter.

```
Bad Request
Distributed Tracing
MissingValueException
A value is required for "name".
```

We've been using the `opentelemetry-collector` for weeks now and it just started to show up on April 6th.  I'm not sure if this is something that changed on New Relic's API.

This is our ConfigMap for the exporter.

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: jaeger
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      jaeger:
        protocols:
          grpc:
          thrift_http:
            endpoint: ":14268"
          thrift_compact:
          thrift_binary:
      zipkin:
    processors:
      batch:
    extensions:
      health_check: {}
    exporters:
      jaeger:
        endpoint: all-in-one-collector.jaeger.svc.cluster.local:14250
        insecure: true
      newrelic:
        apikey: 123abc
        timeout: 30s
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [jaeger, zipkin]
          processors: [batch]
          exporters: [jaeger, newrelic]
```

Thank you.
