### ISSUE TITLE
error creating file exporter: open ./filename.json: permission denied

### ISSUE THREAD

**Issue by 5idu** [open-telemetry/opentelemetry-collector-contrib#3159]
**Describe the bug**
1. my config.yml
```yml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  
exporters:
  file:
    path: ./filename.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [file]
```

2. my docker-compose.yml
```yml
version: "2"
services:
  # Agent
  otel-agent:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "14250"       # Jaeger grpc receiver
      - "14268"       # Jaeger http thrift receiver
      - "55678"       # OpenCensus receiver
      - "4317"        # OTLP gRPC receiver
      - "9411"        # Zipkin receiver
      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
      - "13133"       # health_check
      - "55681:55681"
```

3. my .env file
```
OTELCOL_IMG=otel/opentelemetry-collector-contrib:latest
OTELCOL_ARGS=
```

**What did you expect to see?**
application started success.

**What did you see instead?**
when i run `docker logs`, then i see:
```
Error: cannot build pipelines: cannot build builtExporters: error creating file exporter: open ./filename.json: permission denied
2021/04/17 16:00:48 application run finished with error: cannot build pipelines: cannot build builtExporters: error creating file exporter: open ./filename.json: permission denied
```

**Comment by Jammicus** [comment]
This appears to be an issue in the opentracing-collector rather than the contrib as thats where the exporter lives. This is affecting both contrib and normal collector versions when trying to run in docker compose.

Cause is that the process is trying to create filename.json in the root of the docker-compose environment without the correct permissions. 

A way to get around this, is create a local file called "filename.json" in the directory you are running docker-compose in, and update your compose file to copy that file in like so:

```
version: "2"
services:
  # Agent
  otel-agent:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
      - ./filename.json:/filename.json
    ports:
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "14250"       # Jaeger grpc receiver
      - "14268"       # Jaeger http thrift receiver
      - "55678"       # OpenCensus receiver
      - "4317"        # OTLP gRPC receiver
      - "9411"        # Zipkin receiver
      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
      - "13133"       # health_check
      - "55681:55681"

```

**Comment by 5idu** [comment]
@Jammicus Thank you very much for your help, the problem has been solved.

**Comment by rahjesh-vunet** [comment]
This is not fixed yet. Tried all these workarounds. Still I am unable to make it work.

My docker-compose looks like.
  ```
tracing-server:
    image: otel/opentelemetry-collector:latest
    container_name: tracing-server
    mem_limit: 512M
    volumes:
      - ./otel:/otel
      - ./filename.json:/filename.json:rw
    command: --config /otel/collector.yaml
    ports:
      - 55679:55679
      - 55680:55680
```

tracing-server       | 2022-02-01T16:43:55.368Z	info	service/service.go:143	Starting extensions...
tracing-server       | 2022-02-01T16:43:55.368Z	info	service/service.go:188	Starting exporters...
tracing-server       | 2022-02-01T16:43:55.368Z	info	builder/exporters_builder.go:93	Exporter is starting...	{"kind": "exporter", "name": "file"}
tracing-server       | Error: cannot setup pipelines: cannot start builtExporters: open ./filename.json: permission denied
tracing-server       | 2022/02/01 16:43:55 application run finished with error: cannot setup pipelines: cannot start builtExporters: open ./filename.json: permission denied
