### ISSUE TITLE
Docker logs receiver

### ISSUE THREAD

**Issue by aboguszewski-sumo** [open-telemetry/opentelemetry-collector-contrib#31597]
### The purpose and use-cases of the new component

There are three types of logs that can be scraped:

- [daemon logs](https://docs.docker.com/config/daemon/logs/) - these can actually be scraped by using already existing receivers (there is even no API endpoints for these), the only problem is that the method differs between systems. Also, it seems that the API doesn't allow to scrape them.
- container logs
- [events](https://docs.docker.com/engine/api/v1.44/#tag/System/operation/SystemEvents), which usually are being transformed to logs (for example in [k8sevents receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver). In terms of events, please see also `Additional context` section.

Currently Docker container logs can be fetched by using `filelog` receiver. However, there are cases where you can't access the files, but can access Docker API (@swiatekm-sumo please elaborate if needed). I'm not aware of receivers able to scrape daemon logs and events.

### Example configuration for the component

This is something worth discussing in this issue. Below config should express what I think we need:

```yaml
dockerlogs:
    events:
      enabled: true
      filters:
        ## to be discussed, see https://docs.docker.com/engine/api/v1.44/#tag/System/operation/SystemEvents

    container:
      enabled: true
      excluded_containers: 
        - *-nginx
        - custom-container
      ## possibly more, see https://docs.docker.com/engine/api/v1.44/#tag/Container/operation/ContainerLogs

    daemon:
    ## Let's skip these for now

    ## these are taken directly from dockerstats receiver
    endpoint: unix:///var/run/docker.sock
    collection_interval: 2s
    timeout: 20s
    api_version: 1.24
```

where I could, I tried to be consistent with `dockerstats` receiver.

### Telemetry data types supported

Logs, but see also `Additional context` section.

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@aboguszewski-sumo and possibly more people from Sumo Logic 

### Sponsor (optional)

@astencel-sumo

### Additional context

There is already an issue with regard to Docker events: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29096
Also, there is [`dockerstats` receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/dockerstatsreceiver), but currently it scrapes only metrics.

Now, the question is: how should we resolve the potential connection between these three? We can either:

- refactor `dockerstats` receiver and add scraping logs and events there
- create a new receiver for both logs and events
- create a new receiver for logs and add scraping events to `dockerstats` receiver
- ...some other options that didn't seem reasonable for me

If you look at the issue linked above, we can see that codeowners of `dockerstats` receiver approved the idea of scraping events.
