### ISSUE TITLE
AWS PRW Exporter should default to workspace region for SigV4

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector-contrib#3162]
Currently, users have to manually select a region in the configuration, but we should identify the region automatically from the workspace URL.

Today the config looks like below:
```
exporters:
  awsprometheusremotewrite:
    endpoint: "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-XXX/api/v1/remote_write"
    aws_auth:
        region: "us-east-1"
```

With the improvement, it will look like:

```
exporters:
  awsprometheusremotewrite:
    endpoint: "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-XXX/api/v1/remote_write"
```

I'm already working on it, please don't duplicate the work.
