### ISSUE TITLE
New component: grafanacloudconnector

### ISSUE THREAD

**Issue by rlankfo** [open-telemetry/opentelemetry-collector-contrib#31647]
### The purpose and use-cases of the new component

The Grafana Cloud Connector (`grafanacloudconnector`) is a connector component that can analyze telemetry in  pipelines to generate usage metrics for certain Grafana Cloud products.

### Example configuration for the component

```yaml
connectors:
  grafanacloud:
    host_identifiers: [ "host.id" ]
    metrics_flush_interval: 60s
```

### Telemetry data types supported

* traces to metrics

Potentially in the future, logs to metrics or metrics to metrics would be supported as well.

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

rlankfo, jcreixell

### Sponsor (optional)

jpkrohling
