### ISSUE TITLE
exporter kafka cause otel-collector start fail

### ISSUE THREAD

**Issue by zhboseu** [open-telemetry/opentelemetry-collector-contrib#31677]
### Component(s)

exporter/kafka

## Description
exporter kafka cause otel-collector start fail, both rpc port and http port start fail, report Connection closed 

## Actual Result
telnet 127.0.0.1 4317 

Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host

### Collector version

0.96.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      # 4317
      grpc:
      # 4318
      http:

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 5000
    spike_limit_mib: 1000

  batch:
    send_batch_max_size: 0
    send_batch_size: 8192
    timeout: 200ms

exporters:
  kafka:
    protocol_version: 2.0.0
    brokers:
      - "kafka:9092"
    auth:
      tls:
        insecure: true
        insecure_skip_verify: true
    encoding: otlp_proto
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 120s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 100

extensions:
  health_check:
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "1m"
      exporter_failure_threshold: 5

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: "debug"
      development: true
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter,batch]
      exporters: [kafka]
```

### Log output

```shell
2024-03-11T14:13:04.309+0800	info	service@v0.96.0/telemetry.go:55	Setting up own telemetry...
2024-03-11T14:13:04.309+0800	info	service@v0.96.0/telemetry.go:97	Serving metrics	{"address": "0.0.0.0:8888", "level": "Basic"}
2024-03-11T14:13:04.309+0800	debug	extension@v0.96.0/extension.go:165	Beta component. May change in the future.	{"kind": "extension", "name": "health_check"}
2024-03-11T14:13:04.309+0800	debug	exporter@v0.96.0/exporter.go:273	Beta component. May change in the future.	{"kind": "exporter", "data_type": "traces", "name": "kafka"}
```
