### ISSUE TITLE
[connector/spanmetrics] Delta span metric StartTimeUnixNano doesn't follow specification

### ISSUE THREAD

**Issue by swar8080** [open-telemetry/opentelemetry-collector-contrib#31671]
### Component(s)

connector/spanmetrics

## Expected Behaviour

The [specification](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#temporality) on metric temporality expects uninterrupted series of delta data points to have timestamps like below:

<img width="776" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/17691679/93b5492e-c671-4ed5-b00f-218c80bfc9c7">

## Actual Behaviour

When configuring `spanmetricsconnctor` to use delta temporarily, the timestamps of successive data points follow the pattern `(T1, T1), (T2, T2), (T3, T3)`.  Basically the `StartTimeUnixNano` and `TimeUnixNano` are always set to the current timestamp.

When configured to use cumulative temporality, the connector caches `StartTimeUnixNano` so that it can be used in the next data point. However, when using delta temporality that cache (`resourceMetrics`) gets wiped after each round of exporting metrics:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/71e6c553f73feb6ea99f3f9d625c42e2267a8ec3/connector/spanmetricsconnector/connector.go#L283-L301

### Collector version

v0.94.0

### Environment information

Testing done locally on mac OS

### OpenTelemetry Collector configuration

```yaml
connectors:
  spanmetrics:
    dimensions_cache_size: 5000
    resource_metrics_key_attributes:
      - service.name
    aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"
    metrics_flush_interval: 5s
    exemplars:
      enabled: true
    histogram:
      explicit:
        buckets: ...

exporters:
  prometheus/exporter:
    endpoint: "0.0.0.0:9465"
    enable_open_metrics: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: []
      exporters: [prometheus/exporter]
```

## Why fix this? 
This could be a different way of fixing https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30688 and https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30559. It could also significantly reduce memory usage when combining `spanmetricsconnector` with exporters like `prometheusexporter`.

## Issue with Prometheus Exporter

`prometheusexporter` supports conversion from delta to cumulative temporality. However, it only works if the series follows the specification:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/71e6c553f73feb6ea99f3f9d625c42e2267a8ec3/exporter/prometheusexporter/accumulator.go#L203-L212

I think the author's rationale is the delta series seems reset based on [this part of the spec](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#resets-and-gaps). So with the current delta span metric behaviour, prometheus views each data point as if the counter was reset. 

A workaround is having the connector produce cumulative span metrics, but that requires the connector caching all series in memory, which is redundant since `prometheusexporter` already does this. @matej-g is working on an improvement to expire infrequently updated series from the cache which will definitely help with reducing memory.

## Solution Discussion

Having delta span metrics follow the spec could significantly reduce memory usage when used with `prometheusexporter`.

To do this, I think the connector could probably have to cache the `StartTimeUnixNano` for each series when in delta mode. The currently cached value for each series are much larger since they include things like metric attributes and histogram bucket sizes
