### ISSUE TITLE
Memory leaks for Sum metric exemplars

### ISSUE THREAD

**Issue by tiithansen** [open-telemetry/opentelemetry-collector-contrib#31683]
### Component(s)

connector/spanmetrics

## Description

There is a memory leaks if exemplars are enabled. In file [connector.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/97f685e04fd1b4c77c47d17a320d9d28857e9bd8/connector/spanmetricsconnector/connector.go#L296-L298) histogram exemplars are reset with every export but sum metrics exemplars are not.

## Expected Result

Memory usage should be steady depending how much metrics are being generated.

## Actual Result

Memory usage keeps growing until process gets OOM killed in k8s cluster.

### Collector version

v0.95.0

**Comment by crobert-1** [comment]
I'm not super familiar with this connector, but following your comment it looks like the following lines should potentially be added:
```
			m.events.Reset()
			m.sums.Reset()
```
To this section:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d4458d9f6e97d77c3b34e179ef02a3796065f3cf/connector/spanmetricsconnector/connector.go#L301-L313

This would need to be confirmed through testing though, and preferably a long running test doing memory analysis on the collector to ensure this actually resolves it.

**Comment by tiithansen** [comment]
We are running, slightly modified (adding exemplars if specific attribute is set on span) version in production with 150k spans per second going through this connector. Before applying fix it got OOM killed (8GB limit in 5 instances total 40GB) in half an hour or so. After applying change, its has been steady 200 - 300 MB for days now.

**Comment by crobert-1** [comment]
Would you be able to share your fix, or even post a PR?

**Comment by tiithansen** [comment]
I will create a PR soon.

**Comment by tcaty** [comment]
Hi @crobert-1 and @tiithansen I can confirm that issue really exists. We use helm chart [opentelemetry-collector-0.82.0](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/opentelemetry-collector-0.82.0/charts/opentelemetry-collector) with `otel/opentelemetry-collector-contrib:0.95.0` to deploy it in k8s cluster. I'll share our config details that probably relates to this issue.
<details>
  <summary>values.yml</summary>

  ```
mode: "deployment"

config:
  receivers:
    otlp:
      protocols:
        http: {}
    prometheus:
      config: 
        scrape_configs:
          - job_name: otel-collector-metrics
            scrape_interval: 15s
            static_configs:
            - targets: ['localhost:8888']

  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 4000
      spike_limit_percentage: 20
    batch: {}

  exporters:
    prometheus:
      endpoint: "0.0.0.0:8889"
      enable_open_metrics: true

  connectors:
    spanmetrics:
      exemplars:
        enabled: true
            
  extensions:
    pprof:
      endpoint: "0.0.0.0:1777"

  service:
    ...
           
resources:
  requests:
    cpu: 100m
    memory: 2Gi
  limits:
    memory: 4Gi
useGOMEMLIMIT: true
```
</details>

There are our metrics between 6:00 a.m. and 8:00 a.m. on screenshots below, may be they will be useful.

<details>
  <summary>screenshots</summary>

Crucial points:
 * 6:00 a.m. - otel-collector started with minimal load
 * 7:00 a.m - otel-collector reached limits

Pod resources

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/79706809/d9a8b9e6-77df-4df3-9327-7c56d2718fa5)

Pprof at 6:00 a.m.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/79706809/086e4da5-dcd9-4099-9554-f52b816a2529)

Pprof at 7:00 a.m.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/79706809/9cead9d1-866b-477b-8953-035011a16761)

And some otel-collector metrics

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/79706809/9ea0ce71-22d2-472f-9095-5d2307d6fbd0)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/79706809/d7843e12-6d07-4639-9eb5-cd86c4779cc9)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/79706809/c46f1ea2-2979-472f-a18a-b353b4ccc393)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/79706809/aea36f8b-0731-4f5c-9ff1-7e9fd4984c86)

</details>

We'll try to run otel-collector without exemplars generation and I'll be back with feedback about resource usage.
