### ISSUE TITLE
Support external queue system for exporter via extensions

### ISSUE THREAD

**Issue by pepperkick** [open-telemetry/opentelemetry-collector-contrib#31682]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I want the ability to utilize Redis as the exporter queue to support upstream outages for longer period. The current two options of exporter do not fulfill the requirements or have issues with longer outages.

This usecase came up because I needed near 0% data loss on logs over long periods of time because the upstream is known to be down for many mins. The in-memory queue was ruled out because it would lose data on pod restarts. The persistent queue option was promising but it started refusing new data if the queue is full and based on the code it is difficult to disable the refusal which causes loss of new data once the queue is full.

So since I had access to a Redis cluster, I decided to modify the exporter to support Redis as the queue. I was able to test this and get stable data flow, however I was not able to do proper and long testing yet.

Can this feature be implemented via extensions so in future other queue systems could be added as well? I believe the existing queue systems will need to moved to extensions in that case. 

### Describe alternatives you've considered

Alternatives considered
- In-memory Queue: As mentioned, data is lost if the pod restarts due to crashes.
- Persistent Queue: Starts refusing new data when the queue is full.
- Export to Pulsar, receive from Pulsar: This does work, but the 2nd collector still needs one of the above queue during exporting, ending up in same situation.

### Additional context

Config example
```yaml
exporters:
  logging:
  otlp:
    endpoint: "localhost:4217"
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 5s
      max_elapsed_time: 20s
    sending_queue:
      enabled: true
      requeue_enabled: true
      queue_backend: redis
      num_consumers: 10
      queue_size: 10000
      redis:
        address: "localhost:6379"
        backlog_check_interval: 30
        process_key_expiration: 120
        scan_key_size: 10
    tls:
      insecure: true
```
While queue_size is mentioned 10000, it is actually unlimited because redis can scale up based on usage.

**Comment by djaglowski** [comment]
I may be mistaken but isn't the sending queue designed to work with any storage extension? If so, all that is needed is another storage extension. Then, rather than configure redis as part of the exporter, you configure it as an extension and reference it in the exporter. Adapting the example:

```yaml
extensions:
  redisstorage:
    address: "localhost:6379"
    backlog_check_interval: 30
    process_key_expiration: 120
    scan_key_size: 10

exporters:
  logging:
  otlp:
    endpoint: "localhost:4217"
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 5s
      max_elapsed_time: 20s
    sending_queue:
      enabled: true
      storage: redisstorage # refers to component name of extension configured above
      requeue_enabled: true
      queue_backend: redis
      num_consumers: 10
      queue_size: 10000
    tls:
      insecure: true
```
