### ISSUE TITLE
Elasticexporter - retry_on_failure not working (and other exporterhelper features) 

### ISSUE THREAD

**Issue by intonet** [open-telemetry/opentelemetry-collector-contrib#3169]
**Describe the bug**
exporterhelper features not working with elastic exporter https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper

**Steps to reproduce**
add retry_on_failure to configuration

**What did you expect to see?**

**What did you see instead?**
```
2021-04-19T07:19:02.972Z	info	service/application.go:250	Loading configuration...
Error: cannot load configuration: error reading exporters configuration for elastic: 1 error(s) decoding:

* '' has invalid keys: retry_on_failure
2021/04/19 07:19:02 application run finished with error: cannot load configuration: error reading exporters configuration for elastic: 1 error(s) decoding:

* '' has invalid keys: retry_on_failure
```
**What version did you use?**
Version: image: otel/opentelemetry-collector-contrib:0.24.0

**What config did you use?**
Config: 
```
exporters:
  elastic:
    apm_server_url: "xxx"
    retry_on_failure:
      enabled: true
```

**Environment**
OS: k8s

**Additional context**
I have some time to time messages in otelcollector: 
`2021-04-19T07:13:10.264Z	error	exporterhelper/queued_retry.go:243	Exporting failed. Try enabling retry_on_failure config option.	{"kind": "exporter", "name": "elastic", "error": "[sending event request failed: Post \"xxxxx/intake/v2/events\": context deadline exceeded;`
so i try to turn it on.

**Comment by cyrille-leclerc** [comment]
Hello @intonet . Sorry for the delay.

**Can you please consider migrating to the native OpenTelemetry Protocol support that was GA in Elastic 7.13?**

Please see our documentation https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html .
You would have to
* Upgrade Elastic (APM Server, Elasticsearch, Kibana) to v7.13
* Replace on you OpenTelemetry Collector the Elastic Exporter by the OTLP exporter. It would look like

```

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '127.0.0.1:4317'
  hostmetrics:
    collection_interval: 1m
    scrapers:
      # cpu not supported on MacOS
      # cpu:
      load:
      memory:
processors:
  batch: null
exporters:
  otlp/elastic:
    endpoint: "localhost:8200"
    insecure: true
    headers:
      Authorization: "Bearer my_secret_token"
service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - hostmetrics
      exporters:
        - otlp/elastic
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/elastic
```
