### ISSUE TITLE
[exporter/datadog] Trace stats are severely underreporting hit counts

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-collector-contrib#31713]
### Component(s)

exporter/datadog

## Description
The `trace.*` stats calculated within the `datadogexporter` are severely underreporting hit counts in many cases.

We confirmed this by comparing the span counts 
* Returned by an [APM query](https://ccloud-staging.datadoghq.com/s/027e3e6e3/xhy-k78-u6b)
* To that returned by a [query on `trace.*` metrics](https://ccloud-staging.datadoghq.com/s/027e3e6e3/vt3-tum-z75)

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/381302/4688cc30-2693-43ed-88fe-80e410419e6f)

Strangely, this discrepancy is not observed for a few HTTP routes (e.g. `/metrics/logical_clusters` in the above screenshot).

We do not have sampling enabled anywhere in our OTel Collector configuration.

### Collector version

v0.93.0

## Environment
Kubernetes

### OpenTelemetry Collector configuration

```yaml
exporters:
  datadog
    metrics:
      resource_attributes_as_tags: true
      instrumentation_scope_metadata_as_tags: true
      summaries:
        mode: noquantiles
    traces:
      compute_stats_by_span_kind: false
      peer_tags_aggregation: false
      trace_buffer: 1000

    host_metadata:
      enabled: false
    sending_queue:
      queue_size: 200
```
