### ISSUE TITLE
filestats's "file.path" resource has the wrong directory

### ISSUE THREAD

**Issue by ubcharron** [open-telemetry/opentelemetry-collector-contrib#31738]
### Component(s)

receiver/filestats

## Description

When `resource_attributes.file.path.enabled` is true, the resource attribute "`file.path`" has the current working directory rather than the one from the include statement.

## Steps to Reproduce

Enable "resource_attributes.file.path" and include a glob path that is not under the current working directory.

```yaml
receivers:
    filestats:
      include: /tmp/*
      resource_attributes:
        file.path:
          enabled: true
```

## Expected Result

```
     -> file.path: Str(/tmp/myfile)
```
## Actual Result

```
     -> file.path: Str(/home/bcharron/myfile)
```

### Collector version

0.96.0

### OpenTelemetry Collector configuration

```yaml
exporters:
    debug:
        verbosity: detailed

receivers:
    filestats:
      include: /path/to/check/*
      resource_attributes:
        file.path:
          enabled: true

service:
    pipelines:
        metrics:
            exporters: [debug]
            processors: []
            receivers: [filestats]
```
