### ISSUE TITLE
splunkhecexporter field extraction truncates at 1000 characters

### ISSUE THREAD

**Issue by bdschaap** [open-telemetry/opentelemetry-collector-contrib#31817]
## Description
Field extraction truncates at 1000 characters

## Steps to Reproduce
Transmit a field with a value that is more than 1000 characters.  I used a stack trace with a value that's well over 1000 characters

## Expected Result
Field isn't truncated

## Actual Result
Field is truncated at 1000 characters

Note that routing the log to the debug exporter will field the entire value of the field

### Collector version

0.92

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    ...
exporters:
  splunk_hec:
    ...
  debug:
    verbosity: detailed
service:
  pipelines:
    logs:
	  receivers: [otlp]
	  exporters: [splunk_hec, debug]
```

### Additional context

I'm not certain where in the process field extraction and the truncation occurs.  I'm receiving Otel logs and exporting them via the Splunk HEC exporter.  Those logs are then sent to a Splunk Heavy Forwarder which then forwards it on to Splunk Cloud.
