### ISSUE TITLE
[receiver/prometheus] Add static TAG/LABEL to all metrics scraped with job

### ISSUE THREAD

**Issue by SaschaBrechmannVHV** [open-telemetry/opentelemetry-collector-contrib#31812]
### Component(s)

receiver/prometheus

### Describe the issue you're reporting

Hi all,
i use the prometheus-receiver, to scrape the otel-col Metrics. Now i would route the otel-metrics to an other metrics-DB than the default OT-Metrics, createt by the OT-Agent. For this i need an extra TAG/LABEL with every metric, create bei on prometheus-receiver job.

This is my current config:

```YAML
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector-emtrics
          scrape_interval: 3s
          static_configs:
            - targets: ['localhost:8888']
              labels: ['influxdb_database: apm']

```
The label-part is not working. Did any one have an idee, what i could do?
