### ISSUE TITLE
How to filter based on exception.type

### ISSUE THREAD

**Issue by commonfurture** [open-telemetry/opentelemetry-collector-contrib#31845]
### Describe the issue you're reporting

How to filter based on exception.type
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/37206678/a3131bac-3e08-4b9d-827a-19358638bd53)
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/37206678/b8758036-2b87-4b76-ad1b-d58b2dbb4c56)

**Comment by JaredTan95** [comment]
you can filter in `findTrace` page with `tags`

**Comment by swar8080** [comment]
If that UI doesn't let you filter on span event attributes then you could copy `exception.type` as a span attribute:

```
      transform:
        error_mode: ignore
        trace_statements:
          - context: spanevent
            statements:
              - set(span.attributes["exception.type"], attributes["exception.type"])
```
