### ISSUE TITLE
[receiver/bigip] nil pointer deference code path in getpoolmembers

### ISSUE THREAD

**Issue by paebersold-tyro** [open-telemetry/opentelemetry-collector-contrib#31899]
### Component(s)

receiver/bigip

## Description

If we are unable to collect a list of pools, when we try to collect the list of pool members we encounter a nil pointer dereference and the collector process crashes

## Steps to Reproduce

Accessing a BigIp device but using a user without access to pool information

## Expected Result

Handle pools being unavailable better

## Actual Result

SIGSEGV and crash

### Collector version

v0.91

## Environment
OS: Suse 12sp5

### OpenTelemetry Collector configuration

```yaml
receivers:
  bigip:
    collection_interval: 30s
    endpoint: https://1.2.3.4:443
    username: bigipuser
    password: xxx
    tls:
      insecure_skip_verify: true
exporters:
  debug:
    verbosity: normal
service:
  pipelines:
    metrics:
      receivers:
      - bigip  
      processors: []
      exporters:
      - debug
```

### Log output

```shell
2024-03-21T00:53:46.987Z        warn    bigipreceiver@v0.91.0/scraper.go:90     Failed to scrape pool metrics       {"kind": "receiver", "name": "bigip", "data_type": "metrics", "error": "non 200 code returned 401"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2d26439]

goroutine 85 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/bigipreceiver.(*bigipClient).GetPoolMembers(0xc000625950, {0x42b7ac0, 0xc0005e5080}, 0x0)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/bigipreceiver@v0.91.0/client.go:158 +0x59
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/bigipreceiver.(*bigipScraper).scrape(0xc0005b2070, {0x42b7ac0, 0xc0005e5080})
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/bigipreceiver@v0.91.0/scraper.go:100 +0x734
go.opentelemetry.io/collector/receiver/scraperhelper.ScrapeFunc.Scrape(...)
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scraper.go:20
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport(0xc0007172c0)
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scrapercontroller.go:197 +0x16b
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1()
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scrapercontroller.go:172 +0xd1
created by go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping in goroutine 1
        go.opentelemetry.io/collector/receiver@v0.91.0/scraperhelper/scrapercontroller.go:158 +0x4f
```
