### ISSUE TITLE
Filter Processor fails to filter metric datapoints when cardinality is very high

### ISSUE THREAD

**Issue by tqi-raurora** [open-telemetry/opentelemetry-collector-contrib#31906]
### Component(s)

processor/filter

## Description

When using Filter Processor to filter out datapoints, when the metric has a big cardinality, at first it filters out the data, but after some time it fails to filter

## Steps to Reproduce

I want to filter the metric: http_client_duration_bucket{service_name="notification-sender"}
This metric has a LOT of cardinality. I calculated it to be > 500k

`count(http_client_duration_bucket{service_name="notification-sender"}) > 500k`

I'm using the .yml below (edited the relevant part for clarity):

```
processors:
  filter/by_service_name:
    error_mode: ignore
    metrics:
      datapoint:
        - 'metric.name == "http_client_duration_bucket" and resource.attributes["service.name"] == "notification-sender"'
service:
  pipelines:
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [filter/by_service_name, transform, batch]
      exporters: [prometheus, logging]
```

## Expected Result

I expected not see any `http_client_duration_bucket` with the label `service_name="notification-sender"`

## Actual Result

At first, the data was being filtered, but after some time it seems the data is slowly being failed to filter.
I can see the cardinality for the metric is raising steadily. Below is the evidence I could gather:

Cardinality when filter was applied:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/78105687/dc57b1dc-8d71-4e2b-a319-d8e676b28a52)

Cardinality 3 hours later:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/78105687/25ff0686-eb84-48f9-9777-f23700a68ba6)

Cardinality 6 hours later:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/78105687/0072d94a-470a-4dae-9120-7916c308b8ce)

Cardinality 12 hours later:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/78105687/0267d975-6abf-441e-a64f-d13ff0323c98)

This is a custom metric I have set up via a python script to measure the cardinality via the promethues endpoint (the script basicaly scrapes the promethues exporter endpoint, calculates cardinality for metric_name/service_name pairs, and sends custom metrics to the otel collector)
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/78105687/101dc97b-1ebf-4a25-8bba-817085414cb1)

This is the overal scrape samples scraped promethues metric:
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/78105687/87d6cc89-a32d-4e0a-b2fb-3f4f253913ed)

### Collector version

otelcol-contrib version 0.96.0

### OpenTelemetry Collector configuration

```yaml
#Full config below...
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 16
      http:
        endpoint: 0.0.0.0:4318

processors:
  probabilistic_sampler:
    sampling_percentage: 15

  tail_sampling:
    decision_wait: 30s
    num_traces: 50000
    expected_new_traces_per_sec: 0
    policies:
      [
        {
          name: probabilistic-policy,
          type: probabilistic,
          probabilistic: { sampling_percentage: 15 },
        },
        {
          name: trace-status-policy,
          type: status_code,
          status_code: { status_codes: [ ERROR ] },
        },
      ]

  batch:
    timeout: 1s
    send_batch_size: 15000

  transform:
    metric_statements:
      - context: datapoint
        statements:
        - set(attributes["service.name"], resource.attributes["service.name"]) where attributes["service.name"] == nil
        - set(attributes["host.name"], resource.attributes["host.name"]) where attributes["host.name"] == nil

  filter/traces:
    error_mode: ignore
    traces:
      span:
        - 'resource.attributes["service.name"] == "receivable-settlement"'
        - 'resource.attributes["service.name"] == "receivable-settlement-contract"'
        - 'resource.attributes["service.name"] == "receivable-unit"'
        - 'resource.attributes["service.name"] == "receivable-assignment-accounting"'
        - 'resource.attributes["service.name"] == "pscore-user-consumer"'
        - 'resource.attributes["service.name"] == "refund-data-monitor-consumer-financial"'
        - 'resource.attributes["service.name"] == "authentication-event-provider"'
        - 'resource.attributes["service.name"] == "receivable-unit-listener"'
        - 'resource.attributes["service.name"] == "card-range-api-prod"'
        - 'resource.attributes["service.name"] == "debt-event-consumer"'
        - 'resource.attributes["service.name"] == "cs_async"'
        - 'resource.attributes["service.name"] == "credit-cerc"'
        - 'resource.attributes["service.name"] == "edi-general-ledger-consumer"'
        - 'resource.attributes["service.name"] == "receivable-settlement-r1"'
        - 'resource.attributes["service.name"] == "transaction-replication-topaz"'
        - 'resource.attributes["service.name"] == "receivable-settlement-r2"'
        - 'resource.attributes["service.name"] == "pagclube__mobile-transactions-consumer_"'
        - 'resource.attributes["service.name"] == "payroll-mobile-bff"'
        - 'resource.attributes["service.name"] == "benefits-level-service-async"'
        - 'resource.attributes["service.name"] == "edi-account-balance-consumer"'
        - 'resource.attributes["service.name"] == "edi-receivable-consumer"'
        - 'resource.attributes["service.name"] == "pagclube"'
        - 'resource.attributes["service.name"] == "issuer-supporting-balance-verifier-messaging"'

  filter/metrics:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - ^kafka.*
          - .*kafka.*
          - TRIGGER_LISTENER_LISTEN_TRIGGER.*
          - AMOUNT_TRIGGER_SCORE_ORCHESTRATOR
          - PB_BENORC_PRODUCTS
          - PB_EXPBFF_EXPERIENCE
          - PB_BENLEV_UPGRADE_DOWNGRADE
          - PB_BENLEV_LEVEL_SCORE

  filter/by_service_name:
    error_mode: ignore
    metrics:
      datapoint:
        - 'metric.name == "http_client_duration_bucket" and resource.attributes["service.name"] == "notification-sender"'

exporters:
  otlp:
    endpoint: jaeger.pagmon.intranet.pags:4317
    tls:
      insecure: true

  logging:
    loglevel: warn

  prometheus:
    endpoint: "0.0.0.0:9130"
    metric_expiration: 10m
    add_metric_suffixes: false

  prometheus/full:
    endpoint: "0.0.0.0:19130"
    metric_expiration: 10m
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [125ms, 500ms, 2000ms, 8000ms]
    dimensions:
      - name: http.method
      - name: http.route
      - name: http.scheme
      - name: http.status_code
      - name: net.host.name
      - name: net.protocol.name
      - name: net.protocol.version
      - name: telemetry.sdk.language
      - name: telemetry.sdk.name
      - name: telemetry.sdk.version
    resource_metrics_key_attributes:
      - service.name

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/traces, probabilistic_sampler, batch]
      exporters: [otlp, logging]
    traces/2:
      receivers: [otlp]
      processors: []
      exporters: [spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [filter/metrics, filter/by_service_name, transform, batch]
      exporters: [prometheus, logging]

  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:9115
    logs:
      level: "warn"
      output_paths: []
```

### Additional context

I understand that if it is related to the size of the load this issue may be hard to replicate.
This is a production environment, but I'm willing to run tests, or apply different suggested configurations if it helps.

**Comment by TylerHelmuth** [comment]
This is very curious.

The `filterprocessor` doesn't care about cardinality at all since it doesn't need to remember anything about any datapoint it sees - it simply looks at the data and makes a deterministic decision.

For now I am going to assume that the filterprocessor configuration is not working as you expect and the slow increase in cardinality over time is the result of data making it past the processor and slowly increase a unique count.

I want to check that your OTTL statement is matching as expected.  Can you add a debugexporter with `verbosity: detailed` (or a fileexporter) and share the output for the particular metric you are trying to drop?

**Comment by TylerHelmuth** [comment]
Also you can make your filterprocessor more efficient by doing everything at the metrics level instead of datapoint:

```yaml
filter/by_service_name:
    error_mode: ignore
    metrics:
      metric:
        - 'name == "http_client_duration_bucket" and resource.attributes["service.name"] == "notification-sender"'
```

**Comment by tqi-raurora** [comment]
Hello @TylerHelmuth 

I didn't have success setting up the debug exporter...

Do I just need this?

```
exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
service:
  pipelines:
    metrics/debug:
      receivers: [otlp]
      processors: []
      exporters: [debug]
```
?

Or do I also need to set
```
service:
  telemetry:
    logs:
      level: "warn"
```
?


Where could I see the logs that the debug exporter outputs?

**Comment by TylerHelmuth** [comment]
```yaml
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    metrics/debug:
      receivers: [otlp]
      exporters: [debug]
```

The metrics get printed to the collector logs

**Comment by tqi-raurora** [comment]
@TylerHelmuth 

I think I did manage to get a sample of the metrics:

```
1443023 2024-03-22T16:13:18.078568-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> container.id: Str(9ed30787c5bbf93737b2c74ef5127063b9e5df85ac86aa8188679b6748924cd0)
1443024 2024-03-22T16:13:18.078572-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> host.arch: Str(amd64)
1443025 2024-03-22T16:13:18.078580-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> k8s.container.name: Str(notification-sender)
1443026 2024-03-22T16:13:18.078593-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> k8s.namespace.name: Str(psp-notification)
1443027 2024-03-22T16:13:18.078597-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> k8s.node.name: Str(kubernetes-prod-tb-tbesxprod007-7c6f7bff4f-5z7rf)
1443028 2024-03-22T16:13:18.078601-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> k8s.pod.name: Str(notification-sender-7dc5b9bf9-szlnx)
1443029 2024-03-22T16:13:18.078605-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> k8s.replicaset.name: Str(notification-sender-7dc5b9bf9)
1443030 2024-03-22T16:13:18.078609-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> os.description: Str(Linux 5.4.0-171-generic)
1443031 2024-03-22T16:13:18.078614-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> os.type: Str(linux)
1443032 2024-03-22T16:13:18.078622-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> process.command_args: Slice(["/usr/java/jre/bin/java","-Dhttp.nonProxyHosts=*.intranet.pagseguro.uol|*.p1443032 agseguro.intranet|*.intranet.pags|*.host.pags|*.srv.intranet|*.sys.intranet|*.host.intranet","-Dhttps.nonProxyHosts=*.intranet.pagseguro.uol|*.pagseguro.intranet|*.intranet.pags|*.host.pags|*.srv.intra1443032 net|*.sys.intranet|*.host.intranet","-Dhttp.proxyHost=proxy.intranet.pags","-Dhttp.proxyPort=3128","-Dhttps.proxyHost=proxy.intranet.pags","-Dhttps.proxyPort=3128","-Xmx640m","-Dspring.profiles.active=1443032 prod-tb","-jar","/deployments/app.jar"])
1443033 2024-03-22T16:13:18.078627-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> process.executable.path: Str(/usr/java/jre/bin/java)
1443034 2024-03-22T16:13:18.078631-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> process.pid: Int(1)
1443035 2024-03-22T16:13:18.078635-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> process.runtime.description: Str(Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 17.0.10+11-LTS-2401443035 )
1443036 2024-03-22T16:13:18.078639-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> process.runtime.name: Str(Java(TM) SE Runtime Environment)
1443037 2024-03-22T16:13:18.078650-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> process.runtime.version: Str(17.0.10+11-LTS-240)
1443038 2024-03-22T16:13:18.078655-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> service.name: Str(notification-sender)
1443039 2024-03-22T16:13:18.078660-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> service.version: Str(1.0.263)
1443040 2024-03-22T16:13:18.078663-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> telemetry.auto.version: Str(1.32.1)
1443041 2024-03-22T16:13:18.078667-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> telemetry.sdk.language: Str(java)
1443042 2024-03-22T16:13:18.078671-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> telemetry.sdk.name: Str(opentelemetry)
1443043 2024-03-22T16:13:18.078675-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> telemetry.sdk.version: Str(1.34.1)
1443044 2024-03-22T16:13:18.078680-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]: ScopeMetrics #0
1443045 2024-03-22T16:13:18.078683-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]: ScopeMetrics SchemaURL:
1443046 2024-03-22T16:13:18.078688-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]: InstrumentationScope io.opentelemetry.apache-httpclient-5.0 1.32.1-alpha
1443047 2024-03-22T16:13:18.078691-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]: Metric #0
1443048 2024-03-22T16:13:18.078695-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]: Descriptor:
1443049 2024-03-22T16:13:18.078698-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> Name: http.client.duration
1443050 2024-03-22T16:13:18.078702-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> Description: The duration of the outbound HTTP request
1443051 2024-03-22T16:13:18.078716-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> DataType: Histogram
1443052 2024-03-22T16:13:18.078720-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> AggregationTemporality: Cumulative
1443053 2024-03-22T16:13:18.078724-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]: HistogramDataPoints #0
1443054 2024-03-22T16:13:18.078728-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]: Data point attributes:
1443055 2024-03-22T16:13:18.078732-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> http.method: Str(POST)
1443056 2024-03-22T16:13:18.078738-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> http.status_code: Int(504)
1443057 2024-03-22T16:13:18.078744-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> net.peer.name: Str(www.abadaecia.com.br)
1443058 2024-03-22T16:13:18.078748-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> net.protocol.name: Str(http)
1443059 2024-03-22T16:13:18.078752-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]:      -> net.protocol.version: Str(1.1)
1443060 2024-03-22T16:13:18.078757-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]: StartTimestamp: 2024-03-21 19:41:16.410130698 +0000 UTC
1443061 2024-03-22T16:13:18.078761-03:00 gt-otel-col-loadbalancing-prod2 otelcol-contrib[14759]: Timestamp: 2024-03-22 19:13:16.415058169 +0000 UTC
```

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/78105687/8997dca8-02e8-4bb4-adeb-727083ac72cc)

Is this good to check that the OTTL statement is matching?

**Comment by TylerHelmuth** [comment]
The name of the metric is `http.client.duration` not `http_client_duration_bucket`

**Comment by tqi-raurora** [comment]
> The name of the metric is http.client.duration not http_client_duration_bucket

Oh, I see!
I was looking into this.

Here's my understanding
http.client.duration is a histogram, it is one of the default metrics that comes out of the box from the java otel agent.

Prometheus represents histograms as multiple series, and changes '.' to ' _', so:

`http.client.duration`

Becomes:

`http_client_duration_count`
`http_client_duration_sum`
`http_client_duration_bucket`

From my undestanding, theres no way to filter just one of the prometheus metrics. IE: keep http_client_duration_sum/count and just filtering http_client_duration_bucket, a metric that tends to get big due to the "le" dimension.

Perhaps this filter could be a cool feature for the prometheus exporter?

BTW, I went back to my original filter:
`        - 'metric.name == "http_client_duration_bucket" and resource.attributes["service.name"] == "notification-sender"'`
And testing it better, it was not working at all. Right now I do believe something else on the application side was responsible for the decrease I saw in cardinality.

@TylerHelmuth 
Sorry for that, and thanks for your help

**Comment by tqi-raurora** [comment]
Heres the filter that worked for me:

```
filter/metrics_by_service_name:
    error_mode: ignore
    metrics:
      metric:
        - 'name == "http.client.duration" and resource.attributes["service.name"] == "notification-sender"'
```
