### ISSUE TITLE
[processors/filter] include drop metrics with colon in their name 

### ISSUE THREAD

**Issue by rlanore** [open-telemetry/opentelemetry-collector-contrib#31911]
### Component(s)

processor/filter

## Description

Opentelemetry drop my metric if it contain colon in it's name when use processors/filter include feature

## Steps to Reproduce

Deploy last opentelemetry k8s operator and add opentelemetry colector manifest

## Expected Result

I must see all metric on sdout

## Actual Result

I see only 'up' metric

### Collector version

0.96.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
      prometheus:
  ... ...
    exporters:
      logging:
        verbosity: detailed
    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679
    processors:
      filter/limits:
        metrics:
          include:
            match_type: strict
            metric_names:
            - up
            - namespace_cpu:kube_pod_container_resource_limits:sum
            - namespace_cpu:kube_pod_container_resource_requests:sum
            - namespace_memory:kube_pod_container_resource_limits:sum
            - namespace_memory:kube_pod_container_resource_requests:sum
      batch/metrics:
        timeout: 30s
        send_batch_size: 500
    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        metrics:
          receivers: [prometheus, otlp]
          processors: [filter/limits,batch/metrics, attributes/metrics]
          exporters: [logging,otlp]
      telemetry:
        logs:
          level: debug
        metrics:
          address: 0.0.0.0:8888
          level: basic
```

### Log output

```shell
Nothing usefull
```
