### ISSUE TITLE
Jaeger UI SPM spanmetrics not working in 0.95.0

### ISSUE THREAD

**Issue by PaulKushch** [open-telemetry/opentelemetry-collector-contrib#31922]
## Description

I find it hard to make jaeger SPM to work.  I followed https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26712 but still no success. Still I see traces in the other tab (so tracing works). 

## Steps to Reproduce

My SPM page have no data.
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/5386035/40484092-9375-4673-ad0b-43b8da8f69aa)

## Expected Result

I expect to see metrics in SPM.

## Actual Result
To see metrics for traces in SPM.

### Collector version

0.95.0

## Environment
Ubuntu 22.04

### OpenTelemetry Collector configuration

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: demo
spec:
  config: |
    receivers:
      jaeger:
        protocols:
          thrift_http:
            endpoint: "0.0.0.0:14278"

      otlp:
        protocols:
          grpc:
          http:

    exporters:
      prometheusremotewrite:
        endpoint: http://prometheus-server:80/api/v1/write
        target_info:
           enabled: true

      otlp:
        endpoint: http://jaeger-spm-collector:4317
        tls:
          insecure: true

    connectors:
      spanmetrics:
        exemplars:
          enabled: true

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: []
          exporters: [spanmetrics, otlp]
        metrics:
          receivers: [spanmetrics]
          exporters: [prometheusremotewrite]

```

### Log output

```shell
If I `curl -X POST http://prometheus-server.apm.svc.cluster.local:80/api/v1/write -v` from another pod I get "remote write receiver needs to be enabled with --web.enable-remote-write-receiver" (only issue I can think of)...
So I enabled it in prometheus helm chart by setting `web.enable-remote-write-receiver` in `extraFlags` in values.yaml
```

### Additional context

My Jaeger config 
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-spm
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      log-level: debug
      query:
        base-path: /jaeger
      prometheus:
        server-url: http://prometheus-server:80
        query:
          support-spanmetrics-connector: true
    metricsStorage:
      type: prometheus
  storage:
    options:
      memory:
        max-traces: 100000

```
