### ISSUE TITLE
kafka receiver sasl + tls auth config

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#31931]
### Component(s)

receiver/kafka

## Description

If you want to use sasl with tls atm it's rather unclear how to set it up.

In order to enable tls atm we have a check for:
```
	if config.TLS != nil {
		if err := configureTLS(*config.TLS, saramaConfig); err != nil {
			return err
		}
	}
```

So if you have kafka with sasl and tls you expect this:
```
    auth:
      sasl:
        username: "user"
        password: "secret"
        mechanism: "SCRAM-SHA-512"
```
to work, but it doesn't. 

You also need to set something in tls structure, so it gets enabled. In this case I set insecure to it's default value and then connection works:
```
    auth:
      sasl:
        username: "user"
        password: "secret"
        mechanism: "SCRAM-SHA-512"
    tls:
      insecure: false
``` 

This is also noted in sarama sasl example - https://github.com/IBM/sarama/blob/main/examples/sasl_scram_client/main.go#L92-L108C1

Where they both set tls.enabled=true and sasl.enabled=true

I suggest maybe we can add:
```
tls:
  enabled: false
``` 

as default? And then users wanting to configure tls, can set it to enabled?

Thougths?

### Collector version

v0.95.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
