### ISSUE TITLE
Mongodb Atlas receiver not able to pull logs issue

### ISSUE THREAD

**Issue by preshit1505** [open-telemetry/opentelemetry-collector-contrib#31978]
### Component(s)

receiver/mongodbatlas

## Description
I have setup the mongodb atlas receiver for getting the logs but I am not seeing any logs coming into the collector
## Expected Result
Expected to be getting the logs

## Actual Result
{"level":"warn","ts":1711471695.0430725,"caller":"mongodbatlasreceiver@v0.88.0/logs.go:259","msg":"Attempted to retrieve audit logs but received 0 logs","kind":"receiver","name":"mongodbatlas","data_type":"logs","error":"EOF","log":"mongodb-audit-log.gz"}
{"level":"warn","ts":1711471693.930057,"caller":"mongodbatlasreceiver@v0.88.0/logs.go:229","msg":"Attempted to retrieve host logs but received 0 logs","kind":"receiver","name":"mongodbatlas","data_type":"logs","error":"EOF","log":"mongos.gz"
--

### Collector version

mongodb atlas version 6.0.14

### OpenTelemetry Collector configuration

```yaml
config:
  receivers:

    mongodbatlas:
      public_key: ${MONGODB_PUBLIC_KEY}
      private_key: ${MONGODB_PRIVATE_KEY}
      logs:
        enabled: true
        projects:
        - name: bedrock-control-plane-preview
          include_clusters: [kubevlea]
          access_logs:
            enabled: true
            auth_result: true
            poll_interval: 1m
          collect_audit_logs: true
          collect_host_logs: true

 service:
    extensions: [basicauth/metrics, basicauth/logs, health_check]
    pipelines:
      logs:
        receivers: [mongodbatlas]
        processors: [memory_limiter/logs, k8sattributes, batch/logs]
        exporters: [loki]
      logs:
        encoding: json
```

### Log output

```shell
{"level":"warn","ts":1711471695.0430725,"caller":"mongodbatlasreceiver@v0.88.0/logs.go:259","msg":"Attempted to retrieve audit logs but received 0 logs","kind":"receiver","name":"mongodbatlas","data_type":"logs","error":"EOF","log":"mongodb-audit-log.gz"}
{"level":"warn","ts":1711471693.930057,"caller":"mongodbatlasreceiver@v0.88.0/logs.go:229","msg":"Attempted to retrieve host logs but received 0 logs","kind":"receiver","name":"mongodbatlas","data_type":"logs","error":"EOF","log":"mongos.gz"
```

### Additional context

Audit logs are already enabled from atlas UI
