### ISSUE TITLE
[bug][receiver/filestats] doesn't show the full path

### ISSUE THREAD

**Issue by josepcorrea** [open-telemetry/opentelemetry-collector-contrib#32003]
### Component(s)

receiver/filestats

## Description

filestatsreceiver doesn't show the full path

The metrics show:

file_size_b{file_name="file.log",file_path="/file.log"} 48

The filepath only show the last path.

### Collector version

v0.93.0

## Environment
OS: Red Hat Enterprise Linux Server release 7.5 (Maipo)

### OpenTelemetry Collector configuration

```yaml
receivers:
 filestats:
   include: /tmp/test/file.log

exporters:
  prometheus:
    endpoint: "0.0.0.0:8085"

  pipelines:
    metrics:
      receivers: [filestats]
      exporters: [prometheus]
```
