### ISSUE TITLE
Local configuration is overwritten

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#32048]
### Component(s)

cmd/opampsupervisor

## Description
When I run `opampsupervisor`(the backend program is OpAMP's sample server), I noticed that `EffectivConfig` gets cleared, leaving only the contents of [ownMetricsCfg](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e867aa84edb2dbe0570b57681ba62bdbf92e1d37/cmd/opampsupervisor/supervisor/supervisor.go#L491) and [ExtraLocalConfig](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e867aa84edb2dbe0570b57681ba62bdbf92e1d37/cmd/opampsupervisor/supervisor/supervisor.go#L432). 

## Steps to Reproduce
1. Fill in the correct configuration to ensure that the `opampsupervisor` can connect to the backend normally 
2. Start the backend OpAMP sample server 
3. Fill in the effective configuration in local `effective.yaml`
4. Start `opampsupervisor`
5. Check the otel configuration displayed by the OpAMP UI or view the local file named `effective.yaml`.
## Expected Result
The content I filled in to the local configuration file named effective.yaml will not be cleared after the connection is established.
## Actual Result
The configuration content I filled in was cleared

### Collector version

all

## Environment
OS: Darwin 
Compiler: go 1.21

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 10s
          static_configs:
            - targets:
              - 0.0.0.0:55149
exporters:
  otlphttp:
    endpoint: http://localhost:4318/v1/metrics
service:
  pipelines:
    metrics:
      exporters:
        - otlphttp
      receivers:
        - prometheus
```

### Additional context

I know the reason is that the backend server returns an empty remote configuration. However, I believe that the `opampsupervisor` needs to handle such situations to avoid the issue where configurations get overwritten due to logic errors in the backend.
