### ISSUE TITLE
[connector/spanmetrics] - Spanmetrics connector is not producing correct metrics

### ISSUE THREAD

**Issue by ramanjaneyagupta** [open-telemetry/opentelemetry-collector-contrib#32043]
### Component(s)

connector/spanmetrics

## Description
Setup: Agents -> Gateway(OtelCollectors) -> Storage.
Gateway contains multiple servers which calculates the spanmetrics and exports to Prometheus.
## Steps to Reproduce
Setup spanmetrics connector, Prometheus Exporter
1. Start the collector and wait for sometime to generate the metrics
2. After restart also it is the same behaviour
## Expected Result
Spanmetrics should calculate  metrics Properly (total_calls, counts, histograms etc.. )
## Actual Result
Spanmetrics are not producing correct results. (some of the metrics are in keep increasing)

### Collector version

v0.96.0

## Environment
OS: (Linux (RHEL)

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  prometheus:
    endpoint: "localhost:8889"
    namespace: gateway.spanmetrics
    resource_to_telemetry_conversion:
      enabled: true 

connectors:
  spanmetrics:
   dimensions:
      - name: http.method
      - name: http.status_code
      - name: k8s.namespace.name
    exemplars:
      enabled: true
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"    
    metrics_flush_interval: 15s
    resource_metrics_key_attributes:
      - service.name
      - telemetry.sdk.language
      - telemetry.sdk.name
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection/system, batch]
      exporters: [spanmetrics,tracebackend]
    metrics:
      receivers: [spanmetrics]
      processors: [resourcedetection/system, batch]
      exporters: [prometheus]
```

### Log output

```shell
After few minutes of starting the OTEL collector, all counter metrics, histograms are keep increasing.
```
