### ISSUE TITLE
[exporter/loadbalancingexporter] - Static resolver dropping the data when one of the host is not healthy

### ISSUE THREAD

**Issue by ramanjaneyagupta** [open-telemetry/opentelemetry-collector-contrib#32045]
### Component(s)

exporter/loadbalancing

### Describe the issue you're reporting

Collector Version: v0.96.0
Configuration: 
```
exporters:
  loadbalancing:
    routing_key: "traceID"
    protocol:
      otlp:
        timeout: 1s
    resolver:
      static:
        hostnames:
        - backend-1:4317
        - backend-2:4317
        - backend-3:4317
        - backend-4:4317 
service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - loadbalancing
```
If one of the host is down in the static list, loadbalancingexporter unable to send the data to healthy host. Instead sending the data to health host it is dropping the data on the floor.
