### ISSUE TITLE
[connector/spanmetrics] - unable to export the metrics using prometheusremotewrite when batch processor enabled

### ISSUE THREAD

**Issue by ramanjaneyagupta** [open-telemetry/opentelemetry-collector-contrib#32042]
### Component(s)

connector/spanmetrics

## Description
Unable to export span metrics using prometheusremotewrite when batch processor enabled.
Agetns -> Gateway(OtelCollectors) -> Storage. 
Gateway contains multiple servers which calculates the spanmetrics and writes to the Prometheus using PRW.
## Steps to Reproduce
enable spanmetrics with prometheus remotewrite
## Expected Result
Prometheus Remote Write should able to export the metrics when batch processor is enabled
## Actual Result
It is giving "Permanent Error"; "Duplicate Sample For timestamp"; " Permanent error remote write returned status code of 400 bad request""

### Collector version

v0.96.0

## Environment
OS: Linux (RHEL)

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  prometheusremotewrite:
    endpoint: http://<endpoint>
     target_info:
       enabled: true
    resource_to_telemetry_conversion:
      enabled: true 

connectors:
  spanmetrics:
   dimensions:
      - name: http.method
      - name: http.status_code
      - name: k8s.namespace.name
    exemplars:
      enabled: true
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"    
    metrics_flush_interval: 15s
    resource_metrics_key_attributes:
      - service.name
      - telemetry.sdk.language
      - telemetry.sdk.name
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection/system, batch]
      exporters: [spanmetrics,tracebackend]
    metrics:
      receivers: [spanmetrics]
      processors: [resourcedetection/system, batch]
      exporters: [prometheusremotewrite]
```

### Log output

```shell
" Permanent error remote write returned status code of 400 bad request" "err"=nil duplicate sample for timestamp"
```
