### ISSUE TITLE
The "extension" configuration item of the configuration file is overwritten

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#32050]
### Component(s)

cmd/opampsupervisor

## Description
When I delivered the remote configuration through the OpAMP sample server, I found that the `extension` in the final configuration of OTEL was cleared, leaving only `health_check`.
## Steps to Reproduce
1. Fill in the correct configuration to ensure that the opampsupervisor can connect to the backend normally
2. Start the backend OpAMP sample server
3. Start opampsupervisor
4. Deliver remote configuration through OpAMP  UI
5. Check the otel configuration displayed by the OpAMP UI or view the local file named effective.yaml
## Expected Result
The extension component I added is not cleared, at most `health_check` is added
## Actual Result
The extension component I added was cleared

### Collector version

all

### Environment information

OS: Darwin
Compiler: go 1.21

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 10s
          static_configs:
            - targets:
              - 0.0.0.0:55149
exporters:
  otlphttp:
    endpoint: http://localhost:4318/v1/metrics
extensions:
  pprof:
  memory_ballast:
    size_mib: "256"
service:
  pipelines:
    metrics:
      exporters:
        - otlphttp
      receivers:
        - prometheus
  extensions:
    - memory_ballast
    - pprof
```

### Additional context

I know that the extensions configuration item is overwritten in this [code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e867aa84edb2dbe0570b57681ba62bdbf92e1d37/cmd/opampsupervisor/supervisor/supervisor.go#L580). 
The fundamental reason is that `koanf` cannot parse `extensions` into key-value form, so the previous value will be overwritten.
I think we can solve this problem by adding configuration items to `extensions` instead of executing `koanf.merge` directly.
