### ISSUE TITLE
[extension/opamp] Add support for user-specified non-identifying attributes

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#32107]
### Component(s)

extension/opamp

### Is your feature request related to a problem? Please describe.

In the OpAMP spec, [non-identifying attributes](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionnon_identifying_attributes) include "any user-defined attributes that the end user would like to associate with this Agent."

We would like to be able to add some extra attributes to the agent description this way.

### Describe the solution you'd like

I think a simple solution would be to just have a section of the config that unmarshals to map[string]string, where the attributes can be specified:

```yaml
extension:
  opamp:
    non_identifying_attributes:
      custom.attribute: value
      another.custom.attribute: "another value"
```

If one of the automatically filled non identifying attributes are specified (e.g. `host.name`, `host.arch`, `os.type`), I think the user-specified value of the attribute should act as an override for these attributes.
