### ISSUE TITLE
[pkg/ottl] Add support PCRE2 regex syntax

### ISSUE THREAD

**Issue by aofodo** [open-telemetry/opentelemetry-collector-contrib#32167]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

I need to mask PANs (card numbers) in logs. Card numbers can be in different versions. With different dividers, different lengths. It is important that other data is not accidentally masked. To do this, I use a complex regular expression, including lookahead and other features of the PCRE2 syntax. Without the syntax capabilities of PCRE2, it is impossible to fully mask card numbers

### Describe the solution you'd like

Add support PCRE2 syntax in `processor/transform` for `replace_pattern` and `replace_all_patterns`

**Comment by TylerHelmuth** [comment]
@aofodo we use Go's built-in package for regex which I don't believe supports `PCRE2` regexes by design.

**Comment by amal-v** [comment]
We are trying to remove the `.` from the k8sattributes for k8s labels. For Eg `k8s.pods.labels.service.version=1` to `k8s.pods.labels.service_version=1`. We require some advanced regex like PCRE2 to perform these operations.

**Comment by TylerHelmuth** [comment]
@amal-v can you share the PCRE2 regex you'd like to use for your use case?

**Comment by rdeavila94** [comment]
Ditto this. I have a use case where a span attribute is a JSON string and I need to obfuscate the JSON values with the exception of some that correspond to a specific JSON key. Doesn't seem possible without a negative lookbehind.

for reference
```yml
transform:
  error_mode: ignore
  trace_statements:
    - context: span
      statements:
        - "replace_pattern(attributes[\"my-attribute\"], \"(?<!\\\"(key1|key2)\\\": )\\\"[^\\\"]+\\\"\", \"?\")"
```

There's _probably_ a way to do this by transforming across multiple transformation stages but a single regex solution is much preferable.
