### ISSUE TITLE
Collector fails to start with error in mongodb receiver invalid transport type ""

### ISSUE THREAD

**Issue by ashish121092** [open-telemetry/opentelemetry-collector-contrib#32199]
Using the following configuration for collector it fails to startup with error invalid configuration for mongodb receiver : invalid transport type "".

**Collector image : otel/opentelemetry-collector-contrib:0.97.0**

### **Collector configuration:**

```yml
receivers:
  otlp:
    protocols:
      grpc:
      http:
  mongodb:
    hosts:
      - endpoint: 10.224.10.25:27017
      - endpoint: 10.224.10.28:27017
      - endpoint: 10.224.10.31:27017
    collection_interval: 60s
    initial_delay: 1s
    replica_set: rs0
    tls:
      insecure: true
      insecure_skip_verify: true
```
### **What is the expected behavior?**
The mongodb receiver collects metrics from the hosts.

### **What is the actual behavior?**
The collector fails to start with error invalid configuration for mongodb receiver. Invalid transport type "".

**Error message** : Error: invalid configuration: receivers::mongodb: invalid transport type ""; invalid transport type ""; invalid transport type ""
2024/04/05 17:05:32 collector server run finished with error: invalid configuration: receivers::mongodb: invalid transport type ""; invalid transport type ""; invalid transport type ""

**Comment by TylerHelmuth** [comment]
@ashish121092 please format your configuration and share the entire error message

**Comment by TylerHelmuth** [comment]
The issue is happening because you are specifying `host` configuration without specifying a transport protocol.  If you do 

```yaml
mongodb:
  hosts:
    - endpoint: 10.224.10.25:27017
      transport: "tcp"
    - endpoint: 10.224.10.28:27017
      transport: "tcp"
    - endpoint: 10.224.10.31:27017
      transport: "tcp"
```

It should work.
