### ISSUE TITLE
[extensions/sigv4auth] sigv4auth requires AWS credentials to run 'validate' subcommand

### ISSUE THREAD

**Issue by tredman** [open-telemetry/opentelemetry-collector-contrib#32214]
### Component(s)

extension/sigv4auth

### Describe the issue you're reporting

Hello! I'm trying to invoke `validate` from a build pipeline so that we do basic validation of the OTEL configs we're pushing out to our users. Recently I added an exporter for Amazon Managed Prometheus, which requires the `sigv4auth` extension in order to authenticate.

```yaml
      sigv4auth/amp:
        service: 'aps'
        region: 'us-east-1'
```

After doing this, `validate` fails to run with the following error:

> Error: extensions::sigv4auth/amp: could not retrieve credential provider: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: host is down
2024/04/07 08:37:16 collector server run finished with error: extensions::sigv4auth/amp: could not retrieve credential provider: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: host is down

Initially I resolved this by authenticating to one of my AWS accounts, but through experimentation I found I can fix this by supplying arbitrary/invalid values for the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. This seems like something that the validation command should just handle gracefully, perhaps by just initializing the AWS SDK with some kind of mock config.

otelcol-contrib version 0.97.0

**Comment by mvillafuertem** [comment]
Hi @tredman 

When I have to use osis and when I have to use aps? I haven't found any documentation about it...

```yaml
      sigv4auth:
        service: 'aps'
        region: 'us-east-1'
```

```yaml
      sigv4auth:
        service: 'osis'
        region: 'us-east-1'
```
