### ISSUE TITLE
Documentation regarding the newly added k8s.cluster.name attribute is not correct

### ISSUE THREAD

**Issue by mzanrosso-ikea** [open-telemetry/opentelemetry-collector-contrib#32258]
### Component(s)

processor/resourcedetection/internal/azure

## Description
Documentation regarding the newly added k8s.cluster.name attribute it's not correct:
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor#cluster-name

Wrong:
```
processors:
  resourcedetection/aks:
    detectors: [aks]
    timeout: 2s
    override: false
    aks:
      resource_attributes:
        k8s.cluster.name: true
```
Correct
```
processors:
  resourcedetection/aks:
    detectors: [aks]
    timeout: 2s
    override: false
    aks:
      resource_attributes:
        k8s.cluster.name:
            enabled: true
```

### Collector version

latest

### Environment information

Not relevant

### OpenTelemetry Collector configuration

```yaml
Not relevant
```

### Log output

```shell
Not relevant
```
