### ISSUE TITLE
Panic if Elasticsearch is unavailable during shutdown of the exporter

### ISSUE THREAD

**Issue by lahsivjar** [open-telemetry/opentelemetry-collector-contrib#32317]
### Component(s)

exporter/elasticsearch

## Description

If Elasticsearch is unavailable on shutdown of the exporter then if there is data to be flushed in the exporter it will cause a panic.

## Steps to Reproduce

1. Shutdown Elasticsearch
2. Keep sending data to the collector configured with Elasticsearch exporter
3. Shutdown the exporter

## Expected Result

No panic is observed

## Actual Result

Panic is observed:

```
panic: send on closed channel

goroutine 78 [running]:
github.com/elastic/go-elasticsearch/v7/esutil.(*bulkIndexer).Add(0x14000334a80, {0x102586420, 0x1033c5460}, {{0x101f86420, 0x14}, {0x101f70693, 0x6}, {0x0, 0x0}, {0x0, ...}, ...})
...
```

The root cause of the panic is the handling of bulk failures ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c268b285cf9874178858bc1be54f7888f9197e66/exporter/elasticsearchexporter/elasticsearch_bulk.go#L193-L204)). When the item fails then we try to push the item back into the bulk indexer, however, if the exporter is shutting down then the bulkindexer would already be closed and the flush (which led to the error) is due to ES not available on the final flush initiated by `Close`.

### Collector version

all

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
          otlp:
            protocols:
              grpc:
                endpoint: "127.0.0.1:60979"
        exporters:
          elasticsearch:
            endpoints: [http://127.0.0.1:9200]
            flush:
              interval: 1s
            sending_queue:
              enabled: true
            retry:
              enabled: true
              max_requests: 10000

          debug:
            verbosity: basic

        processors:


        extensions:


        service:
          telemetry:
            metrics:
              address: 127.0.0.1:60980
          extensions: []
          pipelines:
            logs:
              receivers: [otlp]
              processors: []
              exporters: [elasticsearch]
```

### Log output

```shell
panic: send on closed channel

goroutine 78 [running]:
github.com/elastic/go-elasticsearch/v7/esutil.(*bulkIndexer).Add(0x14000334a80, {0x102586420, 0x1033c5460}, {{0x101f86420, 0x14}, {0x101f70693, 0x6}, {0x0, 0x0}, {0x0, ...}, ...})
```
