### ISSUE TITLE
OTTL: Support using `ConvertCase` with `replace_*` functions

### ISSUE THREAD

**Issue by F21** [open-telemetry/opentelemetry-collector-contrib#32342]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

I want to use the transform processor to turn all key names in attributes to lowercase:
```yaml
  transform:
    log_statements:
      - context: log
        statements:
          - replace_all_patterns(attributes, "key", "(.*)", "$$1", ConvertCase("lower"))
```
This currently does not work and the collector fails to start.

### Describe the solution you'd like

The ability to use `ConvertCase` with the `replace_` family of functions.

### Describe alternatives you've considered

n/a

### Additional context

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27820#issuecomment-1918082608
