### ISSUE TITLE
Add makefile targets to automate development on k8s

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/opentelemetry-collector-contrib#32348]
### Describe the issue you're reporting

I was wondering if there are any basic development tools/scripts that automate the development process on k8s.
For example, when I want to debug or edit the code of the `kubeletstats` receiver I need to manually build and load the image on the local cluster and use a very custom values file for the helm chart to be installed using the custom image.
Specifically:

```console
make docker-otelcontribcol && docker tag otelcontribcol otelcontribcol-dev:0.0.1 && kind load docker-image otelcontribcol-dev:0.0.1
``` 

and then I use the following values file:

```yaml
mode: daemonset

image:
  repository: otelcontribcol-dev
  tag: "0.0.1"
  pullPolicy: IfNotPresent

command:
  name: otelcontribcol

clusterRole:
  create: true
  rules:
    - apiGroups:
        - ''
      resources:
        - 'pods'
        - 'nodes'
      verbs:
        - 'get'
        - 'list'
        - 'watch'
    # Only needed if you are using extra_metadata_labels or
    # I
    - apiGroups: [ "" ]
      resources: [ "nodes/proxy"]
      verbs: [ "get" ]


config:
  exporters:
    otlp:
      endpoint: 0.0.0.0:4242
  receivers:
    kubeletstats:
      collection_interval: 10s
      auth_type: 'serviceAccount'
      endpoint: '${env:K8S_NODE_NAME}:10250'
      insecure_skip_verify: true
      k8s_api_config:
        auth_type: serviceAccount
      metrics:
        container.cpu.utilization:
          enabled: true
        container.cpu.time:
          enabled: true
        container.cpu.usage:
          enabled: true
        k8s.container.cpu_limit_utilization:
          enabled: true

  service:
    pipelines:
      metrics:
        receivers: [kubeletstats]
        processors: [batch]
        exporters: [otlp]
```
and `helm install daemonset open-telemetry/opentelemetry-collector --values daemonset_local_k8smetrics.yaml`

So I wonder if we could automate this with sth like:

```console
make kind-image
make kind-install-daemonset
```

This would help to encapsulate all this process and make it easier for new contributors to ramp up.
We can start with sth small and keep adding stuff while we use these targets with the time being.

@TylerHelmuth @jinja2 since you have been working on this area I would like to hear your opinions.
