### ISSUE TITLE
Sample config from sumologic extension doesn't work

### ISSUE THREAD

**Issue by dmolenda-sumo** [open-telemetry/opentelemetry-collector-contrib#32375]
### Component(s)

extension/sumologic

## Description

I try tu run collector with this config: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/sumologicextension#example-config. It didn't start correctly.

## Steps to Reproduce

Try tu run collector with this config: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/sumologicextension#example-config
```
extensions:
  sumologic:
    installation_token: <token>
    collector_name: my_collector
    time_zone: Europe/Warsaw

receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      load:

processors:

exporters:
  sumologic:
    auth:
      authenticator: sumologic # Specify the name of the authenticator extension

service:
  extensions: [sumologic]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: []
      exporters: [sumologic]
```

## Expected Result

Collector should start

## Actual Result
Error:
```
Error: invalid configuration: exporters::sumologic: endpoint is not set
2024/04/15 11:27:02 collector server run finished with error: invalid configuration: exporters::sumologic: endpoint is not set
```

### Collector version

latest

## Environment
OS: darwin/amd64
Compiler(if manually compiled): go version go1.21.7

### OpenTelemetry Collector configuration

```yaml
extensions:
  sumologic:
    installation_token: <token>
    collector_name: my_collector
    time_zone: Europe/Warsaw

receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      load:

processors:

exporters:
  sumologic:
    auth:
      authenticator: sumologic # Specify the name of the authenticator extension

service:
  extensions: [sumologic]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: []
      exporters: [sumologic]
```

### Log output

```shell
Error: invalid configuration: exporters::sumologic: endpoint is not set
2024/04/15 11:27:02 collector server run finished with error: invalid configuration: exporters::sumologic: endpoint is not set
```
