### ISSUE TITLE
RemoteTap Processor doesn't support a limit

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-collector-contrib#32385]
### Component(s)

processor/remotetap

## Description
The remote tap processor specifies a [limit](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/remotetapprocessor/config.go#L21), however, the limit is never used.

## Steps to Reproduce
Specify a limit on a busy pipeline and be bombarded with messages.

## Expected Result
The limit is applied to not overwhelm a consumer

## Actual Result
The consumer is overwhelmed.

### Collector version

0.98.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318

processors:
  remotetap:
    endpoint: 127.0.0.1:12001
    limit: 1
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [remotetap, batch]
      exporters: [debug]

    metrics:
      receivers: [otlp]
      processors: [remotetap, batch]
      exporters: [debug]

    logs:
      receivers: [otlp]
      processors: [remotetap, batch]
      exporters: [debug]
```
