### ISSUE TITLE
[processor/k8sattributes] Metrics sent by a very short-lived CronJob get labels from another CronJob started at the same time, or no labels at all

### ISSUE THREAD

**Issue by juissi-t** [open-telemetry/opentelemetry-collector-contrib#32476]
### Component(s)

processor/k8sattributes

## Description

A very short-lived CronJob (a few seconds) added some OTel metrics and sends them to the collector running in the same worker node. Every now and then there is another CronJob started at the same time, which lives a bit longer (tens of seconds). The metrics sent by the first CronJob gets labels from the second one. The second one does not emit any OTel metrics.

Two pods started at the same time:
```
api-repo-workers   rollout-sync-cronjob-c832add0-28555635               1/1           26s        5m46s
datsun             datsun-watchdog-cronjob-c8bd868a-28555635            1/1           5s         5m46s
```

Metric sent by the `datsun` CronJob seen in Thanos:
```
datsun_summary_datarequest_count{app="rollout-sync", batch_kubernetes_io_controller_uid="9df60c1b-2594-4889-9f06-04c37d0354da", batch_kubernetes_io_job_name="rollout-sync-cronjob-c832add0-28555635", cdk8s_cronjob="rollout-sync", cluster="staging", controller_uid="9df60c1b-2594-4889-9f06-04c37d0354da", env="staging", job="datsun-watchdog", job_name="rollout-sync-cronjob-c832add0-28555635", namespace="api-repo-workers", receive="true", service_name="datsun-watchdog", status="cancelled", tenant_id="default-tenant"}
```

If there are no other CronJobs running at the same time, the metric looks like this (it does not have any labels added by k8sattributes processor):
```
datsun_summary_datarequest_count{cluster="staging", env="staging", job="datsun-watchdog", receive="true", service_name="datsun-watchdog", status="cancelled", tenant_id="default-tenant"}
```

## Steps to Reproduce

1. Create two Kubernetes CronJobs which start at the same time, one which runs for a very short period of time and another one, which runs a longer time
2. Emit OTel metrics from the short-lived one
3. Check the metric labels

## Expected Result

Metrics would have the correct labels.

## Actual Result

Metrics have labels from the wrong CronJob, or no labels added at all.

### Collector version

0.97.0

## Environment
OS: EKS 1.27, Bottlerocket

### OpenTelemetry Collector configuration

```yaml
exporters:
      debug: {}
      otlp:
        endpoint: tempo-distributor.x.y.z:4317
        sending_queue:
          queue_size: 25000
      prometheusremotewrite:
        endpoint: http://vmagent-victoria-metrics-agent.monitoring:8429/api/v1/write
        remote_write_queue:
          num_consumers: 10
          queue_size: 25000
        resource_to_telemetry_conversion:
          enabled: true
        timeout: 15s
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch: {}
      groupbyattrs:
        keys:
        - k8s.pod.name
      k8sattributes:
        extract:
          labels:
          - from: pod
            key_regex: (.*)
            tag_name: $$1
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      resource:
        attributes:
        - action: upsert
          key: cluster
          value: staging
        - action: upsert
          key: env
          value: staging
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411
    service:
      extensions:
      - health_check
      pipelines:
        metrics:
          exporters:
          - prometheusremotewrite
          processors:
          - k8sattributes
          - memory_limiter
          - resource
          - batch
          - groupbyattrs
          receivers:
          - otlp
        traces:
          exporters:
          - otlp
          processors:
          - k8sattributes
          - memory_limiter
          - resource
          - batch
          receivers:
          - otlp
          - jaeger
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
```
