### ISSUE TITLE
[receiver/chronyreceiver] Receiver is not scraping dial unixgram /var/run/chrony/chronyd.sock

### ISSUE THREAD

**Issue by saleelshetye84** [open-telemetry/opentelemetry-collector-contrib#32487]
### Component(s)

receiver/chrony

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
      chrony:
        #address: unix:///var/run/chrony/chronyd.sock
        timeout: {{ .Values.scrape.timeout.chrony }}
        collection_interval: {{ .Values.scrape.duration.chrony }}
        metrics:
          ntp.skew:
            enabled: false
          ntp.time.correction:
            enabled: false


=================================================================
podSecurityContext:
    fsGroup: 5000
  securityContext:
    allowPrivilegeEscalation: true  
    runAsNonRoot: false    
    readOnlyRootFilesystem: true
```

### Log output

```shell
2024-04-08T20:44:32.646Z error scraperhelper/scrapercontroller.go:200 Error scraping metrics {"kind": "receiver", "name": "chrony", "data_type": "metrics", "error": "dial unixgram /var/run/chrony/chronyd.sock: connect: permission denied", "scraper": "chrony"}
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport
go.opentelemetry.io/collector/receiver@v0.87.0/scraperhelper/scrapercontroller.go:200
go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1
go.opentelemetry.io/collector/receiver@v0.87.0/scraperhelper/scrapercontroller.go:172
```

### Additional context

We are running the otel agent as a daemonset configuration on the EKS cluster nodes and we want to have the NTP values scraped.
Is it the case that the chrony receiver should run within the k8s pods with the root privileges so as to scrape the node level /var/run/chrony/chronyd.sock ?

We are running into the above pasted error as permission denied. Is there an alternative to scrape the node level ntp metrics without having the k8s pods to run as root privileges? Or is this a bug with the chrony receiver?
