### ISSUE TITLE
loadbalancingexporter makes the collector accept data to produce a reject otelcol_receiver_refused_spans

### ISSUE THREAD

**Issue by linliaoy** [open-telemetry/opentelemetry-collector-contrib#32482]
### Component(s)

exporter/loadbalancing

## Description
A lot of receiver refused span occurs when I use the svc resolution of k8s for loadbalancingexporter，I added a groupbytrace to fix this temporarily, but the current collector has a lot more cpu and memory footprint，exporter_send_failed_spacs  will also increase。The other one that doesn't use loadbalancingexporter is good

### Collector version

0.97.0

## Environment
OS: kernel 4.19.91
Compiler(if manually compiled):  "go 1.21"

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      otlp/mobile:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4315
            
          http:
            endpoint: ${env:MY_POD_IP}:4316
      
    extensions:
      health_check:
        path: "/health/status"
    processors:
      batch:
        send_batch_size: 10000
      memory_limiter:
        # 80% of maximum memory up to 2G 1\
        limit_mib: 800
        #limit_percentage: 10%
        # 25% of limit up to 2G    
        spike_limit_mib: 200    
        #spike_limit_percentage: 5%
        check_interval: 5s
      groupbytrace:
        wait_duration: 3s
        num_traces: 2000000
        num_workers: 10
    exporters:
      loadbalancing:
        protocol:
          otlp:
            tls:
              insecure: true
            sending_queue:
              num_consumers: 100
              queue_size: 100000
        resolver:
          k8s:
            service: backends-headless.observability
   
    service:
      telemetry:
        metrics:
          address: ":8888"
      extensions: [health_check]
      pipelines:
        traces:      
          receivers: [otlp]      
          #processors: [batch]
          processors: [memory_limiter,groupbytrace]
          exporters: [loadbalancing]
        traces/mobile:
          receivers: [otlp/mobile]      
          #processors: [batch]
          processors: [memory_limiter,groupbytrace]
          exporters: [loadbalancing]
```

### Log output

```shell
No log output, only an increase on the otelcol_receiver_refused_spans value
```
