### ISSUE TITLE
[receiver/syslog] syslog receiver is missing "time/tzdata"

### ISSUE THREAD

**Issue by pichlermarc** [open-telemetry/opentelemetry-collector-contrib#32506]
### Component(s)

receiver/syslog

## Description

We ran into this when using a custom collector that includes fewer components than the full contib build. It looks like in this repo `time/tzdata` is underline-imported via [`clickhouse-go`](https://github.com/ClickHouse/clickhouse-go/blob/4a3adc462363d1ec92c6a1db3a514b992730d621/clickhouse.go) used in `exporter/clickhosue`.

This has the effect that, using the `syslog` receiver it will only work under certain circumstances:
- with the tz database installed
  - this is not installed in certain slim images, or when starting from a `scratch` docker image
- without the tz database installed, with the clickhouse exporter included in the build
  - this will include `time/tzdata` in the final binary via [`clickhouse-go`](https://github.com/ClickHouse/clickhouse-go/blob/4a3adc462363d1ec92c6a1db3a514b992730d621/clickhouse.go)
- without the tz database installed, when the collector is built with the `-tags=timetzdata` build flag

## Steps to Reproduce

- Install the `ocb` as described in the [docs](https://opentelemetry.io/docs/collector/custom-collector/#step-1---install-the-builder)
- create `builder-config.yaml` with the following contents:
```yaml
dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.98.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.98.0
  # - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter v0.98.0

receivers:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.98.0
```
- run the collector builder via `CGO_ENABLED=0 GOOS=linux GOARCH=amd64 ./ocb --config builder-config.yaml`
- create a `Dockerfile` with the following contents
```Dockerfile
FROM alpine:3.19 as certs
RUN apk --update add ca-certificates

FROM scratch

USER 10001

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --chmod=755 ./otelcol-dev/otelcol-dev /otelcol-dev
ENTRYPOINT ["/otelcol-dev"]
```
- run `docker build -t otelcol-dev .`
- create `collector-config.yaml` with the same content as provided below
- run the container with `docker run -v ./collector-config.yaml:/collector-config.yaml otelcol-dev --config=/collector-config.yaml`

## Expected Result

Collector starts up without errors.

## Actual Result

The collector exits with an error (see log output below)

### Collector version

v0.98.0

## Environment
OS: Compiled on Ubuntu 22.04, run on a `scratch` image in Docker
Compiler(if manually compiled): `go1.21.4 linux/amd64`

### OpenTelemetry Collector configuration

```yaml
receivers:
  syslog:
    udp:
      listen_address: "0.0.0.0:54526"
    protocol: rfc3164
    location: America/New_York

exporters:
  debug:
    verbosity: normal

service:
  pipelines:
    logs:
      receivers: [syslog]
      processors: []
      exporters: [debug]
```

### Log output

```shell
2024-04-18T09:24:29.958Z        info    service@v0.98.0/telemetry.go:55 Setting up own telemetry...
2024-04-18T09:24:29.958Z        info    service@v0.98.0/telemetry.go:97 Serving metrics {"address": ":8888", "level": "Basic"}
2024-04-18T09:24:29.958Z        info    exporter@v0.98.0/exporter.go:275        Development component. May change in the future.        {"kind": "exporter", "data_type": "logs", "name": "debug"}
Error: failed to build pipelines: failed to create "syslog" receiver for data type "logs": failed to resolve syslog config: failed to load location America/New_York: unknown time zone America/New_York
2024/04/18 09:24:29 collector server run finished with error: failed to build pipelines: failed to create "syslog" receiver for data type "logs": failed to resolve syslog config: failed to load location America/New_York: unknown time zone America/New_York
```

### Additional context

Waking through the same reproduction steps with the `clickhouseexporter` added to the binary (uncomment the line in `builder-config.yaml`) will result in the collector starting and working normally. It looks to me that the `syslogreciever` should possibly include a underline import like the `clickhouse-go` library to ensure that the tz database ends up in the binary.
