### ISSUE TITLE
New component: GitHub Actions Logs Receiver

### ISSUE THREAD

**Issue by reakaleek** [open-telemetry/opentelemetry-collector-contrib#32505]
### The purpose and use-cases of the new component

Our primary use case is to collect logs from multiple GitHub repositories in our organization and store them in a single place.

The GitHub Actions Log Receiver would receive `workflow_run` GitHub events through a webhook.

When a workflow is `completed`, it downloads the log files and converts them to logs that can be consumed by the logs consumer.

Downloading logs requires the permission `actions: read`; hence, you can provide GitHub PAT or GitHub App credentials. The token or app needs the appropriate permissions for any webhook event it receives. 

Also, you can validate the incoming payload using a webhook secret.

Hence, to allow the collector to receive webhook events, you can specify the webhook endpoint in a GitHub App or in a repository webhook.

### Example configuration for the component

```yaml
      githubactionslog:
        github_auth: # required
          app_id: "${env:GITHUB_APP_ID}"
          installation_id: "${env:GITHUB_INSTALLATION_ID}"
          private_key: "${env:GITHUB_APP_PRIVATE_KEY}"
          # or only a PAT
          token: "${env:GITHUB_TOKEN}"
        batch_size: 10000 # consume logs in batches
        webhook_secret: "${env:WEBHOOK_SECRET}" # optional
        endpoint: localhost:19419
        path: /events
        health_check_path: /health
```

### Telemetry data types supported

logs

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Additional context

We are aware of and even highly inspired by the existing contribution in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27460, but we decided to create our own receiver. 

However, if desired, I am willing to dismiss this proposal and contribute to the existing PR. cc @krzko

We have a working implementation in https://github.com/reakaleek/opentelemetry-collector-contrib/tree/feature/githubactionslogsreceiver/receiver/githubactionslogreceiver and are using it to store logs in elasticsearch.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/16325797/129e4ee7-555b-482d-87a9-dbc45aab7e52)

Because we were aware of the existing receiver, we copied the functions to generate trace and span IDs, as well as service names, to be able to correlate traces with logs.
