### ISSUE TITLE
read multiple resource attributes from a single k8s attribute or label

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-collector-contrib#32515]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

In the otel operator, I'd like to write an annotation or label with the content of all resource attributes, e.g.

```yaml
attributes:
  opentelemetry.io/resource-attributes: service.namespace=shop,deployment.environment=prod
```

The k8s attributes processor should then be able to parse this attribute and set both resource attributes.

### Describe the solution you'd like

```yaml
extract:
  annotations:
    - tag_from_key: true
      key: opentelemetry.io/resource-attributes
      from: pod
```
