### ISSUE TITLE
[receiver/vcenter] No Cluster Attribute on Clustered Resource Pool Resources

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#32535]
### Component(s)

receiver/vcenter

## Description
Currently even though the Resource Pool resources are returned with enough attributes for uniqueness (because of the `vcenter.resource_group.inventory_path`), the info inside of `vcenter.resource_group.inventory_path` is not completely standardized and therefore the Datacenter and Cluster info within this attribute cannot reliably be determined. Nested folder structures within vCenter can make both the Datacenter and Cluster names appear in unpredictable locations. Standalone hosts complicate pulling this info further.

A `vcenter.cluster.name` attribute that is added to all Resource Pool resources (that belong to a Cluster and not a Standalone Host) would both allow users to see this context as well as keep the attributes consistent between the other resources of this receiver.

(The Datacenter attribute version of this issue is already covered in #32531 )

## Steps to Reproduce
Collect against any vCenter environment with a vCenter Cluster (not Standalone Host only).

## Expected Result
Returned Resource Pool resources should have a `vcenter.cluster.name` resource attribute

## Actual Result
Returned Resource Pool resources have no `vcenter.cluster.name`

### Collector version

v1.5.0/v0.98.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/prom:
    client_auth:
      username: [PROMUSER]
      password: [PROMPASS]

exporters:
  prometheusremotewrite:
    endpoint: [PROMENDPOINT]
    auth:
      authenticator: basicauth/prom
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

processors:
  batch:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor

receivers:
  vcenter:
    endpoint: https://[VCENTERHOST]
    username: [VCENTERUSER]
    password: [VCENTERPASS]
    tls:
      insecure: true
    collection_interval: 1m
    initial_delay: 1s

service:
  extensions: [basicauth/prom]
  pipelines:
    metrics:
      receivers: [vcenter]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
