### ISSUE TITLE
[receiver/vcenterreceiver] No attributes to define datacenter

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#32531]
### Component(s)

receiver/vcenter

## Description
Currently, when collecting against any environment, none of the existing resources have resource attributes that define which datacenter they belong to. If there were multiple datacenters, this could cause confusion and even allow for the possibility of two resources with the exact same resource attribute key/values.

## Steps to Reproduce
Collect against any vCenter environment.

## Expected Result
All returned resources have a `vcenter.datacenter.name` resource attribute

## Actual Result
No returned resources have resource attributes related to datacenter

### Collector version

v1.5.0/v0.98.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/prom:
    client_auth:
      username: [PROMUSER]
      password: [PROMPASS]

exporters:
  prometheusremotewrite:
    endpoint: [PROMENDPOINT]
    auth:
      authenticator: basicauth/prom
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

processors:
  batch:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor

receivers:
  vcenter:
    endpoint: https://[VCENTERHOST]
    username: [VCENTERUSER]
    password: [VCENTERPASS]
    tls:
      insecure: true
    collection_interval: 1m
    initial_delay: 1s

service:
  extensions: [basicauth/prom]
  pipelines:
    metrics:
      receivers: [vcenter]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
