### ISSUE TITLE
[receiver/vcenter] Host Resource Should Not Have `vcenter.cluster.name` Attribute if Standalone (Not Clustered)

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#32548]
### Component(s)

receiver/vcenter

## Description
Having a `vcenter.cluster.name` attribute with a value of the Host name (duplicated by the `vcenter.host.name` attribute) returned for Standalone Host resources could be confusing for a customer in understanding which hosts are standalone or clustered.  

A cluster attribute doesn’t make sense for a Standalone Host, as they do not have any concept of a cluster related to them (currently children resources of standalone hosts like VMs or resource pools do not have this extra cluster attribute, so there’s not a good reason for the Host resource to have it either). 

## Steps to Reproduce
Collect against any vCenter environment with a vCenter Standalone Host

## Expected Result
Returned Standalone Host resources should not have a `vcenter.cluster.name` attribute

## Actual Result
Returned Standalone Host resources DO have a `vcenter.cluster.name` attribute

### Collector version

v1.5.0/v0.98.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/prom:
    client_auth:
      username: [PROMUSER]
      password: [PROMPASS]

exporters:
  prometheusremotewrite:
    endpoint: [PROMENDPOINT]
    auth:
      authenticator: basicauth/prom
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

processors:
  batch:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor

receivers:
  vcenter:
    endpoint: https://[VCENTERHOST]
    username: [VCENTERUSER]
    password: [VCENTERPASS]
    tls:
      insecure: true
    collection_interval: 1m
    initial_delay: 1s

service:
  extensions: [basicauth/prom]
  pipelines:
    metrics:
      receivers: [vcenter]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
