### ISSUE TITLE
[receiver/vcenter] No Inventory Path Resource Attribute for VM Resources with vApp Parent

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#32557]
### Component(s)

receiver/vcenter

## Description
Currently, VM resources that are children of a vApp (compared to a Resource Pool) are returned without the `vcenter.resource_pool.name` and `vcenter.resource_pool.inventory_path` attributes. While this generally makes sense (even though the vCenter API categorizes VirtualApp as an extension of ResourcePool), this causes these resources to not be very human identifiable. 

For these VMs, it would still be equally as useful to see their parent vApp's inventory path and name in resource attributes in order to help identify two same named VMs (and would have better parity with their Resource Pool parented cousins).

## Steps to Reproduce
Collect against any vCenter environment with a vApp which contains one or more VMs.

## Expected Result
Returned VM resources that are children of a vApp have helpful resource attributes returned that define identifying parent details like inventory path & parent name (similar to VM resources that are children of Resource Pools)

## Actual Result
Returned VM resources that are children of a vApp have no helpful resource attributes returned that define identifying parent details like inventory path & parent name

### Collector version

v1.5.0/v0.98.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/prom:
    client_auth:
      username: [PROMUSER]
      password: [PROMPASS]

exporters:
  prometheusremotewrite:
    endpoint: [PROMENDPOINT]
    auth:
      authenticator: basicauth/prom
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

processors:
  batch:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor

receivers:
  vcenter:
    endpoint: https://[VCENTERHOST]
    username: [VCENTERUSER]
    password: [VCENTERPASS]
    tls:
      insecure: true
    collection_interval: 1m
    initial_delay: 1s

service:
  extensions: [basicauth/prom]
  pipelines:
    metrics:
      receivers: [vcenter]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
