### ISSUE TITLE
New component: Sum Connector

### ISSUE THREAD

**Issue by greatestusername** [open-telemetry/opentelemetry-collector-contrib#32669]
### The purpose and use-cases of the new component

Sum Connector takes in logs, metrics, or traces and matches an attribute then allows summing numerical values present in that attribute and sending those sums as a time series metric along with any attributes defined within the connector config.

E.G. Log contains a field for `total_price` of a cart. Matching on `total_price` will take numerical values from this field and emit a time series metric of the sums along with any other attributes defined in the connector config.

This will function similarly to -- and be patterned after --  the current [countconnector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/countconnector) but emitting sums of values rather than counts of occurrences.

### Example configuration for the component

```
receivers:
  foo:
connectors:
  sum:
    logs:
      field.to.metric.sum:
        conditions:
          - attributes["boop"] != "NULL"
        attributes:
          - key: boop
            default_value: unspecified_level
          - key: env
            default_value: no_env
exporters:
  bar:

service:
  pipelines:
    metrics/sum:
       receivers: [sum]
       exporters: [bar]
    logs:
       receivers: [foo]
       exporters: [sum]
```

### Telemetry data types supported

In: Traces, metrics, logs
Out: Metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

greatestusername, shalper2

### Sponsor (optional)

@crobert-1

**Comment by crobert-1** [comment]
Hello @greatestusername, can you share a bit more details on the proposed configuration? I'm not sure I follow the proposed options and how it would impact the resulting output.

**Comment by crobert-1** [comment]
Thanks for sharing another example, that was helpful for me to better understand. A couple more questions:

1. For your given example, shouldn't we also specify `source_attribute` or something like that? Maybe I'm missing something, but the given config doesn't seem to specify where the actual value is coming from, it just filters logs where `total.payment` is `NULL`.
2. I assume the default configuration for this component would be no options specified, and then every attribute would be summed, is that accurate? Then if a single new metric is defined, do we _**only**_ keep that, and drop the rest?

**Comment by crobert-1** [comment]
I'll sponsor this component 👍

**Comment by greatestusername** [comment]
> Thanks for sharing another example, that was helpful for me to better understand. A couple more questions:
> 
> 1. For your given example, shouldn't we also specify `source_attribute` or something like that? Maybe I'm missing something, but the given config doesn't seem to specify where the actual value is coming from, it just filters logs where `total.payment` is `NULL`.
> 2. I assume the default configuration for this component would be no options specified, and then every attribute would be summed, is that accurate? Then if a single new metric is defined, do we _**only**_ keep that, and drop the rest?

Thank you for offering to sponsor this!

Also thank you for pointing this out! Yes a `source_attribute` does make sense! I was initially using the conditions and looking for the field in the conditions. So yes I think a single `source_attribute` setting to define which attribute to look for the numerical value. Then any conditions are just conditions rather than where the value is found.

I think having `source_attribute` would also answer question 2? We'd only ever metricize the defined attribute then sum those values into a single metric.

Example config with `source_attribute`:
```
receivers:
  foo:
connectors:
  sum:
    logs:
      checkout.total:
        source_attribute: 
          - attributes["total.payment"]
        conditions:
          - attributes["total.payment"] != "NULL"
        attributes:
          - key: payment.processor
            default_value: unspecified_processor
          - key: env
            default_value: no_env
exporters:
  bar:

service:
  pipelines:
    metrics/sum:
       receivers: [sum]
       exporters: [bar]
    logs:
       receivers: [foo]
       exporters: [sum]
```

Does that make sense?
