### ISSUE TITLE
[receiver/vcenter] `vcenter.cluster.name` Resource Attribute Does Not Make Sense for Datastore Resource

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#32674]
### Component(s)

receiver/vcenter

## Description
Datastores do not “belong” to Clusters (especially not a single Cluster). Datastores exist on the Datacenter level. But Hosts & Clusters (more specifically the Hosts within Clusters) make use of them.

Currently, there is odd behavior where Datastore metrics are repeated for each cluster (although the metric datapoint values are all the same, just with a different cluster attribute on the containing Resource). Datastore metrics are also repeated for standalone Hosts, but no matter how many of these Hosts exist, there will only be one set of metrics (because the containing Resource will not have a cluster attribute).

## Steps to Reproduce
Collect against any vCenter environment with Datastores and some mix of multiple Clusters/Standalone Hosts.

## Expected Result
A single set of metrics would come back for each Datastore under a Resource that represents that Datastore.

## Actual Result
For each Datastore, Datastore Resources are created for each Cluster with repeated metrics. An additional Datastore Resource will also be created for any amount of standalone Hosts with repeated metrics.

### Collector version

v1.5.0/v0.98.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/prom:
    client_auth:
      username: [PROMUSER]
      password: [PROMPASS]

exporters:
  prometheusremotewrite:
    endpoint: [PROMENDPOINT]
    auth:
      authenticator: basicauth/prom
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

processors:
  batch:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor

receivers:
  vcenter:
    endpoint: https://[VCENTERHOST]
    username: [VCENTERUSER]
    password: [VCENTERPASS]
    tls:
      insecure: true
    collection_interval: 1m
    initial_delay: 1s

service:
  extensions: [basicauth/prom]
  pipelines:
    metrics:
      receivers: [vcenter]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
