### ISSUE TITLE
Using processor/filter to drop/keep spans depending on span name

### ISSUE THREAD

**Issue by JasmineCA** [open-telemetry/opentelemetry-collector-contrib#32691]
### Component(s)

processor/filter

### Describe the issue you're reporting

Hello everyone,

I started to use opentelemetry collector to duplicate and re-route spans from different sources to different backends. So we started to ask ourselves how to filter our spans. We decided we will first route spans with their name, which is not a resource attribute, so we could not use the routing connector. Instead, we went for the processor/filter. 

However, the rule "keep this span if name matches xxx" translates into "drop this span if name does not match xxx" with filter. And it is difficult when you add span names. Here is the current configuration of the filter:

```yaml
processors:
  filter:
    error_mode: ignore
    traces:
      span:
        - (not IsMatch(name, ".*/foo")) or (not IsMatch(name,".*/bar))
```

We can also put a single IsMatch and a regex containing all the span names we want to keep, but maybe there is a better solution? In filter there is some include/exclude, but based on resource attributes, which is not possible for span name. Or maybe another processor I didn't stubble into? Do you have a better syntax/solution or do you plan to add this feature to processor/filter?

Thank you!
