### ISSUE TITLE
Not able to scrape metrics using prometheus receiver 

### ISSUE THREAD

**Issue by kadhamecha-conga** [open-telemetry/opentelemetry-collector-contrib#32710]
### Component(s)

receiver/prometheus

### What happened?

The OTel Collector which is running in daemonset mode , which is configured to scrape metrics from pods based on specific annotations, Typically like prometheus.io/scrape and prometheus.io/path to identify pods that expose metrics and the paths where the metrics are available.

i have attached to config and logs to scrape the metrics based on annotation , but scraping is not done and not able to receive the metrics.

can you please help ?

thanks.

### Collector version

0.73

### Environment information

EKS 1.26 

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
          config:
            scrape_configs:
            - job_name: apps
              kubernetes_sd_configs:
              - role: pod
                selectors:
                - field: spec.nodeName=$KUBE_NODE_NAME
                  role: pod
              relabel_configs:
              - action: keep
                regex: "true"
                source_labels:
                - __meta_kubernetes_pod_ready
              - action: keep
                regex: "true"
                source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scrape
              - action: replace
                regex: (.+)
                source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_path
                target_label: __metrics_path__
              - action: replace
                regex: (.+)(?::\d+);(\d+)
                replacement: $$1:$$2
                source_labels:
                - __address__
                - __meta_kubernetes_pod_annotation_prometheus_io_port
                target_label: __address__
              scrape_interval: 30s

    service:
      extensions: [health_check, zpages, memory_ballast]
      telemetry:
        logs:
          level: info
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [otlp, logging]
        metrics:
          receivers: [prometheus,kubeletstats/infra, k8s_cluster]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [otlphttp/metrics]
        logs:
          receivers: [filelog]
          processors: [memory_limiter, k8sattributes, resource/container, resource, batch]
          exporters: [otlp, logging]
```

### Log output

```shell
info	prometheusreceiver@v0.73.0/metrics_receiver.go:243	Scrape job added	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "jobName": "opentelemetry-collector"}
info	prometheusreceiver@v0.73.0/metrics_receiver.go:243	Scrape job added	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "jobName": "apps"}
info	kubernetes/kubernetes.go:326	Using pod service account via in-cluster config	{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "discovery": "kubernetes", "config": "apps"}
info	prometheusreceiver@v0.73.0/metrics_receiver.go:255	Starting discovery manager	{"kind": "receiver", "name": "prometheus", "data_type": "metrics"}
info	prometheusreceiver@v0.73.0/metrics_receiver.go:289	Starting scrape manager	{"kind": "receiver", "name": "prometheus", "data_type": "metrics"}
```
