### ISSUE TITLE
[receiver/kubeletstats] inconsistency while collecting memory usage

### ISSUE THREAD

**Issue by zied-chekir** [open-telemetry/opentelemetry-collector-contrib#32739]
### Component(s)

receiver/kubeletstats

## Description
I'm currently collecting memory usage metric of every node with a daemonset collector using the kubestats receiver, but I've noticed an inconsistency in the memory usage values. When comparing the values scraped with the receiver to those obtained with the 'kubectl top nodes' command, there's a notable difference. While the command reports around 11GB of memory usage, the receiver's sum of values is approximately 20GB, which is double the expected value. I am not sure if this is a bug in the receiver or if it is something else. 
node 1:
<img width="572" alt="node1" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/166112936/9d843cfe-8c05-4c7e-a9cf-d28c575a99f6">
node 2:
<img width="572" alt="node2" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/166112936/22356203-dcca-4aa6-9297-bbc0f7602780">
node 3:
<img width="575" alt="node3" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/166112936/ee288017-23e2-4e1b-a098-3248052457b1">
node 4:
<img width="538" alt="node4" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/166112936/135d9768-c67e-48a1-934a-bcb7534db000">
all nodes with "k top nodes"
<img width="647" alt="nodes_metrics" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/166112936/0ab560cf-ec9a-40d0-9e3b-6f49cebb1b20">

## Expected Result
Cluster memory usage should be around 11GB ( sum of all node's memory ).
## Actual Result
Cluster memory usage is around 20GB.

### Collector version

0.98.0

## Environment
kubernetes: v1.29.2

### OpenTelemetry Collector configuration

```yaml
receivers:
      kubeletstats:
        auth_type: "serviceAccount"
        endpoint: https://${env:K8S_NODE_NAME}:10250
        metric_groups:
        - pod
        - node      
....
service:
   pipelines:
        metrics/kublet:
          receivers: [kubeletstats]
          processors: [k8sattributes, memory_limiter, batch]
          exporters: [otlp/metrics_k8s_kublet]
```
