### ISSUE TITLE
[receiver/vcenter] `vcenter.cluster.memory.effective` Has Incorrect Unit

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#32782]
### Component(s)

receiver/vcenter

## Description
Currently, the metric `vcenter.cluster.memory.effective` appears to be reporting a value in MiB rather than bytes as the metadata of the receiver suggests. This is backed up by the documentation [here](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/d1902b0e-d479-46bf-8ac9-cee0e31e8ec0/07ce8dbd-db48-4261-9b8f-c6d3ad8ba472/vim.ComputeResource.Summary.html).

## Steps to Reproduce
Collect against any vCenter environment with an active Cluster.

## Expected Result
The `vcenter.cluster.memory.effective` metric would be returned for Cluster resources with the value representing a number of bytes.

## Actual Result
The `vcenter.cluster.memory.effective` metric is returned for Cluster resources with the value representing a number of MiB.

### Collector version

v1.6.0/v0.99.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/prom:
    client_auth:
      username: [PROMUSER]
      password: [PROMPASS]

exporters:
  prometheusremotewrite:
    endpoint: [PROMENDPOINT]
    auth:
      authenticator: basicauth/prom
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

processors:
  batch:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor

receivers:
  vcenter:
    endpoint: https://[VCENTERHOST]
    username: [VCENTERUSER]
    password: [VCENTERPASS]
    tls:
      insecure: true
    collection_interval: 1m
    initial_delay: 1s

service:
  extensions: [basicauth/prom]
  pipelines:
    metrics:
      receivers: [vcenter]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
