### ISSUE TITLE
ordering_criteria  does not work for filelog receiver

### ISSUE THREAD

**Issue by zekai-rai** [open-telemetry/opentelemetry-collector-contrib#32792]
### Component(s)

receiver/filelog

## Description

After setting ordering_criteria with mtime, I observed that files are always processed in the descending order of the mtime, regardless whether ascending is true or false. 

I need this for both filelog receiver and otlpjsonfile receiver and tested both. 

## Steps to Reproduce

Configure the receiver this way, and add file one by one so that they have different last modified timestamps. 

```
otlpjsonfile/metrics:
    include: [ /mount/shared-events/test_metrics/data_*.json ]
    start_at: "beginning" # set to "end" if delete_after_read is set to false
    poll_interval: 5s
    fingerprint_size: 5kb
    delete_after_read: true # If true, each log file will be read and then immediately deleted
    #storage: file_storage
    ordering_criteria:
      sort_by: 
        sort_type: mtime
        ascending: true
```

## Expected Result
With sort_type: mtime and ascending: true, I expected files to be processed in the ascending order of the modified time. 

## Actual Result
Files are always processed in the descending order. 

### Collector version

v0.98

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
otlpjsonfile/metrics:
    include: [ /mount/shared-events/test_metrics/data_*.json ]
    start_at: "beginning" 
    poll_interval: 5s
    fingerprint_size: 5kb
    delete_after_read: true # If true, each log file will be read and then immediately deleted
    #storage: file_storage
    ordering_criteria:
      sort_by: 
        sort_type: mtime
        ascending: true
```
