### ISSUE TITLE
[receiver/vcenter] `vcenter.cluster.memory.used` Not Implemented

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#32805]
### Component(s)

receiver/vcenter

## Description
Currently, the `vcenter.cluster.memory.used` is not actually implemented. I verified this by looking at the code.

## Steps to Reproduce
Collect against any vCenter environment with an active Cluster.

## Expected Result
See the `vcenter.cluster.memory.used` metric returned for Cluster resources.

## Actual Result
No `vcenter.cluster.memory.used` metric returned for Cluster resources.

### Collector version

v1.6.0/v0.99.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/prom:
    client_auth:
      username: [PROMUSER]
      password: [PROMPASS]

exporters:
  prometheusremotewrite:
    endpoint: [PROMENDPOINT]
    auth:
      authenticator: basicauth/prom
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

processors:
  batch:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor

receivers:
  vcenter:
    endpoint: https://[VCENTERHOST]
    username: [VCENTERUSER]
    password: [VCENTERPASS]
    tls:
      insecure: true
    collection_interval: 1m
    initial_delay: 1s

service:
  extensions: [basicauth/prom]
  pipelines:
    metrics:
      receivers: [vcenter]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
