### ISSUE TITLE
[receiver/vcenter] `vcenter.cluster.vm.count` Does Not Report Suspended VM Counts

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#32803]
### Component(s)

receiver/vcenter

## Description
Currently, the `vcenter.cluster.vm.count` metric only returns datapoints for Powered On and Powered Off VM counts (through the `vm_count_power_state` attribute). Any suspended VMs get lumped into the Powered On count which isn't really correct.

## Steps to Reproduce
Collect against any vCenter environment with an active Cluster.

## Expected Result
The `vcenter.cluster.vm.count` metric returns values that represent VM "Powered On" count, "Powered Off" count, and "Suspended" count.

## Actual Result
The `vcenter.cluster.vm.count` metric returns values that represent VM "Powered Off count". It also returns value for "Powered On" + "Suspended" counts, but labels it as only "poweredOn" through the `vm_count_power_state` attribute.

### Collector version

v1.6.0/v0.99.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/prom:
    client_auth:
      username: [PROMUSER]
      password: [PROMPASS]

exporters:
  prometheusremotewrite:
    endpoint: [PROMENDPOINT]
    auth:
      authenticator: basicauth/prom
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

processors:
  batch:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor

receivers:
  vcenter:
    endpoint: https://[VCENTERHOST]
    username: [VCENTERUSER]
    password: [VCENTERPASS]
    tls:
      insecure: true
    collection_interval: 1m
    initial_delay: 1s

service:
  extensions: [basicauth/prom]
  pipelines:
    metrics:
      receivers: [vcenter]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
