### ISSUE TITLE
[receiver/vcenter] No Explicit Distinction Between VMs & VM Templates

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#32821]
### Component(s)

receiver/vcenter

## Description
Currently this receiver makes no distinction between VMs & VM Templates. VM Templates can be used to quickly spin up a VM, but can not be turned on/active themselves. In the vCenter UI, these two resource types are differentiated throughout.

One area in the receiver where this is most noticeable is the `vcenter.cluster.vm.count` metric (it includes the count of VM templates in the value where the `vm_count_power_state` is 'poweredOff`).

Another is how VM & VM templates resources that are returned aren't explicitly differentiated. They have some implicit differences though. 

Currently VM Templates are represented as Resources, but do NOT have the Resource Attributes `vcenter.resource_pool.name`, `vcenter.resource_pool.inventory_path`, `vcenter.virtual_app.name`, or `vcenter.virtual_app.inventory_path`. Technically a standard VM could also be returned without these attributes as well if permissions were incorrect for grabbing Resource Pools from the API (although this would be a prerequisite error and should be extremely rare).

Some metrics will also never return for a VM Template Resource, but this occurs for VMs under certain conditions as well.

## Steps to Reproduce
Collect against any vCenter environment with both VMs & VM Templates.

## Expected Result
See some sort of differentiation in the `vcenter.cluster.vm.count` metric between VMs & VM templates. Also be able to see some explicit Resource Attribute indicator that a resource is a VM template rather than a standard VM.

## Actual Result
`vcenter.cluster.vm.count` wraps templates up in its returned values. Returned Resources that represent VM Templates don't have explicit indicators that they are templates.

### Collector version

v1.6.0/v0.99.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/prom:
    client_auth:
      username: [PROMUSER]
      password: [PROMPASS]

exporters:
  prometheusremotewrite:
    endpoint: [PROMENDPOINT]
    auth:
      authenticator: basicauth/prom
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels

processors:
  batch:
    # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor

receivers:
  vcenter:
    endpoint: https://[VCENTERHOST]
    username: [VCENTERUSER]
    password: [VCENTERPASS]
    tls:
      insecure: true
    collection_interval: 1m
    initial_delay: 1s

service:
  extensions: [basicauth/prom]
  pipelines:
    metrics:
      receivers: [vcenter]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
