### ISSUE TITLE
K8s attribute processor not adding correct attributes when used on a collector deployed in deployment (gateway) mode 

### ISSUE THREAD

**Issue by csongnr** [open-telemetry/opentelemetry-collector-contrib#32857]
### Component(s)

processor/k8sattributes

## Description
When using otel in deployment mode, I'm finding that the k8sattribute processor is not decorating metadata correctly, in metrics where the node name is included as an attribute, the added attribute (k8s.node.name) doesn't match the node name reported on the metric, my suspicion is the k8s attribute processor is reporting the node that's hosting the collector, rather than the node where the metric originates from. example metrics where the data is incorrect attached below  

## Steps to Reproduce
deployment: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.naming.fullname" . }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
      component: deployment
  template:
    metadata:
      labels:
        {{- include "common.labels.selectorLabels" . | nindent 8 }}
        component: deployment
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/deployment-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "common.serviceAccount.name" . }}
      containers:
        - name: otel-collector-deployment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["--config", "/config/deployment-config.yaml"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KUBE_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.license.secretName" . }}
                  key: {{ include "common.license.secretKeyName" . }}
          ports:
            - name: grpc
              containerPort: 4317
              protocol: TCP
            - name: http
              containerPort: 4318
              protocol: TCP
          volumeMounts:
            - name: deployment-config
              mountPath: /config
      volumes:
        - name: deployment-config
          configMap:
            name: {{ include "common.naming.fullname" . }}-deployment-config
      {{- with include "common.nodeSelector" . }}
```
deployment-config: 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-config
  namespace: {{ .Release.Namespace }}
data:
  deployment-config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs: 
            - job_name: kube-state-metrics
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: keep
                  regex: kube-state-metrics
                  source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
            - job_name: apiserver
              kubernetes_sd_configs:
                - role: endpoints
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                  action: keep
                  regex: kubernetes;https
                - action: replace
                  source_labels:
                  - __meta_kubernetes_namespace
                  target_label: Namespace
                - action: replace
                  source_labels:
                  - __meta_kubernetes_service_name
                  target_label: Service
    
    processors:
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
          - sources: 
            - from: resource_attribute
              name: k8s.pod.uid

      batch:

    exporters:
      otlphttp:
        endpoint: {{ .Values.endpoint }}
        headers:
          api-key: ${env:LICENSE_KEY}
 
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: 
            - k8sattributes
            - batch
          exporters:
            - otlphttp
         
``` 
## Expected Result
Metrics that report a node name as an attribute are reporting a different node name than the one being added by the k8sattribute processor (k8s.node.name), seeing the same things w/ k8s.pod.name as well as k8s.deployment.name 

## Actual Result

<img width="1389" alt="Screenshot 2024-05-04 at 21 03 06" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/115833851/38453e4c-99ce-4d44-959c-231d9032b88b">

### Collector version

0.99.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

GKE standard cluster 

### OpenTelemetry Collector configuration

```yaml
receivers:
      prometheus:
        config:
          scrape_configs: 
            - job_name: kube-state-metrics
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: keep
                  regex: kube-state-metrics
                  source_labels:
                    - __meta_kubernetes_pod_label_app_kubernetes_io_name
            - job_name: apiserver
              kubernetes_sd_configs:
                - role: endpoints
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: true
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              relabel_configs:
                - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                  action: keep
                  regex: kubernetes;https
                - action: replace
                  source_labels:
                  - __meta_kubernetes_namespace
                  target_label: Namespace
                - action: replace
                  source_labels:
                  - __meta_kubernetes_service_name
                  target_label: Service
    
    processors:
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: KUBE_NODE_NAME
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
        pod_association:
          - sources: 
            - from: resource_attribute
              name: k8s.pod.uid


      batch:

    exporters:
      otlphttp:
        endpoint: {{ .Values.endpoint }}
        headers:
          api-key: ${env:LICENSE_KEY}
 
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: 
            - k8sattributes
            - batch
          exporters:
            - otlphttp
```

### Additional context

k8sattribute processor metadata decoration also broken when used on daemonset w/ same configuration as above.
