### ISSUE TITLE
unknown servuce opentelemetry.proto.collector.trace.v1.TraceService

### ISSUE THREAD

**Issue by kaaax0815** [open-telemetry/opentelemetry-collector-contrib#32892]
## Description
I am trying to setup traefik, collector and jaeger

## Steps to Reproduce
https://opentelemetry.io/docs/collector/installation/

## Expected Result
Should see results in jaeger

## Actual Result
throws error

### Collector version

0.100.0

## Environment
OS: Ubuntu 22.04
Compiler: n/a

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  otlp:
    endpoint: jaeger:14250
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
```

### Log output

```shell
otel-collector-1  | 2024-05-07T08:51:26.946Z	error	exporterhelper/queue_sender.go:101	Exporting failed. Dropping data.	{"kind": "exporter", "data_type": "traces", "name": "otlp", "error": "not retryable error: Permanent error: rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.trace.v1.TraceService", "dropped_items": 16}
otel-collector-1  | go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1
otel-collector-1  | 	go.opentelemetry.io/collector/exporter@v0.100.0/exporterhelper/queue_sender.go:101
otel-collector-1  | go.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Consume
otel-collector-1  | 	go.opentelemetry.io/collector/exporter@v0.100.0/internal/queue/bounded_memory_queue.go:52
otel-collector-1  | go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1
otel-collector-1  | 	go.opentelemetry.io/collector/exporter@v0.100.0/internal/queue/consumers.go:43
```

### Additional context

```yml
// docker-compose.yml
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - telemetry
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.jaeger.tls=true
      - traefik.http.routers.jaeger.tls.certresolver=letsencrypt
      - traefik.http.routers.jaeger.rule=Host(`jaeger.redacted`)
      - traefik.http.routers.jaeger.entrypoints=websecure
      - traefik.http.routers.jaeger.service=jaeger
      - traefik.http.services.jaeger.loadbalancer.server.port=16686
      - traefik.http.routers.jaeger.middlewares=services@file

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - /docker/telemetry/data/otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    networks:
      - telemetry
    depends_on:
      - jaeger

networks:
  telemetry:
    external: true
  traefik:
    external: true
```
