### ISSUE TITLE
[exporter/prometheusremotewriteexporter] Allow to set batch_send_deadline

### ISSUE THREAD

**Issue by pfrayer** [open-telemetry/opentelemetry-collector-contrib#32891]
### Component(s)

exporter/prometheusremotewrite

### Is your feature request related to a problem? Please describe.

In a standalone Prometheus remote-write's configuration, you can set up a `queue_config` with many options. For instance:

```yaml
queue_config:
  capacity: 3000
  max_shards: 100
  min_shards: 1
  max_samples_per_send: 1000
  batch_send_deadline: 30s
  min_backoff: 1s
  max_backoff: 60s
  retry_on_http_429: true
```

Currently in the `prometheusremotewriteexporter` you can only set the following:
```yaml
remote_write_queue:
  enabled: true
  queue_size: 3000
  num_consumers: 10
retry_on_failure:
  enabled: true
```
As we can't set the `batch_send_deadline` option, the  `prometheusremotewriteexporter` seems to perform remote-writes only each 60sec (can't find where it's set).
If the remote-write backend have less HA replicas than the number of  `prometheusremotewriteexporter`  pushing replicas, and the remote-write backend try to elect a new replicas leader less than each 60sec, the HA backend will pick a new leader and the send metrics will be dropped. 

### Describe the solution you'd like

Be able to define the remote-write frequency
