### ISSUE TITLE
Datadog: host.name attribute from apps are being set for otel.datadog_exporter.metrics.running

### ISSUE THREAD

**Issue by tonglil** [open-telemetry/opentelemetry-collector-contrib#3293]
**Describe the bug**
`otel.datadog_exporter.metrics.running` should only show `host` tags for the hosts running the collector.

However, the `host` tags from OTel instrumented apps are showing up in this metric in Datadog.

**Steps to reproduce**
Run the collector for datadog on host A.
Send a metric from host B.
Look in /metric/summary?filter=otel.&metric=otel.datadog_exporter.metrics.running and see `host` tag with A and B.

**What did you expect to see?**
It should only be A.

**What did you see instead?**
I see A and B.

**What version did you use?**
Version: latest version of otel/opentelemetry-collector-contrib:latest

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55682

processors:
  batch:
    timeout: 10s
  memory_limiter:
    # Same as --mem-ballast-size-mib CLI argument
    ballast_size_mib: 165
    # 80% of maximum memory up to 2G
    limit_mib: 400
    # 25% of limit up to 2G
    spike_limit_mib: 125
    check_interval: 5s

exporters:
  logging:
    loglevel: debug
  datadog/api:
    metrics:
      resource_attributes_as_tags: true
    tags:
      - source:otel
    api:
      key: "${DD_API_KEY}"

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [datadog/api, logging]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [datadog/api, logging]
```

**Environment**
GKE

**Additional context**
<img width="1018" alt="Screen Shot 2021-04-30 at 2 44 15 PM" src="https://user-images.githubusercontent.com/3250776/116757357-c8a5f100-a9c2-11eb-972c-6fd44ac9b0c9.png">

Expecting to only see `host:collector-...`, not `host:status-checks-dev-...`
