### ISSUE TITLE
Record pod Ready status, or all pod status conditions

### ISSUE THREAD

**Issue by gdvalle** [open-telemetry/opentelemetry-collector-contrib#32941]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

I would like to be able to see a pod's Ready status in metrics.

### Describe the solution you'd like

A named metric with an analog to `k8s.container.ready` ,like `k8s.pod.ready`.

Or, a more generic solution where all [pod status conditions](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#podcondition-v1-core) are represented, i.e. `k8s.pod.status.condition`. I might prefer this as it captures more states.

I would like to include attributes for the detail info fields (`message`, `reason`), for either approach.

### Describe alternatives you've considered

Using the existing k8s.container.ready metric. It's unfortunately not complete because of pod [ReadinessGates](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/580-pod-readiness-gates).

### Additional context

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32933 for an impl of `k8s.pod.ready`, currently sans attributes.

If we can agree, I think the condition status metric makes more sense. I think we need agreement on how to represent it: other things in this receiver (e.g. `k8s.pod.phase`) use values to represent states, so 0=false, 1=true, 2=unknown could fit, but the ergonomics are a bit poor.

**Comment by TylerHelmuth** [comment]
This feels reasonable, especially if there is existing precedence in KSM.

Is `PodStatus` already watchable via the k8sobjectsreceiver?

**Comment by sirianni** [comment]
>  I think we need agreement on how to represent it: other things in this receiver (e.g. k8s.pod.phase) use values to represent states, so 0=false, 1=true, 2=unknown could fit, but the ergonomics are a bit poor.

Please no.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29157 for a generic `k8s.pod.state` metric modeled after kube-state-metrics.

**Comment by sirianni** [comment]
In general, I feel like the piecemeal and fragmented approach to Kubernetes metrics in OTel is going to make it impossible to have any vendors build meaningful user experiences on top of this dataset, ultimately delaying any possible standardization in this space.

**Comment by TylerHelmuth** [comment]
> In general, I feel like the piecemeal and fragmented approach to Kubernetes metrics in OTel is going to make it impossible to have any vendors build meaningful user experiences on top of this dataset, ultimately delaying any possible standardization in this space.

We have had an uptick in k8s components feature request, it would be be very nice to make progress on https://github.com/open-telemetry/semantic-conventions/issues/1032

**Comment by sirianni** [comment]
Thanks @TylerHelmuth .  In general, my team has been happy with the metrics collected by `kubeletstatsreceiver` and how they are modeled.  They are struggling significantly with the "state" metrics that come from `k8sclusterreceiver`.  We are coming from a Datadog background.

**Comment by gdvalle** [comment]
> Regarding `k8s.pod.status.condition`, would be interesting to see some example data points to understand what kind of data would it actually produces and what did Kube State Metrics do in this regard.

Whoops, thought I answered your question earlier, but apparently didn't hit send.
KSM [seems to use named conditions](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/workload/pod-metrics.md), `kube_pod_status_ready` and `kube_pod_status_scheduled`, so they only support whatever someone bothers to implement.

The generic approach would take any condition and record points for it. Here's a sample from a GKE cluster:
```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'Pod is in NEG "Key{\"k8s1-7929355b-foo-80-6e399202\",
      zone: \"foo-b\"}". NEG is not attached to any BackendService with health
      checking. Marking condition "cloud.google.com/load-balancer-neg-ready" to True.'
    reason: LoadBalancerNegWithoutHealthCheck
    status: "True"
    type: cloud.google.com/load-balancer-neg-ready
  - lastProbeTime: null
    lastTransitionTime: "2024-05-28T19:14:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-05-28T19:14:36Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-05-28T19:14:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-05-28T19:14:20Z"
    status: "True"
    type: PodScheduled

```
The enum is the `status` field, so `Unknown`, `True`, or `False` ([docs](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions)).
We can use `reason` and `message` fields as attributes.
To illustrate:
```
k8s.pod.status.condition{type:"Ready", reason:"", message:""} 1
k8s.pod.status.condition{type:"cloud.google.com/load-balancer-neg-ready", reason:"LoadBalancerNegWithoutHealthCheck", message:'Pod is in NEG "Key{\"k8s1-7929355b-foo-80-6e399202\",
      zone: \"foo-b\"}". NEG is not attached to any BackendService with health
      checking. Marking condition "cloud.google.com/load-balancer-neg-ready" to True.'} 1
```
