### ISSUE TITLE
Prometheus Receiver sample_limit fails silently

### ISSUE THREAD

**Issue by bmiguel-teixeira** [open-telemetry/opentelemetry-collector-contrib#32964]
### Component(s)

receiver/prometheus

## Description

When setting up the `sample_limit` in the scrape configs, when the scrape size hits this value the limit is ONLY logged.

## Steps to Reproduce

Set a small `sample_limit` in a target config.

## Expected Result

Error Logged
otel_received_refused_metrics incremented.

## Actual Result
Error Logged
otel_received_refused_metrics remains at 0

### Collector version

0.100.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus/os:
    config:
      scrape_configs:
      - job_name: "xxxxx"
        sample_limit: 100
```
