### ISSUE TITLE
error: unsupported data type for start time metric

### ISSUE THREAD

**Issue by danilobuerger** [open-telemetry/opentelemetry-collector-contrib#32993]
### Component(s)

receiver/prometheus

## Description

Using the prometheus receiver to ingest the internal telemetry metrics leads to errors

## Steps to Reproduce

use config below

## Expected Result

no errors

## Actual Result

errors, see below

### Collector version

v0.100.0

## Environment
OS: any

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
    trim_metric_suffixes: true
    use_start_time_metric: true
    start_time_metric_regex: .*
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 30s
          static_configs:
            - targets: [localhost:8888]

exporters:
  otlp:
    endpoint: localhost:1337

service:
  telemetry:
    metrics:
      address: localhost:8888
  pipelines:
    metrics/prometheus:
      receivers: [prometheus]
      exporters: [otlp]
```

### Log output

```shell
2024-05-10T22:43:17.210+0200#011error#011scrape/scrape.go:1282#011Scrape commit failed#011{"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_pool": "otel-collector", "target": "http://localhost:8888/metrics", "error": "unsupported data type for start time metric"}
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1
#011github.com/prometheus/prometheus@v0.51.2-0.20240405174432-b4a973753c6e/scrape/scrape.go:1282
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport
#011github.com/prometheus/prometheus@v0.51.2-0.20240405174432-b4a973753c6e/scrape/scrape.go:1360
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run
#011github.com/prometheus/prometheus@v0.51.2-0.20240405174432-b4a973753c6e/scrape/scrape.go:1237
```
