### ISSUE TITLE
loadbalancing: k8s_resolver issuing too many LIST calls to the K8S API 

### ISSUE THREAD

**Issue by diranged** [open-telemetry/opentelemetry-collector-contrib#33004]
### Component(s)

exporter/loadbalancing

## Description

It seems that the Loadbalancing `k8s_receiver` is not relying enough on its `watch` call for the service endpoints, and is instead issuing too many `list` calls. At low scale, this is not terrible .. but when running clusters with 800+ nodes, this becomes a meaningful step-change in the API access behavior patterns:

Here is the graph of `read` API requests  now vs 7 days ago.. the step-change correlates to when we swiched from using `dns` to `k8s` for our `loadbalancing` exporter (_dashed line is 7 day previous average_).

<img width="1621" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/768067/2047624f-45c9-4190-92b4-71889405dfc1">

## Steps to Reproduce

The configuration below exhibits the problem.. and if we switch back to the `dns` resolver, the issue goes away.

```yaml
exporters:
  loadbalancing/metrics:
  routing_key: resource
  protocol:
    otlp:
      tls:
        insecure_skip_verify: true
        ca_file: /tls/ca.crt
        cert_file: /tls/tls.crt
        key_file: /tls/tls.key
  resolver:
    k8s:
      service: '{{ include "common.fullname" . }}-metrics-aggregation-collector-headless.{{ .Release.Namespace }}'
      ports: [4317]
  # works fine:
  # dns:
  #   hostname: '{{ include "common.fullname" . }}-metrics-aggregation-collector-headless.{{ .Release.Namespace }}'
  #    port: 4317
```

## Expected Result

I expect that [this code path](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.99.0/exporter/loadbalancingexporter/resolver_k8s.go#L95-L106) is going to use a `list` call upon startup, and then keep a `watch` going for the rest of the updates.. but based on the request/sec, it doesn't feel like that's happening. At ~600-800 nodes average, this implies that every `~2m` the nodes are issuing a fresh `list` call.

### Collector version

0.99.0

## Environment
OS: BottleRocket 1.19.2
