### ISSUE TITLE
loadbalancing exporter[>=v0.94.0] has memory issue

### ISSUE THREAD

**Issue by alburthoffman** [open-telemetry/opentelemetry-collector-contrib#33020]
### Component(s)

exporter/loadbalancing

## Description
We tried to upgrade our otel collector in prod and started see memory increased a lot and later pods were OOMKilled.
And when rollback the pods become stable and memory reduce to 1/5.

## Steps to Reproduce
1. enable loadbalancing to export traces
2. upgrade to the version >=0.94.0
3. compare the the memory usage
4. run for a while and rollback.

## Expected Result
the memory should increase slowly comparing to old version.

## Actual Result
when rolling back, we will see
<img width="1140" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/863684/ff338ddb-5cdb-4ce2-ac67-04a2c4eb0777">

### Collector version

>=0.94.0

## Environment
OS: alpine 3.12
Compiler(if manually compiled): go 1.21.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: 0.0.0.0:14268
  zipkin:
  otlp:
    protocols:
      grpc:
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  loadbalancing:
    routing_key: "service"
    protocol:
      otlp:
        sending_queue:
          enabled: true
          num_consumers: 300
          queue_size: 200000
        tls:
          insecure: true
        timeout: 10s
    resolver:
      dns:
        hostname: span-processor
        port: 4317

processors:
  batch:
    timeout: 5s
    send_batch_size: 800
  memory_limiter:
    check_interval: 1s
    limit_percentage: 90
    spike_limit_percentage: 5
  k8sattributes:
    passthrough: false
    extract:
      metadata:
        - k8s.namespace.name
        - k8s.pod.name
        - k8s.node.name
        - k8s.pod.hostname
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.name
service:
  pipelines:
    traces:
      receivers: [jaeger,otlp]
      processors: [memory_limiter, batch, resource, k8sattributes]
      exporters: [loadbalancing]
  extensions: [health_check, pprof, zpages]
```
