### ISSUE TITLE
[pkg/stanza] Clarify how "nested" attributes produced by operators should be handled 

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/opentelemetry-collector-contrib#33029]
### Component(s)

pkg/stanza

### Describe the issue you're reporting

As discussed at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32594#issuecomment-2107540529, it's not super clear if attributes produced by stanza operators should be nested of flat.

A configuration like the following:

```yaml
receivers:
  filelog:
    include:
    - /var/log/pods/*/*/*.log
    operators:
      - id: some
        type: add
        field: attributes.key2.key_in
        value: val2
```

gives:

```console
Attributes:
     ...
     -> key2: Map({"key_in":"val2"})
```

If we want to have a flat field instead of a nested one we should use `field: attributes["key2.key_in"]`.

This can be confusing for users (and even component developers) so this issue is to file this "inconsistency" and explore possible solutions.

2 first ideas that come to mind:
A) make the `field: attributes.key2.key_in` to produce flat attributes as well
B) in case we want to keep both, or we cannot change the behavior we should document the difference so that users know what to expect specifically.
