### ISSUE TITLE
Filtering expression involving comparison with unknown symbol generates "This is a bug in the OpenTelemetry Transformation Language"

### ISSUE THREAD

**Issue by tilowiklundSensmetry** [open-telemetry/opentelemetry-collector-contrib#33048]
### Component(s)

processor/filter

## Description

Using the `filter` processor with an expression involving a comparison against an undefined symbol starting with an upper-case letter generates an error message the wording of which suggests a bug in the collector

```
Error: invalid configuration: processors::filter: unable to parse OTTL condition [...]: no value field set.
This is a bug in the OpenTelemetry Transformation Language
```

## Steps to Reproduce

Run the collector with a filter comparing against an undefined symbol, such as `value_double != NaN` (`NaN` is undefined at the time of writing), `value_int == IAmUndefined`, or `IAmUndefined == IAmUndefined`.

Note that the behaviour is different for symbols not starting with upper-case letters (which generate either parsing errors or `is not a valid path` errors).

See attached config for full example.

## Expected Result

Error message not indicating the error is a bug in the collector, such the one generated for lower-case symbols
```
[...] is not a valid path nor a valid OTTL keyword [...]
```
or mixed case symbols
```
[...] invalid syntax: 1:29: unexpected token [...]
```

## Actual Result

An error message indicating the issue is due to a bug in the collector
```
This is a bug in the OpenTelemetry Transformation Language
```

### Collector version

v0.100.0

## Environment

Precompiled binary with md5sum
```
41a4690a6ec5834a05a6615a8fdf1494  otelcol-contrib_0.100.0_linux_amd64.tar.gz
```

OS: Gentoo Linux

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

processors:
  filter:
    metrics:
      datapoint:
          - 'value_double != NaN'

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [filter]
      exporters: [debug]
```

### Log output

```shell
Error: invalid configuration: processors::filter: unable to parse OTTL condition "value_double != NaN": no value field set. This is a bug in the OpenTelemetry Transformation Language
2024/05/14 16:38:05 collector server run finished with error: invalid configuration: processors::filter: unable to parse OTTL condition "value_double != NaN": no value field set. This is a bug in the OpenTelemetry Transformation Language
```
