### ISSUE TITLE
[receiver/nginxreceiver] Add additional labels for nginxreceiver

### ISSUE THREAD

**Issue by aofodo** [open-telemetry/opentelemetry-collector-contrib#33069]
### Component(s)

receiver/nginx

### Is your feature request related to a problem? Please describe.

Metrics look like this
```
nginx_connections_current{__tenant_id__="default", state="active", tenant="default"} 255
nginx_connections_current{__tenant_id__="default", state="reading", tenant="default"} 0
nginx_connections_current{__tenant_id__="default", state="waiting", tenant="default"} 222
nginx_connections_current{__tenant_id__="default", state="writing", tenant="default"} 3
```

But in this example I am using 2 nginx. The metrics are summarized for both nginx. As a result, it looks like this on the graph
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/165767272/0c795a3d-a16c-4b27-9cb8-a0435ab67416)
On the first nginx I have ~200, and on the second ~3 active connections.

### Describe the solution you'd like

I suggest add additional labels in metrics with information about nginx endpoint. For example `http_scheme`, `instance`, `net_host_name` and `net_host_port`

### Additional context

Example of my collector configuration for 2 nginx:
```
receivers:
  nginx/first:
    endpoint: "http://first.nginx:9080"
    collection_interval: 60s
  nginx/second:
    endpoint: "http://second.nginx:9080"
    collection_interval: 60s
```

**Comment by aofodo** [comment]
> I'm not sure endpoint related information should be used as identifying attributes because they may be volatile. Are there any other identifiers available via the API? Perhaps a UUID of some sort?

There is no additional information from the API for identification. Maybe add an optional “job_name: <string>” to the nginxreceiver configuration for identification?

**Comment by djaglowski** [comment]
That's an interesting idea. If we want to do something along those lines I'd suggest we use the [semantic conventions for `service.*`](https://github.com/open-telemetry/semantic-conventions/blob/04bdbba20fa3d4d33f9175e01be8ada6fe714542/docs/resource/README.md#service). 

Config could look like:
```yaml
receivers:
  nginx:
    ...
    service:
      name: foo
      instance.id: 627cc493-f310-47de-96bd-71410b7dec09
```

or maybe more generic:
```yaml
receivers:
  nginx:
    ...
    additional_resource_attributes: # (probably a better name)
      service.name: foo
      service.instance.id: 627cc493-f310-47de-96bd-71410b7dec09
      custom.attribute: bar
```

@dmitryax, I think this issue could be relevant to many different metric scrapers. Do you think this is a reasonable solution we might want to use more broadly?
