### ISSUE TITLE
UP is low and data points don't always come through

### ISSUE THREAD

**Issue by zekai-rai** [open-telemetry/opentelemetry-collector-contrib#33067]
### Component(s)

receiver/prometheus

## Description

We set Prometheus receiver to scrape every 10s. Thus, we expect 6 data points every full minute our service runs. However,  we see a lower number sometimes, especially during high resource usage. We also observe that the UP metric drops below 100% when it happens. 

We enabled logging for otel collector, but haven't noticed any useful information. Any suggestion how to debug this?

## Steps to Reproduce

Configuration.

```
  prometheus:
    config:
      scrape_configs:
      - job_name: 'engine'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8010']
```

## Expected Result
The UP metric is 100% and 6 data points come in every full minute it runs. 

## Actual Result
We sometimes see 4 or even only 3 data points

### Collector version

v0.98.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
