### ISSUE TITLE
Keep aws cloudwatch metadata

### ISSUE THREAD

**Issue by abalamilla** [open-telemetry/opentelemetry-collector-contrib#33080]
### Component(s)

receiver/awscloudwatch

## Description
The aws cloudwatch receiver is showing the attributes: cloudwatch.log.group.name and cloudwatch.log.stream when the debug exporter is enabled, but those values are not sending into other exporters like otlphttp

## Steps to Reproduce
With the following configuration the mentioned attributes are not being consider
`config:
    receivers:
      awscloudwatch:
        region: the-region
        logs:
          poll_interval: 1m
          groups:
            autodiscover:
              limit: 100
              prefix: /the/log/group/name
    service:
      pipelines:
        logs:
          receivers:
            - awscloudwatch
          processors:
            - batch
          exporters:
            - debug
            - otlphttp
`

## Expected Result
Logs sending into otlphttp endpoint having the aws cloudwatch log group name and stream names

## Actual Result
Logs doesn't have aws cloudwatch log group and stream names

### Collector version

0.90.1

## Environment
OS: AWS EKS

### OpenTelemetry Collector configuration

```yaml
config:
    receivers:
      awscloudwatch:
        region: the-region
        logs:
          poll_interval: 1m
          groups:
            autodiscover:
              limit: 100
              prefix: /the/log/group/name
    service:
      pipelines:
        logs:
          receivers:
            - awscloudwatch
          processors:
            - batch
          exporters:
            - debug
            - otlphttp
```

### Log output

```shell
Trace ID:                                                                                 │
│ Span ID:                                                                                  │
│ Flags: 0                                                                                  │
│ ResourceLog #2                                                                            │
│ Resource SchemaURL:                                                                       │
│ Resource attributes:                                                                      │
│      -> aws.region: Str(the-region)                                                        │
│      -> cloudwatch.log.group.name: Str(/the/log/group/name)                  │
│      -> cloudwatch.log.stream: Str(the-stream-name) │
│ ScopeLogs #0
```
