### ISSUE TITLE
New component: Coralogix Processor

### ISSUE THREAD

**Issue by galrose** [open-telemetry/opentelemetry-collector-contrib#33090]
### The purpose and use-cases of the new component

Coralogix processor is for clients using Coralogix.
The processor will have multiple features but the first one is, to template db.statements by removing the variables and replacing them with `?`. Which will add a new tag to the span called db.statement.blueprint.id and db.statement.blueprint. These will be used internally in Coralogix to be able to recognize which queries are of the same template.

At the start we expect it to work only for postgresql, mysql, and sqlserver.
The processor will check the db.system and only if its in the recognized systems it will try to parse the query.

There is an option to work with sampling, and if so it will only add the sampling.priority key to db.statement.blueprints it has not seen before (using an internal cache), then it is possible to use the probabilistic sampler to only send new spans

## basic setup
```yaml
processors:
  coralogix:
    db_statement_blueprints:
      with_sampling: true
```
## with cache
```yaml
processors:
  coralogix:
    db_statement_blueprints:
      with_sampling: true
      cache_config:
        max_cache_size_bytes: 1073741824 #1GB
        max_cached_entries: 10000000
  ```

### Telemetry data types supported

traces

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.
