### ISSUE TITLE
[exporter/prometheus] Allow setting custom "job" and "instance" attributes

### ISSUE THREAD

**Issue by swar8080** [open-telemetry/opentelemetry-collector-contrib#33118]
### Component(s)

exporter/prometheus

## Description
`prometheusexporter` automatically sets the `job` and `instance` attributes on metrics exposed for scraping, which are derived from the metric's resource attributes. 

If you try setting custom `job`/`instance` values then the conversion to prometheus metric data model fails because of duplicate labels:

## Steps to Reproduce
Submit a metric to this component with either of these attributes set. Then call its `/metrics` endpoint

## Expected Result
Custom label values take priority over the default values

## Actual Result
Setting custom label values breaks scraping for these metrics

### Collector version

v0.100.0

### Environment information

Reproduced locally but this should be reproducible on all environments

### OpenTelemetry Collector configuration

```yaml
exporters:
  prometheus:
    endpoint: "0.0.0.0:9465"
    enable_open_metrics: true
    metric_expiration: 99m
    send_timestamps: false

  transform:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["job"], "custom")

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [transform]
      exporters: [prometheus]
```

### Log output

```shell
2024-05-17T18:45:38.607-0400    error   prometheusexporter@v0.100.0/collector.go:386    failed to convert metric calls: duplicate label names in constant and variable labels for metric "calls_total"        {"service": "my-instance", "kind": "exporter", "data_type": "metrics", "name": "prometheus/exporter"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*collector).Collect
        /Users/sswartz/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.100.0/collector.go:386
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1
        /Users/sswartz/go/pkg/mod/github.com/prometheus/client_golang@v1.19.1/prometheus/registry.go:457
```

### Additional context

Our use case is migrating some metrics to OpenTelemetry collector, so we want to preserve the existing `job` values to avoid breaking existing dashboards/alerts

I've patched this in our custom fork by checking if job/instance are already set before setting the default
