### ISSUE TITLE
Getting ERROR Could not get bootstrap info from the Collector: collector's OpAMP client never connected to the Supervisor

### ISSUE THREAD

**Issue by Thejas-I** [open-telemetry/opentelemetry-collector-contrib#33129]
### Component(s)

cmd/opampsupervisor

### Describe the issue you're reporting

I have followed the steps as mentioned at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/16f401b82d3f3d54a5bc3eda17610a3a98cb11ba/cmd/opampsupervisor/README.md
But I am getting the error as "**ERROR opampsupervisor/main.go:24 could not get bootstrap info from the Collector: collector's OpAMP client never connected to the Supervisor**"

Below is my supervisor_linux.yaml
```
server:
  endpoint: wss://127.0.0.1:4320/v1/opamp
  tls:
    # Disable verification to test locally.
    # Don't do this in production.
    insecure_skip_verify: true
    # For more TLS settings see config/configtls.ClientConfig

capabilities:
  reports_effective_config: true
  reports_own_metrics: true
  reports_health: true
  accepts_remote_config: true
  reports_remote_config: true

agent:
  executable: /root/Test/test-master/cmd/otelcol/test-collector
```

Below is my test-collector's config.yml

```
extensions:
  opamp:
    server:
      ws:
        endpoint: ws://127.0.0.1:4320/v1/opamp
        tls:
          insecure_skip_verify: true # Set to true if you're using self-signed certificates

service:
  extensions: [opamp]
```
