### ISSUE TITLE
[Spanmetrics Connector] sometimes counter-type metrics grow exponentially.

### ISSUE THREAD

**Issue by pingping95** [open-telemetry/opentelemetry-collector-contrib#33136]
### Component(s)

connector/spanmetrics

## Description
**Sometimes counter-type metrics grow exponentially.**

This has been happening for about 2 months now.

I would run a heapdump if it was a memory leak,
but the metric values are growing exponentially, so I don't know how to debug it.

This didn't happen when I was using Tempo's Metrics Generator.

However, in order to create RED metrics with Tempo's Metrics Generator, I couldn't sample from the Collector, so I moved to the Opentelemetry Collector.

<br>
<br>
<br>

## Steps to Reproduce
It doesn't happen in the development environment.

The issue occurs on collectors with some traffic, like production environment.

Because of the `metric_expiration` config, it returns back to normal **after 5 minutes.**

**but this is only a temporary measure** and doesn’t help much.

<br>
<br>

## Expected Result
The counter type metric should not be spiking.

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/67780144/08b5e651-968c-4537-ae60-212d271673bb)

<br>
<br>

## Actual Result

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/67780144/1bd538ba-f1a1-4c44-8776-dea986d37683)

### Collector version

v0.99

## Environment
OS: Amazon Linux 2 (AWS EKS)

Compiler(if manually compiled): I don`t know

## Architecture

2 Layer Collectors

```
LoadBalancing Collector -> Spanmetrics Collector
                        -> Tailsampling Collector
```

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/67780144/c289eafa-ca74-461d-9a2d-a6b96b2cac56)

### OpenTelemetry Collector configuration

```yaml
#########################
  ### RECEIVER
  #########################
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318

    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${env:MY_POD_IP}:8888

  #########################
  ### PROCESSORS
  #########################
  processors:
    batch: {}
    memory_limiter:
      check_interval: 2s
      limit_percentage: 70
      spike_limit_percentage: 25

    filter:
      metrics:
        datapoint:
          - 'attributes["span.kind"] == "SPAN_KIND_CLIENT"'
          - 'attributes["span.kind"] == "SPAN_KIND_INTERNAL"'

  #########################
  ### EXPORTERS
  #########################
  exporters:

    prometheusremotewrite/spanmetrics:
      endpoint: https://mimir.xxxxx.xxx/api/v1/push

      target_info:
        enabled: true
      external_labels:
        cluster: xxxxxxxx

    prometheusremotewrite/monitormetrics:
      endpoint: https://mimir.xxxxx.xxx/api/v1/push

      external_labels:
        cluster: xxxxxxxx
        collector-type: spanmetrics

  # SPAN_KIND   : CLIENT, SERVER, INTERNAL, PRODUCER, CONSUMER
  # STATUS_CODE : UNSET, OK, ERROR

  #########################
  ### CONNECTORS
  #########################
  connectors:
    # 1. SERVER Metrics
    spanmetrics:
      histogram:
        explicit:
          buckets: [100ms, 500ms, 2s, 5s, 10s, 20s, 30s]
      aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
      metrics_flush_interval: 15s
      metrics_expiration: 5m

      dimensions_cache_size: 4000
      resource_metrics_cache_size: 4000

      exemplars:
        enabled: false
#        max_per_data_point: 5
      dimensions:
        - name: http.method
        - name: http.status_code
        - name: cluster

#        - name: messaging.kafka.client_id
        # PRODUCER
#        - name: messaging.destination.name
#        - name: messaging.kafka.destination.partition
        # CONSUMER
#        - name: messaging.kafka.consumer.group
#        - name: messaging.kafka.source.partition
#        - name: messaging.operation

      events:
        enabled: false
        dimensions:
          - name: exception.type

      resource_metrics_key_attributes:
        - service.name

  #########################
  ### EXTENSIONS
  #########################
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
    memory_ballast:
      size_in_percentage: 40

  #########################
  ### SERVICES
  #########################
  service:
    extensions:
      - health_check
      - memory_ballast

    pipelines:
      ############################
      #### OTLP -> SPANMETRICS ###
      ############################
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - spanmetrics

      #############################################
      #### KIND: SERVER, CONSUMER, PRODUCER
      #############################################
      metrics/spanmetrics:
        receivers:
          - spanmetrics
        processors:
          - memory_limiter
          - batch
          - filter
        exporters:
          - prometheusremotewrite/spanmetrics

      #############################################
      #### OTEL Monitoring
      #############################################
      metrics/monitormetrics:
        receivers:
          - prometheus
        processors:
          - memory_limiter
          - batch
        exporters:
          - prometheusremotewrite/monitormetrics
```

### Log output

```shell
No special logs.
```

### Additional context

I'm constantly trying to disable spanmetrics settings one by one to figure out what's causing the problem.

1. disable events
2. disable exemplars
3. disable some dimensions

So far, nothing has worked.

**Comment by pingping95** [comment]
I resolved this issue by removing consumer and producer related dimensions.

so i decided to change like this.

SERVER span metrics -> server related dimensions only

CONSUMER span metrics -> consumer related dimensions only

PRODUCER span metrics -> producer related dimensions only

**Comment by pingping95** [comment]
I tried this but still occurs.

1. Apply a filter (SPAN-KIND: Server only) before the SpanMetrics connector.
-> Only server spans pass through the spanmetrics connector

2. add telemetry.sdk.language, telemetry.sdk.name to resource_metrics_key_attribute

```
config:

  #########################
  ### RECEIVER
  #########################
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318

    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${env:MY_POD_IP}:8888

  #########################
  ### PROCESSORS
  #########################
  processors:
    batch: {}
    memory_limiter:
      check_interval: 2s
      limit_percentage: 70
      spike_limit_percentage: 25

    filter/server-span-only:
      error_mode: ignore
      traces:
        span:
          - 'kind.string == "Unspecified"'
          - 'kind.string == "Internal"'
          - 'kind.string == "Client"'
          - 'kind.string == "Producer"'
          - 'kind.string == "Consumer"'

#    filter/server:
#      metrics:
#        datapoint:
#          - 'attributes["span.kind"] == "SPAN_KIND_CLIENT"'
#          - 'attributes["span.kind"] == "SPAN_KIND_UNSPECIFIED"'
#          - 'attributes["span.kind"] == "SPAN_KIND_INTERNAL"'
#          - 'attributes["span.kind"] == "SPAN_KIND_CONSUMER"'
#          - 'attributes["span.kind"] == "SPAN_KIND_PRODUCER"'


  #########################
  ### EXPORTERS
  #########################
  exporters:

    prometheusremotewrite/spanmetrics-server:
      endpoint: https://xxxx.xxxxx.xxxxx/api/v1/push
      target_info:
        enabled: true
      external_labels:
        cluster: xx-xxxx-xxxx

    prometheusremotewrite/monitormetrics:
      endpoint: https://xxxxx.xxxxx.xxxxx/api/v1/push
      external_labels:
        cluster: xx-xxxx-xxxx
        collector-type: spanmetrics

  # SPAN_KIND   : CLIENT, SERVER, INTERNAL, PRODUCER, CONSUMER
  # STATUS_CODE : UNSET, OK, ERROR

  #########################
  ### CONNECTORS
  #########################
  connectors:
    # 1. SERVER Metrics
    spanmetrics/server:
      histogram:
        explicit:
          buckets: [100ms, 500ms, 2s, 5s, 10s, 20s, 30s]
      aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
      metrics_flush_interval: 15s
      metrics_expiration: 5m
      exemplars:
        enabled: false
      dimensions:
        - name: http.method
        - name: http.status_code
        - name: cluster

      events:
        enabled: true
        dimensions:
          - name: exception.type

      resource_metrics_key_attributes:
        - service.name
        - telemetry.sdk.language
        - telemetry.sdk.name

  #########################
  ### EXTENSIONS
  #########################
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
    memory_ballast:
      size_in_percentage: 40

  #########################
  ### SERVICES
  #########################
  service:
    extensions:
      - health_check
      - memory_ballast

    pipelines:
      ############################
      #### OTLP -> SPANMETRICS ###
      ############################
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
          - filter/server-span-only
        exporters:
          - spanmetrics/server
#          - spanmetrics/messaging

      #############################################
      #### KIND: SERVER
      #############################################
      metrics/spanmetrics-server:
        receivers:
          - spanmetrics/server
        processors:
          - memory_limiter
          - batch
#          - filter/server
        exporters:
          - prometheusremotewrite/spanmetrics-server

      #############################################
      #### OTEL Monitoring
      #############################################
      metrics/monitormetrics:
        receivers:
          - prometheus
        processors:
          - memory_limiter
          - batch
        exporters:
          - prometheusremotewrite/monitormetrics

```


![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/67780144/9f2b7ff9-17fc-4614-9fc7-12f2ab6faff7)
