### ISSUE TITLE
azureblobreceiver not reading the logs & traces

### ISSUE THREAD

**Issue by deepan10** [open-telemetry/opentelemetry-collector-contrib#33132]
### Component(s)

receiver/azureblob

## Description

`azureblobreceiver` detecting the `BlobCreate` event and no logs & traces is read

## Steps to Reproduce
1. configure azureblobreceiver
2. Add the below pipeline
```yaml
pipelines:
        traces:
          receivers: [azureblob]
          processors: []
          exporters: [debug]
        logs:
          receivers: [azureblob]          
          processors: []
          exporters: [debug]
```

## Expected Result
It should print the received logs & traces

## Actual Result
TracesExporter {"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 0, "spans": 0}
LogsExporter {"kind": "exporter", "data_type": "logs", "name": "debug", "resource logs": 0, "log records": 0}

### Collector version

Starting otelcol-contrib... {"Version": "0.100.0", "NumCPU": 16}

## Environment
Docker Image `otel/opentelemetry-collector-contrib:latest`

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:          
      http:
  azureblob:
    connection_string: <REDACATED>
    event_hub:
      endpoint: <REDACATED>
    traces: 
      container_name: insights-logs-apptraces

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:   
  pipelines:
    traces:
      receivers: [otlp,azureblob]
      processors: []
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp,azureblob]          
      processors: []
      exporters: [debug]
```

### Log output

```shell
TracesExporter {"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 0, "spans": 0}
LogsExporter {"kind": "exporter", "data_type": "logs", "name": "debug", "resource logs": 0, "log records": 0}
```
