### ISSUE TITLE
Supported json encoded messages in googlecloudpubsub exporter 

### ISSUE THREAD

**Issue by brandonbirdj** [open-telemetry/opentelemetry-collector-contrib#33156]
### Component(s)

exporter/googlecloudpubsub

### Is your feature request related to a problem? Please describe.

Many of the out of the box ways to get logs into pubsub from google cloud utilize jsonPayload, and json encoding. One example is when configuring a log sink from Google Cloud Logging.

In order to make it easier to have a drop in replacement it would be very useful to also support json encoded messages. Putting the message body inside a field called `jsonPayload` could simple be done in the log pipeline of the collector, no exporter changes needed.

Additionally I think  there is perhaps an opportunity to make the attributes set a little more dynamic as opposed to the current cloud events ones.

### Describe the solution you'd like

It would be useful to perhaps allow a user to supply additonal attributes. I do not presently have a usecase for this, and would also be happy to just not use the cloud events ones if json encoding is provided.
```yaml
exporters:
  googlecloudpubsub:
    project: abc
    endpoint: mytestendpoint
    user_agent: projects/abc/topics/requests
    additional_attributes:
    - version
    encoding: json
```

### Describe alternatives you've considered

Forking this provider, or converting all other dependent logic presently relying on json encoding are the only alternatives I have considered.

### Additional context

I would be happy to help write this, but would like direction on how to handle the additional attributes and what to do with the current `ce` ones.
