### ISSUE TITLE
Metrics Transform Processor Proposal

### ISSUE THREAD

**Issue by JingboWangGoogle** [open-telemetry/opentelemetry-collector-contrib#332]
## Metrics Transform Processor
  - The first version of aggregation would only support single-batch processing on metrics to avoid conflicts of different batches with the same time-series ([more description of this corner case](https://github.com/open-telemetry/opentelemetry-collector/issues/1118#issuecomment-643780972)).

### Objectives
The objective of this metrics transform processor is to give OpenTelemetry Collector users the flexibility to rename and aggregate metrics in desired ways so that the metrics are more relevant and cheaper to the users.

### Background
There are cases where metrics are overly detailed for a user’s needs, which also impose unnecessary costs. In these cases, the user wants to compress the metrics written into the collector in some meaningful way before writing them out to the metrics backend. In addition, users may want to significantly transform the format that metrics appear in. This may even be a requirement due to backends requiring metrics to match specific existing formats and names.
Related Work: Filter Processor ([Issue](https://github.com/open-telemetry/opentelemetry-collector/issues/560), [Pull Request](https://github.com/open-telemetry/opentelemetry-collector/pull/1001/files)).

### Requirements
The specific requirements include:
- rename metrics (e.g. rename `cpu/usage` to `cpu/usage_time`)
- rename labels (e.g. rename `cpu` to `core`)
- rename label values (e.g. rename `done` to `complete`)
- aggregate across label sets (e.g. only want the label `usage`, but don’t care about the labels `core`, and `cpu`)
  - aggregation_type: sum, average, max
- aggregate across label values (e.g. want `memory{slab}`, but don’t care about `memory{slab_reclaimable}` & `memory{slab_unreclaimable}`)
  - aggregation_type: sum, average, max

### Proposed Configuration
```yaml
transforms:
  # name is used to match with the metric to operate on. This implementation doesn’t # utilize the filtermetric’s MatchProperties struct because it doesn’t match well 
  # with what I need at this phase. All is needed for this processor at this stage is # a single name string that can be used to match with selected metrics. The list of # metric names and the match type in the filtermetric’s MatchProperties struct are # unnecessary. Also, based on the issue about improving filtering configuration, it # seems like this struct is subject to be slightly modified.
  - name: <current_metric_name>

  # action specifies if the operations are performed on the current copy of the 
  # metric or on a newly created metric that will be inserted
    action: {update, insert}

  # new_name is used to rename metrics (e.g. rename cpu/usage to cpu/usage_time)
  # if action is insert, new_name is required
    new_name: <new_metric_name_inserted>

  # operations contain a list of operations that will be performed on the selected 
  # metrics. Each operation block is a key-value pair, where the key can be any 
  # arbitrary string set by the users for readability, and the value is a struct with # fields required for operations. The action field is important for the processor 
  # to identify exactly which operation to perform 
    operations:

    # update_label action can be used to update the name of a label or the values           
    # of this label (e.g. rename label `cpu` to `core`)
      - action: update_label
        label: <current_label1>
        new_label: <new_label>
        value_actions:
         - value: <current_label_value>
           new_value: <new_label_value>

    # aggregate_labels action aggregates metrics across labels (e.g. only want  
    # the label `usage`, but don’t care about the labels `core`, and `cpu`)
      - action: aggregate_labels
     # label_set contains a list of labels that will remain after the aggregation.    
     # The excluded labels will be aggregated by the way specified by  
     # aggregation_type.
        label_set: [labels...]
        aggregation_type: {sum, average, max}

    # aggregate_label_values action aggregates labels across label values (e.g. want  
    # memory{slab}, but don’t care about memory{slab_reclaimable} &   
    # memory{slab_unreclaimable})
      - action: aggregate_label_values
        label: <label>
     # aggregated_values contains a list of label values that will be aggregated by  
     # the way specified by aggregation_type into new_value. The excluded label  
     # values will remain.
       aggregated_values: [values...]
       new_value: <new_value> 
       aggregation_type: {sum, average, max}
```

#### Insert New Metric
```yaml
# create host/cpu/usage_time from host/cpu/usage
name: host/cpu/usage
action: insert
new_name: host/cpu/utilization
operations:
  ...
```

#### Rename Labels
```yaml
# rename the label cpu to core
operations:
  - action: update_label
    label: cpu
    new_label: core
```

#### Aggregate Labels
```yaml
# aggregate away everything but `state` using summation
...
operations:
  -action: aggregate_labels
   label_set: [ state ]
   aggregation_type: sum
```

#### Aggregate Label Values
```yaml
# combine slab_reclaimable & slab_unreclaimable by summation
...
operations:
  -action: aggregate_label_values
   label: state
   aggregated_values: [ slab_reclaimable, slab_unreclaimable ]
   new_value: slab 
   aggregation_type: sum
```

## Possible Extensions
- Supporting custom types of aggregation (e.g. defined by a formula)
- Support aggregations of non-simple metric types (distributions, etc)
- Support aggregation over time
- Utilizing regex to select metrics

## Thanks to
@draffensperger @james-bebbington @quentinmit
