### ISSUE TITLE
Cannot put traceid & spanid like loki labes

### ISSUE THREAD

**Issue by RaulGF92** [open-telemetry/opentelemetry-collector-contrib#33202]
### Component(s)

exporter/loki

### Describe the issue you're reporting

Previous PR related:

- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7569
- https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/29079

Really I don't know if is a error or really that is solved and we can put traceid like labels but sure documentation is not well explained and a refactor of this could be beneficial.

Explanation of my stack:

I have a full open-telemetry stack

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/9384625/a8be6e7d-b693-404d-89a8-934ec1da2fac)

When I tried to send my logs that works but I want to put traceid & spanid in my loki.labels for work in a raw format and put the labels I want to search without fight with json format.

That is my configuration otel-configuration (I remove all aditional configuration for free space):

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
    default_labels_enabled:
      exporter: false
      job: true

processors:
  attributes:
    actions:
      - action: insert
        key: loki.format
        value: json
      - action: insert
        key: loki.attribute.labels
        value: traceid
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: record.traceid


service:
  pipelines:
    logs:
      receivers:  [ otlp ]
      processors: [ attributes, resource]
      exporters:  [ loki ]
```

That error happen in all formats (json, raw, logfmt) when you tried to put traceid like a label that don't let you also loki don't see this like a label:

![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/9384625/e923b58d-21b2-405f-a979-b7fa7ffbc46b)
