### ISSUE TITLE
[receiver/kafka]: support receiving from multiple topics

### ISSUE THREAD

**Issue by yilmazo** [open-telemetry/opentelemetry-collector-contrib#33204]
### Component(s)

receiver/kafka

### Is your feature request related to a problem? Please describe.

I want to collect logs from multiple Kubernetes clusters using opentelemetry collector, and send them to elasticsearch.  
My setup briefly looks like this:  
`collectors (in k8s clusters)  -->  kafka --> collector (centralized) --> elasticsearch`

I want to use multiple topics on kafka in order to mitigate noisy neighbor situations.  
`topic_from_attribute` configuration on kafka exporter helps me to send logs to separate topics easily, but there is no way to provide a topic pattern or regex for consuming from multiple topics. As a result, I need to automate the process of adding/removing kafka receivers on my centralized collector's config and I'm not sure that it will be a problem to add ~500 kafka receivers on collector config.

### Describe the solution you'd like

Instead of this:
```yaml
receivers:
  kafka/1:
    topic: logs_1
  kafka/2:
    topic: logs_2
  kafka/3:
    topic: logs_3
```

I want to be able to provide a pattern or regexp.
```yaml
receivers:
  kafka:
    topicPattern: logs_*
```

Note: Collector should also periodically check all topics and update the listened topic list based on the `topicPattern`.

### Describe alternatives you've considered

I'm open to any other solutions or recommendations.
