### ISSUE TITLE
New component: eG Innovations Telemetry Exporter

### ISSUE THREAD

**Issue by gsreg** [open-telemetry/opentelemetry-collector-contrib#33219]
### The purpose and use-cases of the new component

eginnovations exporter enables the ability to export telemetry data from an OpenTelemetry collector to the eG Innovations environment for further analysis, alerting and retention.

### Example configuration for the component

WIP

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s

exporters:
    eginnovations:
        endpoint: https://www.eginnovations.com
        userId: "account_specific_generated_id"
        token: "0000000000000000"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [eginnovations]
```

### Telemetry data types supported

- trace
- metrics [WIP]
- logs [WIP]

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [X] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Sponsor (optional)

This component is being developed and contributed by eG Innovations and is looking for a volunteer sponsor.

### Additional context

A version of the OpenTelemetry contrib collector containing the code for this exporter is available here: [eginnovations-exporter](https://github.com/gsreg/opentelemetry-collector-contrib/tree/eginnovations-exporter).
