### ISSUE TITLE
`kafkaexporter` - support injecting headers

### ISSUE THREAD

**Issue by d-mankowski-synerise** [open-telemetry/opentelemetry-collector-contrib#33260]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

[kafkareceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kafkareceiver) does support header extraction, e.g.

```yaml
receivers:
  kafka:
    topic: test
    header_extraction: 
      extract_headers: true
      headers: ["header1", "header2"]
```

However, [kafkaexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter) does not support injecting such headers, that could then be read by kafkareceiver.

Use case: we want to have a following setup: applications (send traces to) -> OT Collector -> Kafka -> Grafana Tempo. Grafana Tempo has [multi-tenancy](https://grafana.com/docs/tempo/latest/operations/multitenancy/) enabled, which means, that in order to identify which tenant sends the telemetry, an `X-Scope-OrgID` header is required.

Note: Tempo is using kafkareceiver internally

### Describe the solution you'd like

kafkaexporter should be able to inject custom headers that are in compatible format with what kafkareceiver expects. Config could look like this:

```yaml
exporters:
  kafka:
    topic: test
    header_injection: 
      inject_headers: true
      headers:
        header1: value1
        header2: value2
```
