### ISSUE TITLE
MySQL Receiver expects non-existent column in information_schema

### ISSUE THREAD

**Issue by heaje** [open-telemetry/opentelemetry-collector-contrib#33271]
### Component(s)

receiver/mysql

## Description
When running [the MySQL receiver changes introduced in 0.101.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32693), the OTel collector produces errors like these:

```
May 28 19:55:31 ue1010217215146 otelcol-contrib[92515]: 2024-05-28T19:55:31.661Z        error        mysqlreceiver@v0.101.0/scraper.go:421        Failed to fetch table size stats        {"kind": "receiver", "name": "mysql/a.b.c:3306", "data_type": "metrics", "error": "Error 1054 (42S22): Unknown column 'TABLE_LENGTH' in 'order clause'"}
```

This error occurs when the collector is used to extract metrics from MySQL 8.0.35.  I do not know about other MySQL versions.  These errors do not occur after downgrading to OTel collector 0.100.0.

## Steps to Reproduce
1. Set up a MySQL 8.0.35 instance to monitor.
2. Enable the MySQL receiver in OTel Collector 0.101.0 with a basic configuration like this:
```yaml
mysql/a.b.c:3306:
    endpoint: a.b.c:3306
    collection_interval: 60s
    username: yyyyyyyyyy
    password: xxxxxxxxx
```

3. Start the Collector and observe the mentioned error in the log output from OTel collector.
4. Downgrade to OTel Collector 0.100.0 and use the exact same configuration.
5. Restart the Collector and observe that no error occurs.

## Expected Result
1. No error should occur

## Actual Result
1. The error indicated in the description happens.

### Collector version

0.101.0

## Environment
OS: Rocky 8.7
Collector installed using an RPM from https://github.com/open-telemetry/opentelemetry-collector-releases/releases (specific RPM is [otelcol-contrib_0.101.0_linux_amd64.rpm](https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.101.0/otelcol-contrib_0.101.0_linux_amd64.rpm))

### OpenTelemetry Collector configuration

```yaml
receivers:
  mysql/a.b.c:3306:
    endpoint: a.b.c:3306
    collection_interval: 60s
    username: yyyyyyyyyy
    password: xxxxxxxxx
```

### Log output

```shell
May 28 19:55:31 ue1010217215146 otelcol-contrib[92515]: 2024-05-28T19:55:31.661Z        error        mysqlreceiver@v0.101.0/scraper.go:421        Failed to fetch table size stats        {"kind": "receiver", "name": "mysql/a.b.c:3306", "data_type": "metrics", "error": "Error 1054 (42S22): Unknown column 'TABLE_LENGTH' in 'order clause'"}
```
