### ISSUE TITLE
[processor/resource] k8s pod metadata not insert when using loki

### ISSUE THREAD

**Issue by g3david405** [open-telemetry/opentelemetry-collector-contrib#33307]
## Description
I want to add pod metadata throught processor called resource
(I used helm chart opentelemetry-collector 0.92.0)
config:
    resource:
      attributes:
        - action: insert
          key: loki.resource.labels
          value: service.name, k8s.pod.name, k8s.pod.uid, k8s.deployment.name, k8s.namespace.name, k8s.node.name, k8s.pod.start_time
  service:
    pipelines:
      logs:
        receivers:
          - otlp
        processors:
          - k8sattributes
          - resource
        exporters:
          - loki

## Expected Result
Loki log should show k8s pod metadata in label

## Actual Result
Only service_name was added to label
![image](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/75260884/fd1bfa33-a60c-4a31-b8be-328e1ab025d6)

### Collector version

helm chart 0.92.0

## Environment
OS: Rocky 9
k8s 1.26.3

### OpenTelemetry Collector configuration

```yaml
exporters:
      debug: {}
      loki:
        default_labels_enabled:
          exporter: true
          job: true
        endpoint: http://loki-distributed-gateway.david-opentelemetry.svc.cluster.local/loki/api/v1/push
        tls:
          insecure: true
      otlp:
        endpoint: tempo-distributed-distributor.david-tempo.svc.cluster.local:4317
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch:
        send_batch_size: 90
        timeout: 30s
      k8sattributes:
        auth_type: serviceAccount
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      resource:
        attributes:
        - action: insert
          key: loki.resource.labels
          value: service.name, k8s.pod.name, k8s.pod.uid, k8s.deployment.name, k8s.namespace.name,
            k8s.node.name, k8s.pod.start_time
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411
    service:
      extensions:
      - health_check
      pipelines:
        logs:
          exporters:
          - loki
          processors:
          - k8sattributes
          - resource
          receivers:
          - otlp
        metrics:
          exporters:
          - prometheus
          processors:
          - batch
          receivers:
          - otlp
        traces:
          exporters:
          - otlp
          processors:
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
```
