### ISSUE TITLE
Not able to filter by nil timestamp

### ISSUE THREAD

**Issue by zekai-rai** [open-telemetry/opentelemetry-collector-contrib#33327]
### Component(s)

processor/filter

## Description

Not able to filter out data point without startTimeUnixNano.

## Steps to Reproduce

Use this filter setting. 

```
filter/engine_initial:
    error_mode: ignore
    metrics:
      datapoint:
          - start_time_unix_nano == nil
```

Submit a metric with data points without startTimeUnixNano. Expecting the data point to be filter out.

### Collector version

v.0.98.00

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
filter/engine_initial:
    error_mode: ignore
    metrics:
      datapoint:
          - start_time_unix_nano == nil
```
