### ISSUE TITLE
[receiver/hostmetricsreceiver] Gopsutil error on windows with multiple processor groups.

### ISSUE THREAD

**Issue by alvarocabanas** [open-telemetry/opentelemetry-collector-contrib#33340]
### Component(s)

receiver/hostmetricsreceiver

## Description
On a windows instance having 48 * 2 logical cpus, windows groups CPUs into batches of 64 logical cpus in a processor group, but Gopsutil's Cpu.TimesWitContext [defined on the cpuscraper in here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/22c3296f0ae71aa043ddaa2f4442bf0a19efc94e/receiver/hostmetricsreceiver/internal/scraper/cpuscraper/cpu_scraper.go#L46) and used to by the resource detector to calculate the cpu times and utilization, indistinctly gets this data from one of the two processor groups and not all of them.

This is generating variable cpu Utilization, sometimes negative and sometimes full usage even if only half the cores are running.

This bug is reported on the [gopsutil library](https://github.com/shirou/gopsutil/issues/887).

## Steps to Reproduce
In our case we reproduced it on a 'm5n.metal' machine in AWS with windows-server-22 but we know reports of it happening in other windows with more than one processor groups.

## Expected Result
Correct Cpu Usage and times.

## Actual Result
Cpu data points from one of the 2 processor groups randomly.

### Collector version

v0.101.0

## Environment
OS: Windows-server 22

### OpenTelemetry Collector configuration

```yaml
receivers:
    hostmetrics:
      collection_interval: 20s
      scrapers:
        cpu:
          metrics:
            system.cpu.time:
              enabled: true
            system.cpu.utilization:
              enabled: true
  processors:
    # group system.cpu metrics by cpu
    metricstransform:
      transforms:
        - include: system.cpu.utilization
          action: update
          operations:
            - action: aggregate_labels
              label_set: [ state ]
              aggregation_type: mean
[ ... ]
```
