### ISSUE TITLE
Invalid warning `Variable substitution using $VAR will be deprecated in favor of ${VAR} and ${env:VAR}, please update $$`

### ISSUE THREAD

**Issue by arielvalentin** [open-telemetry/opentelemetry-collector-contrib#33387]
## Description

When using ottl transform processor with a capture group, the following warning is emitted in the logs: 

> {"level":"warn","ts":1717553616.784837,"caller":"expandconverter@v0.101.0/expand.go:73","msg":"Variable substitution using $VAR will be deprecated in favor of ${VAR} and ${env:VAR}, please update $$","variable":"$"}

## Steps to Reproduce

Create a transform processor that uses replace pattern with a capture group substitution like this:

```yaml
error_mode: ignore
trace_statements:
  - context: span
    statements:
      - |-
        replace_pattern(attributes["baz"], "^(foo|bar)-.*", "$$1")
```

## Expected Result

No warnings are printed

## Actual Result

> {"level":"warn","ts":1717553616.784837,"caller":"expandconverter@v0.101.0/expand.go:73","msg":"Variable substitution using $VAR will be deprecated in favor of ${VAR} and ${env:VAR}, please update $$","variable":"$"}

### Collector version

v0.101.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
