### ISSUE TITLE
googlecloudpubsubreceiver: google.cloud.audit.Auth orizationInfo has no known field with JSON name permissionType

### ISSUE THREAD

**Issue by rafaeljesus** [open-telemetry/opentelemetry-collector-contrib#33400]
### Component(s)

receiver/googlecloudpubsub

## Description

I have a logging sink exporting writing logs to a pubsub topic that the pubsub receiver is consuming from,

the logging sink inclusion filter is as follows:
```yaml
NOT (
  (resource.type="k8s_container" OR resource.type="k8s_pod") AND
  NOT resource.labels.namespace_name=~"kube-*"
) AND
NOT resource.type="cloud_run_revision"
```

below is the screenshot of the data in Cloud Logging, as you can see there is a `permissionType: "ADMIN_READ"`

<img width="648" alt="Screenshot 2024-06-05 at 17 13 25" src="https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/1216425/f59915a8-36fd-48de-a845-fa24af483407">

## Expected Result

data to be exported to the internal logging system

## Actual Result
data is not being exported to the internal logging system, and instead, I am having the following error in logs `"google.cloud.audit.AuthorizationInfo has no known field with JSON name permissionType"`

### Collector version

0.95.0

## Environment
GKE

### OpenTelemetry Collector configuration

```yaml
config:
  exporters:
    otelarrow/logs:
      endpoint: 'ingest.lightstep.com:443'
      headers:
        lightstep-access-token: '${LS_TOKEN}'
  receivers:
    googlecloudpubsub:
      encoding: cloud_logging
      project: org-eu1-staging
      subscription: projects/org-eu1-staging/subscriptions/org-logs-forwarder
  service:
    pipelines:
      logs:
        receivers:
          - googlecloudpubsub
        exporters:
          - otelarrow/logs
```

### Log output

```shell
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver.(*pubsubReceiver).handleCloudLoggingLogEntry
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver@v0.99.0/receiver.go:150
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver.(*pubsubReceiver).createReceiverHandler.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver@v0.99.0/receiver.go:299
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver/internal.(*StreamHandler).responseStream
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/googlecloudpubsubreceiver@v0.99.0/internal/handler.go:193
2024-06-05T17:05:08.890Z        error   googlecloudpubsubreceiver@v0.99.0/receiver.go:150       got an error    {"kind": "receiver", "name": "googlecloudpubsub", "data_type": "logs", "error": "google.cloud.audit.AuthorizationInfo has no known field with JSON name permissionType"}
```
