### ISSUE TITLE
no timestamp value

### ISSUE THREAD

**Issue by yoyoraso** [open-telemetry/opentelemetry-collector-contrib#33412]
### Component(s)

exporter/kafka

## Description
Hi I send data to reciever otlp and export by two ways (file and kafka) I can see in the file a Timestamp value and ObservedTimestamp but for the kafka I don't see any in the message only Trace ID and Span ID 
### Collector version

latest otel/opentelemetry-collector-contrib image

## Environment
kubernetes cluster on ubuntu linux 

### OpenTelemetry Collector configuration

```yaml
receivers: 
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:

    exporters:
      file:
        path: /tmp/otel-logfile.log      
      debug:
        verbosity: detailed      
      kafka:
        brokers:
          - ******
        topic: otel-kafka
        encoding: otlp_json
        producer:
          compression: gzip
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug,kafka]          
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [kafka]          
      telemetry:
        logs:
          level: "debug"
```
