### ISSUE TITLE
awskinesisexporter: Add raw encode option

### ISSUE THREAD

**Issue by AmiltonCabral** [open-telemetry/opentelemetry-collector-contrib#33414]
### Component(s)

exporter/awskinesis

### Is your feature request related to a problem? Please describe.

A new encode that exports raw attributes is useful for some contexts, suppose you have a JSON as a string present in some attribute and need to export this attribute as is to a Kinesis stream.

### Describe the solution you'd like

We can have two options:
1. A general solution that exports all attributes as raw to the kinesis.
2. Similar to the first solution, here we will specify the attributes we need to export as raw.

### Additional context

The config will be something like this, if attributes are not specified, the default is to export the whole attributes as raw.

```yaml
exporters:
  ...
  awskinesis:
    ...
    encoding:
      name: raw
        attributes:
          - analytics-json
```
