### ISSUE TITLE
processor_accepted_spans metric not exported

### ISSUE THREAD

**Issue by rpasche** [open-telemetry/opentelemetry-collector-contrib#33410]
### Component(s)

processor/attributes

### Describe the issue you're reporting

Hi,

we are currently running the `collector-contrib` image version `0.100.0` with this config

```
exporters:
  otlp/apm:
    endpoint: apm:1234
    headers:
      Authorization: Bearer ${env:SECRET_TOKEN}
    tls:
      ca_file: /certs/ca.pem
      cert_file: /certs/tls.crt
      insecure_skip_verify: true
      key_file: /certs/tls.key
extensions:
  basicauth/server:
    htpasswd:
      file: /basicauth/.htpasswd
  health_check: {}
  memory_ballast:
    size_in_percentage: 40
  zpages: {}
processors:
  attributes/tenantid:
    actions:
    - action: upsert
      key: tenant.id
      value: ${env:TENANT_ID}
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
receivers:
  otlp:
    protocols:
      grpc:
        auth:
          authenticator: basicauth/server
        endpoint: ${MY_POD_IP}:4317
        tls:
          ca_file: /certs/ca.pem
          cert_file: /certs/tls.crt
          key_file: /certs/tls.key
      http:
        auth:
          authenticator: basicauth/server
        endpoint: ${MY_POD_IP}:4318
        tls:
          ca_file: /certs/ca.pem
          cert_file: /certs/tls.crt
          key_file: /certs/tls.key
service:
  extensions:
  - health_check
  - zpages
  - memory_ballast
  - basicauth/server
  pipelines:
    logs:
      exporters:
      - otlp/apm
      processors:
      - attributes/tenantid
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - otlp/apm
      processors:
      - attributes/tenantid
      - batch
      receivers:
      - otlp
    traces:
      exporters:
      - otlp/apm
      processors:
      - attributes/tenantid
      - batch
      receivers:
      - otlp
  telemetry:
    logs:
      encoding: json
      level: info
    metrics:
      address: 0.0.0.0:8888
      level: detailed
```

We also use [this grafana dashboard](https://grafana.com/grafana/dashboards/15983-opentelemetry-collector/).

While testing to send `traces` through the collector (which are processed correctly), we noticed that nothing is shown for "Processed Spans". This is looking for the metric `otelcol_processor_accepted_spans`, which is not exported by the collector, although the `level: detailed` is set.

We don't know, why this is the case. Reading the docs, and seeing, that `attributesprocessor` is also using the `processorhelper`, this should work.

The only `processor` related metrics that we see, are all `otelcol_processor_batch_....`

We see `otelcol_receiver_accepted_spans` but I would expect, that this should also exist for `otelcol_processor_accepted_spans` (as documented also at https://opentelemetry.io/docs/collector/internal-telemetry/#activate-internal-telemetry-in-the-collector)

Any hints why we don't see this?

Thanks
