### ISSUE TITLE
[Exporter/LoadBalncer] Increased Memory Utilization after bumping from 0.94.0 to 0.99.0

### ISSUE THREAD

**Issue by NickAnge** [open-telemetry/opentelemetry-collector-contrib#33435]
### Component(s)

exporter/loadbalancing

## Description
Hello team. 

We recently upgraded our internal collectors from version 0.94.0 to 0.99.0, and we observed a rise in memory usage at the load balancer deployment collectors, as depicted in the image below. This persisted even after updating to the latest version, 0.101.0.

![Screenshot 2024-06-07 at 19 04 31](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/53213326/bfcb58ed-9d39-49c8-b0ea-2c8f32fd02c2)

We enabled profiling to our collectors (pprof ) component observed inuse_memory and inuse_objects. I seperated by investigation between 3 pods with low, medium  and high memory usage.

# Inuse Memory - Top

## Low Memory Usage Pod
![Screenshot 2024-06-07 at 19 08 07](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/53213326/9f2b0dc3-ea87-4160-ba0a-317e402919d1)

## Medium Memory Usage Pod
![Screenshot 2024-06-07 at 19 08 40](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/53213326/ae42b771-d79e-4c2b-b8f3-1f5960beb816)

## High Memory Usage Pod
![Screenshot 2024-06-07 at 19 08 48](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/53213326/ca67bd09-1868-4232-acde-d4f0ea952c4f)

# Inuse_objects - top

## Low Memory Usage Pod
![Screenshot 2024-06-07 at 19 10 19](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/53213326/37e055d3-3969-4b67-be88-cc77fe9e25a9)

## Medium Memory Usage Pod
![Screenshot 2024-06-07 at 19 10 02](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/53213326/56c3d397-faff-4007-bddf-bfa77019d3cd)

## High Memory Usage Pod
![Screenshot 2024-06-07 at 19 10 12](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/53213326/2f2f85eb-22c4-4f81-8464-b4d53580d869)

## Steps to Reproduce

1. Deployment mode used as Load Balancer with version 0.94.0 
2. Bump the version to 0.101.0

## Expected Result

Expected result was the memory to remain the same over time, after the bump of the version

## Actual Result

High memory usage after bumping the version

### Collector version

0.101.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        max_recv_msg_size_mib: 20

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 95
    spike_limit_percentage: 15
  k8sattributes:
    passthrough: true

exporters:
  loadbalancing/spans:
    protocol:
      otlp:
        sending_queue:
          enabled: true
          num_consumers: 100
          queue_size: 500
        retry_on_failure:
          enabled: true
          initial_interval: 2s
          max_interval: 2s
          max_elapsed_time: 10s
        tls:
          insecure: true
        timeout: 1
    resolver:
      k8s:
        service: service
  loadbalancing/metrics:
    routing_key: metric
    protocol:
      otlp:
        sending_queue:
          enabled: true
          num_consumers: 50
          queue_size: 500
        retry_on_failure:
          enabled: true
          initial_interval: 2s
          max_interval: 2s
          max_elapsed_time: 10s
        tls:
          insecure: true
        timeout: 1
    resolver:
      k8s:
        service: service

extensions:
  health_check:
  pprof:
    endpoint: :1777

service:
  extensions: [ health_check , pprof]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter ]
      exporters: [ loadbalancing/spans ]
    logs:
      receivers: [ otlp ]
      processors: [ memory_limiter ]
      exporters: [ loadbalancing/spans ]
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, k8sattributes ]
      exporters: [ loadbalancing/metrics ]
```
