### ISSUE TITLE
[s3exporter] 405 returned when using the S3 exporter cross AWS accounts

### ISSUE THREAD

**Issue by dabcoder** [open-telemetry/opentelemetry-collector-contrib#33457]
## Description

We're noticing errors in the `opentelemetry-collector` pod logs when trying to use the [S3 exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awss3exporter) cross AWS accounts. e.g. when trying to collect logs from pods running in an EKS cluster in a given AWS account and send those to an S3 bucket located in a different AWS account. The error:

```
"error": "WebIdentityErr: failed to retrieve credentials\ncaused by: SerializationError: failed to unmarshal error message\n\tstatus code: 405, request id: \ncaused by: UnmarshalError: failed to unmarshal error message
…
caused by: unknown error response tag.
```

In AWS, when with S3 access logging, we can see the below error:

```
...REST.POST.OBJECT .../ "POST /.../ HTTP/1.1" 405 MethodNotAllowed....
```

Yet I've double checked my AWS IAM role, policy and trust relationship, and they look correct (actually using a similar role and policy does work when we're in the same AWS account).

## Steps to Reproduce

Use the below config:
```
config:
    exporters: {}
      awss3:
        s3uploader:
          endpoint: "https://<bucket-name>.s3.<region>.amazonaws.com/<folder>"
          region: "us-east-1"
          s3_prefix: "logs"
          s3_partition: "hour"
```

## Expected Result

No 405 response, and logs should appear in the S3 bucket.

## Actual Result

405 response, no logs in the bucket

## Additional information

Considering the AWS Go SDK v1 deprecation next year, it might be worth switching to v2 if possible. [Related discussion](https://github.com/open-telemetry/opentelemetry-collector-contrib/discussions/33183#discussioncomment-9569571).

### Collector version

opentelemetry-collector-contrib:0.97.0

## Environment
EKS

### OpenTelemetry Collector configuration

```yaml
config:
  exporters: {}
    awss3:
      s3uploader:
        endpoint: "https://<bucket-name>.s3.<region>.amazonaws.com/<folder>"
        region: "us-east-1"
        s3_prefix: "logs"
        s3_partition: "hour"
```
