### ISSUE TITLE
New component: Doris Exporter

### ISSUE THREAD

**Issue by joker-star-l** [open-telemetry/opentelemetry-collector-contrib#33479]
### The purpose and use-cases of the new component

The Doris Exporter would allow for the export of logs, metrics, and traces to [Apache Doris](https://doris.apache.org/), a modern data warehouse for real-time analytics.
The Doris Exporter aims to provide a seamless way to export observability data from OpenTelemetry-collected applications to Doris. This component will enable users to take advantage of Doris’s powerful analytics capabilities to gain insights into their application’s performance and behavior.

### Example configuration for the component

Configuration options:

* `endpoint` (no default): The Doris FE address.
* `database` (default otel): The database name.
* `username` (default ): The authentication username.
* `password` (default ): The authentication password.
* `create_schema` (default true): Whether databases and tables are created automatically.
* `logs_table_name` (default otel_logs): The table name for logs.
* `traces_table_name` (default otel_traces): The table name for traces.
* `metrics_table_name` (default otel_metrics): The table name for metrics.
* `ttl` (default 0):  The data time-to-live, 0 means no ttl.
* `timeout` (default 5s): The timeout for each data send.
* `retry` 
  * `enabled` (default true): Whether retries are allowed.
  * `initial_interval` (default 5s): Retry wait time after the first failure. (Ignored if `enabled` is `false`.)
  * `max_interval` (default 30s):  The upper bound on backoff. (Ignored if `enabled` is `false`.)
  * `max_elapsed_time` (default 100s): The maximum time spent trying to send a batch. (Ignored if `enabled` is `false`.)

Example:

```
exporters:
  doris:
    endpoint: http://doris:8030
    database: otel
    username: username
    password: password
    create_schema: true
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    ttl: 7d
    timeout: 5s
    retry:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 100s
```

### Telemetry data types supported

logs, metrics, and traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@xiaokang, @joker-star-l

### Sponsor (optional)

@atoulme
