### ISSUE TITLE
Validate failed to catch invalid value in resource processor

### ISSUE THREAD

**Issue by EddieEldridge** [open-telemetry/opentelemetry-collector-contrib#33486]
### Component(s)

internal/core

## Description
The `validate` flag failed to catch an invalid configuration

## Steps to Reproduce
```yaml
resource/attributes_add:
    attributes:
    - key: service.layer
      value: null  # Problem value
      action: upsert
```

## Expected Result
The `validate` command would flag this as an illegal value

## Actual Result
The Collector failed to start
```go
Error: failed to build pipelines: failed to create "resource/attributes_add" processor, in pipeline "traces": error creating AttrProc. Either field "value", "from_attribute" or "from_context" setting must be specified for X-th action
```

### Collector version

0.94.0

### OpenTelemetry Collector configuration

```yaml
resource/attributes_add:
    attributes:
    - key: service.layer
      value: null  # Problem value
      action: upsert
```

### Log output

```shell
Error: failed to build pipelines: failed to create "resource/attributes_add" processor, in pipeline "traces": error creating AttrProc. Either field "value", "from_attribute" or "from_context" setting must be specified for X-th action
```
