### ISSUE TITLE
New component: Add systemd receiver

### ISSUE THREAD

**Issue by Hemansh31** [open-telemetry/opentelemetry-collector-contrib#33532]
### The purpose and use-cases of the new component

The systemd receiver collects the value of different properties of a systemd unit and publishes that data as metrics data.

### Example configuration for the component

receivers:
  systemd:
     services:
     - sshd.service
     - example.service
     properties:
     - ActiveState
     - LoadedState
     - MainPID

### Telemetry data types supported

These would be primarily metrics

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@Hemansh31 

### Sponsor (optional)

@atoulme

**Comment by atoulme** [comment]
Can you dhare what metadata.yaml would look like?

**Comment by Hemansh31** [comment]
```yml
type: systemdreceiver/service
scope_name: otelcol/systemdreceiver/service

parent: systemdreceiver

attributes:
  name:
    description: Name of the systemd unit.
    type: string

  type:
    description: The type of systemd unit.
    type: string
    enum: [service]


# ActiveState Code
# Value   Meaning   Description
#   0   active        unit is ~
#   1   reloading     unit is ~
#   2   inactive      unit is ~
#   3   failed        unit is ~
#   4   activating    unit is ~
#   5   deactivating  unit is ~


# LoadState Code
# Value   Meaning   Description
#   0   loaded        unit is ~
#   1   stub          unit is ~
#   2   not-found     unit is ~
#   3   bad-setting   unit is ~
#   4   error         unit is ~
#   5   merged        unit is ~
#   6   masked        unit is ~

metrics:
  systemd.service.ActiveState:
    enabled: true
    description: Active State of the systemd service.
    unit: ~
    gauge:
      value_type: int
    attributes: [name, type]
  systemd.service.LoadState:
    enabled: true
    description: Load State of the systemd service.
    unit: ~
    gauge:
      value_type: int
    attributes: [name, type]

```
