### ISSUE TITLE
openid authorization support (otel extension) for opamp supervisor 

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#33590]
### Is your feature request related to a problem? Please describe.

Please add openid authorization support (like otel extensions) for opamp supervisor configuration. 

### Describe the solution you'd like

Authorization based on openid connect is supported like its done for exporters by otel collector via extension https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/8f6fc8f16a628e0c4d6bdfd4f516ddb46b899e0c/extension/oidcauthextension

```
extensions:
  oidc:
    issuer_url: http://localhost:8080/auth/realms/opentelemetry
    issuer_ca_path: /etc/pki/tls/cert.pem
    audience: account
    username_claim: email

server:
  endpoint: wss://localhost:4320/v1/opamp
  auth:
    authenticator: oidc
```
