### ISSUE TITLE
New component: cfgardenobserver

### ISSUE THREAD

**Issue by jriguera** [open-telemetry/opentelemetry-collector-contrib#33618]
### The purpose and use-cases of the new component

We would like to implement a new observer for [Cloudfoundry](https://www.cloudfoundry.org) containers/applications. The idea is not make use of the main API but the local one, which is available as unix socket on each node and manages the containers lifecycle. The main API would remain as optional and only to get Application info (which only involves one GET http request once the app id is known).

We want to have the applications exposing metrics (prometheus openmetrics format: `/metrics` endpoint) automatically scraped with an OpenTelemetry collector running on each node. The idea is building a "cfgardenobserver" (similar to [k8sobserver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/observer/k8sobserver/README.md), or [dockerobserver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/observer/dockerobserver/README.md)) which polls the garden api periodically and automatically discovers the (local) containers in the diego-cell and feeds a [receivercreator](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/receivercreator/README.md) to build (or remove -if the container is gone-) an instance of a [prometheusclient](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md) (or most likely a [simpleprometheusreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/simpleprometheusreceiver/README.md)) with the proper settings (mTLS or extra metrics labels) to scrape the app instance. Eventually the metrics collected will be pushed to an OTLP endpoint. This would be a similar to K8S with the the [K8S downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) (a sort of reduced API for simple/local queries) with the `k8sobserver`, which avoids querying the entire cluster and only returns information about containers (pods) currently running on the node.

### Example configuration for the component

```
# Otel collector config
extensions:
  cfgarden_observer:
    endpoint: unix:///var/vcap/data/garden/garden.sock
    default_container_port: 8080
    default_metrics_path: /internal/metrics
    # Only used optionally to get application annotations/labels and extra information not provided by low level Garden API
    # Use it carefully because the API is slow and it cannot be continuosly queried (on each listcontainers run)
    cf_api:
        url: https://cf.api
        username: user
        password: pass


receivers:
  receiver_creator:
    watch_observers: [cfgarden_observer]
    receivers:
      prometheus_simple:
        # we only scrape apps from a specific org id
        rule: type == "container" && labels["network.org_id"] == "98368c71-f3fb-4897-81b1-b58e1f226ea1"
        config:
           collection_interval: 60s
          # This is not needed but the endpoint would be build from the ContainerIP property using the default port `8080`
          # (mapped by default in all apps) with the default path /internal/metrics
          # endpoint: '`endpoint`'
        resource_attributes:
          org_id: labels["network.org_id"]
          space_id: labels["network.space_id"]
          app_id: labels["network.app_id"]
          org: labels["log_config.tags.organization_name"]
          space: labels["log_config.tags.space_name"]
          app: labels["log_config.tags.space_name"]
          app_index: labels["log_config.index"]
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@crobert-1

### Sponsor (optional)

@crobert-1

### Additional context

Cloudfoundry is a PaaS which has implemented their own container technology. The component in charge of providing a local API in each node (also known as "diego-cell") is named [Garden](https://github.com/cloudfoundry/garden/blob/main/README.md). Garden can use different backends to manage the lifecycle of the containers (runc, containerd, etc) and abstrat the OS. The [API](https://github.com/cloudfoundry/garden/blob/main/doc/garden-api.md) supports unix socket or regular network port. There is a [golang library](https://pkg.go.dev/code.cloudfoundry.org/garden@v0.0.0-20240611194356-c66dc427ceca) to handle the functionality of interacting with containers. In this case, only GET/List operations would be performed to list running containers and get the [ContainerInfo] property (https://pkg.go.dev/code.cloudfoundry.org/garden#ContainerInfo) will be used. The `ContainerInfo` will be mapped to `observer.Endpoint` as `container` type.

Applications running in a container can be a copy from a docker image or an application build from the code with a [buildpack](https://docs.cloudfoundry.org/buildpacks/). 
By convention, buildpack apps "always" run on a port 8080 inside the container, which is mapped to external ports, depending on the PaaS configuration can be secured with mTLS, non secured at all, or both. The operators can pass the mTLS configuration to `prometheus_simple` receiver to define it.

Docker containers have always the first exposed port as main application port, but is not required to be 8080. The port can be extracted from the port-mappings provided by Garden.

In any case, the [port 61001 (inside the container) uses mTLS and it is always proxying the traffic to the main application port](https://github.com/cloudfoundry/diego-release/blob/develop/docs/envoy-proxy-configuration.md#-envoy-proxy-configuration-for-route-integrity).
