### ISSUE TITLE
Load Balancing by Attribute

### ISSUE THREAD

**Issue by danielbanks** [open-telemetry/opentelemetry-collector-contrib#33660]
### Component(s)

exporter/loadbalancing

### Is your feature request related to a problem? Please describe.

In our project want to setup load balanced sampling based on a session ID an attribute. 

In our project, we care about RUM and we have the concept of a user session with a session ID set as an attribute on our traces. We sample based on the session ID rather than the trace ID. This way we preserve telemetry of the whole user session.

The sampling is working fine but it is client-side head sampling. As we look to scale our solution we want to move this to the collector and introduce load balancing. 

How do we achieve session sampling?

Right now we use the same ID generator for trace IDs as for session and we set it as an attribute. Then we have a head sampling strategy that uses the same logic as the probabilistic head sampler, but rather than applying the decision to the trace ID we apply it to the session ID. This ensures we make the same sampling decision for the whole user session. 

What we would like to do is move these sampling decisions off the client and into the collector so that we have more flexibility. Our client is an Android application and making these decisions client side is not a long-term solution because we have to deal with application updates etc.

Following the recommended practice we would like to have a 2 layer collector setup, with the first layer load balancing the second. The issue is that the load balancer only supports decisions based on trace ID or service name.

Given that we want to sample based on session ID (an attribute), then making load balancing decisions on trace ID alone is not enough. We need to load balance telemetry with the same session ID to the same collector instance so that consistent sampling decisions can be made.

It doesn't look like the load balancer currently supports balancing based on an attribute. This is a friendly request to add it!

### Describe the solution you'd like

The ability to route telemetry based on attributes in addition to service name and trace ID

**Comment by jpkrohling** [comment]
I believe there are a couple of comments to this:

1. balancing based on an arbitrary attribute is doable, and we are doing that already for the service name. It should be easy to extend this function here to do that: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2aa0e6b717c1b9f228552cc91f2214beb72fcde2/exporter/loadbalancingexporter/trace_exporter.go#L135-L165
2. I'm not quite sure you need two layers: if you are doing probabilistic sampling based on the session ID, it's pretty much the same idea we have for the probabilistic sampling at the collector, which means that it can be consistent across collector instances without the need to centralize all session IDs on the same decision instances. So, you might not need the balancer to know about session IDs at all

**Comment by danielbanks** [comment]
Thanks for the reply @jpkrohling. That's useful insight.

I'd like to move our probabilistic sampling of sessions into the collector rather than having this client side. But the [sampler](https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fopentelemetry-collector-contrib%2Fissues%2F33660) configuration can only specify custom attributes for logs not traces. Our target solution is to have load-balanced telemetry across logs and traces, which is sampled based on sessions complete sessions. We want to observe the users sessions so that we can understand the full journey.

Do you have any recommendations for how this can be achieved with the current tooling?

**Comment by jpkrohling** [comment]
Take a look at the code for the probabilistic sampling processor at contrib. It could be changed to use specific attributes instead of trace ID, which would be sufficient for your use case, if I'm understanding it correctly.

**Comment by skandragon** [comment]
I would also like this feature.

**Comment by swar8080** [comment]
Extracting the attribute with an OTTL statement might be useful

As a workaround, we're currently overwriting `service.name` with the deployment name since our load isn't well spread across services. When receiving the load-balanced spans we restore the old value of `service.name`

It looks something like this:

```
processors:
      transform/spans_before_loadbalancing:
        error_mode: ignore
        trace_statements:
          - context: resource
            statements:
              - set(attributes["service.name.backup"], attributes["service.name"])
              - set(attributes["service.name"], attributes["k8s.pod.name"])

processors:
      transform/spans_after_loadbalancing:
        error_mode: ignore
        trace_statements:
          - context: resource
            statements:
              - set(attributes["service.name"], attributes["service.name.backup"])
              - delete_key(attributes, "service.name.backup")
```
