### ISSUE TITLE
postgresql receiver should output hostname with metrics

### ISSUE THREAD

**Issue by nsteinmetz** [open-telemetry/opentelemetry-collector-contrib#33709]
### Component(s)

receiver/postgresql

## Description

I setup otelcol-contrib on two servers - I can't filter metrics per hostname. So I have only an aggregated view of metrics.

## Steps to Reproduce

Launch 2 instances of postgres, one is primary, one is replica
Launch otelcol-contrib on both instances

## Expected Result

being able to filter metrics per hostname

## Actual Result

No filtering per hostname

### Collector version

0.103.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by nsteinmetz** [comment]
Ok found how to do it, just add the `resourcedetection` processor and add it in the pipeline configuration

```yaml
  processors:
    resourcedetection:
      detectors: [env, system]
[...]
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/uptrace, debug]
      metrics:
        receivers: [otlp, postgresql]
        processors: [cumulativetodelta, batch, resourcedetection]
        exporters: [otlp/uptrace, debug]
```
