### ISSUE TITLE
redis receiver should allow to use a username in addition to password

### ISSUE THREAD

**Issue by nsteinmetz** [open-telemetry/opentelemetry-collector-contrib#33707]
### Component(s)

receiver/redis

## Description

With Redis 7, a new ACL mechanism was deployed and there is no longer a single user (ie `requirepass` property).

Thus, it would be nice to pass a username and a password to redis when you have a dedicated user for monitoring instead of default one.

## Steps to Reproduce

Set ACL in redis.conf

```
user default on > some_password ~* +@all
user monitoring_user on > monitoring_password ~* +@admin +@dangerous
```

## Expected Result

```
receivers:
    redis:
      endpoint: localhost:6379
      collection_interval: 10s
      username: monitoring_user
      password: monitoring_password
```

## Actual Result

Only default password works to authenticate to redis

```
receivers:
    redis:
      endpoint: localhost:6379
      collection_interval: 10s
      password: some_password
```

### Collector version

0.103.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
