### ISSUE TITLE
NO_PROXY env var doesn't work after upgrade collector

### ISSUE THREAD

**Issue by diecgia** [open-telemetry/opentelemetry-collector-contrib#33704]
### Component(s)

exporter/elasticsearch

## Description
After upgrading opentelemetry-collector-contrib from version 0.81.0 to 0.101.0, otlp/elastic exporter is failing because it tries to send traces through the proxy set on env vars, but no_proxy var is also set for elastic URL, so it shouldn't use proxy.
## Steps to Reproduce
Upgrade to collector-contrib 0.101.0 and set the following env vars:
            "no_proxy_"="<elastic_url>",
            "http_proxy"="<proxy_url>",
            "https_proxy"="<proxy_url>"
## Expected Result
Send traces to elastic without the proxy, because it is set in the env var no_proxy
## Actual Result
Traces are attempted to be sent through the proxy

### Collector version

0.101.0

### Environment information

opentelemetry-collector-contrib image

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
processors:
  batch:
    send_batch_max_size: 1
    send_batch_size: 1
    timeout: 10s
exporters:
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  otlp/elastic:
    endpoint: "<elastic_url>"
    tls:
      insecure: true
extensions:
  health_check: {}
service:
  extensions:
    - health_check
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlp/elastic]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic, logging]
```
