### ISSUE TITLE
TCP version of HTTP Check Receiver

### ISSUE THREAD

**Issue by Breee** [open-telemetry/opentelemetry-collector-contrib#33718]
### Is your feature request related to a problem? Please describe.

I'd like to migrate from elastic heartbeats  to otel collector,   https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/httpcheckreceiver is perfect for that i think, it is however missing the possibility to check TCP endpoints

### Describe the solution you'd like

Someone already proposed it, however it just got closed down sadly https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/20738

 It would be great to have something along the lines of: 

```
receivers:
  tcpcheck:
    endpoint: notdefault:1313
    transport: tcp
    collection_interval: 15s
```
