### ISSUE TITLE
[receiver/prometheus] honor_labels set to true and scraping a prometheus pushgateway not working

### ISSUE THREAD

**Issue by paebersold-tyro** [open-telemetry/opentelemetry-collector-contrib#33742]
### Component(s)

receiver/prometheus

## Description

Scraping a Prometheus pushgateway with `honor_labels: true` results in a scrape endpoint failure.  Suspect this is due to the scrape metrics having both instance and jobs labels (from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15239) but would like clarification that this is the problem.  Also is there any work around (other than setting `honor_labels: false`).  Attempted doing a label drop with metric_relabel_config but that did not work.

## Steps to Reproduce

Prometheus receiver config

```
          - job_name: test-pushgateway
            scrape_interval: 30s
            scrape_timeout: 10s
            honor_labels: true
            scheme: http
            kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                - app-platform-monitoring
            relabel_configs:
            # and pod is running
            - source_labels: [__meta_kubernetes_pod_phase]
              regex: Running
              action: keep
            # and pod is ready
            - source_labels: [__meta_kubernetes_pod_ready]
              regex: true
              action: keep
            # and only metrics endpoints
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: metrics
```

## Expected Result

Endpoint is scraped, job and instances labels from the pushgateway are used.

## Actual Result

Endpoint scrape failure (see log message below)

### Collector version

0.102.0

## Environment
OS: Kubernetes 1.29

### OpenTelemetry Collector configuration

```yaml
receiver:
    prometheus:
      config:
          - job_name: test-pushgateway
            scrape_interval: 30s
            scrape_timeout: 10s
            honor_labels: true
            scheme: http
            kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                - app-platform-monitoring
            relabel_configs:
            # and pod is running
            - source_labels: [__meta_kubernetes_pod_phase]
              regex: Running
              action: keep
            # and pod is ready
            - source_labels: [__meta_kubernetes_pod_ready]
              regex: true
              action: keep
            # and only metrics endpoints
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: metrics
exporter:
  debug: {}
service:
  pipeline:
    metrics:
      exporters: [debug]
      processors: []
      receivers: [prometheus]
```

### Log output

```shell
2024-06-24T06:20:36.193Z        warn    internal/transaction.go:125     Failed to scrape Prometheus endpoint    {"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_timestamp": 1719210036190, "target_labels": "{__name__=\"up\", instance=\"10.18.67.171:9091\", job=\"test-pushgateway\"}"}
```

### Additional context

sample of metrics that are returned from the pushgateway

```
app_platform_attestation{feature="coredns",instance="",job="cluster",team="bob",test="TestCoreDNSNameResolution"} 1
app_platform_attestation{feature="coredns",instance="",job="cluster",team="bob",test="TestIsCoreDNSDeployed"} 1
app_platform_attestation{feature="coredns",instance="",job="cluster",team="bob",test="TestIsCoreDNSServiceAvailable"} 1
push_failure_time_seconds{feature="coredns",instance="",job="cluster"} 0
push_time_seconds{feature="coredns",instance="",job="cluster"} 1.7192055849949868e+09
```

**Comment by dashpole** [comment]
Can you set the log level of the collector to debug to see the detailed error message for why the scrape failed?

**Comment by dashpole** [comment]
I think it should be:

```yaml
service:
    logs:
        level: DEBUG
```
