### ISSUE TITLE
New component: googlecloudmonitoringreceiver

### ISSUE THREAD

**Issue by datsabk** [open-telemetry/opentelemetry-collector-contrib#33762]
### The purpose and use-cases of the new component

The component will retrieve GCP Cloud Monitoring timeseries data and convert it into Otel compatible data format. 

### Example configuration for the component

```
googlecloudmonitoring:
  collection_interval: 120s
  region: us-central1
  project_id: cloudwerx-otel-integration-dev
  service_account_key: "path/to/service_account.json"
  services:
    - service_name: "compute"
      delay: 60 # Second
      metric_name: "compute.googleapis.com/instance/cpu/usage_time"
      interval: 120 # Second
```

### Telemetry data types supported

Metrics

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

Tyler Helmuth, Abhishek Kothari

### Sponsor (optional)

David Ashpole (dashpole)

### Additional context

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2286

The component has already been accepted by the sponsor and we are on track to create the first PR soon. This issue is to primarily abide by the new component process as per the contribution guidelines.
