### ISSUE TITLE
[resourcedetection] cpuinfo ignores the configured timeout in the resourcedetection processor

### ISSUE THREAD

**Issue by cwegener** [open-telemetry/opentelemetry-collector-contrib#33771]
### Component(s)

processor/resourcedetection, processor/resourcedetection/internal/system

## Description
The host cpuinfo attributes introduced in  #26533 use the `cpu.Info()` call from `gopsutil`.

`cpu.Info()` ignores any timeouts that a user configures in the resourcedetection processor, as it is simply calling `cpu.InfoWithContext(context.Background)`  [^1]

```
func Info() ([]InfoStat, error) {
	return InfoWithContext(context.Background())
}
```

## Steps to Reproduce

N/A - A repro would require a really elaborate set up with a reliable way of slowing down COM calls in windows. Outside of production systems, I don't know how to artificially slow down COM calls ...

## Expected Result

cpuinfo honors the configured timeout as configured by the user.

## Actual Result

cpuinfo disregards the configured timeout as configured by the user.

[^1]: https://github.com/shirou/gopsutil/blob/master/cpu/cpu_windows.go#L92-L94

### Collector version

v0.103.1

## Environment
OS: Windows (10, 11, 2019, 2022)

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  resourcedetection:
    timeout: 60s
    detectors:
      - system
      - env
    system:
      resource_attributes:
        host.id:
          enabled: true
exporters:
  logging:
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - resourcedetection
      exporters:
        - logging
```
