### ISSUE TITLE
swallowed exception in Operator.Process

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-collector-contrib#33783]
### Component(s)

pkg/stanza, pkg/stanza/fileconsumer

## Description

Some of the usages of https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d78d7bb37d0c84da04ac8a83356eb669ecd75a95/pkg/stanza/operator/operator.go#L40 don't check for the error, which can lead to silent errors

### Real config

```yaml
      filelog/fraud-detection-raw:
        include:
          - /var/log/pods/*/*/*.log      
        operators:
        - id: container-parser
          type: container
```

Why?
- `include_file_path: true` is missing - but is required unless you set `add_metadata_from_filepath: false`
- exception: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6395ff8916f355d9a2c6d8e837e2e07dd6a4f14f/pkg/stanza/operator/parser/container/parser.go#L294

### Test

remove this line: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/6395ff8916f355d9a2c6d8e837e2e07dd6a4f14f/pkg/stanza/operator/parser/container/parser_test.go#L246

## Expected Result

error is reported to user

## Actual Result

error is silent - you just don't get log messages

### Collector version

0.103.0
