### ISSUE TITLE
k8sobjects to elasticsearch failed for the field app

### ISSUE THREAD

**Issue by MaheshSankaran** [open-telemetry/opentelemetry-collector-contrib#33801]
### Component(s)

receiver/k8sobjects

## Description
Trying to configure k8s object events to elasticsearch

## Steps to Reproduce
```
receivers:
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: events
            mode: watch
          - name: pods
            mode: pull


    exporters:
      logging:
        verbosity: detailed
      elasticsearch/events:
        endpoints: [https://elasticsearch-es-internal-http:9200]
        index: indexname
        user: elastic
        password: elastic
        sending_queue:
          enabled: true
          num_consumers: 1
          queue_size: 1000
        tls:
          insecure_skip_verify: true

    service:
      pipelines:
        logs:
          receivers:
          - k8sobjects
          exporters:
          - logging
          - elasticsearch/events
```

## Actual Result
error	elasticsearchexporter@v0.103.0/elasticsearch_bulk.go:309	Drop docs: failed to index: struct { Type string "json:\"type\""; Reason string "json:\"reason\"" }{Type:"document_parsing_exception", Reason:"[1:447] object mapping for [Body.metadata.labels.app] tried to parse field [app] as object, but found a concrete value"}	{"kind": "exporter", "data_type": "logs", "name": "elasticsearch/events", "status": 400}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*worker).flush
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.103.0/elasticsearch_bulk.go:309
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*worker).run
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.103.0/elasticsearch_bulk.go:291
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newBulkIndexer.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.103.0/elasticsearch_bulk.go:207

### Collector version

v0.103.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: events
            mode: watch
          - name: pods
            mode: pull


    exporters:
      logging:
        verbosity: detailed
      elasticsearch/events:
        endpoints: [https://elasticsearch-es-internal-http:9200]
        index: indexname
        user: elastic
        password: elastic
        sending_queue:
          enabled: true
          num_consumers: 1
          queue_size: 1000
        tls:
          insecure_skip_verify: true

    service:
      pipelines:
        logs:
          receivers:
          - k8sobjects
          exporters:
          - logging
          - elasticsearch/events
```

### Log output

```shell
error	elasticsearchexporter@v0.103.0/elasticsearch_bulk.go:309	Drop docs: failed to index: struct { Type string "json:\"type\""; Reason string "json:\"reason\"" }{Type:"document_parsing_exception", Reason:"[1:447] object mapping for [Body.metadata.labels.app] tried to parse field [app] as object, but found a concrete value"}	{"kind": "exporter", "data_type": "logs", "name": "elasticsearch/events", "status": 400}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*worker).flush
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.103.0/elasticsearch_bulk.go:309
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*worker).run
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.103.0/elasticsearch_bulk.go:291
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newBulkIndexer.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.103.0/elasticsearch_bulk.go:207
```
