### ISSUE TITLE
[processor/transform] Allow specifying metric name suffix when using convert summary functions

### ISSUE THREAD

**Issue by h0cheung** [open-telemetry/opentelemetry-collector-contrib#33850]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

There are functions like `convert_summary_count_val_to_sum` and `convert_summary_sum_val_to_sum`, which can convert values in summary to sum and count.
However, the have some limitions:
- the suffix added is always `_sum` or `_count`. But according to OpenTelemetry's convention, `.` should be used instead of `_` in this case.
- Support for quantile is missing.

### Describe the solution you'd like

1. Update function specification: `convert_summary_count_val_to_sum(aggregation_temporality, is_monotonic, Optional[suffix])`. The new optional parameters allow setting the suffix to add. By default, `suffix` is ".sum".
2. New function: `converter_summary_quantile_val_to_gauge(Optional[suffix])`. The `suffix` defaults to ".quantile_%s", where `%s` will be replaced with the quantile value and the decimal point will be removed. For example, ".quantile_99", ".quantile_999" will be added.

### Describe alternatives you've considered

Use a single function or component to convert summary to two sums and a gauge.

**Comment by TylerHelmuth** [comment]
As a workaround for now, a second statement can be written to change the metric name

**Comment by h0cheung** [comment]
> As a workaround for now, a second statement can be written to change the metric name

But is I don't have the full list of metrics to be converted, I can't do it exactly.

If I change metric name by rename all metrics ends with `_sum` or `_count`, many metrics may be transformed incorrectly.

**Comment by TylerHelmuth** [comment]
@evan-bradley and I are good with moving forward with this idea.

**Comment by odubajDT** [comment]
Hi, I would like to work on this

**Comment by odubajDT** [comment]
First PR handling the optional suffixes https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37238

Addition of converter_summary_quantile_val_to_gauge(Optional[suffix]) function will be added in a separate PR

**Comment by odubajDT** [comment]
@h0cheung clarification question here:

> New function: `converter_summary_quantile_val_to_gauge(Optional[suffix])`. The suffix defaults to ".quantile_%s", where %s will be replaced with the quantile value and the decimal point will be removed. For example, ".quantile_99", ".quantile_999" will be added.

Since a single summary datapoint has slice of quantiles, do I understand it correctly that a single Summary can be converted into multiple Gauges? Thanks!

cc @evan-bradley @TylerHelmuth

**Comment by odubajDT** [comment]
Looked at some of the options and implemented the solution as following:

Function will convert all quantiles of a Summary to a single Gauge with multiple datapoints, where each datapoint has an attribute representing the quantile.

The conversion will look like the following:

```
summary
   datapoints:
       sum: 22
       count: 10
       quantiles:
             quantile: 0.1
             value: 2
             quantile: 0.5
             value: 5
             quantile: 0.9
             value: 7
```

will be converted to following:

```
gauge:
    datapoints:
         attributes:
              quantile="0.10"
         value: 2
         attributes:
              quantile="0.50"
         value: 5
         attributes:
              quantile="0.90"
         value: 7
         
```

The name, attributes(on datapoint level), timestamps, unit, description etc will be copied from the summary to gauge without any modifications


Let me know your thoughts!

cc @TylerHelmuth @evan-bradley
