### ISSUE TITLE
Loadbalancing Exporter Not Forwarding Incoming Request Headers to Downstream Collector

### ISSUE THREAD

**Issue by bvsvas** [open-telemetry/opentelemetry-collector-contrib#33883]
### Component(s)

exporter/loadbalancing

## Description
Experiencing an issue with the loadbalancing exporter in OpenTelemetry Collector where incoming request headers (HTTP/gRPC) are not being forwarded to the downstream(second) collector. This behavior is critical for our use case, where headers such as Authorization need to be preserved throughout the request flow.

## Steps to Reproduce

1. Configure the OpenTelemetry Collector with the loadbalancing exporter (Configure two collectors, first one with loadbalancing exporter).
2. Send a request with specific headers (e.g., Authorization) to the collector.
3. Observe that the downstream collector does not receive the headers.

## Expected Result
The loadbalancing exporter should forward all incoming request headers to the downstream collector by default.

## Actual Result
The request headers are not being forwarded to the downstream collector.

### Collector version

0.103.0

## Environment
OS: CentOS
Kubernetes: 1.28
Deployment: Kubernetes Cluster
Image: otel/opentelemetry-collector-contrib:0.103.0

### OpenTelemetry Collector configuration

```yaml
extensions:
      health_check:
        endpoint: 0.0.0.0:13133
        path: "/health"
    exporters:
      loadbalancing:
        protocol:
          otlp:
            timeout: 1s
            tls:
              insecure: true
        resolver:
          k8s:
            service: otelcol-ingester-service
            ports:
            - 4318
            - 4317
    processors:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      telemetry:
        logs:
          level: debug
      extensions: [health_check]
      pipelines:
        metrics:
          exporters:
            - loadbalancing
          processors: []
          receivers:
            - otlp
        traces:
          exporters:
            - loadbalancing
          processors: []
          receivers:
            - otlp
```

### Additional context

We have attempted using the headerssetter extension, but the issue persists. Any guidance on how to ensure headers are forwarded would be appreciated.

```
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
        path: "/health"
      headers_setter:
        headers:
        - action: insert
          key: authorization
          from_context: authorization
    exporters:
      loadbalancing:
        routing_key: "service"
        protocol:
          otlp:
            timeout: 1s
            tls:
              insecure: true
        resolver:
          k8s:
            service: otelcol-ingester-service
            ports:
            - 4318
            - 4317
    processors:
      resource:
        attributes:
        - key: authorization
          from_context: authorization
          action: insert
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            include_metadata: true
          http:
            endpoint: 0.0.0.0:4318
            include_metadata: true
    service:
      telemetry:
        logs:
          level: debug
      extensions: [headers_setter]
      pipelines:
        metrics:
          exporters:
            - loadbalancing
          processors: 
            - resource
          receivers:
            - otlp
        traces:
          exporters:
            - loadbalancing
          processors:
            - resource
          receivers:
            - otlp
```
