### ISSUE TITLE
Reuse add_metadata_from_filepath

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-collector-contrib#33912]
### Component(s)

pkg/stanza, receiver/filelog

### Is your feature request related to a problem? Please describe.

[add_metadata_from_filepath](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/docs/operators/container.md#add-metadata-from-file-path) is tied to the container operator.

### Describe the solution you'd like

Would it make sense to move this feature to [file consumer](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d065d41b980812603841ecb70db1431cd3312b53/pkg/stanza/fileconsumer/config.go#L73), so that it can be reused, e.g. in [OTLP JSON File Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/otlpjsonfilereceiver/README.md)?

### Describe alternatives you've considered

Could be done manually - if operators were supported for OTLP JSON File Receiver:

```yaml
otlpjsonfile:
        include:
          - /var/log/pods/*/anti-fraud/*.log
        include_file_path: true
        operators:
          - id: extract_metadata_from_filepath
            type: regex_parser
            cache:
              size: 128
            parse_from: attributes["log.file.path"]
            regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$
          - from: attributes.restart_count
            to: resource["k8s.container.restart_count"]
            type: move
          - from: attributes.uid
            to: resource["k8s.pod.uid"]
            type: move
          - from: attributes.container_name
            to: resource["k8s.container.name"]
            type: move
          - from: attributes.namespace
            to: resource["k8s.namespace.name"]
            type: move
          - from: attributes.pod_name
            to: resource["k8s.pod.name"]
            type: move
```
