### ISSUE TITLE
[receiver/expvar] Add ability to collect internal memstats

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-collector-contrib#33926]
### Component(s)

receiver/expvar

### Is your feature request related to a problem? Please describe.

Current the `expvarreceiver` has the ability to query an HTTP endpoint to gather memstats. However, it doesn't have the ability to query the actual process the collector is running on, and emit that (unless of course, the user has started an expvar server in the same process and pointed the expvarreceiver at it, but this requires code changes from the user).

Having memstats about the collector is useful especially in high-memory usage scenarios. 

### Describe the solution you'd like

Currently the configuration looks like:
```yaml
receivers:
  expvar:
    endpoint: "http://localhost:8000/custom/path"
    timeout: 1s
    collection_interval: 30s
    metrics:
      process.runtime.memstats.total_alloc:
        enabled: true
      process.runtime.memstats.mallocs:
        enabled: false
```

We could add another field similar to `metrics`, called `internal_metrics`, which has the same type but collects the metrics from internally (using the `runtime` package). Disabled by default, but optionally enabled. 

### Describe alternatives you've considered

There's two other ways I thought of doing this: 
1. an `expvarextension` that starts a server and serves the collector's internal memstats. Would work, is a lot more code and IMO overkill. 
2. Compiling my own collector, running the expvar server manually from that, before starting the collector.
