### ISSUE TITLE
TCP Statsd Receiver is not able to read payload

### ISSUE THREAD

**Issue by 4wdonny** [open-telemetry/opentelemetry-collector-contrib#33951]
### Component(s)

receiver/statsd

## Description
TCP Statsd Receiver can't decode payload

## Steps to Reproduce
I've deployed the veneur-emit docker image and have it setup to emit metrics to a GCP LB in front of some collector pods using the statsd receiver set to TCP transport mode. If I set veneur-emit to ship the same metric via UDP to an agent running the statsd receiver with UDP set as the transport, I see my metrics processed correctly. 
## Expected Result
Statsd Metrics are ingested and processed over TCP the same as they are UDP
## Actual Result
```debug	statsdreceiver@v0.103.0/reporter.go:46	TCP transport (10.3.5.124:8128) Error reading payload: EOF	{"kind": "receiver", "name": "statsd", "data_type": "metrics"}```

Veneur Emit command
```
/veneur-emit -hostport tcp://$GCP_LB:8128 -name "my.test.metric" -tag "env:sandbox" -count "1" -debug
```

### Collector version

0.103.0

## Environment
GKE 1.28

### OpenTelemetry Collector configuration

```yaml
statsd:
    endpoint: "0.0.0.0:8128"
    transport: "tcp"
    aggregation_interval: 60s
    enable_metric_type: true
    enable_simple_tags: true
    is_monotonic_counter: true
    timer_histogram_mapping:
      - statsd_type: "histogram"
        observer_type: "gauge"
      - statsd_type: "timing"
        observer_type: "histogram"
        histogram:
          max_size: 100
```
