### ISSUE TITLE
AzureDataExplorerExporter azure manage identity

### ISSUE THREAD

**Issue by Ivalberto** [open-telemetry/opentelemetry-collector-contrib#33990]
### Component(s)

exporter/azuredataexplorer

## Description
HI Guys, I trying to setup the azure data explorer exporter using manage identity , but always i recieving : identity isn't assignet to this resource, I already create a Manage Identity on azure, and adden as user assingned managed identity on the cluster, and give the permission also as AllDataBaseAdmin role

I this case Do I need to associate the MI to a Service Account similar to the process to use Workload identity in the cluster? or not ncesary ? 

 Thank in advance.

## Steps to Reproduce

- Create a managed identity on Azure , 
- associate to azure data explorer
- set manage identity on configuration file 

## Expected Result

- Otel collector sending info to azure data explorer

## Actual Result

- Error accessing to azure data explorer : identity isn't assigned to this resource

### Collector version

0.102

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
azuredataexplorer:
      # Kusto cluster uri
      cluster_uri: "https://xxxxxxxxx-cluster.eastus.kusto.windows.net"
      managed_identity_id: "xxxxxxxx-829e-4202-8621-xxxxxxxxxxxx"
      # Database for the logs
      db_name: "xxxxxx-adx-database"
      # Metric table name
      metrics_table_name: "metrics"
```

### Log output

```shell
Op(OpMgmt): Kind(KInternal): Error while getting token : ManagedIdentityCredential authentication failed. ManagedIdentityCredential authentication failed. the requested identity isn't assigned to this resource\nGET http://x.x.x.x/metadata/identity/oauth2/token\n--------------------------------------------------------------------------------\nRESPONSE 400 Bad Request\n--------------------------------------------------------------------------------\n{\n  \"error\": \"invalid_request\",\n  \"error_description\": \"Identity not found\"\n}\n--------------------------------------------------------------------------------\nTo troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id\nGET http://x.x.x.x/metadata/identity/oauth2/token\n--------------------------------------------------------------------------------\nRESPONSE 400 Bad Request\n--------------------------------------------------------------------------------\n{\n  \"error\": \"invalid_request\",\n  \"error_description\": \"Identity not found\"\n}\n--------------------------------------------------------------------------------\nTo troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id"}
```
