### ISSUE TITLE
Copy multiple attributes/labels in k8sattributes

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-collector-contrib#34040]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

As a user, I'd like to add my resource attributes as k8s attributes/labels in a generic way:

`opentelemetry.io/resource.deployment.environment` should become `deployment.environment` and so on

### Describe the solution you'd like

similar to to the existing `regex: field=(?P<value>.+)` syntax

```yaml
k8sattributes:
  auth_type: "serviceAccount"
  passthrough: false
  extract:
   labels:
     - key_regex: opentelemetry.io/resource.(?P<key>.+)
       from: pod
```
