### ISSUE TITLE
New component: Google Cloud Logging Receiver

### ISSUE THREAD

**Issue by abhishek-at-cloudwerx** [open-telemetry/opentelemetry-collector-contrib#34056]
### The purpose and use-cases of the new component

Presently, the recommended method for retrieving Google Cloud Logs is to use Log Router, Google PubSub and the googlepubsubreceiver. However, this would involve creation and setup of infrastructure for routing the logs. Each time we need a new log, the router infrastructure would be added/changed. 

Proposing a component that would allow retrieving logs directly using GCP [Cloud Logging API](https://cloud.google.com/logging/docs/reference/v2/rest). This would allow clients with lower log volumes to easily retrieve logs for specific services and resources. 

### Example configuration for the component

```
googlecloudlogging:
  collection_interval: 120s
  region: us-central1
  project_id: my-project-id
  service_account_key: "path/to/service_account.json"
  resources:
    - resource_type: "cloudfunctions"
      additionalFilters: 
        - name: "resource.labels.service_name"
          value: "service-name"
        - name: "resource.labels.location"
          value: "us-east-1"
      resource_names:
        - "projects/my-project-id1"
        - "projects/my-project-id2"
    - resource_type: "another-resource-type"
      resource_names:
        - "projects/my-project-id3"
        - "projects/my-project-id4"
``` 

### Telemetry data types supported

logs

### Is this a vendor-specific component?

- [X] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@abhishek-at-cloudwerx, @TylerHelmuth

### Sponsor (optional)

@dashpole

### Additional context

This proposal seeks community opinion on how useful/necessary the component is. We are open to do the development for this component. However, the component is not intended to be used at extremely high volumes - use of Log router and GCP Pub Sub is the right approach for that case.
