### ISSUE TITLE
[lokiexporter]: Allow resource level attributes to be added to loki labels 

### ISSUE THREAD

**Issue by eroteme** [open-telemetry/opentelemetry-collector-contrib#3405]
**Is your feature request related to a problem? Please describe.**
Currently the loki exporter is able to add logrecord attributes to loki labels. Resource attributes could also be added as labels to assist with filtering of loki data.

**Describe the solution you'd like**
Resources can be  taken from the ResourceLogs and their attributes added in a similar way to the logrecord attributes already being added. A separate config block could be added for resource attributes to provide which attributes should be added.

**Describe alternatives you've considered**
Not add resource attributes to loki labels but lose some important filtering I need in loki

**Additional context**
Already working on a potential solution for this and will add a PR soon

**Comment by eroteme** [comment]
Example config to specify the resource attributes for loki labels 

```
  loki:
    endpoint: "https://loki:3100/loki/api/v1/push"
    tenant_id: "example"
    labels:
      attributes:
        container.name: "container_name"
        k8s.cluster.name: "k8s_cluster_name"
        severity: "severity"
      resource: 
        resource.name:  "resource_name"
        severity: "severity"
```

Not sure in the example above which severity label should be used (from the resource or from the log record) and how we decide
