### ISSUE TITLE
Question about env variables in Windows Server

### ISSUE THREAD

**Issue by jonymaster** [open-telemetry/opentelemetry-collector-contrib#34060]
### Component(s)

extension/basicauth

### Describe the issue you're reporting

Hello, 

When using basicauth in a Windows Server, I'm trying to access to an Environment Variable set at system level. 

On Linux it should be:

```
basicauth/logs:
    client_auth:
      username: "MY_USER"
      password: ${env:MY_SECRET}
```

But on Windows it seems nothing works. Any advice?
