### ISSUE TITLE
Exclude Dimension Setting in Span Metrics Connector Does Not Apply to Non-Default Dimensions

### ISSUE THREAD

**Issue by EOjeah** [open-telemetry/opentelemetry-collector-contrib#34102]
### Component(s)

connector/spanmetrics

## Description
The `spanmetricsconnector` component in the OpenTelemetry Collector has a setting called `exclude_dimensions` that is intended to exclude specific dimensions from the metrics. This setting works correctly for the default dimensions, which are `service.name`, `span.name`, `span.kind`, and `status.code`. However, it does not work for dimensions that are added by process tags such as `host.name` by any processors before the `spanmetricsconnector`

## Steps to Reproduce
Send sample zipkin span to the otel collector traces pipeline with the span metrics connector and prometheus output for metrics
```json
[
    {
        "traceId": "30101010101",
        "id": "1",
        "kind": "SERVER",
        "name": "GET /api",
        "timestamp": 1697040000000000,
        "duration": 2000001,
        "localEndpoint": {
            "serviceName": "example"
        },
        "tags": {
            "http.route.name": "api.example.com",
            "host.name": "ec2-10.1.1.1.amazonaws.com"
        }
    }
]
```

## Expected Result
`host_name` is not part of the metric dimension
```
calls_total{service_name="example", span_kind="SPAN_KIND_SERVER", status_code="STATUS_CODE_UNSET"}
```

## Actual Result
`host_name` metric is included with the metric
```
calls_total{host_name="ec2-10.1.1.1.amazonaws.com", service_name="example", span_kind="SPAN_KIND_SERVER", status_code="STATUS_CODE_UNSET"}
```

### Collector version

v0.103.0

## Environment
Ubuntu 22.04.4 LTS 

### OpenTelemetry Collector configuration

```yaml
receivers:
  zipkin:

connectors:
  spanmetrics:
    exclude_dimensions: ['host.name']
    
exporters:
  prometheus:
service:
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [spanmetrics]
    metrics:
      receivers: [spanmetrics]
      exporters: [prometheus]
```
