### ISSUE TITLE
New component: Log deduplication processor

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector-contrib#34118]
### The purpose and use-cases of the new component

We're working to put together a log de-duplication processor at Honeycomb and wanted to get the temperature of the community for hosting such a component in the contrib repository.

### Example configuration for the component

```yaml
dedupe:
  // TTL is the time-to-live for each entry in the cache. Default is 30 seconds.
  ttl: 30s
  // MaxEntries is the maximum number of entries that can be stored in the cache. Default is 1000.
  max_entries: 1000
  // AttributeNames is the list of attributes to use as the key for deduplication.
  attribute_names: []
```

### Telemetry data types supported

logs

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@codeboten @MikeGoldsmith
