### ISSUE TITLE
[reciever/kafkametrics] Add support for topic configurations and assigning cluster alias

### ISSUE THREAD

**Issue by RutvikS-crest** [open-telemetry/opentelemetry-collector-contrib#34148]
### Component(s)

receiver/kafkametrics

### Is your feature request related to a problem? Please describe.

kafkametrics reciever only supports one topic metric.
- `kafka.topic.partitions`

We want to monitor multiple kafka clusters, It will be easier if there is an additional metric dimension for each cluster.  

We want to monitor kafka's topic configurations like replication-factor, min-insync-relicas, log-retention settings etc. These metrics will help us monitor and standardise topic configurations across all of our clusters.

### Describe the solution you'd like

I propose to support following metrics that can easily be fetched using sarama client.
- `kafka.topic.replication_factor`
- `kafka.topic.log_retention_ms`
- `kafka.topic.log_retention_bytes`
- `kafka.topic.min_insync_replicas`

Add an optional configuration field to assign cluster alias name. 
```
receivers:
  kafkametrics:
    protocol_version: 2.0.0
    cluster_alias: kafka-ecom
    scrapers:
      - brokers
      - topics
      - consumers
```
