### ISSUE TITLE
set always uses UTC

### ISSUE THREAD

**Issue by agardnerIT** [open-telemetry/opentelemetry-collector-contrib#34161]
### Component(s)

processor/transform

## Description

Opening at the request of @TylerHelmuth as [per this Slack thread](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1721173952203439).

I'm using `set(time, Now())` in the transform processor but it's setting time to UTC (`+0000`) while my system time is `+1000`

## Expected Result

The `transform` processor / OTTL should either:

1. Respect system time
2. Have the ability to set a timezone eg. `set(time, Now().Timezone("AEST")`

### Collector version

v0.103.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
...
processors:
  transform/add_timestamp:
    log_statements:
      - context: log
        statements:
          - set(observed_time, Now())
          - set(time, Now())
...
```
