### ISSUE TITLE
Memory leak problem with Opentelemetry Collector Using KafkaReceiver

### ISSUE THREAD

**Issue by Dennis8274** [open-telemetry/opentelemetry-collector-contrib#34163]
### Component(s)

receiver/kafka

## Description
a memory-leak found in my process,which fetch msg from kafka using sarama,a kafka golang sdk
![image](https://github.com/user-attachments/assets/9d5f8cd8-351c-4a47-afd2-b9bde0f0c6f0)
<img width="1234" alt="image" src="https://github.com/user-attachments/assets/b7dd5181-88fb-4579-aaa9-08a1d7ac3b9c">
<img width="1452" alt="image" src="https://github.com/user-attachments/assets/96be2507-5048-4bf9-8318-d8db118cb2aa">

### Collector version

v0.98.0

## Environment
go version go1.20.13 darwin/amd64

### OpenTelemetry Collector configuration

```yaml
extensions:
  zpages:
  pprof:

receivers:
  kafka:
    brokers: xxx
    topic: zzz
    encoding:         json
    client_id:        khaos-collector
    group_id:         khaos-collector
    protocol_version: 1.1.1
    initial_offset:   latest
    metadata:
      retry:
        max:     10
        backoff: 3s
    autocommit:
      enable:   true
      interval: 10

processors:
  memory_limiter:
    check_interval: 10s
    limit_percentage: 80
    spike_limit_percentage: 20

exporters:
  nop:

service:
  telemetry:
    logs:
      level: INFO
      encoding: console
      sampling:
        enabled: false
    metrics:
      address: localhost:8888
  extensions: [zpages,pprof]
  pipeline:
    logs:
      receivers: [ kafka ]
      processors: [ memory_limiter ]
      exporters: [ nop ]
```
