### ISSUE TITLE
Send httpcheck to elastic

### ISSUE THREAD

**Issue by Breee** [open-telemetry/opentelemetry-collector-contrib#34185]
### Component(s)

cmd/otelcontribcol

## Description

I'm trying to get httpcheck metrics into elastic

## Expected Result

Metrics in Elastic APM

## Actual Result

No metrics

Any idea why?

### Collector version

0.103.0

## Environment
docker

### OpenTelemetry Collector configuration

```yaml
receivers: 
  httpcheck:
    targets:
      - endpoint: https://example.com
        method: GET
    collection_interval: 60s

processors: 
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

exporters:
  debug:
    verbosity: detailed 
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "${env:ELASTIC_APM_SERVER_ENDPOINT}"  
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer ${env:ELASTIC_APM_SECRET_TOKEN}"  

service:
  pipelines:
    metrics:
      receivers: [httpcheck]
      exporters: [debug, otlp/elastic]
```
