### ISSUE TITLE
New component: `otlpjson` connector

### ISSUE THREAD

**Issue by ChrsMark** [open-telemetry/opentelemetry-collector-contrib#34208]
### The purpose and use-cases of the new component

This new connector will be used in order to extract `otlpjson` from incoming Logs.
The connector will be responsible for unpacking valid otlp json from Log records
and specifically the `Body` field (this can be configurable).

This component will serve similarly to the [`otlpjsonfilereceiver`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/otlpjsonfilereceiver) but in a later stage
in the pipeline. This is particularly useful when the `otlpjson` cannot be consumed directly
by the aforementioned receiver.
An example use-case can be found at https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33846.

### Example configuration for the component

Initially the configuration can be quite basic like in [`otlpjsonfilereceiver`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/otlpjsonfilereceiver) but we can expand later according to the needs.

```yaml
connectors:
  otlpjson:
```

The connector can be used in a pipeline to extract Logs, Metrics and Traces like this:

```yaml
receivers:
  filelog:
    include:
      - /var/log/foo.log

exporters:
  debug:

connectors:
  otlpjson:

service:
  pipelines:
    logs/raw:
      receivers: [filelog]
      exporters: [otlpjson]
    metrics/otlp:
      receivers: [otlpjson]
      exporters: [debug]
    logs/otlp:
      receivers: [otlpjson]
      exporters: [debug]
    traces/otlp:
      receivers: [otlpjson]
      exporters: [debug]
```

### Telemetry data types supported

1) Logs to Logs
2) Logs to Metrics
3) Logs to Traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@djaglowski, @ChrsMark

### Sponsor (optional)

@djaglowski (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33846#issuecomment-2228738273)

### Additional context

1) Filing this issue after we shortly chatted about it with @zeitlinger on Slack.
2) A very basic PoC illustrating the idea can be found at https://github.com/ChrsMark/otlpjsonconnector.
