### ISSUE TITLE
Ability to define multiple filelog receivers OR apply different tags based on log file

### ISSUE THREAD

**Issue by jamesqo** [open-telemetry/opentelemetry-collector-contrib#34256]
### Component(s)

cmd/otelcontribcol

### Is your feature request related to a problem? Please describe.

I am trying to set up the OpenTelemetry collector to send logs to Datadog using the Datadog exporter. Here is what the relevant portion of my configuration file looks like:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
  filelog:
    include:
        - /data/portal-cron/logs/validation_utils_py3.json
        - /data/portal-cron/logs/cvr-fetcher.log
    start_at: beginning
    attributes:
      ddtags: host:pipelines3.cbioportal.aws.mskcc.org
```

This will cause all events sent to Datadog to be tagged with `host:pipelines3.cbioportal.aws.mskcc.org`. But let's say I only want to apply this tag to events read from `cvr-fetcher.log`. I don't see an option to do this-- either by defining multiple `filelog` receivers, or perhaps there is some setting I'm missing? I have looked at the receiver schema [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/filelogreceiver/README.md), but I could not find anything.

### Describe the solution you'd like

Ability to set up multiple filelog receivers ([this fork](https://help.sumologic.com/docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs/) seems to have that ability, Ctrl+F search "multiple filelog receivers"), or apply `ddtags` only to specific log files

**Comment by djaglowski** [comment]
You can define multiples of any component by adding `/name` to the component type:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
  filelog:
    include:
        - /data/portal-cron/logs/validation_utils_py3.json
    start_at: beginning
    attributes:
      ddtags: host:pipelines3.cbioportal.aws.mskcc.org
  filelog/2:
    include:
        - /data/portal-cron/logs/cvr-fetcher.log
    start_at: beginning
```

Then just refer to each on in your pipelines:

```yaml
service:
  pipelines:
    logs:
      receivers: [ otlp, filelog, filelog/2 ]
      processors: ...
      exporters: ...
```
