### ISSUE TITLE
Grouped metric type "counter" silently dropped

### ISSUE THREAD

**Issue by ole-kaas** [open-telemetry/opentelemetry-collector-contrib#34263]
### Component(s)

receiver/prometheus

## Description
We have deployed Target Allocator to discover pod/service-monitors instead of Promtheus Operator. The metrics endpoints are discoverered, but some of the  metrics are missing. It seems that all grouped metrics of type "counter" are silently dropped, while grouped metrics of type "gauge" works as expected together with all the other metrics.

Example of dropped metric:
```
# HELP cnpg_pg_stat_database_blks_read Number of disk blocks read in this database
# TYPE cnpg_pg_stat_database_blks_read counter
cnpg_pg_stat_database_blks_read{datname=""} 122
cnpg_pg_stat_database_blks_read{datname="my-database"} 426
cnpg_pg_stat_database_blks_read{datname="postgres"} 359
cnpg_pg_stat_database_blks_read{datname="template0"} 0
cnpg_pg_stat_database_blks_read{datname="template1"} 1379
```

Example from same endpoint that works as expected:

```
# HELP cnpg_pg_stat_replication_flush_diff_bytes Difference in bytes from the last write-ahead log location flushed to disk by this standby server
# TYPE cnpg_pg_stat_replication_flush_diff_bytes gauge
cnpg_pg_stat_replication_flush_diff_bytes{application_name="my-cnpg-cluster-2",client_addr="10.244.0.99/32",client_port="53160",usename="streaming_replica"} 0
cnpg_pg_stat_replication_flush_diff_bytes{application_name="my-cnpg-cluster-3",client_addr="10.244.3.70/32",client_port="47804",usename="streaming_replica"} 0
```

## Steps to Reproduce
We are using cloudnative-pg operator to deploy psql. Example metrics are from db clusters deplyed by the operator
https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg/0.21.4
## Expected Result
That the metrics would be available OR some mention in the log that the metrics for some reason could not be scraped/processed.
## Actual Result
Metric missing and no mention in the log

### Collector version

0.103.0

## Environment
Azure Kubernetes 1.29.5

### OpenTelemetry Collector configuration

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: targetallocator
  labels:
    metrics-scraper: opentelemetry
spec:
  mode: statefulset
  observability:
    metrics:
      enableMetrics: true
  targetAllocator:
    enabled: true
    serviceAccount: targetallocator-collector
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        matchLabels:
          metrics-scraper: opentelemetry
      podMonitorSelector:
        matchLabels:
          metrics-scraper: opentelemetry
  replicas: 1
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "opentelemetry-collector-metric-scraper"
              scrape_interval: 10s
              static_configs:
                - targets: ["0.0.0.0:8888"]

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      loadbalancing:
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          dns:
            hostname: opentelemetry-collector-headless.opentelemetry.svc.cluster.local

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch]
          exporters: [loadbalancing]
```

**Comment by dashpole** [comment]
Can you paste the full metric output from the endpoint?  We can use that to run it as a unit test.

Can you enable debug logging as well to see if you get any additional details?  Should be:

```yaml
service:
    telemetry:
        logs:
            level: DEBUG
```
