### ISSUE TITLE
[pkg/stanza] Container parser not playing well with downstream operator that experiences an error

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#34295]
### Component(s)

pkg/stanza

## Description
I'm seeing strange behavior when I use the container parser chained with a regex parser that sometimes fails (because the regex is not always present in the log). When the `regex_parser` fails, logs collection stops.  I believe this is because the container parser currently breaks out of the `crioConsumer` goroutine if the `Write` returns an error:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d8085724ce153870078e21004f8e68d25175768e/pkg/stanza/operator/parser/container/parser.go#L156-L169

## Steps to Reproduce

Use a filelogreceiver config such as 

```yaml
filelog:
        exclude: []
        include:
        - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        operators:
        - id: container-parser
          max_log_size: 102400
          type: container
        - type: regex_parser
          regexp: '\slevel=(?P<severity_field>\w+)\s'
          on_error: send_quiet
          severity:
            parse_from: attributes.severity_field
        retry_on_failure:
          enabled: true
        start_at: end
```

Send through a log that does not match the regex parser and then send through a log that does match.

## Expected Result

Both logs are sent, with the second having a severity set.

## Actual Result

Neither logs are sent.

### Collector version

v0.105.0
