### ISSUE TITLE
Azure Service Logs streaming issue

### ISSUE THREAD

**Issue by saiganeshkABI** [open-telemetry/opentelemetry-collector-contrib#34307]
### Component(s)

receiver/azureeventhub

## Description
The Azure service logs are unable to forward via OTel Collector.
## Steps to Reproduce
Add the receiver component in builder config file
Run the builder
Configure Azure Event Hub receiver
Restart the otel collector
_config.yaml_
## Expected Result
The logs should be streamed to the exporter
## Actual Result
Getting issue while running the Otel Collector

### Collector version

0.104.0

## Environment
OS: Windows
Compiler(if manually compiled): go 1.22.1

### OpenTelemetry Collector configuration

```yaml
receivers:
  azureeventhub:
    connection: Endpoint=$CONNECTION_STRING
exporters:
  datadog:
    api:
      key: "$API"
      site: "$SITE"
service:
  pipelines:
    logs:
      receivers: [otlp,azureeventhub]
      exporters: [datadog]
```

### Log output

```shell
2024/07/30 08:15:47 collector server run finished with error: cannot start pipelines: *Error{Condition: amqp:link:stolen, Description: At least one receiver for the endpoint is created with epoch of '0', and so non-epoch receiver is not allowed. Either reconnect with a higher epoch, or make sure all epoch receivers are closed or disconnected. TrackingId:7e4c4ef7-c44e-4191-8b48-e761833ae1e2_B30, SystemTracker:datadogsecurity:eventhub:insights-activity-logs~8191, Timestamp:2024-07-30T08:15:47 Reference:bd89eaf1-314a-45f1-be80-63e298c7d01c, TrackingId:ee451c2a-f6d5-4d9e-acd8-a296660db2b5_B30, SystemTracker:datadogsecurity:eventhub:insights-activity-logs~8191|$default, Timestamp:2024-07-30T08:15:47 TrackingId:082ce81bf786443594531b6dfad80453_G1, SystemTracker:gateway5, Timestamp:2024-07-30T08:15:47, Info: map[]}
```
