### ISSUE TITLE
vCenter failed to receive VMs metrics panic runtime error invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shaharSirotkin** [open-telemetry/opentelemetry-collector-contrib#34343]
### Component(s)

vCenter receiver

## Description
I tried to config a vcenterreciver and got a stack trace of runtime error saying:
panic: runtime error: invalid memory address or nil pointer dereference.

## Steps to Reproduce
Install otel-collector-contrib on your PC and use a config.yaml to receive metrics from vCenter in version 7.0.3   

## Expected Result
normal metrics of vcenter

## Actual Result
panic: runtime error: invalid memory address or nil pointer dereference.

github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).buildVMMetrics()
.....

### Collector version

0.105.0

## Environment
Windows 10 Enterprise

### OpenTelemetry Collector configuration

```yaml
receivers:
    vecenter/vc1:
        endpoint: https://dev-vc1.my.domain
        username: vm_mgr_svc
        password: **************
        collection_interval: 1m
        tls:
            insecure: false
            insecure_skip_verify: true

exporters:
     file/myfile:
         path: metrics

service:
     pipelines:
          metrics:
               receivers:
                    - vcenter/vc1
               exporters:
                   - file/myfile
      telemetry:
          metrics:
                address: 0.0.0.0:8993
```

### Log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference.

github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).buildVMMetrics()
.....
```
