### ISSUE TITLE
supervisor  does not consistently use property "storage.directory" to store  effective yaml, agent.log

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#34341]
### Component(s)

cmd/opampsupervisor

### What happened?

Observations from testing
 
config file changes
YAML
```
storage:
  directory: /home/root/myfolder/super_check
``` 
contents of /home/root/myfolder/super_check after running supervisor
```
root@:~/super# ls /home/root/myfolder/super_check
persistent_state.yaml
``` 
 
Contents of directory from where supervisor was run
```
root@:~/super# ls
agent.log         effective.yaml    otelcol supervisor     supervisor.yaml
``` 
 
storage: what we give applies for persistent_state.yaml file not effective yaml file.
effective.yaml file is still created in same directory from where supervisor was run

### Collector version

master

**Comment by cforce** [comment]
After a first test it look like "effective.yaml" file is still in same directory as supervisor and not in the configured one. 
The change shall cover all files which are created  to be  located only in the configured folder, shouldn't' it?
@BinaryFissionGames

**Comment by BinaryFissionGames** [comment]
> After a first test it look like "effective.yaml" file is still in same directory as supervisor and not in the configured one. The change shall cover all files which are created to be located only in the configured folder, shouldn't' it? @BinaryFissionGames

It should cover all files, yeah.

I've given it another test off main (commit 7f79eba285), and I'm seeing `effective.yaml` end up in my configured storage directory.

Can you confirm the commit you've built the supervisor off of? If you're still seeing the issue, it'd also be helpful to get a config for the supervisor that reproduces the issue. I'm also curious if this is happening on startup or on reconfigure.

**Comment by cforce** [comment]
based on tagged src i used git clone --branch v0.106.1 --depth 1 https://github.com/open-telemetry/opentelemetry-collector-contrib.git
--
```
server:
  endpoint: ws://localhost:9082/

capabilities:
  reports_effective_config: true
  reports_own_metrics: true
  reports_health: true
  accepts_remote_config: true
  reports_remote_config: true

storage:
  directory: ./yaml

agent:
  executable: ./otelcol
```
