### ISSUE TITLE
[exporter/datadog] incorrect `service.name` transformation

### ISSUE THREAD

**Issue by sudomateo** [open-telemetry/opentelemetry-collector-contrib#34366]
### Component(s)

exporter/datadog

### What happened?

I wrote up everything in https://github.com/DataDog/opentelemetry-mapping-go/issues/356 since that's where the issue actually lies but Datadog Support requested that I open an issue on this repository instead. I'm going out of office starting tomorrow so I wanted to get this in beforehand. I'll come back and transfer the content over nicely to this issue when I'm back.

### Collector version

latest

### Environment information

N/A

### OpenTelemetry Collector configuration

```yaml
processors:
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["service.name"], "sudomateo")
          - set(attributes["ddtags"], "source:sudomateo")
```

### Log output

```shell
N/A
```

### Additional context

N/A
