### ISSUE TITLE
[exporter/datadog] support setting the source field

### ISSUE THREAD

**Issue by sudomateo** [open-telemetry/opentelemetry-collector-contrib#34367]
### Component(s)

exporter/datadog

### Is your feature request related to a problem? Please describe.

I wrote up everything in https://github.com/DataDog/opentelemetry-mapping-go/issues/355 since that's where the feature would need to be implemented but Datadog Support requested that I open an issue on this repository instead. I'm going out of office starting tomorrow so I wanted to get this in beforehand. I'll come back and transfer the content over nicely to this issue when I'm back.

### Describe the solution you'd like

The following configuration should correctly set the source field within Datadog.

```yaml
processors:
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["ddtags"], "source:sudomateo")
```

### Describe alternatives you've considered

N/A

### Additional context

N/A
