### ISSUE TITLE
New component:TCP Receiver

### ISSUE THREAD

**Issue by yanfeng1992** [open-telemetry/opentelemetry-collector-contrib#34414]
### The purpose and use-cases of the new component

To monitor the availability and performance of TCP endpoints.
Use case: TCP network detection plug-in, usually used to monitor whether a TCP port on the local machine is listening, or whether a remote port can be connected

### Example configuration for the component

```
receivers:
  tcpcheck:
    endpoint: 10.255.88.146:32443 # required
    collection_interval: 60s
```

### Telemetry data types supported

```
attributes:
  error.message:
    description: Error message recorded during check
    type: string
  tcp.endpoint:
    description: Full TCO endpoint
    type: string

metrics:
  tcpcheck.status:
    description: 1 if the TCP client successfully connected, otherwise 0.
    enabled: true
    sum:
      value_type: int
      aggregation_temporality: cumulative
      monotonic: false
    unit: "1"
    attributes: [tcp.endpoint]
  tcpcheck.duration:
    description: Measures the duration of TCP connection.
    enabled: true
    gauge:
      value_type: int
    unit: ms
    attributes: [tcp.endpoint]
  tcpcheck.error:
    description: Records errors occurring during TCP check.
    enabled: true
    sum:
      value_type: int
      aggregation_temporality: cumulative
      monotonic: false
    unit: "{error}"
    attributes: [error.message]
```

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

yanfeng1992

### Sponsor (optional)

@atoulme

**Comment by yanfeng1992** [comment]
If you are interested in this, please become a sponsor. Thank you. @codeboten @mx-psi

**Comment by yanfeng1992** [comment]
Invitation to become a sponsor, is anyone interested in this?
@songy23 @mwear @dmitryax

**Comment by atoulme** [comment]
```
tcpcheck.error:
    description: Records errors occurring during TCP check.
    enabled: true
    sum:
      value_type: int
      aggregation_temporality: cumulative
      monotonic: false
     ```
Shouldn't `monotonic` be true?
