### ISSUE TITLE
unknown type: "tail_sampling"

### ISSUE THREAD

**Issue by ankurops** [open-telemetry/opentelemetry-collector-contrib#34418]
### Component(s)

processor/tailsampling

## Description
I am attempting to implement a tail sampling policy to trace only error and latency-based spans. However, I am encountering the following error while trying to implement the same.

`Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

Error decoding 'processors': unknown type: "tail_sampling" for id: "tail_sampling" (valid values: [filter batch memory_limiter attributes resource span probabilistic_sampler])`

## Steps to Reproduce
docker image : otel/opentelemetry-collector:0.106.1

### Collector version

0.106.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4319"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'sample'
          scrape_interval: 15s
          metrics_path: "/actuator/prometheus"
          static_configs:
            - targets: ['192.168.1.8:8080']
              labels:
                application : 'sample'
                owner : 'ankur'
                source : 'otlp'

processors:
  memory_limiter:
    check_interval: 15s
    limit_percentage: 60
    spike_limit_percentage: 20
  tail_sampling:
    decision_wait: 10s 
    num_traces: 100
    expected_new_traces_per_sec: 100
    policies:
      - name: status-code-policy
        type: status_code
        status_code:
          status_codes: [ERROR]
    # policies:
    #   [          
    #     {
    #       name: errors-policy,
    #       type: status_code,
    #       status_code: {status_codes: [ERROR]}
    #     },
    #     {
    #       name: randomized-policy,
    #       type: probabilistic,
    #       probabilistic: {sampling_percentage: 25}
    #     },
    #     {
    #       name: latency-based-policy,
    #       type: latency,
    #       latency: {threshold_ms: 5000, upper_threshold_ms: 10000}
    #     }
    #   ]
  batch:
    send_batch_size: 512
    timeout: 5s
  filter:
    error_mode: ignore
    traces:
      span:
        - attributes["http.route"] == "/actuator/health"
        - attributes["http.route"] == "/actuator/prometheus"
     
exporters:
  otlp:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://prometheus:9091/api/v1/write"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter,tail_sampling,batch,filter]
      exporters: [otlp]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
