### ISSUE TITLE
[processor/resourcedetectionprocessor] Add a more general and flexible detector

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-collector-contrib#34556]
### Component(s)

processor/resourcedetection

### Is your feature request related to a problem? Please describe.

Currently `resourcedetectionprocessor` has built-in aws, azure, consul, docker, k8snode, system and so on rich out-of-the-box detection. Those detectors all rely on third-party components, and adding new detectors requires the user to add an implementation of the new detector in the otel-col-contrib library. Therefore, a more flexible approach is needed.

### Describe the solution you'd like

This proposal is intended to refer to a more flexible, general-purpose approach to detection, similar to the [prometheus HTTP SD config](https://prometheus.io/docs/prometheus/latest/http_sd/), where users simply implement a custom interface and return it in a specified format.

This feature will be on the `processor/resourcedetectionprocessor/internal/http` directory, and the following configuration items are provided:

```yaml
processors:
  resourcedetection/http:
    detectors: [http]
    http:
      endpoint: http://my-http-resourcedetection:8080 # external http url
      interval: 1h # the interval of requests
      headers:
        my-token: xxxxxxxxxxx
        tanent: one
      .......more options......
```

the response of the http should be returned as json(contains real attributes and their values) , Examples:

```json
[
    {
        "datacenter": "idc01",
        "enabled": true
    },
    {
        "zone": "zone01",
        "enabled": false
    }
]
```

Based on the above results, the `http detector` will append or override `datacenter=idc01` in the resource value in telemetry data.
