### ISSUE TITLE
opentelementry receiver log from file and export to opensearch 

### ISSUE THREAD

**Issue by NamanGajjar26** [open-telemetry/opentelemetry-collector-contrib#34566]
### Component(s)

exporter/opensearch

## Description
hi there 
i am try to send receivers log file from this path (/app/log/naman/namanlog.log) and export this log to opensearch and make new index (demo1-index) get this log opensearch

## Steps to Reproduce
         ` config:
            receivers:    
              filelog:
                include: ["/app/log/naman/namanlog.log"] 
                start_at: beginning      
               
            processors:
              batch:
                timeout: 60s
                send_batch_max_size: 10000
          
            extensions:
              basicauth/client:
                client_auth:
                  username: admin
                  password: TadhakDev01
              health_check:
                endpoint: ${env:MY_POD_IP}:13133
          
            exporters: 
              logging:
                loglevel: debug  
              opensearch:
                logs_index: otel-index-opensearch
                http:
                  endpoint: http://opensearch-cluster-master-headless.myopensearch.svc.cluster.local:9200
                  auth:
                    authenticator: basicauth/client
                  tls:
                   insecure: true
          
            service:    
              extensions:
                - basicauth/client
                - health_check
              pipelines:           
                logs:
                  receivers: [filelog]        
                  exporters: [opensearch]`
## Expected Result
i want to get this log message in opensearch using opentelemetry
{"@timestamp":"2024-08-09T13:33:12.406Z","flb-key":"kube.custommvc.app.log.naman.namanlog.log","Timestamp":"2024-08-09T13:33:12.1972500+00:00","Level":"Error","MessageTemplate":"time_error_new2","TraceId":"b6475c2b94d380210de53197e5c482e8","SpanId":"53a55dc04afce4b5","Properties":{"Method":"errorlog","IndiaTime":"2024-08-09T19:03:12.1972334","UtcTimestamp":"2024-08-09T13:33:12.1972475Z","Timestamp":"2024-08-09T13:33:12.1972429+00:00"}}
## Actual Result
there are show error in opentelemetry error 
error reader/reader.go:140 process: %w {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/app/log/naman/namanlog.log", "error": "failed to process the docker log: move: field log does not exist"}

![Screenshot from 2024-08-09 19-16-29](https://github.com/user-attachments/assets/8cb2f8e8-ae9b-407b-bafe-3aa04e350be3)

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:    
              filelog:
                include: ["/app/log/naman/namanlog.log"] 
                start_at: beginning      
               
            processors:
              batch:
                timeout: 60s
                send_batch_max_size: 10000
          
            extensions:
              basicauth/client:
                client_auth:
                  username: admin
                  password: TadhakDev01
              health_check:
                endpoint: ${env:MY_POD_IP}:13133
          
            exporters: 
              logging:
                loglevel: debug  
              opensearch:
                logs_index: otel-index-opensearch
                http:
                  endpoint: http://opensearch-cluster-master-headless.myopensearch.svc.cluster.local:9200
                  auth:
                    authenticator: basicauth/client
                  tls:
                   insecure: true          
            service:    
              extensions:
                - basicauth/client
                - health_check
              pipelines:           
                logs:
                  receivers: [filelog]        
                  exporters: [opensearch]
```

### Log output

```shell
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/internal/reader/reader.go:140
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
 github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/file.go:160
2024-08-09T13:36:29.945Z error reader/reader.go:140 process: %w {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/app/log/naman/namanlog.log", "error": "failed to process the docker log: move: field log does not exist"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).ReadToEnd
 github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/internal/reader/reader.go:140
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
 github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/file.go:160
2024-08-09T13:36:29.945Z error reader/reader.go:140 process: %w {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/app/log/naman/namanlog.log", "error": "failed to process the docker log: move: field log does not exist"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).ReadToEnd
 github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/internal/reader/reader.go:140
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
 github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/file.go:160
2024-08-09T13:36:29.945Z error reader/reader.go:140 process: %w {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/app/log/naman/namanlog.log", "error": "failed to process the docker log: move: field log does not exist"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).ReadToEnd
 github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/internal/reader/reader.go:140
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
 github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/file.go:160
2024-08-09T13:36:29.945Z error reader/reader.go:140 process: %w {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer", "path": "/app/log/naman/namanlog.log", "error": "failed to process the docker log: move: field log does not exist"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).ReadToEnd
 github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/internal/reader/reader.go:140
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
 github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.106.1/fileconsumer/file.go:160
```
