### ISSUE TITLE
[opampsupervisor] don't merge multiple received agent config files

### ISSUE THREAD

**Issue by Asarew** [open-telemetry/opentelemetry-collector-contrib#34608]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

Right now the supervisor merges the received config files meaning that pipeline names need to be unique in across all files the config-map. if this is not done the supervisor silently "deletes" config pipelines and no errors are thrown anywhere and proper execution can (and will) be assumed by the collector and the end-user.

```go
const nop1Config = `
receivers:
  nop:
exporters:
  nop:

service:
  pipelines:
    metrics/2:
      receivers: [nop, nop]
      exporters: [nop]
`

const nop2Config = `
receivers:
  nop:
exporters:
  nop:

service:
  pipelines:
    traces/3:
      receivers: [nop]
      exporters: [nop]
    metrics/2:
      receivers: [nop]
      exporters: [nop]
`

agentConfig := &protobufs.AgentConfigMap{
    ConfigMap: map[string]*protobufs.AgentConfigFile{
		"file1.yaml": {
			ContentType: "text/yaml",
			Body:        []byte(nop1Config),
		},
		"file2.yaml": {
			ContentType: "text/yaml",
			Body:        []byte(nop2Config),
		},
	},
}
```
Will result in this `effective.yaml`
```yaml
exporters:
    nop: null
extensions:
    health_check:
        endpoint: localhost:45843
    opamp:
        instance_uid: 01914658-9d6d-7f2f-8f98-be5e80c1ed3e
        ppid: 1
        ppid_poll_interval: 5s
        server:
            ws:
                endpoint: ws://localhost:35835/v1/opamp
                tls:
                    insecure: true
receivers:
    nop: null
service:
    extensions:
        - health_check
        - opamp
    pipelines:
        metrics/2:
            exporters:
                - nop
            receivers:
                - nop
                - nop
        traces/3:
            exporters:
                - nop
            receivers:
                - nop
    telemetry:
        logs:
            encoding: json
        resource:
            foo: bar
            host.arch: arm64
            host.name: b6c93dcf7b8c
            os.type: linux
            service.instance.id: 01914658-9d6d-7f2f-8f98-be5e80c1ed3e
            service.name: otelcol-custom
            service.version: 1.0.0


```

### Describe the solution you'd like

Save each received AgentConfigFile as a seperate file and give each to the collector --config cli param as it support multiple files.
