### ISSUE TITLE
[connector/exceptionsconnector] the dimension configuration does not support the resource attributes context

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-collector-contrib#34603]
### Component(s)

connector/exceptions

## Description

Configure additional attribute in dimensions as described in the documentation, such as adding `k8s.namespace.name`, and find that the resulting `metric` or `logs` do not record `k8s.namespace.name`:

```yaml
  exceptions/traces:
    dimensions:
      - name: k8s.namespace.name # add additional dimension 👈 
      - name: exception.type
      - name: exception.message
      - name: exception.stacktrace
      # span name
      - name: name
```

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d46a7c30553de71eaea0eeeb4927d0644ed39140/connector/exceptionsconnector/connector_logs.go#L71

I think we need should pass a resource attribute, similar to spanmetricconnector

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d46a7c30553de71eaea0eeeb4927d0644ed39140/connector/spanmetricsconnector/connector.go#L524

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
