### ISSUE TITLE
[exporter/googlecloud] OpAMP extension panics if googlecloud exporter is configured

### ISSUE THREAD

**Issue by BinaryFissionGames** [open-telemetry/opentelemetry-collector-contrib#34628]
### Component(s)

exporter/googlecloud

## Description

If the google cloud exporter is configured, the OpAMP extension may panic when it tries to compose the effective config.

```
panic: cannot marshal type: func() []option.ClientOption [recovered]
	panic: cannot marshal type: func() []option.ClientOption
```

The issue is that the functional options in the config struct cannot be marshalled, so the yaml marshal panics. To fix this, we'll need to put `mapstructure:"-"` tags on the functional arguments in the googlecloud exporter config structs.

I also think the opamp extension could probably handle this situation more gracefully, by at the very least catching the panic.

### Collector version

v0.106.1

**Comment by JaredTan95** [comment]
Can you post a yaml configuration with minimal produce this issue?

**Comment by BinaryFissionGames** [comment]
Thanks @dashpole! I think it's not just this option, but basically anything that can't be marshalled by the yaml package that will end up causing problems.

For reference, here's a small config that exhibits the issue (you do not need an OpAMP server running to reproduce):
```yaml
receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      load:

exporters:
  googlecloud:
    project: "${GCP_PROJECT}"

extensions:
  opamp:
    capabilities:
      reports_effective_config: true
    server:
      ws:
        endpoint: "ws://localhost:1111/v1/opamp"
        tls:
          insecure: true

service:
  extensions: [opamp]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [googlecloud]
```
