### ISSUE TITLE
Update context dynamically from attributes

### ISSUE THREAD

**Issue by jriguera** [open-telemetry/opentelemetry-collector-contrib#34649]
### Is your feature request related to a problem? Please describe.

We would need to have a way to define tenants from attributes. The `headerssetterextension` can automatically set tenants (or other headers) from the context, but there is not way to modify/update the context.  See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27901 for more details.

### Describe the solution you'd like

We are not sure about the solution. Potential solutions are:

* Create a dedicated component which is able to modify the context.
* Extend `groupbyattrprocessor` (or other processor) to group resources with a new context.
* Extend the OTTL to include a new function.

The problem is the context it needs to be changed is the connection context, "one level up" of the resource context.

### Describe alternatives you've considered

Right now we are [using a custom processor to overcome this limitation](https://github.com/springernature/o11y-otel-contextprocessor/tree/main/otelcol-dev/contextprocessor). This processor was not developed to be committed to Otel repos, it started as a PoC and now we are using it internally. If agreed, we are happy to integrated in Otel Contrib.

**Comment by jriguera** [comment]
Just my 2 cents.

I do not think that is possible make a new OTTL function (for the `transformprocessor`) because it will need to create a new Context and emit (or somehow batch) the telemetry being currently processed. See this piece of code (from [here](https://github.com/springernature/o11y-otel-contextprocessor/blob/542b2feba23cb23a687eed82200ea94f08bc8210/otelcol-dev/contextprocessor/metrics.go#L42-L49)):

```
        rms := md.ResourceMetrics()
        for i := 0; i < rms.Len() && err == nil; i++ {
                rm := rms.At(i)
                attrs := rm.Resource().Attributes()
                newCtx := ctxt.actionsRunner.Apply(ctx, attrs)
                newMd := pmetric.NewMetrics()
                rm.CopyTo(newMd.ResourceMetrics().AppendEmpty())
                err = ctxt.nextConsumer.ConsumeMetrics(newCtx, newMd)
```

I think the best way is having a dedicated processor, which makes people aware of its purpose with a clear documentation and use cases (dealing with the Context).  Extending the `groupbyattrprocessor` would be another option, but I will require extra configuration parameters to manage Context.

Time ago I discussed this topic with @jpkrohling

**Comment by newly12** [comment]
+1 for this need, we faced similar situation where we need to 
1. extract attributes and set them in context, which will be honored by downstream otel collector's batch processor 
3. copy attributes and set them in context, which will be used by downstream otel collector's batch processor to group data by certain attributes k/vs for other purpose

**Comment by atoulme** [comment]
Please consider attending a SIG meeting to discuss this.

**Comment by LilWatson** [comment]
+1 I'm having the same problem currently.

Is there anything against integrating https://github.com/springernature/o11y-otel-contextprocessor/tree/main/otelcol-dev/contextprocessor to contrib?

**Comment by jriguera** [comment]
I have updated the example with a similar configuration we are using in production as a gateway role.

You can always create your own distribution of the otelcol binary with this processor.

**Comment by Reyarc** [comment]
We are running Grafana Mimir too and have the same issue with the needs of a dynamic header value (x-scope-orgid). 
Our receiver would be kafka FYI.

Is this proposition scheduled to merge on the contrib repo ? I would be glad to hear it, since we are going to fork and use it.

**Comment by jriguera** [comment]
@Reyarc  not yet, the implementation is quite opinionated, I think it should be part of another processor.

**Comment by abh** [comment]
@open-telemetry/collector-contrib-triagers

I believe this is still relevant.

**Comment by zorek187** [comment]
Still relevant

**Comment by sathieu** [comment]
> [@Reyarc](https://github.com/Reyarc) not yet, the implementation is quite opinionated, I think it should be part of another processor.

@jriguera Could you give more info on why [contextprocessor](https://github.com/springernature/o11y-otel-contextprocessor/tree/main/otelcol-dev/contextprocessor) is opinionated, and what can be done to ease it's integration in otelcol-contrib?

**Comment by jriguera** [comment]
I think it is opinionated because this is the only processor which is not about processing data, but about moving some data to the context of the (HTTP) connection. In order to do that, it needs to iterate on the resource attributes (for example, for [metrics](https://github.com/springernature/o11y-otel-contextprocessor/blob/37ba6644713a1e3b0836e00b368631af3f729b83/otelcol-dev/contextprocessor/metrics.go#L43-L49))

```
	rms := md.ResourceMetrics()
	for i := 0; i < rms.Len() && err == nil; i++ {
		rm := rms.At(i)
		attrs := rm.Resource().Attributes()
		newCtx := ctxt.actionsRunner.Apply(ctx, attrs)
		newMd := pmetric.NewMetrics()
		rm.CopyTo(newMd.ResourceMetrics().AppendEmpty())
		err = ctxt.nextConsumer.ConsumeMetrics(newCtx, newMd)
	}
```
It creates a new metric, and calls the next consumer with `nextConsumer.ConsumeMetrics` (most likely another processor in the pipeline), generating a new context with the values taken from the resource attributes of each batch. So, it fragments the data by the amount of `ResourceMetrics` shipped in the same context and also cleans the context (like `batch` or `groupbyattrs` processors do).

Because of that, in order to use it properly, it requires a bit of knowledge about the what is a HTTP context, OTLP telemetry data structure and how/where is the tenant label. For example, the following 2 situations would require a different chain of processors in order to get it working properly:

### 1. Tenant value is defined from a resource attribute set by the receiver ...
... for example based on the "filename" in the `filelog` receiver, or in case of metrics, if all bellowing to the same tenant are scraped by the same instance of `prometheus_simple` receiver. In this scenario the configuration is trivial, for example, given these pipelines:
```
    logs/app: 
      receivers: [receiver_creator/app]
      processors: [k8sattributes/platform, filter/o11y-katee, transform/o11y, context/tenant, groupbyattrs/tenant, batch/tenant]
      exporters: [otlphttp/loki]
    metrics/app:
      receivers: [receiver_creator/app]
      processors: [k8sattributes/platform, filter/o11y-katee,  transform/o11y, context/tenant, groupbyattrs/tenant, batch/tenant]
      exporters: [otlphttp/mimir]
```
In this setup, metrics and logs are received by a `prometheus_simple`/`filelog` instances created by `receiver_creator`. Each time a `receiver_creator` receives a notification from the watcher about  a new POD in Kubernetes, it creates one instance for `prometheus_simple` and another for `filelog`. The tetant is defined by K8S annotations at namespace level or at POD level. The first processor `k8sattributes/platform` enriches the telemetry with those metadata/labels from K8S API, the next processor `filter/o11y-katee` drops metric of some workloads based on some criteria.  `transform/o11y` gets the value of the labels enriched by the `k8sattributes` processor (it sets `o11y_namespace_team` and `o11y_pod_team` based on the K8S labels) to calculate the tenant with these statements:
```
  transform/o11y:
    error_mode: ignore
    metric_statements:
      - context: resource
        statements:
          - set(rexource.cache["tenant"], "anonymous")
          - set(resource.cache["tenant"], resource.attributes["o11y_namespace_team"])
          - set(resource.cache["tenant"], resource.attributes["o11y_pod_team"]) where resource.attributes["o11y_pod_team"] != nil and resource.attributes["o11y_pod_team"] == ""
          - set(resource.attributes["o11y_tenant"], resource.cache["tenant"]) 
```
`context/tenant` processor reads the new resource attribute `o11y_tenant` and moves to the context, emitting telemetry data with only one Resource set. The next processor `groupbyattrs` reassembles the data and finally the `batch` processor creates batches by tenant ready to send to the exporters.
```
  batch/tenant:
    timeout: 10s
    # batch data by tenant-id
    metadata_keys:
    - x-scope-orgid

  groupbyattrs/tenant:
    keys: [o11y_tenant]

  context/tenant:
    actions:
      - action: insert
        key: x-scope-orgid
        value: anonymous
        from_attribute: o11y_tenant
```
The pipeline is:  `receiver -> context/tenant -> groupbyattrs/tenant -> batch`.


### 2. Tenant is defined from a datapoint/logline attribute in the telemetry ...
... for example, when the same receiver instance gets metrics which belong to different tenants based on a label:
```
  metrics:
    receivers: [prometheus/cf]
  processor.
    processors: [transform/normalize, groupbyattrs/cf, cfattributes/labels, transform/tenant, groupbyattrs/tenant, context/tenant, batch/tenant]
    exporters: [otlphttp/app-mimir]
  ```

In this example, we want to gather platform metrics like quotas or application info to send to their tenant. Metrics are collected from a Cloudfoundry API Prometheus exporter, so in the same context there will be metrics which belong to different tenants. The first processor `transform/normalize` makes sure all datapoint attributes like `application_id` or `space_id` are present with these label names,  next processor `groupbyattrs/cf` creates batches of metrics by those attributes  (`application_id`, `space_id`, ...), moving these labels to resource level (applications and/or spaces with the same `id` belong to the same tenant). The next processor is similar to `k8sattributesprocessor` but for CF (it enriches metrics with annotations, labels and metadata from CF API). Next processor calculates the tenant from the previous annotations/labels/metadata and before sending to the `context` processor, metrics need to be grouped by  tenant -and this is the difference with the previous point-. Finally it batches the metrics by tenant before sending them to the exporters.

```
    groupbyattrs/tenant:
      keys: [o11y_tenant]

    groupbyattrs/cf:
      keys: [space_id, application_id, buildpack_id, domain_id, route_id]

    context/tenant:
      actions:
        - action: upsert
          key: x-scope-orgid
          value: anonymous
          from_attribute: o11y_tenant
```
The pipeline is:  `receiver -> groupbyattrs/tenatlabel -> context/tenant -> [groupbyattrs/tenant] -> batch`.


### Conclusion

On one hand, as you can see, the behavior of the `context` processor is always related to `groupbyattrs` processor. Context processor must be in between or at least before it. For me this is a quite strong indication in favor to include such functionality in `groupbyattrs` processor (also that processor also cleans the context).

On the other hand, probably the functionality of this component is special enough to justify keeping it in its own processor, and only used it on purpose, taken in consideration the previous two points.
