### ISSUE TITLE
[receiver/datadog] Missing DDAgentFeaturesDiscovery

### ISSUE THREAD

**Issue by melchiormoulin** [open-telemetry/opentelemetry-collector-contrib#34718]
### Component(s)

receiver/datadog

## Description
Currently Datadog receiver does not implement GET /info needed for  [featuresdiscovery](https://github.com/DataDog/dd-trace-java/blob/529f893c6ad269ef5a3b90f64f6ad919525b5286/communication/src/main/java/datadog/communication/ddagent/DDAgentFeaturesDiscovery.java#L140) by Datadog SDK 

This lead to the fallback mecanism of Datadog SDK which probe opentelemetry collector tracing endpoint with Content-lenght: 0 which lead to a stacktrace 
## Expected Result
No stacktrace.
## Actual Result
```
2024-07-12T13:56:36.749Z	error	datadogreceiver@v0.104.0/receiver.go:95	Unable to unmarshal reqs	{"kind": "receiver", "name": "datadog", "data_type": "traces"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver.(*datadogReceiver).handleTraces
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/datadogreceiver@v0.104.0/receiver.go:95
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2166
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2683
go.opentelemetry.io/collector/config/confighttp.(*decompressor).ServeHTTP
	go.opentelemetry.io/collector/config/confighttp@v0.104.0/compression.go:172
go.opentelemetry.io/collector/config/confighttp.(*ServerConfig).ToServer.maxRequestBodySizeInterceptor.func2
	go.opentelemetry.io/collector/config/confighttp@v0.104.0/confighttp.go:485
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2166
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.52.0/handler.go:212
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.52.0/handler.go:73
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2166
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
	go.opentelemetry.io/collector/config/confighttp@v0.104.0/clientinfohandler.go:26
net/http.serverHandler.ServeHTTP
	net/http/server.go:3137
net/http.(*conn).serve
	net/http/server.go:2039
```

### Collector version

v0.104.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  datadog:
    endpoint: 0.0.0.0:8080
    read_timeout: 60s

processors:
  probabilistic_sampler:
    sampling_percentage: 0

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [datadog]
      processors: [probabilistic_sampler]
      exporters: [debug]
```

### Additional context

I can handle the fix. 
To quick fix we can just check content length:0 of the http request and return same response code 400.
