### ISSUE TITLE
[pkg/ottl] Cannot access flags from span context

### ISSUE THREAD

**Issue by niko-renko** [open-telemetry/opentelemetry-collector-contrib#34739]
### Component(s)

pkg/ottl

## Description
Cannot access flags from span context. Making a statement that uses `flags` will fail.

## Steps to Reproduce
Make & Use a transformer:
```
  transform:
    error_mode: ignore
    trace_statements:
    - context: span
      statements:
      - set(attributes["flags"], flags)
```

## Expected Result
Spans will have a `flags` attribute that contain the `flags` values from the span context.

## Actual Result
```
2024/08/19 17:23:35 collector server run finished with error: invalid configuration: processors::transform: unable to parse OTTL statement "set(attributes[\"collector_test_2\"], flags)": error while parsing arguments for call to "set": invalid argument at position 1: segment "flags" from path "flags" is not a valid path nor a valid OTTL keyword for the Span context - review https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottlspan to see all valid paths
```

### Collector version

v0.107.0

## Environment
OS: Ubuntu 20

### OpenTelemetry Collector configuration

```yaml
receivers:
...

processors:
  transform:
    error_mode: ignore
    trace_statements:
    - context: span
      statements:
      - set(attributes["flags"], flags)

exporters:
...

service:
  pipelines:
    receivers: [...]
    processors: [transform]
    exporters: [...]
```

### Log output

```shell
2024/08/19 17:23:35 collector server run finished with error: invalid configuration: processors::transform: unable to parse OTTL statement "set(attributes[\"collector_test_2\"], flags)": error while parsing arguments for call to "set": invalid argument at position 1: segment "flags" from path "flags" is not a valid path nor a valid OTTL keyword for the Span context - review https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottlspan to see all valid paths
```
