### ISSUE TITLE
Geoip processor not found

### ISSUE THREAD

**Issue by grioda01** [open-telemetry/opentelemetry-collector-contrib#34737]
### Component(s)

processor/geoip

## Description
I set up the opentelemetrycollector resource on an azure kubernetes cluster, built on a Opentelemetry helm operator version 0.67.0
the collector image used is otel/opentelemetry-collector-contrib:0.106.1

I am getting the following error from the opentelemetrycollector

Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'processors': unknown type: "geoip" for id: "geoip" (valid values: [attributes cumulativetodelta probabilistic_sampler resource span tail_sampling memory_limiter deltatorate groupbyattrs metricstransform resourcedetection routing sumologic batch filter groupbytrace experimental_metricsgeneration redaction remotetap transform k8sattributes])

## Steps to Reproduce

Intall Opentelemetry Operator helm chart
Install opentelemetrycollector resource with geoip included in processor of config

## Expected Result
Geoip processor should be available

## Actual Result

I am getting the following error from the opentelemetrycollector

Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'processors': unknown type: "geoip" for id: "geoip" (valid values: [attributes cumulativetodelta probabilistic_sampler resource span tail_sampling memory_limiter deltatorate groupbyattrs metricstransform resourcedetection routing sumologic batch filter groupbytrace experimental_metricsgeneration redaction remotetap transform k8sattributes])

### Collector version

0.106.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
Containerized solution in Azure Kubernetes cluster, via Opentelemetry Operator Helm chart

### OpenTelemetry Collector configuration

```yaml
exporters:
      debug:
        verbosity: detailed
      elasticsearch:
        auth:
          authenticator: basicauth
        endpoint: xxxxxx
        logs_index: xxxxxxx
        pipeline: adjust_otel
    extensions:
      basicauth:
        client_auth:
          password: xxxxxxxx
          username: xxxxxxxxx
    processors:
      batch: {}
      geoip:
        providers:
          maxmind:
            database_path: /tmp/geoipdb/GeoLite2-City.mmdb
      k8sattributes:
        extract:
          labels:
          - from: node
            key: kubernetes.azure.com/cluster
            tag_name: k8s.cluster.name
          metadata:
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.start_time
          - k8s.cluster.uid
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.name
          - from: resource_attribute
            name: k8s.namespace.name
          - from: resource_attribute
            name: k8s.pod.uid
    receivers:
      filelog:
        exclude:
        - /var/log/pods/accurint-apps*/acccron/*.log
        - /var/log/pods/accurint-apps*/clamav/*.log
        include:
        - /var/log/pods/accurint-apps*/*/*.log
        - /var/log/pods/bwg-apps*/*/*.log
    service:
      extensions:
      - basicauth
      pipelines:
        logs:
          exporters:
          - debug
          - elasticsearch
          processors:
          - geoip
          - k8sattributes
          - batch
          receivers:
          - filelog
```

### Log output

```shell
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'processors': unknown type: "geoip" for id: "geoip" (valid values: [attributes cumulativetodelta probabilistic_sampler resource span tail_sampling memory_limiter deltatorate groupbyattrs metricstransform resourcedetection routing sumologic batch filter groupbytrace experimental_metricsgeneration redaction remotetap transform k8sattributes])
```
