### ISSUE TITLE
statement are not executed in order

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#34860]
### Component(s)

processor/routing

### Describe the issue you're reporting

Not quite sure if this is by design or a bug, this behavior is not documented and sort of surprise to me.

Here is an issue I encountered, given this routing processor config. 

```yaml
          - statement: route() where resource.attributes["__otel_enabled__"] == nil
            exporters: [otlp]
          - statement: delete_key(resource.attributes, "__otel_enabled__") where resource.attributes["__otel_enabled__"] == true
            exporters: [otlp]
          - statement: delete_key(resource.attributes, "__otel_enabled__") where resource.attributes["__otel_enabled__"] == false
            exporters: [nop]
```

the flag `__otel_enabled__` could have 3 values
1. not defined
2. `true`
3. `false`

the goal is that when the flag `__otel_enabled__` is explicitly set to `false`, route it to `nop` exporter.

However statements are execute in random order([range through map](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/routingprocessor/logs.go#L119)), given data has `__otel_enabled__` set to `false`, when 3rd one is executed before 1st one, both statements match, when 1st one is executed before 3rd one, only first statement matches.
