### ISSUE TITLE
vcenter data collection is not happening

### ISSUE THREAD

**Issue by vishnu-k1** [open-telemetry/opentelemetry-collector-contrib#34958]
## Description
I used vcenter receiver to pull data from vcenter data for monitoring but it endsup with error and terminating the collector from running.

 ## Steps to Reproduce

## Expected Result
vcenter datacollection
## Actual Result
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x382497e]
 
goroutine 95 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).buildVMMetrics(0xc001da4660, 0x17f15d72807f6040, 0xc001e498c8, 0xc003206988, 0xc002397a60?)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver@v0.108.0/processors.go:310 +0x1de
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).processVMs(0xc001da4660, 0x17f15d72807f6040, 0xc001e498c8, 0xc002b80840, 0xc002397850, 0xc002397cd0)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver@v0.108.0/processors.go:228 +0xfb
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).processDatacenterData(0xc001da4660, 0xc001e498c8, 0xc002397cd0)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver@v0.108.0/processors.go:41 +0x25d
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).scrapeAndProcessAllMetrics(0xc001da4660, {0x56df948, 0xc001e133e0}, 0xc002397cd0)

### Collector version

108

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
RHEL 9.4 go 1.22

### OpenTelemetry Collector configuration

```yaml
receivers:

    vcenter:
      endpoint: 'https://kmga001.dryicelabs.com/'
      username: 'svc-vc-readonly'
      password: 'wwwww'
      collection_interval: 5m
      initial_delay: 1s
      tls:
        insecure: true
      metrics:
       vcenter.host.cpu.utilization:
        enabled: false

processors:
  metricstransform:
   transforms:
    include: ^system
    match_type: regexp
    action: update
    operations:
        - action: add_label
          new_label: host.name
          new_value: "SC009"
        - action: add_label
          new_label: os.type
          new_value: "RHEL"
        - action: add_label
          new_label: os.version
          new_value: "RHEL 9.4"
        - action: add_label
          new_label: host.ip
          new_value: "10.1.1.77"

  batch:
    send_batch_size: 3

exporters:
 otlp/data-prepper:
  endpoint: "http://10.1.180.221:21891"
  tls:
    insecure: true

 file:
  path: '/tmp/incoming_to_otel.json'
 debug:
  verbosity: detailed
service:
 pipelines:

   metrics/vc:
    receivers: [vcenter]
    exporters: [otlp/data-prepper]
```

### Log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe8 pc=0x382497e]
 
goroutine 95 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).buildVMMetrics(0xc001da4660, 0x17f15d72807f6040, 0xc001e498c8, 0xc003206988, 0xc002397a60?)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver@v0.108.0/processors.go:310 +0x1de
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).processVMs(0xc001da4660, 0x17f15d72807f6040, 0xc001e498c8, 0xc002b80840, 0xc002397850, 0xc002397cd0)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver@v0.108.0/processors.go:228 +0xfb
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).processDatacenterData(0xc001da4660, 0xc001e498c8, 0xc002397cd0)
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver@v0.108.0/processors.go:41 +0x25d
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/vcenterreceiver.(*vcenterMetricScraper).scrapeAndProcessAllMetrics(0xc001da4660, {0x56df948, 0xc001e133e0}, 0xc002397cd0)
```
