### ISSUE TITLE
[processor/transform] undefined function `aggregate_on_attributes`

### ISSUE THREAD

**Issue by jaysoncena** [open-telemetry/opentelemetry-collector-contrib#34967]
### Component(s)

processor/transform

## Description
Undefined function `aggregate_on_attributes` for transformprocessor

## Steps to Reproduce
Use the following config
```
$ cat << EOF > /tmp/otel-test.yaml
service:
  pipelines:
    metrics:
      receivers: [nop]
      processors: [transform]
      exporters: [nop]

receivers:
  nop:

processors:
  transform:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - delete_key(attributes, "test")
          - aggregate_on_attributes("sum")

exporters:
  nop:
EOF
```

Test using the official docker image v0.108.0
```
$ docker run -v /tmp/otel-test.yaml:/etc/otelcol-contrib/config.yaml otel/opentelemetry-collector-contrib:0.108.0
Error: invalid configuration: processors::transform: unable to parse OTTL statement "aggregate_on_attributes(\"sum\")": undefined function "aggregate_on_attributes"
2024/09/03 03:20:20 collector server run finished with error: invalid configuration: processors::transform: unable to parse OTTL statement "aggregate_on_attributes(\"sum\")": undefined function "aggregate_on_attributes"
```
## Expected Result
The collector should be able to parse the config successfully

## Actual Result
undefined function `aggregate_on_attributes` 

### Collector version

v0.108.0

## Environment
Official docker image
otel/opentelemetry-collector-contrib:0.108.0

### OpenTelemetry Collector configuration

```yaml
service:
  pipelines:
    metrics:
      receivers: [nop]
      processors: [transform]
      exporters: [nop]

receivers:
  nop:

processors:
  transform:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - delete_key(attributes, "test")
          - aggregate_on_attributes("sum")

exporters:
  nop:
```

### Log output

```shell
Error: invalid configuration: processors::transform: unable to parse OTTL statement "aggregate_on_attributes(\"sum\")": undefined function "aggregate_on_attributes"
2024/09/03 03:20:20 collector server run finished with error: invalid configuration: processors::transform: unable to parse OTTL statement "aggregate_on_attributes(\"sum\")": undefined function "aggregate_on_attributes"
```
