### ISSUE TITLE
Azure Blob Receiver cannot read non-JSON logs

### ISSUE THREAD

**Issue by stuart23** [open-telemetry/opentelemetry-collector-contrib#34997]
### Component(s)

receiver/azureblob

## Description

Receiver fails to unmarshal logs that are not in json format.

## Steps to Reproduce

Deploy this collector and subscribe to blobs that are not in json format.

## Expected Result

We can still parse these logs, although they will be missing a lot of data.

## Actual Result

```"failed to unmarshal logs: ReadObjectCB: expect { or n, but found...+125 more"```

### Collector version

v0.107.0

## Environment
OS: AKS linux

### OpenTelemetry Collector configuration

```yaml
config:
  extensions:
    health_check: {}

  receivers:
    azureblob:
      connection_string: ${env:STORAGE_CONNECTION_STRING}
      logs:
        container_name: "airflow-logs"
      event_hub:
        endpoint: ${env:EVENTHUB_CONNECTION_STRING}

  processors:
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25

  exporters:
    debug:
      verbosity: detailed

  service:
    pipelines:
      metrics: null
      traces: null
      logs:
        receivers:
        - azureblob
        processors:
        - memory_limiter
        exporters:
        - debug

    extensions:
    - health_check
```

### Log output

```shell
The unmarshalling error message does not make it to the logs, although it should
```
