### ISSUE TITLE
Long lines are unexpectedly split into multiple OTEL Log records

### ISSUE THREAD

**Issue by cwegener** [open-telemetry/opentelemetry-collector-contrib#35042]
### Component(s)

pkg/stanza/fileconsumer, receiver/filelog

## Description

When using the filelog receiver, any lines that are longer than the default buffer size (16KB) will be split into multiple log records instead of one single log record.

## Steps to Reproduce

1. Create simple default filelog receiver config
2. Ingest a file that has a line length that is greater than 16KB)

## Expected Result

Lines longer than 16KB gets emitted as one single OTEL Log record

## Actual Result

Lines longer than 16KB get emitted as multiple OTEL Log records, each record getting split at the 16KB boundary.

### Collector version

v0.108.0

## Environment
OS: Archlinux
Compiler(if manually compiled): go 1.23.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    start_at: beginning
    include:
      - "/tmp/metrics_101089747.json"

exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    logs/raw:
      receivers:
        - filelog
      exporters:
        - debug
```
