### ISSUE TITLE
'max_concurrent_files' must be positive

### ISSUE THREAD

**Issue by jmatsushita** [open-telemetry/opentelemetry-collector-contrib#35080]
### Component(s)

receiver/filelog

## Description

Setting 'max_concurrent_files' to 1 results in the error `'max_concurrent_files' must be positive`

## Steps to Reproduce

Set filelog receiver config `max_concurrent_files: 1`

## Expected Result

'max_concurrent_files' is enforced correctly

## Actual Result

'max_concurrent_files' must be positive

### Collector version

v0.106.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  otlp:
    endpoint: 192.168.191.3:4317
    tls:
      insecure: true
  debug:

receivers:
  filelog/bot-history:
    include:
    - /hostfs/u/production/bot/log/*-verbose.log.gz
    max_concurrent_files: 1
    max_batches: 1
    start_at: beginning
    retry_on_failure:
      enabled: true
      initial_interval: 15s
      max_elapsed_time: 0
    multiline:
      line_start_pattern: ^\d{4}-[01]\d-[0-3]\dT
    compression: gzip
    operators:
    - type: regex_parser
      regex: (?P<timestamp_field>^\d{4}-\d{2}-\d{2}T\d{2}\d{2}\d{2}(\+|\-)\d{2}\d{2})
      timestamp:
        layout: "%Y-%m-%dT%H%M%S%z"
        parse_from: attributes.timestamp_field
```

### Log output

```shell
otel-collector-1  | 2024-09-09T19:29:18.542Z    info    service@v0.106.1/telemetry.go:96        Serving metrics {"address": ":8888", "metrics level": "Normal"}
otel-collector-1  | Error: failed to build pipelines: failed to create "filelog/bot-history" receiver for data type "logs": 'max_concurrent_files' must be positive
otel-collector-1  | 2024/09/09 19:29:18 collector server run finished with error: failed to build pipelines: failed to create "filelog/bot-history" receiver for data type "logs": 'max_concurrent_files' must be positive
```
