### ISSUE TITLE
[receiver/azuremonitor] Count values not usable

### ISSUE THREAD

**Issue by TWpgo** [open-telemetry/opentelemetry-collector-contrib#35155]
### Component(s)

receiver/azuremonitor

## Description
The count values are repeated not a single data point.
The number of repetitions is not predictable.

## Expected Result
![image](https://github.com/user-attachments/assets/ff4e0ac6-0a8c-4592-abe8-841223ade67c)
This is the result in Azure Monitor. There should be a single datapoint per timeinterval
## Actual Result
![image](https://github.com/user-attachments/assets/c96e9872-8743-46e6-b269-2d3cb9e29dc1)
This is the same metric received from the azuremonitor plugin and exported to otelhttp endpoint of Mimir and displayed in Grafana. The actual value is identical to Azure Monitor but repeated multiple times. It's not predictable how often the value is repeated so I cannot use that value for calculations.

### Collector version

v0.109.0

## Environment
Running official docker container in kubernetes
Receiving metics from Azure Monitor via the otel collector.
Sending the metics to otel ingress of Mimir.
Evaluating the values in Grafana.

### OpenTelemetry Collector configuration

```yaml
receivers:
  azuremonitor:
    subscription_id: "****"
    auth: "managed_identity"
    client_id: "***"
    resource_groups:
      - my-rg
```
