### ISSUE TITLE
[exporter/loadbalancing] couldn't find the exporter for the endpoint bug 

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector-contrib#35153]
### Component(s)

exporter/loadbalancing

## Description

Using this exporter encounters a bug. I have tried `dsn` and `k8s` resolver; both cause bugs.

use dns resolver, config:
```
  loadbalancing/jaeger:
    routing_key: "traceID"
    protocol:
      otlp:
        # all options from the OTLP exporter are supported, except the endpoint
        timeout: 1s
        tls:
          insecure: true
        sending_queue:
          enabled: true
          storage: file_storage/all_settings
        retry_on_failure:
          enabled: true
          max_elapsed_time: 500s
    resolver:
      dns:
        hostname: jaeger-collector-headless.insight-system.svc.cluster.local
        port: "4317"
        interval: 1s
        timeout: 200ms
```
It's error logs:
![img_v3_02el_0ff18611-890a-42bf-b8aa-598edaf5394g](https://github.com/user-attachments/assets/47ec3c8e-298b-409a-9b8c-a886f8c5e859)

using `k8s` resolver config:
```
  loadbalancing/jaeger:
    routing_key: "traceID"
    protocol:
      otlp:
        # all options from the OTLP exporter are supported, except the endpoint
        timeout: 1s
        tls:
          insecure: true
        sending_queue:
          enabled: true
          storage: file_storage/all_settings
        retry_on_failure:
          enabled: true
          max_elapsed_time: 500s
    resolver:
      k8s:
        service: insight-jaeger-collector
        ports:
          - 4317
```

It's error logs:
![image](https://github.com/user-attachments/assets/5d050fb4-09e2-4e04-bd6f-2711aeaff666)

I have noticed this:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/21208c0f5b87a2201e9a3ce7364053c2c7377b82/exporter/loadbalancingexporter/loadbalancer.go#L236

It also shows that something is wrong with the code.

### Collector version

v0.109.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Comment by atoulme** [comment]
Please provide your complete configuration file and indicate the version of the collector used.

**Comment by jpkrohling** [comment]
It looks like I can reproduce this with a fairly simple config, like:

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-loadbalancer
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.114.0
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}

    exporters:
      loadbalancing:
        protocol:
          otlp:
            timeout: 1s
            tls:
              insecure: true
            sending_queue:
              enabled: true
              storage: file_storage/all_settings
            retry_on_failure:
              enabled: true
              max_elapsed_time: 500s
        resolver:
          dns:
            hostname: otelcol-backend-collector-headless

    service:
      extensions: [ ]
      pipelines:
        traces:
          receivers:  [ otlp ]
          processors: [  ]
          exporters:  [ loadbalancing ]
```

And with this backend:

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-backend
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.114.0
  replicas: 10
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}

    exporters:
      debug: {}

    service:
      extensions: [ ]
      pipelines:
        traces:
          receivers:  [ otlp  ]
          processors: [  ]
          exporters:  [ debug ]
```
