### ISSUE TITLE
[SQL Server] expose server.port

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#35183]
### Component(s)

receiver/sqlserver

### Is your feature request related to a problem? Please describe.

Similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32810 we find that multiple SQL server instances running on the same host will be commingled. 

### Describe the solution you'd like

the SQL server receiver should expose a server.port attribute similar to what the mongodbreceiver is doing.

**Comment by atoulme** [comment]
The metadata.yaml would be enhanced with
```
  server.address:
    description: The address of the SQL server host.
    enabled: true
    type: string
  server.port:
    description: The port of the SQL server host.
    enabled: false
    type: int
```
