### ISSUE TITLE
elasticexporter does not seem to support the insecure option

### ISSUE THREAD

**Issue by hoffoo** [open-telemetry/opentelemetry-collector-contrib#3519]
**Describe the bug**
Docs specify that elasticexporter should have an insecure flag, does not seem to work and I dont see it in the code

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.
```    
  exporters:
      elastic:
        apm_server_url: '****'
        secret_token: ***
        insecure: true
```

**What did you expect to see?**
Be able to write to apm server 

**What did you see instead?**
2021-05-24T23:48:41.127Z	warn	batchprocessor/batch_processor.go:184	S": "processor", "name": "batch", "error": "sending event request failed: Post \"h-http:8200/intake/v2/events\": x509: certificate signed by unknown authority", "e"https://apm-server-apm-http:8200/intake/v2/events\": x509: certificate signed byending event request failed\ngo.elastic.co/apm/transport.(*HTTPTransport).sendStrtic.co/apm@v1.9.1-0.20201218004853-18a8126106c6/transport/http.go:278\ngo.elasticTTPTransport).SendStream\n\tgo.elastic.co/apm@v1.9.1-0.20201218004853-18a8126106c68\ngithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticexper).sendEvents\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/expor0.0.0-00010101000000-000000000000/exporter.go:195\ngithub.com/open-telemetry/openontrib/exporter/elasticexporter.(*elasticExporter).ExportResourceSpans\n\tgithub.entelemetry-collector-contrib/exporter/elasticexporter@v0.0.0-00010101000000-0000149\ngithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticexesExporter.func1\n\tgithub.com/open-telemetry/opentelemetry-collector-contrib/exp@v0.0.0-00010101000000-000000000000/exporter.go:52\ngo.opentelemetry.io/collectorper.(*tracesRequest).export\n\tgo.opentelemetry.io/collector@v0.27.0/exporter/exp:55\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send\o/collector@v0.27.0/exporter/exporterhelper/common.go:222\ngo.opentelemetry.io/corterhelper.(*retrySender).send\n\tgo.opentelemetry.io/collector@v0.27.0/exporter/_retry.go:241\ngo.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExpo).send\n\tgo.opentelemetry.io/collector@v0.27.0/exporter/exporterhelper/traces.goy.io/collector/exporter/exporterhelper.(*queuedRetrySender).send\n\tgo.openteleme7.0/exporter/exporterhelper/queued_retry.go:171\ngo.opentelemetry.io/collector/ex.NewTracesExporter.func2\n\tgo.opentelemetry.io/collector@v0.27.0/exporter/export1\ngo.opentelemetry.io/collector/consumer/consumerhelper.ConsumeTracesFunc.Consumemetry.io/collector@v0.27.0/consumer/consumerhelper/traces.go:29\ngo.opentelemetrsor/batchprocessor.(*batchTraces).export\n\tgo.opentelemetry.io/collector@v0.27.0ssor/batch_processor.go:254\ngo.opentelemetry.io/collector/processor/batchprocesssendItems\n\tgo.opentelemetry.io/collector@v0.27.0/processor/batchprocessor/batch.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcetelemetry.io/collector@v0.27.0/processor/batchprocessor/batch_processor.go:144\nrime/asm_amd64.s:1374"}

**What version did you use?**
v0.27.0

**What config did you use?**
```
  exporters:
      elastic:
        apm_server_url: '****'
        secret_token: ***
        insecure: true
```
**Environment**
docker and otel/opentelemetry-collector-contrib:latest image

**Additional context**

Thanks!

**Comment by cyrille-leclerc** [comment]
Hello @hoffoo . Sorry for the delay.
Can you please consider migrating to the native OpenTelemetry Protocol support that was GA in Elastic 7.13?
Please see our documentation https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html .
You would have to
* Upgrade Elastic (APM Server, Elasticsearch, Kibana) to v7.13
* Replace on you OpenTelemetry Collector the Elastic Exporter by the OTLP exporter. It would look like

```

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '127.0.0.1:4317'
  hostmetrics:
    collection_interval: 1m
    scrapers:
      # cpu not supported on MacOS
      # cpu:
      load:
      memory:
processors:
  batch: null
exporters:
  otlp/elastic:
    endpoint: "localhost:8200"
    insecure: true
    headers:
      Authorization: "Bearer my_secret_token"
service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - hostmetrics
      exporters:
        - otlp/elastic
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/elastic
```
