### ISSUE TITLE
AWS Secretsmanager configmap provider not working

### ISSUE THREAD

**Issue by paraniraja** [open-telemetry/opentelemetry-collector-contrib#35191]
### Component(s)

confmap/provider/secretsmanagerprovider

## Description

Below configuration is throwing not supported secretsmanager provider, 
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.109.0

exporters:
    clickhouse:
      endpoint: https://provider1.domain.com:12345
      headers:
        api-key: ${secretsmanager:<SecretArnOrName>}

however in the otel/opentelemetry-collector-contrib-dev docker it is working fine

## Steps to Reproduce

Using otel-collector-helm chart, add the following config in values.yaml file
`image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.109.0

exporters:
    clickhouse:
      endpoint: https://provider1.domain.com:12345
      headers:
        api-key: ${secretsmanager:<SecretArnOrName>}`

## Expected Result
Collector should read the secrets from AWS secret manager

## Actual Result
Error: failed to resolve config: cannot resolve the configuration: scheme "secretsmanager" is not supported for uri "secretsmanager:<SecretArnOrName>"                                  │
│ 2024/09/14 15:59:42 collector server run finished with error: failed to resolve config: cannot resolve the configuration: scheme "secretsmanager" is not supported for uri "secretsmana │
│

### Collector version

v0.109.0, v0.107.0, v0.108.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.109.0

config:
  exporters:
    clickhouse:
      endpoint: https://provider1.domain.com:12345
      headers:
        api-key: ${secretsmanager:<SecretArnOrName>}
```

### Log output

```shell
Error: failed to resolve config: cannot resolve the configuration: scheme "secretsmanager" is not supported for uri "secretsmanager:<SecretArnOrName>"                                  │
│ 2024/09/14 15:59:42 collector server run finished with error: failed to resolve config: cannot resolve the configuration: scheme "secretsmanager" is not supported for uri "secretsmana │
│
```
