### ISSUE TITLE
New component: Faro exporter

### ISSUE THREAD

**Issue by mar4uk** [open-telemetry/opentelemetry-collector-contrib#35319]
### The purpose and use-cases of the new component

The purpose of this component would be to export telemetry in Faro format

### Example configuration for the component

```yaml
exporters:
  faro:
    endpoint: https://example-endpoint.com/collect/app-key-example
 ```

### Telemetry data types supported

Logs
Traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

mar4uk, rlankfo

### Sponsor (optional)

@dehaansa
