### ISSUE TITLE
[receiver/k8scluster] Adding kubernetes labels as attributes to HorizontalPodAutoscaling metrics

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#35318]
### Component(s)

receiver/k8scluster

### Is your feature request related to a problem? Please describe.

I'm interested in adding Kubernetes labels as attributes to HorizontalPodAutoscaling metrics we have in k8scluster receiver:

### Describe the solution you'd like

There is two ways we could achieve this:
 1) Enhance k8sattributes processor to look at `hpa.UID` and extract labels from that.
 

2) Alternatively have some support of mapping labels to attributes, on each metric  in k8sclusterreceiver :thinking: ?
```
metrics:
   k8s.hpa.desired_replicas
     enabled:
     labels:
       - attribute_name: team
          key: app.kubernetes.io/team
```

Any suggestions / ideas?
