### ISSUE TITLE
Kafka Receiver does not include topic or receiver as a label

### ISSUE THREAD

**Issue by jhuizingh** [open-telemetry/opentelemetry-collector-contrib#35336]
### Component(s)

receiver/kafka

## Description

The metrics emitted by the Kafka Receiver to not contain enough labels to determine which Kafka Receiver and topic they are referring to if you use multiple instances of the Kafka Receiver. Many other receivers include a `receiver` label which shows exactly which receiver the metric comes from by name, but the Kafka Receiver does not. 

## Steps to Reproduce

Create an otel collector with the following relevant pieces 

```
  ... irrelevent parts omitted ...
  receivers:
    kafka/first:
      topic: kafka-topic-first
    kafka/second:
      topic: kafka-topic-second
  service:
    pipelines:
      metrics/kafka:
        receivers:
          - kafka/first
          - kafka/second
  ... irrelevent parts omitted ...
```

## Expected Result

Metric in the form:

```
otelcol_kafka_receiver_offset_lag {
  cluster="mycluster",
  http_scheme="http",
  net_host_name="10.110.0.242",
  net_host_port="8888",
  partition="24",
  server_address="10.110.0.242",
  server_port="8888",
  service_name="otelcol-contrib",
  service_version="0.103.1",
  url_scheme="http",
  receiver="kafka/first",
  topic="kafka-topic-first"
}
```
## Actual Result

Metric in the form:

```
otelcol_kafka_receiver_offset_lag {
  cluster="mycluster",
  http_scheme="http",
  net_host_name="10.110.0.242",
  net_host_port="8888",
  partition="24",
  server_address="10.110.0.242",
  server_port="8888",
  service_name="otelcol-contrib",
  service_version="0.103.1",
  url_scheme="http"
}
```

### Collector version

0.103.1

## Environment
AWS EKS
Kubernetes v 1.30.3

Image: opentelemetry-collector-contrib
Helm Chart: opentelemetry-collector-0.95.0 

### OpenTelemetry Collector configuration

```yaml
receivers:
    kafka/first:
      topic: kafka-topic-first
    kafka/second:
      topic: kafka-topic-second
  service:
    pipelines:
      metrics/kafka:
        receivers:
          - kafka/first
          - kafka/second
```

### Log output

```shell
N/A
```
