### ISSUE TITLE
[exporter/loadbalancing] Data loss occurring when change in downstream DNS records or pods 

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-collector-contrib#35378]
### Component(s)

exporter/loadbalancing

## Description

We have used the DNS resolver and K8S resolver which seem to both cause data loss, because they route based on the IP address.

We are using the load balancing exporter for tail sampling, but this problem is generally applicable to this exporter. 

When our downstream services changes scales/deploys, the IP addresses change. And, since the IP address is tied to exporter, the spans get trapped in that exporter's queue, with no way out. That exporter is deleted along with the data that lives in its queue. 

Everytime we deploy we get a bunch of dropped spans as a result.

## Steps to Reproduce

Set up the loadbalancing exporter with the DNS resolver, then change the IP address that the DNS record resolves to. You will see `otelcol_exporter_send_failed_spans` tick up.

## Expected Result

Data is not dropped but re-balanced / successfully exported. 

## Actual Result

Data is lost along with the exporter that is deleted due to its IP address no longer being active.

### Potential solutions

We are using a stateful set, so the DNS records / pod names are stable, i.e. `pod-0, pod-1, ... , pod-n`. If the exporters were attached to these names instead of the IP addresses, this would solve the issue. This may be possible using the [pod hostname](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields) or SRV record.

Another potential solution, which may or may not be possible, is to release the data trapped in the exporter queue, when an exporter is deleted. 

### Collector version

v0.109.0

## Environment
Kubernetes, arm64

### OpenTelemetry Collector configuration

```yaml
exporters:
  loadbalancing:
    protocol:
      otlp:
        sending_queue:
          queue_size: 1000
    resolver:
      dns:
        hostname: stateful-sampler.tailsampling
        port: "4317"
```

**Comment by bvsvas** [comment]
We noticed similar issue# [35512](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35512) for metrics, we are using this otel lb since our custom exporter is stateful. 

Do you see any errors in `loadbalancing` exporter logs in your case? We see only 503, http_server_duration and refused_metric_point metrics.

**Comment by jamesmoessis** [comment]
@bvsvas our primary signal is the metric `otelcol_exporter_send_failed_spans`, I don't think there's a 503 because we are using a headless service and the exporter is trying to send to an IP address that has nothing running on it.

We have temporarily solved the issue by falling back to the static resolver, but it means we have to hardcode all the hostnames in:

```yaml
exporters:
  loadbalancing:
    protocol:
      otlp:
        sending_queue:
          queue_size: 500
    resolver:
      static:
        hostnames:
          - pod-0.stateful-sampler.tailsampling:4317
          - pod-1.stateful-sampler.tailsampling:4317
          - pod-2.stateful-sampler.tailsampling:4317
          - ....
```

Would appreciate some thoughts from maintainers, @jpkrohling @MovieStoreGuy any ideas? I would be happy to take a closer look and contribute a fix, just would want some input from codeowners first.
