### ISSUE TITLE
[processor/metricsgeneration] Add option to match metric attributes for calculation operations

### ISSUE THREAD

**Issue by crobert-1** [open-telemetry/opentelemetry-collector-contrib#35425]
### Component(s)

processor/metricsgeneration

### Describe the issue you're reporting

**Context**
Currently the metrics generation processor simply grabs the first datapoint's value from the metric whose name matches the supplied `metric2` configuration option. This value is then used for generating all new metrics and datapoints.

**Current implementation's limitation**
The limitation here is that attributes are ignored when generating a new metric. An example of when this yields unexpected results is for the host metrics receiver's filesystem scraper. Let's say a user wants to calculate total size of the filesystem in bytes using the two metrics `system.filesystem.usage` and `system.filesystem.utilization`. This would be done by the following configuration:

```
experimental_metricsgeneration:
  rules:
    - name: system.filesystem.capacity
       unit: bytes
       type: calculate
       metric1: system.filesystem.usage
       metric2: system.filesystem.utilization
       operation: divide
```

The problem here is that the attributes of these two metrics may mismatch. One attribute is the filesystem's `mountpoint`. The resulting metric would incorrectly use the first datapoint's value, regardless of mountpoint. This would result in meaningless generated metrics.

**Proposal**
I propose adding a new configuration option, `match_attributes`, a `bool` that's disabled by default. This would preserve current functionality be default.

If this option is enabled, the two datapoints being compared must have identical attributes to create a resulting datapoint in the desired metric. If they're not an identical match, no action will be taken.

Resulting configuration:
```
experimental_metricsgeneration:
  rules:
    - name: system.filesystem.capacity
       unit: bytes
       type: calculate
       metric1: system.filesystem.usage
       metric2: system.filesystem.utilization
       match_attributes: true
       operation: divide
```
