### ISSUE TITLE
Issue is regarding the duplicate metrics and hostname discrepancies after setting up OpenTelemetry (Otel) along with Datadog agent

### ISSUE THREAD

**Issue by zendesk-shweta** [open-telemetry/opentelemetry-collector-contrib#35448]
## Description 
we have duplicated hosts being reported:
 
One Host i-xxxxxxxx which had for aliases ip-xxx-xx-xxx-xx.usw2.abc.com
One Host  ip-xxx-xx-xxx-xx.usw2.abc.internal-podx which had no aliases

### Collector version

VERSION=0.101.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
extensions:
  zpages:
    endpoint: :
  health_check:
    endpoint: 

receivers:
  datadog:
    endpoint: 
    read_timeout:
  otlp:
    protocols:
      grpc:
        endpoint: 
      http:
        endpoint: 
  prometheus:
   config:
     scrape_configs:
     - job_name: ' abc '
       scrape_interval: 60s
       static_configs:
       - targets: ['']
       metric_relabel_configs:
       - source_labels: [__name__]
         regex: '   '
         action: drop

processors:
  batch:
  memory_limiter:
    check_interval: 
    limit_percentage: 
    spike_limit_percentage: 

exporters:
  nop:
  logging:
    loglevel: info
  datadog:
    api:
      site: "datadoghq.com"
      key: ${env:DD_API_KEY}
    tls:
        insecure_skip_verify: true
    sending_queue:
      enabled: true
      queue_size: 20000
      num_consumers: 100
    timeout: 1s
    retry_on_failure:
      enabled: false
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 5m
    host_metadata:
      enabled: false
  otlphttp:
    endpoint: 
    tls:
      insecure: true

service:
  telemetry:
    metrics:
      level: basic
      address: ":8888"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp]
    traces/datadog:
      receivers: [datadog]
      processors: [memory_limiter, batch]
      exporters: [otlphttp] # TBD: isolate it on aggr.
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [datadog] #TBD: make it nop for verification.

  extensions: [zpages, health_check]
```
