### ISSUE TITLE
"limit" in receiver/awscloudwatchreceiver is not functioning as expected

### ISSUE THREAD

**Issue by thilee-siva** [open-telemetry/opentelemetry-collector-contrib#35486]
### Component(s)

receiver/awscloudwatch

## Steps to Reproduce
I’m using the OpenTelemetry Collector with the awscloudwatch receiver to fetch logs from CloudWatch and send them to Datadog. However, I’ve noticed that the receiver isn’t able to access all the log groups in the region, even though I’ve overridden the default limit of 50.

## Expected Result
I have 75 log groups. When writing to any log group that appears alphabetically after the 50th position, I expect the logs to be read by OTEL.

## Actual Result
However, it only reads the log groups that are before the 50th position.

### Collector version

0.99.0

## Environment
OS: Ubuntu 20.04

### OpenTelemetry Collector configuration

```yaml
receivers:
  awscloudwatch:
    profile: "${PROFILE}"
    region: "${REGION}"
    logs:
      poll_interval: 1m
      groups:
        autodiscover:
          limit: 100
```

### Log output

```shell
N/A
```

### Additional context

N/A
