### ISSUE TITLE
New component: Zipkin V2 UDP Receiver

### ISSUE THREAD

**Issue by EOjeah** [open-telemetry/opentelemetry-collector-contrib#35515]
### The purpose and use-cases of the new component

This component will enable the Collector to receive traces in the form of [Zipkin](https://zipkin.io/) v2 JSON spans over UDP.

### Example configuration for the component

```yaml
zipkin_udp:
  listen_address: ":52352"
  udp:
    queue_size: 1000
    num_workers: 10
    buffer_size: 100
    max_packet_size: 65000
```

### Telemetry data types supported

traces

### Is this a vendor-specific component?

- [ ] This is a vendor-specific component
- [ ] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [ ] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

EOjeah

### Additional context

Currently, the OpenTelemetry Collector supports receiving Zipkin traces over HTTP. However, some environments with very high throughput use case can benefit from the lower overhead and simplicity of UDP.

Due to nature of UDP as inherently unreliable, packets may be lost but the risk is mitigated by the nature of tracing data, where occasional loss of spans is generally acceptable.
