### ISSUE TITLE
cumulativetodeltaprocessor throws error processor "cumulativetodelta" which is not configured

### ISSUE THREAD

**Issue by lorelei-rupp-imprivata** [open-telemetry/opentelemetry-collector-contrib#35556]
### Component(s)

processor/cumulativetodelta

## Description
Following the example here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/cumulativetodeltaprocessor/README.md#examples 
using 
```
processors:
  cumulativetodelta:
```

Throws an error when the pod actually tries to start 
Error: invalid configuration: service::pipelines::metrics: references processor "cumulativetodelta" which is not configured2024/10/02 14:52:47 collector server run finished with error: invalid configuration: service::pipelines::metrics: references processor "cumulativetodelta" which is not configured

We do use the https://github.com/Dynatrace/dynatrace-otel-collector custom image version 0.13.0
which uses This release includes version 0.108.0/0.108.1 of the upstream Collector components.

We use the https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector to roll this out with chart version  0.104.0

### Collector version

0.108.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
opentelemetry-collector:
  mode: deployment
  nameOverride: dynatrace-collector
  fullnameOverride: dynatrace-collector
  image:
    repository: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector
    tag: 0.13.0

  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:64317
          http:
            endpoint: ${env:MY_POD_IP}:4318
            cors:
              allowed_headers:
              - '*'
              max_age: 7200
    processors:
      cumulativetodelta:
      transform: # https://docs.dynatrace.com/docs/extend-dynatrace/opentelemetry/collector/use-cases/histograms
        error_mode: ignore
        trace_statements:
          - context: resource
            statements:
              - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])
        log_statements:
          - context: resource
            statements:
              - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])
        metric_statements:
          - context: metric
            statements:
              # Get count from the histogram. The new metric name will be <histogram_name>_count
              - extract_count_metric(true) where type == METRIC_DATA_TYPE_HISTOGRAM

              # Get sum from the histogram. The new metric name will be <histogram_name>_sum
              - extract_sum_metric(true) where type == METRIC_DATA_TYPE_HISTOGRAM

              # convert the <histogram_name>_sum metrics to gauges.
              - convert_sum_to_gauge() where IsMatch(name, ".*_sum")

          - context: resource #make sure DT entity dimensions are set on metrics
            statements:
              - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])


      batch/traces:
        timeout: 1s
        send_batch_size: 50
      memory_limiter:
        check_interval: 2s

        # Maximum amount of memory, in MiB, targeted to be allocated by the process heap.
        # Note that typically the total memory usage of process will be about 50MiB higher
        # than this value.
        limit_mib: 900

        # The maximum, in MiB, spike expected between the measurements of memory usage.
        spike_limit_mib: 100

      resourcedetection/ec2:
        detectors: [ "env" , "ec2"]
        timeout: 2s
        override: false

      resource:
        attributes:
          - key: cloud.account.id
            action: delete
          - key: cloud.platform
            action: delete
          - key: cloud.provider
            action: delete
          - key: cloud.region
            action: delete
          - key: host.arch
            action: delete
          - key: host.name
            action: delete
          - key: os.description
            action: delete
          - key: os.type
            action: delete
          - key: process.pid
            action: delete
          - key: process.runtime.description
            action: delete
          - key: process.runtime.name
            action: delete
          - key: process.runtime.version
            action: delete
          - key: process.executable.path
            action: delete
          - key: telemetry.auto.version
            action: delete
          - key: telemetry.sdk.name
            action: delete
          - key: telemetry.sdk.version
            action: delete

    exporters:
      otlphttp:
        XXXXXXXX

    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter,batch/traces,transform,attributes/environment,resource ]
          exporters: [ otlphttp ]
        metrics:
          receivers: [ otlp ]
          processors: [ memory_limiter,transform,cumulativetodelta,attributes/environment,resourcedetection/ec2]
          exporters: [ otlphttp ]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]
  ports:
    otlp:
      enabled: true
      containerPort: 64317
      servicePort: 64317
      hostPort: 64317
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false

  extraEnvsFrom:
    - secretRef:
        name: XXXXX

  resources:  
    limits:
      cpu: 500m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
```

### Log output

```shell
Error: invalid configuration: service::pipelines::metrics: references processor "cumulativetodelta" which is not configured2024/10/02 14:52:47 collector server run finished with error: invalid configuration: service::pipelines::metrics: references processor "cumulativetodelta" which is not configured
```

**Comment by dyladan** [comment]
The config in the OP uses `attributes/environment` processor in the traces and logs pipelines, but it isn't configured. Removing that processor seems to work just fine to me. The following config correctly validates and the processor starts (http exporter is replaced with debug)

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:64317
      http:
        endpoint: ${env:MY_POD_IP}:4318
        cors:
          allowed_headers:
          - '*'
          max_age: 7200
processors:
  cumulativetodelta:
  transform: # https://docs.dynatrace.com/docs/extend-dynatrace/opentelemetry/collector/use-cases/histograms
    error_mode: ignore
    trace_statements:
      - context: resource
        statements:
          - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
          - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
          - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
          - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
          - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
          - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
          - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])
    log_statements:
      - context: resource
        statements:
          - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
          - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
          - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
          - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
          - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
          - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
          - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])
    metric_statements:
      - context: metric
        statements:
          # Get count from the histogram. The new metric name will be <histogram_name>_count
          - extract_count_metric(true) where type == METRIC_DATA_TYPE_HISTOGRAM

          # Get sum from the histogram. The new metric name will be <histogram_name>_sum
          - extract_sum_metric(true) where type == METRIC_DATA_TYPE_HISTOGRAM

          # convert the <histogram_name>_sum metrics to gauges.
          - convert_sum_to_gauge() where IsMatch(name, ".*_sum")

      - context: resource #make sure DT entity dimensions are set on metrics
        statements:
          - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
          - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
          - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
          - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
          - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
          - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
          - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])


  batch/traces:
    timeout: 1s
    send_batch_size: 50
  memory_limiter:
    check_interval: 2s

    # Maximum amount of memory, in MiB, targeted to be allocated by the process heap.
    # Note that typically the total memory usage of process will be about 50MiB higher
    # than this value.
    limit_mib: 900

    # The maximum, in MiB, spike expected between the measurements of memory usage.
    spike_limit_mib: 100

  resourcedetection/ec2:
    detectors: [ "env" , "ec2"]
    timeout: 2s
    override: false

  resource:
    attributes:
      - key: cloud.account.id
        action: delete
      - key: cloud.platform
        action: delete
      - key: cloud.provider
        action: delete
      - key: cloud.region
        action: delete
      - key: host.arch
        action: delete
      - key: host.name
        action: delete
      - key: os.description
        action: delete
      - key: os.type
        action: delete
      - key: process.pid
        action: delete
      - key: process.runtime.description
        action: delete
      - key: process.runtime.name
        action: delete
      - key: process.runtime.version
        action: delete
      - key: process.executable.path
        action: delete
      - key: telemetry.auto.version
        action: delete
      - key: telemetry.sdk.name
        action: delete
      - key: telemetry.sdk.version
        action: delete

exporters:
  debug:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter,batch/traces,transform,resource ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter,transform,cumulativetodelta,resourcedetection/ec2]
      exporters: [ debug ]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [debug]
```

**Comment by lorelei-rupp-imprivata** [comment]
@dyladan thanks for taking a look at this. Sorry I totally forgot about this processor, we use an env override to add this in, and we do need to have this in our config, it looks like this in our override values files for this helm chart 
```
opentelemetry-collector:
  config:
    processors:
      attributes/environment:
          actions:
          - key: environment
            value: "dev-eks-cluster-for-example" 
            action: insert
```
