### ISSUE TITLE
TargetAllocators - cannot discover services from two different serviceMonitor

### ISSUE THREAD

**Issue by flenoir** [open-telemetry/opentelemetry-collector-contrib#35607]
### Component(s)

receiver/prometheus

### Describe the issue you're reporting

Hi, 

Working with target allocators, i want to discover services from 2 distincts "serviceMonitors". when i read the [doc](http://servicemonitors%20to%20be%20selected%20for%20target%20discovery.%20this%20is%20a%20map%20of%20{key,value}%20pairs.%20each%20{key,value}%20in%20the%20map%20is%20going%20to%20exactly%20match%20a%20label%20in%20a%20servicemonitor's%20meta%20labels.%20the%20requirements%20are%20anded/),

 i see "ServiceMonitors to be selected for target discovery. This is a map of {key,value} pairs. Each {key,value} in the map is going to exactly match a label in a ServiceMonitor's meta labels. The requirements are ANDed".

My config is : 

```
spec:
  serviceAccount: my_sa
  targetAllocator:
    enabled: true
    serviceAccount: my_sa
    # allocationStrategy: "consistent-hashing"
    replicas: 2
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        release: first
        my-other-key: alpha
```

but is this case, i only point on service monitor that have both labels. I'd prefer to point on 2 differents serviceMonitor that have "release: first" for the firs one and "my-other-key: alpha" for the second one.

 how can i have OR instead of AND ?
