### ISSUE TITLE
Zipkin UDP Receiver

### ISSUE THREAD

**Issue by EOjeah** [open-telemetry/opentelemetry-collector-contrib#35620]
### Component(s)

receiver/zipkin

### Is your feature request related to a problem? Please describe.

Feature Request: Receive zipkin formatted spans over UDP

### Describe the solution you'd like

Currently, the zipkin receiver only receivers spans over http. However, some environments with very high throughput use case can benefit from the lower overhead and simplicity of UDP.

```yaml
zipkin:
  protocols:
    http: # existing
      endpoint: "localhost:9411" 
    udp: # new
      endpoint: "localhost:52352"
      queue_size: 1000
      num_workers: 10
      buffer_size: 100
      max_packet_size: 65000
```

### Describe alternatives you've considered

- udp logs receiver with a new connector to convert those logs to traces

### Additional context

Due to nature of UDP as inherently unreliable, packets may be lost but the risk is mitigated by the nature of tracing data, where occasional loss of spans is generally acceptable.
