### ISSUE TITLE
googlecloudmonitoringreceiver: DataPoints are out of order

### ISSUE THREAD

**Issue by andrewegel** [open-telemetry/opentelemetry-collector-contrib#35780]
### Component(s)

receiver/googlecloudmonitoring

## Description

The GoogleAPI: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list this receiver calls states:

> The points in each time series are currently returned in reverse time order (most recent to oldest).

(So newest -> oldest)

I believe this causes an issue with downstream processors such as the deltatocumulative processor which expects datapoints to be in order of oldest -> newest; Case in point, when I tried the OTEL configuration (in this issue), can see that the internal telemetry data is showing `otelcol_deltatocumulative_datapoints_dropped`:

```
% curl -sq http://127.0.0.1:8888/metrics  | grep otelcol_deltatocumulative_datapoints_dropped
# HELP otelcol_deltatocumulative_datapoints_dropped number of datapoints dropped due to given 'reason'
# TYPE otelcol_deltatocumulative_datapoints_dropped counter
otelcol_deltatocumulative_datapoints_dropped{reason="older-start",service_instance_id="07d9c375-40fc-4576-a808-3d4da3deda7e",service_name="collector",service_version="development"} 4
otelcol_deltatocumulative_datapoints_dropped{reason="out-of-order",service_instance_id="07d9c375-40fc-4576-a808-3d4da3deda7e",service_name="collector",service_version="development"} 8
```

This also cased a bit of an issue further down in our metrics store in AMP where the PromQL `rate(router_googleapis_com_nat_sent_bytes_count[$__rate_interval])` was showing outright incorrect values when computing the rate which was off by roughly a factor of 4 (which is about the number of datapoints that were dropped between scrapes)

## Steps to Reproduce

Use the sample config and you will see the debug exporter will output metrics only on the last timestamp scraped - if you turn off the `deltatocumulative` processor, you will see datapoints exported like so (newest -> oldest)

```
NumberDataPoints #0
StartTimestamp: 2024-10-14 19:19:00 +0000 UTC
Timestamp: 2024-10-14 19:20:00 +0000 UTC
Value: 5163934
NumberDataPoints #1
StartTimestamp: 2024-10-14 19:18:00 +0000 UTC
Timestamp: 2024-10-14 19:19:00 +0000 UTC
Value: 5348459
NumberDataPoints #2
StartTimestamp: 2024-10-14 19:17:00 +0000 UTC
Timestamp: 2024-10-14 19:18:00 +0000 UTC
Value: 5623164
NumberDataPoints #3
StartTimestamp: 2024-10-14 19:16:00 +0000 UTC
Timestamp: 2024-10-14 19:17:00 +0000 UTC
Value: 5159819
NumberDataPoints #4
StartTimestamp: 2024-10-14 19:15:00 +0000 UTC
Timestamp: 2024-10-14 19:16:00 +0000 UTC
Value: 5729918
```

## Expected Result

Same as above, except the order now goes from oldest -> newest

### Collector version

2295a097522e0326c5e31128c4361a6f3e63c058

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug:
    verbosity: detailed
    sampling_initial: 0
    sampling_thereafter: 1
receivers:
  googlecloudmonitoring:
    collection_interval: 5m
    project_id: <redacted>
    metrics_list:
    - metric_name: router.googleapis.com/nat/sent_bytes_count
processors:
  deltatocumulative:
    max_stale: 20m
service:
  telemetry:
    logs:
      level: DEBUG
      development: true
      encoding: console
      sampling:
        enabled: false
  pipelines:
    metrics:
      receivers:
      - googlecloudmonitoring
      processors:
      - deltatocumulative
      exporters:
      - debug
```
