### ISSUE TITLE
Unable to filter logs from subset of k8s pod using filter processor.

### ISSUE THREAD

**Issue by vkamlesh** [open-telemetry/opentelemetry-collector-contrib#35841]
### Component(s)

processor/filter

### Describe the issue you're reporting

We are migrating from using a Fluentd agent to the OpenTelemetry collector for log ingestion. Currently, our logs are sent to a Logz.io cluster. During the migration, we will transition to a new Loki remote cluster and use the OpenTelemetry collector to push logs there.
We are attempting to use the following configuration to ingest subsets of pod logs based on a regular expression, but it is not functioning as expected.

In short, we want to filter specific logs from a subset of pods(applications).

Current Fluentd configuration snippet:

```
    # Filter out logs - Including only logs that contain level field
    <filter {kubernetes.var.log.containers.handler-func**,kubernetes.var.log.containers.gen-api**,kubernetes.var.log.containers.stream-func-http**}>
      @type grep
        <exclude>
          key message
          pattern /.*Processed request .* \d+ .* elapsed (\d+\.\d+)+ms.*|.* HTTP request .*|.*\ \[.*\]\ .*\ request\ GET\ .*\ HTTP/.*|.*Trigger Details.*|.*Executing .* (.*)|.* HTTP .* after .*ms - .*|.*Information.*Trace.*|.*Executed\ \'.*\'.*ms.*|.*info\:\ .*\[.*\].*/
        </exclude>
    </filter>
```

New Otel-collector config.

```
      filter/platform-pod-logs:
        logs:
          include:
            match_type: regexp
            resource_attributes:
              - key: k8s.pod.name
                value: '(handler-func-.*|gen-api-.*|obs-api-.*|stream-func-http-.*)'
          exclude:
            match_type: regexp
            record_attributes:
              - key: body
                value: ".*Processed request .* \\d+ .* elapsed (\\d+\\.\\d+)+ms.*|.* HTTP request .*|.* \\[.*\\] .* request GET .* HTTP/.*|.*Trigger Details.*|.*Executing .* (.*)|.* HTTP .* after .*ms - .*|.*Information.*Trace.*|.*Executed '.*'.*ms.*|.*info: .*\\[.*\\].*"
```

**Comment by vkamlesh** [comment]
The following filter config is working but it's not an exact match of regex.  

```
    filter/drop_platform_logs:
        logs:
          log_record:
            - 'IsMatch(body, ".*Processed request .*") == true and (resource.attributes["service.name"] == "new-api")'
            - 'IsMatch(body, ".* HTTP request .*") == true and (resource.attributes["service.name"] == "handler-func-http") and (resource.attributes["service.name"] == "management-api")'
            - 'IsMatch(body, ".*Executing .*") == true and (resource.attributes["service.name"] == "handler-func-http") and (resource.attributes["service.name"] == "management-api")'
            - 'IsMatch(body, ".*Trigger Details.*") == true and (resource.attributes["service.name"] == "tt-service")' #This regex can only be tested in the US EST time.
            ##The IsMatch doesn't support multiple OR statements so can't use ".*Processed request .* \\d+ .* elapsed (\\d+\\.\\d+)+ms.*|.* HTTP request .*|.
```
