### ISSUE TITLE
[jaegerreceiver] Gives warning about "jaeger receiver will deprecate Thrift-gen and replace it with Proto-gen"

### ISSUE THREAD

**Issue by davispuh** [open-telemetry/opentelemetry-collector-contrib#35894]
### Component(s)

receiver/jaeger

## Description

After starting Collector in logs can see warning.

## Steps to Reproduce

Note sure, I think need to enable `jaegerreceiver`

## Expected Result

No such warning.

## Actual Result

Warning:

```
{"level":"warn","ts":1729291563.3518195,"caller":"jaegerreceiver@v0.111.0/factory.go:49","msg":"jaeger receiver will deprecate Thrift-gen and replace it with Proto-gen to be compatbible to jaeger 1.42.0 and higher. See #18485 for more details.","kind":"receiver","name":"jaeger","data_type":"traces"}
```

### Collector version

v0.111.0

## Environment
OS: openSUSE Leap 15.6

### OpenTelemetry Collector configuration

```yaml
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
```

### Log output

```shell
{"level":"warn","ts":1729291563.3518195,"caller":"jaegerreceiver@v0.111.0/factory.go:49","msg":"jaeger receiver will deprecate Thrift-gen and replace it with Proto-gen to be compatbible to jaeger 1.42.0 and higher. See #18485 for more details.","kind":"receiver","name":"jaeger","data_type":"traces"}
```
