### ISSUE TITLE
Filed serverity_number is not mapped to filed serverity_text as expected

### ISSUE THREAD

**Issue by Wudadada** [open-telemetry/opentelemetry-collector-contrib#35891]
### Component(s)

processor/transform

## Description
want to map Filed serverity_number to filed serverity_text, like serverity_number 9 to serverity_text 'INFO'，but it didn't take effect，is it a bug or my config error?
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/18ec0e8a-b0cc-412e-82f2-09fa6e3b32b1">
## Steps to Reproduce
As my configuration
## Expected Result
Filed serverity_number is not mapped to filed serverity_text 
## Actual Result
Wasn't mapped

### Collector version

v0.111.0

## Environment
OS:  centOS 8

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:19100']

processors:
  batch:
    timeout: 5s
    send_batch_size: 100000
  transform:
    log_statements:
      - context: log
        statements:
          - set(severity_text, "TRACE") where severity_number == 1
          - set(severity_text, "DEBUG") where severity_number == 5
          - set(severity_text, "INFO") where severity_number == 9
          - set(severity_text, "WARN") where severity_number == 13
          - set(severity_text, "ERROR") where severity_number == 17
          - set(severity_text, "FATAL") where severity_number == 21

exporters:
  clickhouse:
    endpoint: tcp://10.105.212.248:9000?dial_timeout=10s
    create_schema: true
    database: otel
    async_insert: true
    ttl: 72h
    compress: lz4
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    username: "default"
    password: "123"
    cluster_name: cluster_3S_1R
    table_engine:
      name: "ReplicatedMergeTree"

    logs_table_name: otel_logs

    traces_table_name: otel_traces

    metrics_tables:
      gauge: 
        name: "otel_metrics_gauge"
      sum: 
        name: "otel_metrics_sum"
      summary: 
        name: "otel_metrics_summary"
      histogram: 
        name: "otel_metrics_histogram"
      exponential_histogram: 
        name: "otel_metrics_exp_histogram"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [clickhouse]

  telemetry:
    logs:
      level: "debug"
```

### Log output

```shell
Oct 21 15:23:04 xxx otelcol-contrib[3819905]: 2024-10-21T15:23:04.742+0800#011debug#011clickhouseexporter@v0.111.0/exporter_logs.go:127#011insert logs#011{"kind": "exporter", "data_type": "logs", "name": "clickhouse", "records": 1, "cost": "242.2003ms"}
```
