### ISSUE TITLE
[processor/spanprocessor] Implement context-aware/structured span processing capabilities

### ISSUE THREAD

**Issue by lopes-felipe** [open-telemetry/opentelemetry-collector-contrib#35934]
### Component(s)

processor/span

### Is your feature request related to a problem? Please describe.

Currently, this processor's span transformation capabilities are based on regex and/or attribute names without any contextual awareness of their origin (e.g., SQL Query, Redis Command, Web Request, etc.). 

This makes it hard to apply more complex processing logic, such as removing comments or collapsing parameters for `IN-clauses` ([ref](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md#sanitization-of-dbquerytext)), as well as extracting any common attribute defined by the semantic conventions ([ref](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/trace.md)).

### Describe the solution you'd like

The ability to apply transformation logic to the spans, based on a configuration. Ex:
```
span:
  name:
    sql:
      comments: <keep|remove>
      alias: <keep|remove> # whether SQL aliases ("AS") should be truncated
      space_between_parentheses: <keep|remove> # IN ( ? ) | IN (?)
      ...
  attributes:
    sql:
      table_name: <insert|upsert> # db.collection.name (users; dbo.products)
      operation: <insert|upsert> # db.operation.name (SELECT; INSERT; UPDATE; DELETE; CREATE; mystoredproc)
      query_summary: <insert|update> # db.query.summary (SELECT orders; INSERT shipping_details; UPDATE users)
      ...
```

### Additional context

This feature is based on [this](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35593) Datadog-specific obfuscation process PR. However, the idea here is to provide something similar but much more flexible, complete, and vendor-agnostic. 

I can definitely take this, if approved :)
