### ISSUE TITLE
support include/exclude filtering for the resource processor

### ISSUE THREAD

**Issue by kosamson** [open-telemetry/opentelemetry-collector-contrib#35949]
### Component(s)

processor/resource

### Is your feature request related to a problem? Please describe.

While signals can be [included/excluded from the attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/README.md#includeexclude-filtering), there is no similar option in the [resource processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourceprocessor/README.md). This can be inconvenient at times if there are some signals that need to have their resource attributes updated, but other signals that need to preserve their original resource attributes.

### Describe the solution you'd like

It would be nice if the resource processor config allowed using [include/exclude matching](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/README.md#includeexclude-filtering) from the attributes processor.

### Describe alternatives you've considered

A workaround to this is by configuring one signal pipeline which includes the resource processor, and another pipeline which does not include the resource processor. The signals that need resource attribute processing would be ingested from one receiver, and those that do not need it from a different receiver.

This causes some duplicated configuration and requires a client-side change (which sends data to the collector) to use a different receiver port, which is not ideal, 

See the below example:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  otlp/modifiedresource:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14317
processors:
  attributes:
    actions:
      - key: environment
        value: production
        action: insert
  resource:
    attributes:
      - key: cloud.zone
        value: zone-1
        action: upsert
exporters:
  otlp:
    endpoint: otelcol:4317
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [otlp]
    traces/modifiedresource:
      receivers: [otlp/modifiedresource]
      processors: [attributes, resource]
      exporters: [otlp]
```
