### ISSUE TITLE
keep_matching_keys function not working with metric context

### ISSUE THREAD

**Issue by Shindek77** [open-telemetry/opentelemetry-collector-contrib#35956]
### Describe the issue you're reporting

Hello Community, 
is **keep_matching_keys** ottl function doest not work for **metric context** as i am using it but it is not working properly. Gives error on otel as **processors::transform/test: unable to parse OTTL statement "keep_matching_keys(attributes,"^(url|http|service|cloud|event).")": undefined function "keep_matching_keys" .** Please help me on this 
```
transform/test:
  metric_statements:
  - context: metric
    statements:
    - keep_matching_keys(attributes, "^(url|http|service|cloud|event).")
    - keep_matching_keys(resource.attributes, "^(url|http|service|cloud|event).*").
```
