### ISSUE TITLE
duplicate logs are sent on timestamp parsing error

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#35973]
### Component(s)

pkg/stanza

## Description

Duplicate logs will be sent on time parser error.

## Steps to Reproduce

This can be reproduced with any logs with time parser enabled, configured with a different time format than the logs.

## Expected Result

No duplication.

### Collector version

v0.111.0

### Additional context

1. entry is passed to `p.HandleEntryError` method: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/helper/parser.go#L171-L184
2. as long as `send` or `send_quite` is used, in the method the entry will be emitted, which causes this duplication: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/stanza/operator/helper/transformer.go#L103

It looks like duplication happens on any of these special parser errors.

**Comment by newly12** [comment]
cc @djaglowski @ChrsMark

**Comment by ChrsMark** [comment]
Hmm, error handling there is becoming tricky (related to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35726).

However I could not reproduce this one @newly12.

I use the following configuration:

```yaml
receivers:
  filelog:
    start_at: end
    include_file_path: true
    include:
    - /var/log/some/mute.log
    operators: 
      - id: some1
        type: add
        field: attributes.timestamp
        value: "Jun 5 13:50:27 EST 2020"
      - id: some
        type: time_parser
        parse_from: attributes.timestamp
        layout_type: strptime
        layout: '%a %b %e %H:%M:%S %Z %Y'
        on_error: send 

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [debug]
      processors: []
```
And then I only see one log emitted. Do I miss anything here?
@newly12 if you could provide some minimal configuration sample and steps to reproduce the issue that would helpful.

**Comment by newly12** [comment]
Thanks for the quick turnaround :) 

Yes I had a different config,  not sure if it is related to the embedded timestamp parser, here is my config.
```yaml
exporters:
  debug:
    verbosity: detailed
    sampling_initial: 100

receivers:
  filelog:
    include: [ /tmp/json.log ]
    fingerprint_size: 16
    operators:
      - type: json_parser
        id: json
        on_error: send_quiet
        timestamp:
          parse_from: attributes.timestamp
          layout_type: gotime
          layout: Mon Jan 02 15:04:05 MST 2006

service:
  telemetry:
    metrics:
      level: detailed
  pipelines:
    logs:
      receivers: [ filelog ]
      exporters: [ debug ]
```

`/tmp/json.log` - please notice the log is too small(for this testing), if I create it before I start the collector, nothing shown in the otel output, so you may need to start collector process first and then create this log file.
```
{"timestamp": "123", "message": "xxxxxxxxxxxx"}
```

otel collector logs
```
2024-10-24T21:22:09.951+0800	info	ResourceLog #0
Resource SchemaURL: 
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope  
LogRecord #0
ObservedTimestamp: 2024-10-24 13:22:09.852174 +0000 UTC
Timestamp: 1970-01-01 00:00:00 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Str({"timestamp": "123", "message": "xxxxxxxxxxxx"})
Attributes:
     -> log.file.name: Str(json.log)
     -> timestamp: Str(123)
     -> message: Str(xxxxxxxxxxxx)
Trace ID: 
Span ID: 
Flags: 0
LogRecord #1
ObservedTimestamp: 2024-10-24 13:22:09.852174 +0000 UTC
Timestamp: 1970-01-01 00:00:00 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Str({"timestamp": "123", "message": "xxxxxxxxxxxx"})
Attributes:
     -> log.file.name: Str(json.log)
     -> timestamp: Str(123)
     -> message: Str(xxxxxxxxxxxx)
Trace ID: 
Span ID: 
Flags: 0
	{"kind": "exporter", "data_type": "logs", "name": "debug"}
```
