### ISSUE TITLE
[processor/resource] Add support for profiles signal

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#35979]
### Component(s)

processor/resource

### Describe the issue you're reporting

This processor would be useful for testing and validation of the experimental profiling signal.

As inspiration for how to add support this PR can be used: open-telemetry/opentelemetry-collector/pull/11071 (there is no processor with support as of the writing of this issue)

Example of configuration using profiles (needs `service.profilesSupport` [feature gate](https://github.com/open-telemetry/opentelemetry-collector/blob/main/featuregate/README.md#controlling-gates) to be enabled):

```yaml
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp:
    endpoint: ${OTLP_ENDPOINT}
service:
  pipelines:
    profiles:
      receivers: [otlp]
      exporters: [otlp]
```
