### ISSUE TITLE
[exporter/file] Add support for profiles signal

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#35978]
### Component(s)

exporter/file

### Describe the issue you're reporting

This exporter would be useful for testing and validation of the experimental profiling signal.

As inspiration for how to add support this PR can be used: open-telemetry/opentelemetry-collector/pull/11435

Example of configuration using profiles (needs `service.profilesSupport` [feature gate](https://github.com/open-telemetry/opentelemetry-collector/blob/main/featuregate/README.md#controlling-gates) to be enabled):

```yaml
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp:
    endpoint: ${OTLP_ENDPOINT}
service:
  pipelines:
    profiles:
      receivers: [otlp]
      exporters: [otlp]
```
