### ISSUE TITLE
[receiver/awsfirehosereceiver] Support receiving multiple record type using single endpoint

### ISSUE THREAD

**Issue by kaiyan-sheng** [open-telemetry/opentelemetry-collector-contrib#35988]
### Component(s)

receiver/awsfirehose

### Is your feature request related to a problem? Please describe.

When trying to ingest both logs and metrics from Firehose, I tried with two receivers configured with the same endpoint:
```
receivers:
      awsfirehose/cwmetrics:
        endpoint: {{ (.Values.receiver).hostname | default "localhost"}}:4433
        include_metadata: true
        record_type: cwmetrics
      awsfirehose/cwlogs:
        endpoint: {{ (.Values.receiver).hostname | default "localhost"}}:4433
        include_metadata: true
        record_type: cwlogs
```
This gave me an error:
```
2024-10-23T20:01:59.169Z	error	graph/graph.go:426	Failed to start component	{"error": "listen tcp 127.0.0.1:4433: bind: address already in use", "type": "Receiver", "id": "awsfirehose/cwmetrics"}
```
In order to workaround this issue, I have to use two different endpoints, one for metrics and one for logs.

I would like to have a single endpoint to ingest both metrics and logs.

### Describe the solution you'd like

We should be able to check what does the request from Firehose looks like and figure out if it's logs or metrics, if it's JSON format metrics or OTEL1.0 format metrics and then apply the right marshaling.

**Comment by Aneurysm9** [comment]
I would strongly recommend simply using different ports for each signal type.  The collector requires [unique component instances per signal type](https://github.com/open-telemetry/opentelemetry-collector/pull/8169#discussion_r1283727573), even for components that support multiple signal types, and the mechanism used by the OTLP receiver to support multiple signal types on the same port is generally [considered a hack](https://github.com/open-telemetry/opentelemetry-collector/issues/10534) and [may not be supported](https://github.com/open-telemetry/opentelemetry-collector/issues/11622#issuecomment-2465001214) going forward.

Beyond that, the type of configuration presented in the issue description here doesn't really fit in with the `sharedcomponent` model, which expects the same configuration of the component to be used for multiple signal types by allowing signal type-specific instances to share an HTTP handler.

**Comment by axw** [comment]
> Beyond that, the type of configuration presented in the issue description here doesn't really fit in with the sharedcomponent model, which expects the same configuration of the component to be used for multiple signal types by allowing signal type-specific instances to share an HTTP handler.

Agreed, I think @kaiyan-sheng was just showing what she tried to configure. It fails of course because two instances of the receiver cannot bind to the same host:port.

The proposal would be to either get rid of the `record_type` config setting, or introduce something like `record_type: auto`, and determine the record type from the data: check for CloudWatch JSON/OTLP metrics, and otherwise treat the data as logs.

Minimal config would be something like:

```yaml
receivers:
  awsfirehose:
    endpoint: hostname:1234
```

So there would be no requirement for multiple receiver instances.
