### ISSUE TITLE
[pkg/ottl] truncate_all function corrupts UTF-8 encoding

### ISSUE THREAD

**Issue by mugli** [open-telemetry/opentelemetry-collector-contrib#36017]
### Component(s)

pkg/ottl

## Description
The `truncate_all` OTTL function truncates the string (UTF-8 encoded byte slice in Go) without checking if it breaks multi-byte UTF-8 codepoints in the middle. So using the `transform` processor with `truncate_all` often results in corrupted UTF-8 values.

Here's the code: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ed099909a87ac3d51f577b9e86e15369481861a3/pkg/ottl/ottlfuncs/func_truncate_all.go#L50 

(It looks like opentelemetry-go SDK had a similar problem which is fixed now: https://github.com/open-telemetry/opentelemetry-go/issues/3160)

**Impact:**
While the collector or a chain of collectors usually works fine with the corrupted UTF-8 down the line (https://github.com/open-telemetry/opentelemetry-collector/issues/11449), some components fail:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35723
- Entire batch gets dropped: https://github.com/open-telemetry/oteps/pull/257#pullrequestreview-2070923423 
(We are seeing similar behavior with one of the vendors too. They drop the entire batch if anything contains an invalid UTF-8 string)

## Steps to Reproduce
The `truncate_all` slicing code should be self-explanatory that it doesn't handle `rune`.

## Expected Result
`truncate_all` will slice the string _up to_ the given length. If truncating at exactly the length results in a broken UTF-8 encoding, it'll truncate _before_ where the last `rune` started.

## Actual Result
`truncate_all` slices UTF-8 encoded string without checking if it breaks a multi-byte character in the middle.
This results in the entire batch getting dropped on the vendor side.

### Collector version

v0.111.0

## Environment
This applies to all environment

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
  transform:
    trace_statements:
      - context: span
        statements:
        - truncate_all(attributes, 4095)
        - truncate_all(resource.attributes, 4095)
exporters:
  otlphttp:
    endpoint: https://otlp.nr-data.net
    headers:
      api-key: $NEW_RELIC_API_KEY
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [otlphttp]
```
