### ISSUE TITLE
[exporter/loadbalancing] Panic when exporting and scraping prometheus metrics

### ISSUE THREAD

**Issue by uristernik** [open-telemetry/opentelemetry-collector-contrib#36012]
### Component(s)

exporter/prometheus

## Description
We are implementing a pipeline where we:
generate span metrics with spanmetrics plugin --> exposing the metrics with prometheus plugin in port 9091 --> have a prometheus server scrape the metrics on this port

We are seeing occasionaly the following panic `panic: send on closed channel`. 
This doesn't appear to happen when we are not scraping the metrics, I am still working locally to repro.

Attaching full stack trace below

## Steps to Reproduce
I am still trying to isolate the issue and find how to accurately reproduce, this seems to be related to heavy load as well. Attaching the configuration we are running in the agent.

## Expected Result
No panics at all

## Actual Result
Occasional panics

### Collector version

v0.94.0

## Environment
Running as a DaemonSet in EKS cluster version v1.29.8-eks-a737599
OS: Amazon Linux 2

### OpenTelemetry Collector configuration

```yaml
connectors:
    spanmetrics:
      aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
      resource_metrics_key_attributes:
        - service.name
      histogram:
        explicit:
          buckets: [2ms, 4ms, 6ms, 8ms, 10ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1s, 1400ms, 2s, 5s, 10s, 15s]
  exporters:
    prometheus:
      endpoint: 0.0.0.0:9091
    debug:
      verbosity: basic
    loadbalancing/traces:
      resolver:
        k8s:
          service: opentelemetry-collector.default
      protocol:
        otlp:
          tls:
            insecure: true
          retry_on_failure:
            enabled: true
            max_interval: 5s
            max_elapsed_time: 30s
          sending_queue:
            enabled: true
            num_consumers: 20
            queue_size: 50000
          timeout: 20s
    file/logs:
      path: /dev/null
    file/traces:
      path: /dev/null
  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"
  processors:
    filter/fastpath:
      # if any condition is met, the telemetry is dropped (each condition is ORed together)
      traces:
        span:
        - (end_time - start_time) < Duration("1ms")
    batch:
      send_batch_max_size: 64
      send_batch_size: 64
      timeout: 50ms
    batch/big:
      timeout: 60s
    batch/med:
      timeout: 15s
    batch/small:
      timeout: 1s
    memory_limiter:
      # Maximum amount of total memory targeted to be allocated by the process
      # This defines the hard limit
      limit_percentage: 95
      # Maximum spike expected between the measurements of memory usage.
      # The value must be less than limit_mib.
      # The soft limit value will be equal to (limit_mib - spike_limit_mib).
      # The recommended value for spike_limit_mib is about 20% limit_mib.
      spike_limit_percentage: 10
      check_interval: 1s
    resource:
      attributes:
      - action: insert
        key: k8s.node.name
        value: ${K8S_NODE_NAME}
    resource/add_environment:
      attributes:
        - action: insert
          value: test
          key: deployment.environment
  receivers:
    otlp:
      protocols:
        grpc:
          max_recv_msg_size_mib: 32
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
        - job_name: opentelemetry-agent
          scrape_interval: 10s
          static_configs:
          - targets:
            - ${K8S_POD_IP}:9090
  service:
    telemetry:
      logs:
        level: INFO
        encoding: json
        initial_fields:
          service: opentelemetry-agent
        sampling:
          enabled: true
          tick: 60s
          initial: 3
          thereafter: 0
      metrics:
        address: 0.0.0.0:9090
    extensions:
    - health_check
    pipelines:
      metrics/spanmetrics:
        exporters:
        - prometheus
        processors:
        - batch/small
        receivers:
        - spanmetrics
      traces:
        exporters:
        - loadbalancing/traces
        - spanmetrics
        processors:
        - memory_limiter
        - filter/fastpath
        - resource
        - resource/add_cluster_name
        - resource/add_environment
        - batch
        receivers:
        - otlp
  enabled: true
```

### Log output

```shell
panic: send on closed channel

goroutine 32 [running]:
go.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Offer(...)
go.opentelemetry.io/collector/exporter@v0.94.1/internal/queue/bounded_memory_queue.go:43
go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).send(0x40046fce40, {0x878ca98, 0x400226e8d0}, {0x87418f0, 0x4002588258})
go.opentelemetry.io/collector/exporter@v0.94.1/exporterhelper/queue_sender.go:154 +0xb4
go.opentelemetry.io/collector/exporter/exporterhelper.(*baseExporter).send(0x40021cd900, {0x878ca98?, 0x400226e8d0?}, {0x87418f0, 0x4002588258})
go.opentelemetry.io/collector/exporter@v0.94.1/exporterhelper/common.go:199 +0x48
go.opentelemetry.io/collector/exporter/exporterhelper.NewTracesExporter.func1({0x878ca98, 0x400226e8d0}, {0x4001d93dd0?, 0x4007aa0594?})
go.opentelemetry.io/collector/exporter@v0.94.1/exporterhelper/traces.go:99 +0xb4
go.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces(...)
go.opentelemetry.io/collector/consumer@v0.94.1/traces.go:25
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.(*traceExporterImp).consumeTrace(0x4007b28c78?, {0x878ca98, 0x400226e8d0}, 0xa?)
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter@v0.94.0/trace_exporter.go:134 +0x188
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter.(*traceExporterImp).ConsumeTraces(0x400225daa0, {0x878ca98, 0x400226e8d0}, {0x4001d934d0?, 0x4008845d38?})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter@v0.94.0/trace_exporter.go:121 +0x164
go.opentelemetry.io/collector/internal/fanoutconsumer.(*tracesConsumer).ConsumeTraces(0x40?, {0x878ca98, 0x400226e8d0}, {0x4001d934d0?, 0x4008845d38?})
go.opentelemetry.io/collector@v0.94.1/internal/fanoutconsumer/traces.go:71 +0xa8
go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).export(0x400188f500, {0x878ca98, 0x400226e8d0}, 0x40?, 0x0)
go.opentelemetry.io/collector/processor/batchprocessor@v0.94.1/batch_processor.go:407 +0x168
go.opentelemetry.io/collector/processor/batchprocessor.(*shard).sendItems(0x400188f700, 0x2)
go.opentelemetry.io/collector/processor/batchprocessor@v0.94.1/batch_processor.go:256 +0x54
go.opentelemetry.io/collector/processor/batchprocessor.(*shard).processItem(0x400188f700, {0x728cd40?, 0x400820b420?})
go.opentelemetry.io/collector/processor/batchprocessor@v0.94.1/batch_processor.go:230 +0x48
go.opentelemetry.io/collector/processor/batchprocessor.(*shard).start(0x400188f700)
go.opentelemetry.io/collector/processor/batchprocessor@v0.94.1/batch_processor.go:215 +0x13c
created by go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).newShard in goroutine 1
go.opentelemetry.io/collector/processor/batchprocessor@v0.94.1/batch_processor.go:160 +0x174
Setting up own telemetry...
Serving metrics
Building spanmetrics connector
Using percentage memory limiter
Memory limiter configured
Starting otelcontribcol...
Starting extensions...
Extension is starting...
Starting health_check extension
Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks. Enable the feature gate to change the default and remove this warning.
Extension started.
Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks. Enable the feature gate to change the default and remove this warning.
Starting spanmetrics connector
Using the 0.0.0.0 address exposes this server to every network interface, which may facilitate Denial of Service attacks. Enable the feature gate to change the default and remove this warning.
Starting GRPC server
Starting HTTP server
Health Check state change
Everything is ready. Begin running and processing data.
The default endpoints for all servers in components will change to use localhost instead of 0.0.0.0 in a future version. Use the feature gate to preview the new default.
```
