### ISSUE TITLE
Dropping lables configured in scraping config drops more metrics than requested

### ISSUE THREAD

**Issue by xzizka** [open-telemetry/opentelemetry-collector-contrib#36061]
### Component(s)

receiver/prometheus

## Description

> This is very much related to the issue mentioned here: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36060
> The environment is the same, the only difference is the config.

The scraping is configured like this:
```
...
          scrape_configs:
          - job_name: integrations/kubernetes/kubelet
            scrape_interval: 15s
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
                - role: node
            metric_relabel_configs:
                - source_labels: [__name__]
                  regex: '(kubelet_pleg_relist_duration_seconds_bucket|kubelet_pleg_relist_duration_seconds_count|kubelet_pleg_relist_interval_seconds_.*)'
                  action: keep
                - action: labeldrop
                  regex: container_id|id|image_id|uid
            relabel_configs:
...
```
This scraping should return the following metrics:
- kubelet_pleg_relist_interval_seconds_count
- kubelet_pleg_relist_interval_seconds_sum
- kubelet_pleg_relist_interval_seconds_bucket
- kubelet_pleg_relist_duration_seconds_bucket 
- kubelet_pleg_relist_duration_seconds_count

These metrics are then visible in Prometheus:
![image](https://github.com/user-attachments/assets/585549a8-718c-48c2-b990-78e58fb69a21)

Debug output from the collector log.
```
testuser@testvm:~/otel-logs $ kubectl logs -l component=otel-collector --follow | grep pleg
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_interval_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_interval_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_interval_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_interval_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_interval_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_interval_seconds
     -> Name: kubelet_pleg_relist_interval_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_interval_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
...
```

If I add a drop action to the scraping for _kubelet_pleg_relist_interval_seconds_count_ and _kubelet_pleg_relist_interval_seconds_sum_:
```
...
          scrape_configs:
          - job_name: integrations/kubernetes/kubelet
            scrape_interval: 15s
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
                - role: node
            metric_relabel_configs:
                - source_labels: [__name__]
                  regex: '(kubelet_pleg_relist_duration_seconds_bucket|kubelet_pleg_relist_duration_seconds_count|kubelet_pleg_relist_interval_seconds_.*)'
                  action: keep
                - action: labeldrop
                  regex: container_id|id|image_id|uid
                - source_labels: [__name__]
                  regex: '(kubelet_pleg_relist_interval_seconds_count|kubelet_pleg_relist_interval_seconds_sum)'
                  action: drop
            relabel_configs:
...
```
Then all the kubelet_pleg_relist_interval_seconds_.+ metrics are removed and not visible in Prometheus/Grafana.
![image](https://github.com/user-attachments/assets/d996dcc6-5108-49ba-8747-31e177d3ffba)

Debug output from the collector log.
```
testuser@testvm:~/otel-logs $ kubectl logs -l component=otel-collector --follow | grep pleg
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
     -> Name: kubelet_pleg_relist_duration_seconds
...
```
## Steps to Reproduce
Use the config above for opentelemetry-contrib metrics collection.

## Expected Result
To drop just the requested metrics.

## Actual Result
Instead of dropping just kubelet_pleg_relist_interval_seconds_count and kubelet_pleg_relist_interval_seconds_sum metric also kubelet_pleg_relist_interval_seconds_bucket is dropped.

### Collector version

0.112.0-amd64

## Environment
K8S 1.29
K8S 1.30

### OpenTelemetry Collector configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-monitoring-collector-conf
  namespace: otel-system
  labels:
    app: opentelemetry
    component: otel-monitoring-collector-conf
data:
  otel-monitoring-collector-config: |
    exporters:
      prometheusremotewrite:
        endpoint: https://prometheus-dev:28080/api/v1/push
        tls:
          insecure_skip_verify: true
        headers: 
          X-Scope-OrgID: k8s-nprod-otel
        external_labels:
          cluster: "k8s-nprod-2856"
          otel_component: "otel-collector"
      debug/metrics:
        verbosity: detailed
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: integrations/kubernetes/kubelet
            scrape_interval: 15s
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
                - role: node
            metric_relabel_configs:
                - source_labels: [__name__]
                  regex: '(kubelet_pleg_relist_duration_seconds_bucket|kubelet_pleg_relist_duration_seconds_count|kubelet_pleg_relist_interval_seconds_.*)'
                  action: keep
                - action: labeldrop
                  regex: container_id|id|image_id|uid
            relabel_configs:
                - replacement: kubernetes.default.svc.cluster.local:443
                  target_label: __address__
                - regex: (.+)
                  replacement: /api/v1/nodes/$${1}/proxy/metrics
                  source_labels:
                    - __meta_kubernetes_node_name
                  target_label: __metrics_path__
            scheme: https
            tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
                server_name: kubernetes
    processors:
      batch/metrics:
      memory_limiter/metrics:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 20
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter/metrics, batch/metrics]
          exporters: [debug/metrics, prometheusremotewrite]
```

### Log output

```shell
Logs are mentioned in the description part of this issue.
```

### Additional context

If we call the scraping with Prometheus agent, it works as expected.
