### ISSUE TITLE
[receiver/prometheus] static scape config doesn't work with Target Allocator

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector-contrib#36062]
### Component(s)

receiver/prometheus

## Description

Duplicate of https://github.com/open-telemetry/opentelemetry-operator/issues/3034

If you set both static scrape config and Target Allocator. Your static config will be ignored
## Steps to Reproduce

```
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 30s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
        target_allocator:
          collector_id: ${env:MY_POD_NAME}
          endpoint: http://opentelemetry-targetallocator
          interval: 30s
```

## Expected Result

Collector metrics to be scraped

## Actual Result

No Collector metrics are scraped

### Collector version

v0.112.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 30s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
        target_allocator:
          collector_id: ${env:MY_POD_NAME}
          endpoint: http://opentelemetry-targetallocator
          interval: 30s
```
