### ISSUE TITLE
"Error decoding 'exporters': unknown type 'doris' for id 'doris' - Unsupported Exporter Type"

### ISSUE THREAD

**Issue by LiuS1mple** [open-telemetry/opentelemetry-collector-contrib#36085]
### Component(s)

exporter/doris

## Description
Encountered an error when configuring exporters: `error decoding 'exporters': unknown type: "doris" for id: "doris"`. It seems that "doris" is not recognized as a valid exporter type. 

## Steps to Reproduce
1. Configure "doris" as an exporter in the configuration file.
2. Deploy the collector with the new configuration.
3. Observe the error message upon startup.

## Expected Result
Since release 0.110.0 includes support for the "doris" exporter type, the collector should recognize "doris" as a valid exporter and start without issues.

## Actual Result
error decoding 'exporters': unknown type: "doris" for id: "doris"

### Collector version

0.112.0

## Environment
OS :Debian 6.1.85-1
Docker Image:  `opentelemetry/opentelemetry-collector:0.112.0`
Compiler: N/A (using pre-built Docker image from Docker Hub, no manual compilation)

### OpenTelemetry Collector configuration

```yaml
exporters:
      debug:
        verbosity: detailed
      doris:
        endpoint: http://192.168.0.189:8030
        database: otel
        username: admin
        password: admin
        table:
          logs: otel_logs
          traces: otel_traces
          metrics: otel_metrics
        create_schema: true
        mysql_endpoint: 192.168.0.189:9030
        history_days: 0
        create_history_days: 0
        replication_num: 1
        timezone: Asia/Shanghai
        timeout: 5s
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 1000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
```

### Log output

```shell
error decoding 'exporters': unknown type: "doris" for id: "doris" (valid values: [otelarrow prometheus sentry signalfx otlphttp googlemanagedprometheus awskinesis otlp alibabacloud_logservice influxdb opensearch sumologic awsemf carbon clickhouse dataset elasticsearch googlecloudpubsub kafka loadbalancing azuredataexplorer cassandra logzio zipkin azuremonitor prometheusremotewrite pulsar debug awscloudwatchlogs file loki opencensus tencentcloud_logservice nop coralogix honeycombmarker mezmo rabbitmq awss3 datadog logicmonitor sapm splunk_hec syslog awsxray googlecloud])
```
