### ISSUE TITLE
filelog receiver reads old logs even when start_at is set to end

### ISSUE THREAD

**Issue by obs-gh-enricogiorio** [open-telemetry/opentelemetry-collector-contrib#36091]
Hi @djaglowski I am still an issue where filelog starts reading from beginning of files despite a fix that was mentioned in [this other issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24839).
That issue mentions that when the max concurrent files is reached, the receiver enters "batch" mode, and starts reading from the beginning of the files, regardless of what "start_at" is set to.
I made sure `start_at` is set to `end` and I have checked the receiver's logs, nothing mentions that any batching happened.
Also given the amount of log files I have in the system, I can pretty much ensure that the default limit of 1024 concurrent files has ever been reached.

For instance, on `16/10/24 13:22:24.363 CEST`, the receiver read a log line with timestamp `14/05/24 14:40:41.042 CEST`, which is >5 months old.
<img width="1386" alt="image" src="https://github.com/user-attachments/assets/6c568370-39a1-443e-8f75-8732d66ad72e">

From this screenshot you can see:

BUNDLE_TIMESTAMP is when the log line was parsed (technically it's when it reached our system, but it's likely just a few seconds earlier)
timestamp is the log's timestamp
delta is the discrepancy between the two. The logs you see are 4 months old
The purple bits above are when the data falls over time. You can see that this did not happen constantly but only twice, with many instances of very old logs being read all together

This is how I configured the receiver:
```
  filelog:
    exclude:  '[]'
    include:  '["/var/log/pods/*/*/*.log", "/var/log/kube-apiserver-audit.log"]'
    include_file_name: false
    include_file_path: true
    exclude_older_than: 24h
    operators:
    - id: container-parser
      max_log_size: 102400
      type: container
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval:  30s
      max_elapsed_time: 5m
    start_at: "end"
    storage: file_storage
```
