### ISSUE TITLE
[receiver/kafka] 

### ISSUE THREAD

**Issue by dyanneo** [open-telemetry/opentelemetry-collector-contrib#36093]
### Component(s)

receiver/kafka

## Description
The value of `last` for the measurement `otelcol_kafka_receiver_offset_lag` does not appear to be calculated correctly.
Also, for context, we are seeing an issue in the otel collector where it keeps emitting lag metrics for partitions it's no longer consuming.
- We understand that topic is not present as a tag in this metric, per [issue 35336](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35336)

## Steps to Reproduce
***WIP***

### Per this screen shot, the value of partition 4's lag as shown using kafka's consumer-groups.sh utility changes over time, and is in the low hundreds or smaller:
![Screenshot 2024-10-30 at 10 19 19 AM](https://github.com/user-attachments/assets/faa66da6-fd46-469c-8074-6429d918ed51)
- you can see starting and ending offsets and the calculated lag of 117, 74, 112, and 129

### Per this screen shot, the value of partition 4's lag does not match what true lag is, per kafka's tools:
![Screenshot 2024-10-30 at 10 31 03 AM](https://github.com/user-attachments/assets/ace79253-fdb4-4abb-a4d9-23cf613a9de7)
#### Query in Grafana query builder:
![Screenshot 2024-10-30 at 10 21 27 AM](https://github.com/user-attachments/assets/54409ec6-1483-4fe5-a3ec-0e5da28c8e46)
#### Query as Grafana is running it:
![Screenshot 2024-10-30 at 10 22 00 AM](https://github.com/user-attachments/assets/d8f1cda5-9bb3-4090-a3f6-2d67c008bc24)

### Collector version

otelcol_version: 0.109.0

## Environment
***WIP***

### OpenTelemetry Collector configuration

```yaml
---
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:PORT
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector-metrics
          scrape_interval: 30s
          static_configs:
            - targets: ["127.0.0.1:PORT"]

processors:
  memory_limiter:
    check_interval: 1ms
    limit_percentage: 70
    spike_limit_percentage: 15

  resource:
    attributes:
      - key: application
        from_attribute: service.name
        action: insert

  resource/internal:
    attributes:
      - key: labels.application
        value: ${env:CLOUD_APPLICATION}
        action: upsert
      - key: application
        value: ${env:CLOUD_APPLICATION}
        action: upsert
      
  filter/application:
    error_mode: ignore
    traces:
      span:
        - 'resource.attributes["application"] == nil'
    metrics:
      metric:
        - 'resource.attributes["application"] == nil'

  filter/tracingsampler:
    error_mode: ignore
    traces:
      span:
        - 'attributes["sampler.parent"] == nil'

  filter/summarytype:
    error_mode: ignore
    metrics:
      metric:
        - "type == METRIC_DATA_TYPE_SUMMARY"

  metricstransform/version_correction:
    transforms:
      - match_type: strict
        include: tgt.otel.extension.heartbeat
        action: update
        operations:
          - action: update_label
            label: otel.extension.version
            value_actions:
              - value: "v0.8.0\n"
                new_value: "v0.8.0"
          - action: update_label
            label: otel.scope.version
            value_actions:
              - value: "v0.8.0\n"
                new_value: "v0.8.0"

  batch/metrics:
    timeout: 5s
    send_batch_size: 100
    send_batch_max_size: 101

  batch/traces:
    timeout: 5s
    send_batch_size: 33
    send_batch_max_size: 34

exporters:
  tgtkafkaexporter:
    brokers:
      - BROKER_REDACTED
    topic: TOPIC_REDACTED
    protocol_version: 2.7.0
    encoding_extension: tgtinflux_encoding
    producer:
      compression: snappy
      max_message_bytes: 2000000

  kafka:
    brokers:
      - BROKER_REDACTED
    topic: TOPIC_REDACTED
    protocol_version: 2.7.0
    producer:
      compression: snappy
      max_message_bytes: 2000000

service:
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource
        - filter/application
        - filter/summarytype
        - metricstransform/version_correction
        - batch/metrics
      exporters:
        - tgtkafkaexporter

    metrics/internal:
      receivers:
        - prometheus
      processors:
        - resource
        - resource/internal
        - filter/application
        - filter/summarytype
        - metricstransform/version_correction
        - batch/metrics
      exporters:
        - tgtkafkaexporter

    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource
        - filter/application
        - filter/tracingsampler
        - batch/traces
      exporters:
        - kafka

  telemetry:
    logs:
      level: "info"
    metrics:
      address: 0.0.0.0:PORT
```

### Log output

```shell
***WIP***
```

### Where this gauge is defined: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0d28558da65cbce23963906dbb3205fa2f383c0c/receiver/kafkareceiver/internal/metadata/generated_telemetry.go#L75-L79

### One of the places where this gauge is updated: 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0d28558da65cbce23963906dbb3205fa2f383c0c/receiver/kafkareceiver/kafka_receiver.go#L560

### Where this _could_ be addressed:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0d28558da65cbce23963906dbb3205fa2f383c0c/receiver/kafkareceiver/kafka_receiver.go#L529-L531
