### ISSUE TITLE
[Prometheus Receiver] Prometheus Receiver configuration failing with new 0.112.0 (latest)

### ISSUE THREAD

**Issue by developer1622** [open-telemetry/opentelemetry-collector-contrib#36160]
### Component(s)

receiver/prometheus

## Description
Thank you.
Previously following scrape config used to work fine, but with the new latest changes , I am getting error, attached

```
    receivers:
      prometheus/coredns:
        config:
          scrape_configs:
            - job_name: "dns"
              scrape_interval: 2m
              scrape_timeout: 59s
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - kube-system
              relabel_configs:
                - source_labels:
                    - "__meta_kubernetes_namespace"
                    - "__meta_kubernetes_pod_label_k8s_app"
                  action: keep
                  regex: "kube-system;kube-dns"
                - source_labels:
                    - "__meta_kubernetes_pod_container_port_name"
                  action: keep
                  regex: "metrics"
                - source_labels: [ __meta_kubernetes_pod_ip, __meta_kubernetes_pod_container_port_number ]
                  action: replace
                  target_label: __address__
                  regex: (.*);(.*)
                  replacement: $$1:$$2
```

## Steps to Reproduce

Run the above scrape config, results in the error

## Expected Result
No error

## Actual Result

```
failed to get config: cannot resolve the configuration: cannot convert the confmap.Conf: environment variable "2" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$
```

### Collector version

v0.112.0

## Environment

OS: (e.g., "Ubuntu 22.04")
go version go1.22.8 linux/amd64

### Additional context

Seems like two dollars are not taking correctly. is that the issue ?

failed to get config: cannot resolve the configuration: cannot convert the confmap.Conf: environment variable "2" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$

Thank you
