### ISSUE TITLE
startup and cfg issues with opamp supervisor (last_recv_remote_config.dat, opamp_server_port)

### ISSUE THREAD

**Issue by cforce** [open-telemetry/opentelemetry-collector-contrib#36196]
### Component(s)

cmd/opampsupervisor

### What happened?

I have build collector and supervisor based on tag 0.112.0 and observed following issues

```
user@:~/collector# ./supervisor --config=supervisor.yaml
{"level":"info","ts":1730782759.1137323,"caller":"supervisor/supervisor.go:202","msg":"Supervisor starting","id":"0192fab1-0864-75df-8ee0-a58b065f70e2"}
{"level":"info","ts":1730782759.1137323,"caller":"supervisor/supervisor.go:202","msg":"Supervisor starting","id":"0192fab1-0864-75df-8ee0-a58b065f70e2"}
{"level":"error","ts":1730782759.1138253,"caller":"supervisor/supervisor.go:778","msg":"error while reading last received config","error":"open last_recv_remote_config.dat: no such file or directory","stacktrace":"github.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor.(*Supervisor).loadAndWriteInitialMergedConfig\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/supervisor.go:778\ngithub.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor.(*Supervisor).Start\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/supervisor.go:205\nmain.runInteractive\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/main.go:43\nmain.run\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/main_others.go:9\nmain.main\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/main.go:19\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
{"level":"error","ts":1730782759.1138253,"caller":"supervisor/supervisor.go:778","msg":"error while reading last received config","error":"open last_recv_remote_config.dat: no such file or directory","stacktrace":"github.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor.(*Supervisor).loadAndWriteInitialMergedConfig\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/supervisor.go:778\ngithub.com/open-telemetry/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor.(*Supervisor).Start\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/supervisor/supervisor.go:205\nmain.runInteractive\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/main.go:43\nmain.run\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/main_others.go:9\nmain.main\n\t/builds/opentelemetry-collector-contrib/cmd/opampsupervisor/main.go:19\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
{"level":"info","ts":1730782759.1157913,"caller":"supervisor/supervisor.go:989","msg":"No config present, not starting agent."}
{"level":"info","ts":1730782759.1157913,"caller":"supervisor/supervisor.go:989","msg":"No config present, not starting agent."}
```

1.) Looking at the code there might be no toleration of the fact that the file "last_recv_remote_config.dat" is not existing always.
As this might happen on a fresh initial start where no config ever has been downloaded and cached. Is there a test  covering such scenario? 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/740d9aa2ccdd74b825d866486efb507e1282362f/cmd/opampsupervisor/supervisor/supervisor.go#L762

2.) The supervisor shall be fine with 1.) and retry to connect to opamp backend until it is reachable and not write "..not starting agent." : The agent (supervisor to opamp backend client) shall retry to connect continuously and never get in the situation to end up in a failed state where agent is no started. 1.) is no startup fail state - it is a bug i would say. Also in any real "startup fail state" (e.g the supervisor.yaml cfg file can't be read) the supervisor shall terminate itself by exit and not just write error logs. 

3.) But maybe i am misleading the info message "No config present, not starting agent." as actually still the collector  is started but with the wrong opamp port cfg - one that is different than the one what i have configured in the supervisor.yaml

supervisor.yaml
```
agent:
  executable: ./collector
  opamp_server_port: 12548
  health_check_port: 12547
```

After the initial start  of the supervisor  (see 1.) the effective.yaml generated looks like below
As you can see the opamp  sever ports does NOT use the configured "opamp_server_port: 12548" but still uses 
random ports 36455
```
exporters:
    nop: null
extensions:
    health_check:
        endpoint: localhost:12547
    opamp:
        instance_uid: 0192fb21-2782-7c4a-b29a-96d36787d53e
        ppid: 40915
        ppid_poll_interval: 5s
        server:
            ws:
                endpoint: ws://127.0.0.1:36455/v1/opamp
                tls:
                    insecure: true
receivers:
    nop: null
service:
    extensions:
        - health_check
        - opamp
    pipelines:
        logs:
            exporters:
                - nop
            receivers:
                - nop
    telemetry:
        logs:
            encoding: json
        resource:
            host.arch: arm64
            host.name: XXX
            os.description: YYYYY
            os.type: linux
            service.instance.id: 0192fb21-2782-7c4a-b29a-96d36787d53e
            service.name: collector
            service.version: 0.112.0
```

### Collector version

0.112.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### Additional context

related 
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36001 
https://github.com/ArthurSens/opentelemetry-collector-contrib/commit/65992b7312c97864bdf7f9304c3d3a938f9ac8d7
@djaglowski fyi
