### ISSUE TITLE
[exporters/otlphttpexporter] Support for json_log_encoding extension

### ISSUE THREAD

**Issue by mishranant** [open-telemetry/opentelemetry-collector-contrib#36203]
### Component(s)

extension/encoding/jsonlogencoding

### Is your feature request related to a problem? Please describe.

My use-case is to get data from the Kubernetes API, the data I am receiving on http endpoint is like so:
```
  "resourceLogs": [
    {
      "resource": {},
      "scopeLogs": [
        {
          "logRecords": [
            {
              "attributes": [
                {
                  "key": "k8s.resource.name",
                  "value": {
                    "stringValue": "nodes"
                  }
                }
              ],
              "body": {
                "kvlistValue": {
                  "values": [
                    {
                      "key": "spec",
                      "value": {
                        "kvlistValue": {
                          "values": [
                            {
                              "key": "podCIDR",
                              "value": {
                                "stringValue": "10.244.0.0/24"
                              }
                            },
                            {
                              "key": "podCIDRs",
                              "value": {
                                "arrayValue": {
                                  "values": [
                                    {
                                      "stringValue": "10.244.0.0/24"
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "key": "providerID",
                              "value": {
                                "stringValue": "kind://docker/agent/agent-control-plane"
                              }
                            }
                          ]
                        }
                      }
                    },
                      "key": "kind",
                      "value": {
                        "stringValue": "Node"
                      }
                    },
                    {
                      "key": "apiVersion",
                      "value": {
                        "stringValue": "v1"
                      }
                    },
                  ]
                }
              },
              "observedTimeUnixNano": "1730192641520626677",
              "spanId": "",
              "traceId": ""
            }
          ],
          "scope": {}
        }
      ]
    }
  ]
}
```

I want to get the raw event object JSON data instead of OTLP JSON data in the log body. Referring to [this issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25857), I added json_log_extension in my config_map:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcontribcol
  labels:
    app: otelcontribcol
data:
  config.yaml: |
    receivers:
      k8sobjects:
        objects:
        - name: events
          mode: watch
        - name: pods
          mode: pull
          interval: 15m
        - name: configmaps
          mode: pull
          interval: 15m
        - name: cronjobs
          mode: pull
          interval: 15m
        - name: daemonsets
          mode: pull
          interval: 15m
        - name: deployments
          mode: pull
          interval: 15m
        - name: ingresses
          mode: pull
          interval: 15m
        - name: jobs
          mode: pull
          interval: 15m
        - name: namespaces
          mode: pull
          interval: 15m
        - name: nodes
          mode: pull
          interval: 15m
        - name: persistentvolumes
          mode: pull
          interval: 15m
        - name: persistentvolumeclaims
          mode: pull
          interval: 15m
        - name: replicasets
          mode: pull
          interval: 15m
        - name: serviceaccounts
          mode: pull
          interval: 15m
        - name: services
          mode: pull
          interval: 15m
        - name: statefulsets
          mode: pull
          interval: 15m

    exporters:
      otlphttp:
        endpoint: "http://echo-server:8000/client/kube_agent"
        encoding: json
        compression: none
        headers:
          Content-Type: "application/json"

    extensions:
      json_log_encoding:

    service:
      extensions: [json_log_encoding]
      pipelines:
        logs:
          receivers: [k8sobjects]
          exporters: [otlphttp]
```
But that did not help at all. What could be the issue?

### Describe the solution you'd like

If support for json_log_encoding is missing, would request it to be added.
