### ISSUE TITLE
httpcheck receiver configuration failed in v112.0

### ISSUE THREAD

**Issue by sRAVanI417** [open-telemetry/opentelemetry-collector-contrib#36205]
## Steps to Reproduce

Following the document https://opentelemetry.io/blog/2023/synthetic-testing/. 
Please let me know if the httpcheck reciever is custom reciever requiring any additional plugins.
1. In otel collector yaml, add the reciever as below:
recievers:
  httpcheck:
    targets:
      - endpoint: http://example.com
        method: GET
      - endpoint: http://my-app.com
        method: GET
    collection_interval: 10s
    
2. run docker-compose

## Expected Result
3. Otel collector should be up and running

## Actual Result
Recieving below error 

otel-collector-1  | Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):                                                       
otel-collector-1  | 
otel-collector-1  | error decoding 'receivers': unknown type: "httpcheck" for id: "httpcheck" (valid values: [zipkin nop otlp hostmetrics jaeger kafka opencensus prometheus])            
otel-collector-1  | 2024/11/05 12:04:47 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
otel-collector-1  | 
otel-collector-1  | error decoding 'receivers': unknown type: "httpcheck" for id: "httpcheck" (valid values: [zipkin nop otlp hostmetrics jaeger kafka opencensus prometheus])
otel-collector-1 exited with code 1

### Collector version

v112.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: x.y.z.aaaa
      http:
        endpoint: x.y.z.aaaa
  httpcheck:
    targets:
      - endpoint: https://example.com/api-endpoint
        method: GET 
    collection_interval: 10s
# Processors
processors:
  batch:

# Exporters
exporters:
  debug: 
    verbosity: detailed
  otlphttp/logs:
    endpoint: "http://loki:xxxx/otlp"
    tls:
      insecure: true
  otlphttp/traces:
    endpoint: "http://tempo:xxxx"
    tls:
      insecure: true
  prometheus:
    endpoint: otel-collector:8889
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,otlphttp/logs]
    metrics:
      receivers: [otlp, httpcheck]
      exporters: [debug,prometheus]
    traces:
      receivers: [otlp]
      exporters: [debug,otlphttp/traces]
```

### Log output

```shell
otel-collector-1  | Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):                                                       
otel-collector-1  | 
otel-collector-1  | error decoding 'receivers': unknown type: "httpcheck" for id: "httpcheck" (valid values: [zipkin nop otlp hostmetrics jaeger kafka opencensus prometheus])            
otel-collector-1  | 2024/11/05 12:04:47 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
otel-collector-1  | 
otel-collector-1  | error decoding 'receivers': unknown type: "httpcheck" for id: "httpcheck" (valid values: [zipkin nop otlp hostmetrics jaeger kafka opencensus prometheus])
otel-collector-1 exited with code 1
```
