### ISSUE TITLE
Unable to remove automatically added job/instance labels from Prometheus Receiver

### ISSUE THREAD

**Issue by kaushal02** [open-telemetry/opentelemetry-collector-contrib#36245]
### Component(s)

receiver/prometheus

### Description
I'm trying to prevent or remove the automatically added `job` and `instance` labels from metrics collected via the Prometheus receiver, but none of the documented approaches work.

My source metrics look like this:
```
mitigator_connector_rate{datasink="mitigator_api_edge",instance_id="kaushal-local",pipeline="mitigator_unified_api_edge",pool_id="default"} 0.0
```

But after collection through OTEL, they get additional labels:
```
mitigator_connector_rate{datasink="mitigator_api_edge",instance="localhost:9122",instance_id="kaushal-local",job="defender",pipeline="mitigator_unified_api_edge",pool_id="default"} 0.0
```

### Environment
- OpenTelemetry Collector Contrib version: 0.112.0
- Platform: Linux

### Configuration
I've tried multiple approaches to remove these labels, none of which worked:

1. Using metric_relabel_configs:
```yaml
scrape_configs:
  - job_name: 'defender'
    metric_relabel_configs:
      - regex: "job|instance"
        action: labeldrop
```

2. Using honor_labels:
```yaml
scrape_configs:
  - job_name: 'defender'
    honor_labels: true
```

3. Using transform processor:
```yaml
processors:
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - drop_labels(["job", "instance"])
```

4. Using resource processor:
```yaml
processors:
  resource:
    attributes:
      - key: job
        action: delete
      - key: instance
        action: delete
```

5. Using attributes processor:
```yaml
processors:
  attributes:
    actions:
      - key: job
        action: delete
      - key: instance
        action: delete
```

### Expected Behavior
The metrics should be collected and exported without the automatically added `job` and `instance` labels, preserving only the original labels from the source metrics.

### Actual Behavior
The `job` and `instance` labels persist regardless of configuration attempts to remove them.

### Questions
1. Is there a supported way to prevent these labels from being added in the first place?
2. If not, what is the correct approach to remove them?
3. Could the documentation be improved to clarify how to handle this common use case?

### Additional Context
These labels are not needed in our use case and add unnecessary complexity to our metrics. While they don't affect functionality, they make metrics harder to work with and increase cardinality unnecessarily.

### Collector version

0.112.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]
  prometheus:
    config:
      scrape_configs:
        - job_name: 'defender'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:9122']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  prometheus:
    endpoint: "0.0.0.0:9123"

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus]
```

**Comment by bacherfl** [comment]
Hi @kaushal02! 

Just looked into this - I believe the reason those labels can not be removed is because they are added by the `prometheusexporter`, based on the `service.name` and `service.instance.id` attributes of the related resource - see https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/5258d980313cd2af5a7679a4172440a616fd9594/exporter/prometheusexporter/collector.go#L340 

This is specific to the prometheus exporter, as the `job`/`instance` labels are used by the prometheus components to associate a prometheus metric to a OpenTelemetry Resource (i.e. `job <-> service.name` and `instance <-> service.instance.id`) - You can verify this by, e.g. adding the `debug` exporter to the pipeline, and there those two labels are missing - this also explains why e.g. the transform processor did not remove those labels, as they were re-added after the processor.
 I'm not sure however, if it should be possible to remove those two particular labels in the prometheus exporter, given their purpose in establishing the connection to the resource for a given metric. Here I will have to refer to the code owners of the prometheus exporter @dashpole @Aneurysm9 as they have more insights here.

**Comment by dashpole** [comment]
@bacherfl is correct.  If you want to remove those labels, you would need to remove the `service.name` and `service.instance.id` resource attributes (e.g. using the `resource` processor).  However, removing those attributes may make it difficult to use your metrics, and may result in collisions (two timeseries with the exact same list of labels).

**Comment by dashpole** [comment]
feel free to reopen if you have further questions.

**Comment by ovidiubuligan** [comment]
@dashpole I have the same problem with instance having too high cardinality for us and we don't care about instance. We are using the spanmetrics connector and  only care about the high level metrics from the spans.
Using `aggregate_labels` `metricstransform`  also doesn't work with `instance`  also tried it with `status.code` and still doesn't work .

```yaml

# in processors:
  metricstransform/aggregate-span-metrics-labels:
    transforms:
      - include: traces.span.metrics.calls_total
        action: update
        operations:
          # Aggregate by all labels except 'instance'
          - action: aggregate_labels
            label_set: 
              - job
              - service.name
              - span.kind
              - span.name
              - status.code #  tested removing also status.code and still didn't "aggregated  away" 
              - my_custom_dimension
              #...
            aggregation_type: sum

#... in pipelines

    metrics:
      receivers: [spanmetrics] #,servicegraph]
      processors:
        - filter/drop-unwanted-span-metrics # Add the new filter here
        - metricstransform/aggregate-span-metrics-labels
        - batch
      exporters: [otlphttp/prometheus-span-metrics]
``` 

Also having multiple collectors is no problem for me without instance since I can add a new label with the "collector". 

Shouldn't `aggregate_labels` fom `metricstransform` be able to solve this issue ?
