### ISSUE TITLE
resource attributes from container operator are not passed to downstream connector

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-collector-contrib#36254]
### Component(s)

connector/otlpjson, receiver/filelog

### Is your feature request related to a problem? Please describe.

With this setup

```yaml
receivers:
  filelog/otlp-json-logs:
    include:
      - /var/log/pods/*/*/*.log
    include_file_path: true
    operators:
      - id: container-parser
        type: container

connectors:
  otlpjson:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs/raw_otlpjson:
      receivers: [ filelog/otlp-json-logs ]
      processors: [ ]
      exporters: [ otlpjson ]
    logs/otlp:
      receivers: [ otlpjson ]
      processors: [ ]
      exporters: [ debug ]
```

### Describe the solution you'd like

The detected resource attributes from the container parser (e.g. `k8s.container.name`) should be added to the resource attributes of the log entries.

However, there is no way to propagate resource attributes from the file receiver to a connector IIUC.
See https://github.com/open-telemetry/opentelemetry-collector/blob/720f3a86a3de10bc679e3cb8f8f5de4b868455e6/service/internal/graph/graph.go#L296
