### ISSUE TITLE
[cmd/opampsupervisor] Support environment variable expansion in supervisor config

### ISSUE THREAD

**Issue by mrsillydog** [open-telemetry/opentelemetry-collector-contrib#36269]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

Currently, environment variable expansion is not supported in the supervisor configuration. For example, given the following configuration:

```yaml
server:
  endpoint: ${OPAMP_SERVER_ENDPOINT}
agent:
  executable: /bin/otelcontribcol
```

and the following environment variable set:

```bash
echo $OPAMP_SERVER_ENDPOINT
ws://localhost/v1/opamp
```

the final configuration does not expand the referenced environment variable to result in a final configuration of:

```yaml
server:
  endpoint: ws://localhost/v1/opamp
agent:
  executable: /bin/otelcontribcol
```

### Describe the solution you'd like

I'd like to utilize the `go.opentelemetry.io/collector/confmap` Resolver along with the `go.opentelemetry.io/collector/confmap/provider/envprovider` and `go.opentelemetry.io/collector/confmap/provider/fileprovider` Providers to allow for the expansion of environment variables when the supervisor config is read in from file.

### Additional context

I'm happy to implement this enhancement if accepted.

**Comment by VihasMakwana** [comment]
Hi!

Just so you know, `envprovider` will only work if following config is supplied:

```yaml
server:
  endpoint: ${env:OPAMP_SERVER_ENDPOINT}
agent:
  executable: /bin/otelcontribcol
```

notice the env prefix.
