### ISSUE TITLE
[receiver/k8scluster] Invalid image name and tag attributes when containing a digest

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-collector-contrib#36279]
### Component(s)

receiver/k8scluster

## Description

If a container that is being instrumented using the `k8scluster` receiver has been deployed using a container image that contains a cryptographic digest, the receiver produces invalid attributes. The [regex](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/common/docker/images.go#L14) used to parse the container does not apply to images with a digest. 

## Steps to Reproduce

1. Deploy a collector in K8s with the k8scluster receiver enabled
2. Deploy a Pod (as a daemonset or any other deployment strategy) with a container's image that contains a digest. For example (simplified output of a pod description):

```yaml
Containers:
  opentelemetry-collector:
    Container ID:  containerd://6a8fb288d22908242a8508d8625e5a328307a09218a2e659cc9457a0c7a5fe28
    Image:         docker.elastic.co/beats/elastic-agent@sha256:52eeed9e66facc651d4344ef7d9ce912fccff5bb3969e745eed3ab953f309534
    Image ID:      docker.elastic.co/beats/elastic-agent@sha256:52eeed9e66facc651d4344ef7d9ce912fccff5bb3969e745eed3ab953f309534

```

## Expected Result

```yaml
Resource attributes:
     -> container.image.name: Str(docker.elastic.co/beats/elastic-agent)
```

## Actual Result

```yaml
Resource attributes:
     -> container.image.name: Str(sha256)
     -> container.image.tag: Str(a048efd6da2a01c20fb2342b624d740e44a7f651183b017c1962835d9e05186a)
```

### Collector version

v0.112.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
   k8s_cluster:
     auth_type: serviceAccount
    metrics:
      k8s.pod.status_reason:
        enabled: true
```
