### ISSUE TITLE
add directory attribute in file.count metric (filestats receiver)

### ISSUE THREAD

**Issue by josepcorrea** [open-telemetry/opentelemetry-collector-contrib#36274]
### Component(s)

receiver/filestats

### Is your feature request related to a problem? Please describe.

when you want to count the files in a directory, the metric does not show the directory name, so you cannot distinguish different receivers.
```
 filestats/1:
   include: /tmp/test1/test*
   metrics:
     file.count:
       enabled: true
   resource_attributes:
     file.path:
       enabled: true

 filestats/2:
   include: /tmp/test2/*
   metrics:
     file.count:
       enabled: true
   resource_attributes:
     file.path:
       enabled: true
```

Only one metric is generated, so you cannot distinguish between the two:
```
file_count{host_name="localhost", os_type="linux"}
```
### Describe the solution you'd like

Add the directory attribute to be able to distinguish the different file_count metrics:
```
file_count{directory="/tmp/test1", host_name="localhost", os_type="linux"}
file_count{directory="/tmp/test2", host_name="localhost", os_type="linux"}
```
In this way the metrics of both directories can be distinguished.
