### ISSUE TITLE
[datadogexporter/datadogconnector] OpenTelemetry Missing Tags in APM Stats while upgrading to 0.95.0

### ISSUE THREAD

**Issue by JM89** [open-telemetry/opentelemetry-collector-contrib#36329]
## Description

I am publishing traces from EKS Services to DataDog using `otel/opentelemetry-collector-contrib:0.94.0`. 
I have been trying to upgrade to the latest version, but could not go beyond 0.95.0 without breaking most of our alerting system which relies heavily on APM Metrics and specific tags being present. 
 
I went through reusing the Datadog Connector as described [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/examples/trace-metrics.yaml) and [here](https://docs.datadoghq.com/opentelemetry/guide/migration/); and “trace.Microsoft.AspNetCore.server.hits” APM metrics now appear in DataDog, **but without any of the custom tags available in the APM traces**. I can see a number of options in the datadog connector (e.g. peer_tags) but none worked. The tags service, env and resource_name seems to go through, but not “host” or anything custom. 
 
Is this behavior expected? Can these tags be available the same way they used to be? Is there a better way of doing this? 

## Steps to Reproduce

Upgrade the OpenTelemetryCollector sidecar from 0.94.0 to 0.95.0 and reuse datadog connector as configured below. Note that this was tried with v0.113.0 as well. 

## Expected Result

The computed APM Metrics contain the same tags as the APM traces. 

## Actual Result

The computed APM Metrics contain only service, env, and resource_name. The tag "host" is set to "none" and custom tags are not available. 

### Collector version

v0.95.0

## Environment
- AWS EKS
- .NET Applications publishing traces. 
- OpenTelemetry Collector running as sidecar. 

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
          http:
processors: 
  batch:
    timeout: 10s
connectors:
    datadog/connector:
exporters:
  datadog:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE}
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/connector]
    traces/2:
      receivers: [datadog/connector]
      processors: [batch]
      exporters: [datadog]
    metrics:
      receivers: [datadog/connector]
      processors: [batch]
      exporters: [datadog]
```

**Comment by jackgopack4** [comment]
can you share what your config was for v0.94.0?

**Comment by JM89** [comment]
> 0.114.0

Thank you for your answer. Please find below the 0.94.0 configuration. 

```yaml
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      datadog:
        api:
          key: ${env:DD_API_KEY}
          site: ${env:DD_SITE}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [datadog]
```

Yes, I had tried with 0.113.0, any related changes on 0.114.0. I also tried 0.94.0 **with** the datadog connector, and turns out the tags aren't there either, so I suspect this is a behavior from the datadog connector itself not the exporter. I haven't reached out DataDog support since it was rapidly isolated to the datadog connector and I thought github was the best place to ask.

**Comment by jackgopack4** [comment]
if you can open the support ticket that will allow our engineers to view sample traces from the support tool, that's why I suggested it

**Comment by JM89** [comment]
I have now opened a DataDog support ticket. I am still very interested to understand the difference between the APM stats computations by the DataDog exporter v0.94.0 and the connector in the meantime? Especially around this host tag? Seems like this is not an expected behaviour.

**Comment by parkedwards** [comment]
i am also running into this issue. our `attributes` processor is used to set a key/value tag onto our otlp traces and statistics we send to DD

```
    processors:
      attributes/env:
        actions:
          - action: insert
            key: env
            value: ${env}
...
        traces:
          receivers: [otlp]
          processors: [batch/dd, attributes/env]
          exporters: [datadog/connector]
        traces/dd-with-sampling:
          receivers: [datadog/connector]
          processors: [batch/dd, attributes/env, tail_sampling]
          exporters: [datadog/external]
        metrics/dd:
          receivers: [datadog/connector]
          processors: [batch/dd, attributes/env]
          exporters: [datadog/external]
```

however, only our traces have the resulting `env` tag.  the statistics do not have this tag populating.  we're on `-contrib:0.116.1`

**Comment by mackjmr** [comment]
@parkedwards The reason why the attributes processor is not added to your trace stats is that the OTLP metrics which are exported via the datadog connector are not the trace stats, but contain a tag which contains the serialised trace stats payload. If you want the env tag on your stats computed in dd connector, you will need to set resource attribute `deployment.environment.name` on the relevant traces.

**Comment by JM89** [comment]
Hi, 

Unfortunately, the support ticket does not help much to progress on this issue. I would deeply appreciate any technical assistance with this configuration as well as some context on the expected behavior.  

I have done a few more tests, and so far, I have managed to find a way to get the cluster name and host back by trial and error, but **no custom metrics go through for the trace metrics `trace.Microsoft.AspNetCore.server.hits`**. However, the other custom metrics coming from OTEL have all tags. No problems with the traces themselves. 

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  mode: sidecar
  image: /docker/otel/opentelemetry-collector-contrib:0.117.0
  resources:
    requests:
      cpu: 10m
      memory: 46Mi
  env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: vault-secrets
          key: datadog-api-key
    - name: DD_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: DD_CLUSTER_NAME
      value: multisportcommon-uat
    - name: DD_TEAM
      value: team_x
    - name: DD_HOSTNAME
      value: $(DD_NODE_NAME)-$(DD_CLUSTER_NAME)
  config: 
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors: 
      resourcedetection:
        detectors: [system, eks]
        timeout: 15s
        override: false
        eks:
          resource_attributes: # No effect noticed
            k8s.cluster.name:
              enabled: true
        system:
          resource_attributes: # No effect noticed
            host.name:
              enabled: true
            host.id:
              enabled: false
      batch:
        timeout: 10s
      resource/custom:
        attributes: # No effect noticed
          - action: insert
            key: cluster_name
            value:  coming_from_resource
          - action: insert
            key: test_two
            value:  coming_from_resource
          - action: insert
            key: k8s.cluster.name	
            value:  coming_from_resource
          - action: insert 
            key: host.ip
            value: coming_from_resource 
          - action: insert
            key: host.name
            value: coming_from_resource 
      attributes/custom:
        actions:
          - action: insert
            key: test
            value: coming_from_attr_custom  # This does not appears in trace.Microsoft.AspNetCore.server.hits but appears in otlp custom metrics and traces + aspire
          - action: insert
            key: topicname
            value: coming_from_attr_custom  # This does not appears in trace.Microsoft.AspNetCore.server.hits but appears in otlp custom metrics and traces + aspire
      transform:
        metric_statements: &statements
          - context: resource
            statements:
              - set(attributes["datadog.host.name"], "coming_from_transform")     # This appears in trace.Microsoft.AspNetCore.server.hits
              - set(attributes["kube_cluster_name"], "coming_from_transform")     # This does not appear in trace.Microsoft.AspNetCore.server.hits but appears in otlp custom metrics and traces + aspire
              - set(attributes["k8s.cluster.name"], "coming_from_transform_two")  # This appears in trace.Microsoft.AspNetCore.server.hits under cluster_name
              - set(attributes["cluster_name"], "coming_from_transform")          # This does not appear in trace.Microsoft.AspNetCore.server.hits but appears in otlp custom metrics and traces + aspire
              - set(attributes["datadog.host.use_as_metadata"], true)
              - set(attributes["datadog.test_three"], "coming_from_transform")  # This does not appear in trace.Microsoft.AspNetCore.server.hits but appears in otlp custom metrics and traces + aspire
              - set(attributes["team"], "coming_from_transform")                  # This does not appear in trace.Microsoft.AspNetCore.server.hits but appears in otlp custom metrics and traces + aspire
              - set(attributes["datadog.team"], "coming_from_transform_two")      # This does not appear in trace.Microsoft.AspNetCore.server.hits but appears in otlp custom metrics and traces + aspire
              - set(attributes["topicname"], "coming_from_transform")             # This does not appear in trace.Microsoft.AspNetCore.server.hits but appears in otlp custom metrics and traces + aspire
              - set(attributes["service.name"], "coming_from_transform")          # This appeared before in trace.Microsoft.AspNetCore.server.hits under `service`, and can be overriden 
        trace_statements: *statements # Use the same statements as in metrics
        log_statements: *statements # Use the same statements as in metrics
    exporters:
      datadog/exporter:
        api:
          key: "${API_KEY}"
          site: datadoghq.eu
        metrics:
          resource_attributes_as_tags: true
      otlp/aspire:
        endpoint: aspire-otlp.blizard:18889
        tls:
          insecure: true
    connectors:
      datadog/connector:
        traces:
          peer_tags: ["cluster_name", "test", "test_two", "k8s.cluster.name", "host.ip", "host.name"] # No effect noticed
          resource_attributes_as_container_tags: ["cloud.availability_zone", "cloud.region"]              # No effect noticed
          compute_stats_by_span_kind: true                                                                # No effect noticed
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resourcedetection, transform, attributes/custom, resource/custom, batch]
          exporters: [datadog/connector, datadog/exporter, otlp/aspire]
        metrics:
          receivers: [datadog/connector, otlp]
          processors: [resourcedetection, transform, attributes/custom, resource/custom, batch]
          exporters: [datadog/exporter, otlp/aspire]
```

I can see the documentation suggests that span tags should not be there, where can I get the full list of tags available by default? are the resource tags also subject to this explicit "filtering"? can this behavior be overridden in any way?

![Image](https://github.com/user-attachments/assets/fc4c86b8-3108-4cbb-a310-86c58a49fc71)

Reference doc:
- [OpenTelemetry Semantic Conventions and Datadog Conventions](https://docs.datadoghq.com/opentelemetry/schema_semantics/semantic_mapping/?tab=datadogexporter)
- [Mapping OpenTelemetry Semantic Conventions to Hostnames](https://docs.datadoghq.com/opentelemetry/schema_semantics/hostname/?tab=datadogexporter)

Thank you very much,

PS:

[parkedwards](https://github.com/parkedwards) Based on what I have seen so far, have you tried the transform processor yet?

```yaml
processors:
      transform:
        metric_statements: &statements
          - context: resource
            statements:
              - set(attributes["deployment.environment.name"], "new env")  
        trace_statements: *statements # Use the same statements as in metrics
        log_statements: *statements # Use the same statements as in metrics
 service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [transform, batch]
        exporters: [datadog/connector, datadog]
      metrics:
        receivers: [datadog/connector, otlp]
        processors: [transform, batch]
        exporters: [datadog]
```
