### ISSUE TITLE
[processor/transformprocessor] Unexpected behaviour when setting resource attributes

### ISSUE THREAD

**Issue by tarokkk** [open-telemetry/opentelemetry-collector-contrib#36360]
### Component(s)

processor/transform

## Description
Only the last event record change will be persistent when modifying a `resource` attribute on a log record.

## Steps to Reproduce

Set up a file log receiver and use a transport processor in the pipeline like this:
```
      transform/example:
        log_statements:
          - conditions: null
            context: log
            statements:
              - set(resource.attributes["vhost"],attributes["example"])
```

The file log receiver "sometimes" emits the logs in "batches" with the same resource "header"

## Expected Result

```
log1 Resource{"vhost": "xxx"}, Log{"example": "xxx"}
log2 Resource{"vhost": "yyy"}, Log{"example": "yyy"}
```

## Actual Result

```
log1 Resource{"vhost": "yyy"}, Log{"example": "xxx"}
log2 Resource{"vhost": "yyy"}, Log{"example": "yyy"}
```

I assume that the setter does not clone the resource & scope part on modification which makes the individual log records to overwrite each resource context.

### Collector version

0.104.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
