### ISSUE TITLE
filestats's "file_permissions" resource does not show when it is a directory

### ISSUE THREAD

**Issue by josepcorrea** [open-telemetry/opentelemetry-collector-contrib#36444]
### Component(s)

receiver/filestats

## Description
When `file.ctime` metric is true, the resouce `file_permissions` does not show when it is a directory.
When you specify a * in the include, and there is a folder in the path, the resource does not indicate that it is a directory.

## Steps to Reproduce
```
 filestats:
   include: /tmp/jocorrea/*
   metrics:
     file.mtime:
       enabled: false
     file.ctime:
       enabled: true
   resource_attributes:
     file.path:
       enabled: true
```

## Expected Result
> {file_name="dir_jocorrea", file_path="/tmp/jocorrea/dir_jocorrea", file_permissions="drwxr-xr-x"}
> {file_name="file_jocorrea", file_path="/tmp/jocorrea/file_jocorrea", file_permissions="-rw-r--r--"}

## Actual Result
> {file_name="dir_jocorrea", file_path="/tmp/jocorrea/dir_jocorrea", file_permissions="-rwxr-xr-x"}
> {file_name="file_jocorrea", file_path="/tmp/jocorrea/file_jocorrea", file_permissions="-rw-r--r--"}

In the actual result, the dir_jocorrea file_permissions do not display the **d**.

### Collector version

v0.108.1

## Environment
OS: Red Hat Enterprise Linux Server 7.5 (Maipo) (Linux)
