### ISSUE TITLE
[exporter/datadog] Missing custom resource attributes in datadog

### ISSUE THREAD

**Issue by dariogriffo** [open-telemetry/opentelemetry-collector-contrib#36461]
### Component(s)

exporter/datadog

## Description
When exporting metrics from a .net API to datadog via the collector, custom resource attributes, are not visible in datadog

## Steps to Reproduce

Use the following code to export 

```
using System.Diagnostics.Metrics;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;

var builder = WebApplication.CreateBuilder(args);
Meter m = new Meter("Meter");
var c = m.CreateCounter<int>("counter");
builder.Services.AddOpenTelemetry()
    .ConfigureResource(builder => builder
        .AddService(serviceName: "OTel.NET Getting Started")
        .AddAttributes(new Dictionary<string, object>
        {
            ["environment.name"] = "production",
            ["team.name"] = "backend"
        }))
    .WithMetrics(builder => builder
        .AddMeter(m.Name)
        .ConfigureResource(b=>b.AddAttributes(new Dictionary<string, object>
        {
            ["environment.name"] = "production",
            ["team.name"] = "backend"
        }))
        .AddConsoleExporter((exporterOptions, metricReaderOptions) =>
        {
            metricReaderOptions.PeriodicExportingMetricReaderOptions.ExportIntervalMilliseconds = 1000;
        }).AddOtlpExporter()
    );
var app = builder.Build();

app.MapGet("/", () =>
{
    c.Add(1);
    return "Hello World!";
});

app.Run();
```

Resource of the attributes are present in the collector (attached image with environment and team.name attributes 

![IMG_20241119_213456_431](https://github.com/user-attachments/assets/73a06805-07e4-4ceb-8a5d-c75c8f7d94eb)

## Expected Result

The 2 custom attributes set at resource level appear in datadog 

## Actual Result

The custom attributes won't appear in datadog. The metrics with service and version attributes appear

### Collector version

0.114.0

## Environment
OS: (e.g., "Docker via debian bookworm")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: "http://seq:5341/ingest/otlp"
    tls:
      insecure: true
  otlp/aspire:
    endpoint: aspire:18889
    tls:
      insecure: true    
  datadog:
    api:
      site: MY_SITE
      key: MY_KEY
service:
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp, otlp/aspire ]
      processors: [batch]      
    metrics:
        receivers: [ otlp ]
        exporters: [ datadog, otlp/aspire ]
  telemetry:
    logs:
      level: "debug"
```

### Log output

```shell
Image attached
```
