### ISSUE TITLE
New component: Envoy access log receiver

### ISSUE THREAD

**Issue by zirain** [open-telemetry/opentelemetry-collector-contrib#36464]
### The purpose and use-cases of the new component

This receiver is design to receive logs from Envoy [ALS](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/grpc/v3/als.proto).

### Example configuration for the component

```yaml
receivers:
  envoyaccesslog:
    protocols:
      grpc:
  envoyaccesslog/withendpoint:
    protocols:
      grpc:
        endpoint: 0.0.0.0:8080
```

### Telemetry data types supported

logs

### Additional context

Both [Envoy Gateway](https://gateway.envoyproxy.io/docs/api/extension_types/#alsenvoyproxyaccesslog) and [Istio](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyHttpGrpcV3LogProvider) support expose access log with ALS, this would help them use Otel-collector as unify backend for collecting logs, metrics and tracing.
