### ISSUE TITLE
New component: Sematext Exporter

### ISSUE THREAD

**Issue by AkhigbeEromo** [open-telemetry/opentelemetry-collector-contrib#36465]
### The purpose and use-cases of the new component

The Sematext Metric Exporter component is designed to export telemetry data, specifically metrics  and logs, to the Sematext platform, enabling real-time monitoring, alerting, and observability. This exporter supports sending metrics to [Sematext Cloud](https://sematext.com/) in Influx line protocol format and logs using the Bulk Index Api format.

The primary changes include:

- **Addition of an `app_token`** for authentication with the Sematext platform.
- **Introduction of Region** to specify the data storage location.

### Configuration Options

- **`timeout`**  (default = 5s) Timeout for requests
- **`Region`**  Specifies the Sematext region the user is operating in; must be one of:  
  - `US`  
  - `EU`

- **`app_token`**  Specifies the token of the Sematext Monitoring App to which the user wants to send data.

- **`payload_max_lines`**  *(default = 1,000)*  Maximum number of lines allowed per HTTP POST request.

- **`payload_max_bytes`**  *(default = 300,000)*  Maximum number of bytes allowed per HTTP POST request.

- **`metrics_schema`**  *(default = telegraf-prometheus-v2)*  The chosen metrics schema to write.

- **`sending_queue`**  [Details here](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.25.0/exporter/exporterhelper/README.md#configuration)  
  - **`enabled`** *(default = true)* Enables the sending queue.  
  - **`num_consumers`** *(default = 10)* The number of consumers from the queue.  
  - **`queue_size`** *(default = 1000)* Maximum number of batches allowed in the queue at a given time.

- **`retry_on_failure`**  [Details here](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.25.0/exporter/exporterhelper/README.md#configuration)  
  - **`enabled`** *(default = true)* Enables retries on failure.  
  - **`initial_interval`** *(default = 5s)* Time to wait after the first failure before retrying.  
  - **`max_interval`** *(default = 30s)* Upper bound on backoff interval.  
  - **`max_elapsed_time`** *(default = 120s)* Maximum amount of time (including retries) spent trying to send a request/batch.

---

The full list of settings exposed for this exporter are documented in [config.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/config.go).

### Example:
```yaml
timeout: 500ms
region: US  
retry_on_failure:
  enabled: true
  initial_interval: 1s
  max_interval: 3s
  max_elapsed_time: 10s
metrics:
  app_token: 2064e37c-4fac-45f6-831d-922d43fde759
  sending_queue:
    enabled: true
    num_consumers: 3
    queue_size: 10
  payload_max_lines: 100
  payload_max_bytes: 1000
logs:
  app_token: 9064e37c-4gac-49f6-831d-922l43fse759
```

### Telemetry data types supported

Metrics, Logs

### Is this a vendor-specific component?

- [x] **This is a vendor-specific component**
- [x] If this is a vendor-specific component, I am a member of the OpenTelemetry organization.
- [x] If this is a vendor-specific component, I am proposing to contribute and support it as a representative of the vendor.

### Code Owner(s)

@AkhigbeEromo

### Sponsor (optional)

@andrzej-stencel
