### ISSUE TITLE
Mismatch in reported data on Timestamp and StartTimestamp

### ISSUE THREAD

**Issue by frzifus** [open-telemetry/opentelemetry-collector-contrib#36504]
### Component(s)

receiver/hostmetrics

## Description

As far as I understand there seems to be an issue when recording the `Timestamp` and `StartTimestamp`.

> Every OTLP metric data point has two associated timestamps. The first, mandatory timestamp is the one associated with the observation, the moment when the measurement became current or took effect, and is referred to as TimeUnixNano. The second, optional timestamp is used to indicate when a sequence of points is unbroken, and is referred to as StartTimeUnixNano.

Short:
- **StartTimestamp** - Represents the time when a metric's collection period began
- **Timestamp** - Represents the time when the metric data point was recorded

## Steps to Reproduce

I am using a machine in `CET+02` (`$ date; Fr 22. Nov 17:41:57 CET 2024`). 
There I used this config shown below with a collector (`./bin/otelcontribcol_linux_amd64 --config=config.yaml`):

## Expected Result

An almost equal TS in `StartTimestamp` and `Timestamp`.

## Actual Result

I see 1h mismatch between both timestamps, while both claim to be UTC.

### Collector version

v0.113.0

## Environment
OS: Fedora 41 Silverblue
Compiler(if manually compiled): go 1.23

### OpenTelemetry Collector configuration

```yaml
receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [debug]
```

### Log output

```shell
Data point attributes:
     -> state: Str(slab_unreclaimable)
StartTimestamp: 2024-11-22 15:44:12 +0000 UTC
Timestamp: 2024-11-22 16:41:53.73050196 +0000 UTC
Value: 238321664
```
