### ISSUE TITLE
Support mapping of ClientService to an exposed list of attributes

### ISSUE THREAD

**Issue by awangc** [open-telemetry/opentelemetry-collector-contrib#36503]
### Component(s)

connector/servicegraph

### Is your feature request related to a problem? Please describe.

Currently when enabling virtual nodes in servicegraphs, we can provide a list of attributes that allow a client span to create a virtual server node based on the attribute present. This request is to provide support for similar action for server spans, i.e., a new configuration option that allows us to provide a list of attributes that allow a server span to create a virtual client node based on the attribute present. This options does not currently exist, so any server span that does not have a corresponding client span gets assigned a generic `user` node as client, which hides how services are called.

### Describe the solution you'd like

With a config like the below:
```
connectors:
  servicegraph:
     latency_histogram_buckets: [100ms, 250ms, 1s, 5s, 10s]
     dimensions:
       - peer.service
       - client.address
     virtual_node_client_attributes:
       - peer.service
       - client.address
```

Server spans that has the attribute of `client.address` (or `peer.service`) will list the `client.address` (or `peer.service`) in the client node in the node graph, instead of the generic `user`.
