### ISSUE TITLE
New component: AWS SQS Receiver

### ISSUE THREAD

**Issue by yash025** [open-telemetry/opentelemetry-collector-contrib#36516]
### The purpose and use-cases of the new component

The AWS SQS receiver is designed to implement a mechanism for retrieving and processing telemetry data triggered by event notifications for S3 uploads, integrating directly with the OpenTelemetry Collector. This receiver will collect messages from Amazon Simple Queue Service (SQS) associated with S3 upload events and forward these to the OpenTelemetry Collector for further processing and exporting.

### Example configuration for the component

```
    receivers:
      awssqsreceiver:
        queue: "https://sqs.us-west-2.amazonaws.com/xxxx/fci-raw-spans-queue-qal-usw2"
        region: "us-west-2"
        visibility_timeout: 120
        worker_pool: 2
        wait_timeout: 15
```

### Telemetry data types supported

- traces
- metrics
- logs

### Code Owner(s)

@yash025, @igrishi @MaheshGPai
