### ISSUE TITLE
How to write logs via File Exporter in non OTLP JSON format

### ISSUE THREAD

**Issue by genadipost** [open-telemetry/opentelemetry-collector-contrib#36515]
### Component(s)

exporter/file

### Describe the issue you're reporting

I would like to export logs to a file using OpenTelemetry Collector [File Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter) , also i would like to format the logs in [logfmt](https://pkg.go.dev/github.com/kr/logfmt#section-documentation) format.

I was able to export the logs to a file but i am unable to find documentation which explains how to change the format of the logs.

Logs (also traces and metrics) seems can be exported in [OTLP JSON format](https://opentelemetry.io/docs/specs/otel/protocol/file-exporter/#telemetry-data-requirements) **only**.

> The data must be encoded according to the format specified in the [OTLP JSON Encoding](https://opentelemetry.io/docs/specs/otlp/#json-protobuf-encoding).
 Only top-level objects, TracesData, MetricsData, and LogsData are supported.
 Files must contain exactly one type of data: traces, metrics, or logs.
 ...
 This is an example showing logs:
 `{"resourceLogs":[{"resource":{"attributes":[{"key":"resource-attr","value":{"stringValue":"resource-attr-val-1"}}]},"scopeLogs":[{"scope":{},"logRecords":[{"timeUnixNano":"1581452773000000789","severityNumber":9,"severityText":"Info","body":{"stringValue":"This is a log message"},"attributes":[{"key":"app","value":{"stringValue":"server"}},{"key":"instance_num","value":{"intValue":"1"}}],"droppedAttributesCount":1,"traceId":"08040201000000000000000000000000","spanId":"0102040800000000"},{"timeUnixNano":"1581452773000000789","severityNumber":9,"severityText":"Info","body":{"stringValue":"something happened"},"attributes":[{"key":"customer","value":{"stringValue":"acme"}},{"key":"env","value":{"stringValue":"dev"}}],"droppedAttributesCount":1,"traceId":"","spanId":""}]}]}]}
`

**Comment by VihasMakwana** [comment]
@genadipost can you try this out? Haven't tested it, but it should work.

```yaml
exporters:
    file:
        encoding: text_encoding
        path: /otel-data/otel-exporter.log
        rotation:
            max_backups: 15
            max_megabytes: 50
extensions:
    text_encoding:
        encoding: utf8

    file_storage:
        directory: /var/lib/otelcol
processors:
    batch:
        send_batch_max_size: 1500
        send_batch_size: 1000
        timeout: 1s
    k8sattributes:
        extract:
            labels:
                - from: pod
                    key: app.kubernetes.io/name
                    tag_name: service.name
                - from: pod
                    key: k8s-app
                    tag_name: service.name
                - from: pod
                    key: app.kubernetes.io/instance
                    tag_name: k8s.app.instance
                - from: pod
                    key: app.kubernetes.io/version
                    tag_name: service.version
                - from: pod
                    key: app.kubernetes.io/component
                    tag_name: k8s.app.component
            metadata:
                - k8s.namespace.name
                - k8s.pod.name
                - k8s.pod.uid
                - k8s.node.name
                - k8s.pod.start_time
                - k8s.deployment.name
                - k8s.replicaset.name
                - k8s.replicaset.uid
                - k8s.daemonset.name
                - k8s.daemonset.uid
                - k8s.job.name
                - k8s.job.uid
                - k8s.container.name
                - k8s.cronjob.name
                - k8s.statefulset.name
                - k8s.statefulset.uid
                - container.image.tag
                - container.image.name
                - k8s.cluster.uid
        filter:
            node_from_env_var: K8S_NODE_NAME
        pod_association:
            - sources:
                - from: resource_attribute
                    name: k8s.pod.uid
            - sources:
                - from: resource_attribute
                    name: k8s.pod.name
                - from: resource_attribute
                    name: k8s.namespace.name
                - from: resource_attribute
                    name: k8s.node.name
            - sources:
                - from: resource_attribute
                    name: k8s.pod.ip
            - sources:
                - from: resource_attribute
                    name: k8s.pod.name
                - from: resource_attribute
                    name: k8s.namespace.name
            - sources:
                - from: connection
    resourcedetection/env:
        detectors:
            - env
        override: false
        timeout: 2s
receivers:
    filelog:
        exclude: []
        include:
            - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        operators:
            - id: container-parser
                max_log_size: 102400
                type: container
        retry_on_failure:
            enabled: true
        start_at: end
        storage: file_storage
service:
    extensions:
        - file_storage
        - text_encoding
    pipelines:
        logs:
            exporters:
                - file
                - debug
            processors:
                - k8sattributes
                - resourcedetection/env
                - batch
            receivers:
                - filelog
```
