### ISSUE TITLE
Unable to aggregate prometheus metrics using metricstransform processor 

### ISSUE THREAD

**Issue by rohankmr414** [open-telemetry/opentelemetry-collector-contrib#36539]
### Component(s)

processor/metricstransform

## Description

I'm trying to drop a high cardinality label from a prometheus metric by doing a sum aggregation on all the labels except for the one with high cardinality, I'm trying to do this via the metricstransform processor but it doesn't seem to work. Below is my collector config.

## Steps to Reproduce

Use the following collector config to scrape the metrics and process it

```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "high_cardinality_generator"
          scrape_interval: 5s
          static_configs:
            - targets: ["metrics_generator:8000"]  # Target the generator

processors:
  metricstransform:
    transforms:
      - include: high_card_metric_created_total  # The high-cardinality metric name
        action: update
        operations:
          - action: aggregate_labels
            label_set: [ user_id ]          # Remove all labels to aggregate entirely
            aggregation_type: sum

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"  # Expose aggregated metrics here

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [metricstransform]
      exporters: [prometheus]
```

## Expected Result

The `high_card_metric_created_total` metric on the prometheus exporter endpoint is not supposed to have the `user_id` label and is supposed to be a sum aggregate.

## Actual Result

No transformation is applied on the metric

### Collector version

v0.114.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "high_cardinality_generator"
          scrape_interval: 5s
          static_configs:
            - targets: ["metrics_generator:8000"]  # Target the generator

processors:
  metricstransform:
    transforms:
      - include: high_card_metric_created_total  # The high-cardinality metric name
        action: update
        operations:
          - action: aggregate_labels
            label_set: [ user_id ]          # Remove all labels to aggregate entirely
            aggregation_type: sum

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"  # Expose aggregated metrics here

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [metricstransform]
      exporters: [prometheus]
```
