### ISSUE TITLE
[Transform] Mixed ressource.attribute 

### ISSUE THREAD

**Issue by a-patos** [open-telemetry/opentelemetry-collector-contrib#36556]
### Component(s)

processor/transform

## Description

We are trying to set up an OtelCol collector on an instance that reads the files contained in /var/log/nginx/** to send them to a Loki backend via the OTLP endpoint.

When we have multiple files scraped in the filelog receiver, we end up with an incorrect resource.attributes["log.file.path"] in some cases. It seems to be incorrectly handled by the transform block, which appears to process lines by block rather than file by file.

## Steps to Reproduce
```shell
echo testalban >> /var/log/nginx/error.log
```
## Expected Result

```YAML
2024-11-26 17:19:07.782	 testalban
Fields:
application: Tools 
deployment_environment_name	: PROD
host_name	: i-045be5223b82fc8ca

log_file_name: error.log
log_file_path	: /var/log/nginx/error.log

service_name: my-nginx


```

## Actual Result
```YAML
2024-11-26 17:19:07.782	 testalban
Fields:
application: Tools 
deployment_environment_name	: PROD
host_name	: i-045be5223b82fc8ca

log_file_name: error.log
log_file_path	: /var/log/nginx/access.log

service_name: my-nginx
```

### Collector version

v0.113.0

## Environment
OS: AMAZON Linux 2023
Compiler(if manually compiled): from RPM install

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog/access:
    # Get Nginx logs
    include_file_name: true
    include_file_path: true
    include:
      - /var/log/nginx/access.log
      - /var/log/nginx/error.log
    retry_on_failure:
      enabled: true
    start_at: end
    max_batches: 1
    
processors:
  # Add Compagnie attribute for identify service
  attributes:
    actions:
      - action: upsert
        key: application
        value: "${env:ENV_ST}"
      - action: upsert
        key: deployment.environment.name
        value: "${env:ENV_NAME}"
      - action: upsert
        key: service.name
        value: "${env:COMPOSANT_NAME}"
      - action: upsert
        key: host.name
        value: "${env:HOSTNAME}"

transform:
    error_mode: ignore
    log_statements:
      - context: log
      # Convert Attribute to Ressource Attribute  for Loki Indexation (Attribute can't be index on loki backend).
        statements:
          - set(resource.attributes["application"], attributes["application"]) where attributes["application"] != nil
          - set(resource.attributes["deployment.environment.name"], attributes["deployment.environment.name"]) where attributes["deployment.environment.name"] != nil
          - set(resource.attributes["service.name"], attributes["service.name"]) where attributes["service.name"] != nil
          - set(resource.attributes["host.name"], attributes["host.name"]) where attributes["host.name"] != nil
          - set(resource.attributes["log.file.path"], attributes["log.file.path"]) where attributes["log.file.path"] != nil
exporters:
  # output to loki backend
  otlphttp/logs:
    endpoint: "https://loki.prod.local.fr:8443/otlp"
    headers:
      "X-Scope-OrgID": "trash" 


service:
  pipelines:
    logs/nginx:
          receivers:
            - filelog/access
          processors:
            - attributes
            - transform
          exporters:
            - otlphttp/logs
```

### Log output

```shell
nothing
```
