### ISSUE TITLE
feature(googlecloudspannerreceiver): Allow specifying scraping all databases for a Spanner instance

### ISSUE THREAD

**Issue by adinhodovic** [open-telemetry/opentelemetry-collector-contrib#36553]
### Component(s)

googlecloudspannerreceiver

### Is your feature request related to a problem? Please describe.

I'd like to not have to specify databases for the googlecloudspannerreceiver. They're generated and would be great to just configure the collector to list all existing databases for an instance and then just scrape them.

### Describe the solution you'd like

```yaml
    receivers:
      googlecloudspanner:
        collection_interval: 60s
        projects:
        - instances:
            instance_id: <test>
          project_id: <test>
```

Alternatively adding a flag to scrape all or `.*`.

```yaml
    receivers:
      googlecloudspanner:
        collection_interval: 60s
        projects:
        - instances:
          - databases:
            - ".*"
            // or scrapeAll config
            scrapeAll: true
            instance_id: <test>
          project_id: <test>
```

Would this be considered?
