### ISSUE TITLE
[processor/filter] 'and' operator is not working proper when we use '!=' in conditions

### ISSUE THREAD

**Issue by vaibhhavv** [open-telemetry/opentelemetry-collector-contrib#36564]
### Component(s)

processor/filter

## Description
I am using OTel v0.111.0, Helm chart v0.108.0.
I am utilising `filter` processor, and observed that when I utilise the filter processor with 
1. `and` operator along with `==`, then it works perfect
2. But if use `and` operator along with `!=`, then it does not filter out things correctly.

Note: In my case, I tested it for traces

## Steps to Reproduce
Suppose you are receiving traces, on your OTel and you want to filter services on both below resource attributes and use them in pipeline
1. my.resource.attributes1 = value1
2. my.resource.attributes2 = value2

**Working Filter**
```
filter/working-filter:
      error_mode: ignore
      traces:
        span:
          - resource.attributes["my.resource.attributes1"] == "value1" and resource.attributes["my.resource.attributes2"] == "value2"
```

**Not Working Filter**
```
filter/not-working-filter:
      error_mode: ignore
      traces:
        span:
          - resource.attributes["my.resource.attributes1"] != "value1" and resource.attributes["my.resource.attributes2"] != "value2"
```

```
pipelines:
      traces/pipeline1:
        exporters:
          - otlphttp
        processors:
          - filter/working-filter
          - batch
        receivers:
          - otlp

      traces/pipeline2:
        exporters:
          - otlphttp
        processors:
          - filter/not-working-filter
          - batch
        receivers:
          - otlp
```

## Expected Result
1. Pipeline1 should drop the services that have both attributes, rest others should get exporter. This is working as expected.
2. Pipeline2 should drop all the services other than the ones that contain both the attributes and forward them to the exporter.

## Actual Result
1. Pipeline1 works as expected.
2. Pipeline2 is not working as expected and not dropping all other services. Mostly with `!=` operator, I see it not works as expected.

### Collector version

v0.111.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
