### ISSUE TITLE
Failover does not respect priority-levels

### ISSUE THREAD

**Issue by ioannispl41** [open-telemetry/opentelemetry-collector-contrib#36587]
### Component(s)

connector/failover

### What happened?

Hello,

I came across a weird behavior … 

It seems  am unable to redirect traffic back to priority level one.

Here’s my current configuration:

```
config:
  connectors:
    failover:
      priority_levels:
        - [traces/first]
        - [traces/second]
      retry_interval: 1m
      retry_gap: 10s
      max_retries: 0 # Unlimited retries
  exporters:
    # Data sources: traces, metrics, logs
    otlp/1:
      endpoint: endpointA
      retry_on_failure:
        enabled: false
      sending_queue:
        enabled: false
      tls:
        insecure: true
    otlp/2:
      endpoint: endpointB
      retry_on_failure:
        enabled: false
      sending_queue:
        enabled: false
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        exporters: [failover]
      traces/first:
        receivers: [failover]
        exporters: [otlp/1]
      traces/second:
        receivers: [failover]
        exporters: [otlp/2]
```

When  changed the _max-retries_ value to 1000, it worked as expected: when _otlp/1_ stopped, traffic flowed through _otlp2_, and when _otlp1_ was restarted, it went through _otlp1_ again.

I believe that the issue is related to this [line](https://github.com/sinkingpoint/opentelemetry-collector-contrib/blob/a3e60ada4a845c7d84e76368f44621a2ed63b7fb/connector/failoverconnector/internal/state/pipeline_selector.go#L121-L122): not allowing connector to switch to a higher priority-level when _max-retries_==0.

### Collector version

v0.110.0
