### ISSUE TITLE
Open telemetry events are not exported by azure monitor

### ISSUE THREAD

**Issue by ovidiubuligan** [open-telemetry/opentelemetry-collector-contrib#3665]
**Describe the bug**
When exporting traces with attached events , only traces are exported. Events are not sent.
Using the jaeger-all-in-one as a sync I can see the  events attached.
**Steps to reproduce**

Any hello world app that does a trace with an event attached sent via any otel grpc protocol.

**What did you expect to see?**
Events showing up in azure monitor .

**What did you see instead?**
![image](https://user-images.githubusercontent.com/4757459/120102503-0a59c100-c154-11eb-9968-1c30881302fe.png)

**What version did you use?**
Ran from sources from main from commit  63437f7eb72c6b16f2d76d9637baa0c17e5767a2

**What config did you use?**
```yaml
receivers:
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
      http:

# ########################################################
# Processors
# ########################################################
processors:
  batch:
exporters:
  #azuremonitor:
  #azuremonitor/2:
  azuremonitor:
    instrumentation_key: AAAAAAAAAAAAAAAAAAAA
  jaeger:
    endpoint: "localhost:14250"
    insecure: true

# ####################################
# Service
# ####################################
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor]
```

**Environment**
OS:  windows 10 64 bit
Compiler GO 16

**Additional context**
Looking at he `exporter\azuremonitorexporter\trace_to_envelope.go` there is no call to the azure sdk to also attach events.
