### ISSUE TITLE
[processor/k8sattributes] Allow to extract metadata from other namespaces

### ISSUE THREAD

**Issue by sathieu** [open-telemetry/opentelemetry-collector-contrib#36670]
### Component(s)

processor/k8sattributes

### Is your feature request related to a problem? Please describe.

We have a notion of tenant. The tenant name is a label attached to a namespace.

Like this:

```yaml
      k8sattributes:
        extract:
          labels:
          # ...
          - from: namespace
            key: kubitus-project.gitlab.io/tenant  # << label name
            tag_name: kubitus.tenant.name  # << attribute
          metadata:
          - k8s.namespace.name
          # ...
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
```

We use this to set tenant using a `transform`:

```yaml
      transform/loki-tenant:
        error_mode: ignore
        log_statements:
        - context: log
          statements:
          # default tenant id
          - set(resource.attributes["tenant_id"], "1")
          # use namespace label when available
          - set(resource.attributes["tenant_id"], resource.attributes["kubitus.tenant.name"])
            where resource.attributes["kubitus.tenant.name"] != nil
```

But this is not enough because we have some logs where the tenant should be extracted from a namespace which is not the pod namespace. For example we have ingress-nginx logs in the ingress-nginx namespace where the ingress namespace is found.

Here is what we tried:

```yaml
      transform/loki-tenant:
        error_mode: ignore
        log_statements:
        - context: log
          statements:
          # set namespace from pod namespace
          - set(cache["tenant_namespace"], resource.attributes["k8s.namespace.name"])
          # if pod namespace is ingress-nginx, extract namespace from JSON body
          - set(cache["ingress_nginx_body"], ParseJSON(body))
            where IsMatch(cache["tenant_namespace"], "^ingress-nginx") and IsMatch(body, "^\\{")
          - set(cache["tenant_namespace"], cache["ingress_nginx_body"]["namespace"])
            where cache["ingress_nginx_body"]["namespace"] != nil
          # default tenant id
          - set(resource.attributes["tenant_id"], "1")
          # use namespace label when available. BUT we want it from cache["tenant_namespace"]!
          - set(resource.attributes["tenant_id"], resource.attributes["kubitus.tenant.name"])
            where resource.attributes["kubitus.tenant.name"] != nil
```

### Describe the solution you'd like

Currently k8sattributes does several things:

1. extract POD ID
2. set resource attributes based on above step
3. if passthru: stop
4. set resource attributes for pod
5. get namespace name
6. get attributes for pod namespace
7. set namespace attributes based on above step
6. get attributes for pod node
7. set nodeattributes based on above step

I want only step 6, extracting attributes for a namespace that is not necessarily a pod namespace.

### Describe alternatives you've considered

Injecting into `k8s.namespace.name` and reverting after. This is hackish and I couln't get it to work.
