### ISSUE TITLE
timeUnixNano Field Inconsistency Across Data Points

### ISSUE THREAD

**Issue by MaheshSankaran** [open-telemetry/opentelemetry-collector-contrib#36711]
### Component(s)

exporter/kafka, receiver/prometheus

## Description
I am using the OpenTelemetry Contrib Collector to scrape metrics via the Prometheus receiver and export them to a Kafka topic. While inspecting the data, I observed that the timeUnixNano field varies across data points
This inconsistency in timestamps causes issues in downstream processing, as it becomes difficult to align metrics collected at the same point in time.

## Steps to Reproduce

Configure OpenTelemetry Contrib Collector with the Prometheus receiver and Kafka exporter.
Scrape metrics from a Prometheus target.
Inspect the output written to the Kafka topic.

## Expected Result
The timeUnixNano field should be consistent for all data points collected during the same scrape interval.
## Actual Result
The timeUnixNano field differs across data points collected during the same scrape interval, as shown in the example data above.

### Collector version

v0.110.0

## Environment

Kubernetes deployment with v0.110.0 Image

### OpenTelemetry Collector configuration

```yaml
receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kubelet'
              scheme: https
              bearer_token: '*******'
              tls_config:
                insecure_skip_verify: true
              scrape_interval: 15s
              metrics_path: /metrics/cadvisor
              static_configs:
                - targets:
                    - x.x.x.x:10250
                    - x.x.x.x:10250
                    - x.x.x.x:10250
    processors:
      filter/metric_3:
        metrics:
          include:
            match_type: expr
            expressions:
              - MetricName == "container_memory_working_set_bytes"

    exporters:

      kafka/metric_3:
        brokers:
          - cluster-kafka-brokers:9092
        topic: 'container_memory_working_set_bytes_testing'
        encoding: 'otlp_json'
        sending_queue:
          queue_size: 3000

    service:
      pipelines:
        metrics/one:
          receivers: [prometheus]
          processors: [filter/metric_3]
          exporters: [kafka/metric_3]
```

### Additional context

This issue specifically occurs with the container_memory_working_set_bytes metric, which has a large volume of data. The high volume of data might be contributing to the timestamp inconsistencies in the timeUnixNano field.

Below is the example json data on kafka topic
```
[
  {
    "attributes": [
      {"key": "container", "value": {"stringValue": "ubuntu-container"}},
      {"key": "id", "value": {"stringValue": "/kubepods.slice/kubepods..."}},
      {"key": "image", "value": {"stringValue": "docker.io/library/ubuntu:latest"}},
      {"key": "namespace", "value": {"stringValue": "default"}},
      {"key": "pod", "value": {"stringValue": "ubuntu-pod"}}
    ],
    "timeUnixNano": "1733579863520000000",
    "asDouble": 409600
  },
  {
    "attributes": [
      {"key": "container", "value": {"stringValue": "agent"}},
      {"key": "id", "value": {"stringValue": "/kubepods.slice/kubepods..."}},
      {"key": "image", "value": {"stringValue": "docker.io/zabbix/agent2:alpine-6.0.33"}},
      {"key": "namespace", "value": {"stringValue": "test"}},
      {"key": "pod", "value": {"stringValue": "agent-nd2vs"}}
    ],
    "timeUnixNano": "1733579862606000000",
    "asDouble": 75251712
  }
]

```
