### ISSUE TITLE
[exporter/loadbalancing] Data loss still unavoidable under high load and autoscaling

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-collector-contrib#36717]
### Component(s)

exporter/loadbalancing

## Description

We had the previous issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35378 

However this is unfortunately not quite solved.

There is the top-level exporter queue and the sub exporter queues. To avoid data loss on an autoscale down event, there can't be queues on the sub-exporter. However if you disable this queue, it's extremely slow because the endpoints are exported to synchronously in-series. 

So, basically, if we have a queue, we get data loss on scaling. If we don't have a queue, we get data loss from performance issues because it's too slow to export. This problem gets worse the more downstream you have.

I've annotated the problematic code here with comments: 

```go
for exp, td := range exporterSegregatedTraces {
  start := time.Now()
  // with no queue, this blocks.
  // with queue, this doesn't block but causes data loss when the downstream gets scaled down.
  err := exp.ConsumeTraces(ctx, td) 
  exp.consumeWG.Done()
  errs = multierr.Append(errs, err)
  ...
}
```

## Steps to Reproduce

Disable sub-exporter queue.
```yaml
  loadbalancing:
    # top-level exporter queue
    sending_queue:
      queue_size: 6000
      num_consumers: 200 # even with high consumer amount the problem persisted for us
    protocol:
      otlp:
        sending_queue:
          enabled: false
```

Then throw some load at the collector. 

Result is severe performance issues and high export times.

## Proposed solution

I think we need to have a way of disabling the sub exporter queue without blocking in series here. An `errgroup` or similar so the consumers can export to different endpoints in-parallel without relying on the sub exporter queue. Open to other ideas to solve the problem, but this seems simplest to me.

### Collector version

v0.115.0
