### ISSUE TITLE
how can i convert log to gauge ?

### ISSUE THREAD

**Issue by jluncc** [open-telemetry/opentelemetry-collector-contrib#36710]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

hi, i have some request log, like   

```
request_url1,200,2  
request_url2,500,1
```  

this means request_url_name, response_code, time

now i can receive this log on the opentelemetry collector receiver, the next step i want to convert this log to gauge metric (just like _request_url_info{url="request_url1",code="200"} 2_ ), and then expose it let prometheus to consume so that we can query on the guafana.

my question is **how can i convert the log to gauge metric** ?

--

i have search seems if i want to convert log to metric, i need connector, and i find one: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/signaltometricsconnector, but this can not convert to gauge,  

so is there any ideas can help me to do that ?

### Describe the solution you'd like

maybe some processor or connector can help me to do that ?

**Comment by jaronoff97** [comment]
@jluncc for your use case it seems that you want to keep track of http responses which is usually better expressed as a counter. Can you explain your use case a bit more for a gauge?

**Comment by jluncc** [comment]
> @jluncc for your use case it seems that you want to keep track of http responses which is usually better expressed as a counter. Can you explain your use case a bit more for a gauge?

@jaronoff97 thanks for your reply!  

for example my log is 

```log
request_url1, ip1, env1, content-type, response-code, 2  
```

and i want to convert to gauge like  

```txt
request_url_info{url="request_url1", ip="ip1", env="env1", content-type="content-type", code="response-code"} 2
```

the value is response time,  

and then expose to prometheus, use promql to compuate reqeust info with label filter or aggregate function flexible  

--- 

however now i use fluentbit to convert log to gauge: https://docs.fluentbit.io/manual/pipeline/filters/log_to_metrics  

but i want to know is i can do the same thing on collector ?

**Comment by jluncc** [comment]
> What error do you get when trying to convert to a histogram? Can you share your configuration too?

error log:

```log
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
error decoding 'connectors': unknown type: "signaltometrics" for id: "signaltometrics" (valid values: [datadog grafanacloud roundrobin servicegraph spanmetrics forward count exceptions otlpjson routing])
```  

my config:  

```yaml
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 3300
        spike_limit_mib: 650
      batch:
        send_batch_size: 1500
        send_batch_max_size: 3000
        timeout: 2s    
    connectors:
      signaltometrics:
        logs:
          - name: test.histogram
            description: test histogram compuate
            histogram:
              value: Int(attributes["request_time"])
    exporters:
      debug:
        verbosity: normal         
    service:    
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [debug,signaltometrics]                  
        metrics:
          receivers: [signaltometrics]
          processors: [memory_limiter,batch]
          exporters: [debug]
```
