### ISSUE TITLE
tracer newRecordingSpan memory leak

### ISSUE THREAD

**Issue by PowerSurj** [open-telemetry/opentelemetry-collector-contrib#36746]
## Description
Observing memory leak

![image](https://github.com/user-attachments/assets/26102aba-624f-4da6-a7d1-d2f2c04e7769)

## Steps to Reproduce
dedicated for tracing otelcol pods are running in k8s
k8s applications export traces to otlp grpc endpoint
collectors perform probabilistic sampling with equalizing mode and export traces to awsxray

otel configuration provided below

## Profiles
cpu, memory and goroutines pprof attached

[pprof.otelcol-contrib.samples.cpu.001.pb.gz](https://github.com/user-attachments/files/18072018/pprof.otelcol-contrib.samples.cpu.001.pb.gz)
[pprof.otelcol-contrib.goroutine.001.pb.gz](https://github.com/user-attachments/files/18072019/pprof.otelcol-contrib.goroutine.001.pb.gz)
[pprof.otelcol-contrib.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/user-attachments/files/18072020/pprof.otelcol-contrib.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)

### Collector version

0.114.0

## Environment
AWS EKS 1.30
running collectors as containers

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  awsxray:
    index_all_attributes: true
  debug/detailed:
    sampling_initial: 1
    verbosity: detailed
  debug/normal:
    verbosity: normal
processors:
  batch:
    send_batch_max_size: 10000
    timeout: 1s
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  probabilistic_sampler:
    mode: equalizing
    sampling_percentage: 1
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: localhost:1777
  zpages:
    endpoint: localhost:55679
service:
  extensions:
    - health_check
    - zpages
    - pprof
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    traces/awsxray:
      exporters:
        - debug/detailed
        - awsxray
      processors:
        - memory_limiter
        - probabilistic_sampler
        - batch
      receivers:
        - otlp
```

### Log output

```shell
no errors in the logs
```
