### ISSUE TITLE
[connector/routing] Ability to dynamically determine a pipeline ID

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#36809]
### Component(s)

connector/routing

## Scenario

- A specialized observability team manages a gateway collector
- All other teams forward their data to the gateway collector for processing
- Each team MAY provide custom processing logic for their data

In order to accomplish this, the observability team could define a simple contract which the other teams must follow:
- Annotate your telemetry with a specific attribute. e.g. `resource.attributes["team"] = "team-A"`
- A routing connector with a fixed name will route to a pipeline named according to the attribute.
- A forward connector with a fixed name will subscribe to data coming off of team-specific pipelines.
- Teams may provide corresponding processing configuration in a file called e.g. `team-A.yaml`.

```yaml
# gateway-base.yaml
receivers:
  otlp: ...
  
processors:
  transform/default: ...
  
connectors:
  routing/by-team-name:
    default_pipelines: [ logs/default ]
    table:
      - context: resource
        condition: attributes["team"] != nil
        lookup_pipeline: Format("custom-%s", attributes["team"])
      - ... # can evaluate other routes as usual
  forward/out: # all teams MUST forward here when done
      
exporters:
  otlp: ...
  
service:
  pipelines:
    logs/in: 
      receivers: [ otlp ]
      exporters: [ routing/by-team-name ]
    logs/default:
      receivers: [ routing/by-team-name ]
      processors: [ transform/default ]
      exporters: [ otlp ]
    logs/out:
      receivers: [ forward/out ]
      exporters: [ otlp ]
```

```yaml
# team-A.yaml
processors:
  transform/team-A:
  filter/team-A:

service:
  pipelines:
    logs/my-team:
      receivers: [ routing/by-team-name ]
      processors: [ transform/team-A, filter/team-A ]
      exporters: [ forward/out ]
```

The observability team runs the collector with a base config to define the static elements, and each team's config to pull in team specific processing rules. `otelcol --config gateway-base.yaml --config team-A.yaml ...`

## Problem

Currently, all routes must include a `pipelines` field which explicitly names the pipeline(s) to which the data should be routed if it matches the route criteria. In the above example, a contract or convention is used to manage routing, but there is no way to dynamically lookup relevant pipelines.

### Describe the solution you'd like

Instead of requiring each route item to specify `pipelines`, allow an alternative field e.g. `lookup_pipeline` which is a "computed" pipeline ID.

If a route uses this field, the value is interpreted as an [OTTL expression](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35621) which must return a string that is interpreted as a `pipeline.ID`. (The data type can be inferred from the type of data that is being routed.)

The routing connector can use its [`PipelineIDs` method](https://github.com/open-telemetry/opentelemetry-collector/blob/8bd803fd70460d8de870548b9d6214272feaa50a/connector/logs_router.go#L42) to check if it is a valid pipeline. If so, it routes the data to that pipeline. _If not, the route is not considered a match_ in which case route matching moves on to the next route as usual.

**Comment by atoulme** [comment]
@jpkrohling @mwear please review as codeowners

**Comment by jeffalder** [comment]
@djaglowski Are you still advocating for this? Looks like there hasn't been much activity.

What are your thoughts about rules on the "request" context? We can't evaluate an OTTL expression there, so we'd have to either use a request attribute directly, or disallow support for the "request" context. I think the former (use a request attribute directly) makes more sense.

**Comment by andrewvc** [comment]
I have a rough [PoC](https://github.com/andrewvc/opentelemetry-collector-contrib/pull/1/changes) that allows dynamic pipelines with a syntax like 

```yaml
connectors:
  routing:
    default_pipelines: [logs/other]
    table:
      - route([Concat(["logs/tenant-", resource.attributes["tenant"]], "")]) where resource.attributes["tenant"] != nil
```

This collapses the routing table entries into single strings if used.

This is built on my [Context Inference PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/44762). I'm hesitant, however to go further. The more I think about it, I'm not certain dynamic pipelines are worth the code complexity. In the multitenant example given in this repo, I do think it'd be better to give each tenant their own collector vs. colocating everyone on a single collector. It seems like that pattern might create stability issues. 

It's a lot of complexity for something that can be solved today in perhaps some more awkward ways. Another way would be to add more static rules via some config management tool (ansible etc.) for instance (if combining everything in one collector is desired).
