### ISSUE TITLE
Azure Event Hub receiver does not set ObservedTimestamp

### ISSUE THREAD

**Issue by dentonk** [open-telemetry/opentelemetry-collector-contrib#36861]
### Component(s)

receiver/azureeventhub

## Description
The Azure Event Hub receiver does not set the the **ObservedTimestamp** for ingested logs.

## Steps to Reproduce
Configure an Otel collector pipeline using the `azureeventhub` receiver and the `file` exporter with no additional processing and view the output log records. 

## Expected Result
Each log record should contain an **ObservedTimestamp** as described in the logs data model [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-observedtimestamp).

## Actual Result
In addition to the `body`, each log record only contains a `timeUnixNano` field but not an `observedTimeUnixNano`, as seen in other log records where the **ObservedTimestamp** is set.

### Collector version

v0.115.0

## Environment
Docker Desktop 4.36.0 running on Mac OSX M3

### OpenTelemetry Collector configuration

```yaml
receivers:
  azureeventhub/AzureEH:
    connection: Endpoint=<REDACTED>
    format: raw
    group: $$Default
    offset: "-1"
    partition: ""
processors:
exporters:
  file/no_rotation:
    path: /output.log
extensions:
service:
  pipelines:
    logs/pipeline1:
      receivers:
        - azureeventhub/AzureEH
      processors:
      exporters:
        - file/no_rotation
```

### Log output

```shell
{
  "resourceLogs":
  [
    {
      "resource":
      {},
      "scopeLogs":
      [
        {
          "scope":
          {},
          "logRecords":
          [
            {
              "timeUnixNano": "1734376978561000000",
              "body":
              {
                "bytesValue": "<REDACTED>"
              },
              "traceId": "",
              "spanId": ""
            }
          ]
        }
      ]
    }
  ]
}
```
