### ISSUE TITLE
Logs to debug authentication using oauth2

### ISSUE THREAD

**Issue by Jonaprince** [open-telemetry/opentelemetry-collector-contrib#36944]
### Component(s)

exporter/prometheusremotewrite, extension/oauth2clientauth

### Describe the issue you're reporting

Hello,

I'm trying to push metrics using the remote write protocol to an enpoint which require oauth2 authentication. But I can't and I have no much way to debug my problem. Here is my configuration:
```yaml
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      memory:

extensions:
  oauth2client:
    client_id: "<MY_ID>"
    client_secret: <MY_SECRET>
    token_url: "https://<MY_OAUTH2_PROVIDER>/token"
    endpoint_params:
      grant_type: "client_credentials"
    scopes:
    - openid
    timeout: 30s


exporters:

  debug:
    verbosity: detailed

  prometheusremotewrite/withauth:
    auth:
      authenticator: oauth2client
    endpoint: "https://<MY_REMOTE_WRITE_URL>/api/v1/write"

service:
  extensions: [oauth2client]
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [hostmetrics
      processors: []
      exporters: [prometheusremotewrite/withauth]
```

The only logs that I get is: 
```
otlp-exporter  | 2024-12-24T10:19:44.243Z       error   internal/queue_sender.go:103    Exporting failed. Dropping data.        {"kind": "exporter", "data_type": "metrics", "name": "prometheusremotewrite/withauth", "error": "Permanent error: Permanent error: context deadline exceeded", "dropped_items": 6}
```

So I don't have many hints to diagnose the issue. I don't know if it due to a oauth misconfiguration or anything else. Is there a way to get more logs about the requests status for example ?

Thank you for your help.
