### ISSUE TITLE
Filter does not filter out metric

### ISSUE THREAD

**Issue by hlx-a1** [open-telemetry/opentelemetry-collector-contrib#36973]
**Describe the bug**
I have created a filter processor to drop a particular metric name, yet despite messages in the log indicating that my filter processor is loaded, the metric is still present in prometheus.

**Steps to reproduce**
1. Deploy a `whoami` instance behind traefik, configure traefik to export metrics to OTEL collector
2. Configure OTEL collector as below to drop `http_server_request_duration_bucket`

**What did you expect to see?**
The `http_server_request_duration_bucket` metric to stop being sent to prometheus

**What did you see instead?**
The `http_server_request_duration_bucket` metric still present

**What version did you use?**
`0.114.0`

**What config did you use?**
```yaml
# https://grafana.com/docs/grafana-cloud/monitor-applications/application-observability/setup/collector/opentelemetry-collector/

receivers:
  otlp/pub:
    protocols:
      http:
        endpoint: 10.0.0.2:4318
        auth: { authenticator: bearertokenauth }

  otlp/local:
    protocols:
      http:
        endpoint: 10.0.0.2:34318

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: OTLC1_PROD_COLLECTOR
        static_configs: [ { targets: [ 10.?.?.?:9100 ], labels: { namespace: HLX, environment: PROD } } ]
      - job_name: HLXVPLAPP002
        static_configs: [ { targets: [ 10.?.?.?:9100 ], labels: { namespace: HLX, environment: PROD } } ]
      - job_name: HLXVPLAPP003
        static_configs: [ { targets: [ 10.?.?.?:9100 ], labels: { namespace: HLX, environment: PROD } } ]
      - job_name: HLXVPLAPP004
        static_configs: [ { targets: [ 10.?.?.?:9100 ], labels: { namespace: HLX, environment: PROD } } ]

processors:
  batch:

  # Enriches telemetry data with resource information from the host
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor
  resourcedetection:
    detectors: [ env, system ]
    override: false

  filter/drop_big_metrics:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - http_server_request_duration_bucket

  transform/drop_unneeded_resource_attributes:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor
    error_mode: ignore
    trace_statements:
    - context: resource
      statements:
      - delete_key(attributes, "k8s.pod.start_time")
      - delete_key(attributes, "os.description")
      - delete_key(attributes, "os.type")
      - delete_key(attributes, "process.command_args")
      - delete_key(attributes, "process.executable.path")
      - delete_key(attributes, "process.pid")
      - delete_key(attributes, "process.runtime.description")
      - delete_key(attributes, "process.runtime.name")
      - delete_key(attributes, "process.runtime.version")
    metric_statements:
    - context: resource
      statements:
      - delete_key(attributes, "k8s.pod.start_time")
      - delete_key(attributes, "os.description")
      - delete_key(attributes, "os.type")
      - delete_key(attributes, "process.command_args")
      - delete_key(attributes, "process.executable.path")
      - delete_key(attributes, "process.pid")
      - delete_key(attributes, "process.runtime.description")
      - delete_key(attributes, "process.runtime.name")
      - delete_key(attributes, "process.runtime.version")
    log_statements:
    - context: resource
      statements:
      - delete_key(attributes, "k8s.pod.start_time")
      - delete_key(attributes, "os.description")
      - delete_key(attributes, "os.type")
      - delete_key(attributes, "process.command_args")
      - delete_key(attributes, "process.executable.path")
      - delete_key(attributes, "process.pid")
      - delete_key(attributes, "process.runtime.description")
      - delete_key(attributes, "process.runtime.name")
      - delete_key(attributes, "process.runtime.version")

  transform/add_resource_attributes_as_metric_attributes:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["deployment.environment"], resource.attributes["deployment.environment"])
          - set(attributes["service.version"], resource.attributes["service.version"])

exporters:
  debug:
  #  verbosity: detailed

  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter
  otlp/grafana_cloud_traces:
    endpoint: ${env:GRAFANA_CLOUD_TEMPO_ENDPOINT}
    #tls: # causes error
    #  insecure: false
    auth:
      authenticator: basicauth/grafana_cloud_traces

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter
  loki/grafana_cloud_logs:
    endpoint: ${env:GRAFANA_CLOUD_LOKI_URL}
    tls:
      insecure: false
    auth:
      authenticator: basicauth/grafana_cloud_logs

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusremotewriteexporter
  prometheusremotewrite/grafana_cloud_metrics:
    endpoint: ${env:GRAFANA_CLOUD_PROMETHEUS_URL}
    tls:
      insecure: false
    auth:
      authenticator: basicauth/grafana_cloud_metrics
    add_metric_suffixes: false

extensions:
  health_check:
    endpoint: 10.?.?.?:?
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/basicauthextension
  basicauth/grafana_cloud_traces:
    client_auth:
      username: ${env:GRAFANA_CLOUD_TEMPO_USERNAME}
      password: ${env:GRAFANA_CLOUD_API_KEY}
  basicauth/grafana_cloud_metrics:
    client_auth:
      username: ${env:GRAFANA_CLOUD_PROMETHEUS_USERNAME}
      password: ${env:GRAFANA_CLOUD_API_KEY}
  basicauth/grafana_cloud_logs:
    client_auth:
      username: ${env:GRAFANA_CLOUD_LOKI_USERNAME}
      password: ${env:GRAFANA_CLOUD_API_KEY}
  bearertokenauth:
    token: ${env:HELIX_CLIENT_BEARER_TOKEN}

# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/grafanacloudconnector
connectors:
  grafanacloud/host_hours_pricing:
    host_identifiers: [ "host.name" ]
    metrics_flush_interval: 60s

service:
  #telemetry:
  #  logs:
  #    level: "debug"

  pipelines:
    traces:
      receivers: [ otlp/pub, otlp/local ]
      processors:
      - resourcedetection
      - transform/drop_unneeded_resource_attributes
      - batch
      exporters:
      - otlp/grafana_cloud_traces
      #- spanmetrics
      - grafanacloud/host_hours_pricing

    metrics:
      #receivers: [ otlp/pub, otlp/local, prometheus, spanmetrics ]
      receivers: [ otlp/pub, otlp/local, prometheus ]
      processors:
      - resourcedetection
      - filter/drop_big_metrics
      - transform/drop_unneeded_resource_attributes
      - transform/add_resource_attributes_as_metric_attributes
      - batch
      exporters: [ prometheusremotewrite/grafana_cloud_metrics ]

    metrics/host_hours_pricing:
      receivers: [ grafanacloud/host_hours_pricing ]
      processors:
      - filter/drop_big_metrics
      - batch
      exporters: [ prometheusremotewrite/grafana_cloud_metrics ]

    logs:
      receivers: [ otlp/pub, otlp/local ]
      processors:
      - resourcedetection
      - transform/drop_unneeded_resource_attributes
      - batch
      exporters: [ loki/grafana_cloud_logs ]

  extensions:
  - basicauth/grafana_cloud_traces
  - basicauth/grafana_cloud_metrics
  - basicauth/grafana_cloud_logs
  - bearertokenauth
  - health_check
```

**Environment**
OS: Rocky Linux 9.5
