### ISSUE TITLE
HAProxy receiver documentation error in file name

### ISSUE THREAD

**Issue by jakubsuchy** [open-telemetry/opentelemetry-collector-contrib#37000]
### What happened?

Documentation states:
```
haproxy:
  endpoint: file:///var/run/haproxy.ipc
  collection_interval: 1m
  metrics:
    
```

This will result in error file not found. Correct config is:
```
haproxy:
  endpoint: /var/run/haproxy.ipc
  collection_interval: 1m
  metrics:
    
```

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
