### ISSUE TITLE
OTel Collector Fails Health Check on AWS App Runner with Minimal Config

### ISSUE THREAD

**Issue by garysassano** [open-telemetry/opentelemetry-collector-contrib#37081]
## Problem Summary

I spent **half a day** trying to make the `opentelemetry-collector-contrib` work on AWS App Runner using its default health check configuration on `/` path and port `4318`:

![image](https://github.com/user-attachments/assets/40199212-71c3-476e-ade1-e43e6d65383f)

Despite multiple attempts with minimal configurations, the health check consistently failed. Eventually, I was only able to make it work by reverse-engineering the `opentelemetry-collector-config` default confmap from the logs and tweaking it. However, this resulted in a bloated configuration containing many components I don’t need.

---

## Investigation Process

1. **Extracting Default Configuration**  
   Since I couldn’t find the default configuration in this repository, I used the logs generated by the `opentelemetry-collector-config` default confmap and reverse-engineered it with Claude 3.5 Sonnet.  
   *(See image below for log details)*  
   ![Log Output](https://github.com/user-attachments/assets/5189bd7e-7b8a-46cb-b7e6-2c21aa5fb87f)

2. **Reverse-Engineered Configuration**  
   The resulting configuration included multiple receivers, exporters, and extensions, even though I only required OTLP.  
   Here’s the output I obtained (excluding Prometheus):

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  zipkin:
    endpoint: 0.0.0.0:9411
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
  opencensus:
    endpoint: 0.0.0.0:55678

exporters:
  debug:
    verbosity: detailed

extensions:
  health_check:
    endpoint: localhost:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  telemetry:
    metrics:
      address: localhost:8888
      level: normal

  extensions: [health_check, pprof, zpages]

  pipelines:
    traces:
      receivers: [otlp, zipkin, jaeger, opencensus]
      exporters: [debug]
    metrics:
      receivers: [otlp, opencensus]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
```

3. **Final Working Configuration**  
   I then replaced the `debug` exporter with my actual `otlp` exporter pointing to Honeycomb and finally got the setup working.  

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  zipkin:
    endpoint: 0.0.0.0:9411
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
  opencensus:
    endpoint: 0.0.0.0:55678

exporters:
  otlp:
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: XXX

extensions:
  health_check:
    endpoint: localhost:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  telemetry:
    metrics:
      address: localhost:8888
      level: normal

  extensions: [health_check, pprof, zpages]

  pipelines:
    traces:
      receivers: [otlp, zipkin, jaeger, opencensus]
      exporters: [otlp]
    metrics:
      receivers: [otlp, opencensus]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [otlp]
```

---

4. **Minimal Config Attempt and Failure**

I initially tried simplifying the configuration to only include the required OTLP components, as shown below:

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318

exporters:
  otlp:
    endpoint: api.honeycomb.io:443
    headers:
      x-honeycomb-team: XXX

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]

extensions:
  health_check:
```

However, this configuration failed the AWS App Runner health check.

---

## Open Question

Why does the simplified configuration fail the App Runner health check while the bloated configuration doesn't?

---

## Collector version

0.112.0
