### ISSUE TITLE
add gauge metric support for signaltometrics connector

### ISSUE THREAD

**Issue by gilad-aperio** [open-telemetry/opentelemetry-collector-contrib#37093]
### Component(s)

connector/signaltometrics

### Is your feature request related to a problem? Please describe.

Many systems, especially legacy ones, report metrics through logs. Analyzing metric data directly from logs is inefficient and complex, which highlights the need to extract it from the logs during collection and store it as a separate signal. This capability already exists on the receiving end of many monitoring platforms ([1](https://coralogix.com/docs/user-guides/monitoring-and-insights/events2metrics/), [2](https://docs.datadoghq.com/logs/log_configuration/logs_to_metrics/), [3](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/MonitoringLogData.html)) - having it in OTel would greatly enhance it.
The [signaltometrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/signaltometricsconnector) connector is a huge step toward this, but it does not produce the [gauge](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#gauge) metric type currently. This is a request to add gauge to the list of supported produced metrics.

### Describe the solution you'd like

Example configuration:
```
connectors:
  signaltometrics:
    gauge:
      value: ExtractGrokPatterns(body, "%{TIMESTAMP_ISO8601:timestamp} Memory usage: %{NUMBER:memory_mb:float}MB")
```
Log: `2025-01-08 16:28:00 Memory usage: 600MB`
Result:
```
[
  {
    "timestamp": "2025-01-08 16:28:00",
    "memory_mb": 600
  }
]
```
