### ISSUE TITLE
Attribute not being exported

### ISSUE THREAD

**Issue by alecernas** [open-telemetry/opentelemetry-collector-contrib#37178]
### Component(s)

processor/transform

## Description
I want to set an attribute depending on my log file path, but apparently that is not possible
## Steps to Reproduce
Config file is enough 

## Expected Result
I should be able to see the category attribute
## Actual Result
No category attribute present, if I remove the "where" part then it works, but I need  those attributes set some how

### Collector version

0.103.0

## Environment
Debian OS
https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.103.0/otelcol-contrib_0.103.0_linux_amd64.deb

### OpenTelemetry Collector configuration

```yaml
receivers:
  # Detailed configuration options can be found at https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver
  filelog:
    # File path pattern to read logs from. Update this to the destination from where you want to read logs.
    include: ["my-log.log", "another-log.log"]
    include_file_path: true
    # attributes:
      # A map of key: value pairs to add to the entry's attributes.
    # resource:
      # A map of key: value pairs to add to the entry's resource.
    resource:
      service.name: "my-qa-app"
      deployment.environment: "qa"
    retry_on_failure:
      enabled:
        true
processors:
  resourcedetection/ec2:
    detectors: ["ec2"]
    ec2:
      # A list of regex's to match tag keys to add as resource attributes can be specified
      tags:
        # This means you have a tag `Name` associated with the EC2 Instance.
        - ^Name$
  transform/ec2:
    error_mode: ignore
    log_statements:
      - context: resource
        statements:
          - set(attributes["category"], "main-log") where attributes["log.file.name"] == "my-log.log"
          - set(attributes["category"], "another-log") where attributes["log.file.name"] == "another-log.log"
  service:
    pipelines:
      logs:
        receivers: [filelog]
        processors: [resourcedetection/ec2, transform/ec2]
        exporters: [otlp/last9]
```

**Comment by bacherfl** [comment]
Hi @alecernas ! I just tried this and it seems like the `log.file.name` attribute is not part of the `resource` attributes, but of the attributes in the `log` context, i.e. of the log entries. Can you try to change the transform processor config to the following and see if this helps?

```
    log_statements:
      - context: log  # <-- instead of resource
        statements:
          - set(attributes["category"], "main-log") where attributes["log.file.name"] == "my-log.log"
          - set(attributes["category"], "another-log") where attributes["log.file.name"] == "another-log.log"
```
