### ISSUE TITLE
Azure Monitor receiver doesn't honor time grain

### ISSUE THREAD

**Issue by an-mmx** [open-telemetry/opentelemetry-collector-contrib#37337]
### Component(s)

receiver/azuremonitor

## Description
Azure monitor receiver has gaps in metrics when collecting PT1M metrics with 1 minute interval. It results in data points lost.

## Steps to Reproduce
Configure Azure Monitor receiver to fetch any Azure metric with PT1M time grain

## Expected Result
Metrics received for every minute without gaps: for 60 minutes receive 60 data points.

## Actual Result
Some metrics are lost, for 60 minutes interval it collects roufly 40..45 data points.

### Collector version

v0.117.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug:
    verbosity: detailed

processors:
  filter/azuremonitor/eventhub:
    error_mode: ignore
    metrics:
      metric:
        - 'not name == "azure_incomingmessages_total"'

receivers:
  azuremonitor/eventhub:
    subscription_id: "${env:AM_SUBSCRIPTION_ID}"
    tenant_id: "${env:AM_TENANT_ID}"
    client_id: "${env:AM_SP_CLIENT_ID}"
    client_secret: "${env:AM_SP_CLIENT_SECRET}"
    collection_interval: 1m
    initial_delay: 1s
    resource_groups:
      - ${env:AM_RESOURCE_GROUP}
    services:
      - microsoft.eventhub/namespaces

service:
  pipelines:
    metrics:
      exporters:
      - debug
      processors:
      - filter/azuremonitor/eventhub
      receivers:
      - azuremonitor/eventhub
```

### Log output

```shell

```
