### ISSUE TITLE
elasticsearchexporter support for dynamic log Body json parsing

### ISSUE THREAD

**Issue by PowerSurj** [open-telemetry/opentelemetry-collector-contrib#37339]
### Component(s)

exporter/elasticsearch

### Is your feature request related to a problem? Please describe.

elasticsearchexporter doesn't do dynamic log Body json parsing without defining the Body schema.

When using transform processor merge_maps(cache, ParseJSON(body), "upsert") where IsMatch(body, "^\\{") 
all keys being prepended to attributes key.

However, we need to keep log message json keys to be at the root

### Describe the solution you'd like

support dynamic nested json log message parsing in the exporter
resulting with the fields at the root document level without attributes. prefix

as in example fluentd natively supports json parsing in the filter

### Describe alternatives you've considered

ELK Ingestion Pipelines can handle this, but it is an additional configuration dependency

**Comment by carsonip** [comment]
@PowerSurj sorry for the delayed response.

- Can you provide your elasticsearch exporter config, and ES version?
- Have you tried setting `mapping::mode` to `otel` or `bodymap`? See es exporter README for more details.

**Comment by PowerSurj** [comment]
We are running elasticsearch 8.15

exporter config snippet
```
exporters:
  elasticsearch/log:
    endpoints: https://elasticsearch-es-http.elastic-system.svc.cluster.local:9200
    logs_index: test
    password: ${username}
    tls:
      insecure: false
      insecure_skip_verify: true
    user: ${password}
```

we have been using fluentd with dynamic json parser filte, as considering consolidating log collection estate to otel collector without resulting in additional attributes prefix to all fields

is there currently an alternative to bodymap, which is experimental?
