### ISSUE TITLE
Filelog Receiver Not Handling Multiline Logs with line_start_pattern.

### ISSUE THREAD

**Issue by Rahuly360** [open-telemetry/opentelemetry-collector-contrib#37338]
> I have a mysql container logs containing multiple logs like Error logs , slow query logs and server logs together.
I need to parse slow query logs but it is not working .

Example logs : 
2025-01-05T20:11:50.970826-00:00 341377 [Note] [MY-010914] [Server] Aborted connection 341377 to db: 'TEST' user: 'TEST' host: 'TEST_HOST' (The client was disconnected by the server because of inactivity.).

==> /mysql_datadir/mysql_logs/slow_query.log <==

```
# Time: 2025-01-05T20:11:54.389753-00:00
# User@Host: mysql_backup[mysql_backup] @  [HOST_IP]  Id: 341646
# Query_time: 3.118553  Lock_time: 0.000001 Rows_sent: 191444  Rows_examined: 191444 Thread_id: 341646 Errno: 0 Killed: 0 Bytes_received: 60 Bytes_sent: 31005283 Read_first: 1 Read_last: 0 Read_key: 1 Read_next: 0 Read_prev: 0 Read_rnd: 0 Read_rnd_next: 191445 Sort_merge_passes: 0 Sort_range_count: 0 Sort_rows: 0 Sort_scan_count: 0 abc: 0 abc: 0 Start: 2025-01-05T20:11:51.271200-00:00 End: 2025-01-05T20:11:54.389753-00:00
use TEST;
SET timestamp=1736107911;
SELECT ABC FROM `ABC_Table`;
```

==> /mysql_datadir/mysql_logs/mysqld.log <==

```
2025-01-05T20:12:00.224997-00:00 341658 [Note] [MY-010914] [Server] Got packets out of order
2025-01-05T20:12:06.023456-00:00 341383 [Note] [MY-013730] [Server] 'wait_timeout' period of 600 seconds was exceeded for `TEST_Service`@`%`. The idle time since last command was too long.
```

I need to read slow query logs only 
like: 

```
# Time: 2025-01-05T20:11:54.389753-00:00
# User@Host: mysql_backup[mysql_backup] @  [HOST_IP]  Id: 341646
# Query_time: 3.118553  Lock_time: 0.000001 Rows_sent: 191444  Rows_examined: 191444 Thread_id: 341646 Errno: 0 Killed: 0 Bytes_received: 60 Bytes_sent: 31005283 Read_first: 1 Read_last: 0 Read_key: 1 Read_next: 0 Read_prev: 0 Read_rnd: 0 Read_rnd_next: 191445 Sort_merge_passes: 0 Sort_range_count: 0 Sort_rows: 0 Sort_scan_count: 0 abc: 0 abc: 0 Start: 2025-01-05T20:11:51.271200-00:00 End: 2025-01-05T20:11:54.389753-00:00
use TEST;
SET timestamp=1736107911;
SELECT ABC FROM `ABC_Table`;
```

Receiver Configuration:
```
      filelog:
        exclude:
        - some_files
        include:
        - some_files_containing_container_logs
        start_at: beginning
        include_file_name: true
        include_file_path: true
        multiline:
          line_start_pattern: '^# Time:'
        operators:
          - type: regex_parser
            regex: '^# Time:\s*(?P<time>[^\n]+)\n# User@Host:\s*(?P<user>[^[]+)\[(?P<user_role>[^\]]+)\]\s*@\s*(?P<host>[^\s]+)\s*\[\]\s*Id:\s*(?P<id>\d+)\n# Query_time:\s*(?P<query_time>\d+\.\d+)\s*Lock_time:\s*(?P<lock_time>\d+\.\d+)\s*Rows_sent:\s*(?P<rows_sent>\d+)\s*Rows_examined:\s*(?P<rows_examined>\d+)\s*Thread_id:\s*(?P<thread_id>\d+)\s*Errno:\s*(?P<errno>\d+)\s*Killed:\s*(?P<killed>\d+)\s*Bytes_received:\s*(?P<bytes_received>\d+)\s*Bytes_sent:\s*(?P<bytes_sent>\d+)\s*Read_first:\s*(?P<read_first>\d+)\s*Read_last:\s*(?P<read_last>\d+)\s*Read_key:\s*(?P<read_key>\d+)\s*Read_next:\s*(?P<read_next>\d+)\s*Read_prev:\s*(?P<read_prev>\d+)\s*Read_rnd:\s*(?P<read_rnd>\d+)\s*Read_rnd_next:\s*(?P<read_rnd_next>\d+)\s*Sort_merge_passes:\s*(?P<sort_merge_passes>\d+)\s*Sort_range_count:\s*(?P<sort_range_count>\d+)\s*Sort_rows:\s*(?P<sort_rows>\d+)\s*Sort_scan_count:\s*(?P<sort_scan_count>\d+)\s*Created_tmp_disk_tables:\s*(?P<created_tmp_disk_tables>\d+)\s*Created_tmp_tables:\s*(?P<created_tmp_tables>\d+)\s*Start:\s*(?P<start_time>[^\n]+)\s*End:\s*(?P<end_time>[^\n]+)\nSET\stimestamp=(?P<timestamp>\d+);\n(?P<query>[\s\S]+)$'
```

**Comment by Rahuly360** [comment]
@VihasMakwana @djaglowski  Can you please help here

**Comment by VihasMakwana** [comment]
I just noticed that you have 
```
Time: 2025-01-05T20:11:54.389753-00:00
```

But your `multiline` pattern has `^# Time:` and hence, it's not working. 
Please use https://regex101.com/ and figure out the right regex.

**Comment by Rahuly360** [comment]
I have a mysql container logs containing multiple logs like Error logs , slow query logs and server logs together.
I need to parse slow query logs but it is not working .

Example logs : 
2025-01-05T20:11:50.970826-00:00 341377 [Note] [MY-010914] [Server] Aborted connection 341377 to db: 'TEST' user: 'TEST' host: 'TEST_HOST' (The client was disconnected by the server because of inactivity.).

==> /mysql_datadir/mysql_logs/slow_query.log <==
# Time: 2025-01-05T20:11:54.389753-00:00
# User@Host: mysql_backup[mysql_backup] @  [HOST_IP]  Id: 341646
# Query_time: 3.118553  Lock_time: 0.000001 Rows_sent: 191444  Rows_examined: 191444 Thread_id: 341646 Errno: 0 Killed: 0 Bytes_received: 60 Bytes_sent: 31005283 Read_first: 1 Read_last: 0 Read_key: 1 Read_next: 0 Read_prev: 0 Read_rnd: 0 Read_rnd_next: 191445 Sort_merge_passes: 0 Sort_range_count: 0 Sort_rows: 0 Sort_scan_count: 0 abc: 0 abc: 0 Start: 2025-01-05T20:11:51.271200-00:00 End: 2025-01-05T20:11:54.389753-00:00
use TEST;
SET timestamp=1736107911;
SELECT ABC FROM `ABC_Table`;

==> /mysql_datadir/mysql_logs/mysqld.log <==
2025-01-05T20:12:00.224997-00:00 341658 [Note] [MY-010914] [Server] Got packets out of order
2025-01-05T20:12:06.023456-00:00 341383 [Note] [MY-013730] [Server] 'wait_timeout' period of 600 seconds was exceeded for `TEST_Service`@`%`. The idle time since last command was too long.


I need to read slow query logs only 
like: 
# Time: 2025-01-05T20:11:54.389753-00:00
# User@Host: mysql_backup[mysql_backup] @  [HOST_IP]  Id: 341646
# Query_time: 3.118553  Lock_time: 0.000001 Rows_sent: 191444  Rows_examined: 191444 Thread_id: 341646 Errno: 0 Killed: 0 Bytes_received: 60 Bytes_sent: 31005283 Read_first: 1 Read_last: 0 Read_key: 1 Read_next: 0 Read_prev: 0 Read_rnd: 0 Read_rnd_next: 191445 Sort_merge_passes: 0 Sort_range_count: 0 Sort_rows: 0 Sort_scan_count: 0 abc: 0 abc: 0 Start: 2025-01-05T20:11:51.271200-00:00 End: 2025-01-05T20:11:54.389753-00:00
use TEST;
SET timestamp=1736107911;
SELECT ABC FROM `ABC_Table`;



Receiver Configuration:
      filelog:
        exclude:
        - some_files
        include:
        - some_files_containing_container_logs
        start_at: beginning
        include_file_name: true
        include_file_path: true
        multiline:
          line_start_pattern: '^# Time:'
        operators:
          - type: regex_parser
            regex: '^# Time:\s*(?P<time>[^\n]+)\n# User@Host:\s*(?P<user>[^[]+)\[(?P<user_role>[^\]]+)\]\s*@\s*(?P<host>[^\s]+)\s*\[\]\s*Id:\s*(?P<id>\d+)\n# Query_time:\s*(?P<query_time>\d+\.\d+)\s*Lock_time:\s*(?P<lock_time>\d+\.\d+)\s*Rows_sent:\s*(?P<rows_sent>\d+)\s*Rows_examined:\s*(?P<rows_examined>\d+)\s*Thread_id:\s*(?P<thread_id>\d+)\s*Errno:\s*(?P<errno>\d+)\s*Killed:\s*(?P<killed>\d+)\s*Bytes_received:\s*(?P<bytes_received>\d+)\s*Bytes_sent:\s*(?P<bytes_sent>\d+)\s*Read_first:\s*(?P<read_first>\d+)\s*Read_last:\s*(?P<read_last>\d+)\s*Read_key:\s*(?P<read_key>\d+)\s*Read_next:\s*(?P<read_next>\d+)\s*Read_prev:\s*(?P<read_prev>\d+)\s*Read_rnd:\s*(?P<read_rnd>\d+)\s*Read_rnd_next:\s*(?P<read_rnd_next>\d+)\s*Sort_merge_passes:\s*(?P<sort_merge_passes>\d+)\s*Sort_range_count:\s*(?P<sort_range_count>\d+)\s*Sort_rows:\s*(?P<sort_rows>\d+)\s*Sort_scan_count:\s*(?P<sort_scan_count>\d+)\s*Created_tmp_disk_tables:\s*(?P<created_tmp_disk_tables>\d+)\s*Created_tmp_tables:\s*(?P<created_tmp_tables>\d+)\s*Start:\s*(?P<start_time>[^\n]+)\s*End:\s*(?P<end_time>[^\n]+)\nSET\stimestamp=(?P<timestamp>\d+);\n(?P<query>[\s\S]+)$'

**Comment by Rahuly360** [comment]
@VihasMakwana My logs also have   below multiline logs it should pickup as body but it is not picking 

# Time: 2025-01-05T20:11:54.389753-00:00
# User@Host: mysql_backup[mysql_backup] @  [HOST_IP]  Id: 341646
# Query_time: 3.118553  Lock_time: 0.000001 Rows_sent: 191444  Rows_examined: 191444 Thread_id: 341646 Errno: 0 Killed: 0 Bytes_received: 60 Bytes_sent: 31005283 Read_first: 1 Read_last: 0 Read_key: 1 Read_next: 0 Read_prev: 0 Read_rnd: 0 Read_rnd_next: 191445 Sort_merge_passes: 0 Sort_range_count: 0 Sort_rows: 0 Sort_scan_count: 0 abc: 0 abc: 0 Start: 2025-01-05T20:11:51.271200-00:00 End: 2025-01-05T20:11:54.389753-00:00
use TEST;
SET timestamp=1736107911;
SELECT ABC FROM `ABC_Table`;

**Comment by Rahuly360** [comment]
## Time: 2025-01-05T20:11:54.389753-00:00
## User@Host: mysql_backup[mysql_backup] @  [HOST_IP]  Id: 341646
## Query_time: 3.118553  Lock_time: 0.000001 Rows_sent: 191444  Rows_examined: 191444 Thread_id: 341646 Errno: 0 Killed: 0 Bytes_received: 60 Bytes_sent: 31005283 Read_first: 1 Read_last: 0 Read_key: 1 Read_next: 0 Read_prev: 0 Read_rnd: 0 Read_rnd_next: 191445 Sort_merge_passes: 0 Sort_range_count: 0 Sort_rows: 0 Sort_scan_count: 0 abc: 0 abc: 0 Start: 2025-01-05T20:11:51.271200-00:00 End: 2025-01-05T20:11:54.389753-00:00
use TEST;
SET timestamp=1736107911;
SELECT ABC FROM `ABC_Table`;

**Comment by Rahuly360** [comment]
@VihasMakwana before the 
Time
User
Query_time 
there is # but it is not showing in description
you can check logs here
https://mysql.wisborg.dk/2019/01/31/more-statistics-for-slow-queries-log_slow_extra/



``

**Comment by andrzej-stencel** [comment]
@Rahuly360 sorry for being late to the party. Your regex is doesn't match the example log you posted, so I suppose you're getting an error similar to `Failed to process entry {"operator_id": "regex_parser", "operator_type": "regex_parser", "error": "regex pattern does not match", "action": "send", "entry.timestamp": "0001-01-01T00:00:00.000Z", "log.file.name": "mysql-slow-logs.log"}`.

You probably need to work on your regex. From a quick debugging, it breaks down on parsing the host / host IP part of the log.

This still works:

```yaml
receivers:
  filelog:
    include:
      - mysql-slow-logs.log
    start_at: beginning
    multiline:
      line_start_pattern: '^# Time:'
    operators:
      - type: regex_parser
        regex: '^# Time:\s*(?P<time>[^\n]+)\n# User@Host:\s*(?P<user>[^[]+)\[(?P<user_role>[^\]]+)\]\s*@\s*(?P<host>[^\s]+)\s*' # Still works
```

But this doesn't:


```yaml
receivers:
  filelog:
    include:
      - mysql-slow-logs.log
    start_at: beginning
    multiline:
      line_start_pattern: '^# Time:'
    operators:
      - type: regex_parser
        regex: '^# Time:\s*(?P<time>[^\n]+)\n# User@Host:\s*(?P<user>[^[]+)\[(?P<user_role>[^\]]+)\]\s*@\s*(?P<host>[^\s]+)\s*\[\]\s*' # Doesn't work
```
