### ISSUE TITLE
Instrumentation scope is not set for stanza based receivers

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-collector-contrib#37348]
### Component(s)

receiver/filelog, receiver/journald, receiver/syslog, receiver/otlpjsonfile

## Description

[Instrumentation Scope](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L72) OpenTelemetry log record field is not set for receivers that are created using Stanza's internal package. This field is very useful when configuring routing pipelines based on the receiver name/type. 

## Steps to Reproduce (Linux)

```
$ make otelcontribcol
$ ./bin/otelcontribcol_linux_amd64 --config filelog.yaml 2>&1 | grep InstrumentationScope
```
(write some logs, e.g: `echo "hii" >> /tmp/hello.log`)

## Expected Result

```
InstrumentationScope  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelog 0.117.0-dev
InstrumentationScope  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelog 0.117.0-dev
InstrumentationScope  github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelog 0.117.0-dev
```

## Actual Result

```
InstrumentationScope
InstrumentationScope
InstrumentationScope
```

### Collector version

v0.117.0, 1b93d01364

## Environment
OS: Arch
Compiler: go1.23.4

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include:
      - /tmp/hello.log
processors:
  batch:
exporters:
  debug/vvv:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [debug/vvv]
```

### Log output

```shell

```
