### ISSUE TITLE
Logzio exporter mkdir /tmp: permission denied

### ISSUE THREAD

**Issue by yotamloe** [open-telemetry/opentelemetry-collector-contrib#3736]
We have an issue with our logzio exporter users are getting errors using it from opentelemetry-collector-contrib image version >= 0.24
```
otel-agent    | Error: cannot build pipelines: cannot build builtExporters: error creating logzio exporter: mkdir /tmp: permission denied
otel-agent    | 2021/06/07 10:20:51 application run finished with error: cannot build pipelines: cannot build builtExporters: error creating logzio exporter: mkdir /tmp: permission denied
```
The exporter works fine with version <=0.23.

**Steps to reproduce**
* Run opentelemetry-collector-contrib docker image version >= 0.24 with logzio [exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/logzioexporter)

**What version did you use?**
Version >= `0.24`
Works fine with version <= `0.23`

**What config did you use?**
```yaml
receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"

exporters:
  logzio:
    account_token: "****"
    region: "us"

service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [logzio]
```
