### ISSUE TITLE
New component: Lightstep receiver

### ISSUE THREAD

**Issue by kostz** [open-telemetry/opentelemetry-collector-contrib#37383]
### The purpose and use-cases of the new component

Hello community, we have just released a Lightstep receiver https://github.com/zalando/otelcol-lightstep-receiver , and I'm wondering if we can include this into contrib pack someday.

This component receives tracing traffic from `lightstep_tracer_(go|python|js)`, converts it to open telemetry and propagates via tracing pipeline.

Also here's Zalando engineering [blog post](https://engineering.zalando.com/posts/2025/01/otelcollector-lightstep-receiver-oss.html) introducing the component.

### Example configuration for the component

```
receivers:
  lightstepreceiver:
    protocols:
      pbgrpc:
        endpoint: "0.0.0.0:4317"
      pbhttp:
        endpoint: "0.0.0.0:4327"
      thrift:
        endpoint: "0.0.0.0:4417"
```

### Telemetry data types supported

traces
