### ISSUE TITLE
[ecs_observer]: Add params support

### ISSUE THREAD

**Issue by oleg-glushak** [open-telemetry/opentelemetry-collector-contrib#37404]
### Component(s)

extension/observer/ecsobserver

### Is your feature request related to a problem? Please describe.

To be able to scrape endpoints with optional URL parameters we need to add `params` field support to be consumed as per https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config

This issue is motivated by the real scenario where we'd like to scrape `detailed` [RabbitMQ metrics](https://www.rabbitmq.com/docs/prometheus) and need to form this URL to scrape: `/metrics/detailed?family=myfamily1&family=mafamily2`. Currently there doesn't seem to be an option for it.

### Describe the solution you'd like

Add `params` field next to the `metrics_path` field following the format described in [Prometheus scrape_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config)

### Describe alternatives you've considered

Putting the line with URL parameters`/metrics/detailed?family=myfamily1&family=mafamily2` to the `metrics_path` field. This doesn't work (and it seems [isn't supposed to work](https://stackoverflow.com/questions/40172415/question-mark-in-prometheus-metrics-path-gets-encoded)) with the `Failed to scrape Prometheus endpoint` error in the logs.

### Additional context

If we confirm that it's the right direction, I'd be happy to implement it.

**Comment by oleg-glushak** [comment]
It seems there's a working workaround and this feature isn't necessarily needed:

The working snippet for our specific case looks like that:

```
       - job_name: "rabbitmq"
          metrics_path: /metrics/detailed
          params:
            family: ['myfamily']
```

```
  ecs_observer/rabbitmq:
    refresh_interval: 60s
    cluster_name: ${esc_cluster_name}
    cluster_region: ${region}
    result_file: '/etc/ecs_sd_targets_rabbitmq.yaml'
    task_definitions:
      - metrics_path: '/metrics/detailed'
        arn_pattern: '.*'
        metrics_ports:
          - 15692 
```
