### ISSUE TITLE
[routing/connector] Invalid configuration when using context other than resource

### ISSUE THREAD

**Issue by vlaborie** [open-telemetry/opentelemetry-collector-contrib#37410]
### Component(s)

connector/routing

## Description

The collector crash with in invalid configuration error when a request context is used with routing/connector.

## Steps to Reproduce

Use a routing connector with **request** context.

## Expected Result

No configuration error.

## Actual Result

Collector crash with invalid configuration error.

### Collector version

0.118.0

## Environment
Docker: otel/opentelemetry-collector-contrib:0.118.0

### OpenTelemetry Collector configuration

```yaml
connectors:
      routing/logs:
        default_pipelines: [logs/default]
        table:
          - context: request
            condition: request["x-tenant"] == "tenant-1"
            pipelines: [logs/tenant-1]
      routing/metrics:
        default_pipelines: [metrics/default]
        table:
          - context: request
            condition: request["x-tenant"] == "tenant-1"
            pipelines: [logs/tenant-1]
      routing/traces:
        default_pipelines: [traces/default]
        table:
          - context: request
            condition: request["x-tenant"] == "tenant-1"
            pipelines: [traces/tenant-1]
```

### Log output

```shell
Error: invalid configuration: connectors::routing/metrics: invalid context: request
2025/01/22 11:05:04 collector server run finished with error: invalid configuration: connectors::routing/metrics: invalid context: request
```
