### ISSUE TITLE
Collector sending queue value not getting reflected

### ISSUE THREAD

**Issue by adithya-r-nathan** [open-telemetry/opentelemetry-collector-contrib#37445]
### Component(s)

exporter/clickhouse

## Description
The sending_queue.queue_size configuration was set to 10000 for the OpenTelemetry Collector’s ClickHouse exporter. However, when checking the metrics, the queue size appears to be set to the default value of 1000. This discrepancy suggests that the configured value is not being applied as expected.
	•	Operator Version: 0.68.1
	•	Collector Image: otel/opentelemetry-collector-contrib:0.109.0

## Steps to Reproduce
Steps to Reproduce
	1.	Deploy an OpenTelemetry Collector using the following configuration:
                `exporters:
                      clickhouse:
                        endpoint: tcp://{{.Values.endpoints }}
                        username: {{.Values.db_user | quote }}
                        database: {{.Values.database }}
                        password: {{.Values.db_pw | quote }}
                        logs_table_name:  {{ .Values.logtable }}
                        traces_table_name: otel_traces
                        create_schema: true
                        ttl: 12h
                        timeout: 10s
                        sending_queue:
                          queue_size: 10000
                        retry_on_failure:
                          enabled: true
                          initial_interval: 5s
                          max_interval: 30s
                          max_elapsed_time: 300s`
	2.	Verify that the deployment uses:
	•	OpenTelemetry Operator: 0.68.1
	•	Collector Image: otel/opentelemetry-collector-contrib:0.109.0
	3.	Monitor the metrics using the /metrics endpoint or Prometheus.
	4.	Look for the exporter_send_queue_size metric.
## Expected Result
The exporter_send_queue_size metric should reflect the configured value of 10000.

## Actual Result
The exporter_send_queue_size metric shows the default value of 1000, indicating that the configuration was not applied.

### Collector version

v0.109.0

## Environment
OS: AWS EKS (Managed Kubernetes Service)
Cluster Version: 1.30

### OpenTelemetry Collector configuration

```yaml
exporters:
      clickhouse:
        endpoint: tcp://{{.Values.endpoints }}
        username: {{.Values.db_user | quote }}
        database: {{.Values.database }}
        password: {{.Values.db_pw | quote }}
        logs_table_name:  {{ .Values.logtable }}
        traces_table_name: otel_traces
        create_schema: true
        ttl: 12h
        timeout: 10s
        sending_queue:
          queue_size: 10000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
```

### Log output

```shell
{
    "metric": {
      "__name__": "otelcol_exporter_queue_capacity",
      "app_kubernetes_io_component": "opentelemetry-collector",
      "app_kubernetes_io_instance": "otel-agent.otel-log-agent",
      "app_kubernetes_io_managed_by": "opentelemetry-operator",
      "app_kubernetes_io_name": "otel-log-agent-collector",
      "app_kubernetes_io_part_of": "opentelemetry",
      "app_kubernetes_io_version": "0.109.0",
      "argocd_argoproj_io_instance": "ms-prd-ff-otel-agent",
      "cluster": "ms-prd",
      "controller_revision_hash": "7fcbf5ff45",
      "eks_cluster": "ms-prd",
      "exporter": "otlp",
      "instance": "100.0.1.233:8888",
      "job": "kubernetes-pods",
      "kubernetes_namespace": "otel-agent",
      "kubernetes_pod_name": "otel-log-agent-collector-bmrl8",
      "pod_template_generation": "3",
      "prometheus": "vm-agent/vm-stack",
      "service_instance_id": "d743e776-a212-49fe-abc7-1733161f9ac3",
      "service_name": "otelcol-contrib",
      "service_version": "0.109.0"
    },
    "value": [
      1737646453.21,
      "1000"
    ],
    "group": 1
  }
```

### Additional context

![Image](https://github.com/user-attachments/assets/6ef12f56-d327-42c3-9759-9617cabd91c0)

In argocd I am able to see the configuration as 10000 but in metrics it is 1000(default value).
