### ISSUE TITLE
Support for Common Event Format (CEF) over syslog

### ISSUE THREAD

**Issue by sboschman** [open-telemetry/opentelemetry-collector-contrib#37442]
### Component(s)

receiver/syslog

### Is your feature request related to a problem? Please describe.

Some of our network devices (e.g. firewalls) only support CEF (over syslog). To be able to ingest these logs into an otel pipeline for further processing and storage we would like to forward them to the `receiver/syslog` otel component. Unfortunately only the RFC3164 and RFC5424 protocols/formats are supported at the moment.

### Describe the solution you'd like

Expand the supported stanza parser for syslog protocols/formats with Common Event Format (CEF) [additional info](https://www.splunk.com/en_us/blog/learn/common-event-format-cef.html).

**Comment by odubajDT** [comment]
If this is accepted, I would like to take on the implementation

**Comment by djaglowski** [comment]
Would this mean adding a new protocol to the syslog receiver? Or is it a second step of parsing that occurs after receiving a 
syslog message?

**Comment by sboschman** [comment]
To my understanding CEF is just the message format, and syslog can be used as the transport mechanism.

> CEF uses Syslog as a transport mechanism. It uses the following format that contains a
Syslog prefix, a header, and an extension:
Jan 18 11:07:53 host CEF:Version|Device Vendor|Device Product|Device
Version|Device Event Class ID|Name|Severity|[Extension]

```
Sep 19 08:26:10 host CEF:0|Security|threatmanager|1.0|100|worm successfully stopped|10|src=10.0.0.1 dst=2.1.2.2 spt=1232
```

[source](https://www.microfocus.com/documentation/arcsight/arcsight-smartconnectors-8.4/pdfdoc/cef-implementation-standard/cef-implementation-standard.pdf)


Our current forwarding setup, which we would like to migrate to otelcol, is based on fluentd:
```
<source>
  @type syslog

  frame_type octet_count
  <transport tcp>
  </transport>

  emit_unmatched_lines true
</source>

# Try to parse CEF (Common Event Format)
<filter syslog.unmatched>
  @type parser
  key_name unmatched_line
  <parse>
    @type cef
  </parse>
</filter>
```

Which seems to support the idea that it is the second step of parsing the incoming syslog messages in terms of the otel collector.

**Comment by djaglowski** [comment]
It sounds like a standalone parser would be more appropriate than including this in the syslog input. Another way to look at it - if you use another mechanism besides syslog to transmit CEF logs, then wouldn't you want to be able to parse those in the same way?

**Comment by sboschman** [comment]
Currently the message transport layer and message parsing are both encapsulated in the `syslog` receiver component. The `syslog_input` operator embeds the `syslog_parser` as far as I can tell.

It is not possible to use the message transport layer of `syslog_input` with f.e. the `regex_parser`. So, the `syslog_input` operator does need some sort of support to plug a parser capable of parsing CEF. Allowing us to use the `syslog` receiver to ingest messages formatted with CEF.

The actual CEF parsing can be done in the `syslog_parser` (e.g. `syslog.protocol=cef`) or in a separate `cef_parser`. In the latter case the `syslog_input` config should allow for choosing the parser and not require the `syslog` field in its config. But in both cases cef parsing can be plugged into f.e. the `filelog` receiver.

**Comment by djaglowski** [comment]
To be clear, the `syslog_input` is just:
- Either `tcp_input` or `udp_input`
- Then `syslog_parser`
- Then optionally apply arbitrary `operators` (which could include `cef_parser`)

I thought we had established that CEF is a text format that may be carried inside of a syslog payload. In that case, you could do e.g.: `tcp_input -> syslog_parser -> cef_parser` (Or equivalently, `syslog_input -> cef_parser`)

However, if you are saying it is a format that should be parsed _instead_ of syslog, then you can do e.g. `tcp_input -> cef_parser` and skip syslog altogether.

**Comment by sboschman** [comment]
I am a bit confused here, where is f.e. [RFC 6587](https://www.rfc-editor.org/rfc/rfc6587#section-3.4.1) Octet Counting handled? Octet Counting to me is part of the syslog transport layer and has nothing to do with the parsing of the syslog message and shouldn't be handled by `syslog_parser`.

(The following might not reflect the actual code impl, but merely my idea of how a syslog pipeline works)
`tcp_input` (or `udp_input`)
&nbsp;&nbsp;&nbsp;&darr;
`syslog_input` (handling the transport layer, e.g. Octet Counting and outputting a syslog message, regardless the format of the message)
&nbsp;&nbsp;&nbsp;&darr;
`message_parser` (the actual message might be formatted according to RFC5424, RFC3164, CEF, LEEF or ...)


RFC 6587 defines the syslog message stream as follows:
```
TCP-DATA = *SYSLOG-FRAME

       SYSLOG-FRAME = MSG-LEN SP SYSLOG-MSG   ; Octet-counting
                                              ; method

       MSG-LEN = NONZERO-DIGIT *DIGIT

       NONZERO-DIGIT = %d49-57

       SYSLOG-MSG is defined in the syslog protocol RFC5424 and may
                  also be considered to be the payload in[RFC3164
```

So to me `tcp_input` -> `syslog_parser` makes no sense, as `tcp_input` is about `TCP-DATA` and `syslog_parser` is about `SYSLOG-MSG`. I am missing something to handle `SYSLOG-FRAME` (which I thought was the role of `syslog_input`.

> I thought we had established that CEF is a text format that may be carried inside of a syslog payload. In that case, you could do e.g.: tcp_input -> syslog_parser -> cef_parser (Or equivalently, syslog_input -> cef_parser)

Yes, CEF is the text format carried as `SYSLOG-MSG` (I would call this the syslog payload, but perhaps that is wrong). So `tcp_input` -> `syslog_parser` -> `cef_parser` is not going to work, as it is first going to parse a CEF message as RFC5424 or RFC3164 and will fail. The `SYSLOG-MSG` should not be parsed as if it were a RFC5424 or RFC3164 formatted message.

> However, if you are saying it is a format that should be parsed instead of syslog, then you can do e.g. tcp_input -> cef_parser and skip syslog altogether.

Yes, CEF should be parsed instead of syslog RFC5424 or RFC3164 format. But no, you can't skip syslog altogether. You still need the syslog transport layer (`SYSLOG-FRAME`) part before you get to the `SYSLOG-MSG`.

**Comment by djaglowski** [comment]
Thanks for explaining @sboschman. I'm in support of using `syslog_input` to handle the transport, including octet counting. However, since CEF is clearly not a syslog format, I think it would make sense to make `protocol` optional or allow a value such as `none`. Then, we can implement a `cef_parser` separately and use it in any logs receiver. Does this sound acceptable?

**Comment by sboschman** [comment]
A seperate `cef_parser` sounds like a good option. All though the way in which CEF piggybacks onto the syslog transport layer (in the case of 'CEF over syslog') might make it a bit more complicated than just swapping `syslog_parser` for `cef_parser`. I will try to make some time this week to have a look at the actual `syslog_input` and `syslog_parser` code, to better understand the issue from a code perspective.

**Comment by sboschman** [comment]
OK, had a bit of time to look at the code (disclaimer, my golang skills are seriously lacking). I understand now that the `syslog_parser` basically is a wrapper around an upstream syslog library, which does most of the heavy lifting. From an otelcol perspective a `cef_parser` would make the most sense. But atm I don't see how to integrate this with the upstream syslog library. Duplicating a lot of the syslog code from the library, up to the point where CEF comes into play doesn't sound very appealing to me. Maybe ask the upstream syslog library for a custom parser hook?

**Comment by Dylan-M** [comment]
> a `cef_parser` would make the most sense. But atm I don't see how to integrate this with the upstream syslog library.

You wouldn't. It would be a processor. Specifically the transform processor. You would bring it in, and the CEF data would be in the "message" after parsing the syslog. After that, you would add a processor to parse out the CEF portion.

**Comment by sboschman** [comment]
@Dylan-M perhaps I don't understand the current syslog receiver and processors. But as far as I understand you have to intercept the CEF message within the syslog stream. You cannot first parse the syslog stream as RFC5424, which is done by the syslog receiver (actually the included upstream syslog lib), and then add a second parse/process step taking a RFC5424 syslog message as input. If you sent CEF over syslog it currently rejects the message as it is not RFC5424, and the message never makes it to e.g. a transform processor downstream in the pipeline.

**Comment by Dylan-M** [comment]
> [@Dylan-M](https://github.com/Dylan-M) perhaps I don't understand the current syslog receiver and processors. But as far as I understand you have to intercept the CEF message within the syslog stream. You cannot first parse the syslog stream as RFC5424, which is done by the syslog receiver (actually the included upstream syslog lib), and then add a second parse/process step taking a RFC5424 syslog message as input. If you sent CEF over syslog it currently rejects the message as it is not RFC5424, and the message never makes it to e.g. a transform processor downstream in the pipeline.

Adding support for CEF isn't what is causing that to fail. Your messages not perfectly matching the RFCs (the Library is overly strict) is what causes the parsing failure.

I don't (can't) use the Syslog parser at all right now due to these limitations (also, the parser isn't part of the receiver the way you think - the receiver is just TCP or UDP, and then syslog parsing is already a secondary function). Because it is based on the Stanza library, it uses tcp or udp, and then passes it off to the Stanza syslog_parser operator (note operator there, a part of the Stanza library).

Below is my current massive, and disgusting, syslog parser using regex. This is 100% OTTL, and expects the raw data via TCP or UDP receivers. You'll notice I already handle LEEF messages, and I could easily add other formats like CEF to it. However, regex is horribly inefficient for this, so I've been holding off waiting for actual OTTL parsers for these things to be written.

```
# mega-syslog-parser v3.1
transform:
  error_mode: ignore
  log_statements:
    - context: log
      statements:
        # syslog-ng-prefix
        - set(attributes["syslog-ng"], "true") where not IsMap(body) and IsMatch(body, "\\w{3}\\s\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\s\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\s(\\d+\\s)?<\\d+>.*")
        - set(body, ExtractPatterns(body, "\\w{3}\\s\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\s\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\s(?P<syslog_message>(\\d+\\s)?<\\d+>.*)")) where not IsMap(body) and IsMatch(body, "\\w{3}\\s\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\s\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\s(\\d+\\s)?<\\d+>.*")
        - set(body, body["syslog_message"]) where IsMap(body) and body["syslog_message"] != nil

        # ESXi "Syslog"
        # <182>2024-07-25T18:54:02.265Z esxi-a vmkernel: cpu21:2097238)ScsiDeviceIO: 4124: Cmd(0x45b9309b77c8) 0x42, CmdSN 0xd82373 from world 20761373 to dev "t10.VMDRAID_Intel_Raid_1_VolumeVolume000000001" failed H:0xc D:0x0 P:0x0
        - set(attributes["syslog_type"], "syslog from ESXi devices") where not IsMap(body) and IsMatch(body, "^(?:\\d+\\s)?<\\d+>\\d{1,4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?(?:[+-][\\d:]{4,5})?Z?\\s+[^\\s]+\\s+(?:[^\\s:]+?\\s[^\\:s]+?\\s[^\\:s]+?\\s(?:[^\\s\\[:]+?|\\[[^\\[\\]]+?\\])\\s+)?(?:[^\\s\\[:]+(?:\\[\\d+\\])?:\\s+)?.+$")
        - set(body, ExtractPatterns(body, "^((?P<framing_octet>\\d+)\\s)?<(?P<priority>\\d+)>(?P<timestamp>\\d{1,4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?(?:[+-][\\d:]{4,5})?Z?)\\s+(?P<hostname>[^\\s]+)\\s+(?:(?P<prefix>[^\\s:]+?\\s[^\\:s]+?\\s[^\\:s]+?\\s(?:[^\\s\\[:]+?|\\[[^\\[\\]]+?\\]))\\s+)?(?:(?P<process>[^\\s\\[:]+)(?:\\[(?P<pid>\\d+)\\])?:\\s+)?(?P<message>.+)$")) where not IsMap(body) and IsMatch(body, "^(?:\\d+\\s)?<\\d+>\\d{1,4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?(?:[+-][\\d:]{4,5})?Z?\\s+[^\\s]+\\s+(?:[^\\s:]+?\\s[^\\:s]+?\\s[^\\:s]+?\\s(?:[^\\s\\[:]+?|\\[[^\\[\\]]+?\\])\\s+)?(?:[^\\s\\[:]+(?:\\[\\d+\\])?:\\s+)?.+$")

        # rfc3164-tz-ip
        # <0>1990 Oct 22 10:52:01 TZ-6 scapegoat.dmz.example.org 10.1.2.3 sched[0]: That's All Folks!
        - set(attributes["syslog_type"], "syslog rfc3164 with added timezone and IP address") where not IsMap(body) and IsMatch(body, "^<\\d+>\\d{4}\\s+\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+TZ[+-]\\d+\\s+[^\\s]+\\s+\\d+\\.\\d+\\.\\d+\\.\\d+\\s+[^\\s:]+:\\s+.*")
        - set(body, ExtractPatterns(body, "^<(?P<priority>\\d+)>(?P<timestamp>\\d{4}\\s+\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+TZ[+-]\\d+)\\s+(?P<hostname>[^\\s]+)\\s+(?P<ip_addr>\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+(?P<process>[^\\s:]+):\\s+(?P<message>.*)")) where not IsMap(body) and IsMatch(body, "^<\\d+>\\d{4}\\s+\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+TZ[+-]\\d+\\s+[^\\s]+\\s+\\d+\\.\\d+\\.\\d+\\.\\d+\\s+[^\\s:]+:\\s+.*")

        # rfc3164-tz-yr
        # <165>Aug 24 05:34:00 CST 1987 mymachine myproc[10]: %% It's time to make the do-nuts.  %%  Ingredients: Mix=OK, Jelly=OK # Devices: Mixer=OK, Jelly_Injector=OK, Frier=OK # Transport: Conveyer1=OK, Conveyer2=OK # %%
        - set(attributes["syslog_type"], "syslog rfc3164 with added timezone and year") where not IsMap(body) and IsMatch(body, "^<\\d+>\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+\\w{3}\\s+\\d{4}\\s+[^\\s]+\\s+[^\\s:]+:\\s+.*")
        - set(body, ExtractPatterns(body, "^<(?P<priority>\\d+)>(?P<timestamp>\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+\\w{3}\\s+\\d{4})\\s+(?P<hostname>[^\\s]+)\\s+(?P<process>[^\\s:]+):\\s+(?P<message>.*)")) where not IsMap(body) and IsMatch(body, "^<\\d+>\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+\\w{3}\\s+\\d{4}\\s+[^\\s]+\\s+[^\\s:]+:\\s+.*")

        # cisco specific formats that don't correctly match standards
        - set(attributes["syslog_type"], "syslog cisco formatted near rfc3164") where not IsMap(body) and IsMatch(body, "^<\\d+>[^\\s:]+:\\s+[^\\s:]+:\\s+\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d{3})?:\\s+.*")
        - set(body, ExtractPatterns(body, "^<(?P<priority>\\d+)>(?P<pid>[^\\s:]+):\\s+(?P<hostname>[^\\s:]+):\\s+(?P<timestamp>\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d{3})?):\\s+(?P<message>.*)")) where not IsMap(body) and IsMatch(body, "^<\\d+>[^\\s:]+:\\s+[^\\s:]+:\\s+\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d{3})?:\\s+.*")
        - set(attributes["syslog_type"], "syslog cisco formatted near rfc5424") where not IsMap(body) and IsMatch(body, "^<\\d+>[^\\s]+\\s+\\d{4}\\s+\\w+\\s\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+\\w+:\\s+.*")
        - set(body, ExtractPatterns(body, "^<(?P<priority>\\d+)>(?P<version>[^\\s]+)\\s+(?P<timestamp>\\d{4}\\s+\\w+\\s\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+\\w+):\\s+(?P<message>.*)")) where not IsMap(body) and IsMatch(body, "^<\\d+>[^\\s:]+:\\s+[^\\s:]+:\\s+\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d{3})?:\\s+.*")

        # Cisco ASA Formatted "Syslog" RFC 3164 With Year
        # <167>May 20 2024 15:08:29: %ASA-7-777777: Built local-host inside:10.10.0.20
        - set(attributes["syslog_type"], "syslog rfc3164 cisco asa with optional year") where not IsMap(body) and IsMatch(body, "^(?:<\\d+>)?\\w+\\s{1,2}\\d{1,2}(?:\\s+\\d{4})?\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}:?\\s+[^\\s:]+:?\\s+(?:[^\\s\\[:]+(?:\\[\\d+\\])?:\\s+)?.*")
        - set(body, ExtractPatterns(body, "^(?:<(?P<priority>\\d+)>)?(?P<timestamp>\\w+\\s{1,2}\\d{1,2}(?:\\s+\\d{4})?\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}):?\\s+(?P<hostname>[^\\s:]+):?\\s+(?:(?P<process>[^\\s\\[:]+)(?:\\[(?P<pid>\\d+)\\])?:\\s+)?(?P<message>.*)")) where not IsMap(body) and IsMatch(body, "^(?:<\\d+>)?\\w+\\s{1,2}\\d{1,2}(?:\\s+\\d{4})?\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}:?\\s+[^\\s:]+:?\\s+(?:[^\\s\\[:]+(?:\\[\\d+\\])?:\\s+)?.*")

        # Access Point Logs 1
        # <190>363041: 363044: Nov 7 14:38:47.482 SST: %SEC-xx-xxxxxxx: list SNMP denied xx.xx.xx.xx xxx packets
        - set(attributes["syslog_type"], "near syslog from AP p1") where not IsMap(body) and IsMatch(body, "^(?:<\\d+>)(?:\\d+:?\\s+?\\d+:)?\\s+\\w+\\s{1,2}\\d{1,2}(?:\\s+\\d{4})?\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?:?\\s+.*")
        - set(body, ExtractPatterns(body, "^(?:<(?P<priority>\\d+)>)(?:(?P<proc_1>\\d+):?\\s+?(?P<proc_2>\\d+):)?\\s+(?P<timestamp>\\w+\\s{1,2}\\d{1,2}(?:\\s+\\d{4})?\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?):?\\s+(?P<message>.*)")) where not IsMap(body) and IsMatch(body, "^(?:<\\d+>)(?:\\d+:?\\s+?\\d+:)?\\s+\\w+\\s{1,2}\\d{1,2}(?:\\s+\\d{4})?\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?:?\\s+.*")

        # Access Point Logs 2
        # <132>7777-ABX1340-01: *spamApTask3: May 20 15:09:15.005: %LOG-4-Q_IND: [SA]capwap_ac_sm.c:2053 Ignoring discovery request received on a wrong VLAN (6) on interface (13) from AP 8D-C6-86-9D-08-3C
        - set(attributes["syslog_type"], "near syslog from AP p2") where not IsMap(body) and IsMatch(body, "^(?:<\\d+>)[^\\s:]+:?\\s+?(?:[^\\[:]+:)?\\s+\\w+\\s{1,2}\\d{1,2}(?:\\s+\\d{4})?\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?:?\\s+.*")
        - set(body, ExtractPatterns(body, "^(?:<(?P<priority>\\d+)>)(?P<hostname>[^\\s:]+):?\\s+?(?:(?P<process>[^\\[:]+):)?\\s+(?P<timestamp>\\w+\\s{1,2}\\d{1,2}(?:\\s+\\d{4})?\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?):?\\s+(?P<message>.*)")) where not IsMap(body) and IsMatch(body, "^(?:<\\d+>)[^\\s:]+:?\\s+?(?:[^\\[:]+:)?\\s+\\w+\\s{1,2}\\d{1,2}(?:\\s+\\d{4})?\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}(?:\\.\\d+)?:?\\s+.*")

        # rfc3164
        # <34>Oct 11 22:14:15 mymachine su: 'su root' failed for lonvick on /dev/pts/8
        - set(attributes["syslog_type"], "syslog rfc3164") where not IsMap(body) and IsMatch(body, "^<\\d+>\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+[^\\s]+\\s+[^\\s:]*?:?\\s*.*")
        - set(body, ExtractPatterns(body, "^(<(?P<priority>\\d+)>)?(?P<timestamp>\\w+\\s{1,2}\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2})\\s+(?P<hostname>[^\\s]+)\\s+(?:(?P<process>[^\\s\\[:]+)(?:\\[(?P<pid>\\d+)\\])?:\\s+)?(?P<message>.*)")) where not IsMap(body) and IsMatch(body, "^<\\d+>\\w+\\s+\\d{1,2}\\s+\\d{1,2}:\\d{1,2}:\\d{1,2}\\s+[^\\s]+\\s+[^\\s:]*?:?\\s*.*")

        # rfc5424
        # <85>1 2023-04-05T16:20:56Z loki.example.com su - ID47 - BOM'su root' failed for lonvick on /dev/pts/8
        # 757 <14>1 2022-10-19T15:15:32-07:00 b-fw-1-b.ruckus.edu - - - - 1,2022/10/19 15:15:24,012501002053,TRAFFIC,end,2561,2022/10/19 15:15:24,10.13.63.5,138.23.62.34,0.0.0.0,0.0.0.0,Allow Internal Zones to Net Services,,,dns-base,vsys1,iecn,inside,ae4.1032,ae4.1030,RUCKUS-Log-Forwarding-Template,2022/10/19 15:15:24,4127477,1,50251,53,0,0,0x19,udp,allow,212,82,130,2,2022/10/19 15:14:54,0,any,,7088216349921087004,0x8000000000000000,10.0.0.0-10.255.255.255,United States,,1,1,aged-out,389,12,0,0,vsys1,b-fw-1-b,from-policy,,,0,,0,,N/A,0,0,0,0,79a1a95e-34c3-4819-b826-27391a206529,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,2022-10-19T15:15:32.492-07:00,,,infrastructure,networking,network-protocol,3,\"used-by-malware,has-known-vulnerability,pervasive-use\",dns,dns-base,no,no,0
        - set(attributes["syslog_type"], "syslog rfc5424") where not IsMap(body) and IsMatch(body, "^(\\d+\\s)?<\\d+>[^\\s]+\\s+\\d{1,4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}(\\.\\d+)?([+-][\\d:]{4,5})?Z?\\s+[^\\s]+\\s+[^\\s:]+?:?\\s*.*")
        - set(body, ExtractPatterns(body, "^(?:(?P<framing_octet>\\d+)\\s)?<(?P<priority>\\d+)>(?P<version>[^\\s]+)\\s+(?P<timestamp>\\d{1,4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}(\\.\\d+)?([+-][\\d:]{4,5})?Z?)\\s+(?P<hostname>[^\\s]+)\\s+(?:(?P<prefix>[^\\s:]+?\\s[^\\:s]+?\\s[^\\:s]+?\\s(?:[^\\s\\[:]+?|\\[[^\\[\\]\\]]+?\\]))\\s+)?(?:(?P<process>[^\\s\\[:]+)(?:\\[(?P<pid>\\d+)\\])?:\\s+)?(?P<message>.+)")) where not IsMap(body) and IsMatch(body, "^(\\d+\\s)?<\\d+>[^\\s]+\\s+\\d{1,4}-\\d{1,2}-\\d{1,2}T\\d{1,2}:\\d{1,2}:\\d{1,2}(\\.\\d+)?([+-][\\d:]{4,5})?Z?\\s+[^\\s]+\\s+[^\\s:]+?:?\\s*.*")

        # RFC 5424 with or without framing octet and a timestamp in UNIX time
        # <134>1 1729780712.350113344 SOMEPLACE_SOMEWHERE vpn_firewall src=xx.xx.xx.xx dst=xx.xx.xx.xx mac=00:00:00:00:0000:00 protocol=xxx sport=xxx dport=xxx pattern: allow (dst xx.xx.xx.xx/xx || dst xx.xx.xx.xx/xx)
        # <134>1 1729780712.341701835 SOMEPLACE_SOMEWHERE vpn_firewall src=xx.xx.xx.xx dst=xx.xx.xx.xx mac=00:00:00:00:0000 protocol=xxx sport=xxxx dport=xxxx pattern: allow all
        # <134>1 1729780711.444469190 SOMEPLACE_SOMEWHERE urls src=xx.xx.xx.xx:xx dst=xx.xx.xx.xx:xx mac=00:00:00:00:000 agent='Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko' request: GET http://xxxxxxxxxxxxxxxxx
        # <134>1 1729780721.993317388 ANOTHERPLACE_ELSEWHERE ip_flow_end src=xx.xx.xx.xx dst=xx.xx.xx.xx protocol=xxxx sport=xxxx dport=xxxx translated_src_ip=xx.xx.xx.xx translated_port=xxxx
        # <134>1 1729780721.993317388 ANOTHERPLACE_ELSEWHERE ip_flow_end src=xx.xx.xx.xx dst=xx.xx.xx.xx protocol=xxxx sport=xxxx dport=xxxx translated_src_ip=xx.xx.xx.xx translated_port=xxxx
        - set(attributes["syslog_type"], "syslog rfc5424_unix_ts") where not IsMap(body) and IsMatch(body, "^(?:\\d+\\s)?<\\d+>[^\\s]+\\s+\\d+\\.\\d+\\s+[^\\s]+\\s+(?:[^\\s:]+?\\s[^\\:s]+?\\s[^\\:s]+?\\s(?:[^\\s\\[:]+?|\\[[^\\[\\]]+?\\])\\s+)?(?:[^\\s\\[:]+(?:\\[\\d+\\])?:\\s+)?.+$")
        - set(body, ExtractPatterns(body, "^((?P<framing_octet>\\d+)\\s)?<(?P<priority>\\d+)>(?P<version>[^\\s]+)\\s+(?P<timestamp>\\d+\\.\\d+)\\s+(?P<hostname>[^\\s]+)\\s+(?:(?P<prefix>[^\\s:]+?\\s[^\\:s]+?\\s[^\\:s]+?\\s(?:[^\\s\\[:]+?|\\[[^\\[\\]]+?\\]))\\s+)?(?:(?P<process>[^\\s\\[:]+)(?:\\[(?P<pid>\\d+)\\])?:\\s+)?(?P<message>.+)$")) where not IsMap(body) and IsMatch(body, "^(?:\\d+\\s)?<\\d+>[^\\s]+\\s+\\d+\\.\\d+\\s+[^\\s]+\\s+(?:[^\\s:]+?\\s[^\\:s]+?\\s[^\\:s]+?\\s(?:[^\\s\\[:]+?|\\[[^\\[\\]]+?\\])\\s+)?(?:[^\\s\\[:]+(?:\\[\\d+\\])?:\\s+)?.+$")

        # Syslog encoded key value pairs
        # <189>date=2024-10-29 time=12:46:29 devname="xxxxxx" devid="xxxxx" logid="0000000013" type="traffic" subtype="forward" level="notice" vd="root" eventtime=1730227589896640962 tz="-0600" srcip=xx.xx.xx.xx srcport=xxx srcintf="xxxxx" srcintfrole="lan" dstip=xx.xx.xx.xx dstport=xx dstintf="wan1" dstintfrole="wan" sessionid=650905222 proto=17 action="accept" policyid=309 policytype="policy" poluuid="xxxxxxx" service="DNS" dstcountry="Reserved" srccountry="Reserved" trandisp="noop" duration=180 sentbyte=96 rcvdbyte=175 sentpkt=1 rcvdpkt=1 appcat="unscanned"
        - set(attributes["syslog_type"], "syslog encoded key values") where not IsMap(body) and IsMatch(body, "^(?:<\\d+>)[^=]+=[^=\\s]+.+[^=]+=[^=]+$")
        - set(body, ExtractPatterns(body, "^(?:<(?P<priority>\\d+)>)(?<kv_pairs>[^=]+=[^=\\s]+.+[^=]+=[^=]+)$")) where not IsMap(body) and IsMatch(body, "^(?:<\\d+>)[^=]+=[^=\\s]+.+[^=]+=[^=]+$")

        # Additional parsing for messages with subfields
        - set(body, ExtractPatterns(body["message"], "^(?P<timestamp>\\w{3}\\s+\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\s\\w{3}\\s\\d{4})\\|(?P<proc>[^\\|]+)\\|(?:\\[(?P<kv_pairs>[^\\[\\]]+)\\]|(?P<msg>[^\\|]+))\\|(?P<trigger>[^\\|]+)\\|(?P<event>[^\\|]+)\\|(?P<ip_a>[\\.\\d]+)\\|(?P<ip_b>[\\.\\d]+)")) where IsMap(body) and body["message"] != nil and not IsMap(body["message"]) and IsMatch(body["message"], "^\\w{3}\\s+\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\s\\w{3}\\s\\d{4}\\|[^\\|]+\\|(?:\\[[^\\[\\]]+\\]|[^\\|]+)\\|[^\\|]+\\|[^\\|]+\\|[\\.\\d]+\\|[\\.\\d]+")

        # Key value parsing
        - merge_maps(body, ParseKeyValue(body["kv_pairs"], delimiter="=", pairDelimiter=" "), "upsert") where IsMap(body) and body["kv_pairs"] != nil and body["kv_pairs"] != ""
        - set(body["timestamp"], body["time"]) where IsMap(body) and body["time"] != nil and body["time"] != "" and (body["timestamp"] == nil or body["timestamp"] == "")

        ## LEEF Parsing ##
        - merge_maps(body, ExtractPatterns(body["message"], "(?:(?P<message>.+LEEF:)?|LEEF:)(?P<LEEF_Version>[^|]+)\\|(?P<Vendor>[^|]+)\\|(?P<Product>[^|]+)\\|(?P<Version>[^|]+)\\|(?P<EventID>[^|]+)\\|((?P<pair_delimiter>([^|]|\\dx\\d{2}))\\|)?(?P<leefmessage>.*?)\\|?$"), "upsert") where IsMap(body) and body["message"] != nil and IsMatch(body["message"], ".*LEEF:\\d.*")
        # LEEF 2.0 Automatic Parser
        # Does not currently work due to a bug in ParseKeyValue()
        #- merge_maps(body, ParseKeyValue(body["leefmessage"], "=", body["pair_delimiter"]), "upsert") where IsMap(body) and body["leefmessage"] != nil and body["LEEF_Version"] == "LEEF:2.0" and body["pair_delimiter"] != nil
        # LEEF 2.0 Manual Parsers
        - merge_maps(body, ParseKeyValue(body["leefmessage"], "=", "^"), "upsert") where IsMap(body) and body["leefmessage"] != nil and body["LEEF_Version"] == "LEEF:2.0" and body["pair_delimiter"] != nil and body["pair_delimiter"] == "^"
        - merge_maps(body, ParseKeyValue(body["leefmessage"], "=", "!"), "upsert") where IsMap(body) and body["leefmessage"] != nil and body["LEEF_Version"] == "LEEF:2.0" and body["pair_delimiter"] != nil and body["pair_delimiter"] == "!"
        - merge_maps(body, ParseKeyValue(body["leefmessage"], "=", " "), "upsert") where IsMap(body) and body["leefmessage"] != nil and body["LEEF_Version"] == "LEEF:2.0" and body["pair_delimiter"] != nil and body["pair_delimiter"] == " "
        # LEEF 1.0 Manual Parsers
        - merge_maps(body, ParseKeyValue(body["leefmessage"], "=", " "), "upsert") where IsMap(body) and body["leefmessage"] != nil and body["LEEF_Version"] == "LEEF:1.0" and IsMatch(body["leefmessage"], "^(?:[^\\s\\t]+[^\\t\\w])+\\w+$$")
        - merge_maps(body, ParseKeyValue(body["leefmessage"], "=", "	"), "upsert") where IsMap(body) and body["leefmessage"] != nil and body["LEEF_Version"] == "LEEF:1.0" and IsMatch(body["leefmessage"], "^(?:[^\\s\\t]+\\t)+[^\\s\\t]+$$")
        - merge_maps(body, ParseKeyValue(body["leefmessage"], "=", "|"), "upsert") where IsMap(body) and body["leefmessage"] != nil and body["LEEF_Version"] == "LEEF:1.0" and IsMatch(body["leefmessage"], "^(?:[^\\s\\t]+\\|)+[^\\s\\t]+$$")

        ## Facility and Severity Parsers
        - set(body["facility"], String(Int(Int(body["priority"]) / 8))) where IsMap(body) and body["priority"] != nil and body["priority"] != ""
        - set(body["severity"], String(Int(body["priority"]) - (Int(body["facility"]) * 8))) where IsMap(body) and body["priority"] != nil and body["priority"] != ""
        - set(severity_number, 21) where IsMap(body) and (Concat([body["severity"]], "") == "0" or Concat([body["severity"]], "") == "1") and body["priority"] != nil and body["severity"] != nil
        - set(severity_number, 17) where IsMap(body) and (Concat([body["severity"]], "") == "2" or Concat([body["severity"]], "") == "3") and body["priority"] != nil and body["severity"] != nil
        - set(severity_number, 13) where IsMap(body) and Concat([body["severity"]], "") == "4" and body["priority"] != nil and body["severity"] != nil
        - set(severity_number, 9) where IsMap(body) and (Concat([body["severity"]], "") == "5" or Concat([body["severity"]], "") == "6") and body["priority"] != nil and body["severity"] != nil
        - set(severity_number, 5) where IsMap(body) and Concat([body["severity"]], "") == "7" and body["priority"] != nil and body["severity"] != nil

        # Clean up some temporary fields
        - delete_key(body, "time") where IsMap(body) and body["time"] != nil
        - delete_key(body, "timestamp") where IsMap(body) and body["timestamp"] != nil
        - delete_key(body, "kv_pairs") where IsMap(body) and body["kv_pairs"] != nil
        - delete_key(body, "severity") where IsMap(body) and body["severity"] != nil
        - delete_key(body, "leefmessage") where IsMap(body) and body["leefmessage"] != nil
        - delete_key(body, "priority") where IsMap(body) and body["priority"] != nil
```
