### ISSUE TITLE
[processor/resourcedetection]  Container env OTEL_RESOURCE_ATTRIBUTES not extracted when using pull receiver like prometheus, redis...

### ISSUE THREAD

**Issue by sswieton** [open-telemetry/opentelemetry-collector-contrib#37473]
### Component(s)

processor/resourcedetection

## Description

I would like to enrich resource attributes with environment variables defined in the containers using OTEL_RESOURCE_ATTRIBUTES variable
To achieve this, I used the **resourcedetection** processor.

The problem occurs only for pods detected by pull receivers. I have reproduced it with the Prometheus and Redis receivers.
The resource detection processor enriches Resource attributes with **only system metadata and not env variables.****

## Steps to Reproduce

I used a Pull receiver like **redisreceiver** or  **prometheusreceiver**

```
receivers:
    redis:
      endpoint: "redis-otlp-tcp:6379"
      collection_interval: 10s
      password: pwd
      username: user
```

**processor resourcedetection**

```
    resourcedetection:
      detectors: [env,system]
      timeout: 2s
      override: false
```

## Expected Result

The objective is to enrich resource attributes  with attributes that allow the execution of k8sattributes ( and the pod_association)

## Actual Result

In the Resource Attributes, I can only get information related to the system, not the env

```
Resource SchemaURL: https://opentelemetry.io/schemas/1.6.1
Resource attributes:
     -> redis.version: Str(7.2.5)
     -> host.name: Str(otel-collector-sandbox-7bb68868c7-6g884)
     -> os.type: Str(linux)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope github.com/open-telemetry/opentelemetry-collector-contrib/receiver/redisreceiver 0.115.0


```

### Collector version

0.115.1

## Environment

Kubernetes.
Version : Chart Helm opentelemetry-collector-0.111.1 
app Version : 0.115.1

### OpenTelemetry Collector configuration

```yaml
metrics:
        receivers:
          - redis
        processors:
          - resourcedetection
          - batch
        exporters: 
          - debug/verbose
```

### Log output

```shell

```
