### ISSUE TITLE
[BUG] metricsgeneration/infinite loop

### ISSUE THREAD

**Issue by bmiguel-teixeira** [open-telemetry/opentelemetry-collector-contrib#37474]
### Component(s)

processor/metricsgeneration

## Description

When using destination and metric1 with equal values (same metric) the processors enters an infinite loop.

## Steps to Reproduce

In a perfect scenario, when using the scaling operations, I would like to change the selected metric "in-place". However, if we set metric name equal name, the processor enters in infinite loop.
Config shown below.

```
  metricsgeneration/scale:
    rules:
    - name: linux_memory_free_percent_percent
      type: scale
      metric1: linux_memory_free_percent_percent
      operation: multiply
      scale_by: 100
```

This happens because we iterate over the metrics array, and if we find a atching metric, we scale it based on the operation and we "ADD IT" to the ongoing metrics array. If the metrics names are equal this causes never ending loop.

## Expected Result

Replace/update metric in-place. If thiscould be a desired behaviour for the config above, I can submit a PR.

## Actual Result

Infinite loop in processor.

### Collector version

0.118.0

## Environment
N/A

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

**Comment by VihasMakwana** [comment]
@bmiguel-teixeira 
From another perspective, this also happens because new metric's name conflicts with old:

```yaml
  metricsgeneration/scale:
    rules:
    - name: linux_memory_free_percent_percent # new name conflicts with metric1
      type: scale
      metric1: linux_memory_free_percent_percent
      operation: multiply
      scale_by: 100
```

We can only allow this if names are different? wdyt?
