### ISSUE TITLE
[processor/interval] unavailable in 0.118.0

### ISSUE THREAD

**Issue by wojciechkaleb** [open-telemetry/opentelemetry-collector-contrib#37501]
### Component(s)

[processor/interval]

## Description
I'm getting bug that processors/invervalprocessor is unknown type in the processor context
```
error decoding 'processors': unknown type: "intervalprocessor" for id: "intervalprocessor" (valid values: [probabilistic_sampler remotetap resourcedetection transform batch filter groupbyattrs groupbytrace metricsgeneration resource routing deltatocumulative attributes cumulativetodelta geoip logdedup redaction memory_limiter k8sattributes metricstransform span sumologic tail_sampling deltatorate])
```

I'm using opentelemetry-collector-contrib 0.118.0 and as mentioned in the release notes there should be as the new component.
https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.118.0

Is there anything more than the collector configuration I should adjust?
```
processors:
  intervalprocessor:
```

### Collector version

0.118.0

## Environment
OS: (e.g., "Ubuntu 20.04")

### OpenTelemetry Collector configuration

```yaml
extensions:
  basicauth/traces:
    client_auth:
      username: '${TEMPO_USER}'
      password: '${TEMPO_PASSWORD}'
  basicauth/metrics:
    client_auth:
      username: '${PROM_USER}'
      password: '${PROM_PASSWORD}'
  basicauth/logs:
    client_auth:
      username: '${LOKI_USER}'
      password: '${LOKI_PASSWORD}'
  health_check:
    endpoint: 0.0.0.0:${HEALTHCHECK_PORT}
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:${HTTP_PORT}

processors:
  batch/metrics:
    timeout: 10s
    send_batch_max_size: 20000
  batch/traces:
  intervalprocessor:


exporters:
  otlp:
    endpoint: '${TEMPO_ENDPOINT}'
    auth:
      authenticator: basicauth/traces
  prometheusremotewrite:
    endpoint: '${PROM_ENDPOINT}'
    auth:
      authenticator: basicauth/metrics

  loki:
    endpoint: '${LOKI_ENDPOINT}'
    auth:
      authenticator: basicauth/logs

service:
  extensions:
    [health_check, basicauth/traces, basicauth/metrics, basicauth/logs]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces, tail_sampling]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors:
        [
          intervalprocessor,
          batch/metrics,
        ]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      exporters: [loki]
```

### Log output

```shell
error decoding 'processors': unknown type: "intervalprocessor" for id: "intervalprocessor" (valid values: [probabilistic_sampler remotetap resourcedetection transform batch filter groupbyattrs groupbytrace metricsgeneration resource routing deltatocumulative attributes cumulativetodelta geoip logdedup redaction memory_limiter k8sattributes metricstransform span sumologic tail_sampling deltatorate])
```

### Additional context

Not sure if I understand your distribution process correctly and all the dependencies between projects but I've checked the manifest.yml of 0.118.0 and there is no `processors/intervalprocessor` mentioned
https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-contrib/manifest.yaml
