### ISSUE TITLE
Automatic metric relabel to append _total to metric name

### ISSUE THREAD

**Issue by sherabi** [open-telemetry/opentelemetry-collector-contrib#37510]
### Component(s)

prometheus receiver

### What happened?

I am using the latest version of OTel with K8s. It seems that the prometheus receiver automatically appends `_total` to the metric name for metrics of type `counter`.
I wanted to keep my original metric name and it seems almost impossible to undo the automatic renaming of the metric. I tried setting `trim_metric_suffixes: true` but it doesn't seem to work.

I tried `metric_relabel_configs` which also didn't seem to work with the prometheus receiver

```yaml
              metric_relabel_configs:
                - source_labels: [__name__]
                  regex: 'web_account_balance_fetch_results_total'
                  target_label: __name__
                  action: replace
                  replacement: 'web_account_balance_fetch_results'
                - source_labels: [__name__]
                  regex: 'web_account_balance_fetch_results'
                  action: keep
              metrics_path: /metrics
              scheme: http
```

I even tried the `metricstransform` processor which also did not work.

```yaml
      metricstransform:
        transforms:
          - include: web_account_balance_fetch_results_total
            match_type: strict
            action: update
            new_name: web_account_balance_fetch_results
```

How can I keep the original metric name?

### Collector version

0.118.0

### Environment information

GKE K8S version 1.30

### OpenTelemetry Collector configuration

```yaml
config:
    receivers:
      prometheus:
        trim_metric_suffixes: true
        config:
          scrape_configs:
            - job_name: 'synthetics'
              static_configs:
                - targets: ['synthetics.default.svc:3000']
                  labels:
                    service: 'synthetics'
              metric_relabel_configs:
                - source_labels: [__name__]
                  regex: 'web_account_balance_fetch_results_total'
                  target_label: __name__
                  action: replace
                  replacement: 'web_account_balance_fetch_results'
                - source_labels: [__name__]
                  regex: 'web_account_balance_fetch_results'
                  action: keep
              metrics_path: /metrics
              scheme: http
    processors:
      k8sattributes:
        auth_type: serviceAccount
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.namespace.name
            - k8s.container.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.job.name
            - k8s.daemonset.name
            - k8s.statefulset.name
            - k8s.cronjob.name
            - k8s.node.name
            - container.image.name
            - container.image.tag
      attributes:
        actions:
          - action: insert
            key: node_id
            from_attribute: node
          - action: delete
            key: node
      # metricstransform:
      #   transforms:
      #     - include: web_account_balance_fetch_results_total
      #       match_type: strict
      #       action: update
      #       new_name: web_account_balance_fetch_results
    exporters:
      # debug:
      #   verbosity: detailed
      otlphttp/grafana:
        endpoint: "https://otlp-gateway-dev-us-central-0.grafana.net:443/otlp"
        headers:
          authorization: "Basic ${DEV_OTEL_GRAFANA_CLOUD_API_KEY}"
          instance-id: "xxxxx"
      debug:
        verbosity: detailed
    service:
      pipelines:
        metrics/dev:
          receivers:
            - prometheus
          processors:
            # - metricstransform
            - attributes
            - k8sattributes
          exporters:
            # - debug
            - otlphttp/grafana
```

### Log output

```shell
No change to the metric name
```
