### ISSUE TITLE
Inserting wrong `trace_id` in logs because of datadog exporter

### ISSUE THREAD

**Issue by seanyu4296** [open-telemetry/opentelemetry-collector-contrib#3758]
**Describe the bug**

### Inserting wrong `trace_id` for Datadog exporter
Hi I am inserting `trace_id` and `span_id` in my service's logs through https://github.com/open-telemetry/opentelemetry-js-contrib/pull/432/files, but i am getting a different `trace_id` (e.g. `88fbc3df6201cf40ca3de6411f0f456e` instead of `14573057136609150318`

I digged into it and I think it is because of this 
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f1e8331be111a4a8bf65670dfaff359714edef85/exporter/datadogexporter/translate_traces.go#L457-L465

Is it possible that otel-collector does not need to convert the ids for `trace_id` and `span_id` and just accept a hex string?

What would be an acceptable workaround do i do the same conversion in my service code?

cc : @ericmustin 

### Setup
- opentelemetry-collector-ontrib 0.28.0
- @opentelemetry/node 0.21.0

otel-agent-config.yaml
```yaml
receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  datadog/api:
    api:
      key: ****

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/api]

```

## What are possible workarounds?

1. I am thinking of using `id.js` in `dd-trace` https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/id.js

2. Do the same logic  here https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f1e8331be111a4a8bf65670dfaff359714edef85/exporter/datadogexporter/translate_traces.go#L457-L465 but in the app code? `chop to 16 characters -> convert hex to int`
