### ISSUE TITLE
Different Behavior with different opentelemetry collector images when using prometheusremotewrite exporter

### ISSUE THREAD

**Issue by jpadmin** [open-telemetry/opentelemetry-collector-contrib#37600]
### Component(s)

exporter/prometheusremotewrite

## Description
I have been using opentelemetry collector in a kubernetes cluster with the help of the open telemetry operator but it fails to spawn the pods stating that prometheusremotewrite is an unknown type.

## Steps to Reproduce
1. Install Opentelemetry operator using the documentation as provided in [the documentation](https://opentelemetry.io/docs/kubernetes/helm/operator/)
2. Try to set up a collector using the following manifest after setting a valid prometheus push url.
```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector
  namespace: default
spec:
  mode: daemonset
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch: {}

    exporters:
      prometheusremotewrite:
        endpoint: "<PROMETHEUS OR MIMIR PUSH URL>"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
```
3. Observe the error in the pod logs.
> error decoding 'exporters': unknown type: "prometheusremotewrite" for id: "prometheusremotewrite" (valid values: [otlphttp file loadbalancing otelarrow debug nop otlp])
> 2025/01/30 18:45:21 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

## Additional Information
The system fails when we use the docker image : **_otel/opentelemetry-collector-k8s:0.117.0_ or _otel/opentelemetry-collector-k8s:0.118.0_** 
At the same time, it succeeds when we change the image repository to **_otel/opentelemetry-collector-contrib:0.117.0_ or _otel/opentelemetry-collector-contrib:0.118.0_**

Is this an issue with the image not in sync, or is this setting invalid for **_otel/opentelemetry-collector-k8s_** images?
 
## Expected Result
The collector pods would come up

## Actual Result
The collector pods failed with the above errors

### Collector version

0.117.0, 0.118.0

## Environment
OS: Mac OS 15.1 (24B83) using K8s, Debian latest, I think this option does not apply to me because I am directly referring the images from opentelemetry docker registry
Compiler(if manually compiled): NA

### OpenTelemetry Collector configuration

```yaml
collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      prometheusremotewrite:
        endpoint: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push
        tls:
          insecure: true
    processors:
      batch: {}
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        metrics:
          exporters:
            - prometheusremotewrite
          processors:
            - batch
          receivers:
            - otlp
```

### Log output

```shell
error decoding 'exporters': unknown type: "prometheusremotewrite" for id: "prometheusremotewrite" (valid values: [otlphttp file loadbalancing otelarrow debug nop otlp])
2025/01/30 18:45:21 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
```
