### ISSUE TITLE
New component: Add a headers_transform extension with support for authenticator

### ISSUE THREAD

**Issue by constanca-m** [open-telemetry/opentelemetry-collector-contrib#37616]
### The purpose and use-cases of the new component

**Use case**: I am using `awsfirehosereceiver`. The receiver sets my API key in the header `X-Amz-Firehose-Access-Key`. However, my receiver is using an authenticator extension that expects the header `authorization` with the scheme `ApiKey`:

```yaml
 extensions:
  bearertokenauth/withscheme:
    scheme: "ApiKey"
    token: "randomtoken"
```

Since the header is not present, even though there is one with the API key, the requests will keep failing.

**Purpose**: The new extension should get:

- The name of an authenticator extension
- A list of OTTL statements to set the values of the headers

It will then execute each statement, before calling `Authenticate` of the authenticator extension given.

### Example configuration for the component

Example configuration:

```yaml
extensions:
  bearertokenauth/withscheme:
    scheme: "ApiKey"
    token: "randomtoken"

  headers_transform:
    server: # this is meant for receiver
      next_auth: bearertokenauth/withscheme
      statements:
        - set(headers["Authorization"], Format("ApiKey %s", [headers["X-Amz-Firehose-Access-Key"]]))
    # client: # this is meant for exporters
```

### Telemetry data types supported

-

### Code Owner(s)

@constanca-m, @axw
