### ISSUE TITLE
New component: `httpclientreceiver`

### ISSUE THREAD

**Issue by verejoel** [open-telemetry/opentelemetry-collector-contrib#37622]
### The purpose and use-cases of the new component

This would pretty much do the same thing as [Vector's HTTP Client source](https://vector.dev/docs/reference/configuration/sources/http_client/).

For us an immediate use-case would be scraping Alertmanager API and emitting these data as logs on some regular interval.

### Example configuration for the component

```yaml
httpclient:
  endpoint: http://example.com
  method: GET
  headers:
    Content-Type: application/json
  interval: 1m
  decoder: json
```

### Telemetry data types supported

Data would be emitted as logs, I don't really see a way metrics or traces could be supported.

### Code Owner(s)

@verejoel

### Sponsor (optional)

@atoulme 

### Additional context

We're trying to implement the pipeline detailed in https://blog.cloudflare.com/alerts-observability/ with OTel instead of Vector.
