### ISSUE TITLE
OTLP exporter emits empty messages when using redis storage for persistent queue

### ISSUE THREAD

**Issue by dentonk** [open-telemetry/opentelemetry-collector-contrib#37636]
### Component(s)

extension/storage/redisstorage

## Description
Empty otlp messages are emitted when the otlp exporter is configured with the sending queue enabled and the redis storage extension used for persistence. The same pipeline works as expected with the file storage extension. Monitoring the redis database shows that the indexes and messages are being set and retrieved from redis and the values look correct. There are no errors being reported in the collector logs. Performing a packet capture of the redis requests also shows what looks to be the expected sets, gets and responses. The body of the POST from the exporter is completely empty.

## Steps to Reproduce

- configure an otel collector with an otlp receiver, otlp exporter pipeline
- enable the sending queue on the exporter with file storage enabled to start to verify the pipeline
- send sample telemetry to the collector and monitor the output of the otlp exporter
  - in my case I used another collector to receive the data as well as wireshark to view the actual otlphttp request directly
- spin up a redis database if one does not already exist
  - in my case I used docker and the redis-stack which includes redis insight to easily monitor the database
- add the redis storage extension to the collector config and reconfigure the exporter to use redis for storage
- send sample telemetry to the collector and monitor the output of the otlp exporter
  - the messages being emitted are empty
- disable the downstream otlp collection so that messages will remain in the queue
- send sample telemetry to the collector and view the keys in the redis database
  - redis insight supports decoding the value of the key as protobuf, so you can easily read the message and see it is still intact
- re-enable the downstream otlp collection and view the keys in the redis database 
  - note the queue is cleared and the indexes are updated, indicating thing seem to be working however, the messages will still be empty

## Expected Result

The messages emitted when using the redis storage extension should be intact and no different than those emitted when the file storage extension is used for the exporter persistent queue.

## Actual Result

The messages are empty.

### Collector version

Collector Contrib v0.118.0

## Environment
mac OS 14.6.1, M3
Docker Desktop 4.36.0 
Redis 7.4.2 from https://hub.docker.com/r/redis/redis-stack
(sha256:5b9c55e53a8b74decc26010abc6baaea632e678a07ee5fcb6ff798465ebb00b1)

docker-compase.yml:
```
version: "2"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./storage:/storage
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP gRPC receiver
```

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp/telemgen:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
exporters:
  otlphttp:
    endpoint: http://host.docker.internal:4418
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000
      storage: redis_storage
    timeout: 5s
extensions:
  file_storage:
    directory: /storage
  redis_storage:
    db: 0
    endpoint: host.docker.internal:6379
    expiration: 5m
    password: ""
service:
  extensions:
    - file_storage
    - redis_storage
  pipelines:
    logs:
      receivers:
        - otlp/telemgen
      processors:
      exporters:
        - otlphttp
  telemetry:
    logs:
      level: debug
```

### Log output

```shell
Output from Wireshark Follow HTTP Stream:

POST /v1/logs HTTP/1.1
Host: host.docker.internal:4318
User-Agent: OpenTelemetry Collector Contrib/0.118.0 (linux/arm64)
Content-Length: 23
Content-Encoding: gzip
Content-Type: application/x-protobuf
Accept-Encoding: gzip


HTTP/1.1 200 OK
Content-Type: application/x-protobuf
Date: Sun, 02 Feb 2025 16:29:28 GMT
Content-Length: 2


.
```

### Additional context

<img width="1642" alt="Image" src="https://github.com/user-attachments/assets/722255bb-216d-4274-a4ef-132c7901e6d2" />

<img width="1344" alt="Image" src="https://github.com/user-attachments/assets/bb884941-1ba9-4002-9dc3-4481415ab04b" />
