### ISSUE TITLE
[pkg/ottl] Improve slice and maps dynamic indexing validation

### ISSUE THREAD

**Issue by edmocosta** [open-telemetry/opentelemetry-collector-contrib#37646]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

We've recently introduced support for indexing maps and slices with dynamic values (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36644), allowing statements to access elements using `Int`, `String`, `Converter`, and `Path`, which was a great addition to OTTL.

Given slices and maps are indexed using different data types (slices w/ integers, and maps w/ strings), we should improve the OTTL contexts/parser to validate the path's key's types and avoid raising errors at runtime:

```
ERROR	failed processing logs	{"error": "failed to execute statement: set(attributes[\"test\"], attributes[\"array.attribute\"][cache[\"index\"]]), unable to resolve an integer index in slice: could not resolve key for map/slice, expecting 'int64' but got 'string'"}
```

### Describe the solution you'd like

When users configure statements using invalid key types, for example, slices with string keys, or maps with integer keys, we should raise an error at the collector startup:

```yaml
log_statements:
 - context: log
   statements:
    - set(cache["index"], "foo")
    - set(attributes["test"], attributes["array.attribute"][cache["index"]]) # slices indexes must be an integer, not string
```

**Comment by bacherfl** [comment]
I'd like to look into implementing this if this gets accepted

**Comment by bacherfl** [comment]
@edmocosta can this actually be done during the collector startup? In most cases I think we will not know what will be the type of the values we are going to index during the statement execution. So in the example from the issue description, we will only know the type of `attributes["array.attribute"]` once we execute the statement for a given log context.

**Comment by edmocosta** [comment]
I'm sorry, that was a bad example! I'll update it.
You're correct, we don't know the dynamic attributes values at startup, what I meant was validating it for the paths we already know the types, such as `attributes`, `cache`, etc.

**Comment by bacherfl** [comment]
Thank you for the clarification, @edmocosta! I will look into how this could be achieved. Another limitation however may be that we can only do this for statements that consist of known paths, like `attributes`, and literals, as something like the following might also not be possible until we have a context object:

```
log_statements:
 - context: log
   statements:
    - set(cache["key"], attributes["foo"]) # type of attributes["foo"] is not known at startup
    - set(attributes["test"], attributes[cache["key"]]) # maps indexes must be a string, not int
```
