### ISSUE TITLE
New component: biztalkserverreceiver

### ISSUE THREAD

**Issue by syron** [open-telemetry/opentelemetry-collector-contrib#37649]
### The purpose and use-cases of the new component

The purpose is to be able to create metrics and thereby monitor Microsoft BizTalk Server (A platform for system integrations) by calling its web APIs (https://learn.microsoft.com/en-us/rest/api/overview/biztalk/?view=rest-biztalk-2020). Those API's can be used to fetch the state of the deployed system integrations.

Important to note is that this is only applicable for biztalk versions BizTalk Server 2016 Feature Pack 1 and later.

#### Example - Empty Auth
```yaml
biztalkserver:
  endpoint: https://biztalkserver/
  interval: 1m  
```

#### Example - Basic Auth
```yaml
biztalkserver:
  endpoint: https://biztalkserver/
  interval: 1m  
  auth: basic
  username: myuser
  password: abc
```

#### Example - NTLM Auth
```yaml
biztalkserver:
  endpoint: https://biztalkserver/
  interval: 1m  
  auth: ntlm
  username:  myuser
  password: abc
```

### Telemetry data types supported

Metrics mainly, since this would be used to fetch the state of different entity-types, such as Send Ports, Receive Locations, Orchestrations and so on.

### Code Owner(s)

@lukasstolt , @riha , @syron
