### ISSUE TITLE
hostmetricsreceiver failed to read usage

### ISSUE THREAD

**Issue by stelucz** [open-telemetry/opentelemetry-collector-contrib#37663]
### Component(s)

receiver/hostmetrics

## Description
Collector's hostmetric receiver fails to scrape metrics:
```
2025-01-31T09:53:51.834Z    error    scraperhelper@v0.118.0/obs_metrics.go:61    Error scraping metrics    {"kind": "receiver", "name": "hostmetrics", "data_type": "metrics", "error": "failed to read usage at /hostfs/boot/efi: permission denied; failed to read usage at /hostfs/var/lib/containers/storage/overlay: permission denied"}
go.opentelemetry.io/collector/scraper/scraperhelper.wrapObsMetrics.func1
    go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/obs_metrics.go:61
go.opentelemetry.io/collector/scraper.ScrapeMetricsFunc.ScrapeMetrics
    go.opentelemetry.io/collector/scraper@v0.118.0/metrics.go:24
go.opentelemetry.io/collector/scraper/scraperhelper.scrapeMetrics
    go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/controller.go:225
go.opentelemetry.io/collector/scraper/scraperhelper.NewMetricsController.func1
    go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/controller.go:216
go.opentelemetry.io/collector/scraper/scraperhelper.(*controller[...]).startScraping.func1
    go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/controller.go:177
```

```
scrape_samples_post_metric_relabeling{} 26
        {"kind": "exporter", "data_type": "metrics", "name": "debug"}
2025-01-31T12:13:10.619Z        error   scraperhelper@v0.118.0/obs_metrics.go:61        Error scraping metrics  {"kind": "receiver", "name": "hostmetrics", "data_type": "metrics", "error": "failed to read usage at /hostfs/boot/efi: permission denied; failed to read usage at /hostfs/var/lib/containers/storage/overlay: permission denied"}
go.opentelemetry.io/collector/scraper/scraperhelper.wrapObsMetrics.func1
        go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/obs_metrics.go:61
go.opentelemetry.io/collector/scraper.ScrapeMetricsFunc.ScrapeMetrics
        go.opentelemetry.io/collector/scraper@v0.118.0/metrics.go:24
go.opentelemetry.io/collector/scraper/scraperhelper.scrapeMetrics
        go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/controller.go:225
go.opentelemetry.io/collector/scraper/scraperhelper.NewMetricsController.func1
        go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/controller.go:216
go.opentelemetry.io/collector/scraper/scraperhelper.(*controller[...]).startScraping.func1
        go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/controller.go:177
2025-01-31T12:13:10.620Z        info    Metrics {"kind": "exporter", "data_type": "metrics", "name": "debug", "resource metrics": 6, "metrics": 19, "data points": 410}
2025-01-31T12:13:10.620Z        info    system.network.connections{protocol=tcp,state=ESTABLISHED} 46
```

## Steps to Reproduce
Install collector through helm with following values:
```
mode: daemonset
nameOverride: "nodeplane"
image:
  repository: "docker.io/otel/opentelemetry-collector-k8s"

hostNetwork: true
presets:
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  logsCollection:
    enabled: false
    includeCollectorLogs: true
  hostMetrics:
    enabled: true

config:
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${env:MY_POD_IP}:8888
    prometheus/node:
      config:
        scrape_configs:
        - job_name: 'node'
          scrape_interval: 10s
          static_configs:
          - targets: ['localhost:9100']
  service:
    extensions:
    - health_check
    pipelines:
      metrics:
        receivers: [prometheus, prometheus/node]
        processors: []
        exporters: [debug]
```

`host_path` is properly created and mounted in daemonset. Both paths `/hostfs/boot/efi`, `/hostfs/var/lib/containers/storage/overlay` are accessible and readable from pod, I verified that by sidecar container to deployed daemonset.

```
control-plane-c27y7:~# ls -la /hostfs/boot/efi
total 5
drwx------    3 root     root           512 Jan  1  1970 .
drwx------    4 root     root          4096 Dec 20 09:19 ..
drwx------    4 root     root           512 Sep 13 11:34 EFI
control-plane-c27y7:~# cat /hostfs/boot/efi/EFI/ubuntu/grub.cfg
search.fs_uuid 0779efe3-af2b-48bc-9534-987d7a83795d root
set prefix=($root)'/boot/grub'
configfile $prefix/grub.cfg
control-plane-c27y7:~# ls -la /hostfs/var/lib/containers/storage/overlay
total 788
drwx------  188 root     root         24576 Feb  3 16:42 .
drwx------    6 root     root          4096 Dec 20 09:17 ..
-rw-------    1 root     root             5 Dec 20 09:17 .has-mount-program
drwx------    5 root     root          4096 Dec 20 10:00 011b7beae0bd1c8b3e92c29681570acc2bb33ad01f6dbd2d9ea4f9a9de9ed42d
drwx------    5 root     root          4096 Feb  3 12:05 03516aa377dc4c33c1384d4ddb64e1ae751f0310d3ee233e4a9c8517bfccf5ee
drwx------    6 root     root          4096 Jan 21 13:16 03af251906410714c5aef9fa705b63f6bbc39c4a5e787de7361eeb18886c2ed2
```
I have tried to set up whole hostmetrics receiver manually instead of using preset option, but it behaves the same.

## Expected Result
No error in scrape.

## Actual Result
Errors when scraping.

### Collector version

0.118.0

## Environment
Azure VM
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
Kubernetes Server Version: v1.29.5

### OpenTelemetry Collector configuration

```yaml
receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${env:MY_POD_IP}:8888
    prometheus/node:
      config:
        scrape_configs:
        - job_name: 'node'
          scrape_interval: 10s
          static_configs:
          - targets: ['localhost:9100']
  service:
    extensions:
    - health_check
    pipelines:
      metrics:
        receivers: [prometheus, prometheus/node]
        processors: []
        exporters: [debug]
```

### Log output

```shell
scrape_samples_post_metric_relabeling{} 26
        {"kind": "exporter", "data_type": "metrics", "name": "debug"}
2025-01-31T12:13:10.619Z        error   scraperhelper@v0.118.0/obs_metrics.go:61        Error scraping metrics  {"kind": "receiver", "name": "hostmetrics", "data_type": "metrics", "error": "failed to read usage at /hostfs/boot/efi: permission denied; failed to read usage at /hostfs/var/lib/containers/storage/overlay: permission denied"}
go.opentelemetry.io/collector/scraper/scraperhelper.wrapObsMetrics.func1
        go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/obs_metrics.go:61
go.opentelemetry.io/collector/scraper.ScrapeMetricsFunc.ScrapeMetrics
        go.opentelemetry.io/collector/scraper@v0.118.0/metrics.go:24
go.opentelemetry.io/collector/scraper/scraperhelper.scrapeMetrics
        go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/controller.go:225
go.opentelemetry.io/collector/scraper/scraperhelper.NewMetricsController.func1
        go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/controller.go:216
go.opentelemetry.io/collector/scraper/scraperhelper.(*controller[...]).startScraping.func1
        go.opentelemetry.io/collector/scraper/scraperhelper@v0.118.0/controller.go:177
2025-01-31T12:13:10.620Z        info    Metrics {"kind": "exporter", "data_type": "metrics", "name": "debug", "resource metrics": 6, "metrics": 19, "data points": 410}
2025-01-31T12:13:10.620Z        info    system.network.connections{protocol=tcp,state=ESTABLISHED} 46
```
