### ISSUE TITLE
New component: kafkatopicsobserver

### ISSUE THREAD

**Issue by wojtekzyla** [open-telemetry/opentelemetry-collector-contrib#37665]
### The purpose and use-cases of the new component

The Kafka topics observer extension is a Receiver Creator-compatible "watch observer" that will detect and report
kafka topics in kafka cluster based on regex template. This observer watches available topics and matches them with the
provided regex. If any change in available topics matching the regex is detected, the observer updates the endpoints list.

### Example configuration for the component
```
kafkatopics_observer:
  protocol_version: 3.7.0
  brokers: ["1.2.3.4:9092", "2.3.4.5:9092"]
  topic_regex: "^test[0-9]$"
  topics_sync_interval: 5s
  resolve_canonical_bootstrap_servers_only: false
  session_timeout: 30s
  heartbeat_interval: 20s
  auth:
    plain_text:
      username: fooUser
      password: fooPassword
```
### Telemetry data types supported

logs, metrics, traces

### Code Owner(s)

@MovieStoreGuy

### Sponsor (optional)

@MovieStoreGuy
