### ISSUE TITLE
[processor/transform] Add ability to add element in array

### ISSUE THREAD

**Issue by adelbot** [open-telemetry/opentelemetry-collector-contrib#37672]
### Is your feature request related to a problem? Please describe.

I use an attributes that it is an array.
The collector receive this attributes and i must add a new element into.

The transform with "set" update this attributes.
The insert seem not exist

### Describe the solution you'd like

Before 

scope = ["aaa"]

transform/scope:
    error_mode: ignore
    trace_statements:
      - context: resource
        statements:
          - insert(attributes["scope"], ["xxx"] ) 

After

scope = [ "aaa","xxx"]

**Comment by edmocosta** [comment]
Hi @adelbot! I think the [append](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#append) function would work for your use case:

```yaml
log_statements:
 - context: resource
   statements:
    - append(attributes["scope"], "xxx") # single value
    - append(attributes["tags"], values = ["aaaa", "bbb"]) # multiple values
```
