### ISSUE TITLE
[exporter/clickhouse] Database creation fail with dash in database name

### ISSUE THREAD

**Issue by vlaborie** [open-telemetry/opentelemetry-collector-contrib#37690]
### Component(s)

exporter/clickhouse

## Description

The Clickhouse exporter do not support database creation when a dash is present in the database name.

## Steps to Reproduce

Use a database name with a dash in it.

## Expected Result

Database is successfully created by clickhouse exporter.

## Actual Result

Collector crash because there is a syntax error on database creation SQL request.

### Collector version

0.119.0

## Environment
Docker: otel/opentelemetry-collector-contrib:0.119.0

### OpenTelemetry Collector configuration

```yaml
exporters:
  clickhouse:
    endpoint: tcp://clickhouse.clickhouse.svc.cluster.local:9440?secure=true&skip_verify=true&dial_timeout=10s
    compress: lz4
    database: "otel-tenant1"
    cluster_name: default
    table_engine:
      name: ReplicatedMergeTree
    username: otel-collector-exporter
    password: exporter
    ttl: 360h
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
```

### Log output

```shell
2025-02-04T19:36:13.499Z	error	graph/graph.go:426	Failed to start component	{"error": "create database: code: 62, message: Syntax error: failed at position 35 ('-'): -tenant1 ON CLUSTER default. Expected one of: UUID, ON, storage definition, ENGINE, PARTITION BY, PRIMARY KEY, ORDER BY, SAMPLE BY, TTL, COMMENT, table overrides declaration list, table override declaration, TABLE OVERRIDE, INTO OUTFILE, FORMAT, SETTINGS, end of query", "type": "Exporter", "id": "clickhouse/tenant1"}
```

### Additional context

I have an incoming PR for this.
