### ISSUE TITLE
[exporter/awsxray] Exporter not handling span links correctly

### ISSUE THREAD

**Issue by arun-annamalai** [open-telemetry/opentelemetry-collector-contrib#37724]
### Component(s)

exporter/awsxray

## Description
I have an ECS application that is instrumented with span links and a collector running as a sidecar to the application. When I export to the xray otlp endpoint using an otlpttp exporter (https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-OTLPEndpoint.html) span links are correctly handled. When I export to the xray native API using the awsxrayexporter, then the span links are not showing up. 

## Steps to Reproduce
Use any application with a span link. 

## Expected Result
The spans should be linked even if I use the awsxrayexporter. 

## Actual Result
The spans are only linked if I use the otlphttp exporter. 

### Collector version

collector contrib v0.115.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

ECS Environment, Java SDK 1.42.0, collector contrib v0.115.0

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318
  otlp/internal:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4319

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 1s

exporters:
  awsxray:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [awsxray]
  telemetry:
    logs:
      level: DEBUG
      sampling:
        tick: 5s
        initial: 50
    metrics:
      readers:
        - periodic:
            interval: 60000
            exporter:
              otlp:
                protocol: grpc/protobuf
                endpoint: http://localhost:4319
```

### Log output

```shell

```
