### ISSUE TITLE
[cloudflarereceiver] Allow receiving all log attributes without manually specifying fields

### ISSUE THREAD

**Issue by petern48** [open-telemetry/opentelemetry-collector-contrib#37720]
### Component(s)

receiver/cloudflare

### Is your feature request related to a problem? Please describe.

Currently, if we want to receive attributes from [cloudflare logpush](https://developers.cloudflare.com/logs/about/). We need to specify the attributes manually in the config file. Cloudflare logpush already gives us the option to [specify which attributes are sent](https://developers.cloudflare.com/logs/reference/log-output-options/#output-types). Therefore, it's often unnecessary to manually specify (again) which attributes to receive because we simply want to ingest everything that is sent.

```yaml
receivers:
  cloudflare:
    logs:
      tls:
        key_file: some_key_file
        cert_file: some_cert_file
      endpoint: 0.0.0.0:12345
      secret: 1234567890abcdef1234567890abcdef
      timestamp_field: EdgeStartTimestamp
      attributes:
        ClientIP: http_request.client_ip
        ClientRequestURI: http_request.uri
```
^ [src](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/81e69e408400e8c3b95c9295d0efe22eeb6dcfc8/receiver/cloudflarereceiver/README.md#example)

### Describe the solution you'd like

I'm proposing a new convention where if the attributes field is empty, then it indicates we want to ingest everything that is sent. This helps users avoid having to modify which fields they want in two places. Happy to submit a PR myself.

```yaml
receivers:
  cloudflare:
    logs:
      tls:
        key_file: some_key_file
        cert_file: some_cert_file
      endpoint: 0.0.0.0:12345
      secret: 1234567890abcdef1234567890abcdef
      timestamp_field: EdgeStartTimestamp
      attributes:
          # empty. no attributes specified -> receive all attributes that are sent
```
