### ISSUE TITLE
Add ability to mute all errors (mainly due to access rights) coming from hostmetricsreceiver

### ISSUE THREAD

**Issue by sarkisjad** [open-telemetry/opentelemetry-collector-contrib#37747]
### Component(s)

receiver/hostmetrics

### Is your feature request related to a problem? Please describe.

I am looking to mute some errors coming from the `filesystem` scraper in the `hostmetricsreceiver`. 

### Describe the solution you'd like

I am encountering an issue in the `hostmetricsreceiver`, primarily due to access rights restrictions for certain certain directories. This is resulting in a large number of verbose error logs.

```
2024-12-18T15:52:29.501+0100    error   scraperhelper/scrapercontroller.go:205  Error scraping metrics  {"kind": "receiver", "name": "hostmetrics", "data_type": "metrics", "error": "failed to read usage at /path/to/an/unauthorized/file: no such file or directory; failed to read usage at /path/to/another/unauthorized/file: no such file or directory; failed to read usage at /path/to/one/more/unauthorized/file: no such file or directory", "scraper": "hostmetrics"}
```

When NFS tries to access these files, they are unavailable because of access rights. 

I believe this is coming from the `filesystem` scraper.
I want to find a way to silence these errors.
Could we add an additional setting [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/66082aebf2576321950c06d203cda04a27576c42/receiver/hostmetricsreceiver#file-system) maybe? 

### Additional context

This is my receiver config:
```
receivers:
  hostmetrics: # pull
    collection_interval: ${env:HOST_METRICS_COLLECTION_INTERVAL}s
    scrapers:
      cpu:
        metrics:
          system.cpu.time:
            enabled: false
          system.cpu.logical.count:
            enabled: true
      disk:
        metrics:
          system.disk.io_time:
            enabled: false
          system.disk.merged:
            enabled: false
          system.disk.operations:
            enabled: false
          system.disk.operation_time:
            enabled: false
          system.disk.pending_operations:
            enabled: false
          system.disk.weighted_io_time:
            enabled: false
      filesystem:
        include_virtual_filesystems: true
        metrics:
          system.filesystem.inodes.usage:
            enabled: false
          system.filesystem.utilization:
            enabled: true
      load:
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      network:
        metrics:
          system.network.dropped:
            enabled: false
          system.network.packets:
            enabled: false
      processes:
        metrics:
          system.processes.created:
            enabled: false

```
