### ISSUE TITLE
googlecloudmonitoringreceiver doesn't get attributes for the metrics

### ISSUE THREAD

**Issue by HazemAbdelmagid** [open-telemetry/opentelemetry-collector-contrib#37742]
### Component(s)

receiver/googlecloudmonitoring

## Description
I have been trying to use googlecloudmonitoring receiver to collect metrics related to memorystore and then forward them to prometheus but when I try to query the metrics I can't find any attributes in the metrics which doesn't allow us to filter the metrics if we have multiple instances running in memorystore, example:

`openetelemetry_operator_system_redis_googleapis_com_server_uptime{instance="collector.opentelemetry-operator-system.svc:9090", job="scrapeconfig/prometheus-system/otel-scrape-config"}`

```
## Steps to Reproduce
googlecloudmonitoring:
        collection_interval: 5m
        project_id: {{ projectName }}
        metrics_list:
        - metric_name: "redis.googleapis.com/stats/cpu_utilization"
```
## Expected Result
googlecloudmonitoring receiver should be able to collect the listed metrics and provide attributes for each metric to allow filteration.

## Actual Result
`openetelemetry_operator_system_redis_googleapis_com_server_uptime{instance="collector.opentelemetry-operator-system.svc:9090", job="scrapeconfig/prometheus-system/otel-scrape-config"}`

### Collector version

0.118.0

## Environment
GKE Cluster

### OpenTelemetry Collector configuration

```yaml
config:
    exporters:
      debug:
        verbosity: detailed
      googlecloudpubsub:
        project: <redacted>
        topic: projects/<redacted>/topics/metrics-pubsub
    processors:
      batch:
        timeout: 5s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 10
    receivers:
      googlecloudmonitoring:
        collection_interval: 5m
        project_id: <redacted>
        metrics_list:
        - metric_name: "redis.googleapis.com/instance/stats/cpu_utilization"
    service:
      pipelines:
        metrics:
          exporters:
          - googlecloudpubsub
          - debug
          processors:
          - batch
          - memory_limiter
          receivers:
          - googlecloudmonitoring
```

### Log output

```shell
No logs as there is no errors but only the metric with missing attributes.

`openetelemetry_operator_system_redis_googleapis_com_server_uptime{instance="collector.opentelemetry-operator-system.svc:9090", job="scrapeconfig/prometheus-system/otel-scrape-config"}`
```
