### ISSUE TITLE
Redaction processor doesn't inspect scope attributes

### ISSUE THREAD

**Issue by patdimond** [open-telemetry/opentelemetry-collector-contrib#37799]
### Component(s)

processor/redaction

## Description

I was looking at the redaction processor to understand how it works and noticed that it doesn't look at attributes attached to the scope. See this section here -> https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/redactionprocessor/processor.go#L88-L90

I believe the attributes from the scope should be retrieved using `ils.Scope().Attributes()` and be passed into `s.processAttrs`.

Currently any attributes attached to the instrumentation scope aren't processed for redaction.

## Steps to Reproduce

Ran a collector locally with redaction version `v0.113.0`
and config
```
  redaction:
    allow_all_keys: true
    blocked_values:
      - "test123"
```
Patched telemetrygen to name the scope test123
```
diff --git a/cmd/telemetrygen/pkg/traces/worker.go b/cmd/telemetrygen/pkg/traces/worker.go
index c3cc86d747..ebd2ca9c50 100644
--- a/cmd/telemetrygen/pkg/traces/worker.go
+++ b/cmd/telemetrygen/pkg/traces/worker.go
@@ -42,7 +42,7 @@ const (
 )
 
 func (w worker) simulateTraces(telemetryAttributes []attribute.KeyValue) {
-       tracer := otel.Tracer("telemetrygen")
+       tracer := otel.Tracer("test123")
        limiter := rate.NewLimiter(w.limitPerSecond, 1)
        var i int
 ```
and ran telemetrygen with the following
```
./telemetrygen traces \  
    --otlp-endpoint="127.0.0.1:1337" \
    --traces=1 \
    --otlp-attributes 'service.name="testcase"' \
    --otlp-attributes 'service.version="test123"' \
    --telemetry-attributes 'rpc.method="test123"' \
    --otlp-insecure
 ```

## Expected Result
All instances of test123 would be redacted

## Actual Result

Only `rpc.method` and `service.version` are redacted. `otel.scope.name` is present as test123.

### Collector version

Built locally - I think v0.113.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:1337
processors:
  batch:
  redaction:
    allow_all_keys: true
    blocked_values:
      - "test123"

exporters:
  otlp:
    endpoint: 127.0.0.1:4317
    tls:
      insecure: true
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, redaction]

      exporters: [otlp]
  telemetry:
    logs:
      level: DEBUG
      development: true
```

### Log output

```shell

```

**Comment by mx-psi** [comment]
I am in favor of having a mechanism to redact these

**Comment by TylerHelmuth** [comment]
Agreed

**Comment by andsel** [comment]
I've tried to reproduce with the following modified collector config, removed the `otlp` exporter, and switched `exporters.debig.verbosity` to `detailed`:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:1337
processors:
  batch:
  redaction:
    allow_all_keys: true
    blocked_values:
      - "test123"

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, redaction]
      exporters: [debug]
  telemetry:
    logs:
      level: DEBUG
      development: true
```

the log I found in collectors is:
```
2025-04-15T09:40:13.960+0200	info	ResourceSpans #0
Resource SchemaURL: https://opentelemetry.io/schemas/1.25.0
Resource attributes:
     -> service.name: Str(testcase)
     -> service.version: Str(****)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope test123
Span #0
    Trace ID       : 1462d5a17498014d16dee856350b67b5
    Parent ID      : aadc28c9afba9449
    ID             : 24594bd331878c71
    Name           : okey-dokey-0
    Kind           : Server
    Start time     : 2025-04-15 07:40:13.931071 +0000 UTC
    End time       : 2025-04-15 07:40:13.931194 +0000 UTC
    Status code    : Unset
    Status message :
Attributes:
     -> net.sock.peer.addr: Str(1.2.3.4)
     -> peer.service: Str(telemetrygen-client)
     -> rpc.method: Str(****)
Span #1
    Trace ID       : 1462d5a17498014d16dee856350b67b5
    Parent ID      :
    ID             : aadc28c9afba9449
    Name           : lets-go
    Kind           : Client
    Start time     : 2025-04-15 07:40:13.931071 +0000 UTC
    End time       : 2025-04-15 07:40:13.931194 +0000 UTC
    Status code    : Unset
    Status message :
Attributes:
     -> net.sock.peer.addr: Str(1.2.3.4)
     -> peer.service: Str(telemetrygen-server)
     -> rpc.method: Str(****)
```

the only`test123` instance is in
```
InstrumentationScope test123
```

printed by https://github.com/open-telemetry/opentelemetry-collector/blob/f0ab7c34ac6270e78cd4ce0b21a91c1f5a8e0e45/exporter/debugexporter/internal/otlptext/traces.go#L31

corresponding to `pcommon.InstrumentationScope.Name()` from `ils.Scope().Name()` and I think it's not part of attrivbutes `ils.Scope().Attributes()`. 

Should it be redacted?
Is there any other Scope().Attributes() that's not printed?
