### ISSUE TITLE
Support for namespace labels as attributes in K8S Processor

### ISSUE THREAD

**Issue by backjo** [open-telemetry/opentelemetry-collector-contrib#378]
**Is your feature request related to a problem? Please describe.**
At Intuit, we run a fleet of multi-tenant K8S clusters, with each K8S namespace having several labels containing important metadata. This metadata would be useful to have as a resource attribute - for analysis, correlation etc. 
**Describe the solution you'd like**
The K8S processor should support extraction of labels and annotations on the Namespace.
 If a span is received and the namespace can be determined, and if configured with extract rules for namespace labels/annotations, the K8S processor should attempt to extract those labels/annotations, similarly to what it does today for Pod labels/annotations.

```yaml
   extract:
      namespace:
        annotations:
          - tag_name: a1 # extracts value of namespace annotation with key `annotation-one` and inserts it as a tag with key `a1`
            key: annotation-one
          - tag_name: a2 # extracts value of namespace annotation with key `annotation-two` with regexp and inserts it as a tag with key `a2`
            key: annotation-two
            regex: field=(?P<value>.+)
        labels:
          - tag_name: l1 # extracts value of namespace label with key `label1` and inserts it as a tag with key `l1`
            key: label1
          - tag_name: l2 # extracts value of namespace label with key `label1` with regexp and inserts it as a tag with key `l2`
            key: label2
            regex: field=(?P<value>.+)
```

If the processor does not have Namespace READ permissions, it should fail gracefully and log an error message about insufficient privileges.
