### ISSUE TITLE
Unable to send metrics to GCP as googlecloudexporter is flagging the metrics due to too many labels

### ISSUE THREAD

**Issue by gaur-piyush** [open-telemetry/opentelemetry-collector-contrib#37869]
### Component(s)

exporter/googlecloud

## Description

We're using Harvest to scrape metrics from our ONTAP devices. We then use Otel to send these metrics to GCP. However, these are being flagged with too many labels. Is there a way to control the number of labels or modify the configuration to adjust them? Currently it is having more than 30+ labels. 

## Steps to Reproduce

If you have access to an ONTAP device, use Harvest to scrape the metrics and then use Otel to send to GCP using googslecloud exporter. 

## Expected Result
It should either allow the metrics or set the limit within the configuration. 

## Actual Result
Metrics are getting dropped. 

### Collector version

0.111.0

### Environment information

```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.8-gke.1128001
```

### OpenTelemetry Collector configuration

```yaml
config:
    exporters:
        debug:
            verbosity: normal
        googlecloud:
            project: PROJ_ID
            metric:
                prefix: custom.googleapis.com
            sending_queue:
                enabled: true
                queue_size: 40000
    extensions:
        health_check: 
            endpoint: "0.0.0.0:13133"
    processors:
        batch:
            send_batch_size: 8192
            send_batch_max_size: 10000
            timeout: 10s
        memory_limiter:
            check_interval: 5s
            limit_percentage: 80
            spike_limit_percentage: 30
        resourcedetection:
            detectors: [gcp]
            timeout: 10s
    receivers:
        prometheus:
            config:
                scrape_configs:
                - job_name: 'ontap-metrics-harvest'
                  scrape_interval: 300s
                  static_configs:
                  - targets: ['harvest-poller-harvest-poller-gcnv-harvest.ontap-monitoring.svc.cluster.local:12990'] 
    service:
        extensions:
            - health_check
        pipelines:
            metrics:
                receivers: [prometheus]
                processors: [resourcedetection]
                exporters: [googlecloud, debug]
```

### Log output

```shell

```
