### ISSUE TITLE
New component: Cloudwatch metric streams encoding extension

### ISSUE THREAD

**Issue by constanca-m** [open-telemetry/opentelemetry-collector-contrib#37870]
### The purpose and use-cases of the new component

Some aws receivers and exporters, like `awsfirehosereceiver`, get data from cloudwatch metric streams. The purpose of this extension is to transform these metrics into otel metrics.

Relates to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37113.

### Example configuration for the component

```  
extensions:
  cloudwatch_metric_streams_encoding:
     # See output format: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-metricstream.html#cfn-cloudwatch-metricstream-outputformat
     # format: opentelemetry1.0 # options [json, opentelemetry1.0], and opentelemetry0.7 not supported.

receivers:
  awsfirehose:
    include_metadata: true
    access_key: "access_key"
    endpoint: :4434
    encoding: cloudwatch_metric_streams_encoding
```

### Telemetry data types supported

- Metrics

### Code Owner(s)

@axw

### Sponsor (optional)

@atoulme
