### ISSUE TITLE
AWS SSM provider for configuration

### ISSUE THREAD

**Issue by Linaa** [open-telemetry/opentelemetry-collector-contrib#37877]
### Describe the issue you're reporting

otel collector running on AWS ( ECS or K8s ) would benefit from directly reading the secrets from SSM, instead of fetching them before start up. This will greatly simplify the implementation. This is similar to the existing aws secretsmanager provider.

example configuration:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  memory_limiter:

exporters:
  otlp/provider1:
    endpoint: https://provider1.domain.com:12345
    headers:
      api-key: ${ssm:<parameter-name>}
    compression: gzip

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/provider1]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/provider1]
```
