### ISSUE TITLE
Problem with receiving traces in OTEL Collector - GH Receiver + GH Action run-with-telemetry

### ISSUE THREAD

**Issue by davide-russo-tfs** [open-telemetry/opentelemetry-collector-contrib#37873]
### Component(s)

Github Receiver

### Describe the issue you're reporting

Hello,

I'm trying to do a simple test by using the run-with-telemetry GH Action with the Github Receiver.
The following services are running on my personal laptop:

- OpenTelemetry Collector v. 0.119.0
- Github Runner

I created a simple GH Action Workflow to deploy a few resources into a Databricks workspace. This is the config file:

```
name: deploy_databricks

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all

concurrency: 1

env: 
  DATABRICKS_TOKEN: ###
  otel-exporter-otlp-endpoint: localhost:4317
  otel-service-name: test_otel_github

jobs:
  deploy_resources:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main  # Download Databricks CLI

      - name: "Deploy resources with monitoring"
        uses: krzko/run-with-telemetry@v0.5.0
        with:
          otel-exporter-otlp-endpoint: ${{ env.otel-exporter-otlp-endpoint }}
          otel-service-name: ${{ env.otel-service-name }}
          step-name: Deploy resources with monitoring
          run: databricks bundle deploy
```
This is instead the config file of the OpenTelemetry collector that I'm using:

```
receivers:
  github:
    scrapers:
      scraper:
    webhook:
      endpoint: localhost:4317
    tls:
      insecure: true

exporters:
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [github]
      exporters: [debug]
```
The workflow executes successfully but I don't receive any trace in output:

![Image](https://github.com/user-attachments/assets/0c3738d3-96f9-4fc6-8b8d-70d8614a7d07)

In addition, I see the following error in the logs of the GH Workflow:

![Image](https://github.com/user-attachments/assets/e1d9abfd-9c8b-408e-a8ad-e71afccc519c)

I followed the documentation of the repos but can't find the mistake I'm committing. I also tried with other ports and by removing the "tls" block.
Any help is super appreciated, thanks
