### ISSUE TITLE
Prometheus exporter: listen tcp: address :::8888: too many colons in address

### ISSUE THREAD

**Issue by oxidand** [open-telemetry/opentelemetry-collector-contrib#37876]
### Component(s)

exporter/prometheus

## Description

After upgrading to `opentelemetry-collector-contrib:0.119.0` the daemonset doesn't start. We don't use Prometheus and it's not specified anywhere in the config.

## Steps to Reproduce

Upgrade from 0.118.0 to 0.119.0.

## Expected Result

Pod status: Running

## Actual Result

Pod status: CrashLoopBackOff

### Collector version

0.119.0

## Environment
AWS EKS, deployed with [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector).

```yaml
mode: daemonset

image:
  repository: "otel/opentelemetry-collector-contrib"
```

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: ${OTEL_ENDPOINT}
    headers:
      dsn-header: ${OTEL_DSN}
extensions:
  health_check:
    endpoint: '[${env:MY_POD_IP}]:13133'
processors:
  batch:
    send_batch_size: 10000
    timeout: 10s
  cumulativetodelta: {}
  k8sattributes:
    extract:
      metadata:
      - k8s.namespace.name
      - k8s.deployment.name
      - k8s.statefulset.name
      - k8s.daemonset.name
      - k8s.cronjob.name
      - k8s.job.name
      - k8s.node.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.pod.start_time
    filter:
      node_from_env_var: K8S_NODE_NAME
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resourcedetection:
    detectors:
    - env
    - system
receivers:
  filelog:
    exclude:
    - /var/log/pods/opentelemetry_daemonset-opentelemetry-collector*_*/opentelemetry-collector/*.log
    include:
    - /var/log/pods/*/*/*.log
    include_file_name: false
    include_file_path: true
    operators:
    - id: container-parser
      max_log_size: 102400
      type: container
    retry_on_failure:
      enabled: true
    start_at: end
  hostmetrics:
    collection_interval: 10s
    root_path: /hostfs
    scrapers:
      cpu: null
      disk: null
      filesystem:
        exclude_fs_types:
          fs_types:
          - autofs
          - binfmt_misc
          - bpf
          - cgroup2
          - configfs
          - debugfs
          - devpts
          - devtmpfs
          - fusectl
          - hugetlbfs
          - iso9660
          - mqueue
          - mqueue
          - nsfs
          - overlay
          - proc
          - procfs
          - pstore
          - rpc_pipefs
          - securityfs
          - selinuxfs
          - squashfs
          - sysfs
          - tracefs
          match_type: strict
        exclude_mount_points:
          match_type: regexp
          mount_points:
          - /dev/*
          - /proc/*
          - /sys/*
          - /run/k3s/containerd/*
          - /var/lib/docker/*
          - /var/lib/kubelet/*
          - /snap/*
      load: null
      memory: null
      network: null
  kubeletstats:
    auth_type: serviceAccount
    collection_interval: 20s
    endpoint: '[${env:K8S_NODE_IP}]:10250'
  otlp:
    protocols:
      grpc:
        endpoint: '[${env:MY_POD_IP}]:4317'
        max_recv_msg_size_mib: 20
service:
  extensions:
  - health_check
  pipelines:
    logs:
      exporters:
      - otlp
      processors:
      - k8sattributes
      - batch
      receivers:
      - otlp
      - filelog
    metrics:
      exporters:
      - otlp
      processors:
      - k8sattributes
      - cumulativetodelta
      - batch
      - resourcedetection
      receivers:
      - hostmetrics
      - kubeletstats
      - otlp
    traces:
      exporters:
      - otlp
      processors:
      - k8sattributes
      - batch
      receivers:
      - otlp
  telemetry:
    metrics:
      address: '[${env:MY_POD_IP}]:8888'
```

### Log output

```shell
Error: failed to create SDK: binding address 6d84:6da1:8daf:fd1b:56a7::25:8888 for Prometheus exporter: listen tcp: address 6d84:6da1:8daf:fd1b:56a7::25:8888: too many colons in address
2025/02/12 11:22:55 collector server run finished with error: failed to create SDK: binding address 6d84:6da1:8daf:fd1b:56a7::25:8888 for Prometheus exporter:
listen tcp: address 6d84:6da1:8daf:fd1b:56a7::25:8888: too many colons in address
```

### Additional context

I have tried explicitly to set the Prometheus exporter to null, tried setting a fake endpoint in IPv6 format, but it still defaults to Pod IPv6 without `[]`

**Comment by ArthurSens** [comment]
Port 8888 is the port where the collector own telemetry is exposed. You're setting an environment variable there:

```yaml
  telemetry:
    metrics:
      address: '[${env:MY_POD_IP}]:8888'
```

Is that the correct way to set your IP?

**Comment by oxidand** [comment]
That was the issue, thanks.

I remember now that this part was added automatically and prevented the pods from starting. Based on the example, we changed the format to IPv6 and it didn't complain until we upgraded to 0.119.0. But the error message was about an exporter and that's what caused the confusion. Thanks for the quick reply.

**Comment by neoeinstein** [comment]
Is the lack of support for IPv6 exporter addresses intentional? We operate in an ecosystem where pods are _only_ given IPv6 addresses, and so if this cannot handle those addresses, that would be a problem for us. Are there any workarounds?

**Comment by ysghandi** [comment]
I am getting the same error after upgarding from `otelcol-contrib_0.116.0_windows_amd64` to `otelcol-contrib_0.123.0_windows_amd64`.
Here's my receiver config:
```
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlphttp:
    endpoint: "http://localhost:3100/otlp"

    timeout: 15s
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:9465
    namespace: "otelcol"

extensions:
  health_check:
  pprof:
  zpages:

service:
  # telemetry:
  #   logs:
  #     level: debug
  extensions: [health_check, pprof, zpages]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
  
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
```
And here the collector:
```
receivers:
  filelog:
    include: D:/Log Example/**/*[^0-9].log
    start_at: end
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (?P<level>\w+)\[(?P<thread>\d+)\] (?P<component>\S+)\s+(?P<message>.*)$'
        timestamp:
          parse_from: attributes.timestamp
          layout: '%Y-%m-%d %H:%M:%S,%L'
        severity:
          parse_from: attributes.level

  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      load:
      network:
      process:
        include:
          names: ["mosquitto"]
          match_type: "regexp"

processors:
  batch:
    timeout: 5s
    send_batch_size: 50
    send_batch_max_size: 100

  memory_limiter:
    check_interval: 5s
    limit_mib: 100

  resourcedetection/system:
    detectors: [system]
    system:
      resource_attributes:
        host.name:
          enabled: true
        host.id:
          enabled: true
        os.description:
          enabled: true
        os.type:
          enabled: true

  resource:
    attributes:
      - action: upsert 
        key: service.name
        value: "Node X"  


exporters:
  otlphttp:
    endpoint: http://localhost:4318
    tls: 
      insecure: true


service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch, memory_limiter, resource, resourcedetection/system]
      exporters: [otlphttp]

    metrics:
      receivers: [hostmetrics]
      processors: [batch,memory_limiter, resourcedetection/system]
      exporters: [otlphttp]
```
How can I resolve this issue?
Thanks.
