### ISSUE TITLE
[cmd/opampsupervisor] Add support for local Collector config file via agent.config_file

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector-contrib#37886]
### Component(s)

cmd/opampsupervisor

### Is your feature request related to a problem? Please describe.

The [spec](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/opampsupervisor/specification) says:
>The Supervisor creates a Collector config file in a temp directory and passes to the Collector via --config command line option. The config file is created by merging the **local config file (optional)** and the remote config received from OpAMP backend (also optional).

The spec also defines how the local config file path is specified in the supervisor config:
```yaml
agent:
  # Path to optional local Collector config file to be merged with the
  # config provided by the OpAMP server.
  config_file: /etc/otelcol/config.yaml
```

This feature is not yet implemented in the Supervisor.

### Describe the solution you'd like

See the spec: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/opampsupervisor/specification
