### ISSUE TITLE
Sending Data to Splunk the Host it not Defined in the exportor

### ISSUE THREAD

**Issue by robertlynch2020** [open-telemetry/opentelemetry-collector-contrib#3789]
**Describe the bug**

We are generating OpenTelemety Data and we are sending it via HEC/ HTTP into Splunk using an exporter 0.26.0.
The data is arriving and we can see "source", "sourcetype" etc... but the "Host" is not defined. Splunk is reading this as unknown when it arrives.

![image](https://user-images.githubusercontent.com/85939450/122048223-eabfcb00-cdd8-11eb-8d4a-7a3873e7670f.png)

I can see everything else that we need, but no host.
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/splunkhecexporter

![image](https://user-images.githubusercontent.com/85939450/122048363-0c20b700-cdd9-11eb-86e8-f1bbf0f18787.png)

So when the data comes into Splunk it comes in as Unknown
![image](https://user-images.githubusercontent.com/85939450/122048477-35d9de00-cdd9-11eb-90b4-cc4271083571.png)

There does not seem a way to set host! 

**Steps to reproduce**
Sent Data into Splunk via HTTP using Opentelemetry exporter

**What did you expect to see?**
Host in the exporter file - 

**What did you see instead?**
Unknown

**What version did you use?**
0.26.0

**What config did you use?**
Config: (e.g. the yaml config file)

**Below is otelcol-gateway-config.yml**
```yaml
receivers:
  otlp: # pushed by clients
    protocols:
      grpc:
        endpoint: :${OTLP_RECEIVER_PORT}

processors:
  batch:
    timeout: 1s

exporters:
  prometheus: # pulled by prometheus
    endpoint: :${PROMETHEUS_EXPORTER_PORT}
  splunk_hec: # pushed to splunk
    token: "a04daf32-68b9-48b2-88a0-6ac53b3ec002"
    endpoint: "https://mx33456vm:8088/services/collector"
    source: "mx"
    sourcetype: "otel"
    index: "metrics_test"
    insecure_skip_verify: true
  splunk_hec/events: # pushed to splunk
    token: "a04daf32-68b9-48b2-88a0-6ac53b3ec002"
    endpoint: "https://mx33456vm:8088/services/collector"
    source: "mx"
    sourcetype: "otel"
    index: "events_test"
    insecure_skip_verify: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus,splunk_hec,splunk_hec/events]
```

**Environment**
OS: LINUX red Hat

**Additional context**
