### ISSUE TITLE
[processor/k8sattributes] Invalid value: []string{""}: values set must be empty for exists and does not exist

### ISSUE THREAD

**Issue by saltbo** [open-telemetry/opentelemetry-collector-contrib#37892]
### Component(s)

k8sattributes

## Description

failed to create "k8sattributes/knative" processor when using the exists op in the filter.labels

```yaml
processors:
  batch: {}
  k8sattributes/knative:
    auth_type: serviceAccount
    extract:
      labels:
      - key: serving.knative.dev/configuration
        tag_name: knative.serving.configuration
    filter:
      labels:
      - key: serving.knative.dev/configuration
        op: exists
```

2025/02/13 09:22:47 collector server run finished with error: cannot build pipelines: failed to create "k8sattributes/knative" processor, in pipeline "traces": values: Invalid value: []string{""}: values set must be empty for exists and does not exist

### Collector version

0.60.0, 0.119.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
processors:
  batch: {}
  k8sattributes/knative:
    auth_type: serviceAccount
    extract:
      labels:
      - key: serving.knative.dev/configuration
        tag_name: knative.serving.configuration
    filter:
      labels:
      - key: serving.knative.dev/configuration
        op: exists
```

### Log output

```shell
Error: cannot build pipelines: failed to create "k8sattributes/knative" processor, in pipeline "traces": values: Invalid value: []string{""}: values set must be empty for exists and does not exist
2025/02/13 09:25:42 collector server run finished with error: cannot build pipelines: failed to create "k8sattributes/knative" processor, in pipeline "traces": values: Invalid value: []string{""}: values set must be empty for exists and does not exist
```
