### ISSUE TITLE
Splunkenterprisereceiver errors when default enabled metrics are present but corresponding endpoint not configured

### ISSUE THREAD

**Issue by shalper2** [open-telemetry/opentelemetry-collector-contrib#37907]
### Component(s)

receiver/splunkenterprise

## Description
During operation of an otherwise well configured collector the Splunkenterprise receiver throws errors for metrics which are enabled by default (i.e. no extra configuration is needed to turn them on). This occurs when the corresponding endpoint is not present in the config. 

## Steps to Reproduce
Run the splunkenterprise receiver without configuring a cluster master endpoint. 

## Expected Result
That the metrics which cant be collected due to a missing or misconfigured endpoint report the error but that overall receiver operation is uninterrupted (i.e. properly configured metric/endpoint pairs work as expected).

## Actual Result
All metrics stop emitting.

### Collector version

0.119

## Environment
This bug is environment agnostic

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
  basicauth/client:
    client_auth:
      username: internal_observability
      password: "foobar"

splunkenterprise:
    collection_interval: 60s
    indexer:
      auth:
        authenticator: basicauth/client
      endpoint: https://localhost:8089
      timeout: 10s
      tls:
        insecure_skip_verify: true
    metrics:
      splunk.indexer.throughput:
        enabled: true
```

### Log output

```shell
Error scraping metrics        {"kind": "receiver", "name": "splunkenterprise/indexer", "data_type": "metrics", "error": "no client corresponding to the endpoint type was found; no client corresponding to the endpoint type was found; no client corresponding to the endpoint type was found; no client corresponding to the endpoint type was found; no client corresponding to the endpoint type was found; no client corresponding to the endpoint type was found; no client corresponding to the endpoint type was found; no client corresponding to the endpoint type was found; no client corresponding to the endpoint type was found; no client corresponding to the endpoint type was found", "errorCauses": [{"error": "no client corresponding to the endpoint type was found"}, {"error": "no client corresponding to the endpoint type was found"}, {"error": "no client corresponding to the endpoint type was found"}, {"error": "no client corresponding to the endpoint type was found"}, {"error": "no client corresponding to the endpoint type was found"}, {"error": "no client corresponding to the endpoint type was found"}, {"error": "no client corresponding to the endpoint type was found"}, {"error": "no client corresponding to the endpoint type was found"}, {"error": "no client corresponding to the endpoint type was found"}, {"error": "no client corresponding to the endpoint type was found"}], "scraper": "splunkenterprise"}
```
