### ISSUE TITLE
resource attributes "from_attribute" not working

### ISSUE THREAD

**Issue by JCoelho008** [open-telemetry/opentelemetry-collector-contrib#37908]
### Component(s)

processor/resource

## Description
I'm sending logs from Promtail to a Otel Collector Loki receiver and then I'm exporting to a Loki instance with a otlphttp exporter. 
My issue is that on Grafana I can't see the labels from Promtail in the label browser, but I can filter by them (e.g.: {service_name="otelcol_service"} | environ=`LIT`). 

I already added the debug exporter and I can see that the service.name is on the Resource attributes but the labels from Promtail are in Attributes.
Resource SchemaURL:
Resource attributes:
     -> service.name: Str(otelcol_service)
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 2025-02-13 17:08:14.292419357 +0000 UTC
Timestamp: 2025-02-13 17:08:14.292419357 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str(test)
Attributes:
     -> app_iot: Str(app)
     -> env: Str(LIT)
     -> filename: Str(/var/logs/test.log)
     -> environ: Str(LIT)
Trace ID:
Span ID:
Flags: 0

## Steps to Reproduce
Promtail config:
clients:
  - url: http://127.0.0.1:3500/loki/api/v1/push
    batchwait: 1s
    batchsize: 1024000 #default

scrape_configs:
- job_name: Promtail-job
  static_configs:
  - targets:
      - localhost
    labels:
      env: "LIT"
      app_iot: app
      __path__: /var/logs/test.log

Otel Collector config:
receivers:
  loki:
    protocols:
      http:
        endpoint: 127.0.0.1:3500

processors:
  attributes/loki:
    actions:
    - action: insert
        key: environ
        from_attribute: env

  resource/loki:
    attributes:
      - key: service.name
        value: otelcol_service
        action: upsert
      - action: update
        key: environ
        from_attribute: env

exporters:
  otlphttp/logs:
    endpoint: https://my-endpoint
  
  debug: 
    verbosity: detailed 
service:
  pipelines:
    logs:
      receivers: [loki]
      processors: [attributes/loki, resource/loki]
      exporters: [debug, otlphttp/logs]

Note: tried with and without the attributes/loki

## Expected Result
I was expecting to see the environ label in the "Resource attributes" and then be able to query like {environ="LIT"}

## Actual Result
environ is only in "Attributes" and I can only  query like {service_name="otelcol_service"} | environ=`LIT`

### Collector version

0.119.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  loki:
    protocols:
      http:
        endpoint: 127.0.0.1:3500

processors:
  attributes/loki:
    actions:
    - action: insert
        key: environ
        from_attribute: env

  resource/loki:
    attributes:
      - key: service.name
        value: otelcol_service
        action: upsert
      - action: update
        key: environ
        from_attribute: env

exporters:
  otlphttp/logs:
    endpoint: https://my-endpoint
  
  debug: 
    verbosity: detailed 
service:
  pipelines:
    logs:
      receivers: [loki]
      processors: [attributes/loki, resource/loki]
      exporters: [debug, otlphttp/logs]
```

### Log output

```shell
Resource SchemaURL:
Resource attributes:
     -> service.name: Str(otelcol_service)
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 2025-02-13 17:08:14.292419357 +0000 UTC
Timestamp: 2025-02-13 17:08:14.292419357 +0000 UTC
SeverityText:
SeverityNumber: Unspecified(0)
Body: Str(test)
Attributes:
     -> app_iot: Str(app)
     -> env: Str(LIT)
     -> filename: Str(/var/logs/test.log)
     -> environ: Str(LIT)
Trace ID:
Span ID:
Flags: 0
```

**Comment by crobert-1** [comment]
Two things:
1. The `update` action will **only** set the resource attribute's value if the key **already exists** as a resource attribute. In this case it doesn't exist so it won't be set as a resource attribute. You can use `insert` or `upsert` as described [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/README.md) to add a new resource attribute.
2. The resource processor is looking at existing resource attributes when using the `from_attribute` config option. `env` is an attribute on the data point, not the resource, which means it will not be found, and thus will not be set as a resource attribute.

Since you're trying to add a resource attribute that would be set from a data point attribute, you probably want to use the [transform processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) instead. You should be able to use the [DataPoint context](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/contexts/ottldatapoint) to add a resource attribute using the value of a data point attribute.

**Comment by JCoelho008** [comment]
@crobert-1 thanks for the suggestion! I was using the resource with from_attribute because I didn’t fully understand from the documentation that the resource attribute had to already exist. 
After following your advice to use the transform processor, it worked perfectly! The labels are now appearing as expected. 
I really appreciate your help!

**Comment by JCoelho008** [comment]
Sorry to reopen this issue, and let me know if it is better to open a new one, but like I said in the previous comment, everything was working as expected. My issue now is that some log entries, from different log files (note that in my promtail config I have now multiple log files) I see labels such as app_iot with the wrong values.
Quickly showing my config, in otel collector I have this:
```
transform:
      log_statements:
        - context: log
          statements:
            - set(resource.attributes["app_iot"], attributes["app_iot"])
            - delete_key(attributes, "app_iot")
```

I noticed that the values were incorrect and to validate that I removed the delete_key row, which gives me in grafana a "new" attribute called, for this example, "app_iot_extracted", and the app_iot value was different than the app_iot_extracted value.
Since I have labels specific for each log file, should I have a different approach? I mean, not adding the values from attributes to the resource.attributes? Does that mean that I won't be able to query like {app_iot="app1"}? (because with these values in attributes only, I can only query like {env="LIT"} | app_iot=`app1`

Thanks again in advance for your help!

**Comment by edmocosta** [comment]
Hi @JCoelho008! It seems your logs records are being grouped into the same `resource`, which explains why your are seeing wrong values (multiple values to a single resource). I think you could either enabling the [transform.flatten.logs](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#transformflattenlogs) to provide each log record a distinct copy of its resource and scope, or maybe make the `resource.attributes["app_iot"]` an array,  appending all `attributes["app_iot"]` values to it, for example:

```yaml
transform:
      log_statements:
        - context: log
          statements:
            - append(resource.attributes["app_iot"], attributes["app_iot"])
            - delete_key(attributes, "app_iot")
```

**Comment by JCoelho008** [comment]
I'm also having some trouble enabling transform.flatten.logs. I tried to add "flatten_data: true" under transform but then got the error:
`Error: invalid configuration: processors::transform: 'flatten_data' requires the 'transform.flatten.logs' feature gate to be enabled                                                                                                            │
│ 2025/02/21 07:35:49 collector server run finished with error: invalid configuration: processors::transform: 'flatten_data' requires the 'transform.flatten.logs' feature gate to be enabled  `

Already tried enabling it with extraEnvs but got no luck.

Noticed that I can enable feature gates in this values file (https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/values.yaml) but the values file that we are using is this one (https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml). Will the feature gate and transform.flatten.logs still work for me?

Thanks

**Comment by edmocosta** [comment]
Hi @JCoelho008!

> I also have a resource processor to "upsert" the key service.name with the value otelcol_service. Should this be placed before or after the transform in the processors pipeline?

Processors are executed in the same order you configure them in your pipeline, so if you need access the modified data from the previous processor, that should comes first. 

In your case, I think you can replace both `attributes` and `resource` processors by a single `transform` processor, since the data you're modifying are all supported by the transform processor.

> With flatten_data set to true, will the CPU/memory usage of the collector increase significantly?

When this option is enabled, the processor copy the resource and scope for every log record, regrouping them at the end. 
It probably increases the CPU consumption, but that should be acceptable depending on your environment and data load.

> Error: invalid configuration: processors::transform: 'flatten_data' requires the 'transform.flatten.logs' feature gate to be enabled

I haven't tested it, but It seems you can enabled the feature gate by passing them at the [extraArgs](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml#L203) value:

```yaml
command:
  extraArgs:
    - '--feature-gates=+transform.flatten.logs'
```
