### ISSUE TITLE
[AWS S3 Exporter] GZIP not compressing json logs

### ISSUE THREAD

**Issue by KevinThompsonYCRX** [open-telemetry/opentelemetry-collector-contrib#37917]
## Description
Sent my logs through the exporter & they appeared in s3 as `logs_103016847.json.gz`, but when I downloaded the content it was just a json file. Is there something wrong with the switch statement?

I set `compression: gzip`, but did not specify the file extension so I know at least part of the code parsed the compression correctly

### Collector version

0.119.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp/app:
    protocols:
      http:
        endpoint: ${env:MY_POD_IP}:24225
  otlp/audit:
    protocols:
      http:
        endpoint: ${env:MY_POD_IP}:24226
  otlp/infra:
    protocols:
      http:
        endpoint: ${env:MY_POD_IP}:24227
processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s
  memory_limiter:
    check_interval: 2s
    limit_mib: 4000
exporters:
  awss3/app:
    s3uploader:
      region: 'us-east-1'
      s3_bucket: 'test-otel-exporter'
      s3_prefix: '/app/${env:CLUSTER_NAME}'
      s3_partition: 'hour'
      storage_class: 'INTELLIGENT_TIERING'
      compression: gzip
  awss3/audit:
    s3uploader:
      region: 'us-east-1'
      s3_bucket: 'test-otel-exporter'
      s3_prefix: '/audit/${env:CLUSTER_NAME}'
      s3_partition: 'hour'
      storage_class: 'INTELLIGENT_TIERING'
      compression: gzip
  awss3/infra:
    s3uploader:
      region: 'us-east-1'
      s3_bucket: 'test-otel-exporter'
      s3_prefix: '/infrastructure/${env:CLUSTER_NAME}'
      s3_partition: 'hour'
      storage_class: 'INTELLIGENT_TIERING'
service:
  pipelines:
    logs/app:
      receivers: [otlp/app]
      processors:
        - memory_limiter
        - batch
      exporters: [awss3/app]
    logs/audit:
      receivers: [otlp/audit]
      processors:
        - memory_limiter
        - batch
      exporters: [awss3/audit]
    logs/infra:
      receivers: [otlp/infra]
      processors:
        - memory_limiter
        - batch
      exporters: [awss3/infra]
```

### Log output

```shell

```
