### ISSUE TITLE
Process persists in the processscraper for 5 minutes since the process ends

### ISSUE THREAD

**Issue by dpeddi-gen** [open-telemetry/opentelemetry-collector-contrib#37971]
### Component(s)

receiver/hostmetrics/internal/scraper/processscraper

## Description

I'm trying to use opentelemetry cli collector to scrape process(es).
I tried to run a "/bin/sleep 34". The  process disappears from after 5 minutes since the process ends.

Since i have the same issue both in prometheus ingested with otlphttp and with the prometheus exporter I expect this is an issue in the cli itself.

## Steps to Reproduce

run 
otelcol-contrib --config=./config.yaml

in another ssh session:
/bin/sleep 34

visit 0.0.0.0:8889 
... /bin/sleep 34... will be present in the output for 5 minutes

## Expected Result

the process should disappear from 0.0.0.0:8889 and from the prometheus otlp, after less then the double of collection_interval

## Actual Result

The process disappear after 5 minute since the process ends.

### Collector version

otelcol-contrib_0.119.0_linux_amd64

## Environment
OS: (e.g., "Ubuntu 20.04")
Red Hat Enterprise Linux Server release 6.10 (Santiago)
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
processors:
  resourcedetection:
    detectors: [env, system]
  deltatocumulative:

  batch:
    send_batch_size: 1
    timeout: 10s

# receivers configure how data gets into the Collector.
receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      # CPU utilization metrics
      cpu:
        metrics:
          system.cpu.time:
            enabled: false
          system.cpu.frequency:
            enabled: false
          system.cpu.logical.count:
            enabled: false
          system.cpu.physical.count:
            enabled: false
          system.cpu.utilization:
            enabled: false

      # Disk I/O metrics
      disk:
        metrics:
          system.disk.io:
            enabled: false
          system.disk.io_time:
            enabled: false
          system.disk.merged:
            enabled: false
          system.disk.operation_time:
            enabled: false
          system.disk.operations:
            enabled: false
          system.disk.pending_operations:
            enabled: false
          system.disk.weighted_io_time:
            enabled: false
      # File System utilization metrics
      filesystem:
        metrics:
          system.filesystem.inodes.usage:
            enabled: false
          system.filesystem.usage:
            enabled: false
          system.filesystem.utilization:
            enabled: false

      # CPU load metrics
      load:
#         enabled: false
      # Memory utilization metrics
      memory:
#         enabled: false
      # Network interface I/O metrics & TCP connection metrics
      network:
#         enabled: false
      # Paging/Swap space utilization and I/O metrics
      paging:
#         enabled: false
      process:
        #scrape_process_delay: 30s
        mute_process_exe_error: true
        metrics:
          process.cpu.time:
            enabled: true
          process.cpu.utilization:
            enabled: true
          process.disk.io:
            enabled: true
          process.memory.usage:
            enabled: true
          process.memory.virtual:
            enabled: true
          process.uptime:
            enabled: true


service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [deltatocumulative, batch, resourcedetection]
      exporters: [debug, otlphttp/prometheus, prometheus]


exporters:
  debug:
    sampling_initial: 5
    sampling_thereafter: 5

  otlphttp/prometheus:
    endpoint: http://<remotehost>:9090/api/v1/otlp

  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true
```

### Log output

```shell

```

**Comment by dpeddi-gen** [comment]
Hello,

probably this behaviour is due to 
  deltatocumulative:
     max_stale: "5m"

I'm testing it would work better by decreasing this parameter to a multiple of collection_interval

**Comment by dpeddi-gen** [comment]
Hello,

I'm not sure that this is an issue of "receiver/hostmetrics"... 

Using  prometheus exporter, by adding metric_expiration, the metrics can be muted after a reasonable time
```
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    **metric_expiration: 30s**
    resource_to_telemetry_conversion:
      enabled: true
```

using file exporter, the metrics are logged when the command runs. when it ends they are not logged anymore.
```
exporters:
  file/no_rotation:
    path: ./file_exporter.out
```

So the problem seems to be on otlphttp... I can't find a flag equivalent do **metric_expiration**
```
  otlphttp/prometheus:
    endpoint: http://<remotehost>:9090/api/v1/otlp
```

thanks
