### ISSUE TITLE
[exporter/elasticsearch] body is mapped to message instead of attributes.message when using ecs mapping

### ISSUE THREAD

**Issue by jori-be** [open-telemetry/opentelemetry-collector-contrib#38005]
### Component(s)

exporter/elasticsearch

## Description
I'm using kafka receiver to get data with otlp_json encoding.
I'm exporter this to ES via the elasticsearch exporter.
When I use mapping mode ecs, I see that body (full json logline in this case) is mapped to message. I expect that attricutes.message is mapped to message.

## Steps to Reproduce
This is the incoming kafka document as an example:
`{
    "resourceLogs": [{
            "resource": {
                "attributes": [{
                        "key": "k8s.namespace.name",
                        "value": {
                            "stringValue": "someapp"
                        }
                    }, {
                        "key": "k8s.pod.name",
                        "value": {
                            "stringValue": "someapp-nextgen-fddd569d8-mfh4t"
                        }
                    }, {
                        "key": "k8s.container.restart_count",
                        "value": {
                            "stringValue": "0"
                        }
                    }, {
                        "key": "k8s.pod.uid",
                        "value": {
                            "stringValue": "49da5701-5b5f-4df2-b23d-efb6c2bb1bd4"
                        }
                    }, {
                        "key": "k8s.container.name",
                        "value": {
                            "stringValue": "someapp-nextgen"
                        }
                    }
                ]
            },
            "scopeLogs": [{
                    "scope": {},
                    "logRecords": [{
                            "timeUnixNano": "1739880438000000000",
                            "observedTimeUnixNano": "1739880438217002837",
                            "body": {
                                "stringValue": "{\"instant\":{\"epochSecond\":1739880438,\"nanoOfSecond\":196229395},\"thread\":\"http-nio-8080-exec-6\",\"level\":\"DEBUG\",\"loggerName\":\"org.springframework.security.web.FilterChainProxy\",\"message\":\"Securing GET /admin/health\",\"endOfBatch\":false,\"loggerFqcn\":\"org.apache.commons.logging.LogAdapter$Log4jLog\",\"contextMap\":{},\"threadId\":28,\"threadPriority\":5}"
                            },
                            "attributes": [{
                                    "key": "contextMap",
                                    "value": {
                                        "kvlistValue": {}
                                    }
                                }, {
                                    "key": "threadPriority",
                                    "value": {
                                        "doubleValue": 5
                                    }
                                }, {
                                    "key": "log.file.path",
                                    "value": {
                                        "stringValue": "/var/log/pods/someapp_someapp-nextgen-fddd569d8-mfh4t_49da5701-5b5f-4df2-b23d-efb6c2bb1bd4/someapp-nextgen/0.log"
                                    }
                                }, {
                                    "key": "log.iostream",
                                    "value": {
                                        "stringValue": "stdout"
                                    }
                                }, {
                                    "key": "thread",
                                    "value": {
                                        "stringValue": "http-nio-8080-exec-6"
                                    }
                                }, {
                                    "key": "level",
                                    "value": {
                                        "stringValue": "DEBUG"
                                    }
                                }, {
                                    "key": "instant",
                                    "value": {
                                        "kvlistValue": {
                                            "values": [{
                                                    "key": "epochSecond",
                                                    "value": {
                                                        "doubleValue": 1739880438
                                                    }
                                                }, {
                                                    "key": "nanoOfSecond",
                                                    "value": {
                                                        "doubleValue": 196229395
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }, {
                                    "key": "message",
                                    "value": {
                                        "stringValue": "Securing GET /admin/health"
                                    }
                                }, {
                                    "key": "endOfBatch",
                                    "value": {
                                        "boolValue": false
                                    }
                                }, {
                                    "key": "logtag",
                                    "value": {
                                        "stringValue": "F"
                                    }
                                }, {
                                    "key": "loggerFqcn",
                                    "value": {
                                        "stringValue": "org.apache.commons.logging.LogAdapter$Log4jLog"
                                    }
                                }, {
                                    "key": "threadId",
                                    "value": {
                                        "doubleValue": 28
                                    }
                                }, {
                                    "key": "loggerName",
                                    "value": {
                                        "stringValue": "org.springframework.security.web.FilterChainProxy"
                                    }
                                }, {
                                    "key": "log.file.name",
                                    "value": {
                                        "stringValue": "0.log"
                                    }
                                }, {
                                    "key": "log.file.path_resolved",
                                    "value": {
                                        "stringValue": "/var/log/pods/someapp_someapp-nextgen-fddd569d8-mfh4t_49da5701-5b5f-4df2-b23d-efb6c2bb1bd4/someapp-nextgen/0.log"
                                    }
                                }
                            ],
                            "traceId": "",
                            "spanId": ""
                        },
                    ]
                }
            ]
        }
    ]
}
`

See screenshot, all other attribute fields are correctly mapped, only the message not.

![Image](https://github.com/user-attachments/assets/fde22e00-18a0-4416-a95c-eda158b4039f)

## Expected Result
attributes.message is mapped to message

## Actual Result
body is mapped to message instead of attributes.message

### Collector version

0.119.0

## Environment
OS: (e.g., "Rocky 9")
Elasticsearch version: 8.11.4

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  kafka:
    topic: eks-logs
    brokers:
    - kafka01.example.com:9092
    - kafka02.example.com:9092
    - kafka03.example.com:9092
    encoding: otlp_json
    protocol_version: 2.0.0
processors:
  attributes:
    actions:
    - key: test
      from_attribute: loggerName
      action: insert
  resource:
    attributes:
    - key: application
      from_attribute: k8s.container.name
      action: insert
exporters:
  debug:
    verbosity: detailed
  elasticsearch:
    endpoints:
    - http://elastic-data01.example.com:9200
    - http://elastic-data02.example.com:9200
    - http://elastic-data03.example.com:9200
    logs_index: test-index
    mapping:
      mode: ecs

service:
  pipelines:
    logs:
      receivers: [kafka]
      processors: [attributes,resource]
      exporters: [elasticsearch, debug]
  extensions: [health_check, pprof, zpages]
```

### Log output

```shell

```
