### ISSUE TITLE
Azure Event Hub receiver blocks startup if it cannot connect to Azure

### ISSUE THREAD

**Issue by debarghyad2x** [open-telemetry/opentelemetry-collector-contrib#38049]
### Component(s)

receiver/azureeventhub

### Describe the issue you're reporting

I am not sure what is causing this, but when run in a Kubernetes environment, adding this receiver to the pipeline causes the startup probes to fail. There are no errors in the logs for the collector.  When run outside Kubernetes, via docker, it works correctly. I have tried increasing the timeouts for the startup probes but with the same result.

**Comment by atoulme** [comment]
We don't have an azure event hub exporter. Please post your configuration? Version of the collector?

**Comment by debarghyad2x** [comment]
> We don't have an azure event hub exporter. Please post your configuration? Version of the collector?

My bad, I meant the Azure event hub _receiver_, edited my original post.
Collector version `0.119.0`

Config (with some parts removed): 
```
mode: "statefulset"

nodeSelector:
  name: utils

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi

statefulset:
  volumeClaimTemplates:
  - metadata:
      name: otel-queue
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources: 
        requests: 
          storage: 10Gi
  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenDeleted: Retain
    whenScaled: Retain

extraVolumeMounts: 
  - name: otel-queue
    mountPath: /var/lib/otelcol/file_storage

ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

serviceMonitor:
  metricsEndpoints:
    - port: metrics
  enabled: true
  interval: 30s
  relabelings:
  - action: replace
    replacement: d2x-infra
    targetLabel: owner

# Base collector configuration.
config:
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    file_storage:
      timeout: 1s
  receivers:
    otlp:
      protocols:
        http:
        grpc:
          endpoint: 0.0.0.0:4317
    azureeventhub/entra-audit:
      connection: "Endpoint=<connection string>"

  processors:
    batch: {}
    memory_limiter:  
      check_interval: 5s          
      limit_percentage: 80
      spike_limit_percentage: 25

    resource/entra-audit:
      attributes:
        - action: insert
          key: logtype
          value: "entra-audit"

  exporters:
    otlphttp/opensearch-vector:
      endpoint: <opensearch-endpoint>
      tls:
        insecure: true

  service:
    extensions: [file_storage, health_check]
    pipelines:
      logs/opensearch-vector-entra:
        exporters: [otlphttp/opensearch-vector]
        processors: [resource/entra-audit, batch]
        receivers: [azureeventhub/entra-audit] 

## This container is used to set the /var/lib/otelcol/file_storage folder permissions to writeable
## so that otelcollector can write the queue to it. Otherwise it does not have write permissions.
initContainers:
 - name: init-fs
   image: busybox:1.36
   command:
     - sh
     - '-c'
     - 'chown -R 10001: /var/lib/otelcol/file_storage' # use the path given as per `extensions.file_storage.directory` & `extraVolumeMounts[x].mountPath`
   volumeMounts:
     - name: otel-queue # use the name of the volume used for persistence
       mountPath: /var/lib/otelcol/file_storage # use the path given as per `extensions.file_storage.directory` & `extraVolumeMounts[x].mountPath`
```
