### ISSUE TITLE
Configmap pull value from url or api endpoint

### ISSUE THREAD

**Issue by phantonrider** [open-telemetry/opentelemetry-collector-contrib#38052]
### Is your feature request related to a problem? Please describe.

We have an issue/requirement where we use a password managers to store and rotate passwords. Cyberark and hashicorp vault are used. This means that any of the receivers and exporters that require passwords have to be updated manually. 

### Describe the solution you'd like

The possibility of defining config to collect from an endpoint any value that we require. Similar to the s3 and awssecretmanager that already exists. The value than can be used as a variable in the configuration for receivers and exporters to use were needed.

### Describe alternatives you've considered

Configuration managers to update the configuration for us which adds delay and possible password rotation before the configuration update is applied. Also the password or other value is visible in the config file which reduces security of that password.

**Comment by VihasMakwana** [comment]
This should be possible using embedded configuration. Something like:

```yaml

exporter/foo:
    username: username
    password: ${http://example.com/password}

```

password will be stored at http://example.com/password. 

To make it a bit more secure (i.e. to not expose the url), you can do:

```export PASSWORD_URL=${http://example.com/password}```

```yaml

exporter/foo:
    username: username
    password: ${env:PASSWORD_URL}

```

The `${..}` sytanx is needed to recursively expand the configuration.
