### ISSUE TITLE
[processor/transform] Add support for failover statements

### ISSUE THREAD

**Issue by edmocosta** [open-telemetry/opentelemetry-collector-contrib#38051]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

Given we've recently added support for granular `error_mode` at the transform processor (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/37676), I'm opening this issue to discuss a possible enhancement on the error handling. 

### Describe the solution you'd like

The proposal would be supporting some kind of "failover statements" to be executed when a configurations statement with `error_more`  equals to `ignore` or `silent` fails to execute.

**Why?**
Currently, the statements execution is not atomic, so If I've multiple statements on my configuration block, actions  performed by previous statements are not reverted, for example:

```yaml
log_statements:
 - context: log
   error_mode: ignore
   statements:
    - set(severity_text, "INFO")
    - merge_maps(attributes, ParseJSON(1), "upsert") # This statement fail, but previous changes are not reverted
``` 

That situation might be fine for most use cases, but in few situations it would be nice to have the possibility of reverting the changes or add some extra logic/data to mark that some processing has failed, for example:

```yaml
log_statements:
 - context: log
   error_mode: ignore
   statements:
     - set(attributes["foo"], "bar")
     - merge_maps(attributes, ParseJSON(1), "upsert") # This statement fail, but previous changes are not reverted
   failover_statements:
     - delete_key(attributes, "foo")
     - set(attributes["_jsonparsinggroupfailure"], true)
``` 

### Describe alternatives you've considered

Currently, we can achieve a similar result by checking for "possible" errors verifying the absence of expected data, for example, the above scenario could be expressed as:

```yaml
log_statements:
 - context: log
   error_mode: ignore
   statements:
     - set(attributes["foo"], "bar")
     - merge_maps(attributes, ParseJSON(1), "upsert")

 - context: log
   conditions: 
      - attributes["some_expected_merged_key"] == nil
   statements:
     - delete_key(attributes, "foo")
     - set(attributes["_jsonparsingfailure"], true)
``` 

That's a reasonable approach, but it feels disconnected with the previous statements, and prone to errors as we need some data to be able to determine if previous executions have failed.

### Additional context

Finally, the solution described here is just an idea, it definitely needs more thoughts, and it would be great the hear other people's thoughts on that, and discuss if such feature would be useful for processor's users.
