### ISSUE TITLE
[exporters/sentryexporter] Recorded errors in spans not being exported in Sentry

### ISSUE THREAD

**Issue by uds5501** [open-telemetry/opentelemetry-collector-contrib#3809]
**Describe the bug**
When we record errors and/or exceptions via opentelemetry sdk / api. The exceptions are stored as an event (in Go sdk) within the span Events.
When the conversion between input span to sentry spans occur, there is no conversion of these exceptions to sentry events, which needs to be there to leverage full capabilities of Sentry's distributed tracing suite.
 
**Steps to reproduce**
You can follow a simple architecture of 

[Golang Code] ---(OTLP GRPC)----> [Otel-collector-contrib] ---- (sentryexporter) ----> Sentry UI

For example, my instrumentation was : 
```go

func oneMore(c *gin.Context) {
	_, span := tracer.Start(c.Request.Context(), "apiHit", oteltrace.WithAttributes(attribute.String("test", "onetwothreee")))
	defer span.End()
	app, err := http.Get("https://trell11.co")
	if err != nil {
		span.RecordError(err)
	}
	fmt.Println(app)
}
```

The error didn't show up on Sentry but the distrubted traces did (minus the errors).

**What did you expect to see?**
I expect that the traces show me that there was an error in a particular transaction and link to the error.

**What did you see instead?**
The error didn't show up on Sentry but the distrubted traces did (again, minus the errors).

**What version did you use?**
Version: `v0.28.0`

**What config did you use?**
```yaml

receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 683
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      health_check: {}
    exporters:
      logging: {}
      sentry:
        dsn: mydsn
      elastic:
        apm_server_url: myserver
        secret_token: mytoken
    service:
      extensions: [health_check]
      pipelines:
        traces/3:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [sentry, logging, elastic]
```
**Environment**
OS: Ubuntu 20.04
