### ISSUE TITLE
[receiver/memcached] memcached config requires a transport not specified in docs

### ISSUE THREAD

**Issue by strawgate** [open-telemetry/opentelemetry-collector-contrib#38111]
## Description
Docs provide an example that does not work:
```
receivers:
  memcached:
    endpoint: "localhost:11211"
    collection_interval: 10s
```

Error: invalid configuration: receivers::memcached::addrconfig: invalid transport type ""
2025/02/22 01:03:33 collector server run finished with error: invalid configuration: receivers::memcached::addrconfig: invalid transport type ""

it actually requires `transport: udp/tcp` to work

## Steps to Reproduce

```
receivers:
  memcached:
    endpoint: "172.17.0.1:11211"
    collection_interval: 10s
```

## Expected Result

works

## Actual Result

doesn't work

### Collector version

0.120.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```
