### ISSUE TITLE
headers_setter invalidated when tail_sampling processor is added to pipeline

### ISSUE THREAD

**Issue by kworkbee** [open-telemetry/opentelemetry-collector-contrib#38123]
## Description

Same as #29852 (Re-open).

If the `tail_sampling` processor configuration is added to the pipeline, the `headers_setter` extension configuration is invalidated.

## Steps to Reproduce

OTEL Collector

```yaml
    exporters:
      debug: {}
      otlphttp:
        auth:
          authenticator: headers_setter
        compression: zstd
        endpoint: http://tempo-gateway # Use tempo as backend
        tls:
          insecure: true
    extensions:
      headers_setter:
        headers:
        - from_context: X-Tenant
          key: X-Scope-OrgID
        - action: insert
          default_value: TRACE
          from_context: X-Tenant
          key: X-Scope-OrgID
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch:
        metadata_keys:
        - X-Tenant
      filter/ottl:
        error_mode: ignore
        traces:
          span:
          - IsMatch(attributes["http.route"], "/actuator*")
          - IsMatch(attributes["url.path"], "/actuator*")
          - IsMatch(attributes["http.route"], "/check/health")
          - IsMatch(attributes["url.path"], "/check/health")
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      resource:
        attributes:
        - action: upsert
          key: datacenter
          value: baremetal
      tail_sampling:
        policies:
        - name: sample_ok_traces
          numeric_attribute:
            key: http.response.status_code
            max_value: 299
            min_value: 200
          probabilistic:
            sampling_percentage: 100
          type: numeric_attribute
        - name: sample_not_ok_traces
          numeric_attribute:
            key: http.response.status_code
            max_value: 599
            min_value: 400
          probabilistic:
            sampling_percentage: 100
          type: numeric_attribute
    // ...
```

## Expected Result

If the `X-Scope-OrgID` is specified according to the above configuration, the Trace must be passed to the tenant of the specified value, otherwise to the `TRACE` tenant.

## Actual Result

Despite the settings, all traces are passed to the `TRACE` tenant.

### Collector version

0.120.0

## Environment
OS: AWS AL2023
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
      debug: {}
      otlphttp:
        auth:
          authenticator: headers_setter
        compression: zstd
        endpoint: http://tempo-gateway # Use tempo as backend
        tls:
          insecure: true
    extensions:
      headers_setter:
        headers:
        - from_context: X-Tenant
          key: X-Scope-OrgID
        - action: insert
          default_value: TRACE
          from_context: X-Tenant
          key: X-Scope-OrgID
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch:
        metadata_keys:
        - X-Tenant
      filter/ottl:
        error_mode: ignore
        traces:
          span:
          - IsMatch(attributes["http.route"], "/actuator*")
          - IsMatch(attributes["url.path"], "/actuator*")
          - IsMatch(attributes["http.route"], "/check/health")
          - IsMatch(attributes["url.path"], "/check/health")
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      resource:
        attributes:
        - action: upsert
          key: datacenter
          value: baremetal
      tail_sampling:
        policies:
        - name: sample_ok_traces
          numeric_attribute:
            key: http.response.status_code
            max_value: 299
            min_value: 200
          probabilistic:
            sampling_percentage: 100
          type: numeric_attribute
        - name: sample_not_ok_traces
          numeric_attribute:
            key: http.response.status_code
            max_value: 599
            min_value: 400
          probabilistic:
            sampling_percentage: 100
          type: numeric_attribute
    // ...
```

### Log output

```shell

```

**Comment by VihasMakwana** [comment]
I'll take a look and get back to you.

**Comment by VihasMakwana** [comment]
@kworkbee I was able to reproduce this and I'll start working on a fix.

**Comment by VihasMakwana** [comment]
@SimranCode Hey,

I did some digging and it's not really that simple to fix the behaviour. 
Consider this example:
- let's say you receive traces from multiple receivers and they all set some headers in the context. 
- tail sampling processor samples all the traces and the context of traces can have different values for same headers.

How do we decide which value to on the outgoing trace? There will be conflicts and we might end up setting it to a wrong value.

**Comment by meSATYA** [comment]
Similar issue is seen for servicegraph & spanmetrics connectors. We are receiving `X-Scope-OrgID` in the span header, but after the metrics are generated on the connector, the metric doesn't include the header which is an obstacle in sending the metrics to respective tenants on Mimir.

```
connectors:
  servicegraph:
    dimensions:
    - db.name
    - db.system
    - messaging.operation
    - messaging.system
    - messaging.destination
    - net.peer.name
    - net.sock.peer.name
    - peer.service
    - server.address
    latency_histogram_buckets:
    - 100ms
    - 250ms
    - 500ms
    - 1s
    - 5s
    - 10s
    metrics_flush_interval: 1m
    store:
      max_items: 5000
      ttl: 300s
    virtual_node_extra_label: true

processors:
  batch:
    metadata_cardinality_limit: 300
    metadata_keys:
    - X-Scope-OrgID
    send_batch_size: 5000
    timeout: 5s

extensions:
  headers_setter:
    headers:
    - action: upsert
      from_context: X-Scope-OrgID
      key: X-Scope-OrgID
  health_check:
    endpoint: ${env:MY_POD_IP}:13133
  zpages:
    endpoint: ${env:MY_POD_IP}:55679

exporters:
  otlphttp/mimir:
    auth:
      authenticator: headers_setter
    compression: gzip
    endpoint: http://mimir-gateway.mimir-dev:80/otlp
    retry_on_failure:
      enabled: true
      initial_interval: 200ms
      max_elapsed_time: 0s
      max_interval: 10s
    sending_queue:
      enabled: true
      num_consumers: 8
      queue_size: 10000
    timeout: 10s
    tls:
      insecure: true
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
        include_metadata: true
        max_recv_msg_size_mib: 16
      http:
        endpoint: ${env:MY_POD_IP}:4318
        include_metadata: true
services:
  extensions:
    - zpages
    - health_check
    - headers_setter
  pipelines:
    traces:
      exporters:
      - servicegraph
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
    metrics/servicegraph:
      exporters:
      - otlphttp/mimir
      processors:
      - memory_limiter
      - batch
      receivers:
      - servicegraph
```
