### ISSUE TITLE
New component: azureservicebusreceiver

### ISSUE THREAD

**Issue by lukasstolt** [open-telemetry/opentelemetry-collector-contrib#38125]
### The purpose and use-cases of the new component

The purpose of this component is to enable monitoring of Azure Service Bus by collecting metrics such as topic/queue size, count of active messages and count of deadletter messages. Some of these metrics are available using the azuremonitorreceiver, but this way Azure monitor will not be needed. Also, an important addition is that this will enable monitoring of active-/deadletter messages on the scope of a topic subscription, which Azure Monitor does not support.

### Example configuration for the component

```
receivers:  
  azureservicebus:
    namespace_fqdn: example.servicebus.windows.net
    collection_interval: 1m
    auth: default_credentials
```

### Telemetry data types supported

Metrics

### Code Owner(s)

@lukasstolt @syron @riha
