### ISSUE TITLE
tailsampling with multiple and policies not sampled

### ISSUE THREAD

**Issue by cyrilfantin** [open-telemetry/opentelemetry-collector-contrib#38142]
### Component(s)

processor/tailsampling

## Description
in the readme, there is an example where a noisy endpoint is sampling more than the other
```
{
        # Rule 3: low sampling for a noisy endpoint
        name: team_a-noisy-endpoint-1,
        type: and,
        and:
          {
            and_sub_policy:
              [
                {
                  name: service-name-policy,
                  type: string_attribute,
                  string_attribute:
                    { key: service.name, values: [service-1] },
                },
                {
                  # filter by route
                  name: route-name-policy,
                  type: string_attribute,
                  string_attribute:
                    {
                      key: http.route,
                      values: [/v1/name/.+],
                      enabled_regex_matching: true,
                    },
                },
                {
                  # apply probabilistic sampling
                  name: probabilistic-policy,
                  type: probabilistic,
                  probabilistic: { sampling_percentage: 1 },
                },
              ],
          },
      },
      {
        # Rule 4: high sampling for other endpoints
        name: team_a-service-1,
        type: and,
        and:
          {
            and_sub_policy:
              [
                {
                  name: service-name-policy,
                  type: string_attribute,
                  string_attribute:
                    { key: service.name, values: [service-1] },
                },
                {
                  # invert match - apply to all routes except the ones specified
                  name: route-name-policy,
                  type: string_attribute,
                  string_attribute:
                    {
                      key: http.route,
                      values: [/v1/name/.+],
                      enabled_regex_matching: true,
                      invert_match: true,
                    },
                },
                {
                  # apply probabilistic sampling
                  name: probabilistic-policy,
                  type: probabilistic,
                  probabilistic: { sampling_percentage: 100 },
                },
              ],
          },
      },
``` 

I try to apply just these policies but the noisy endpoint is ignored.
If i apply only policy for the noisy endpoint it works but other endpoints are not sampled anymore

if i try to not use invert_match like
`values: [.*],
  enabled_regex_matching: true,`
the noisy endpoint is not sampled

## Steps to Reproduce
tailsampling with just 2 policies and, one for a noisy endpoint and another one for default endpoint

## Expected Result
the noisy endpoint should be sample with a sampling_percentage and all other sample with another value

## Actual Result
default endpoints are sampled but not the noisy endpoint

### Collector version

latest

## Environment
Run with public.ecr.aws/aws-observability/aws-otel-collector:latest on AWS ECS

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

processors:
  tail_sampling:
    decision_wait: 10s
    decision_cache:
      sampled_cache_size: 100000
      non_sampled_cache_size: 100000
    policies:
      - name: and-policy-other
        type: and
        and:
          and_sub_policy:
            - name: other-than-s3
              type: string_attribute
              string_attribute:
                key: http.url
                values: ["my_noisy_url"]
                invert_match: true
            - name: probabilistic-policy-other
              type: probabilistic
              probabilistic:
                sampling_percentage: 20
      - name: and-policy-s3
        type: and
        and:
          and_sub_policy:
            - name: s3
              type: string_attribute
              string_attribute:
                key: http.url
                values: ["my_noisy_url"]
            - name: probabilistic-policy-s3
              type: probabilistic
              probabilistic:
                sampling_percentage: 1

exporters:
  debug:
    verbosity: detailed
  awsxray:
    indexed_attributes: ["environment", "product", "otel.resource.service.name"]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        [ tail_sampling ]
      exporters: [awsxray]


  extensions: [health_check]
```

### Log output

```shell

```
