### ISSUE TITLE
googlecloudpubsubreceiver: growing unacked message in subscription

### ISSUE THREAD

**Issue by RuslanAkchurinMutinex** [open-telemetry/opentelemetry-collector-contrib#38164]
### Component(s)

receiver/googlecloudpubsub

## Description
I am using Open Telemetry Collectors deployed in GKE. This is a dedicated deployment that only works with one subscription. There is a organization sink sending all relevant logs to that subscription. Throughput is conservative, after applying filter in sink it's only around ~200k messages per day. Collectors deployment consists of 5 pods with 500mi/1Gi limits (not even close to hit them anyway). Shortly after deployment I purge messages and almost immediately observe slow but steady growth of unacked messages. There are no errors in collector output (except channel re-establishing) There are no failed or refused records in collector self telemetry. There are no messages in dlq. Subscription is set with 600 ack deadline, exactly once delivery enabled.

## Steps to Reproduce
Setup organization sink, setup subscription, start collecting logs from it.

## Expected Result
All sent messages are acknowledged

## Actual Result
Some messages are not acknowledged and their number growths with time.

### Collector version

v0.120.1

## Environment
OS: cos

### OpenTelemetry Collector configuration

```yaml
receivers:
  googlecloudpubsub/logs/minimal:
    project: ${PROJECT_ID}
    subscription: ${SUBSCRIPTION_ID}
    encoding: cloud_logging

processors:
  batch:
    send_batch_size: 4096

exporters:
  otlp/googlecloud:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": ${HONEYCOMB_API_KEY}
      "x-honeycomb-dataset": ${HONEYCOMB_DATASET}

service:
  pipelines:
    logs/minimal:
      receivers: [googlecloudpubsub/logs/minimal]
      processors: [batch]
      exporters: [otlp/googlecloud]
```

### Log output

```shell

```

### Additional context

<img width="1904" alt="Image" src="https://github.com/user-attachments/assets/7b5e4d5f-0bb4-4a2f-aabc-dbb8791c7db8" />
