### ISSUE TITLE
sqlserver receiver complains about TLS handshaking errors in version 0.120.0

### ISSUE THREAD

**Issue by percy78** [open-telemetry/opentelemetry-collector-contrib#38248]
### Component(s)

receiver/sqlserver

## Description

When upgrading to version 0120.0 from the previous version we were running at, metrics from sqlserver running on Linux/k8s stopped working due to tls handshaking issue.  

## Steps to Reproduce

Roll back to 0.109.0 and metrics is again visible in Grafana

## Expected Result

No issues in the otel-collector image 0.120.0 logs complaining about tls handshake failure  

## Actual Result

"error": "sqlServerScraperHelper failed gett │hake failed: tls: fail │
│ ing metric rows: TLS Handshake failed: tls: failed to parse certificate from server: x509: negative serial number"

### Collector version

0.120.0

## Environment
K8s RKE 

### OpenTelemetry Collector configuration

```yaml
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta
  namespace: otel-collector-metrics-and-traces
spec:
  # Mode should be deployment as we're not collecting node metrics
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.120.0

  # Use a pre-defined serviceaccount that gets created in rbac.yaml
  serviceAccount: otel-collector

  # Configuration for the OTEL Collector
  config: 
    exporters:
      debug:
        verbosity: detailed
      # Exporter for OaaS
      otlp/with_auth:
        auth:
          authenticator: oauth2client
        endpoint: ""
        tls:
          insecure: false
          insecure_skip_verify: true
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      # Authentication toward OaaS
      oauth2client:
        client_id: ""
        client_secret: ""
        timeout: 2s
        token_url: ""
    processors:
      batch:
        metadata_keys:
        - X-Scope-OrgID
      attributes/cluster:
        actions:
        - key: cluster
          value: wl006-t
          action: upsert
      k8sattributes/miq954:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
        # Filter telemetry to a namespace.
        # Required since we don't have cluster-wide access.
        filter:
          namespace: otel-collector-metrics-and-traces
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: 'kubernetes-pods'
            honor_labels: true
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names:
                  - otel-collector-metrics-and-traces
                  - otel-collector-logs
                  - miq954-test
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_slow]
                action: drop
                regex: true
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
                action: replace
                regex: (https?)
                target_label: __scheme__
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
                action: replace
                regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
                replacement: '[$2]:$1'
                target_label: __address__
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_ip]
                action: replace
                regex: (\d+);((([0-9]+?)(\.|$)){4})
                replacement: $2:$1
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
                replacement: __param_$1
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_phase]
                regex: Pending|Succeeded|Failed|Completed
                action: drop
      redis: 
        endpoint: redis.miq954-test.svc.cluster.local:6379
        username: myuser
        password: mypassword
        collection_interval: 10s
        tls:
          insecure: true
      mysql:
        endpoint: mariadb.miq954-test.svc.cluster.local:3306
        username: 
        password: 
        database: db1
        collection_interval: 10s
        initial_delay: 1s
        statement_events:
          digest_text_limit: 120
          time_limit: 24h
          limit: 250
      sqlserver:
        collection_interval: 10s
        username: 
        password: 
        server: 172.17.162.93  
        port: 1433
        metrics:  
          sqlserver.database.count:
            enabled: true
          sqlserver.database.io:
            enabled: true
          sqlserver.database.latency: 
            enabled: true
          sqlserver.database.operations:
            enabled: true
          sqlserver.processes.blocked:
            enabled: true
          sqlserver.resource_pool.disk.throttled.read.rate:
            enabled: true
          sqlserver.resource_pool.disk.throttled.write.rate:
            enabled: true
          sqlserver.user.connection.count:
            enabled: true
      postgresql:
        endpoint: postgres.miq954-test.svc.cluster.local:5432
        transport: tcp
        username: 
        password: 
        databases: 
          - db1
        connection_pool:
          max_idle_time: 10m
          max_lifetime: 0
          max_idle: 2
          max_open: 5
        tls:
          insecure: true
          insecure_skip_verify: true
      kafkametrics:
        cluster_alias: kafka-test
        protocol_version: 2.0.0
        brokers:
          - "kafka-svc.miq954-test.svc.cluster.local:9092"
        scrapers:
          - brokers
          - consumers
          - topics
        collection_interval: 5s
      kafka:
        protocol_version: 2.0.0
        brokers:
          - "kafka-svc.miq954-test.svc.cluster.local:9092"
        topic:  otlp-metrics
        header_extraction: 
          extract_headers: true
          headers: ["header1", "header2"]
      mongodb:
        hosts:
          - endpoint: mongo-nodeportort-svc.miq954-test.svc.cluster.local:27017
        username: 
        password: 
        collection_interval: 60s
        initial_delay: 1s
        tls:
          insecure: true
          insecure_skip_verify: true
    service:
      extensions:
      - health_check
      - oauth2client
      pipelines:
        metrics:
          exporters:
          - otlp/with_auth
          processors:
          - attributes/cluster
          - k8sattributes/miq954
          - memory_limiter
          - batch
          receivers:
          - otlp
          - prometheus      
          - redis      
          - mysql      
          - sqlserver
          - postgresql
          - kafkametrics
          - kafka
          - mongodb
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 32Mi
```

### Log output

```shell
"error": "sqlServerScraperHelper failed gett │hake failed: tls: fail │
│ ing metric rows: TLS Handshake failed: tls: failed to parse certificate from server: x509: negative serial number"
```

### Additional context

Tried image 0.117.0 and the issue doesn't appear in here subsequently appeared in the latter ones. 

Postgres mongodb and redis has options to add tls as insecure presumably that's the option that is missing here.
