### ISSUE TITLE
New component: OCI Logging Analytics Exporter [exporter/ocilogginganalyticsexporter]

### ISSUE THREAD

**Issue by naga-barri** [open-telemetry/opentelemetry-collector-contrib#38244]
### The purpose and use-cases of the new component

The OCI Logging Analytics Exporter will transmit metrics from the OpenTelemetry Collector to [OCI Logginng Analytics|https://docs.oracle.com/en-us/iaas/logging-analytics/home.htm] platform. It is designed to export customer logs to OCI Logging Analytics service.
This exporter plugin uses OCI AuthN/AuthZ to export data from customer environment into OCI Logging Analytics service. This will be the first exporter that supports OCI Auth.

### Example configuration for the component

The following settings are **required**:

- `namespace` (no default): The OCI tenancy namespace to which the collected log data will be uploaded.
- `log_group_id` (no default): The log group OCID to which the log data will be mapped.

The following configuration options can also be configured:

- `auth_type` (default: config_file): The authentication type to use. Supported values are:
- `config_file`: Use OCI configuration file for authentication.
- `instance_principal`: Use OCI instance principal for authentication.
- `oci_config_file_path` (no default): Path to the OCI configuration file. If auth_type is config_file and this is not provided, the exporter will search for the configuration in the default location ($HOME/.oci/config or the location specified by the OCI_CONFIG_FILE environment variable).
- `config_profile` (default: DEFAULT): The profile to be used in the OCI configuration file, if auth_type is config_file
- `passphrase` (no default) : Password for the private key, if applicable.
- `oci_config_file` (no default): Contains the OCI configuration details (alternative to providing a oci_config_file_path), if auth_type is config_file. The following fields are required:
- `fingerprint` (no default): The fingerprint of the OCI user.
- `private_key` (no default): The private key of the OCI user.
- `tenancy` (no default): The OCI tenancy OCID.
- `region` (no default): The OCI region.
- `user` (no default): The OCI user OCID.

NOTE: If both oci_config_file_path and oci_config_file are provided, the exporter will prioritize oci_config_file and ignore oci_config_file_path.

Example:

```
exporters:
  oci_logging_analytics:
    namespace: "my_namespace"
    log_group_id: "ocid1.loggroup.oc1..example"
    auth_type: "config_file"
    oci_config_file_path: "/path/to/oci/config"
    config_profile: "DEFAULT"

```

**Optional Settings**
The following settings can be optionally configured:

- `timeout` (default: 5s): The maximum duration before a request times out.

`sending_queue`:
- `enabled` (default: false): If true, logs will be buffered in a queue before being sent.
- `queue_size` (default: 500): The number of logs that can be buffered before dropping.
- `blocking` (default = false): If true, blocks the request until the queue has space otherwise returns immediately.
- `num_consumers` (default: 10): The number of consumers that will process logs from the queue.
- `storage` (default = none): When set, enables persistence and uses the component specified as a storage extension for the persistent queue. There is no in-memory queue when set.

`retry_on_failure`:
- `enabled` (default: true): If true, failed requests will be retried.
- `initial_interval` (default: 5s): The initial time to wait before retrying a failed request.
- `max_interval` (default: 30s): The maximum time to wait between retries.
- `max_elapsed_time` (default: 300s): The maximum time allowed for all retries.

Example:

```
exporters:
  oci_logging_analytics:
    namespace: "my_namespace"
    log_group_id: "ocid1.loggroup.oc1..example"
    auth_type: "config_file"
    oci_config_file_path: "/path/to/oci/config"
    config_profile: "DEFAULT"
    timeout: 10s
    sending_queue:
      enabled: true
      queue_size: 1000
      num_consumers: 10
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s


```

### Telemetry data types supported

logs

### Code Owner(s)

naga-barri, santhoshkvuda, Kalsaria-C
