### ISSUE TITLE
New component: pprofreceiver

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#38260]
### The purpose and use-cases of the new component

With support for profiles as a native signal for the collector, it would be nice if the collector could emit profiles of itself or any other pprof enabled process and export pprof profiles.

### Example configuration for the component
```
receivers:
  pprof/self: # no configuration
  pprof/somegoprocess:
    endpoint: 127.0.1.1:8000
```
### Telemetry data types supported

profiles

### Code Owner(s)

@MovieStoreGuy  @atoulme 

### Sponsor (optional)

@MovieStoreGuy
