### ISSUE TITLE
Docker receiver doesn't show stats for all containers

### ISSUE THREAD

**Issue by sekulicd** [open-telemetry/opentelemetry-collector-contrib#38265]
### Describe the issue you're reporting

I am running few Docker containers on my machine and i wanted to collect their start using docker receiver, however looks like i am only getting starts for one container, probably otel-collector itself.

Here is my setup:

collector-config.yaml
```
receivers:
  hostmetrics:
    collection_interval: 10s
    root_path: /hostfs
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      load:
      network:

  docker_stats:
    collection_interval: 10s
    endpoint: unix:///var/run/docker.sock

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889”

  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: “debug”
      encoding: “console”
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics, docker_stats]
      processors: [batch]
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

```

docker-compose.yaml
```
services:
  ########################
  # OpenTelemetry Collector
  ########################
  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    networks:
      - dokploy-network
    volumes:
      - ./collector-config.yaml:/etc/otelcol/config.yaml:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"  # gRPC OTLP
      - "4318:4318"  # HTTP OTLP
      - "8889:8889"  # Prometheus metrics endpoint
    restart: unless-stopped
    privileged: true
    security_opt:
      - apparmor:unconfined
    group_add:
      - "988"
```

Stats:

```
curl -G "http://localhost:9090/api/v1/query" \
     --data-urlencode "query={__name__=~\"container.+\"}" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3149    0  3149    0     0  1606k      0 --:--:-- --:--:-- --:--:-- 3075k
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "container_blockio_io_service_bytes_recursive_total",
          "device_major": "8",
          "device_minor": "0",
          "instance": "otel-collector:8889",
          "job": "otel-collector",
          "operation": "read"
        },
        "value": [
          1740737015.138,
          "0"
        ]
      },
      {
        "metric": {
          "__name__": "container_blockio_io_service_bytes_recursive_total",
          "device_major": "8",
          "device_minor": "0",
          "instance": "otel-collector:8889",
          "job": "otel-collector",
          "operation": "write"
        },
        "value": [
          1740737015.138,
          "4096"
        ]
      },
      {
        "metric": {
          "__name__": "container_cpu_usage_kernelmode_nanoseconds_total",
          "instance": "otel-collector:8889",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "84197000"
        ]
      },
      {
        "metric": {
          "__name__": "container_cpu_usage_nanoseconds_total",
          "instance": "otel-collector:8889",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "1931704000"
        ]
      },
      {
        "metric": {
          "__name__": "container_cpu_usage_usermode_nanoseconds_total",
          "instance": "otel-collector:8889",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "1847507000"
        ]
      },
      {
        "metric": {
          "__name__": "container_cpu_utilization_ratio",
          "instance": "otel-collector:8889",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "0"
        ]
      },
      {
        "metric": {
          "__name__": "container_memory_file_bytes",
          "instance": "otel-collector:8889",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "40960"
        ]
      },
      {
        "metric": {
          "__name__": "container_memory_percent_ratio",
          "instance": "otel-collector:8889",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "0.023660501472984645"
        ]
      },
      {
        "metric": {
          "__name__": "container_memory_usage_limit_bytes",
          "instance": "otel-collector:8889",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "32857325568"
        ]
      },
      {
        "metric": {
          "__name__": "container_memory_usage_total_bytes",
          "instance": "otel-collector:8889",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "7774208"
        ]
      },
      {
        "metric": {
          "__name__": "container_network_io_usage_rx_bytes_total",
          "instance": "otel-collector:8889",
          "interface": "eth0",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "72388"
        ]
      },
      {
        "metric": {
          "__name__": "container_network_io_usage_rx_bytes_total",
          "instance": "otel-collector:8889",
          "interface": "eth1",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "3564"
        ]
      },
      {
        "metric": {
          "__name__": "container_network_io_usage_rx_dropped_total",
          "instance": "otel-collector:8889",
          "interface": "eth0",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "0"
        ]
      },
      {
        "metric": {
          "__name__": "container_network_io_usage_rx_dropped_total",
          "instance": "otel-collector:8889",
          "interface": "eth1",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "0"
        ]
      },
      {
        "metric": {
          "__name__": "container_network_io_usage_tx_bytes_total",
          "instance": "otel-collector:8889",
          "interface": "eth0",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "12014245"
        ]
      },
      {
        "metric": {
          "__name__": "container_network_io_usage_tx_bytes_total",
          "instance": "otel-collector:8889",
          "interface": "eth1",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "0"
        ]
      },
      {
        "metric": {
          "__name__": "container_network_io_usage_tx_dropped_total",
          "instance": "otel-collector:8889",
          "interface": "eth0",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "0"
        ]
      },
      {
        "metric": {
          "__name__": "container_network_io_usage_tx_dropped_total",
          "instance": "otel-collector:8889",
          "interface": "eth1",
          "job": "otel-collector"
        },
        "value": [
          1740737015.138,
          "0"
        ]
      }
    ]
  }
}
```
