### ISSUE TITLE
invalid memory address or nil pointer dereference with log files larger than 1 MB

### ISSUE THREAD

**Issue by pantanuj** [open-telemetry/opentelemetry-collector-contrib#38289]
### Component(s)

receiver/otlpjsonfile

## Description
When the log file size being read exceeds 1 MB, collector errors out with invalid memory address or nil pointer dereference. The stack trace is 
```
2025-03-02T17:07:03.725-0600    info    fileconsumer/file.go:265        Started watching file   {"otelcol.component.id": "otlpjsonfile", "otelcol.component.kind": "Receiver", "otelcol.signal": "traces", "component": "fileconsumer", "path": "C:\\otel-file-export\\logs-metrics.log"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x71d8005]

goroutine 29 [running]:
go.opentelemetry.io/collector/pdata/plog.Logs.ResourceLogs(...)
        go.opentelemetry.io/collector/pdata@v1.26.0/plog/logs.go:60
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otlpjsonfilereceiver.createLogsReceiver.func1({0xc1662f0?, 0xc0011d2690?}, {{0xc002040000?, 0x100000?, 0x0?}, 0xc0014065a0?})
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otlpjsonfilereceiver@v0.120.1/file.go:92 +0x145
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).readContents(0xc00197c270, {0xc1662f0, 0xc0011d2690})
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.120.1/fileconsumer/internal/reader/reader.go:221 +0x303
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).ReadToEnd(0xc00197c270, {0xc1662f0, 0xc0011d2690})
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.120.1/fileconsumer/internal/reader/reader.go:117 +0x7c8
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1(0xc00197c270)
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.120.1/fileconsumer/file.go:169 +0x9e
created by github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume in goroutine 86
        github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.120.1/fileconsumer/file.go:166 +0x1ea
```
## Steps to Reproduce
Configure pipeline to export logs to disk using file exporter. Default settings with max_megabytes set to 2.
Try to read the logs using a separate pipeline with otlpjsonfile receiver. Exporting to debug console for testing.

## Expected Result
Log files should be parsed and should be written to console

## Actual Result
Log files are parsed if size is small ( less than 1 MB). For any higher size, nil pointer exception is thrown

### Collector version

0.120.1

## Environment
OS: Windows 11

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlpjsonfile:
    include:
      - "C:/otel-file-export/*.log"

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlpjsonfile]
      processors: [batch]
      exporters: [debug]
    traces:
      receivers: [otlpjsonfile]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlpjsonfile]
      processors: [batch]
      exporters: [debug]
```

### Log output

```shell

```
