### ISSUE TITLE
[exporter/kafka] Kerberos ccache support

### ISSUE THREAD

**Issue by sokoide** [open-telemetry/opentelemetry-collector-contrib#38291]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

Kafka exporter supports keytab for Kerberized connection, but doesn't support credential cache.

### Describe the solution you'd like

We'd like to support Kerberos credential cache as below.

```yaml
exporters:
  kafka:
    auth:
      kerberos:
        service_name: 'foo'
        realm: 'BAR.COM'
        use_keytab: false
        keytab_file: '/this/is/ignored'
        # use credential cache
        use_ccache: true
        ccache_file: '/tmp/krb5cc_111861'
...
```

### Additional context

We have an environment which we can't copy/generate keytab files, but can have prestashed tickets updated regularly. We'd like to use the ticket as a credential cache.
