### ISSUE TITLE
Storage metrics don't reflect I/O from all devices

### ISSUE THREAD

**Issue by jonnangle** [open-telemetry/opentelemetry-collector-contrib#38301]
### Component(s)

receiver/awsecscontainermetrics

## Description

storage.read_bytes and storage.write_bytes metrics only reflect one block device.

## Steps to Reproduce

Create an ECS task with a container that uses multiple block IO devices.

## Expected Result

The metrics reflect the sum of all Read / Write op counters exposed via `blkio_stats.io_service_bytes_recursive`.

## Actual Result

The metrics only reflect the metric from the final Read/Write op counter in the list.

### Collector version

v0.120.0

## Environment
OS: Linux on AWS ECS Fargate

### OpenTelemetry Collector configuration

```yaml
receivers:
  awsecscontainermetrics:
    collection_interval: 60s

processors:
  batch:
    timeout: 200ms

exporters:
  prometheusremotewrite:
    endpoint: https://prometheus.endpoint

service:
  pipelines:
    metrics:
      receivers:
        - awsecscontainermetrics
      processors:
        - batch
      exporters:
        - prometheusremotewrite
```

### Log output

```shell

```

### Additional context

Fix for this: accumalate reads/writes when iterating over the `IoServiceBytesRecursives` list [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/awsecscontainermetricsreceiver/internal/awsecscontainermetrics/metrics_helper.go#L112-L115).
