### ISSUE TITLE
Githubreceiver fails with ERROR 404 trying to login api.github.com

### ISSUE THREAD

**Issue by bayer-alvaro** [open-telemetry/opentelemetry-collector-contrib#38393]
### Component(s)

receiver/github

### Describe the issue you're reporting

I've tried several different configurations, switching endpoint between "https://api.github.com" and " "https://api.github.com/graphql". All fail with

`error   scraperhelper@v0.120.1-0.20250303102058-a9bca17f1a4c/obs_metrics.go:61  Error scraping metrics  {"otelcol.component.id": "github", "otelcol.component.kind": "Receiver", "otelcol.signal": "metrics", "error": "returned error 404: {\"data\":null}"}`

My config file

```
extensions:
    bearertokenauth/github:
        token: ${env:GH_TOKEN}

receivers:
    github:
        initial_delay: 1s
        collection_interval: 120s
        scrapers:
            scraper:
#                metrics:
#                    vcs.repository.contributor.count:
#                        enabled: true
                github_org: "myorg"
                search_query: "org:myorg topic:beat12345678"
                endpoint: "https://api.github.com"
                auth:
                    authenticator: bearertokenauth/github

exporters:
  awsemf/application:
    namespace: 'BAY_CDP_SERVICES/Otel/Application'
    region: 'eu-central-1'
    log_group_name: '/bay-cdp-custom/github'
    dimension_rollup_option: NoDimensionRollup
    resource_to_telemetry_conversion:
      enabled: true

service:
    extensions: [bearertokenauth/github]
    pipelines:
        metrics:
            receivers: [github]
            processors: []
            exporters: [awsemf/application]

```
