### ISSUE TITLE
Exporter does not respect tls/insecure_skip_verify settings

### ISSUE THREAD

**Issue by bugzyt** [open-telemetry/opentelemetry-collector-contrib#38390]
### Component(s)

exporter/x

### What happened?

**Describe the bug**
Unable to upgrade the Opentelemetry Collector helm chart 0.105v to the latest version due to a TLS issue. None of the TLS settings including insecure_skip_verify are working. I've tried different versions from 0.109v - 0.120v but same issue persist.

Doc reference: https://docs.splunk.com/observability/en/gdi/opentelemetry/common-config/collector-common-config-tls.html 

**Steps to reproduce**
My collector config:

```
exporters:
  splunk_hec:
    index: "main"
    endpoint: https://splunk-hec.com/services/collector/event
    tls:
      insecure: false
      insecure_skip_verify: true
service:
  pipelines:
    logs:
      exporters: [splunk_hec]
```
**What did you expect to see?**
I expected the collector to skip TLS verification as documented.

**What did you see instead?**
The collector is still attempting to verify the server TLS certificate.

### Collector version

0.109.0v - 0.120.0v

## Environment
OS: Red Hat Enterprise Linux CoreOS 414.92
Kubernetes: 1.27

### OpenTelemetry Collector configuration

```yaml
exporters:
  splunk_hec:
    index: "main"
    endpoint: https://splunk-hec.com/services/collector/event
    tls:
      insecure: false
      insecure_skip_verify: true
service:
  pipelines:
    logs:
      exporters: [splunk_hec]
```

### Log output

```shell
2025-03-04T18:46:54.343Z info    exporterhelper/queued_retry.go:215      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "data_type": "logs", "name": "splunk_hec", "error": "Post \"https://splunk-hec.com/services/collector/event": remote error: tls: handshake failure", "interval": "16.969110576s"}
```
