### ISSUE TITLE
Unable to set health_check endpoint in config

### ISSUE THREAD

**Issue by MaartenDeMeyer** [open-telemetry/opentelemetry-collector-contrib#38418]
## Description

I'm deploying the otel collector via a helm chart to my k8s cluster. I'm trying to update beyond v 0.103.0, but I can't get my health_check extension to survive the 0.0.0.0 -> localhost change in v 0.104.0. I can't set the UseLocalHostAsDefaultHost featuregate, since I'm deploying otel as part of a bigger chart and have no control over the CLI. I'm trying to set the health_check's endpoint to 0.0.0.0:13133 explicitly, but no matter what syntax I try, deployment fails with

`cannot unmarshal string into Go struct field OpenTelemetryCollectorSpec.spec.config of type v1beta1.Config`

chart:

```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  image: otel/opentelemetry-collector-contrib:latest
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
...
   extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
...
    service:
      telemetry:
        logs:
          level: "debug"
      extensions: [health_check]
```

Removing the single endpoint line from health_check causes config to pass fine. I've tried with & without various quotes, http:// prefix, checked whitespaces & indentation are correct, and using a health_check/1: entry as described here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/healthcheckextension/README.md . What am I missing?
