### ISSUE TITLE
Azure Event Hub receiver empty offset not starting at latest

### ISSUE THREAD

**Issue by dentonk** [open-telemetry/opentelemetry-collector-contrib#38487]
### Component(s)

receiver/azureeventhub

## Description
The [readme for the Azure Event Hub receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/azureeventhubreceiver/README.md) indicates that when the offset is empty "it starts with the latest offset." Currently that is not the case, and instead it starts at the beginning of the event hub. This is true whether the checkpoint storage is enabled or not. Since https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37157 was merged, the good news is, it will use the stored checkpoint on subsequent restarts, but when there is no checkpoint present, the first run will always start at the beginning of the event hub, as opposed to the latest/end as intended and documented.

## Steps to Reproduce

- Create an Azure Event Hub namespace, hub, consumer group and access policy
- Send a couple messages to the event hub (this can be done using the Data Explorer > Send events option within the Azure Event Hub UI)
- Configure the OTel Collector with the azureeventhub receiver and resources above
- When configuring the receiver, set the offset to `""` which is supposed to tell it to "starts with the latest offset."
- Configure the file storage extension and add it to the azureeventhub receiver
- Configure the collector with the file exporter
- Start the collector
- Check the output file

Repeat the above but with the checkpoint storage disabled. The same unexpected results will occur.

## Expected Result
The messages that were sent before the OTel Collector was running should NOT be immediately ingested/exported once the collector is started. The output file should contain no messages.

## Actual Result
The messages that were sent before the OTel Collector was running are immediately ingested/exported once the collector is started. The output file contains all of the previously stored messages.

### Collector version

v0.121.0

### Environment information

OS: Docker Desktop v4.36.0 on Apple M3

```
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output.log:/output.log
      - ./storage:/storage
```

### OpenTelemetry Collector configuration

```yaml
receivers:
  azureeventhub:
    connection: Endpoint=sb://otelnamespace.servicebus.windows.net/;SharedAccessKeyName=otel_policy;SharedAccessKey=<REDACTED>;EntityPath=otelhub
    format: raw
    group: otelcg
    offset: ""
    partition: ""
    storage: file_storage/eventhub_checkpoint
processors:
  transform/DecodeEventHub:
      error_mode: ignore
      log_statements:
          - context: log
            statements:
              - set(body, Decode(body, "utf-8"))
exporters:
  file:
    path: /output.log
extensions:
  file_storage/eventhub_checkpoint:
      directory: /storage
service:
  extensions:
    - file_storage/eventhub_checkpoint
  pipelines:
    logs/pipeline1:
      receivers:
        - azureeventhub
      processors:
        - transform/DecodeEventHub
      exporters:
        - file
```

### Log output

```shell

```
