### ISSUE TITLE
metricstransformprocessor doesn't rename metric names properly using regexp groups

### ISSUE THREAD

**Issue by pmalek-sumo** [open-telemetry/opentelemetry-collector-contrib#3849]
**Describe the bug**
When a regexp group is used to match a part of metric name the capture group is not available in the result (when specified in the `new_name` configuration option).

**Steps to reproduce**

* Use the config mentioned below
* Observe below described non effect

**What did you expect to see?**

Metrics called `CPU_LoadAvg_1`, `CPU_LoadAvg_5`, `CPU_LoadAvg_15`

**What did you see instead?**

Metrics called: `CPU_LoadAvg__`

**What version did you use?**

Version: tip https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/e75ff8c0927531b929628fa50fd408e73d6d285d

**What config did you use?**

Config:

```yaml
receivers:
  hostmetrics:
    collection_interval: 1s
    scrapers:
      load:

processors:
  metricstransform:
    transforms:
    - include: ^system.cpu.load_average(.*)m$
      match_type: regexp
      action: update
      new_name: CPU_LoadAvg__$1

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [metricstransform]
      exporters: [logging]
```

Named capture group also doesn't work:

```yaml
    - include: ^system.cpu.load_average(?P<interval>.*)m$
      match_type: regexp
      action: update
      new_name: CPU_LoadAvg__$interval
```

**Environment**
OS: Mac OS  and Ubuntu in vagrant
Compiler(if manually compiled): 1.16.4

**Comment by pmalek-sumo** [comment]
It seems that in order to use the value captured from the regex one needs to use double `$` like so (using single `$` to get env variables):

```yaml
processors:
  metricstransform:
    transforms:
    - include: ^system\.cpu\.load_average\.(.*)m$
      match_type: regexp
      action: update
      new_name: CPU_LoadAvg__$${1}_${SHELL}
    # pick one: above or below
    - include: ^system\.cpu\.load_average\.(?P<interval>.*)m$
      match_type: regexp
      action: update
      new_name: CPU_LoadAvg__$${interval}_${SHELL}
```

Curly braces are required if the placeholder is not the list thing in the `new_name`.

**Comment by pmalek-sumo** [comment]
It seems that most of this has been covered by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4132 but there's still the question of using/not using braces.

This becomes problematic when someone wants to use a match group number/name and use it not as the last part in `new_name`. Given this:

```yaml
    - include: ^net_(.*)_recv$
      match_type: regexp
      action: update
```

and the metric called `net_bytes_recv`, we have the following set of results:

```
      new_name: net_${1}recv -> returns net_recv
      new_name: net_$${1}recv -> returns net_bytesrecv
      new_name: net_$1recv -> returns net_recv
      new_name: net_$$1recv -> returns net_
      new_name: net_$1.recv -> returns net_.recv
      new_name: net_$$1.recv -> returns net_bytes.recv
      new_name: net_${1}.recv -> returns net_.recv
      new_name: net_$${1}.recv -> returns net_bytes.recv
```


Hence I propose this to update the README https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4143













Here using braces is necessary, unless there's a dot after the group name, like so:

```yaml
include: ^system\.cpu\.(.*)$$
match_type: regexp
action: update
new_name: system.processor.$$1.something
```

otherwise using `new_name: system.processor.$$1stat`
