### ISSUE TITLE
support clickhouse exporter

### ISSUE THREAD

**Issue by Cairry** [open-telemetry/opentelemetry-collector-contrib#38633]
### Is your feature request related to a problem? Please describe.

Is it supported to export data to ClickHouse for storage, or which version supports this operation now?

### Describe the solution you'd like

support ClickHouse export

---
Version：v0.100.0
```
Error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': error reading configuration for "clickhouse": 1 error(s) decoding:

* '' has invalid keys: create_schema
2025/03/14 08:45:53 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:

* error decoding 'exporters': error reading configuration for "clickhouse": 1 error(s) decoding:

* '' has invalid keys: create_schema
```

**Comment by crobert-1** [comment]
Hello @Cairry, thanks for filing this issue! Can you please share the full collector configuration you're using that's hitting this issue? This will help us give better guidance.

**Comment by SpencerTorres** [comment]
Please provide the full configuration file.

Also confirm that you are using the correct distribution. Only [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) contains the ClickHouse exporter.

Thanks!

**Comment by Cairry** [comment]
> Please provide the full configuration file.
> 
> Also confirm that you are using the correct distribution. Only [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) contains the ClickHouse exporter.
> 
> Thanks!

```
receivers:
  filelog:
    include:
      - /opt/data/logs/access-structured.log
    start_at: beginning
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.time_local
          layout: '%Y-%m-%d %H:%M:%S'
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  batch:
    timeout: 5s
    send_batch_size: 5000
exporters:
  clickhouse:
    endpoint: tcp://localhost:9000?dial_timeout=10s&compress=lz4&async_insert=1
    # ttl: 72h
    traces_table_name: otel_traces
    logs_table_name: otel_logs
    create_schema: true
    timeout: 5s
    database: default
    sending_queue:
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s


service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [clickhouse]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
```

Below is the helm version of the operator
```
apiVersion: v2
appVersion: 0.74.0
description: OpenTelemetry Operator Helm chart for Kubernetes
home: https://opentelemetry.io/
icon: https://raw.githubusercontent.com/cncf/artwork/a718fa97fffec1b9fd14147682e9e3ac0c8817cb/projects/opentelemetry/icon/color/opentelemetry-icon-color.png
maintainers:
- name: Allex1
- name: dmitryax
- name: TylerHelmuth
name: opentelemetry-operator
sources:
- https://github.com/open-telemetry/opentelemetry-operator
type: application
version: 0.26.2
```
