### ISSUE TITLE
Sentry: mapping OTLP service.name to DSNs for multiple Sentry Projects

### ISSUE THREAD

**Issue by sodabrew** [open-telemetry/opentelemetry-collector-contrib#3869]
**Is your feature request related to a problem? Please describe.**

The Sentry exporter takes a DSN argument which maps to a single Project, but I wouldn't want to run a separate OpenTelemetry Collector process for each of my projects.
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/sentryexporter

**Describe the solution you'd like**
Ideally, Sentry itself could accept traces for multiple projects through a single API key and use the service name to put the traces into the right one.

Alternatively, have a mapping of service.name to dsn values in the opentelemetry collector config file. This wouldn't require changes to the Sentry hosted service and wouldn't be an unreasonable burden on the collector config (at least to have a starting point for next steps)

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service

cc @AbhiPrasad

**Comment by AbhiPrasad** [comment]
I think this is a very reasonable request - in fact we’ve tracked a similar issue in our fork of the SDK. https://github.com/getsentry/opentelemetry-collector-contrib/issues/10

I’ll assign myself there and see if I can push out a patch. Thanks for reporting!

**Comment by sodabrew** [comment]
Thank you!

**Comment by RyanSiu1995** [comment]
Upvote for this.
Instead of getting API key, the exporter maybe can also respect a custom field, which contains DSN, inside the trace data.
Otherwise, we need to have a ton of sentry exporters inside the cluster.

**Comment by bloodsper** [comment]
Was this ever finished somewhere? If not; have people been setting up an insane amount of sentry exporters?

**Comment by ananthakumaran** [comment]
This issue can be worked around using [routing](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor) processor. sample below


```
  processors:
    batch: {}
    memory_limiter: {}
    routing:
      attribute_source: resource
      from_attribute: service.name
      default_exporters:
      - logging
      table:
      - value: foo
        exporters: [sentry/foo]
      - value: bar
        exporters: [sentry/bar]
  exporters:
    logging: {}
    sentry/foo:
      dsn: "https://secret@sentry.io/n"
    sentry/bar:
      dsn: "https://secret@sentry.io/n"
  service:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - memory_limiter
          - batch
          - routing
        exporters:
          - logging
          - sentry/foo
          - sentry/bar
```
