### ISSUE TITLE
awsxray exporter ignores NO_PROXY env var

### ISSUE THREAD

**Issue by Yorkerrr** [open-telemetry/opentelemetry-collector-contrib#38757]
## Description
exporter still use https proxy specified in https_proxy environment variable for awsxray, even though no_proxy is set to ".amazonaws.com"

## Steps to Reproduce
1. configure awsxray exporter
2. set https_proxy env variable
3. set no_proxy env variable

## Expected Result
awsxray exporter ignores https_proxy and pushes traces to aws api directly.

## Actual Result
awsxray exporter tries to push traces via https_proxy

### Collector version

0.41.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  awsxray:

service:
  pipelines:
    traces:
      receivers: [awsxray]
      exporters: [awsxray]
```

### Log output

```shell

```

### Additional context

it seems the issue in aws client util 

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/47d88c882cc688514fe312fce7675920d175db2b/internal/aws/awsutil/conn.go#L58C2-L58C10 it configures proxy from env variable or configuration without processing of no_proxy
