### ISSUE TITLE
[receiver/k8scluster] Associate hpa metrics with the scale target

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector-contrib#38768]
### Is your feature request related to a problem? Please describe.

HPA objects are associated with a scale target typically expressed with an expression:
```
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: sample-app
```

This is not currently present on the hpa metrics and therefore it is difficult to understand which hpa metrics are associated with which target.

### Describe the solution you'd like

Add additional dimensions to hpa metrics identifying the metric with the target in a way that allows disambiguation.
