### ISSUE TITLE
How to verify the loadbalancing feature using k8s resolver

### ISSUE THREAD

**Issue by zendesk-shweta** [open-telemetry/opentelemetry-collector-contrib#38788]
### Component(s)

exporter/loadbalancing

### Describe the issue you're reporting

Hi , i am using loadbalancing feature on my existing otel collectors and did the changes on config file
```
Exporter:
loadbalancing/l3:
    routing_key: "service"  # Key to route based on service name
    protocol:
      otlp:
        timeout: 1s  # Timeout for the OTLP exporter
        tls:
          insecure: true
    resolver:
      k8s:
        service: otel-abc.otel-abc-service  # Use the identified service name
        ports:
          - 1111  # Add the ports you want to use for load balancing

service:
  pipelines:
    traces/default:
      receivers: [otlp/default]
      processors: [memory_limiter, attributes/meta_env, attributes/meta_pipeline_otlp, transform/otel_tracer, batch]
      exporters: [loadbalancing/l3, count/svc_collector]
    traces/datadog:
      receivers: [otlp/datadog]
      processors: [memory_limiter, attributes/meta_env, attributes/meta_pipeline_dd, transform/dd_tracer, batch]
      exporters: [loadbalancing/l3, count/svc_dd]
    metrics/collector_obs:
```

after pushing the changes to cluster , and checking the pods , i don't see any reference for exporter , i am not sure how to verify the changes?
Also , is there other changes required on the container side?
current service type is clusterIP

Please suggest how to verify if our load balancer exporter is working as expected and how to verify the changes?

Thanks
