### ISSUE TITLE
Help to config otel colletor to send traces to different newrelic account based on attibute value

### ISSUE THREAD

**Issue by sambestsolutions** [open-telemetry/opentelemetry-collector-contrib#38791]
### Describe the issue you're reporting

HI

I want to configure the OpenTelemetry (OTel) Collector to send traces to different New Relic accounts based on the value of the tenantId attribute.

For example, if tenantId="t0001", the trace should be sent to one New Relic account, and if tenantId="t0002", it should be sent to another New Relic account. If neither of these values is present, the trace should be sent to a default third New Relic account.

I tried to achieve this using the routing processor, but all traces ended up in every account.

Can someone provide the correct configuration and specify which OTel Collector version I should use for this?

Below is the config I used for this purpose

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*:5080


processors:
  batch: {}
  routing:
    from_attribute: tenantId
    default_exporters: [otlphttp/newrelic3]
    table:
    - value: t0001
      exporters: [otlphttp]
    - value: t0002
      exporters: [otlphttp/newrelic2]


exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  otlphttp:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: 

  otlphttp/newrelic2:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: 
  
  otlphttp/newrelic3:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: 

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp, otlphttp/newrelic2, otlphttp/newrelic3]

```

**Comment by crobert-1** [comment]
Hello @sambestsolutions, thanks for filing this issue! Your best bet here is probably to use the [routing connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/routingconnector), as the routing processor has been deprecated in favor of the connector.

**Comment by sambestsolutions** [comment]
> Hello [@sambestsolutions](https://github.com/sambestsolutions), thanks for filing this issue! Your best bet here is probably to use the [routing connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/routingconnector), as the routing processor has been deprecated in favor of the connector.

Hi @crobert-1 Thank you for you response and as suggested I used routing connectors and now this is sending all the traces to all the environments i.e this is brodcasting to all configured instances, I have attached the config I used for this, Is there anything I have missed here


```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*:5080


connectors:
  routing:
    #default_pipelines: [logs/other]
    table:
      - context: resource
        condition: attributes["tenantId"] == "t0001"
        pipelines: [traces/dev]
      - context: resource
        condition: attributes["tenantId"] == "t0002"
        pipelines: [traces/jumjum]


exporters:
  otlphttp/dev:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: 

  otlphttp/jumjum:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: 
  
  otlphttp/stage:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: 


service:
  pipelines:
    traces/dev:
      receivers: [otlp]
      exporters: [otlphttp/dev]
    traces/jumjum:
      receivers: [otlp]
      exporters: [otlphttp/jumjum]
    traces/stage:
      receivers: [otlp]
      exporters: [otlphttp/stage]



```

**Comment by crobert-1** [comment]
Just a quick glance, the trace pipelines need to include the routing connector. Right now the receivers are sending data directly to the exporter without going through the connector.

**Comment by sambestsolutions** [comment]
> Just a quick glance, the trace pipelines need to include the routing connector. Right now the receivers are sending data directly to the exporter without going through the connector.

Hi Thanks for the reply, I modified the config as below and now no traces are getting uploaded, Please note that I am very new to this and trying to get it to work, Help is really appreciated. 

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*:5080


connectors:
  routing:
    table:
      - context: resource
        condition: attributes["tenantId"] == "t0001"
        pipelines: [traces/dev]
      - context: resource
        condition: attributes["tenantId"] == "t0002"
        pipelines: [traces/jumjum]


exporters:
  otlphttp/dev:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: 

  otlphttp/jumjum:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: 
  
  otlphttp/stage:
    endpoint: https://otlp.nr-data.net:4317
    headers:
      api-key: 


service:
  pipelines:
    traces/in:
      receivers: [otlp]
      exporters: [routing]
    traces/dev:
      receivers: [routing]
      exporters: [otlphttp/dev]
    traces/jumjum:
      receivers: [routing]
      exporters: [otlphttp/jumjum]
    traces/stage:
      receivers: [routing]
      exporters: [otlphttp/stage]






```
