### ISSUE TITLE
[k8sobjectsreceiver] Degrade gracefully, when watched CRDs are not found

### ISSUE THREAD

**Issue by krisztianfekete** [open-telemetry/opentelemetry-collector-contrib#38803]
### Component(s)

receiver/k8sobjects

## Description
Today, if you specify a list of CRDs to be watched, the collector won't start if any of them are missing and stay in  CrashLoopBackOff.

## Steps to Reproduce

Apply the following receiver and use it in a pipeline without having `telemetries.telemetry.istio.io` installed on your cluster. 

```yaml
receivers:
    k8sobjects:
      objects:
        - name: telemetries
          mode: watch
          group: telemetry.istio.io/v1alpha1
```
## Expected Result

The collector should start, and the receiver should be able to watch all CRDs it has found.

## Actual Result

```console
Error: invalid configuration: receivers::k8sobjects: resource XY not found. Valid resources are: [                                                                                                                                                                      helmchartconfigs configmaps rolebindings etc. ... 
```

### Collector version

v0.115.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  k8sobjects:
    objects:
      - name: telemetries
        mode: watch
        group: telemetry.istio.io/v1alpha1
```

### Log output

```shell
Error: invalid configuration: receivers::k8sobjects: resource XY not found. Valid resources are: [                                                                                                                                                                      helmchartconfigs configmaps rolebindings etc. ...
```
