### ISSUE TITLE
New component: azure authentication extension

### ISSUE THREAD

**Issue by constanca-m** [open-telemetry/opentelemetry-collector-contrib#38908]
### The purpose and use-cases of the new component

This extension authenticator would work in a similar way `googleclientauth` [extension](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/extension/googleclientauthextension/factory.go).

Currently, there already several azure exporters and receivers, and each have their own authentication ways:
-  `azureblobreceiver`: needs `service_principal` or `connection_string`
- `azureeventhubreceiver`: connection
- `azuremonitorreceiver`: `service_principal`, `workload_identity`, `managed_identity`, `default_credentials`.
- `azureblobexporter`: `connection_string`, `system_managed_identity`,
`user_managed_identity`, `service_principal`.
- `azuredataexplorerexporter`: Service principal, managed identity, default.
- `azuremonitorexporter`: `connection_string`.

With this authenticator extension, we could have a common approach to all of them. This way we have:
- Only one configuration for all the Azure components.
- Supports different authentication methods (see below).
- Implements (`auth.Server` [interface](https://pkg.go.dev/go.opentelemetry.io/collector/extension/auth#Server) and `auth.Client` [interface](https://pkg.go.dev/go.opentelemetry.io/collector/extension/auth#Client)), so it can be used in both receivers and exporters.

Example of integration with some existent components:
- Before:
```yaml
receivers:
  azureeventhub:
    connection: "..." # connection string is discouraged
    
exporters:
  azureblob:
    auth:
      connection_string: "..." # connection string is discouraged
  azuremonitor:
    connection_string: "..." # connection string is discouraged
```

- After:
```yaml
extensions:
  # see in next section example configurations
  azureauth/blob:
  azureauth/monitor:
  azureauth/eventhub:

exporters:
  azureblob:
    auth:
      authenticator: azureauth/blob
  azuremonitor:
    auth:
      authenticator: azureauth/monitor

receivers:
  azureeventhub:
    name: ...
    namespace: ...
    auth:
      authenticator: azureauth/eventhub
```

We could start with the following options for authentication:
- Managed identity support for [Azure resources](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#authenticating-azure-hosted-applications)
- Workload identity support for [Kubernetes](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#authenticating-azure-hosted-applications)
- Service principal support with client secret/certificate for [non Azure](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/README.md#authenticating-service-principals).
- And the default credentials. Discouraged for production. In [azidentity](https://github.com/Azure/azure-sdk-for-go/blob/54746265023eaf4025bb53f3b869cae2489d1f27/sdk/azidentity/default_azure_credential.go#L43-L46), it is mentioned:
> In production, it's better to use a specific credential type so authentication is more predictable and easier to debug.

Connection string is not mentioned for [optimal security](https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string), so there will not be support for that.

See also [recommended authentication](https://learn.microsoft.com/en-us/azure/developer/go/sdk/authentication/authentication-overview?tabs=bash#recommended-app-authentication-approach) approach. We will use the credentials to get the token.

### Example configuration for the component

1. Managed identity:
```yaml
extensions:
  azureauth:
    # resource defines the scope
    resource: "https://<...>.com/.default"
    managed_identity:
      # Types: user or system
      # See https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview#managed-identity-types.
        client_id: ""  # If empty then system-assigned, otherwise user-assigned
```

2. Workload identity:

```yaml
extensions:
  azureauth:
    # resource defines the scope
    resource: "https://<...>.com/.default"
    workload_identity:
      tenant_id: "${AZURE_TENANT_ID}"
      client_id: "${AZURE_CLIENT_ID}"
```

3. Service principal support with client secret/certificate:
```yaml
extensions:
  azureauth:
    # resource defines the scope
    resource: "https://<...>.com/.default"
    service_principal:
      tenant_id: "${AZURE_TENANT_ID}"
      client_id: "${AZURE_CLIENT_ID}"
      client_secret: "${AZURE_CLIENT_SECRET}" # or client_certificate_path
```

4. Default credentials, discouraged in production:
```yaml
extensions:
  azureauth:
    # resource defines the scope
    resource: "https://<...>.com/.default"
    # See DefaultAzureCredential authentication order:
    # https://github.com/Azure/azure-sdk-for-go/blob/54746265023eaf4025bb53f3b869cae2489d1f27/sdk/azidentity/default_azure_credential.go#L48-L57
    use_default: true
```

### Telemetry data types supported

-

### Code Owner(s)

@constanca-m

### Sponsor (optional)

@atoulme
