### ISSUE TITLE
GitHub receiver step spans show huge times when step is skipped

### ISSUE THREAD

**Issue by adrielp** [open-telemetry/opentelemetry-collector-contrib#39020]
### Component(s)

receiver/github

## Description

The step spans for skipped runs show times consistently show times like: `4639920h 46m`. I'm mainly opening this up for myself to track and am actively looking at the fix. Wanted to provide transparency though on the discovery. 

## Steps to Reproduce

Any job with skipped steps will show this way.

## Expected Result

Expected result is `0` time w/ the status of skipped.

## Actual Result

Actual result is a crazy huge time w/ a status of skipped as depicted below.

![Image](https://github.com/user-attachments/assets/02baa2cd-7199-4ece-8984-834b3099c420)

### Collector version

v0.122.0

## Environment
All

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

**Comment by bacherfl** [comment]
Hi @adrielp! Thank you for creating the issue - may i ask to also include the collector config, so it's also easier to reproduce for others?

**Comment by arianvp** [comment]
Reproduces with the following config:

```yaml
receivers:
  github:
    initial_delay: 1s
    collection_interval: 60s
    scrapers:
      scraper:
        github_org: MercuryTechnologies
        auth:
          authenticator: bearertokenauth/github
    webhook:
      secret: "${env:GITHUB_WEBHOOK_SECRET}"
      endpoint: 0.0.0.0:8080
      path: /events
      health_path: /health

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "${env:HONEYCOMB_DATASET}"
    tls:
      insecure: false
  debug: # To use locally for testing/debugging
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
    
extensions:
  bearertokenauth/github:
    token: "${env:GITHUB_PAT}"
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check, bearertokenauth/github]
  pipelines:
    traces:
      receivers:
        - github
      processors:
        - batch
      exporters:
        - otlp
```

**Comment by adrielp** [comment]
Yea, it's the default behavior for the config w/ any traces. GitHub does a weird thing when emitting skipped jobs. Soon as I'm back from Kubecon I'll have a fix up for this. Largely wanted to open this up for myself to go fix (though if someone wants to take it on, no objections). 

@arianvp thanks for providing the config.

**Comment by arianvp** [comment]
Enjoy KubeCon!

**Comment by arianvp** [comment]
Also happens for `cancelled` jobs

**Comment by adrielp** [comment]
Discussed in the CICD SIG today. Requires fix.

**Comment by adrielp** [comment]
Pull request to fix this issue is open.

**Comment by arianvp** [comment]
This issue is not fixed for me

<img width="878" alt="Image" src="https://github.com/user-attachments/assets/37fe9300-4deb-43db-8884-198c2297321f" />

Maybe some interation with #39511 ?  it seems to happen to the queued span

**Comment by arianvp** [comment]
Unfortunately I'm still seeing these issues.

The common trend seems to be that these are jobs that have an `if` statement and never spawn a job run:

```
name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
```

<img width="825" height="402" alt="Image" src="https://github.com/user-attachments/assets/a40fc87f-4081-4886-8bc7-0bd602ae3c51" />

I can dig into finding events for these if needed
