### ISSUE TITLE
[exporter/splunkhec] 403 errors are retried

### ISSUE THREAD

**Issue by friedrichg** [open-telemetry/opentelemetry-collector-contrib#39037]
### Component(s)

exporter/splunkhec

## Steps to Reproduce
Use a wrong hec token 

## Expected Result
It should not retry

## Actual Result
The message says is retrying

### Collector version

v.117.0

## Environment
OS: Alpine

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug:
    verbosity: normal
  splunk_hec:
    token: ${env:SPLUNK_HEC_TOKEN}
    endpoint: "https://splunkurl"
    index: "some"
    source: "http:test3"
receivers:
  filelog:
    include:
    -  /var/log/my.log
processors:
  batch: {}
service:
  pipelines:
    logs:
      receivers:
      - filelog
      exporters:
      - debug
      - splunk_hec
```

### Log output

```shell
Mar 28 14:39:44 c7deed39eaa7 otel-collector[1154]: 2025-03-28T14:39:44.484Z        info        internal/retry_sender.go:126        Exporting failed. Will retry the request after interval.        {"kind": "exporter", "data_type": "logs", "name": "splunk_hec", "error": "HTTP 403 \"Forbidden\"", "interval": "35.47795968s"}
```

### Additional context

Maybe the worker should return with permanent error when getting 4xx errors

Like it does here
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/8e54ec121c994f9e0461a2afaad18c6edb27583a/exporter/splunkhecexporter/hec_worker.go#L37
