### ISSUE TITLE
Missing log with File exporter when group by attribute is not present

### ISSUE THREAD

**Issue by CosbyBs86** [open-telemetry/opentelemetry-collector-contrib#39031]
### Component(s)

exporter/file

## Description
When the groub by feature is enabled and the resource_attribute field is not present in the log, logs are ignored and not dumped on file

## Steps to Reproduce
Configure the exporter as following:
`exporters:
  file:
    path: ./file-exporter/test-*.log
    rotation:
      max_megabytes: 10
      max_days: 1
      max_backups: 3
    format: json
    flush_interval: 10
    group_by:
      enabled: true
      resource_attribute: batchID
`

then send logs through OTEL without the batchID resource attribute

## Expected Result
Logs are dumped in default file (for example in the case above in ./file-exporter/test-.log)

## Actual Result
Logs are ignored and lost

### Collector version

v0.122.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
   otlp:
     protocols:
       grpc:
         endpoint: "0.0.0.0:4317"
       http:
         endpoint: "0.0.0.0:4318"

processors:
  batch:
    send_batch_max_size: 1000  # Massimo 1000 log per batch
    timeout: 30s  # Timeout di 30 secondi
    send_batch_size: 500  # Dimensione consigliata del batch (minore del max)

exporters:
  file:
    path: ./file-exporter/test-*.log
    rotation:
      max_megabytes: 10
      max_days: 1
      max_backups: 3
    format: json
    flush_interval: 10
    group_by:
      enabled: true
      resource_attribute: batchID

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
```

### Log output

```shell

```
