### ISSUE TITLE
prometheusremotewrite to retry when seeing context deadline exceeded up to max_elapsed_time

### ISSUE THREAD

**Issue by awangc** [open-telemetry/opentelemetry-collector-contrib#39041]
### Component(s)

exporter/prometheusremotewrite

### Describe the issue you're reporting

Currently when sending metrics with retry enabled, and we hit an error that translates into "context deadline exceeded", the metrics seem to be dropped before `max_elapsed_time` has passed.

An unresponsive server is actually the occasion to keep retrying, and to mark "context deadline exceeded" errors as permanent error seems to be working against retry.

~~Also according to [OTLP spec](https://opentelemetry.io/docs/specs/otlp/#failures), `DEADLINE_EXCEEDED` is actually a retryable error.~~
UPDATED: as pointed out, prometheusremotewrite follows its own spec and not OTLP protocol. The [spec](https://prometheus.io/docs/specs/prw/remote_write_spec/#retries-backoff) does not clarify what must happen in the event of a connection timeout so current implementation conforms to the spec.

~~Is there a way of making sure retries take place until `max_elapsed_time`?~~
UPDATED: can we update implementation to retry until `max_elapsed_time`? 

Example config

```
receivers:
  prometheus/test:
    config:
      scrape_configs:
        - job_name: 'test'
          scrape_interval: 8s
          static_configs:
            - targets: ['0.0.0.0:8888']

  prometheus/self:
    config:
      scrape_configs:
        - job_name: 'self'
          scrape_interval: 5s
          static_configs:
            - targets: ['0.0.0.0:8888']

exporters:
  prometheusremotewrite/test:
    endpoint: "http://0.0.0.0:3928/test/api/v1/write" # this endpoint will not respond so we should see increased queue size
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 30s
      max_elapsed_time: 1800s
    remote_write_queue:
      enabled: true
      queue_size: 100

  prometheusremotewrite/self:
    endpoint: "http://prometheus:9090/api/v1/write" # this endpoint works so we can see the queue size
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 30s
      max_elapsed_time: 1800s
    remote_write_queue:
      enabled: true
      queue_size: 100


service:
  pipelines:
    metrics:
      receivers: [prometheus/test]
      exporters: [prometheusremotewrite/test]
    metrics/self:
      receivers: [prometheus/self]
      exporters: [prometheusremotewrite/self]
```

Create a local webapp that does not respond
```
from flask import Flask, request
import time
import os

app = Flask(__name__)

TIMEOUT = int(os.environ.get("TIMEOUT", 3600))  

@app.route("/")
def sleep():
    time.sleep(TIMEOUT)
    return "error", 500

if __name__ == "__main__":
    app.run(debug=True, host='0.0.0.0', port=3928)
```
and run it locally:
```
$ python app.py
```
then use this `prometheus.yaml`:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

```
and this docker-compose.yaml
```
version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.122.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector.yaml
    ports:
      - 4317:4317
  
  prometheus:
    image: prom/prometheus
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - 9090:9090
```
and start
```
$ docker compose up
```
If we check on the `otelcol_exporter_queue_size`, we see it never grows even before hitting the `max_elapsed_time` of `1800s` (30 min). 

![Image](https://github.com/user-attachments/assets/e93d1016-fc13-40d2-822a-709c77a55233)

And in the logs we see that it is hitting context deadline exceeded error and seems to be dropping items.
```
prometheusremotewrite-otel-collector-1  | 2025-03-29T01:34:21.109Z	error	internal/queue_sender.go:46	Exporting failed. Dropping data.	{"otelcol.component.id": "prometheusremotewrite/test", "otelcol.component.kind": "Exporter", "otelcol.signal": "metrics", "error": "Permanent error: Permanent error: context deadline exceeded", "dropped_items": 31}
prometheusremotewrite-otel-collector-1  | go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1
prometheusremotewrite-otel-collector-1  | 	go.opentelemetry.io/collector/exporter@v0.122.0/exporterhelper/internal/queue_sender.go:46
prometheusremotewrite-otel-collector-1  | go.opentelemetry.io/collector/exporter/exporterhelper/internal/batcher.(*disabledBatcher[...]).Consume
prometheusremotewrite-otel-collector-1  | 	go.opentelemetry.io/collector/exporter@v0.122.0/exporterhelper/internal/batcher/disabled_batcher.go:23
prometheusremotewrite-otel-collector-1  | go.opentelemetry.io/collector/exporter/exporterqueue.(*asyncQueue[...]).Start.func1
prometheusremotewrite-otel-collector-1  | 	go.opentelemetry.io/collector/exporter@v0.122.0/exporterqueue/async_queue.go:47
prometheusremotewrite-otel-collector-1  | 2025-03-29T01:34:31.179Z	error	internal/queue_sender.go:46	Exporting failed. Dropping data.	{"otelcol.component.id": "prometheusremotewrite/test", "otelcol.component.kind": "Exporter", "otelcol.signal": "metrics", "error": "Permanent error: Permanent error: context deadline exceeded", "dropped_items": 31}
```
