### ISSUE TITLE
[receiver_creator] Started components not reporting status

### ISSUE THREAD

**Issue by rogercoll** [open-telemetry/opentelemetry-collector-contrib#39053]
### Component(s)

receiver/receivercreator

### Is your feature request related to a problem? Please describe.

The receiver creator dynamically starts and stops the configured components based on the watcher rules. This is done by "manually" initiating these components using the [GetFactory](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/graph/host.go#L47) exposed method and sharing the telemetry consumer.

As the start-up is not managed by the collector's internal services, the [ReportStatus interface](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/status/status.go#L101) is not being used. As a result, the spawned components and their runtime status are not reflected in other components like the [healthcheck extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckv2extension) (e.g `curl http://localhost:13133/health/status?verbose`). The following screenshot shows that `receiver_creator` status is being shown by the healtcheck extension, but not the started redis receiver:

![Image](https://github.com/user-attachments/assets/d13a5097-43ce-469b-8c8f-0c0e2b10a927)

Another involved component that might report inaccurate output is the `zpages extension`, either the inner receiver is running or not, it will not appear in the pipelines overview (`http://localhost:55679/debug/pipelinez`):

![Image](https://github.com/user-attachments/assets/e8de4ba1-2ee7-4e2b-a03b-aa206f3ff957)

### Describe the solution you'd like

Component status reporting for any spawned component. 

### Describe alternatives you've considered

Extending the [service core package](https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/hostcapabilities/interfaces.go) to dynamically add/remove receivers from the pipeline. → that would prevent the need of the GetFactory cast method and would easily be able to report component's status.

### Additional context

Configuration used:

```yaml
extensions:
  zpages:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: "localhost:13133"
      status:
        enabled: true
        path: "/health/status"
      config:
        enabled: true
        path: "/health/config"
  docker_observer:

receivers:
  receiver_creator:
    watch_observers: [docker_observer]
    receivers:
      redis/on_container:
        rule: type == "container" && port == 6379
        resource_attributes:
          service.name: redis_on_container
        config:
          endpoint: "localhost:6379"
          collection_interval: 10s

exporters:
  debug:
service:
  pipelines:
    metrics:
      receivers: [receiver_creator]
      processors: []
      exporters: [debug]
  extensions: [zpages, docker_observer, healthcheckv2]

```
