### ISSUE TITLE
[receiver/journald] journald receiver does not collect logs through a rotation when using the files option

### ISSUE THREAD

**Issue by mjlshen** [open-telemetry/opentelemetry-collector-contrib#39061]
### Component(s)

receiver/journald

## Description
When configuring the journald receiver with the `files` option, OTEL Collector ends up starting a process like this under the hood:

```bash
journalctl --utc --output=json --follow --unit gitlab-runner --priority info --file "/var/log/journal/**/*" --all
```

and stream logs into its pipeline, however it stops being able to collect these logs once a journald log rotation occurs (until OTEL Collector is restarted).

## Steps to Reproduce
1. Start `gitlab-runner` or w/e systemd unit, validate that it is generating logs in journald
2. Start OTEL Collector with the journald receiver configured to scrape the systemd unit from step 1.
3. Force a rotation of journald, `journalctl --rotate`

## Expected Result
OTEL Collector is able to recover from journald log rotation (I'm personally not aware of built-in journald functionality to do this) eventually. In this case, re-running `journalctl --utc --output=json --follow --unit gitlab-runner --priority info --file "/var/log/journal/**/*" --all` at any point after rotation would allow logs to be streamed again, but ideally there would be some indication that this was needed.

## Actual Result
1. OTEL Collector stops collecting logs from journald (until OTEL collector is restarted, e.g. `systemctl restart otelcol-contrib.service`)
2. The systemd unit that's being monitored is still writing logs to journald

### Collector version

v0.117.0

## Environment
OS: Amazon Linux 2023
Compiler(if manually compiled): N/A

### OpenTelemetry Collector configuration

```yaml
receivers:
  journald:
    files: /var/log/journal/**/*
    priority: info
    units:
      - gitlab-runner
    all: true
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 30s
      max_elapsed_time: 5
```

### Log output

```shell

```
