### ISSUE TITLE
New component: Azure logs encoding extension

### ISSUE THREAD

**Issue by constanca-m** [open-telemetry/opentelemetry-collector-contrib#39095]
### The purpose and use-cases of the new component

Purpose: Azure logs enconding extension is similar to the already existent component AWS logs encoding extension. Just like AWS, azure logs from multiple services can be sent to different destinations (Azure storage, event hubs...).

We need an encoding extension to unmarshal these logs into plog.Logs.

Use case: internally, we have an azure receiver that receives logs from event hub. That receiver needs an encoding extension to extract the logs from those records. The most close example we have upstream at the moment would be the `azureventhubreceiver` and the way it is decoding the azure resource logs into logs in this [file](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/azureeventhubreceiver/azureresourcelogs_unmarshaler.go).

### Example configuration for the component

Configuration would be like this:

```yaml
extensions:
  azurelogs_encoding/resourcelogs:
     format: azure_monitor

receivers:
   azurefunctionsreceiver:
      encoding: azurelogs_encoding/resourcelogs
```

### Telemetry data types supported

Logs.

### Code Owner(s)

@constanca-m (and @zmoog once he becomes a member)

### Additional context

We are internally using this for our own azure receiver. We would like to contribute to the community with this new receiver as well, but it would be necessary to have this encoding logic in its own extension.
