### ISSUE TITLE
New component: netcheckreceiver

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#39114]
### The purpose and use-cases of the new component

Add a `netcheckreceiver` for TCP/UDP port probing, similar to [net_response](https://github.com/flashcatcloud/categraf/tree/main/inputs/net_response).

### Example configuration for the component

```
receivers:
  netcheck:
    targets:
      - endpoint: endpoint.com:80
        protocol: tcp
        timeout: 10s
      - endpoint: localhost:8080
        method: udp
        tags:
         - region: "local"
    collection_interval: 10s
``` 

### Telemetry data types supported

metrics

### Additional context

Currently, OTel has a `httpcheckreceiver` component. Perhaps it can also be merged into the `netcheckreceiver` component.
