### ISSUE TITLE
OTel not adding kubeletstats attributes

### ISSUE THREAD

**Issue by dmyerscough** [open-telemetry/opentelemetry-collector-contrib#39187]
### Component(s)

receiver/kubeletstats

## Description

I have an OTel collector that is receiving kubelet stats metrics. I can see the k8s.pod.name as a resource attribute. However, when I try to add it as an attribute on the metric, it seems to not add it as a label

```
attributes/k8s-aas:
        actions:
        - action: insert
          key: cluster
          value: XXXXX
        - action: insert
          key: csp
          value: aws
        - action: insert
          from_attribute: k8s.pod.name
          key: pod_name
```

```
StartTimestamp: 2025-04-06 21:26:28 +0000 UTC
Timestamp: 2025-04-06 21:31:29.547988996 +0000 UTC
Value: 68878336
ResourceMetrics #38
Resource SchemaURL:
Resource attributes:
     -> k8s.pod.uid: Str(ba9df558-c0cb-4369-960a-1c8d2780e25d)
     -> k8s.pod.name: Str(node-problem-detector-cpu-v2t2m)
     -> k8s.namespace.name: Str(node-problem-detector)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver 0.117.0
Metric #0
Descriptor:
     -> Name: k8s.pod.cpu.time
     -> Description: Total cumulative CPU time (sum of all cores) spent by the container/pod/node since its creation
     -> Unit: s
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> nv_visible: Str(1)
     -> customer: Str(k8s-aas)
     -> mgmt_owner: Str(k8s-aas)
     -> nspect_id: Str(XXXXXX-XXXX-XXXXX)
     -> cluster: Str(XXXXXX)
     -> csp: Str(aws)
     -> env: Str(non-prod)
```

## Steps to Reproduce

The OTel collector config is run for the OTel Contoller 

## Expected Result

I would expect the kubeletstats metrics (e.g., `k8s_pod_cpu_time`) to include the `pod_name` as a label in the metric, similar to the static labels added in `attributes/k8s-aas`

## Actual Result

The kubeletstats metrics contain all the static labels defined in `attributes/k8s-aas`, except for the `pod_name`.. When I was testing out the Prometheus receivers the `pod_name` was set so it makes me think there is something off with the `kubeletstats`.

### Collector version

0.117.0

## Environment
OS: k8s EKS
Controler: OTel Operator

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug:
    verbosity: detailed
  otlphttp/auth-logs:
    auth:
      authenticator: oauth2client
    endpoint: https://XXXXXXX
  otlphttp/auth-metrics:
    auth:
      authenticator: oauth2client
    endpoint: https://XXXXXXX
extensions:
  health_check:
    endpoint: ${env:POD_IP}:13133
  oauth2client:
    client_id: ${env:PANOPTES_CLIENT_ID}
    client_secret: ${env:PANOPTES_CLIENT_SECRET}
    scopes:
      - api://XXXXXXX/.default
    token_url: ${env:PANOPTES_TOKEN_URL}
processors:
  attributes/add_loki_resource_labels:
    actions:
      - action: insert
        key: loki.resource.labels
        value: filename,cluster,pod,namespace,container
  attributes/k8s-aas:
    actions:
      - action: insert
        key: cluster
        value: XXXXXXX
      - action: insert
        key: csp
        value: aws
      - action: insert
        key: env
        value: non-prod
      - action: insert
        from_attribute: k8s.pod.name
        key: pod_name
  attributes/k8s-aas_logs:
    actions:
      - action: insert
        key: csp
        value: aws
      - action: insert
        key: env
        value: non-prod
  attributes/panoptes:
    actions:
      - action: insert
        key: nv_visible
        value: "1"
      - action: insert
        key: customer
        value: XXXXXXX
      - action: insert
        key: mgmt_owner
        value: XXXXXXX
      - action: insert
        key: nspect_id
        value: XXXXXXX
  batch:
    send_batch_max_size: 4000
    send_batch_size: 2000
    timeout: 10s
  filter:
    logs:
      exclude:
        match_type: regexp
        record_attributes:
          - key: level
            value: (?i).*(debug|info|trace|Normal).*
          - key: body
            value: .*========.*
          - key: body
            value: .*Failed to scrape Prometheus endpoint.*
  k8sattributes:
    auth_type: serviceAccount
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
    passthrough: false
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.name
      - sources:
          - from: resource_attribute
            name: k8s.namespace.name
      - sources:
          - from: connection
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  remotetap/end:
    endpoint: 0.0.0.0:12002
  remotetap/start:
    endpoint: 0.0.0.0:12001
  resource/k8s-aas_logs:
    attributes:
      - action: insert
        key: cluster
        value: XXXXXXX
      - action: insert
        from_attribute: service.namespace
        key: service_namespace
  resource/k8s-aas_metrics:
    attributes:
      - action: insert
        from_attribute: k8s.pod.name
        key: pod
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["node_name"], resource.attributes["k8s.node.name"])
receivers:
  filelog:
    exclude:
      - /var/log/pods/*/otel-collector/*.log
    include:
      - /var/log/pods/*/*/*.log
    include_file_name: true
    include_file_path: true
    operators:
      - id: parser-containerd
        output: merge-cri-lines
        parse_to: body
        regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*)( |)(?P<log>.*)$
        timestamp:
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          parse_from: body.time
        type: regex_parser
      - combine_field: body.log
        combine_with: ""
        id: merge-cri-lines
        is_last_entry: body.logtag == "F"
        overwrite_with: newest
        source_identifier: attributes["log.file.path"]
        type: recombine
      - id: extract-metadata-from-filepath
        parse_from: attributes["log.file.path"]
        parse_to: attributes
        regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<run_id>\d+)\.log$
        type: regex_parser
      - from: attributes.container_name
        to: resource["k8s.container.name"]
        type: move
      - from: attributes.namespace
        to: resource["k8s.namespace.name"]
        type: move
      - from: attributes.pod_name
        to: resource["k8s.pod.name"]
        type: move
      - field: attributes.run_id
        type: remove
      - field: attributes.uid
        type: remove
      - field: attributes["log.file.path"]
        type: remove
      - from: body.log
        to: body
        type: move
    preserve_leading_whitespaces: true
  hostmetrics:
    collection_interval: 60s
    root_path: /hostfs
    scrapers:
      cpu: {}
      disk: {}
      filesystem:
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup2
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict
        exclude_mount_points:
          match_type: regexp
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /run/k3s/containerd/*
            - /run/containerd/runc/*
            - /var/lib/docker/*
            - /var/lib/kubelet/*
            - /snap/*
      load: {}
      memory: {}
      network: {}
      process:
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true
  journald:
    directory: /var/log/journal
    priority: info
    units:
      - ssh
      - kubelet
      - containerd
  kubeletstats:
    auth_type: serviceAccount
    collection_interval: 60s
    endpoint: https://${env:NODE_NAME}:10250
    extra_metadata_labels:
      - container.id
    insecure_skip_verify: true
    metric_groups:
      - pod
      - container
  otlp:
    protocols:
      grpc:
        endpoint: ${env:POD_IP}:4317
      http:
        endpoint: ${env:POD_IP}:4318
  prometheus:
    config:
      global:
        scrape_interval: 60s
        scrape_timeout: 10s
      scrape_configs:
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
        - job_name: kubernetes-endpoints
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_service_label_(.+)
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_service_name
              target_label: service
        - job_name: kubernetes-services
          kubernetes_sd_configs:
            - role: service
          metrics_path: /probe
          params:
            module:
              - http_2xx
        - job_name: kubernetes-ingresses
          kubernetes_sd_configs:
            - role: ingress
          metrics_path: /probe
          params:
            module:
              - http_2xx
          relabel_configs:
            - regex: (.+);(.+);(.+)
              replacement: ${1}://${2}${3}
              source_labels:
                - __meta_kubernetes_ingress_scheme
                - __address__
                - __meta_kubernetes_ingress_path
              target_label: __param_target
            - replacement: blackbox-exporter.example.com:9115
              target_label: __address__
            - source_labels:
                - __param_target
              target_label: instance
            - action: labelmap
              regex: __meta_kubernetes_ingress_label_(.+)
            - source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - source_labels:
                - __meta_kubernetes_ingress_name
              target_label: ingress
        - job_name: yace-exporter
          kubernetes_sd_configs:
            - relabel_configs:
                - action: replace
                  regex: (.*)
                  replacement: $1
                  separator: ;
                  source_labels:
                    - __meta_kubernetes_pod_node_name
                  target_label: instance
              role: pod
              selectors:
                - label: app.kubernetes.io/name=yet-another-cloudwatch-exporter
                  role: pod
        - job_name: otel-collector
          static_configs:
            - targets:
                - 0.0.0.0:8888
service:
  extensions:
    - oauth2client
    - health_check
  pipelines:
    metrics:
      exporters:
        - debug
        - otlphttp/auth-metrics
      processors:
        - remotetap/start
        - k8sattributes
        - transform
        - attributes/panoptes
        - attributes/k8s-aas
        - memory_limiter
        - batch
        - remotetap/end
      receivers:
        - kubeletstats
  telemetry:
    metrics:
      address: 0.0.0.0:8888
```

### Log output

```shell
StartTimestamp: 2025-04-06 21:26:28 +0000 UTC
Timestamp: 2025-04-06 21:31:29.547988996 +0000 UTC
Value: 68878336
ResourceMetrics #38
Resource SchemaURL:
Resource attributes:
     -> k8s.pod.uid: Str(ba9df558-c0cb-4369-960a-1c8d2780e25d)
     -> k8s.pod.name: Str(node-problem-detector-cpu-v2t2m)
     -> k8s.namespace.name: Str(node-problem-detector)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver 0.117.0
Metric #0
Descriptor:
     -> Name: k8s.pod.cpu.time
     -> Description: Total cumulative CPU time (sum of all cores) spent by the container/pod/node since its creation
     -> Unit: s
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> nv_visible: Str(1)
     -> customer: Str(k8s-aas)
     -> mgmt_owner: Str(k8s-aas)
     -> nspect_id: Str(XXXXXX-XXXX-XXXXX)
     -> cluster: Str(XXXXXX)
     -> csp: Str(aws)
     -> env: Str(non-prod)
```
