### ISSUE TITLE
Token is not renewing after few times when we use oauth2clientauthextension

### ISSUE THREAD

**Issue by saikalyanbhagavathula** [open-telemetry/opentelemetry-collector-contrib#39201]
### Component(s)

extension/oauth2clientauth

## Description
When we use oauth2clientauthextension token is not getting regenerated after couple of times. 
The request is still sending with old token, even that is expired. How is new token is fetched by opentelemetry collector?

## Expected Result
Token to renew after every time current token usage expires.

## Actual Result
Token is not renewing after few times.

### Collector version

v0.122.0

## Environment
OS: (e.g., "Ubuntu 20.04")

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check: {}
  zpages: {}
  oauth2client:
    client_id: "<environment_clientId"
    client_secret: "<environment_client_secret>"
    token_url: "<Endpoint_to_get_token>"
    expiry_buffer: 10s
```

### Log output

```shell
2025-04-07T04:31:51.570Z	error	internal/queue_sender.go:46	Exporting failed. Dropping data.	{"otelcol.component.id": "otlp/<exporter_name>", "otelcol.component.kind": "Exporter", "otelcol.signal": "metrics", "error": "not retryable error: Permanent error: rpc error: code = Unauthenticated desc = Error response message from server", "dropped_items": 1867}
```
