### ISSUE TITLE
`tcpcheck.error` does not match the value set

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#39234]
### Component(s)

receiver/tcpcheck

## Steps to Reproduce
Simply start with `tcpcheck`‘s default configuration.

## Expected Result
When TCP errors occur continuously, the value of tcpcheck.error should increase incrementally.

## Actual Result
The value is always 1.

### Collector version

v0123.0

## Environment
OS:  Darwin & Linux

### OpenTelemetry Collector configuration

```yaml
exporters:
  otlphttp/metric:
    metrics_endpoint: localhost:8080/metric
  file:
    path: ./otel.log
processors:
  batch:
    send_batch_size: 100
    send_batch_max_size: 100
    timeout: 5s
  cumulativetodelta:
receivers:
  tcpcheck:
    targets:
      - endpoint: xxx.example.com:443
        dialer:
          timeout: 15s
service:
  pipelines:
    metrics/self:
      receivers:
       - tcpcheck
      processors:
        - cumulativetodelta
        - batch
      exporters:
        - otlphttp/metric
        - file
```

### Log output

```shell

```

### Additional context

The detailed description of the `tcpcheck.error` metric is [metadata.yaml](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/33b352ad893cb5240623562409cfad8b997237be/receiver/tcpcheckreceiver/metadata.yaml#L36C3-L36C17). 

After reviewing the [OTel code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/33b352ad893cb5240623562409cfad8b997237be/receiver/tcpcheckreceiver/scraper.go#L62), I think there are the following solutions:
1. Set the `tcpcheck.error` metric to the `gauge` type.
2. Save the `cumulative` value of the timeseries and then assign it, rather than the [pointValue](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/33b352ad893cb5240623562409cfad8b997237be/receiver/tcpcheckreceiver/scraper.go#L49).
3. Set the metric type to Delta when [initializing](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/33b352ad893cb5240623562409cfad8b997237be/receiver/tcpcheckreceiver/internal/metadata/generated_metrics.go#L100) `tcpcheck.error`
