### ISSUE TITLE
receivers prometheus telemetry job and instance not found

### ISSUE THREAD

**Issue by adelbot** [open-telemetry/opentelemetry-collector-contrib#39240]
### Component(s)

receiver/prometheus

## Description
The attributes job and insta,ce don't exists

## Steps to Reproduce
receivers:

  prometheus/test:
    config:
      scrape_configs:
      - job_name: 'otel-collector-TEST'
        scrape_interval: 10s
        static_configs:
        - targets: ['127.0.0.1:8889']
          labels:
            job_name: 'otel-collector-test'

exporters:

  file/rotation_with_custom_settings:
    path: /var/log/otelcol-contrib/otelcol.out
    flush_interval: 5
    format: json

service:

  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '127.0.0.1'
                port: 8889

  pipelines:

    metrics/test:
      receivers: [ prometheus/test ]
      exporters: [ file/rotation_with_custom_settings ]

## Expected Result
Attributes job and instance created

## Actual Result
{
              "name": "otelcol_process_runtime_total_sys_memory_bytes",
              "description": "Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys') [alpha]",
              "gauge": {
                "dataPoints": [
                  {
                    "attributes": [
                      {
                        "key": "job_name",
                        "value": {
                          "stringValue": "otel-collector-test"
                        }
                      },
                      {
                        "key": "service.instance.id",
                        "value": {
                          "stringValue": "b17fb5fc-07af-49a1-8c6b-60ba37cb08d0"
                        }
                      },
                      {
                        "key": "service.name",
                        "value": {
                          "stringValue": "otelcol-contrib"
                        }
                      },
                      {
                        "key": "service.version",
                        "value": {
                          "stringValue": "0.122.0"
                        }
                      }
                    ],
                    "timeUnixNano": "1744092206298000000",
                    "asDouble": 35738888
                  }
                ]
              }

### Collector version

0.122.0

## Environment
OS: REDHAT8

### OpenTelemetry Collector configuration

```yaml
receivers:

  prometheus/test:
    config:
      scrape_configs:
      - job_name: 'otel-collector-TEST'
        scrape_interval: 10s
        static_configs:
        - targets: ['127.0.0.1:8889']
          labels:
            job_name: 'otel-collector-test'


exporters:

  file/rotation_with_custom_settings:
    path: /var/log/otelcol-contrib/otelcol.out
    flush_interval: 5
    format: json

service:

  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '127.0.0.1'
                port: 8889

  pipelines:

    metrics/test:
      receivers: [ prometheus/test ]
      exporters: [ file/rotation_with_custom_settings ]
```

### Log output

```shell
Apr 08 08:02:28 wdyd5798.net.intra.laposte.fr otelcol-contrib[1199707]: 2025-04-08T08:02:28.812+0200        info        targetallocator/manager.go:184        Scrape job added        {"otelcol.component.id": "prometheus/test", "otelcol.component.kind": "Receiver", "otelcol.signal": "metrics", "jobName": "otel-collector-TEST"}
Apr 08 08:02:28 wdyd5798.net.intra.laposte.fr otelcol-contrib[1199707]: 2025-04-08T08:02:28.812+0200        info        service@v0.122.0/service.go:283        Everything is ready. Begin running and processing data.
Apr 08 08:02:28 wdyd5798.net.intra.laposte.fr otelcol-contrib[1199707]: 2025-04-08T08:02:28.815+0200        info        prometheusreceiver@v0.122.0/metrics_receiver.go:224        Starting scrape manager        {"otelcol.component.id": "prometheus/test", "otelcol.component.kind": "Receiver", "otelcol.signal": "metrics"}
```

**Comment by iblancasa** [comment]
Hi @adelbot can you explain the issue a bit more? What is exactly what you miss? Because (in the output you provided) I can see `service.instance.id` and `job_name` but I'm not sure what do you expect to see.

**Comment by iblancasa** [comment]
> in my config, i force job_name because job attributes don't exist

But that is not the same configuration that you shared in the first comment, right?

The output you shared under the `Actual result` statement is with your configuration or with the one you provided?

Please, try to detail more what is your issue.

**Comment by adelbot** [comment]
Actual_result is the output how it work today : 
job don't exist
instance : don't exist
job_name exist because i add the label

If i add labels job, it don't exist also


I don't understand why job and instance don't exist
It seem that these 2 attributes are removed

**Comment by iblancasa** [comment]
So this output is what you have currently with your configuration. Right?
```json
{
   "name":"otelcol_process_runtime_total_sys_memory_bytes",
   "description":"Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys') [alpha]",
   "gauge":{
      "dataPoints":[
         {
            "attributes":[
               {
                  "key":"job_name",
                  "value":{
                     "stringValue":"otel-collector-test"
                  }
               },
               {
                  "key":"service.instance.id",
                  "value":{
                     "stringValue":"b17fb5fc-07af-49a1-8c6b-60ba37cb08d0"
                  }
               },
               {
                  "key":"service.name",
                  "value":{
                     "stringValue":"otelcol-contrib"
                  }
               },
               {
                  "key":"service.version",
                  "value":{
                     "stringValue":"0.122.0"
                  }
               }
            ],
            "timeUnixNano":"1744092206298000000",
            "asDouble":35738888
         }
      ]
   }
```

That is not the same as this one you pasted:
```yaml
receivers:

  prometheus/test:
    config:
      scrape_configs:
      - job_name: 'otel-collector-TEST'
        scrape_interval: 10s
        static_configs:
        - targets: ['127.0.0.1:8889']
          labels:
            job_name: 'otel-collector-test'


exporters:

  file/rotation_with_custom_settings:
    path: /var/log/otelcol-contrib/otelcol.out
    flush_interval: 5
    format: json

service:

  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '127.0.0.1'
                port: 8889

  pipelines:

    metrics/test:
      receivers: [ prometheus/test ]
      exporters: [ file/rotation_with_custom_settings ]
```

Can you paste what is the output with this configuration? And add more information that can be useful to debug your issue.
Can you also try to use the `debug` exporter with high verbosity to see if the "missing" stuff is there?
