### ISSUE TITLE
Feature Request: Support for Generic SASL OAUTHBEARER Authentication

### ISSUE THREAD

**Issue by ssijbabu** [open-telemetry/opentelemetry-collector-contrib#39248]
### Component(s)

exporter/kafka

### Is your feature request related to a problem? Please describe.

Yes, our feature request is related to the problem of securing the Kafka exporter's connection to a Kafka cluster using standard SASL OAUTHBEARER authentication. Currently, the Kafka exporter appears to only support the AWS MSK-specific variation of OAUTHBEARER. This limitation prevents us from utilizing our organization's preferred and standardized authentication method for securing this crucial monitoring component. We are familiar with configuring Kafka clients (consumers and producers) with generic SASL OAUTHBEARER properties and desire the same level of security and centralized management for our Kafka exporter.

### Describe the solution you'd like

We would like the Kafka exporter to be enhanced with support for generic SASL OAUTHBEARER authentication. This would involve adding configuration options within the exporter's settings (likely in the OpenTelemetry Collector's YAML configuration) to accommodate standard Kafka client properties related to OAUTHBEARER. These properties include, but are not limited to: 
```
sasl.mechanism=OAUTHBEARER
sasl.login.callback.handler.class=
sasl.jaas.config=
```
The exporter should then use these configurations to establish a secure connection to the Kafka cluster using the OAUTHBEARER mechanism.

### Additional context

https://kafka.apache.org/documentation/#security_sasl_oauthbearer

**Comment by axw** [comment]
Adding support for non-AWS MSK SASL/OAUTHBEARER sounds reasonable to me.

> These properties include, but are not limited to:
>
> sasl.mechanism=OAUTHBEARER
> sasl.login.callback.handler.class=
> sasl.jaas.config=

This is JAAS config, for Java applications. I don't think we'll be supporting this as-is. I would expect this to fit with the existing configuration, adding something along the lines of the [oauth2clientauthextension configuration](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oauth2clientauthextension#configuration).

**Comment by ssijbabu** [comment]
Hi @axw 

That sounds great! We appreciate you considering this feature request.

Regarding the configuration, our primary goal is to ensure the Kafka exporter can support all the necessary parameters and functionalities described in the official Apache Kafka documentation for SASL/OAUTHBEARER.  As long as it does that, all will be happy with the approach.

[Kafka official documentation on SASL/OAUTHBEARER](https://kafka.apache.org/documentation/#security_sasl_oauthbearer.)

Thank you for your time and consideration.

**Comment by Schm1tz1** [comment]
Hi all,

that sounds great indeed. I can also see that more and more customers are actually using Kafka with OAuth so having "generic"    OAuth as an authentication method would really be a great thing to have!

Thanks !

**Comment by axw** [comment]
As above I think this makes sense, but to be very explicit: I don't personally have a need for this, so it's not high on my priority list to implement. I'm happy to review PRs to add support.

**Comment by Schm1tz1** [comment]
@axw - Sure, great! I can help top support with this but probably need to dig into the source code first. I'd be happy if you can provide any hint. My idea also is maybe we can use the generic auth modules here. Not sure if that is possible and how it is implements but worth a try IMHO ;-).

**Comment by axw** [comment]
@Schm1tz1 great! :) Here are a few pointers.

1. You would need to add configuration settings to internal/kafka/configkafka.SASLConfig: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/16ac39d8db602bd6207685c90c61739354038e48/internal/kafka/configkafka/config.go#L299-L300
2. Update internal/kafka.configureSASL to set the relevant parts of the Sarama config: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/16ac39d8db602bd6207685c90c61739354038e48/internal/kafka/authentication.go#L43

For (1) you might want to base the configuration settings on https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/oauth2clientauthextension#configuration
For (2) you could copy the implementation of that extension.

The other option (_probably_ my preference) would be to make oauth2clientauthextension implement the oauth2.TokenSource interface, and then configure the Kafka exporter/receiver components with a reference to the extension. So your configuration would look something like this:

```yaml
extensions:
  oauth2client:
    client_id: someclientid
    client_secret: someclientsecret
    endpoint_params:
      audience: someaudience
    token_url: https://example.com/oauth2/default/v1/token
    scopes: ["api.metrics"]
    # tls settings for the token client
    tls:
      insecure: true
      ca_file: /var/lib/mycert.pem
      cert_file: certfile
      key_file: keyfile
    # timeout for the token client
    timeout: 2s
    # buffer time before token expiry to refresh
    expiry_buffer: 10s

receivers:
  kafka:
    auth:
      sasl:
        mechanism: "OAUTHBEARER"
        token_source_extension: oauth2client
```

That would be similar to how HTTP-based exporters can use the oauth2client extension for injecting the Authorization header into outgoing HTTP requests: they can be configured with an "auth" extension.
