### ISSUE TITLE
[processor/transform] support constants or lookups in OTTL statements

### ISSUE THREAD

**Issue by ryn9** [open-telemetry/opentelemetry-collector-contrib#39296]
### Describe the issue you're reporting

I am sure I am missing something, but I have a use case where I need to efficiently map numerical status codes from one log attribute to a word in another log attribute.

I planned on doing this via maps for efficiency (as compared to lists of conditional clauses)

I worry about efficiency, as there does not seem to be a way to create and store maps in a global context (I imagine a global cache).

There also does not seem to be a way to be a way to create and store maps in a context that covers the entire resourceLogs array.

As such - I am currently creating the maps in the resource context, thinking this is at least better than doing this at the logs context.

Additionally after seeing that we cannot currently access resource.cache from the log context, I have placed these maps in resource.attributes and delete them when done process - **gross I know :(**

As such, the ugly config more-or-less looks like this:
```
   transform:

    log_statements:
    
      - context: resource
        statements:
          - set(resource.attributes["___"], {} )
          - set(resource.attributes["___"]["mapper_ifAdminStatus"], {"1":"up", "2":"down", "3":"testing"} )
          - set(resource.attributes["___"]["mapper_ifOperStatus"], {"1":"up", "2":"down", "3":"testing", "4":"unknown", "5":"dormant", "6":"notPresent", "7":"lowerLayerDown"} )

     - context: log
        conditions:
          - log.attributes["ifAdminStatus"] != nil
        statements:
          - set(
              log.attributes["ifAdminStatusMapped"],
              resource.attributes["___"]["mapper_ifAdminStatus"][String(log.attributes["ifAdminStatus"])]
            )

      - context: log
        conditions:
          - log.attributes["ifOperStatus"] != nil
        statements:
          - set(
              log.attributes["ifOperStatusMapped"],
              resource.attributes["___"]["mapper_ifOperStatus"][String(log.attributes["ifOperStatus"])]
            )

      - context: resource
        statements:
          - delete_key(resource.attributes, "___")
```
**I am all ears on how to do this better 

That all being said - I think it would be very advantageous to have a global cache to store variables upon config initialization.
I would then envision being able to write something like this:
```
   transform:

    log_statements:
    
      - context: global
        statements:
          - set(global.cache["mapper_ifAdminStatus"], {"1":"up", "2":"down", "3":"testing"} )
          - set(global.cache["mapper_ifOperStatus"], {"1":"up", "2":"down", "3":"testing", "4":"unknown", "5":"dormant", "6":"notPresent", "7":"lowerLayerDown"} )

     - context: log
        conditions:
          - log.attributes["ifAdminStatus"] != nil
        statements:
          - set(
              log.attributes["ifAdminStatusMapped"],
              global.cache["mapper_ifAdminStatus"][String(log.attributes["ifAdminStatus"])]
            )

      - context: log
        conditions:
          - log.attributes["ifOperStatus"] != nil
        statements:
          - set(
              log.attributes["ifOperStatusMapped"],
              global.cache["mapper_ifOperStatus"][String(log.attributes["ifOperStatus"])]
            )

```

**Comment by edmocosta** [comment]
Another similar option would be supporting some kind of `constants` path at root configuration level, so we could allow setting "any" kind of constant values, not only maps, for example:

```yaml
transform:
  constants:
    ifAdminStatusAttribute: "ifAdminStatus" 
    ifAdminStatusTable:
      "1": "up"
      "2": "down"
      "3": "testing"
    commonLabels:
      - "production"
      - "env:prod" 
  log_statements:
     - set(log.attributes[constants.ifAdminStatusAttribute], constants.ifAdminStatusTable[String(log.attributes[constants.ifAdminStatusAttribute])]) where log.attributes[constants.ifAdminStatusAttribute] != nil
     - set(log.attributes["labels"], constants.commonLabels)
  trace_statements:
    - set(span.attributes["labels"], constants.commonLabels)
```
