### ISSUE TITLE
[pkg/ottl] Add support to use `scope` as an OTTL path context name

### ISSUE THREAD

**Issue by edmocosta** [open-telemetry/opentelemetry-collector-contrib#39308]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

The `EnablePathContextNames` currently only adds the legacy `instrumentation_scope` to the allowed path prefix, which does not allows expressing statements like: 

```yaml
log_statements:
 - statements:
    - set(log.attributes["foo"], "foo") where scope.name != nil
```

Instead, it must be written as following, which IMO is okay, but a bit confusing considering the transform processor for example, does not have such context name available anymore:

```yaml
log_statements:
 - statements:
    - set(log.attributes["foo"], "foo") where instrumentation_scope.name != nil
```

### Describe the solution you'd like

Given both contexts names `scope` and the legacy `instrumentation_scope` are (internally) interchangeable,  it would be nice to allow the usage of the `scope` context as well in the relevant top contexts, so users wouldn't be forced to use the `instrumentation_scope` .
