### ISSUE TITLE
[operators/router] A valid expression for expr-lang return invalid operation error

### ISSUE THREAD

**Issue by kuisathaverat** [open-telemetry/opentelemetry-collector-contrib#39337]
### Component(s)

operators/router

## Description

Testing to usinf the operator `router` we found that a valid expression for the library [expr-lang](https://github.com/expr-lang/expr/blob/master/docs/language-definition.md) return am `invalid operation` error.
it is a `not` expression, we tested `not()` and `!()` both return the same error.

We validate the expression with https://go.dev/play/ using the following code:

```Go
package main

import (
	"fmt"

	"github.com/expr-lang/expr"
)

func main() {
	env := map[string]interface{}{
		"text":    `10.1.38.154 - - [03/Apr/2025:12:07:14 +0000] "GET / HTTP/1.1" 500 2431`,
		"output":  "%v",
		"sprintf": fmt.Sprintf,
	}

	// code := `sprintf(output, not(text matches "^\\[.*") )`
	code := `sprintf(output, !(text matches "^\\[.*") )`

	program, err := expr.Compile(code, expr.Env(env))
	if err != nil {
		panic(err)
	}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}

	fmt.Println(output)
}
```

And this is the snipet configuration for the collector.

```yaml
    filelog:
      include:
        - /var/log/pods/*_apache*/*/*.log
      start_at: end
      operators:
        # Operator to parse the container logs
        - type: container
          id: container-parser
        - id: choose-operator
          type: router
          routes:
            - output: add-attribute
              expr: '!(body-message matches "^\\[.*")'
          default: noop
        - id: add-attribute
          type: add
          field: attributes.test
          value: match
        - id: noop
          type: noop
```

The OpenTelemetry collector returns the following warning (but is an error) and ignore the route.

```log
2025-04-11T11:15:46.517Z        warn    router/transformer.go:66        Running expression returned an error    {"operator_id": "choose-operator", "operator_type": "router", "entry.timestamp": "2025-04-11T11:15:46.514Z", "log.file.path": "/var/log/pods/default_apache-7b8dc8dc56-64ql5_99e72b40-8604-4fbc-b517-3b9be2401d00/apache/0.log", "log.iostream": "stdout", "logtag": "F", "error": "invalid operation: string - <nil> (1:7)\n | !(body-message matches \"^\\\\[.*\")\n | ......^"}
```

```log
2025-04-11T11:35:45.451Z        warn    router/transformer.go:66        Running expression returned an error    {"operator_id": "choose-operator", "operator_type": "router", "entry.timestamp": "2025-04-11T11:35:45.335Z", "log.iostream": "stdout", "logtag": "F", "log.file.path": "/var/log/pods/default_apache-7b8dc8dc56-mjg6t_10a61802-2841-4492-850d-d5cec6801b51/apache/0.log", "error": "invalid operation: string - <nil> (1:9)\n | not(body-message matches \"^\\\\[.*\")\n | ........^"}
```

## Steps to Reproduce

I provide a test case that deploys Wordpress and the collector in a k8s cluster.

* Create a k8s cluster
* deploy Apache and the Collector
```shell
git clone https://github.com/kuisathaverat/otel-playground.git 
cd otel-playground
make -C test-routes deploy
```
* Verify the logs for the error

## Expected Result

The expression should be evaluated without error.

## Actual Result

The OpenTelemetry collector returns the following warning (but it is an error) and ignores the route.

```log
2025-04-11T11:15:46.517Z        warn    router/transformer.go:66        Running expression returned an error    {"operator_id": "choose-operator", "operator_type": "router", "entry.timestamp": "2025-04-11T11:15:46.514Z", "log.file.path": "/var/log/pods/default_apache-7b8dc8dc56-64ql5_99e72b40-8604-4fbc-b517-3b9be2401d00/apache/0.log", "log.iostream": "stdout", "logtag": "F", "error": "invalid operation: string - <nil> (1:7)\n | !(body-message matches \"^\\\\[.*\")\n | ......^"}
```

### Collector version

v0.123.0

## Environment
OS: k8s

### OpenTelemetry Collector configuration

```yaml
exporters:
  # Debug exporter to see the logs in the console
  debug:
    verbosity: detailed
extensions:
  # Health check extension to check the health of the collector
  health_check:
    endpoint: ${env:MY_POD_IP}:13133
receivers:
  # Receiver to read the Apache logs
  filelog:
    include:
      - /var/log/pods/*_apache*/*/*.log
    start_at: end
    operators:
      # Operator to parse the container logs
      - type: container
        id: container-parser
      - id: choose-operator
        type: router
        routes:
          - output: add-attribute
            expr: '!(body-message matches "^\\[.*")'
        default: noop
      - id: add-attribute
        type: add
        field: attributes.test
        value: match
      - id: noop
        type: noop
# Disable the default receivers
  prometheus: null
  zipkin: null
service:
  # disable the default telemetry
  telemetry: {}
  # enable the Health check extension
  extensions: [health_check]
  # pipelines to process the logs
  pipelines:
    # disable the default pipelines
    metrics: null
    traces: null
    # pipeline to process the logs
    logs:
      receivers:
        - filelog
      processors:
        - batch
      exporters:
        - debug
```

### Log output

```shell
2025-04-11T11:15:46.517Z        warn    router/transformer.go:66        Running expression returned an error    {"operator_id": "choose-operator", "operator_type": "router", "entry.timestamp": "2025-04-11T11:15:46.514Z", "log.file.path": "/var/log/pods/default_apache-7b8dc8dc56-64ql5_99e72b40-8604-4fbc-b517-3b9be2401d00/apache/0.log", "log.iostream": "stdout", "logtag": "F", "error": "invalid operation: string - <nil> (1:7)\n | !(body-message matches \"^\\\\[.*\")\n | ......^"}

2025-04-11T11:35:45.451Z        warn    router/transformer.go:66        Running expression returned an error    {"operator_id": "choose-operator", "operator_type": "router", "entry.timestamp": "2025-04-11T11:35:45.335Z", "log.iostream": "stdout", "logtag": "F", "log.file.path": "/var/log/pods/default_apache-7b8dc8dc56-mjg6t_10a61802-2841-4492-850d-d5cec6801b51/apache/0.log", "error": "invalid operation: string - <nil> (1:9)\n | not(body-message matches \"^\\\\[.*\")\n | ........^"}
```

**Comment by andrzej-stencel** [comment]
The problem is `body-message`. Did you mean `body.message`? Actually looking at your config, you are dealing with logs from Kubernetes logs parsed by the `container` operator. In that case, `body` is a string that contains the log message. Can you change the expression to `'!(body matches "^\\[.*")'` and let me know how this works?

**Comment by kuisathaverat** [comment]
Yes, I meant `body.message`, I copied it wrong from the original scenario I am using. I changed it, and the error disappeared, but it did nothing. Checking the examples, I found all uses `body.message` that's why I am using it, it is not clear for me if the attributes are available after each operator or at the end of all operators. For example, `body.text` is available in the final object but not during the process or executing all operators.

**Comment by kuisathaverat** [comment]
I changed it to body and added an attribute with the message to debug what is evaluated in the router operator. I not sure why it does not match. It should add an extra attribute `attributes.test: match` but it is not added.

```yaml
      operators:
        # Operator to parse the container logs
        - type: container
          id: container-parser
        - id: add-attribute-00
          type: add
          field: attributes.msg
          value: EXPR(body)
        - id: choose-operator
          type: router
          routes:
            - output: add-attribute
              expr: 'not(body matches "^\\[.*")'
          default: noop
        - id: add-attribute
          type: add
          field: attributes.test
          value: match
        - id: noop
          type: noop
```
for the body `10.1.47.1 - - [11/Apr/2025:14:50:07 +0000] "GET / HTTP/1.1" 200 45` with the expression `not(body matches "^\\[.*")`

```log

2025-04-11T14:50:07.718Z        info    Logs    {"resource logs": 1, "log records": 1}
2025-04-11T14:50:07.720Z        info    ResourceLog #0
Resource SchemaURL: 
Resource attributes:
     -> k8s.container.name: Str(apache)
     -> k8s.namespace.name: Str(default)
     -> k8s.pod.name: Str(apache-7b8dc8dc56-mq2hr)
     -> k8s.container.restart_count: Str(0)
     -> k8s.pod.uid: Str(a12ab6e3-c44a-4064-aba9-1767ab7f428a)
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope  
LogRecord #0
ObservedTimestamp: 2025-04-11 14:50:07.560388218 +0000 UTC
Timestamp: 2025-04-11 14:50:07.491506232 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Str(10.1.47.1 - - [11/Apr/2025:14:50:07 +0000] "GET / HTTP/1.1" 200 45)
Attributes:
     -> logtag: Str(F)
     -> msg: Str(10.1.47.1 - - [11/Apr/2025:14:50:07 +0000] "GET / HTTP/1.1" 200 45)
     -> test: Str(match)
     -> log.file.path: Str(/var/log/pods/default_apache-7b8dc8dc56-mq2hr_a12ab6e3-c44a-4064-aba9-1767ab7f428a/apache/0.log)
     -> log.iostream: Str(stdout)
Trace ID: 
Span ID: 
Flags: 0
```

In https://go.dev/play/ the expression for the same body evaluates to `true` 

```Go
package main

import (
	"fmt"

	"github.com/expr-lang/expr"
)

func main() {
	env := map[string]interface{}{
		"body":    `10.1.47.1 - - [11/Apr/2025:14:50:07 +0000] "GET / HTTP/1.1" 200 45`,
		"output":  "%v",
		"sprintf": fmt.Sprintf,
	}

	code := `sprintf(output, not(body matches "^\\[.*"))`

	program, err := expr.Compile(code, expr.Env(env))
	if err != nil {
		panic(err)
	}

	output, err := expr.Run(program, env)
	if err != nil {
		panic(err)
	}

	fmt.Println(output)
}
```

**Comment by kuisathaverat** [comment]
I just added the expression also as an attribute to check the value, and it is true. I do not get why router does not go to the operator `add-attribute`

```yaml
      operators:
        # Operator to parse the container logs
        - type: container
          id: container-parser
        - id: add-attribute-00
          type: add
          field: attributes.msg
          value: EXPR(body)
        - id: add-attribute-01
          type: add
          field: attributes.expr
          value: EXPR(not(body matches "^\\[.*"))
        - id: choose-operator
          type: router
          routes:
            - output: add-attribute
              expr: 'not(body matches "^\\[.*")'
          default: noop
        - id: add-attribute
          type: add
          field: attributes.test
          value: match
        - id: noop
          type: noop
```

```log
2025-04-11T14:59:02.928Z        info    Logs    {"resource logs": 1, "log records": 1}
2025-04-11T14:59:02.928Z        info    ResourceLog #0
Resource SchemaURL: 
Resource attributes:
     -> k8s.pod.uid: Str(6ff079f6-8f67-4900-a684-0eef2e118cf1)
     -> k8s.container.name: Str(apache)
     -> k8s.namespace.name: Str(default)
     -> k8s.pod.name: Str(apache-7b8dc8dc56-trpzr)
     -> k8s.container.restart_count: Str(0)
ScopeLogs #0
ScopeLogs SchemaURL: 
InstrumentationScope  
LogRecord #0
ObservedTimestamp: 2025-04-11 14:59:02.627892166 +0000 UTC
Timestamp: 2025-04-11 14:59:02.587253662 +0000 UTC
SeverityText: 
SeverityNumber: Unspecified(0)
Body: Str(10.1.47.1 - - [11/Apr/2025:14:59:02 +0000] "GET / HTTP/1.1" 200 45)
Attributes:
     -> log.iostream: Str(stdout)
     -> msg: Str(10.1.47.1 - - [11/Apr/2025:14:59:02 +0000] "GET / HTTP/1.1" 200 45)
     -> expr: Bool(true)
     -> test: Str(match)
     -> log.file.path: Str(/var/log/pods/default_apache-7b8dc8dc56-trpzr_6ff079f6-8f67-4900-a684-0eef2e118cf1/apache/0.log)
     -> logtag: Str(F)
Trace ID: 
Span ID: 
Flags: 0
```
