### ISSUE TITLE
ACL requirement for AWS S3 Exporter was a breaking change listed as Enhancement

### ISSUE THREAD

**Issue by Erog38** [open-telemetry/opentelemetry-collector-contrib#39346]
### Component(s)

exporter/awss3

## Description

Starting in [v0.121.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.121.0) Users are required to provide a valid ACL for bucket access. Many existing buckets don't support ACLs as a default. This means that we see errors as listed in the logs provided.

This will require a bucket configuration change and a collector change and as such needs to be mentioned as a breaking change. 

## Steps to Reproduce

1. Have or create S3 bucket without ACL support

2. Use provided configuration in any vanilla collector

3. Then use a tool such as `telemetrygen` to send: 

```bash
telemetrygen logs \
    --duration 10m \
    --otlp-endpoint localhost:4317 \
    --otlp-insecure \
    --rate 100
```

## Expected Result

Logs to show up in AWS S3

## Actual Result

Error logs as attached.

### Collector version

v0.123.0

### OpenTelemetry Collector configuration

```yaml
receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
processors:
    batch:
        timeout: 10s
      memory_limiter:
        limit_percentage: 80
exporters:
      awss3
        s3uploader:
          region: us-east-1
          compression: gzip
          s3_bucket: $BUCKET
          s3_prefix: "some-prefix"
          role_arn: valid-arn
service:
    telemetry:
        pipelines:
            logs:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [awss3]
```

### Log output

```shell
Exporting failed. Rejecting data. Try enabling sending_queue to survive temporary failures.
operation error S3: PutObject, https response error StatusCode: 400, RequestID: XXX, HostID: XXX, api error AccessControlListNotSupported: The bucket does not allow ACLs
Sender failed
operation error S3: PutObject, https response error StatusCode: 400, RequestID: XXX, HostID: XXX, api error AccessControlListNotSupported: The bucket does not allow ACLs
```
