### ISSUE TITLE
🐞 Potential Bug with filter Processor in otel/opentelemetry-collector-contrib

### ISSUE THREAD

**Issue by fabriciodf** [open-telemetry/opentelemetry-collector-contrib#39466]
### Component(s)

processor/filter

### What happened?

✅ How to Reproduce
test.sh
```bash
#!/bin/bash
# This script sends 1 current metric and 1 expired metric

CURRENT_TIME=$(date +%s000000000)  # Current timestamp in nanos
EXPIRED_TIME=$((CURRENT_TIME - 39*60*1000000000))  # 39 minutes ago

curl -X POST http://localhost:4318/v1/metrics \
  -H "Content-Type: application/json" \
  -d '{
    "resourceMetrics": [{
      "scopeMetrics": [{
        "metrics": [
          {
            "name": "valid.metric",
            "sum": {
              "dataPoints": [{
                "timeUnixNano": "'"$CURRENT_TIME"'",
                "asInt": 100,
                "attributes": [{"key": "status", "value": {"stringValue": "current"}}]
              }]
            }
          },
          {
            "name": "expired.metric",
            "sum": {
              "dataPoints": [{
                "timeUnixNano": "'"$EXPIRED_TIME"'",
                "asInt": 50,
                "attributes": [{"key": "status", "value": {"stringValue": "expired"}}]
              }]
            }
          }
        ]
      }]
    }]
  }'
```

otel-collector-config.yaml
```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  filter/drop_old_metrics:
    error_mode: ignore
    metrics:
      datapoint:
        - 'time_unix_nano < UnixNano(Now()) - 1800000000000' # 30 minutes in nanoseconds

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [filter/drop_old_metrics]
      exporters: [debug]
```

🧪 Run with Docker
```bash
# Using core image (works as expected)
docker run --rm -it \
  -v "$(pwd)/otel-collector-config.yaml":/etc/otelcol/config.yaml \
  -p 4318:4318 \
  otel/opentelemetry-collector:latest
```
# Using contrib image (filter fails)
```bash
docker run --rm -it \
  -v "$(pwd)/otel-collector-config.yaml":/etc/otelcol/config.yaml \
  -p 4318:4318 \
  otel/opentelemetry-collector-contrib:latest
```

✅ Expected Behavior (core image)
The expired metric is filtered out correctly:

```
2025-04-17T01:14:10.954Z        info    Metrics {"resource metrics": 1, "metrics": 1, "data points": 1}
...
-> Name: valid.metric
...
Timestamp: 2025-04-17 01:14:10 +0000 UTC
Value: 100
```
❌ Unexpected Behavior (contrib image)
Both metrics are exported — the filter does not seem to take effect:

```
2025-04-17T01:14:48.931Z        info    Metrics {"resource metrics": 1, "metrics": 2, "data points": 2}
...
-> Name: valid.metric
Timestamp: 2025-04-17 01:14:48 +0000 UTC
Value: 100

-> Name: expired.metric
Timestamp: 2025-04-17 00:35:48 +0000 UTC
Value: 50
```

🔎 Notes

Same configuration file used for both runs.

The issue appears only when using the contrib image (otel/opentelemetry-collector-contrib).

It appears that the UnixNano(Now()) comparison is not being properly evaluated in the contrib distribution.

Thanks in advance for checking this! Let me know if I can help reproduce it further or test a fix. 🙏

### Collector version

v0.123.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```
