### ISSUE TITLE
basic auth doesnt work properly in latest k8s otelcollector

### ISSUE THREAD

**Issue by arik-pillar** [open-telemetry/opentelemetry-collector-contrib#39461]
### Component(s)

cmd/otelcontribcol

## Description
I'm using open-telemetry/opentelemetry-collector helm chart on EKS
## Steps to Reproduce
Deploy the helm chart with the provided config (that sets up basicauth extension)
Add a sample inline `admin:test` creds to allow
Send an http test trace to the otelcol receiver with the `admin:test` (stringifed as base64) creds in the Authorization header (Basic YWRtaW46dGVzdA==)
## Expected Result
The trace should pass (status 200)
## Actual Result
The trace is blocked (status 401 with 'Unauthorized' message)

### Collector version

otel/opentelemetry-collector-k8s 0.123.0 

## Environment
OS: EKS 1.31, running amazon linux ec2 instances

### OpenTelemetry Collector configuration

```yaml
# values.yaml

mode: deployment
  
config:
  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"
    basicauth/server:
      htpasswd: 
        inline: |
          admin:test
        
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:                           
          endpoint: "0.0.0.0:4318"
          auth:
            authenticator: basicauth/server
    otlp/noauth: # only open internally
      protocols:
        http:
          endpoint: "0.0.0.0:4319"  # Using a different port

    
  service:
    telemetry:
      logs:
        level: "debug"
      metrics:
        address: "0.0.0.0:8888"
    extensions:
      - health_check
      - basicauth/server

    pipelines:
      logs:
        exporters:
          - debug
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - otlp/noauth
      metrics:
        exporters:
          - debug
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - otlp/noauth
          - prometheus
      traces:
        exporters:
          - debug
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - otlp/noauth

image:
  repository: "otel/opentelemetry-collector-k8s"
  pullPolicy: IfNotPresent
  tag: "0.123.0"
  digest: ""
imagePullSecrets: []
```

### Log output

```shell

```

### Additional context

Send a test trace:
POST https://otel..your.domain/v1/traces
Headers:
Content-type: application/json
Authorization: Basic YWRtaW46dGVzdA==
Body:
{
  "resource_spans": [
    {
      "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": { "string_value": "example-service" }
          }
        ]
      },
      "instrumentation_library_spans": [
        {
          "instrumentation_library": {
            "name": "example-library",
            "version": "1.0"
          },
          "spans": [
            {
              "trace_id": "00000000000000000000000000000001",
              "span_id": "0000000000000001",
              "name": "http-request",
              "kind": 1,
              "start_time": "2025-04-15T12:00:00.000Z",
              "end_time": "2025-04-15T12:00:05.000Z",
              "attributes": [
                {
                  "key": "http.url",
                  "value": { "string_value": "https://httpbin.org/get" }
                },
                {
                  "key": "http.status_code",
                  "value": { "int_value": 200 }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
