### ISSUE TITLE
Azure blob many small files. No append?

### ISSUE THREAD

**Issue by JelleSmet-TomTom** [open-telemetry/opentelemetry-collector-contrib#39475]
### Component(s)

exporter/azureblob

### Describe the issue you're reporting

Hi,
First of all thanks for the azureblob exporter. A truly useful exporter for my use case.
I am able to successfully export my logs to blob storage ... however the problem I enounter is that my logs end up in many small files ... sometimes even a log per file. This yields into an impossible amount of files to work with.

My config is very vanilla and looks like this:

```
      azureblob:
        url: "https://xxxxxxxx.blob.core.windows.net/"
        container:
          logs: "logs2"
        auth:
          type: "connection_string"
          connection_string: "xxxxxxxxxxxxxxxxxxx"
        append_blob:
          enabled: true
          separator: "\n"
```
Prior to this exporter I have put a batch processor thinking it would solve this issue and pack more logs into a single file but it does not help:
```
      batch/azure:
        send_batch_size: 4096
        send_batch_max_size: 8192
        timeout: 60000
```

I kind of expected `append_blob` to tackle this exact problem but that does not seem to be the case.
Any help would be appreciated

For reference:

![Image](https://github.com/user-attachments/assets/0cd2c3bf-bc73-4558-9dff-86d21054b2ee)

Sincerely,
