### ISSUE TITLE
`Unset` should not bet set as a value for `status.code`

### ISSUE THREAD

**Issue by smith** [open-telemetry/opentelemetry-collector-contrib#39498]
### Component(s)

exporter/elasticsearch

## Description

When the exporter exports spans, [sets `status.code` to the string value of the status code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/elasticsearchexporter/internal/serializer/otelserializer/traces.go#L75).

[OpenTelemetry Transformation to non-OTLP Formats](https://opentelemetry.io/docs/specs/otel/common/mapping-to-non-otlp/#span-status) specifies:

> Span Status MUST be reported as key-value pairs associated with the Span, unless the Status is UNSET. In the latter case it MUST NOT be reported.

## Steps to Reproduce

Run the otel demo and export traces with the exporter

## Expected Result

`FROM traces-* where status.code == "Unset"` returns no results.

## Actual Result

`FROM traces-* where status.code == "Unset"` returns many spans with `"Unset"` for the status code.

### Collector version

v0.121.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  elasticsearch/otel:
    endpoints: ["${env:ELASTIC_ENDPOINT}"]
    api_key: ${env:ELASTIC_API_KEY}
    mapping:
      mode: otel
    logs_dynamic_index:
      enabled: true
    metrics_dynamic_index:
      enabled: true
    traces_dynamic_index:
      enabled: true
    sending_queue:
      enabled: true
    tls:
      ca_file: /usr/share/elastic-agent/config/certs/ca/ca.crt
      insecure_skip_verify: true
```

### Log output

```shell

```
