### ISSUE TITLE
How to use the new Azure Authentication feature with Event Hub as receiver?

### ISSUE THREAD

**Issue by TomEijk** [open-telemetry/opentelemetry-collector-contrib#39496]
### Describe the issue you're reporting

Hi,

I want wondering how to modify the Azure Event Hub as receiver: 

```
receivers:
  azureeventhub:
    connection: Endpoint=sb://namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=superSecret1234=;EntityPath=hubName
    partition: foo
    group: bar
    offset: "1234-5566"
    format: "azure"
    # optional
    time_formats:
      # All supported time format. Default is empty string array, which means using the current iso8601 parser. The format is based on https://pkg.go.dev/time#Layout. If no time-zone info, will use UTC time.
      logs: ["01/02/2006 15:04:05","2006-01-02 15:04:05","2006-01-02T15:04:05Z07:00"]
      metrics: ["01/02/2006 15:04:05"]
```

To work with the new Azure Authentication extension in the latest release:

```
    extensions:
      azureauth:
        service_principal:
          client_id: ${CLIENT_ID}
          tenant_id: ${TENANT_ID}
          client_secret: ${CLIENT_SECRET}
```

How to point to the correct Event Hub namespace and Event Hub name for example?

**Comment by TomEijk** [comment]
Hmm the `azureauth` extension also doesn't seem to be available in the new splunk-otel-collector (`0.124.0`) yet:

```
error decoding 'extensions': unknown type: "azureauth" for id: "azureauth" (valid values: [opamp basicauth docker_observer ecs_task_observer http_forwarder ack ecs_observer host_observer k8s_observer oauth2client file_storage headers_setter pprof smartagent zpages bearertokenauth health_check])

```

**Comment by constanca-m** [comment]
Hi @TomEijk , at the moment the components (azure auth and azure monitor receiver) are not compatible with each other, since `azuremonitorreceiver` does not support auth extension in the config ([source code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c2e12729a13e4cef07b503fede311cb8c8942af9/receiver/azuremonitorreceiver/config.go#L239-L259)).

I have created https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39048 to add support for this. I did not have time to look at it, but I will try to pick it up again soon.

**Comment by TomEijk** [comment]
Hi @constanca-m ! Thank you for your reply! I actually meant `azureeventhub` but I think the same holds for that component?

**Comment by constanca-m** [comment]
> but I think the same holds for that component?


Yes, you are correct. Currently no components support the `azureauth`. I have opened a [PR today ](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39574)to bump the stability to alpha, so the extension is available in the next release. Then we can start adding it in the configuration of the receivers.

**Comment by TomEijk** [comment]
Cool! Thanks, I'll closely monitor the upcoming releases in that case :)

**Comment by illrill** [comment]
+1, would love to see this for `azureeventhubreceiver`, similar to how #39658 did it for `azuremonitorreceiver` 👍

**Comment by constanca-m** [comment]
I don't mind helping or even making the changes on the receiver, but I would need the `azureeventhubreceiver` codeowners approval on moving this.

**Comment by cparkins** [comment]
@constanca-m I have no concerns with updating the code to support the Azure Auth Extension.

**Comment by illrill** [comment]
Assuming the pseudo logic will be "if `azureeventhub.auth != nil`, then ignore `azureeventhub.connection`"

```
receivers:
  azureeventhub:
    name: ...
    namespace: ...
    auth:
      authenticator: azureauth
extensions::
  azureauth:
    workload_identity:
      tenant_id: "${AZURE_TENANT_ID}"
      client_id: "${AZURE_CLIENT_ID}"
```

Should `azureeventhub.connection` still be supported, or marked as deprecated?
