### ISSUE TITLE
Azureblob Exporter: Blob names include serial number after .json instead of before, breaking file extension

### ISSUE THREAD

**Issue by gous1924** [open-telemetry/opentelemetry-collector-contrib#39593]
### Component(s)

exporter/azureblob

## Description

When using the Azure Blob Exporter, the generated blob names append the serial number after the file extension (e.g. .json_3535), resulting in an invalid or misleading file extension.

## Steps to Reproduce

1. Use opentelemetry-collector-contrib:0.124.1 as the base image.
2. Add the below azureblob exporter configuration.

## Expected Result

`logs/2024/04/15/logs_15_04_05_3742.json`

## Actual Result

`logs/2024/04/15/logs_15_04_05.json_3742`

### Collector version

0.124.1

### OpenTelemetry Collector configuration

```yaml
exporters:
  azureblob:
    auth:
      type: "connection_string"
      connection_string: "DefaultEndpointsProtocol=https;AccountName=$(AZURE_STORAGE_ACCOUNT);AccountKey=$(AZURE_STORAGE_ACCESS_KEY);EndpointSuffix=core.windows.net"
```

### Log output

```shell

```
