### ISSUE TITLE
Prometheusremotewrite send_metadata not working

### ISSUE THREAD

**Issue by bote795** [open-telemetry/opentelemetry-collector-contrib#39591]
### Component(s)

exporter/prometheusremotewrite

### What happened?

## Description

Hi,
I am trying to send the Datatype and description of metric types via exporter prometheusremotewrite
I have enabled `send_metadata: true` but I don't see any changes.

I have added the logging exporter and do see the DataType:
```
Metric #17                                                                                                                                                                                                                                                                 │
│ Descriptor:                                                                                                                                                                                                                                                                │
│      -> Name: airflow_executor_running_tasks                                                                                                                                                                                                                               │
│      -> Description: Metric autogenerated by statsd_exporter.                                                                                                                                                                                                              │
│      -> Unit:                                                                                                                                                                                                                                                              │
│      -> DataType: Gauge     
```


## Steps to Reproduce

Sample config:

example of my exporter
```
│   prometheusremotewrite/cm9sntm27000j01o9am2kjyho-testMimi:                                                                                                                                                                                                                
│     endpoint: http://load-balancer.play-with-grafana-mimir.orb.local/api/v1/push                                                                                                                                                                                           
│     headers:                                                                                                                                                                                                                                                               
│         "X-Scope-OrgID": "demo"                                                                                                                                                                                                                                            
│     target_info:                                                                                                                                                                                                                                                           
│       enabled: false                                                                                                                                                                                                                                                       
│     send_metadata: true
```


pipeline:
```
│   pipelines:                                                                                                                                                                                                                                                               │
│     metrics/cm9sntm27000j01o9am2kjyho-testMimi:                                                                                                                                                                                                                            
│       exporters:                                                                                                                                                                                                                                                           
│       - prometheusremotewrite/cm9sntm27000j01o9am2kjyho-testMimi                                                                                                                                                                                                           
│       processors:                                                                                                                                                                                                                                                          
│       receivers:                                                                                                                                                                                                                                                           
│       - prometheus/cm9sntm27000j01o9am2kjyho-testMimi    
```

```
receiver
  prometheus/cm9sntm27000j01o9am2kjyho-testMimi:
    config:
      scrape_configs:
      - job_name: airflow_collector
        kubernetes_sd_configs:
        - role: service
        metric_relabel_configs:
        - action: keep
          regex: (airflow.*)
          source_labels:
          - __name__
        relabel_configs:
        - action: keep
          regex: cm9sntm27000j01o9am2kjyho
          source_labels:
          - __meta_kubernetes_service_label_deployment_id
        - action: keep
          regex: airflow
          source_labels:
          - __meta_kubernetes_service_label_app
        - action: keep
          regex: statsd
          source_labels:
          - __meta_kubernetes_service_label_component
        - action: keep
          regex: TCP
          source_labels:
          - __meta_kubernetes_service_port_protocol
        - source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
```

## Expected Result
expect Type to be filled in the metrics explorer

## Actual Result

![Image](https://github.com/user-attachments/assets/927b38eb-86b5-4968-bce2-a49552ee6360)

### Collector version

v0.99.0

### Environment information

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")


### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell
Metric #17                                                                                                                                                                                                                                                                 │
│ Descriptor:                                                                                                                                                                                                                                                                │
│      -> Name: airflow_executor_running_tasks                                                                                                                                                                                                                               │
│      -> Description: Metric autogenerated by statsd_exporter.                                                                                                                                                                                                              │
│      -> Unit:                                                                                                                                                                                                                                                              │
│      -> DataType: Gauge
```

### Additional context

_No response_
