### ISSUE TITLE
Add apachespark scraping by application id

### ISSUE THREAD

**Issue by NN---** [open-telemetry/opentelemetry-collector-contrib#39627]
### Is your feature request related to a problem? Please describe.

It is possible to scrape by application name but not by id.

### Describe the solution you'd like

```yaml
  apachespark:
    collection_interval: 60s
    endpoint: http://spark:4040
    application_ids:
      - "spark-1234"
```
