### ISSUE TITLE
[receiver/apachespark] Apache Spark Receiver doesn't work with ending slash in the endpoint

### ISSUE THREAD

**Issue by NN---** [open-telemetry/opentelemetry-collector-contrib#39620]
## Description
The code does not remove the last slash if appears in endpoint and Spark server has a distinction between '/api' and '//api'.

## Steps to Reproduce
Configure receiver with slash:
```yml
  apachespark:
    collection_interval: 60s
    endpoint: http://sparkserver/
```

## Expected Result
Receiver fetches metrics.

## Actual Result
Error, character '<' is unexpected

### Collector version

OpenTelemetry 1.32

## Environment
Ubuntu 22.04

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14317
      http:
        endpoint: 0.0.0.0:14318
  apachespark:
    collection_interval: 60s
    endpoint: http://history.rnd.speedata.io

service:
  pipelines:
    metrics:
      receivers: [apachespark]
      exporters: [debug]
```

### Log output

```shell

```
