### ISSUE TITLE
[exporter/elasticsearch] retry setting not take effect after the es down

### ISSUE THREAD

**Issue by ChrisYe2015** [open-telemetry/opentelemetry-collector-contrib#39670]
### Component(s)

exporter/elasticsearch

## Description
I use exporter's persistent queue to ensure that logs are not lost when es is offline,
My collection solution is ： opentelemetry sdk->collector(use elasticsearch exporter)->elasticsearch
I configured sending_queue, but found that retry_on_failure does not work in elasticsearch exporter, so I configured retry
after es is offline and restarted, the logs are not retried as expected but lost, and use retry_on_failure for otlp jaeger can work.
Please help me see if there is a problem with the configuration or how to ensure that log not lost
## Steps to Reproduce
1. docker stop es
2. send request for generate logs for collector
3. after at least 10 min then docker start es
## Expected Result
es will collect logs of requests during service offline
## Actual Result
no collect and log loss

### Collector version

v0.123.0

## Environment
linux docker

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  docker_stats:
    endpoint: unix:///var/run/docker.sock

exporters:
  debug:
  #verbosity: detailed
  otlp:
    endpoint: "jaeger:8027"
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 168h
      max_elapsed_time: 168h
    sending_queue:
      enabled: true
      storage: file_storage/otlp
      queue_size: 1073741824
  elasticsearch:
    tls:
      insecure: false
    endpoints: ["xxxx:8011"] 
    logstash_format:
      enabled: true
    timeout: 2m
    discover:
      on_start: true
      interval: 5
    retry:
      enabled: true
      max_retries: 100000
      initial_interval: 5s
      max_interval: 168h
      retry_on_status:
        - 429
        - 500
        - 502
        - 503
        - 504
    flush:
      bytes: 10485760
    sending_queue:
      enabled: true
      storage: file_storage/es
      queue_size: 1073741824

extensions:
  file_storage/es:
    directory: /var/lib/storage/es
    timeout: 10s
  file_storage/otlp:
    directory: /var/lib/storage/otlp
    timeout: 10s

service:
  extensions: [file_storage/es, file_storage/otlp]
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]
```

### Log output

```shell
2025-04-26T03:23:17.302Z        debug   elasticsearchexporter@v0.123.0/esclient.go:71   Request failed. {"reason": "dial tcp xxxx:8011: connect: connection refused"}
2025-04-26T03:23:18.239Z        debug   elasticsearchexporter@v0.123.0/esclient.go:71   Request failed. {"reason": "dial tcp xxxx:8011: connect: connection refused"}
2025-04-26T03:23:57.171Z        error   elasticsearchexporter@v0.123.0/bulkindexer.go:348       bulk indexer flush error        {"error": "failed to execute the request: context deadline exceeded"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.flushBulkIndexer
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:348
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*asyncBulkIndexerWorker).flush
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:331
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*asyncBulkIndexerWorker).run
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:324
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newAsyncBulkIndexer.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:217
2025-04-26T03:23:57.172Z        error   elasticsearchexporter@v0.123.0/bulkindexer.go:348       bulk indexer flush error        {"error": "failed to execute the request: context deadline exceeded"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.flushBulkIndexer
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:348
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*asyncBulkIndexerWorker).flush
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:331
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.(*asyncBulkIndexerWorker).run
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:324
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter.newAsyncBulkIndexer.func1
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter@v0.123.0/bulkindexer.go:217
```

**Comment by carsonip** [comment]
Thanks for creating an issue. Your collector config looks good. This will need to be investigated.

**Comment by ChrisYe2015** [comment]
@carsonip  Thanks for reply！ 
This is similar to this question：https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/39779
 Could it be that the ES exporter has a problem judging the ES service being offline?

**Comment by ChrisYe2015** [comment]
Hi @carsonip , i find if enable batcher, must need disable sending_queue ,will retry success afte es down and up.
I'm not sure if this is normal behavior that If a persistent queue is enabled, es down cannot retry successful?

**Comment by carsonip** [comment]
Off the top of my head, I have no idea. Didn't expect the persistent queue to affect how batcher retries work. Can you try it again to confirm?

**Comment by dtomilestone** [comment]
I am experiencing something similar where I have not managed to configure Elasticsearch exporter with a persistent queue (file_storage) that is able to retry for more than a handful of times when ES goes down.

An example scenario I expect to be supported: If Elasticsearch goes down for one hour, any logs sent to the collector should be kept in the persistent queue. The collector should keep retrying to send those logs for as long as it’s configured to do so. Even if the collector is restarted during that hour, the logs must stay in the persistent queue. Once ES comes back online, all the queued logs must be sent to it.

I can confirm that the "exporterhelper" "retry_on_failure" is not supported in the configuration, and we are forced to use "retry" which might be why the current behavior and our expectations are different.

**Comment by lahsivjar** [comment]
> I can confirm that the "exporterhelper" "retry_on_failure" is not supported in the configuration, and we are forced to use "retry" which might be why the current behavior and our expectations are different.

Hmm, it looks like our expoterhelper options don't configure the retry options ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d87ea4c16f98fc9eb157c8599b41523c32ae5746/exporter/elasticsearchexporter/factory.go#L205-L210)). I have been a bit away for a while so I am not sure about the background for this but I will take a look as to why this is not available and if it is just missing it should be a quick job to add the configuration.

**Comment by carsonip** [comment]
@ChrisYe2015 @dtomilestone Thanks for reporting the issue. I got to the bottom of it and found a bug in HTTP request level retries. Bugfix: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41142

With the bugfix and a controller config like this, you should expect the retries to work when ES is down. There should not be any data loss.
```yaml
extensions:
  basicauth:
    client_auth:
      username: elastic
      password: redacted
  file_storage/es:
    directory: ./storage/es
    timeout: 10s
exporters:
  elasticsearch:
    endpoint: redacted
    auth:
      authenticator: basicauth
    timeout: 2m
    batcher:
      enabled: true
      flush_timeout: 1s
    sending_queue:
      enabled: true
      block_on_overflow: true
      queue_size: 10000
    retry:
      enabled: true
      max_retries: 100000
      initial_interval: 5s
      max_interval: 168h
      retry_on_status:
        - 429
        - 500
        - 502
        - 503
        - 504
  debug:
    verbosity: detailed
  nop:
processors:
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

service:
  extensions: [basicauth, file_storage/es]
  pipelines:
    logs:
      exporters:
        - elasticsearch
      processors:
      receivers:
        - otlp
    metrics:
      exporters:
        - elasticsearch
      processors:
      receivers:
        - otlp
    traces:
      exporters:
        - elasticsearch
      processors:
      receivers:
        - otlp
  telemetry:
    logs:
      encoding: json
      level: info
    metrics:
      address: 0.0.0.0:8888
      level: detailed
```
