### ISSUE TITLE
Feature Request: Add Namespace Filtering Support to `k8sobserver` Extension

### ISSUE THREAD

**Issue by Ygshvr** [open-telemetry/opentelemetry-collector-contrib#39677]
### Component(s)

extension/observer/k8sobserver

### Is your feature request related to a problem? Please describe.

The `k8sobserver` extension in the OpenTelemetry Collector's `receiver_creator` is really useful in discovering Kubernetes resources such as pods, services, ingresses, and nodes. However, it currently lacks a built-in mechanism to filter these resources by namespace. Implementing namespace filtering would significantly enhance the flexibility and scalability of Kubernetes monitoring, especially in multi-tenant or large-scale environments.

### Describe the solution you'd like

Introduce a namespaces configuration option within the k8sobserver extension. This would allow users to specify an array of namespaces to watch.
**Example configuration**
```yaml
extensions:
  k8s_observer:
    auth_type: serviceAccount
    namespaces: [default, prod, staging]
    observe_pods: true
    observe_services: true
    observe_ingresses: true
    observe_nodes: false

receivers:
  receiver_creator:
    watch_observers: [k8s_observer]
    receivers:
      redis:
        rule: type == "port" && pod.name matches "redis"
        config:
          password: '`pod.labels["SECRET"]`'
```

**Comment by ChrsMark** [comment]
Thank's @Ygshvr, scoping based on k8s Namespace makes sense!

My suggestion would be to ensure consistency with other components like `k8sclusterreceiver` where the setting already exists and is a single string: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.124.1/receiver/k8sclusterreceiver/config.go#L46

**Comment by bacherfl** [comment]
@ChrsMark  If this issue is available, I would like to work on this

**Comment by Ygshvr** [comment]
Thanks @ChrsMark for the suggestion, but my proposal was based on [k8seventsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/k8seventsreceiver/README.md#configuration) and [k8sobjectreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sobjectsreceiver#getting-started) where it's an array. This is useful in case one has to watch multiple namespaces.

**Comment by ChrsMark** [comment]
Another interesting idea from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36217 would be to use 2 settings, one for setting a denyList and one for an allowList: 
```
namespaceAllowList: []
namespaceDenyList: []
```

**Comment by bacherfl** [comment]
> Another interesting idea from [#36217](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/36217) would be to use 2 settings, one for setting a denyList and one for an allowList:
> 
> ```
> namespaceAllowList: []
> namespaceDenyList: []
> ```

I agree that this might be the most flexible solution. I will keep track of #36217 and stay close to how it's working there to make sure we are using the same pattern

**Comment by bacherfl** [comment]
@ChrsMark I just had another look at the linked issue for the k8sobjects receiver - Please correct me if I miss something, but it does seem like the [field selector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/521d9e5faef67d3fdace6e1aa04574587ffd8929/receiver/k8sobjectsreceiver/README.md?plain=1#L54) does already cover the use case of allowing/denying specific namespaces, e.g. by setting the selector to something like the following:

```
  k8sobjects:
    auth_type: kubeConfig
    objects:
      - name: pods
        mode: pull
        field_selector: metadata.namespace!=default,metadata.namespace!=foo
```

So maybe it could be an option to also add the possibility to configure the field selectors in the `k8sobserver` extension?
