### ISSUE TITLE
httpcheck returns 1 even if http_status_class & http_status_code is not the same

### ISSUE THREAD

**Issue by gfelot** [open-telemetry/opentelemetry-collector-contrib#39683]
### Component(s)

receiver/httpcheck

## Description
Getting status code from a healthcheck URL with `receivers/httpcheck` of services that is up return 1 also when `http_status_class` & `http_status_code` are not equal.

## Steps to Reproduce
```yaml
receivers:  
  httpcheck: # https://signoz.io/blog/health-check-monitoring-with-opentelemetry/
    collection_interval: 30s
    targets:
      - endpoint: "https://<ip_server>/healthcheck"
        method: GET
        tls:
          insecure_skip_verify: true
[...]
exporters:
  clickhousemetricswrite:
    endpoint: tcp://<signoz_serveur>:9000/signoz_metrics?username=u&password=p
    tls:
      insecure: true
    resource_to_telemetry_conversion:
      enabled: true
```
## Expected Result
When service is up, `http_status_code: 200`  is sent so only the line with `http_status_class: 2xx` should be at one.

When I request in clickhouse (SigNoz stack) with 

```sql
SELECT *
FROM signoz_metrics.time_series_v4
WHERE (metric_name = 'httpcheck_status') AND (JSONExtractString(labels, 'service_name') = 'PASSPORT') AND (JSONExtractString(labels, 'vm_hostname') = '3dx-dev08')
LIMIT 10
```

I got answer like 

```bash
Row 3:
──────
env:            DEV
temporality:    Cumulative
metric_name:    httpcheck_status
description:    1 if the check resulted in status_code matching the status_class, otherwise 0.
unit:           1
type:           Sum
is_monotonic:   false
fingerprint:    2470872169406690154 -- 2.47 quintillion
unix_milli:     1745697600000 -- 1.75 trillion
labels:         {"__name__":"httpcheck_status","__temporality__":"Cumulative","deployment_environment":"DEV","health_score":"3","host_name":"FRPAR3DXDEV08","http_method":"GET","http_status_class":"5xx","http_status_code":"200","http_url":"https://<ip_serveur>/3dpassport/healthcheck","os_type":"linux","service_name":"PASSPORT","vm_hostname":"3dx-dev08"}
attrs:          {}
scope_attrs:    {}
resource_attrs: {}
__normalized:   true
```

I can see `unit:           1` and I interprete this as 1.

For exemple in this 2xx check

```bash
Row 7:
──────
env:            DEV
temporality:    Cumulative
metric_name:    httpcheck_status
description:    1 if the check resulted in status_code matching the status_class, otherwise 0.
unit:           1
type:           Sum
is_monotonic:   false
fingerprint:    9321289193155664995 -- 9.32 quintillion
unix_milli:     1745697600000 -- 1.75 trillion
labels:         {"__name__":"httpcheck_status","__temporality__":"Cumulative","deployment_environment":"DEV","health_score":"3","host_name":"FRPAR3DXDEV08","http_method":"GET","http_status_class":"2xx","http_status_code":"200","http_url":"https://<ip_serveur>/3dpassport/healthcheck","os_type":"linux","service_name":"PASSPORT","vm_hostname":"3dx-dev08"}
attrs:          {}
scope_attrs:    {}
resource_attrs: {}
__normalized:   true
```

## Actual Result
Getting 1 for 2xx, 0 for 3xx to 5xx.

### Collector version

v0.111.39

## Environment
OS: RedHat 8.10
Compiler: Compilled with `go version go1.23.6 (Red Hat 1.23.6-1.module+el8.10.0+22945+b2c96a17) linux/amd64`

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

**Comment by AtiX** [comment]
Adding onto that, it seems like the metric for `http_status_class=2xx `and `http_status_code=200` still stays at `1` even if the target host returns an error.

What you receive are two data points (e.g. when the service returns a 502 error):

- `http_status_class=2xx` and `http_status_code=502` = 0 (expected, the status code does not match the status_class)
- `http_status_class=2xx` and `http_status_code=200` = 1 (unexpected, the service is returning a 502, so the value should not be 1)

**Comment by axw** [comment]
> I can see unit:           1 and I interprete this as 1.

This is the metric unit, not a data point value. See https://opentelemetry.io/docs/specs/semconv/general/metrics/#instrument-units and https://unitsofmeasure.org/ucum -- a unit of "1" represents "the unity".

I'm not familiar with SigNoz, but looking at https://signoz.io/docs/userguide/write-a-metrics-clickhouse-query/#table-schema-definitions--examples-for-metrics it appears to separate the time series identity from the samples (data points).

I'm going to close this as "can't reproduce" as I don't think there's an issue with httpcheck. If you still think there is, please reproduce the issue using the debug exporter, so we can rule out any vendor-specific parts of your pipeline.

**Comment by martin-schulze-e2m** [comment]
While I am not using SigNoz, I think I hit the same problem with prometheus (using the prometheus exporter).
To "reproduce" I create an artificial downtime of around 2 minutes on an endpoint watched by httpcheck and then plotted the metrics for HTTP 2xx and 5xx (y offset 0.5 for better visibility):

<img width="1375" height="407" alt="Image" src="https://github.com/user-attachments/assets/a1237daf-991c-434d-9547-be715eb3964f" />

As you can see, this short disruptions leads to following problems in the metrics:

1. the `class=5xx`, `code=503` and `class=2xx, no `code` are newly created as the outage begins and remain "active" for another 10 minutes
2. the `class 5xx`, no `code` and `class=2xx, code=200` metrics go right over the "gap"

In effect this means I can use neither metrics to determine if there is a short outage.

I tried to create a fixed metric with:

```
    metricstransform:
      transforms:
        - include: httpcheck.status
          action: insert
          new_name: httpcheck.status.fixed
          operations:
          - action: aggregate_labels
            label_set: [ http.status.class, http.url, http.method ] # removes http_status_code
            aggregation_type: sum
```

However, that just remains at 1 for `http_class=2xx` during the outage. I queried the `opentelemetry-collector` prometheus exporter `/metrics` interface directly and observed the `http_class=2xx, http_code=200` data point still being 1 during the outage. (Probably due to [`metric_expiration`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/prometheusexporter) being 5 minutes by default.)

Not shown above: When the outage lasts long enough, the series with `code=200` will actually stop, so it seems the stale value is kept around only for some time.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41385 might be related

I would propose to have a persistent `class=2xx`, `no code` metric that flips between 1 and 0. An alternative solution would be to at least export the first value after flipping to mark the exact point when it happens.

Maybe I am using this wrong, then I would be grateful for pointers on how to use the metric as intended for down detection.
