### ISSUE TITLE
No recent tag pushes to otel/opentelemetry-collector-contrib

### ISSUE THREAD

**Issue by parkedwards** [open-telemetry/opentelemetry-collector-contrib#39694]
### Describe the issue you're reporting

Hey there - we're noticing that there haven't been any docker version pushes to `otel/opentelemetry-collector-contrib` - we currently use the opentelemetry-operator via helm chart, and point the collector's image repo to `otel/opentelemetry-collector-contrib`

```yaml
  values:
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-contrib
```
 
the last tagged version we're able to find is `0.122.1`

im also noticing that this dockerhub repo hasn't had a new update in the last month, only `-dev` has consistent pushes

![Image](https://github.com/user-attachments/assets/f7bfb5ff-1923-4852-aa73-bba67f1cf996)

are we missing a publish step somewhere?
