### ISSUE TITLE
Same metric name, unit, and type with different description leads to incorrect description on the produced metric

### ISSUE THREAD

**Issue by lahsivjar** [open-telemetry/opentelemetry-collector-contrib#39736]
### Component(s)

connector/signaltometrics

## Description

If two metrics are defined with same metric name, unit, and type but with different descriptions then only the last description is used. This case is possible if we want to define metrics with different attributes or condition criteria. See steps to reproduce for examples.

## Steps to Reproduce

Define signal to metrics connector with the following configuration:
```yaml
spans:
    - name: metric.1
      description: Metric with resource.foo attribute
      unit: ms
      include_resource_attributes:
        - key: resource.foo
      histogram:
        value: Milliseconds(end_time - start_time)
    - name: with_resource_foo_only
      description: Metric with resource.bar attribute
      unit: ms
      include_resource_attributes:
        - key: resource.bar
      histogram:
        value: Milliseconds(end_time - start_time)
```

## Expected Result

The above config should produce the metric with `resource.foo` resource attribute having description _"Metric with resource.foo attribute"_ and the metric with `resource.bar` resource attribute having description _"Metric with resource.bar attribute"_.

## Actual Result

Metrics with both `resource.foo` as well as `resource.bar` attributes have the same description: _"Metric with resource.bar attribute"_.

### Collector version

v0.125.0
