### ISSUE TITLE
unbalanced kafka partitioning after upgrading to 0.124.0

### ISSUE THREAD

**Issue by r-tekdogan** [open-telemetry/opentelemetry-collector-contrib#39810]
### Component(s)

exporter/kafka

## Description
We upgraded collector from 0.121.0 to 0.124.0 without changing the config. 
We have kafka cluster in 3 regions with 24 partitions
After the upgrade we realised kafka exporter writes to 1 partition and the rest of the partitions didn't receive any data

## Expected Result
Even distribution among kafka partitions
## Actual Result
Only partition receives data

![Image](https://github.com/user-attachments/assets/6fd37481-4af4-4939-97e5-19814e2ac959)

### Collector version

v0.124.0

## Environment
OS: Docker alpine 3.21.3
Compiler(if manually compiled): go 1.24.2

### OpenTelemetry Collector configuration

```yaml
exporters:
  kafka/metrics:
    protocol_version: 2.0.0
    brokers: ${env:OTEL_KAFKA_BROKERS_METRICS}
    topic: opentelemetry__collector-gateway__metrics
    producer:
      compression: gzip
      max_message_bytes: 10485760 # 10MB
    auth:
      tls:
        ca_file: /var/run/secrets/kafka.client.ca-chain.pem
        cert_file: /var/run/secrets/kafka.client.certificate.pem
        key_file: /var/run/secrets/kafka.client.certificate.key
    sending_queue:
      queue_size: 750000
      storage: file_storage
```

### Log output

```shell

```
