### ISSUE TITLE
Not able to drop the duplicate labels using the exclude dimensions in span metrics

### ISSUE THREAD

**Issue by adithya-r-nathan** [open-telemetry/opentelemetry-collector-contrib#39838]
### Component(s)

connector/spanmetrics

### Describe the issue you're reporting

I'm trying to drop extra or duplicate labels using the exclude_dimensions in the span metrics connector, but they still appear in the output metrics

span metrics connector config:
```
connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [4ms, 10ms, 25ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1s, 1500ms, 2s, 4s, 10s, 20s, 40s]
    exclude_dimensions:
      - index
      - container.id
      - host.name
      - service.instance.id
      - k8s_replicaset_name
      - k8s_pod_name
      - service_instance_id
      - process_pid
      - process_runtime_description
      - process_runtime_name
      - process_command_args
      - job
      - `k8s_container_name`
```

**Additional Question**

Is it possible to include the span name as a field in the service graph connector?
