### ISSUE TITLE
Cannot recombine journald receiver logs

### ISSUE THREAD

**Issue by matthewbyrne** [open-telemetry/opentelemetry-collector-contrib#39906]
### Component(s)

receiver/journald

## Description
I'm trying to ingest from journald, `route` logs to a `regex_parser` and then `recombine` any multiline logs

## Steps to Reproduce
Our receiver config below takes journald logs and matches them to a router, or sends them to a `catchall` router. From the router, the log goes into a `regex_parser`, and finally into the `recombine` operator.

## Expected Result
Logs which don't start with a date (YYYY-MM-DD) are combined into the previous log

## Actual Result
The first line of the log (the date, log level, log message etc) is routed correctly through the router to the `default_logs` regex_parser and parsed. Then it goes to the `recombine` (I know this because the `multiline` value is set for `multiline_handler`) but it does not combine with any others logs. I then see the other logs (the stack trace) unparsed and without the `multiline` value is set for `multiline_handler.

So my understanding is that those other logs are not going through the `recombine` operator, because they don't match the `route` and thus go through the `catchall`. But if I set an output of `handle_multiline` at the `catchall` `regex_parser` I still don't get multilines working. I get each log individually into opensearch tagged with multiline.

```
      - type: regex_parser
        parse_from: body.MESSAGE
        parse_to: body
        id: catchall
        regex: '(?P<message>.*)'
        output: handle_multiline
      - type: recombine
        id: handle_multiline
        combine_field: body.MESSAGE
        combine_with: "\n"
        is_first_entry: 'body.MESSAGE matches "^\\d{4}-\\d{2}-\\d{2}.*"'
        source_identifier: body.SYSLOG_IDENTIFIER
        output: add_multiline_tag
```

### Collector version

0.119.0

## Environment
OS: Amazon Linux

### OpenTelemetry Collector configuration

```yaml
receivers:
  journald:
    matches:
      - _SYSTEMD_UNIT: foo-bar.service
    operators:
      - type: router
        id: route_logs
        routes:
          - output: [default_logs]
            expr: 'body.MESSAGE matches "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2},\\d{3} \\w+.*"'
        default: [catchall]
      - type: regex_parser
        id: default_logs
        parse_from: body.MESSAGE
        parse_to: body
        regex: '^(?P<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2},\d{3}) (?P<log_level>\w+) (?P<message>.*)'
        output: [ handle_multiline]
      - type: regex_parser
        parse_from: body.MESSAGE
        parse_to: body
        id: catchall
        regex: '(?P<message>.*)'
        output: noop
      - type: recombine
        id: handle_multiline
        combine_field: body.MESSAGE
        combine_with: "\n"
        is_first_entry: body.MESSAGE matches "^\\d{4}-\\d{2}-\\d{2}.*"
        source_identifier: body.SYSLOG_IDENTIFIER
        output: add_multiline_tag
      - type: add
        id: add_multiline_tag
        field: body.multiline_handler
        value: multiline
        output: noop
      - type: noop
```

### Log output

```shell
No errors or warnings
```
