### ISSUE TITLE
Kafka exporter doesn't work with SASL_SSL

### ISSUE THREAD

**Issue by jovezhong** [open-telemetry/opentelemetry-collector-contrib#39919]
### What happened?

**Describe the bug**

It seems that kafkaexport only work with unauthorized kafka. I am sure on my VM I can connect to either Aiven Kafka or the GCP managed Kafka, but when I configure the same access in `/etc/otelcol-contrib/config.yaml` I failed to start the collector.

`sudo /usr/bin/otelcol-contrib --config=/etc/otelcol-contrib/config.yaml`

> Error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF
> 2025/05/02 05:44:13 collector server run finished with error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF

**Steps to reproduce**

```yaml
exporters:
  kafka/metrics:
    brokers: ["mybroker:9092"]
    auth:
      sasl:
         username: avnadmin
         password: ..
         mechanism: SCRAM-SHA-256
    tls:
         insecure: true
    topic: otlp_metrics
    metrics:
         encoding: otlp_json
```

**What did you expect to see?**

write data to kafka
**What did you see instead?**

fail to start the collector
> Error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF
> 2025/05/02 05:44:13 collector server run finished with error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF

### Collector version

0.125.0

## Environment
OS: (e.g., "Ubuntu 20.04") Debian
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  kafka/metrics:
    brokers: ["mybroker:9092"]
    auth:
      sasl:
         username: avnadmin
         password: ..
         mechanism: SCRAM-SHA-256
    tls:
         insecure: true
    topic: otlp_metrics
    metrics:
         encoding: otlp_json
```
### Log output

```shell

```

**Comment by jovezhong** [comment]
Thanks github-actions (I always say thank you to AI)

I have to [set up a kafka proxy](https://www.linkedin.com/pulse/how-set-up-kafka-proxy-gcp-any-cloud-jove-zhong-avy6c/) to disable the auth to make it work. Please check whether it's a bug.

**Comment by axw** [comment]
@jovezhong you need to nest `sasl` under `auth`, i.e.:

```yaml
exporters:
  kafka/metrics:
    brokers: ["mybroker:9092"]
    auth:
      sasl:
        username: avnadmin
        password: ..
        mechanism: SCRAM-SHA-256
    tls:
      insecure: true
    metrics:
      encoding: otlp_json
```

**Comment by jovezhong** [comment]
Sorry, I put wrong info in the original ticket. I am actually putting `sasl` under auth. But still got error while connecting to Kafka cluster

> 2025-05-12T04:29:24.756Z	info	extensions/extensions.go:62	Extension started.	{"otelcol.component.id": "health_check", "otelcol.component.kind": "extension"}
2025-05-12T04:29:25.527Z	error	graph/graph.go:438	Failed to start component	{"error": "kafka: client has run out of available brokers to talk to: unexpected EOF", "type": "Exporter", "id": "kafka/metrics"}
2025-05-12T04:29:25.527Z	info	service@v0.125.0/service.go:331	Starting shutdown...
2025-05-12T04:29:25.527Z	info	healthcheck/handler.go:132	Health Check state change	{"otelcol.component.id": "health_check", "otelcol.component.kind": "extension", "status": "unavailable"}
2025-05-12T04:29:25.527Z	info	extensions/extensions.go:69	Stopping extensions...
2025-05-12T04:29:25.527Z	info	service@v0.125.0/service.go:345	Shutdown complete.
Error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF
2025/05/12 04:29:25 collector server run finished with error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF

The full config is like this (the kakfa is only accessible within GCP VPC)
```yaml
extensions:
  health_check:

receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu: {}
      memory: {}
      disk: {}
      load: {}

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  resource:
    attributes:
      - key: instance
        value: instancename
        action: insert

exporters:
  kafka/metrics:
    brokers: ["bootstrap.demo.us-west1.managedkafka.tpdemo2025.cloud.goog:9092"]
    auth:
      sasl:
        mechanism: PLAIN
        username: name@project.iam.gserviceaccount.com
        password: thekey
    topic: otlp_metrics
    metrics:
      encoding: otlp_json

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch,resource]
      exporters: [kafka/metrics]

  extensions: [health_check]

```

**Comment by rafaelrodrigues3092** [comment]
Unsure if related, but I am experiencing the same issue as @jovezhong using the kafka exporter with Azure Event Hub starting with v0.124.0 (worked fine with v0.123.0).

```
exporters:
  kafka:
    brokers:
      - '<NAMESPACE>.servicebus.windows.net:9093'
    metrics:
      topic: metrics
      encoding: otlp_proto
    tls:
      insecure: true
    auth:
      sasl:
        mechanism: PLAIN
        username: '$$ConnectionString'
        password: '<KEY>'
```

Thanks

**Comment by axw** [comment]
Sorry for the delay, I've been on vacation - I'm looking into it. Using `insecure: true` with Event Hubs seems wrong. That config means disable TLS, and I think Event Hubs requires TLS.

**Comment by axw** [comment]
I've tested with Azure Event Hubs, it works if you use this config:

```yaml
exporters:
  kafka:
    brokers:
      - '<NAMESPACE>.servicebus.windows.net:9093'
    metrics:
      topic: metrics
      encoding: otlp_proto
    tls:
      insecure: false
    auth:
      sasl:
        mechanism: PLAIN
        username: '$$ConnectionString'
        password: '<KEY>'
```

i.e. just replace `insecure: true` with `insecure: false`. As mentioned above, `tls::insecure: true` means don't use TLS at all. This is also the default configuration. If you want to enable TLS, you need to configure `tls: {}` or `tls::insecure: false`.

I haven't yet tested with GCP's Managed Kafka, but the above shows that you can indeed use SASL with TLS.
