### ISSUE TITLE
Multiple null values when collecting events

### ISSUE THREAD

**Issue by gmlexx** [open-telemetry/opentelemetry-collector-contrib#39922]
### Component(s)

receiver/k8sobjects

## Description

The default events configuration produces a lot of noise with null fields that doesn't seem valuable

The k8sreceiver doesn't produce any noise and collects a clean structure

## Steps to Reproduce

Put receiver configuration
```
      k8sobjects:
        objects:
          - name: events
            mode: watch
```

## Expected Result

Clean structure with the defined fields only

## Actual Result

```
[
  {
    "Key": "type",
    "Value": {
      "StringValue": "MODIFIED",
      "BoolValue": null,
      "IntValue": null,
      "DoubleValue": null,
      "ArrayValue": null,
      "KeyValueList": null,
      "BytesValue": null
    }
  },
  {
    "Key": "object",
    "Value": {
      "StringValue": null,
      "BoolValue": null,
      "IntValue": null,
      "DoubleValue": null,
      "ArrayValue": null,
      "KeyValueList": {
        "Values": [
          {
            "Key": "reportingInstance",
            "Value": {
              "StringValue": "",
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "apiVersion",
            "Value": {
              "StringValue": "v1",
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "involvedObject",
            "Value": {
              "StringValue": null,
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": {
                "Values": [
                  {
                    "Key": "name",
                    "Value": {
                      "StringValue": "openstack-standalone-cp-0-2-2",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "uid",
                    "Value": {
                      "StringValue": "eb08a457-3a39-4741-b7bf-4a0ab6088626",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "apiVersion",
                    "Value": {
                      "StringValue": "source.toolkit.fluxcd.io/v1",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "resourceVersion",
                    "Value": {
                      "StringValue": "1306",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "kind",
                    "Value": {
                      "StringValue": "HelmChart",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "namespace",
                    "Value": {
                      "StringValue": "kcm-system",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  }
                ]
              },
              "BytesValue": null
            }
          },
          {
            "Key": "reason",
            "Value": {
              "StringValue": "ArtifactUpToDate",
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "message",
            "Value": {
              "StringValue": "artifact up-to-date with remote revision: '0.2.2'",
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "lastTimestamp",
            "Value": {
              "StringValue": "2025-05-07T11:12:33Z",
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "count",
            "Value": {
              "StringValue": null,
              "BoolValue": null,
              "IntValue": 38,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "type",
            "Value": {
              "StringValue": "Normal",
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "reportingComponent",
            "Value": {
              "StringValue": "source-controller",
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "kind",
            "Value": {
              "StringValue": "Event",
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "metadata",
            "Value": {
              "StringValue": null,
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": {
                "Values": [
                  {
                    "Key": "name",
                    "Value": {
                      "StringValue": "openstack-standalone-cp-0-2-2.183cf281a3b6d8ec",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "namespace",
                    "Value": {
                      "StringValue": "kcm-system",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "uid",
                    "Value": {
                      "StringValue": "137f9559-9ad2-44fb-b3fd-aa8a6930763f",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "resourceVersion",
                    "Value": {
                      "StringValue": "224513",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "creationTimestamp",
                    "Value": {
                      "StringValue": "2025-05-06T13:16:34Z",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  },
                  {
                    "Key": "managedFields",
                    "Value": {
                      "StringValue": null,
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": {
                        "Values": [
                          {
                            "StringValue": null,
                            "BoolValue": null,
                            "IntValue": null,
                            "DoubleValue": null,
                            "ArrayValue": null,
                            "KeyValueList": {
                              "Values": [
                                {
                                  "Key": "fieldsType",
                                  "Value": {
                                    "StringValue": "FieldsV1",
                                    "BoolValue": null,
                                    "IntValue": null,
                                    "DoubleValue": null,
                                    "ArrayValue": null,
                                    "KeyValueList": null,
                                    "BytesValue": null
                                  }
                                },
                                {
                                  "Key": "fieldsV1",
                                  "Value": {
                                    "StringValue": null,
                                    "BoolValue": null,
                                    "IntValue": null,
                                    "DoubleValue": null,
                                    "ArrayValue": null,
                                    "KeyValueList": {
                                      "Values": [
                                        {
                                          "Key": "f:reason",
                                          "Value": {
                                            "StringValue": null,
                                            "BoolValue": null,
                                            "IntValue": null,
                                            "DoubleValue": null,
                                            "ArrayValue": null,
                                            "KeyValueList": {
                                              "Values": null
                                            },
                                            "BytesValue": null
                                          }
                                        },
                                        {
                                          "Key": "f:reportingComponent",
                                          "Value": {
                                            "StringValue": null,
                                            "BoolValue": null,
                                            "IntValue": null,
                                            "DoubleValue": null,
                                            "ArrayValue": null,
                                            "KeyValueList": {
                                              "Values": null
                                            },
                                            "BytesValue": null
                                          }
                                        },
                                        {
                                          "Key": "f:source",
                                          "Value": {
                                            "StringValue": null,
                                            "BoolValue": null,
                                            "IntValue": null,
                                            "DoubleValue": null,
                                            "ArrayValue": null,
                                            "KeyValueList": {
                                              "Values": [
                                                {
                                                  "Key": "f:component",
                                                  "Value": {
                                                    "StringValue": null,
                                                    "BoolValue": null,
                                                    "IntValue": null,
                                                    "DoubleValue": null,
                                                    "ArrayValue": null,
                                                    "KeyValueList": {
                                                      "Values": null
                                                    },
                                                    "BytesValue": null
                                                  }
                                                }
                                              ]
                                            },
                                            "BytesValue": null
                                          }
                                        },
                                        {
                                          "Key": "f:firstTimestamp",
                                          "Value": {
                                            "StringValue": null,
                                            "BoolValue": null,
                                            "IntValue": null,
                                            "DoubleValue": null,
                                            "ArrayValue": null,
                                            "KeyValueList": {
                                              "Values": null
                                            },
                                            "BytesValue": null
                                          }
                                        },
                                        {
                                          "Key": "f:type",
                                          "Value": {
                                            "StringValue": null,
                                            "BoolValue": null,
                                            "IntValue": null,
                                            "DoubleValue": null,
                                            "ArrayValue": null,
                                            "KeyValueList": {
                                              "Values": null
                                            },
                                            "BytesValue": null
                                          }
                                        },
                                        {
                                          "Key": "f:count",
                                          "Value": {
                                            "StringValue": null,
                                            "BoolValue": null,
                                            "IntValue": null,
                                            "DoubleValue": null,
                                            "ArrayValue": null,
                                            "KeyValueList": {
                                              "Values": null
                                            },
                                            "BytesValue": null
                                          }
                                        },
                                        {
                                          "Key": "f:involvedObject",
                                          "Value": {
                                            "StringValue": null,
                                            "BoolValue": null,
                                            "IntValue": null,
                                            "DoubleValue": null,
                                            "ArrayValue": null,
                                            "KeyValueList": {
                                              "Values": null
                                            },
                                            "BytesValue": null
                                          }
                                        },
                                        {
                                          "Key": "f:lastTimestamp",
                                          "Value": {
                                            "StringValue": null,
                                            "BoolValue": null,
                                            "IntValue": null,
                                            "DoubleValue": null,
                                            "ArrayValue": null,
                                            "KeyValueList": {
                                              "Values": null
                                            },
                                            "BytesValue": null
                                          }
                                        },
                                        {
                                          "Key": "f:message",
                                          "Value": {
                                            "StringValue": null,
                                            "BoolValue": null,
                                            "IntValue": null,
                                            "DoubleValue": null,
                                            "ArrayValue": null,
                                            "KeyValueList": {
                                              "Values": null
                                            },
                                            "BytesValue": null
                                          }
                                        }
                                      ]
                                    },
                                    "BytesValue": null
                                  }
                                },
                                {
                                  "Key": "manager",
                                  "Value": {
                                    "StringValue": "source-controller",
                                    "BoolValue": null,
                                    "IntValue": null,
                                    "DoubleValue": null,
                                    "ArrayValue": null,
                                    "KeyValueList": null,
                                    "BytesValue": null
                                  }
                                },
                                {
                                  "Key": "operation",
                                  "Value": {
                                    "StringValue": "Update",
                                    "BoolValue": null,
                                    "IntValue": null,
                                    "DoubleValue": null,
                                    "ArrayValue": null,
                                    "KeyValueList": null,
                                    "BytesValue": null
                                  }
                                },
                                {
                                  "Key": "apiVersion",
                                  "Value": {
                                    "StringValue": "v1",
                                    "BoolValue": null,
                                    "IntValue": null,
                                    "DoubleValue": null,
                                    "ArrayValue": null,
                                    "KeyValueList": null,
                                    "BytesValue": null
                                  }
                                },
                                {
                                  "Key": "time",
                                  "Value": {
                                    "StringValue": "2025-05-07T11:12:33Z",
                                    "BoolValue": null,
                                    "IntValue": null,
                                    "DoubleValue": null,
                                    "ArrayValue": null,
                                    "KeyValueList": null,
                                    "BytesValue": null
                                  }
                                }
                              ]
                            },
                            "BytesValue": null
                          }
                        ]
                      },
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  }
                ]
              },
              "BytesValue": null
            }
          },
          {
            "Key": "source",
            "Value": {
              "StringValue": null,
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": {
                "Values": [
                  {
                    "Key": "component",
                    "Value": {
                      "StringValue": "source-controller",
                      "BoolValue": null,
                      "IntValue": null,
                      "DoubleValue": null,
                      "ArrayValue": null,
                      "KeyValueList": null,
                      "BytesValue": null
                    }
                  }
                ]
              },
              "BytesValue": null
            }
          },
          {
            "Key": "firstTimestamp",
            "Value": {
              "StringValue": "2025-05-06T13:16:34Z",
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          },
          {
            "Key": "eventTime",
            "Value": {
              "StringValue": null,
              "BoolValue": null,
              "IntValue": null,
              "DoubleValue": null,
              "ArrayValue": null,
              "KeyValueList": null,
              "BytesValue": null
            }
          }
        ]
      },
      "BytesValue": null
    }
  }
]
```

### Collector version

0.123.0

## Environment
kind kubernets cluster

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug: {}
  otlphttp:
    auth:
      authenticator: basicauth/logs
    logs_endpoint: http://kof-storage-victoria-logs-single-server:9428/insert/opentelemetry/v1/logs
    tls:
      insecure: true
extensions:
  basicauth/logs:
    client_auth:
      password: <password>
      username: <username>
processors:
  batch: {}
  resource/k8sobjects:
    attributes:
    - action: insert
      key: k8s.cluster.name
      value: mothership
receivers:
  k8s_cluster:
    allocatable_types_to_report:
    - cpu
    - memory
    - storage
    auth_type: serviceAccount
    collection_interval: 10s
    node_conditions_to_report:
    - Ready
    - MemoryPressure
    - DiskPressure
    - NetworkUnavailable
  k8sobjects:
    objects:
    - mode: watch
      name: events
service:
  extensions:
  - basicauth/logs
  pipelines:
    logs:
      exporters:
      - otlphttp
      - debug
      processors:
      - resource/k8sobjects
      - batch
      receivers:
      - k8sobjects
```

### Log output

```shell

```

**Comment by ChrsMark** [comment]
Should be considered as part of https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24242

**Comment by ChrsMark** [comment]
@gmlexx I've started checking the whole deprecation story (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24242) of the `k8sevents` receiver and as a first step I'm checking if `k8sobjects` receiver can already replace the `k8sevents` receiver.

(the issue is quite similar to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26099)

The answer is that it cannot as is right now but if we use it along with `transform` processor then it can. See my side-by-side comparison example below:

`k8sevents_config.yaml`:
```yaml
exporters:
  debug:
    verbosity: detailed

receivers:
  k8s_events:
    auth_type: kubeConfig

service:
  telemetry:
    logs:
      level: INFO
  pipelines:
    logs:
      receivers: [ k8s_events ]
      processors: [ ]
      exporters: [ debug ]
```

`k8sobjects_config.yaml`:
```yaml
exporters:
  debug:
    verbosity: detailed

receivers:
  k8sobjects/events:
    auth_type: kubeConfig
    objects:
      - mode: watch
        name: events

processors:
  transform/events:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["k8s.node.name"], body["object"]["source"]["host"])

          - set(resource.attributes["k8s.object.kind"],body["object"]["involvedObject"]["kind"])
          - set(resource.attributes["k8s.object.name"], body["object"]["involvedObject"]["name"])
          - set(resource.attributes["k8s.object.uid"], body["object"]["involvedObject"]["uid"])
          - set(resource.attributes["k8s.object.fieldpath"], body["object"]["involvedObject"]["fieldPath"])
          - set(resource.attributes["k8s.object.api_version"], body["object"]["involvedObject"]["apiVersion"])
          - set(resource.attributes["k8s.object.resource_version"], body["object"]["involvedObject"]["resourceVersion"])

          - set(log.cache["time"], body["object"]["firstTimestamp"]) where body["object"]["firstTimestamp"] != nil
          - set(log.cache["time"], body["object"]["lastTimestamp"]) where body["object"]["lastTimestamp"] != nil
          - set(log.cache["time"], body["object"]["eventTime"]) where body["object"]["eventTime"] != nil
          - set(log.time, Time(attributes["time"], "%Y-%m-%dT%H:%M:%SZ"))
          - delete_key(log.cache, "time")

          - set(attributes["k8s.event.reason"], body["object"]["reason"])
          - set(attributes["k8s.event.action"], body["object"]["action"])
          - set(attributes["k8s.event.start_time"], body["object"]["metadata"]["creationTimestamp"])
          - set(attributes["k8s.event.uid"], body["object"]["metadata"]["uid"])
          - set(attributes["k8s.namespace.name"], body["object"]["involvedObject"]["namespace"])

          - set(log.cache["Normal"], 9)
          - set(log.cache["Warning"], 13)
          - set(log.severity_text, body["object"]["type"])
          - set(log.severity_number, log.cache[log.severity_text])
          - delete_key(log.cache, "normal")
          - delete_key(log.cache, "warning")

          - set(attributes["k8s.event.count"], body["object"]["count"])

          - set(body, body["object"]["message"])

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8889
  pipelines:
    logs:
      receivers: [ k8sobjects/events ]
      processors: [ transform/events ]
      exporters: [ debug ]
```

#### Output of `k8sevents`

 ```console
2025-05-23T14:18:36.607+0300	info	Logs	{"resource logs": 1, "log records": 1}
2025-05-23T14:18:36.607+0300	info	ResourceLog #0
Resource SchemaURL:
Resource attributes:
     -> k8s.node.name: Str(kind-control-plane)
     -> k8s.object.kind: Str(Pod)
     -> k8s.object.name: Str(redis-deployment-77b9b7cfbd-lzfxs)
     -> k8s.object.uid: Str(f0287324-4a42-4154-9a10-f1e1c21a692e)
     -> k8s.object.fieldpath: Str(spec.containers{busybox})
     -> k8s.object.api_version: Str(v1)
     -> k8s.object.resource_version: Str(350656)
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2025-05-23 11:18:36 +0000 UTC
SeverityText: Normal
SeverityNumber: Info(9)
Body: Str(Started container busybox)
Attributes:
     -> k8s.event.reason: Str(Started)
     -> k8s.event.action: Str()
     -> k8s.event.start_time: Str(2025-05-23 14:18:36 +0300 EEST)
     -> k8s.event.name: Str(redis-deployment-77b9b7cfbd-lzfxs.184223ef6cebd4a1)
     -> k8s.event.uid: Str(a41b7951-9451-4a50-a69d-89a524a64683)
     -> k8s.namespace.name: Str(default)
     -> k8s.event.count: Int(1)
Trace ID:
Span ID:
Flags: 0
```

#### Output of `k8sobjects` receiver + `transform` processor

 ```console
2025-05-23T14:18:36.607+0300	info	Logs	{"resource logs": 1, "log records": 1}
2025-05-23T14:18:36.607+0300	info	ResourceLog #0
Resource SchemaURL:
Resource attributes:
     -> k8s.namespace.name: Str(default)
     -> k8s.node.name: Str(kind-control-plane)
     -> k8s.object.kind: Str(Pod)
     -> k8s.object.name: Str(redis-deployment-77b9b7cfbd-lzfxs)
     -> k8s.object.uid: Str(f0287324-4a42-4154-9a10-f1e1c21a692e)
     -> k8s.object.fieldpath: Str(spec.containers{busybox})
     -> k8s.object.api_version: Str(v1)
     -> k8s.object.resource_version: Str(350656)
ScopeLogs #0
ScopeLogs SchemaURL:
InstrumentationScope
LogRecord #0
ObservedTimestamp: 2025-05-23 11:18:36.607234 +0000 UTC
Timestamp: 2025-05-23 11:18:36 +0000 UTC
SeverityText: Normal
SeverityNumber: Info(9)
Body: Str(Started container busybox)
Attributes:
     -> k8s.resource.name: Str(events)
     -> event.domain: Str(k8s)
     -> event.name: Str(redis-deployment-77b9b7cfbd-lzfxs.184223ef6cebd4a1)
     -> k8s.event.reason: Str(Started)
     -> k8s.event.start_time: Str(2025-05-23T11:18:36Z)
     -> k8s.event.uid: Str(a41b7951-9451-4a50-a69d-89a524a64683)
     -> k8s.namespace.name: Str(default)
     -> k8s.event.count: Int(1)
Trace ID:
Span ID:
Flags: 0
```

So I think that for your use-case you can already switch to `k8sobjects` receiver and use it along with the `transform` processor to achieve the wanted result. The good thing is that having the whole raw object you can apply even more custom transformations to extract more data if needed. `k8sobjects` receiver provides more flexibility compared to `k8sevents` receiver. 

I will continue the investigation around the whole Events vs Logs story and I will update https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24242 so as to see how we can proceed with the deprecation of the component.
