### ISSUE TITLE
[opampsupervisor] Local config with extensions overwriting opamp extension

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector-contrib#39931]
### Component(s)

cmd/opampsupervisor

## Description

If you supply the opampsupervisor with a local config for the collector that includes extensions, such as 

```yaml
extensions:
  basicauth:
    client_auth:
      username: username
      password: password

service:
  extensions: [basicauth]
```

Then when the commander passes in the config via an additional config flag the default opamp extension will be removed from the extension list.

The problem occurs here:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/61f8c78d4833dfca588db0fa530df1fc79da8413/cmd/opampsupervisor/supervisor/commander/commander.go#L75-L102

The commander doesn't do any fancy merging of the config, it just passes the local config(s) as the last parameters, which means those configs' list take precedence over the supervisor's `effective.yaml`.

## Steps to Reproduce

Configure an opampsupervisor to pass the above local config to its agent

## Expected Result

The agent can start with both the basicauth and opampsupervisor extensions

## Actual Result

only the basicauth extension ends up in the extension list.

### Collector version

latest

### Work Around

In your local config make sure that you add the opampextension to the extension list. For the scenario above the work around is:

```yaml
extensions:
  basicauth:
    client_auth:
      username: username
      password: password

service:
  extensions: [opamp, basicauth]
```
