### ISSUE TITLE
Feature Request: Support Dynamic Regex Patterns in OTTL IsMatch() Function

### ISSUE THREAD

**Issue by fuog** [open-telemetry/opentelemetry-collector-contrib#39997]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

Currently, the `IsMatch()` function in OpenTelemetry's OTTL requires a static regex pattern, which limits its flexibility. I would like to use a regex pattern stored in a telemetry attribute, such as a Kubernetes pod annotation (e.g., `k8s.pod.annotation.regex_pattern`), to dynamically filter telemetry data. This is not possible today, as `IsMatch()` only accepts hardcoded string literals, forcing me to use workarounds like custom processors or preprocessing in application logic.

### Describe the solution you'd like

I propose adding support for dynamic regex patterns in the `IsMatch()` function, allowing the regex pattern to be sourced from an attribute or another OTTL-accessible value. For example:
```yaml
processors:
  transform:
    traces:
      - context: span
        statements:
          - set(attributes["regex_match"], true) where IsMatch(attributes["username"], attributes["k8s.pod.annotation.regex_pattern"])
```
This would enable `IsMatch()` to use a regex pattern stored in `k8s.pod.annotation.regex_pattern` (e.g., `^user.*$`) to evaluate `attributes["username"]`. The function should handle invalid regex patterns gracefully, perhaps by logging an error or skipping the match.

### Describe alternatives you've considered

writing some static filters in important cases. Providing less UX to the platform users.

### Additional context

This feature would greatly enhance OTTL's flexibility for Kubernetes-based environments, where pod annotations or labels often store configuration data like regex patterns. It would simplify dynamic filtering use cases, such as matching span attributes against patterns defined in Kubernetes resources, without requiring custom code or external preprocessing. To mitigate performance and security concerns (e.g., ReDoS attacks), the implementation could include regex compilation caching and pattern validation.
