### ISSUE TITLE
OTTL: Standard function ToString (and others) "undefined" in transformprocessor when building otelcontribcol from source (v0.125.0 / main)

### ISSUE THREAD

**Issue by trinitry** [open-telemetry/opentelemetry-collector-contrib#40037]
### Component(s)

cmd/otelcontribcol

## Description
When using the transformprocessor with OTTL statements, standard functions like ToString, ReplaceAllString, etc., are reported as "undefined function". This occurs even when building the otelcontribcol binary directly from the [opentelemetry-collector-contrib](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) source repository (tried with tag v0.125.0 and the main branch).

The otelcontribcol components command confirms that the transform processor (version v0.125.0) is present in the built binary.

## Steps to Reproduce
1. Clone the [opentelemetry-collector-contrib](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) repository.
- Attempt 1: git checkout v0.125.0
- Attempt 2: git checkout main && git pull
2. Build a custom collector Docker image using the following Dockerfile (simplified):

```
# Stage 1: Builder
FROM golang:1.23-bullseye AS builder

ARG TARGETARCH
ARG OTEL_COLLECTOR_VERSION="v0.125.0" # Or "main"

RUN apt-get update && apt-get install -y make git file
WORKDIR /src

# This COPY command points to a local clone of opentelemetry-collector-contrib
COPY ./opentelemetry-collector-contrib ./opentelemetry-collector-contrib
WORKDIR /src/opentelemetry-collector-contrib

RUN echo "Building otelcontribcol from source for GOARCH=${TARGETARCH}..." && \
    make otelcontribcol GOOS=linux GOARCH=${TARGETARCH}

RUN mkdir -p /build_output && \
    cp "./bin/otelcontribcol_linux_${TARGETARCH}" /build_output/otelcol

# Stage 2: Final Image
FROM debian:bullseye-slim
COPY --from=builder "/build_output/otelcol" /usr/local/bin/otelcol
# ... (user setup, certs, etc.)
ENTRYPOINT ["/usr/local/bin/otelcol"]
CMD ["--config=/etc/otelcol-contrib/config.yaml"]
```
3. Build command (example for v0.125.0):
```
docker buildx build \
  --platform linux/arm64 \
  --build-arg OTEL_COLLECTOR_VERSION=v0.125.0 \
  -t custom-otel-collector-edge:v0.125.0-from-source \
  . # Assuming Dockerfile and opentelemetry-collector-contrib subdir are in context
```
4. Collector configuration (config.yaml):
```
receivers:
  # ... (e.g., journald)
processors:
  transform:
    log_statements:
      - context: log
        statements:
          # This is the failing statement
          - set(attributes["raw_message_str"], ToString(attributes["MESSAGE"]))
          # Other statements like ReplaceAllString, IsMatch also fail similarly
          # - set(attributes["extracted_numbers_str"], ReplaceAllString(attributes["raw_message_str"], "^.*\"MESSAGE\\\\\":\\\\[([\\\\d,\\\\s]+)\\\\].*$", "$1"))
exporters:
  # ... (e.g., otlphttp, debug)
service:
  pipelines:
    logs:
      receivers: [/* your receiver */]
      processors: [transform]
      exporters: [/* your exporter */]
```
5. Run the collector (e.g., via Docker Compose, ensuring the built image and config are used).

## Expected Result

The OpenTelemetry Collector should start without errors, and the transformprocessor should successfully parse and apply the OTTL statements using standard functions like ToString.

## Actual Result

The collector fails to start with an error similar to this in the logs:

> Error: invalid configuration: processors::transform: unable to parse OTTL statement "set(log.attributes[\"raw_message_str\"], ToString(log.attributes[\"MESSAGE\"]))": error while parsing arguments for call to "set": invalid argument at position 1: undefined function "ToString"

Similar "undefined function" errors occur for other standard OTTL functions like ReplaceAllString, IsMatch, etc.

### Collector version

v0.125.0, 8c7038b37fc4432e7a036b3eb53fac6fed79d15a

## Environment
- Build environment: Docker golang:1.23-bullseye on macOS.
- Target platform for collector binary: linux/arm64.
- Runtime environment: Docker on a Linux ARM64 edge device.

### OpenTelemetry Collector configuration

```yaml
receivers:
  # ... (e.g., journald)
processors:
  transform:
    log_statements:
      - context: log
        statements:
          # This is the failing statement
          - set(attributes["raw_message_str"], ToString(attributes["MESSAGE"]))
          # Other statements like ReplaceAllString, IsMatch also fail similarly
          # - set(attributes["extracted_numbers_str"], ReplaceAllString(attributes["raw_message_str"], "^.*\"MESSAGE\\\\\":\\\\[([\\\\d,\\\\s]+)\\\\].*$", "$1"))
exporters:
  # ... (e.g., otlphttp, debug)
service:
  pipelines:
    logs:
      receivers: [/* your receiver */]
      processors: [transform]
      exporters: [/* your exporter */]
```

### Log output

```shell
Error: invalid configuration: processors::transform: unable to parse OTTL statement "set(log.attributes[\"raw_message_str\"], ToString(log.attributes[\"MESSAGE\"]))": error while parsing arguments for call to "set": invalid argument at position 1: undefined function "ToString"
```

### Additional context

- The command docker run --rm <your-built-image-tag> components confirms the transform processor is present and lists its module as github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.125.0.
- The issue seems to indicate that standard OTTL functions are not being correctly registered or made available within the transformprocessor despite it being compiled from source.
- This problem prevents any useful log transformation using OTTL.
