### ISSUE TITLE
[receiver/libhoney] requires / after paths

### ISSUE THREAD

**Issue by mterhar** [open-telemetry/opentelemetry-collector-contrib#40070]
## Description

If you don't include a `/` after the paths, it will not treat them as wildcards and will not interpret the datasets properly. Every request gets a 404 error. 

## Steps to Reproduce

use a config like this and see 400 errors:

```yaml
receivers:
  libhoney:
    http:
      endpoint: 127.0.0.1:8080
      traces_url_paths:
        - "/1/events"
        - "/1/batch"
```

## Expected Result

It should take a request to /1/batch/{dataset} and process it. 

## Actual Result

Without the slash at the end of `- "/1/batch/`, it will only process requests that go to /1/batch which is not how libhoney forms URLs. 

### Collector version

v0.126.0

## Environment
OS: Docker

### OpenTelemetry Collector configuration

```yaml
receivers:
  libhoney:
    http:
      endpoint: 127.0.0.1:8080
      traces_url_paths:
        - "/1/events"
        - "/1/batch"
```

### Log output

```shell
curl -d '{"foo": "bar"}' http://127.0.0.1:8080/1/batch/dataset
404 page not found
```
