### ISSUE TITLE
[receiver/azuremonitorreceiver] Review our settings for scaling

### ISSUE THREAD

**Issue by andrewegel** [open-telemetry/opentelemetry-collector-contrib#40078]
### Describe the issue you're reporting

More or less this is our configuration:

```
azuremonitor:
    auth: default_credentials
    subscription_ids: [...one-subscription...]
    use_batch_api: true
    append_tags_as_attributes: true
    services:
    - "Microsoft.Network/loadBalancers"
    - "Microsoft.Network/natgateways"
    metrics:
      "Microsoft.Network/loadBalancers":
        "VipAvailability": [average]
        "DipAvailability": [average]
        "ByteCount": [total]
        "SYNCount": [count, total]
        "SnatConnectionCount": [total]
        "AllocatedSnatPorts": [average]
        "UsedSnatPorts": [average]
      "Microsoft.Network/natgateways":
        "SNATConnectionCount": [total]
        "ByteCount": [total]
        "DatapathAvailability": [average]
    collection_interval: 300s
    initial_delay: 1s
```

From this thread: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38895#discussion_r2087716774

I wanted input from the Authors of this receiver on what settings we should be using; Some infra stats about this environment:

* 25 NATs
* 486 LBs

In just one subscription in a lower environment; Comments about running this in a production scale aside, following other scraper patterns such as those in the gcpmonitoring receiver and a custom AWS CloudWatch we've built, we think we want to have a scrape interval of 5m given these numbers. But based on the discussion in this thread https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/38895#discussion_r2087716774 that wasn't how this receiver was intended to be ran as it'll only grab the last data point, when we want 1m granular data points within that 5m window; On the surface it looks like this code was designed around the idea that it'll scrape every 10s and only request 1m metrics when needed. Whats recommended here?

As an aside, even with a 5m scrape interval I see somewhat often error messages:

```
Exception:Microsoft.Online.QueryService.Contracts.QueryThrottledException: Cannot request more than 500000 time series per query. DataSource: MetricsStore. Message: Too many series requested. Total estimated requested time series:720265, Total requested for this partition:20579, Maximum allowed series count for this partition: 15714
```

(Full example at the bottom)

```
2025-05-13T20:55:02.705Z    error   azuremonitorreceiver@.../scraper_batch.go:460 failed to get Azure Metrics values data {"otelcol.component.id": "azuremonitor", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "subscription": "...", "region": "centralus", "resourceType": "Microsoft.Network/loadBalancers", "metrics": ["DipAvailability"], "resources": [...50 resources...], "response": {}, "responseError": "POST https://centralus.metrics.monitor.azure.com/subscriptions/.../metrics:getBatch\n--------------------------------------------------------------------------------\nRESPONSE 529: 529 \nERROR CODE UNAVAILABLE\n--------------------------------------------------------------------------------\n{\n  \"values\": [\n    {\n      \"starttime\": \"2025-05-13T20:50:24Z\",\n      \"endtime\": \"2025-05-13T20:54:24Z\",\n      \"interval\": \"PT1M\",\n      \"value\": [\n        {\n          \"id\": \"/subscriptions/.../resourceGroups/.../providers/Microsoft.Insights/metrics/DipAvailability\",\n          \"type\": \"Microsoft.Insights/metrics\",\n          \"name\": {\n            \"value\": \"DipAvailability\",\n            \"localizedValue\": \"Health Probe Status\"\n          },\n          \"displayDescription\": \"Average Load Balancer health probe status per time duration\",\n          \"unit\": \"Count\",\n          \"timeseries\": [],\n          \"errorMessage\": \"Query was throttled with reason: QueryTooExpensive. Requested Metric:slbv2centralus|DipHealth|DipAvailability. Output Dimensions: CaAddress,DipPort,LoadBalancerArmId,ProtocolType,VipAddress,VipPort. Dimension Filters: CaAddress,DipPort,HostAddress,IsProbeReturnedByHost,LoadBalancerArmId,ProtocolType,PublicIpArmId,Ring,VipAddress,VipPort. RequestedSamplingType: Count,Sum,NullableAverage,Max,Min. Start time: 5/13/2025 8:50:24 PM End time: 5/13/2025 8:53:24 PM. Resolution: 00:01:00, Resolution Function: Automatic. Last Value Mode: False, Context:MetricsMP, CustomerId:mdmquerycert.mdmrp.prod.windows.azure.net. TraceID:{e619c7af-c7bd-42a9-a538-c56a274d360a};AzSubId=...;AzResType=Microsoft.Network/loadBalancers;AzRegion=centralus;, IsUserQuery:1, ClientTimeout:00:00:59.9990000, ClientName:GatewayService-API->QueryServiceCoordinator, ElapsedTime(ms):42, Exception:Microsoft.Online.QueryService.Contracts.QueryThrottledException: Cannot request more than 500000 time series per query. DataSource: MetricsStore. Message: Too many series requested. Total estimated requested time series:720265, Total requested for this partition:20579, Maximum allowed series count for this partition: 15714. Full Metric Name = (slbv2centralus,DipHealth,DipAvailability) | Dimension Names = (slbv2centralus,DipHealth,DipAvailability)-CaAddress,DipPort,HostAddress,IsProbeReturnedByHost,LoadBalancerArmId,ProtocolType,PublicIpArmId,Ring,VipAddress,VipPort,VnetId. Composite Metric: False. Cross Stamp Request: False.\\r\\n   at Microsoft.Online.Metrics.QueryServiceCoordinator.Throttling.QueryRestrictionThrottlingManager.IsQueryThrottledOnResultsCount(Exception exception, Int64 maxQueryCombinations, String combinedDataSourceString, FullMetricName2 outputMetricName, IReadOnlyList`1 dimensionNames, QueryDataSource combinedDataSource, Boolean isComposite) in 
```
