### ISSUE TITLE
scopeSpan.Atrributes not found in doris

### ISSUE THREAD

**Issue by pioneerlfn** [open-telemetry/opentelemetry-collector-contrib#40088]
### Component(s)

exporter/doris

## Description
scopeSpan.Attributes not write to doris

## Steps to Reproduce
select a record from otel.otel_traces, and check the field, we can see scopeSpan.name, scopeSpan.version, but can't found the field scopeSpan.Atrributes

## Expected Result

scopeSpan.Attributes found in doris table

### Collector version

latest

## Environment
any enviromen t

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

connectors:
  spanmetrics:
    namespace: span.metrics
    metrics_flush_interval: 30s
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: db.system
      - name: db.operation
      - name: db.name
      - name: db.statement

processors:
  tail_sampling:
    policies:
      #      - name: error-sampling
      #  type: status_code
      #  status_code: {status_codes: [ERROR]}
      #- name: latency-sampling
      #  type: latency
      #  latency: {threshold_ms: 100}
      - name: rate-sampling
        type: probabilistic
        probabilistic: {sampling_percentage: 10}

exporters:
  prometheusremotewrite:
    endpoint: http://localhost:9090/api/v1/write
    target_info:
      enabled: true
  doris:
    endpoint: http://xxx.xxx.xxx.xxx:8030
    database: otel
    username: root
    password:
    table:
      logs: otel_logs
      traces: otel_traces
      metrics: otel_metrics
    create_schema: true
    mysql_endpoint: xxx.xxx.xxx.xxx:9030
    history_days: 0
    create_history_days: 0
    replication_num: 1
    timezone: Asia/Shanghai
    timeout: 5s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 1000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces/metrics:
      receivers: [otlp]
      exporters: [spanmetrics]
    traces/storage:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [doris]

    metrics:
      receivers: [spanmetrics]
      exporters: [prometheusremotewrite]
```

### Log output

```shell

```
