### ISSUE TITLE
[processor/resource] "failed to create 'resource' process..." since upgrading from 0.123

### ISSUE THREAD

**Issue by defields923** [open-telemetry/opentelemetry-collector-contrib#40101]
### Component(s)

processor/resource

## Description
I am using the collector-contrib docker image tag:latest. A month ago, 0.123.0 was tagged, which worked fine. Since I am using "latest," a new build of my docker image pulled version 0.126.0 (tagged 2 days ago), and now the 'validate' command is returning an error. I have narrowed it down to the offending processor by process of elimination, and it is caused by the "resource" processor.

## Steps to Reproduce
1. Add a simple resource processor, in my case:
  resource:
    attributes:
      - key: otel.collector
        action: upsert
        value: ${ENV}
      - key: process.runtime.description
        action: delete

2. add to any pipeline:
      processors: [memory_limiter, resource, batch]

3. build image from tagged contrib:
"FROM otel/opentelemetry-collector-contrib:latest (or 0.126.0)"

## Expected Result
Collector launches as usual

## Actual Result
Docker build fails when attempting to run "/otelcol-contrib validate ..."

### Collector version

0.126.0

## Environment
OS: MacOS 15.4.1 (24E263)
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
processors:
   resource:
    attributes:
      - key: otel.collector
        action: upsert
        value: ${ENV}
      - key: process.runtime.description
        action: delete

service:
 pipelines:
  traces:
   processors: [memory_limiter, resource, batch]
... repeat for logs, metrics
```

### Log output

```shell
0.303 Error: failed to build pipelines: failed to create "resource" processor, in pipeline "logs": error creating AttrProc. Either field "value", "from_attribute" or "from_context" setting must be specified for 0-th action
0.303 2025/05/15 18:43:01 collector server run finished with error: failed to build pipelines: failed to create "resource" processor, in pipeline "logs": error creating AttrProc. Either field "value", "from_attribute" or "from_context" setting must be specified for 0-th action
```
