### ISSUE TITLE
Span metrics calls count always 0 with delta aggregation temporality

### ISSUE THREAD

**Issue by jsonlsy** [open-telemetry/opentelemetry-collector-contrib#40139]
### Component(s)

connector/spanmetrics

## Description
Kudos to @san-san for finding this bug.

Looks like this PR introduced a bug when using delta aggregation temporality: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39052

With delta aggregation temporality, resourceMetrics get purged after exporting the metrics [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.126.0/connector/spanmetricsconnector/connector.go#L333). So, the metrics generated are always newly created ones and have `isFirst` set to true. This results in the value always getting overwritten [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.126.0/connector/spanmetricsconnector/internal/metrics/metrics.go#L394).

Can confirm that this is not an issue in `v0.123.0` (i.e. prior to the first value logic)

## Steps to Reproduce
- Run collector with the span metrics connector
- Send a span to the collector 
- Wait for span metrics to be flushed. The value of the `calls` metrics is 0 instead of 1.
- Send another span with the same relevant attributes
- Wait for span metrics to be flushed. The value of the new `calls` metrics is 0 instead of 1.

## Expected Result
Data point value of the emitted `traces.span.metrics.calls` metric should be 1 after each sent span

## Actual Result
Data point value of the emitted `traces.span.metrics.calls` metric is 0 after each sent span

### Collector version

v0.126.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

connectors:
  spanmetrics:
    exclude_dimensions: 
      - span.name
      - span.kind
      - status.code
    metrics_flush_interval: 10s
    aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
    
exporters:
  file:
    path: /tmp/spanmetrics.json
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [spanmetrics]
    metrics:
      receivers: [spanmetrics]
      exporters: [file]
```

## Proposed solution
I think we can check the aggregation type [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.126.0/connector/spanmetricsconnector/internal/metrics/metrics.go#L394) so that we set the first value to 0 for cumulative metrics only. If my understanding is correct, the issue addressed by https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/39052 applies to cumulative metrics only.
