### ISSUE TITLE
Counter connector metrics value doesn't increase

### ISSUE THREAD

**Issue by Frefreak** [open-telemetry/opentelemetry-collector-contrib#40143]
### Component(s)

connector/count

## Description

The count metrics seems to be always 1 (or zero/not showing up when initialized)

## Steps to Reproduce

1. Start the collector
2. Send traces to the collector
3. Observe the metrics in Prometheus (port 8889)
4. The counter value will always show 1, indicating that the counter is not persisting between measurements

## Expected Behavior
The counter should maintain its value and increment properly, showing the cumulative count of traces over time.

## Actual Behavior
The counter value resets to 1 each time

### Collector version

0.126.0

## Environment
OS: macOS

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

connectors:
  count:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [count, debug]
    metrics:
      receivers: [count]
      exporters: [prometheus]

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
```

### Log output

```shell

```

### Additional context

For a brief look the consumer logic seems always create a new counter for each batch.
