### ISSUE TITLE
How to remove a label from a metric.

### ISSUE THREAD

**Issue by ixiaoyi93** [open-telemetry/opentelemetry-collector-contrib#40197]
## Description
I have a metric and corresponding label as follows.
```
{
  __name__="runtime_jvm_gc_timeOrCount_v2",
  collector_name="Copy",
  container="alphanote",
  container_id="6f8690a00aa2d8248140b73795013a0cf8f1c4d98f5ac50c116dd68849b00d6c",
  endpoint="http-metrics",
  env="prod",
  exported_instance="alpha-prod.alphanote-847697457f-wxfl9.alphanote",
  exported_job="alphanote",
  exported_namespace="alpha-prod",
  gc_type="Young GC",
  host_arch="amd64",
  host_name="172.18.31.237",
  instance="10.16.0.43:8889",
  job="metrics-aggregation-collector",
  k8s_deployment_name="alphanote",
  k8s_replicaset_name="alphanote-847697457f",
  name="jvm_gc_time",
  namespace="grafana-stack",
  nodename="cn-beijing.172.18.6.111",
  os_description="Linux 5.10.134-17.2.al8.x86_64",
  os_type="linux",
  pod="metrics-aggregation-collector-7c8b784578-wpsf5",
  pod_name="metrics-aggregation-collector-7c8b784578-wpsf5",
  podip="10.16.0.32",
  podname="alphanote-847697457f-wxfl9",
  process_command_line="/opt/java/jre/bin/java -javaagent:/otel-auto-instrumentation-java/javaagent.jar -Xms1024M -Xmx1024M -jar /data/app/note.war",
  process_executable_path="/opt/java/jre/bin/java",
  process_pid="18",
  process_runtime_description="Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 25.341-b10",
  process_runtime_name="Java(TM) SE Runtime Environment",
  process_runtime_version="1.8.0_341-b10",
  service="metrics-aggregation-collector",
  service_instance_id="alpha-prod.alphanote-847697457f-wxfl9.alphanote",
  service_name="alphanote",
  service_version="prod-739cb6c3-4",
  telemetry_distro_name="opentelemetry-java-instrumentation",
  telemetry_distro_version="2.3-20250228",
  telemetry_sdk_language="java",
  telemetry_sdk_name="opentelemetry",
  telemetry_sdk_version="2.3-20250228",
  unique_cluster_account="Primary_Account",
  unique_cluster_id="ce87f67e991864eb4945a9c8eb0c64c96",
  unique_cluster_name="aliyun-public-observability",
  unique_cluster_region="cn-beijing"
}
```

In order to save storage resources, I want to delete some useless labes. Currently, the following prometheus configuration is used to delete related lables.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-aggregation-collector
  namespace: grafana-stack
  labels:
    helm.sh/chart: opentelemetry-collector-0.118.0
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: metrics-aggregation-collector
    app.kubernetes.io/version: "0.120.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: standalone-collector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
      app.kubernetes.io/instance: metrics-aggregation-collector
      component: standalone-collector
  endpoints:
    - interval: 10s
      port: metrics
      metricRelabelings:
        - sourceLabels: [server]
          regex: "unknown"
          action: drop
        - action: labeldrop
          regex: 'container_id'
        - action: labeldrop
          regex: 'pod'
        - action: labeldrop
          regex: 'pod_name'
        - action: labeldrop
          regex: 'os_type'
        - action: labeldrop
          regex: 'host_arch'
        - action: labeldrop
          regex: 'container_id'
        - action: labeldrop
          regex: 'exported_job'
        - action: labeldrop
          regex: 'os_description'
        - action: labeldrop
          regex: 'exported_instance'
        - action: labeldrop
          regex: 'exported_namespace'
        - action: labeldrop
          regex: 'k8s_deployment_name'
        - action: labeldrop
          regex: 'k8s_replicaset_name'
        - action: labeldrop
          regex: 'process_command_line'
        - action: labeldrop
          regex: 'process_pid'
        - action: labeldrop
          regex: 'process_runtime_description'
        - action: labeldrop
          regex: 'process_runtime_name'
        - action: labeldrop
          regex: 'process_runtime_version'
        - action: labeldrop
          regex: 'telemetry_distro_name'
        - action: labeldrop
          regex: 'telemetry_distro_version'
        - action: labeldrop
          regex: 'process_executable_path'
  jobLabel: "metrics-aggregation-collector"
  namespaceSelector:
    matchNames:
      - grafana-stack
```

Although this mode is effective, it seems to cause a certain amount of CPU and memory resource pressure on opentelemetry-collector, resulting in the loss of some indicators. For example, some Java services cannot query JVM monitoring and thread pool monitoring.

Therefore, I use `processors/attributes` to clean the indicator data and store it directly in prometheus. However, I always fail to achieve the desired effect. The configuration is as follows.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-gateway
  namespace: grafana-stack
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: collector-gateway
    app.kubernetes.io/version: "0.115.1"
    app.kubernetes.io/component: standalone-collector
data:
  relay: |
    connectors:
      servicegraph:
        latency_histogram_buckets:
        - 100ms
        - 200ms
        - 500ms
        - 1s
        - 5s
        - 10s
        metrics_flush_interval: 30s
        store:
          max_items: 10
          ttl: 1s
      spanmetrics:
        aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE
        dimensions:
        - name: http.request.method
        - name: http.response.status_code
        - name: http.route
        dimensions_cache_size: 1000
        events:
          dimensions:
          - name: exception.type
          - name: exception.message
          enabled: true
        exemplars:
          enabled: true
        histogram:
          explicit:
            buckets:
            - 100us
            - 1ms
            - 2ms
            - 6ms
            - 10ms
            - 100ms
            - 250ms
        metrics_expiration: 5m
        metrics_flush_interval: 15s
        resource_metrics_key_attributes:
        - service.name
        - telemetry.sdk.language
        - telemetry.sdk.name
    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: tempo-distributor:4317
        tls:
          insecure: true
      loadbalancing:
        routing_key: "service"
        protocol:
          otlp:
            timeout: 1s
            tls:
              insecure: true
        resolver:
          k8s:
            service: metrics-aggregation-collector.grafana-stack
            ports:
              - 4317
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch:
        send_batch_size: 10000
        timeout: 0s
      filter:
        error_mode: ignore
        traces:
          span:
          - attributes["db.statement"] == "INFO server"
          - attributes["operation"] == "ReadOperationHandler.handle"
          - IsMatch(attributes["http.route"], ".*/health.*")
      attributes/droptags:
        actions:
        - action: delete
          key: 'container.id'
        - action: delete
          key: 'pod'
        - action: delete
          key: 'pod_name'
        - action: delete
          key: 'os_type'
        - action: delete
          key: 'host.arch'
        - action: delete
          key: 'exported.job'
        - action: delete
          key: 'os.description'
        - action: delete
          key: 'exported_instance'
        - action: delete
          key: 'exported_namespace'
        - action: delete
          key: 'exported_job'
        - action: delete
          key: 'k8s.deployment.name'
        - action: delete
          key: 'k8s.replicaset.name'
        - action: delete
          key: 'process.command_line'
        - action: delete
          key: 'process.pid'
        - action: delete
          key: 'process.runtime_description'
        - action: delete
          key: 'process.runtime.name'
        - action: delete
          key: 'process.runtime.version'
        - action: delete
          key: 'telemetry.distro.name'
        - action: delete
          key: 'telemetry.distro.version'
        - action: delete
          key: 'process.executable.path'
      k8sattributes:
        passthrough: true
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      transform:
        error_mode: ignore
        trace_statements:
          - context: resource
            statements:
              - set(attributes["env"], attributes["k8s.namespace.name"])
              - replace_match(attributes["env"], "*inner", "inner")
              - replace_match(attributes["env"], "*prod", "prod")
              - replace_all_patterns(attributes, "key", "k8s\\.namespace\\.name", "namespace")
              - replace_all_patterns(attributes, "key", "k8s\\.container\\.name", "container")
              - replace_all_patterns(attributes, "key", "k8s\\.node\\.name", "nodename")
              - replace_all_patterns(attributes, "key", "k8s\\.pod\\.ip", "podip")
              - replace_all_patterns(attributes, "key", "k8s\\.pod\\.name", "podname")
        metric_statements:
          - context: resource
            statements:
              - set(attributes["env"], attributes["k8s.namespace.name"])
              - replace_match(attributes["env"], "*inner", "inner")
              - replace_match(attributes["env"], "*prod", "prod")
              - replace_all_patterns(attributes, "key", "k8s\\.namespace\\.name", "namespace")
              - replace_all_patterns(attributes, "key", "k8s\\.container\\.name", "container")
              - replace_all_patterns(attributes, "key", "k8s\\.node\\.name", "nodename")
              - replace_all_patterns(attributes, "key", "k8s\\.pod\\.ip", "podip")
              - replace_all_patterns(attributes, "key", "k8s\\.pod\\.name", "podname")
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    service:
      extensions:
      - health_check
      pipelines:
        traces:
          exporters:
          - otlp
          - spanmetrics
          - servicegraph
          - debug
          processors:
          - k8sattributes
          - transform
          - filter
          - memory_limiter
          - batch
          receivers:
          - otlp
        metrics:
          exporters:
          - loadbalancing
          - debug
          processors:
          - attributes/droptags
          - k8sattributes
          - transform
          - filter
          - memory_limiter
          - batch
          receivers:
          - otlp
          - servicegraph
          - spanmetrics
      telemetry:
        logs:
          level: debug
        metrics:
          address: ${env:MY_POD_IP}:8888
```

How can I achieve my effect through `processors/attributes`?

**Comment by Frapschen** [comment]
I recommand your to use transformprocessor.

for `process.xxx` label, you can use:
```
transform:
  error_mode: ignore
  metric_statements:
    - context: Datapoint
      statements:
        - delete_matching_keys(datapoint.attributes, "process\.(command_line|pid|runtime_description|runtime\.name|runtime\.version|executable\.path)")
```
