### ISSUE TITLE
[tailsamplingprocessor] Ignore policy

### ISSUE THREAD

**Issue by LaserPhaser** [open-telemetry/opentelemetry-collector-contrib#40208]
### Is your feature request related to a problem? Please describe.

I would like to see ignore policy that does not affect any other policies. 
For example I would like to sample all traces with 500 http error code 
But I have 2 services that I do not care about, or they are not fixed yet and it's known.
So I want to ignore exact 2 services in making decisions about drop or sample.

Basically it should work absolutely the same as drop/keep evaluation, but if the span matched his policy appears it just must be ignored. 

I can work very well in cases like (I want to sample all "error" traces, but I want to ignore traces that have only 404 codes and marked like errors.)

### Describe the solution you'd like

Right now I did it with dirty patch in evaluate function of status_code.go

```
	decision, service := hasSpanWithCondition(batches, func(span ptrace.Span, serviceName string) bool {
		for _, statusCode := range r.statusCodes {
			if span.Status().Code() == statusCode {
				if v, ok := span.Attributes().Get("http.status_code"); ok {
					value := v.Int()
					if value == 404 {
						return false
					}
				}
```

But it would be cool to see it configurable like drop/keep policies.

**Comment by Frapschen** [comment]
@LaserPhaser, please refer to the example provided at https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor#a-practical-example. You will notice that **Rule 1** closely mirrors your scenario.

**Comment by LaserPhaser** [comment]
@Frapschen Is it work like, ignore span in taking decision, or it's skip the span and trace  if match the rule? 
I suppose that in Rule 1 the policy is: 
Do not sample team-a spans. 

But I want to have a policy: 
Ignore team-a samples in taking decision (keep them if trace will be sampled, but do not use them in taking decision)

For example:
We have a policy to keep all Error traces and Ingore all 404 http.satus_codes


1st case:
We have trace with 3 spans:
1st span = 200ok 
2nd span = 404 (span marked as Error)
3rd span = 500  (span marked as Error)

Trace must be sampled because we have 3rd span with Error mark. 

2nd case:

1st span = 200ok 
2nd span = 404 (span marked as Error)
3rd span = 200ok

Trace must be not sampled, because we have Ignore rule - do not case about 404 errors in http.status_code

**Comment by portertech** [comment]
@LaserPhaser did you attempt to use `ottl_condition` policies? Could have used one instead of patching `status_code`. I am concerned about the potential complexity something like `skip` policy introduces. I wonder if you've exhausted all options.

**Comment by portertech** [comment]
For example, 

``` yaml
processors:
  tail_sampling:
    policies:
      - name: capture-http-500-errors-except-foobar
        type: ottl_condition
        ottl_condition:
          error_mode: ignore
          span:
            - 'attributes["http.status_code"] == 500 and resource.attributes["service.name"] != "foobar"'
```

OR

``` yaml
processors:
  tail_sampling:
    policies:
      - name: capture-error-spans-except-404
        type: ottl_condition
        ottl_condition:
          error_mode: ignore
          span:
            - 'status.code == STATUS_CODE_ERROR and attributes["http.status_code"] != 404'
```
