### ISSUE TITLE
otel collector receiver/filelog is missing events after a log file rotates

### ISSUE THREAD

**Issue by punyasahoo** [open-telemetry/opentelemetry-collector-contrib#40200]
### Describe the issue you're reporting

Using the otel collector filelog receiver to get Openshift audit files and send them to splunk. I noticed that after a log file is rotated some events at the end the rotated log file are missing. I was triggered because in the collector logs this is often logged as a json parser error due to not getting a complete event line.

How can this be prevented? I read about extending the filelog include pattern with the pattern of the rotated log files. But will this not result in duplicated events because an audit.log will be read again after it is moved to a different name?

The otel collector configuration

```yaml
exporters:
 splunk_hec/audit:
   token: ${SPLUNK_HEC_TOKEN}
   endpoint: https://my.splunk.forwarder:8088/services/collector
   disable_compression: false
   tls:
     insecure_skip_verify: false
     ca_file: /etc/splunk/certs/hec_ca_file
   idle_conn_timeout: 10s
   profiling_data_enabled: false
   retry_on_failure:
     enabled: true
     initial_interval: 5s
     max_elapsed_time: 300s
     max_interval: 30s
   sending_queue:
     enabled: true
     num_consumers: 10
     queue_size: 5000
extensions:
 file_storage:
   directory: /var/addon/splunk/otel_pos
 health_check:
   endpoint: 0.0.0.0:13133
processors:
 batch/audit:
   timeout: 5s
   send_batch_size: 2048
   send_batch_max_size: 8192
 filter/audit_logs:
   logs:
     log_record:
       - IsMatch(ParseJSON(body)["verb"], "get") and not IsMatch(ParseJSON(body)["requestURI"], ".*/secrets/.*$")
       - IsMatch(ParseJSON(body)["verb"], "update") and IsMatch(ParseJSON(body)["requestURI"], "/apis/conjur.cyberark.com/v1/namespaces/tenant-conjur-follower.*/conjurfollowers/conjur-follower.*/status$")
       - IsMatch(ParseJSON(body)["verb"], "patch") and IsMatch(ParseJSON(body)["requestURI"], "/apis/conjur.cyberark.com/v1/namespaces/tenant-conjur-follower.*/conjurfollowers/conjur-follower.*/status$")
       - IsMatch(ParseJSON(body)["verb"], "list")
       - IsMatch(ParseJSON(body)["verb"], "watch")
 resource/add_log_metadata:
   attributes:
     - action: insert
       key: com.splunk.index
       value:  gen_xxxx_yy
     - action: insert
       key: k8s.cluster.name
       value: ${K8S_CLUSTERNAME}
     - action: insert
       key: log_type
       value: audit
     - action: insert
       key: host.name
       value: ${K8S_NODE_NAME}
 memory_limiter:
   check_interval: 2s
   limit_percentage: 80
 resourcedetection:
   detectors:
     - env
     - system
   override: true
   timeout: 15s
receivers:
 filelog/openshift-audit:
   include:
     - /var/log/oauth-apiserver/audit.log
     - /var/log/kube-apiserver/audit.log
     - /var/log/openshift-apiserver/audit.log
   start_at: end
   storage: file_storage
   retry_on_failure:
     enabled: true
   include_file_path: true
   include_file_name: true
   poll_interval: 1ms
   operators:
     - type: json_parser
       id: json_parser
       parse_from: body
       on_error: send
       timestamp:
         parse_from: attributes.requestReceivedTimestamp
         layout: '%Y-%m-%dT%H:%M:%S.%f%z'
     - type: copy
       from: attributes['log.file.path']
       to: attributes['com.splunk.source']
 nop:
service:
 extensions:
   - file_storage
   - health_check
 pipelines:
   logs/audit:
     receivers:
       - filelog/openshift-audit
     processors:
       - filter/audit_logs
       - resource/add_log_metadata
       - memory_limiter
       - batch/audit
     exporters:
       - splunk_hec/audit
 telemetry:
   metrics:
     address: 0.0.0.0:8890
   logs:
     level: info
```

Below is the log 

```console
2025-05-20T19:00:02.624Z	error	helper/transformer.go:122	Failed to process entry	{"otelcol.component.id": "filelog/openshift-audit", "otelcol.component.kind": "Receiver", "otelcol.signal": "logs", "operator_id": "json_parser", "operator_type": "json_parser", "error": "json: string unexpected end of JSON input", "action": "send", "entry.timestamp": "0001-01-01T00:00:00.000Z", "log.file.name": "audit.log", "log.file.path": "/var/log/kube-apiserver/audit.log"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*TransformerOperator).HandleEntryError
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/helper/transformer.go:122
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ParseWith
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/helper/parser.go:142
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWithCallback
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/helper/parser.go:111
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWith
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/helper/parser.go:98
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/json.(*Parser).Process
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/parser/json/parser.go:30
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*TransformerOperator).ProcessBatchWith
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/helper/transformer.go:82
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/json.(*Parser).ProcessBatch
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/parser/json/parser.go:25
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*WriterOperator).WriteBatch
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/helper/writer.go:55
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/input/file.(*Input).emitBatch
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/input/file/input.go:48
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).readContents
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/fileconsumer/internal/reader/reader.go:209
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).ReadToEnd
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/fileconsumer/internal/reader/reader.go:116
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/fileconsumer/file.go:169
2025-05-20T19:00:02.624Z	error	helper/transformer.go:122	Failed to process entry	{"otelcol.component.id": "filelog/openshift-audit", "otelcol.component.kind": "Receiver", "otelcol.signal": "logs", "operator_id": "json_parser", "operator_type": "json_parser", "error": "expected { character for map value", "action": "send", "entry.timestamp": "0001-01-01T00:00:00.000Z", "log.file.name": "audit.log", "log.file.path": "/var/log/kube-apiserver/audit.log"}
```

**Comment by Frapschen** [comment]
@punyasahoo, please format your configuration to make it more readable.

> I was triggered because in the collector logs this is often logged as a json parser error due to not getting a complete event line.

Please also provide the error logs.

**Comment by punyasahoo** [comment]
[audit.txt](https://github.com/user-attachments/files/20391666/audit.txt)

**Comment by Frapschen** [comment]
ping Pinging code owners: @andrzej-stencel

**Comment by andrzej-stencel** [comment]
I suspect you're experiencing this error because the poll interval is set to a very low value: `poll_interval: 1ms`. The File Log receiver is designed to read any logs written to the rotated files, but it will only read logs written since the previous poll interval. With the poll interval as low as `1ms`, it's very likely that the next poll happens before the log producer completes writing to the file. Increasing the poll interval increases the likelihood of the log producer completing the writing to the rotated file.

> I read about extending the filelog include pattern with the pattern of the rotated log files. But will this not result in duplicated events because an audit.log will be read again after it is moved to a different name?

Including rotated files in the match pattern should not result in duplicated events, because the File Log receiver identifies files not based on file names, but based on their fingerprint, i.e. the initial part of the file (by default `1kb`, configured via `fingerprint_size`).

I would recommend increasing the poll interval, unless you have a reason to keep it this short, and if you do have a reason, please share so that we can all learn. You can also change the include patterns to match the rotated files, however on the first start of the changed configuration the old (previously untracked) rotated files will be re-ingested unless you delete or rename the rotated files before restarting the collector with the updated configuration.

**Comment by punyasahoo** [comment]
i changed my config to below but still i am getting error 

```yaml
filelog/openshift-audit:
   include:
     - /var/log/oauth-apiserver/audit.log*
     - /var/log/kube-apiserver/audit.log*
     - /var/log/openshift-apiserver/audit.log*
   start_at: end
   storage: file_storage
   retry_on_failure:
     enabled: true
   include_file_path: true
   include_file_name: true
   poll_interval: 500ms
   fingerprint_size: 1kb
```


Error:

```
2025-06-12T11:49:55.875Z	error	adapter/receiver.go:61	ConsumeLogs() failed	{"otelcol.component.id": "filelog/openshift-audit", "otelcol.component.kind": "Receiver", "otelcol.signal": "logs", "error": "failed to eval condition: IsMatch(ParseJSON(body)[\"verb\"], \"list\"), error getting value in ottl.StandardStringLikeGetter[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottllog.TransformContext]: json: string unexpected end of JSON input; failed to eval condition: IsMatch(ParseJSON(body)[\"verb\"], \"list\"), error getting value in ottl.StandardStringLikeGetter[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottllog.TransformContext]: invalid character 'W' looking for beginning of value", "errorCauses": [{"error": "failed to eval condition: IsMatch(ParseJSON(body)[\"verb\"], \"list\"), error getting value in ottl.StandardStringLikeGetter[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottllog.TransformContext]: json: string unexpected end of JSON input"}, {"error": "failed to eval condition: IsMatch(ParseJSON(body)[\"verb\"], \"list\"), error getting value in ottl.StandardStringLikeGetter[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottllog.TransformContext]: invalid character 'W' looking for beginning of value"}]}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/adapter.(*receiver).consumeEntries
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/adapter/receiver.go:61
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*BatchingLogEmitter).flusher
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.122.0/operator/helper/emitter.go:171
2025-06-12T12:23:31.091Z	info	fileconsumer/file.go:265	Started watching file	{"otelcol.component.id": "filelog/openshift-audit", "otelcol.component.kind": "Receiver", "otelcol.signal": "logs", "component": "fileconsumer", "path": "/var/log/kube-apiserver/audit.log"}
```
