### ISSUE TITLE
[loadbalancingexporter] Logs - duplicate traffic + routing_key not working

### ISSUE THREAD

**Issue by szibis** [open-telemetry/opentelemetry-collector-contrib#40223]
### Component(s)

exporter/loadbalancing

## Description

We grab logs via filelog and later do some mangling. Send via loadbalancer logs OTLP.
Vector accepts on gRPC Opentelemetry. 
We need this to make Throttling effective for each `service.name`, any type of sharding is needed here because otherwise this make rate limiting per pod not per service kind of useless.

## Expected Result

Send balanced from detected endpoints from headless service based on service key send to specific Vector STS as much close all same services to same k8s vector pod.

## Actual Result

We would like to achieve per service send to specific Vector Statefulset but actualy traffic is duplicated we get double the logs we getting through filelog

All is working when sending otlphttp/otlp but when we use loadbalancing exporter with otlp it behaves differently and duplicates traffic in collector - once loadbalancing introduced I think on that component.

moment of switch in Vector is visible
<img width="834" alt="Image" src="https://github.com/user-attachments/assets/b2cad3e4-781c-4b57-b73f-e080b6af622f" />
In Otel also visible 
<img width="574" alt="Image" src="https://github.com/user-attachments/assets/d23aff37-8bad-43ef-baf5-d6b48ccb99ae" />
I am also not sure if routing_key actually working in Logs which is bad to.

### Collector version

0.123.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
        loadbalancing/logs:
          routing_key: "service"
          protocol:
            otlp:
              compression: gzip
              read_buffer_size: 0
              write_buffer_size: 524288 # default 512 * 1024 - 0.5MB fro HTTP client
              tls:
                insecure: true
              timeout: 1s
              keepalive:
                time: 600m
                timeout: 30s
          resolver:
            # use k8s service resolver, if collector runs in kubernetes environment
            k8s:
              service: vector-headless.vector
              ports:
                - 4317
          timeout: 5s
          sending_queue:
            enabled: true
            num_consumers: 5
            queue_size: 30000
            storage: file_storage/psq
            block_on_overflow: true
            sizer: "requests"
          retry_on_failure:
            enabled: true
            initial_interval: 10s
            randomization_factor: 0.7
            multiplier: 1.5
            max_interval: 30s
            max_elapsed_time: 300s
```

### Log output

```shell

```
