### ISSUE TITLE
k8sattributes doesn't collect k8s labels

### ISSUE THREAD

**Issue by hunter86bg** [open-telemetry/opentelemetry-collector-contrib#40238]
### Component(s)

processor/k8sattributes, receiver/kubeletstats

## Description
k8sattributes doesn't pull any kubernetes pod labels but it doesn't provide any error or warning about it.

## Steps to Reproduce
1. Deploy the otel operator via helm and ensure manager.createRbacPermissions is set to 'true'
2. Validate the cluserrole has these permissions:
```
rules:
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - watch
  - list
```
3. Create an additional role and rolebinding:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-reader
rules:
- apiGroups: [""] # Core API group
  resources: ["pods", "namespaces", "nodes"]
  verbs: ["get", "list", "watch"]
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-reader-binding
subjects:
- kind: ServiceAccount
  name: <SA NAME>
  namespace: <namespace>
roleRef:
  kind: ClusterRole
  name: otel-collector-reader
  apiGroup: rbac.authorization.k8s.io
```
4. Create OpenTelemetryCollector:
```
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  priorityClassName: "mission-critical-pods"
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "services"
      effect: "NoSchedule"
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 125m
      memory: 128Mi
  mode: daemonset
  managementState: managed
  config:
    receivers:
      # For more details check https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md
      kubeletstats:
        collection_interval: 60s
        auth_type: "serviceAccount"
        # Escape ${} as FluxCD will expand it
        endpoint: "$${env:K8S_NODE_NAME}:10250"
        metric_groups:
          - pod
          - container
          - node

    exporters:
      otlp:
        endpoint: "<OTEL_ENDPOINT>:4317"
        tls:
          insecure: true
        sending_queue:
          # Enables a queue for handling network blips and temporary unavailability of the gateway.
          enabled: true
          num_consumers: 2    # Number of goroutines reading from the queue and sending data.
          queue_size: 5000 # Max number of batches allowed in the queue.

        retry_on_failure:
          # Configures retries for failed export attempts.
          enabled: true
          initial_interval: 5s # Time to wait after the first failure before retrying.
          max_interval: 30s    # Max time to wait between retries.
          max_elapsed_time: 0s # Retry for ever

        # Most probably we don't need it as compression require more CPU
        # compression: gzip
      # Debug Exporter
      debug:
        verbosity: detailed # valid values are basic, normal and detailed
        # sampling_initial: 5

    # Needed for liveliness/Readiness probes
    extensions:
      health_check: {}

    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        metrics:
          receivers:
          - kubeletstats
          processors:
            # A common and recommended order for the processors:
            # 1. Add/modify resource attributes.
            # 2. Apply memory limits before batching or heavy processing.
            # 3. Batch data before exporting.
            - k8sattributes
            - resource/debug
            - transform/promote_labels
            - memory_limiter
            - batch
          exporters:
            - otlp
            - debug
      extensions:
        - health_check

    processors:
      # Order of the processors is defined in spec.config.service.pipelines.processors
      batch:
        # Max number of items (spans, metrics, logs) in a batch.
        send_batch_size: 8192
        # Max time to wait before sending an incomplete batch.
        timeout: 1s
        # Optional: Max size of a batch in bytes (0 means no limit based on byte size).
        # send_batch_max_size: 0

      # --- Memory Limiter (to prevent OOMKills) ---
      memory_limiter:
        check_interval: 5s
        limit_percentage: 75
        # Sets the difference (as a % of total available memory) between the 'limit_percentage' (hard limit)
        # and a lower "soft limit".
        # - Hard Limit for refusing data: 'limit_percentage' (e.g., 75%).
        # - Soft Limit for aggressive GC: 'limit_percentage' - 'spike_limit_percentage' (e.g., 75% - 15% = 60%).
        # So, aggressive GC starts if memory exceeds 60%; data is refused if it exceeds 75%.
        spike_limit_percentage: 15 # Additional percentage allowed for spikes above the `limit_percentage`.
                                  # Effectively, measures will be taken if usage exceeds this combined threshold for too long.

      # For help use https://opentelemetry.io/docs/platforms/kubernetes/collector/components/#kubernetes-attributes-processor
      k8sattributes:
          auth_type: serviceAccount
          extract:
            # This section is for extracting ARBITRARY K8s labels
            labels:
            # Example from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30474#issue-2078300868
            - tag_name: k8s.labels.$$1
              key_regex: (.*)
              from: pod

          # filter:
          #   node_from_env_var: K8S_NODE_NAME
          passthrough: true
          # Order matters here
          pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
          - sources:
            - from: resource_attribute
              name: k8s.pod.ip
          - sources:
            - from: resource_attribute
              name: k8s.pod.uid
          - sources:
            - from: connection

      transform/promote_labels:
        metric_statements:
          # The context is 'datapoint', meaning these operations apply to individual metric data points.
          - context: datapoint
            statements:
              - set(datapoint.attributes["service"], resource.attributes["k8s.labels.service"])

      # DEBUG #
      resource/debug:
        attributes:
          - action: insert
            key: debug_resource_present
            value: "true"

```

## Expected Result
To see any labels in k8s.labels

## Actual Result
No labels extracted at all:
```
ResourceMetrics #85
Resource SchemaURL: 
Resource attributes:
     -> k8s.pod.uid: Str(4e9a9258-27f9-4c0f-82f5-1cd321ef2352)
     -> k8s.pod.name: Str(podname1)
     -> k8s.namespace.name: Str(Namespace123)
     -> k8s.container.name: Str(Name123)
     -> debug_resource_present: Str(true)
```

### Collector version

0.123.0

## Environment
GKE 1.31.7-gke.1265000.

### OpenTelemetry Collector configuration

```yaml
receivers:
      # For more details check https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/kubeletstatsreceiver/documentation.md
      kubeletstats:
        collection_interval: 60s
        auth_type: "serviceAccount"
        # Escape ${} as FluxCD will expand it
        endpoint: "$${env:K8S_NODE_NAME}:10250"
        metric_groups:
          - pod
          - container
          - node

    exporters:
      otlp:
        endpoint: "<OTEL_ENDPOINT>:4317"
        tls:
          insecure: true
        sending_queue:
          # Enables a queue for handling network blips and temporary unavailability of the gateway.
          enabled: true
          num_consumers: 2    # Number of goroutines reading from the queue and sending data.
          queue_size: 5000 # Max number of batches allowed in the queue.

        retry_on_failure:
          # Configures retries for failed export attempts.
          enabled: true
          initial_interval: 5s # Time to wait after the first failure before retrying.
          max_interval: 30s    # Max time to wait between retries.
          max_elapsed_time: 0s # Retry for ever

        # Most probably we don't need it as compression require more CPU
        # compression: gzip
      # Debug Exporter
      debug:
        verbosity: detailed # valid values are basic, normal and detailed
        # sampling_initial: 5

    # Needed for liveliness/Readiness probes
    extensions:
      health_check: {}

    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        metrics:
          receivers:
          - kubeletstats
          processors:
            # A common and recommended order for the processors:
            # 1. Add/modify resource attributes.
            # 2. Apply memory limits before batching or heavy processing.
            # 3. Batch data before exporting.
            - k8sattributes
            - resource/debug
            - transform/promote_labels
            - memory_limiter
            - batch
          exporters:
            - otlp
            - debug
      extensions:
        - health_check

    processors:
      # Order of the processors is defined in spec.config.service.pipelines.processors
      batch:
        # Max number of items (spans, metrics, logs) in a batch.
        send_batch_size: 8192
        # Max time to wait before sending an incomplete batch.
        timeout: 1s
        # Optional: Max size of a batch in bytes (0 means no limit based on byte size).
        # send_batch_max_size: 0

      # --- Memory Limiter (to prevent OOMKills) ---
      memory_limiter:
        check_interval: 5s
        limit_percentage: 75
        # Sets the difference (as a % of total available memory) between the 'limit_percentage' (hard limit)
        # and a lower "soft limit".
        # - Hard Limit for refusing data: 'limit_percentage' (e.g., 75%).
        # - Soft Limit for aggressive GC: 'limit_percentage' - 'spike_limit_percentage' (e.g., 75% - 15% = 60%).
        # So, aggressive GC starts if memory exceeds 60%; data is refused if it exceeds 75%.
        spike_limit_percentage: 15 # Additional percentage allowed for spikes above the `limit_percentage`.
                                  # Effectively, measures will be taken if usage exceeds this combined threshold for too long.

      # For help use https://opentelemetry.io/docs/platforms/kubernetes/collector/components/#kubernetes-attributes-processor
      k8sattributes:
          auth_type: serviceAccount
          extract:
            # This section is for extracting ARBITRARY K8s labels
            labels:
            # Example from https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/30474#issue-2078300868
            - tag_name: k8s.labels.$$1
              key_regex: (.*)
              from: pod

          # filter:
          #   node_from_env_var: K8S_NODE_NAME
          passthrough: true
          # Order matters here
          pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
          - sources:
            - from: resource_attribute
              name: k8s.pod.ip
          - sources:
            - from: resource_attribute
              name: k8s.pod.uid
          - sources:
            - from: connection

      transform/promote_labels:
        metric_statements:
          # The context is 'datapoint', meaning these operations apply to individual metric data points.
          - context: datapoint
            statements:
              - set(datapoint.attributes["service"], resource.attributes["k8s.labels.service"])

      # DEBUG #
      resource/debug:
        attributes:
          - action: insert
            key: debug_resource_present
            value: "true"
```

### Log output

```shell
# made it prettier to read easier
2025-05-23T07:49:12.967Z        debug   ottl@v0.123.0/parser.go:36      TransformContext after statement execution
{
  "statement": "set(datapoint.attributes[\"service\"], resource.attributes[\"k8s.labels.service\"])",
  "condition matched": true,
  "TransformContext": {
    "resource": {
      "attributes": {
        "k8s.node.name": "<REPLACED>",
        "debug_resource_present": "true"
      },
      "dropped_attribute_count": 0
    },
    "scope": {
      "attributes": {},
      "dropped_attribute_count": 0,
      "name": "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver",
      "version": "0.123.0"
    },
    "metric": {
      "description": "Total cumulative CPU time (sum of all cores) spent by the container/pod/node since its creation",
      "name": "k8s.node.cpu.time",
      "unit": "s",
      "type": "Sum",
      "aggregation_temporality": "Cumulative",
      "is_monotonic": true,
      "datapoints": [
        {
          "attributes": {},
          "exemplars": [],
          "flags": 0,
          "start_time_unix_nano": 1733304186000000000,
          "time_unix_nano": 1747986552966546874,
          "value_double": 20649137.516585
        }
      ]
    },
    "datapoint": {
      "attributes": {},
      "exemplars": [],
      "flags": 0,
      "start_time_unix_nano": 1733304186000000000,
      "time_unix_nano": 1747986552966546874,
      "value_double": 20649137.516585
    },
    "cache": {}
  }
}
ResourceMetrics #2
Resource SchemaURL: 
Resource attributes:
     -> k8s.pod.uid: Str(f8d2cf08-9212-4ead-9428-d397a889ca7a)
     -> k8s.pod.name: Str(<POD_NAME>)
     -> k8s.namespace.name: Str(<POD_NAMESPACE>)
     -> k8s.container.name: Str(<CONTAINER_NAME)
     -> debug_resource_present: Str(true)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
InstrumentationScope github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kubeletstatsreceiver 0.123.0
Metric #0
Descriptor:
     -> Name: container.cpu.time
     -> Description: Total cumulative CPU time (sum of all cores) spent by the container/pod/node since its creation
     -> Unit: s
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
StartTimestamp: 2025-05-22 08:00:41 +0000 UTC
Timestamp: 2025-05-23 07:49:12.966546874 +0000 UTC
Value: 17.373287
Metric #1
Descriptor:
     -> Name: container.cpu.utilization
     -> Description: Container CPU utilization
     -> Unit: 1
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 2025-05-22 08:00:41 +0000 UTC
Timestamp: 2025-05-23 07:49:12.966546874 +0000 UTC
Value: 0.000730
Metric #2
Descriptor:
     -> Name: container.filesystem.available
     -> Description: Container filesystem available
     -> Unit: By
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 2025-05-22 08:00:41 +0000 UTC
Timestamp: 2025-05-23 07:49:12.966546874 +0000 UTC
Value: 51628134400
Metric #3
Descriptor:
     -> Name: container.filesystem.capacity
     -> Description: Container filesystem capacity
     -> Unit: By
     -> DataType: Gauge
<TRUNCATED>
```
