### ISSUE TITLE
Increased CPU usage after upgrading to 0.121.0

### ISSUE THREAD

**Issue by zarbis** [open-telemetry/opentelemetry-collector-contrib#40245]
### Component(s)

receiver/prometheus

### What happened?

Originally reported here: #38904 

After upgrading from `0.117.0` to `0.126.0` I've noticed roughly 5-10 times increase in CPU usage.
I've narrowed down regression to be in version `0.121.0`.

Some additional info:
- I run `logs`, `metrics` and `traces` collectors as separate OTECOLs via otel-operator
- This issue is present ONLY in `metrics` collector

Here is CPU profile:
![Image](https://github.com/user-attachments/assets/31c5741d-90fc-422c-a370-3e49d94e6720)

Memory:
![Image](https://github.com/user-attachments/assets/4c2acc79-666f-4523-b636-9556f6f40fdf)

Goroutines:

![Image](https://github.com/user-attachments/assets/90c66d6f-99c4-4b04-a639-d88d36d717fd)

### Collector version

0.121.0

## Environment
EKS 1.31

### OpenTelemetry Collector configuration

```yaml
config:
  connectors:
    forward/all: {}
  exporters:
    debug/detailed:
      sampling_initial: 5
      sampling_thereafter: 100
      verbosity: detailed
    debug/normal:
      verbosity: normal
    otlphttp:
      auth:
        authenticator: basicauth/client
      compression: gzip
      endpoint: <REDACTED>
  extensions:
    basicauth/client:
      client_auth:
        password: ${OTEL_GW_PASSWORD}
        username: ${OTEL_GW_USERNAME}
    health_check:
      endpoint: 0.0.0.0:13133
      path: /
    pprof:
      endpoint: 0.0.0.0:1777
  processors:
    attributes:
      actions:
      - action: upsert
        key: cluster
        value: <REDACTED>
      - action: upsert
        key: alerting_tier
        value: "1"
    batch:
      send_batch_max_size: 5000
      send_batch_size: 2000
    memory_limiter:
      check_interval: 1s
      limit_percentage: 80
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
        - job_name: dummy
          static_configs:
          - targets:
            - 127.0.0.1:8888
  service:
    extensions:
    - basicauth/client
    - health_check
    - pprof
    pipelines:
      metrics/forward:
        receivers:
        - otlp
        - prometheus
        processors:
        - memory_limiter
        - attributes
        exporters:
        - forward/all
      metrics/otlp:
        receivers:
        - forward/all
        processors:
        - batch
        exporters:
        - otlphttp
```

### Log output

```shell

```
