### ISSUE TITLE
AWS ContainerInsights EKS PodName incorrect in job-created pods

### ISSUE THREAD

**Issue by sf-joeh** [open-telemetry/opentelemetry-collector-contrib#40241]
### Component(s)

receiver/awscontainerinsight

## Description

We have AWS Container Insights being collected and exported successfully in an EKS environment with EC2 compute (Seen the same behaviour on both K8s version 1.28 and 1.31), but noticed that when pods are created by a K8s job, the PodName dimension on the pod-level metrics seems to be truncated. For example, for a job named "container-insights-testing", the PodName dimension is set to "container". I've tested this for other kebab-case names and you always get the string up to the first hyphen. 

(Please let me know if this bug belongs in a different repository e.g. https://github.com/aws-observability/aws-otel-collector) 

I attempted a workaround using processors i.e.

```  
filter/broken_job_pods:
    metrics:
      include:
        match_type: strict
        expressions:
          - 'attributes["kubernetes.labels.job-name"] != nil'
 ```

piped into 

```
 resource/fix_job_names:
    attributes:
      - key: PodName
        from_attribute: kubernetes.labels.job-name
        action: upsert
```

But didn't have any luck getting that to work.

The other less nice workaround is to simply name jobs without any dashes in, (`containerinsightstest` for example), which works but ideally we wouldn't have to do this. 

## Steps to Reproduce

1. Have AWS container insights being collected by the [aws adot-collector ](https://github.com/aws-observability/aws-otel-collector)
2. Create a K8s job that creates a simple pod
3. Look at the metrics produced in CloudWatch

## Expected Result

`PodName` dimenison is set to the full PodName (as it is for "normal" pods), or perhaps something else such as the JobName. 

## Actual Result

The `PodName` dimension becomes a truncated version of the pod names. e.g. "container" from "container-insights-test" or "my" from "my-testing-pods".

### Collector version

0.43.3

## Environment
OS: AmazonLinux
Running on AWS EKS. Seem the same behaviour on clusters on v1.28 and v1.31

### OpenTelemetry Collector configuration

```yaml
extensions:
  health_check:

receivers:
  awscontainerinsightreceiver:

processors:
  batch/metrics:
    timeout: 60s

  resource:
    attributes:
      - key: Sources
        action: delete

exporters:
  awsemf/containerinsights:
    namespace: ContainerInsights
    log_group_name: "/aws/containerinsights/${cluster_name}/performance"
    log_stream_name: "{NodeName}"
    resource_to_telemetry_conversion:
      enabled: true
    dimension_rollup_option: NoDimensionRollup
    parse_json_encoded_attr_values: [Sources, kubernetes]
    metric_declarations:
      # node metrics
      - dimensions: [[NodeName, InstanceId, ClusterName]]
        metric_name_selectors:
          - node_cpu_utilization
          - node_memory_utilization
          - node_network_total_bytes
          - node_cpu_reserved_capacity
          - node_memory_reserved_capacity
          - node_number_of_running_pods
          - node_number_of_running_containers
      - dimensions: [[ClusterName]]
        metric_name_selectors:
          - node_cpu_utilization
          - node_memory_utilization
          - node_network_total_bytes
          - node_cpu_reserved_capacity
          - node_memory_reserved_capacity
          - node_number_of_running_pods
          - node_number_of_running_containers
          - node_cpu_usage_total
          - node_cpu_limit
          - node_memory_working_set
          - node_memory_limit

      # pod metrics
      - dimensions:
          [
            [PodName, Namespace, ClusterName],
            [Service, Namespace, ClusterName],
            [Namespace, ClusterName],
            [ClusterName],
          ]
        metric_name_selectors:
          - pod_cpu_utilization
          - pod_memory_utilization
          - pod_network_rx_bytes
          - pod_network_tx_bytes
          - pod_cpu_utilization_over_pod_limit
          - pod_memory_utilization_over_pod_limit
          - pod_number_of_containers
          - pod_number_of_running_containers
      - dimensions: [[PodName, Namespace, ClusterName], [ClusterName]]
        metric_name_selectors:
          - pod_cpu_reserved_capacity
          - pod_memory_reserved_capacity
      - dimensions: [[PodName, Namespace, ClusterName]]
        metric_name_selectors:
          - pod_number_of_container_restarts

      # cluster metrics
      - dimensions: [[ClusterName]]
        metric_name_selectors:
          - cluster_node_count
          - cluster_failed_node_count

      # service metrics
      - dimensions: [[Service, Namespace, ClusterName], [ClusterName]]
        metric_name_selectors:
          - service_number_of_running_pods

      # node fs metrics
      - dimensions: [[NodeName, InstanceId, ClusterName], [ClusterName]]
        metric_name_selectors:
          - node_filesystem_utilization

      # namespace metrics
      - dimensions: [[Namespace, ClusterName], [ClusterName]]
        metric_name_selectors:
          - namespace_number_of_running_pods

service:
  pipelines:
    metrics/containerinsights:
      receivers: [awscontainerinsightreceiver]
      processors: [filter/containerinsights, resource, batch/metrics]
      exporters: [awsemf/containerinsights]

  telemetry:
    logs:
      level: debug # Set to "debug" if you need to investigate why metrics may not be appearing

  extensions: [health_check]
```

### Log output

```shell

```
