### ISSUE TITLE
sumologicextension: tag discovery can fail when process discovery fails

### ISSUE THREAD

**Issue by echlebek** [open-telemetry/opentelemetry-collector-contrib#40252]
### Component(s)

extension/sumologic

## Description
When process discovery fails to read a process' name, then tag discovery can fail, leading to a broken collector. This situation was mitigated for Windows, but seems to be also happening on at least Darwin and could potentially happen on Linux too.

## Steps to Reproduce
Create a zombie process that would be normally discovered by the process discovery feature. Its presence can disrupt the startup of the collector when the sumologicextension is used.

## Expected Result
No failure.

## Actual Result
Failure.

### Collector version

tip

**Comment by echlebek** [comment]
@rnishtala-sumo can furnish some more details for this issue as he ran into it while upgrading the sumologicextension.

**Comment by rnishtala-sumo** [comment]
Here's the log output seen

`sumologicextension@v0.124.0/extension.go:913	collector metadata update failed: Error getting executable name: invalid argument	{"collector_name": "service.sumologic.com-1748019244892", "collector_id": "00005AF3108E528A"}`


Otel configuration

```
extensions:
  ## Configuration for Sumo Logic Extension
  ## Manages registration, heartbeats and authentication to Sumo Logic
  ## ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/sumologicextension
  sumologic:
    installation_token: ${SUMOLOGIC_INSTALLATION_TOKEN}
    collector_credentials_directory: /var/lib/otelcol-sumo/credentials

  ## Configuration for Health Check Extension
  ## Health Check extension enables an HTTP url that can be probed to check the status of the OpenTelemetry Collector
  ## ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
  health_check:
    endpoint: localhost:13133

  ## Configuration for File Storage Extension
  ## The File Storage extension can persist state to the local file system
  ## ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage
  file_storage:
    compaction:
      directory: /var/lib/otelcol-sumo/file_storage
      on_rebound: true
    directory: /var/lib/otelcol-sumo/file_storage

receivers:
  ## Configuration for OTLP Receiver
  ## Receives data via gRPC or HTTP using OTLP format.
  ## ref: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

exporters:
  ## Configuration for Sumo Logic Exporter
  ## This exporter supports sending logs, metrics and traces data to Sumo Logic.
  ## ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.102.0/exporter/sumologicexporter
  sumologic:
    sending_queue:
      enabled: true
      storage: file_storage
    retry_on_failure:
      max_elapsed_time: 0

processors:
  ## Configuration for Memory Limiter Processor
  ## The memory_limiter processor is used to prevent out of memory situations on the collector.
  ## ref: https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor
  memory_limiter:
    ## check_interval is the time between measurements of memory usage for the
    ## purposes of avoiding going over the limits. Defaults to zero, so no
    ## checks will be performed. Values below 1 second are not recommended since
    ## it can result in unnecessary CPU consumption.
    check_interval: 5s
    ## Maximum amount of memory, in %, targeted to be allocated by the process heap.
    limit_percentage: 75
    ## Spike limit (calculated from available memory). Must be less than limit_percentage.
    spike_limit_percentage: 20

  ## Configuration for Batch Processor
  ## The batch processor accepts records and places them into batches grouped by node and resource
  ## ref: https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor
  batch:
    ## Number of records after which a batch will be sent regardless of time
    send_batch_size: 1_024
    ## Time duration after which a batch will be sent regardless of size
    timeout: 1s

  ## Configuration for Sumo Logic Schema Processor
  ## The Sumo Logic Schema processor modifies the metadata on logs, metrics and traces sent to Sumo Logic
  ## so that the Sumo Logic apps can make full use of the ingested data.
  ## ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/sumologicprocessor
  sumologic:

  ## Configuration for Resource Detection Processor
  ## The resource detection processor can be used to detect resource information from the host, in a format that conforms to the
  ## OpenTelemetry resource semantic conventions, and append or override the resource value in telemetry data with this information.
  ## ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor
  resourcedetection/system:
    detectors: ["system", "ec2", "gcp", "azure"]
    system:
      hostname_sources: ["dns", "os"]

service:
  extensions:
    - sumologic
    - health_check
    - file_storage
  telemetry:
    metrics:
      address: localhost:8888
  pipelines:
    metrics/default:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
        - sumologic
      exporters:
        - sumologic
    logs/default:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
        - sumologic
      exporters:
        - sumologic
    traces/default:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
        - sumologic
      exporters:
        - sumologic
```
