### ISSUE TITLE
[spanmetrics] Support resource dimensions

### ISSUE THREAD

**Issue by albertteoh** [open-telemetry/opentelemetry-collector-contrib#4027]
**Is your feature request related to a problem? Please describe.**
Add resource dimensions to span metrics such as `ip`, `hostname`, `region`, etc.

**Describe the solution you'd like**
Along with building the metrics key based on a span's `Attributes()`, the span metrics processor should also permit searching for the configured dimensions in the `Resource()` list of attributes. The configuration schema should not change for the user.  That is, if the user wants to add `region` to the span metrics dimensions, it should simply involve adding `region` to the `dimensions` list alongside the span attributes like so:
```
 processors:
   spanmetrics:
     metrics_exporter: prometheus
     dimensions:
     - name: http.method
     - name: region
```
