### ISSUE TITLE
[processor/transform] Add drop_bucket OTTL function

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-collector-contrib#40280]
### Component(s)

processor/transform

### Is your feature request related to a problem? Please describe.

In the OpenTelemetry Collector, Prometheus-style histograms and native OTLP histograms both represent metric buckets differently. This proposal introduces a new OTTL function, drop_bucket(), to allow filtering/removal of individual histogram buckets — regardless of the source format.

Prometheus users often rely on relabeling rules to drop low-value histogram buckets (e.g., le="0.0") using metric_relabel_configs, like:
```yaml
metric_relabel_configs:
  - source_labels: [__name__, le]
    regex: 'example_latency_seconds_bucket;0\.0.*'
    action: drop
```

Currently, there is no way to achieve this in the Collector using OTTL. This functionality is often necessary to reduce cardinality or remove meaningless buckets (e.g., always-zero latency buckets).

### Describe the solution you'd like

Add a new function like:
```
- drop_bucket("0\.0.*") where metric.name == "example_latency_seconds_bucket"
```
