### ISSUE TITLE
kafkaexporter - unable to use snappy compression in 0.126.0

### ISSUE THREAD

**Issue by ryn9** [open-telemetry/opentelemetry-collector-contrib#40288]
## Description
unable to use snappy compression in 0.126.0

If not setting a compression level, it errors saying compression level -1 is not supported
If setting a compression level, it errors saying compression level provided is not supported

## Steps to Reproduce
use snappy compression with kafkaexporter 

### Collector version

0.126.0

## Environment
0.126.0 container

### OpenTelemetry Collector configuration

```yaml
exporters:

  kafka/out:
    brokers:
      - kafka-server:9092
    metrics:  
      topic: kafka-topic
      encoding: otlp_json
    producer:
      compression: snappy

  kafka/out2:
    brokers:
      - kafka-server:9092
    metrics:  
      topic: kafka-topic
      encoding: otlp_json
    producer:
      compression: snappy
      compression_params:
        level: 1
```

### Log output

```shell

```
