### ISSUE TITLE
Proposal: Span Stats processor

### ISSUE THREAD

**Issue by ashwinidulams** [open-telemetry/opentelemetry-collector-contrib#403]
## Span Statistics Proposal

A processor for aggregating spans to derive RED (Request, Error, Distribution) metrics across a set of dimensions (dynamic or otherwise) and exporting the results to a metrics sink (prometheus endpoint, stream etc).  

## Motivation

A trace contains end-to-end data about the service call chain in the context of a request/transaction. This data can be mined to derive context rich metrics that can help us identify and isolate the problem as quickly as possible. For example, span level aggregation can be used to detect any performance problems within the  process boundary defined by the span. 

Instead of forwarding the spans to a separate processor (stream processing application) for aggregation, a otel processor can process the spans in flight and emit RED metrics at configurable time intervals.

## Proposed Configuration

```yaml
processors:
  # name of the processor 
  spanstatsprocessor:
    # time window for aggregation in seconds.
    timewindowseconds: 15
    # dimensions for aggregation. could be an array of aggregations as well.
    # for each set of dimensions, RED (request, error and distribution) metrics will be emitted aggregated per timewindow.
    dimensions:
    - http.url
    - custom_tag1
    # sink for metrics
    sink:
      # prometheus sink with a endpoint exposed at port 24880
      # alternately could be a kafka stream.
      prometheusport: 24880
```

**Comment by jrcamp** [comment]
Just so it's not lost, @jmacd wrote in the original issue:
> See open-telemetry/opentelemetry-specification#657, which aims to specify conventions for this kind of processor.

**Comment by jmacd** [comment]
There is a related discussion https://github.com/open-telemetry/opentelemetry-specification/pull/739.

Also https://github.com/open-telemetry/opentelemetry-specification/issues/381.

This is a great thing and we should have such a processor. I would expect this processor to output OTLP metrics into a metrics pipeline, which I believe is implied by the config snippet above. :+1:

**Comment by pauldraper** [comment]
What are the metrics? `span.count` and `span.duration`?

Does it make sense to allow attributes as metrics (e.g. response.bytes).

**Comment by albertteoh** [comment]
I'd like to take on this task if no one's put their hand up yet.

>  I would expect this processor to output OTLP metrics into a metrics pipeline

@jmacd, this suggestion makes a lot of sense, as I've [recently learned](https://github.com/jaegertracing/jaeger/issues/2574#issuecomment-713473271) from @jpkrohling. As I'm new to OTEL, what do you suggest would be the best approach to achieving this? I haven't put too much thought into it, but my initial thinking is to copy the OTLP exporter's metrics exporting functionality. 

If this doesn't sound like the right approach, can you please point me in the right general direction?

**Comment by albertteoh** [comment]
I've put together a Proof of Concept. Here's a screenshot:
<img width="1725" alt="Screen Shot 2020-10-26 at 9 07 30 pm" src="https://user-images.githubusercontent.com/26584478/101727044-d63c0680-3b07-11eb-90c9-0dacb6910e6c.png">

**Comment by albertteoh** [comment]
Wondering if I could get some early feedback on this from the community, particularly, the approach taken to transform trace telemetry to metrics, which I've illustrated here:

![Metrics from trace processor 3 pipelines (1)](https://user-images.githubusercontent.com/26584478/101728714-fde09e00-3b0a-11eb-8c26-f228c0b74ead.png)

The approach is to have a common trace receiver that feeds two pipelines, a trace-only pipeline for trace ingestion, and a trace->metrics pipeline that performs aggregations on span data and writes them out to a configured metrics exporter.

The exporter is chosen using a processor configuration like so:
```
exporters:
   prometheus:
     endpoint: "0.0.0.0:8889"
     ...

processors:
  spanmetrics:
    metrics_exporter: prometheus
    ...
```

And the code that performs the metrics exporter discovery:
```
// Start implements the component.Component interface.
func (p *processorImp) Start(ctx context.Context, host component.Host) error {
	exporters := host.GetExporters()

	for k, exp := range exporters[configmodels.MetricsDataType] {
                ...
                // Check if the exporter k has the same name as the configured exporter. e.g. prometheus
		if k.Name() == p.config.MetricsExporter {
			p.metricsExporter = metricsExp
			break
		}
	}
	if p.metricsExporter == nil {
		return fmt.Errorf( "failed to find metrics exporter: '%s'", p.config.MetricsExporter)
	}
	return nil
}
```

That all seems okay to me so far, though please suggest any improvements to the above proposed approach.

The part that I'm less sure of is the user experience when configuring pipelines, which seems less than ideal due to the following OTEL collector constraints (which make sense by the way):
1. Needing at least one receiver and at least one exporter in a pipeline.
2. Exporters are only discoverable if they belong to a pipeline.

Here's the relevant sections of my POC config. Note the need for:
- a dummy `otlp/spanmetrics` receiver (requirement 1.).
- an unused exporter (I just used `logger`) in the `traces/spanmetrics` pipeline, which aggregates span data to metrics (requirement 1.).
- a dummy `metrics/spanmetrics` pipeline to "house" the `prometheus` metrics exporter to ensure it's discoverable in the processor `Start()` function (requirement 2.).
```
 receivers:
   # Dummy receiver that's never used, because a pipeline is required to have one.
   otlp/spanmetrics:
     protocols:
       grpc:
         endpoint: "localhost:12345"

 service:
   pipelines:
     traces:
       receivers: [jaeger]
       processors: [batch, queued_retry]
       exporters: [logging]
     # Dedicated pipeline for receiving spans and emitting metrics.
     # Note the logging exporter is not really used, but is mandatory for pipelines (must have at least one receiver and exporter)
     traces/spanmetrics:
       receivers: [jaeger]
       processors: [spanmetrics]
       exporters: [logging]
     # A dummy 'internal' pipeline dedicated to exposing a metrics exporter for the spanmetrics pipeline.
     # The exporter name must match the metrics_exporter name.
     # The receiver is just a dummy and never used; added because it's mandatory.
     metrics/spanmetrics:
       receivers: [otlp/spanmetrics]
       exporters: [prometheus]
```

To me, the need for these dummy configuration entries makes for a less than ideal configuration experience for those using this processor and wondering if folks have any suggestions to improve this?

**Comment by objectiser** [comment]
@albertteoh Could there be a concept of a `local` metrics receiver, that any component could generate metrics for? So then the `spanmetrics` processor could be part of the normal trace pipeline, and the `local` metrics receiver could be used to trigger a single metrics pipeline.

```
receivers:
  otlp:
    protocols:
      grpc:
         endpoint: "localhost:12345"

  local/mymetrics:

exporters:
   prometheus:
     endpoint: "0.0.0.0:8889"
     ...

processors:
  spanmetrics:
    metrics_receiver: local/mymetrics

service:
  pipelines:
   traces:
     receivers: [otlp]
     processors: [spanmetrics, batch, queued_retry]
     exporters: [logging]
   metrics:
     receivers: [local/mymetrics]
     exporters: [prometheus]
```

**Comment by albertteoh** [comment]
Thanks @objectiser, that config looks cleaner. Please correct me if I'm wrong; I think the `spanmetrics` processor still needs an exporter as they expose the `ConsumeMetrics` function for sending metrics (i.e. to trigger a pipeline), whereas receivers don't offer such means.

Your suggestion got me thinking though... I'd like to understand the motivation for [needing at least one receiver in a pipeline](https://github.com/open-telemetry/opentelemetry-collector/blob/master/config/config.go#L572)? Removing this requirement would mean a local receiver is no longer needed for the use case of producing metrics from traces, and we simply configure what's necessary (@tigrannajaryan @bogdandrutu, what do you think?):
```
receivers:
   jaeger:
     protocols:
       thrift_http:
         endpoint: "0.0.0.0:14278"

exporters:
   prometheus:
     endpoint: "0.0.0.0:8889"
     ...

processors:
  spanmetrics:
    metrics_exporter: prometheus

service:
  pipelines:
   traces:
     receivers: [jaeger]
     processors: [spanmetrics, batch, queued_retry]
     exporters: [logging]
   metrics:
     exporters: [prometheus]
```

**Comment by objectiser** [comment]
@albertteoh My suggestions were not based on the current internal implementation, but focusing first on how it might be simplified for configuration - and then address how to deal with this "local" receiver as a second consideration.

I like your updated suggestion as well - my only comment would be that it would not allow any processors to be defined on the metrics generated by the `spanmetrics` processor - whereas if those metrics could be passed to a `local` receiver, it still offers the full metrics pipeline to process the metrics and potentially export to multiple destinations.

**Comment by djaglowski** [comment]
[Here is a very rough draft of an alternate proposal](https://docs.google.com/document/d/1zPq--oeHEjQbGLQTDhwPf2ByZ4vzW3mYwQRawAnO0yQ/edit?usp=sharing). I'm providing here in case it may generate useful discussion or ideas.

**Comment by objectiser** [comment]
@djaglowski Sounds reasonable - although for clarity could you add an example OTC config that addresses this use case, for example:
* tracing data, processed to derive metrics
* tracing data then needs to be further processed before being exported
* derived metrics then exported to another metrics pipeline that maybe does additional processing before exporting to the desired backend

**Comment by djaglowski** [comment]
@objectiser, I've updated the doc to include your example scenario and a possible configuration for it. This example highlights a gap in my proposal, which I've also addressed at the end. Thanks for reviewing, and for the suggestion.

**Comment by objectiser** [comment]
@djaglowski Looks good, thanks for the update.

**Comment by albertteoh** [comment]
Thanks for putting together the proposal, @djaglowski. 

I feel an important requirement for trace -> metrics aggregation is having access to all span data before any filtering (like tail-based sampling) and potentially after span modification processors are applied.

If I understand correctly, the signal translators are implemented as exporters, which I believe would be subject to all processors in the pipeline being executed first before reaching the exporter.

**Comment by djaglowski** [comment]
@albertteoh I believe my proposal covers this, though the usability may be a bit poor. 

In the example shown in the doc, copied below, `pipeline a` is a forking mechanism for the raw traces, so that they can be 1) passed along to `pipeline b` without modification, and 2) processed into metrics and passed to `pipeline c`.

```
receivers:
  some/tracingreceiver:
  otlp/tracingreceiver:
    endpoint: "0.0.0.0:1111"
  otlp/metricsreceiver:
    endpoint: "0.0.0.0:2222"
  
processors:
  some/tracingprocessor:
  some/metricsprocessor:
  
exporters:
  some/tracingexporter:
  some/metricsexporter:
  otlp/tracingexporter:
    endpoint: "0.0.0.0:1111"
  tracestometrics: # perform some derivation and behave as otlp/metricsexporter
    endpoint: "0.0.0.0:2222"

service:
  pipelines:
    a:
      receivers: [some/tracingreceiver]
      exporters: [otlp/tracingexporter, tracestometrics]
    b:
      receivers: [some/tracingreceiver]
      processors: [some/tracingprocessor]
      exporters: [some/tracingexporter]
    c:
      receivers: [some/metricsreceiver]
      processors: [some/metricsprocessor]
      exporters: [some/metricsexporter]
```

**Comment by djaglowski** [comment]
A new type of component would simplify the above proposal. I've expanded upon this in the doc, but here is the high level idea:
```
receivers:
  some/tracingreceiver:
  
processors:
  some/tracingprocessor:
  some/metricsprocessor:
  
exporters:
  some/tracingexporter:
  some/metricsexporter:

translators: # must be used as both exporter and receiver
  tracestotraces:
  tracestometrics:

service:
  pipelines:
    a:
      receivers: [some/tracingreceiver]
      exporters: [tracestotraces, tracestometrics]
    b:
      receivers: [tracestotraces]
      processors: [some/tracingprocessor]
      exporters: [some/tracingexporter]
    c:
      receivers: [tracestometrics]
      processors: [some/metricsprocessor]
      exporters: [some/metricsexporter]
```

![image](https://user-images.githubusercontent.com/5255616/102917224-d1098080-4452-11eb-8751-f1cf33b52b20.png)
