### ISSUE TITLE
awsemf - CloudWatch logs unsupported protocol scheme error

### ISSUE THREAD

**Issue by lzac** [open-telemetry/opentelemetry-collector-contrib#40308]
### Component(s)

exporter/awsemf

## Description
We've been using the `awsemf` exporter with no major issues since a long time but it looks like it's no longer working as expected starting from v0.125.0.
My guess is that something broke because of the upgrade aws-sdk-go-v2 with #39314 as we're now getting the following error with no configuration changes on our side.

`scraper-collector-opentelemetry-collector-0 opentelemetry-collector 2025-05-27T07:00:48.102Z	warn	batchprocessor@v0.126.0/batch_processor.go:264	Sender failed	{"resource": {}, "otelcol.component.id": "batch/cloudwatch", "otelcol.component.kind": "processor", "otelcol.pipeline.id": "metrics/awsemfkubestate", "otelcol.signal": "metrics", "error": "operation error CloudWatch Logs: PutLogEvents, exceeded maximum number of attempts, 2, https response error StatusCode: 0, RequestID: , request send failed, Post \"/\": unsupported protocol scheme \"\""}`

## Steps to Reproduce
We've upgraded our helm chart from `0.123.0` to `0.124.0`, which actually upgrade the collector to `0.125.0`, and started getting the error.

## Expected Result
Logs should be properly sent to CloudWatch.

## Actual Result
CloudWatch does not receive any log.

### Collector version

v0.125.0

### OpenTelemetry Collector configuration

```yaml
config:
  "service":
    "pipelines":
      "metrics/awsemfkubestate":
        "receivers":
        - "prometheus"
        "processors":
        - "filter/awsemfkubestate"
        - "batch"
        "exporters":
        - "awsemf"
  "processors":
    "batch": {}
    "filter/awsemfkubestate":
      "metrics":
        "include":
          "match_type": "strict"
          "metric_names":
          - "kube_deployment_spec_replicas"
          - "kube_deployment_status_replicas_available"
  "exporters":
    "awsemf":
      "region": "${REGION}"
      "output_destination": "cloudwatch"
      "dimension_rollup_option": "NoDimensionRollup"
      "resource_to_telemetry_conversion":
          "enabled": true
      "namespace": "${EMF_NAMESPACE}"
      "log_group_name": "${LOG_GROUP_NAME}"
      "log_retention": 7
      "log_stream_name": "${LOG_STREAM_NAME}"
      "metric_declarations":
        - "dimensions": [[namespace, deployment]]
          "metric_name_selectors":
            - "kube_deployment_spec_replicas"
            - "kube_deployment_status_replicas_available"
```

### Log output

```shell
scraper-collector-opentelemetry-collector-0 opentelemetry-collector 2025-05-27T07:00:48.102Z	warn	batchprocessor@v0.126.0/batch_processor.go:264	Sender failed	{"resource": {}, "otelcol.component.id": "batch/cloudwatch", "otelcol.component.kind": "processor", "otelcol.pipeline.id": "metrics/awsemfkubestate", "otelcol.signal": "metrics", "error": "operation error CloudWatch Logs: PutLogEvents, exceeded maximum number of attempts, 2, https response error StatusCode: 0, RequestID: , request send failed, Post \"/\": unsupported protocol scheme \"\""}
```

**Comment by avaitla** [comment]
We are hitting this issue as well, I was a bit surprised at this error at first, but reverting to v0.123.0 resolves it. Something is broken in the awsemf exporter. It seems the amazon otel collector works however.

**Comment by al-alison** [comment]
We got the same error when upgrading to the latest version, in awsemfexporter, awscloudwatchexporter and even in the awsxrayexporter
The workaround we found was adding the "endpoint" property in the exporters configuration, with the protocol included, like this:

```
awsemf:
    region: 'us-east-1'
    endpoint: https://logs.us-east-1.amazonaws.com
    log_group_name: '/otel/metrics/{ClusterName}'
    log_stream_name: '{TaskId}'
    log_retention: 7
    resource_to_telemetry_conversion:
        enabled: true

  awscloudwatchlogs:
    region: 'us-east-1'
    endpoint: https://logs.us-east-1.amazonaws.com
    log_group_name: '/otel/logs/{ClusterName}'
    log_stream_name: '{TaskId}'
    log_retention: 7

  awsxray:
    region: 'us-east-1'
    endpoint: https://xray.us-east-1.amazonaws.com
    telemetry:
      enabled: true
```
