### ISSUE TITLE
Is it possible to include the namespace in the service graph

### ISSUE THREAD

**Issue by adithya-r-nathan** [open-telemetry/opentelemetry-collector-contrib#40324]
### Component(s)

connector/servicegraph

### Describe the issue you're reporting

Have been trying to add the namespace in the service graph but it is not getting reflected/the field is not getting added in the metrics
Below is the sample service graph configuration
```
servicegraph:
        latency_histogram_buckets:  [4ms, 10ms, 25ms, 50ms, 100ms, 200ms, 400ms, 800ms, 1s, 1500ms, 2s, 4s, 10s, 20s, 40s]
        dimensions:
          - cluster
          - k8s_namespace_name
          - db.system
          - messaging.system
          - code.function	
          - db.name
          - peer.service
          - span_name 
          - server.address
          - server.port
          - calls
          - server
        virtual_node_peer_attributes:
          - db.name
          - db.system
          - messaging.system
          - peer.service
          - k8s_namespace_name
          - namespace
          - namespace_name
        virtual_node_extra_label: true
        store:
          ttl: 5s
```
