### ISSUE TITLE
[exporter/coralogix] Unauthenticated error with v0.127.0

### ISSUE THREAD

**Issue by rlebran** [open-telemetry/opentelemetry-collector-contrib#40330]
### Component(s)

Coralogix exporter

## Description
After upgrading to version 0.127.0, every call made to  Coralogix seems to fail with an unauthenticated error.

## Steps to Reproduce
Upgrade from 0.126.0 to 0.127.0 with no config change.

## Expected Result
Exporter calls should not failed as the private key is provided and valid.

## Actual Result
Every call failed with an unauthenticated error

### Collector version

0.127.0

### OpenTelemetry Collector configuration

```yaml
exporters:
  coralogix:
    application_name: otel
    application_name_attributes:
      - service.name
      - k8s.namespace.name
      - service.namespace
    sending_queue:
      enabled: true
      sizer: "items"
      num_consumers: 10
      queue_size: 25000
      batch:
        flush_timeout: 1s
        min_size: 1024
        max_size: 2048
    domain: eu2.coralogix.com
    private_key: ${env:CORALOGIX_PRIVATE_KEY}
    subsystem_name: k8s-saas
    subsystem_name_attributes:
      - subsystem.name
[...]
```

### Log output

```shell
{"level":"error","ts":"2025-05-27T14:47:31.349Z","caller":"internal/queue_sender.go:57","msg":"Exporting failed. Dropping data.","resource":{"service.name":"opentelemetry-collector"},"otelcol.component.id":"coralogix","otelcol.component.kind":"exporter","otelcol.signal":"logs","error":"not retryable error: Permanent error: rpc error: code = Unauthenticated desc = c5e597274094beff3ed21416556add2a344b6f11","dropped_items":3,"stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1\n\tgo.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/internal/queue_sender.go:57\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*defaultBatcher).flush.func1\n\tgo.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/internal/queuebatch/default_batcher.go:217"}
{"level":"error","ts":"2025-05-27T14:47:31.790Z","caller":"internal/queue_sender.go:57","msg":"Exporting failed. Dropping data.","resource":{"service.name":"opentelemetry-collector"},"otelcol.component.id":"coralogix","otelcol.component.kind":"exporter","otelcol.signal":"traces","error":"not retryable error: Permanent error: rpc error: code = Unauthenticated desc = c5e597274094beff3ed21416556add2a344b6f11","dropped_items":3,"stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1\n\tgo.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/internal/queue_sender.go:57\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*defaultBatcher).flush.func1\n\tgo.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/internal/queuebatch/default_batcher.go:217"}
{"level":"error","ts":"2025-05-27T14:47:32.087Z","caller":"internal/queue_sender.go:57","msg":"Exporting failed. Dropping data.","resource":{"service.name":"opentelemetry-collector"},"otelcol.component.id":"coralogix","otelcol.component.kind":"exporter","otelcol.signal":"metrics","error":"not retryable error: Permanent error: rpc error: code = Unauthenticated desc = c5e597274094beff3ed21416556add2a344b6f11","dropped_items":10,"stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1\n\tgo.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/internal/queue_sender.go:57\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*defaultBatcher).flush.func1\n\tgo.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/internal/queuebatch/default_batcher.go:217"}
```
