### ISSUE TITLE
[receiver/sqlquery] Executes long queries sequentially instead of in parallel when multiple long-running queries are configured

### ISSUE THREAD

**Issue by josepcorrea** [open-telemetry/opentelemetry-collector-contrib#40350]
### Component(s)

receiver/sqlquery

### What happened?

Component(s)
receiver/sqlquery

otelcol-contrib version 0.125.0

We are using the sqlqueryreceiver in otelcol-contrib to execute multiple SQL queries concurrently against a PostgreSQL instance. However, when we configure multiple long-running queries, they are executed sequentially, not in parallel as expected.

❗ Bug Description
We configured three queries like the following:

```yaml
receivers:
  sqlquery/postgres:
    driver: postgres
    datasource: "host=localhost database=postgres port=5432 user=postgres_otel password=XXX sslmode=disable"
    collection_interval: 3m
    max_open_conn: 0
    queries:
      - sql: "SELECT 52 AS sleep1 FROM pg_sleep(360)"
        metrics:
          - metric_name: pg_sleep_query_1
            value_column: sleep1
            value_type: double
      - sql: "SELECT 62 AS sleep2 FROM pg_sleep(360)"
        metrics:
          - metric_name: pg_sleep_query_2
            value_column: sleep2
            value_type: double
      - sql: "SELECT 72 AS sleep3 FROM pg_sleep(360)"
        metrics:
          - metric_name: pg_sleep_query_3
            value_column: sleep3
            value_type: double
```

🧪 Expected behavior
According to the [source code](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/sqlqueryreceiver/...), each SQL query is registered as a separate scraper, and the scraperhelper.NewMetricsController should run them concurrently using goroutines. Therefore, all 3 queries should start at the same time and report in ~6 minutes.

🐞 Actual behavior
What we observe is sequential execution. With the configuration above and collection_interval: 3m, we only receive one new metric every ~6 minutes, indicating that each query runs after the previous one finishes. After 18 minutes, we have only received 3 datapoints (one per query), each 6 minutes apart.

We confirmed this behavior visually (attached Prometheus graph):

📷 See attached screenshot:
You can see pg_sleep_query_1, pg_sleep_query_2, and pg_sleep_query_3 appear one after the other, not at the same time.

![Image](https://github.com/user-attachments/assets/22f6053a-3a04-4789-901c-fe8c7b28745b)

🧩 Possible cause
While scrapers are technically launched in parallel, the connection pool (MaxOpenConn) appears to be exhausted or serialized internally. Since each query runs for 360 seconds (pg_sleep(360)), and the collection interval is 180s, the pool likely blocks additional queries from running.

Setting max_open_conn: 0 (unlimited) should avoid this, but it seems to not be working as expected — or the receiver is not properly parallelizing DB calls at the DB client level.

### Collector version

0.125.0

## Environment
os_description="Red Hat Enterprise Linux 8.4"
os_type="linux"

### OpenTelemetry Collector configuration

```yaml
receivers:
  sqlquery/postgres:
    driver: postgres
    datasource: "host=localhost database=postgres port=5432 user=postgres_otel password=XXX sslmode=disable"
    collection_interval: 3m
    max_open_conn: 0
    queries:
      - sql: "SELECT 52 AS sleep1 FROM pg_sleep(360)"
        metrics:
          - metric_name: pg_sleep_query_1
            value_column: sleep1
            value_type: double
      - sql: "SELECT 62 AS sleep2 FROM pg_sleep(360)"
        metrics:
          - metric_name: pg_sleep_query_2
            value_column: sleep2
            value_type: double
      - sql: "SELECT 72 AS sleep3 FROM pg_sleep(360)"
        metrics:
          - metric_name: pg_sleep_query_3
            value_column: sleep3
            value_type: double
```

### Log output

```shell

```
