### ISSUE TITLE
Opampsupervisor on Windows Does Not Start - Crashes Without Meaningful Errors/Messages

### ISSUE THREAD

**Issue by ForkingFrenzy** [open-telemetry/opentelemetry-collector-contrib#40368]
### Component(s)

cmd/opampsupervisor

## Description
 opampsupervisor_0.127.0_windows_amd64.exe crashes/doesn't launch and does not output any meaningful error messages. 

## Steps to Reproduce
This is reproducible. I've successfully done it many times via a fresh Windows VM and also my personal Windows device.
Be on a windows 10 machine. 
- Install otel collector contrib v0.127.0
- Disable the otel service via windows service.
- Download opampsupervisor_0.127.0_windows_amd64.exe from github releases page
- Copy the opamsupervisor to `C:\Program Files\OpenTelemetry Collector`
- Save below code as `supervisor.yaml`

```
server:
  endpoint: wss://whateveryouropamserverurl:4320/v1/opamp
  tls:
    insecure_skip_verify: false

capabilities:
  accepts_remote_config: true
  reports_effective_config: true
  reports_own_metrics: false
  reports_own_traces: false
  reports_own_logs: true
  reports_health: true
  reports_remote_config: true

agent:
  executable: otelcol-contrib.exe

storage:
  directory: ./
```

- Launch powershell as admin
- `cd C:\Program Files\OpenTelemetry Collector`
- `Unblock-File -Path .\opampsupervisor_0.127.0_windows_amd64.exe`
- `.\opampsupervisor_0.127.0_windows_amd64.exe --config supervisor.yaml`

## Expected Result
Not exiting and giving more errors to work on like on linux where if a config is bad it would tell you.

## Actual Result
Nothing silent exit.

I've tried the following variants. None worked. All quietly exited without error message.
- `.\opampsupervisor_0.127.0_windows_amd64.exe -config supervisor.yaml`
- `.\opampsupervisor_0.127.0_windows_amd64.exe supervisor.yaml`
- `.\opampsupervisor_0.127.0_windows_amd64.exe --config supervisor.yaml`
- `.\opampsupervisor_0.127.0_windows_amd64.exe -config supervisor.yaml`
- `.\opampsupervisor_0.127.0_windows_amd64.exe supervisor.yaml`

### Collector version

0.127.0

## Environment
OS: Windows Server 2022 Version 10.0.20348 Build 20348

Downloaded from github releases: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fopampsupervisor%2Fv0.127.0/opampsupervisor_0.127.0_windows_amd64.exe

### OpenTelemetry Collector configuration

```yaml
server:
  endpoint: wss://whateveryouropamserverurl:4320/v1/opamp
  tls:
    insecure_skip_verify: false

capabilities:
  accepts_remote_config: true
  reports_effective_config: true
  reports_own_metrics: false
  reports_own_traces: false
  reports_own_logs: true
  reports_health: true
  reports_remote_config: true

agent:
  executable: otelcol-contrib.exe

storage:
  directory: ./
```

### Log output

```shell
n/a
```

### Additional context

FYI when given a flag that doesn't exist it outputs an argument error statement.

`.\opampsupervisor_0.127.0_windows_amd64.exe -blahblah`
> flag provided but not defined: -blahblah
> Usage of C:\Program Files\OpenTelemetry Collector\opampsupervisor_0.127.0_windows_amd64.exe:
>   -config string
>         Path to a supervisor configuration file

**Comment by VihasMakwana** [comment]
Hi @ForkingFrenzy !
Can you attach logs (whatever logs there are)?

**Comment by ForkingFrenzy** [comment]
```
telemetry:
  logs:
    level: debug
    output_paths: [".\supervisor.log"]
```
I've tried outputting the logs to file. However there is no log. Silent exit. 
It does however create the "supervisor.log" file with the size 0kb.

**Comment by ForkingFrenzy** [comment]
Upon further analysis. It seems that the supervisor.yaml configuration file isn't correct. Hence the crash. (expected)
However the issue still remains. There is a lack of error messages with the supervisor on windows.

For anyone struggling to get supervisor.exe on windows to work. 

The config that ended up working on windows is as follows
```
server:
  endpoint: wss://whateveryouropamserverurl:4320/v1/opamp
  tls:
    insecure_skip_verify: false

capabilities:
  accepts_remote_config: true
  reports_effective_config: true
  reports_own_metrics: false
  reports_own_traces: false
  reports_own_logs: true
  reports_health: true
  reports_remote_config: true

agent:
  executable: "./otelcol-contrib.exe"

storage:
  directory: ./
```

` .\opampsupervisor_0.127.0_windows_amd64.exe -config supervisor.yaml`
