### ISSUE TITLE
file_storage extension: permission denied

### ISSUE THREAD

**Issue by yuzhouliu9** [open-telemetry/opentelemetry-collector-contrib#40381]
### Component(s)

extensions/file_storage

## Description
I'm trying to set up the s3 exporter with a persistent queue to avoid dropping logs when the otel collector pod dies
```yaml
    exporters:
      awss3/devops:
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 10000
          storage: file_storage/otc

    extensions:
      file_storage/otc:
        directory: /otel-storage
        create_directory: true

    service:
      extensions: [file_storage/otc]
```

The collector pod has the correct volume and volumeMount, and the PVC exists
```yaml
  volumeMounts:
    - name: otel-storage
      mountPath: /otel-storage
      readOnly: false
  volumes:
    - name: otel-storage
      persistentVolumeClaim:
        claimName: devops-otel-storage
```

But the collector pod exits with error
```
Error: cannot start pipelines: failed to start "awss3/devops" exporter: open /otel-storage/exporter_awss3_devops_logs: permission denied; failed to shutdown pipelines: no existing monitoring routine is running
2025/05/29 20:04:54 collector server run finished with error: cannot start pipelines: failed to start "awss3/devops" exporter: open /otel-storage/exporter_awss3_devops_logs: permission denied; failed to shutdown pipelines: no existing monitoring routine is running
```

I'm not sure what I'm missing in configuration to give it the proper permissions.

## Steps to Reproduce
See description

## Expected Result
file_storage extension should be able to write to mounted volume

## Actual Result
file_storage extension results in `permission denied`

### Collector version

0.126.0

## Environment
OS: Ubuntu 20.04

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

**Comment by VihasMakwana** [comment]
@yuzhouliu9 hello!

Maybe try adding following in your k8s yaml

```yaml

securityContext:
          fsGroup: 1001
          runAsUser: 1001
          runAsGroup: 1001

```
