### ISSUE TITLE
influxdb exporter, failed to convert OTLP metric to line protocol: unsupported sum aggregation temporality AGGREGATION_TEMPORALITY_DELTA

### ISSUE THREAD

**Issue by juanma-cvega** [open-telemetry/opentelemetry-collector-contrib#4038]
**Describe the bug**
I'm currently using Micrometer in a Spring Boot application with the Statsd implementation to send metrics to the collector. I've already tried using the AWS CloudWatch EMF exporter but now I'm trying to send metrics to InfluxDB instead. When the collector tries to send the metrics to the database, I get the error 

> failed to convert OTLP metric to line protocol: unsupported sum aggregation temporality AGGREGATION_TEMPORALITY_DELTA

After enabling debug level for the logs, I can see entries like the following, which I guess are causing the issue. 

>-> Name: tomcat_sessions_created,statistic=count
>-> Description:
>-> Unit:
>-> DataType: IntSum
>-> IsMonotonic: true
>-> AggregationTemporality: AGGREGATION_TEMPORALITY_DELTA

**Steps to reproduce**
Deploy a Spring Boot application with the Micrometer Statsd implementation and flavor 'telegraf' 

**What did you expect to see?**
Metrics being sent to InfluxDB. 

**What did you see instead?**
An error when the collector tries to send the metrics to the database.

**What version did you use?**
Version: 0.29.0

**What config did you use?**
```
extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  statsd:
    endpoint: 0.0.0.0:8125

exporters:
  influxdb:
    endpoint: https://endpoint
    timeout: 500ms
    org: test
    bucket: test
    headers:
      Authorization: "Basic XXX"
    metrics_schema: telegraf-prometheus-v2
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [ statsd ]
      processors: [ ]
      exporters: [ influxdb, logging ]
  extensions: [zpages]
```

**Environment**
AWS ECS Fargate with openjdk base image (Debian).
Collector deployed as a sidecar.
InfluxDB v1.8.3
opentelemetry-java-instrumentation with OTEL_METRICS_EXPORTER=none (currently for X-Ray traces only).
