### ISSUE TITLE
[receiver/prometheusreceiver] HA tracker intermittently working

### ISSUE THREAD

**Issue by khjean** [open-telemetry/opentelemetry-collector-contrib#40401]
## Description
Collect metrics via prometheusreceiver from two otel-collector for HAs and send metrics via prometheusremotewrite.
Use `receivers.prometheus.config.global.external_labels` of promehteusreceiver to set `__replica__`  and `cluster` label.
Transmission endpoint is Mimir(cortex).
Enable HA tracker config from Mimir.

## Steps to Reproduce
1. Collect metrics for target application from 2 otel collectors (using receiver's external_labels)
2. Otel collector sends metrics to mimir via prometheusremotewrite

## Expected Result
Get deduplicated metric series from mimir

## Actual Result
I get intermittent deduplicated metric series
But if I put `external_labels` in prometheusremotewrite, it works fine
i don't know why

### Collector version

0.127.0

## Environment
N/A

## Configtest1 ( HA Tracker intermittently working )
```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 5s
        scrape_protocols: ["PrometheusProto", "OpenMetricsText1.0.0", "OpenMetricsText0.0.1", "PrometheusText0.0.4"]
        external_labels:
          cluster: "channel"
          __replica__: "replica1"
      scrape_configs:
        - job_name: 'application_metrics_0'
          metrics_path: '/actuator/prometheus'
          file_sd_configs:
            - files:
                - "etc/otelcol-contrib/extra/targets/*.yml"
processors:
exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite:
    endpoint: "http://host.docker.internal:3300/api/v1/push"
#    external_labels:
#     cluster: "channel"
#      __replica__: "replica1"
    timeout: 30s
    tls:
      insecure: false
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]
```

## Configtes2 ( HA Tracker successfully working )
```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 5s
        scrape_protocols: ["PrometheusProto", "OpenMetricsText1.0.0", "OpenMetricsText0.0.1", "PrometheusText0.0.4"]
#        external_labels:
#          cluster: "channel"
#          __replica__: "replica1"
      scrape_configs:
        - job_name: 'application_metrics_0'
          metrics_path: '/actuator/prometheus'
          file_sd_configs:
            - files:
                - "etc/otelcol-contrib/extra/targets/*.yml"
processors:
exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite:
    endpoint: "http://host.docker.internal:3300/api/v1/push"
    external_labels:
     cluster: "channel"
      __replica__: "replica1"
    timeout: 30s
    tls:
      insecure: false
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]
```

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell
N/A
```

### Additional context

If you change to prometheus agent mode instead of otel-collector and use the same settings for the remaining settings, it will work well.
If you use `external_labels` in otel-collecotr prometheusremotewrite exporter, it will work well.

**Comment by dashpole** [comment]
> Enable HA tracker config from Mimir.

I don't have much context on how this feature is meant to work.  @jmichalek132 do you know what might be broken?

**Comment by jmichalek132** [comment]
In mimir (cortex) deduplication works by sending metrics via 2 instances differentiated by a label, there's HA tracker which picks one of the pair, requests from that instance are written, from the other one they get discarded.

It might help sharing mimir config / adding debug exporter showing the data sent is the same.
Also it would be helpful showing the queries showing the missing data etc, but not sure this belongs to this repository in the first place and shouldn't be raise against mimir repo.

FYI @dashpole @ArthurSens, if you think it belongs here feel free to assign it to me.

**Comment by khjean** [comment]
for more context, this is my localtest query result
`jvm_buffer_memory_used_bytes{id="direct", instance="host.docker.internal:7777", job="application_metrics_0", cluster="channel"}`
`jvm_buffer_memory_used_bytes{id="direct", instance="host.docker.internal:7777", job="application_metrics_0", cluster="channel", __replica__="replica1"}`
`jvm_buffer_memory_used_bytes{id="direct", instance="host.docker.internal:7777", job="application_metrics_0", cluster="channel", __replica__="replica2"}`

I was expecting the replica1, 2 metric series did not show up. However, they do show up intermittently. 
In local config, mimir's `ha_cluster_label` is `"cluster"` and `ha_replica_label` is `"__replica__"`

I am curious about the difference between the two settings below in the otel collector
- `receivers.prometheus.config.global.external_labels`
- `exporters.prometheusremotewrite.external_labels`

I think the only difference would be which pipeline or step uses external_labels but Only the `exporters.prometheusremotewrite.external_labels` setting works normally with HA_tracker, otherwise it works intermittently

**Comment by krajorama** [comment]
The HA tracker in Mimir is very simple, it will only look at the first time series in every remote write request. And remote write requests split series into batches randomly , so which series is the first is random over time.

When you add the external labels in the Prometheus remote write exporter, the labels are attached to every series for sure. Which means HA tracker can work every time.

When you add the external labels in the Prometheus receiver , I suspect they don't get attached to some synthetic metrics like "up", "scrape_samples_scraped", "scrape_samples_post_metric_relabeling", "scrape_series_added" and if one of these happens to be the first in the remote write request, HA fails and _none_ of the series in the same request will be treated correctly.

What you can do to check is to query these metrics above for a timestamp where you see unexpected metrics. I assume these will not have the replica set.

**Comment by jmichalek132** [comment]
> The HA tracker in Mimir is very simple, it will only look at the first time series in every remote write request. And remote write requests split series into batches randomly , so which series is the first is random over time.
> 
> When you add the external labels in the Prometheus remote write exporter, the labels are attached to every series for sure. Which means HA tracker can work every time.
> 
> When you add the external labels in the Prometheus receiver , I suspect they don't get attached to some synthetic metrics like "up", "scrape_samples_scraped", "scrape_samples_post_metric_relabeling", "scrape_series_added" and if one of these happens to be the first in the remote write request, HA fails and _none_ of the series in the same request will be treated correctly.
> 
> What you can do to check is to query these metrics above for a timestamp where you see unexpected metrics. I assume these will not have the replica set.

Hmm okay so testing this locally this might not be the case, since it seems external labels added via the prometheus receiver are also added to metrics such as  `scrape_samples_scraped`.

Config tested with:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: [localhost:8888]
      global:
        external_labels:
          test: test
exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite/prometheus:
    endpoint: "http://localhost:9091/api/v1/write"
    resource_to_telemetry_conversion:
      enabled: false
    target_info:
      enabled: true
  nop:
processors:
extensions:
  health_check:
  pprof:
service:
  telemetry:
    logs:
      level: "DEBUG"
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
                with_resource_constant_labels:
                  included: ["service.name"]
  extensions: [pprof, health_check]
  pipelines:
    metrics:
      receivers:
        - prometheus
        - otlp
      processors:
      exporters:
        - prometheusremotewrite/prometheus
```

External labels showing up in the prometheus on the receiving side.

![Image](https://github.com/user-attachments/assets/7abc7df2-7e23-4ec4-a7cb-dee700bf93a9)

**Comment by khjean** [comment]
I agree with the above
In my test results, the external label addition of the Prometheus receiver was added normally
However, it does not work properly with the ha tracker

In my test results, I expected the two metric series below to disappear, but they disappeared intermittently
`jvm_buffer_memory_used_bytes{id="direct", instance="host.docker.internal:7777", job="application_metrics_0", cluster="channel", __replica__="replica1"}`
`jvm_buffer_memory_used_bytes{id="direct", instance="host.docker.internal:7777", job="application_metrics_0", cluster="channel", __replica__="replica2"}`

The metric series below not disappeared ( this is normal and expected results except for above )
`jvm_buffer_memory_used_bytes{id="direct", instance="host.docker.internal:7777", job="application_metrics_0", cluster="channel"}`

When I tested it with all the same settings in Prometheus agent mode instead of otel-collector, it worked normally, so I think it is a bug in otel-collector not mimir

**Comment by jmichalek132** [comment]
@khjean to continue to debug this it would be ideal if you would share your full configuration so we can replicate this locally, not just snippets of config / results of queries you run.

**Comment by khjean** [comment]
this is otel-collector replica1 config
```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 5s
        scrape_protocols: ["PrometheusProto", "OpenMetricsText1.0.0", "OpenMetricsText0.0.1", "PrometheusText0.0.4"]
        external_labels:
          cluster: "channel"
          __replica__: "replica1"
      scrape_configs:
        - job_name: 'application_metrics_0'
          metrics_path: '/actuator/prometheus'
          file_sd_configs:
            - files:
                - "etc/otelcol-contrib/extra/targets/*.yml"
processors:
exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite:
    endpoint: "http://host.docker.internal:3300/api/v1/push"
    timeout: 30s
    tls:
      insecure: false
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]
```

this is otel-collector replica2 config
```
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 5s
        scrape_protocols: ["PrometheusProto", "OpenMetricsText1.0.0", "OpenMetricsText0.0.1", "PrometheusText0.0.4"]
        external_labels:
          cluster: "channel"
          __replica__: "replica2"
      scrape_configs:
        - job_name: 'application_metrics_0'
          metrics_path: '/actuator/prometheus'
          file_sd_configs:
            - files:
                - "etc/otelcol-contrib/extra/targets/*.yml"
processors:
exporters:
  debug:
    verbosity: detailed
  prometheusremotewrite:
    endpoint: "http://host.docker.internal:3300/api/v1/push"
    timeout: 30s
    tls:
      insecure: false
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite]
```

this is mimir's config
```
...
mimir:
  structuredConfig:
    distributor:
      remote_timeout: 5s
      ha_tracker:
        enable_ha_tracker: true
        kvstore:
          store: consul
          consul:
            host: mimir-consul-server.mimir.svc.cluster.local:8500
    limits:
      accept_ha_samples: true
      ha_cluster_label: "cluster"
      ha_replica_label: "__replica__"
...
```
