### ISSUE TITLE
Libhoney receiver msgpack response is wrong

### ISSUE THREAD

**Issue by mterhar** [open-telemetry/opentelemetry-collector-contrib#40413]
## Description

The libhoney receiver properly handles batches of events but then responds with an OTLP-style `partialSuccess` sort of response. The libhoney exporters will not necessarily error our but may retry or emit error log messages. 

## Steps to Reproduce

It's difficult to send msgpack from the CLI to get a raw signal back, but if you use the libhoney-go examples, you can see it in action. 

## Expected Result

A msgpacked object like `[]ResponseInBatch{{Status: http.StatusAccepted}}`

## Actual Result

A msgpacked object like `partialSuccess: []`

### Collector version

1.127.0

## Environment
OS: macos 15.5
Compiler(if manually compiled): go1.23.8

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4417
      http:
        endpoint: 0.0.0.0:4418
  libhoney:
    http:
      endpoint: 0.0.0.0:8088
      traces_url_paths:
        - "/1/events"
        - "/1/batch"
    auth_api: https://api.honeycomb.io
    fields:
      resources:
        service_name: service.name
      scopes:
        library_name: library.name
        library_version: library.version
      attributes:
        trace_id: trace.trace_id
        parent_id: trace.parent_id
        span_id: trace.span_id
        name: name
        error: error
        spankind: span.kind
        durationFields:
          - duration_ms
```

### Log output

```shell

```
