### ISSUE TITLE
Adjusted count from signaltometrics connector do not have span information

### ISSUE THREAD

**Issue by himamulch** [open-telemetry/opentelemetry-collector-contrib#40465]
### Component(s)

connector/signaltometrics

### Describe the issue you're reporting

Is there a reason why the adjusted count metric data point generated using signaltometrics connector does not carry the name of the span for which the metric is generated? Or am I missing something in the config causing this behavior? Below is a reference config I am using -

  signaltometrics:
    spans:
    - name: adjusted_count
      description: Adjusted count for spans with sampling threshold
      sum:
        value: Int(AdjustedCount())

**Comment by lahsivjar** [comment]
> signaltometrics:
spans:
- name: adjusted_count
description: Adjusted count for spans with sampling threshold
sum:
value: Int(AdjustedCount())

The configuration you are using will generate a metric named `adjusted_count` which will have the adjusted count for all the spans. If you want to get a sum metric plotting adjusted count and a dimension with `span.name` as a value, then it won't be possible to do it directly using the connector. You could, however, use something like the [transformprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor) to add a new span attribute for `span.name`:

```
trace_statements:
 - context: span
   statements:
    - set(attributes["span_name"], span.name)
```

Then, you can use the signal to metrics connector to produce the required metrics:

```
signaltometrics:
  spans:
    - name: span.adjusted_count
      description: Adjusted count for spans with sampling threshold
      attributes:
        - key: span_name
      sum:
        value: Int(AdjustedCount())
```

Note that doing this has a potential to cause a high cardinality for the metric `span.adjusted_count` depending on the cardinality of span names.
