### ISSUE TITLE
[extension/awslogsencoding] Add support for AWS RDS log

### ISSUE THREAD

**Issue by constanca-m** [open-telemetry/opentelemetry-collector-contrib#40474]
### Component(s)

extension/encoding/awslogsencoding

### Is your feature request related to a problem? Please describe.

Add support for AWS RDS logs coming through cloudwatch.  The log structure depends on the engine or log type, so we need to add separation for it ([PostgreSQL](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.PostgreSQL.overview.parameter-groups.html) for example).

### Describe the solution you'd like

```yaml
extension:
  awslogs_encoding:
    format: cloudwatch_logs_subscription_filter
    message_format:
      engine: postgresql # mariadb, ...
      log_type: # general_log, slow_query_log, ...
```

### Describe alternatives you've considered

N/A

### Additional context

N/A
