### ISSUE TITLE
New component: Tinybird Exporter

### ISSUE THREAD

**Issue by jordivilaseca** [open-telemetry/opentelemetry-collector-contrib#40475]
### The purpose and use-cases of the new component

The Tinybird OpenTelemetry Exporter will enable the export of traces, metrics, and logs to Tinybird, a real-time data platform built over ClickHouse. This exporter is designed for developers and data teams who need to analyze OpenTelemetry data at scale and in real-time.

The OpenTelemetry exporter leverages Tinybird’s [Events API](https://www.tinybird.co/docs/classic/get-data-in/ingest-apis/events-api) to automatically handle ingestion scaling and backpressure, removing the complexity of infrastructure provisioning and management that traditionally comes with processing large volumes of observability data.

Key use cases include real-time monitoring dashboards, anomaly detection systems, performance analytics, and any application requiring immediate insights from OpenTelemetry data streams.

### Example configuration for the component

```
exporters:
  tinybird:
    token: ${TINYBIRD_TOKEN}
    metrics_datasource: metrics
    logs_datasource: logs
    traces_datasource: traces
    endpoint: https://api.us-east.aws.tinybird.co
```

### Telemetry data types supported

logs, traces and metrics

### Additional context

Implementation PRs will be provided by a developer of Tinybird
