### ISSUE TITLE
[spanmetricsprocessor] latency_histogram_buckets only supports buckets >= 1ms

### ISSUE THREAD

**Issue by fabiomdiniz** [open-telemetry/opentelemetry-collector-contrib#4051]
**Describe the bug**
It seems that any sub-millisecond bucket in latency_histogram_buckets  (e.g. ``0.1ms or 1us``) is ignored by spanmetricsprocessor

**Steps to reproduce**
Define a sub-msec bucket and send metrics:

```
processors:
  spanmetrics:
    metrics_exporter: otlp/spanmetrics
    latency_histogram_buckets: [0.1ms, 0.5ms, 1ms, 10ms]
```

and see that for this sample config only buckets 1ms and 10ms are created
