### ISSUE TITLE
Make the `groupbyattrsprocessor` behave more like `GROUP BY` in SQL

### ISSUE THREAD

**Issue by crazyscientist** [open-telemetry/opentelemetry-collector-contrib#40524]
Imagine, within a batch there are multiple resources, metrics and datapoints, e.g.

```
Resource {service.name="foo", service.instance.id="id-1"}
  Metric "counter-1" (SUM)
    DataPoint {some.attr="some value"}
Resource {service.name="foo", service.instance.id="id-2"}
  Metric "counter-1" (SUM)
    DataPoint {some.attr="some value"}
```

and I would like to group this by "service.name" to look like this:

```
Resource {service.name="foo"}
  Metric "counter-1" (SUM)
    DataPoint {some.attr="some value"}
    DataPoint {some.attr="some value"}
```

Naively, my expectation would have been that I can achieve this by defining a pipeline like this:

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 127.0.0.1:4318
processors:
  batch:
    timeout: 10s
  groupbyattrs:
    keys:
      - "service.name"
  transform/del_attr:
    metric_statements:
      - keep_keys(resource.attributes, ["service.name"])
service:
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - batch
        - groupbyattrs
```

But the metrics and datapoints are not regrouped, because of the different values of the "service.instance.id" attribute. ATM, I have to explicitly delete that attribute in order to group as intended.

Long story short: I'd like to propose a config option that allows grouping like this (i.e. somehow aggregate the attributes, which are not specified in the `groupbyattrs.keys` list). Or, if this intended behavior for this processor, to emphasize on this little detail.

Thank you
