### ISSUE TITLE
Error when sending metrics to datadog "Payload is empty"

### ISSUE THREAD

**Issue by kellen-miller** [open-telemetry/opentelemetry-collector-contrib#40531]
## Description

When using exporting metrics to datadog, seeing the following error

## Steps to Reproduce

Turn on the datadog/connector and datadog/exporter.

## Expected Result

No error

## Actual Result

Seeing an `Payload is empty` error constantly

### Collector version

v0.124.1

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:
        send_batch_max_size: 1000
        send_batch_size: 100
        timeout: 10s

      memory_limiter:
        check_interval: 1s
        limit_mib: 1000

      tail_sampling:
        policies:
          [
            {
              name: error-policy,
              type: status_code,
              status_code: { status_codes: [ERROR] }
            },
            {
              name: probabilistic-policy,
              type: probabilistic,
              probabilistic: { sampling_percentage: 5 }
            },
          ]

    connectors:
      datadog/connector:
        traces:
          span_name_as_resource_name: true
          compute_stats_by_span_kind: true
          peer_tags_aggregation: true

    exporters:
      datadog/exporter:
        api:
          site: datadoghq.com
          key: ${env:DD_API_KEY}

    service:
      pipelines:
        metrics:
          receivers: [otlp, datadog/connector]
          processors: [memory_limiter, batch]
          exporters: [datadog/exporter]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [datadog/connector]
        traces/sampling:
          receivers: [datadog/connector]
          processors: [memory_limiter, tail_sampling, batch]
          exporters: [datadog/exporter]
```

### Log output

```shell
2025-06-06T16:40:36.354Z error datadog@v0.127.0/zaplogger.go:67 Error code "400 Bad Request" received while sending transaction to "https://api.datadoghq.com/api/beta/sketches": "Payload is empty", dropping it {"resource": {}, "otelcol.component.id": "datadog/exporter", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics"}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/datadog.(*Zaplogger).Errorf
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/datadog@v0.127.0/zaplogger.go:67
github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder/transaction.(*HTTPTransaction).internalProcess
github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder@v0.66.0-devel.0.20250407180930-ebfcfa2817ce/transaction/transaction.go:427
github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder/transaction.(*HTTPTransaction).Process
github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder@v0.66.0-devel.0.20250407180930-ebfcfa2817ce/transaction/transaction.go:355
github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder.(*Worker).process
github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder@v0.66.0-devel.0.20250407180930-ebfcfa2817ce/worker.go:196
github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder.(*Worker).callProcess.func1
github.com/DataDog/datadog-agent/comp/forwarder/defaultforwarder@v0.66.0-devel.0.20250407180930-ebfcfa2817ce/worker.go:184
```
