### ISSUE TITLE
getting resource_not_found_exception with elasticsearch 8.17 version while trying to export metrics from otel collector to elasticsearch.

### ISSUE THREAD

**Issue by HiteshDhuria** [open-telemetry/opentelemetry-collector-contrib#40631]
### Component(s)

exporter/elasticsearch

## Description

I am using otel contrib collector with traces being sent to jaeger collector and metrics to elasticsearch. Despite with all proper configuration, I am getting resource_not_found_exception with empty reason.

## Steps to Reproduce

  elasticsearch/metrics: # This exporter will now be valid with the contrib image
    endpoints: ["https://es:9200"]
    metrics_index: "otel-main-metrics"
    mapping:
      mode: otel
    headers:
      Authorization: "Basic credentialbase64"
    tls:
      insecure_skip_verify: true
    retry:
      max_retries: 5
      retry_on_status:
        - 429
        - 500
      enabled: true
      initial_interval: 1
    sending_queue:
      enabled: true
      num_consumers: 10 
      queue_size: 5000

## Expected Result
                   successful insert should come.
## Actual Result
                getting resource_not_found_exception with empty reason.

### Collector version

0.126.0

## Environment
OS: Payara image packed with ECS

### OpenTelemetry Collector configuration

```yaml
elasticsearch/metrics: # This exporter will now be valid with the contrib image
    endpoints: ["https://es:9200"]
    metrics_index: "otel-main-metrics"
    mapping:
      mode: otel
    headers:
      Authorization: "Basic credentialbase64"
    tls:
      insecure_skip_verify: true
    retry:
      max_retries: 5
      retry_on_status:
        - 429
        - 500
      enabled: true
      initial_interval: 1
    sending_queue:
      enabled: true
      num_consumers: 10 
      queue_size: 5000
```

### Log output

```shell

```
