### ISSUE TITLE
In Windows the filelog receiver includes are incorrectly case sensitive when filenames use a wildcard

### ISSUE THREAD

**Issue by tolgabalci** [open-telemetry/opentelemetry-collector-contrib#40685]
### What happened?

Under Windows the following example matches the file MyLog.20250612.log even though the case does not match:

```yaml
receivers:
  filelog:
    include:
      - "c:/logs/mylog.20250612.log"
```

However, the next example with a wildcard in place of the date fails the match:

```yaml
receivers:
  filelog:
    include:
      - "c:/logs/mylog.*.log"
```

This makes it challenging to reliably use the filelog receiver under Windows.  

One solution is to use character classes to provide both the upper and lower versions of every character in the file:

```yaml
receivers:
  filelog:
    include:
      - "c:/[lL][oO][gG][sS]/[mM][yY][lL][oO][gG].*.[lL][oO][gG]"
```

While the above works, it hurts the legibility and maintainability of the config files.

This behavior also makes the experience under Windows inconsistent. In some scenarios, the filenames are case-insensitive, and in others, they are case-sensitive. This can lead to easily missing data collection that can be difficult to track down.

**UPDATE**: Found an additional, less significant quirk. It appears that the drive letter must always be stated as lowercase.  The following fails to match:
```yaml
receivers:
  filelog:
    include:
      - "[cC]:/[lL][oO][gG][sS]/[mM][yY][lL][oO][gG].*.[lL][oO][gG]"
```

Specifying the drive letter in uppercase also fails to match:
```yaml
receivers:
  filelog:
    include:
      - "C:/[lL][oO][gG][sS]/[mM][yY][lL][oO][gG].*.[lL][oO][gG]"
```

While explicitly specifying the drive letter in lowercase matches correctly:
```yaml
receivers:
  filelog:
    include:
      - "c:/[lL][oO][gG][sS]/[mM][yY][lL][oO][gG].*.[lL][oO][gG]"
```
 

### Collector version

v0.125.0

## Environment
Windows (any version), tested under Windows 10

### OpenTelemetry Collector configuration

```yaml
receivers:
  filelog:
    include:
      - "c:/logs/mylog.*.log"
```

### Log output

```shell

```
