### ISSUE TITLE
Prometheus not able to scrape otel-collector's internal metrics in v0.128.0

### ISSUE THREAD

**Issue by dhanyarmathews** [open-telemetry/opentelemetry-collector-contrib#40687]
### Component(s)

cmd/otelcontribcol

### Describe the issue you're reporting

We had a setup that used v0.120.0. 
The command used for the setup creation is:
kubectl create --namespace otel-demo -f https://raw.githubusercontent.com/open-telemetry/opentelemetry-demo/main/kubernetes/opentelemetry-demo.yaml

The image is
image: otel/opentelemetry-collector-contrib:0.120.0

In the configMap, there is a parameter telemetry.metrics.address key that points to ' ${env:MY_POD_IP}:8888'

In that we could see collector's internal metrics being available at the prometheus.
However, when we change the version of the image is changed to v.0.128.0, prometheus is not able to scrape metrics.
Following is the change:
image: otel/opentelemetry-collector-contrib:0.128.0

The configMap parameter  telemetry.metrics.address is deprecated in v0.128.0. Based on  https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/observability.md, we tried adding 'prometheus'key to reader but it did not help either.

What need to be changed for otel/opentelemetry-collector-contrib:0.128.0 to be able to see otel collector's internal metrics in prometheus.

**Comment by francois07** [comment]
As per the [documentation](https://opentelemetry.io/docs/collector/internal-telemetry/#configure-internal-metrics), you can use `service.telemetry.metrics.readers` like so

```yaml
service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: ${env:MY_POD_IP}
                port: 8888
```

To expose a prometheus endpoint of internal telemetry
