### ISSUE TITLE
How to rate limit the pipeline - file input

### ISSUE THREAD

**Issue by smalenfant** [open-telemetry/opentelemetry-collector-contrib#40725]
### Component(s)

exporter/influxdb

### Describe the issue you're reporting

I'm using the otlpjsonfile receiver to parse an exported output. Just trying to create a repeatable scenario. I had to rebatch using a python script due to input size (#40623). Now that my metrics are being read, I'm experiencing output drops.

It doesn't seem like the `sending_queue` and `retry_on_failure` is working. At least not from the output.

Show I be looking at some internal Otel metrics to verify that metrics are retried and not dropped?

How can I slow down either the receiver, or create back pressure so it doesn't drop any metrics?

```
receivers:
  otlpjsonfile:
    include:
      - /tmp/rebatch.json
    start_at: "beginning"

  filter/include:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - ossi_.*

exporters:
  influxdb:
    endpoint: http://influxdb3-core:8181
    timeout: 10s
    org: cox
    bucket: telegraf
    sending_queue:
      enabled: true
    retry_on_failure:
      enabled: true

service:
  pipelines:
    metrics:
      receivers:
        - otlpjsonfile
      processors:
        - filter/include
      exporters:
        - influxdb
```

Results:

```
otel-collector  | 2025-06-14T12:25:27.598Z	error	internal/base_exporter.go:117	Exporting failed. Rejecting data.	{"resource": {"service.instance.id": "c1aae3a9-85cc-46ad-b74b-d25970c41a50", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "influxdb", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics", "error": "sending queue is full", "rejected_items": 2900}
```
