### ISSUE TITLE
[processor/k8sattributesprocessor] pod_association not working for source: container.id

### ISSUE THREAD

**Issue by florianl** [open-telemetry/opentelemetry-collector-contrib#40745]
### Expected result

Associate and enrich ResourceProfile.Attribute with additional k8s information based on container.id.

### Component(s)

processor/k8sattributes

### What happened?

Using the container ID starting with `581f3ac4` as an example.

This container ID is known by kubectl:
```
$ kubectl get pods --all-namespaces -o jsonpath='{range .items[*]}{range .status.containerStatuses[*]}{.containerID}{"\n"}{end}{end}' | grep 581f3ac4745d68495d71651b76e5ff19f42be92323c25d9281120d3594931a88
containerd://581f3ac4745d68495d71651b76e5ff19f42be92323c25d9281120d3594931a88
```

From debug logs of `k8sattributes` one can also tell, that it was detected in some way:
```
2025-06-16T14:09:37.044163599Z 2025-06-16T14:09:37.044Z	debug	k8sattributesprocessor@v0.128.0/processor.go:143	evaluating pod identifier	{"resource": {"service.instance.id": "851203be-4a32-4115-aa09-bb73bfe7e1d8", "service.name": "otelcol-ebpf-profiler", "service.version": "0.128.0"}, "otelcol.component.id": "k8sattributes", "otelcol.component.kind": "processor", "otelcol.pipeline.id": "profiles", "otelcol.signal": "profiles", "value": [{"Source":{"From":"resource_attribute","Name":"container.id"},"Value":"581f3ac4745d68495d71651b76e5ff19f42be92323c25d9281120d3594931a88"},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""}]}
```

But looking at the debug output of the exporter, resource attributes were not enriched based on the container.id:
```
[..]
2025-06-16T14:09:37.081041887Z ResourceProfiles #3
2025-06-16T14:09:37.081046047Z Resource SchemaURL: https://opentelemetry.io/schemas/1.6.1
2025-06-16T14:09:37.081047762Z Resource attributes:
2025-06-16T14:09:37.081049321Z      -> container.id: Str(581f3ac4745d68495d71651b76e5ff19f42be92323c25d9281120d3594931a88)
2025-06-16T14:09:37.081050896Z      -> host.name: Str(otelcol-profiler-2bgb5)
2025-06-16T14:09:37.081052521Z      -> os.type: Str(linux)
2025-06-16T14:09:37.081053973Z ScopeProfiles #0
[..]
```

### Collector version

v0.128.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  profiling:
    SamplesPerSecond: 19

processors:
  resourcedetection:
    detectors: [ system ]
    system:
      hostname_sources: [ "os" ]
      resource_attributes:
        host.id:
          enabled: true
        host.name:
          enabled: true
        os.type:
          enabled: true
  k8sattributes:
    auth_type: "serviceAccount"
    passthrough: false
    filter:
      # only retrieve pods running on the same node as the collector
      node_from_env_var: KUBERNETES_NODE_NAME
    extract:
      # The attributes provided in 'metadata' will be added to associated resources
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.start_time
        - service.namespace
        - service.name
        - service.version
        - service.instance.id
      labels:
        # This label extraction rule takes the value 'app.kubernetes.io/component' label and maps it to the 'app.label.component' attribute which will be added to the associated resources
        - tag_name: app.label.component
          key: app.kubernetes.io/component
          from: pod
      otel_annotations: true 
    pod_association:
      - sources:
          # This rule associates all resources containing the 'container.id' attribute with the matching pods. If this attribute is not present in the resource, this rule will not be able to find the matching pod.
          - from: resource_attribute
            name: container.id

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: debug  # Set the global logging level to debug
  pipelines:
    profiles:
      receivers: [ profiling ]
      processors: [ resourcedetection, k8sattributes ]
      exporters: [ debug ]
```

### Log output

```shell

```

### Additional context

<details>
<summary> used manifest.yaml </summary>

```
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: otelcol-profiler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol-profiler
  namespace: otelcol-profiler
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - namespaces
  - endpoints
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol-profiler
  namespace: otelcol-profiler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otelcol-profiler
subjects:
- kind: ServiceAccount
  name: otelcol-profiler
  namespace: otelcol-profiler
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: otelcol-profiler
  name: otelcol-profiler
spec:
  selector:
    matchLabels:
      app: otelcol-profiler
  template:
    metadata:
    spec:
      hostPID: true
      containers:
        - name: otelcol-profiler
          image: flehner/testing:20250616011
          securityContext:
            procMount: "Unmasked"
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            limits:
              memory: 500Mi
              cpu: "2"
            requests:
              memory: 500Mi
              cpu: "2"
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: debugfs
              mountPath: /sys/kernel/debug
      serviceAccountName: otelcol-profiler
      volumes:
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
            type: Directory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol-profiler
  namespace: otelcol-profiler

```

</details>

**Comment by ChrsMark** [comment]
I cannot reproduce it with metrics:

```yaml
mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.128.0

presets:
  kubernetesAttributes:
    enabled: true
    # You can also configure the preset to add all of the associated pod's labels and annotations to you telemetry.
    # The label/annotation name will become the resource attribute's key.
    extractAllPodLabels: true
    extractAllPodAnnotations: true
  kubeletMetrics:
    enabled: true

clusterRole:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - nodes
        - services
        - pods
        - namespaces
      verbs:
        - get
        - list
        - watch
    - apiGroups: [ "" ]
      resources: [ "nodes/proxy"]
      verbs: [ "get" ]
    - apiGroups:
        - ""
      resources:
        - nodes/stats
      verbs:
        - get
    - nonResourceURLs:
        - "/metrics"
      verbs:
        - get

resources:
  limits:
    cpu: 1
    memory: 1Gi

config:
  exporters:
    debug:
      verbosity: detailed

  processors:
    k8sattributes:
      extract:
        metadata:
          - k8s.namespace.name
          - k8s.deployment.name
          - k8s.statefulset.name
          - k8s.daemonset.name
          - k8s.cronjob.name
          - k8s.job.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
      filter:
        node_from_env_var: K8S_NODE_NAME
      passthrough: false
      pod_association:
        - sources:
            - from: resource_attribute
              name: container.id

  receivers:
    kubeletstats:
      auth_type: serviceAccount
      collection_interval: 20s
      endpoint: ${env:K8S_NODE_IP}:10250
      insecure_skip_verify: true
      extra_metadata_labels:
        - container.id

  service:
    extensions: [health_check]
    telemetry:
      logs:
        level: DEBUG
    pipelines:
      metrics:
        receivers: [ kubeletstats ]
        processors: [ k8sattributes ]
        exporters: [ debug ]
```

I also see similar logs when association is performed:

```console
2025-06-17T10:23:20.462Z	debug	k8sattributesprocessor@v0.128.0/processor.go:143	evaluating pod identifier	{"resource": {"service.instance.id": "00efdd65-23d5-4d90-b90f-0886d6459eff", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "k8sattributes", "otelcol.component.kind": "processor", "otelcol.pipeline.id": "metrics", "otelcol.signal": "metrics", "value": [{"Source":{"From":"resource_attribute","Name":"container.id"},"Value":"c8b768d0cb404bb7ffd480a2a270950e4164f757b369e7c8d40ab5bed3f982fa"},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""},{"Source":{"From":"","Name":""},"Value":""}]}
```

I wonder if that's a specific issue with profiles signal 🤔 .

I also wonder how https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35999 ensured that the processor works with profiles. I see we never actually added e2e tests: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35999#pullrequestreview-2404696714. The [added e2e tests](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35999/files#diff-92cca7ce2020408b9bcd2fd0eb8d457505f31cebf5e124e2b9cf6f053dd7f19eL622) never check if profiles are enriched by the processor since the telemetrygen does not not support profiles yet.
