### ISSUE TITLE
k8s_observer should add `spec.nodeName` of a pod to the pod details

### ISSUE THREAD

**Issue by ChristianCiach** [open-telemetry/opentelemetry-collector-contrib#40768]
### Component(s)

extension/observer/k8sobserver 

### Is your feature request related to a problem? Please describe.

`.spec.nodeName` is a mandatory attribute for all pods, but it's not currently added to the pod details exposed by the `k8s_observer` extension. Because of this, when using the `receiver_creator`, it's not currently possible to declare rules and config-templates that reference the node of the pod.

When using RKE2 oder K3s, there are some "bare pods" in `kube-system` namespace that don't match the default filelog filter, so I need to create my own config for these special pods. These pods are best identified by the local node name they use as a suffix of their names. I try to target these pods:

```yaml
    receivers:
      receiver_creator/logs:
        watch_observers: [k8s_observer]
        receivers:
          filelog/control-plane:
            rule: type == "pod.container" && pod.namespace == "kube-system" && pod.name endsWith [?????]
            config:
              include:
                - /var/log/pods/`pod.namespace`_`pod.name`_`pod.annotations["kubernetes.io/config.hash"]`/`container_name`/*.log
```

There is currently no way to complete this `rule` statement.

### Describe the solution you'd like

I would like to see the `spec.nodeName` attribute added to the pod details, exposed as `k8s.pod.node`, so that I can create such a rule:

```yaml
rule: type == "pod.container" && k8s.namespace.name == "kube-system" && k8s.pod.name endsWith k8s.pod.node
```

### Describe alternatives you've considered

This use-case could also be satisfied by allowing access to environment variables inside the rule-expressions, ~~but this also doesn't seem to be possible~~.

Edit: I was wrong about the environment variables. Looks like they can be accessed everywhere in the config:

```yaml
    receivers:
      receiver_creator/logs:
        watch_observers: [k8s_observer]
        receivers:
          filelog/control-plane:
            # RKE2 kubernetes system pods
            rule: >-
              type == "pod.container" 
              && pod.namespace == "kube-system" 
              && pod.labels["tier"] == "control-plane" 
              && "kubernetes.io/config.hash" in pod.annotations
              && pod.name endsWith "-${env:K8S_NODE_NAME}"
            config:
              include:
                - /var/log/pods/`pod.namespace`_`pod.name`_`pod.annotations["kubernetes.io/config.hash"]`/`container_name`/*.log
              include_file_name: false
              include_file_path: true
```

I still think there are legitimate use-cases that require to access the nodeName of a pod.
