### ISSUE TITLE
[receiver_creator] In "discovery" mode, allow specifying a default config (or even enforce specific settings)

### ISSUE THREAD

**Issue by ChristianCiach** [open-telemetry/opentelemetry-collector-contrib#40769]
### Component(s)

receiver/receivercreator

### Is your feature request related to a problem? Please describe.

When using the receiver_creator with `discovery: true`, the default (log) configuration is currently hardcoded:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/af7b258b86a0aabf96678d968972afffa4790cdb/receiver/receivercreator/discovery.go#L217-L222

As a cluster administrator I would like to add some attributes to this default config. In fact, I even would like to enforce some attributes.

In particular, I want to ensure that `filelog.config.storage` is set for *all* filelog receivers.

Currently, when users add a `logs/config` annotation to their pods, they need to specify the `storage` attribute as well:

```yaml
      annotations:
        io.opentelemetry.discovery.logs.redis/config: |
          storage: some-storage-id
```

Of course, this can easily be forgotten. Also, I think the users should not even know about the existence of the storage configuration. This should be the responsibility of me, the cluster administrator. Users should not be able to disable the storage or set another storage ID.

### Describe the solution you'd like

At the very least, the receiver_creator should allow to extend the default filelog configuration. 

Better yet, it should (maybe in addition to allowing custom defaults) allow to override the user provided configuration. Maybe something like that:

```yaml
  config:
    extensions:
      k8s_observer: {}
    receivers:
      receiver_creator/logs:
        watch_observers: [k8s_observer]
        discovery:
          enabled: true
          filelog_config:
            default: |
              # Override the default "operators" config of the receiver_creator
              # To add additional log parsing
              operators:
                - type: container
                - type: recombine
                  combine_field: body
                  is_first_entry: body matches "^\\S"
            enforced: |
              # Fixed "storage" setting, overrides even user-provided configuration
              storage: my-storage

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

**Comment by ChrsMark** [comment]
Hey @ChristianCiach, can't the default config be covered by the `default_annotations` [setting](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/receivercreator/config.go#L95)?

Sth like the following:

```yaml
receiver_creator/logs:
  watch_observers: [ k8s_observer ]
  discovery:
    enabled: true
    default_annotations:
      io.opentelemetry.discovery.logs/config: |
        operators:
          - type: container
          - type: recombine
             combine_field: body
             is_first_entry: body matches "^\\S"
```

One thing to note here is that the default hard-coded config can be extended or overridden ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/receivercreator#define-configuration-1)). Extending the config might complicates a little bit the behaviour so we might consider dropping this and only allow overriding. 

I also hit an issue with default config for metrics at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/40712.

@dmitryax let us know what think on these.

**Comment by ChristianCiach** [comment]
> Hey @ChristianCiach, can't the default config be covered by the default_annotations [setting](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/receivercreator/config.go#L95)?

I didn't try it, but I don't think it will work as I need it to.

For example, assume I would configure something like that:

```yaml
receiver_creator/logs:
  watch_observers: [ k8s_observer ]
  discovery:
    enabled: true
    default_annotations:
      io.opentelemetry.discovery.logs/config: |
        storage: my-storage-id
```

And a user configures their pod like this:

```yaml
metadata:
  annotations:
    io.opentelemetry.discovery.logs/config: |
      max_log_size: "3MiB"
```

... then surely this annotation would completely replace the default-annotation, including replacing the storage confguration?

Edit: [Yes, it would](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/29eb0a741a519b082a79a118c4b91b0ce3d52a89/receiver/receivercreator/discovery.go#L300) :)
