### ISSUE TITLE
JMX receiver was not starting in Kubernetes pod

### ISSUE THREAD

**Issue by saikalyanbhagavathula** [open-telemetry/opentelemetry-collector-contrib#40794]
### Component(s)

receiver/jmx

## Description
I tried to start a jmx receiver in a kubernetes pod but getting below error while starting the jmx receiver.

 $ kubectl logs otel-collector-2pmlq -n default
Defaulted container "otel-collector" out of: otel-collector, init-downloader (init)
2025-06-18T06:13:03.526Z	info	service@v0.128.0/service.go:199	Setting up own telemetry...	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}}
2025-06-18T06:13:03.527Z	info	builders/builders.go:26	Development component. May change in the future.	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "debug", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics"}
2025-06-18T06:13:03.531Z	info	service@v0.128.0/service.go:259	Starting otelcol-contrib...	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "Version": "0.128.0", "NumCPU": 24}
2025-06-18T06:13:03.531Z	info	extensions/extensions.go:41	Starting extensions...	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}}
2025-06-18T06:13:03.533Z	info	otlpreceiver@v0.128.0/otlp.go:117	Starting GRPC server	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "jmx", "otelcol.component.kind": "receiver", "endpoint": "0.0.0.0:34605"}
2025-06-18T06:13:03.533Z	info	service@v0.128.0/service.go:282	Everything is ready. Begin running and processing data.	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}}
2025-06-18T06:13:03.539Z	error	subprocess/subprocess.go:244	subprocess died	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "jmx", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "error": "fork/exec /opt/java/java-17-openjdk/bin/java: no such file or directory"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess.(*Subprocess).run
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver@v0.128.0/internal/subprocess/subprocess.go:244
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess.(*Subprocess).Start.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver@v0.128.0/internal/subprocess/subprocess.go:117

## Steps to Reproduce
Pasting the config in below config section

## Expected Result

Expected to jmx receiver start and collect metrics.

## Actual Result

Jmx receiver failing with below error.

2025-06-18T06:13:03.533Z	info	service@v0.128.0/service.go:282	Everything is ready. Begin running and processing data.	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}}
2025-06-18T06:13:03.539Z	error	subprocess/subprocess.go:244	subprocess died	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "jmx", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "error": "fork/exec /opt/java/java-17-openjdk/bin/java: no such file or directory"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess.(*Subprocess).run
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver@v0.128.0/internal/subprocess/subprocess.go:244
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess.(*Subprocess).Start.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver@v0.128.0/internal/subprocess/subprocess.go:117

### Collector version

0.128.0

### OpenTelemetry Collector configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      jmx:
        jar_path: /opt/jmx/opentelemetry-java-contrib-jmx-metrics.jar
        endpoint: service:jmx:rmi:///jndi/rmi://0.0.0.0:5656/jmxrmi
        collection_interval: 10s
        target_system: jvm
    processors: 
    exporters: 
      debug:
        verbosity: detailed
    service:
      pipelines:
        metrics:
          receivers:
            - jmx
          processors:
          exporters:
            - debug

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  namespace: default
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector-sa
      volumes:
        - name: otel-java-bin
          emptyDir: {}
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-config
        - name: otel-jmx-jar
          emptyDir: {}
        - name: tmp-dir
          emptyDir: {}

      initContainers:
        - name: init-downloader
          image: alpine
          command:
            - sh
            - -c
            - >
              apk add --no-cache wget openjdk17 &&
              cp -r /usr/lib/jvm/java-17-openjdk /opt/java &&
              wget -O /opt/jmx/opentelemetry-java-contrib-jmx-metrics.jar https://github.com/open-telemetry/opentelemetry-java-contrib/releases/download/v1.46.0/opentelemetry-jmx-metrics.jar && echo "jar download" && java -version && ls /opt && ls /opt/jmx 
          volumeMounts:
            - name: otel-java-bin
              mountPath: /opt/java
            - name: otel-jmx-jar
              mountPath: /opt/jmx

      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.128.0
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: PATH
              value: $PATH:/opt/java/java-17-openjdk/bin
          args:
            - "--config=/etc/otel-collector-config.yaml"
          volumeMounts:
            - name: otel-collector-config-vol
              mountPath: /etc/otel-collector-config.yaml
              subPath: otel-collector-config.yaml
            - name: otel-jmx-jar
              mountPath: /opt/jmx
            - name: tmp-dir
              mountPath: /tmp
            - name: otel-java-bin
              mountPath: /opt/java
```

### Log output

```shell
kubectl logs otel-collector-2pmlq -n default
Defaulted container "otel-collector" out of: otel-collector, init-downloader (init)
2025-06-18T06:13:03.526Z	info	service@v0.128.0/service.go:199	Setting up own telemetry...	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}}
2025-06-18T06:13:03.527Z	info	builders/builders.go:26	Development component. May change in the future.	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "debug", "otelcol.component.kind": "exporter", "otelcol.signal": "metrics"}
2025-06-18T06:13:03.531Z	info	service@v0.128.0/service.go:259	Starting otelcol-contrib...	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "Version": "0.128.0", "NumCPU": 24}
2025-06-18T06:13:03.531Z	info	extensions/extensions.go:41	Starting extensions...	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}}
2025-06-18T06:13:03.533Z	info	otlpreceiver@v0.128.0/otlp.go:117	Starting GRPC server	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "jmx", "otelcol.component.kind": "receiver", "endpoint": "0.0.0.0:34605"}
2025-06-18T06:13:03.533Z	info	service@v0.128.0/service.go:282	Everything is ready. Begin running and processing data.	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}}
2025-06-18T06:13:03.539Z	error	subprocess/subprocess.go:244	subprocess died	{"resource": {"service.instance.id": "e8bf9d6e-9fa3-40e3-a7b7-f830ab8d6146", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "jmx", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "error": "fork/exec /opt/java/java-17-openjdk/bin/java: no such file or directory"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess.(*Subprocess).run
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver@v0.128.0/internal/subprocess/subprocess.go:244
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess.(*Subprocess).Start.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver@v0.128.0/internal/subprocess/subprocess.go:117
```

**Comment by VihasMakwana** [comment]
I suspect this has more to do with kubernetes configuration rather than the receiver. I would suggest you to put a `sleep 600` in your init container and try sshing into it.
So that you can verify that the java binary exists.

**Comment by rogercoll** [comment]
Agree with @VihasMakwana, the error is descriptive: `"error": "fork/exec /opt/java/java-17-openjdk/bin/java: no such file or directory"`

@saikalyanbhagavathula Could you debug the container and verify that the jar is in the expected path?

**Comment by koolrays** [comment]
Hi there i am having same issue and added a debug container to confirm the java file exists:
`OpenJDK 64-Bit Server VM (build 21.0.8+9-alpine-r0, mixed mode, sharing)
/ # ls -al /opt/java/java-21-openjdk/bin/
total 480
drwxr-xr-x    2 10001    10001        16384 Sep  5 19:49 .
drwxr-xr-x   10 10001    10001          188 Sep  5 19:49 ..
-rwxr-xr-x    1 10001    10001        14184 Sep  5 19:49 jar
-rwxr-xr-x    1 10001    10001        14184 Sep  5 19:49 jarsigner
-rwxr-xr-x    1 10001    10001        14152 Sep  5 19:49 java`

Can you confirm what path the jmxreceiver expects the jar to be in?

**Comment by rogercoll** [comment]
@koolrays `/opt/opentelemetry-java-contrib-jmx-metrics.jar` see receiver's documentation: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.134.0/receiver/jmxreceiver#jar_path-default-optopentelemetry-java-contrib-jmx-metricsjar

**Comment by koolrays** [comment]
Thanks @rogercoll  I have the correct path set in my dockerfile shown below:
```Containerfile
`FROM ubuntu:22.04 AS downloader
RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/open-telemetry/opentelemetry-java-contrib/releases/download/v1.37.0/opentelemetry-jmx-metrics.jar \
    -O /opentelemetry-jmx-metrics.jar

# FROM eclipse-temurin:21 AS jre-build
# # Create a custom Java runtime
# RUN $JAVA_HOME/bin/jlink \
#          --add-modules java.base \
#          --strip-debug \
#          --no-man-pages \
#          --no-header-files \
#          --compress=2 \
#          --output /javaruntime

FROM otel/opentelemetry-collector-contrib:latest
# Set JAVA_HOME and add to PATH
# ENV JAVA_HOME=/opt/java/openjdk
# ENV PATH="${JAVA_HOME}/bin:${PATH}"
# COPY --from=jre-build /javaruntime $JAVA_HOME
COPY --from=downloader /opentelemetry-jmx-metrics.jar /opt/opentelemetry-java-contrib-jmx-metrics.jar
# COPY ./config.yaml /etc/otelcol/config.yaml`
```

and Otel Config:

```yaml
receivers:
     # JMX Metrics receiver
    jmx:
      jar_path: /opt/opentelemetry-java-contrib-jmx-metrics.jar
      endpoint: <jolokia kafka endpoint>:6733
      target_system: jvm
      collection_interval: 30s
      #initial_delay: 1s
      username: <jolokia-endpoint-username>
      # determined by the environment variable value
      password: <jolokia-endpoint-password>
     
      resource_attributes:
        deployment.environment: dev
        #my.other.attr: my.other.value
      log_level: info
```

However I still get the error:

```console
2025-09-08T16:56:33.524Z	error	subprocess/subprocess.go:244	subprocess died	{"resource": {"service.instance.id": "d65a5a08-2eba-43a9-a7a6-b82d897abd4c", "service.name": "otelcol-contrib", "service.version": "0.134.0"}, "otelcol.component.id": "jmx", "otelcol.component.kind": "receiver", "otelcol.signal": "metrics", "error": "fork/exec /opt/java/java-21-openjdk/bin/java: no such file or directory"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess.(*Subprocess).run
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver@v0.134.0/internal/subprocess/subprocess.go:244
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver/internal/subprocess.(*Subprocess).Start.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jmxreceiver@v0.134.0/internal/subprocess/subprocess.go:117
```

I would appreciate it if you can point me to a resource that shows a working/correctly configured  jmx receiver to fetch metrics from a java bean server endpoint(In my case jolokia endpoint exposing kafka metrics). Thank you.
