### ISSUE TITLE
"Duplicate Sample for Timestamp" Error with metricstransformprocessor  and prometheusremotewriteexporter

### ISSUE THREAD

**Issue by mmikitka-arcticwolf** [open-telemetry/opentelemetry-collector-contrib#40808]
### Component(s)

exporter/prometheusremotewrite

## Description
When using the `metricstransformprocessor` Processor to aggregate away labels via `sum` then pushing these metrics to Thanos Receive via the `prometheusremotewriteexporter` Exporter, I see the following errors in the otel-collector pod:

```
2025-06-18T15:53:34.524Z	error	internal/queue_sender.go:56	Exporting failed. Dropping data.	{"error": "Permanent error: Permanent error: Permanent error: remote write returned HTTP status 409 Conflict; err = %!w(<nil>): add 34 samples: duplicate sample for timestamp\n", "dropped_items": 2048}
```

And, the following errors in the Thanos Receive pod
```
ts=2025-06-18T16:44:34.556434615Z caller=writer_errors.go:138 level=warn component=receive component=receive-writer tenant=default-tenant msg="Error on ingesting samples with different value but same timestamp" numDropped=19
```

My unconfirmed suspicion is that `metricstransformprocessor` is copying the timestamp from the source OTel metric, there is no aggregation layer within `prometheusremotewriteexporter`, and it is forwarding the metic payload as-is to Thanos Receive. It's possible that the `intervalprocessor` Processor may reduce the likelihood of this error, but I'm reluctant to adopt an Alpha module.

## Steps to Reproduce
Using the supplied OTel Collector configuration, send the following OTel metrics into the pipeline at the same time, every 30 seconds:
```
testmetric.gauge{hostname="A"}
testmetric.gauge{hostname="B"}
```

## Expected Result
The `prometheusremotewriteexporter` Exporter does not re-use timestamps for the same metric time-series.

## Actual Result
See logs

### Collector version

v0.123.0

## Environment
Kubernetes: Using the `otel/opentelemetry-collector-contrib:0.123.0` container image

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
      http:
        endpoint: ${env:MY_POD_IP}:4318
processors:
  metricstransform:
    transforms:
      - include: ^testmetric\..+
        match_type: regexp
        action: update
        operations:
          - action: aggregate_labels
            label_set: []
            aggregation_type: sum
  batch:
    timeout: 5s
exporters:
  debug:
    verbosity: basic
  prometheusremotewrite:
    endpoint: https://receive.example.com/api/v1/receive
    tls:
      insecure: false
      ca_file: /ca-certs/certificate_chain
    remote_write_queue:
      enabled: true
      num_consumers: 1
    max_batch_request_parallelism: 1
    target_info:
      enabled: true
    external_labels:
      _otel_collector: ${env:MY_POD_NAME}
extensions:
  health_check:
    endpoint: ${env:MY_POD_IP}:13133
service:
  extensions:
    - health_check
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - metricstransform
        - batch
      exporters:
        - debug
        - prometheusremotewrite
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: ${env:MY_POD_IP}
                port: 8888
      level: detailed
```

### Log output

```shell
I see the following errors in the otel-collector pod:


2025-06-18T15:53:34.524Z	error	internal/queue_sender.go:56	Exporting failed. Dropping data.	{"error": "Permanent error: Permanent error: Permanent error: remote write returned HTTP status 409 Conflict; err = %!w(<nil>): add 34 samples: duplicate sample for timestamp\n", "dropped_items": 2048}


And, the following errors in the Thanos Receive pod

ts=2025-06-18T16:44:34.556434615Z caller=writer_errors.go:138 level=warn component=receive component=receive-writer tenant=default-tenant msg="Error on ingesting samples with different value but same timestamp" numDropped=19
```

**Comment by dashpole** [comment]
Can you use the debug exporter to show what OTLP the prometheusremotewrite exporter is receiving from the pipeline?  THE PRW exporter should just be using the timestamps it is given.  Maybe the transform processor isn't doing what you expect?

**Comment by mmikitka-arcticwolf** [comment]
I have not tested with the debug exporter, but that is a good idea. My unconfirmed suspicion is that metricstransformprocessor is copying the timestamp from the source OTel metric, there is no aggregation layer within prometheusremotewriteexporter, and it is forwarding the metic payload as-is to Thanos Receive. It's possible that the intervalprocessor Processor may reduce the likelihood of this error, but I'm reluctant to adopt an Alpha module.

**Comment by mmikitka-arcticwolf** [comment]
@dashpole I took some time to investigate this issue further using the debug exporter with `verbosity: detailed`. My hunch is that multiple metrics with the same labels and millisecond-precision timestamp are being emitted from the OTel Collector prometheusremotewrite exporter, and the Prometheus Remote Write specification uses millisecond-precision timestamps.

> Timestamps MUST be int64 counted as milliseconds since the Unix epoch. Values MUST be float64.

https://prometheus.io/docs/specs/prw/remote_write_spec/

For example, here is some sample data (the timestamps, when truncated to milliseconds would be `2025-10-28 18:05:16.871 +0000 UTC`)
```
StartTimestamp: 2025-10-28 18:04:16.832373576 +0000 UTC
Timestamp: 2025-10-28 18:05:16.871577128 +0000 UTC
Value: 3068
Metric #1
Descriptor:
     -> Name: mymetric.counter.1
     -> Description: mymetric counter
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0

StartTimestamp: 2025-10-28 18:04:16.832379533 +0000 UTC
Timestamp: 2025-10-28 18:05:16.871579064 +0000 UTC
Value: 3497
Metric #0
Descriptor:
     -> Name: mymetric.counter.0
     -> Description: mymetric counter
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
```

Any thoughts on how to aggregate metrics and avoid these millisecond-level timestamp collisions?

**Comment by dashpole** [comment]
The error indicates that you have the same timestamp _for the same metric_ if i'm understanding it correctly.  So your example should have the same metric names.  I would think that your metricstransform processor should aggregate those properly, assuming your regex is selecting the metric.

Otherwise, i'm not sure.  IMO it really a valid use-case to send metrics at a sub-millisecond interval, so I don't think we should propose protocol changes if your theory is correct.

**Comment by mmikitka-arcticwolf** [comment]
@dashpole Adapting the configuration in the description, I used the following in my otel-collector:
```
processors:
  metricstransform:
    transforms:
      - include: ^mymetric\..+
        match_type: regexp
        action: update
        operations:
          - action: aggregate_labels
            label_set: []
            aggregation_type: sum
  batch:
    timeout: 5s
```

And, sending the `mymetric.counter.0` and `mymetric.counter.1` metrics with the same millisecond timestamp resulted in the following error message in Prometheus and Thanos Receive:

```
Error on ingesting samples with different value but same timestamp
```

Can you help me understand a few things about the implementation?

1. Is metricstransform updating the value of the metric in context and keeping everything else in the metric unmodified?
2. Is metricstransform maintaining state for every regexp match, and summing that value with the current metric being processed?

> IMO it really a valid use-case to send metrics at a sub-millisecond interval, so I don't think we should propose protocol changes if your theory is correct.

I agree, and I'm wondering whether there is a way to get metric aggregation with sub-millisecond metrics with the current suite of otel-collector extensions. It seems as though I need some aggregation batching mechanism that uses rolling windows to aggregate metrics and only forwards the aggregated metrics, not the modified source metrics.
