### ISSUE TITLE
Rename multiple metrics using Substitution doesn't work

### ISSUE THREAD

**Issue by hossain-rayhan** [open-telemetry/opentelemetry-collector-contrib#4081]
**Describe the bug**
I am using the `metricstransformprocessor` to rename multiple metrics using `substitution`. I tried to follow the given example in the [README](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor#rename-multiple-metrics-using-substitution). But it didn't work for me.
```yaml
# rename all system.cpu metrics to system.processor.*
include: ^system\.cpu\.(.*)$
match_type: regexp
action: update
new_name: system.processor.$1

```

I have a metric nane `new_container_memory_limit` and I want to rename it to `container_memory_limit`. I was using the following config:
```yaml
- include: ^new_container_(.*)$
  match_type: regexp
  action: update
  new_name: container_$1
```
The metric is being renamed as `container_` (whereas I am expecting `container_memory_limit`)

I am not sure what I am missing here. Any guidance is appreciated.

**What version did you use?**
Latest contrib build, version: v0.29.0-60-g168076c3

**Comment by hossain-rayhan** [comment]
@bogdandrutu @jrcamp any hints?

**Comment by hossain-rayhan** [comment]
**Solution:**
`$` is being treated as a special character. We need to use double dollar sign `$$` instead of a single `$`. 

Following cofig worked for me:
```yaml
- include: ^new_container_(.*)$$
  match_type: regexp
  action: update
  new_name: container_$$1
  ```
