### ISSUE TITLE
Any processor for Deleting span events attributes

### ISSUE THREAD

**Issue by NeerajK23** [open-telemetry/opentelemetry-collector-contrib#40830]
### Component(s)

processor/attributes

### Describe the issue you're reporting

Currently we have otelcol.processor.attributes processor which help to delete the bogus or unwanted attributes either based on key or pattern. But is there any thing that will help to delete event attributes. 
The use case is some application generates random event attributes with say either userid or timestamp.
Example for span events key : span_event_userid1, span_even_userid2 and so on or span_event_timestamp.

For span attributes we can use attributes process like as below:
attributes:
  actions:
    - action: delete
       pattern: 'span_randonattribute.*$'

Is there anything we can do for events or just using for span attributes will also wokr for events attributes?

**Comment by VihasMakwana** [comment]
@NeerajK23 I think you can use [transformprocessor](https://github.com/codeboten/opentelemetry-collector-contrib/tree/main/processor/transformprocessor). Something like:

```yaml
processors:
   transform:
     error_mode: ignore
     trace_statements:
          - delete_key(spanevent.attributes, "k8s.namespace.name")
```

I'll tag codeowners of transformprocessor to confirm this

**Comment by edmocosta** [comment]
Yes, the transform processor can be used for that, and the [delete_matching_keys](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/ottl/ottlfuncs#delete_matching_keys) function should have a similar behavior to what you're looking for:

```yaml
processors:
   transform:
      trace_statements:
          - delete_matching_keys(spanevent.attributes, "span_event_(userid\\d+|timestamp)$")
```

You can test it out [here](https://ottl.run/#eyJ2ZXJzaW9uIjoidjAuMTI4LjAiLCJldmFsdWF0b3IiOiJ0cmFuc2Zvcm1fcHJvY2Vzc29yIiwicGF5bG9hZCI6IntcInJlc291cmNlU3BhbnNcIjpbe1wicmVzb3VyY2VcIjp7fSxcInNjb3BlU3BhbnNcIjpbe1wic2NvcGVcIjp7XCJuYW1lXCI6XCJteS5saWJyYXJ5XCIsXCJ2ZXJzaW9uXCI6XCIxLjAuMFwifSxcInNwYW5zXCI6W3tcInRyYWNlSWRcIjpcIjViOGVmZmY3OTgwMzgxMDNkMjY5YjYzMzgxM2ZjNjBjXCIsXCJzcGFuSWRcIjpcImVlZTE5YjdlYzNjMWIxNzRcIixcInBhcmVudFNwYW5JZFwiOlwiZWVlMTliN2VjM2MxYjE3M1wiLFwibmFtZVwiOlwiSSdtIGEgc2VydmVyIHNwYW5cIixcInN0YXJ0VGltZVVuaXhOYW5vXCI6XCIxNTQ0NzEyNjYwMDAwMDAwMDAwXCIsXCJlbmRUaW1lVW5peE5hbm9cIjpcIjE1NDQ3MTI2NjEwMDAwMDAwMDBcIixcImtpbmRcIjoyLFwic3RhdHVzXCI6e30sXCJldmVudHNcIjpbe1wibmFtZVwiOlwiZm9vXCIsXCJhdHRyaWJ1dGVzXCI6W3tcImtleVwiOlwic3Bhbl9ldmVudF91c2VyaWQxXCIsXCJ2YWx1ZVwiOntcInN0cmluZ1ZhbHVlXCI6XCJ1c2VyaWQxXCJ9fSx7XCJrZXlcIjpcInNwYW5fZXZlbnRfdXNlcmlkMlwiLFwidmFsdWVcIjp7XCJzdHJpbmdWYWx1ZVwiOlwidXNlcmlkMlwifX0se1wia2V5XCI6XCJzcGFuX2V2ZW50X3RpbWVzdGFtcFwiLFwidmFsdWVcIjp7XCJzdHJpbmdWYWx1ZVwiOlwidGltZXN0YW1wXCJ9fSx7XCJrZXlcIjpcImFub3RoZXJcIixcInZhbHVlXCI6e1wic3RyaW5nVmFsdWVcIjpcInRpbWVzdGFtcFwifX1dfV19XX1dfV19IiwiY29uZmlnIjoidHJhY2Vfc3RhdGVtZW50czpcbiAgICAtIGRlbGV0ZV9tYXRjaGluZ19rZXlzKHNwYW5ldmVudC5hdHRyaWJ1dGVzLCBcInNwYW5fZXZlbnRfKHVzZXJpZFxcXFxkK3x0aW1lc3RhbXApJFwiKSJ9).

**Comment by NeerajK23** [comment]
Perfect. Thanks @edmocosta , @VihasMakwana 

I used transform processor something as below and it is working. Is there any difference using with or without "- context:spanevent"
```
processors:
   transform:
     error_mode: ignore
      trace_statements:
        - context: spanevent
           statements:
             - delete_matching_keys(attributes, ".*_timestamps$")
             - delete_matching_keys(attributes, "^somevalue_.*")
```
