### ISSUE TITLE
[connector/datadogconnector] panic when receive terminated signal

### ISSUE THREAD

**Issue by ahkui** [open-telemetry/opentelemetry-collector-contrib#40845]
### Component(s)

connector/datadog

## Description
panic when receive terminated signal

<img width="1678" alt="Image" src="https://github.com/user-attachments/assets/db5547ad-90d3-46ff-96b0-ce62be37a2b5" />

### Collector version

otel/opentelemetry-collector-contrib:0.127.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  debug: {}
  nop: {}
  datadog:
    api:
      key: xxx
      site: xxx
  otelarrow/gateway:
    endpoint: xxx:4319
    tls: { insecure: false }
    arrow: { zstd: { level: 10 } }

extensions:
  health_check:
    endpoint: ${env:MY_POD_IP}:13133
  zpages:
    endpoint: ${env:MY_POD_IP}:55679

processors:
  batch: {}
  batch/datadog:
    # See https://docs.datadoghq.com/opentelemetry/setup/collector_exporter/#batch-processor-configuration
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  k8sattributes: {}
  resource: {}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
        keepalive:
          server_parameters:
            max_connection_age: 1m
            max_connection_age_grace: 10m
      http:
        endpoint: ${env:MY_POD_IP}:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otelcol
          scrape_interval: 10s
          static_configs: [{ targets: ["${env:MY_POD_IP}:8888"] }]

connectors:
  datadog/connector: {}
  failover/logs:
    retry_interval: 10s
    priority_levels:
      - [logs/main]
      - [logs/nop]
  failover/metrics:
    retry_interval: 10s
    priority_levels:
      - [metrics/main]
      - [metrics/nop]
  failover/traces:
    retry_interval: 10s
    priority_levels:
      - [traces/main]
      - [traces/nop]

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: ${env:MY_POD_IP}
                port: 8888
  extensions: [zpages, health_check]
  pipelines:
    # Logs pipelines
    logs:
      receivers: [otlp]
      processors: [memory_limiter, k8sattributes, resource, batch]
      exporters: [failover/logs]
    logs/main:
      receivers: [failover/logs]
      processors: [memory_limiter, batch/datadog]
      exporters: [datadog]
    logs/nop:
      receivers: [failover/logs]
      exporters: [debug, nop]

    # Metrics pipelines
    metrics:
      receivers: [otlp, prometheus, datadog/connector]
      processors: [memory_limiter, k8sattributes, resource, batch]
      exporters: [failover/metrics]
    metrics/main:
      receivers: [failover/metrics]
      processors: [memory_limiter, batch/datadog]
      exporters: [datadog]
    metrics/nop:
      receivers: [failover/metrics]
      exporters: [debug, nop]

    # Traces pipelines
    traces:
      receivers: [otlp]
      processors: [memory_limiter, k8sattributes, resource, batch]
      exporters: [failover/traces, datadog/connector]
    traces/main:
      receivers: [failover/traces]
      processors: [memory_limiter, batch]
      exporters: [otelarrow/gateway]
    traces/nop:
      receivers: [failover/traces]
      exporters: [debug, nop]
```

### Log output

```shell
2025-06-20T19:38:09.956Z    info    otelcol@v0.127.0/collector.go:358    Received signal from OS    {"resource": {}, "signal": "terminated"}
2025-06-20T19:38:09.956Z    info    service@v0.127.0/service.go:331    Starting shutdown...    {"resource": {}}
2025-06-20T19:38:09.956Z    info    healthcheck/handler.go:132    Health Check state change    {"resource": {}, "otelcol.component.id": "health_check", "otelcol.component.kind": "extension", "status": "unavai
lable"}
2025-06-20T19:38:09.959Z    info    inframetadata@v0.27.1/reporter.go:210    Stopped reporter    {"resource": {}, "otelcol.component.id": "datadog", "otelcol.component.kind": "exporter", "otelcol.signal": "me
trics"}
2025-06-20T19:38:09.959Z    info    datadogconnector@v0.127.0/connector_native.go:115    Shutting down datadog connector    {"resource": {}, "otelcol.component.id": "datadog/connector", "otelcol.component.kin
d": "connector", "otelcol.signal": "traces", "otelcol.signal.output": "metrics"}
2025-06-20T19:38:09.959Z    info    datadogconnector@v0.127.0/connector_native.go:116    Stopping obfuscator and concentrator    {"resource": {}, "otelcol.component.id": "datadog/connector", "otelcol.componen
t.kind": "connector", "otelcol.signal": "traces", "otelcol.signal.output": "metrics"}
2025-06-20T19:38:09.959Z    info    datadog@v0.127.0/zaplogger.go:39    Exiting concentrator, computing remaining stats    {"resource": {}, "otelcol.component.id": "datadog", "otelcol.component.kind": "export
er", "otelcol.signal": "metrics"}
panic: send on closed channel

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-collector-contrib/connector/datadogconnector.(*traceToMetricConnectorNative).Shutdown(0xc001149280, {0xc000bb0060?, 0xc000c93320?})
    github.com/open-telemetry/opentelemetry-collector-contrib/connector/datadogconnector@v0.127.0/connector_native.go:120 +0xd2
go.opentelemetry.io/collector/service/internal/graph.(*Graph).ShutdownAll(0xc001937380, {0xd0ebc00, 0x14705440}, {0xd069eb0, 0xc000bb0060})
    go.opentelemetry.io/collector/service@v0.127.0/internal/graph/graph.go:477 +0x1a9
go.opentelemetry.io/collector/service.(*Service).Shutdown(0xc0016d3540, {0xd0ebc00, 0x14705440})
    go.opentelemetry.io/collector/service@v0.127.0/service.go:337 +0xdd
go.opentelemetry.io/collector/otelcol.(*Collector).shutdown(0xc0010626e0, {0xd0ebc00, 0x14705440})
    go.opentelemetry.io/collector/otelcol@v0.127.0/collector.go:388 +0xb8
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc0010626e0, {0xd0ebc00, 0x14705440})
    go.opentelemetry.io/collector/otelcol@v0.127.0/collector.go:374 +0x990
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc0017a0908, {0xbd365c1?, 0x7?, 0xbd2a43a?})
    go.opentelemetry.io/collector/otelcol@v0.127.0/command.go:39 +0x94
github.com/spf13/cobra.(*Command).execute(0xc0017a0908, {0xc0000b2370, 0x1, 0x1})
    github.com/spf13/cobra@v1.9.1/command.go:1015 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0017a0908)
    github.com/spf13/cobra@v1.9.1/command.go:1148 +0x46f
github.com/spf13/cobra.(*Command).Execute(0xc1b6998?)
    github.com/spf13/cobra@v1.9.1/command.go:1071 +0x13
main.runInteractive({0xc1b6998, {{0xbd79765, 0xf}, {0xbe4b467, 0x1f}, {0xbd36408, 0x7}, {}}, 0x0, {{{0x0, ...}, ...}, ...}, ...})
    github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:70 +0x4a
main.run(...)
    github.com/open-telemetry/opentelemetry-collector-releases/contrib/main_others.go:10
main.main()
    github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:63 +0x598
```
