### ISSUE TITLE
[splunkhecreceiver] hec input queue is not blocked if persistence disc is full

### ISSUE THREAD

**Issue by thel1988** [open-telemetry/opentelemetry-collector-contrib#40862]
## Description
It seems that the otel collector is still accepting hec events even though it is not able to either send it to the export or save it to the persistence queue.

Even though block_on_overflow is set to true.

I try to look at the hec health endpoint:
```
curl https://localhost:8088/services/collector/health -k
{"text": "HEC is healthy", "code": 17}
```

## Steps to Reproduce
Make sure the hec backend is not available to test if it can reject hec messages if the disc for the persistent queues is full, so the sender knows if somethings is wrong.

I know it should be controlled be in the event on the disc being full with sizer: requests.

## Expected Result
It should being to reject HEC messages instead of replying ok and the health endpoint should also return an error in the case of the disc being full?

## Actual Result
HEC is just replying OK, if disc is being full

### Collector version

0.128.0

## Environment
Docker: image: "otel/opentelemetry-collector-contrib:latest"
Ubuntu: 22.04

### OpenTelemetry Collector configuration

```yaml
receivers:
  splunk_hec:
    endpoint: "[::]:8088"
    access_token_passthrough: true
extensions:
  file_storage/hec_buffer:
    directory: /data/data 

exporters:
  splunk_hec:
    endpoint: "anotherhost:8088" 
    sending_queue:
      enabled: true
      storage: file_storage/hec_buffer
      block_on_overflow: true
      sizer: requests 
      queue_size: 100000
      num_consumers: 30
    retry_on_failure:
      max_elapsed_time: 48h
      initial_interval: 5s
    token: "x" 
service:
  extensions: [file_storage/hec_buffer]
  pipelines:
    logs: 
      receivers: [splunk_hec]
      processors: [batch]
      exporters: [splunk_hec]
```

### Log output

```shell
Exporting failed. Rejecting data.	{"resource": {"service.instance.id": "894d97b3-560e-4801-96a5-bb3a535ae812", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "splunk_hec", "otelcol.component.kind": "exporter", "otelcol.signal": "logs", "error": "write /data/docker-mount/hec-buffer/{redacted}/exporter_splunk_hec__logs: no space left on device", "rejected_items": 46}
```
