### ISSUE TITLE
[loadbalancingexporter] `Endpoints is deprecated in v1.33+; use discovery.k8s.io/v1 EndpointSlice`

### ISSUE THREAD

**Issue by skandragon** [open-telemetry/opentelemetry-collector-contrib#40871]
### Component(s)

exporter/loadbalancing

## Description

Kubernetes 1.33+ has marked the `corev1.Endpoints` usage as deprecated, and the warning above is spamming us every 4 seconds in a collector running on k8s v1.33

## Steps to Reproduce

Run the load balancer with k8s resolution on k8s 1.33

## Expected Result

No warnings :)

## Actual Result

Warnings.

### Collector version

  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/loadbalancingexporter v0.128.0

## Environment
Kubernets 1.33 in AWS EKS, although a locally installed 1.33 on bare metal also has this warning.

### OpenTelemetry Collector configuration

```yaml
loadbalancing/metrics:
    protocol:
      otlp:
        timeout: 10s
        tls:
          insecure: true
    resolver:
      k8s:
        ports:
          - 14317
        service: ${env:HEADLESS_SERVICE_NAME}.${env:POD_NAMESPACE}
    routing_key: streamID
```

### Log output

```shell

```
