### ISSUE TITLE
New component: execreceiver

### ISSUE THREAD

**Issue by mike9421** [open-telemetry/opentelemetry-collector-contrib#40880]
### The purpose and use-cases of the new component

Execute the script and convert the script's standard output into metrics.

### Example configuration for the component

```
#### configuration level
exec # execreceiver
├── global_interval: 10s  # global execution interval
├── global_timeout: 10s  # global execution timeout
├── global_resource: 1   # global resource information
│   └── env: "online"
├── group_concurrency: 1 # Concurrency for processing script groups, defaults to CPU core count * 10
└── groups 
    └── name: "group1" 
        ├── commands # collection of executed commands
        │   ├── name1: "ls -l"
        │   └── name2: "pwd"
        ├── script_overwrite: false # whether to overwrite existing files, default to true
        ├── scripts # scripts specified in the configuration
        │   └── file1: "ls -l"
        ├── interval: 10s  # execution interval
        ├── timeout: 10s  # execution timeout
        ├── resource       # resource information
        │   └── host: "host1"
        └── relabel_configs 
            └── action: replace
                ├── target_label: region
                └── replacement: us
```

examples
```
exec:
  global_interval: 30s                    
  global_timeout: 15s                    
  global_resource:               
    - host: "web-server-01"
    - environment: "production"
    - datacenter: "dc-east"
  group_concurrency: 2      
  groups:
    # system basic information check
    - name: "system-basic"
      commands:
        system_info: "uname -a"      
        os_version: "cat /etc/os-release" 
        hostname: "hostname"             
        current_user: "whoami"           
        disk_usage: "df -h"              
        process_count: "ps aux | wc -l" 
      script_overwrite: false            
      scripts:
        /opt/scripts/system_monitor.sh: "ls -l" 
        /opt/scripts/disk_analysis.sh: "df -h"  
        /opt/scripts/process_monitor.sh: "ps aux"
      interval: 60s           
      timeout: 10s             
      resource:
        - host: "web-server-01"
        - component: "system"
      relabel_configs:
        - action: replace
          target_label: env
          replacement: production
        - action: replace
          target_label: service
          replacement: system-monitor
 
    # application service check
    - name: "application-health"
      commands:
        app_health: "curl -f http://localhost:8080/health"   
        app_metrics: "curl -f http://localhost:8080/metrics"  
        port_check: "netstat -tlnp | grep :8080"             
        network_test: "ping -c 3 8.8.8.8"                    
        dns_check: "nslookup google.com"                     
        connection_count: "netstat -an | grep ESTABLISHED | wc -l"
      script_overwrite: true             
      scripts:
        /opt/scripts/app_health.sh: "curl -f http://localhost:8080/health"  
        /opt/scripts/network.sh: "netstat -tlnp"                            
      interval: 120s             
      timeout: 15s                    
      resource:
        - host: "web-server-01"
        - component: "application"
      relabel_configs:
        - action: replace
          target_label: env
          replacement: production
        - action: replace
          target_label: service
          replacement: app-monitor
        - action: replace
          target_label: version
          replacement: v1.2.3
```

### Telemetry data types supported

Mainly metrics. Logs and traces might also be added.

### Code Owner(s)
I am interested in implementing this feature.
