### ISSUE TITLE
[ottl] New function `Fail` to abort a list of statements conditionally

### ISSUE THREAD

**Issue by ChristianCiach** [open-telemetry/opentelemetry-collector-contrib#40897]
### Component(s)

pkg/ottl

### Is your feature request related to a problem? Please describe.

I am new to Otelcol, so maybe I am doing something wrong. But I quite often encounter a situation where it doesn't make sense to continue the rest of the ottl statements and I would rather propagate an error. 

### Describe the solution you'd like

I am thinking about something like that:

```yaml
      transform/logs-parse-json:
        log_statements:
          - error_mode: propagate
            statements:
              - merge_maps(log.cache, ParseJSON(log.body), "upsert")
              - set(log.severity_text, log.cache["level"])
              - fail("Missing log level") where log.severity_text == ""
```

**Comment by TylerHelmuth** [comment]
This is a pretty cool idea. Today the way to handle it is some conditions, but a way to break out sooner would be cool.

**Comment by TylerHelmuth** [comment]
This current API would need to rely on `fail` return an error. Depending on the error_mode that could be annoying, but thats probably the best way to do it in a non-breaking way.

**Comment by ChristianCiach** [comment]
Good point. This would only really make sense with `error_mode: propagate`. With `ignore` it would just log the error and continue with the rest of the `statements` block. But I would be okay with that. I had situations in mind where I want to propagate an unexpected situation.

But you are right in that won't give us an option to exit a block of statements early *without* propagating an error to the logs. You either propagate the error (and make it visible to the logs) *or* you are forced to run the rest of the statements (silently or not). I guess there are ways to model around this, for example by using a `silent` block to, for example, parse some json (which can fail), set something like `log.cache["jsonparsed"] = true` and then make the next block of statements conditional on that attribute. 

Still, I think manually failing a block of statements based on a boolean expressions is something that I would like to have. 

I didn't really think this through before creating this issue... 

Edit: Maybe a new `error_mode` like `abort_silently` would be nice, but this would be a separate issue for the transform-processor.

**Comment by ChristianCiach** [comment]
We could probably add a special type of error that aborts the current sequence of statements without it being logged. Something like:

```yaml
      transform/logs-parse-json:
        log_statements:
          - error_mode: propagate
            statements:
              - merge_maps(log.cache, ParseJSON(log.body), "upsert")
              - set(log.severity_text, log.cache["level"])
              - break() where log.severity_text != ""
              - set(log.severity_text, log.cache["log.level"]
              - break() where log.severity_text != ""
```

It happens to me all the time that I *know* that there is no sense in continuing the rest of the statements because I already found the attribute I was looking for and there is no need burning CPU cycles by continuing the rest of the regexps. 

This could also be done by adding the `error_mode: abort_silently` mentioned above if/when we get `fail()`, but then I would have to split my statements into a lot of `log_statements`-elements, making it hard to read.

Of course, I could also do it like this:

```yaml
      transform/logs-parse-json:
        log_statements:
          - statements:
              - merge_maps(log.cache, ParseJSON(log.body), "upsert")
              - set(log.severity_text, log.cache["level"])
              - set(log.severity_text, log.cache["log.level"]) where log.severity_text == ""
              - set(log.severity_text, log.cache["lvl"]) where log.severity_text == ""
```

But the `where` conditions can get out of hand quickly the longer the sequence of statements becomes. I would rather have a way to signal "we are done here!" to the interpreter.

Most other log-collectors also have poor support to express conditions like these. This always makes me think that I must be doing something wrong. Vector seems to be the only tool of its kind that cleanly supports these best-effort parsing situations, due to its VRL syntax.

**Comment by edmocosta** [comment]
I think the `fail` editor is nice idea, but make something like the `break` or any other flow control to work seamless with the transform process and OTTL statements sequence would be a more complex issue, and it definitely would need a broadly discussion.

If your current use-case is selecting the first non empty value, I'm wondering if some `FirstNotEmpty([...])` converter would do the work for now, so you don't need to wait for this proposal to go through.

```yaml
transform/logs-parse-json:
  log_statements:
    statements:
      - merge_maps(log.cache, ParseJSON(log.body), "upsert")
      - set(log.severity_text, FirstNotEmpty([log.cache["level"], log.cache["log.level"], log.cache["lvl"]])
```

**Comment by ChristianCiach** [comment]
> If your current use-case is selecting the first non empty value, I'm wondering if some FirstNotEmpty([...]) converter would do the work for now

Yes, this would reduce a lot of noise from my configurations. There are still some places where I need to match the same attribute against multiple regexps (where I only expect one to actually match), but the same idea could be applied in these cases.

**Comment by ChristianCiach** [comment]
> If your current use-case is selecting the first non empty value, I'm wondering if some FirstNotEmpty([...]) converter would do the work for now

~~I would probably prefer a new `set` function like `setNonEmpty` that works like `set` but is a no-op for `nil` oder `""` values. I will create a separate ticket for that, as this has nothing to do with the proposed `fail`-function here.~~


~~Edit: Or maybe as an overload to `set`:~~

```
set(target, value, Optional[ignoreEmpty])
```

~~Where `ignoreEmpty` is a boolean. If true, `set` ignores `nil` or `""` values.~~

~~I find the distinction between `nil` and `""` in OTTL a bit clunky, as I've already mentioned in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/31387#issuecomment-3008893223 . This is not really an issue with OTTL, but more with the fact that some attributes may be empty (not nil) by default. It would be nice if OTTL could abstract this away by allowing users to write something like `where not log.severity_text`.~~

Edit: Oops! `set` already behaves like I want it to:

> If value resolves to nil, e.g. it references an unset map value, there will be no action.

I don't know how I could miss that, but this helps me remove a ton of `where` conditions from my OTTL statements.

This doesn't guard against `""` values, but this is rarely necessary.

**Comment by edmocosta** [comment]
> Where ignoreEmpty is a boolean. If true, set ignores nil or "" values.

~~The `set` function is already a no-op for `nil` values ([see](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/ottlfuncs/func_set.go#L40)), and given it's very generic, the definition of empty for non-string types is not so trivial (should Go's zeroed values be considered empty?). IMO,  the `where` conditions is currently the more suitable place for checking that. In addition to that, the converter would be more flexible as well, as we could also use it in conditions.~~

Ops, I didn't see your edits before writing this message 😄

**Comment by ChristianCiach** [comment]
I don't think I want this anymore. I probably had some misconceptions about how error-handling works in the transform-processor.

What I wanted to do was something like this:

```yaml
      transform/logs-parse:
        log_statements:
          - error_mode: propagate
            conditions:
              - IsMatch(log.body, "^\\{")  # json?
            statements:
              - merge_maps(log.attributes, ParseJSON(log.body), "upsert")
              - set(log.attributes["log.format"], "json")  # Won't be set if ParseJSON fails due to "propagate"

          - error_mode: ignore
            conditional:
              - log.attributes["log.format"] == "json"
            statements:
              - # do a lot of complex stuff with the parsed json attributes
```

... but not with `ParseJSON` (which *can* fail), but with custom parsing (like `ExtractPatterns`, which cannot normally fail).

But then I saw this part of the documentation:

> **propagate**: The processor returns the error up the pipeline. This will result in the payload being dropped from the collector.

Well, that's not what I want :) I want to skip the rest of the first `log_statements` sequence when json-parsing fails and then proceed with the second sequence of statements. 

Even worse: Looking at the source, it looks like `propagate` may even drop more than just the current log event, [because it exits the whole loop resource-logs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/fab70b831af2303a9eba7a8d52db3792957c30e0/processor/transformprocessor/internal/common/processor.go#L152) (which I assume can contain more than a single log-event). I cannot imagine a situation where I just want to discard logs, so "propagate" is something I would probably never use. This means that the proposed `fail`-function would be useless to me as well.

Instead I am now doing it this way:

```yaml
      transform/logs-parse:
        log_statements:
          - error_mode: silent
            conditions:
              - IsMatch(log.body, "^\\{")  # json?
            statements:
              - set(log.attributes["_JSON"], ParseJSON(log.body))  # may fail
              - set(log.attributes["log.format"], "json") where log.attributes["_JSON"] != nil
           
          - error_mode: ignore
            conditional:
              - log.attributes["log.format"] == "json"
            statements:
              - # do a lot of complex stuff with the parsed json attributes
              - # ...
              - delete_key(log.attributes, "_JSON")
```

I would prefer to use `log.cache` for storing the parsed json attributes, but `log.cache` doesn't survive a sequence of statements, even within the same processor.

This works similarly with `ExtractPatterns`, which (unfortunately?) doesn't raise an error when the Pattern doesn't match, but returns an empty map instead:

```yaml
      transform/logs-parse:
        log_statements:
          - error_mode: silent
            # conditions: []  # There is no good condition for this pattern. Let's just try it...
            statements:
              - set(log.attributes["_MATCHES"], ParsePatterns(log.body, MY_COMPLEX_LOG_PATTERN)  # may return empty map, but won't ever fail
              - set(log.attributes["log.format"], "my-company-log-format") where Len(log.attributes["_MATCHES"]) > 0

          - error_mode: ignore
            conditional:
              - log.attributes["log.format"] == "my-company-log-format"
            statements:
              - # do a lot of complex stuff with the parsed regex groups
              - # ...
              - delete_key(log.attributes, "_MATCHES")
```

^ This is where I was originally planning to use the proposed fail function, like this:

```yaml
          - error_mode: propagate
            # conditions: []  # There is no good condition for this pattern. Let's just try it...
            statements:
              - set(log.cache["_MATCHES"], ParsePatterns(log.body, MY_COMPLEX_LOG_PATTERN)  # may return empty map, but won't ever fail
              - fail("Regex didn't match") where Len(log.attributes["_MATCHES"]) == 0
              - # If the Regex didn't match, continue with the next `statements` sequence below
              - # Continue doing a lot of complex stuff with the parsed regex groups
              - # ...
```

`Len(log.attributes["_MATCHES"]) > 0` seems a bit ugly, but there is no `IsEmpty` function. I could probably compare with `== {}` instead.

So I will close this issue. Not because `fail()` is a fundamentally bad idea, but because there is no way I would ever use it with the way error-handling currently works.

Feel free to re-open if you feel strongly in favour of a `fail`-function.

**Comment by ChristianCiach** [comment]
I guess what I *really* want is an extended `conditions`-block where I can initialize attributes that I can then use in the `conditions` and `statements`-blocks. Maybe something like this, introducing a `prepare` block:

```yaml
        log_statements:
          - error_mode: ignore
            prepare:
              - set(log.cache["_MATCHES"], ParsePatterns(log.body, MY_COMPLEX_LOG_PATTERN))
            conditions:
              - Len(log.cache["_MATCHES"]) > 0
            statements:
              - # do a lot of complex stuff with the parsed regex groups in `log.cache`
```

But I can live with my current solution that uses a "temporary" `log.attributes["_PARSED"]` attribute as an intermediate state between two statement sequences.

Or maybe allow nested statements:

```yaml
        log_statements:
          - error_mode: ignore
            statements:
              - set(log.cache["_MATCHES"], ParsePatterns(log.body, MY_COMPLEX_LOG_PATTERN))
              - error_mode: ignore
                conditions:
                  - Len(log.cache["_MATCHES"]) > 0
                statements:
                  - # do a lot of complex stuff with the parsed regex groups in `log.cache`
```
