### ISSUE TITLE
Receiver : Prometheus : Authorization Password not replaced

### ISSUE THREAD

**Issue by joaolcorreia** [open-telemetry/opentelemetry-collector-contrib#40916]
## Description
When you have a receiver prometheus that requires authentication the password is not being adding to the header `authorization: Basic xxxxxxx`

The xxxxx is replaces the username:<secret>  and shows <secret> instead of replacing the password given in the config file

## Steps to Reproduce

Configure a prometheus receiver with authentication pointing to Pipedream and inspect the headers.
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'warpstream'
          metrics_path: '/api/v1/monitoring/prometheus/virtual_clusters/xxxxxx'
          scheme: https
          basic_auth:
            username: prometheus
            password: "xxxxxxxxx"
          scrape_interval: 60s
          static_configs:
            - targets: ['xxxxx.m.pipedream.net']
              labels:
                service: 'warpstream'
                environment: 'production'
```

## Expected Result
You should see `username:password` base 64 encoded 

## Actual Result
You see `username:<secret>` you see `<secret>` instead of the actual secret.

### Collector version

latest

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```
