### ISSUE TITLE
Node Network Metric unavailable(k8s.node.network.io)

### ISSUE THREAD

**Issue by NithinRusum** [open-telemetry/opentelemetry-collector-contrib#40915]
### Component(s)

receiver/kubeletstats

## Description
I am using kubeletstats receiver for CPU, Memory, Disk and Network metrics of node and pod.
I am unable to see k8s.node.network.io metric.
I am getting the other metrics like CPU, Memory, Disk, also getting the pod network metrics from k8s_pod_network_io_bytes_total

### Collector version

v0.126.0

## Environment
OS: Oracle Linux Server
Version: 8.10
Kubernetes Version: 1.32

### OpenTelemetry Collector configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-config
  namespace: obs
data:
  otel-collector-config.yaml: |
    extensions:
      health_check:
        endpoint: "0.0.0.0:13133"
        path: "/healthz"
        response_body:
          healthy: "I'm good"
          unhealthy: "I'm bad"

    receivers:
      kubeletstats:
        collection_interval: 120s
        auth_type: 'serviceAccount'
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
        extra_metadata_labels:
          - k8s.volume.type
        k8s_api_config:
          auth_type: serviceAccount
        metric_groups:
          - container
          - pod
          - node
          - volume
        
        metrics:
          container.cpu.usage:
            enabled: true
          container.memory.usage:
            enabled: true
          container.memory.working_set:
            enabled: true
          container.filesystem.usage:
            enabled: true
          container.filesystem.available:
            enabled: true
          k8s.node.cpu.usage:
            enabled: true
          k8s.node.memory.available:
            enabled: true
          k8s.node.memory.usage:
            enabled: true
          k8s.pod.cpu.usage:
            enabled: true
          k8s.pod.memory.available:
            enabled: true
          k8s.pod.memory.usage:
            enabled: true
          k8s.node.network.io:
            enabled: true
          k8s.node.network.errors:
            enabled: true
          k8s.volume.available:
            enabled: true
          k8s.volume.capacity:
            enabled: true
          container.uptime:
            enabled: true
          k8s.container.memory_limit_utilization:
            enabled: true
        
        resource_attributes:
          k8s.node.name:
            enabled: true
          k8s.pod.uid:
            enabled: true
          k8s.pod.name:
            enabled: true
          k8s.namespace.name:
            enabled: true
          k8s.container.name:
            enabled: true
          container.id:
            enabled: true
          k8s.volume.name:
            enabled: true
          k8s.volume.type:
            enabled: true
          k8s.persistentvolumeclaim.name:
            enabled: true
          fs.type:
            enabled: true
          partition:
            enabled: true
      
      k8s_cluster:
        allocatable_types_to_report:
        - cpu
        - memory
        - storage
        - ephemeral-storage
        collection_interval: 120s
        node_conditions_to_report:
        - Ready
        - MemoryPressure

      hostmetrics/agent:
        collection_interval: 120s
        scrapers:
          cpu:
            metrics:
              system.cpu.logical.count:
                enabled: true
          memory:
            metrics:
              system.memory.utilization:
                enabled: true
              system.memory.limit:
                enabled: true
          disk:
          filesystem:
            metrics:
              system.filesystem.utilization:
                enabled: true
          network:


    processors:

      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        filter:
          node_from_env_var: "K8S_NODE_NAME"
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.pod.start_time
            - k8s.cluster.uid
          # Pod labels which can be fetched via K8sattributeprocessor
          labels:
            - tag_name: vm_id
              key: Name
              from: node
        # Pod association using resource attributes and connection
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
              - from: resource_attribute
                name: k8s.pod.ip
              - from: connection

      resource/agent:
        attributes:
          - action: upsert
            key: service.namespace
            value: agent
      attributes/agent:
        actions:
          - key: service.namespace
            action: upsert
            value: agent
          - key: service.name
            action: upsert
            value: otel-collector
          - key: tenancy
            action: insert
            value: "qa_tenancy"
          
      resourcedetection/k8snode:
        detectors: [k8snode]
        k8snode:
          node_from_env_var: "K8S_NODE_NAME"
      transform/metric:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["host.name"], resource.attributes["K8S_NODE_NAME"])

    exporters:
      prometheusremotewrite:
        endpoint: http://<NLB IP>:80/api/v1/push
        tls:
          insecure: true
        resource_to_telemetry_conversion:
          enabled: true

    service:
      extensions: [health_check]
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        metrics:
          receivers: [kubeletstats, k8s_cluster, hostmetrics/agent]
          processors: [k8sattributes, attributes/agent, resourcedetection/k8snode, transform/metric]
          exporters: [prometheusremotewrite]
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opentelemetry-collector
  namespace: obs
spec:
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      serviceAccountName: opentelemetry-collector
      containers:
      - name: collector
        image: otel/opentelemetry-collector-contrib:0.104.0
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        args:
        - "--config=/conf/otel-collector-config.yaml"
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_NAMESPACE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8888
        - containerPort: 4317
        - containerPort: 4318
        volumeMounts:
        - name: config
          mountPath: /conf
        - name: varlogpods
          mountPath: /var/log
          readOnly: true
        resources:
          limits:
            cpu: 400m
            memory: 384Mi
          requests:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: config
        configMap:
          name: opentelemetry-collector-config
      - name: varlogpods
        hostPath:
          path: /var/log
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-collector
  namespace: obs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-collector
rules:
# 1. Access Kubernetes events
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "get", "list", "watch" ]

# 2. Read node labels
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "get", "list", "watch" ]

# 3. Edit pod labels
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "list", "watch", "patch" ]

# 4. Access kubelet cadvisor
- apiGroups: [ "" ]
  resources: [ "nodes/proxy" ]
  verbs: [ "get", "list" ]

- apiGroups: [ "" ]
  resources: [ "nodes/metrics", "nodes/stats" ]
  verbs: [ "get" ]

- apiGroups: [ "" ]
  resources: [ "namespaces", "services", "resourcequotas", "replicationcontrollers" ]
  verbs: [ "list", "watch", "get" ]
# Apps API group
- apiGroups: [ "apps" ]
  resources: [ "replicasets", "daemonsets", "statefulsets", "deployments" ]
  verbs: [ "list", "watch", "get" ]
# Batch API group
- apiGroups: [ "batch" ]
  resources: [ "jobs", "cronjobs" ]
  verbs: [ "list", "watch", "get" ]
# Autoscaling API group
- apiGroups: [ "autoscaling" ]
  resources: [ "horizontalpodautoscalers" ]
  verbs: [ "list", "watch", "get" ]

- apiGroups: [ "" ]
  resources: [ "persistentvolumeclaims", "persistentvolumes" ]
  verbs: [ "get", "list", "watch" ]
```

### Log output

```shell

```

### Additional context

I have tried running a debug pod using 
```
kubectl run my-shell --rm -i --tty --image=ubuntu --overrides='{ "apiVersion": "v1", "spec": { "serviceAccountName": "daemonset-opentelemetry-collector", "hostNetwork": true }  }' -- bash
apt update
apt-get install curl jq
export token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) && curl -H "Authorization: Bearer $token" https://$HOSTNAME:10250/stats/summary --insecure
```
Noticed that the network metrics are available.
`"network": { "time": "2025-06-24T06:46:39Z", "name": "", "interfaces": [ { "name": "enp0s10", "rxBytes": 531333467421, "rxErrors": 0, "txBytes": 317500745726, "txErrors": 0 }, { "name": "flannel.1", "rxBytes": 417028354265, "rxErrors": 0, "txBytes": 178258917953, "txErrors": 0 }, { "name": "cni0", "rxBytes": 170124022983, "rxErrors": 0, "txBytes": 460685006684, "txErrors": 0 } ] },`

Just not seeing the k8s.node.network.io
