### ISSUE TITLE
[exporter/awss3exporter]: Timeout errors are not retried

### ISSUE THREAD

**Issue by jsirianni** [open-telemetry/opentelemetry-collector-contrib#40964]
### Component(s)

exporter/awss3exporter

## Description

While testing the S3 exporter's queue and retry configuration, I found that timeout errors do not result in retry.

```json
{
  "level":"error",
  "ts":"2025-06-27T10:32:45.791-0400",
  "caller":"internal/queue_sender.go:57","msg":"Exporting failed. Dropping data.",
  "resource":{"service.instance.id":"0197b199-6e6e-792e-9893-e0c00aba6e66"},
  "otelcol.component.id":"awss3/jsirianni",
  "otelcol.component.kind":"exporter",
  "otelcol.signal":"logs",
  "error":"read upload data failed: context deadline exceeded",
  "dropped_items":500000,
  "stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.128.0/exporterhelper/internal/queue_sender.go:57\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.128.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.128.0/exporterhelper/internal/queuebatch/async_queue.go:47"
}
```

The collector does not continue to log failed requests. If I restart the collector, the failed batch is not present in the persistent sending queue. 

## Steps to Reproduce

I configured retry and sending queue. `retry_max_attempts: 100` to ensure requests retry until they are successful. I fed the pipeline a log batch of 500,000 logs. This will generally result in a timeout to s3, when using a very short timeout such as 1 second.

```yaml
exporters:
    awss3/jsirianni:
        marshaler: otlp_json
        resource_attrs_to_s3:
            s3_prefix: com.awss3.prefix
        s3uploader:
            file_prefix: null
            region: us-east-2
            retry_max_attempts: 100
            retry_max_backoff: 2s
            retry_mode: standard
            s3_bucket: jsirianni-output
            s3_partition_format: year=%Y/month=%m/day=%d/hour=%H/minute=%M
            s3_prefix: drop-logs-test
        sending_queue:
            block_on_overflow: false
            enabled: true
            num_consumers: 10
            queue_size: 200
            storage: file_storage/jsirianni
            wait_for_result: false
        timeout: 1s
extensions:
    file_storage/jsirianni:
        compaction:
            directory: /opt/otel/storage
            on_rebound: true
        directory: /opt/otel/storage
```

## Expected Result

I would expect the following:
1. I should continue to see timeout errors, proving the request is retried up until the max attempts
2. When restarting the collector during the retry logic, I would expect the batch to be persisted in the queue

## Actual Result

Failed requests due to timeout are not retried. The request is not persisted in the queue. The queue appears to function if I keep feeding the exporter.

### Collector version

v0.128.0

## Environment
OS: Fedora
Compiler(if manually compiled): Go 1.24

### OpenTelemetry Collector configuration

```yaml
exporters:
    awss3/jsirianni:
        marshaler: otlp_json
        resource_attrs_to_s3:
            s3_prefix: com.awss3.prefix
        s3uploader:
            file_prefix: null
            region: us-east-2
            retry_max_attempts: 100
            retry_max_backoff: 2s
            retry_mode: standard
            s3_bucket: jsirianni-output
            s3_partition_format: year=%Y/month=%m/day=%d/hour=%H/minute=%M
            s3_prefix: drop-logs-test
        sending_queue:
            block_on_overflow: false
            enabled: true
            num_consumers: 10
            queue_size: 200
            storage: file_storage/jsirianni
            wait_for_result: false
        timeout: 1s
extensions:
    file_storage/jsirianni:
        compaction:
            directory: /opt/otel/storage
            on_rebound: true
        directory: /opt/otel/storage
```

### Log output

```shell
{"level":"error","ts":"2025-06-27T10:32:45.791-0400","caller":"internal/queue_sender.go:57","msg":"Exporting failed. Dropping data.","resource":{"service.instance.id":"0197b199-6e6e-792e-9893-e0c00aba6e66"},"otelcol.component.id":"awss3/jsirianni","otelcol.component.kind":"exporter","otelcol.signal":"logs","error":"read upload data failed: context deadline exceeded","dropped_items":500000,"stacktrace":"go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.128.0/exporterhelper/internal/queue_sender.go:57\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*disabledBatcher[...]).Consume\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.128.0/exporterhelper/internal/queuebatch/disabled_batcher.go:22\ngo.opentelemetry.io/collector/exporter/exporterhelper/internal/queuebatch.(*asyncQueue[...]).Start.func1\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.128.0/exporterhelper/internal/queuebatch/async_queue.go:47"}
{"level":"info","ts":"2025-06-27T10:32:49.691-0400","caller":"filestorage@v0.128.0/client.go:235","msg":"finished compaction","resource":{"service.instance.id":"0197b199-6e6e-792e-9893-e0c00aba6e66"},"otelcol.component.id":"file_storage/jsirianni","otelcol.component.kind":"extension","directory":"/opt/observiq-otel-collector/storage/exporter_awss3_jsirianni_logs","elapsed":0.061465876}
```
