### ISSUE TITLE
[exporter/kafka] all traces send to the same partition when partitioning by trace id is disabled

### ISSUE THREAD

**Issue by leiwingqueen** [open-telemetry/opentelemetry-collector-contrib#40985]
### Component(s)

exporter/kafka

## Description

We send traces to flink with kafka exporter. Since I found all the trace send to the same partition if I don't set the flag partition_traces_by_id on. I expect all the trace sending to the partitions round robin even I don't set the partition_traces_by_id.

## Possible Solution

set the kafka producer to the RandomPartitioner when the flag partition_traces_by_id is false.
generate new uuid as key sending to kafka when the flag partition_traces_by_id is false.

## Steps to Reproduce

set partition_traces_by_id to false

## Expected Result

 I expect all the trace sending to the partitions round robin even I don't set the partition_traces_by_id.

## Actual Result

All traces send to the same partition

### Collector version

v0.124.1

## Environment
OS: CentOS 7 (Kernel 3.10.0-862.el7.x86_64)

### OpenTelemetry Collector configuration

```yaml
exporters:
    debug: {}    
    kafka:
      topic: spans
      brokers:
        - "127.0.0.1:9092"
      traces:
        encoding: otlp_json
  connectors:
  processors:
    batch: {}
    # Default memory limiter configuration for the collector based on k8s resource limits.
    memory_limiter:
      # check_interval is the time between measurements of memory usage.
      check_interval: 5s
      # By default limit_mib is set to 80% of ".Values.resources.limits.memory"
      limit_percentage: 80
      # By default spike_limit_mib is set to 25% of ".Values.resources.limits.memory"
      spike_limit_percentage: 25
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:14250
        thrift_http:
          endpoint: ${env:MY_POD_IP}:14268
        thrift_compact:
          endpoint: ${env:MY_POD_IP}:6831
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
    zipkin:
      endpoint: ${env:MY_POD_IP}:9411
  service:
    pipelines:
      traces:
        exporters:
          - kafka
        processors:
          - probabilistic_sampler
          - memory_limiter
          - batch
        receivers:
          - otlp
          - jaeger
          - zipkin
```

### Log output

```shell

```
