### ISSUE TITLE
[exporter/bmchelix] distinct datapoints are merged into a single metric payload

### ISSUE THREAD

**Issue by NassimBtk** [open-telemetry/opentelemetry-collector-contrib#40991]
### Component(s)

exporter/bmchelix

## Description

The `bmchelix` exporter merged multiple datapoints into the same metric object (`BMCHelixOMMetric`) even though each datapoint had different attributes (e.g., `entityName`, `instanceName`, etc.). This resulted in a single metric with multiple samples that should have been split into distinct metrics per datapoint, each reflecting its own unique entity identity.

## Steps to Reproduce

1. Emit an OpenTelemetry metric (e.g., `nt_services_servicestatus`) with multiple datapoints, each containing distinct attributes such as:

   * `entityName`
   * `instanceName`
   * `id`
2. Observe the resulting payload from the `bmchelix` exporter.

Example output:

```json
[{
  "labels": {
      "entityId": "OTEL:WIN-P03F6KRGOLO:windows_services:SERVICES_SessionEnv",
      "entityName": "SERVICES_SessionEnv",
      "entityTypeId": "windows_services",
      "fqdn": "WIN-P03F6KRGOLO",
      "host.name": "WIN-P03F6KRGOLO",
      "hostType": "server",
      "hostname": "WIN-P03F6KRGOLO",
      "id": "SERVICES_SessionEnv",
      "instanceName": "Remote Desktop Configuration",
  },
  "samples": [
    { "value": 1, "timestamp": 1750928911000 },
    { "value": 0, "timestamp": 1750928911000 },
    ...
  ]
}]
```
> All samples were grouped under the same metric, even though they refer to different Windows services.

## Expected Result

Each datapoint with distinct identifying attributes should result in an independent `BMCHelixOMMetric` object, ensuring correct entity resolution on the BMC Helix side.

```json
[
{
  "labels": {
      "entityId": "OTEL:WIN-P03F6KRGOLO:windows_services:SERVICES_SessionEnv",
      "entityName": "SERVICES_SessionEnv",
      "entityTypeId": "windows_services",
      "fqdn": "WIN-P03F6KRGOLO",
      "host.name": "WIN-P03F6KRGOLO",
      "hostType": "server",
      "hostname": "WIN-P03F6KRGOLO",
      "id": "SERVICES_SessionEnv",
      "instanceName": "Remote Desktop Configuration",
  },
  "samples": [
    { "value": 1, "timestamp": 1750928911000 }
  ]
},
{
  "labels": {
      "entityId": "OTEL:WIN-P03F6KRGOLO:windows_services:SERVICES_Spooler",
      "entityName": "SERVICES_Spooler",
      "entityTypeId": "windows_services",
      "fqdn": "WIN-P03F6KRGOLO",
      "host.name": "WIN-P03F6KRGOLO",
      "hostType": "server",
      "hostname": "WIN-P03F6KRGOLO",
      "id": "SERVICES_Spooler",
      "instanceName": "Print Spooler",
  },
  "samples": [
    { "value": 0, "timestamp": 1750928911000 }
  ]
},
]
```

## Actual Result

Multiple datapoints were incorrectly merged under one metric, causing loss of per-entity distinction and incorrect payload semantics.

### Collector version

0.128.0

## Environment

OS: All (Windows, Unix, etc.)

### OpenTelemetry Collector configuration

```yaml
#═══════════════════════════════════════════════════
# INPUTS
#═══════════════════════════════════════════════════
receivers:
  # OTLP
  # Receives data via gRPC or HTTP using OTLP format. For additional information on the OTLP receiver:
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
  otlp:
    protocols:
      grpc:
        max_recv_msg_size_mib: 100
        endpoint: localhost:4317

#═══════════════════════════════════════════════════
# PROCESSING
#═══════════════════════════════════════════════════
processors:

  transform/hardware_for_helix:

    metric_statements:
    ...
  # memory_limiter
  # Limits the memory usage of the collector. For additional information on the memory limiter:
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor
  memory_limiter:
    check_interval: 5s
    limit_mib: 2000
    spike_limit_mib: 400

  # batch
  # Processes and sends data in batches of 10s. For additional information on the batch processor:
  # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor
  batch:
    timeout: 10s
    send_batch_size: 100
    send_batch_max_size: 100

#═══════════════════════════════════════════════════
# OUTPUT
#═══════════════════════════════════════════════════
exporters:
  bmchelix:
    endpoint: https://sentry2-itom-poc.onbmc.com
    api_key: <api-key>

#═══════════════════════════════════════════════════
# EXTRAS
#═══════════════════════════════════════════════════
extensions:
  # healthcheck
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
  health_check:

#═══════════════════════════════════════════════════
# ACTUAL COLLECTOR PIPELINE DESCRIPTION
#═══════════════════════════════════════════════════
service:
  telemetry:
    logs:
      level: debug
  extensions: [health_check, basicauth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, transform/hardware_for_helix] 
      exporters: [bmchelix]
```

### Log output

```shell

```

### Tip

<sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
