### ISSUE TITLE
Processor to enforce an allowlist schema for redaction and compliance

### ISSUE THREAD

**Issue by leonsp-ai** [open-telemetry/opentelemetry-collector-contrib#4131]
**Is your feature request related to a problem? Please describe.**
We need to be able to redact span attributes or tags based on key names, key values, and value size. Some attributes are sensitive (e.g. `date_of_birth`, `credit_card`) and for legal compliance reasons cannot be allowed in a trace. The best practice for preventing accidental leaks of sensitive values is to explicitly allow known good values rather than banning known bad values.

**Describe the solution you'd like**
A processor that can process spans to delete or mask sensitive values. The actions of the processor should be auditable so developers can debug missing fields.

Example configuration:

```yaml
processors:
  redaction:
    allowed_keys: ["id, "name"]
    blocked_values:
    - "^4[0-9]{12}(?:[0-9]{3})?$" # Visa credit card number
    - "^(5[1-5][0-9]{14})$"       # Mastercard
    summary: debug # vs info or silent
```

Example input:

```yaml
"id":               5
"date_of_birth":    "2021-07-06"
"4111111111111111": "such a nice credit card number"
"5555555555554444": "another sample number"
"name":             "Jane Doe 4111111111111111"
"unknown":          4
```

Example non-production output:

```yaml
"id":                 5
"name":               "Jane Doe ****"
"masked_keys":        "4111111111111111,5555555555554444,date_of_birth,unknown"
"masked_key_count":   4
"masked_values":      "name"
"masked_value_count": 1
```

Example production output:

```yaml
"id":                 5
"name":               "Jane Doe ****"
"masked_key_count":   4
"masked_value_count": 1
```

**Describe alternatives you've considered**
[AttributesProcessor](https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/attributesprocessor) could be enhanced to include these features. Right now its regex support is limited to splitting an existing attribute into multiple attributes or matching a span by one of its values, but it cannot delete all attributes that do not match a list or mask a value that matches a regex. Because this enhancement is not on the roadmap, it is unlikely to be implemented in AttributesProcessor. It also makes more sense to have all redaction or compliance features in one processor.

**Additional context**
There is a request for an attribute allowlist at the opentelemetry specification level here: <https://github.com/open-telemetry/opentelemetry-specification/issues/823>. That request is solving a related technical problem (unbounded schema growth) rather than the more narrow business problem (data compliance).
