### ISSUE TITLE
Sentry Exporter not exporting traces to sentry

### ISSUE THREAD

**Issue by bhwanip** [open-telemetry/opentelemetry-collector-contrib#4141]
**Describe the bug**
I have my services sending tracing using opentellimetry api to the collector (config below), 
Collector works well with zipkin and sends traces there.
But these tracing are not being sent to sentry, we need to use sentry in our organisation.

For my sentry project, we also have sentry environments like dev, staging and prod, but seems exporter has no config to specify the env in collector config file?

**What did you expect to see?**
Expect to see traces appear in sentry, like they are doing in case of zipkin

**What did you see instead?**
Sentry has no traces at all

**What version did you use?**
otel/opentelemetry-collector-contrib-dev:latest

**What config did you use?**

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://host.docker.internal:9411/api/v2/spans"
  logging:
      loglevel: info
  sentry:
    dsn: mydsn
    insecure_skip_verify: true

processors:
  batch:

extensions:
  health_check: {}

service:
  extensions:
       - health_check
  pipelines:
    traces:
      receivers: [otlp]
      processors:
        - batch
      exporters: 
        - sentry
        - logging
```

**Environment**
Apple Mac laptop
