### ISSUE TITLE
[Processor] Add new trace logging processor

### ISSUE THREAD

**Issue by joe-elliott** [open-telemetry/opentelemetry-collector-contrib#4183]
**Is your feature request related to a problem? Please describe.**
We have two needs that that could be addressed by a trace logging processor:
- Correlation of traces and logs
- Debugging a trace pipeline by providing additional data about what is passing through it

**Describe the solution you'd like**
We would like a new processor that logged all traces as they passed through it. The processor would support various formats (logfmt, json), logging modes (roots only, all spans), and configurable span/process attributes to include on the line. Initially the processor can just log to stdout, but as logs approach GA it could also use the logging pipeline directly.

We have done something similar in the [Grafana Agent](https://github.com/grafana/agent/pull/551) and would like to port this to the otel collector minus the Agent specific bits.

**Describe alternatives you've considered**
The [logging exporter](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/loggingexporter/README.md) is similar but requires being the endpoint of a pipeline. We would like a processor that could be placed at different spots in a pipeline for debugging and log/trace correlation.

**Additional context**
If the otel community would accept this processor we would be glad to PR it.

**Comment by djaglowski** [comment]
This is a good use case for connectors ([in development](https://github.com/open-telemetry/opentelemetry-collector/pull/6700)), specifically the `forward` connector. Basically, you can duplicate the traces and send one stream to the logging exporter.

```yaml
receivers:
  otlp:

exporters:
  otlp:
  logging:

connectors:
  forward:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, forward]
    traces/log:
      receivers: [forward]
      exporters: [logging]
```
