### ISSUE TITLE
Add copy operator to internal/stanza used by filelogreceiver

### ISSUE THREAD

**Issue by pmalek-sumo** [open-telemetry/opentelemetry-collector-contrib#4187]
**Is your feature request related to a problem? Please describe.**

`internal/stanza` [imports](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/0170fa4e2506483fa13ace13351028251e7918d8/internal/stanza/register.go#L17-L29) several `opentelemetry-log-collection` operators but not (and that makes sense) but I'm not sure why can't we extend this set to include also [`copy` operator](https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/operators/copy.md)

**Describe the solution you'd like**

Add copy operator to internal/stanza used by filelogreceiver so that it is available

**Describe alternatives you've considered**

* Using `restructure` operator:

  ```
        - type: restructure
          ops:
          - add:
              field: $$attributes["file.name"]
              value: $$attributes["something"]
  ```
  
  which doesn't work 
  
  ```
  Attributes:
       -> file.name: STRING($$attributes["something"])
       -> something: STRING(reg.log)
  ```

* Using `metadata` operator which is not exactly the same as it required to add some logic (unless I don't know a way to write a proper expression which doesn't fail then the key is absent)
  
  ```
        - type: metadata
          id: metadata
          attributes:
            _sourceName: 'EXPR( $$attributes["file.name"] != nil ? $$attributes["file.name"] : "<undefined>" )'
  ```

Both of which have more verbose syntax than plain copy operator:

```
      - type: copy
        from: $$attributes["file.name"]
        to: $$attributes["something"]
```
