### ISSUE TITLE
[metrics_transform_processor] Support extracting a new metric from a label

### ISSUE THREAD

**Issue by maxedmands** [open-telemetry/opentelemetry-collector-contrib#4194]
**Describe the bug**
[The documentation of `metricstransformprocessor` seems to indicate](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor#readme) that it should be possible to extract a timeseries from an existing metric into a new, separately named metric.

For example, if someone is using the `hostmetrics` receiver which produces a `system.memory.usage` metric with a `state` attribute that can be `used`, then it should be possible to use this processor to create a new metric `system.memory.usage.used` that has the same data as the `{state: "used"}` timeseries from `system.memory.usage` -- while also removing the extracted timeseries from the original metric.

**Steps to reproduce**

* Use `hostmetrics` receiver with `memory` scraper enabled.
* Use `metricstransform` processor with the following config:
```yml
    transforms:
      - include: system.memory.usage
        experimental_match_labels: { "state": "used" }
        action: update
        new_name: system.memory.usage.used
```
* Use `otlp` exporter and inspect the resulting metrics OTLP stream (I used [grpc-dump](https://github.com/bradleyjkemp/grpc-tools#grpc-dump) for this)

**What did you expect to see?**

I would have expected `system.memory.usage.used` to be extracted into its own metric, like this:

```json
"metrics": [
  {
    "name": "system.memory.usage.used",
    "description": "Bytes of memory in use.",
    "unit": "By",
    "intGauge": {
      "dataPoints": [
        {
          "timeUnixNano": "1626278141744421000",
          "value": "18703810560"
        }
      ]
    }
  }
  {
    "name": "system.memory.usage",
    "description": "Bytes of memory in use.",
    "unit": "By",
    "intGauge": {
      "dataPoints": [
        {
          "labels": [
            {
              "key": "state",
              "value": "free"
            }
          ],
          "timeUnixNano": "1626278141744421000",
          "value": "5825544192"
        },
        {
          "labels": [
            {
              "key": "state",
              "value": "inactive"
            }
          ],
          "timeUnixNano": "1626278141744421000",
          "value": "9830383616"
        }
      ]
    }
  },
]
```

**What did you see instead?**

The processor seems to be leaving the metric unchanged, and not introducing a new one:

```json
"metrics": [
  {
    "name": "system.memory.usage",
    "description": "Bytes of memory in use.",
    "unit": "By",
    "intGauge": {
      "dataPoints": [
        {
          "labels": [
            {
              "key": "state",
              "value": "used"
            }
          ],
          "timeUnixNano": "1626278141744421000",
          "value": "18703810560"
        },
        {
          "labels": [
            {
              "key": "state",
              "value": "free"
            }
          ],
          "timeUnixNano": "1626278141744421000",
          "value": "5825544192"
        },
        {
          "labels": [
            {
              "key": "state",
              "value": "inactive"
            }
          ],
          "timeUnixNano": "1626278141744421000",
          "value": "9830383616"
        }
      ]
    }
  }
]
```

**What version did you use?**
Compiled from `main` branch on 8641edc22

**What config did you use?**
```yml
receivers:
  hostmetrics:
    collection_interval: 1s
    scrapers:
      memory:

processors:
  metricstransform:
    transforms:
      - include: system.memory.usage
        experimental_match_labels: { "state": "used" }
        action: update
        new_name: system.memory.usage.used

exporters:
  otlp: # details redacted

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [metricstransform]
      exporters: [otlp]
```

**Environment**
OS: MacOS Catalina 10.15.7
Compiler(if manually compiled): go1.16.2

**Workaround**
Using `action: insert` instead of `action: update` here will create the new metric, but (according to the semantics of `insert`) will not remove the timeseries from the original metric. So, it's possible to work around this issue by doing a subsequent `delete_label_value` operation, like this:

```yml
    transforms:
      - include: system.memory.usage
        experimental_match_labels: { "state": "used" }
        action: insert
        new_name: system.memory.usage.used
      - include: system.memory.usage
        action: update
        operations:
          - action: delete_label_value
            label: state
            label_value: used
```

**Comment by zachauten** [comment]
@bogdandrutu  I think i'm running into this as well. I'm trying to rename some of the JVM metrics that are collected by default, so that datadog can pick them up into a dashboard that it creates for JVM metrics sent by the datadog agent.
```
processors:
  metricstransform:
    transforms:
      - include: process.runtime.jvm.memory.usage
        action: update
        match_type: strict
        experimental_match_labels: {"type": "heap"}
        new_name: jvm.heap_memory
```

Collector logs:
```
Metric #9
Descriptor:
     -> Name: process.runtime.jvm.memory.usage_after_last_gc
     -> Description: Measure of memory used after the most recent garbage collection event on this pool
     -> Unit: By
     -> DataType: Sum
     -> IsMonotonic: false
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
Data point attributes:
     -> pool: Str(G1 Survivor Space)
     -> type: Str(heap)
StartTimestamp: 2023-03-01 20:29:16.851929946 +0000 UTC
Timestamp: 2023-03-01 21:03:15.362638953 +0000 UTC
Value: 5242880
NumberDataPoints #1
Data point attributes:
     -> pool: Str(G1 Old Gen)
     -> type: Str(heap)
StartTimestamp: 2023-03-01 20:29:16.851929946 +0000 UTC
Timestamp: 2023-03-01 21:03:15.362638953 +0000 UTC
Value: 15987200
NumberDataPoints #2
Data point attributes:
     -> pool: Str(G1 Eden Space)
     -> type: Str(heap)
StartTimestamp: 2023-03-01 20:29:16.851929946 +0000 UTC
Timestamp: 2023-03-01 21:03:15.362638953 +0000 UTC
Value: 0
```
Apologies if you are not considered a code owner, or if this has been addressed elsewhere!
