### ISSUE TITLE
DoubleValueRecorder with ECS resource labels incorrectly exported to Cloudwatch

### ISSUE THREAD

**Issue by robbie-unlikelyai** [open-telemetry/opentelemetry-collector-contrib#4296]
**Describe the bug**
When a DoubleValueRecorder metric is sent from an application to Cloudwatch through the Collector (using the `awsemf` exporter) with ECS resource labels, the metric does not show up in Cloudwatch Metrics.

**Steps to reproduce**
Run a Java service in ECS, with the Java SDK build in. In that service, setup one DoubleCounter and one DoubleValueRecorder metric as shown below:
```
    var counter =
        meter
            .doubleCounterBuilder("counter1")
            .setDescription("Example counter")
            .setUnit("Count")
            .build();
    counter.add(1);
    var valueRecorder =
        meter
            .doubleValueRecorderBuilder("valuerecorder1")
            .setDescription("Value recorder 1")
            .setUnit("Count")
            .build();
    valueRecorder.record(1);
```

Then, run a collector with the following configuration that takes the metrics in and exports them to Cloudwatch:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch/metrics:
    timeout: 60s
  resourcedetection:
    detectors: [ecs]
  resource:
    attributes:
      - key: ClusterArn
        from_attribute: aws.ecs.cluster.arn
        action: insert
      - key: TaskArn
        from_attribute: aws.ecs.task.arn
        action: insert
      - key: TaskFamily
        from_attribute: aws.ecs.task.family
        action: insert

exporters:
  awsemf:
    namespace: Test
    log_group_name: /aws/ecs/application/metrics/test
    resource_to_telemetry_conversion:
      enabled: true
    dimension_rollup_option: NoDimensionRollup
    metric_declarations:
      dimensions: [[ClusterArn, TaskFamily], [TaskArn]]
      metric_name_selectors: [ . ]

service:
  pipelines:
    metrics/service:
      receivers: [otlp]
      processors: [batch/metrics, resourcedetection, resource]
      exporters: [awsemf]
```

**What did you expect to see?**
In cloudwatch, I expected to see both metrics with `[[ClusterArn, TaskFamily], [TaskArn]]` dimensions.

**What did you see instead?**
The counter metric does appear as expected, but the value recorder does not appear properly in Cloudwatch metrics. When looking at the `/aws/ecs/application/metrics/test` logGroup for valuerecorder entries, it does not have any of the cloudwatch resource labels attached or a `_aws` field - it looks as follows:
```
{
    "OTelLib": "test",
    "valuerecorder1": {
        "Max": 1,
        "Min": 1,
        "Count": 1,
        "Sum": 1
    }
}
```
Conversely, the counter has a `_aws` field and lots of other fields with ECS labels (e.g. `aws.ecs.cluster.arn` and `aws.ecs.task.arn`).

**What version did you use?**
Collector: `0.30.0`
Java SDK: `1.4.1`

**What config did you use?**
Config: See above

**Environment**
Task running in ECS Fargate with Java service and Collector container running in the same task.

**Additional context**
n/a
