### ISSUE TITLE
Add service environment configuration to elastic exporter

### ISSUE THREAD

**Issue by vinsce** [open-telemetry/opentelemetry-collector-contrib#438]
Based on the [Kibana documentation](https://www.elastic.co/guide/en/kibana/current/filters.html#environment-selector), the special field `service.environment` is used to identify the environment of the service. If the variable is not specified, the environment associated with the service is _Not defined_.

![image](https://user-images.githubusercontent.com/5099266/87449258-3b450c00-c5fd-11ea-9a80-f4c08dd138c2.png)

However the `service.environment` variable is not recognized by the elastic exporter, and it is considered a generic label and converted to `labels.service_environment`:
![image](https://user-images.githubusercontent.com/5099266/87450089-62500d80-c5fe-11ea-8b1d-969cda37b056.png)

This is the collector configuration I'm using:
```yaml
receivers:
  otlp:
    endpoint: "localhost:55680"

processors:
    resource/service:
        labels: {
          "service.environment": "test",
          "service.name": "application name"
        }
    batch:
        timeout: 1s
        send_batch_size: 1024

exporters:
    elastic:
        apm_server_url: "http://localhost:8200"

service:
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch, resource/service]
            exporters: [elastic]
```

The `service.name` is correctly propagated to elastic as it is but the `service.environment` is not.
