### ISSUE TITLE
metricstransform processor removing instrumentationLibrary values

### ISSUE THREAD

**Issue by ralphabouhaidar** [open-telemetry/opentelemetry-collector-contrib#4390]
**Describe the bug**
The `metricstransform` processor is being used to add a label on all metrics. The labels are correctly being added on all metrics however, when using it the `instrumentationLibrary` values are removed from the metrics on which we perform this operation.

**Steps to reproduce**
- Use the config provided below 

**What did you expect to see?**
The added label on all metrics,

**What did you see instead?**
The label was indeed added but [the instrumentationLibrary values are being removed.](https://user-images.githubusercontent.com/47003226/127513890-73a5a0c0-e400-4e5d-b579-f944b3730a5a.png)

**What version did you use?**
Version: v0.26.0

**What config did you use?**
Config:
```yaml
receivers:
  otlp: # pushed by clients
    protocols:
      grpc:
        endpoint: :8800

processors:
  metricstransform:
    transforms:
      - include: ^(.*)$ # add the host.name label on all metrics
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: host.name
            new_value: mvr

exporters:
  file:
    path: ./metrics.json

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [metricstransform]
      exporters: [file]
```

**Environment**
OS: Red Hat 7

**Additional context**
The metrics are being generated using the python instrumentation library.
