### ISSUE TITLE
How to map TraceId/SpanId using the Filelog Receiver

### ISSUE THREAD

**Issue by edinardo** [open-telemetry/opentelemetry-collector-contrib#4595]
Based on the [Log and Event Record Definition](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#log-and-event-record-definition)  `TraceId` and `SpanId` are "root" fields like `Timestamp` but I can't find in the documentation how to parse or map it to the respective fields, so they end up inside the `Body`.

Starting from the regex_parse, where the timestamp and severity map to the respective fields...
```
filelog:
  include: [ /var/log/*.log ]
  operators:
    - type: regex_parser
      regex: '^(?P<Instant>.{23})\s+(?P<Level>(\w+)) \[(?P<Thread>(.+)),(?P<TraceId>(\w+)),(?P<SpanId>(\w+))\] (?P<Logger>(.+)) : (?P<Message>.*)'
      timestamp:
        parse_from: Instant
        layout_type: strptime
        layout: '%F %T.%L'
        location: UTC
      severity:
        parse_from: Level
```
... do we have something like this to map the traces?
```
      trace:
        parce_from: TraceId
```

On a side note, it seems possible to move from `Body` to `Attributes` using the `move` operator, but I couldn't find a way to move it to the root level.

A logging entry example to be parsed by the regex_parse is like:
```
2021-08-11 00:17:01.277  INFO [http-nio-8080-exec-1,c45f0a94e4b3a323ab191ab293cbdfeb,7f89f3065a149f98] org.springframework.web.servlet.DispatcherServlet : Completed initialization in 2 ms
```

**Comment by djaglowski** [comment]
@edinardo Thanks for raising this. This functionality actually does exist, but unfortunately it looks like we did not document it well. We'll add documentation soon.

In the meantime, here's an example of how it can be configured: https://github.com/open-telemetry/opentelemetry-log-collection/pull/76#issuecomment-808694646

> On a side note, it seems possible to move from Body to Attributes using the move operator, but I couldn't find a way to move it to the root level.

Can you clarify what you mean by the "root level"? Do you mean to the root of the body? If so, you can do:
```yaml
type: move
from: $$body.some_field
to: $$body
```
