### ISSUE TITLE
[k8sprocessor] Watch pods in a set of namespaces

### ISSUE THREAD

**Issue by gebn** [open-telemetry/opentelemetry-collector-contrib#4623]
**Is your feature request related to a problem? Please describe.**

The processor is currently able to watch pods in a single namespace, on a single node, or across the entire cluster. In multi-tenant clusters, watching every pod is at best inefficient and worst forbidden, while looking at a single node is best-suited for DaemonSet deployments. This means the only option left is to have a processor or collector for each namespace of a multi-namespace application.

**Describe the solution you'd like**

It would be great if instead of a single namespace as is currently the case:

```yaml
k8s_tagger:
  filter:
    namespace: foo
```

A list of namespaces could be passed:

```yaml
k8s_tagger:
  filter:
    namespaces:
    - foo
    - bar
    - baz
```

**Describe alternatives you've considered**

- Run an OTel Collector deployment per namespace, either consolidated in a single namespace, or in the respective namespaces.
- Configure an instance of `k8s_tagger` for each namespace and list them in the pipeline, assuming the correct one will pick up a given pod and all others will ignore it.
- Configure a distinct pipeline for each namespace, each with a `k8s_tagger` instance filtering by that namespace. Each could use a receiver listening on a dedicated port.

**Additional context**

Prometheus's [K8s service discovery](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) is capable of watching multiple namespaces at once:

```yaml
kubernetes_sd_configs:
- namespaces:
    names:
    - foo
    - bar
    - baz
```
