### ISSUE TITLE
filelog receiver can't filter on severity

### ISSUE THREAD

**Issue by overmeulen** [open-telemetry/opentelemetry-collector-contrib#4627]
**Describe the bug**
Filtering log entries on their severity doesn't work

**Steps to reproduce**
Log file:
```
2021-08-13 14:04:17.018  INFO test1
2021-08-13 14:04:17.018  WARN test2
2021-08-13 14:04:17.018  ERROR test3
```
Collector config:
```
receivers:
  filelog:
    include: [ /path/to/dummy/test.log ]
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})  (?P<severity>[A-Z]+) (?P<message>.*)$'
        timestamp:
          parse_from: timestamp
          layout: '%Y-%m-%d %H:%M:%S.%f'
        severity:
          parse_from: severity
      - type: filter
        expr: '$severity != "error"'
```

**What did you expect to see?**
A single log entry being exported

**What did you see instead?**
The collector fails to start with the following exception:

> Error: cannot build pipelines: cannot build receivers: cannot create receiver filelog: failed to compile expression ' != "error"': unexpected token Operator("!=") (1:2)

Seems like "$severity" is considered as an env variable and replace by an empty string upon collector startup
Now even if I workaround this problem by doing the following before starting the collector:

> export severity='$severity'

The filtering still doesn't work and no log entries are exported
I guess this comes from the fact that "severity" is not exposed in expression special variables:
https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/types/expression.md

**What version did you use?**
opentelemetry-collector-contriv v0.31.0

**Comment by atoulme** [comment]
A few changes have happened since this was filed, the dollar notation was dropped and now by default values are stored under attributes. So the proper syntax should now be `attributes.severity`.

**Comment by crobert-1** [comment]
Hello @overmeulen, apologies for the delay, I just tested and this is working as expected.

Your config can be as simple as this for the `operators` section (leaving everything else the same):
```
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3})  (?P<severity>[A-Z]+) (?P<message>.*)$'
      - type: filter
        expr: 'attributes.severity != "ERROR"'
```
I'm going to close as fixed, but please feel free to let us know if you have any other questions!
