### ISSUE TITLE
ResourceDetector should be able to pull information about AutoScalingGroup for AWS resources

### ISSUE THREAD

**Issue by Konig-Corey** [open-telemetry/opentelemetry-collector-contrib#4716]
**Is your feature request related to a problem? Please describe.**
When using the resourcedetection processor I would like to be able to get resource information about the resources auto scaling group

**Describe the solution you'd like**
Have another attribute that can be consumed for aws resources for the resources auto scaling group

**Describe alternatives you've considered**
This attribute could be injected manually but seems fitting that the resourcedetection process would gather this information because it is already pulling information about the host, account, cloud provider etc. Maybe we can provide a way to add any additional attributes that can be found in aws resources metadata. 

**Additional context**
n/a - proposal seems pretty straight forward. 

Please not me know if any additional information needs to be included.

**Comment by alolita** [comment]
@aateeqi can you take a look at this?

**Comment by khanhntd** [comment]
Hey @alolita, will talk with @aateeqi and look at this issue with him.

**Comment by sethAmazon** [comment]
You should be able to get this from the tags.

**Comment by sethAmazon** [comment]
<img width="1226" alt="Screen Shot 2022-01-20 at 12 26 22 PM" src="https://user-images.githubusercontent.com/81644108/150390306-49d73358-5839-4c2b-add6-5f70e18a27ee.png">
What you can do is add the name of the launch template as part of the tags in the launch template

**Comment by sethAmazon** [comment]
<img width="842" alt="Screen Shot 2022-01-20 at 12 29 04 PM" src="https://user-images.githubusercontent.com/81644108/150390756-b6b4f93e-ef98-4c5e-aa82-cb0c30523086.png">

**Comment by sethAmazon** [comment]
@Konig-Corey is this enough of a workaround or do you want this feature to still be added?

**Comment by Konig-Corey** [comment]
Hello, Yes I am sorry I should have closed this ticket. We are using exactly what you suggested above to pull the ASG as it will also be present on an instance that is a member of an ASG. Just for anyone else who sees this item. We were able to accomplish this with the resourcedetection receiver and the following configurations. 

```
  resourcedetection:
    detectors: [env, ec2]
    timeout: 5s
    override: false    
    ec2: 
      tags:  ## list of regex filters to apply additional attributes based of ec2 console tags.
      # refer to resource process for attribute renaming
        - ^aws:autoscaling:groupName$
```

Thank you @sethAmazon
