### ISSUE TITLE
Prometheus staleness markers are generated for metrics that aren't stale.

### ISSUE THREAD

**Issue by a-feld** [open-telemetry/opentelemetry-collector-contrib#4748]
**Describe the bug**

Staleness markers may be incorrectly generated for replicated services (jobs with multiple targets).

_Setup_
* 2 replicated prometheus endpoints (same metric set, except for service_instance_id)
* Example configuration:
```yaml
global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "kubernetes-pods"
    static_configs:
      - targets: ["localhost:8000", "localhost:8001"]
```

**Steps to reproduce**
* Deploy 2 instances of the opentelemetry-collector.
* Configure the prometheus receiver to scrape both instances.
* Configure the logging exporter in deubg mode

Observe metric values with NaN are reported.

**What did you expect to see?**
No NaN values should be reported.

**What did you see instead?**
NaN metric values were reported.

**What version did you use?**
Version: 0.30.1

**What config did you use?**
```yaml
receivers:
  prometheus:
    config:
      global:
        scrape_interval: 5s
        scrape_timeout: 5s
        evaluation_interval: 5s
      scrape_configs:
        - job_name: "kubernetes-pods"
          static_configs:
            - targets: ["localhost:8000", "localhost:8001"]

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [logging]
```

**Environment**
OS: MacOS and hyperkit (docker/k8s)
Compiler(if manually compiled): go1.16

**Additional context**
I believe what could be happening is the labelset / metric names are the same for both replicas, with the exception of **service_instance_id**

* Each pod is scraped independently
* Since the first replica’s service_instance_id label is not observed when the second replica is scraped, I believe this is causing NaNs to be emitted for the first pod’s scrape (to be confirmed?), deleting the state - even though the metrics aren’t actually stale
