### ISSUE TITLE
Loki exporter failed to transform logs into Loki log streams

### ISSUE THREAD

**Issue by edinardo** [open-telemetry/opentelemetry-collector-contrib#4841]
OpenTelemetry Collector Contrib receives logs from `Filelog`, processes them as `Batch`, and exports them to `Logging` + `Loki`.
On the `Logging` exporter everything seems good:
```
2021-08-23T15:39:53.006-0700    DEBUG   loggingexporter/logging_exporter.go:81  ResourceLog #0
InstrumentationLibraryLogs #0
InstrumentationLibrary
LogRecord #0
Timestamp: 2021-08-23 22:39:43.37903868 +0000 UTC
Severity: Undefined
ShortName:
Body: 2021-08-23T15:39:43.289-07:00 INFO [http-nio-8080-exec-2|99b9c22cb69dbf5fba44123362e1096a|229bd369f9fe0f1d] com.gan.shortener.controler.ShortenerController : Created shortened URL
Attributes:
     -> file.name: STRING(shortener.log)
```
But for the `Loki` exporter we have the following error:
```
2021-08-23T15:39:53.006-0700    error   exporterhelper/queued_retry.go:288      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "name": "loki", "error": "Permanent error: failed to transform logs into Loki log streams", "dropped_items": 1}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector@v0.30.0/exporter/exporterhelper/queued_retry.go:288
go.opentelemetry.io/collector/exporter/exporterhelper.(*logsExporterWithObservability).send
        go.opentelemetry.io/collector@v0.30.0/exporter/exporterhelper/logs.go:114
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
        go.opentelemetry.io/collector@v0.30.0/exporter/exporterhelper/queued_retry.go:155
github.com/jaegertracing/jaeger/pkg/queue.ConsumerFunc.Consume
        github.com/jaegertracing/jaeger@v1.24.0/pkg/queue/bounded_queue.go:104
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumersWithFactory.func1
        github.com/jaegertracing/jaeger@v1.24.0/pkg/queue/bounded_queue.go:83
```

A similar simple setting using `promtail` sends the same log without errors.

Collector version: v0.33.0

Configuration:
```
receivers:
  otlp:
    protocols:
      grpc:
  filelog:
    include: [ shortener.log ]
processors:
  batch:
    timeout: 10s
exporters:
  logging:
    logLevel: debug
  jaeger:
    endpoint: "localhost:14250"
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push
    labels:
      attributes:
        severity: ""
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [logging,loki]
```

Environment:
  OS: "Ubuntu 20.04"

Just for extra reference, the log generated by Logback was:
`2021-08-23T15:39:43.289-07:00 INFO [http-nio-8080-exec-2|99b9c22cb69dbf5fba44123362e1096a|229bd369f9fe0f1d] com.gan.shortener.controler.ShortenerController : Created shortened URL`
