### ISSUE TITLE
[attributeprocessor] Support applying an action conditionally on the existence of another attribute

### ISSUE THREAD

**Issue by samanthawalter** [open-telemetry/opentelemetry-collector-contrib#4859]
**Is your feature request related to a problem? Please describe.**
We would like to be able to apply an insert/update/upsert action only if another specified attribute exists.

**Describe the solution you'd like**
Implement this change in the AttrProc whose logic is shared by both the Attribute Processor and Resource Processor.

Add the ability to configure an attribute key which must exist for the action to be applied.

An example configuration would look like
```yaml
processors:
 attributes:
   actions:
     - action: upsert
       key: k8s.cluster.name
       from_attribute: k8s-cluster
       dependent_on_attribute: k8s-pod-name
```
In this case, the attribute k8s.cluster.name will be added with the value from k8s-cluster only if the attribute k8s-pod-name exists.

We have a custom processor that implements this feature which we are willing to contribute.
