### ISSUE TITLE
[attributeprocessor] Support sourcing attribute value from current timestamp

### ISSUE THREAD

**Issue by samanthawalter** [open-telemetry/opentelemetry-collector-contrib#4860]
**Is your feature request related to a problem? Please describe.**
We would like to be able to add an attribute to traces/metrics/logs whose value is the time at which it passed through the collector.

**Describe the solution you'd like**
Implement this change in the AttrProc whose logic is shared by both the Attribute Processor and Resource Processor.

In addition to sourcing the attribute value from `value` or `from_attribute`, add the ability to source the value from the current timestamp with `from_time`. The resulting attribute is an integer attribute in seconds, milliseconds, or nanoseconds (configurable) since the unix epoch.

An example configuration would look like
```yaml
processors:
 attributes:
   actions:
     - action: insert
       key: ingress.time
       from_time: milliseconds
```
In this case, the attribute ingress.time will be inserted as the current timestamp in milliseconds since the unix epoch.

We have a custom processor that implements this feature which we are willing to contribute.
