### ISSUE TITLE
Allow attribute processor to work on resource resource attributes for traces

### ISSUE THREAD

**Issue by kuberkaul** [open-telemetry/opentelemetry-collector-contrib#4962]
While attempting to follow [semantic convention](https://github.com/open-telemetry/opentelemetry-specification/tree/c35c212315223a0a0045d103318ca1bc40704fce/specification) for otel , we are setting multiple resource attribute

`resource.attributes.cloud: true` 

We want to check if this resource attribute is set correctly then add a span attribute :

`span.attribute.retain: true` 

This can then be useful for a tail based sampling processor to drop any traces that dont set the correct resource attribute.

**Describe the solution you'd like**
```
      attribute/check_resource_attr:
        exclude:
          match_type: strict
          resource_attributes: (this would be checking a resource attribute)
            - key: cloud
               value: "true"
       actions:
          - key: retain-span (this would be modifying span attribute)
            action: true
 ```

The main goal here to be able to modify resource attributes or be able to set span attributes based on presence of a resource attribute.
