### ISSUE TITLE
Proposal: Metric Aggregation Processor

### ISSUE THREAD

**Issue by huyan0** [open-telemetry/opentelemetry-collector-contrib#4968]
# Metric Aggregation Processor Proposal

## Objectives

The objective of the metric aggregation processor is to provide OpenTelemetry (OT) Collector users the ability to use exporters to send cumulative metrics to backend systems like Prometheus.

## Background

Currently, the Prometheus exporter for the OT Collector is not functioning as expected. This is because OTLP Exporter in the SDK is pass through, and currently the Collector doesn't have any aggregation functionality, so the Collector receives deltas aggregations and instantaneous metric events and export them directly without converting them to cumulative values([_#1255_](https://github.com/open-telemetry/opentelemetry-collector/issues/1255)). In the Go SDK, aggregation of delta values is performed by the Accumulator and the Integrator(SDK Processor), but there is no similar component in the Collector. Any cumulative exporter that may be implemented in the future will encounter the same problem (a proposed exporter: [#1150](https://github.com/open-telemetry/opentelemetry-collector/issues/1150)). A processor that maintains states of metrics (time series) and applies incoming deltas to cumulative values solves this problem.

## **Requirements**

The processor should convert instantaneous and delta OTLP metrics to cumulative OTLP metrics. The following table proposes a mapping from instantaneous and delta metric kinds to cumulative metric kinds based on OTel-Proto [PR](https://github.com/open-telemetry/opentelemetry-proto/pull/168)[ open-telemetry/opentelemetry-collector#168](https://github.com/open-telemetry/opentelemetry-proto/pull/168).  In the table, red entries are invalid type and kind combinations, white entries correspond to OTLP metrics that are already cumulative(or gauge), and should pass through the processor,  and green entries correspond to OTLP metrics that the processor should aggregate.

![image](https://user-images.githubusercontent.com/15348067/88231601-20e0e300-cc3a-11ea-93cc-3fc03c43f6bd.png)
_*Grouping scalar indicates the most recent value to occur in a collection interval.
**Discussions around [PR open-telemetry/opentelemetry-collector#168](https://github.com/open-telemetry/opentelemetry-proto/pull/168) are still ongoing.This table reflects a current status; will need to be updated when status changes_

For green entries, the processor should maintain the cumulative value as a state. Metric state should be identified by a OTLP metric descriptor and a label set. For each metric of a stateful kind, the processor should aggregate cumulative values for every data point by labels.

## Design Idea

The metric aggregation processor should be similar to the SDK Controller; it should contain:

* Accumulator, which is the entry point of OTLP metric events and manages incremental changes of each metric
* Integrator, which takes checkpoints of the incremental changes from Accumulator and apply them to cumulative values
* Ticker,  which initiates the process of collection and sends metrics to the next metric consumer and
* Custom Aggregators, which maintain the state of metrics; a unique metric is defined by the combination of a metric name, a kind, a type and a label set.

The metric aggregation processor should accept concurrent updates of the metric state by taking in OTLP metrics passed from the pipeline, and perform collection periodically to send cumulative metrics to exporters, acting as a SDK push Controller. The following diagram illustrates the workflow.

![image1](https://user-images.githubusercontent.com/15348067/88231540-0870c880-cc3a-11ea-8afa-8184dfcb4731.png)

cc @alolita @danielbang907 @huyan0 @jmacd

**Comment by pragmaticivan** [comment]
Howdy! @huyan0 Was there any progress towards implementing that proposal?

I'm currently validating a standalone (multiple workloads) Otel collector for `single page apps/client/StatsD`(Metric)  collection but found that was not very clear.

I have taken a look at:
- https://github.com/prometheus/statsd_exporter
- https://github.com/weaveworks/prom-aggregation-gateway

Those projects aims to mitigate that scenario.

**Comment by andyzhangdialpad** [comment]
Thanks for this amazing proposal! @alolita was there any progress on the implementation. We are considering contributing to this. Don't want to reinvent the wheel of course.

**Comment by chenluo1234** [comment]
@huyan0 @alolita @amanbrar1999 @JasonXZLiu Any progress on this issue? 

> I believe that the use cases for this issue have since been solved by changes to the metrics proto, such as the addition of cumulative aggregation temporality. I could be wrong, does anyone know any specific use cases for this processor?

One use case we are having is using statsd receiver and prometheusremotewriteexporter together. Given that statsd receiver produces delta metrics, we will need this processor to convert them into cumulative metrics before handing over to prometheusremotewriteexporter, which only accepts cumulative metrics.

**Comment by danielgblanco** [comment]
Looking through some of the Metrics [Data Model use cases](https://opentelemetry.io/docs/reference/specification/metrics/datamodel/#example-use-cases) in the specification, I understand any mentions of `Collector re-aggregates [e.g. 10s delta temporality exports] into 60 second resolution` would require a processor like the one mentioned in this proposal that can handle state, or a non-OTLP exporter that can aggregate delta sums into cumulative temporality like the `prometheusexporter` does (although support for delta histograms is pending on https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9006). As far I can tell this wouldn't be possible to achieve in a single pipeline with OTLP receiver and exporter.

We (Skyscanner) are currently PoC'ing a solution to generate `http.*.duration` and `rpc.*.duration` metrics from Envoy spans to collect Istio metrics without Mixer (or Prometheus), which we would like to export in OTLP histograms with delta temporality. We use the `spanmetricsprocessor` for this, and to avoid exporting a huge number of data points (as the processor is stateless) we currently use cumulative temporality to a `prometheusexporter` to aggregate histograms and a separate pipeline to scrape that endpoint, use the `cumulativetodeltaprocessor` to turn them into delta histograms, and then export them via OTLP.

Having something like this would make our pipelines much simpler. Is somebody working on this? I've also read there may be plans on the `transformprocessor` to handle aggregations? Any comments/insight would be much appreciated. Thanks!

**Comment by mplachter** [comment]
A little bump for an update here.

Something like this would reduce the complexity of the otel config for using this for cronjobs and lambda functions.
Yes this could be done with the `metricstransform` by aggregating based on a label but it causes some extra implementation on the dev side or more complex otel config.

**Comment by danielgblanco** [comment]
The `transformprocessor` cannot aggregate metrics on consistent intervals in its current form though, as it's stateless. It can only aggregate metrics handled as part of a single batch, not across batches (i.e. exports for different clients).

**Comment by mplachter** [comment]
@alolita @amanbrar1999 @JasonXZLiu any update on this?

**Comment by ishworg** [comment]
bump. folks, is there any guidance and/or timeline on this proposal whether accepted or rejected? It has been more than two years now. kindly advise what operators should expect in the future.

**Comment by AlexeiZenin** [comment]
+1

**Comment by MovieStoreGuy** [comment]
I can't speak for the maintainers, however, I myself see the benefit of a dedicated processor to perform aggregations as a means of reducing complexity of other processors to reimplement  this. I don't think this is strictly related to prom but I see it would greatly benefit from it.

**Comment by rbizos** [comment]
This feature would be highly beneficial to my team as well, we would be happy to give a hand in the implementation

**Comment by kovrus** [comment]
> I can't speak for the maintainers, however, I myself see the benefit of a dedicated processor to perform aggregations as a means of reducing complexity of other processors to reimplement this. I don't think this is strictly related to prom but I see it would greatly benefit from it.

I second that! I would be happy to sponsor it.

**Comment by jpettit** [comment]
+1 <3

**Comment by bitomaxsp** [comment]
@kovrus Hi Ruslan. What does it mean that you are sponsoring? Are you doing all the implemention work? or are you responsible for finding someone who will work on it?

**Comment by kovrus** [comment]
Hi @bitomaxsp, please take a look at the first point of the [Adding new components](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/CONTRIBUTING.md#adding-new-components). It provides a good explanation on sponsorship.

**Comment by MovieStoreGuy** [comment]
Any way that we can help get this started?

It was brought up in the APAC end user group as something that was needed.

**Comment by devurandom** [comment]
Would the proposed solution to this issue allow aggregation of metrics data points in user-defined intervals?

We gather metrics using the OpenTelemetry Java Agent, batch them using the OpenTelemetry Collector and export them to Grafana Cloud. Grafana Cloud plans have a maximum included "data points per minute" (DPM, cf. https://grafana.com/docs/grafana-cloud/billing-and-usage/active-series-and-dpm/#data-points-per-minute-dpm) which we would like to not exceed. If the OpenTelemetry Collector would support aggregating each time series in intervals of 60s that would be a great help.

Related: https://github.com/open-telemetry/opentelemetry-java/issues/5393

**Comment by bitomaxsp** [comment]
These is also a bigger issue when it comes to accumulating intervals from "lambdas". That i think is not covered by OTEL SDK at all iirc. It would be nice to come up with some guides on how to deal with that and include that in that processor as well.

**Comment by yuri-rs** [comment]
I've achieved my goal of Metric Aggregation by chaining several processors in the following order: 
`batch -> groupbyattrs -> transform/TruncateTime -> metricstransform/aggregate_labels`

Although the process might seem extensive, it effectively gets the job done. 
This approach could be useful for anyone tackling a similar challenge.

**Comment by axaxs** [comment]
> I've achieved my goal of Metric Aggregation by chaining several processors in the following order: `batch -> groupbyattrs -> transform/TruncateTime -> metricstransform/aggregate_labels`
> 
> Although the process might seem extensive, it effectively gets the job done. This approach could be useful for anyone tackling a similar challenge.

Any chance you could expand on your settings?  Did you use delta or cumulative counters?  Our use case is multiple short lived processes, all writing same metrics and attributes but with different counts.  Our expectation is to have otel treat these as cumulative, and be able to export to prometheus, but we've hit a bit of a block as others have stated.

**Comment by diranged** [comment]
Agreed - @yuri-rs  would you mind posting your config?

**Comment by yuri-rs** [comment]
> Agreed - @yuri-rs would you mind posting your config?

Sure @diranged @axaxs. I did collector aggregation for delta metrics. 
Example below aggregate connector cunters (Deltas) into 5s buckets (from 1s individual measurements) and aggregate multiple series into one keeping only service.name label:

```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 1s
          static_configs:
            - targets: ['0.0.0.0:8888']

exporters:
  logging:
    verbosity: detailed

processors:
  groupbyattrs:
  batch:
    timeout: 5s
  resource/personal_metrics:
    attributes:
      - action: upsert
        value: "local"
        key: service.name
  transform/count_metric:
    metric_statements:
      - context: resource
        statements:
          - keep_keys(attributes, ["service.name"])
  metricstransform/count_metric:
    transforms:
      - include: "otlp.*"
        match_type: regexp
        action: update
        operations:
          - action: aggregate_labels
            aggregation_type: sum
            label_set: []
  transform/TruncateTime:
    metric_statements:
      - context: datapoint
        statements:
          - set(time, TruncateTime(time, Duration("5s")))

connectors:
  count:
    metrics:
      otlp.collector.metric.count:
    datapoints:
      otlp.collector.metric.data_point.count:

service:
  pipelines:
    metrics/internal:
      receivers: [prometheus]
      processors: [resource/personal_metrics]
      exporters: [count]
    metrics/count:
      receivers: [ count]
      processors: [ transform/count_metric, batch, groupbyattrs, transform/TruncateTime, metricstransform/count_metric ]
      exporters: [ logging ]

  telemetry:
    logs:
      level: debug
```
