### ISSUE TITLE
Jaeger Receiver Should Honor TLS Settings

### ISSUE THREAD

**Issue by keitwb** [open-telemetry/opentelemetry-collector-contrib#5004]
The jaeger receiver accepts `tls_settings` under the thrift http server config but  does not honor it.  It seems to always create a plain HTTP listener per https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/jaegerreceiver/trace_receiver.go#L467.

The config used is like the following:

```yaml
  jaeger/tls:
    protocols:
      grpc:
      thrift_http:
        tls_settings:
          cert_file: /etc/otelotel-sec.crt
          key_file: /etc/otelotel-sec.key
```

Expected behavior is that a TLS-backed HTTP server is created that uses the configured cert.
