### ISSUE TITLE
Jaeger exporter does not generate processes for each peer.service

### ISSUE THREAD

**Issue by dgrozenok** [open-telemetry/opentelemetry-collector-contrib#5005]
**Describe the bug**
JaegerExport does not generate Jaeger processes for separate peer.service attributes. As a result in the Jaeger UI all the spans named from a single service.

**Steps to reproduce**
- Clone the repository https://github.com/dgrozenok/OtlpDemo
- Run `docker-compose up`
- Start the solution
- Navigate to https://localhost:5001/WeatherForecast
- Open Jaeger and see that both Web API and google.com http request are named by the Web API service

**What did you expect to see?**
WEB API and GOOGLE.COM services as captions for the spans similar to how they look like in Zipkin:
![image](https://user-images.githubusercontent.com/22241673/97763424-cb359580-1ac8-11eb-9d89-16dc7f319b7a.png)

**What did you see instead?**
Both services are named by the same main service WEB API:
![image](https://user-images.githubusercontent.com/22241673/97763470-eef8db80-1ac8-11eb-95d8-078fa89b4347.png)

**What version did you use?**
Version: `v0.13.0`

**What config did you use?**
https://github.com/dgrozenok/OtlpDemo/blob/master/otel-collector-config.yaml
```
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin,jaeger,logging]
```
