### ISSUE TITLE
receiver_creator/host with the `port` option is not working as expected

### ISSUE THREAD

**Issue by harnitsignalfx** [open-telemetry/opentelemetry-collector-contrib#5069]
I tried enabling the receiver_creator/host with a "hostport" rule and a port specified. The port doesn't seem to be getting picked up, the logs indicate that Config.port is not specified.

Rule: 
```  
  receiver_creator/host:
    receivers:
      smartagent/apache:
        rule: type == "hostport" && port == 80
        config:
          type: collectd/apache
          url: http://`endpoint`/server-status?auto
```

Logs:
``` 
2021-09-02T17:19:26.624Z	info	receivercreator@v0.33.0/observerhandler.go:87	starting receiver	{"kind": "receiver", "name": "receiver_creator/host", "name": "smartagent/apache", "endpoint": "[::]:80", "endpoint_id": "(host_observer)[::]-80-TCP-13080"}
2021-09-02T17:19:26.630Z	error	receivercreator@v0.33.0/observerhandler.go:136	failed to start receiver	{"kind": "receiver", "name": "receiver_creator/host", "receiver": "smartagent/apache", "error": "Validation error in field 'Config.port': port is a required field (got '0')"}
```

Couple of additional notes:
1. Setting the `is_ipv6 == "true"` in the rule causes the error to go away. However, it seems like a no-op. There are no metrics that get gathered and no logs to indicate that something is awry.

```
rule: type=="hostport" && port == 80 && is_ipv6 == "true"
```

2. The example for receiver_creator for hostport suggest that type == "port" should be used. It should be "hostport" instead.

Version -  {"Version": "v0.33.1", "NumCPU": 4}

Environment: Debian 10

Config.yaml - 

```
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  smartagent:
    bundleDir: ${SPLUNK_BUNDLE_DIR}
    collectd:
      configDir: ${SPLUNK_COLLECTD_DIR}
  zpages:
    endpoint: 0.0.0.0:55679
  host_observer:
receivers:
  fluentforward:
    endpoint: 127.0.0.1:8006
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_binary:
        endpoint: 0.0.0.0:6832
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  sapm:
    endpoint: 0.0.0.0:7276
  zipkin:
    endpoint: 0.0.0.0:9411
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681
  prometheus/internal:
    config:
      scrape_configs:
      - job_name: otel-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - 0.0.0.0:8888
        metric_relabel_configs:
        - source_labels:
          - __name__
          regex: .*grpc_io.*
          action: drop
  signalfx:
    endpoint: 0.0.0.0:9943
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      load:
      paging:
      processes:
  receiver_creator/host:
    receivers:
      smartagent/apache:
        rule: type == "hostport" && port == 80
        config:
          type: collectd/apache
          url: http://`endpoint`/server-status?auto
    watch_observers:
    - host_observer
processors:
  batch:
  memory_limiter:
    ballast_size_mib: ${SPLUNK_BALLAST_SIZE_MIB}
    check_interval: 2s
    limit_mib: ${SPLUNK_MEMORY_LIMIT_MIB}
  resourcedetection:
    detectors:
    - system
    - gce
    - ecs
    - ec2
    - azure
    override: false
  resourcedetection/internal:
    detectors:
    - system
    - gce
    - ecs
    - ec2
    - azure
    override: true
  resource/add_environment:
    attributes:
    - action: insert
      value: production
      key: deployment.environment
exporters:
  logging:
    loglevel: debug
  sapm:
    access_token: ${SPLUNK_ACCESS_TOKEN}
    endpoint: ${SPLUNK_TRACE_URL}
  signalfx:
    access_token: ${SPLUNK_ACCESS_TOKEN}
    api_url: ${SPLUNK_API_URL}
    ingest_url: ${SPLUNK_INGEST_URL}
    correlation:
  splunk_hec:
    token: ${SPLUNK_HEC_TOKEN}
    endpoint: ${SPLUNK_HEC_URL}
    source: otel
    sourcetype: otel
service:
  extensions:
  - health_check
  - zpages
  - host_observer
  pipelines:
    metrics/logging:
      receivers:
      - receiver_creator/host
      processors:
      - resourcedetection
      exporters:
      - logging
    metrics:
      receivers:
      - otlp
      - signalfx
      - hostmetrics
      - receiver_creator/host
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      exporters:
      - signalfx
    metrics/internal:
      receivers:
      - prometheus/internal
      processors:
      - memory_limiter
      - batch
      - resourcedetection/internal
      exporters:
      - signalfx
    traces:
      receivers:
      - jaeger
      - sapm
      - zipkin
      - otlp
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      - resource/add_environment
      exporters:
      - sapm
      - signalfx
    logs:
      receivers:
      - fluentforward
      - otlp
      processors:
      - memory_limiter
      - batch
      - resourcedetection
      - resource/add_environment
      exporters:
      - splunk_hec
```
