### ISSUE TITLE
BodyProcessor: Move fields from Resource to Body

### ISSUE THREAD

**Issue by jwimmersplk** [open-telemetry/opentelemetry-collector-contrib#5072]
**Is your feature request related to a problem? Please describe.**
As a user of the SplunkHecExporter, I want to modify the payload before being sent to this exporter.  I want to move fields from the Resource object into the Body so when they are ingested by Splunk, they are not indexed fields like they are today.  I would prefer to create a kubernetes map that Splunk can extract at search time rather than at index time. 

**Describe the solution you'd like**
```
  resource/splunk:
    body:
    - key: kubernetes.namespace.name
      from_resource: k8s.namespace.name
      action: upsert
```

**Describe alternatives you've considered**
I am currently able to mitigate some of the fields using the filelog receiver operators but this runs before the k8s_tagger processor so I don't have all of the k8s fields I need to build the data object a user would expect.  

Here in the filelog operator, using the fields extracted from the filepath regex, I move them into a kubernetes object
```
  - type: move
    from: $body["namespace"]
    to: "kubernetes.namespace"
```

Then in the processor after k8s_tagger runs, I delete the attributes I don't need to be indexed fields. 
```
resource/remove:
  attributes:
  - key: k8s.namespace.name
    action: delete
```

**Additional context**
Indexed fields are useful but can increase the disk space usage of an index if not used sparingly. Having a processor that would allow the flexibility to move the data around to avoid this would be very helpful in letting a user make a decision to either save on ingestion license or disk space. 

What would be really nice is to be able to grab all fields like k8s.* and move them to the body.  I'm also curious if this should be a request to SplunkHecExporter 
![Screen Shot 2021-09-02 at 3 41 37 PM](https://user-images.githubusercontent.com/86021971/131906199-718b8099-d2a6-44bf-ae6d-6e40f0a6e690.png)

Above is an example of what I would want to see in Splunk
