### ISSUE TITLE
Not able to get resource metrics as labels in prometheus exporter

### ISSUE THREAD

**Issue by ankitnayan** [open-telemetry/opentelemetry-collector-contrib#5075]
**Describe the bug**
Not able to get resource metrics using below config in `prometheus` exporter
```
    resource_to_telemetry_conversion:
      enabled: true
```

**Steps to reproduce**
otel-collector-config.yml looks like
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s
  memory_limiter:
    # Same as --mem-ballast-size-mib CLI argument
    ballast_size_mib: 683
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

extensions:
  health_check: {}
  zpages: {}
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true

service:
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [prometheus]
```
**Current Behaviour**
```
system_cpu_time{cpu="cpu0",state="idle"} 9.76013346e+06
system_cpu_time{cpu="cpu0",state="interrupt"} 0
system_cpu_time{cpu="cpu0",state="nice"} 13.32
system_cpu_time{cpu="cpu0",state="softirq"} 6048.61
system_cpu_time{cpu="cpu0",state="steal"} 13547.32
system_cpu_time{cpu="cpu0",state="system"} 73781.09
system_cpu_time{cpu="cpu0",state="user"} 282649.92
system_cpu_time{cpu="cpu0",state="wait"} 457.76
system_cpu_time{cpu="cpu1",state="idle"} 9.75988229e+06
system_cpu_time{cpu="cpu1",state="interrupt"} 0
system_cpu_time{cpu="cpu1",state="nice"} 4.29
system_cpu_time{cpu="cpu1",state="softirq"} 5887.16
system_cpu_time{cpu="cpu1",state="steal"} 13489.81
system_cpu_time{cpu="cpu1",state="system"} 73566.51
system_cpu_time{cpu="cpu1",state="user"} 282017.25
system_cpu_time{cpu="cpu1",state="wait"} 608.4
```

**What did you expect to see?**
I expected to see resource metrics as labels exported.

**What version did you use?**
Running otel-collector version 0.26.0 and 0.34.0, both seem to have the same problem

**Environment**
OS: darwin19.0, Mac and Linux
