### ISSUE TITLE
`number_of_workers` doesn't work in googlecloudexporter

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/opentelemetry-collector-contrib#5166]
**Describe the bug**
The attributes `number_of_workers` described in [`googlecloudexporter` documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudexporter/README.md) doesn't work.

**Steps to reproduce**
Try running `opentelemetry-collector-contrib` binary with the following config.yaml that is documented as an example:

```
exporters:
  googlecloud:
    project: my-project
    endpoint: test-endpoint
    user_agent: my-collector {{version}}
    use_insecure: true
    timeout: 12s
    number_of_workers: 3

    resource_mappings:
      - source_type: source.resource1
        target_type: target-resource1
        label_mappings:
          - source_key: contrib.opencensus.io/exporter/googlecloud/project_id
            target_key: project_id
            optional: true
          - source_key: source.label1
            target_key: target_label_1

    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 120s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 50

    metric:
      prefix: prefix
      skip_create_descriptor: true
```

**What did you expect to see?**
The collector works without errors.

**What did you see instead?**
The error messages like these.

```
collector_1  | 2021-09-08T03:22:23.579Z info    service/collector.go:303        Starting otelcontribcol...  {"Version": "v0.34.0", "NumCPU": 12}
collector_1  | 2021-09-08T03:22:23.579Z info    service/collector.go:242        Loading configuration...
collector_1  | Error: cannot load configuration: error reading exporters configuration for googlecloud: 1 error(s) decoding:
collector_1  |
collector_1  | * '' has invalid keys: number_of_workers
collector_1  | 2021/09/08 03:22:23 collector server run finished with error: cannot load configuration: error reading exporters configuration for googlecloud: 1 error(s) decoding:
collector_1  |
collector_1  | * '' has invalid keys: number_of_workers
reporting-api-forwarder_collector_1 exited with code 1
```

**What version did you use?**
Version: `v0.34.0`

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: Debian 10.2
Compiler(if manually compiled): go1.16.5

**Additional context**
N/A
