### ISSUE TITLE
Document RBAC rules for the Prometheus Receiver on Kubernetes

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector-contrib#5189]
Prometheus Receiver should document the the required RBAC rules for user pods to be auto discovered and scraped. Currently, the receiver doesn't mention any of the RBAC rules.

It also doesn't mention any annotation requirements such as:

*  prometheus.io/port: int
* prometheus.io/scrape: true

**Comment by rakyll** [comment]
An example RBAC rule:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
  namespace: otel
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collector
subjects:
- kind: ServiceAccount
  name: otel-collector
  namespace: otel
```
