### ISSUE TITLE
[filterprocessor] Resource attributes matching uses logical AND on list of resource attributes

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#5234]
**Describe the bug**
According to [the filter processor documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#filter-processor):

> `resource_attributes`: ResourceAttributes defines a list of possible resource attributes to match metrics against. A match occurs if **any** resource attribute matches at least one expression in this given list. 

But in reality [**all** expressions](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/ff3c324c3eeece2e4a558d86fbe4df87a20666d0/internal/coreinternal/processor/filtermatcher/attributematcher.go#L97-L114) have to be satisfied in order to get the match. This seems to be an unexpected behaviour.

The following configuration, according to the docs, should exclude metrics from **both** containers `app_container_1` and `app_container_2`.
```
processors:
  filter:
    metrics:
      exclude:
        match_type: strict
        resource_attributes:
          - Key: container.name
            Value: app_container_1
          - Key: container.name
            Value: app_container_2
```

But in reality none of them will be excluded because the matching can happen only if both conditions are satisfied which is impossible for the provided sample config.

I believe we should change the conditions matching logic from `AND` to `OR`.

Big thanks to @pmalek-sumo for raising this problem [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4895#issuecomment-918140065)

Not sure who is the owner of the processor, based on the git history I'm pinging @anniefu and @hossain-rayhan. Please let us know if you are ok with the proposed change. I can work on it.

**Comment by hossain-rayhan** [comment]
Hey @dmitryax , thanks for tagging me here. I am the owner of this change. I am not sure if I understand your requirement clearly. I believe you are expecting an option where we can choose include/exclude metrics with logical OR for multiple values for a single key. For that requirement, I think the regex matching is the best option. The approach you mentioned to above (repeating same keys again and again) does not seem ideal to me. Please correct me if I am wrong. 

We can achieve your goal using regex and we have an example in the same [page](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor#filter-metrics-using-resource-attributes) you linked. Let me know if that does not help.

```yaml
processors:
  filter:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - hello_world
          - hello/world
        resource_attributes:
          - Key: container.name
            Value: (app_container_1|app_container_1)

```

**Comment by dmitryax** [comment]
Hey @hossain-rayhan thanks for replying,

> I believe you are expecting an option where we can choose include/exclude metrics with logical OR for multiple values for a single key.

Yes that's what I expect, and that's what is stated in the docs.

I provided not a good example which can be easily replaced with a regex. But I have another specific use case where I want this configuration

```
  filter/logs:
    logs:
      resource_attributes:
        - key: k8s.pod.annotations.splunk.com/exclude
          value: "true"
        - key: k8s.namespace.annotations.splunk.com/exclude
          value: "true"
```

to drop logs with `k8s.pod.annotations.splunk.com/exclude=true` or `k8s.namespace.annotations.splunk.com/exclude=true`And according to the docs it should work, but it doesn't. Regexp won't help here, so I have to create two different processors, which is not ideal.
