### ISSUE TITLE
Invalid "up" metric

### ISSUE THREAD

**Issue by rakyll** [open-telemetry/opentelemetry-collector-contrib#5249]
When I use the prometheus receiver, I often see the following error:

```2021-09-16T06:28:33.422Z	warn	internal/metricsbuilder.go:139	The 'up' metric contains invalid value	{"kind": "receiver", "name": "prometheus", "value": "NaN", "scrape_timestamp": 1631773712738, "target_labels": "map[__name__:up instance:192.168.32.58:8443 job:k8s]"}```

My Prometheus scrape config is:

```
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 60s
              static_configs:
                - targets: ['0.0.0.0:8888']
            - job_name: k8s
              kubernetes_sd_configs:
              - role: pod
 ```

I run public.ecr.aws/w6n7a8r1/prometheus-example which publishes Prometheus metrics at :9090/metrics.
