### ISSUE TITLE
Collector Contrib fails to recognise "insecure" option

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-collector-contrib#5377]
**Describe the bug**
When provided with the following simple configuration, collector-contrib fails to start:

```
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: backend:8080
    insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
```

Error:
```
Error: cannot load configuration: error reading exporters configuration for otlp: 1 error(s) decoding:

* '' has invalid keys: insecure
```

**What version did you use?**
Docker image `otel/opentelemetry-collector-contrib:latest`, version `0.34.0`

Docker image `otel/opentelemetry-collector:latest`, version `0.34.0` works find without any error.

**Comment by iNikem** [comment]
I have just noticed, why latest docker image uses 0.34, when latest version is 0.36? But still, this does not explain the difference between core and contrib collectors

**Comment by mx-psi** [comment]
open-telemetry/opentelemetry-collector#4063 changed the way this setting is specified (it is now under the `tls` section), so probably it explains this

**Comment by bogdandrutu** [comment]
@iNikem see previous comment, that was a breaking change unfortunately.

**Comment by iNikem** [comment]
Does this mean that https://opentelemetry.io/docs/collector/configuration/#exporters and https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md and related docs were left unchanged?

**Comment by iNikem** [comment]
Also, why the difference between core and contrib images?

**Comment by leewoobin789** [comment]
otel collector contib with the version of 0.35.0 does not produce any type of error.
But the newest one 0.36.0 gets me in trouble with the "insecure" property.
is TLS setting not optional anymore?
Thank you in advance!

**otel/opentelemetry-collector-contrib:0.35.0**
```
2021/09/22 12:44:46 collector server run finished with error: cannot load configuration: error reading exporters configuration for otlp: 1 error(s) decoding:

* '' has invalid keys: insecure
```

**Comment by almeidaalex** [comment]
> [open-telemetry/opentelemetry-collector#4063](https://github.com/open-telemetry/opentelemetry-collector/pull/4063) changed the way this setting is specified (it is now under the `tls` section), so probably it explains this

I've changed  my config to:
```
 jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
```
Now it's not complaining about this error
