### ISSUE TITLE
filterprocessor doesn't return an error when an invalid match_type is set in config

### ISSUE THREAD

**Issue by pmalek-sumo** [open-telemetry/opentelemetry-collector-contrib#5382]
**Describe the bug**

filterprocessor doesn't return an error when an invalid match_type is set in config

**Steps to reproduce**

1. Use the following config or similar with invalid config - different than `strict`/`regexp` for logs or different than `strict`/`regexp`/`expr` for metrics:

```yaml
receivers:
    nop:

processors:
    filter/invalid:
        logs:
            include:
                match_type: invalid

exporters:
    nop:

service:
    pipelines:
        logs:
            receivers: [nop]
            processors: [filter/invalid]
            exporters: [nop]
```

**What did you expect to see?**

Collector to fail to start because of invalid config.

**What did you see instead?**

Collector starting successfully 

**What version did you use?**

Version: https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/372e040eb0b9331cb4b2ca370c8777eb820a854c

**What config did you use?**

Config: as in the **Steps to reproduce** section

**Environment**
OS: Mac
Compiler: `go1.17.1`
