### ISSUE TITLE
prometheusexporter has duplicated obsreport stats.

### ISSUE THREAD

**Issue by Frefreak** [open-telemetry/opentelemetry-collector-contrib#5436]
**Describe the bug**
Currently for every one data point, the prometheusexporter's obsreport count 2.

**Steps to reproduce**
1. start collector with prometheusexporter as metric exporter (and logging, for comparison)
2. send one metric message with one data point (e.g. by sending to otlp receiver)

**What did you expect to see?**
With default collector option, `curl -s localhost:8888/metrics  | grep -P "^otelcol_exporter_sent_metric_points"` should return 1 for each exporter.

**What did you see instead?**
It returns 2. For every metric data point the value adds 2.

![image](https://user-images.githubusercontent.com/7122156/134796617-eebbf7a0-171d-4146-a8d8-4b6833c3bc69.png)

**What version did you use?**
Version: 5870e74e2

**What config did you use?**
Config:

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    logLevel: debug
  prometheus:
    endpoint: localhost:8889

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, logging]
```

**Environment**
OS: Archlinux
Compiler(if manually compiled): go1.17.1

**Additional context**
The problem is that `obsrep.StartMetricsOp`/`obsrep.StartMetricsOp` combo is called both in prometheusexporter and in exporthelper (which by default already uses an `obsReporter` to update the stats). However just removing this in prometheusexporter would make the granularity too coarse, which is either all fail or all success for a `pdata.Metric`.
I think one of the better solution is disable that in the exporterhelper side. However currently it seems there's no way to configure that. I already submitted a issue regarding [this](https://github.com/open-telemetry/opentelemetry-collector/issues/4109) to the collector repo. Once that change is accepted, this issue would be trivial to fix.
