### ISSUE TITLE
[Filter Processor] Ability to filter telemetry based on instrumentation library meta data

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector-contrib#5715]
In some scenario where there are multiple telemetry sources producing the data in same format, we may have  allow/block the telemetry from known/unknown sources in order. This helps in saving some processing cycles in the back-ends which don't know  what to do with these metrics from unidentified/unwanted sources or versions of sources

**Describe the solution you'd like**
something like 

```yaml
  filter:
    metrics:
      exclude:
        match_type: regexp
        instrumentation_libraries:
          - name: "opentelemetry.io"
             version < "0.9"
```

Drop or Include the packets depending on the predicate defined in the filter config.

**Comment by TylerHelmuth** [comment]
This is achievable with OTTL in the filterprocessor:

```yaml
processors:
  filter/ottl:
    error_mode: ignore
    traces:
      span:
        - 'instrumentation_scope.name == "opentelemetry.io"'
        - 'instrumentation_scope.version == "0.9"'
    metrics:
      metric:
        - 'instrumentation_scope.name == "opentelemetry.io"'
        - 'instrumentation_scope.version == "0.9"'
    logs:
      log_record:
        - 'instrumentation_scope.name == "opentelemetry.io"'
        - 'instrumentation_scope.version == "0.9"'
```
