### ISSUE TITLE
Sentry Exporter  Distributed  Span Returning Invalid Span ID

### ISSUE THREAD

**Issue by tonnyadhi** [open-telemetry/opentelemetry-collector-contrib#5721]
**Describe the bug**
Probabaly  this related with  #4141 which  has been closed. I try  to build  and use  latest  fix from #4141  by  building  my  own docker  image  from  opentelemetry-collector-contrib  main branch  (dd44390). 
But sentry can not displayed the entire traces  and returning invalid  span id, like in  the  picture  bellow
 
![Cuplikan layar dari 2021-10-13 09-00-35](https://user-images.githubusercontent.com/9076285/137054081-b36f7a3e-406f-4cbd-905c-8169467e4236.png)

Meanwhile  the  same  traces  displayed  correctly  in  jaeger,  also  this  trace  has  been  sent  from  opentelemetry-collector

![Cuplikan layar dari 2021-10-13 09-03-32](https://user-images.githubusercontent.com/9076285/137054239-a5e3a666-3fcc-4437-981c-abe53c4ca74e.png)

**Steps to reproduce**
Build  and  use  docker  image from  main  branch  (dd44390). Here is  my  Dockerfile
```
FROM golang:1.17 AS build

WORKDIR /src
ADD . /src

RUN make otelcontribcol

FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM scratch

ARG USER_UID=10001
USER ${USER_UID}

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /src/bin/otelcontribcol_linux_amd64 /otelcontribcol
ENTRYPOINT ["/otelcontribcol"]
EXPOSE 4317 55680 55679
```
After  that,  this  docker  deployed  into  GKE  with  Opentelemetry  Operator

**What did you expect to see?**
Traces  on  sentry  displayed  correctly  on  Sentry

**What did you see instead?**
Traces  return  invalid  parent  span   id

**What version did you use?**
Version: main  branch  (dd44390)

**What config did you use?**
Here  is  my opentelemetry operator config 
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector-sentry 
  namespace: opentelemetry-collector
spec:
  mode: deployment
  image: ragnalinux/opentelemetry-collector-contrib:latest
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        ballast_size_mib: 720 
        limit_mib: 1500
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      health_check: {}
    exporters:
      logging: {}
      sentry:
        dsn: SENTRY_DSN 
      jaeger:
        endpoint: JAEGER_URL
    service:
      extensions: [health_check]
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [sentry, jaeger, logging]
```

**Environment**
GKE  with  k8s  v1.18
