### ISSUE TITLE
Drop labels of metrics

### ISSUE THREAD

**Issue by xp-1000** [open-telemetry/opentelemetry-collector-contrib#5853]
**Is your feature request related to a problem? Please describe.**
In some cases we could need to drop undesired dimension present at metrics level.

For example the squid prometheus exporter explicitly add a `host` label for the `up` metric (not all others) https://github.com/boynux/squid-exporter/blob/master/collector/metrics.go#L80

```
...
# HELP squid_swap_outs_total The number of objects saved to disk
# TYPE squid_swap_outs_total counter
squid_swap_outs_total 0
# HELP squid_up Was the last query of squid successful?
# TYPE squid_up gauge
squid_up{host="localhost"} 1
```

While the `host` dimension can cause conflict with the `host.name` dimension this can be necessary to delete this dimension. this will make all metrics consistent having same labels.

**Describe the solution you'd like**
the easier would be to have the ability to delete label from a processor. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor seems appropriate for this need.

**Describe alternatives you've considered**

1. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/attributesprocessor supports `delete` action to delete a label but it does not support metrics (only traces and logs).

2. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor supports metric and `delete` action but it only works at resource level (so it will drop global labels but this will not apply to label at metric level).

3. take advantage of specific ability at receiver or exporter level. for example https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter has a `translation_rules` option which can be used to delete a label on metrics. The obvious limitation is that it will be possible to use for everybody.

4. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor works at metric level but it does not have the ability to delete a label (only to delete metric which have a specific label/value).

The only workaround I found is to use `metricstransformprocessor` with `update` operation like this:

```yaml
 metricstransform/squid:
   transforms:
   - action: update
     include: squid_up
     match_type: strict
     operations:
     - action: delete_label_value
       label: host
       label_value: localhost
```

but it does not achieve exactly what I want because:
- we need to know the value of the dimension we want to drop (`localhost` here). ability to delete a dimension, not matter its value, would be useful.
- it does not really drop the dimension, it only empty its value: `{"name":"squid_up","description":"Was the last query of squid successful?","gauge":{"dataPoints":[{"attributes":[{"key":"host","value":{"stringValue":""}}],"timeUnixNano":"1634233278172000000","asDouble":1}]}}]}]}]}`

**Additional context**
I proposed a new action on the existing `metricstransformprocessor` processor but I suppose it can be a new exporter (or another existing one).

**Comment by dmitryax** [comment]
Hi @xp-1000. 

You cannot just drop an attribute from a metric because it may result into invalid metric with duplicate data points. You need an aggregation instead. `metricstransform` processor provides a way to aggregate data points into predefined set of attributes and dropping attributes that are not defined.

For example, the following config will drop all attributes other than `label1` and `label2`:
```
      - include: my_metric
        action: update
        match_type: strict
        operations:
          - action: aggregate_labels
            label_set: [label1, label2]
            aggregation_type: avg
```

Do you want similar behavior but with ability to define attributes that should be dropped instead, similar to `without` clause in [prometheus aggregation](https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators), right?
