### ISSUE TITLE
Elasticsearchexporter: dynamic index

### ISSUE THREAD

**Issue by leewoobin789** [open-telemetry/opentelemetry-collector-contrib#5854]
**Is your feature request related to a problem? Please describe.**
For future usecase:
According to the existing readme of Elasticsearchexporter, which is inactivated in the current collector version , there seems to be no dynamic index capability e.g. overwriting index name with prefix and namespace etc.
This feature would make another integration component like logstash obsolete and simplifies the overall architecture.

**Describe the solution you'd like**
 Optional configuration: overwriting index name with predefined prefix and value of a ecs field name like elasticsearch plugin in fluentd.

**Describe alternatives you've considered**
None

**Additional context**
- configuration extension on elasticsearch exporter

**Comment by wajika** [comment]
index: should support ILM or template...

**Comment by leewoobin789** [comment]
@djaglowski i will be working on it. just telling to avoid any redundant effort.

**Comment by leewoobin789** [comment]
Idea:
```yaml
elasticsearch/log:
    endpoints: [http://localhost:9200]
    logs_index: myLogIndex
    logs_dynamic_index:
        disabled: false #default: true
        prefix: "staticPrefix-" # both static or attribute/resource based prefix (if one of prefix & suffix does not match, then fall back to logs_index"
        suffix: "-{resource['k8s.namespace']}" # both static or attribute/resource based suffix (if one of prefix & suffix does not match, then fall back to logs_index"
```
ex) staticPrefix-myLogIndex-someNamespace
there will be no breaking changes as it is addition of optional setting.
What do you think folks? :) @djaglowski @JaredTan95
