### ISSUE TITLE
[kafkareceiver] failed to unmarshal messages from kafka/Azure event hub 

### ISSUE THREAD

**Issue by rushirg** [open-telemetry/opentelemetry-collector-contrib#5908]
**Describe the bug**
I've created two traces pipelines (traces, traces/2). In "traces" pipeline, I've configured to receive the traces from otlpreceiver and exported to Azure Event Hub (kafka surface enabled) using kafkexporter, and in "traces/2" pipeline I am trying to receive the same traces from the same Azure Event Hub using kafkareceiver and then logging to stdout. 
However I am hitting an error where kafkareceiver continuously throwing error messages **"failed to unmarshal message"**

**Steps to reproduce**

- create a new config.yaml file from the below Config
- run the collector (v0.37.1) 
   .\otelcontribcol_windows_amd64.exe --config config.yaml

**What did you expect to see?**
No error message

**What did you see instead?**
```
2021-MM-DDTHH:MM:SS.MSZ        info    kafkareceiver@v0.37.1/kafka_receiver.go:363     Starting consumer group {"kind": "receiver", "name": "kafka", "partition": 0}
2021-MM-DDTHH:MM:SS.MSZ        error   kafkareceiver@v0.37.1/kafka_receiver.go:380     failed to unmarshal message             {"kind": "receiver", "name": "kafka", "error": "proto: illegal wireType 6"}
github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver.(*tracesConsumerGroupHandler).ConsumeClaim
        github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver@v0.37.1/kafka_receiver.go:380
github.com/Shopify/sarama.(*consumerGroupSession).consume
        github.com/Shopify/sarama@v1.30.0/consumer_group.go:734
github.com/Shopify/sarama.newConsumerGroupSession.func2
        github.com/Shopify/sarama@v1.30.0/consumer_group.go:659
```

**What version did you use?**
Version: 
otelcontribcol version v0.37.1

**What config did you use?**
Config:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
  kafka:
    brokers: "<Azure-Event-Hub-Namespace>.servicebus.windows.net:9093"
    topic: "otlp_spans"
    auth:
      plain_text: 
        username: "$$ConnectionString"
        password: "<ConnectionStringKey>"
      tls:
        insecure: true

processors:
  batch:

exporters:
  kafka:
    brokers: "<Azure-Event-Hub-Namespace>.servicebus.windows.net:9093"
    topic: "otlp_spans"
    auth:
      plain_text: 
        username: "$$ConnectionString"
        password: "<ConnectionStringKey>"
      tls:
        insecure: true
  logging:
    loglevel: debug
  
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]
    traces/2:
      receivers: [kafka]
      processors: [batch]
      exporters: [logging]
```

**Environment**
OS:
 Windows

**Additional context**
- Kafka endpoints and topics for both the receiver and exporter are same (i.e. same Azure Event Hub Namespace)
- pipeline to log the traces is working

```
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging]
```
