### ISSUE TITLE
[Prometheus Receiver] Add test to validate metrics renaming as per configuration

### ISSUE THREAD

**Issue by PaurushGarg** [open-telemetry/opentelemetry-collector-contrib#6090]
**Is your feature request related to a problem? Please describe.**
In order to verify that the Prometheus receiver is functioning as expected, a new test is needed to verify that Prometheus receiver renames the metric as per `metric_relabel_configs` configuration  provided in `scrap_configs` of Prometheus Receiver configuration in OTEL collector configuration yaml file.
Create testcases for:  

- [ ] Metrics renaming using `relabel.Action` for replace, drop, and keep.
- [ ] Labels renaming using `relabel.Action` replace, drop, keep, and hashmod.

**Describe the solution you'd like**
Prometheus Receiver should rename the metric and labels as per `metric_relabel_configs` configuration. 
Create testdata for Prometheus Receiver to scrape and provide renaming configuration for each `relabel.Action` in Promethues Receiver configuration . For example: 
```
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: rename
        scrape_interval: 5s
        static_configs:
         - targets: [ "localhost: 4567" ]
        metric_relabel_configs:
        # rename otelcol_process_cpu_seconds to process_cpu_seconds by replacing the __name__ label 
          - source_labels: [ __name__ ]
            regex: "otelcol_(.*)"
            action: replace
            target_label:  __name__
            replacement: "$1"
```
**Expected Behavior:** 
Prometheus Receiver renames the metrics as per the given configuration. To validate, assert that the metric name has been renamed. In addition, similar to [metric_receiver_test.go](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/9ceb2fff514995a5b85e89447b02095d3f0c6302/receiver/prometheusreceiver/metrics_receiver_test.go#L1295) validate the scrapes to ensure correct OTLP data transformation. 

**Additional context**
Related to https://github.com/open-telemetry/wg-prometheus/issues/57

Related Open Issues:
#5001 
cc: @alolita @Aneurysm9
