### ISSUE TITLE
Could not use enable the sentry exporter

### ISSUE THREAD

**Issue by yeqown** [open-telemetry/opentelemetry-collector-contrib#6218]
**Describe the bug**

```sh
Error: cannot load configuration: unknown exporters type "sentry" for sentry
2021/11/09 11:19:40 collector server run finished with error: cannot load configuration: unknown exporters type "sentry" for sentry
```

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
collector startup

**What did you see instead?**
collector failed to startup

**What version did you use?**
Version: `otel/opentelemetry-collector:0.38.0`

**What config did you use?**
Config: 

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
  memory_limiter:
    # Same as --mem-ballast-size-mib CLI argument
    ballast_size_mib: 683
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
extensions:
  zpages: {}
exporters:
  otlp:
    endpoint: "otel-collector.default:4317" # Replace with a real endpoint.
    insecure: true
  sentry:
    dsn: mydsn
    insecure_skip_verify: true
service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [sentry]
```

**Environment**
```sh
Darwin yeqown.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```

**Additional context**
