### ISSUE TITLE
[kafkareceiver] commit unprocessed messages

### ISSUE THREAD

**Issue by arnitolog** [open-telemetry/opentelemetry-collector-contrib#6222]
**Describe the bug**
it looks like Kafkareceiver commits even un-processed (or processed with error) messages.

**Steps to reproduce**
configure kafkareciver with the below config:
```
  receivers:
    kafka:
      protocol_version: 2.8.0
      brokers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9093
      topic: jaeger-spans
      encoding: jaeger_proto
      group_id: otel-collector
      client_id: otel-collector
      auth:
        tls:
          ca_file: /tmp/certificates/ca.crt
          insecure: true
      autocommit:
        enable: false
      message_marking: 
        after: true
        on_error: false
  exporters:
    otlp:
      endpoint: some-fake-endpoint.svc.cluster.local:9999
      tls:
        insecure: true
  service:
    extensions:
      - health_check
    pipelines:
      traces:
        receivers: [kafka]
        exporters: [otlp]
```
Push traces into jaeger-spans topic and check LAG for otel-collector consumer group.

**What did you expect to see?**
LAG should constantly grow as we can't complete the pipeline due to the exporters endpoint is unavailable/not reachable 

**What did you see instead?**
LAG is going up and down, which means that offsets are committed back

**What version did you use?**
Version: 
opentelemetry collector 0.38.0

**Additional context**
queue and LAG:
![image](https://user-images.githubusercontent.com/34036079/141102049-9e9690bf-4f34-4cea-b089-3f7a6a923234.png)

spans accepted rate:
![image](https://user-images.githubusercontent.com/34036079/141102541-a4a4ac17-92e4-4dca-92aa-6e89eb1a9e2d.png)

exporter sent rate:
![image](https://user-images.githubusercontent.com/34036079/141102764-f6be4841-0d44-42ca-b8fb-ab4db3b42042.png)
