### ISSUE TITLE
How do we use Metrics Transform Processor?

### ISSUE THREAD

**Issue by tomkerkhove** [open-telemetry/opentelemetry-collector-contrib#6224]
Being new to processors, I was wondering how I can use the "Metrics Transform Processor" in the OTLP collector?

**Comment by bertysentry** [comment]
In your config yaml file, you simply specify the transforms, like in the example below:

```yaml
receivers:
  # [...]

processors:
  metricstransform/1:
    transforms:
      # Transform otelcol_some_metric to otel.some.metric
      - include: ^otelcol_([^_]+)_(.*)$$
        match_type: regexp
        action: update
        new_name: otel.$${1}.$${2}

      # Transform my_metric to my.metric
      - include: ^([^_\.]+)_(.*)$$
        match_type: regexp
        action: update
        new_name: $${1}.$${2}

exporters:
  # [...]

service:
  extensions: # your extensions
  pipelines:
    metrics:
      receivers: # your receivers
      processors: [memory_limiter,batch,metricstransform/1] # <-- metricstransform
      exporters: # your exporters
```

[More details about possible metric transforms are documented here](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor).
