### ISSUE TITLE
datadogexporter : TLS and mTLS settings

### ISSUE THREAD

**Issue by Prabakaranmkd** [open-telemetry/opentelemetry-collector-contrib#6235]
**Describe the bug**
TLS and mTLS settings are not available for datadogexporter 

is there any option like insecure_skip_verify: false

**Comment by mx-psi** [comment]
Hey @Prabakaranmkd, thanks for reporting this. While we don't have the `insecure_skip_verify` option, you can modify the endpoints to use http like so:

```yaml
exporters:    
  datadog:
    api:
      key: ${DD_API_KEY}
    metrics:
      endpoint: http://api.datadoghq.com
    traces:
      endpoint: http://trace.agent.datadoghq.com

# rest of your collector config goes here
```

Could you try this out and see if it works?
