### ISSUE TITLE
Failed to create containerd task: Exec: "/otelcontribcol": permission denied: unknown - when running the container as non root 

### ISSUE THREAD

**Issue by arundathi-nirmata** [open-telemetry/opentelemetry-collector-contrib#6238]
We are running otel-collector deployment on cluster v1.21.1  with nonroot specific security context.

Facing issue of runContainerError and eventually pod goes to CrashLoopBackOff with the below error

`Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/otelcontribcol": permission denied: unknown`

Below is the deployment I am using 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-agent
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-agent
    spec:
      containers:
      - name: otel-agent
        image: otel/opentelemetry-collector-contrib:0.37.1
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
        livenessProbe:
          exec:
            command:
            - cat
            - /etc/otel/config.yaml
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/otel/config.yaml
        volumeMounts:
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/otel/config.yaml
          name: data
          subPath: config.yaml
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: data
        configMap:
          name: otel-agent-config
```
