### ISSUE TITLE
collectd receiver – "The start time must be before the end time"

### ISSUE THREAD

**Issue by guilledipa** [open-telemetry/opentelemetry-collector-contrib#6303]
**Describe the bug**

OpenTelemetry is returning the following error (this is one example among other distribution type system metrics being received from Collectd):

```
ERROR        collectdreceiver/receiver.go:179        unable to process metrics        {"component_kind": "receiver", "component_type": "collectd", "component_name": "collectd", "error": "rpc error: code = InvalidArgument desc = Field timeSeries[4].points[0].interval.start_time had an invalid value of \"2021-11-14T17:14:08.026-08:00\": The start time must be before the end time (2021-11-14T17:14:08.026-08:00) for the non-gauge metric 'custom.googleapis.com/<some-name>/processes/fork_rate'."}
```

**Steps to reproduce**
Configure Collectd using the http_write plugin pointing it to the otel-contrib collectd receiver.

**What did you expect to see?**
Distribution type metrics being received and in this case, sent to GCP Cloud Monitoring (stackdriver exporter)

**What did you see instead?**
The error shown above in the OTel logs. 

**What version did you use?**
OTel contrib version: "v0.18.0"
Collectd version: 5.8.0

**What config did you use?**

* OpenTelemetry config

```
extensions:
  health_check:
receivers:
  collectd:
    config:
exporters:
  prometheus:
    endpoint: ":24445"
  stackdriver:
    project: "<some project>"
    endpoint: "monitoring.googleapis.com:443"
    metric:
      prefix: "custom.googleapis.com/<some_name>/"
      skip_create_descriptor: false
    retry_on_failure:
    number_of_workers: 3
service:
  extensions: [health_check]
  pipelines:
    metrics/monitoringatcorp:
      receivers: [collectd]
      exporters: [prometheus,stackdriver]
```

* Collectd `http_write` config:

```
LoadPlugin write_http
<Plugin write_http>
    <Node "example">
          URL "localhost:8081"
          Format "json"
    </Node>
</Plugin>
```

**Environment**
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Additional context**

Here the json message (corresponding to the error shown above) sent out by collectd out of the wire:

```
        Object
            Member Key: values
                Array
                    Number value: 77263073
                Key: values
            Member Key: dstypes
                Array
                    String value: derive
                Key: dstypes
            Member Key: dsnames
                Array
                    String value: value
                Key: dsnames
            Member Key: time
                Number value: 1636938428.026
                Key: time
            Member Key: interval
                Number value: 60.000
                Key: interval
            Member Key: host
                String value: <some hostname>
                Key: host
            Member Key: plugin
                String value: processes
                Key: plugin
            Member Key: plugin_instance
                String value: 
                Key: plugin_instance
            Member Key: type
                String value: fork_rate
                Key: type
            Member Key: type_instance
                String value: 
                Key: type_instance
```
