### ISSUE TITLE
`LongValueRecorder` doesn't pick up dimension from `resourcedetection/environment`

### ISSUE THREAD

**Issue by robbie-unlikelyai** [open-telemetry/opentelemetry-collector-contrib#6342]
**Describe the bug**
We use open-telemetry to send metrics from a Java service to AWS Cloudwatch. We try to add an `env` dimension to all of our metrics using the following method:
* Run our open-telemetry container with the environment variable `OTEL_RESOURCE_ATTRIBUTES` set to `env=test`.
* Run the `resourcedetection` processor with the `env` detector to convert the environment variable into an `env` attribute with value `test`.
* Use the `resource_to_telemetry_conversion` option with the `awsemf` exporter to turn this into an `env` dimension on the metrics with the value `test`.

When we do this, we find that the `env` dimension is added to `DoubleCounter` metrics, but not to `LongValueRecorder` metrics.

**Steps to reproduce**
Run an open-telemetry collector (with the config given below) next to a Java service that records metrics with the following code:
```
    var counter =
        meter
            .doubleCounterBuilder("counter1")
            .setDescription("Example counter")
            .setUnit("Count")
            .build();
    counter.add(1);
    var valueRecorder =
        meter
            .longValueRecorderBuilder("longrecorder1")
            .setDescription("Value recorder 1")
            .setUnit("Count")
            .build();
    valueRecorder.record(1);
```

The `doubleCounter` metric will have `env` as a dimension on the metric, but the `longValueRecorder` will not.

**What did you expect to see?**
`env` as a dimension on both metrics in CloudWatch

**What did you see instead?**
`env` didn't appear as a dimension on the LongValueRecorder metric in CloudWatch

**What version did you use?**
Versions: 
* Collector container:`otel/opentelemetry-collector-contrib:0.38.0`
* SDK version: `1.4.1`

**What config did you use?**
Config:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  batch/metrics:
    timeout: 60s
  resourcedetection/environment:
    detectors: [env]
  awsemf/application:
    namespace: Metrics
    log_group_name: /aws/ecs/application/metrics/
    resource_to_telemetry_conversion:
      enabled: true
metrics/application:
  receivers: [otlp]
  processors: [batch/metrics, resourcedetection/environment]
  exporters: [awsemf/application]
```

**Environment**
OS: Linux, running in AWS

**Additional context**
This could be linked to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4296.
