### ISSUE TITLE
Exporting Kubernetes Logs via OTLPHTTP-Exporter

### ISSUE THREAD

**Issue by TomasLongo** [open-telemetry/opentelemetry-collector-contrib#6417]
Hi all,

I'm currently trying to export Kubernetes container logs (aka node logs) with the otlphttp-exporter (The functionality is enabled through the helm chart) and the following agent config 

```yaml
agentCollector:
  enabled: true
  containerLogs:
    enabled: true
  configOverride:
    exporters:
      otlphttp:
        endpoint: http://echo-server.default.svc.cluster.local
    service:
      pipelines:
        logs:
          exporters:
            - otlphttp
            - logging/debug
```

the behaviour I observe with this config:

* the logs are properly  exported to STDOUT with the log exporter.
* The otlphttp exporter sends an empty body to the destination
  * I verified this by exporting the logs to an echo-server. The exporter sends a PUT to the server, which tells me that the body is empty

Is this the second point an intended behaviour, e.g. exporting k8s logs with otlphttp is not supported yet? Or am I missing some config details here?

thanks in advance for your help. 

Cheers, Tomas
