### ISSUE TITLE
tanzuobservability exporter type unknown

### ISSUE THREAD

**Issue by klxfeiyang** [open-telemetry/opentelemetry-collector-contrib#6424]
**Describe the bug**
```
Error: cannot load configuration: unknown exporters type "tanzuobservability" for tanzuobservability
2021/11/24 01:21:27 collector server run finished with error: cannot load configuration: unknown exporters type "tanzuobservability" for tanzuobservability
```

**Steps to reproduce**
Deploy opentelemetry binary using tanzuobservability as an exporter

**What did you expect to see?**
opentelemetry binary to recognize `tanzuobservability` as a compatible exporter type

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: opentelemetry-collector:0.38.0

**What config did you use?**
Config:

```
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 683
    exporters:
      otlp:
        endpoint: "http://someotlp.target.com:4317" # Replace with a real endpoint.
        tls:
          insecure: true
      tanzuobservability:
        traces:
          endpoint: "foobar"
    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [tanzuobservability]
```

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
May be related to this issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/6218
