### ISSUE TITLE
[datadogexporter] `.count` and `.sum` metrics not being exported for Summary type

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-collector-contrib#6485]
**Describe the bug**
For a `Summary` metric `foo`, I only see the `foo.quantile` metric in datadog.  I do not see the `foo.count` and `foo.sum` metrics.

**Steps to reproduce**
Send a `Summary` metric to the OTel Collector configured with the Datadog exporter.

**What did you expect to see?**
I expected to see the following metrics:
* `foo.sum`
* `foo.count`
* `foo.quantile` 

**What did you see instead?**
Only `foo.quantile`

**What version did you use?**
Version: `v0.39.0`

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 10s
    send_batch_max_size: 50
    send_batch_size: 50

exporters:
  logging:
    logLevel: info
  datadog:
    env: "${DD_ENV}"
    api:
      key: "${DD_APIKEY}"

service:
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - logging
        - datadog
```

**Environment**
OS: Linux

**Additional context**
I stepped through the code https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/internal/translator/metrics_translator.go#L363-L377 and it appears that `t.prevPts.Diff()` is returning `ok = false` for both the count and sum, causing `consumer.ConsumeTimeSeries` not to be called.  I haven't been able to root cause why this is the case.

**Comment by KSerrania** [comment]
Hi @sirianni,

Thanks for raising this issue!

To help us investigate, could you share the code you used to generate the summary metrics, as well as the output of the logging exporter? If possible, could you also enable the [file exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter) and send us its output?

I've tried reproducing your issue using the following app (with the Go SDK) to generate summary metrics, but haven't managed to reproduce what you're seeing yet:
<details>

<summary>App code</summary>

```
package main

import (
	"context"
	"log"
	"time"

	"google.golang.org/grpc"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/global"
	controller "go.opentelemetry.io/otel/sdk/metric/controller/basic"
	processor "go.opentelemetry.io/otel/sdk/metric/processor/basic"
	"go.opentelemetry.io/otel/sdk/metric/selector/simple"
)

// Initializes an OTLP exporter, and configures the corresponding trace and
// metric providers.
func initProvider() func() {
	ctx := context.Background()

	exp, err := otlpmetricgrpc.New(
		ctx,
		otlpmetricgrpc.WithInsecure(),
		otlpmetricgrpc.WithEndpoint("otel-collector:30080"),
		otlpmetricgrpc.WithDialOption(grpc.WithBlock()),
	)
	handleErr(err, "failed to create exporter")

	cont := controller.New(
		processor.New(
			simple.NewWithInexpensiveDistribution(),
			exp,
		),
		controller.WithExporter(exp),
		controller.WithCollectPeriod(2*time.Second),
	)

	global.SetMeterProvider(cont.MeterProvider())
	handleErr(cont.Start(context.Background()), "failed to start controller")

	return func() {
		// Push any last metric events to the exporter.
		handleErr(cont.Stop(context.Background()), "failed to stop controller")
	}
}

func main() {
	log.Printf("Waiting for connection...")

	shutdown := initProvider()
	defer shutdown()

	meter := global.Meter("test-meter")

	commonLabels := []attribute.KeyValue{
		attribute.String("label", "value"),
	}

	ioReadBytes := metric.Must(meter).
		NewInt64Histogram(
			"io.read.bytes",
			metric.WithDescription("IO read bytes"),
		).Bind(commonLabels...)
	defer ioReadBytes.Unbind()

	for i := 0; i < 10; i++ {
		ioReadBytes.Record(context.Background(), int64(i))

		<-time.After(time.Second)
	}

	log.Printf("Done!")
}

func handleErr(err error, message string) {
	if err != nil {
		log.Fatalf("%s: %v", message, err)
	}
}
```
</details>

<details>

<summary>Collector config</summary>

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:30080"

exporters:
  file/metrics:
    path: /etc/otel/metrics.dat
  datadog:
    api:
      key: <api key>

service:
  telemetry:
    logs:
      level: warn

  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [datadog, file/metrics]
```
</details>

My main guesses for now are either:
- something weird around the timestamps of the summary metrics (that's the main reason why a point would be considered invalid by `t.prevPts.Diff()`)
- not enough metrics sent (the count and sum metrics are cumulative metrics, we don't send the first point - you need to send at least two points to be able to see something).
