### ISSUE TITLE
Meter values sent to Elastic APM are missing labels

### ISSUE THREAD

**Issue by benbek** [open-telemetry/opentelemetry-collector-contrib#6492]
**Describe the bug**
I don't see _any_ labels when I look at a meter record in my APM metric index. I send multiple labels – a numeric attribute and two strings – but none of them appear.
When the same go code points directly to the APM server, labels do appear.

Note: this bug is also opened in the [contrib repo](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5935) but is reproducible in this non-contrib collector as well.

**Steps to reproduce**
Running [this gist](https://gist.github.com/benbek/1375cd7c5f217361d1ab0b5f357ca9a6) should bump up two counters – both with attributes.
Just point [this line](https://gist.github.com/benbek/1375cd7c5f217361d1ab0b5f357ca9a6#file-main-go-L18) to your right endpoint.

**What did you expect to see?**
the labels. Same ones that I see if I bypass the collector.

**What did you see instead?**
no labels.

**What version did you use?**
- go 1.17
- elastic/apm 7.15.1
- opentelemetry 1.0.1
- opentelemetry collector helm chart version: 0.6.0

**What config did you use?**
```yaml
image:
  repository: otel/opentelemetry-collector
command:
  name: otelcol

config:
  exporters:
    logging: null
    otlp/elastic:
      endpoint: "${ELASTIC_SERVER_URL}"
      headers:
        Authorization: "Bearer ${ELASTIC_SECRET_TOKEN}"
  extensions:
    health_check: {}
  processors:
    batch: {}
    memory_limiter: null
    resource/pii:
      attributes:
        - key: host.ip
          action: delete
  receivers:
    jaeger: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http: null
  service:
    extensions:
      - health_check
    pipelines:
      metrics:
        exporters:
          - otlp/elastic
        processors:
          - memory_limiter
          - batch
          - resource/pii
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - otlp/elastic
        processors:
          - memory_limiter
          - batch
          - resource/pii
        receivers:
          - otlp
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
agentCollector:
  enabled: true
standaloneCollector:
  enabled: true
  replicaCount: 1
```

**Environment**
GKE

**Additional context**
See additional discussion about this problem here: https://discuss.elastic.co/t/opentelemetry-metrics-dont-have-labels/287510
