### ISSUE TITLE
[metricstransformprocessor] Summary datapoint merging is not handled.

### ISSUE THREAD

**Issue by p120ph37** [open-telemetry/opentelemetry-collector-contrib#6504]
**Describe the bug**
In `datapoint_aggregation.go`, the `MetricDescriptor_SUMMARY` type is not handled.

**Steps to reproduce**
1. Get a Summary metric into the pipeline.  For example, the `http.server.requests` metric emitted from Spring Boot + `micrometer-registry-statsd` is a "timer" type, and becomes a "summary" when received by the `statsdreceiver`, with this config:
```
statsd:
  timer_histogram_mapping:
    - statsd_type: histogram
      observer_type: summary
    - statsd_type: timer
      observer_type: summary
```
2. Apply a `metricstransform` processor with a "sum" aggregation type to the metric, such as with this config:
```
metricstransform:
  transforms:
    - include: http.server.requests
      action: update
      operations:
        - action: aggregate_labels
          label_set: [ uri ]
          aggregation_type: sum
```

**What did you expect to see?**
I expect the labels of the `http.server.requests` metric besides `uri` to be removed, and the summaries for those datapoints to be aggregated.

**What did you see instead?**
The `http.server.requests` metric is dropped entirely.

**What version did you use?**
Version: aws-opentelemetry-collector v0.15

**Additional context**
The `datapoint_aggregation.go` file already has logic for aggregating histogram datapoints, but is missing logic for summary datapoints (specifically, it has logic for `MetricDescriptor_GAUGE_DISTRIBUTION`, but not `MetricDescriptor_SUMMARY`)
