### ISSUE TITLE
Invalid config examples in windowsperfcountersreceiver README.md

### ISSUE THREAD

**Issue by tamir-michaeli** [open-telemetry/opentelemetry-collector-contrib#6720]
**Describe the bug**
Documentation issue:
The provided config examples in the windowsperfcountersreceiver README are invalid. All having the same mistake of using "counters" instead of "perfcounters".
For example, this is an invalid config taken from the readme.

```
windowsperfcounters:
  collection_interval: <duration> # default = "1m"
  counters:
    - object: <object name>
      instances: [<instance name>]*
      counters:
        - <counter name>
   ```

valid config can be seen under testdata:
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/eacfde3fcbd46ba60a6db0e9a41977390c4883bd/receiver/windowsperfcountersreceiver/example_config.yaml
