### ISSUE TITLE
Data from OTLP receiver does not show up on Prometheus Exporter

### ISSUE THREAD

**Issue by imrenagi** [open-telemetry/opentelemetry-collector-contrib#6824]
Hi, 

I'm trying to use otel-collector to send observability data to those platform:
* newrelic (both trace and metrics)
* prometheus (metrics only)

I managed to send both trace and metrics data to newrelic. I can confirm the trace and metrics can be seen from newrelic console. But Im unable to see similar metrics on prometheus endpoint exposed on the collector. Per my understanding, if we are using otlp receiver, we should be able to export it any backend by defining its exporter. But Im not sure why adding prometheus exporter doesnt expose any metrics. Is it possible to fan out data we got from receivers.otlp to all exporters defined on the services.pipelines.metrics.exporters? 

Thanks for the help!
Here is the config Im using:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:  

processors:
  batch:

exporters:
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    headers:
      api-key: ${OTEL_EXPORTER_NEWRELIC_LICENCE_KEY}
  prometheus:
    endpoint: "0.0.0.0:9464"

service: 
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, prometheus]
```
