### ISSUE TITLE
AttributesProcessor (or a better suited processor) to support changing span.kind

### ISSUE THREAD

**Issue by o11ydemo** [open-telemetry/opentelemetry-collector-contrib#6883]
**Is your feature request related to a problem? Please describe.**
I have a need to change some span's span.kind to another kind. As far as I can tell this isn't supported with the AttributesProcessor, SpanProcessor, etc.

**Describe the solution you'd like**
Ideally this is just another item that can be changed. 

**Describe alternatives you've considered**
I've thought about forcing this change in code itself, but this has come up in places where no manual instrumentation is needed.

**Additional context**
Open to hearing if there are other ways to achieve this.

**Comment by jpkrohling** [comment]
cc @boostchicken

**Comment by boostchicken** [comment]
techincally this is not an attribute, so it should live in the SpanProcessor

**Comment by boostchicken** [comment]
PR is out there for this.

**Comment by jpkrohling** [comment]
@kovrus, do you know if the transform processor supports this?

**Comment by kovrus** [comment]
Based on SpanContext source code - yes, see  https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/contexts/internal/ottlcommon/span.go#L280-L292 and  https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/ottl/contexts/internal/ottlcommon/span.go#L81, but I can double check and verify that.

**Comment by kovrus** [comment]
For example, the following config will set the all the spans of the `Internal` (1) to `Client` (3) kind, see also https://github.com/open-telemetry/opentelemetry-collector/blob/main/pdata/ptrace/traces.go#L73-L96 for kind codes.

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  transform:
    trace_statements:
      - context: span
        statements:
        - set(kind, 3) where kind == 1

exporters:
  logging:
    logLevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform]
      exporters: [logging]
```
