### ISSUE TITLE
prometheus receiver: more info about scrape error

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-collector-contrib#6900]
**Is your feature request related to a problem? Please describe.**
Currently, prometheusreceiver in case of error reports the following in the logs:
```
warn    internal/metricsbuilder.go:124  Failed to scrape Prometheus endpoint    {"kind": "receiver", "name": "prometheus", "scrape_timestamp": 1639773267689, "target_labels": "map[__name__:up]"}
```
It would be awesome to have more information about what really went wrong for debugging purposes.

**Describe the solution you'd like**
Perhaps it's possible to log http request errors. For example, `socket hang up`, `timeout exceeded` or `response code 503`.

**Comment by jpkrohling** [comment]
cc @Aneurysm9 @dashpole

**Comment by dashpole** [comment]
See https://github.com/open-telemetry/opentelemetry-collector/issues/2364#issuecomment-785303139.  Scraping happens in the prometheus server code, and is a debug log line.  You can enable debug logging with `--log-level=DEBUG`

**Comment by morigs** [comment]
@dashpole Thank you!
It's kinda strange that error is on the debug level

**Comment by jinxin-fu** [comment]
> See [open-telemetry/opentelemetry-collector#2364 (comment)](https://github.com/open-telemetry/opentelemetry-collector/issues/2364#issuecomment-785303139). Scraping happens in the prometheus server code, and is a debug log line. You can enable debug logging with `--log-level=DEBUG`

Hi. I am a green hand in this project . I want to ask where to add the debug logging flag `--log-level=DEBUG`  for image "otel/opentelemetry-collector-contrib". Looking forward to your reply  Thanks.

**Comment by morigs** [comment]
@jinxin-fu usually, you specify arguments after image name, if you use docker. For exanple,
```sh
$ docker run -p 4317:4317 -it --rm -v $(pwd)/otel:/otel --name otel \
  otel/opentelemetry-collector-contrib:0.42.0 --config /otel/config.yaml --log-level=DEBUG
```
However, it looks like `--log-level` flag has been deprecated and removed in [v0.38.0](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.38.0)

From now on you should use config file instead. Use `service.telemetry.logs.level`

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger:
    endpoint: "host.docker.internal:14250"
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: DEBUG
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
```
