### ISSUE TITLE
[prometheus exporter] Metric value overflow on metrics_expiration

### ISSUE THREAD

**Issue by albertteoh** [open-telemetry/opentelemetry-collector-contrib#6935]
**Describe the bug**
When a metric expires, the value for the metric appears to overflow the max int64 value: `9223372036854775808`.

**Steps to reproduce**
1. Start otel collector with provided config below.
2. Start HotROD example: `docker run   --rm --network="host" --env JAEGER_AGENT_HOST=localhost  --env JAEGER_AGENT_PORT=6835   -p8080-8083:8080-8083   jaegertracing/example-hotrod:latest   all`
    1. This will emit spans to otel collector on port `6835`.
3. Click on a button on HotROD example to send a trace.
4. Check that the `latency_bucket` metrics are correct for the first minute of data, and make a note of which bucket has `count > 0`. For example, where the metric has label `le = "250"`.
    1. Example query: `latency_bucket{service_name = "driver", le="250"}`

**What did you expect to see?**

After a minute (on metric expiry), the metric with `le = "250"` (example query `latency_bucket{service_name = "driver", le="250"}`) should no longer be query-able (a null value).

**What did you see instead?**

After a minute (on metric expiry), the metric with `le = "250"` (example query `latency_bucket{service_name = "driver", le="250"}`) will jump to `9223372036854775808`.

**What version did you use?**
Version: `main` branch

**What config did you use?**
Config: 
```
receivers:
  jaeger:
    protocols:
      thrift_binary:
        endpoint: "localhost:6836"
      thrift_compact:
        endpoint: "localhost:6835"
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: :12345
  otlp:
    protocols:
      grpc:
        endpoint: :4317
  prometheus:
    config:
      global:
        external_labels:
          p8s_logzio_name: spm-demo-otel
      scrape_configs: 
      - job_name: 'atm'
        scrape_interval: 15s
        static_configs:
        - targets: [ "0.0.0.0:8889" ]
exporters:
  jaeger:
    endpoint: "localhost:14250"
    tls:
      insecure: true
  prometheus:
    endpoint: "localhost:8889"
    metric_expiration: 1m
  logging:
    loglevel: debug
processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
    latency_histogram_buckets: [2ms, 6ms, 10ms, 100ms, 250ms, 500ms, 1000ms, 10000ms, 100000ms, 1000000ms]
    # Additional list of dimensions on top of:
    # - service.name
    # - operation
    # - span.kind
    # - status.code
    dimensions:
      # If the span is missing http.method, the processor will insert
      # the http.method dimension with value 'GET'.
      # For example, in the following scenario, http.method is not present in a span and so will be added as a dimension to the metric with value "GET":
      # - promexample_calls{http_method="GET",operation="/Address",service_name="shippingservice",span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_UNSET"} 1
      - name: http.method
        default: GET
      # If a default is not provided, the http.status_code dimension will be omitted
      # if the span does not contain http.status_code.
      # For example, consider a scenario with two spans, one span having http.status_code=200 and another missing http.status_code. Two metrics would result with this configuration, one with the http_status_code omitted and the other included:
      # - promexample_calls{http_status_code="200",operation="/Address",service_name="shippingservice",span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_UNSET"} 1
      # - promexample_calls{operation="/Address",service_name="shippingservice",span_kind="SPAN_KIND_SERVER",status_code="STATUS_CODE_UNSET"} 1
      - name: http.status_code    
extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [spanmetrics,batch]
      exporters: [jaeger, logging]
    metrics/spanmetrics:
      # This receiver is just a dummy and never used.
      # Added to pass validation requiring at least one receiver in a pipeline.
      receivers: [otlp/spanmetrics]
      exporters: [prometheus]
    metrics:
      receivers: [otlp,prometheus]
      exporters: [logging]      
  telemetry:
    logs:
      level: "debug"
```

**Environment**
OS: "Ubuntu 20.04"
Compiler(if manually compiled): "go 1.17.5")

**Additional context**

- Is there something the `spanmetrics` processor should be doing to avoid this problem?
- Is it perhaps a config or a promeetheus query issue?
- Is this expected behaviour and is the recommendation to simply increase the `metric_expiration` duration?

The following screenshots illustrate the problem for the default `5m` `metric_expiration` configuration:

**Before Expiry**
<img width="1654" alt="before-expiry" src="https://user-images.githubusercontent.com/26584478/147091355-f41ae85e-10f7-4e7f-92cf-bfccd6a7483c.png">

**After Expiry**
<img width="1654" alt="after-expiry" src="https://user-images.githubusercontent.com/26584478/147091346-cce82f75-460b-467c-bda8-c68e1b59bb11.png">

The logs also reflect the above screenshots, showing the correct metrics initially, then suddenly jumping to a very large count:
- Initially, the `le = "250"` bucket has a count of `3`.
- 5 mins later without sending any traces, a number of logs indicate the expiry of the metrics.
- At this time, `le = "250"` bucket jumps to a very large number, which appears to be 1 + MaxInt64.
- Other buckets remain at 0.
