### ISSUE TITLE
Permanent error: failed to convert OTLP metric to line protocol

### ISSUE THREAD

**Issue by yok789456** [open-telemetry/opentelemetry-collector-contrib#7049]
Got error when insert spanmetric into **influx** but metric can(data from kafka).

opentelemetry-collector-contrib: v0.40.0

diagram:
`service -> opentelemetry-collector-contrib(metric, spanmetric) -> kafka -> opentelemetry-collector-contrib(consumer) -> influx`

> 2022-01-05T08:52:06.853Z	error	exporterhelper/queued_retry.go:183 Exporting failed. The error is not retryable. Dropping data. {"kind": "exporter", "name": "influxdb/test_historgram", "error": "Permanent error: failed to convert OTLP metric to line protocol: invalid metric histogram bucket counts qty 10 vs explicit bounds qty 10", "dropped_items": 92}

config(from kafka to influx)
```yaml
receivers:
  kafka/metric:
    brokers:
      - localhost:9092
    topic: telemetry.metric.otlp
    group_id: otel-collector-metric-consumer
    auth:
      tls:
        insecure: true
    protocol_version: 2.8.0
  
  kafka/spanmetric:
    brokers:
       - localhost:9092
    topic: telemetry.spanmetric.otlp
    group_id: otel-collector-spanmetric-consumer
    auth:
      tls:
        insecure: true
    protocol_version: 2.8.0


processors:
  batch:
    timeout: 3s

memory_limiter:
  limit_mib: 120
  check_interval: 4s

extensions:
  zpages: {}
  
  memory_ballast:
    # Memory Ballast size should be max 1/3 to 1/2 of memory.
    size_in_percentage: 30
  
  health_check:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8877"
    namespace: "genesis"

  influxdb/test:
    endpoint: http://localhost
    timeout: 5000ms
    sending_queue:
      enabled: true
      num_consumers: 3
      queue_size: 10
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 3s
      max_elapsed_time: 10s
    org: test@test-email
    bucket: test
    token: token
    metrics_schema: telegraf-prometheus-v2

  influxdb/test_historgram:
    endpoint: http://localhost
    timeout: 5000ms
    sending_queue:
      enabled: true
      num_consumers: 3
      queue_size: 10
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 3s
      max_elapsed_time: 10s
    org: test@test-email
    bucket: test_historgram
    token: token
    metrics_schema: telegraf-prometheus-v2

service:
  extensions: [zpages, memory_ballast, health_check]
  pipelines:
    metrics:
      receivers: [kafka/metric]
      processors: [memory_limiter, batch]
      exporters: [influxdb/test] // ok

    metrics/spanmetrics:
      receivers: [kafka/spanmetric]
      processors: [memory_limiter, batch]
      exporters: [influxdb/test_historgram] // got error
```
