### ISSUE TITLE
[MetricsTransformProcessor] experimental_match_labels didn't work with update operation 

### ISSUE THREAD

**Issue by chenluo1234** [open-telemetry/opentelemetry-collector-contrib#7071]
**Describe the bug**
I am trying to use `experimental_match_labels` to add a new label only to those timeseries with matched label {service: "banana"}. The config looks like the following:
```
 metricstransform:
    transforms:
 - action: update
      experimental_match_labels: {service: "banana"}
      include: .*
      match_type: regexp
      operations:
      - action: add_label
         new_label: tier
         new_value: production
```
However, those timeseries with label {service: "banana"} didn't get new label "tier" added. 

**Steps to reproduce**
You can easily reproduce this using a unit test. 
```
	standardTests = []metricsTransformTest{
		// UPDATE
		{
			name: "add_label",
			transforms: []internalTransform{
				{
					MetricIncludeFilter: internalFilterStrict{include: "metric1", matchLabels: map[string]StringMatcher{
						"service": strictMatcher("banana"),
					}},
					Action: Update,
					Operations: []internalOperation{
						{
							configOperation: Operation{
								Action:   AddLabel,
								NewLabel: "tier",
								NewValue: "production",
							},
						},
					},
				},
			},
			in: []*metricspb.Metric{
				metricBuilder().setName("metric1").
					setDataType(metricspb.MetricDescriptor_CUMULATIVE_INT64).
					setLabels([]string{"service"}).
					addTimeseries(1, []string{"banana"}).
					addInt64Point(0, 3, 2).build(),
			},
			out: []*metricspb.Metric{
				metricBuilder().setName("metric1").
					setDataType(metricspb.MetricDescriptor_CUMULATIVE_INT64).
					setLabels([]string{"service", "tier"}).
					addTimeseries(1, []string{"banana", "production"}).
					addInt64Point(0, 3, 2).build(),
			},
		},
 }
```

**What did you expect to see?**
Those timeseries with label {service: "banana"} should get new label {"tier": "production"} applied.

**What did you see instead?**
Those timeseries with label {service: "banana"} didn't get new label {"tier": "production"} applied.

**What version did you use?**
go.opentelemetry.io/collector v0.41.0
github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.41.0

**Environment**
OS: Ubuntu 18.04
Compiler(if manually compiled): go 1.17
