### ISSUE TITLE
promethues receiver get unknown error when scrape a target with same metricname and different type(histogram/counter)

### ISSUE THREAD

**Issue by buptubuntu** [open-telemetry/opentelemetry-collector-contrib#7076]
**Describe the bug**
promethues receiver get unknown error when scrape a target with same metricname and different type(histogram/counter)

target exporter data as below:
```
# HELP http_requests Seconds spent serving HTTP requests.
# TYPE http_requests histogram
http_requests_bucket{method="GET",path="metrics",status="200",le="0.005"} 524
http_requests_bucket{method="GET",path="metrics",status="200",le="0.01"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="0.025"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="0.05"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="0.1"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="0.25"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="0.5"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="1"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="2.5"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="5"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="10"} 525
http_requests_bucket{method="GET",path="metrics",status="200",le="+Inf"} 525
http_requests_sum{method="GET",path="metrics",status="200"} 0.6790628170000005
http_requests_count{method="GET",path="metrics",status="200"} 525
# HELP http_requests_total The total number of HTTP requests.
# TYPE http_requests_total counter
http_requests_total{status="200"} 5766

```

**Steps to reproduce**
* start an expoter to expose data as above(http://localhost:9199/metrics)
* start otel collector to use promethues receiver to get the data from http://localhost:9199/metrics,config file as below:
```
extensions:
  health_check: 
  pprof:
    block_profile_fraction: 3
    endpoint: ':0'
    mutex_profile_fraction: 5
  zpages: 
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: static-configs
          scrape_interval: 20s
          scrape_timeout: 10s
          static_configs:
            - labels:
                __metrics_path__: /metrics
              targets:
                - '127.0.0.1:9199'
processors:
  batch: 
exporters:
  logging:
    loglevel: debug
service:
  pipelines:
    metrics:
      receivers:
        - prometheus
      processors:
        - batch
      exporters:
        - logging
  extensions:
    - health_check
    - pprof
    - zpages
```
* get unexpected error when call MetricFamily.Add method 

**What did you expect to see?**
Dont report error and accept the data

**What did you see instead?**
get unexpected error when call MetricFamily.Add method 

**What version did you use?**
Version: 0.38.0
Not sure if it is fixed in latest version

**What config did you use?**
```
extensions:
  health_check: 
  pprof:
    block_profile_fraction: 3
    endpoint: ':0'
    mutex_profile_fraction: 5
  zpages: 
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: static-configs
          scrape_interval: 20s
          scrape_timeout: 10s
          static_configs:
            - labels:
                __metrics_path__: /metrics
              targets:
                - '127.0.0.1:9199'
processors:
  batch: 
exporters:
  logging:
    loglevel: debug
service:
  pipelines:
    metrics:
      receivers:
        - prometheus
      processors:
        - batch
      exporters:
        - logging
  extensions:
    - health_check
    - pprof
    - zpages
```

**Environment**
OS: Centos
Compiler(if manually compiled): (e.g., "go 17.1")

**Additional context**
