### ISSUE TITLE
How to use the  receiver/prometheus to collect the metric from prometheus instances

### ISSUE THREAD

**Issue by jinxin-fu** [open-telemetry/opentelemetry-collector-contrib#7150]
I want to use opentelemtry to collect the metric from a prometheus instance and process , then put data to other backend.
How can I collect the data from prometheus use receiver/prometheus.
```
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 5s
          static_configs:
            - targets: ["localhost:8888"]
```
