### ISSUE TITLE
How to use simple_prometheus receiver

### ISSUE THREAD

**Issue by jinxin-fu** [open-telemetry/opentelemetry-collector-contrib#7180]
the otel configured as follow: 
```
  prometheus_simple:
    collection_interval: 5s
    # the federation endpoint:
    # Read more about it here: https://prometheus.io/docs/prometheus/latest/federation/
    # You can query the federation with PromQL, encoded as part of the query string.
    endpoint: http://prometheus-kube-prometheus-hypermoni.hypermonitor.svc:9090
    metrics_path: /federate
    params:
      'match[]':
        - '{job="serviceMonitor/hypermonitor/prometheus-kube-prometheus-node-exporter/0"}'
        - '{__name__=~"job:.*"}'
```
Error: cannot load configuration: unknown receivers type "prometheus_simple" for prometheus_simple
2022/01/17 01:27:33 collector server run finished with error: cannot load configuration: unknown receivers type "prometheus_simple" for prometheus_simple

How to use the receiver in opentelemetry-collector-contrib such as prometheus_simple
