### ISSUE TITLE
New Component: RabbitMQ Metric Receiver

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector-contrib#7241]
## The purpose and use-cases of the new component
The RabbitMQ Metric Receiver would pull KPI stats from a node with the [RabbitMQ Management Plugin API](https://www.rabbitmq.com/management.html). It will generate metrics on queue messages (delivered, published, etc.).

Targeting version 3.8 and 3.9 of RabbitMQ as they are the [currently supported](https://www.rabbitmq.com/versions.html) versions at the time of writing.

## Example configuration for the component

The following configuration settings are required:
- `username`
- `password`

The following configuration settings are optional:

- `endpoint` (default: `http://localhost:15672`): The URL of the node to be monitored.
- `collection_interval` (default = `10s`): This receiver collects metrics on an interval. Valid time units are `ns`, `us` (or `µs`), `ms`, `s`, `m`, `h`.
- `tls` (defaults defined [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md)): TLS control. By default insecure settings are rejected and certificate verification is on.

### Example Configuration

```yaml
receivers:
  rabbitmq:
    endpoint: http://localhost:15672
    username: otelu
    password: $RABBITMQ_PASSWORD
    collection_interval: 10s
```

## Telemetry data types supported
Metrics

## Sponsor (Optional)
@djaglowski
