### ISSUE TITLE
Prometheus COUNTER metric exported as Gauge and Sum data types

### ISSUE THREAD

**Issue by anna-tran** [open-telemetry/opentelemetry-collector-contrib#7285]
**Describe the bug**
I'm trying to scrape Prometheus metrics from Cortex and exporting to CloudWatch via the OTEL Collector.
According to the [proposed specification](https://github.com/open-telemetry/opentelemetry-specification/pull/2266/commits/b27b024048135bdeece32a632ef2387965b2436a) for Prometheus to OTEL data type conversion, Prometheus Counter becomes an OTLP Sum.

However that Counter metric in Cortex is exposed as both a **Sum** and **Gauge** data type metric. The metric data type is identified in the collector logs but not in CloudWatch, which leads to spikey graphs because CloudWatch interprets both **Sum** and **Gauge** data under the same metric.

**Steps to reproduce**
1. Run an application with a Cortex backend in Elastic Kubernetes Service (EKS) and set up appropriate permissions to scrape Prometheus metrics from the application (see [here](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-OpenTelemetry.html#AMP-onboard-ingest-metrics-OpenTelemetry-pre) for basic permission setup).
2. Create Kubernetes deployment yaml config with the OTEL collector configured with
  - a prometheus receiver
  - a metric filter processor
  - `logging` and `awsemf` exporters
3. Create the deployment and monitor CloudWatch and pod logs

**What did you expect to see?**
Expected to see only Prometheus Counter metrics exposed only as monotonic **Sum** metrics.

**What did you see instead?**
Actually saw Prometheus Counter metrics exposed as both monotonic **Sum** metrics and **Gauge** metrics.

**What version did you use?**
Used the latest OTEL image available from ECR
public.ecr.aws/aws-observability/aws-otel-collector:latest

**What config did you use?**
```
---
# create adot-col namespace
apiVersion: v1
kind: Namespace
metadata:
  name: adot-col
  labels:
    name: adot-col

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-conf
  namespace: adot-col
  labels:
    app: aws-adot
    component: adot-collector-conf
data:
  adot-collector-config: |
    receivers:
      prometheus:
        config:
          global:
            scrape_interval: 15s
            scrape_timeout: 10s
            evaluation_interval: 1m
          scrape_configs:
          - job_name: cortex/ingester
            kubernetes_sd_configs:
            - namespaces:
                names:
                - cortex
              role: pod
            metrics_path: "/metrics"
            relabel_configs:
            - action: replace
              target_label: pod_name
              source_labels:
              - __meta_kubernetes_pod_name
              regex: (.*)
              replacement: $$1
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: instance
              regex: (.*)
              replacement: $$1

    processors:
      filter/include:
        metrics:
          include:
            match_type: regexp
            metric_names:
              - (^cortex_ingester_memory_series.*)

    exporters:
      awsemf:
        log_group_name: 'AOTLogGroup'
        log_stream_name: 'AOTLogStream'
        namespace: 'AOTMetricNS'
        dimension_rollup_option: NoDimensionRollup
        resource_to_telemetry_conversion:
          enabled: true
        
      logging:
        loglevel: debug
        sampling_initial: 5
        sampling_thereafter: 200

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [filter/include]
          exporters: [awsemf, logging]
---
# create adot-col service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-proxy-ingest-service-account
  namespace: adot-col
  annotations:
    eks.amazonaws.com/role-arn: <arn-of-role-with-adot-collector-permissions>

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adotcol-admin-role
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/proxy
    - services
    - endpoints
    - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adotcol-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: adot-proxy-ingest-service-account
    namespace: adot-col
roleRef:
  kind: ClusterRole
  name: adotcol-admin-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: adot-collector
  namespace: adot-col
  labels:
    app: aws-adot
    component: adot-collector
spec:
  ports:
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: adot-collector
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adot-collector
  namespace: adot-col
  labels:
    app: aws-adot
    component: adot-collector
spec:
  selector:
    matchLabels:
      app: aws-adot
      component: adot-collector
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aws-adot
        component: adot-collector
    spec:
      serviceAccountName: adot-proxy-ingest-service-account
      containers:
      - command:
          - "/awscollector"
          - "--config=/conf/adot-collector-config.yaml"
        image: public.ecr.aws/aws-observability/aws-otel-collector:latest
        imagePullPolicy: Always
        name: adot-collector
        resources:
          limits:
            cpu:  1000m
            memory: 8000Mi
          requests:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 8888  # Default endpoint for querying metrics.
        volumeMounts:
        - name: adot-collector-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: adot-collector-conf
            items:
              - key: adot-collector-config
                path: adot-collector-config.yaml
          name: adot-collector-config-vol
---
```

**Environment**
Deployed to an EKS cluster using
Kubernetes version
1.21
Platform version
eks.2

**Additional context**
Log of the Prometheus metric converted to Sum DataType
```
StartTimestamp: 2022-01-17 22:53:23.936 +0000 UTC
Timestamp: 2022-01-17 22:53:42.737 +0000 UTC
Value: 6.000000
Metric #2
Descriptor:
     -> Name: cortex_ingester_memory_series_removed_total
     -> Description: The total number of series that were removed per user.
     -> Unit:
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
```

Log of the same Prometheus metric converted to a Gauge DataType
```
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-01-17 22:53:43.845 +0000 UTC
Value: 3.000000
Metric #2
Descriptor:
     -> Name: cortex_ingester_memory_series_removed_total
     -> Description:
     -> Unit:
     -> DataType: Gauge
```

`cortex_ingester_memory_series_removed_total` is a COUNTER value in Cortex ([code reference](https://github.com/cortexproject/cortex/blob/master/pkg/ingester/metrics_test.go#L132))

**Comment by anna-tran** [comment]
@alolita for reference

**Comment by jpkrohling** [comment]
cc @Aneurysm9 @dashpole @gouthamve

**Comment by Aneurysm9** [comment]
I've been working with @anna-tran on this and we have observed that the metric from some instances is consistently received as a sum and for others consistently received as a gauge.  We have not been able to identify differences between the instances that would account for this and the exposition coming from each for this metric is identical.

**Comment by sethAmazon** [comment]
@Aneurysm9 what do you mean by instance in this context. Are more than 1 pod of the collector being deployed? @anna-tran can you please show me output of kubectl get pods -A

**Comment by Aneurysm9** [comment]
Not more than one collector pod, more than one metric source pods.  When the collector scrapes pod A it consistently treats this as a gauge and when it scrapes pod B it consistently treats it as a sum.

**Comment by sethAmazon** [comment]
So there are multiple instances of cortex running?

**Comment by Aneurysm9** [comment]
Multiple instances of the Cortex ingester service, yes.  In this case the Cortex ingester service is a service being monitored, not (necessarily) a target for the metric data.

**Comment by sethAmazon** [comment]
I'm under the assumption cortex_ingester_memory_series_removed_total is created by cortex and not a metric that is being sent to cortex then to the collector.

**Comment by sethAmazon** [comment]
Are there any flags I have to turn on in cortex to get it to emit this metric?

**Comment by anna-tran** [comment]
Yes, "cortex_ingester_memory_series_removed_total" is a metric [emitted by Cortex](https://github.com/cortexproject/cortex/blob/master/pkg/ingester/metrics.go#L16) which the collector scrapes from our Prometheus `/metrics` endpoint. This metric should be available without needing to turn on any flags. 

I'm working with @sethAmazon to try to reproduce the same setup for further debugging.

**Comment by sethAmazon** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md we should always see sum as the value according to the docs since we are only seeing counter metric type for this metric

**Comment by sethAmazon** [comment]
When it is a gauge it is a delta for removed metric else it is sum of all removed

**Comment by jeromeinsf** [comment]
@sethAmazon Any luck reproducing on your side?

**Comment by sethAmazon** [comment]
I have not been able to reproduce in my own instance. I have looked into @anna-tran eks cluster and I can see the issue. I do not have access to that cluster since it owned by another team.

**Comment by sethAmazon** [comment]
This is from the slack channel. The issue was with the config of prometheus. As far as getting delta values this is as designed to match cw agent. I spoke with @Aneurysm9 and we are not sure at this point if we will support sending raw to emf instead of calculated delta. If we do support it, we do not know if it should be boolean flag driven and metric selector driven.

**Comment by Aneurysm9** [comment]
The specific configuration issue was the use of a relabeling rule that could result in duplicate `instance` labels:

```yaml
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: instance
              regex: (.*)
              replacement: $$1
```

Because the source here was a `StatefulSet` it was possible for multiple pods to be scheduled on the same node, resulting in a duplicate `instance` label confusing the target metadata resolution logic.  It is not clear to me that there is a way to detect or respond to this misconfiguration within the receiver.

I am closing this issue as it is resolved.  Please feel free to open a new issue to request control over the cumulative-to-delta conversion in the `awsemfexporter` if desired.
