### ISSUE TITLE
Attribute Processor Not Deleting Tag With a Particular Key

### ISSUE THREAD

**Issue by suddendust** [open-telemetry/opentelemetry-collector-contrib#7291]
**Describe the bug**

We have the following OTEL config to scrub PII data in spans:
```
      attributes/delete:
        actions:
          - key: authorization
            action: delete
      attributes/delete2:
        actions:
          - key: Authorization
            action: delete
      attributes/delete3:
        actions:
          - key: "x-someheader-jwt"
            action: delete
```
While there are no spans containing tag `authorization`, we see that we have spans with tag `x-someheader-jwt`.  For some reasons, these spans are not getting processed. We also tried:
```
      attributes/delete:
        actions:
          - key: authorization
            action: delete
         - key: authorization
            action: delete
         - key: "x-someheader-jwt"
            action: delete
```
But this didn't work as well. The tag is still present.

**Steps to reproduce**
Add this to your OTEL config and hit a request containing this header. 

**What did you expect to see?**
There should be no spans with tag `x-someheader-jwt`

**What did you see instead?**
There are spans with tag `x-someheader-jwt`

**What version did you use?**
Version: 0.21.0

**What config did you use?**
```
      attributes/delete:
        actions:
          - key: authorization
            action: delete
      attributes/delete2:
        actions:
          - key: Authorization
            action: delete
      attributes/delete3:
        actions:
          - key: "x-someheader-jwt"
            action: delete
```

**Environment**
K8s
