### ISSUE TITLE
Scrapers: separate resource attributes in metadata.yaml

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#7301]
## Problem

Currently `attributes` fields in metadata.yaml sometimes are used for both metric and resource attributes. Some scrapers don't specify resource attributes in metadata.yaml, but use resource attribute "hardcoded" in scraper code instead. We need to establish an approach and probably separate the resource attributes from other metric attributes.

## Proposal

We can introduce another field in metadata.yaml to specify resource attributes. mdatagen should generate them into a new struct variable `ResourceAttributes` with alias `RA` keeping existing `Attributes` with `A` alias for metric attributes.

The field can be added to the metadata.yaml in the following format:

```yaml
resource_attributes:
  <attribute_name>:
    # Optional description
    description: ...
    # Actual attribute string, if not provided `<attribute_name>` used instead, optional.
    value: state
    # Use a variable from `semconv` package instead of defining new attribute name,
    # e.g. "v1.8.0/AttributeCloudAccountID", optional.
    semconv: 
```

Besides generating `ResourceAttributes` struct that should be used in scraper code, the updated the new `resource_attributes` field should be used to generate additional documentation for the scraper. Potentially, if `resource_attributes::semconv` is set in metadata.yaml, we can also parse the semconv docstrings and auto-generate metric documentation from auto-generated semconv code :)

Action items:
- [x] Introduce resource attributes in metadata.yaml and generate helpers from it
- [ ] #8840
- [x] #8841
- [x] #16373
- [ ] #19174
