### ISSUE TITLE
Google Cloud PubSub traces do not show up

### ISSUE THREAD

**Issue by jessberg** [open-telemetry/opentelemetry-collector-contrib#7377]
**Describe the bug**
I have set up the extension for Google PubSub.  No traces appear in the PubSub topic despite enabling the PubSub exporter.

**Steps to reproduce**
I ran this using the application in cloud-ops-sandbox [Online Boutique](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox).  I edited the manifests to deploy the collector in two ways:
1. I changed the version of the agent's image to otel/opentelemetry-collector-contrib:latest. 
2. I changed the version of the collector's image to otel/opentelemetry-collector-contrib:latest and added the command         "/otelcontribcol" to the gateway to match the examples here.  I also added the pubsub to the pipeline through
```
 googlecloudpubsub:
      googlecloudpubsub/dyntrace:
        project: dynamic-tracing
        endpoint: test-endpoint
        user_agent: opentelemetry-collector-contrib:0.42.0
        insecure: true
        timeout: 20s
        topic: projects/dynamic-tracing/topics/otlp-topic
```
and googlecloudpubsub/dyntrace to the exporters.  The full YAML to reproduce and deploy the collector is below.

**What did you expect to see?**
I expected the traces to be exported to my PubSub topic.

**What did you see instead?**
No traces appear in the PubSub topic despite enabling the PubSub exporter.  However, tracing appears in logs and Google Trace, my other two exporters.  So I believe the collector is functional in general, and it is just this exporter that isn't working.

**What version did you use?**
Version: latest

**What config did you use?**
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrycollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetrycollector
  template:
    metadata:
      labels:
        app: opentelemetrycollector
    spec:
      # Init container retrieves the current cloud project id from the metadata server
      # and inserts it into the collector config template
      # https://cloud.google.com/compute/docs/storing-retrieving-metadata
      initContainers:
      - name: otel-gateway-init
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:326.0.0-alpine
        command:
        - '/bin/bash'
        - '-c'
        - |
           sed "s/{{PROJECT_ID}}/$(curl -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/project/project-id)/" /template/collector-gateway-config-template.yaml >> /conf/collector-gateway-config.yaml
        volumeMounts:
        - name: collector-gateway-config-template
          mountPath: /template
        - name: collector-gateway-config
          mountPath: /conf
      containers:
      # This gateway container will receive trace information from one or more microservices
      # and forward it to Cloud Trace
      - name: otel-gateway
        command:
        - "/otelcontribcol"
        - --config=/conf/collector-gateway-config.yaml
        image: otel/opentelemetry-collector-contrib:latest
        volumeMounts:
        - name: collector-gateway-config
          mountPath: /conf
      volumes:
      # Simple ConfigMap volume with template file
      - name: collector-gateway-config-template
        configMap:
          items:
          - key: collector-gateway-config-template.yaml
            path: collector-gateway-config-template.yaml
          name: collector-gateway-config-template
      # Create a volume to store the expanded template (with correct cloud project ID)
      - name: collector-gateway-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app: opentelemetrycollector
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-gateway-config-template
# Open Telemetry Collector config
# https://opentelemetry.io/docs/collector/configuration/
data:
  collector-gateway-config-template.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
    exporters:
      googlecloud:
        project: {{PROJECT_ID}}
      logging:
      googlecloudpubsub:
      googlecloudpubsub/dyntrace:
        project: dynamic-tracing
        endpoint: test-endpoint
        user_agent: opentelemetry-collector-contrib:0.42.0
        insecure: true
        timeout: 20s
        topic: projects/dynamic-tracing/topics/otlp-topic
    service:
      pipelines:
        traces:
          receivers: [otlp] # Receive otlp-formatted data from other collector instances
          processors: []
          exporters: [googlecloud, logging, googlecloudpubsub/dyntrace] # Export directly to Google Cloud
```

**Environment**
I ran this on Google Cloud Platform.

**Additional Context**
The collector container has no errors in its logs.  I know it is finding the extension, because before I updated versions I got extension not found errors, and those are now gone.  I haven't found any useful information through combing through the events or logs of the container.
