### ISSUE TITLE
Kubernetes example always uses default configuration even if supplied config is different

### ISSUE THREAD

**Issue by 163a** [open-telemetry/opentelemetry-collector-contrib#7404]
**Describe the bug**
Newer releases ignore custom configuration when launched on Kubernetes.

**Steps to reproduce**
1. Clone repo and use https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/kubernetes
2. Change the ConfigMap in kubernetes to another config content within otel-collector.yaml
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/kubernetes/otel-collector.yaml
(In this case, adding dynatrace exporter and removing some other config from default demo setup)
3. Applied this to namespace in Kubernetes.
`kubectl create ns otel`
`kubectl -n otel apply -f ./otel-collector.yaml`

**What did you expect to see?**
* Launch otel collector using custom configuration (having edited the contents of the config).
* Metrics reach `dynatrace` endpoint.

**What did you see instead?**
* `dynatrace` exporter never appeared.
* Appeared default demo config using logging receiver, zipkin, etc. was in place, as they appeared in logs.

**What version did you use?**
Version: `v0.43.0`, `v0.42.0`, `v0.39.0`, `v0.38.0`

Switching to `v0.36.0` image resolves the issue

**What config did you use?**
Config:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: [ '0.0.0.0:8888' ]
    processors:
      batch:
       # Batch size must be less than or equal to 1000
       send_batch_size: 200
       send_batch_max_size: 1000
       timeout: 30s
    exporters:
      dynatrace:
       # optional - Dimensions specified here will be included as a dimension on every exported metric
       #            unless that metric already has a dimension with the same key.
       default_dimensions:
         otel_collector: kubernetes_demoapps
       # optional - prefix will be prepended to each metric name in prefix.name format
       prefix: a1_spanner_otel
       endpoint: https://abcd12345.live.dynatrace.com/api/v2/metrics/ingest
       # Token must at least have the Ingest metrics (metrics.ingest) permission
       api_token: dt0c01.ABC.123
      logging:
       loglevel: debug
    service:
      pipelines:
        metrics:
         receivers: [prometheus, otlp]
         processors: [batch]
         exporters: [dynatrace, logging]
      telemetry:
        logs:
          level: "debug"
```

**Environment**
Kubernetes: v1.21 , v1.20

**Additional context**
* Fixed with change to image version and specify config arg
* Specifying config arg on newer versions seems to be ignored / result in CrashLoopBackOff

Snippet of otel-collector.yaml
```
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        args: ["--config", "/etc/otel/config.yaml"]
        image: otel/opentelemetry-collector-contrib:0.36.0
```
