### ISSUE TITLE
Datadog exporter sending EC2 hostname for containers in AWS ECS Fargate

### ISSUE THREAD

**Issue by austindrenski** [open-telemetry/opentelemetry-collector-contrib#7414]
**Describe the bug**

Datadog is showing an ECS Fargate container running the OTel Collector (contrib) as a normal host with an EC2 hostname, rather than displaying it like other containers in our cloud infrastructure that are running/deployed with the Datadog Agent.

I think this might be caused by an ordinal string comparison between the OTel convention's `fargate` and the ECS task metadata's `FARGATE`. 

- [Task Metadata Endpoint V4 (Fargate) uses `"LaunchType": "FARGATE"` in the examples](https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html#task-metadata-endpoint-v4-fargate-examples) 

-  [`model/semconv/v1.5.0/resource.go#L152-L157`](https://github.com/open-telemetry/opentelemetry-collector/blob/32301d929b413918efeefc1d9a1165b03ac71988/model/semconv/v1.5.0/resource.go#L152-L157):
   ```go
   const (
   	// ec2
   	AttributeAWSECSLaunchtypeEC2 = "ec2"
   	// fargate
   	AttributeAWSECSLaunchtypeFargate = "fargate"
   )
   ```

- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/83f5ea17ca05cd541de0e02ec9ff9b626f0678e3/exporter/datadogexporter/internal/attributes/hostname.go#L84-L87

**Steps to reproduce**

- Deploy `otel/opentelemetry-collector-contrib:latest` to AWS ECS Fargate
- Check https://app.datadoghq.com/infrastructure

**What did you expect to see?**

- Starting an OTel Collector in ECS Fargate appears as a container in Datadog.

**What did you see instead?**

- The OTel Collector appears in the infrastructure list with an EC2 hostname.

**What version did you use?**

- ```
  otel/opentelemetry-collector-contrib:latest
  DIGEST:sha256:d34519458388e55a3fce38a33e6bc424267c1f432927c09e932ba45f7575bd84
  ```

**What config did you use?**

- ```yml
  receivers:
    awsecscontainermetrics:

  processors:
    batch:

  exporters:
    datadog:
      env: "${DD_ENV}"
      api:
        key: "${DD_API_KEY}"

  service:
    pipelines:
      metrics:
        receivers: [ awsecscontainermetrics ]
        processors: [ batch ]
        exporters: [ datadog ]
  ```

**Environment**

- ECS Fargate

**Additional context**

- _Long time listener, first time caller. Thanks for all the work you've all put into this. It's an exciting time to be working with telemetry._

**Comment by jpkrohling** [comment]
Not sure where the problem is, so, I'm copying AWS and Datadog folks: @anuraaga, @KSerrania @mx-psi @gbbr @knusbaum

**Comment by mx-psi** [comment]
Thanks for opening the issue @austindrenski and thanks for the ping @jpkrohling. 

It looks like the `awsecscontainermetrics` uses a non-standard attribute name for the launchtype. [`aws.ecs.task.launch_type`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/d38704ef5f786fa0edb87befa2a8c0bf619cbb0c/receiver/awsecscontainermetricsreceiver/internal/awsecscontainermetrics/constant.go#L29) instead of the OpenTelemetry semantic convention `aws.ecs.launchtype`, so the Datadog exporter won't recognize this attribute. For this semantic convention, the attribute must be lowercase 'fargate' [according to the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/resource/semantic_conventions/cloud_provider/aws/ecs.md), so I think the Datadog exporter code is correct.

I will look into opening a PR to fix this on the `awsecscontainermetrics` component. 

Also, if all your metrics come from ECS Fargate (and pretty much on every other setting), you may be interested in using the `resourcedetection` processor. A full example with our recommended configuration (works on every major cloud vendor) is:

```
receivers:
  awsecscontainermetrics:

processors:
  batch:
  resourcedetection:
    detectors: [gce, ecs, ec2, azure, system] 

exporters:
  datadog:
    env: "${DD_ENV}"
    api:
      key: "${DD_API_KEY}"

service:
  pipelines:
    metrics:
      receivers: [ awsecscontainermetrics ]
      processors: [ batch, resourcedetection ]
      exporters: [ datadog ]
```

I am not familiar with the metrics produce by `awsecscontainermetrics`, but depending on their origin, you may need to tweak the `override` flag on the `resourcedetection` processor.

**Comment by mx-psi** [comment]
Opened #7425 to add the semantic conventions on `awsecscontainermetricsreceiver`.

**Comment by mx-psi** [comment]
@austindrenski did you have a chance to try out v0.44 and/or the resourcedetection processor?

**Comment by austindrenski** [comment]
@mx-psi Thanks for getting this patched and released so quickly! 

_note: I'm linking various Datadog pages below to clarify where I am or am not seeing things behind the auth wall. Recognize that no one else is going to be able to see what I'm seeing, but figure the page links might help to repro on your end._

I was able to update to `v0.44` today and run deploy a couple of tests this week with various configurations of the `resourcedetection` processor, but I'm still haven't been able to get the containers to show up in Datadog.

The good news is that our ECS containers are no longer being detected as EC2 instances and no longer appear in the [Datadog infrastructure list](https://app.datadoghq.com/infrastructure). It also looks like our [plan and usage](https://app.datadoghq.com/billing/usage) page now reflects fewer host instances, which is ___very___ welcome news.

Unfortunately, however, those ECS containers have not appeared in the [Datadog containers list](https://app.datadoghq.com/containers).

We have other ECS containers deployed with Datadog Agent images that _do appear_ in the containers list, which seems to suggest that the OTel exporter is omitting or missetting some attribute, relative to what's being sent from the Datadog Agent.

It's also possible that I've misconfigured something silly, but I've run out of ideas on what to tweak next, so hoping you might be able to provide some insight on where I've gone wrong... Any thoughts?

___

For reference, see below for our current `config.yaml`. I've also tested `detectors: [ ecs, ec2, system ]` in case some EC2 metadata was also needed, but it made no difference in the containers list.

```yaml
receivers:
  awsecscontainermetrics:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  resourcedetection:
    detectors: [ ecs ]

exporters:
  datadog:
    env: "${DD_ENV}"
    api:
      key: "${DD_API_KEY}"

service:
  pipelines:
    metrics:
      receivers: [ awsecscontainermetrics, otlp ]
      processors: [ batch, resourcedetection ]
      exporters: [ datadog ]
    traces:
      receivers: [ otlp ]
      processors: [ batch, resourcedetection ]
      exporters: [ datadog ]
```

___

Additionally, I'm attaching two screencaps below that show the [`Infrastructure` and `Metrics` tabs for a trace](https://app.datadoghq.com/apm/traces) from one of our ECS containers deployed with the OTel contrib collector (`v0.44`).

It seems like Datadog recognizes that this trace originated from an ECS container, but it doesn't seem to make the association to any container metrics or dashboards.

![trace-infrastructure-tab-redacted](https://user-images.githubusercontent.com/21338699/153681858-7a2b21e8-5502-4736-b4f6-9639684115ac.png)

![trace-metrics-tab-redacted](https://user-images.githubusercontent.com/21338699/153681873-ea22ea38-08dd-47e5-a74e-525a45508394.png)
