### ISSUE TITLE
[receiver/mysql] Data model issues

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector-contrib#7511]
Several metrics appear to have minor data modeling problems. Notably:
- `buffer_pool_pages` and `buffer_pool_size` have enumerated labels that include "total" and subtotals. The totals should be separate metrics.
- `buffer_pool_pages`, `buffer_pool_size`, and `threads` are modeled as doubles, though the values appear to be ints.

**Comment by djaglowski** [comment]
Capturing some findings here on `buffer_pool_pages` and `buffer_pool_size`.

#### `buffer_pool_pages`

Currently modeled as:
```yaml
# metric definition
mysql.buffer_pool_pages:
    enabled: true
    description: The number of pages in the InnoDB buffer pool.
    unit: 1
    sum:
      value_type: double
      monotonic: false
      aggregation: cumulative
    attributes: [buffer_pool_pages]

# attribute definition
buffer_pool_pages:
    value: kind
    description: The buffer pool pages types.
    enum: [data, dirty, flushed, free, misc, total]
```

There are several problems with the six labels:
1. It's clear that `total` should not be included in the same set as other values, which would presumably be subtotals.
2. In the definition of [misc](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_pages_misc), we see the formula `misc = total - free - data` This is equivalent to `misc + free + data = total`. Therefore, we should have a metric that has only these three labels, and this exactly sums to the value currently captured as `total`.
3. In the definition of [data](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_pages_data), we see the formula `data = dirty + clean`. Therefore, there is overlap between `data` and `dirty`. We can resolve this by having a new metric that has labels `dirty` and `clean`, which sum together to represent `data`. `clean` will have to be derived using the formula `total - dirty = clean`.
4. `flushed` appears to be a monotonic counter that tracks flush requests. Therefore this should be a separate metric.

This gives us three separate metrics, roughly modeled as:
```yaml
pages: 
  attribute values: [data, free, misc]
  data type: non-monotonic
data_pages: 
  attribute values: [dirty, clean]
  data type: non-monotonic
page_flushes:
  data type: monotonic
```

#### `buffer_pool_size`

Currently modeled as:
```yaml
  mysql.buffer_pool_size:
    enabled: true
    description: The number of bytes in the InnoDB buffer pool.
    unit: By
    sum:
      value_type: double
      monotonic: false
      aggregation: cumulative
    attributes: [buffer_pool_size]

# attribute definition
buffer_pool_size:
    value: kind
    description: The buffer pool size types.
    enum: [data, dirty, total]
```

1. The `total` [buffer pool size](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_buffer_pool_size) is actually a configuration setting. However, it can be configured to dynamically adjust. This blurs the line a bit, but I believe this could arguably be modeled as a `limit` metric.
2. Similar to pages, the [data](https://dev.mysql.com/doc/refman/8.0/en/server-status-variables.html#statvar_Innodb_buffer_pool_bytes_data) value represents `dirty + clean` bytes. This should be a separate metric, with possible attribute values `dirty` and `clean`, which sum to represent `data`.

This gives us two separate metrics, roughly modeled as:
```yaml
size.limit: 
  data type: non-monotonic
data_size.usage: 
  attribute values: [dirty, clean]
  data type: non-monotonic
```
