### ISSUE TITLE
New component: OpenTSDB Exporter

### ISSUE THREAD

**Issue by foxlegend** [open-telemetry/opentelemetry-collector-contrib#7535]
## The purpose and use-cases of the new component
OpenTSDB Exporter sends data to an [OpenTSDB](http://opentsdb.net/) time series database via the OpenTSDB [HTTP API](http://opentsdb.net/docs/build/html/api_http/index.html).

For information, this is complementary of New component proposal #7534. I already started to develop this component here: https://github.com/foxlegend/opentelemetry-collector-opentsdb-contrib.

## Example configuration for the component
Example:

```
exporters:
  opentsdb:
    endpoint: http://localhost:4242/api/put
    batch_size: 25
    skip_tags:
      - scheme
      - port
      - service.name
```
The following settings are configurable:
* `endpoint`: the server to which the collector is going to send data,
* `batch_size`: the number of metrics to send to the database per request (opentsdb is configured to accept a limited number of bytes per request),
* `skip_tags`: tags to skip, as OpenTSDB requires to use as few tags as possible (maximum 8 by default).

## Telemetry data types supported
Supported pipeline type: metrics
