### ISSUE TITLE
SumoLogic exporter panics

### ISSUE THREAD

**Issue by okashansky-mdsol** [open-telemetry/opentelemetry-collector-contrib#7548]
**Describe the bug**
SumoLogic exporter panicked processing malformed histogram.

**Steps to reproduce**
Run a collector with the attached configuration file providing a target that exposes histogram metrics. Wait 1 minute, then stop the target.

**What did you expect to see?**
The collector is working, (optionally) SumoLogic exporter puts an error message in the log. 

**What did you see instead?**
The collector crashed. Exception "runtime error: index out of range [0] with length 0" here: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/60e2b7313b96f0898cb6e6a3aa7263f08efc2144/exporter/sumologicexporter/prometheus_formatter.go#L299

**What version did you use?**
Versions: 0.41.0, 0.42.0, 0.43.0

**What config did you use?**
Config: 
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: job
          scrape_interval: 5s
          static_configs:
            - targets: [localhost:9991]

exporters:
  sumologic:
    endpoint: http://localhost:9991/exporter
    compress_encoding: gzip
    max_request_body_size: 1048576
    log_format: json
    metric_format: prometheus
    source_category: ignore-it
    source_name: local
    source_host: local-scraper

service:
  telemetry:
    logs:
      level: debug
      development: true
      encoding: json
  extensions: []
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [sumologic]
```

**Environment**
OS:  Ubuntu 20.04

**Additional context**
The exporter does not break the histogram, but its panic crashes the collector.
![2022-02-03 13_57_12-](https://user-images.githubusercontent.com/67710973/152425948-b06a8214-f901-47e0-9b38-85dc415372c7.png)
![2022-02-03 14_04_05-panic go - heimdall  WSL_ Ubuntu  - Visual Studio Code](https://user-images.githubusercontent.com/67710973/152425977-9510fd98-e8b2-4d29-a932-52d39dd3a1b5.png)
