### ISSUE TITLE
Feature Request: include/exclude rules based matching for RoutingProcessor

### ISSUE THREAD

**Issue by william-tran** [open-telemetry/opentelemetry-collector-contrib#7561]
**Is your feature request related to a problem? Please describe.**

I want to route logs/metrics/spans to different exporters. The [matching](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.43.0/processor/attributesprocessor#includeexclude-filtering) support for each of these types is expressive enough, but the current routing processor can only use http headers and resource attributes.

**Describe the solution you'd like**

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  routingrules:
    # the first matching rule is used
    rules:
      # send high priority telemetry to a different tier
      - include:
          # for options see https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.43.0/processor/attributesprocessor#includeexclude-filtering
        exporters: [otlp/guaranteed]
      # drop noise with an empty exporters list
      - include:
          # ...
        exporters: []
    # otherwise send things here
    default_exporters: [otlp/besteffort]

exporters:
  otlp/guaranteed:
    endpoint: otelcol1:4317
  otlp/besteffort:
    endpoint: otelcol2:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [routingrules]
      exporters: [otlp/guaranteed, otlp/besteffort]
```

**Describe alternatives you've considered**

- using attributes -> groupbyattrs -> routing as in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7407#issuecomment-1029353509, but ~the current routing processor doesn't use resource attributes and~ it pollutes the Resource concept
- using filterprocessor as in https://github.com/open-telemetry/opentelemetry-collector/issues/2310, but it doesn't support spans, and I want to evaluate rules in order and use the first matching rule, rather than fan out to multiple filters and then carefully play with those to ensure mutual exclusivity.

**Additional context**

We use want to route telemetry through different pipelines that provide different QoS. @jpkrohling, what are your thoughts, as you've been involved in both discussions above?
