### ISSUE TITLE
exporter/dynatrace has invalid keys: insecure_skip_verify

### ISSUE THREAD

**Issue by qgervacio** [open-telemetry/opentelemetry-collector-contrib#7566]
**Describe the bug**
The doc mentioned field `insecure_skip_verify` in https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/dynatraceexporter but when used the following error is thrown

```
aws-otel-eks-ci-vgzfc 2022/02/04 14:59:50 application run finished with error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "dynatrace/blackbox": 1 error(s) decoding: 
aws-otel-eks-ci-vgzfc * '' has invalid keys: insecure_skip_verify
```

**Steps to reproduce**
create a config with `insecure_skip_verify`

```
dynatrace/blackbox:
    endpoint: https://xxx/api/v2/metrics/ingest
    api_token: xxx
    insecure_skip_verify: true
```

**What did you expect to see?**
Expected the minimal config to pass

**What did you see instead?**
`has invalid keys: insecure_skip_verify`

**What version did you use?**
Version: tag/v0.43.1 via https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.16.0

**What config did you use?**
```
dynatrace/blackbox:
    endpoint: https://xxx/api/v2/metrics/ingest
    api_token: xxx
    insecure_skip_verify: true
```

**Environment**
eks

**Additional context**
None

**Comment by jpkrohling** [comment]
cc @dyladan @arminru

**Comment by dyladan** [comment]
I'm out until Monday but I've put this on my list

**Comment by arminru** [comment]
Thanks for reporting this @qgervacio!

The collector-wide HTTP/TLS config struct was restructured a while ago but apparently it was forgotten to reflect this in the docs.
We'll make sure to update them.

In recent version you need to nest the flag in a `tls:` section like this:
```
dynatrace/blackbox:
    endpoint: https://xxx/api/v2/metrics/ingest
    api_token: xxx
    tls:
        insecure_skip_verify: true
```
More details can be found here: https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md#client-configuration

@jpkrohling are docs/readme fixes like these usually backported or should it be enough to just fix it on main?
