### ISSUE TITLE
[exporter/datadog] DD Exporter not registering Otel tags for all targets in prometheus scrape config

### ISSUE THREAD

**Issue by ikhan-tc** [open-telemetry/opentelemetry-collector-contrib#7578]
**Describe the bug**
DD Exporter not sending host metadata for all hosts configured in prometheus receiver. 

**Steps to reproduce**
1. Configure prometheus receiver scrape config with multiple static hosts.
2. Add custom tag like `app:opentelemetry` in otel-collector-config `tags` section.
3. Filter the hosts in Datadog UI with tag `app:opentelemetry`

**What did you expect to see?**
Datadog UI should list all targets configured in prometheus receiver

**What did you see instead?**
one or two targets. not all the targets.

**What version did you use?**
Version:0.43.0

**What config did you use?**
Config: 
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "node-exporter"
          scrape_interval: 10s
          scrape_timeout: 5s
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
              - "node-exporter1:9100"
              - "node-exporter2:9100"
              - "node-exporter3:9100"

exporters:

  datadog:
    env: dev
    tags:
      - app:opentelemetry

processors:
 batch:
   timeout: 10s


service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [datadog]
```

**Comment by mx-psi** [comment]
Hi @ikhan-tc thanks for taking the time to open the issue. 

As I briefly commented (https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/7570#pullrequestreview-877127151) on your PR, the `tags` field in the Datadog exporter is sent in a different payload from the timeseries of a metric. I believe the problem here is that this payload that sends the tags is being sent after the timeseries payloads of some of your Prometheus metrics. This should not happen always, but be a rather unusual occurrence. Are you able to reproduce this consistently?

As a work around until this is fixed, you can use the `metricstransform` processor to add the labels as attributes. For example here is a configuration that should produce the same results as your example configuration:

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "node-exporter"
          scrape_interval: 10s
          scrape_timeout: 5s
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
              - "node-exporter1:9100"
              - "node-exporter2:9100"
              - "node-exporter3:9100"

exporters:
  datadog:
    env: dev
    api:
      key: <API key goes here>

processors:
 batch:
   timeout: 10s

  metricstransform:
    transforms:
      - include: '.*' # match all metrics
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: app
            new_value: opentelemetry
            # add further 'action: add_label' here to add more tags.
            # labels are added as tags to metrics with a 'label:value' format.

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch, metricstransform]
      exporters: [datadog]
```
