### ISSUE TITLE
AttributeProcessor 'from_context' does not extract from gRPC metadata

### ISSUE THREAD

**Issue by roybh1** [open-telemetry/opentelemetry-collector-contrib#7583]
**Describe the bug**
Extracting a field from gRPC metadata to add to spans attributes using AttributeProcessor's 'from_context' does not work

**Steps to reproduce**
Using metadata.set as described [here](https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/exporter-trace-otlp-grpc) 

```
function otlpGrpcSpanFactory(options: Options): SpanExporter {
  const metadata = new Metadata();
  metadata.set('SOME_HEADER', SOME_VALUE);

  const collectorOptions = {
    url: SOME_URL
    metadata,
  };

  return new GRPCTraceExporter(collectorOptions);
}
```

and sending to a collector (gRPC) of the latest commit with config:
```
receivers:
  otlp:
    protocols:
      grpc:

processors:
  attributes:
    actions:
      - key: SOME_KEY
        action: insert
        from_context: "some_header"
      - key: test_key
        action: insert
        value: "VALUE"

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [logging]
```

**What did you expect to see?**
Expected to see both SOME_KEY and test_key in the span attributes

**What did you see instead?**
![image](https://user-images.githubusercontent.com/32637910/152676093-5529146d-eec3-4326-b7a7-47f3a06727e6.png)

**What version did you use?**
Version: 'e794616815bd9a145503f87078a623d6e2908e2d'

**Environment**
OS: OSX Monterey
compiled locally using makefile

**Additional context**
I am no expert in Golang, but trying to print the Metadata object here: (https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/internal/coreinternal/attraction/attraction.go)
![image](https://user-images.githubusercontent.com/32637910/152676334-60e07a41-a9bb-42df-9751-bd644d4aaeee.png)

showed an empty object

EDIT:
I have use the grpc/metadata library and it worked
![image](https://user-images.githubusercontent.com/32637910/152679497-9b375733-1982-4cd0-b646-c614914a7c44.png)

**Comment by jpkrohling** [comment]
On your receiver, make sure to specify that you do want to propagate the metadata down the pipeline within the context:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
```

https://github.com/open-telemetry/opentelemetry-collector/blob/7dcc512f268a67c0482c0fb69d82c565a0480a50/config/configgrpc/configgrpc.go#L157-L159

Feel free to reopen if this doesn't solve your problem.
