### ISSUE TITLE
The `scrape_timeout` option is mandatory for `prometheus_exec`

### ISSUE THREAD

**Issue by xp-1000** [open-telemetry/opentelemetry-collector-contrib#7586]
**Describe the bug**
Since https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6159 merged, the new `scrape_timeout` is available. However, it is mandatory so it breaks any existing configuration (which obviously do not define this field which did not exist before).
I think it concerns versions >= 0.42.0 but I did not see this breaking change in release notes: https://github.com/open-telemetry/opentelemetry-collector-contrib/releases

**Steps to reproduce**
configure prometheuesexec receiver without `scrape_timeout` option

**What did you expect to see?**
Keep the old hardcoded (10s) value as default to prevent breaking change

**What did you see instead?**
Error:
```
2022-02-07T11:56:48.766+0100    error   scrape/scrape.go:477    Creating target failed  {"kind": "receiver", "name": "prometheus_exec/wallix", "scrape_pool": "wallix", "error": "instance 0 in group : scrape timeout cannot be 0", "errorVerbose": "scrape timeout cannot be 0\ngithub.com/prometheus/prometheus/scrape.PopulateLabels\n\t/home/qmanfroi/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220117154355-4855a0c067e2/scrape/target.go:436\ngithub.com/prometheus/prometheus/scrape.TargetsFromGroup\n\t/home/qmanfroi/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220117154355-4855a0c067e2/scrape/target.go:485\ngithub.com/prometheus/prometheus/scrape.(*scrapePool).Sync\n\t/home/qmanfroi/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220117154355-4855a0c067e2/scrape/scrape.go:475\ngithub.com/prometheus/prometheus/scrape.(*Manager).reload.func1\n\t/home/qmanfroi/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220117154355-4855a0c067e2/scrape/manager.go:205\nruntime.goexit\n\t/usr/lib/go/src/runtime/asm_amd64.s:1581\ninstance 0 in group \ngithub.com/prometheus/prometheus/scrape.TargetsFromGroup\n\t/home/qmanfroi/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220117154355-4855a0c067e2/scrape/target.go:487\ngithub.com/prometheus/prometheus/scrape.(*scrapePool).Sync\n\t/home/qmanfroi/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220117154355-4855a0c067e2/scrape/scrape.go:475\ngithub.com/prometheus/prometheus/scrape.(*Manager).reload.func1\n\t/home/qmanfroi/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20220117154355-4855a0c067e2/scrape/manager.go:205\nruntime.goexit\n\t/usr/lib/go/src/runtime/asm_amd64.s:1581"}
```

**What version did you use?**
v0.43.0

**What config did you use?**
Config:
```yaml
receivers:
  # we configure the new component in its corresponding section (receivers here)
  prometheus_exec/wallix:
    exec: wallix_bastion_exporter/wallix_bastion_exporter -p toto -u tata
    port: 9191
    scrape_interval: 300s
exporters:
  file:
    path: /tmp/otel
service:
  pipelines:
    metrics:
      # we add it to the metrics pipeline to enable it
      receivers: [prometheus_exec/wallix]
      exporters: [file]
```
