### ISSUE TITLE
[processor/tailsampling] and policy does not work outside of composite blocks

### ISSUE THREAD

**Issue by SquidDev** [open-telemetry/opentelemetry-collector-contrib#7589]
**Describe the bug**
I just updated to the latest commit with the intent of playing with the tailsampler's new AND polity (#6802). However, it appears the sampler is only supported within a composite sampler. From what I can tell, the `And` case only appears within the composite parser: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e182f5222c42cd35103ff4699706f2f641fe5b9b/processor/tailsamplingprocessor/composite_helper.go#L80-L81 and not in the top level one: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/e182f5222c42cd35103ff4699706f2f641fe5b9b/processor/tailsamplingprocessor/processor.go#L117-L145

**Steps to reproduce**
 - Build the latest commit (e182f5222c42cd35103ff4699706f2f641fe5b9b)
 - Copy the config attached below and save it
 - Run `bin/otelcontribcol_linux_amd64 --config otel-config.yaml` 

**What did you expect to see?**
I would expect the config to be accepted. Alternatively, the documentation should mention that this is only expected within a composite block (though this would be surprising).

**What did you see instead?**
Instead, the config is rejected with the following error:

```
2022-02-07T14:23:57.475Z        info    builder/exporters_builder.go:255        Exporter was built.     {"kind": "exporter", "name": "logging"}
Error: cannot build pipelines: error creating processor "tail_sampling" in pipeline "traces": unknown sampling policy type and
2022/02/07 14:23:57 collector server run finished with error: cannot build pipelines: error creating processor "tail_sampling" in pipeline "traces": unknown sampling policy type and
```

**What version did you use?**
Version: e182f5222c42cd35103ff4699706f2f641fe5b9b

**What config did you use?**

<details>
<summary>otel-config.yaml</summary>

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug

processors:
  batch:

  tail_sampling:
    decision_wait: 10s
    policies:
    - name: and_example
      type: and
      and:
        and_sub_policy:
        - name: is_a_service
          type: string_attribute
          string_attribute:
            key: service.name
            values: [some-service]

        - name: is_slow
          type: latency
          latency:
            threshold_ms: 1000

    - name: sample
      type: probabilistic
      probabilistic:
        sampling_percentage: 5

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling, batch]
      exporters: [logging]
```

</details>

**Environment**
OS: Fedora 35
Compiler(if manually compiled): go version go1.17.6 linux/amd64
