### ISSUE TITLE
Ability to strip headers for AWS Proxy

### ISSUE THREAD

**Issue by sukrit007wawa** [open-telemetry/opentelemetry-collector-contrib#7596]
**Is your feature request related to a problem? Please describe.**
If we deploy a istio (envoy) proxy in front of the collector,  the signing process fails because proxy sets x-forwarded-proto to 'http' causing a mismatch in the signing process.  

Similar to aws-sig4-proxy,  we need the ability to strip out or exclude headers from signing.  See https://github.com/awslabs/aws-sigv4-proxy#examples

**Describe the solution you'd like**
Ability to pass an environment variable/configuration to exclude headers that would include headers that needs to be removed when using awsproxy.  The default value of this configuration can include headers like x-forwarded-port,x-forwarded-proto

**Describe alternatives you've considered**
We are considering suppressing this header using envoy filters.

**Additional context**
To reproduce this issue,  you can simply exec inside otel-collector,  and run the curl command 
```
curl -X POST \
-H 'x-forwarded-proto: http' \
http://localhost:2000/GetSamplingRules
```

**Comment by jpkrohling** [comment]
cc @anuraaga @Aneurysm9 @mxiamxia

**Comment by sethAmazon** [comment]
Can you please put your collector config and logs

**Comment by rapphil** [comment]
This is still relevant

**Comment by jpkrohling** [comment]
@kovrus, do you think this would be suitable for the header setter?

**Comment by kovrus** [comment]
@jpkrohling It could be a good place to implement that, we can change the header setter config to look like the following:

```
extensions:
  headers_setter:
    headers:
      - key: <header>
        action: insert
        from_context: ...  
      - key: <header>
        action: insert
        value: ...
      - key: <header>
        action: drop    
```
