### ISSUE TITLE
AWS X-Ray Exporter is not recording error message

### ISSUE THREAD

**Issue by gautam-nutalapati** [open-telemetry/opentelemetry-collector-contrib#7781]
**Describe the bug**
I have [sample app](https://github.com/prisidio/opentelemetry-demo-app) that produces an exception, which is wrapped in otel custom span.
```
        Span s = span.startSpan();
        try {
            int i = 1 / 0;
        } catch (Exception e) {
            s.recordException(e);
        }
```
In AWS XRay, I do not see this error log for respective trace.

**Steps to reproduce**
- Create a custom span, and record an exception.
- Use awsxray exporter and check the specific trace data in XRay console
I created a sample app that can be used to reproduce this: [Link](https://github.com/prisidio/opentelemetry-demo-app) 

**What did you expect to see?**
Exception information in trace data. 
I used Jaeger exporter instead of awsxray, and I was able to see exception information in trace data.
<img width="2557" alt="Screen Shot 2022-02-09 at 5 13 28 PM" src="https://user-images.githubusercontent.com/81705313/153307475-02f89314-08ee-4bd0-a717-f13833ece8f5.png">

 
**What did you see instead?**
No exception information in trace data. Trace data: [Link](https://gist.github.com/gautam-nutalapati/b19c883deeb08a751d2b35b80b2b063a)

**What version did you use?**
Version: 0.44.0
(aws-otel-collector 0.16.0)

**What config did you use?**
```
extensions:
  health_check:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30

exporters:
  awsxray:
    region: "${AWS_REGION}"
service:
  telemetry:
    logs:
      level: "debug"
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch/traces]
      exporters: [awsxray]

```

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
