### ISSUE TITLE
Support write_relabel_configs for prometheusremotewrite exporter 

### ISSUE THREAD

**Issue by brianpham** [open-telemetry/opentelemetry-collector-contrib#7789]
**Is your feature request related to a problem? Please describe.**
We are seeing high cardinality for the instance label when using the kubernetes_sd_config. Instead of relabeling it, we want to just drop the label completely. We aren't able to do that in the relabel_configs as part of the scrape config, so we wanted to drop it before it pushes to prometheus in the pipeline. 

**Describe the solution you'd like**
Having some kind of configuration like this would work so it drops the instance label before pushing to Prometheus. 

```
write_relabel_configs:
  - action: labeldrop
      regex: 'instance'
```

**Describe alternatives you've considered**
We tested with the Grafana Agent and that seems to work but in our use case, we would need to use the OpenTelemetry Collector to send logs to Prometheus.

```
      remote_write:
        - url: <prometheus_url>
          basic_auth:
            username: <username>
            password: <grafana_token>
          write_relabel_configs:
            - action: labeldrop
              regex: 'instance'
```
 
**Additional context**
A little bit of background, we are running the workload on GKE. Our pipeline consist of otel-collector-agent scraping pods > otel-collector > remote Prometheus.
