### ISSUE TITLE
loadbalancing exporter is not sending span data to the back-end in a docker-compose setup

### ISSUE THREAD

**Issue by nasushkov** [open-telemetry/opentelemetry-collector-contrib#7910]
**Describe the bug**

I'm trying to make a proof of concept for a tail-based sampling solution, which is somewhat described [here](https://github.com/open-telemetry/opentelemetry-collector/issues/1724). I've built two distributions and placed each in a separate Docker image. One is built with the [load-balancing exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/loadbalancingexporter) and the other with the [tail-based sampling processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor). I test this setup locally with a simple _docker-compose_ file (described below).

I send spans to the load-balancing collector (UDP port 6832) and I see them exported as logging exporter shows. However, I don't see they are received by the tail-based sampling collector down the pipeline. What am I doing wrong here?

**Steps to reproduce**

- run the docker-compose file with _docker-compose up_  and send some spans. Navigate to _http://localhost:16686_ 
- send some spans to the endpoint

**What did you expect to see?**

Spans are shown in the Jeager UI

**What did you see instead?**

I don't see any spans and they were not received by the tail-sampling collector.

**What version did you use?**
Version: `v0.42.0`, `v0.43.0` for the tailsamplingprocessor

**What config did you use?**

Load balancer configuration:

```
receivers:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
        # endpoint: localhost:6831
      thrift_http:

processors:

exporters:
  logging:
    loglevel: debug
  loadbalancing:
    protocol:
      otlp:
        tls:
          insecure: true

    # how to get the list of backends: DNS
    resolver:
      dns:
        hostname: sampling-collector # assumes 4317 as the default port for the resolved IP addresses

service:
  pipelines:
    traces:
      receivers: [ jaeger ]
      processors: []
      exporters: [ logging, loadbalancing ]
```
Tail-based sampling configuration:

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  tail_sampling:
    decision_wait: 30s
    num_traces: 50000
    policies:
      [
        {
            name: composite-policy,
            type: composite,
            composite:
              {
                max_total_spans_per_second: 50000,
                policy_order: [error-catching-policy, latency-policy, test-composite-policy-3],
                composite_sub_policy:
                  [
                    {
                      name: error-catching-policy,
                      type: status_code,
                      status_code: {status_codes: [ERROR]}
                    },
                    {
                      name: latency-policy,
                      type: latency,
                      latency: {threshold_ms: 1000}
                    },
                    {
                      name: ab-test-policy,
                      type: string_attribute,
                      string_attribute: { key: ab-active, values: [true] }
                    },
                    {
                      name: default-policy,
                      type: always_sample
                    },
                  ],
                rate_allocation:
                  [
                    {
                      policy: error-catching-policy,
                      percent: 25
                    },
                    {
                      policy: latency-policy,
                      percent: 25
                    },
                    {
                      policy: ab-test-policy,
                      percent: 25
                    },
                    {
                      policy: default-policy,
                      percent: 25
                    }
                  ]
              }
          },
      ]

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ tail_sampling ]
      exporters: [ logging, jaeger ]
```
Here is my docker-compose file:

```
version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: on-failure
    ports:
      # http://localhost:16686
      - 16686:16686

  sampling-collector:
    build: ./sampling-collector
    volumes:
      - ./sampling-collector/config:/etc/otel:ro
    expose:
      - "80"
      - "443"
      - "4317" 
    depends_on:
      - jaeger
     
  load-balancer-collector:
    build: ./load-balancer-collector/.
    volumes:
      - ./load-balancer-collector/config:/etc/otel:ro
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp" 
      - "5778:5778"
      - "14268:14268"
      - "9411:9411"
    depends_on: 
      - sampling-collector
```

**Environment**
OS: macOS Big Sur (11.3.1)

**Additional context**

I use the following Dockerfile to build stuff:

```
ARG REGISTRY_URL=""
ARG GO_VERSION=1.17
ARG ALPINE_VERSION=3.14

FROM ${REGISTRY_URL}golang:${GO_VERSION}-alpine${ALPINE_VERSION} as build
RUN apk --no-cache add ca-certificates
RUN apk add make
RUN apk add build-base
WORKDIR /go/src/load-balancer-collector
COPY ./Makefile ./
COPY ./.otelcol-builder.yaml ./
RUN make build-prod

FROM scratch as bin
WORKDIR /load-balancer-collector
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /go/src/load-balancer-collector/dist/ ./

ENTRYPOINT [ "/load-balancer-collector/otelcol-lb"]
# Mount your config.yaml to /etc/otel/config.yaml
CMD ["--config", "/etc/otel/config.yaml"]
```
Makefile with a build-prod script:

```
.PHONY: init build build-prod clean

GOPATH := ${GOPATH}
GOPATH ?= ${HOME}/go 

init: 
	@GO111MODULE=on go install go.opentelemetry.io/collector/cmd/builder@latest	

build: init clean
	@$(GOPATH)/bin/builder --config=./.otelcol-builder.yaml --output-path=./dist --name=otelcol-lb

# We make sure that cgo is disabled, so the binary works with scratch image
build-prod: init clean
	@CGO_ENABLED=0 GOOS=linux $(GOPATH)/bin/builder --config=./.otelcol-builder.yaml --output-path=./dist --name=otelcol-lb

clean:
	@rm -rf ./dist
```

**Comment by jpkrohling** [comment]
Can you eliminate Docker from the equation? Most of the networking issues involving Docker are related to Docker itself, so, eliminating it would help ensure the problem is on the collector side.

You can use this as a reference: https://github.com/jpkrohling/opentelemetry-collector-deployment-patterns/tree/main/pattern-4-load-balancing

**Comment by jpkrohling** [comment]
Yes, you can use something like this in your configuration file, close to where the pipelines are defined:

```yaml
service:
  telemetry:
    metrics:
      address: ":8988"
```
