### ISSUE TITLE
EKS awsxray exporter don't work as expected

### ISSUE THREAD

**Issue by mihneastaub** [open-telemetry/opentelemetry-collector-contrib#7938]
**Describe the bug**
Hello Guys,

I'm using `opentelemetry-collector` version 0.44.0  in EKS Cluster with the receiver `opencensus` and exporter `awsxray`. The problem is that I don't see anything in the AWS X-RAY console and also I don't see any errors in the logs related to the exporter.

I want to highlight that the receiver is receiving data from the workloads, but the problem is when they are exported. Also, I have tested this also with Jager and is working.

**Steps to reproduce**
Deploy the kubernetes resources in the EKS cluster, please see below the resources that I'm using:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
  namespace: istio-system
  labels:
    app: opentelemetry-collector
data:
  config: |
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678

    processors:
      memory_limiter:
        limit_mib: 100
        spike_limit_mib: 10
        check_interval: 5s

    exporters:
      awsxray:
      awsxray/customname:
        region: "xxx"
      logging:
        loglevel: debug

    extensions:
      health_check:
        port: 13133

    service:
      extensions:
      - health_check
      pipelines:
        traces:
          receivers:
          - opencensus
          processors:
          - memory_limiter
          exporters:
          - awsxray
          - logging
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
  namespace: istio-system
  labels:
    app: opentelemetry-collector
spec:
  type: ClusterIP
  selector:
    app: opentelemetry-collector
  ports:
    - name: grpc-opencensus
      port: 55678
      protocol: TCP
      targetPort: 55678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-collector
  namespace: istio-system
  labels:
    app: opentelemetry-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      containers:
        - name: opentelemetry-collector
          image: "otel/opentelemetry-collector-contrib:0.44.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc-opencensus
              containerPort: 55678
              protocol: TCP
          volumeMounts:
            - name: opentelemetry-collector-config
              mountPath:  /etc/otelcol-contrib
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          resources:
            requests:
              cpu: 40m
              memory: 100Mi
      volumes:
        - name: opentelemetry-collector-config
          configMap:
            name: opentelemetry-collector
            items:
              - key: config
                path: config.yaml
```
**What did you expect to see?**
Should I see the tracing in the AWS X-RAY console.

**What did you see instead?**
I don't see anything in the AWS X-RAY console.

**What version did you use?**
Version: 0.44.0

**What config did you use?**
Config: 
```
  receivers:
    opencensus:
      endpoint: 0.0.0.0:55678

  processors:
    memory_limiter:
      limit_mib: 100
      spike_limit_mib: 10
      check_interval: 5s

  exporters:
    awsxray:
    awsxray/customname:
      region: "xxx"
    logging:
      loglevel: debug

  extensions:
    health_check:
      port: 13133

  service:
    extensions:
    - health_check
    pipelines:
      traces:
        receivers:
        - opencensus
        processors:
        - memory_limiter
        exporters:
        - awsxray
        - logging
```

**Environment**
Kubernetes version: 1.21
