### ISSUE TITLE
[prometheusreceiver] allow to pull Prometheus jobs from `/job` endpoint of the OpenTelemetryOperator-TargetAllocator

### ISSUE THREAD

**Issue by secustor** [open-telemetry/opentelemetry-collector-contrib#7944]
**Is your feature request related to a problem? Please describe.**
The TargetAllocator is component of a Collector deployment which allows to shard Prometheus targets on multiple Collector instances. 

To allow the Collector to dynamically discover new jobs the `/jobs` [endpoint](https://github.com/open-telemetry/opentelemetry-operator/blob/0a429a74a2895ba379fde5dfe2d67955e508e878/cmd/otel-allocator/README.md#endpoints) of the TargetAllocator should be used.   

**Describe the solution you'd like**
``` yaml
receivers:
    prometheus:
      target_allocator:
        endpoint:  http://my-targetallocator-service
        interval: 30s
        collector_id: ${COLLECTOR_ID}
# imported struct from the Prometheus code base. Can be used optionally to configure the jobs as seen in the docs 
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config
        http_sd_config: 
          basic_auth:
            username: prometheus
            password: changeme
```

With this configuration `prometheusreceiver` will scrape the `/job` endpoint every 30s to discover jobs.  

These jobs will be then used to generate a scrape configuration with a HTTP_SD job per returned job.     
Therefore if `/job` returns following JSON: 
``` json
{
  "job1": {
    "_link": "/jobs/job1/targets"
  },
  "job2": {
    "_link": "/jobs/job2/targets"
  }
}
```
This scrape config will be generated and then applied:
``` yaml
scrape_configs:
- job_name: job1
  http_sd_configs:
  - url: "http://my-targetallocator-service/jobs/job1/targets?collector_id=aCollector"
    basic_auth:
        username: prometheus
        password: changeme
- job_name: job2
  http_sd_configs:
  - url: "http://my-targetallocator-service/jobs/job2/targets?collector_id=aCollector"
    basic_auth:
        username: prometheus
        password: changeme

```
**Describe alternatives you've considered**
Some alternatives have been considered, these can be found in this issue: https://github.com/open-telemetry/opentelemetry-operator/issues/713
