### ISSUE TITLE
splunkhecexporter: Log record attributes ignored

### ISSUE THREAD

**Issue by rockb1017** [open-telemetry/opentelemetry-collector-contrib#7949]
**Describe the bug**
I cannot see the metadata (log record's attributes) when log is ingested to Splunk
I have logging exporter set up to cross check and I indeed see attributes. 

(Stdout print from logging exporter)
```
LogRecord #24
Timestamp: 2022-02-17 00:45:08.162251308 +0000 UTC
Severity: 
ShortName: 
Body: num: 157622 | loggen-dxvtq | 2022-02-17T00:45:08.162192 | rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

Attributes:
     -> stream: STRING(stdout)
     -> k8s.container.name: STRING(loggen)
     -> k8s.namespace.name: STRING(default)
     -> k8s.pod.name: STRING(loggen-dxvtq)
     -> k8s.pod.uid: STRING(bb7523b7-b23b-4b35-a538-6b70e79260e1)
     -> run_id: STRING(0)
Trace ID: 
Span ID: 
Flags: 0
```
(screenshot of what I see on Splunk)
![image](https://user-images.githubusercontent.com/12387289/154411366-bfd3e56a-b49c-4287-8ebe-7a3cafc06dbb.png)

**Steps to reproduce**
```
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    logs:
      exporters:
      - logging
      - splunk_hec
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
      - filelog
```

```
receivers:
  filelog:
    exclude:
    - /var/log/pods/default_otel-opentelemetry-collector*_*/opentelemetry-collector/*.log
    include:
    - /var/log/pods/*/*/*.log
    include_file_name: false
    include_file_path: true
    operators:
    - id: get-format
      routes:
      - expr: $$body matches "^\\{"
        output: parser-docker
      - expr: $$body matches "^[^ Z]+ "
        output: parser-crio
      - expr: $$body matches "^[^ Z]+Z"
        output: parser-containerd
      type: router
    - id: parser-crio
      output: extract_metadata_from_filepath
      regex: ^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$
      timestamp:
        layout: "2006-01-02T15:04:05.000000000-07:00"
        layout_type: gotime
        parse_from: time
      type: regex_parser
    - id: parser-containerd
      output: extract_metadata_from_filepath
      regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log>.*)$
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: time
      type: regex_parser
    - id: parser-docker
      output: extract_metadata_from_filepath
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: time
      type: json_parser
    - id: extract_metadata_from_filepath
      parse_from: $$attributes["file.path"]
      regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<run_id>\d+)\.log$
      type: regex_parser
    - attributes:
        k8s.container.name: EXPR($.container_name)
        k8s.namespace.name: EXPR($.namespace)
        k8s.pod.name: EXPR($.pod_name)
        k8s.pod.uid: EXPR($.uid)
        run_id: EXPR($.run_id)
        stream: EXPR($.stream)
      type: metadata
    - id: clean-up-log-body
      ops:
      - move:
          from: log
          to: $
      type: restructure
    start_at: beginning
```

```
exporters:
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200
  splunk_hec:
    disable_compression: true
    endpoint: https://X.X.X.X:8088/services/collector
    index: main
    max_connections: 2000
    source: otel
    sourcetype: otel
    timeout: 10s
    tls:
      insecure_skip_verify: true
    token: XXXX
```

**What version did you use?**
Version: `0.43.0`
Helm chart: https://github.com/open-telemetry/opentelemetry-helm-charts `0.9.1`

**Environment**
Kubernetes

**Additional context**
It used to work, but now I don't see any metadata.
