### ISSUE TITLE
New skywalking receiver for tracing data

### ISSUE THREAD

**Issue by JaredTan95** [open-telemetry/opentelemetry-collector-contrib#7954]
## The purpose and use-cases of the new component

Add this new receiver, we can receive the `apache/skywalking`'s tracing data, and convert it into `otlp` trace.

## Example configuration for the component

```yaml
receivers:
  skywalking:
    protocols:
      grpc:
  skywalking/withendpoint:
    protocols:
      grpc:
        endpoint: 0.0.0.0:11800
      http:
        endpoint: 0.0.0.0:12800
```

## Telemetry data types supported

support traces data first

## Sponsor (Optional)
no Sponsor for now.
