### ISSUE TITLE
prometheusreceiver upsert job to service.name

### ISSUE THREAD

**Issue by CoderPoet** [open-telemetry/opentelemetry-collector-contrib#8060]
**Describe the bug**
When using prometheusreceiver, if the user has declared service.name in resource attributes, it will be overridden by the job

**Steps to reproduce**

1. exporter some metrics with service.name resource attributes
![image](https://user-images.githubusercontent.com/19374680/155134660-bafa7dcf-4eb0-4018-ad65-8776cbe91fe2.png)

![image](https://user-images.githubusercontent.com/19374680/155134594-5e89b710-1b6d-4805-858f-319284005a5b.png)

2. use otel prometheusreceiver pull app metrics
<img width="235" alt="image" src="https://user-images.githubusercontent.com/19374680/155134521-11b7512f-45b4-4c86-81f0-10fed87a9c09.png">

**What did you expect to see?**
The service_name should be kafka-producer, not job

**What did you see instead?**
The service_name should is job value

**What version did you use?**
v0.45.1

**What config did you use?**
```yaml   exporters:
    extensions:
    processors:
    receivers:
      prometheus:
        config:
          global:
            evaluation_interval: 1m
            scrape_interval: 30s
            scrape_timeout: 10s
          scrape_configs:
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $$1:$$2
              source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: k8s_namespace_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: k8s_pod_name
            - action: drop
              regex: Pending|Succeeded|Failed
              source_labels:
              - __meta_kubernetes_pod_phase
            - source_labels:
              - __meta_kubernetes_service_name
              target_label: k8s_service_name
      zipkin: {}
    service:
      extensions:
      - health_check
      - pprof
      - zpages
      pipelines:
        metrics:
          exporters:
          processors:
          receivers:
          - prometheus
```

        
**Environment**
MacOs
go 17.6

**Additional context**
https://github.com/open-telemetry/opentelemetry-collector/pull/3139#discussion_r811756868

**Comment by Aneurysm9** [comment]
Setting the `job` label's value as `service.name` is [required by the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#resource-attributes).  The prometheus exporter to prometheus receiver pipeline cannot maintain the information that `service.name` (or any other resource attribute) was set as a resource attribute because the Prometheus exposition format does not provide a mechanism for distinguishing resource attributes from metric attributes.

Since you appear to be using the OTel Go SDK to generate these metrics, would it be possible to use the OTLP exporter and receiver?  Those components will properly distinguish between, and preserve, resource and metric attributes.

**Comment by CoderPoet** [comment]
> Setting the `job` label's value as `service.name` is [required by the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#resource-attributes). The prometheus exporter to prometheus receiver pipeline cannot maintain the information that `service.name` (or any other resource attribute) was set as a resource attribute because the Prometheus exposition format does not provide a mechanism for distinguishing resource attributes from metric attributes.
> 
> Since you appear to be using the OTel Go SDK to generate these metrics, would it be possible to use the OTLP exporter and receiver? Those components will properly distinguish between, and preserve, resource and metric attributes.

Thank you very much for your reply! But I'm thinking, since otel has opened up the prom way to expose the metrics, then this problem must exist and need to be solved, right? Is it necessary to rethink the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#resource-attributes)?

**Comment by CoderPoet** [comment]
> Setting the `job` label's value as `service.name` is [required by the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#resource-attributes). The prometheus exporter to prometheus receiver pipeline cannot maintain the information that `service.name` (or any other resource attribute) was set as a resource attribute because the Prometheus exposition format does not provide a mechanism for distinguishing resource attributes from metric attributes.
> 
> Since you appear to be using the OTel Go SDK to generate these metrics, would it be possible to use the OTLP exporter and receiver? Those components will properly distinguish between, and preserve, resource and metric attributes.

And my question is: prometheusreceiver set the value of the job to `service.name`, according to the specification should actually be the user-configured service name or target belongs to the service, right?
<img width="815" alt="image" src="https://user-images.githubusercontent.com/19374680/155258166-4add6baf-d7fc-4af0-bab9-5d5f1ff10a71.png">

**Comment by crobertson-conga** [comment]
I just ran into this.  It doesn't make sense that the service doing the scraping gets to rename the service if it is already set.  Especially if the endpoint is an aggregation of multiple services.  My specific use case is using the [Span Metrics Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.45.0/processor/spanmetricsprocessor) to set up timing for multiple services.  The path recommended to use for rate-limiting makes this bug appear.

**Comment by CoderPoet** [comment]
> I just ran into this. It doesn't make sense that the service doing the scraping gets to rename the service if it is already set. Especially if the endpoint is an aggregation of multiple services. My specific use case is using the [Span Metrics Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.45.0/processor/spanmetricsprocessor) to set up timing for multiple services. The path recommended to use for rate-limiting makes this bug appear.

Yes, I also feel that not all metrics need the `servce.name` attribute, so can the prometheusreceiver consider not setting it?

**Comment by crobertson-conga** [comment]
Note, I did use the method that Aneurysm9 suggested (hooking up the pipelines via otlp) and that seems to work rather well for my use case.

**Comment by alexrudd** [comment]
For anyone else who comes across this. Here's the processor config I used to correct my `service_name` label as it had been combining it with the prometheus receiver `job_name`.

```yaml
processors:
  resource:
    attributes:
    - key: service.name
      from_attribute: service_name
      action: upsert
    - key: service_name
      action: delete
```
