### ISSUE TITLE
[elasticsearchexporter] can't start

### ISSUE THREAD

**Issue by makefriend8** [open-telemetry/opentelemetry-collector-contrib#8112]
**Describe the bug**

Error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "elasticsearch": 1 error(s) decoding:

**Steps to reproduce**
`
otelcol-contrib_0.45.0_windows_amd64>otelcol-contrib.exe --config=otel-collector.yaml
`

**What did you expect to see?**
start successful

**What did you see instead?**
`
2022/02/24 09:37:25 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/02/24 09:37:25 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
Error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "elasticsearch": 1 error(s) decoding:

* '' has invalid keys: endpoint
2022/02/24 09:37:25 collector server run finished with error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "elasticsearch": 1 error(s) decoding:

* '' has invalid keys: endpoint
`

**What version did you use?**
Version: 0.45.0

**What config did you use?**
```
receivers:    
  otlp:     
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4417"
processors:
  batch:
exporters:
  elasticsearch:
    endpoint: "https://192.168.170.129:9200"
    user: elastic
    password: mypassword
  logging:
    loglevel: debug
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]
```

**Environment**
windows 10
go 17
