### ISSUE TITLE
[metricstransformprocessor] Regex group interpolation not working on add_label

### ISSUE THREAD

**Issue by jvaesteves** [open-telemetry/opentelemetry-collector-contrib#8121]
**Describe the bug**
In the **metricstransformprocessor**, I am trying to use the add_label operation to add the label **application** with one of the matching groups of metric regexp, but I every time I do it, it adds the label value as the regex interpolation itself

**Steps to reproduce**
```yaml
processors:
  batch:
  metricstransform:
    transforms:
      - include: ^spark\.(.+?)\.driver\.(.+?)\.(.+)\$\$
        new_name: spark.\$\${3}
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: application
            new_value: \$\${1}
```

**What did you expect to see?**
```
spark_generatedClassSize_min{application="foo"}
```

**What did you see instead?**
```
spark_generatedClassSize_min{application="${1}"}
```

**What config did you use?**
```yaml
receivers:
  statsd:
    endpoint: "localhost:8125"
    aggregation_interval: 10s

processors:
  batch:
  metricstransform:
    transforms:
      - include: ^spark\.(?P<application>.+?)\.driver\.(.+?)\.(.+)\$\$
        new_name: spark\.\$\${3}
        match_type: regexp
        action: combine

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [statsd]
      processors: [batch,metricstransform]
      exporters: [prometheus]
```

**What version did you use?**
otelcol-contrib_0.45.0_linux_amd64.deb

**Environment**
OS: Ubuntu 20.04.3 LTS

**Additional context**
