### ISSUE TITLE
[Metrics builder] Allow attribute values of any types

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector-contrib#8127]
Currently the experimental mdata generator can generate code for recording metrics with attributes values of string type only. We need to add support for recording other attribute value types in the attributes definition section of metadata.yaml. `attributes.<attrinbute_name>` section should get another optional argument `type` with default value string. 

```yaml
attributes:
  <attribute.name>:
   ...

   # Optional: To be added
   type: <string|int|double|bool|bytes>
```

If `type` value is specified to anything other than `string`, generated `record...DataPoint` function should expect specific attribute type according to the provided option, e.g. `int64`, `float64`, `bool` or `[]byte`.

Complex type like array and map can be avoided since they are not broadly adopted yet.
