### ISSUE TITLE
Health check extension returns 200 status code during errors

### ISSUE THREAD

**Issue by william-tran** [open-telemetry/opentelemetry-collector-contrib#8276]
**Describe the bug**
When I simulate exporter errors and use health check with `check_collector_pipeline` enabled, I get a response like 

```
$ while true; do python3 test.py; curl -v localhost:13133; done

Traces cannot be uploaded; HTTP status code: 500, message: Internal Server Error
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 13133 (#0)
> GET / HTTP/1.1
> Host: localhost:13133
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 07 Mar 2022 17:06:40 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
* Closing connection 0
```

**Steps to reproduce**

run v0.46.0 with this config.yaml

```yaml
receivers:
  jaeger:
    protocols:
      thrift_http:

extensions:
  health_check:
    check_collector_pipeline:
      enabled: false
      interval: 1s
      exporter_failure_threshold: 1

exporters:
  otlphttp:
    # should result in connection refused
    endpoint: "http://localhost:55555"
    retry_on_failure:
      enabled: true
    sending_queue:
      enabled: true
      queue_size: 10

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - jaeger
      exporters:
        - otlphttp
```

And with this python script test.py:

```python
from opentelemetry import trace
from opentelemetry.exporter.jaeger.thrift import JaegerExporter
from opentelemetry.sdk.resources import SERVICE_NAME, Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

trace.set_tracer_provider(
TracerProvider(
        resource=Resource.create({SERVICE_NAME: "my-helloworld-service"})
    )
)
tracer = trace.get_tracer(__name__)

# create a JaegerExporter
jaeger_exporter = JaegerExporter(
    collector_endpoint='http://localhost:14268/api/traces?format=jaeger.thrift',
)

# Create a BatchSpanProcessor and add the exporter to it
span_processor = BatchSpanProcessor(jaeger_exporter)

# add to the tracer
trace.get_tracer_provider().add_span_processor(span_processor)

with tracer.start_as_current_span("hello"):
    print("Hello world from OpenTelemetry Python!")
```

and requirements.txt

```
opentelemetry-api
opentelemetry-sdk
opentelemetry-exporter-jaeger-thrift
```

```
$ pip install -r requirements.txt
```

execute in a loop until you see errors:

```sh
$ while true; do python3 test.py; curl -v localhost:13133; done
```

**What did you expect to see?** 
Health check eventually responds with a 5xx status code

**What did you see instead?**
Health check always responds with a 200 status code

**What version did you use?**
0.46.0

**What config did you use?**
See above

**Environment**
OS: locally tested on OSX
