### ISSUE TITLE
[receiver/kafkametricsreceiver] collector crashes if Kafka is unavailable at startup

### ISSUE THREAD

**Issue by mwear** [open-telemetry/opentelemetry-collector-contrib#8349]
**Describe the bug**
If Kafka is not available when the kafka metrics receiver attempts to start, the collector fails to start.  

**Steps to reproduce**
Configure the kafka metrics receiver and start the collector without a running Kafka instance. Alternatively, you can use [this docker-compose example](https://github.com/mwear/otel-collector-examples/tree/main/kafka-metrics-receiver)

If using the example, do the following:

```
git clone git@github.com:mwear/otel-collector-examples.git
cd otel-collector-examples/kafka-metrics-receiver
docker-compose up
```

**What did you expect to see?**
I expected a warning at the bare minimum, although, ideally, the receiver would try to reconnect with a backoff strategy.

**What did you see instead?**
The collector exits with an error. Specifically, I saw this:

```
otel-collector | 2022-03-08T22:00:01.140Z	info	service/service.go:97	Starting receivers...
otel-collector | 2022-03-08T22:00:01.140Z	info	builder/receivers_builder.go:68	Receiver is starting...	{"kind": "receiver", "name": "kafkametrics"}
kafka        | 2022-03-08 22:00:01,516 INFO spawned: 'zookeeper' with pid 8
kafka        | 2022-03-08 22:00:01,518 INFO spawned: 'kafka' with pid 9
otel-collector | Error: cannot start receivers: failed to create client while starting brokers scraper: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
otel-collector | 2022/03/08 22:00:01 collector server run finished with error: cannot start receivers: failed to create client while starting brokers scraper: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
otel-collector exited with code 1
```

**What version did you use?**
v0.46.0

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      http:
      grpc:
  
  kafkametrics:
    protocol_version: 2.0.0
    brokers: kafka:9092
    scrapers:
      - brokers
      - topics
      - consumers

exporters:
  logging:

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp, kafkametrics]
      processors: [batch]
      exporters: [logging]
  telemetry:
    logs:
      level: debug
```

**Environment**
The "official" [collector contrib docker image](https://hub.docker.com/layers/otel/opentelemetry-collector/0.46.0/images/sha256-41bbec0c3ef5a55430977cdf42938cdc6fd1e66f1f1de03015905a604bcc4e4b?context=explore)
