### ISSUE TITLE
prometheus receiver scrape kubelet 10250/metrics/cadvisor fail

### ISSUE THREAD

**Issue by jinxin-fu** [open-telemetry/opentelemetry-collector-contrib#8385]
otel config as follow 
```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'local-cadvisor'
          scrape_interval: 20s
          static_configs:
            - targets: ['192.168.1.51:10250']
          metrics_path: /metrics/cadvisor
          scheme: https
```
I have config the kubelet-config to enable anonymous
the error log:
```
 warn    internal/metricsbuilder.go:125  Failed to scrape Prometheus endpoint    {"kind": "receiver", "name": "prometheus", "scrape_timestamp": 1646990804917, "target_labels": "map[__name__:up instance:192.168.1.51:10250 job:local-cadvisor]"}
```

I can't find more logs to fix the error ,  am I miss some config to scrape kubelet cadvisor metrics by otel receiver
