### ISSUE TITLE
[exporter/datadog] Rename `metrics::send_monotonic_counter` to `metrics::sums::cumulative_monotonic_mode`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#8489]
### What will change?

The `metrics::send_monotonic_counter` setting from the Datadog exporter will be renamed to `metrics::sums::cumulative_monotonic_mode`, which will hold an enum. The setting name was taken from the Datadog OpenMetrics integration, but its meaning is confusing and it's not in a dedicated section for the metric name.

### Who is affected?

You are affected if you explicitly set `metrics::send_monotonic_counter` on your Datadog exporter configuration. If you are affected, a warning will be logged stating that you are using it, together with a link to this issue.

Example warning:

```
Deprecated: "metrics::send_monotonic_counter" has been deprecated in favor of "metrics::sums::cumulative_monotonic_mode" and will be removed in v0.50.0. See github.com/open-telemetry/opentelemetry-collector-contrib/issues/8489 for details
```

The default behavior of the Datadog exporter will not change.

### What should I do if I am affected?

Remove any references to `metrics::send_monotonic_counter` from your configuration and set `metrics::sums::cumulative_monotonic_mode` instead.

<details>

<summary> Example with <code>metrics::send_monotonic_counter: true</code> (click to expand) </summary>

If using:

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    metrics:
      send_monotonic_counter: true
# ...
```

You can replace it by

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    metrics:
      sums:
        cumulative_monotonic_mode: to_delta
# ...
```

</details>

<details>

<summary> Example with <code>metrics::send_monotonic_counter: false</code> (click to expand) </summary>

If using:

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    metrics:
      send_monotonic_counter: false
# ...
```

You can replace it by

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    metrics:
      sums:
        cumulative_monotonic_mode: raw_value
# ...
```

</details>

### When will it change?

*To be filled when this happens*

| Change description           | Version of deprecation | Version of removal  |
|------------------------------|------------------------|---------------------|
| Renaming of `metrics::send_monotonic_counter` | v0.48.0 | TBD |
