### ISSUE TITLE
Enable attributesprocessor to delete dynamically named attributes

### ISSUE THREAD

**Issue by chris-pinola-rf** [open-telemetry/opentelemetry-collector-contrib#8551]
**Is your feature request related to a problem? Please describe.**
There are several applications at my organization that encode epoch timestamps into attribute names (e.g. `started_at_1647633980`). This causes our downstream trace storage system to need to ingest hundreds-of-thousands of different attribute dimensions which is causing serious performance issues. Patching this problematic behavior out of all the affected applications could take several months.

Fortunately, all the applications route their telemetry data through an instance of the OTel Collector, so it would be extremely convenient if we could drop the problematic attributes before relaying them to our exporters. The `attributesprocessor` is currently inadequate for solving this problem because it requires us to know the precise attribute names ahead of time, and given that the attributes we wish to delete are named dynamically (but follow a consistent naming convention), this is impossible.

**Describe the solution you'd like**
I would like to be able to define DELETE actions with support for wildcards or regex patterns so that I could delete any attribute (even >1) that matched a pattern. I cannot use the DELETE action in its present state since it requires me to know precisely the name of the attribute that I wish to delete.

Here's an example of my desired configuration:
```yaml
  processors:
    attributes/drop-malformed-attributes:
      actions:
        - key: started_at_
          pattern: started_at_\d+
          action: delete
```

Or perhaps:
```yaml
  processors:
    attributes/drop-malformed-attributes:
      actions:
        - key: started_at_\d+
          is_pattern: true
          action: delete
```

**Describe alternatives you've considered**
The only alternative would be to eagerly provision DELETE actions for all possible epoch timestamps for the next ~month, which is infeasible, e.g.:
```yaml
  processors:
    attributes/drop-malformed-attributes:
      actions:
        - key: started_at_1647633980
          action: delete
        - key: started_at_1647633981
          action: delete
        - key: started_at_1647633982
          action: delete
        - key: started_at_1647633983
          action: delete
        - key: started_at_1647633984
          action: delete
        - key: started_at_1647633985
          action: delete
        - key: started_at_1647633986
          action: delete
        - key: started_at_1647633987
          action: delete
          ...
```

**Additional context**
