### ISSUE TITLE
Unknown extensions type "jaegerremotesampling"

### ISSUE THREAD

**Issue by sakthiraam** [open-telemetry/opentelemetry-collector-contrib#8554]
**Describe the bug**
I'm using the latest version of otel collector contrib and getting Unknown extensions type "jaegerremotesampling"

**Steps to reproduce**
run the otel collector contrib executable with the below yaml configuration.

**What did you expect to see?**
otel collector to start with jaegerremotesampling extension listening of gRPC and http port number defined in the config

**What did you see instead?**
A error as below

$ ./otelcol-contrib --config=file:./otel_test_config.yml
2022/03/19 12:08:08 proto: duplicate proto type registered: jaeger.api_v2.PostSpansRequest
2022/03/19 12:08:08 proto: duplicate proto type registered: jaeger.api_v2.PostSpansResponse
Error: failed to get config: cannot unmarshal the configuration: unknown extensions type "jaegerremotesampling" for "jaegerremotesampling" (valid values: [zpages oidc pprof memory_ballast k8s_observer asapclient fluentbit oauth2client host_observer awsproxy basicauth bearertokenauth health_check http_forwarder file_storage])
2022/03/19 12:08:08 collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown extensions type "jaegerremotesampling" for "jaegerremotesampling" (valid values: [zpages oidc pprof memory_ballast k8s_observer asapclient fluentbit oauth2client host_observer awsproxy basicauth bearertokenauth health_check http_forwarder file_storage])

**What version did you use?**
Version: otel collector contrib - 0.47.0

**What config did you use?**
```
extensions:
  memory_ballast:
    size_in_percentage: 40
  zpages:
    endpoint: 0.0.0.0:55679
  health_check:
    endpoint: 0.0.0.0:13133
  health_check/1:
    endpoint: 0.0.0.0:13134
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5
  pprof:
    endpoint: 0.0.0.0:1888
  jaegerremotesampling:
    http:
      endpoint: :5878
    source:
      file: /home/test/otel/strategy.json
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
  memory_limiter:
    limit_mib: 1536
    spike_limit_mib: 512
    check_interval: 5s
exporters:
  logging:
    logLevel: debug
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
  extensions: [memory_ballast, zpages, health_check, pprof, jaegerremotesampling]
```

**Environment**
OS: CentOS 7

**Additional context**
