### ISSUE TITLE
Authenticator - Sigv4 -  unknown extensions type - release-0.47.0

### ISSUE THREAD

**Issue by transadm312** [open-telemetry/opentelemetry-collector-contrib#8779]
**Describe the bug**
unknown extensions type "sigv4auth" for "sigv4auth"

**Steps to reproduce**

**What did you expect to see?**
OTEL to export prom metrics to AWS

**What did you see instead?**

```
Error: failed to get config: cannot unmarshal the configuration: unknown extensions type "sigv4auth" for "sigv4auth" (valid values: [file_storage zpages awsproxy fluentbit pprof bearertokenauth host_observer basicauth k8s_observer oidc oauth2client memory_ballast asapclient health_check http_forwarder])
2022/03/22 07:03:06 collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown extensions type "sigv4auth" for "sigv4auth" (valid values: [file_storage zpages awsproxy fluentbit pprof bearertokenauth host_observer basicauth k8s_observer oidc oauth2client memory_ballast asapclient health_check http_forwarder])
```
**What version did you use?**
v0.47.0

**What config did you use?**
```
      apiVersion: opentelemetry.io/v1alpha1
      kind: OpenTelemetryCollector
      metadata:
        name: metrics
      spec:
        mode: deployment
        image: otel/opentelemetry-collector-contrib:0.47.0
        config: |
          extensions:
            sigv4auth:
              assume_role:
                arn: "arn:aws:iam::1111111111111:role/test-metrics-prometheus"
          receivers:
            prometheus/fluentbit:
              config:
                global:
                  scrape_interval: 5m
                  scrape_timeout: 1m
          exporters:
            prometheusremotewrite:
              endpoint: "https://....."
              namespace: cshared
              auth:
                authenticator: sigv4auth
          service:
            extensions: [sigv4auth]
            pipelines:
              metrics:
                receivers: [prometheus/fluentbit]
                processors: []
                exporters: [prometheusremotewrite]
```

**Environment**
EKS

**Additional context**
