### ISSUE TITLE
[exporter/datadog] Remove `service` setting

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#8781]
### What will change?

The `service` setting from the Datadog exporter will be removed in favor of using the [`service.name` semantic convention](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.9.0/specification/resource/semantic_conventions#service), which is a required convention.

### Who is affected?

You are affected if you use the `service` setting from the exporter. If you are affected, a warning will be logged stating that you are using it, together with a link to this issue.

Example warning:

```
Deprecated: "service" has been deprecated and will be removed in v0.52.0. See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/8781
```

### What should I do if I am affected?

Remove any references to `service` from your configuration and set the `service.name` semantic convention on your SDK or using the resource processor instead.
<details>

<summary> Example using the Go SDK for traces (click to expand) </summary>

If using:

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    service: test-service
# ...
```

You can remove the `service` setting and set this as a resource on the Go SDK, as shown on [the official example](https://github.com/open-telemetry/opentelemetry-go/blob/v1.5.0/example/otel-collector/main.go):

First, create a new resource with the service name: 
```go
ctx := context.Background()
res, err := resource.New(ctx,
		resource.WithAttributes(
			// the service name used to display traces in backends
			semconv.ServiceNameKey.String("test-service"),
		),
	)
```

Then, pass it to your trace provider builder as an option:
```go
tracerProvider := sdktrace.NewTracerProvider(
                // other options may go here ...
		sdktrace.WithResource(res),	
     )
```

All language SDKs support setting semantic conventions; if you need help please reach out on the language SDK repo or comment here

</details>

<details>

<summary> Example using the resource processor (click to expand) </summary>

If using:

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    service:  test-service
# ...
```

You can replace it by using a [`resource` processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor#resource-processor), which will override any existing `service.name` attribute:

```yaml
processors:
  resource:
     - key: service.name
        value: "test-service"
        action: upsert

# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
# ...
```

Lastly, you need to **add the resource processor to all your pipelines**.

</details>

### When will it change?

*To be filled when this happens*

| Change description           | Version of deprecation | Version of removal  |
|------------------------------|------------------------|---------------------|
| Removal of `service` | v0.49.0 | TBD |
