### ISSUE TITLE
[receiver/mongodbatlas] Duplicate Metrics

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector-contrib#8831]
**Describe the bug**
For metrics that have several datapoints identified by attributes, like [mongodbatlas.process.asserts](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/mongodbatlasreceiver/metadata.yaml#L140-L147), the datapoints are spread across duplicate metrics rather than all bundled under a single metric. This is causing an issue specifically in the googlecloudexporter as Stackdriver is detecting these as duplicate metrics, since they all have the same timestamp, and rejecting them.

**Steps to reproduce**
Configure `mongodbatlas` receiver with `googlecloudexporter` and wait a few collections.

**What did you expect to see?**
No errors during the process with a valid config.

**What did you see instead?**
Getting export errors like this:

```
Exporting failed. Try enabling retry_on_failure config option.	{"kind": "exporter", "name": "googlecloud", "error": "[rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[100] had an invalid value: Duplicate TimeSeries encountered.
```

**What version did you use?**
Version: v0.45.1

**What config did you use?**
Config: 
```yaml
receivers:
  mongodbatlas:
    public_key: REDACTED
    private_key: REDACTED

processors:
  batch:

exporters:
  logging:
  googlecloud:
    retry_on_failure:
      enabled: false

service:
  pipelines:
    metrics:
      receivers: [mongodbatlas]
      processors: [batch]
      exporters: [logging, googlecloud]

```

**Environment**
OS: MacOS 12.2.1
Compiler(if manually compiled): go 1.17.8

**Additional context**
This should be an implementation fix only. I also saw this receiver was not using the `--experimental-gen` flag for mdatagen which would likely make solving this issues easier. 

I am happy to volunteer to make these changes if the owner does not want too.
