### ISSUE TITLE
loadbalancing exporter blocking the process of consume traces when loadbalancer backends change

### ISSUE THREAD

**Issue by ralphgj** [open-telemetry/opentelemetry-collector-contrib#8843]
**Describe the bug**
Hi, we found the loadbalancing exporter sometimes would block all the request of upload trace data. So we add some logs and found the endpoint exporters that should be removed spent a long time. 

In https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/loadbalancer.go#L121,
```
	if !newRing.equal(lb.ring) {
		lb.updateLock.Lock()
		defer lb.updateLock.Unlock()

		lb.ring = newRing

		// TODO: set a timeout?
		ctx := context.Background()

		// add the missing exporters first
		lb.addMissingExporters(ctx, resolved)
		lb.removeExtraExporters(ctx, resolved)
	}
```
when loadbalancer backends changed, `lb.removeExtraExporters` sometimes spent more than 10s, so it blocked the consume processing in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/trace_exporter.go#L97 and the cause seems `onBackendChanges` hold the `updateLock`

Can we make the shutdown process async like this?
In https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter/loadbalancer.go#L152, 
```
func (lb *loadBalancerImp) removeExtraExporters(ctx context.Context, endpoints []string) {
	for existing := range lb.exporters {
		if !endpointFound(existing, endpoints) {
			go lb.exporters[existing].Shutdown(ctx)
			delete(lb.exporters, existing)
		}
	}
}
```

**What version did you use?**
Version: 0.42.0

**What config did you use?**
Config: 
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4318"

exporters:
  logging:
    logLevel: debug
  loadbalancing:
    protocol:
      otlp:
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 20s
          max_elapsed_time: 60s
        sending_queue:
          enabled: true
          num_consumers: 20
          queue_size: 1000000
    resolver:
      dns:
        hostname: opentelemetry-collector-sampling.otel.svc.cluster.local
        port: 4317

extensions:
  health_check:
    endpoint: "localhost:13134"

service:
  extensions: [ health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ loadbalancing ]

```

**Environment**
docker image: otel/opentelemetry-collector-contrib:0.42.0

**Additional context**
