### ISSUE TITLE
[exporter/datadog] Rename `metrics::report_quantiles` to `metrics::summaries::mode`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#8845]
### What will change?

The `metrics::report_quantiles` setting from the Datadog exporter will be renamed to `metrics::summaries::mode`, which will hold an enum. The setting name was taken from the Datadog OpenMetrics integration, but it limits future modes and it's not in a dedicated section for the metric type.

### Who is affected?

You are affected if you explicitly set `metrics::report_quantiles` on your Datadog exporter configuration. If you are affected, a warning will be logged stating that you are using it, together with a link to this issue.

Example warning:

```
Deprecated: "metrics::report_quantiles" has been deprecated in favor of "metrics::summaries::mode" and will be removed in v0.50.0. See github.com/open-telemetry/opentelemetry-collector-contrib/issues/8845 for details
```

The default behavior of the Datadog exporter will not change.

### What should I do if I am affected?

Remove any references to `metrics::report_quantiles` from your configuration and set `metrics::summaries::mode` instead.

<details>

<summary> Example with <code>metrics::report_quantiles: true</code> (click to expand) </summary>

If using:

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    metrics:
      report_quantiles: true
# ...
```

You can replace it by

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    metrics:
      summaries:
        mode: gauges
# ...
```

</details>

<details>

<summary> Example with <code>metrics::report_quantiles: false</code> (click to expand) </summary>

If using:

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    metrics:
      report_quantiles: false
# ...
```

You can replace it by

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    metrics:
      summaries:
        mode: noquantiles
# ...
```

</details>

### When will it change?

*To be filled when this happens*

| Change description           | Version of deprecation | Version of removal  |
|------------------------------|------------------------|---------------------|
| Renaming of `metrics::report_quantiles` | v0.50.0 | TBD |
