### ISSUE TITLE
[receiver/hostmetricsreceiver] CPU utilization uses inaccurate time delta

### ISSUE THREAD

**Issue by rubenruizdegauna** [open-telemetry/opentelemetry-collector-contrib#8856]
**Describe the bug**
`system.cpu.utilization` delta time is calculated using timestamps read in each scrape. These timestamp reads are not directly related to the cpu times reads so the used delta time to calculate utilization is not aligned with the delta time from times values. This makes `system.cpu.utilization` inacurate. 

As cpu utilization relies on cpu times, the delta time should be calculated from the cpu times value (gopsutil already provides a `Total()` [function](https://github.com/shirou/gopsutil/blob/master/cpu/cpu.go#L89) that returns the total number of seconds). This way we can avoid timestamp read and persistence between scrapes simplifying it.

**Now**: 
```
utilization.user = cpu.user / (time diff from system time)
utilization.idle = cpu.idle / (time diff from system time)
...
```

**Proposal**: 
```
utilization.user = cpu.user / (elapsed seconds from times)
utilization.idle = cpu.idle / (elapsed seconds from times)
...
```

**What version did you use?**
Version: v0.47.0

**What config did you use?**
```
receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
```

**Additional context**
I am the one that worked on cpu utilization that includes the wrong calculation :( . I have worked on a solution PR if this issue is accepted.
