### ISSUE TITLE
Minimal config.yaml Proposal

### ISSUE THREAD

**Issue by philipcwhite** [open-telemetry/opentelemetry-collector-contrib#8992]
**Is your feature request related to a problem? Please describe.**
When I first started using the collector the config.yaml file was quite minimal.  I realize it hasn't grown substantially but I would prefer it was kept simple.  

**Describe the solution you'd like**
A clear and concise description of what you want to happen.  Keep the file simple like this.  
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
exporters:
  logging:
    log_level: debug
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
```

**Describe alternatives you've considered**
I would be fine with having additional fields included but commented out as long as the file stays relatively small in size.  You could  put a comment in the config referencing back to the repo for additional configuration examples.  New users may not realize that there is a fairly good reference here.

**Additional context**
