### ISSUE TITLE
Cannot export using otlp with basic auth

### ISSUE THREAD

**Issue by politician** [open-telemetry/opentelemetry-collector-contrib#8999]
**Describe the bug**
I would like to export traces to a Tempo instance hosted on Grafana Cloud. This requires authentication with basic auth, but I cannot make it work using the `basicauth` extension, it seems only supported when receiving traces via otlp but not exporting.

It works when using basic auth headers.

**Steps to reproduce**

```yaml
receivers:
  jaeger:
    protocols:
      grpc:
      thrift_http:

processors:
  batch:

exporters:
  logging:
    logLevel: debug

  otlp:
    endpoint: tempo-eu-west-0.grafana.net:443
    auth:
      authenticator: basicauth

extensions:
  basicauth:
    htpasswd:
      inline: |
        user:pass

service:
  extensions:
    - basicauth

  pipelines:
    traces:
      receivers:
        - jaeger
      processors:
        - batch
      exporters:
        - logging
        - otlp
```

**What did you expect to see?**

Traces sent to Tempo

**What did you see instead?**

`cannot start exporters: requested authenticator is not a client authenticator`

**Workaround using headers**

```yaml
receivers:
  jaeger:
    protocols:
      grpc:
      thrift_http:

processors:
  batch:

exporters:
  logging:
    logLevel: debug

  otlp:
    endpoint: tempo-eu-west-0.grafana.net:443
    headers:
      authorization: Basic {{ "user:pass" | b64enc }}

service:
  pipelines:
    traces:
      receivers:
        - jaeger
      processors:
        - batch
      exporters:
        - logging
        - otlp
```

**What version did you use?**
Version: `0.48.0`

**Environment**
Kubernetes
