### ISSUE TITLE
[exporter/kafka] tls not work

### ISSUE THREAD

**Issue by ayu-programer** [open-telemetry/opentelemetry-collector-contrib#9012]
**Describe the bug**
i want to export the collected link data to Kafka by the opentelemetry-collector，and my kafka  protocol is tls
and my config was  as below

```
kafka:
    topic: otel-spans
    brokers:
      - "broker-4475-0.strimzi.kafka.mid:443"
      - "broker-4475-1.strimzi.kafka.mid:443"
      - "broker-4475-2.strimzi.kafka.mid:443"
    auth:
      tls:
        insecure: true
        cert_file: /usr/local/otel/kafka-ca.crt
        key_file: /usr/local/otel/kafka-ca.key
```

but it will report an error client has run out of available brokers to talk to (Is your cluster reachable

so as for me,how can i connect to the  kafka cluster? 
if i want to ignore the tls config，How should I configure it？if i config as below, is it true?
```
kafka:
    topic: otel-spans
    brokers:
      - "broker-4475-0.strimzi.kafka.mid:443"
      - "broker-4475-1.strimzi.kafka.mid:443"
      - "broker-4475-2.strimzi.kafka.mid:443"
    auth:
      tls:
        insecure: false
        insecure_skip_verify: true
```
