### ISSUE TITLE
[exporter/datadog] Remove `env` setting

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector-contrib#9016]
### What will change?

The `env` setting from the Datadog exporter will be removed in favor of using the [`deployment.environment` semantic convention](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.9.0/specification/resource/semantic_conventions/deployment_environment.md).

### Who is affected?

You are affected if you use the `env` setting from the exporter. If you are affected, a warning will be logged stating that you are using it, together with a link to this issue.

Example warning:

```
Deprecated: "env" has been deprecated and will be removed in v0.52.0. See https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/9016
```

### What should I do if I am affected?

Remove any references to `env` from your configuration and set the `deployment.environment` semantic convention on your SDK or using the resource processor instead.
<details>

<summary> Example using the Go SDK for traces (click to expand) </summary>

If using:

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    env: test-environment
# ...
```

You can remove the `service` setting and set this as a resource on the Go SDK. This is similar to the way one sets service.name, shown on [the official example](https://github.com/open-telemetry/opentelemetry-go/blob/v1.5.0/example/otel-collector/main.go):

First, create a new resource with the environment name: 
```go
ctx := context.Background()
res, err := resource.New(ctx,
		resource.WithAttributes(
			// the service name used to display traces in backends
			semconv.DeploymentEnvironmentKey.String("test-environment"),
		),
	)
```

Then, pass it to your trace provider builder as an option:
```go
tracerProvider := sdktrace.NewTracerProvider(
                // other options may go here ...
		sdktrace.WithResource(res),	
     )
```

All language SDKs support setting semantic conventions; if you need help please reach out on the language SDK repo or comment here

</details>

<details>

<summary> Example using the resource processor (click to expand) </summary>

If using:

```yaml
# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
    env:  test-environment
# ...
```

You can replace it by using a [`resource` processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourceprocessor#resource-processor), which will override any existing `service.name` attribute:

```yaml
processors:
  resource:
     - key: deployment.environment
        value: "test-environment"
        action: upsert

# ...
exporters:
  datadog:
    api:
      key: ${DD_API_KEY}
# ...
```

Lastly, you need to **add the resource processor to all your pipelines**.

</details>

If you also want to keep `env` **as a host tag**,  you will need to add it to the `tags` list.

### When will it change?

*To be filled when this happens*

| Change description           | Version of deprecation | Version of removal  |
|------------------------------|------------------------|---------------------|
| Removal of `env` | v0.49.0 | TBD |
