### ISSUE TITLE
Jaeger remote sampling to be exposed no GRPC port

### ISSUE THREAD

**Issue by greut** [open-telemetry/opentelemetry-collector-contrib#9086]
**Is your feature request related to a problem? Please describe.**

With the following confuguration; the remote sampling data are available on port 5778 but not using the GRPC interface, the port 14250.

```yaml
receivers:
  jaeger:
    protocols:
      grpc: {}
      thrift_http: {}
    remote_sampling:
      endpoint: "jaeger:14250"
      host_endpoint: "0.0.0.0:5778"
      tls:
        insecure: true

processors:
  batch: {}

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [jaeger]
  telemetry:
    logs:
      level: debug
```

**Describe the solution you'd like**

That the behavior on the HTTP proxy, on port 5778 works similarly on the GRPC endpoint.

**Describe alternatives you've considered**

As an alternative, we're telling our Java integrations to use the OTEL collector for the sampling rather than the local OTEL agents.

**Additional context**

@jpkrohling wanted to be pinged on that one. Thanks!

the docker file used here.

```yaml
version: "2.4"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.32.0
    command:
      - "--sampling.strategies-file=/strategies.json"
      - "--sampling.strategies-reload-interval=10s"
      - "--log-level=debug"
    volumes:
      - "./strategies.json:/strategies.json"
    ports:
      - 127.0.0.1:14251:14250
      - 127.0.0.1:16686:16686

  otel:
    image: otel/opentelemetry-collector-contrib:0.48.0
    command:
      - "--config=/config.yaml"
    volumes:
      - "./config.yaml:/config.yaml"
    ports:
      - 127.0.0.1:14250:14250
      - 127.0.0.1:5778:5778
```

**Comment by jpkrohling** [comment]
It looks like I can't reproduce this. I built a client to retrieve the remote sampling configs:

```go
package main

import (
	"context"
	"log"
	"time"

	"github.com/jaegertracing/jaeger/proto-gen/api_v2"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

func main() {
	// prepare the connection to the inventory service
	conn, err := grpc.Dial(":14251", grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Printf("failed to connect to the inventory system: %v\n", err)
		return
	}
	defer conn.Close()
	cl := api_v2.NewSamplingManagerClient(conn)

	// reserve an item from the inventory
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	st, err := cl.GetSamplingStrategy(ctx, &api_v2.SamplingStrategyParameters{ServiceName: "foo"})
	if err != nil {
		log.Fatalf("failed to get sampling strategies: %v", err)
	}

	log.Printf("sampling strategies retrieved: %v", st)
}
```

This is my collector config:

```yaml
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14251
      thrift_http:
    remote_sampling:
      endpoint: "localhost:14250"
      host_endpoint: "0.0.0.0:5778"
      tls:
        insecure: true

exporters:
  logging:

processors:

extensions:

service:
  extensions:
  pipelines:
    traces:
      receivers: [jaeger]
      processors:
      exporters: [logging]
```

And I'm starting Jaeger with:

```console
podman run -p 14250:14250 jaegertracing/all-in-one:latest
```

When running the client, I get this:

```
$ go run ./
2022/04/18 17:26:50 sampling strategies retrieved: probabilisticSampling:<samplingRate:0.001 > 
```

Changing the client to get the data straight from Jaeger (14250 on line 15 from the client, instead of 14251) gets me this:

```
$ go run ./
2022/04/18 17:26:43 sampling strategies retrieved: probabilisticSampling:<samplingRate:1 > 
```

There's something odd with the sampling rates, but they are all available at the expected locations. Do you spot any differences between our setups that could account for this difference in behavior?
