### ISSUE TITLE
ability to aggregate telemetry data of child process into parent 

### ISSUE THREAD

**Issue by davidmirza408** [open-telemetry/opentelemetry-collector-contrib#9106]
**Is your feature request related to a problem? Please describe.**
The volume of data generated by hostmetricsreceiver for process monitoring can be overwhelming on buys systems with multiple child processes. 

**Describe the solution you'd like**
In an effort to reduce the volume of data, i would like to propose that we make available a config setting that aggregates the metrics of a child process into its parent process.  

**Describe alternatives you've considered**
N/A

**Additional context**
I would like to volunteer to make the code changes.

cc: @dmitryax

**Comment by davidmirza408** [comment]
This would be implemented as a top level config setting.  E.g.
```
receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      process:
        mute_process_name_error: true 
        aggregated_child_metrics: true
        filters:
          -
            min_uptime: 60s
            include_executable_name: 
              executable_name: [appd-otel-collector]
              match_type: strict

```
this means that regardless of which filter resulted in the process being reported on, the metrics will be aggregated.  

For the case where a filter results in the inclusion of the parent process but not the child process, the metrics of the child will be ignored when aggregating data.
