### ISSUE TITLE
New component: logs operators processor

### ISSUE THREAD

**Issue by dehaansa** [open-telemetry/opentelemetry-collector-contrib#9133]
## The purpose and use-cases of the new component
Currently logs operators from [opentelemetry-log-collection](https://github.com/open-telemetry/opentelemetry-log-collection) are only available when leveraging a logs receiver that is configured to support them (and uses opentelemetry-log-collection under the hood). Other logging receivers should also be able to leverage the logs operators, and they should be maintainable moving forward separate from requiring an update to each relevant receiver. For these reasons, the logs operators should be configurable as a processor independent from the receiver being used.

## Concerns & RIsks
Currently as the opentelemetry-log-collection library does not internally use the Logs data model, there is a Converter that converts from opentelemetry-log-collection/entry.Entry to pdata.Logs. For this processor to work, it will need to convert back to entry.Entry, run the logs operators, then again convert back to pdata.Logs.

## Example configuration for the component
```
processors:
  logsoperators:
    operators:
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
        timestamp:
          parse_from: body.time
          layout: '%Y-%m-%d'
        severity:
          parse_from: body.sev
```

## Telemetry data types supported
Logs

## Sponsor (Optional)
None

**Comment by pmm-sumo** [comment]
That's a good call @djaglowski I think that in ideal work [general purpose operators](https://github.com/open-telemetry/opentelemetry-log-collection/tree/main/docs/operators#what-operators-are-available) of `opentelemetry-log-collection` and the `transformprocessor` should converge functionality-wise

FYI @anuraaga

**Comment by dmitryax** [comment]
I think the log operators from the logs-collection library provide a lot of functionality that would require a lot of time to be replicated by the generic transform processor. 

Another point to support this proposal: I hope that bringing operators into a processor may help to better integrate the logs-collection library's model with the collector's pipeline data model, or at least uncover more issues that can be resolved sooner.

So generally I support this proposal even if this processor should be eventually replaced by the generic transform processor.

**Comment by djaglowski** [comment]
Glad to hear others think this would be useful. I'm happy to sponsor it.

**Comment by bogdandrutu** [comment]
Please make sure we don't have a name conflict, and have a good separation of concerns.

See https://github.com/open-telemetry/opentelemetry-collector-contrib/pulls?q=is%3Apr+is%3Aopen+transform+ make sure no duplicate work, and capabilities are clearly separated between this and the generic transform processor.

**Comment by Aneurysm9** [comment]
If the purpose of this processor is to provide structure to unstructured logs, would `logstructure` be a better name for it?  That would seem to provide some clarity about what separates it from the `transform` processor.

**Comment by djaglowski** [comment]
This was discussed in the Collector SIG today. Decision is that more due diligence must be done to estimate what may be necessary to expose equivalent functionality in the `transform` processor. If this functionality cannot be done in a relatively short timeframe, then this component may be added. However, it will be necessary to specify that the component is experimental and will likely be deprecated in the future.

**Comment by jsirianni** [comment]
I would love to have this processor. Today I was hoping I would be able to use operators with the k8sevents receiver, unfortunately I cannot. This processor (or some alternative) is exactly what I need to move forward with some of my configurations.

Currently I leverage filelogreceiver's `operators` option but it seems awkward to do it there and not with a processor.

**Comment by bogdandrutu** [comment]
@jsirianni which `operators` did you need (give me the top 2 most useful)?

**Comment by jsirianni** [comment]
Generally speaking, all of the parser operators are important. We can already leverage them with the filelog and syslog receivers, which is where they would be used most.

The [add](https://github.com/open-telemetry/opentelemetry-log-collection/blob/main/docs/operators/add.md) operator is very useful for adding arbitrary key=value pairs. I was hoping to add some "metadata" to the Kubernetes Events receiver, such as cluster name. I believe the events receiver does not support operators (unlike filelog and syslog).

If all logging receivers had the ability to nest operators, this would not be an issue. However, I think it makes sense to use operators as a processor rather than including them within a receivers configuration.

Instead of this
```yaml
receivers:
  filelog:
    include:
    - /var/log/app/log.json
    start_at: end
    resource:
      log_type: app
    operators:
      - type: json_parser
      - type: add
        field: resources.cluster_name
        value: stage
```

It may make sense to have
```
receivers:
  filelog:
    include:
    - /var/log/app/log.json
    start_at: end

processors:
  logstransform:
    operators:
      - type: json_parser
      - type: add
        field: resources.cluster_name
        value: stage 
```

This way, it is not the log receiver's responsibility to support operators / post processing.
