### ISSUE TITLE
[extension/filestorage] Mark as Beta

### ISSUE THREAD

**Issue by cpheps** [open-telemetry/opentelemetry-collector-contrib#9135]
# Proposal
I would like to propose to update the [filestorage extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage) to be in beta rather than alpha. The extension has gone through minimal changes in the past two months and appears fairly stable. Updating it to beta status will give users more assurance and confidence in using the extension.

@BinaryFissionGames and I ran some benchmarking tests against the collector with and without the filestorage extension enabled and we didn't see much difference in performance than without using it.

# Benchmarks:
Here's a breakdown of the benchmarks we ran:

We used the [aws logbench tool](https://github.com/awslabs/amazon-log-agent-benchmark-tool) in our testing.

Logs were sent to an in-house gRPC server that tracks throughput. The server was on a separate machine to not interfere with the collector.

Benchmark parameters:
**Log Rate:** 15000 logs/sec
**Num Files:** 10 files
**Test duration:** 30 seconds (we found running longer doesn't show much difference)

### Without filestorage

```yaml
receivers:
  filelog:
    include: ["/opt/logs/*.log"]
​
processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200
​
exporters:
  otlp:
    endpoint: throughput-count:9124
    compression: none
    tls:
      insecure: true
​
service:
  pipelines:
    logs:
      receivers:
        - filelog
      processors:
        - batch
      exporters:
        - otlp
```

### With filestroage

```yaml
receivers:
  filelog:
    include: ["/opt/logs/*.log"]
​
processors:
  batch:
    send_batch_max_size: 200
    send_batch_size: 200
​
exporters:
  otlp:
    endpoint: throughput-count:9124
    compression: none
    tls:
      insecure: true
    sending_queue:
      persistent_storage_enabled: true
​
extensions:
  file_storage:
    directory: "/opt/collector/storage"
​
service:
  extensions: [file_storage]
  pipelines:
    logs:
      receivers:
        - filelog
      processors:
        - batch
      exporters:
        - otlp
```
### Without filestorage

**Avg CPU:**  88.03%
**Avg Memory:** 1053.83 MB
**Log records Processed:** 3,875,800
**Avg Throughput:** 87K logs/sec

Throughput Graph:
![file-batch-otlp-rate](https://user-images.githubusercontent.com/11877763/162763593-2ef8b616-2d49-4c56-8f54-62dda994bb03.png)

### With filestorage

**Avg CPU:**  132.34%
**Avg Memory:** 328.05 MB
**Log records Processed:** 3,758,950
**Avg Throughput:** 86K logs/sec

Throughput Graph:
![file-batch-persistent-otlp-rate](https://user-images.githubusercontent.com/11877763/162763816-c8782a0c-6e4d-4d21-8d93-9ab64c3b7c88.png)

## Conclusion

The filestorage extension has a slightly lower throughput, uses more CPU, and less memory than a collector running without it. We feel this falls in line with expectations of sending batched log records to disk. Overall there seemed to be a negligible impact on the collector as far as performance or stability was concerned.
