### ISSUE TITLE
[mysqlreceiver]How to config the mysql Cluster receiver and prometheus exporters

### ISSUE THREAD

**Issue by Alanasking** [open-telemetry/opentelemetry-collector-contrib#9247]
**Is your feature request related to a problem? Please describe.**
Currently, only one MySQL endpoint can be configured，But usually MySQL is a cluster
receivers:
  mysql:
    **endpoint: localhost:3306**
    username: otel
    password: $MYSQL_PASSWORD
    database: otel
    collection_interval: 10s

**Describe the solution you'd like**
hostname1，hostname2，hostname3  are the three members of the MySQL Cluster.
how to config the mysql receiver and prometheus exporters? 

Example:

receivers:
  mysql:
    **endpoint: hostname1:3306，hostname2:3306，hostname3:3306**
    username: otel
    password: $MYSQL_PASSWORD
    database: otel
    collection_interval: 10s

exporters:
  prometheus:
    endpoint: "1.2.3.4:1234"
    namespace: test-space
    const_labels:
      label1: value1
      "another label": spaced value
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

**Describe alternatives you've considered**

**Additional context**

**Comment by ZhouZhongzhi** [comment]
You can try to configure multiple receivers of the same type.
**example:**
receivers:
  mysql/1:
    endpoint: 192.168.101.1:3306
    username: otel
    password: $MYSQL_PASSWORD
    database: otel
    collection_interval: 10s
  mysql/2:
    endpoint: 192.168.101.2:3306
    username: otel
    password: $MYSQL_PASSWORD
    database: otel
    collection_interval: 10s

......

service:
  pipelines:
    metrics/save:
      receivers: [mysql/1,mysql/2]
      exporters: [prometheus]

**Comment by Alanasking** [comment]
Thank you for your reply!@ZhouZhongzhi
I configured it according to what you said, but prometheus export can only display the metric of one mysql/1
-----------------------------------
My config.yaml:
receivers:
   mysql/1:
       endpoint: mysql-node1.mysqlservice.svc.cluyster.local:3306
       username: root
       password: $MYSQL_PASSWORD
       collection_interval: 10s
    mysql/2:
       endpoint: mysql-node3.mysqlservice.svc.cluyster.local:3306
       username: root
       password: $MYSQL_PASSWORD
       collection_interval: 10s
    mysql/3:
       endpoint: mysql-node4.mysqlservice.svc.cluyster.local:3306
       username: root
       password: $MYSQL_PASSWORD
       collection_interval: 10s
......
exporters:
   prometheus:
      endpoint: "0.0.0.0:8889"
      const_labels:
          OTEL1: MYDATAAAAAAAAAAAAAAAAAAAAAAAAA1
service:
    pipelines:
        [metrics:](url)
            receivers: [mysql/1,mysql/2,mysql/3]
            preocessors: [batch]
            exporters: [prometheus]

-----------------------------------
prometheus metric:
# HELP mysql_buffer_pool_data_pages The number of data pages in the InnoDB buffer pool.
# TYPE mysql_buffer_pool_data_pages gauge
mysql_buffer_pool_data_pages{OTEL1="MYDATAAAAAAAAAAAAAAAAAAAAAAAAA1",status="clean"} 332
mysql_buffer_pool_data_pages{OTEL1="MYDATAAAAAAAAAAAAAAAAAAAAAAAAA1",status="dirty"} 0
# HELP mysql_buffer_pool_limit The configured size of the InnoDB buffer pool.
# TYPE mysql_buffer_pool_limit gauge 
....

**Comment by ZhouZhongzhi** [comment]
I tested this configuration using two mysql instances.
The root cause of this problem is that mysql-recevier does not add the 'instance' tag when collecting data.

Use two mysql-receivers to collect mysql metrics at the same time,the two receivers will transmit the same  metricName<label> to subsequent pipelines. Because they are the same metricName<label> combination, the last data overwrites the previous data

You end up with only one of the data

**Comment by pmm-sumo** [comment]
There are several solutions. Also curious what @djaglowski thinks

What I would do is using separate pipelines, e.g.

```yaml
receivers:
  mysql/1:
    endpoint: 192.168.101.1:3306
    ...
  mysql/2:
    endpoint: 192.168.101.2:3306
    ...
processors:
  attributes/1:
    actions:
      - key: instance
        action: insert
        value: instance-1
  attributes/2:
    actions:
      - key: instance
        action: insert
        value: instance-2
pipelines:
  metrics/1:
    receivers: [mysql/1]
    processors: [attributes/1]
    exporters: [prometheus]
  metrics/2:
    receivers: [mysql/2]
    processors: [attributes/2]
    exporters: [prometheus]
  ...
```

I think we currently do not have attribute describing the MySQL instance. If we would have one, the above would be probably not required (or made more elegantly with transformprocessor)
