### ISSUE TITLE
sending_queue full when exporting data to backend

### ISSUE THREAD

**Issue by ajsaclayan** [open-telemetry/opentelemetry-collector-contrib#9251]
**Describe the bug**
Hi team, we are having an issue sending telemetry to a backend. In our case the backend is event hub using the [kafkaexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter).
The error happens on the batch processor:
`batchprocessor/batch_processor.go:185	Sender failed	{"kind": "processor", "name": "batch", "pipeline": "traces", "error": "sending_queue is full"}`

We don't believe it's an issue communicating with event hub, since there are multiple replicas running at a given time that are sending data successfully. There were no server side errors from event hub. The issue also doesn't correlate with any spike in requests.  This is occurring in all pipelines (trace/metrics/logs).

**Steps to reproduce**
- Deployed to Kubernetes
- Batch processor configured on collector
    - send_batch_size: 50
    - send_batch_max_size: 50
- Queued retry on the collector
- Using the default configurations of [exporter helper](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper#exporter-helper).
    - `sending_queue.queue_size`: 5000

**What did you expect to see?**
We expect the collector to remediate itself if there was any temporary backend outage.

**What did you see instead?**
Collector is unable to recover until that pod is killed or restarted.

**What version did you use?**
Version: `v0.47.0`

**What config did you use?**
Config: 
I slimmed down our actual pipeline to include the relevant bits. 

```
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resource, probabilistic_sampler, batch]
          exporters: [logging, kafka/traces]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, resource, batch]
          exporters: [logging, kafka/metrics]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, resource]
          exporters: [logging, kafka/logs]
```

**Environment**
OS: Linux

**Additional context**

**Comment by MovieStoreGuy** [comment]
Just to give me a bit more context on the setup, you mentioned Pods, does that mean you're entire environment is running inside cube?  Do you run the collector as part of the pod or as its own deployment? Did any of your brokers restart? 

I can kinda see how you could get in a scenario where collector has resolve the broker IPs but one of them restarted or the resolved IP had changed. 

In this scenario, what would you want the kafka client to do because the potential resolutions could be:
- Attempt X number of reconnection attempts, this does have the downside that back pressure will build up and at some point either the collector or application will need to drop data
- The collector detects that exporter is failing, it is restarted from scratch and looses all state that was accumulated

I understand that the collector is really sensitive to outages here since the collector itself doesn't fully support durability of the data (there is an extension from memory that it can use to recover from but I can't remember the name).

I am concerned that _nothing_ happened since that highlights a bigger problem that something is writing memory where it shouldn't be so getting more information on you, and the frequency of when it happens would be nice :) 

Like if it happens to be at 6hr uptime or load spikes. 

I would also suggest adding the prom receiver to read the internal metrics from the collector to see what insights can be gained from there.

**Comment by ajsaclayan** [comment]
Hi @MovieStoreGuy ,

> Just to give me a bit more context on the setup, you mentioned Pods, does that mean you're entire environment is running inside cube? Do you run the collector as part of the pod or as its own deployment?

This collector is running in a pod. We have some other containers running as a sidecar.

>  Did any of your brokers restart?

We are using an Azure event hub as an alternative to a Kafka cluster. Microsoft provides a Kafka endpoint we can target. According to the docs, brokers are fully managed by Event Hub. That being said, there may be a way to see if Event Hub exposes these restarts to us. More here https://docs.microsoft.com/en-us/azure/event-hubs/apache-kafka-developer-guide

> In this scenario, what would you want the kafka client to do because the potential resolutions could be

We would prefer scenario 1 to try and avoid data loss. Is there a setting for scenario 1? This is how we have configured our exporter (for metrics). I see there are built-in retries for send failures.
```
      kafka/metrics:
        brokers:
          - "${KAFKA_ENDPOINT}"
        metadata:
          full: false
          retry:
            max: 5 # 3 is the default
            backoff: 1000ms # 250ms is the default
        protocol_version: 1.0.0
        topic: metrics
        encoding: otlp_proto
        auth:
          sasl:
            username: "${KAFKA_USERNAME}"
            password: "${KAFKA_PASSWORD}"
            mechanism: PLAIN
          tls:
            insecure: false
```
I did notice the protocol version is not latest (`2.0.0`). Maybe we can bump this.

> I would also suggest adding the prom receiver to read the internal metrics from the collector to see what insights can be gained from there.

We are capturing prometheus metrics from this collector, but there isn't a smoking gun that would lead to the queue size climbing. Load looks to be stable for affected instances
