### ISSUE TITLE
[prometheusexporter] `honor_labels: true` doesn't send proper internal scrape metrics

### ISSUE THREAD

**Issue by gouthamve** [open-telemetry/opentelemetry-collector-contrib#9256]
**Reproduce**

1. Run a **Prometheus** with the following config:
```
scrape_configs:
- job_name: 'broken'
  scrape_interval: 1s
  static_configs:
  - targets: ['non-existent:12345']
```

2. Run a **collector** with the following config:
```
service:
  telemetry:
    useOtelForInternalMetrics: true
    logs:
      level: "debug"


receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'testing'
        scrape_interval: 5s
        honor_labels: true
        metrics_path: '/federate'

        params:
          'match[]':
            - '{job="broken"}'

        static_configs:
        - targets: ['localhost:9090']

processors:
  batch:

exporters:
  prometheus:
    endpoint: localhost:9091

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheus]
```

3. Go to `localhost:9091/metrics` and you'll see:
```
# HELP scrape_duration_seconds Duration of the scrape
# TYPE scrape_duration_seconds gauge
scrape_duration_seconds{instance="non-existent:12345",job="broken"} 0.009786041
# HELP scrape_samples_post_metric_relabeling The number of samples remaining after metric relabeling was applied
# TYPE scrape_samples_post_metric_relabeling gauge
scrape_samples_post_metric_relabeling{instance="non-existent:12345",job="broken"} 5
# HELP scrape_samples_scraped The number of samples the target exposed
# TYPE scrape_samples_scraped gauge
scrape_samples_scraped{instance="non-existent:12345",job="broken"} 5
# HELP scrape_series_added The approximate number of new series in this scrape
# TYPE scrape_series_added gauge
scrape_series_added{instance="non-existent:12345",job="broken"} 5
# HELP up The scraping was successful
# TYPE up gauge
up{instance="non-existent:12345",job="broken"} 1
```

You should see this:
```
# HELP scrape_duration_seconds Duration of the scrape
# TYPE scrape_duration_seconds gauge
scrape_duration_seconds{instance="non-existent:12345",job="broken"} 0.009786041
scrape_duration_seconds{instance="localhost:9090",job="testing"} SOMETHING
# HELP scrape_samples_post_metric_relabeling The number of samples remaining after metric relabeling was applied
# TYPE scrape_samples_post_metric_relabeling gauge
scrape_samples_post_metric_relabeling{instance="non-existent:12345",job="broken"} 0  <----- SHOULD BE 0.
scrape_samples_post_metric_relabeling{instance="localhost:9090",job="testing"} 5 <----- THIS SHOULD BE 5 BUT MISSING
# HELP scrape_samples_scraped The number of samples the target exposed
# TYPE scrape_samples_scraped gauge
scrape_samples_scraped{instance="non-existent:12345",job="broken"} 0     <----- SHOULD BE 0.
scrape_samples_scraped{instance="localhost:9090",job="testing"} 5 <----- THIS SHOULD BE 5 BUT MISSING
# HELP scrape_series_added The approximate number of new series in this scrape
# TYPE scrape_series_added gauge
scrape_series_added{instance="non-existent:12345",job="broken"} 0     <----- SHOULD BE 0.
scrape_series_added{instance="localhost:9090",job="testing"} 5 <----- THIS SHOULD BE 5 BUT MISSING
# TYPE up gauge
up{instance="non-existent:12345",job="broken"} 0    <----- SHOULD BE 0.
up{instance="localhost:9090",job="testing"} 1    <----- SHOULD BE 1 BUT MISSING
```

I initially had trouble wrapping my head around what shoud actually appear, only to realise, even the numbers are wrong 🙃 

This is on commit: 0328a79ec6d13896f053ab9d05231f02d0eb7b08
