### ISSUE TITLE
New component: Environment Extension

### ISSUE THREAD

**Issue by jsirianni** [open-telemetry/opentelemetry-collector-contrib#9260]
## The purpose and use-cases of the new component

Allow the collector to set environment variables at runtime, limited to its process only.

Usecases
- Setting `GOOGLE_APPLICATION_CREDENTIALS` instead of configuring a systemd override / windows system variable
- Proxy variables
- Recently, a user asked about [setting variable defaults on slack](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1649874731568689)

At observIQ, we have noticed friction when asking users to create the `GOOGLE_APPLICATION_CREDENTIALS` variable when running the Google exporter outside of GCP. Some users are not familiar / comfortable creating systemd overrides or modifying Windows system environment variables. This extension would reduce the number of steps required to install and stream telemetry to Google.

Allowing users to define non sensitive environment variables within their configuration will simplify the setup experience.

observIQ is willing to develop and contribute this extension.

## Example configuration for the component

```yaml
extensions:
  environment:
    # Always set
    - key: GOOGLE_APPLICATION_CREDENTIALS
      value: /opt/collector/credentials.json
      overwrite: true

    # Set HTTP proxy, overwrite defaults to `false`
    - key: HTTP_PROXY
      value: http://10.90.1.10:3000
    
   # Support setting if not already set
    - key: SOME_VARIABLE_DEFAULT
      value: "some default value"
      overwrite: false 
```

## Telemetry data types supported

Traces, Metrics, Logs.

**Comment by jsirianni** [comment]
> How would this relate to the config providers we have elsewhere?

Good question. I believe using the config provider to read environment variables makes a lot of sense for things that should not be hard coded into the configuration, such as credentials for a receiver.

I could see both being used when sensitive values must be injected into the config, but kept out of git.

In this example, Rabbitmq credentials are read from the environment while the location of the google credentials file is kept within the configuration.

```yaml
receivers:
  rabbitmq:
    endpoint: http://localhost:15672
    username: $RABBITMQ_USERNAME
    password: $RABBITMQ_PASSWORD

extensions:
  environment:
    - key: GOOGLE_APPLICATION_CREDENTIALS
      value: /opt/collector/credentials.json
      overwrite: true

exporters:
  googlecloud

service:
  extensions:
    - environment
  pipelines:
    metrics:
      receivers:
      - rabbitmq
      exporters:
      - googlecloud
```

This does seem to defeat the purpose. If the user is already setting `RABBITMQ_USERNAME` and `RABBITMQ_PASSWORD`, they should be fine with setting `GOOGLE_APPLICATION_CREDENTIALS` as well. At the end of the day, my example would contain one less environment variable for the user to set.

I believe placing the location of the Google credential file into the config is not a security risk. This file should have permissions restricted to the user running the collector process. Relying on environment variables set with a systemd override or windows system variable is security through obscurity, and would not prevent a rouge actor from accessing the file if they have already gained privileged access to the system.

Many configurations do not have sensitive data in the pipeline (e.g. Host Metrics, Prometheus, log pipelines, tracing), meaning this solution would not require them to set any environment variables.

**Comment by mx-psi** [comment]
I feel like the correct solution for this particular case is for the Google Cloud exporter to allow setting the credentials through a field in configuration instead of always requiring an environment variable. 

I understand the intent of forcing an environment variable (preventing people from putting their credentials in a possibly unsecure way), but I think this should be solved differently (should we e.g. mark sensitive fields with a struct tag and prevent setting them as plain text on the default YAML provider?).

The config providers point from @jpkrohling is also interesting; with a file expand provider we could have:

```yaml
exporters:
  googlecloud:
    credentials: ${file:/opt/collector/credentials.json}
```
