### ISSUE TITLE
Skywalking Receiver/Exporter How to use it ?

### ISSUE THREAD

**Issue by tonycody** [open-telemetry/opentelemetry-collector-contrib#9338]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/skywalkingreceiver
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/skywalkingexporter

I've been trying for a long time, but I can't figure out how to use it? Skywalking UI never had data.

I'm using a mirror image: otel/opentelemetry-collector-contrib-dev:latest

```yaml
receivers:
  otlp:
    protocols:
      grpc:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'vm-monitoring' # make sure to use this in the vm.yaml to filter only VM metrics
          scrape_interval: 10s
          static_configs:
            - targets: [ 'node-exporter:9100' ]
  skywalking:
    protocols:
      grpc:
        endpoint: "oap:11800"

exporters:
  opencensus:
    endpoint: "oap:11800" # The OAP Server address
    tls:
      insecure: true
  skywalking:
    endpoint: "oap:11800"
    tls:
      insecure: true
  logging:
    logLevel: info
processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp, skywalking ]
#      processors: [ batch ]
      exporters: [ logging,opencensus ]
    logs:
      receivers: [ otlp ]
#      processors: [ batch ]
      exporters: [ skywalking ,logging ]
    metrics:
      receivers: [ otlp ]
#      processors: [ batch ]
      exporters: [ skywalking,opencensus,logging ]
```
