### ISSUE TITLE
[processor/resourcedetection] docker detector is not wired

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector-contrib#9371]
**Describe the bug**

As [reported on CNCF Slack](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1649949788590829), when `docker` detector is configured, it returns an error while initialisation:

```
Error: cannot build pipelines: error creating processor "resourcedetection" in pipeline "metrics": invalid detector key: docker
```

This happens due to Docker detector [not being wired in the factor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/factory.go#L61-L73)

**Steps to reproduce**

Sample config where this fails:

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 15s
          static_configs:
            - targets: ['0.0.0.0:8888']
processors:
  resourcedetection:
    detectors: ["docker"]
exporters:
  logging/debug:
    loglevel: debug
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [resourcedetection]
      exporters: [logging/debug]
```
