### ISSUE TITLE
Question: How do you set a resource tag based on a span tag?

### ISSUE THREAD

**Issue by tillig** [open-telemetry/opentelemetry-collector-contrib#9387]
I am working with OpenTelemetry Collector in Istio and I have Istio adding a custom trace span tag `sidecar_name` to outbound OpenCensus trace spans.

I would like that to be the `service.name` resource tag value. I have tried setting up a `resourceprocessor` configuration like this:

```yaml
processors:
  resource/istio:
    attributes:
      - key: service.name
        from_attribute: sidecar_name
        action: upsert
```

I've added that processor to my `traces` pipeline. However, it doesn't appear the `sidecar_name` tag is available, so no change happens. If I switch the configuration temporarily...

```yaml
processors:
  resource/istio:
    attributes:
      - key: service.name-copy
        from_attribute: service.name
        action: upsert
```

...then I do get the `service.name-copy` coming through as a resource tag, which means the processor is getting hit. I believe that also means it's not able to find `sidecar_name` when it's running.

I think I _could_ use the [`transformprocessor`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md) but [I just discovered that's not included in the released Docker container](https://github.com/open-telemetry/opentelemetry-collector-releases/issues/104) so I'm kinda stuck unless I want to try setting up a Go environment and building a custom instance of the container myself.

I'm hoping there's something I'm overlooking, like a configuration syntax for the `resourceprocessor` that I'm just not seeing.

**Comment by tillig** [comment]
I have a similar issue where things like `pod_name` get added to spans by Istio and I'd like to translate those into `k8s.pod.name` resource tags.

**Comment by bogdandrutu** [comment]
@anuraaga ?

**Comment by dmitryax** [comment]
You can try this processor https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbyattrsprocessor to move span attributes to resource attributes

**Comment by tillig** [comment]
@dmitryax Looking at that, it'd be a two-step process, where I do something like:

```yaml
processors:
  # Move these span attributes up to be a resource
  groupbyattrs:
    keys:
      - pod_name
      - sidecar_name
  # "Rename" the moved attributes to be the right thing on the resource
  resource:
    attributes:
      - key: k8s.pod.name
        from_attribute: pod_name
        action: upsert
      - key: service.name
        from_attribute: sidecar_name
        action: upsert
      - key: pod_name
        action: delete
      - key: sidecar_name
        action: delete
service:
  pipelines:
    traces:
      # They'd need to run in that order
      processors: [ groupbyattrs, resource ]
```

Does that sound right?
