### ISSUE TITLE
New component: SQL Receiver

### ISSUE THREAD

**Issue by pmcollins** [open-telemetry/opentelemetry-collector-contrib#9408]
## The purpose and use-cases of the new component

The SQL Receiver will use custom SQL queries to generate metrics from a database connection. Its configuration and general functionality are derived from the SignalFx SmartAgent's [SQL Monitor](https://github.com/signalfx/signalfx-agent/tree/main/pkg/monitors/sql).

## Example configuration for the component

```yaml
receivers:
  sql:
    driver: postgres
    datasource: "host=localhost port=5432 user=postgres password=s3cr3t sslmode=disable"
    queries:
      - sql: "select count(*) as count, 42 as val from movie"
        metrics:
          - metric_name: movie.count
            value_column: "count"
          - metric_name: movie.val
            value_column: "val"
      - sql: "select count(*) as count, genre from movie group by genre"
        metrics:
          - metric_name: movie.genres
            value_column: "count"
            attribute_columns: [ "genre" ]
```

## Telemetry data types supported

Metrics.

## Sponsor (Optional)

@dmitryax
