### ISSUE TITLE
Datadog exporter missing support for logs datatype

### ISSUE THREAD

**Issue by MaticDiba** [open-telemetry/opentelemetry-collector-contrib#9409]
**Is your feature request related to a problem? Please describe.**
When trying to use datadog exporter for logs I got this error:
```
Error: cannot build exporters: pipeline "logs" of data type "logs" has an exporter datadog, which does not support that data type
```

**Describe the solution you'd like**
Is it possible for Datadog exporter to also include logs with respective `trace_id` to be received and sent with the exporter?

Is there another approach to consuming logs, traces, and metrics in datadog with the use of OpenTelemetry?

**Additional context**
Used collector config:
```
receivers:
  hostmetrics:
    scrapers:
      load:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      paging:
      process:    
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s
    
exporters:
  logging:
    logLevel: info
  datadog: 
    hostname: telemetrylabs
    env: "core-local"
    service: "--"
    version: "1"
    api:
      key: --
      site: datadoghq.eu

service:
  telemetry:
    logs:
      level: "DEBUG"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, logging]
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]
```
