### ISSUE TITLE
[exporter/prometheusremotewrite] [receiver/docker_stats]  error: Permanent error: invalid temporality and type combination

### ISSUE THREAD

**Issue by resdenia** [open-telemetry/opentelemetry-collector-contrib#9424]
I've been set up collector for metrics using exporter:prometheusremotewrite and  receiver:docker_stats,
I receiving metrics, but when metrics is sends i expiriencing that error:
`error   exporterhelper/queued_retry.go:183      Exporting failed. The error is not retryable. Dropping data.  {"kind": "exporter", "name": "prometheusremotewrite", "error": "Permanent error: invalid temporality and type combination", "dropped_items": 53}`

**Opentelemetry version is 0.48.0**

My config file is:
```
exporters:
  prometheusremotewrite:
    resource_to_telemetry_conversion:
      enabled: true
    endpoint: https://url.com/
    headers:
      Authorization: Bearer some-token

receivers:
  docker_stats:
    api_version: 1.24
    collection_interval: 2s
    endpoint: unix:///var/run/docker.sock
    provide_per_core_cpu_metrics: true
    timeout: 20s

service:
  pipelines:
    metrics:
      receivers:
      - docker_stats
      exporters:
      - prometheusremotewrite
  telemetry:
    logs:
      level: debug
```
