### ISSUE TITLE
SpanMetrics continuously increase. 

### ISSUE THREAD

**Issue by Konig-Corey** [open-telemetry/opentelemetry-collector-contrib#9551]
**Issue**
When using the spanmetric processor the output metrics are supposed to be metrics of the spans seen by the collection agent. When using the prometheus as storage for these metrics I have noticed the metrics are appear to continue to grow when the rate of spans is not. 

**Reproducing  / Config**

Key Notes on Setup: 
- Running collection agent per instance, multiple instance behind a single load balance. 
- The issues appears when service has high load.

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680 # default port

processors:
  memory_limiter:
    limit_mib: 500
    check_interval: 5s

  spanmetrics:
    metrics_exporter: awsprometheusremotewrite
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    aggregation_temporality: AGGREGATION_TEMPORALITY_CUMULATIVE

  batch:    
  
  resource: 
    attributes:
                   
  filter:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - .*_datadog_.*   # ignore metrics about datadog

exporters:
  logging/metrics:
    loglevel: info 
  logging/traces:
    loglevel: info     
  
  awsxray:
    # indexed_attributes: [list]
    index_all_attributes: true

  awsprometheusremotewrite:
    endpoint: ${AMP_URL} # value consumed from consul
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 10s
      max_elapsed_time: 30s
    timeout: 15s
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: 
        - otlp      
      processors:
        - memory_limiter
        - spanmetrics   
        - batch
      exporters: 
        - logging/traces
        - awsxray
    
    metrics: 
      receivers: 
        - otlp
      processors: 
        - memory_limiter 
        - filter
        - batch
      exporters: 
        - logging/metrics
        - awsprometheusremotewrite       

```

**Expected processor result**
The resulting rate query in prometheus should follow the trend of the applications request counts. We can expect spikes during peak traffic but in general the pattern would NOT continue to grow. Example expected pattern
<img width="1681" alt="image" src="https://user-images.githubusercontent.com/25379059/165395992-cf259546-42dd-4196-919b-517c817e86db.png">
The depicted trend is of a single instance running a service behind a alb with very little traffic. 

**What was actually seen**
I am unsure of the exact cause, however, when we introduce more instances behind the ALB and much heavier node the count of the metrics appears to never correctly reset and continues to grow. The query used for the above graph is identical to the one shown here with the exception of a different env under heavier load. 
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/25379059/165396386-ce9d6e0b-8f3d-4f62-809c-7b3b031cd900.png">
As you can see in the picture above, when viewing a "rate" the metrics appear to be continuously grow even though that is not the true trend of the requests. 

**What version did you see this?**
This has been an ongoing issues for us from version 37 - present. 

**Environment**
OS: Amazon Linux

**Additional context**
An educated guess of the issue is that metrics are being silently dropped on export to prometheus because there is a unique metric with an older timestamp and prometheus refuses. (This can happen if a 'metric' attempts to be submitted but there is already a newer one prometheus). Possibly leading to the metrics getting skewed? 

This processor is imperative for our teams to replicate a similar functionality once provided by datadog (trace metrics).
