### ISSUE TITLE
New component: receiver/nsxtreceiver

### ISSUE THREAD

**Issue by schmikei** [open-telemetry/opentelemetry-collector-contrib#9568]
I'd like to author a component that receives metrics and logs for [NSX-T](https://docs.vmware.com/en/VMware-NSX-T-Data-Center/index.html). 

## The purpose and use-cases of the new component
The receiver should be able to receive metrics important to run virtual networking using NSX-T. The receiver is planned to ingest metrics via the [NSX Rest API](https://docs.vmware.com/en/VMware-NSX-Data-Center-for-vSphere/6.4/nsx_64_api.pdf). As for logs, it should ingest them via wrapping the [syslogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/syslogreceiver) and providing this [official documentation](https://docs.vmware.com/en/VMware-NSX-Data-Center-for-vSphere/6.4/com.vmware.nsx.logging.doc/GUID-EA70974C-07F8-469D-8A9D-0ED54F0C8F34.html) on how to set up a syslog forwarder for NSX.

## Example configuration for the component

I think the config struct would look something like this
```go
// Config is the configuraiton for the NSX receiver
type Config struct {
	config.ReceiverSettings `mapstructure:",squash"`
	MetricsConfig           MetricsConfig `mapstructure:"metrics"`
	LoggingConfig           LoggingConfig `mapstructure:"logs"`
}

// MetricsConfig is the metrics configuration portion of the nsxreceiver
type MetricsConfig struct {
	scraperhelper.ScraperControllerSettings `mapstructure:",squash"`
	confighttp.HTTPClientSettings           `mapstructure:",squash"`
	Settings                                metadata.MetricsSettings `mapstructure:"settings"`
	Username                                string                   `mapstructure:"username"`
	Password                                string                   `mapstructure:"password"`
}

// LoggingConfig is the configuration of a syslog receiver
type LoggingConfig struct {
	*syslogreceiver.SysLogConfig `mapstructure:",squash"`
}

```

```yaml
receivers:
  nsx:
    metrics:
      endpoint: https://nsx-34795.cf5e88ac.australia-southeast1.gve.goog
      username: admin
      password: password
      settings: ...
      tls: ...
      timeout: 60s
    logs:
      listen_address: 0.0.0.0:5120

exporters:
  file:
    path: "./content.json"

service:
  pipelines:
    metrics:
      receivers: [nsx]
      exporters: [file]
    logs:
      receivers: [nsx]
      exporters: [file]

```

Focused metrics I would like to grab from the API
```json
[
  "nsx.interface.packet.count",
  "nsx.interface.throughput",
  "nsx.node.cache.memory.usage",
  "nsx.node.load_balancer.utilization",
  "nsx.node.memory.usage",
  "nsx.node.cpu.utilization",
  "nsx.node.disk.usage",
  "nsx.node.disk.utilization"
]
```

## Telemetry data types supported

metrics && logs 

## Sponsor (Optional)

Need a sponsor! Would love to work with the community to help achieve this!
