### ISSUE TITLE
metricstransformprocessor: Snap timestamps to the previous second/minute

### ISSUE THREAD

**Issue by csmehta** [open-telemetry/opentelemetry-collector-contrib#9588]
**Is your feature request related to a problem? Please describe.**
I am trying to group by metrics coming from different workers to the collector.
```
    - include: app.counter.job.input-row
          action: update
          operations:
            - action: aggregate_labels
              aggregation_type: sum
              label_set: []
```
But for this to be effective timestamps have to match as well.

**Describe the solution you'd like**
Ability to snap timestamp to nearest second/minute based on config.
```
    - include: app.counter.job.input-row
          action: update
          operations:
            - action: update_timestamp
              round_to_nearest: 1m
            - action: aggregate_labels
              aggregation_type: sum
              label_set: []
```

**Describe alternatives you've considered**
None

**Additional context**
This will help reduce the outgoing metric volume, considering we don't require sub-second visibility into the metric.
