### ISSUE TITLE
New component: receiver/expvarreceiver

### ISSUE THREAD

**Issue by jamesmoessis** [open-telemetry/opentelemetry-collector-contrib#9592]
## The purpose and use-cases of the new component

An Expvar Receiver scrapes metrics from [expvar](https://pkg.go.dev/expvar), which exposes data in JSON format from an HTTP endpoint. The metrics are extracted from the `expvar` variable [memstats](https://pkg.go.dev/runtime#MemStats), which exposes various information about the Go runtime.

## Example configuration for the component

In the past we've used the `signalfx-agent`'s [expvar monitor](https://github.com/signalfx/signalfx-agent/blob/main/docs/monitors/expvar.md), and I feel like this receiver could expose similar configurations. 

We can also take inspiration from the [hostmetricsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/internal/scraper/cpuscraper/documentation.md) which provides a set of default metrics, while allowing metrics to be included/excluded.

An example config could look like: 

```yaml
expvar:
  collection_interval: 30s
  host: 0.0.0.0
  port: 10000
  https: false
  path: /debug/vars 
  metrics: 
    <metric_name>:
      enabled: <true|false>
```

## Telemetry data types supported

Metrics only. 

## Sponsor (Optional)

Looking for a sponsor 😃 

Open to any suggestions and advice!
