### ISSUE TITLE
New Component: `ethtool receiver` 

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector-contrib#9593]
# The purpose and use-cases of the new component
when monitor network bound compute nodes, it becomes important to understand per network interface statistics to check for saturation.

# Example configuration for the component
Looking to make transitioning from the [telegraf agent]( https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ethtool/README.md) to Open Telemetry collector simple to understand.

I would like it to be something similar:

```yaml
ethtool:
   collection_interval: 10s
   interfaces:
     include:
     - pattern1
     - pattern2
    exclude:
    - lo0
```
In the event that a conflict was to happen, the exclude definition will override any include patterns.

The default configuration will monitor all interfaces excluding the loopback interface.  

# Telemetry data types supported

Metrics Only

# Sponsor (Optional)
Looking for a sponsor 🙏🏽 

Open to any suggestions.
