### ISSUE TITLE
New component: Mezmo Log Exporter

### ISSUE THREAD

**Issue by billmeyer** [open-telemetry/opentelemetry-collector-contrib#9599]
## The purpose and use-cases of the new component

Mezmo exporter enables the ability to export log telemetry from an OpenTelemetry collector to the LogDNA platform (https://logdna.com) for further analysis, alerting and retention.

Supported pipeline types: logs

## Example configuration for the component

Two configuration entries are required:

- `ingest_url` (Required): The endpoint which to export logs to LogDNA.
- `ingest_token` (Required): The token from LogDNA which will be used for ingestion.

Example:

```
receivers:
  nop:

processors:
  nop:

exporters:
  mezmo:
    ingest_url: "https://logdna.com/log/ingest"
    ingest_key: "00000000000000000000000000000000"

service:
  pipelines:
    logs:
      receivers: [ nop ]
      processors: [ nop ]
      exporters: [ mezmo ]
```

## Telemetry data types supported

Logs

## Sponsor (Optional)

This component is being developed and contributed by LogDNA (Mezmo) and is looking for a volunteer sponsor.

A version of the OpenTelemetry contrib collector containing the code for this exporter is available here: https://github.com/billmeyer/opentelemetry-collector-contrib/tree/mezmo-exporter

Given that it's a log exporter, it's minimally invasive to the entire repository.  It has been built and tested with unit tests and volume tests passing without errors.
