### ISSUE TITLE
[receiver/sqlserver] Should some metrics be int instead of double?

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#9601]
**Describe the bug**
The question came up on whether some of the metrics in this receiver should be an int rather than a double. They were initially created as doubles as that's how the Windows performance counter monitor tool presented them. Some may actually be ok if changed to an integer though.

**Steps to reproduce**
Run collection with sqlserver receiver configured.

**What did you expect to see?**
Some of the metrics should possibly have an int type.

**What did you see instead?**
All metrics have a double type.

**What version did you use?**
Version: `1c4dd67f7af084c467ce5378115fa151f7276547`

**What config did you use?**
```
receivers:
    sqlserver:
      collection_interval: 10s
exporters:
    logging:
      loglevel: debug
service:
    pipelines:
        metrics:
            receivers: [sqlserver]
            # processors: [nop]
            exporters: [logging]
```

**Environment**
OS: Windows Server 2019
