### ISSUE TITLE
New component: Big-IP Receiver

### ISSUE THREAD

**Issue by StefanKurek** [open-telemetry/opentelemetry-collector-contrib#9680]
## The purpose and use-cases of the new component
The F5 Big-IP Metric Receiver would pull KPI statistics from F5's iControl REST API (https://clouddocs.f5.com/api/icontrol-rest/). It will focus on the LTM Module for Big-IP and collect throughput, connection, session, and availability metrics for LTM Virtual Servers, Pools, Pool Members, and Nodes.

Targeting version 11.6.5+ (https://support.f5.com/csp/article/K2200#1).

## Example configuration for the component
`collection_interval`: interval to collect metrics (default `10s`)
`username`: required for F5 iControl REST API token
`password`: required for F5 iControl REST API token
`endpoint`: endpoint for F5 iControl REST API (default `https://localhost:443`)
TLS settings based on OTEL HTTPClientSettings

```
receivers:
    bigip:
      collection_interval: 10s
      username: "bigipuser"
      password: "bigippassword"
      endpoint: https://localhost:443
      tls:
        insecure_skip_verify: true
```

## Telemetry data types supported
Metrics

## Testing
The integration test will not spin up a docker container like many of the other receiver integration tests. This is because the F5 Big-IP license makes it prohibitive to set this sort of environment up. So instead, the integration test spins up a mock http server which will playback recorded responses from an actual Big-IP environment. 

I have also included a script which will record and save the needed responses for the mock server, so that a future developer will easily be able to modify this integration test while working with their own environment.
