### ISSUE TITLE
[processor/metricstransform] support of regex group in new_value of label operations (e.g. add_label)

### ISSUE THREAD

**Issue by howardyoo** [open-telemetry/opentelemetry-collector-contrib#9746]
**Problem**
I have a requirement that I need to convert a part of my metrics name to be added as a label. For example, let's say I have a metric that has a name of xyz.abc.efg. The part xyz is a prefix of the metric name, and thus I would like to convert that part into a new label called 'prefix'. Currently the rule does not proper convert the $${1} into the value, but I see `_1` as the value when the transform happens.

**Describe the solution you'd like**
In the otel config, I'd like to define a metricstransform rule that looks something like this:
```
    processors:
      metricstransform:
        transforms:
          - include: ^(\w*)\.(.*)$$
            match_type: regexp
            action: update
            new_name: $${2}
            operations:
              - action: add_label
                new_label: prefix
                new_value: $${1}
```
This will convert the metrics having the name `xyz.abc.def` into metric that has the name `abc.def` and label `prefix=xyz`

**Describe alternatives you've considered**
There is no alternatives to convert the metric names in this way, other than that you have to do it outside of otel collector.

**Additional context**
N/A
