### ISSUE TITLE
An exception occurs (tracing: skywalking-receiver to zipkin-exporter )

### ISSUE THREAD

**Issue by forest003** [open-telemetry/opentelemetry-collector-contrib#9786]
**Describe the bug**
I want to convert skywalking format of tracing to zipkin format, but something is wrong. 

**What did you expect to see?**
I want to convert skywalking format of tracing to zipkin format.

**What did you see instead?**
2022-05-07T10:17:51.697+0800        error        exporterhelper/queued_retry.go:183        Exporting failed. The error is not retryable. Dropping data.        {"kind": "exporter", "name": "zipkin", "error": "Permanent error: failed to push trace data via Zipkin exporter: SpanID is invalid", "dropped_items": 1}

**What version did you use?**
Version: 0.50.0

**What config did you use?**
Config:
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

  skywalking:
    protocols:
      grpc:
        endpoint: 0.0.0.0:11800
      http:
        endpoint: 0.0.0.0:12800

processors:
  batch:

exporters:
  logging:
    logLevel: debug

  zipkin:
    endpoint: "http://host:9411/api/v2/spans"
    compression: gzip
    tls:
      insecure: true

  otlp:
    endpoint: host:4317
    tls:
      insecure: true

service:

  pipelines:

    traces:
      receivers: [skywalking]
      processors: [batch]
      exporters: [logging, zipkin ]

**Environment**
OS: Linux version 3.10.0-862.14.4.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Wed Sep 26 15:12:11 UTC 2018

**Comment by JaredTan95** [comment]
thx, I will check it soon or later.

**Comment by forest003** [comment]
> Did you reproduce the problem？



> thx, I will check it soon or later.

**Comment by JaredTan95** [comment]
@forest003 This is caused by skywalking traceid convert to otlp trace id bug. with https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/11562 fixed. You can try it again.

As latest result as follows:

- otelcol-configs: 
```yaml
receivers:
  skywalking:
    protocols:
      grpc:
        endpoint: 0.0.0.0:11800
      http:
        endpoint: 0.0.0.0:12800
  skywalking/customname:
    protocols:
      http:
        endpoint: 0.0.0.0:12801

exporters:
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true
  zipkin:
    endpoint: "http://localhost:9411/api/v2/spans"

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [skywalking]
      processors: [batch]
      exporters: [jaeger,zipkin]

```

- jaeger ui shows:
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/12468337/176981206-03c4f235-5d72-4dcb-bd4a-699e6ad33aa6.png">

- zipkin ui shows and no exceptions in otelcol:
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/12468337/176981213-eee9205c-8191-40a0-b55e-601591851f73.png">
