### ISSUE TITLE
[new component] Add apache pulsar exporter support

### ISSUE THREAD

**Issue by tjiuming** [open-telemetry/opentelemetry-collector-contrib#9795]
## The purpose and use-cases of the new component
Pulsar exporter exports logs, metrics, and traces to Pulsar. This exporter uses a synchronous producer
that blocks and able to batch messages(configurable).

Supported pipeline types: logs, metrics, traces

## Example configuration for the component
```yaml
exporters:
  pulsar:
    service_url: pulsar://localhost:6650
    topic: otlp-spans
    encoding: otlp_proto
    auth_name: tls
    auth_param: '{"tlsCertFile":"cert.pem","tlsKeyFile":"key.pem"}'
    insecure: false
    tls_trust_certs_file_path: ca.pem
    enable_batch: true
```

## Telemetry data types supported

traces, metrics and logs
