### ISSUE TITLE
[new component] add apache pulsar receiver support

### ISSUE THREAD

**Issue by tjiuming** [open-telemetry/opentelemetry-collector-contrib#9796]
## The purpose and use-cases of the new component
Pulsar receiver receives logs, metrics, and traces from Pulsar.

Supported pipeline types: logs, metrics, traces

## Example configuration for the component
```yaml
receivers:
  pulsar:
    service_url: pulsar://localhost:6650
    topic: otlp-spans
    subscription: otlp_spans_sub
    consumer_name: otlp_spans_sub_1
    encoding: otlp_proto
    auth_name: tls
    auth_param: '{"tlsCertFile":"cert.pem","tlsKeyFile":"key.pem"}'
    insecure: false
    tls_trust_certs_file_path: ca.pem
```

## Telemetry data types supported

Supported pipeline types: logs, metrics, traces
