### ISSUE TITLE
New component: receiver/promtailreceiver

### ISSUE THREAD

**Issue by fbuetler** [open-telemetry/opentelemetry-collector-contrib#9800]
## The purpose and use-cases of the new component

The Promtail receiver implements the [Loki push api](https://grafana.com/docs/loki/latest/clients/promtail/#loki-push-api) as specified [here](https://grafana.com/docs/loki/latest/api/#get-lokiapiv1tail). It allows Promtail instances to specify the open telemetry collector as their `lokiAddress`.

The implementation may be done analogously to [fluentforwardreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/fluentforwardreceiver)

## Example configuration for the component

The configuration of the receiver may be adapted from the [loki_push_api configuration](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#loki_push_api)

Example

```yaml
receivers:
  promtail:
    endpoint: 0.0.0.0:8006
    # Label map to add to every log line sent to the push API
    labels:
      [ <labelname>: <labelvalue> ... ]    
```

## Telemetry data types supported

Logs only.

**Comment by djaglowski** [comment]
I'll sponsor this.

**Comment by mar4uk** [comment]
Hi! I also has started working on promtailreceiver component. I was thinking to implement this component using opentelemetry-log-collection repo. The config would look like:

```
receivers:
  promtail:
    config:
      positions:
        filename: /tmp/positions.yaml
        sync_period: 10s
      scrape_configs:
        - job_name: system
          static_configs:
            - labels:
                job: varlogs
                __path__: /var/log/*.log
      target_config:
        sync_period: 10s
```

And the new input operator would be added to opentelemetry-log-collection repo. Here what I have done so far https://github.com/mar4uk/opentelemetry-log-collection/pull/1 (draft). And in openelemetry-contrib repo it would look like filelogreceiver (I also have a draft)

**Comment by mar4uk** [comment]
I think it should be the same receiver, we can just add loki_push_api section to config:
```
receivers:
  promtail:
    config:
      scrape_configs:
        loki_push_api:
          server:
            http_listen_port: 3500
            grpc_listen_port: 3600
          labels:
            pushserver: push1 
```
took this example from [Example Push Config](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#example-push-config)

**Comment by djaglowski** [comment]
@mar4uk, I'm still learning promtail, but I see now that your proposal is a generalized integration of promtail, whereas the push use case is just a specific case. Is that right? One receiver makes sense to me then. 

A couple other questions:

Am I understanding correctly that promtail can be run in process and does not require an additional executable?

What do you think about removing the `config` level in the receiver config? It seems redundant to me:
```yaml
receivers:
  promtail:
    scrape_configs:
      ...
```


What are your thoughts on all of this @fbuetler?

**Comment by Mario-Hofstaetter** [comment]
Would `lokireceiver` be a better name instead of `promtailreceiver` ? The push api is a loki specification, `promtail` is just one client out of many.
Afterall there is already a [lokiexporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/lokiexporter), not a promtailexporter.

Features of promtail other than pushapi (tailing files, windows eventlog, ...) are handled by (or will be handled by?) [filelogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver) and other receivers.

Also, the link in OP points to [GET /loki/api/v1/tail](https://grafana.com/docs/loki/latest/api/#get-lokiapiv1tail), it should be [POST /loki/api/v1/push](https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push) imho?

**Comment by mar4uk** [comment]
> What do you think about removing the config level in the receiver config? It seems redundant to me:

My idea was to keep under config level exact promtail config format, so user can paste promtail config as it is under config level. On the same level as config could be added additional settings, like postions_directory or something elsse
>  Am I understanding correctly that promtail can be run in process and does not require an additional executable?

Yes, that's correct

> Features of promtail other than pushapi (tailing files, windows eventlog, ...) are handled by (or will be handled by?) [filelogreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver) and other receivers.

Agree with this point. Actually promtail has features that are already implemented by filelog, journard, syslog.. Maybe adding promtail as a separate receiver is not the best way to go?

I'm not sure if the implementation of loki push api in the receiver is necessary as well. Why don't just use otlp receiver and loki exporter to push logs to loki instead of adding new promtail receiver?

**Comment by Mario-Hofstaetter** [comment]
> I'm not sure if the implementation of loki push api in the receiver is necessary as well. Why don't just use otlp receiver and loki exporter to push logs to loki instead of adding new promtail receiver?

Currently we are using promtail `loki_push_api` as target for our .NET apps using [serilog-sinks-grafana-loki](https://github.com/serilog-contrib/serilog-sinks-grafana-loki), which is working very nice.  (Loki devs said it is discouraged to directly push to loki because promtail does buffering & retry)

OpenTelemetry Logs are not yet stable (?), but I am not entirely sure about the state of Logging Export in OLTP in [otel-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet). I have not found a Serilog OLTP Sink yet, if that even makes sense.

> *While the OpenTelemetryLoggerProvider (i.e integration with ILogger) is stable, the OTLP Exporter for Logs is still non-stable.

So an OpenTelemetry Collector `lokireceiver` would could be another piece to further help use transition to only using otelcol for everything.

**Comment by mar4uk** [comment]
@Mario-Hofstaetter  
> Currently we are using promtail loki_push_api as target for our .NET apps using [serilog-sinks-grafana-loki](https://github.com/serilog-contrib/serilog-sinks-grafana-loki),

I was thinking that you can use collector as a target instead of promtail loki_push_api. 
For example, let's imagine you have OpenTelemetry Collector only, and don't have promtail.
Collector has otlp receiver it can receive requests (http or grpc) on configured port. So instead of sending logs to loki_push_api target you can send logs to collector via otlp.

(There is also thread in CNCF otel-collector channel about promtail receiver https://cloud-native.slack.com/archives/C01N6P7KR6W/p1649822054450679 about possible promtail receiver usage). 

> So an OpenTelemetry Collector lokireceiver would could be another piece to further help use transition to only using otelcol for everything.

Did I understand the use case correct? You would like to have lokireceiver with config like
```
receivers:
  lokireceiver:
    endpoint: 0.0.0.0:8006
    labels:  [ <labelname>: <labelvalue> ... ]
```
from your app you would send logs to that endpoint (which one would you use [POST /loki/api/v1/push](https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push) or [POST /promtail/api/v1/raw](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#loki_push_api)?)
Collector will have loki receiver and loki exporter enabled in pipeline. Is this correct?

My suggestion is to use otlp receiver instead of lokireceiver for that case:
```
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:8006"
```
from your app you would send logs to that endpoint. Collector will have otlp receiver and loki exporter enabled in pipeline.
The difference with previous example is the format of the body of the POST request.

The reason to use lokireceiver (promtailreceiver) instead of otlp receiver is to avoid changing the part of application responsible for sending logs. So you will be able to switch from promtail to otelcollector right away. Is this what you are looking for from lokireceiver (promtailreceiver)?
