### ISSUE TITLE
prometheusremotewrite exporter doesn't work well with groupbyattrs processor?

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector-contrib#9981]
**Describe the bug**
When enable `groupbyattrs` processor in metrics pipeine and use `prometheusremotewrite` exporter, it fails during prometheus translator at [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheusremotewrite/metrics_to_prw.go#L64-L65) probably because flag like`pmetric.MetricAggregationTemporalityCumulative` was removed by `groupbyattrs` processor.

**Steps to reproduce**
Please use the given config to reproduce this error `Permanent error: invalid temporality and type combination`

**What did you expect to see?**
things to work while having these 2 components in a pipeline

**What did you see instead?**
```
2022-05-12T22:46:09.098+0800    error   exporterhelper/queued_retry.go:183      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "name": "prometheusremotewrite", "error": "Permanent error: invalid temporality and type combination; invalid temporality and type combination; invalid temporality and type combination; invalid temporality and type combination; Permanent error: Permanent error: remote write returned HTTP status 404 Not Found; err = <nil>: 404 page not found\n", "errorCauses": [{"error": "Permanent error: invalid temporality and type combination; invalid temporality and type combination; invalid temporality and type combination; invalid temporality and type combination"}, {"error": "Permanent error: Permanent error: remote write returned HTTP status 404 Not Found; err = <nil>: 404 page not found\n"}], "dropped_items": 15}
```

**What version did you use?**
Version: v0.50.0

**What config did you use?**
Config: (e.g. the yaml config file)
```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: kubernetes-cadvisor-metrics
          static_configs:
            - targets:
                - localhost:8888
              labels:
                k: v

exporters:
  prometheusremotewrite:
    endpoint: http://localhost:8888


processors:
  groupbyattrs:
    keys:
      - k

service:
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      address: 127.0.0.1:8888
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [groupbyattrs]
      exporters: [ prometheusremotewrite]
```

**Environment**
OS: MacOS 12.3.1
Compiler(if manually compiled): go 1.17.8

**Additional context**
