### ISSUE TITLE
Error: unknown processors type "transform" for "transform"

### ISSUE THREAD

**Issue by gurpartb** [open-telemetry/opentelemetry-collector-contrib#9989]
**Describe the bug**
Otel Collector doesn't recognize Processor Transform
`Error: failed to get config: cannot unmarshal the configuration: unknown processors type "transform" for "transform" (valid values: [filter groupbyattrs groupbytrace spanmetrics experimental_metricsgeneration metricstransform resource tail_sampling resourcedetection batch memory_limiter attributes cumulativetodelta deltatorate probabilistic_sampler k8sattributes routing span])`

**Steps to reproduce**
Run `otelcol-contrib.exe` `v0.51.0` using `agent-config.yaml` provide below

**What did you expect to see?**
I expected log output in file to contain attribute `"com.splunk.sourcetype": "JSON"`

**What did you see instead?**
Otel Collector crashed with error: `collector server run finished with error: failed to get config: cannot unmarshal the configuration: unknown processors type "transform"`

**What version did you use?**
Version: `v0.51.0`

**What config did you use?**
```
receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006

processors:
  transform:
      queries:
        - set(com.splunk.sourcetype, "JSON") where attributes["appSourceType"] == "json"

exporters:
  file:
    path: "C:/temp/otel-file.json"

service:
  pipelines:
    logs:
      receivers:
      - fluentforward
      processors:
      - transform
      exporters:
      - file
```

**Environment**
Windows 10 Enterprise

**Additional context**
NA
